// Level 1 Unit 2 — Classroom & USP Campus Life (Portuguese, BP primary)
// Functions: naming classroom objects, locating items, asking who/what,
// classroom commands, simple yes/no exchanges, polite requests.

const createContentItem = (target, pronunciation, note, type = 'word', example = '', exampleNote = '', breakdown = null, activityIds = []) => ({
  type, activityIds,
  targetText: target, romanization: pronunciation, nativeText: note, pronunciation,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'pt-l1u2-orientation',
  pronunciation: 'pt-l1u2-pronunciation',
  vocabClassroom: 'pt-l1u2-vocab-classroom',
  vocabPeople: 'pt-l1u2-vocab-people',
  grammarGenderArticles: 'pt-l1u2-grammar-gender-articles',
  grammarThisThat: 'pt-l1u2-grammar-this-that',
  grammarQuestions: 'pt-l1u2-grammar-questions',
  reading: 'pt-l1u2-reading',
  listening: 'pt-l1u2-listening',
  writing: 'pt-l1u2-writing',
  culture: 'pt-l1u2-culture',
  task: 'pt-l1u2-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do', goals: ['Name the 15 most common classroom and campus objects at USP with correct article (o/a) and gender.', 'Ask "What is this?" and "Whose is this?" and answer in complete short sentences.', 'Follow basic classroom commands (Abram o livro! Repitam! Escutem!) and produce one polite request of your own.'], task: 'Picture yourself in your first classroom at USP — you sit down and need to ask what something on the table is, point to a board, and respond to the professor\'s commands.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Sound traps in this lesson', goals: ['Pronounce "lápis" (pencil) /ˈla.pis/ with stress on the FIRST syllable — proparoxítona would need an accent, so default penultimate is the right read.', 'Distinguish "livro" (book, m, ends in -o) from "lousa" (board, f, ends in -a) — gender follows the ending in most cases.', 'Handle the BP palatalization in "professor de história", "ditado", and "dia" — every /d/ before /i/ becomes /dʒ/.'], task: 'Read each example aloud, mark the stressed syllable, and identify the gender from the ending.' },
  { id: ACT.vocabClassroom, section: 'Vocabulary I', title: 'Classroom objects and surfaces', goals: ['Memorize 15 classroom nouns with the correct article (o livro, a caneta, os livros, as canetas).', 'Recognize the standard masculine -o / feminine -a default, AND the exceptions: o mapa (m, ends in -a), a flor (f, ends in -r), o dia (m, ends in -a).'], task: 'Point to five objects around you and name each with the correct definite article.' },
  { id: ACT.vocabPeople, section: 'Vocabulary II', title: 'People in the classroom', goals: ['Use 10 people-in-class nouns with gender pairs: o professor / a professora, o aluno / a aluna, o colega / a colega (same form, different article).', 'Apply the rule that "colega" and "estudante" are EPICENO (same form for both genders, only the article changes).'], task: 'Describe your study group with the right article + noun for each member.' },
  { id: ACT.grammarGenderArticles, section: 'Grammar I', title: 'Gender + definite/indefinite articles', goals: ['Use the four definite articles: o (m sg), a (f sg), os (m pl), as (f pl).', 'Use the four indefinite articles: um (m sg), uma (f sg), uns (m pl), umas (f pl).', 'Recognize that EVERY Portuguese noun has a fixed grammatical gender, and you must learn it WITH the article: not "livro" but "o livro".'], task: 'Convert five definite-article sentences into indefinite-article versions and back.' },
  { id: ACT.grammarThisThat, section: 'Grammar II', title: 'Demonstratives: este/esse/aquele', goals: ['Use the three-way Portuguese demonstrative system: este/esta (near speaker), esse/essa (near listener), aquele/aquela (far from both).', 'Apply correct gender and number agreement: este livro / esta caneta / estes livros / estas canetas.', 'Use the neuter "isto / isso / aquilo" when the gender/identity of the thing is unknown ("What is this?" = "O que é isto?").'], task: 'Point at three objects at different distances and describe each with the right demonstrative.' },
  { id: ACT.grammarQuestions, section: 'Grammar III', title: 'Wh-questions: o que, quem, onde, de quem', goals: ['Use o que (what), quem (who), onde (where), de quem (whose) to form information questions.', 'Apply the "de + quem" pattern for possession questions: "De quem é este livro?" ("Whose book is this?").'], task: 'Ask five different wh-questions about objects in the room.' },
  { id: ACT.reading, section: 'Reading', title: 'A morning at USP', goals: ['Read a short paragraph describing a USP classroom with full noun + article + gender agreement.', 'Answer five comprehension questions about object location, ownership, and identity.'], task: 'Read the paragraph aloud and answer the five comprehension questions.' },
  { id: ACT.listening, section: 'Listening', title: 'Asking the professor', goals: ['Follow a 6-turn dialogue between a student and a professor about classroom items and ownership.', 'Reproduce the dialogue with your own questions.'], task: 'Listen along, then perform the dialogue with one different object swapped in.' },
  { id: ACT.writing, section: 'Writing', title: 'Describe your study space', goals: ['Write 4-6 sentences describing your study space with correct gender, number, and article agreement.', 'Use at least one demonstrative and one possessive in your description.'], task: 'Write your own classroom/desk description using the model.' },
  { id: ACT.culture, section: 'Culture', title: 'USP, the vestibular, and the colega culture', goals: ['Know that USP entry is via the FUVEST vestibular — one of the most selective university entrance exams in Brazil.', 'Understand the "colega" relationship: more than acquaintance, less than amigo; the default term for classmates and coworkers in BP.'], task: 'Explain to a Brazilian friend what your own university\'s admission process is, using the USP vocabulary as reference.' },
  { id: ACT.task, section: 'Task', title: 'Survive your first class', goals: ['Run a 6-turn classroom interaction: ask what something is, ask whose, follow a command, ask a question of the professor.'], task: 'Roleplay your first class at USP with the AI tutor playing a paulistano professor.' },
];

const content = [
  createContentItem('Aula na USP', 'AU-la na U-S-P', 'Picture a Monday morning at the Cidade Universitária campus of USP. You walk into your first class — a small room with about 30 colegas, a quadro at the front, and books, pens, and laptops on each table. By the end of this lesson you can name everything you see and ask about anything you do not recognize.', 'word', 'Cenário: sala 207, prédio de Engenharia, USP Cidade Universitária.', 'Concrete location grounds every example in this lesson. The USP Engineering building is the Politécnica (Poli).', null, [ACT.orientation]),
  createContentItem('Funções da aula', 'fun-SÕIS da AU-la', 'Five micro-skills: nomear (name), identificar (identify), perguntar (ask), seguir comandos (follow commands), pedir (request). Once automatic, every future lesson layers on top.', 'word', 'nomear · identificar · perguntar · seguir · pedir', 'These five verbs map directly to the activities below.', null, [ACT.orientation]),
  createContentItem('Gênero a partir do final', 'gender from the ending', 'Default rule: nouns ending in -o are MASCULINE (o livro), nouns ending in -a are FEMININE (a caneta). Exceptions exist (o mapa, o dia, a mão) but the default covers ~85 percent of nouns.', 'word', 'o livro (m), a caneta (f) — exceções: o mapa, o dia, a mão', 'Always learn a noun WITH its article — "livro" alone is incomplete information.', null, [ACT.orientation]),

  createContentItem('lápis', 'lápis /ˈla.pis/', 'Pronounce as proparoxítona-looking but actually paroxítona — stress on first syllable (LÁ-pis). Same form singular and plural ("um lápis, dois lápis"). The acute on á marks the open vowel and stress.', 'word', 'O lápis está sobre a mesa.', 'Invariant for number — you cannot say "lápises". Use a counter: "dois lápis", "muitos lápis".', null, [ACT.pronunciation]),
  createContentItem('professor de história', 'professor dʒi is-TÓ-ria', 'Three potential palatalizations in this phrase: "de" → /dʒi/ (BP) when reduced, "história" has open ó. Read as "pro-fes-SÔR dji is-TÓ-ria" in fast BP speech.', 'word', 'O professor de história ensina muito bem.', 'Common student phrase; multiple sound rules stack.', null, [ACT.pronunciation]),
  createContentItem('ditado', 'ditado /dʒiˈta.du/', 'Dictation exercise. Note BP palatalization: di- becomes /dʒi/, final -do → /du/. Stress on -TA-.', 'word', 'A professora pediu um ditado.', '"Ditado" is also a common classroom exercise name.', null, [ACT.pronunciation]),
  createContentItem('caderno', 'caderno /kaˈdeʁ.nu/', 'Notebook. Standard penultimate stress (ca-DER-no). Note the BP /ʁ/ uvular on -der-; in EP it would be a trilled /r/.', 'word', 'Meu caderno é azul.', 'Common classroom item; takes masculine article "o".', null, [ACT.pronunciation]),

  createContentItem('o livro', 'o livro /u ˈli.vɾu/', 'Book — masculine, ends in -o. In BP, final -o → /u/. The most basic classroom item.', 'word', 'O livro está sobre a mesa.', '"Sobre" = "on top of"; alternative "em cima de".', null, [ACT.vocabClassroom]),
  createContentItem('a caneta', 'a caneta /a kaˈne.ta/', 'Pen — feminine, ends in -a. Note closed ê pronunciation in -ne-. BP final -a stays clear /a/.', 'word', 'A caneta é da professora.', '"Da" = "de + a" article contraction.', null, [ACT.vocabClassroom]),
  createContentItem('o lápis', 'o lápis /u ˈla.pis/', 'Pencil — masculine, invariant for number. Despite ending in -is, it is singular.', 'word', 'Você tem um lápis?', 'Plural form is identical: "Você tem dois lápis?"', null, [ACT.vocabClassroom]),
  createContentItem('o caderno', 'o caderno /u kaˈdeʁ.nu/', 'Notebook — masculine. Standard -o ending.', 'word', 'Meu caderno tem 100 páginas.', '"Tem" is the 3rd person singular of "ter" (to have).', null, [ACT.vocabClassroom]),
  createContentItem('a mochila', 'a mochila /a moˈʃi.la/', 'Backpack — feminine. Note the /ʃ/ sound from "ch" (mo-SHI-la).', 'word', 'A mochila está no chão.', '"No" = "em + o" article contraction.', null, [ACT.vocabClassroom]),
  createContentItem('a mesa', 'a mesa /a ˈme.za/', 'Table or desk — feminine. Intervocalic s = /z/ (ME-za).', 'word', 'A mesa do professor é grande.', '"Do" = "de + o" article contraction.', null, [ACT.vocabClassroom]),
  createContentItem('a cadeira', 'a cadeira /a kaˈdej.ɾa/', 'Chair — feminine. Diphthong -ei- in second syllable; standard penultimate stress.', 'word', 'Esta cadeira é confortável.', 'Standard furniture vocabulary.', null, [ACT.vocabClassroom]),
  createContentItem('o quadro', 'o quadro /u ˈkwa.dɾu/', 'Board (blackboard or whiteboard) — masculine. Standard university chalkboard; "lousa" is the BP-São Paulo regional variant.', 'word', 'O professor escreveu no quadro.', 'BP southern speakers use "quadro"; SP regional "lousa" is also common.', null, [ACT.vocabClassroom]),
  createContentItem('a lousa', 'a lousa /a ˈlow.za/', 'Board (especially blackboard) — feminine. Regional BP-paulistano term; equivalent to "quadro". Note the oral ou diphthong.', 'word', 'A lousa está suja.', 'Common in São Paulo classrooms; less used in other regions of Brazil.', null, [ACT.vocabClassroom]),
  createContentItem('o giz', 'o giz /u ʒis/', 'Chalk — masculine. Final s = /s/ in BP-standard, /ʃ/ in EP and Rio. Soft g = /ʒ/.', 'word', 'Preciso de mais giz.', 'Standard classroom material; many BP universities now use whiteboards (lousa branca).', null, [ACT.vocabClassroom]),
  createContentItem('o apagador', 'o apagador /u apagaˈdoʁ/', 'Eraser (board eraser) — masculine. Stress on last syllable (-DOR ends in -r). For pencil eraser: "a borracha".', 'word', 'O apagador está perto do quadro.', 'Final -r often dropped in BP fast speech.', null, [ACT.vocabClassroom]),
  createContentItem('o computador', 'o computador /u kõ.puˈta.doʁ/', 'Computer — masculine. Stress on -DOR. Note the nasal vowel in com- /kõ/.', 'word', 'O computador da sala não está funcionando.', '"Notebook" (laptop) is common BP usage borrowed from English.', null, [ACT.vocabClassroom]),
  createContentItem('o livro didático', 'livro didático /dʒiˈda.tʃi.ku/', 'Textbook — literally "didactic book". Note TWO BP palatalizations in "didático": di- → /dʒi/, -ti- → /tʃi/.', 'word', 'O livro didático de cálculo é grosso.', 'Common in Brazilian schools and universities; standard term in education contexts.', null, [ACT.vocabClassroom]),
  createContentItem('a folha de papel', 'a folha de papel /a ˈfo.ʎa dʒi paˈpɛw/', 'A sheet of paper. Note the palatal lh in "folha" /ʎ/, the BP palatalization on "de", and the BP velar l in "papel" /pa.ˈpɛw/.', 'word', 'Pegue uma folha de papel.', '"Pegue" = imperative of "pegar" (to grab/take).', null, [ACT.vocabClassroom]),
  createContentItem('o relógio', 'o relógio /u heˈlɔ.ʒiu/ (BP) /ʁeˈlɔ.ʒiu/', 'Clock or watch — masculine. Note the open ó /ɔ/ stressed, soft g = /ʒ/, and the BP retroflex/uvular initial r.', 'word', 'O relógio da sala está atrasado.', 'BP uses "h" sound for initial r; EP uses trilled r.', null, [ACT.vocabClassroom]),
  createContentItem('a janela', 'a janela /a ʒaˈnɛ.la/', 'Window — feminine. Open é /ɛ/ in stressed syllable. Soft j = /ʒ/.', 'word', 'A janela está aberta.', 'Standard architecture vocabulary.', null, [ACT.vocabClassroom]),
  createContentItem('a porta', 'a porta /a ˈpɔʁ.ta/', 'Door — feminine. Open ó /ɔ/ stressed.', 'word', 'A porta está fechada.', 'Note: "porta" with open ó (door) contrasts with "porto" with closed ô (port/harbor).', null, [ACT.vocabClassroom]),

  createContentItem('o professor', 'o professor /u proˈfe.soʁ/', 'Male teacher/professor — masculine. Universal across primary through university. Final r often dropped in BP.', 'word', 'O professor de português é brasileiro.', 'Standard academic title; less hierarchical than English "professor".', null, [ACT.vocabPeople]),
  createContentItem('a professora', 'a professora /a proˌfeˈso.ɾa/', 'Female teacher/professor — feminine. Same role, gender-marked.', 'word', 'A professora Costa ensina cálculo.', 'Used as direct address: "Professora!" + first name in BP.', null, [ACT.vocabPeople]),
  createContentItem('o aluno', 'o aluno /u aˈlu.nu/', 'Male pupil/student in a specific class. Contrasts with "estudante" which is more general.', 'word', 'O aluno chegou atrasado.', 'Use "aluno" when describing student-of-someone relationship.', null, [ACT.vocabPeople]),
  createContentItem('a aluna', 'a aluna /a aˈlu.na/', 'Female pupil/student. Standard feminine -a ending.', 'word', 'A aluna fez a melhor prova.', '"Aluna" pairs with "professor(a)" — student of a specific teacher.', null, [ACT.vocabPeople]),
  createContentItem('o estudante', 'o estudante /u es.tuˈdɐ̃.tʃi/', 'Male student (general). Same word for male and female; article distinguishes. Final -te palatalizes in BP.', 'word', 'O estudante de doutorado deu uma aula.', '"Doutorado" = "doctorate" (PhD program).', null, [ACT.vocabPeople]),
  createContentItem('a estudante', 'a estudante /a es.tuˈdɐ̃.tʃi/', 'Female student. Same word as masculine; only article changes.', 'word', 'A estudante coreana é minha colega.', 'Adjectives still agree in gender: "coreana" feminine.', null, [ACT.vocabPeople]),
  createContentItem('o colega', 'o colega /u koˈlɛ.ga/', 'Male classmate, coworker, or peer. Despite ending in -a, the noun is masculine when the referent is male — gender determined by referent, not ending.', 'word', 'Meu colega de quarto é da Argentina.', 'EPICENO noun: same form for both genders; article changes.', null, [ACT.vocabPeople]),
  createContentItem('a colega', 'a colega /a koˈlɛ.ga/', 'Female classmate, coworker, or peer. Same word, feminine article.', 'word', 'A colega da Maria é da Bahia.', 'Adjectives agree: "minha colega coreana".', null, [ACT.vocabPeople]),
  createContentItem('a turma', 'a turma /a ˈtuʁ.ma/', 'Class / group of students / cohort — feminine. "Minha turma" = "my class group".', 'word', 'A turma de cálculo tem 50 alunos.', 'Used both for the people and the section number.', null, [ACT.vocabPeople]),
  createContentItem('o diretor / a diretora', 'diretor / diretora', 'School principal / department head — gender-marked.', 'word', 'A diretora da escola convocou uma reunião.', 'Used at primary, secondary, and university (faculty director) levels.', null, [ACT.vocabPeople]),

  createContentItem('Artigos definidos', 'definite articles', 'Portuguese has FOUR definite articles, agreeing in gender and number with the noun: o (m sg) / a (f sg) / os (m pl) / as (f pl). They appear MUCH more frequently than English "the" — used with possessives, names, abstract nouns, and more.', 'sentence', 'o livro / a caneta / os livros / as canetas', 'BP often uses articles before names ("a Maria", "o João") — very common, not formal.', [{ target: 'o (m sg)', note: 'o livro, o professor, o dia' }, { target: 'a (f sg)', note: 'a caneta, a professora, a casa' }, { target: 'os (m pl)', note: 'os livros, os professores, os dias' }, { target: 'as (f pl)', note: 'as canetas, as professoras, as casas' }], [ACT.grammarGenderArticles]),
  createContentItem('Artigos indefinidos', 'indefinite articles', 'Portuguese has FOUR indefinite articles: um (m sg) / uma (f sg) / uns (m pl) / umas (f pl). The plural forms uns/umas mean "some" — less common in English usage but standard in Portuguese.', 'sentence', 'um livro / uma caneta / uns livros / umas canetas', 'um/uma = "a/an"; uns/umas = "some/a few".', [{ target: 'um (m sg)', note: 'um livro = "a book"' }, { target: 'uma (f sg)', note: 'uma caneta = "a pen"' }, { target: 'uns (m pl)', note: 'uns livros = "some books / a few books"' }, { target: 'umas (f pl)', note: 'umas canetas = "some pens"' }], [ACT.grammarGenderArticles]),
  createContentItem('Gênero ocultos', 'gender exceptions', 'Some nouns DEFY the default -o/-a rule. Memorize the exceptions: o dia, o mapa, o problema, o sistema, o cinema (all m despite -a); a mão, a flor, a tribo (all f despite atypical endings). Always learn noun + article together.', 'sentence', 'o dia (m), o mapa (m), o problema (m), a mão (f), a flor (f)', 'Many -ema words are masculine because they come from Greek neuter (problema, sistema, tema, poema, drama, telegrama).', null, [ACT.grammarGenderArticles]),
  createContentItem('Contrações de preposição', 'preposition + article contractions', 'Portuguese MERGES preposition + article into a single word. de + o = do, de + a = da, em + o = no, em + a = na, a + a = à (crase), por + o = pelo, por + a = pela. These are obligatory — you cannot write them separately.', 'sentence', 'do professor, da escola, no quadro, na mesa, à praia, pelo caminho', 'Beginners often forget these contractions and write "de o" or "em a" — always merge.', [{ target: 'de + o = do', note: 'o livro do professor' }, { target: 'de + a = da', note: 'a sala da professora' }, { target: 'em + o = no', note: 'no quadro = "on the board"' }, { target: 'em + a = na', note: 'na mesa = "on the table"' }, { target: 'a + a = à', note: 'crase; "vou à USP"' }], [ACT.grammarGenderArticles]),

  createContentItem('este / esta — near speaker', 'este/esta — proximal', 'Demonstrative for things NEAR the speaker. este (m sg) este livro, esta (f sg) esta caneta, estes (m pl) estes livros, estas (f pl) estas canetas.', 'sentence', 'Este livro é meu. Esta caneta é dela.', 'In BP, "este/esse" are often blurred in speech; in formal writing keep them distinct.', [{ target: 'este (m sg)', note: 'este livro = "this book (near me)"' }, { target: 'esta (f sg)', note: 'esta caneta = "this pen (near me)"' }, { target: 'estes (m pl)', note: 'estes livros = "these books"' }, { target: 'estas (f pl)', note: 'estas canetas = "these pens"' }], [ACT.grammarThisThat]),
  createContentItem('esse / essa — near listener', 'esse/essa — medial', 'Demonstrative for things NEAR the LISTENER (not the speaker). Standard Portuguese has a three-way distance system; English collapses these into "that".', 'sentence', 'Esse livro que você tem é meu? Essa caneta aí é boa.', '"Aí" (there, near you) often pairs with esse/essa.', [{ target: 'esse (m sg)', note: 'esse livro = "that book (near you)"' }, { target: 'essa (f sg)', note: 'essa caneta = "that pen (near you)"' }], [ACT.grammarThisThat]),
  createContentItem('aquele / aquela — far from both', 'aquele/aquela — distal', 'Demonstrative for things FAR from BOTH speaker and listener. The "over there" distance. "Lá" (there, far) often pairs with aquele/aquela.', 'sentence', 'Aquele livro lá no fundo é meu.', 'Captures the "way over there" sense English needs "that one over there" to express.', [{ target: 'aquele (m sg)', note: 'aquele livro = "that book (over there)"' }, { target: 'aquela (f sg)', note: 'aquela caneta = "that pen (over there)"' }], [ACT.grammarThisThat]),
  createContentItem('isto / isso / aquilo', 'neuter demonstratives', 'Use ISTO/ISSO/AQUILO when the gender or identity of the thing is unknown — typical for "What is this?" questions. They don\'t agree with anything (no gender, no number).', 'sentence', 'O que é isto? — Isto é um livro.', 'Once the thing is identified by gender, switch back to este/esse/aquele with proper agreement.', [{ target: 'isto (near me)', note: 'unknown thing near speaker' }, { target: 'isso (near you)', note: 'unknown thing near listener' }, { target: 'aquilo (far)', note: 'unknown thing far from both' }], [ACT.grammarThisThat]),

  createContentItem('o que', 'o que = what (object/thing)', 'Ask "what" with O QUE — placed at the beginning of the sentence. "O que é isto?" ("What is this?"). The "o" is the article, "que" is the question word; together they ask about a thing.', 'sentence', 'O que é isto? O que você quer? O que aconteceu?', 'Same word order as English wh-questions for the object case.', null, [ACT.grammarQuestions]),
  createContentItem('quem', 'quem = who', 'Ask "who" with QUEM. "Quem é ele?" ("Who is he?"). Quem can also be the object of "de" → "de quem" ("whose / from whom").', 'sentence', 'Quem é a professora? De quem é este livro?', 'No gender or number — invariant form.', null, [ACT.grammarQuestions]),
  createContentItem('onde', 'onde = where', 'Ask "where" with ONDE. Combines with prepositions: "de onde" (from where), "para onde" (to where), "por onde" (through where).', 'sentence', 'Onde está o lápis? De onde você é?', 'Common in classroom: "Onde está o meu caderno?"', null, [ACT.grammarQuestions]),
  createContentItem('de quem — possession question', '"whose" pattern', 'Use "DE QUEM" + SER to ask whose something is. Word order: De quem + é + thing. "De quem é este livro?" ("Whose book is this?"). Answer: "É de [name]" / "É meu/minha".', 'sentence', 'De quem é esta mochila? — É da Sofia. / É minha.', 'BP often uses "é de + name" as the natural answer rather than possessives.', null, [ACT.grammarQuestions]),

  createContentItem('Sala 207', 'reading text', 'Imagine our classroom at USP. Read aloud, paying attention to articles, palatalization, and stress.', 'paragraph', 'A sala 207 do prédio de Engenharia da USP tem 30 cadeiras, uma mesa grande para o professor, e um quadro branco no fundo. Sobre a minha mesa está o meu livro de cálculo, um caderno azul, e dois lápis. A mochila da minha colega Sofia está no chão, perto da porta. A janela está aberta porque hoje faz calor.', 'Translation: "Classroom 207 in USP\'s Engineering building has 30 chairs, a large desk for the professor, and a whiteboard at the back. On my desk are my calculus textbook, a blue notebook, and two pencils. My classmate Sofia\'s backpack is on the floor, near the door. The window is open because it\'s hot today."', [{ target: 'do prédio de Engenharia', note: 'de + o = do; "prédio" = building' }, { target: 'um quadro branco', note: 'indefinite article; "branco" = white' }, { target: 'no fundo', note: 'em + o = no; "fundo" = back/depth' }, { target: 'sobre a minha mesa', note: '"sobre" = on top of; possessive "minha" + article "a" (BP uses both together)' }, { target: 'no chão', note: '"chão" = floor; nasal ã' }, { target: 'faz calor', note: 'impersonal weather phrase; "fazer" used impersonally' }], [ACT.reading]),
  createContentItem('Perguntas', 'comprehension questions', 'Five questions targeting the paragraph. Answer in short sentences using SER + article.', 'sentence', 'Q1: Onde está a sala? Q2: Quantas cadeiras tem? Q3: O que está sobre a mesa? Q4: De quem é a mochila? Q5: Por que a janela está aberta?', 'Practice question-word + verb order.', [{ target: 'A1: A sala 207 está no prédio de Engenharia da USP.', note: 'full sentence' }, { target: 'A2: Tem 30 cadeiras.', note: 'short answer; "tem" = "has/there are"' }, { target: 'A3: O livro, o caderno e dois lápis.', note: 'list answer' }, { target: 'A4: É da Sofia.', note: 'short "é de + name"' }, { target: 'A5: Porque faz calor.', note: 'reason answer with "porque"' }], [ACT.reading]),

  createContentItem('Diálogo: Perguntando à professora', 'dialogue: asking the professor', 'A natural classroom exchange between a USP student and her professor about classroom items. Standard polite-respectful register: student uses "professora", professor uses "você".', 'conversation', 'Aluna: Professora, com licença. De quem é este lápis sobre a sua mesa?\nProfessora: Ah, deve ser do João. Ele esqueceu na aula passada.\nAluna: E aquela mochila no canto, é sua?\nProfessora: Não, aquela é da Sofia. A minha é a azul aqui ao lado.\nAluna: Entendi. Posso pegar um pedaço de giz?\nProfessora: Claro, fique à vontade.\nAluna: Muito obrigada, professora!', 'Common micro-interactions: identifying lost objects, asking permission, polite request, thanks.', [{ target: 'com licença', note: 'standard "excuse me" before asking a question' }, { target: 'deve ser', note: '"must be"; modal "dever" expressing inference' }, { target: 'esqueceu na aula passada', note: '"forgot in the last class"; past tense of esquecer' }, { target: 'fique à vontade', note: '"feel free / be at ease"; standard polite invitation' }], [ACT.listening]),

  createContentItem('Descrição do meu espaço de estudo', 'writing template', 'Six-sentence template for describing your study space. Fill in the bracketed slots — the structure carries the rest.', 'sentence', 'Eu estudo na [lugar]. Na minha mesa tem [objeto m] e [objeto f]. Sobre a [objeto] está o meu [objeto m]. A minha [objeto f] é [cor]. Este [objeto m] é meu, mas essa [objeto f] é do(a) [pessoa]. Eu gosto muito de estudar aqui!', 'Six sentences using gender-marked articles, demonstratives, and possessives.', null, [ACT.writing]),
  createContentItem('Exercício de escrita', 'writing exercise', 'Write your own 4-6 sentence study space description. Use at least one demonstrative, one possessive, and one article contraction.', 'sentence', 'Exemplo: Eu estudo no meu quarto. Na minha mesa tem um computador e uma agenda. Sobre a agenda está o meu lápis preto. A minha caneta é azul. Este caderno é meu, mas essa caneta é da minha irmã. Eu gosto muito de estudar aqui!', 'Translation: "I study in my room. On my desk are a computer and a planner. On the planner is my black pencil. My pen is blue. This notebook is mine, but that pen is my sister\'s. I really like studying here!"', null, [ACT.writing]),

  createContentItem('USP e o vestibular FUVEST', 'USP entrance exam', 'USP entry is via the FUVEST vestibular — one of the most selective university entrance exams in Brazil. Two stages: first phase (90 multiple-choice questions covering all high school subjects) and second phase (written essays + specific area questions over three days). Acceptance rates for popular courses (medicina, engenharia) can be under 1 percent.', 'word', 'FUVEST = Fundação Universitária para o Vestibular.', 'Free tuition + extreme selectivity creates intense study culture; many students attend "cursinho" (prep-school year) before applying.', null, [ACT.culture]),
  createContentItem('Colega ≠ amigo', 'colega vs amigo distinction', 'BP distinguishes carefully: "colega" = classmate, coworker, peer (functional relationship); "amigo" = friend (personal bond). Calling a coworker "meu amigo" too quickly can sound exaggerated; "meu colega" is the natural default.', 'word', 'colega de turma, colega de trabalho, amigo íntimo', 'EP also makes this distinction but the boundary is slightly different — friendship vocabulary in EP is more cautious.', null, [ACT.culture]),
  createContentItem('Aula vs classe', 'BP vs EP terminology', 'BP: "a aula" = the lesson/class session; "a turma" = the cohort/section. EP: "a aula" = the lesson; "a classe" = the class group. BP "classe" exists but is rarer and more abstract (social class).', 'word', 'BP: minha aula de cálculo, minha turma 32.\nEP: a minha aula de cálculo, a minha classe.', 'Mix these and you sound foreign — pick BP and stick with it.', null, [ACT.culture]),

  createContentItem('Tarefa: primeira aula', 'task: first class', 'Roleplay your first day in a USP classroom. The AI tutor plays your colega and the professor. Use every skill: name objects, ask whose, use demonstratives, ask one wh-question.', 'conversation', '[Sala 207, USP]\nColega: Oi! Você é nova aqui?\nVocê: [cumprimentar + responder]\nColega: De quem é essa mochila?\nVocê: [responder usando demonstrativo + possessivo]\nProfessora: Bom dia, pessoal! Abram o livro na página 15.\nVocê: [perguntar sobre objeto que você não tem]\nColega: Toma, pode pegar o meu.\nVocê: [agradecer + comentar]', 'Six turns; combine vocabulary, demonstratives, and articles.', [{ target: 'apresentar-se brevemente', note: 'you already know this from Unit 1; reuse "Oi, sou…"' }, { target: 'usar demonstrativo', note: 'this/that/over-there + correct gender' }, { target: 'pedir emprestado', note: 'borrowing: "Você pode me emprestar…?"' }, { target: 'agradecer', note: '"Obrigado/Obrigada" — gender-mark yourself!' }], [ACT.task]),
];

module.exports = {
  title: 'Level 1 · Unit 2: Na sala de aula — Classroom and Campus Life',
  category: 'classroom',
  difficulty: 'beginner',
  targetLang: 'pt', nativeLang: 'en', track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'naming-objects', label: 'Naming objects with article', goal: 'Identify any classroom object using definite article + correct gender (o livro, a caneta).' },
    { id: 'asking-whose', label: 'Asking whose', goal: 'Use "De quem é…?" to ask ownership and answer with "é de + name" or possessive.' },
    { id: 'demonstratives', label: 'Three-way demonstratives', goal: 'Use este/esse/aquele based on distance from speaker and listener.' },
    { id: 'classroom-requests', label: 'Polite requests', goal: 'Make a basic classroom request using "Posso…?" or "Você pode me emprestar…?".' },
  ],
  relatedPools: ['topic-classroom', 'topic-objects'],
  content,
};
