// Level 1 Unit 5 — Life in the Portuguese-Speaking World
// Functions: describing daily life in Brazil and Portugal; family, food, leisure;
// comparing cultural rhythms; making cross-cultural observations.

const createContentItem = (target, pronunciation, note, type = 'word', example = '', exampleNote = '', breakdown = null, activityIds = []) => ({
  type, activityIds, targetText: target, romanization: pronunciation, nativeText: note, pronunciation,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'pt-l1u5-orientation', pronunciation: 'pt-l1u5-pronunciation',
  vocabFamily: 'pt-l1u5-vocab-family', vocabFoodLeisure: 'pt-l1u5-vocab-food-leisure',
  grammarTer: 'pt-l1u5-grammar-ter', grammarGostar: 'pt-l1u5-grammar-gostar',
  grammarBpEpContrast: 'pt-l1u5-grammar-bp-ep',
  reading: 'pt-l1u5-reading', listening: 'pt-l1u5-listening', writing: 'pt-l1u5-writing',
  culture: 'pt-l1u5-culture', task: 'pt-l1u5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do', goals: ['Describe family relationships in Portuguese (pai, mãe, irmão, primo, tio, avó) with possessives and gender agreement.', 'Talk about preferences using "gostar de" + noun/verb.', 'Compare daily-life elements (food, leisure, family meals) between Brazil and Portugal.'], task: 'Picture a Sunday lunch with a Brazilian host family in São Paulo or a Portuguese family in Lisbon — feijoada vs cozido. By end of lesson you describe both scenes confidently.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'BP vs EP family words', goals: ['Pronounce "tia" with BP palatalization /ˈtʃi.a/ vs EP /ˈti.a/.', 'Handle the nasal final -ão in "irmão", "tio Antônio".', 'Pronounce "feijoada" /fej.ʒuˈa.da/ — the iconic Brazilian dish.'], task: 'Read each name and word, note BP/EP differences.' },
  { id: ACT.vocabFamily, section: 'Vocabulary I', title: 'Family members', goals: ['Memorize 18 family terms with gender pairs: pai/mãe, irmão/irmã, filho/filha, tio/tia, primo/prima, avô/avó, sogro/sogra, marido/esposa, etc.', 'Recognize BP-specific terms like "padrinho/madrinha" (godparent) and "afilhado/afilhada" (godchild).'], task: 'Draw your family tree and label each member.' },
  { id: ACT.vocabFoodLeisure, section: 'Vocabulary II', title: 'Food and leisure', goals: ['Memorize 15 food/leisure nouns: feijoada, arroz, feijão, açaí, pão de queijo, futebol, samba, novela, praia.', 'Use BP/EP food contrasts: pão de queijo vs pastel de Belém, açaí vs ginja.'], task: 'List five Brazilian and five Portuguese foods or leisure activities.' },
  { id: ACT.grammarTer, section: 'Grammar I', title: 'TER for possession and family', goals: ['Conjugate TER (to have): eu tenho, você tem, nós temos, eles têm.', 'Use TER for possession ("tenho um carro"), family ("tenho dois irmãos"), and impersonal "there is/are" in BP ("tem muita gente aqui").'], task: 'Build 6 sentences using ter for different meanings.' },
  { id: ACT.grammarGostar, section: 'Grammar II', title: 'GOSTAR DE for likes', goals: ['Use GOSTAR + DE + noun: "Eu gosto DE feijoada", "Eu gosto DE estudar". The preposition DE is OBLIGATORY.', 'Apply article contractions: gosto do café, gosto da praia, gosto dos jogos.', 'Negate with "Não gosto de…".'], task: 'Write 5 like/dislike sentences using gostar de.' },
  { id: ACT.grammarBpEpContrast, section: 'Grammar III', title: 'BP vs EP lexicon and grammar', goals: ['Recognize 10 BP/EP lexical pairs: ônibus/autocarro, café da manhã/pequeno-almoço, trem/comboio, geladeira/frigorífico, celular/telemóvel.', 'Apply the gerund vs infinitive rule: BP "estou estudando" vs EP "estou a estudar".'], task: 'Translate 5 sentences between BP and EP forms.' },
  { id: ACT.reading, section: 'Reading', title: 'Domingo na família Silva', goals: ['Read a paragraph describing a Brazilian Sunday family lunch and answer comprehension questions.'], task: 'Read aloud, answer questions.' },
  { id: ACT.listening, section: 'Listening', title: 'Brazilian vs Portuguese visitor', goals: ['Follow a 6-turn dialogue between a Brazilian USP student and a Portuguese exchange student comparing home life.'], task: 'Listen, reproduce with your own cultural reference.' },
  { id: ACT.writing, section: 'Writing', title: 'Describe your family', goals: ['Write 6-8 sentences about your family using ter, gostar de, and at least 5 family-relationship terms.'], task: 'Write the family paragraph.' },
  { id: ACT.culture, section: 'Culture', title: 'Family rhythms and Sunday lunch', goals: ['Understand the central role of Sunday family lunch in both Brazilian and Portuguese culture.', 'Compare Brazilian feijoada to Portuguese cozido — both are slow-cooked Sunday traditions.'], task: 'Describe one family-meal tradition from your own culture in Portuguese.' },
  { id: ACT.task, section: 'Task', title: 'Cross-cultural conversation', goals: ['Run a 6-turn conversation comparing your family, food, and leisure to a Brazilian colega\'s.'], task: 'Roleplay with the AI tutor.' },
];

const content = [
  createContentItem('Família e domingo', 'family and Sunday', 'In both Brazil and Portugal, Sunday lunch is the family centerpiece. In BP it might be feijoada or churrasco; in EP it might be cozido or arroz de marisco. Both can stretch 3-4 hours with avó(o)s, tio(a)s, primo(a)s.', 'word', 'Brasil: feijoada · churrasco · domingo em família\nPortugal: cozido · arroz de marisco · almoço de domingo', 'Sunday lunch culture grounds many of this lesson\'s examples.', null, [ACT.orientation]),
  createContentItem('Lusofonia', 'lusophone world', 'Portuguese is spoken in nine official countries: Brasil (210M), Portugal (10M), Angola, Moçambique, Cabo Verde, Guiné-Bissau, São Tomé e Príncipe, Timor-Leste, and Equatorial Guinea. Plus diaspora communities in the US, Canada, France, UK, Japan. Total ~260M speakers.', 'word', 'CPLP — Comunidade dos Países de Língua Portuguesa', 'Each country has distinctive accents, lexicon, and food traditions; this lesson focuses on BP with EP contrasts.', null, [ACT.orientation]),

  createContentItem('tia /ˈtʃi.a/ (BP) vs /ˈti.a/ (EP)', 'BP-EP palatalization', '"Tia" (aunt) — pronounced "TCHI-a" in BP, "TI-a" in EP. The single clearest BP accent marker.', 'word', 'A tia Marisa é a irmã da minha mãe.', '"Tia" / "tio" also used affectionately for older adults you respect, not just blood relatives.', null, [ACT.pronunciation]),
  createContentItem('irmão', 'irmão /iʁˈmɐ̃w̃/', '"Brother" — full nasal -ão diphthong. Beginners drop nasalization and say "irMÃO" with oral vowel — produces "irmau" not a word.', 'word', 'Meu irmão é mais velho que eu.', '"Mais velho" = older; "mais novo" = younger.', null, [ACT.pronunciation]),
  createContentItem('feijoada', 'feijoada /fej.ʒuˈa.da/', 'The iconic Brazilian dish — black beans stewed with various pork cuts. Pronunciation: closed e + i diphthong, soft j /ʒ/, hiatus u-a (two syllables), final -a clear /a/.', 'word', 'Domingo a gente faz feijoada.', 'Saturday or Sunday is the traditional feijoada day.', null, [ACT.pronunciation]),

  createContentItem('o pai', 'o pai /u paj/', 'Father — masculine. Common in BP affectionate forms: "papai" (daddy), "pai" (dad/father).', 'word', 'Meu pai é engenheiro.', 'Plural "os pais" = "the parents" (covers father + mother).', null, [ACT.vocabFamily]),
  createContentItem('a mãe', 'a mãe /a mɐ̃j̃/', 'Mother — feminine. Nasal -ãe diphthong. BP affectionate: "mamãe".', 'word', 'Minha mãe é professora.', 'Common BP exclamation: "Minha mãe!" or "Nossa mãe!" expressing surprise.', null, [ACT.vocabFamily]),
  createContentItem('o irmão / a irmã', 'irmão / irmã', 'Brother / sister. Singular irmão (nasal -ão), feminine irmã (nasal ã). Plural: irmãos (mixed/male), irmãs (all female).', 'word', 'Tenho dois irmãos e uma irmã.', 'Mixed-gender plural defaults to masculine "irmãos".', null, [ACT.vocabFamily]),
  createContentItem('o filho / a filha', 'filho / filha', 'Son / daughter. Palatal lh in middle. Plural filhos covers any-gender mix; "filhas" only when all female.', 'word', 'Meus pais têm três filhos.', '"Filho único" = only child.', null, [ACT.vocabFamily]),
  createContentItem('o tio / a tia', 'tio / tia', 'Uncle / aunt. BP palatalization on tia /ˈtʃi.a/.', 'word', 'Minha tia mora em Salvador.', '"Tio/tia" also used affectionately for any older family friend you respect; particularly common in northern Brazil.', null, [ACT.vocabFamily]),
  createContentItem('o primo / a prima', 'primo / prima', 'Cousin. Gender-marked. "Primo de segundo grau" = second cousin.', 'word', 'Tenho muitos primos no Rio.', 'Brazilian extended families often gather at Sunday lunches; "primo" relationships closer than US convention.', null, [ACT.vocabFamily]),
  createContentItem('o avô / a avó', 'avô / avó', 'Grandfather / grandmother. CRITICAL contrast: avô (closed ô, masculine) vs avó (open ó, feminine). The classic Portuguese minimal pair.', 'word', 'Meus avós moram em Minas.', 'Plural "avós" covers both genders; affectionate forms "vovô" / "vovó".', null, [ACT.vocabFamily]),
  createContentItem('o sobrinho / a sobrinha', 'sobrinho / sobrinha', 'Nephew / niece. Palatal nh.', 'word', 'Meu sobrinho tem 5 anos.', 'Standard family-tree term.', null, [ACT.vocabFamily]),
  createContentItem('o neto / a neta', 'neto / neta', 'Grandson / granddaughter. Closed e in "neto".', 'word', 'Os meus netos visitam toda semana.', 'Plural "netos" any gender.', null, [ACT.vocabFamily]),
  createContentItem('o marido / a esposa', 'marido / esposa', 'Husband / wife. "Esposa" (feminine of esposo) is most common in BP. EP and older BP also uses "mulher" for "wife".', 'word', 'O marido da Maria é médico.', 'BP increasingly uses "companheiro/companheira" for non-married partners.', null, [ACT.vocabFamily]),
  createContentItem('o namorado / a namorada', 'namorado / namorada', 'Boyfriend / girlfriend. Used for unmarried dating partners. "Estamos namorando" = we are dating.', 'word', 'Minha namorada é estudante de medicina.', 'BP common; EP often uses just "rapaz/rapariga" or specific name.', null, [ACT.vocabFamily]),
  createContentItem('o sogro / a sogra', 'sogro / sogra', 'Father-in-law / mother-in-law. "Cunhado/cunhada" = brother/sister-in-law.', 'word', 'Minha sogra é portuguesa.', 'Common in BP-EP cross-cultural marriages.', null, [ACT.vocabFamily]),
  createContentItem('o padrinho / a madrinha', 'padrinho / madrinha', 'Godfather / godmother. In Brazilian Catholic culture, padrinhos play active role in child\'s life, often equal to aunts/uncles.', 'word', 'Meu padrinho mora no Recife.', 'Brazilian wedding tradition: each bride/groom picks "padrinhos" who stand alongside.', null, [ACT.vocabFamily]),
  createContentItem('o cunhado / a cunhada', 'cunhado / cunhada', 'Brother / sister-in-law (spouse\'s sibling, or sibling\'s spouse).', 'word', 'Minha cunhada é jornalista.', 'Common family-tree term.', null, [ACT.vocabFamily]),
  createContentItem('os parentes', 'parentes /paˈɾẽ.tʃis/', 'Relatives (extended family). Distinct from "pais" (parents). BP palatalization on -tes → /tʃis/.', 'word', 'Tenho parentes em todo o Brasil.', 'A common confusion for English speakers: "parentes" ≠ "parents".', null, [ACT.vocabFamily]),

  createContentItem('o arroz e o feijão', 'rice and beans', 'The staple Brazilian lunch combo. Almost always eaten together. "Arroz com feijão" served daily across Brazil.', 'word', 'No almoço sempre como arroz e feijão.', '"Feijão" varies regionally: black beans in Rio, brown in São Paulo, "carioquinha" in Minas.', null, [ACT.vocabFoodLeisure]),
  createContentItem('a feijoada', 'feijoada', 'Brazilian black-bean stew with various pork cuts; traditional Saturday lunch. Iconic of Rio de Janeiro especially. Served with farofa, couve, laranja, and arroz.', 'word', 'Vou fazer feijoada no sábado.', 'Slave-origin dish that became Brazilian national symbol; takes 4+ hours to cook properly.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o pão de queijo', 'pão de queijo /pɐ̃w̃ dʒi ˈke.ʒu/', 'Cheese bread balls, Minas Gerais specialty now nationwide. Made with tapioca flour and cheese. Nasal pão.', 'word', 'Adoro pão de queijo quentinho.', 'BP comfort food; sold at every padaria.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o açaí', 'açaí /a.saˈi/', 'Amazonian berry eaten as frozen smoothie bowl. BP urban favorite since 2000s. Stress on final i; cedilha ç.', 'word', 'Vou tomar um açaí com banana.', 'Originally Amazonian indigenous food; now popular gym-snack across Brazil and globally.', null, [ACT.vocabFoodLeisure]),
  createContentItem('a brigadeiro', 'brigadeiro /bri.gaˈdej.ɾu/', 'Brazilian chocolate truffle made of condensed milk + cocoa + butter, rolled in chocolate sprinkles. Birthday-party staple. Masculine despite -o referring to a generic candy in some usages.', 'word', 'Quero três brigadeiros, por favor.', 'Always served at children\'s birthdays; symbol of Brazilian celebration.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o churrasco', 'churrasco /ʃuˈʁas.ku/', 'Brazilian barbecue tradition, especially in southern Brazil (Rio Grande do Sul). Massive slabs of beef grilled on skewers. Sunday social event.', 'word', 'Vamos fazer um churrasco no domingo.', 'Different from Texas BBQ — focus on beef cuts, salt-only seasoning, slow grilling.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o pastel de Belém / nata', 'pastel de Belém (EP)', 'Famous Portuguese custard tart from the Belém district of Lisbon. The original recipe is a 200-year-old secret. EP equivalent of Brazilian pão de queijo as iconic baked food.', 'word', 'Comprei seis pastéis de nata.', 'EP staple food; tourists buy boxes at Pastéis de Belém shop.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o futebol', 'futebol /futʃiˈbɔw/', 'Soccer — Brazil\'s most-loved sport. Note BP velar l /ɔw/ at end; open ó stressed.', 'word', 'Vou ao jogo do Corinthians.', 'Major BP clubs: Corinthians, Palmeiras, São Paulo, Santos, Flamengo, Vasco.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o samba', 'samba /ˈsɐ̃.ba/', 'Brazilian musical and dance tradition, nasal vowel ɐ̃. Carnaval, Rio, Salvador, Recife all celebrate samba traditions.', 'word', 'Adoro dançar samba.', 'Multiple sub-genres: samba-enredo (Carnaval), pagode, samba-canção.', null, [ACT.vocabFoodLeisure]),
  createContentItem('a novela', 'novela /noˈvɛ.la/', 'Brazilian TV soap opera; nightly cultural event watched by millions. Open ɛ stressed.', 'word', 'Toda noite assisto a novela das 9.', 'Globo TV "novela das nove" is a cultural institution; topics often reflect Brazilian society debates.', null, [ACT.vocabFoodLeisure]),
  createContentItem('a praia', 'praia /ˈpɾa.ja/', 'Beach. BP-EP same word but the cultural meaning differs: BP beaches (Copacabana, Ipanema, Salvador) for daily socializing; EP beaches (Algarve) for summer vacation.', 'word', 'No sábado, vou à praia com a família.', 'Crase à before feminine praia.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o Carnaval', 'Carnaval /kaʁ.naˈvaw/', 'Brazilian Carnaval — the four-day festival before Lent. Massive parades in Rio and Salvador; street parties (blocos) across the country. Public holiday.', 'word', 'No Carnaval, viajamos para Salvador.', 'EP equivalent: smaller scale; mostly Madeira and Algarve celebrations.', null, [ACT.vocabFoodLeisure]),
  createContentItem('a roda de samba', 'roda de samba', 'Informal samba gathering with friends, often at a bar or someone\'s house. Quintessential Brazilian Sunday-afternoon social activity.', 'word', 'No fim de semana tem roda de samba na praça.', 'Less formal than concert; more like collective singalong.', null, [ACT.vocabFoodLeisure]),
  createContentItem('o fado', 'fado /ˈfa.du/', 'Portuguese traditional music genre — melancholic vocal style with guitar accompaniment. UNESCO Intangible Cultural Heritage. The EP cultural counterpart to BP samba.', 'word', 'Em Lisboa, gosto de ouvir fado nos bares de Alfama.', 'Often performed in small "casas de fado" in Alfama, Bairro Alto, Coimbra.', null, [ACT.vocabFoodLeisure]),

  createContentItem('ter (presente)', 'ter — to have', 'Conjugation: eu TENHO, você/ele/ela TEM, nós TEMOS, vocês/eles/elas TÊM (note circumflex on têm 3pl to distinguish from singular tem). One of the most-used verbs.', 'sentence', 'eu tenho / você tem / nós temos / eles têm', 'Same form for both 3sg "tem" (sem til) and 3pl "têm" (com til); accent is the only difference in writing.', [{ target: 'eu tenho', note: 'irregular; not "teno"' }, { target: 'você/ele/ela tem', note: '3rd singular' }, { target: 'nós temos', note: '1st plural' }, { target: 'vocês/eles/elas têm', note: '3rd plural; circumflex on ê' }], [ACT.grammarTer]),
  createContentItem('Ter for impersonal "there is"', 'BP "tem" for existence', 'BP USES "ter" impersonally for "there is/are": "Tem muita gente aqui" = "There are many people here". EP uses "haver" instead: "Há muita gente aqui". The BP "tem" pattern is one of the clearest BP markers in speech.', 'sentence', 'BP: Tem uma padaria perto da USP.\nEP: Há uma padaria perto da USP.', 'Both are correct in their region; "tem" sounds Brazilian, "há" sounds Portuguese.', null, [ACT.grammarTer]),

  createContentItem('gostar de + algo', 'gostar de — to like', 'GOSTAR is always followed by the preposition DE. "Eu gosto DE café" — never "eu gosto café". The DE contracts with definite articles: gosto DO café (de + o), gosto DA música (de + a).', 'sentence', 'Eu gosto de feijoada. Eu gosto DO café da Brasil.', 'A persistent learner trap: dropping DE. Lock it in.', [{ target: 'gostar + DE + bare noun', note: 'eu gosto de música, gosto de café' }, { target: 'gostar + DE + the (contracted)', note: 'gosto DO café (de + o); gosto DA praia (de + a)' }, { target: 'gostar + DE + verb (infinitive)', note: 'eu gosto de estudar, gosto de dormir' }], [ACT.grammarGostar]),
  createContentItem('Negation: não gosto de', 'negating likes', 'Negate with "não" before gostar: "Não gosto de carne". The DE stays. Optional emphasis with "muito" or "nada": "Não gosto NADA de…" = "I don\'t like it AT ALL".', 'sentence', 'Eu não gosto de feijão. / Não gosto NADA de chuva.', '"Não gosto nada" is BP-emphatic; comparable to English "I really don\'t like".', null, [ACT.grammarGostar]),

  createContentItem('Lexical BP vs EP', '10 essential lexical pairs', 'Memorize ten high-frequency BP/EP word pairs: ônibus/autocarro, café da manhã/pequeno-almoço, celular/telemóvel, geladeira/frigorífico, sorvete/gelado, biscoito/bolacha, banheiro/casa-de-banho, abacaxi/ananás, chope/imperial, calça/calças.', 'sentence', 'BP: ônibus, celular, banheiro\nEP: autocarro, telemóvel, casa-de-banho', 'Using BP words in Portugal still works for comprehension but sounds Brazilian; same for EP words in Brazil.', [{ target: 'ônibus / autocarro', note: 'bus' }, { target: 'café da manhã / pequeno-almoço', note: 'breakfast' }, { target: 'celular / telemóvel', note: 'cell phone' }, { target: 'geladeira / frigorífico', note: 'refrigerator' }, { target: 'sorvete / gelado', note: 'ice cream' }, { target: 'biscoito / bolacha', note: 'cookie (BP-EP partly swapped!)' }, { target: 'banheiro / casa-de-banho', note: 'bathroom' }, { target: 'abacaxi / ananás', note: 'pineapple' }, { target: 'chope / imperial', note: 'draft beer' }, { target: 'calça / calças', note: 'pants (BP singular noun, EP plural)' }], [ACT.grammarBpEpContrast]),
  createContentItem('Gerund vs infinitive', '"estou estudando" vs "estou a estudar"', 'Progressive aspect differs: BP uses estar + GERUND (estou estudando); EP uses estar + A + INFINITIVE (estou a estudar). Both mean "I am studying".', 'sentence', 'BP: Estou estudando português.\nEP: Estou a estudar português.', 'Pick one and stick with it. Using EP gerundive construction in BP sounds Portuguese; the reverse sounds Brazilian.', null, [ACT.grammarBpEpContrast]),

  createContentItem('Domingo na família Silva', 'reading: a Brazilian Sunday', 'A typical Brazilian Sunday family lunch. Read aloud, identifying ter, gostar de, and family terms.', 'paragraph', 'Aos domingos, a família Silva almoça toda junta na casa da vovó Lurdes, no bairro do Brás em São Paulo. A vovó faz feijoada com arroz, couve, e farofa. Vêm a mãe, o pai, dois tios, três primos, e os avós. O João, o primo mais velho, traz cerveja. A tia Marisa sempre traz brigadeiros para a sobremesa. Depois do almoço, os adultos jogam dominó e as crianças veem o jogo do Corinthians na TV. Toda família adora esses domingos!', 'Translation: "On Sundays, the Silva family eats lunch all together at Grandma Lurdes\'s house, in the Brás neighborhood of São Paulo. Grandma makes feijoada with rice, collard greens, and farofa. The mother, father, two uncles, three cousins, and grandparents come. João, the oldest cousin, brings beer. Aunt Marisa always brings brigadeiros for dessert. After lunch, the adults play dominoes and the kids watch the Corinthians game on TV. The whole family loves these Sundays!"', [{ target: 'aos domingos', note: 'plural article + "Sundays"; means "every Sunday"' }, { target: 'casa da vovó', note: 'da = de + a; "the grandma\'s house"' }, { target: 'vêm a mãe, o pai', note: 'verb VIR (to come) 3pl "vêm"; circumflex on ê' }, { target: 'farofa', note: 'toasted cassava flour side dish; BP staple' }, { target: 'sobremesa', note: 'dessert; literally "over-table"' }], [ACT.reading]),

  createContentItem('BP vs EP: dois estudantes', 'dialogue: cross-cultural', 'A São Paulo USP student and a Lisbon exchange student compare home life.', 'conversation', 'Sofia (BP): Oi, Joana, tudo bem? De onde você é?\nJoana (EP): Olá, Sofia. Eu sou de Lisboa.\nSofia: Que legal! É bem diferente daqui?\nJoana: Sim, bastante! Em Lisboa, eu tomo o pequeno-almoço com café e pão. E vocês?\nSofia: Aqui a gente toma café da manhã com pão na chapa, café com leite, e às vezes açaí.\nJoana: Açaí? Não conhecia! E o almoço de domingo, como é?\nSofia: Geralmente feijoada com a família toda. E em Portugal?\nJoana: Cozido à portuguesa, também em família. Mas o nosso é mais simples — carne, vegetais, e arroz.\nSofia: Que delícia! Um dia eu provo.', 'Demonstrates BP-EP lexicon, gostar de, ter, family terms.', [{ target: 'tomo o pequeno-almoço', note: 'EP: with article "o" before meal name' }, { target: 'pão na chapa', note: 'BP: bread grilled on hot plate; padaria staple' }, { target: 'açaí', note: 'Amazonian berry; recently introduced to EP markets' }, { target: 'cozido à portuguesa', note: 'EP stew with multiple meats and vegetables' }, { target: 'Que delícia!', note: 'BP "How delicious!" — common reaction expression' }], [ACT.listening]),

  createContentItem('Modelo de descrição familiar', 'family writing template', '8-sentence template for describing your family.', 'sentence', 'Minha família é [grande/pequena/média]. Tenho [N] irmãos e [N] irmãs. Meus pais se chamam [nome do pai] e [nome da mãe]. Meu pai é [profissão] e minha mãe é [profissão]. Eu gosto muito de [atividade/comida]. Aos domingos a gente [atividade familiar]. A minha família mora em [lugar]. Eu sinto saudades quando estou longe.', 'Each blank uses gender-marked vocabulary and ter/gostar.', null, [ACT.writing]),
  createContentItem('Exercício', 'writing exercise', 'Write 6-8 sentences about your family with 5+ family terms and ter/gostar de.', 'sentence', 'Exemplo: Minha família é grande. Tenho dois irmãos mais velhos e uma irmã mais nova. Meu pai é médico e minha mãe é professora. Eu gosto muito de cozinhar com minha mãe. Aos domingos a gente almoça toda junta. Moramos em Boston. Sinto saudades quando estou no Brasil.', '"Sinto saudades" = "I miss"; "saudade" is the famously untranslatable Portuguese word.', null, [ACT.writing]),

  createContentItem('Almoço de domingo', 'Sunday lunch institution', 'In both Brazil and Portugal, Sunday lunch is the family centerpiece — often the only time the extended family gathers each week. BP signature dishes: feijoada (Rio), churrasco (south), moqueca (Bahia), arroz com galinha (Minas). EP signature: cozido à portuguesa, arroz de marisco, bacalhau à brás.', 'word', 'almoço de domingo · feijoada · cozido', 'Skipping Sunday lunch without strong reason is socially noticed.', null, [ACT.culture]),
  createContentItem('Saudade', 'untranslatable saudade', 'Saudade is the Portuguese word famously without exact English equivalent: a melancholic longing for something/someone absent, with affection. Used for: missing a person, longing for a place, nostalgia for a past time. Central to fado music, BP music, Portuguese poetry.', 'word', 'Sinto saudades dos meus pais.', 'Common expressions: "morro de saudade" (I am dying from longing), "matar a saudade" (to satisfy the longing by seeing again).', null, [ACT.culture]),
  createContentItem('Padrinhos brasileiros', 'BP godparent role', 'In BP Catholic and even secular tradition, padrinhos (godparents) play active life role: equivalent to extra aunts/uncles. Brazilian weddings feature multiple padrinhos standing alongside the couple. Child birthday parties prominently include them.', 'word', 'padrinho · madrinha · afilhado · afilhada', 'EP also has padrinhos but with less prominent ongoing role.', null, [ACT.culture]),
  createContentItem('Tutear ou não tutear?', 'BP-EP "you" politics revisited', 'When a Brazilian visits Portugal, the safest you-form is to skip pronouns and use third-person verbs ("Como está?" with no pronoun). When a Portuguese visits Brazil, "você" works for all but the most formal contexts.', 'word', 'BP visitor in EP: "Como está?" (no pronoun)\nEP visitor in BP: "Você é estudante?" (você safe)', 'A common social anxiety; the no-pronoun strategy is universally polite.', null, [ACT.culture]),

  createContentItem('Tarefa: comparando vidas', 'task: cross-cultural compare', 'Roleplay with the AI tutor playing a paulistano (BP) or lisboeta (EP, your choice). Compare 4 aspects of daily life: family, food, leisure, language differences.', 'conversation', '[Café no campus]\nColega: De onde você é?\nVocê: [responder + perguntar sobre o colega]\nColega: [responder]\nVocê: [perguntar sobre família]\nColega: [responder + perguntar]\nVocê: [comparar família]\nColega: [transição para comida]\nVocê: [comparar comidas]\nColega: O que você gosta de fazer no fim de semana?\nVocê: [responder + perguntar de volta]', '10-turn exchange covering all unit content.', [{ target: 'responder origem', note: 'Sou de [cidade], [país]' }, { target: 'perguntar família', note: 'Quantos irmãos você tem?' }, { target: 'comparar família', note: 'Eu tenho X irmãos / família grande/pequena' }, { target: 'comparar comida', note: 'No meu país a gente come… mas aqui parece que…' }, { target: 'lazer', note: 'Eu gosto de [atividade]; nos fins de semana costumo…' }], [ACT.task]),
];

module.exports = {
  title: 'Level 1 · Unit 5: Vida no mundo lusófono — Life in the Portuguese-Speaking World',
  category: 'culture-family', difficulty: 'beginner',
  targetLang: 'pt', nativeLang: 'en', track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describe-family', label: 'Describing family', goal: 'Use ter + family-relationship vocabulary with correct possessives and gender.' },
    { id: 'express-likes', label: 'Expressing likes', goal: 'Use gostar DE + noun/verb with obligatory preposition and contraction.' },
    { id: 'bp-ep-contrast', label: 'BP vs EP awareness', goal: 'Identify 5+ BP-EP lexical differences and the gerund-vs-infinitive split.' },
    { id: 'cross-cultural', label: 'Cross-cultural compare', goal: 'Make a 3-turn comparison of food/family/leisure between your culture and Brazil.' },
  ],
  relatedPools: ['topic-family', 'topic-food', 'topic-culture'],
  content,
};
