// Level 1 Unit 3 — Locations & Places in the City (Portuguese, BP primary)
// Functions: stating where you are, asking where something is, giving simple directions,
// distinguishing ser vs estar for locations, using common prepositions.

const createContentItem = (target, pronunciation, note, type = 'word', example = '', exampleNote = '', breakdown = null, activityIds = []) => ({
  type, activityIds, targetText: target, romanization: pronunciation, nativeText: note, pronunciation,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'pt-l1u3-orientation', pronunciation: 'pt-l1u3-pronunciation',
  vocabPlaces: 'pt-l1u3-vocab-places', vocabPrepositions: 'pt-l1u3-vocab-prepositions',
  grammarEstar: 'pt-l1u3-grammar-estar', grammarSerEstarContrast: 'pt-l1u3-grammar-ser-estar-contrast',
  grammarLocations: 'pt-l1u3-grammar-locations', reading: 'pt-l1u3-reading',
  listening: 'pt-l1u3-listening', writing: 'pt-l1u3-writing',
  culture: 'pt-l1u3-culture', task: 'pt-l1u3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do', goals: ['Name 20 city places in São Paulo (banco, padaria, farmácia, estação de metrô, etc.) with correct article and gender.', 'Use ESTAR (not ser) to state the temporary location of people and movable things: "Eu estou na biblioteca".', 'Distinguish ser-for-fixed-location (geography, identity-of-place) from estar-for-current-position (where someone happens to be now).'], task: 'Picture yourself navigating São Paulo for the first time — Avenida Paulista, Liberdade, the metro. By the end of this lesson you can describe where you are and ask for any place around you.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Sound traps', goals: ['Pronounce "estação" /es.taˈsɐ̃w̃/ with full nasal -ão diphthong; common word that beginners denasalize.', 'Apply BP palatalization in "padaria de bairro" (de → /dʒi/) and "metrô" (closed ô).', 'Handle the BP h-sound of initial r in "restaurante" /hes.taw.ˈɾɐ̃.tʃi/ — five sound rules in one word.'], task: 'Read each example, mark stress and palatalization, and identify the BP-EP differences.' },
  { id: ACT.vocabPlaces, section: 'Vocabulary I', title: 'Places in the city', goals: ['Memorize 20 city places with correct article and gender.', 'Recognize Brazilian-specific places (a padaria, a farmácia 24h, o shopping, o cartório) vs European-specific (o talho, o quiosque, o talho is the EP-only term for butcher).'], task: 'List five places you go to in a typical week, each with article and gender.' },
  { id: ACT.vocabPrepositions, section: 'Vocabulary II', title: 'Location prepositions', goals: ['Use 10 location prepositions (em, ao lado de, perto de, longe de, em frente a, atrás de, dentro de, fora de, sobre, entre).', 'Apply article contractions automatically: em + a = na, em + o = no, de + a = da, de + o = do.'], task: 'Describe the location of three places in your neighborhood using different prepositions.' },
  { id: ACT.grammarEstar, section: 'Grammar I', title: 'ESTAR present indicative', goals: ['Conjugate ESTAR: eu estou, você está, ele/ela está, nós estamos, vocês estão, eles/elas estão.', 'Use ESTAR for TEMPORARY states, CURRENT POSITION, and movable-thing LOCATIONS.'], task: 'Write six estar sentences locating yourself, family, and objects.' },
  { id: ACT.grammarSerEstarContrast, section: 'Grammar II', title: 'SER vs ESTAR — location split', goals: ['Use SER for IDENTITY-of-place (where geographical things permanently are): "A USP é em São Paulo" (USP is located in SP, permanently).', 'Use ESTAR for CURRENT POSITION (where movable people/things are right now): "Eu estou na USP" (I happen to be at USP now).', 'Apply the rule: cities, countries, buildings = SER for their permanent location; people, cars, mobile things = ESTAR for current position.'], task: 'Choose ser or estar correctly in ten location sentences.' },
  { id: ACT.grammarLocations, section: 'Grammar III', title: 'Asking and giving locations', goals: ['Ask "Onde está/é + thing?" with the right verb choice.', 'Give simple directions using "perto de", "ao lado de", "em frente a", "entre".'], task: 'Run a 4-turn location exchange asking and giving directions to three places.' },
  { id: ACT.reading, section: 'Reading', title: 'O meu bairro em São Paulo', goals: ['Read a paragraph describing a São Paulo neighborhood with all locations using correct ser/estar choice.', 'Answer five comprehension questions.'], task: 'Read aloud and answer questions.' },
  { id: ACT.listening, section: 'Listening', title: 'Asking for directions in Liberdade', goals: ['Follow a 6-turn dialogue between a tourist and a Liberdade shop owner.', 'Reproduce it with different destinations.'], task: 'Listen, then perform with a new destination swapped in.' },
  { id: ACT.writing, section: 'Writing', title: 'Describe a place you know', goals: ['Write 5-7 sentences describing a place you know well, using location vocabulary and prepositions.'], task: 'Write a paragraph about your neighborhood, hometown, or campus.' },
  { id: ACT.culture, section: 'Culture', title: 'São Paulo, Liberdade, Paulista', goals: ['Know the major São Paulo landmarks: Avenida Paulista, Liberdade, Vila Madalena, Cidade Universitária.', 'Understand Brazilian neighborhood culture: padaria as social hub, bairro identity, the 24h farmácia.'], task: 'Pick one SP landmark and describe what makes it culturally significant.' },
  { id: ACT.task, section: 'Task', title: 'Get to your USP class', goals: ['Run a 6-turn navigation conversation asking your way from a metro station to a USP building.'], task: 'Roleplay the journey with the AI tutor.' },
];

const content = [
  createContentItem('Cidade de São Paulo', 'CIDADE de São Paulo', 'Picture your first weekend in São Paulo. You need a padaria for breakfast, a farmácia for an aspirin, the metro to get to USP, a banco to exchange money, and a restaurante for dinner. Five everyday needs, five everyday places.', 'word', 'padaria · farmácia · metrô · banco · restaurante', 'These five micro-destinations map to the five micro-skills of this lesson.', null, [ACT.orientation]),
  createContentItem('ser vs estar — visão rápida', 'ser vs estar — quick view', 'Big rule of this unit: use SER for places that ARE somewhere permanently (a USP é em São Paulo). Use ESTAR for people/things that are CURRENTLY somewhere (eu estou na USP). The distinction is one of the most-tested grammar points in any Portuguese course.', 'word', 'Ser-place (fixed) vs Estar-position (current)', 'You will revisit ser/estar at Level 3 — for now lock in just the location use.', null, [ACT.orientation]),
  createContentItem('USP — Cidade Universitária', 'USP — university city', 'The USP main campus, Cidade Universitária, is in the Butantã district of São Paulo, on the west side of the Pinheiros river. Take the metro Linha 4 Amarela to Butantã station, then walk or take a bus to the campus.', 'word', 'Butantã, Zona Oeste, São Paulo, SP, Brasil', 'Concrete location grounds every example in this lesson.', null, [ACT.orientation]),

  createContentItem('estação', 'estação /es.taˈsɐ̃w̃/', 'Train or metro station — feminine. Note the nasal -ão diphthong at the end. Common in any city travel sentence: "estação de metrô", "estação rodoviária" (bus station), "estação de trem".', 'word', 'A estação Butantã fica perto da USP.', 'BP "fica" used to mean "is located"; alternate to "é/está" for permanent places.', null, [ACT.pronunciation]),
  createContentItem('metrô (BP) / metro (EP)', 'BP /meˈtɾo/ EP /ˈmɛ.tɾu/', 'Subway/metro. BP: stressed last syllable WITH circumflex (metrô — "me-TRÔ"). EP: stressed first syllable WITHOUT accent (metro — "MÉ-tru"). One of the most visible spelling+stress BP/EP differences.', 'word', 'BP: Eu pego o metrô. EP: Eu apanho o metro.', 'EP uses "apanhar" (to catch) for transport; BP uses "pegar" (to grab/take).', null, [ACT.pronunciation]),
  createContentItem('restaurante', 'restaurante /hes.taw.ˈɾɐ̃.tʃi/ (BP)', 'Restaurant — masculine. Pronunciation packs FIVE rules: initial r = /h/ in BP (uvular fricative), au diphthong, nasal -an- /ɐ̃/, palatalized final -te /tʃi/, BP final -e → /i/.', 'word', 'O restaurante é na avenida principal.', 'EP pronunciation: /ʁɨʃ.taw.ˈɾɐ̃t/ — trilled initial r, /ʃ/ for the s, dropped final e.', null, [ACT.pronunciation]),
  createContentItem('padaria', 'padaria /pa.daˈɾi.a/', 'Bakery — feminine. Five-syllable word with stress on -RI-. Note: in BP "padaria" also doubles as a "café-snack-corner-grocer" hybrid — much more than just a bread store.', 'word', 'A padaria abre às 6 da manhã.', 'BP padarias are open daily, serve coffee, light meals, and often basic groceries.', null, [ACT.pronunciation]),

  createContentItem('a padaria', 'a padaria', 'Bakery — but in Brazil, much more: bread, coffee, light meals, basic groceries. The neighborhood social hub. Open from before dawn until late evening, often 7 days a week.', 'word', 'Vou à padaria comprar pão fresquinho.', 'EP equivalents: "a pastelaria" for sweets, "a padaria" for bread specifically.', null, [ACT.vocabPlaces]),
  createContentItem('a farmácia', 'a farmácia /a faʁˈma.sia/', 'Pharmacy/drugstore — feminine. In Brazil, often 24h, sells over-the-counter meds without prescription. "Farmácia de plantão" = the rotating-duty pharmacy open at night.', 'word', 'A farmácia está aberta 24 horas.', 'BP/EP same word.', null, [ACT.vocabPlaces]),
  createContentItem('o banco', 'o banco /u ˈbɐ̃.ku/', 'Bank — masculine. Also means "bench" (homophone). Nasal -an- /ɐ̃/ in first syllable.', 'word', 'O Banco do Brasil é o maior banco público.', 'Brazilian banking hours typically Mon-Fri 10am-4pm; ATMs (caixas eletrônicos) accessible longer.', null, [ACT.vocabPlaces]),
  createContentItem('o supermercado', 'o supermercado /u su.peʁ.meʁˈka.du/', 'Supermarket — masculine. Big chains in Brazil: Pão de Açúcar, Carrefour, Extra, Assaí.', 'word', 'O supermercado fica perto da minha casa.', 'BP "ficar" used for "to be located"; EP uses "estar" or "ficar" too.', null, [ACT.vocabPlaces]),
  createContentItem('o shopping', 'o shopping /u ˈʃo.pĩ/', 'Shopping mall — masculine. Borrowed from English. Full BP form "shopping center" abbreviated to just "shopping". Note pronunciation has nasal -ing /ĩ/.', 'word', 'O shopping fica no centro da cidade.', 'EP equivalent: "centro comercial" (more standard than BP "shopping").', null, [ACT.vocabPlaces]),
  createContentItem('a feira', 'a feira /a ˈfej.ɾa/', 'Open-air market — feminine. Brazilian weekly tradition: each neighborhood has its feira day (segunda, terça, etc.) when streets fill with fruit, vegetable, fish, and meat stalls.', 'word', 'A feira de domingo é a melhor do bairro.', 'A core piece of Brazilian neighborhood life; "ir à feira" = weekly Saturday/Sunday outing.', null, [ACT.vocabPlaces]),
  createContentItem('a biblioteca', 'a biblioteca /a bibliuˈtɛ.ka/', 'Library — feminine. Open ê /ɛ/ stressed. USP\'s "biblioteca brasiliana" is one of the most important Lusophone collections in the world.', 'word', 'Estou estudando na biblioteca da USP.', 'University libraries open to students with a USP card; longer hours during finals.', null, [ACT.vocabPlaces]),
  createContentItem('a universidade', 'a universidade /a u.ni.veʁ.siˈda.dʒi/', 'University — feminine. Five-syllable word with BP palatalization in final -de → /dʒi/. Major Brazilian universities: USP, UNICAMP, UFRJ, UFMG.', 'word', 'A universidade fica na zona oeste.', 'BP "fica" + locative for permanent location.', null, [ACT.vocabPlaces]),
  createContentItem('a escola', 'a escola /a esˈkɔ.la/', 'School (primary/secondary) — feminine. Open ó /ɔ/ stressed. BP "escola" = K-12; "universidade" or "faculdade" = university.', 'word', 'A escola da minha irmã é particular.', '"Particular" = private; "pública" = public.', null, [ACT.vocabPlaces]),
  createContentItem('a faculdade', 'a faculdade /a fa.kuwˈda.dʒi/', 'College / specific school within a university — feminine. "Faculdade de Engenharia da USP" = School of Engineering. Also used colloquially for "university" in casual BP speech.', 'word', 'Estudo na faculdade de letras.', 'Each USP "faculdade" is essentially a school: Letras, Engenharia, Direito, Medicina.', null, [ACT.vocabPlaces]),
  createContentItem('o hospital', 'o hospital /u os.piˈtaw/', 'Hospital — masculine. Silent h. BP velar l at end /aw/. The main USP hospital is Hospital das Clínicas (HC).', 'word', 'O Hospital das Clínicas é o maior do Brasil.', 'HC-USP is the biggest teaching hospital in Latin America.', null, [ACT.vocabPlaces]),
  createContentItem('a estação de metrô', 'a estação de metrô', 'Metro/subway station — feminine "estação". São Paulo metro: Linhas 1 (azul), 2 (verde), 3 (vermelha), 4 (amarela), 5 (lilás), 15 (prata).', 'word', 'A estação Butantã fica perto da USP.', 'USP closest station: Butantã (Linha 4 amarela).', null, [ACT.vocabPlaces]),
  createContentItem('o aeroporto', 'o aeroporto /u aeɾoˈpoʁ.tu/', 'Airport — masculine. Closed ô stressed in -porto. São Paulo has two main airports: Guarulhos (GRU, international) and Congonhas (CGH, domestic).', 'word', 'O aeroporto fica longe do centro.', 'GRU is one of the largest airports in South America.', null, [ACT.vocabPlaces]),
  createContentItem('a rodoviária', 'a rodoviária /a ho.do.viˈa.ɾia/', 'Bus station (long-distance) — feminine. From "rodovia" (highway). SP main bus station: Terminal Tietê, third-largest bus station in the world.', 'word', 'A rodoviária do Tietê é enorme.', 'Long-distance buses are a primary travel mode in Brazil due to size of country.', null, [ACT.vocabPlaces]),
  createContentItem('a praça', 'a praça /a ˈpɾa.sa/', 'Public square — feminine. Brazilian neighborhoods organize around praças; common meeting points. Praça da Sé = SP\'s historic central square.', 'word', 'A praça da Sé fica no centro.', 'Many "praças" host weekend feiras or festivals.', null, [ACT.vocabPlaces]),
  createContentItem('o parque', 'o parque /u ˈpaʁ.ki/', 'Park — masculine. SP\'s big parks: Ibirapuera (the Central Park of São Paulo), Parque Villa-Lobos, Parque da Aclimação.', 'word', 'Vou correr no Parque Ibirapuera.', 'Ibirapuera is a major weekend destination for paulistanos.', null, [ACT.vocabPlaces]),
  createContentItem('a igreja', 'a igreja /a iˈgɾe.ʒa/', 'Church — feminine. Soft j = /ʒ/. Catholicism still dominant in Brazil (60%); also significant Protestant (evangelical) population.', 'word', 'A igreja do meu bairro é da época colonial.', 'Many BP cities have colonial-era churches as historic landmarks.', null, [ACT.vocabPlaces]),
  createContentItem('o museu', 'o museu /u muˈzew/', 'Museum — masculine. Diphthong -eu /ew/. SP top museums: MASP (Museu de Arte de São Paulo), Pinacoteca, MAC-USP.', 'word', 'O MASP fica na Avenida Paulista.', 'MASP\'s elevated red-pillar architecture is an SP icon.', null, [ACT.vocabPlaces]),
  createContentItem('o cinema', 'o cinema /u siˈne.ma/', 'Cinema — masculine despite -a ending (Greek neuter origin, like "problema"). Multiplexes common in shoppings.', 'word', 'O cinema do shopping tem 12 salas.', 'BP movie tickets cheaper than US/EU; matinée discounts common.', null, [ACT.vocabPlaces]),
  createContentItem('o cartório', 'o cartório /u kaʁˈtɔ.ɾiu/', 'Notary office — masculine. Open ó /ɔ/ stressed. Brazilian bureaucracy lives at the cartório: birth certificates, real estate registration, document authentication.', 'word', 'Preciso ir ao cartório para autenticar um documento.', 'A particularly Brazilian institution; EP uses "notário" / "conservatória" with different scopes.', null, [ACT.vocabPlaces]),

  createContentItem('em', 'em /ẽj̃/', 'Universal location preposition — "in / on / at". Contracts with definite articles: em + o = no, em + a = na. Most-used preposition in location sentences.', 'sentence', 'em São Paulo, no Brasil, na USP, na sala', '"em" + city = no contraction. "em" + country/region usually contracts via the article.', [{ target: 'em + city (no art.)', note: 'em São Paulo, em Lisboa, em Paris' }, { target: 'em + o = no', note: 'no Brasil, no parque' }, { target: 'em + a = na', note: 'na USP, na padaria' }, { target: 'em + os/as', note: 'nos parques, nas praças' }], [ACT.vocabPrepositions]),
  createContentItem('ao lado de', 'ao lado de', '"Next to / beside". Combines "ao" (a + o) + "lado" + "de". Tracks article contractions: ao lado da escola, ao lado do banco.', 'sentence', 'A farmácia fica ao lado da padaria.', 'Spatial relations: ao lado (beside), em frente (across from), atrás (behind).', null, [ACT.vocabPrepositions]),
  createContentItem('perto de', 'perto de', '"Near / close to". Article-contracts: perto da, perto do. Antonym: longe de.', 'sentence', 'A USP fica perto da estação Butantã.', 'Adverbial pair: perto/longe.', null, [ACT.vocabPrepositions]),
  createContentItem('longe de', 'longe de', '"Far from". Mirror of perto de.', 'sentence', 'A casa dela é longe do centro.', 'Use with "muito longe / muito perto" for emphasis.', null, [ACT.vocabPrepositions]),
  createContentItem('em frente a / a / de', 'em frente a / em frente de', '"In front of / across from". BP allows both "em frente a" and "em frente de"; EP prefers "em frente de". Useful for street-corner directions.', 'sentence', 'O banco fica em frente à praça.', 'Crase "à" appears here: "a + a praça" = à praça.', null, [ACT.vocabPrepositions]),
  createContentItem('atrás de', 'atrás de', '"Behind". Article-contracts: atrás da, atrás do.', 'sentence', 'O parque fica atrás do museu.', 'Antonym: na frente de.', null, [ACT.vocabPrepositions]),
  createContentItem('dentro de', 'dentro de', '"Inside". Often used for enclosed spaces or containers.', 'sentence', 'Os livros estão dentro da mochila.', 'Antonym: fora de.', null, [ACT.vocabPrepositions]),
  createContentItem('fora de', 'fora de', '"Outside (of)". Pair with dentro de.', 'sentence', 'Vamos comer fora hoje.', 'Idiomatic: "comer fora" = eat at a restaurant (not "outside").', null, [ACT.vocabPrepositions]),
  createContentItem('sobre / em cima de', 'sobre / em cima de', '"On top of / on". "Sobre" is more formal/written; "em cima de" is the everyday spoken BP form.', 'sentence', 'O livro está sobre a mesa. / O livro está em cima da mesa.', 'Both fully correct; "em cima de" sounds more natural in casual speech.', null, [ACT.vocabPrepositions]),
  createContentItem('entre', 'entre /ˈẽ.tɾi/', '"Between" (two things) or "among" (three or more). Nasal vowel ẽ. Does NOT take article contractions.', 'sentence', 'A farmácia fica entre a padaria e o banco.', 'Same word for "between" and "among" in Portuguese.', null, [ACT.vocabPrepositions]),

  createContentItem('estar — present', 'estar — present indicative', 'ESTAR conjugates: eu ESTOU, você/ele/ela ESTÁ, nós ESTAMOS, vocês/eles/elas ESTÃO. Used for TEMPORARY states, CURRENT positions, ongoing actions, and weather.', 'sentence', 'Eu estou na USP. Você está em casa? Nós estamos cansados.', 'Standard "está" vs "estás" (EP tu form): EP "tu estás" with -s; BP standard avoids tu form.', [{ target: 'eu estou', note: '1st sg; the form you say most for "I am [somewhere]"' }, { target: 'você/ele/ela está', note: '2nd/3rd sg; works for any subject in BP default' }, { target: 'nós estamos', note: '1st pl' }, { target: 'vocês/eles/elas estão', note: '2nd/3rd pl with full nasal -ão' }], [ACT.grammarEstar]),
  createContentItem('estar — usos', 'uses of estar', 'Six main uses of ESTAR: (1) current LOCATION of movable things/people, (2) TEMPORARY states (estar cansado), (3) WEATHER (está chovendo), (4) PROGRESSIVE aspect (estou estudando), (5) HEALTH (estou bem), (6) MOOD (estou triste).', 'sentence', 'Eu estou em casa. Estou cansada. Está chovendo. Estou estudando.', 'These six are the high-frequency uses; you will meet a few more (e.g., date) later.', null, [ACT.grammarEstar]),

  createContentItem('Ser-place vs Estar-position', 'the location split', 'KEY RULE: SER for places that ARE somewhere permanently (geographic identity); ESTAR for movable people/things currently somewhere (current position). USP é em São Paulo (USP is permanently in SP) vs Eu estou na USP (I happen to be at USP now). The single most-tested grammar point.', 'sentence', 'A USP é em São Paulo. (permanent geographic fact)\nEu estou na USP. (current position)', 'BP often uses "fica" (from ficar) instead of ser for permanent location: "A USP fica em São Paulo" — fully natural, even slightly more common in speech.', [{ target: 'SER + permanent place', note: 'cities, buildings, geography: "A USP é em SP", "O Brasil é na América do Sul"' }, { target: 'FICAR + permanent place', note: 'BP-preferred everyday alternative: "A USP fica em SP"' }, { target: 'ESTAR + current position', note: 'movable people/things: "Eu estou na USP", "O livro está na mesa"' }], [ACT.grammarSerEstarContrast]),
  createContentItem('Exceptions', 'edge cases', 'Some places allow either ser or estar: events (a reunião É às 10 [scheduled] vs a reunião ESTÁ na sala 5 [currently in room 5]). Memorize the broad rule and revisit edge cases in Level 2.', 'sentence', 'A festa é no sábado (event scheduled). A festa está acontecendo agora (event ongoing).', 'Use SER for SCHEDULED events; ESTAR for events HAPPENING NOW.', null, [ACT.grammarSerEstarContrast]),

  createContentItem('Onde + ser/estar?', 'where-questions', 'Two question patterns: "Onde é + permanent place?" and "Onde está + movable thing?". "Onde é a USP?" (Where is USP located? — permanent) vs "Onde está o professor?" (Where is the professor now? — current).', 'sentence', 'Onde é a USP? / Onde está o meu lápis?', 'Wrong-verb choice sounds funny: "Onde está a USP?" implies USP can move — odd.', null, [ACT.grammarLocations]),
  createContentItem('Como chego a/em…?', 'asking how to get somewhere', 'Standard direction-asking pattern: "Como (eu) chego a/à/em + place?" or "Como (eu) faço para chegar a/à + place?". Use crase à for feminine destinations: à USP, à praça.', 'sentence', 'Como eu chego à estação Butantã?', 'Verb "chegar" = "to arrive/reach"; pairs with preposition "a".', null, [ACT.grammarLocations]),
  createContentItem('Vire / siga / pegue', 'direction commands', 'Standard BP direction verbs in imperative: VIRE (turn), SIGA (continue/follow), PEGUE (take). "Vire à esquerda, siga em frente, pegue a próxima rua".', 'sentence', 'Vire à direita na próxima rua, siga em frente por dois quarteirões.', '"À direita" / "à esquerda" — crase obligatory because article "a" precedes feminine noun.', [{ target: 'à direita', note: 'to the right; crase obligatory' }, { target: 'à esquerda', note: 'to the left' }, { target: 'em frente', note: 'straight ahead' }, { target: 'quarteirão', note: 'block (city block); often shortened to "quadra" in BP' }], [ACT.grammarLocations]),

  createContentItem('Meu bairro em São Paulo', 'reading: my SP neighborhood', 'A description of a typical paulistano neighborhood near USP. Read aloud applying ser/estar correctly.', 'paragraph', 'Eu moro no Butantã, um bairro tranquilo na zona oeste de São Paulo. A minha casa fica perto da estação de metrô. Em frente à estação há uma padaria onde eu tomo café da manhã todo dia. Ao lado da padaria, há uma farmácia 24 horas, muito útil. A USP está a 10 minutos a pé da minha casa. Aos sábados, a feira do bairro acontece na praça da igreja. Eu adoro o meu bairro!', 'Translation: "I live in Butantã, a quiet neighborhood in the west zone of São Paulo. My house is near the metro station. Across from the station there is a bakery where I have breakfast every day. Next to the bakery, there is a 24-hour pharmacy, very useful. USP is 10 minutes on foot from my house. On Saturdays, the neighborhood market happens in the church square. I love my neighborhood!"', [{ target: 'fica perto', note: 'BP "ficar" for permanent location' }, { target: 'há uma padaria', note: '"há" = "there is/are"; from haver, used impersonally' }, { target: 'a 10 minutos a pé', note: '"10 minutes on foot"; "a pé" = walking' }, { target: 'todo dia', note: 'BP palatalization: todo + dia → "TÔ-du DJI-a"' }, { target: 'feira do bairro', note: 'weekend open-air market; BP neighborhood tradition' }], [ACT.reading]),
  createContentItem('Perguntas', 'comprehension questions', 'Five questions about the paragraph.', 'sentence', 'Q1: Onde fica a casa do narrador? Q2: O que há em frente à estação? Q3: Quanto tempo a USP fica da casa? Q4: Quando há feira? Q5: Onde acontece a feira?', 'Practice ser/estar/há in answers.', [{ target: 'A1: Fica no Butantã.', note: 'short locative' }, { target: 'A2: Uma padaria.', note: 'short noun answer' }, { target: 'A3: A 10 minutos a pé.', note: 'distance answer' }, { target: 'A4: Aos sábados.', note: 'time answer with "aos"' }, { target: 'A5: Na praça da igreja.', note: 'locative with "em + a = na"' }], [ACT.reading]),

  createContentItem('Pedindo informação na Liberdade', 'dialogue: asking directions', 'Tourist asking a Liberdade shop owner for directions to a metro station. Standard polite-but-warm BP register.', 'conversation', 'Turista: Com licença, senhor. Onde fica a estação de metrô?\nLojista: A Liberdade fica a duas quadras daqui, virando à esquerda.\nTurista: Ah, é longe?\nLojista: Não, fica bem perto. Cinco minutos a pé.\nTurista: E o restaurante japonês "Sushi Lar", o senhor conhece?\nLojista: Conheço, sim. Fica em frente à estação, do lado direito.\nTurista: Muito obrigada!\nLojista: Imagina, qualquer coisa estou aqui.', 'Typical interaction in the Liberdade (SP\'s Japanese district).', [{ target: 'Com licença', note: 'polite opener for any request' }, { target: 'fica a duas quadras', note: '"quadra" = block; BP common in directions' }, { target: 'virando à esquerda', note: 'gerund of virar; "à esquerda" with crase' }, { target: 'conhece, sim', note: 'BP-typical "verb + sim" affirmation; replaces standalone "sim"' }, { target: 'Imagina', note: 'casual "no problem / don\'t mention it" — drops "imagine"\'s -e' }], [ACT.listening]),

  createContentItem('Modelo de descrição', 'writing template', 'Five-sentence template describing a place you know.', 'sentence', 'Eu moro em / estudo em [lugar]. [O lugar] fica em [região/cidade]. Perto da [meu lugar] há [3 lugares próximos]. Eu gosto muito de [lugar específico] porque [razão]. Aos [dia da semana], eu costumo ir a/à [lugar].', 'Five sentences covering: where you are, location, neighborhood places, favorite spot, routine.', null, [ACT.writing]),
  createContentItem('Exercício de escrita', 'writing exercise', 'Write 5-7 sentences describing your neighborhood or campus. Use 3 different prepositions, ser + estar each at least once.', 'sentence', 'Exemplo: Eu moro no centro de Boston. Meu apartamento fica perto da universidade. Ao lado do meu prédio há um café e uma livraria. Eu adoro o Boston Common porque é grande e bonito. Aos domingos, costumo ir a um restaurante coreano que fica em frente à praça.', 'Note: "costumar" + infinitive = "to usually do".', null, [ACT.writing]),

  createContentItem('Avenida Paulista', 'cultural icon', 'Avenida Paulista is SP\'s most iconic street: 2.8 km of skyscrapers, the MASP museum, Trianon park, financial centers, and weekend pedestrian closures. On Sundays the avenue closes to cars and fills with cyclists, musicians, and food carts.', 'word', 'Avenida Paulista, Bela Vista, São Paulo, SP.', 'A landmark every paulistano knows; comparable to NYC\'s Fifth Avenue but with weekend cultural life.', null, [ACT.culture]),
  createContentItem('Bairro Liberdade', 'Japanese district', 'Liberdade is São Paulo\'s historic Japanese neighborhood — the largest Japanese diaspora outside Japan. Asian restaurants, supermarkets (e.g., Casa Bueno), bookstores, the Sunday feira asiática. Also home to Korean, Chinese, and Vietnamese communities.', 'word', 'Liberdade, centro de São Paulo, SP.', 'Reflects Japan-Brazil migration history dating to 1908.', null, [ACT.culture]),
  createContentItem('A padaria como instituição', 'padaria culture', 'The Brazilian neighborhood padaria is far more than a bakery: morning coffee + pão na chapa, midday "executive lunch" plates, after-work drinks, basic groceries. Each bairro has its padaria as social hub. Many open at 5am and close near midnight, 7 days a week.', 'word', 'padaria de bairro · pão francês · café da manhã na padaria', 'EP equivalent narrower: a padaria sells bread; a pastelaria sells pastries/coffee; a café sells coffee+snacks.', null, [ACT.culture]),
  createContentItem('Cidade Universitária', 'USP campus', 'The USP main campus, "Cidade Universitária" (literally "University City"), occupies a vast area in the Butantã district. It includes faculties, residence halls, a hospital (HC-USP), the Reitoria (administration), several museums, sports facilities, and the Praça do Relógio (clock tower square, the cultural center).', 'word', 'Cidade Universitária, Butantã, SP — USP main campus.', 'Take metro Linha 4 to Butantã station, then bus 8012 or 8022 to reach the campus.', null, [ACT.culture]),

  createContentItem('Tarefa: chegar à USP', 'task: get to USP', 'Roleplay finding your way from the metro station Butantã to the USP Engineering building. The AI tutor plays a paulistano who has lived in the neighborhood for years.', 'conversation', '[Saída da estação Butantã, USP]\nVocê: [pedir informação educadamente]\nPaulistano: Você é estudante nova aqui?\nVocê: [confirmar + dizer o destino]\nPaulistano: A Politécnica? Fica longe daqui, uns 15 minutos a pé.\nVocê: [perguntar a direção]\nPaulistano: Saia da estação, vire à direita, siga em frente por uns 10 minutos até a Avenida Professor Mello Moraes.\nVocê: [agradecer + perguntar referência]\nPaulistano: Tem um prédio grande com letras POLI na fachada. Não tem como errar.', 'Six turns; use prepositions, ser/estar, polite request, thanks.', [{ target: 'pedir informação', note: 'Com licença, o senhor sabe onde fica a Politécnica?' }, { target: 'confirmar destino', note: 'Sim, sou nova. Estou indo para a Engenharia.' }, { target: 'perguntar a direção', note: 'Como eu chego lá?' }, { target: 'agradecer', note: 'Muito obrigada / Obrigada mesmo' }], [ACT.task]),
];

module.exports = {
  title: 'Level 1 · Unit 3: Onde estou? — Locations and Places',
  category: 'locations', difficulty: 'beginner',
  targetLang: 'pt', nativeLang: 'en', track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'state-location', label: 'Stating where you are', goal: 'Use ESTAR to give your current location with correct article contraction.' },
    { id: 'ask-where', label: 'Asking where something is', goal: 'Choose ser/estar/ficar based on whether the place is permanent or someone is currently there.' },
    { id: 'directions', label: 'Giving simple directions', goal: 'Use vire/siga/pegue + à direita/esquerda + em frente to navigate one block to the next.' },
    { id: 'neighborhood-describe', label: 'Describing a neighborhood', goal: 'Combine 3+ prepositions and 5+ place nouns in a paragraph about your bairro.' },
  ],
  relatedPools: ['topic-places', 'topic-city'],
  content,
};
