// Level 1 Unit 1 — Greetings & Self-Introduction (Tamil)
// Functions: greeting, introducing yourself, asking where someone is from,
// correcting a wrong assumption, farewells.
// This lesson is the canonical TEMPLATE for all Tamil thematic Level 1 lessons.
//
// All content is authored with Tamil script (target) + ISO-15919 transliteration
// (romanization) + English glosses (canonical source). The AI conversation tutor
// reads this curriculum and delivers it to each learner in their preferred
// native language at runtime — never assume a specific L1 in this file.
//
// Glosses follow the rich-gloss rule (AGENTS.md → "Gloss Richness"):
// every nativeText, exampleNative, and breakdown.native carries register,
// usage context, or contrast info — not a bare definition.

const createContentItem = (
  target,
  romanization,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization,
  nativeText: note,
  pronunciation: romanization,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'ta-l1u1-orientation',
  pronunciation: 'ta-l1u1-pronunciation',
  vocabularyGreetings: 'ta-l1u1-vocab-greetings',
  vocabularyPeople: 'ta-l1u1-vocab-people',
  grammarCopula: 'ta-l1u1-grammar-copula',
  grammarPronouns: 'ta-l1u1-grammar-pronouns',
  grammarNegation: 'ta-l1u1-grammar-negation',
  reading: 'ta-l1u1-reading',
  listening: 'ta-l1u1-listening',
  writing: 'ta-l1u1-writing',
  culture: 'ta-l1u1-culture',
  task: 'ta-l1u1-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Greet someone in Tamil and say goodbye in three registers (intimate, polite, formal) so you can match the situation.',
      'Introduce yourself with your name, place, and one role (student / teacher / engineer) using the patterns என் பெயர்… and நான்… ஆவேன்/ஆகிறேன்.',
      'Ask another person their name and where they are from, then respond using the right pronoun (நீ / நீங்கள் / தாங்கள்).',
    ],
    task: 'Picture your first day at Anna University in Chennai — you walk into a research lab and meet a visiting professor from Madurai. By the end of this lesson you should handle the whole exchange in Tamil without rehearsing each line.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in this lesson',
    goals: [
      'Apply the no-voicing rule in வணக்கம் vaṇakkam — the medial க is voiceless only because it is geminated (kk); without gemination it would be /g/.',
      'Distinguish the retroflex ண in வணக்கம் from the dental ந elsewhere — getting these mixed up changes Tamil into something else.',
      'Pronounce the final ழ in தமிழ் correctly: tongue curled far back, no contact — the litmus test for Tamil pronunciation.',
    ],
    task: 'Read each example aloud and identify whether voicing rule, retroflex, gemination, or ழ applies; then pronounce the spoken form.',
  },
  {
    id: ACT.vocabularyGreetings,
    section: 'Vocabulary I',
    title: 'Greetings, farewells, and first-meeting phrases',
    goals: [
      'Memorize 12 greetings and farewells across three registers, with the right phrase for each situation.',
      'Distinguish வணக்கம் vaṇakkam (formal/respectful — works everywhere) from informal hi/hello — using the wrong register signals the wrong relationship.',
    ],
    task: 'Say each phrase out loud three times with correct retroflex and gemination, then pair each one with the situation where you would use it.',
  },
  {
    id: ACT.vocabularyPeople,
    section: 'Vocabulary II',
    title: 'People, roles, and places',
    goals: [
      'Use the Tamil pronoun system correctly: நான் (I), நீ (you-intimate), நீங்கள் (you-familiar/plural/honorific), தாங்கள் (you-very-formal), அவன் (he-peer), அவள் (she-peer), அவர் (he/she-honorific), அது (it).',
      'State your role (மாணவன்/மாணவி/மாணவர் "student") and origin (place + -ஆர் / "from" structure) in a complete short sentence.',
    ],
    task: 'Say your own role and city using the என் பெயர்… நான் … ஆவேன் pattern, then describe one classmate using the third-person pronoun appropriate to their honor level.',
  },
  {
    id: ACT.grammarCopula,
    section: 'Grammar I',
    title: 'Tamil copula — three patterns + zero',
    goals: [
      'Use the present copula ஆகிறேன் / ஆகிறான் / ஆகிறாள் / ஆகிறார் — agreeing with person, number, gender, and honor. Unlike English "to be", Tamil verbs agree richly.',
      'Often DROP the copula entirely in present-tense identity statements: என் பெயர் ராஜா "(My name [is]) Raja" — Tamil can be copula-less when context is clear.',
      'Use இரு "to be located/exist" for location/existence (different verb from copula), and ஆகு "to become/be" for identification.',
    ],
    task: 'Write six sentences identifying yourself, your friend, and your role — drop the copula in three and use it explicitly in the other three.',
  },
  {
    id: ACT.grammarPronouns,
    section: 'Grammar II',
    title: 'The pronoun system — animacy + honor',
    goals: [
      'Use the THREE words for "you": நீ nī (intimate — close friends, younger siblings, children), நீங்கள் nīṅkaḷ (polite — familiar/plural/honorific), தாங்கள் tāṅkaḷ (very formal — elders, dignitaries, customers).',
      'Use third-person pronouns by animacy + honor: அவன் avaṉ (he, peer), அவள் avaḷ (she, peer), அவர் avar (he/she, honorific), அது atu (it, neutral); ivar / ivaḷ for proximal.',
      'Note the genitive form: என் eṉ (my), உன் uṉ (your-intimate), உங்கள் uṅkaḷ (your-polite), அவனது/அவனுடைய (his), etc.',
    ],
    task: 'Construct three pronoun sentences switching between nī / nīṅkaḷ / tāṅkaḷ based on three different addressees: friend, teacher, customer.',
  },
  {
    id: ACT.grammarNegation,
    section: 'Grammar III',
    title: 'Negation — இல்லை and the correction pattern',
    goals: [
      'Negate identity/location sentences with இல்லை illai ("not/no/not present") placed at the end: அது புத்தகம் இல்லை. ("That is not a book.")',
      'Distinguish identity negation (இல்லை at end) from existential absence (இல்லை as "absent/not here") from verbal negation (suffix -ā-tu added to verb stem).',
      'Apply the correction pattern: NOT-X, [BUT] Y — அது X இல்லை, அது Y. The "but" is implicit.',
    ],
    task: 'Imagine a classmate guesses your origin wrong; correct them in one polite sentence using NOT-X-Y.',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Read a self-introduction',
    goals: [
      'Read a short Tamil self-introduction paragraph aloud with correct retroflex, gemination, ழ, and rhythm.',
      'Answer comprehension questions about the speaker\'s name, place, role, and department using full short sentences.',
    ],
    task: 'Read the paragraph below aloud once, then answer four comprehension questions in complete short sentences.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'A first meeting',
    goals: [
      'Follow a 4-turn first-meeting dialogue and recognize register markers (nī vs nīṅkaḷ, given-name vs name+avarkaḷ honorific).',
      'Reproduce the dialogue with your own name and city, swapping in the relevant phrases naturally.',
    ],
    task: 'Read the polite dialogue along with the AI tutor first, then perform it again with your own information swapped in.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Write your own self-introduction',
    goals: [
      'Write 3–5 sentences in Tamil script covering greeting, name, place, role, and one extra fact.',
      'Use the copula or its drop appropriately so the writing demonstrates the verbless-identity pattern of Tamil.',
    ],
    task: 'Write your own self-introduction in 3–5 sentences using the model on the left, then read it aloud with correct retroflex, gemination, and ழ.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'Honor in pronouns, titles, and Tamil identity',
    goals: [
      'Use the appropriate "you" form for the relationship: nī to a child, nīṅkaḷ to a colleague, tāṅkaḷ to an elder or VIP — getting this wrong is a major social error.',
      'Address professionals by name + honorific suffix -avarkaḷ (-அவர்கள்): ராஜா அவர்கள் (Rājā avarkaḷ "Mr. Raja") in formal contexts, or by title + name (டாக்டர் X, பேராசிரியர் X).',
      'Understand Tamil cultural pride — language, Sangam literature heritage, Bharatanatyam, Carnatic music; reference Tamil Nadu (Chennai, Coimbatore, Madurai, Salem, Trichy) and the broader Tamil world (Sri Lanka, Singapore, Malaysia diaspora).',
    ],
    task: 'Decide how you would address (1) a classmate named Murugan, (2) a teacher named Lakshmi, (3) a senior professor named Subramanian — give the full Tamil form for each.',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'First day at Anna University — in Tamil',
    goals: [
      'Combine everything from this lesson into one continuous scene with no break between greeting, introduction, question, answer, correction, and farewell.',
      'Use the correct pronoun (nī vs nīṅkaḷ vs tāṅkaḷ) based on the relationship — switching mid-conversation signals a shift in relational distance.',
    ],
    task: 'Roleplay your first day at Anna University with the AI tutor playing a visiting professor from Madurai; aim for a 6-turn exchange in Tamil.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 1: வணக்கம் — Greetings and Self-Introduction',
  category: 'greetings',
  difficulty: 'beginner',
  targetLang: 'ta',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'greeting-someone', label: 'Greeting someone', goal: 'Open and close a brief encounter politely (வணக்கம் / போய் வருகிறேன்) and match the register to the relationship.' },
    { id: 'introducing-yourself', label: 'Introducing yourself', goal: 'Give your name, place, and one fact about yourself in two short sentences using என் பெயர்… and நான் … ஆகிறேன்.' },
    { id: 'asking-where-from', label: 'Asking where someone is from', goal: 'Ask நீங்கள் எங்கிருந்து வருகிறீர்கள்? / உங்கள் ஊர் என்ன? and respond naturally with city + ஆர்.' },
    { id: 'correcting-assumption', label: 'Correcting an assumption', goal: 'Use the X-illai, Y pattern to politely correct a wrong guess about your origin or role.' },
  ],
  relatedPools: ['topic-people', 'topic-society'],
  content: [
    // ──── Activity 1 — Orientation
    createContentItem(
      'பாட இலக்குகள்',
      'pāṭa ilakkukaḷ',
      'By the end of this lesson, you can greet someone in Tamil, give your name, say where you are from, ask the same back, and farewell — all in one short conversation without pausing to think.',
      'word',
      'Functional language: வணக்கம் சொல் (greet) · சுய அறிமுகம் cuya aṟimukam (introduce yourself) · ஊர் கேள் ūr kēḷ (ask origin) · மறு maṟu (negate/refute) · விடைபெறு viṭaipeṟu (farewell)',
      'These five micro-skills are the spine of every social encounter in Tamil — once they are automatic, every later lesson layers on top.',
      null,
      [ACT.orientation],
    ),
    createContentItem(
      'நிகழ்வு',
      'nikaḻvu',
      'You are at Anna University in Chennai on your first day and a visiting professor from Madurai turns to you in the lab. The whole encounter takes about 30 seconds and you will need every micro-skill from this lesson.',
      'word',
      'பேராசிரியர்: "வணக்கம்! என் பெயர் சுப்பிரமணியன். நீங்கள் எங்கிருந்து வருகிறீர்கள்?"',
      'A typical opener from a Tamil Nadu academic: polite வணக்கம் + name introduction + immediate origin question.',
      [
        { target: 'வணக்கம் vaṇakkam', note: 'standard formal-respectful all-purpose greeting; works for first meetings, elders, and most contexts' },
        { target: 'என் பெயர்… eṉ peyar…', note: 'self-introduction with the noun பெயர் ("name") and possessive என் ("my"); copula often dropped' },
        { target: 'எங்கிருந்து வருகிறீர்கள்? eṅkiruntu varukiṟīrkaḷ?', note: 'literal: "from-where are you coming?"; the standard origin question, polite plural form' },
      ],
      [ACT.orientation],
    ),
    createContentItem(
      'மூன்று மரியாதை நிலைகள்',
      'mūṉṟu mariyātai nilaikaḷ',
      'Tamil distinguishes three rough politeness registers. Intimate (close friends, children): ஹாய் / நீ / பை. Polite/familiar (peers, colleagues, plural): வணக்கம் / நீங்கள் / விடைபெறுகிறேன். Very formal (elders, dignitaries, customers): வணக்கம் / தாங்கள் / போய் வருகிறேன் ஐயா/அம்மா.',
      'word',
      'INTIMATE: ஹாய் hāy, நீ nī · POLITE: வணக்கம் vaṇakkam, நீங்கள் nīṅkaḷ · FORMAL: வணக்கம் ஐயா/அம்மா, தாங்கள் tāṅkaḷ',
      'Switching from நீ to நீங்கள் mid-conversation signals increased respect; the reverse signals familiarity. தாங்கள் is reserved for major hierarchical gaps.',
      [
        { target: 'INTIMATE: ஹாய், நீ', note: 'use with close peers, family, children — never with strangers or elders' },
        { target: 'POLITE: வணக்கம், நீங்கள்', note: 'the safe default for first meetings, workplace, and any unfamiliar adult' },
        { target: 'FORMAL: தாங்கள் / ஐயா / அம்மா', note: 'reserved for clearly senior figures and customers; over-use can sound stiff among equals' },
      ],
      [ACT.orientation],
    ),

    // ──── Activity 2 — Pronunciation
    createContentItem(
      'வணக்கம்',
      'vaṇakkam',
      'Three pronunciation features in one word: retroflex ண (tongue curled), geminate க்க (held twice as long, voiceless /kk/), and word-final m. The medial க is NOT voiced because it is geminated; without the gemination it would be /g/.',
      'word',
      'வணக்கம் vaṇakkam — broken into syllables: va-ṇa-k-ka-m',
      'The most-heard greeting in Tamil; getting all three features right (retroflex, gemination, voicing) signals trained pronunciation.',
      [
        { target: 'வ va', note: 'voiced bilabial-dental approximant' },
        { target: 'ண ṇa', note: 'retroflex n; tongue curled back — NOT dental ந' },
        { target: 'க்க kka', note: 'geminate; voiceless /kk/ because doubled; held nearly twice as long' },
        { target: 'ம் m', note: 'final m; word-final nasal closes the syllable' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'நீ vs நீங்கள்',
      'nī vs nīṅkaḷ',
      'Two pronouns for "you" with completely different relational meanings. நீ nī (intimate, singular) — close friend, child, sibling. நீங்கள் nīṅkaḷ (polite/plural/familiar honorific) — anyone you are not close with, plural addressees, elders in polite contexts.',
      'word',
      'நீ எங்கே போகிறாய்? nī eṅkē pōkiṟāy? (intimate)\nநீங்கள் எங்கே போகிறீர்கள்? nīṅkaḷ eṅkē pōkiṟīrkaḷ? (polite)',
      'The verb ending changes too: -āy (intimate) vs -īrkaḷ (polite) — the agreement is mandatory; you cannot mix pronoun and ending.',
      [
        { target: 'நீ nī (intimate)', note: 'close friend, sibling, child, animal — INSULT if used with stranger or elder' },
        { target: 'நீங்கள் nīṅkaḷ (polite)', note: 'safe default; familiar/plural/honorific covers most situations' },
        { target: 'தாங்கள் tāṅkaḷ (very formal)', note: 'reserved for elders, dignitaries, customers — overuse sounds stiff' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'தமிழ்',
      'tamiḻ',
      'The language\'s own name — a litmus test for pronunciation. Final ழ is the retroflex approximant (IPA ɻ): tongue tip curled far back, no contact, NOT a /z/ sound.',
      'word',
      'நான் தமிழ் பேசுகிறேன். nāṉ tamiḻ pēcukiṟēṉ. "I speak Tamil."',
      'If you can say "tamiḻ" with a clean ழ in front of a native speaker, you have crossed the pronunciation threshold.',
      [
        { target: 'த ta', note: 'dental t' },
        { target: 'மி mi', note: 'consonant ம with short-i sign' },
        { target: 'ழ் ḻ', note: 'retroflex approximant; the famous Tamil sound; curl tongue back without touching' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'என் பெயர்',
      'eṉ peyar',
      'The self-introduction phrase. Two pronunciation features: alveolar ன் ṉ (not dental ந) and the medial ய y glide in peyar. Often the copula is dropped: "என் பெயர் ராஜா" = "(My name [is]) Raja."',
      'word',
      'என் பெயர் ராஜா. eṉ peyar Rājā. "My name is Raja."',
      'The copula drop is normal in Tamil identity sentences; adding an explicit copula sounds slightly formal.',
      [
        { target: 'என் eṉ', note: 'genitive of நான் ("my"); alveolar ṉ at end' },
        { target: 'பெயர் peyar', note: '"name"; final r is the alveolar tap, very brief' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'சென்னை',
      'ceṉṉai',
      'The capital city itself — Chennai. Geminate ன்ன (alveolar ṉ doubled) plus the diphthong ai. NOT spelled with retroflex ண.',
      'word',
      'நான் சென்னையில் இருக்கிறேன். nāṉ Ceṉṉaiyil irukkiṟēṉ. "I am in Chennai."',
      'Notice the locative -il ("in") attached to the city name — agglutinative suffix stacking, the heart of Tamil grammar.',
      [
        { target: 'ce', note: 'palatal c (often /s/-like word-initially in modern speech)' },
        { target: 'ṉṉa', note: 'geminate alveolar n' },
        { target: 'ai', note: 'diphthong; like English "eye"' },
      ],
      [ACT.pronunciation],
    ),

    // ──── Activity 3 — Vocabulary I: Greetings & farewells
    createContentItem('வணக்கம்', 'vaṇakkam', 'The standard formal-respectful all-purpose greeting; works for first meetings, elders, colleagues, and any time of day. Younger urban speakers may use "hi/hello" casually but vanakkam never feels stiff. Palms-together gesture often accompanies it.', 'word', 'வணக்கம்! என் பெயர் ராஜா.', 'Standard polite opener paired with a self-introduction; a typical first turn in any conversation.', null, [ACT.vocabularyGreetings]),
    createContentItem('ஹாய் / ஹலோ', 'hāy / halō', 'Casual greetings borrowed from English, used among close friends and peers especially in urban Chennai/Coimbatore. Inappropriate with elders or in formal contexts. Common in Tanglish-mixed speech.', 'word', 'ஹாய் ரவி, என்ன சமாச்சாரம்? hāy Ravi, eṉṉa camācāram?', 'Friend-to-friend opener; "என்ன சமாச்சாரம்?" = "what\'s up / what\'s the news?"', null, [ACT.vocabularyGreetings]),
    createContentItem('நல்வரவு', 'nalvaravu', 'A formal "welcome" — literally "good arrival". Used on banners, in formal speeches, and at receptions. In everyday speech, வரவேற்கிறேன் ("I welcome [you]") is the spoken form.', 'word', 'அண்ணா பல்கலைக்கழகத்திற்கு நல்வரவு!', 'Formal welcome banner phrasing for Anna University.', null, [ACT.vocabularyGreetings]),
    createContentItem('காலை வணக்கம்', 'kālai vaṇakkam', 'Good morning — literally "morning greeting". Used roughly from sunrise to 10 AM in polite-to-formal contexts (workplaces, news broadcasts, schools). In casual speech, plain வணக்கம் covers all times.', 'word', 'காலை வணக்கம், ஐயா!', 'Polite morning greeting to a senior man using ஐயா ("sir, father, mister") as honorific.', null, [ACT.vocabularyGreetings]),
    createContentItem('மாலை வணக்கம்', 'mālai vaṇakkam', 'Good evening — used roughly after 4 PM. Same register as காலை வணக்கம்; common in news, ceremonies, and workplace closing greetings.', 'word', 'மாலை வணக்கம், நண்பர்களே!', 'Polite group evening greeting; -ே suffix is the vocative marker for direct address.', null, [ACT.vocabularyGreetings]),
    createContentItem('சந்தித்ததில் மகிழ்ச்சி', 'cantittatil makiḻcci', 'The standard polite phrase at a first meeting; literal translation "happiness in meeting (you)". Universal safe response to a new introduction in any register.', 'word', 'உங்களைச் சந்தித்ததில் மகிழ்ச்சி.', '"Glad to meet you" — அவர் "ungaḷai" + verb-nominal + locative -il; full polite formula.', null, [ACT.vocabularyGreetings]),
    createContentItem('நன்றி', 'naṉṟi', 'The universal "thank you" — works in all registers from casual to formal. In informal contexts often replaced by English "thanks" in urban Tamil. Note the alveolar trill ṟ — distinct from r.', 'word', 'நன்றி, அண்ணா!', '"Thanks, brother!" — அண்ணா is a respectful address for any older male peer.', null, [ACT.vocabularyGreetings]),
    createContentItem('மன்னிக்கவும்', 'maṉṉikkavum', '"Please forgive / excuse me / sorry" — polite apology and attention-getter. The geminate ன்ன and கக together make this a pronunciation drill word.', 'word', 'மன்னிக்கவும், நேரம் என்ன?', 'Polite "excuse me, what time is it?" — common public-transport phrasing.', null, [ACT.vocabularyGreetings]),
    createContentItem('நீங்கள் எப்படி இருக்கிறீர்கள்?', 'nīṅkaḷ eppaṭi irukkiṟīrkaḷ?', 'Polite "how are you?" — literally "you how are-located?". The verb இருக்கிறீர்கள் uses இரு "to be located/exist" + present + 2nd-plural agreement. Standard reply: "நான் நலமாக இருக்கிறேன், நன்றி."', 'word', 'நீங்கள் எப்படி இருக்கிறீர்கள்? — நான் நலமாக இருக்கிறேன், நன்றி.', 'Standard polite exchange; "நலமாக" = "well, in good state".', null, [ACT.vocabularyGreetings]),
    createContentItem('போய் வருகிறேன்', 'pōy varukiṟēṉ', 'The standard Tamil farewell — literally "I go and come [back]". Used at any departure; signals an expected return rather than permanent goodbye. The defining Tamil leave-taking phrase.', 'word', 'சரி, போய் வருகிறேன்.', '"OK, I\'ll be going" — the standard polite close. Compound verb: போய் (having gone) + வருகிறேன் (I come).', null, [ACT.vocabularyGreetings]),
    createContentItem('விடைபெறுகிறேன்', 'viṭaipeṟukiṟēṉ', 'A more formal farewell — literally "I take leave". Used in ceremonies, formal speeches, and respectful contexts. Less common in everyday casual speech.', 'word', 'தங்களிடம் விடைபெறுகிறேன், ஐயா.', '"I take my leave of you, sir" — extremely respectful close to a senior figure.', null, [ACT.vocabularyGreetings]),
    createContentItem('நாளை சந்திப்போம்', 'nāḷai cantippōm', 'A casual farewell explicitly expecting tomorrow\'s meeting — literally "tomorrow we shall meet". The plural-future verb form -pōm includes both speaker and addressee.', 'word', 'நாளை சந்திப்போம்!', 'Friend-to-friend or colleague-to-colleague daily close; common workplace and classroom farewell.', null, [ACT.vocabularyGreetings]),

    // ──── Activity 4 — Vocabulary II: People, roles
    createContentItem('நான்', 'nāṉ', 'First-person singular subject pronoun. Same form for subject and topic; the genitive (possessive) is என் eṉ ("my"). Used in every self-introduction.', 'word', 'நான் மாணவன். nāṉ māṇavaṉ. "I am a (male) student."', 'Note: the verb agrees with nāṉ via -ēṉ ending: irukkiṟēṉ, pēcukiṟēṉ, paṭikkiṟēṉ.', null, [ACT.vocabularyPeople]),
    createContentItem('நீ', 'nī', 'Second-person INTIMATE pronoun — used with close friends, family members, children, younger siblings, or in deliberate disrespect. Genitive: உன் uṉ. Using nī with a stranger or elder is a serious social error.', 'word', 'நீ எங்கே போகிறாய்? nī eṅkē pōkiṟāy?', 'Verb form -āy is mandatory after nī; mixing nī + -īrkaḷ ending sounds broken.', null, [ACT.vocabularyPeople]),
    createContentItem('நீங்கள்', 'nīṅkaḷ', 'Second-person POLITE/PLURAL/FAMILIAR pronoun. The safe default for any adult you do not know intimately. Also serves as plural "you-all". Genitive: உங்கள் uṅkaḷ.', 'word', 'நீங்கள் எப்படி இருக்கிறீர்கள்?', 'Standard polite "how are you?"; verb ends in -īrkaḷ to agree with nīṅkaḷ.', null, [ACT.vocabularyPeople]),
    createContentItem('தாங்கள்', 'tāṅkaḷ', 'Second-person VERY FORMAL pronoun. Reserved for elders, dignitaries, judges, customers in formal industries. Slightly archaic in casual speech; common in classical Tamil and formal writing.', 'word', 'தாங்கள் எங்கிருந்து வருகிறீர்கள், ஐயா?', '"Where do you come from, sir?" — using tāṅkaḷ + ayyā signals maximum respect.', null, [ACT.vocabularyPeople]),
    createContentItem('அவன்', 'avaṉ', 'Third-person MASCULINE PEER pronoun — "he, peer/younger". Used for boys, peer-age men, and equals; intimate or familiar register. With strangers or elders, use அவர் (honorific) instead.', 'word', 'அவன் என் நண்பன். avaṉ eṉ naṇpaṉ. "He is my friend."', 'Tamil 3rd-person system tracks animacy + honor: avaṉ (peer male), avaḷ (peer female), avar (honorific), atu (neutral/it).', null, [ACT.vocabularyPeople]),
    createContentItem('அவள்', 'avaḷ', 'Third-person FEMININE PEER pronoun — "she, peer/younger". Used for girls, peer-age women, and equals. With elders or strangers, use அவர் honorific. Note the retroflex ḷ.', 'word', 'அவள் என் தங்கை. avaḷ eṉ taṅkai. "She is my younger sister."', 'taṅkai = younger sister; akkā = elder sister (older sisters get more respectful address).', null, [ACT.vocabularyPeople]),
    createContentItem('அவர்', 'avar', 'Third-person HONORIFIC pronoun — "he/she/they (respectful)". Used for elders, professionals, strangers, and anyone deserving of respect. Singular but with plural verb agreement: அவர் வருகிறார் avar varukiṟār.', 'word', 'அவர் என் ஆசிரியர். avar eṉ āciriyar. "He/she is my teacher."', 'avar is gender-neutral and politeness-marked; the safest 3rd-person choice when in doubt.', null, [ACT.vocabularyPeople]),
    createContentItem('அது', 'atu', 'Third-person NEUTRAL pronoun — "it / that". Used for things, animals (most), and abstract concepts. Distal; the proximal counterpart is இது itu ("this").', 'word', 'அது புத்தகம். atu puttakam. "That is a book."', 'Copula often dropped in identity sentences with atu/itu + noun.', null, [ACT.vocabularyPeople]),
    createContentItem('நாங்கள் / நாம்', 'nāṅkaḷ / nām', 'Two forms of "we": நாங்கள் nāṅkaḷ EXCLUSIVE (speaker + others, NOT addressee) vs நாம் nām INCLUSIVE (speaker + addressee, "all of us together"). Most languages don\'t distinguish these — Tamil does.', 'word', 'நாங்கள் சென்னையிலிருந்து வருகிறோம் (exc) vs நாம் சாப்பிட போகிறோம் (inc, "let\'s go eat")', 'Subtle but important: nām includes the listener; nāṅkaḷ excludes them.', null, [ACT.vocabularyPeople]),
    createContentItem('பெயர்', 'peyar', 'A person\'s name. The phrase என் பெயர்… ("my name [is]…") is the universal self-introduction opener. Note alveolar r and dropped copula.', 'word', 'என் பெயர் சுப்பிரமணியன். "My name is Subramanian."', 'Long names like Subramanian are typical in Tamil Nadu — often shortened to "Subbu" in casual address.', null, [ACT.vocabularyPeople]),
    createContentItem('மாணவன் / மாணவி / மாணவர்', 'māṇavaṉ / māṇavi / māṇavar', 'Student. Three forms by gender + honor: மாணவன் māṇavaṉ (male, peer), மாணவி māṇavi (female), மாணவர் māṇavar (honorific or plural). Tamil agreement is mandatory.', 'word', 'நான் அண்ணா பல்கலைக்கழகத்தில் மாணவன்/மாணவி. "I am a student at Anna University."', 'Male students use māṇavaṉ; female students use māṇavi; formal/polite reference uses māṇavar.', null, [ACT.vocabularyPeople]),
    createContentItem('ஆசிரியர்', 'āciriyar', 'Teacher — used with honorific agreement automatically (no separate male/female word in respectful register). Family-name + āciriyar is the standard polite address.', 'word', 'லட்சுமி ஆசிரியர் தமிழ் கற்றுத்தருகிறார்.', '"Teacher Lakshmi teaches Tamil." Note the verb -ār ending for the honorific subject.', null, [ACT.vocabularyPeople]),
    createContentItem('பேராசிரியர்', 'pērāciriyar', 'Professor — literally "great teacher". Used for university faculty. Always with honorific agreement.', 'word', 'சுப்பிரமணியன் பேராசிரியர் இன்று வந்திருக்கிறார்.', '"Professor Subramanian has come today." -irukkiṟār is perfect-honorific.', null, [ACT.vocabularyPeople]),
    createContentItem('பொறியாளர்', 'poṟiyāḷar', 'Engineer — literally "machine-handler". Used for any engineering discipline; one of the most common professions in Tamil Nadu given the IT industry.', 'word', 'அவர் மென்பொருள் பொறியாளர். avar meṉporuḷ poṟiyāḷar. "He/she is a software engineer."', 'meṉporuḷ = software ("soft-substance"); a classical-style coinage from Centhamizh.', null, [ACT.vocabularyPeople]),
    createContentItem('மருத்துவர்', 'maruttuvar', 'Doctor — also serves as a title after name: ரமேஷ் மருத்துவர் (Dr. Ramesh). One of the most common Tamil profession words.', 'word', 'என் அம்மா மருத்துவர். eṉ ammā maruttuvar. "My mother is a doctor."', 'ammā = mother; the term of address is also widely used for any older woman.', null, [ACT.vocabularyPeople]),
    createContentItem('நண்பன் / நண்பி / நண்பர்', 'naṇpaṉ / naṇpi / naṇpar', 'Friend — three forms by gender + honor. naṇpaṉ (male friend, peer); naṇpi (female friend, peer); naṇpar (honorific/plural).', 'word', 'அவன் என் நண்பன், அவள் என் நண்பி.', 'Tamil naming requires gender-specific forms for peer relationships.', null, [ACT.vocabularyPeople]),
    createContentItem('ஊர்', 'ūr', '"Hometown / village / native place" — a culturally loaded word. "உங்கள் ஊர் என்ன?" ("What\'s your hometown?") is a universal Tamil first-meeting question, more probing than "where do you live now".', 'word', 'என் ஊர் சேலம். eṉ ūr Cēlam. "My hometown is Salem."', 'Salem (சேலம்) is one of Tamil Nadu\'s major cities — referenced alongside Chennai, Coimbatore, Madurai, Trichy.', null, [ACT.vocabularyPeople]),
    createContentItem('தமிழ்நாடு', 'tamiḻnāṭu', '"Tamil Nadu" — the Tamil-speaking state of India. Literally "Tamil country". The retroflex ṭ in nāṭu is contrasted with dental t.', 'word', 'நான் தமிழ்நாட்டிலிருந்து வருகிறேன்.', '"I come from Tamil Nadu" — note the agglutinated locative+ablative -ttilliruntu ("from-in").', null, [ACT.vocabularyPeople]),
    createContentItem('இந்தியா', 'intiyā', '"India" — pronounced with retroflex t but spelled with dental in this loanword adaptation. Common geographic reference word.', 'word', 'நான் இந்தியன். nāṉ intiyaṉ. "I am Indian (male)."', 'For nationality: intiyaṉ (male), intiyaḷ (female), intiyar (honorific).', null, [ACT.vocabularyPeople]),
    createContentItem('இலங்கை', 'ilaṅkai', '"Sri Lanka" — home to a major Tamil-speaking population (Jaffna and the northern/eastern provinces). Tamil here preserves classical features lost on the mainland.', 'word', 'அவர் இலங்கையிலிருந்து வந்திருக்கிறார்.', '"He/she has come from Sri Lanka" — common Tamil cultural reference.', null, [ACT.vocabularyPeople]),
    createContentItem('சிங்கப்பூர் / மலேசியா', 'ciṅkappūr / malēciyā', 'Singapore and Malaysia — major Tamil diaspora populations. Tamil is an official language in Singapore; widely spoken in Malaysian Indian communities.', 'word', 'என் நண்பன் சிங்கப்பூரிலிருந்து வந்தான்.', '"My friend came from Singapore" — diaspora reference common in cosmopolitan Tamil contexts.', null, [ACT.vocabularyPeople]),

    // ──── Activity 5 — Grammar I: Copula
    createContentItem(
      'ஆகு / இரு / Ø',
      'āku / iru / Ø',
      'Tamil has THREE patterns for "to be": (1) ஆகு āku for identification/becoming ("X is Y", agglutinated as ஆகிறேன்/ஆகிறான்/ஆகிறாள்/ஆகிறார்); (2) இரு iru for existence/location ("X is located at Y"); (3) ZERO COPULA — drop the verb entirely when context is clear.',
      'sentence',
      'நான் மாணவன் (ஆகிறேன்). nāṉ māṇavaṉ (āgiṟēṉ). "I am a student."\nநான் வீட்டில் இருக்கிறேன். nāṉ vīṭṭil irukkiṟēṉ. "I am at home."\nஅவன் ராஜா. avaṉ Rājā. "He is Raja." [zero copula]',
      'Three patterns serve three different functions; choosing the wrong one is a major Tamil-learner trap.',
      [
        { target: 'ஆகு āku (identity)', note: 'X-is-Y; can be dropped in simple identity statements' },
        { target: 'இரு iru (existence/location)', note: 'X-exists / X-is-at-Y; never dropped; takes locative case' },
        { target: 'Ø (zero copula)', note: 'preferred in present-tense identity when context is clear' },
      ],
      [ACT.grammarCopula],
    ),
    createContentItem(
      'வினை ஒத்திசைவு',
      'verb agreement',
      'Tamil verbs agree with the subject in PERSON + NUMBER + GENDER + HONOR. The copula and every verb take one of these endings: -ēṉ (1sg), -ōm (1pl), -āy (2sg-intimate), -īrkaḷ (2pl/polite), -āṉ (3sg-masc-peer), -āḷ (3sg-fem-peer), -ār/-ārkaḷ (3sg/pl-honorific), -atu (3sg-neuter).',
      'sentence',
      'நான் வருகிறேன் (-ēṉ) · நீ வருகிறாய் (-āy) · அவன் வருகிறான் (-āṉ) · அவள் வருகிறாள் (-āḷ) · அவர் வருகிறார் (-ār) · நாங்கள் வருகிறோம் (-ōm) · நீங்கள் வருகிறீர்கள் (-īrkaḷ) · அவர்கள் வருகிறார்கள் (-ārkaḷ)',
      'Tamil agreement is much richer than English — 8 forms of "come" for the present tense alone.',
      [
        { target: '-ēṉ (1sg)', note: 'I' },
        { target: '-āy (2sg intimate)', note: 'you (nī)' },
        { target: '-āṉ / -āḷ / -ār / -atu (3sg)', note: 'he-peer / she-peer / honorific / it' },
        { target: '-ōm / -īrkaḷ / -ārkaḷ (plural)', note: 'we / you-polite / they' },
      ],
      [ACT.grammarCopula],
    ),
    createContentItem(
      'இணைப்புச் சொல் இல்லா அடையாளம்',
      'zero copula',
      'In present-tense identity sentences ("X is Y" where both are nouns), Tamil typically DROPS the copula. "என் பெயர் ராஜா" ("My name [is] Raja") is more natural than the explicit "என் பெயர் ராஜா ஆகிறது". The drop is the default; adding the copula sounds slightly formal/emphatic.',
      'sentence',
      'என் பெயர் ராஜா. அவன் என் நண்பன். அவர் ஆசிரியர். [all zero copula]',
      'When the subject is a thing (atu) + noun, copula is almost always dropped. When the subject is a person + role, it depends on register.',
      null,
      [ACT.grammarCopula],
    ),

    // ──── Activity 6 — Grammar II: Pronouns
    createContentItem(
      'பிரதிபெயர்கள்',
      'piratipeyarkaḷ',
      'Tamil has a rich pronoun system organized by PERSON + NUMBER + HONOR + ANIMACY. The third-person system distinguishes peer-masculine (avaṉ), peer-feminine (avaḷ), honorific (avar — gender-neutral), and neutral/inanimate (atu). All have proximal counterparts (ivaṉ/ivaḷ/ivar/itu) for "this one" rather than "that one".',
      'sentence',
      'நான் (1sg) · நாம்/நாங்கள் (1pl inc/exc) · நீ / நீங்கள் / தாங்கள் (2sg/pl/very-formal) · அவன் / அவள் / அவர் / அது (3sg by honor+animacy)',
      'The honor distinction in third person is mandatory — refer to your teacher as avaṉ and you have insulted them.',
      null,
      [ACT.grammarPronouns],
    ),
    createContentItem(
      'Genitive forms (என் etc.)',
      'genitive forms',
      'Possessive ("my", "your", "his") is formed by dropping the -ṉ/-ḷ/-r ending and replacing with the genitive: நான் → என் ("my"); நீ → உன் ("your-intimate"); நீங்கள் → உங்கள் ("your-polite"); அவன் → அவனுடைய/அவன் ("his"). The genitive often appears WITHOUT an overt possessive marker — pure juxtaposition signals possession.',
      'sentence',
      'என் பெயர் (my name) · உங்கள் ஊர் (your hometown) · அவர் ஆசிரியர் (his/her teacher)',
      'Tamil genitive is the lightest grammatical signal — no -\'s, no separate word, often nothing at all between possessor and possessed.',
      [
        { target: 'என் eṉ', note: 'my (from நான்)' },
        { target: 'உன் uṉ', note: 'your-intimate (from நீ)' },
        { target: 'உங்கள் uṅkaḷ', note: 'your-polite (from நீங்கள்)' },
        { target: 'அவனுடைய avaṉuṭaiya', note: 'his (peer) — long genitive form; short form is just அவன்' },
      ],
      [ACT.grammarPronouns],
    ),
    createContentItem(
      'நீ / நீங்கள் / தாங்கள்',
      'three "you"',
      'CRITICAL TABLE: நீ nī = intimate (use ONLY with close peers, children, family); நீங்கள் nīṅkaḷ = polite/familiar/plural (the default for any adult you don\'t know intimately); தாங்கள் tāṅkaḷ = very formal (elders, dignitaries, customers). The verb ending MUST agree.',
      'sentence',
      'நீ எங்கே போகிறாய்? (-āy)\nநீங்கள் எங்கே போகிறீர்கள்? (-īrkaḷ)\nதாங்கள் எங்கே போகிறீர்கள்? (-īrkaḷ, same as polite)',
      'Using nī with a stranger or elder is a major social error; using tāṅkaḷ with a close friend creates cold distance.',
      null,
      [ACT.grammarPronouns],
    ),

    // ──── Activity 7 — Grammar III: Negation
    createContentItem(
      'இல்லை',
      'illai',
      'The universal "not / no / not present" — used for identity negation, location negation, and short "no" answers. Placed at the END of the sentence; the rest of the structure is unchanged.',
      'sentence',
      'அது புத்தகம் இல்லை. atu puttakam illai. "That is not a book."\nநான் சென்னையில் இல்லை. nāṉ Ceṉṉaiyil illai. "I am not in Chennai."',
      'illai handles all NOMINAL negation; verbal negation (didn\'t do, don\'t do, won\'t do) uses different suffixes on the verb stem.',
      [
        { target: 'Identity: X Y illai', note: '"X is not Y" — copula drop + illai at end' },
        { target: 'Existence: X loc illai', note: '"X is not at Y" — locative + illai' },
        { target: 'Short answer', note: 'just illai = "no"' },
      ],
      [ACT.grammarNegation],
    ),
    createContentItem(
      'வினை மறுப்பு',
      'verbal negation',
      'For verbal negation (didn\'t do, don\'t do habitually), Tamil uses a negative verb suffix instead of a separate word. The auxiliary மாட்டு māṭṭu marks future negation: நான் வரமாட்டேன் nāṉ vara-māṭṭēṉ ("I won\'t come"). Past negation uses -illai with the infinitive: நான் வரவில்லை nāṉ varavillai ("I didn\'t come").',
      'sentence',
      'நான் வர மாட்டேன் (future neg) · நான் வரவில்லை (past neg) · நான் வருவதில்லை (habitual neg)',
      'Three negative forms for three tenses — Tamil verbal negation is more complex than English "don\'t/didn\'t".',
      null,
      [ACT.grammarNegation],
    ),
    createContentItem(
      'X இல்லை, Y',
      'X-illai, Y',
      'Polite correction pattern: state the wrong assumption with illai, then offer the correct version. "X-illai, Y" — the "but" is implicit. Three parts: rejected guess, illai, offered alternative.',
      'sentence',
      'A: நீங்கள் சென்னையிலிருந்து வருகிறீர்களா? "Do you come from Chennai?"\nB: இல்லை, நான் சேலத்திலிருந்து வருகிறேன். "No, I come from Salem."',
      'The illai softens the correction; jumping straight to "I come from Salem" without it sounds blunt.',
      null,
      [ACT.grammarNegation],
    ),

    // ──── Activity 8 — Reading
    createContentItem(
      'சுய அறிமுகம்',
      'cuya aṟimukam',
      'A complete five-sentence self-introduction in Tamil. Read aloud with correct retroflex, gemination, ழ, and rhythm. Notice the parallel structure: most sentences start with நான் or என்.',
      'sentence',
      'வணக்கம்! என் பெயர் சாரா. நான் அமெரிக்காவிலிருந்து வருகிறேன். நான் அண்ணா பல்கலைக்கழகத்தில் மாணவி. என் பாடம் கணினியியல். சந்தித்ததில் மகிழ்ச்சி.',
      'Translation: "Hello! My name is Sarah. I come from America. I am a (female) student at Anna University. My subject is Computer Science. Glad to meet you."',
      [
        { target: 'என் பெயர் சாரா', note: 'name introduction; copula dropped' },
        { target: 'அமெரிக்காவிலிருந்து வருகிறேன்', note: 'agglutinated: amerikā + locative -vil + ablative -iruntu + verb varukiṟēṉ; "from-America come-I"' },
        { target: 'பல்கலைக்கழகத்தில் மாணவி', note: 'university-loc student-fem; "(I am a) student at the university"' },
        { target: 'பாடம் கணினியியல்', note: '"subject (is) Computer Science"; kaṇiṉiyiyal = computer science (kaṇiṉi "computer" + iyal "study/-logy")' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'கேள்விகள்',
      'kēḷvikaḷ',
      'Four standard comprehension questions matching the paragraph. Answer each in a short sentence; full sentences are not required for natural Tamil.',
      'sentence',
      'Q1: உங்கள் பெயர் என்ன? Q2: நீங்கள் எங்கிருந்து வருகிறீர்கள்? Q3: நீங்கள் மாணவியா? Q4: உங்கள் பாடம் என்ன?',
      'Four standard openers covering name, origin, role-yes/no, and specific information.',
      [
        { target: 'A1: என் பெயர் சாரா.', note: 'name + zero copula' },
        { target: 'A2: அமெரிக்காவிலிருந்து.', note: 'short answer; full sentence also fine' },
        { target: 'A3: ஆமாம், மாணவியே.', note: 'ஆமாம் = yes; -ே vocative-emphatic' },
        { target: 'A4: கணினியியல்.', note: 'subject answer; short form is the natural register' },
      ],
      [ACT.reading],
    ),

    // ──── Activity 9 — Listening
    createContentItem(
      'முதல் சந்திப்பு (நட்பு)',
      'mutal cantippu (naṭpu)',
      'A natural polite-register first-meeting conversation between two students at Anna University. Covers all the patterns from this lesson: greetings, names, origins, roles, agreement, farewell.',
      'conversation',
      'அ: வணக்கம்! சந்தித்ததில் மகிழ்ச்சி. என் பெயர் முருகன்.\nஆ: வணக்கம், முருகன்! என் பெயர் சாரா. எனக்கும் மகிழ்ச்சி.\nஅ: நீங்கள் எங்கிருந்து வருகிறீர்கள்?\nஆ: நான் அமெரிக்காவிலிருந்து வருகிறேன். நீங்கள்?\nஅ: நான் மதுரையிலிருந்து வருகிறேன். நீங்கள் இங்கு மாணவியா?\nஆ: ஆமாம், கணினியியல் படிக்கிறேன். நீங்கள்?\nஅ: நானும் கணினியியல் மாணவன்! என்ன ஒரு தற்செயல்!\nஆ: சரி, வகுப்பில் சந்திப்போம்!',
      'A natural exchange between peers using nīṅkaḷ-polite register — the default for student-age first meetings at Tamil universities.',
      [
        { target: 'சந்தித்ததில் மகிழ்ச்சி', note: 'first-meeting polite phrase — both speakers use it' },
        { target: 'நீங்கள்? nīṅkaḷ?', note: 'standard "and you?" return-the-question phrase' },
        { target: '-இலிருந்து -iliruntu', note: 'ablative suffix "from"; attached to the city name' },
        { target: 'நானும் nāṉum', note: '"I also" — additive particle -um attached to nāṉ' },
        { target: 'என்ன ஒரு தற்செயல்! eṉṉa oru taṟceyal!', note: '"what a coincidence!" — common reaction phrase' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'முதல் சந்திப்பு (மரியாதை)',
      'mutal cantippu (mariyātai)',
      'A formal first-meeting conversation with a professor. Notice the formal register: tāṅkaḷ, ayyā/ammā, name + avarkaḷ honorific, verb -ārkaḷ agreement.',
      'conversation',
      'மாணவி: பேராசிரியர் அவர்களே, வணக்கம். என் பெயர் சாரா.\nபேராசிரியர்: வணக்கம், சாரா அவர்களே. அண்ணா பல்கலைக்கழகத்திற்கு நல்வரவு.\nமாணவி: நன்றி, ஐயா. தங்கள் வகுப்பில் கற்க மிகவும் ஆவலாக இருக்கிறேன்.\nபேராசிரியர்: நல்லது. தாங்கள் எங்கிருந்து வருகிறீர்கள்?\nமாணவி: நான் அமெரிக்காவின் பாஸ்டன் நகரிலிருந்து வருகிறேன்.\nபேராசிரியர்: மிகவும் நல்லது. இங்கு வாழ்க்கை வளமாக அமைய வாழ்த்துகிறேன்.\nமாணவி: நன்றி, ஐயா.',
      'Same information as the polite version but with formal phrasing — appropriate for hierarchical student-professor relationships.',
      [
        { target: 'அவர்களே avarkaḷē', note: 'honorific name-suffix + vocative; "respected Sir/Madam" style of address' },
        { target: 'ஐயா ayyā', note: 'formal address for any older male — "sir, father, mister"' },
        { target: 'தாங்கள் tāṅkaḷ', note: 'very formal "you" — only with clearly senior figures' },
        { target: 'வாழ்த்துகிறேன்', note: '"I bless / wish well" — formal blessing verb' },
      ],
      [ACT.listening],
    ),

    // ──── Activity 10 — Writing
    createContentItem(
      'எழுதும் வடிவம்',
      'eḻutum vaṭivam',
      'A reusable five-sentence template for any Tamil self-introduction. Fill in the bracketed slots with your own information.',
      'sentence',
      'வணக்கம்! என் பெயர் [பெயர்]. நான் [நாடு / நகரம்]-லிருந்து வருகிறேன். நான் அண்ணா பல்கலைக்கழகத்தில் [பாத்திரம்]. என் [விருப்பம் / பாடம்] [விவரம்]. சந்தித்ததில் மகிழ்ச்சி.',
      'Five sentences cover the core: greeting, name, origin, role, personal fact, closing.',
      [
        { target: '[பெயர்]', note: 'your name — given name only for casual, family-name+given for formal' },
        { target: '[நாடு / நகரம்]-லிருந்து', note: 'country or city + ablative -iliruntu "from"' },
        { target: '[பாத்திரம்]', note: 'māṇavaṉ/māṇavi/māṇavar / āciriyar / poṟiyāḷar — your role' },
        { target: '[விவரம்]', note: 'something specific that distinguishes you' },
      ],
      [ACT.writing],
    ),
    createContentItem(
      'எழுது',
      'eḻutu',
      'Write your own 3-5 sentence Tamil self-introduction in Tamil script using the template. Include retroflex consonants, gemination, and at least one ழ-word if you can.',
      'sentence',
      'எடுத்துக்காட்டு: வணக்கம்! என் பெயர் கிம் சு-ஜின். நான் கொரியாவிலிருந்து வருகிறேன். நான் அண்ணா பல்கலைக்கழகத்தில் மாணவன். எனக்கு தமிழ் மொழியில் ஆர்வம். சந்தித்ததில் மகிழ்ச்சி!',
      'Translation: "Hello! My name is Kim Su-jin. I come from Korea. I am a student at Anna University. I have interest in the Tamil language. Glad to meet you!"',
      null,
      [ACT.writing],
    ),

    // ──── Activity 11 — Culture
    createContentItem(
      'மரியாதை + பெயர் + அவர்கள்',
      'honor + name + avarkaḷ',
      'Honorific address: in formal Tamil, append -அவர்கள் (-avarkaḷ) to a name to show respect. ராஜா அவர்கள் (Rājā avarkaḷ) = "Mr. Raja" / "the honorable Raja". In academic and professional contexts this is standard for elders, professors, and dignitaries.',
      'sentence',
      'ராஜா அவர்கள் · சுப்பிரமணியன் அவர்கள் · ஜெயலலிதா அவர்கள்',
      'Used in news, formal letters, ceremonies, and academic introductions. Politicians and celebrities are routinely referred to this way.',
      [
        { target: '-அவர்கள் -avarkaḷ', note: 'honorific suffix added to a name; literally "they (honorific)"' },
        { target: 'ஐயா ayyā', note: 'sir/father — for older males' },
        { target: 'அம்மா ammā', note: 'madam/mother — for older females' },
        { target: 'அண்ணா aṇṇā', note: 'elder brother — respectful for slightly older male peers' },
        { target: 'அக்கா akkā', note: 'elder sister — respectful for slightly older female peers' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'நீ / நீங்கள் / தாங்கள் — register',
      'register switch',
      'The three "you" forms ARE the social hierarchy in spoken Tamil. nī between friends and family signals warmth; nīṅkaḷ with strangers signals respect; tāṅkaḷ with dignitaries signals reverence. Switching DOWN (nīṅkaḷ → nī) without permission signals presumption or rudeness; switching UP signals new distance.',
      'sentence',
      'Sibling: நீ எங்கே போற? (nī)\nColleague: நீங்கள் எங்கே போகிறீர்கள்? (nīṅkaḷ)\nProfessor: தாங்கள் எங்கு செல்கிறீர்கள்? (tāṅkaḷ)',
      'Mastering this triple is the social heart of Tamil — every conversation requires choosing one.',
      null,
      [ACT.culture],
    ),
    createContentItem(
      'தமிழ் மரபு',
      'tamiḻ marapu',
      'Tamil cultural pride: language (continuously spoken 2000+ years, Sangam-era poetry, Thirukkural), arts (Bharatanatyam dance, Carnatic music), food (sambar, rasam, idli, dosa, filter coffee), festivals (Pongal four-day harvest festival, Deepavali, Tamil New Year), and the wider Tamil world spanning Tamil Nadu, Sri Lanka, Singapore, Malaysia.',
      'sentence',
      'நான் தமிழ் கற்க விரும்புகிறேன். தமிழ் இலக்கியம் மிகவும் பழமையானது.',
      '"I want to learn Tamil. Tamil literature is very ancient." — a common expression of cultural appreciation that earns warm responses.',
      [
        { target: 'திருக்குறள் tirukkuṟaḷ', note: 'Tamil literary classic — 1330 couplets by Thiruvalluvar, ~5th c CE' },
        { target: 'பொங்கல் poṅkal', note: 'four-day harvest festival in mid-January; biggest Tamil holiday' },
        { target: 'பரதநாட்டியம் pharatanāṭṭiyam', note: 'classical Tamil dance form' },
        { target: 'கோலம் kōlam', note: 'rice-flour floor patterns drawn at dawn at house entrances' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'அண்ணா பல்கலைக்கழகம்',
      'aṇṇā palkalaikkaḻakam',
      'Anna University (named after C.N. Annadurai, founding chief minister of Tamil Nadu, called "Anna" — "elder brother") is one of South India\'s top technical universities, located in Guindy, Chennai. Adjacent to IIT Madras. The course\'s anchor campus for cultural references throughout.',
      'sentence',
      'நான் அண்ணா பல்கலைக்கழகத்தில் கணினியியல் படிக்கிறேன்.',
      '"I study Computer Science at Anna University" — a sentence you will use often as the course anchor.',
      [
        { target: 'அண்ணா aṇṇā', note: 'elder brother / nickname of Annadurai' },
        { target: 'பல்கலைக்கழகம் palkalaikkaḻakam', note: 'university — literally "many-arts gathering"' },
        { target: 'சென்னை IIT, லயோலா கல்லூரி', note: 'other Chennai landmarks: IIT Madras (engineering), Loyola College (arts)' },
      ],
      [ACT.culture],
    ),

    // ──── Activity 12 — Task
    createContentItem(
      'பணி: அண்ணா பல்கலைக்கழகத்தில் முதல் நாள்',
      'paṇi: aṇṇā palkalaikkaḻakattil mutal nāḷ',
      'Roleplay your first day at Anna University with the AI tutor playing a friendly visiting professor from Madurai. Use every skill from this lesson in one continuous scene — greet, introduce, ask, answer, farewell.',
      'conversation',
      '[ஆய்வகம், அண்ணா பல்கலைக்கழகம்]\nபேராசிரியர்: வணக்கம்! என் பெயர் சுப்பிரமணியன்.\nநீ: [வணக்கம் + சுய அறிமுகம்]\nபேராசிரியர்: நீங்கள் எங்கிருந்து வருகிறீர்கள்?\nநீ: [உங்கள் நாடு / நகரம்]\nபேராசிரியர்: நீங்கள் இங்கு மாணவியா/மாணவனா?\nநீ: [ஆமாம் + உங்கள் பாடம்]\nபேராசிரியர்: ஓ, நல்லது! உங்கள் பாடம் என்ன?\nநீ: [பாடம்]\nபேராசிரியர்: உங்களைச் சந்தித்ததில் மகிழ்ச்சி!\nநீ: [விடைபெறு]',
      'Six turns of fluent exchange; the AI tutor will prompt you and respond naturally to whatever you say.',
      [
        { target: 'வணக்கம் சொல்', note: 'வணக்கம் / காலை வணக்கம் — pick the register matching the professor\'s opener' },
        { target: 'சுய அறிமுகம்', note: 'என் பெயர்… or நான்… — natural form' },
        { target: 'ஊர் / நாடு', note: '-iliruntu varukiṟēṉ pattern' },
        { target: 'பாடம்', note: 'state your subject; கணினியியல் / பொறியியல் / மருத்துவம் etc.' },
        { target: 'விடைபெறு', note: 'போய் வருகிறேன் / விடைபெறுகிறேன் — match the register you opened with' },
      ],
      [ACT.task],
    ),
    createContentItem(
      'சவால் — தவறான ஊகத்தை திருத்து',
      'cavāl — taṟavāṉa ūkattai tirutu',
      'Stretch goal: in the same scene, the professor guesses your country incorrectly. Politely correct using X-illai-Y. Closes the loop without making the asker lose face.',
      'conversation',
      'பேராசிரியர்: ஓ, நீங்கள் ஜப்பானியரா?\nநீ: இல்லை, நான் ஜப்பானியன் இல்லை. நான் கொரியன், சியோலிலிருந்து வருகிறேன்.\nபேராசிரியர்: ஓ, மன்னிக்கவும், தவறாக புரிந்துகொண்டேன்!\nநீ: பரவாயில்லை, பரவாயில்லை.',
      '"பரவாயில்லை" (paravāyillai) is a casual reassurance — "it\'s no problem / never mind" — standard response after a small apology.',
      [
        { target: 'X-illai, Y', note: 'the standard correction pattern from Grammar III' },
        { target: 'பரவாயில்லை paravāyillai', note: '"never mind / no problem"; the universal post-apology reassurance' },
        { target: 'மன்னிக்கவும் maṉṉikkavum', note: '"please forgive / sorry"; the polite apology' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
