// Level 1 Unit 7 — Going Places (English)
// Functions: stating destination, purpose, future plans with "going to" and "will".

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u7-orientation',
  pronunciation: 'en-l1u7-pronunciation',
  vocabularyDestinations: 'en-l1u7-vocab-dest',
  vocabularyCompanions: 'en-l1u7-vocab-comp',
  grammarPurpose: 'en-l1u7-grammar-purpose',
  grammarGoingTo: 'en-l1u7-grammar-going-to',
  grammarWill: 'en-l1u7-grammar-will',
  reading: 'en-l1u7-reading',
  listening: 'en-l1u7-listening',
  writing: 'en-l1u7-writing',
  culture: 'en-l1u7-culture',
  task: 'en-l1u7-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['State where you are going and WHY (purpose with "to + verb").', 'Use "going to" for planned future and "will" for spontaneous future.', 'Talk about who you are going with.'],
    task: 'Imagine a friend asks "Where are you going?" — you say where, why, with whom, and when.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Going to → "gonna"',
    goals: ['"Going to" reduces to /ˈɡənə/ ("gonna") in fast speech.', 'Pronounce "I\'ll" /aɪl/ as a single syllable, not /aɪ wɪl/.'],
    task: 'Read each future form aloud.' },
  { id: ACT.vocabularyDestinations, section: 'Vocabulary I', title: 'Destinations',
    goals: ['Name 12+ places people commonly go.'],
    task: 'List five places you go often.' },
  { id: ACT.vocabularyCompanions, section: 'Vocabulary II', title: 'Companions & purposes',
    goals: ['Use family/friends/alone + purpose verbs (meet, buy, see, study, work out).'],
    task: 'Pair a destination with a purpose for three errands.' },
  { id: ACT.grammarPurpose, section: 'Grammar I', title: 'Purpose with "to + verb"',
    goals: ['Use "to + bare verb" to express purpose: "I go to the cafe TO meet a friend".', 'Alternative: "in order to + verb" (more formal).'],
    task: 'Make three purpose sentences.' },
  { id: ACT.grammarGoingTo, section: 'Grammar II', title: '"be going to" — planned future',
    goals: ['Form "subject + be + going to + verb" for planned future.', 'Use for plans you have already decided on.'],
    task: 'Make three "going to" sentences about the weekend.' },
  { id: ACT.grammarWill, section: 'Grammar III', title: '"will" — spontaneous / promise',
    goals: ['Use "subject + will + verb" for sudden decisions, predictions, and promises.', 'Contract: I\'ll, you\'ll, he\'ll …'],
    task: 'Make three "will" sentences.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A busy Saturday',
    goals: ['Read a 5-stop weekend itinerary.'],
    task: 'Identify where the writer goes, why, and with whom.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Where are you off to?',
    goals: ['Follow two short "where are you going" dialogues.'],
    task: 'Reproduce with your own plan.' },
  { id: ACT.writing, section: 'Writing', title: 'My weekend plan',
    goals: ['Write 4–5 sentences about an upcoming weekend.'],
    task: 'Write your own weekend plan with future tense.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Inviting "Want to join?"',
    goals: ['Know "Want to join us?" / "Wanna come?" as inclusive invites.', 'Avoid "Will you come with me?" — sounds awkwardly formal.'],
    task: 'Invite someone to one of your plans.' },
  { id: ACT.task, section: 'Task', title: 'Share your weekend plan',
    goals: ['Combine destination, purpose, companion, and future tense.'],
    task: 'Roleplay sharing your weekend plan and inviting the AI tutor.' },
];

const lesson = {
  title: 'Level 1 · Unit 7: I\'m going to the park — Going Places',
  category: 'travel',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-where-going', label: 'Asking where someone is going', goal: 'Use "Where are you going?".' },
    { id: 'stating-future-plan', label: 'Stating a planned future', goal: 'Use "going to + verb".' },
    { id: 'expressing-purpose', label: 'Expressing purpose', goal: 'Use "to + verb".' },
    { id: 'inviting-companion', label: 'Inviting someone along', goal: 'Use "Want to join us?".' },
  ],
  relatedPools: ['topic-people', 'topic-society'],
  content: [
    createContentItem('Lesson goal', 'going somewhere', 'By end: state where, why, with whom you are going + use "going to" and "will" for future.', 'word', 'Functions: destination · purpose · companion · future.', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Saturday morning', 'A classmate sees you with a backpack and asks where you are off to.', 'word', 'Classmate: "Where are you going?" — You: "I\'m going to the cafe to meet a friend."', 'A typical short exchange.', null, [ACT.orientation]),

    createContentItem('going to → "gonna"', '/ˈɡənə/', 'In fast speech, "going to" reduces to "gonna" /ˈɡənə/. Standard in speech, casual in writing.', 'word', 'I\'m going to study. /aɪm ˈɡənə ˈstʌdi/', 'In formal writing, keep "going to"; in speech, "gonna" is natural.', null, [ACT.pronunciation]),
    createContentItem('I\'ll', '/aɪl/', 'Single syllable contraction of "I will".', 'word', 'I\'ll go. /aɪl ɡoʊ/', 'Don\'t say two separate syllables — it should sound like "aisle".', null, [ACT.pronunciation]),
    createContentItem('want to → "wanna"', '/ˈwɒnə/', 'Casual contraction of "want to".', 'word', 'I want to go. → I wanna go. /aɪ ˈwɒnə ɡoʊ/', 'Very casual; do not write it in formal essays.', null, [ACT.pronunciation]),
    createContentItem('have to → "hafta"', '/ˈhæftə/', 'Casual contraction of "have to".', 'word', 'I have to go. → I hafta go. /aɪ ˈhæftə ɡoʊ/', 'Same level of casualness as "gonna" and "wanna".', null, [ACT.pronunciation]),

    createContentItem('cafe', '/ˈkæfeɪ/', 'small place for coffee and snacks', 'word', 'Let\'s meet at the cafe.', 'British also: "café" (same word).', null, [ACT.vocabularyDestinations]),
    createContentItem('mall', '/mɔːl/', 'large indoor shopping center', 'word', 'I\'m going to the mall.', 'British: "shopping centre".', null, [ACT.vocabularyDestinations]),
    createContentItem('movie theater', '/ˈmuːvi ˈθiːətər/', 'building where films are shown', 'word', 'We\'re going to the movie theater.', 'British: "cinema".', null, [ACT.vocabularyDestinations]),
    createContentItem('amusement park', '/əˈmjuːzmənt pɑːrk/', 'park with rides and games', 'word', 'Everland is an amusement park.', '', null, [ACT.vocabularyDestinations]),
    createContentItem('gym', '/dʒɪm/', 'place to exercise with equipment', 'word', 'I go to the gym three times a week.', 'Short for "gymnasium".', null, [ACT.vocabularyDestinations]),
    createContentItem('restaurant', '/ˈrɛstərɒnt/', 'place to eat a meal', 'word', 'Let\'s go to a Korean restaurant.', '', null, [ACT.vocabularyDestinations]),
    createContentItem('bookstore', '/ˈbʊkstɔːr/', 'shop that sells books', 'word', 'The bookstore is downtown.', 'British: "bookshop".', null, [ACT.vocabularyDestinations]),
    createContentItem('market', '/ˈmɑːrkət/', 'a place to buy groceries / goods', 'word', 'I shop at the market.', 'Open-air or covered; different from "supermarket".', null, [ACT.vocabularyDestinations]),
    createContentItem('beach', '/biːtʃ/', 'sandy shore by the sea', 'word', 'We\'re going to the beach this weekend.', '', null, [ACT.vocabularyDestinations]),
    createContentItem('park', '/pɑːrk/', 'public outdoor area with grass', 'word', 'Let\'s walk in the park.', '', null, [ACT.vocabularyDestinations]),
    createContentItem('museum', '/mjuːˈziːəm/', 'building displaying art or history', 'word', 'The museum is free on Sundays.', '', null, [ACT.vocabularyDestinations]),
    createContentItem('downtown', '/ˌdaʊnˈtaʊn/', 'central business / shopping area', 'word', 'I\'m going downtown.', 'Used without "to": "go downtown".', null, [ACT.vocabularyDestinations]),

    createContentItem('family', '/ˈfæməli/', 'parents, siblings, relatives', 'word', 'I\'m going with my family.', 'Collective noun; usually takes singular verb in American English.', null, [ACT.vocabularyCompanions]),
    createContentItem('friend', '/frɛnd/', 'a person you know and like', 'word', 'I\'m meeting a friend.', 'Plural: friends.', null, [ACT.vocabularyCompanions]),
    createContentItem('alone', '/əˈloʊn/', 'by yourself', 'word', 'I\'m going alone today.', 'Adverb; goes after the verb.', null, [ACT.vocabularyCompanions]),
    createContentItem('together', '/təˈɡɛðər/', 'with someone', 'word', 'Let\'s go together.', 'Often paired with "with".', null, [ACT.vocabularyCompanions]),
    createContentItem('meet', '/miːt/', 'to come together with someone', 'word', 'I\'m going to meet my friend.', 'Irregular past: met.', null, [ACT.vocabularyCompanions]),
    createContentItem('buy', '/baɪ/', 'to purchase', 'word', 'I\'m going to buy clothes.', 'Irregular past: bought.', null, [ACT.vocabularyCompanions]),
    createContentItem('see', '/siː/', 'to watch with eyes', 'word', 'I\'m going to see a movie.', 'Common in "see a movie / see a friend".', null, [ACT.vocabularyCompanions]),
    createContentItem('work out', '/wɜːrk aʊt/', 'to exercise', 'word', 'I\'m going to work out.', 'Phrasal verb; noun form: "workout".', null, [ACT.vocabularyCompanions]),
    createContentItem('study', '/ˈstʌdi/', 'to learn carefully', 'word', 'I\'m going to study.', 'Third-person: "studies".', null, [ACT.vocabularyCompanions]),
    createContentItem('relax', '/rɪˈlæks/', 'to rest and unwind', 'word', 'I\'m going to relax at home.', '', null, [ACT.vocabularyCompanions]),

    createContentItem(
      'Purpose with "to + verb"',
      'infinitive of purpose',
      'Use "to + bare verb" to express WHY you are doing something.',
      'sentence',
      'I\'m going to the cafe to meet a friend. — I came to Korea to study.',
      'Common pattern: [main action] + "to" + [purpose].',
      [
        { target: 'I go to the gym TO exercise.', english: 'purpose: why I go' },
        { target: 'She came TO see you.', english: 'purpose: why she came' },
      ],
      [ACT.grammarPurpose],
    ),
    createContentItem(
      'Alternative: "in order to" / "so that"',
      'more formal purpose',
      '"In order to" is the more formal version of purpose; "so that" introduces a clause.',
      'sentence',
      'I study English in order to work abroad. — I left early so that I could catch the train.',
      'In casual speech, "to" alone is most common.',
      null,
      [ACT.grammarPurpose],
    ),

    createContentItem(
      '"be going to + verb" — planned future',
      'subject + am/are/is + going to + verb',
      'Use for plans you have ALREADY DECIDED before speaking.',
      'sentence',
      'I\'m going to study tonight. — She\'s going to visit her family next month.',
      'Same form for all subjects; only "be" changes (am/is/are).',
      [
        { target: 'I am going to → I\'m going to', english: 'first person' },
        { target: 'He/she/it is going to → he\'s/she\'s/it\'s going to', english: 'third person singular' },
        { target: 'You/we/they are going to → you\'re/we\'re/they\'re going to', english: 'others' },
      ],
      [ACT.grammarGoingTo],
    ),
    createContentItem(
      'Negative: "not going to"',
      'subject + be not + going to + verb',
      'Add "not" after "be" to negate.',
      'sentence',
      'I\'m not going to work tomorrow. — He isn\'t going to come.',
      'In speech, almost always contracted.',
      null,
      [ACT.grammarGoingTo],
    ),
    createContentItem(
      'Question: "Are you going to …?"',
      'be + subject + going to + verb',
      'Invert subject and "be".',
      'sentence',
      'Are you going to study? — Yes, I am. / No, I\'m not.\nIs she going to come? — Yes, she is. / No, she isn\'t.',
      'Short answers repeat the form of "be".',
      null,
      [ACT.grammarGoingTo],
    ),

    createContentItem(
      '"will + verb" — spontaneous future',
      'subject + will + bare verb',
      'Use "will" for SUDDEN decisions made at the moment of speaking, for predictions, and for promises.',
      'sentence',
      'The phone is ringing. I\'ll answer it. (sudden decision)\nIt will rain tomorrow. (prediction)\nI\'ll help you. (promise)',
      'Contract: I\'ll, you\'ll, he\'ll, she\'ll, we\'ll, they\'ll.',
      [
        { target: 'spontaneous: I\'ll get it!', english: 'decision at the moment' },
        { target: 'prediction: It will rain.', english: 'future likelihood' },
        { target: 'promise: I\'ll help you.', english: 'commitment to another' },
      ],
      [ACT.grammarWill],
    ),
    createContentItem(
      'Negation: "won\'t"',
      'irregular contraction',
      '"Will not" contracts to "won\'t" — note the spelling change.',
      'sentence',
      'I won\'t be late. — She won\'t come tonight.',
      'Not "willn\'t" — the contraction is irregular.',
      null,
      [ACT.grammarWill],
    ),
    createContentItem(
      '"going to" vs "will" — which to use?',
      'planned vs spontaneous',
      '"Going to" = already planned. "Will" = decided in the moment, or pure prediction / promise.',
      'sentence',
      'A: We have no milk.\nB: I\'ll buy some on my way home. (decision in the moment)\nA: What are your plans?\nB: I\'m going to visit my parents this weekend. (already planned)',
      'A common test question — match the form to the situation.',
      [
        { target: 'going to → already planned', english: 'use when the plan exists before now' },
        { target: 'will → decided now / prediction / promise', english: 'use for new decisions' },
      ],
      [ACT.grammarWill],
    ),

    createContentItem(
      'A busy Saturday',
      'reading practice',
      'Read aloud and note where the writer goes and why.',
      'sentence',
      'This Saturday is going to be really busy. In the morning, I\'m going to the cafe to meet my friend. At lunch, I\'m going to a restaurant with my family. In the afternoon, I\'m going to the mall to buy clothes. In the evening, I\'m going to the movie theater to see a new film with my sister. On Sunday, I\'ll relax at home.',
      'Notice "going to" for planned events and "will" for the more spontaneous closing.',
      [
        { target: 'going to the cafe to meet my friend', english: 'destination + purpose' },
        { target: 'with my family / with my sister', english: 'companion phrase' },
        { target: 'I\'ll relax at home', english: '"will" for casual decision' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use future forms in your answers.',
      'sentence',
      'Q1: Where is she going on Saturday morning? · Q2: Why is she going to the mall? · Q3: What will she do on Sunday?',
      'Use "going to" for planned, "will" for casual.',
      [
        { target: 'A1: She\'s going to the cafe.', english: 'destination' },
        { target: 'A2: She\'s going to the mall to buy clothes.', english: 'destination + purpose' },
        { target: 'A3: She\'ll relax at home.', english: 'casual prediction' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Where are you going?',
      'listening',
      'Two classmates meet on campus.',
      'conversation',
      'A: Hey, where are you going?\nB: I\'m going to the cafe to meet a friend. Want to join us?\nA: Sure! I have time.\nB: Cool, let\'s go.\nA: By the way, what are you doing later?\nB: I\'m going to study at the library. Want to come?\nA: Maybe. I\'ll text you.',
      'Note casual register: "Want to join?", "I\'ll text you".',
      [
        { target: 'Want to join us?', english: 'casual invite' },
        { target: 'I\'ll text you', english: '"will" for promise' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Weekend plans',
      'listening',
      'Two friends compare weekends.',
      'conversation',
      'A: What are you doing this weekend?\nB: I\'m going to the beach with my family. How about you?\nA: I\'m going to study. I have an exam on Monday.\nB: Oh, that\'s tough. We\'ll bring you a souvenir!\nA: Thanks! Have fun.\nB: You too. Good luck!',
      '"What are you doing this weekend?" — natural way to ask about plans (present continuous as future).',
      [
        { target: 'What are you doing this weekend?', english: 'present continuous for future plans' },
        { target: 'We\'ll bring you a souvenir', english: '"will" for promise' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'weekend plan template',
      'Use this skeleton.',
      'sentence',
      'This weekend, I\'m going to [destination] to [purpose]. I\'m going with [companion]. We\'ll [activity]. On [day], I\'ll [activity].',
      '[destination] · [purpose] · [companion] · [activity] · [other day].',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 4–5 sentences about your real weekend plan. Use "going to" and at least one "will".',
      'sentence',
      'Example: This Saturday, I\'m going to the cafe with a friend. We\'re going to study together. In the evening, I\'ll cook dinner at home. On Sunday, I\'m going to relax.',
      'Check: future tense + destination + purpose.',
      null,
      [ACT.writing],
    ),

    createContentItem(
      '"Want to join?" — inclusive invites',
      'casual invitations',
      'In English-speaking cultures, casual "Want to join us?" or "Want to come?" is the standard invite. It is friendly and easy to refuse politely.',
      'sentence',
      'Want to join us? / Wanna come? / Care to join us?',
      'Reject politely: "Thanks, but I have plans." / "Maybe next time."',
      [
        { target: 'Want to come?', english: 'casual invite — peer to peer' },
        { target: 'Wanna join us?', english: 'very casual contraction' },
        { target: 'Would you like to join?', english: 'more formal version' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Plan vs spontaneous distinction',
      'speech habits',
      'English speakers tend to plan ahead and announce plans with "going to". For sudden offers (drinks, rides, help), "I\'ll" feels more natural.',
      'sentence',
      'Planning: "I\'m going to bring snacks." — Offer: "I\'ll help you with that."',
      'Mismatching can sound odd: "I\'m going to help you" — sounds reluctant or pre-planned.',
      null,
      [ACT.culture],
    ),

    createContentItem(
      'Task: Share your weekend',
      'consolidation task',
      'Roleplay: A friend asks about your weekend. Tell them where, why, with whom, and invite them along.',
      'conversation',
      'Friend: Hey, any plans this weekend?\nYou: [destination + purpose + companion]\nFriend: Oh nice! What time?\nYou: [time + invite them]\nFriend: Sounds great. I\'ll see you there!',
      'AI tutor will play the friend.',
      [
        { target: 'I\'m going to [place] to [verb]', english: 'plan + purpose' },
        { target: 'with my [family/friend]', english: 'companion' },
        { target: 'Want to join us?', english: 'casual invite' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
