// Level 1 Unit 21 — Hopes & Dreams (English)
// Functions: career hopes, expressing wishes, sequencing future plans.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l1u21-orientation',
  pronunciation: 'en-l1u21-pronunciation',
  vocabularyJobs: 'en-l1u21-vocab-jobs',
  vocabularyFuture: 'en-l1u21-vocab-fut',
  grammarWish: 'en-l1u21-grammar-wish',
  grammarBecome: 'en-l1u21-grammar-become',
  grammarAfterBefore: 'en-l1u21-grammar-after',
  reading: 'en-l1u21-reading',
  listening: 'en-l1u21-listening',
  writing: 'en-l1u21-writing',
  culture: 'en-l1u21-culture',
  task: 'en-l1u21-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Talk about your future and dream job in 3-4 sentences.', 'Express wishes with "I wish + past" and "I hope + present/will".', 'Use "become / want to be" + job, with modifiers like "famous", "good", "successful".', 'Sequence events with "after / before + V-ing" and "after / before + noun".'],
    task: 'Picture sitting in a career office at Massachusetts Institute of Technology — your professor asks "What do you want to do after graduation?" By the end of this lesson you can answer with a dream, a plan, and a timeline.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Wish + future sounds',
    goals: ['Pronounce "hope" /hoʊp/ vs "hop" /hɒp/ — long vs short vowel.', 'Pronounce "wish" /wɪʃ/ — voiceless /ʃ/, no /tʃ/.', 'Contraction "I\'d" /aɪd/ — short, one syllable. Past unreal: "I wish I were" /aɪ wɪʃ aɪ wər/.'],
    task: 'Read each wish/hope sentence aloud.' },
  { id: ACT.vocabularyJobs, section: 'Vocabulary I', title: 'Jobs & professions',
    goals: ['Name 14 common jobs: doctor, nurse, teacher, engineer, programmer, designer, lawyer, accountant, artist, journalist, chef, entrepreneur, scientist, athlete.'],
    task: 'Pick three jobs you might pursue.' },
  { id: ACT.vocabularyFuture, section: 'Vocabulary II', title: 'Future & aspiration words',
    goals: ['Use dream, goal, plan, future, hope, graduate, get a job, internship, study abroad, work hard, achieve.'],
    task: 'Pair each future word with an action.' },
  { id: ACT.grammarWish, section: 'Grammar I', title: '"I hope / I wish" — wishes',
    goals: ['Use "I hope + present/will + V" for realistic wishes.', 'Use "I wish + past simple" for unreal/distant wishes.', 'Contrast: "I hope I get into Harvard" (realistic) vs "I wish I were tall" (unreal).'],
    task: 'Make three wish/hope sentences.' },
  { id: ACT.grammarBecome, section: 'Grammar II', title: '"want to be" / "become" — future job',
    goals: ['Form "I want to be + a/an + job".', 'Form "I want to become + a/an + job" — same meaning, slightly more formal.', 'Modify with "good", "successful", "famous".'],
    task: 'State three "want to be/become" sentences.' },
  { id: ACT.grammarAfterBefore, section: 'Grammar III', title: '"after / before + V-ing / N" — sequencing',
    goals: ['Use "after + V-ing / N" for sequence.', 'Use "before + V-ing / N" for prior action.', 'Use "after I + V" / "before I + V" for clauses.'],
    task: 'Sequence three life events.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A career-statement paragraph',
    goals: ['Read a 5-sentence personal-statement-style paragraph.'],
    task: 'Identify the writer\'s dream, path, and reason.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Sharing dreams',
    goals: ['Follow a 6-turn dream-sharing dialogue.'],
    task: 'Reproduce with your own dream.' },
  { id: ACT.writing, section: 'Writing', title: 'My dream',
    goals: ['Write 5-6 sentences about your dream + plan.'],
    task: 'Write your own future plan.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Career paths in the English-speaking world',
    goals: ['Understand US/UK/AU career paths: university → internship → full-time, or trades / community college / gap year.', 'Know terms: STEM, MBA, gap year, side hustle, freelance, startup.'],
    task: 'Compare a career norm from your country with one from the US/UK/AU.' },
  { id: ACT.task, section: 'Task', title: 'Tell your professor your dream',
    goals: ['Combine wish, want-to-be, and time-sequence in a continuous scene.'],
    task: 'Tell the AI tutor (playing your professor) your career dream.' },
];

const lesson = {
  title: 'Level 1 · Unit 21: I hope to become — Hopes & Dreams',
  category: 'career',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'expressing-hopes-en', label: 'Expressing hopes', goal: 'Use "I hope" for realistic, "I wish" for unreal/distant.' },
    { id: 'stating-career-en', label: 'Stating career goals', goal: 'Use "want to be / become + a + job + modifier".' },
    { id: 'sequencing-future-en', label: 'Sequencing future events', goal: 'Use "after / before + V-ing".' },
  ],
  relatedPools: ['topic-career'],
  content: [
    createContentItem('Lesson goal', 'hopes and dreams', 'By end: talk about future career, express wishes, sequence life events.', 'word', 'Functions: dream · wish · become · sequence · plan.', 'Five future-talk micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'career office talk', 'A professor at MIT asks what you want to do after graduating. You explain your dream, the steps, and a timeline.', 'word', 'Professor: "What are your plans?" — You: "I want to become a software engineer. After I graduate, I plan to do an internship in the US."', 'A typical career office conversation.', null, [ACT.orientation]),

    createContentItem('hope /hoʊp/ vs hop /hɒp/', '/hoʊp/ vs /hɒp/', 'Long /oʊ/ vs short /ɒ/ — totally different vowels.', 'word', 'I hope to graduate next year.', 'Don\'t say "I hop to" — that means "jump"!', null, [ACT.pronunciation]),
    createContentItem('wish /wɪʃ/', '/wɪʃ/', 'Voiceless /ʃ/ — soft "sh", no /tʃ/.', 'word', 'I wish I had more time.', 'Compare: "wish" (sh) vs "which" (ch).', null, [ACT.pronunciation]),
    createContentItem('"I\'d" /aɪd/', '/aɪd/', 'Contraction of "I would" or "I had". One syllable.', 'word', 'I\'d like to be a doctor.', 'Context decides "would" or "had" — "I\'d like" = would; "I\'d gone" = had.', null, [ACT.pronunciation]),
    createContentItem('"I wish I were"', '/aɪ wɪʃ aɪ wər/', 'Past subjunctive — use "were" for all subjects in unreal wishes.', 'word', 'I wish I were taller.', 'Some speakers say "I wish I was" — accepted casually, but "were" is standard.', null, [ACT.pronunciation]),

    createContentItem('doctor', '/ˈdɒktər/', 'medical practitioner', 'word', 'I want to be a doctor.', 'Specialties: surgeon, pediatrician, etc.', null, [ACT.vocabularyJobs]),
    createContentItem('nurse', '/nɜːrs/', 'medical caregiver', 'word', 'My sister is a nurse.', 'High-demand profession globally.', null, [ACT.vocabularyJobs]),
    createContentItem('teacher / professor', '/ˈtiːtʃər/ /prəˈfɛsər/', 'educator', 'word', 'I want to be a high school teacher.', 'School: "teacher". University: "professor".', null, [ACT.vocabularyJobs]),
    createContentItem('engineer', '/ˌɛndʒɪˈnɪər/', 'designer/builder of systems', 'word', 'My dream is to be a software engineer.', 'Types: software, mechanical, civil, electrical, chemical.', null, [ACT.vocabularyJobs]),
    createContentItem('programmer / developer', '/ˈproʊɡræmər/ /dɪˈvɛləpər/', 'writes software', 'word', 'She works as a web developer.', 'Often used interchangeably.', null, [ACT.vocabularyJobs]),
    createContentItem('designer', '/dɪˈzaɪnər/', 'visual/UX creator', 'word', 'I want to be a UX designer.', 'Types: graphic, UX, fashion, interior.', null, [ACT.vocabularyJobs]),
    createContentItem('lawyer / attorney', '/ˈlɔːjər/ /əˈtɜːrni/', 'legal professional', 'word', 'My uncle is a lawyer.', 'UK: "lawyer", "solicitor", "barrister". US: "lawyer" or "attorney".', null, [ACT.vocabularyJobs]),
    createContentItem('accountant', '/əˈkaʊntənt/', 'handles finances', 'word', 'An accountant manages taxes for the company.', 'CPA = Certified Public Accountant (US).', null, [ACT.vocabularyJobs]),
    createContentItem('artist', '/ˈɑːrtɪst/', 'creator of visual art', 'word', 'My friend is an artist.', 'Note: takes "an" — vowel sound.', null, [ACT.vocabularyJobs]),
    createContentItem('journalist / reporter', '/ˈdʒɜːrnəlɪst/', 'news writer', 'word', 'A journalist asks good questions.', 'Print, TV, online journalism all common paths.', null, [ACT.vocabularyJobs]),
    createContentItem('chef / cook', '/ʃɛf/ /kʊk/', 'professional / home cook', 'word', 'I want to be a chef.', '"Chef" is professional; "cook" is general/casual.', null, [ACT.vocabularyJobs]),
    createContentItem('entrepreneur', '/ˌɒntrəprəˈnɜːr/', 'business founder', 'word', 'She\'s an entrepreneur with three startups.', 'French loanword; "starts and runs a business".', null, [ACT.vocabularyJobs]),
    createContentItem('scientist / researcher', '/ˈsaɪəntɪst/', 'does research', 'word', 'I want to be a scientist.', 'Types: biologist, chemist, physicist, etc.', null, [ACT.vocabularyJobs]),
    createContentItem('athlete / pro player', '/ˈæθliːt/', 'professional sports player', 'word', 'He\'s a professional athlete.', 'For Olympic / pro-league players.', null, [ACT.vocabularyJobs]),

    createContentItem('dream', '/driːm/', 'long-term life aspiration', 'word', 'My dream is to travel the world.', 'Used for the biggest goals.', null, [ACT.vocabularyFuture]),
    createContentItem('goal', '/ɡoʊl/', 'specific target', 'word', 'My goal this year is to learn English.', 'More concrete than "dream".', null, [ACT.vocabularyFuture]),
    createContentItem('plan', '/plæn/', 'concrete steps', 'word', 'My plan is to graduate, then work for 2 years.', 'Verb: "I plan to go to graduate school".', null, [ACT.vocabularyFuture]),
    createContentItem('future', '/ˈfjuːtʃər/', 'time after now', 'word', 'In the future, I want to live abroad.', 'Often paired with "in the".', null, [ACT.vocabularyFuture]),
    createContentItem('hope', '/hoʊp/', 'desire for good outcome', 'word', 'I hope to find a good job.', 'Noun: "my hope is …". Verb: "I hope + clause".', null, [ACT.vocabularyFuture]),
    createContentItem('graduate', '/ˈɡrædʒueɪt/', 'finish university/school', 'word', 'I graduate in 2026.', 'Verb (with /-eɪt/) vs noun "graduate" /ˈɡrædʒuət/ (a graduate of …).', null, [ACT.vocabularyFuture]),
    createContentItem('get a job', '/ɡɛt ə dʒɒb/', 'be hired', 'word', 'After graduation, I want to get a job at Samsung.', 'Casual standard phrase.', null, [ACT.vocabularyFuture]),
    createContentItem('internship', '/ˈɪntɜːrnʃɪp/', 'short-term, often-unpaid job for students', 'word', 'I did an internship at Google last summer.', 'Critical step in many career paths.', null, [ACT.vocabularyFuture]),
    createContentItem('study abroad', '/ˈstʌdi əˈbrɔːd/', 'study in another country', 'word', 'I want to study abroad in the US.', 'Common for language and resume building.', null, [ACT.vocabularyFuture]),
    createContentItem('work hard', '/wɜːrk hɑːrd/', 'put in effort', 'word', 'I work hard to achieve my goals.', 'Common motivational phrase.', null, [ACT.vocabularyFuture]),
    createContentItem('achieve', '/əˈtʃiːv/', 'successfully reach a goal', 'word', 'She achieved her dream of becoming a CEO.', 'More formal; "reach" is alternative.', null, [ACT.vocabularyFuture]),
    createContentItem('successful', '/səkˈsɛsfʊl/', 'achieved goals', 'word', 'I want to be a successful engineer.', 'Noun: "success" /səkˈsɛs/.', null, [ACT.vocabularyFuture]),

    createContentItem(
      '"I hope + present/will" — realistic wish',
      'achievable future',
      'For wishes that can realistically come true.',
      'sentence',
      'I hope I get into Stanford. — I hope I\'ll find a good job. — I hope the interview goes well.',
      'Two patterns: "hope + present simple" or "hope + will + V". Both fine.',
      [
        { target: 'I hope + present simple', english: 'realistic & near' },
        { target: 'I hope + will + V', english: 'realistic & future' },
        { target: 'I hope to + V', english: 'shorter: "I hope to graduate"' },
      ],
      [ACT.grammarWish],
    ),
    createContentItem(
      '"I wish + past simple" — unreal wish',
      'distant or unreal',
      'For wishes that are not real now (or impossible).',
      'sentence',
      'I wish I were taller. — I wish I had more money. — I wish I could speak French.',
      'Past form but means PRESENT unreal. Use "were" for all subjects formally; "was" accepted casually.',
      [
        { target: 'I wish + past simple', english: 'present unreal' },
        { target: 'I wish + could + V', english: 'wish for ability' },
        { target: 'I wish + would + V', english: 'wish someone else changed' },
      ],
      [ACT.grammarWish],
    ),
    createContentItem(
      '"I hope" vs "I wish" — key distinction',
      'realistic vs unreal',
      'This is one of the biggest English mistakes for new speakers.',
      'sentence',
      'I hope I pass the test. (realistic) — I wish I had studied more. (regret)\nI hope it stops raining. (real possibility) — I wish I were on vacation. (impossible right now)',
      'Test: is it possible? "Hope" = yes. Impossible/unreal? "Wish".',
      [
        { target: '"Hope" = realistic, future', english: 'could really happen' },
        { target: '"Wish" = unreal, regret', english: 'NOT real now or never will be' },
      ],
      [ACT.grammarWish],
    ),

    createContentItem(
      '"want to be / become" + a/an + job',
      'career goal',
      'Standard way to state your career aspiration.',
      'sentence',
      'I want to be a doctor. — I want to become an engineer. — She wants to be a teacher.',
      'Always with "a/an" before the job: "I want to be a doctor", NOT "I want to be doctor".',
      [
        { target: 'I want to be + a/an + job', english: 'standard, casual' },
        { target: 'I want to become + a/an + job', english: 'slightly more formal' },
        { target: 'My dream is to be + a/an + job', english: 'more poetic' },
      ],
      [ACT.grammarBecome],
    ),
    createContentItem(
      'Adding adjectives: "good / successful / famous"',
      'qualified career goal',
      'Add adjectives to specify the kind of professional you want to be.',
      'sentence',
      'I want to be a good doctor. — She wants to be a successful entrepreneur. — He hopes to be a famous chef.',
      'Adjective goes BEFORE the job noun: "a good doctor" — not "a doctor good".',
      [
        { target: 'good + job', english: 'competent, ethical' },
        { target: 'successful + job', english: 'highly accomplished' },
        { target: 'famous + job', english: 'well-known' },
        { target: 'professional + job', english: 'paid expert' },
      ],
      [ACT.grammarBecome],
    ),
    createContentItem(
      '"work as" / "work in" / "work for"',
      'related job vocabulary',
      'Multiple prepositions for jobs.',
      'sentence',
      'I work as a teacher. — I work in marketing. — I work for Samsung.',
      '"As" + job · "in" + field · "for" + company.',
      [
        { target: 'work as + job', english: 'your role' },
        { target: 'work in + field', english: 'industry/area' },
        { target: 'work for + company', english: 'employer' },
      ],
      [ACT.grammarBecome],
    ),

    createContentItem(
      '"after + V-ing / N" — sequence',
      'second event',
      'Mark what happens second.',
      'sentence',
      'After graduating, I want to travel. — After college, I\'ll work for two years. — After I finish school, I plan to study abroad.',
      'After + V-ing OR after + noun OR after + I + V (clause). All fine.',
      [
        { target: 'after + V-ing', english: 'shorter, modern' },
        { target: 'after + N', english: 'after college / after work' },
        { target: 'after + S + V (clause)', english: 'after I graduate' },
      ],
      [ACT.grammarAfterBefore],
    ),
    createContentItem(
      '"before + V-ing / N" — prior',
      'first event',
      'Mark what happens first.',
      'sentence',
      'Before starting work, I want to travel. — Before college, I took a gap year. — Before I graduate, I need to complete my internship.',
      'Same three patterns as "after".',
      [
        { target: 'before + V-ing', english: 'shorter' },
        { target: 'before + N', english: 'before exams / before lunch' },
        { target: 'before + S + V (clause)', english: 'before I leave' },
      ],
      [ACT.grammarAfterBefore],
    ),
    createContentItem(
      '"first / then / finally" — sequencing',
      'multi-step path',
      'Connect multiple steps clearly.',
      'sentence',
      'First, I\'ll graduate. Then, I\'ll do an internship. Finally, I\'ll get a full-time job.',
      'Use commas after sequence words.',
      [
        { target: 'first', english: 'step 1' },
        { target: 'then / next / after that', english: 'middle steps' },
        { target: 'finally / in the end', english: 'last step' },
      ],
      [ACT.grammarAfterBefore],
    ),

    createContentItem(
      'A career statement',
      'reading practice',
      'Read this personal statement aloud.',
      'sentence',
      'My name is Min-su, and I\'m a junior at Massachusetts Institute of Technology. I study computer science because I love solving problems with code. My dream is to become a software engineer at a big tech company. After I graduate, I plan to do an internship in Silicon Valley. I hope my English improves enough to work there for a few years. Then, I want to come back to Korea and start my own company.',
      'Standard personal-statement style.',
      [
        { target: 'I\'m a junior at MIT', english: 'current status' },
        { target: 'My dream is to become', english: 'main goal' },
        { target: 'After I graduate, I plan to', english: 'sequencing' },
        { target: 'I hope my English improves', english: 'hope statement' },
        { target: 'Then, I want to', english: 'further future' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences.',
      'sentence',
      'Q1: What does Min-su study? · Q2: What\'s his dream job? · Q3: What does he plan to do after graduating? · Q4: What\'s his long-term plan?',
      'Use third-person present.',
      [
        { target: 'A1: He studies computer science.', english: 'major' },
        { target: 'A2: He wants to be a software engineer.', english: 'dream' },
        { target: 'A3: He plans to do an internship in Silicon Valley.', english: 'next step' },
        { target: 'A4: He wants to start his own company in Korea.', english: 'long-term' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Sharing dreams',
      'two friends',
      'A casual dream-sharing conversation.',
      'conversation',
      'Sarah: So what do you want to do after college?\nMin-su: Honestly? I want to become a software engineer.\nSarah: Cool! Like at Google or something?\nMin-su: I hope so! Maybe an internship first. What about you?\nSarah: I want to be a journalist. I love writing.\nMin-su: Nice! Where do you want to work?\nSarah: I\'d love to work for The New York Times someday. But first, I need to graduate!\nMin-su: Same. We can do it.',
      'Note casual register: "Honestly?", "Cool!", "I\'d love to".',
      [
        { target: 'I want to become a software engineer', english: 'state career goal' },
        { target: 'I hope so', english: 'agree with optimism' },
        { target: 'I\'d love to work for', english: 'polite want' },
        { target: 'first, I need to graduate', english: 'sequencing' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Professor conversation',
      'formal register',
      'Talking to a professor in office hours.',
      'conversation',
      'Professor Lee: Min-su, what are your plans after graduating?\nMin-su: I want to be a software engineer, Professor. I hope to do an internship abroad first.\nProfessor Lee: That\'s a great goal. Have you applied anywhere?\nMin-su: Not yet. I\'m preparing my resume and improving my English.\nProfessor Lee: Good. If you work hard, I think you can do it. Let me know if you need a reference letter.\nMin-su: Thank you so much, Professor!',
      'Formal markers: "Professor", "Thank you so much".',
      [
        { target: 'I want to be / I hope to', english: 'state goals' },
        { target: 'Have you applied anywhere?', english: 'professor\'s question' },
        { target: 'If you work hard, I think', english: 'encouragement' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'dream-paragraph template',
      'A standard personal-statement structure.',
      'sentence',
      'My name is [name]. I study [major]. My dream is to become a [job + modifier]. After I [milestone], I plan to [next step]. I hope [realistic wish]. Then, I want to [long-term goal].',
      'Six sections: name · major · dream · next step · hope · long-term.',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 5-6 sentences about your dream.',
      'sentence',
      'Example: My name is Sarah. I study English literature at MIT. My dream is to become a successful journalist. After I graduate next year, I plan to do an internship at a newspaper. I hope I can work in New York one day. Then, I want to write a book about my generation.',
      'Use at least one "I hope", one "want to be", and one "after/before".',
      null, [ACT.writing],
    ),

    createContentItem(
      'Career paths in English-speaking countries',
      'big picture',
      'US/UK/AU: university → internship → full-time, OR trades / community college / gap year. Less rigid than East Asian countries; multiple "right" paths.',
      'sentence',
      'Many graduates take a "gap year" before college or after.',
      'A gap year for travel, work, or volunteering is normal and respected.',
      [
        { target: 'university → internship → job', english: 'classic white-collar path' },
        { target: 'trades / community college', english: 'shorter, technical' },
        { target: 'gap year', english: 'year off, common & accepted' },
        { target: 'side hustle / freelance', english: 'multi-income, popular among young' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Career vocabulary',
      'common modern terms',
      'STEM = Science, Technology, Engineering, Math. MBA = Master of Business Administration. Startup = small new company. Side hustle = second income. Freelance = self-employed by project.',
      'sentence',
      'Many tech workers earn extra income with a side hustle.',
      'These terms are common in young-adult career talk.',
      [
        { target: 'STEM', english: 'science + tech + engineering + math' },
        { target: 'MBA', english: 'business graduate degree' },
        { target: 'startup', english: 'new, often tech-driven company' },
        { target: 'side hustle', english: 'extra paid work, often online' },
        { target: 'freelance', english: 'project-based self-employment' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Tell your professor your dream',
      'consolidation task',
      'Roleplay: Tell the AI tutor (your professor) your career dream and plan.',
      'conversation',
      'Tutor: What are your plans after graduating?\nYou: [main career goal with "want to be / become"]\nTutor: [follow-up question about how]\nYou: [plan with "after I + V", "before I + V"]\nTutor: [encouragement + question about a wish]\nYou: [wish with "I hope" or "I wish"]\nTutor: [closing advice]\nYou: [thanks]',
      'AI tutor will play your professor.',
      [
        { target: 'I want to become a + job', english: 'state career goal' },
        { target: 'After I graduate, I plan to + V', english: 'next step' },
        { target: 'I hope + clause', english: 'realistic wish' },
        { target: 'Thank you, Professor', english: 'polite closing' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
