// Level 1 Unit 2 — Classroom & Everyday Objects (English)
// Functions: identifying objects, locating things, borrowing items, has/has-not.
//
// All content is authored in English (the target). The AI conversation tutor
// reads this curriculum and delivers it to each learner in their preferred
// native language at runtime — never assume a specific L1 in this file.

const createContentItem = (
  target,
  ipa,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization: ipa,
  nativeText: note,
  pronunciation: ipa,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u2-orientation',
  pronunciation: 'en-l1u2-pronunciation',
  vocabularyObjects: 'en-l1u2-vocab-objects',
  vocabularyLocations: 'en-l1u2-vocab-locations',
  grammarDemonstratives: 'en-l1u2-grammar-demonstratives',
  grammarHave: 'en-l1u2-grammar-have',
  grammarPrepositions: 'en-l1u2-grammar-prepositions',
  reading: 'en-l1u2-reading',
  listening: 'en-l1u2-listening',
  writing: 'en-l1u2-writing',
  culture: 'en-l1u2-culture',
  task: 'en-l1u2-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Identify and name common classroom and desk objects.',
      'Locate items with on / in / under / next to / behind.',
      'Ask whether someone has something using "have / has".',
      'Use "this / that / these / those" correctly by distance.',
    ],
    task: 'Imagine your first English class — pointing at things on the desk, asking what they are, borrowing a pen.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in this lesson',
    goals: [
      'Distinguish /θ/ in "thing" from /ð/ in "this".',
      'Pronounce /v/ in "have" with teeth on the lower lip — not /b/.',
      'Use the weak forms /ə/ in "a book", /ðə/ in "the table".',
    ],
    task: 'Read each example aloud and feel the throat vibration.',
  },
  {
    id: ACT.vocabularyObjects,
    section: 'Vocabulary I',
    title: 'Classroom and personal objects',
    goals: ['Name 18+ common classroom, desk, and bag items.'],
    task: 'Point to five things around you and name each in English.',
  },
  {
    id: ACT.vocabularyLocations,
    section: 'Vocabulary II',
    title: 'Location prepositions',
    goals: ['Use on, in, under, next to, behind, in front of, between, near.'],
    task: 'Describe where three objects are in the room.',
  },
  {
    id: ACT.grammarDemonstratives,
    section: 'Grammar I',
    title: 'this / that / these / those',
    goals: [
      'Use "this" / "that" for one item near / far.',
      'Use "these" / "those" for multiple items near / far.',
      'Form "What is this?" / "What are these?" correctly.',
    ],
    task: 'Make four pointing sentences with each demonstrative.',
  },
  {
    id: ACT.grammarHave,
    section: 'Grammar II',
    title: 'have / has (+ contractions, negation)',
    goals: [
      'Conjugate "have" / "has" (I/you/we/they have; he/she/it has).',
      'Negate with "do not have" / "does not have".',
      'Form yes/no questions: "Do you have…?" / "Does she have…?"',
    ],
    task: 'Make three "have" sentences in three forms (statement, negative, question).',
  },
  {
    id: ACT.grammarPrepositions,
    section: 'Grammar III',
    title: 'Location prepositions in sentences',
    goals: [
      'Form "There is" / "There are" + location preposition.',
      'Use the right preposition for surface (on), enclosure (in), beneath (under), side (next to).',
      'Combine with the definite article: on THE desk / in THE bag.',
    ],
    task: 'Make three "there is/are" sentences locating items.',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Describe a classroom',
    goals: ['Read a short classroom description and answer questions.'],
    task: 'Read the paragraph and answer: What is on the desk? Where is the bag?',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'Borrowing a pen',
    goals: ['Follow a short borrowing dialogue.', 'Reproduce it with your own items.'],
    task: 'Listen / read, then borrow a different item from the AI tutor.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Describe what is on your desk',
    goals: ['Write 3–4 sentences with "there is/are" and location prepositions.'],
    task: 'Write 3–4 sentences describing your desk right now.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'Classroom etiquette in English-speaking schools',
    goals: [
      'Raise your hand to speak — do not call out.',
      'Address teachers by Mr./Ms./Dr./Professor + last name.',
      'Asking "Can I borrow…?" is friendly; "Give me…" sounds rude.',
    ],
    task: 'Decide the right way to ask for a pen in three settings.',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'Show me what is on your desk',
    goals: ['Combine vocabulary, demonstratives, have, and location in one scene.'],
    task: 'Describe your desk to the AI tutor turn by turn — answer their follow-up questions.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 2: What is this? — Classroom and Everyday Objects',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-what-this-is', label: 'Asking what something is', goal: 'Use "What is this/that?" and respond.' },
    { id: 'asking-if-someone-has', label: 'Asking if someone has something', goal: 'Use "Do you have…?" / "Does he have…?"' },
    { id: 'locating-object', label: 'Locating an object', goal: 'Use "There is/are" + on / in / under / next to.' },
    { id: 'borrowing-politely', label: 'Borrowing politely', goal: 'Use "Can I borrow…?" instead of "Give me…".' },
  ],
  relatedPools: ['topic-school'],
  content: [
    // Activity 1 — Orientation
    createContentItem(
      'Lesson goal',
      'classroom & objects',
      'By the end of this lesson, you can name 18+ classroom objects, point at things and say "this/that/these/those", locate items with prepositions, and politely borrow things from a classmate.',
      'word',
      'Functions: identify · locate · ask has/has-not · borrow politely.',
      'These skills cover most everyday object talk in English.',
      null,
      [ACT.orientation],
    ),
    createContentItem(
      'Real-world scenario',
      'first English class',
      'It is your first English class. The teacher writes new vocabulary on the board. The student next to you forgot their pen.',
      'word',
      'Classmate: "Excuse me, can I borrow a pen?" — You: "Sure, here you go."',
      'A typical polite peer-to-peer exchange.',
      null,
      [ACT.orientation],
    ),

    // Activity 2 — Pronunciation
    createContentItem(
      'this vs thing',
      '/ðɪs/ vs /θɪŋ/',
      'Two "th" sounds — voiced /ð/ (this, that, the) vs voiceless /θ/ (thing, think, three). Both place the tongue tip between the teeth.',
      'word',
      'this /ðɪs/ · that /ðæt/ · thing /θɪŋ/ · three /θriː/',
      'Touch your throat: /ð/ buzzes; /θ/ is silent.',
      [
        { target: '/ð/ — voiced', note: 'this, that, these, those, the, they — function words' },
        { target: '/θ/ — voiceless', note: 'thing, think, three, thank — mostly content words' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'have / has',
      '/hæv/ /hæz/',
      'Upper teeth touch the lower lip with throat vibration for /v/ and /z/. Not /b/ at the end of "have".',
      'word',
      'I have a book. /aɪ hæv ə bʊk/ · She has a pen. /ʃiː hæz ə pɛn/',
      'In fast speech "have" often weakens to /həv/ or /əv/.',
      null,
      [ACT.pronunciation],
    ),
    createContentItem(
      'a / an / the — weak forms',
      '/ə/ /ən/ /ðə/',
      'Articles are almost always unstressed and reduce to schwa.',
      'sentence',
      'a book /ə bʊk/ · an apple /ən ˈæpl/ · the desk /ðə dɛsk/',
      'Stressed articles ("THE answer") signal emphasis; default is weak /ðə/.',
      null,
      [ACT.pronunciation],
    ),
    createContentItem(
      'these / those',
      '/ðiːz/ /ðoʊz/',
      'Plural demonstratives. /ðiːz/ ends in /z/ (voiced); /ðoʊz/ ends in /z/ too. Both start with /ð/.',
      'word',
      'these books /ðiːz bʊks/ · those pens /ðoʊz pɛnz/',
      'Distinguish from "this" /ðɪs/ and "that" /ðæt/ which end in /s/ and /t/.',
      null,
      [ACT.pronunciation],
    ),

    // Activity 3 — Vocabulary I: Objects
    createContentItem('book', '/bʊk/', 'a bound set of printed pages', 'word', 'The book is on the desk.', 'A countable noun; plural "books".', null, [ACT.vocabularyObjects]),
    createContentItem('notebook', '/ˈnoʊtbʊk/', 'a book of blank pages for writing notes', 'word', 'I write in my notebook.', 'Compound noun; the stress is on the first syllable.', null, [ACT.vocabularyObjects]),
    createContentItem('pencil', '/ˈpɛnsəl/', 'a slim writing tool with graphite inside', 'word', 'Lend me a pencil, please.', 'Plural "pencils".', null, [ACT.vocabularyObjects]),
    createContentItem('pen', '/pɛn/', 'a writing tool with ink', 'word', 'Do you have a pen?', 'Note: "ball-point pen" is a more specific form.', null, [ACT.vocabularyObjects]),
    createContentItem('eraser', '/ɪˈreɪsər/', 'a small block used to remove pencil marks', 'word', 'Use the eraser.', 'British English: "rubber" (same item).', null, [ACT.vocabularyObjects]),
    createContentItem('ruler', '/ˈruːlər/', 'a straight tool used to measure or draw lines', 'word', 'Use a ruler to draw a line.', 'Standard 30 cm length in classrooms.', null, [ACT.vocabularyObjects]),
    createContentItem('chair', '/tʃɛr/', 'a piece of furniture for one person to sit on', 'word', 'Please sit on the chair.', 'Singular; plural "chairs".', null, [ACT.vocabularyObjects]),
    createContentItem('desk', '/dɛsk/', 'a flat work surface, usually with drawers', 'word', 'The book is on my desk.', 'Distinct from "table" — desks are for work.', null, [ACT.vocabularyObjects]),
    createContentItem('table', '/ˈteɪbəl/', 'a flat surface on legs, used for eating or working', 'word', 'Put the cups on the table.', 'Used in homes; "desk" is for study/office.', null, [ACT.vocabularyObjects]),
    createContentItem('board', '/bɔːrd/', 'the surface at the front of the classroom for writing', 'word', 'The teacher writes on the board.', '"Whiteboard" or "blackboard" depending on type.', null, [ACT.vocabularyObjects]),
    createContentItem('bag', '/bæɡ/', 'a container with a handle, often used to carry books', 'word', 'My bag is heavy today.', 'Also "backpack" for one worn on the shoulders.', null, [ACT.vocabularyObjects]),
    createContentItem('clock', '/klɒk/', 'a device that shows the time', 'word', 'There is a clock in the classroom.', 'A "watch" is worn on the wrist.', null, [ACT.vocabularyObjects]),
    createContentItem('computer', '/kəmˈpjuːtər/', 'an electronic machine for processing data', 'word', 'I use a computer to study.', 'Stress on the second syllable: com-PU-ter.', null, [ACT.vocabularyObjects]),
    createContentItem('laptop', '/ˈlæptɒp/', 'a portable computer', 'word', 'My laptop is new.', 'Compound noun; stress on the first syllable.', null, [ACT.vocabularyObjects]),
    createContentItem('phone', '/foʊn/', 'a mobile telephone', 'word', 'Where is my phone?', 'Short for "smartphone" or "cell phone".', null, [ACT.vocabularyObjects]),
    createContentItem('glasses', '/ˈɡlæsəz/', 'lenses worn on the face to help you see', 'word', 'I wear glasses.', 'Always plural — no singular form for the pair.', null, [ACT.vocabularyObjects]),
    createContentItem('wallet', '/ˈwɒlət/', 'a small folding case for cards and money', 'word', 'My wallet is in my bag.', 'British English: same word.', null, [ACT.vocabularyObjects]),
    createContentItem('umbrella', '/ʌmˈbrɛlə/', 'a folding rain cover with a handle', 'word', 'Take your umbrella — it is raining.', 'Stress on the second syllable.', null, [ACT.vocabularyObjects]),
    createContentItem('classroom', '/ˈklɑːsruːm/', 'a room where students learn', 'word', 'Our classroom is on the third floor.', 'Compound; stress on the first syllable.', null, [ACT.vocabularyObjects]),

    // Activity 4 — Vocabulary II: Location prepositions
    createContentItem('on', '/ɒn/', 'in contact with the top surface of something', 'word', 'The book is on the desk.', 'Surface contact — top, side, or wall.', null, [ACT.vocabularyLocations]),
    createContentItem('in', '/ɪn/', 'inside / contained within', 'word', 'My phone is in my bag.', 'Enclosure — inside a container.', null, [ACT.vocabularyLocations]),
    createContentItem('under', '/ˈʌndər/', 'in or to a lower position than something', 'word', 'My bag is under the chair.', 'Synonym: "beneath" (more formal).', null, [ACT.vocabularyLocations]),
    createContentItem('next to', '/nɛkst tu/', 'beside / at the side of', 'word', 'My friend is next to me.', 'Two words; very common in everyday English.', null, [ACT.vocabularyLocations]),
    createContentItem('behind', '/bɪˈhaɪnd/', 'at the back of', 'word', 'The board is behind the teacher.', 'Stress on the second syllable.', null, [ACT.vocabularyLocations]),
    createContentItem('in front of', '/ɪn frʌnt ʌv/', 'directly facing or before', 'word', 'I sit in front of the board.', 'Three-word phrase, treated as one preposition.', null, [ACT.vocabularyLocations]),
    createContentItem('between', '/bɪˈtwiːn/', 'in the space separating two things', 'word', 'The pen is between the books.', 'Use with two items only; for three+, use "among".', null, [ACT.vocabularyLocations]),
    createContentItem('near', '/nɪər/', 'close to', 'word', 'My desk is near the window.', 'Less specific than "next to".', null, [ACT.vocabularyLocations]),
    createContentItem('here / there', '/hɪər/ /ðɛr/', 'here = at this location; there = at that location', 'word', 'My bag is here. Yours is there.', '"Here" — close to speaker; "there" — away from speaker.', null, [ACT.vocabularyLocations]),

    // Activity 5 — Grammar I: this / that / these / those
    createContentItem(
      'this — singular, near',
      '/ðɪs/',
      'One item, close to the speaker.',
      'sentence',
      'This is a book. / What is this?',
      'For one item the listener can see or touch close to you.',
      [
        { target: 'This is a pen.', note: 'pointing to one nearby item' },
        { target: 'What is this?', note: 'asking about one nearby item' },
      ],
      [ACT.grammarDemonstratives],
    ),
    createContentItem(
      'that — singular, far',
      '/ðæt/',
      'One item, far from the speaker.',
      'sentence',
      'That is a clock. / What is that?',
      'For one item across the room, on the wall, or visible at a distance.',
      [
        { target: 'That is my bag.', note: 'pointing across the room' },
        { target: 'What is that?', note: 'asking about a far item' },
      ],
      [ACT.grammarDemonstratives],
    ),
    createContentItem(
      'these — plural, near',
      '/ðiːz/',
      'Multiple items close to the speaker.',
      'sentence',
      'These are my books. / What are these?',
      'Verb shifts to plural: "These ARE" (not "These is").',
      [
        { target: 'These are my pens.', note: 'pointing to multiple nearby items' },
        { target: 'What are these?', note: 'asking about multiple nearby items' },
      ],
      [ACT.grammarDemonstratives],
    ),
    createContentItem(
      'those — plural, far',
      '/ðoʊz/',
      'Multiple items far from the speaker.',
      'sentence',
      'Those are my classmates. / What are those?',
      'Use with "are", not "is".',
      [
        { target: 'Those are my friends.', note: 'pointing across the room at multiple people' },
        { target: 'What are those?', note: 'asking about multiple far items' },
      ],
      [ACT.grammarDemonstratives],
    ),

    // Activity 6 — Grammar II: have / has
    createContentItem(
      'have / has — full conjugation',
      'I have, she has',
      '"Have" changes to "has" only with he/she/it. All other subjects use "have".',
      'sentence',
      'I have a book. You have a pen. He has a phone. She has a bag. We have laptops. They have notebooks.',
      'Only the third-person singular takes "has".',
      [
        { target: 'I / you / we / they HAVE', note: 'most subjects' },
        { target: 'he / she / it HAS', note: 'third-person singular only' },
      ],
      [ACT.grammarHave],
    ),
    createContentItem(
      'Negation — do not have / does not have',
      'don\'t / doesn\'t',
      'Negate with "do not" or "does not" before "have". Contractions are usual: don\'t / doesn\'t.',
      'sentence',
      'I don\'t have a pen. She doesn\'t have a laptop.',
      'Use "doesn\'t" only with he/she/it; "don\'t" with all others.',
      [
        { target: 'I/you/we/they don\'t have', note: 'standard negative' },
        { target: 'he/she/it doesn\'t have', note: 'third-person singular negative' },
      ],
      [ACT.grammarHave],
    ),
    createContentItem(
      'Yes/no question — Do you have? / Does she have?',
      'Do/Does + subject + have',
      'Use "Do" or "Does" before the subject, then the bare verb "have".',
      'sentence',
      'Do you have a pen? — Yes, I do. / No, I don\'t.\nDoes she have a phone? — Yes, she does. / No, she doesn\'t.',
      'Note the answer pattern: short with the auxiliary, not "have/has".',
      [
        { target: 'Do you have…?', note: 'most subjects' },
        { target: 'Does he have…?', note: 'third-person singular only' },
        { target: 'Yes, I do. / No, I don\'t.', note: 'short answers — use the auxiliary' },
      ],
      [ACT.grammarHave],
    ),
    createContentItem(
      'Borrowing politely — Can I borrow…?',
      'modal request',
      'Use "Can I borrow…?" to politely ask for an item. Pair with "please" for extra politeness.',
      'sentence',
      'Can I borrow a pen, please? — Sure, here you go.',
      'Alternative: "May I borrow…?" (more formal).',
      null,
      [ACT.grammarHave],
    ),

    // Activity 7 — Grammar III: Location prepositions in sentences
    createContentItem(
      'There is / There are — existence',
      'there is / there are',
      'Use "There is" for one item, "There are" for two or more. State what exists and where.',
      'sentence',
      'There is a book on the desk. — There are pens in the bag.',
      'Common contractions: "There\'s" (= there is) — informal but very common.',
      [
        { target: 'There is a clock on the wall.', note: 'one item' },
        { target: 'There are books on the desk.', note: 'multiple items' },
        { target: 'There\'s a phone in my bag.', note: 'casual contraction' },
      ],
      [ACT.grammarPrepositions],
    ),
    createContentItem(
      'on the desk',
      'surface contact',
      '"On" with a flat top surface — desk, table, floor, wall.',
      'sentence',
      'My book is on the desk. — The clock is on the wall.',
      'Surface need not be horizontal; "on the wall" is fine.',
      null,
      [ACT.grammarPrepositions],
    ),
    createContentItem(
      'in the bag',
      'enclosure',
      '"In" with something contained inside another thing.',
      'sentence',
      'My phone is in my bag. — The students are in the classroom.',
      'Use "in" for enclosure, "into" for movement entering.',
      null,
      [ACT.grammarPrepositions],
    ),
    createContentItem(
      'next to / between',
      'side / two-side',
      '"Next to" — beside one thing. "Between" — in the space separating two things.',
      'sentence',
      'My chair is next to the door. — The pen is between the books.',
      'Use "between" only with two items; "among" for three or more.',
      null,
      [ACT.grammarPrepositions],
    ),

    // Activity 8 — Reading
    createContentItem(
      'Describing my classroom',
      'reading practice',
      'Read this paragraph aloud, then answer the questions.',
      'sentence',
      'This is my classroom. There is a big board at the front. The board is white. There are 20 desks and 20 chairs. On my desk, there is a book, a notebook, and a pen. My bag is under the chair. There is a clock on the wall, next to the door. Our classroom is on the third floor.',
      'A clear five-sentence description using "there is/are" and several prepositions.',
      [
        { target: 'There is a big board', note: 'existence — one item' },
        { target: 'There are 20 desks', note: 'existence — multiple items' },
        { target: 'On my desk, there is a book', note: 'location + existence' },
        { target: 'My bag is under the chair', note: 'subject-first version' },
        { target: 'next to the door', note: 'two-word preposition' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension questions',
      'answer in English',
      'Answer each in one short sentence based on the paragraph.',
      'sentence',
      'Q1: How many desks are there? · Q2: Where is the clock? · Q3: Where is the bag?',
      'Use full short answers.',
      [
        { target: 'A1: There are 20 desks.', note: 'short factual reply' },
        { target: 'A2: It is on the wall, next to the door.', note: 'location' },
        { target: 'A3: It is under the chair.', note: 'location' },
      ],
      [ACT.reading],
    ),

    // Activity 9 — Listening
    createContentItem(
      'Borrowing a pen',
      'classmate dialogue',
      'Two classmates need supplies. Read along, then redo with different items.',
      'conversation',
      'A: Sarah, can I borrow a pen, please?\nB: Sure! Here you go.\nA: Thanks. Do you also have an eraser?\nB: No, I don\'t — sorry. I only have pens and a ruler.\nA: No problem. Just the pen, then. Thanks again.\nB: You\'re welcome.',
      'Standard politeness pattern: ask, thank, deflect, close.',
      [
        { target: 'Can I borrow…?', note: 'polite request' },
        { target: 'Sure / Here you go', note: 'casual yes' },
        { target: 'Do you have…?', note: 'follow-up question' },
        { target: 'No, I don\'t — sorry', note: 'polite refusal' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'What is this?',
      'pointing dialogue',
      'A asks about three objects on B\'s desk. Read, then describe your own desk.',
      'conversation',
      'A: What is this?\nB: That\'s my English textbook.\nA: And what is that?\nB: Oh, that\'s my new laptop.\nA: Cool! Whose bag is next to the desk?\nB: That\'s mine.',
      'Use "this" for items near, "that" for items farther.',
      [
        { target: 'this / that', note: 'singular near / far' },
        { target: 'mine', note: 'possessive pronoun for "my bag"' },
      ],
      [ACT.listening],
    ),

    // Activity 10 — Writing
    createContentItem(
      'Model: describing your desk',
      'writing template',
      'Follow this model to describe your own desk in 3–5 sentences.',
      'sentence',
      'There is a book and a notebook on my desk. My bag is next to the chair. In the bag, there is a phone and a wallet. There is no umbrella today.',
      'Use "there is/are" + at least two location prepositions.',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 3–5 sentences describing your real desk right now. Use at least two prepositions and one "there is/are".',
      'sentence',
      'Hint: On the desk there is __ . My bag is __ the chair. In the bag there is __ and __ .',
      'Check: subject + verb + preposition + place.',
      null,
      [ACT.writing],
    ),

    // Activity 11 — Culture
    createContentItem(
      'Raise your hand',
      'classroom etiquette',
      'In most English-speaking schools, raise your hand and wait to be called on before speaking. Calling out is considered rude.',
      'sentence',
      'Sarah raised her hand. The teacher said, "Yes, Sarah?"',
      'Even in informal classes, this remains the safe default.',
      [
        { target: 'raise your hand', note: 'standard signal to speak' },
        { target: '"Yes, [name]?"', note: 'teacher gives permission to speak' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Addressing teachers',
      'titles and last names',
      'Address teachers with Mr./Ms./Dr./Professor + LAST name (not first). Wait for the teacher to invite first-name use.',
      'sentence',
      'Mr. Smith / Ms. Lee / Dr. Park / Professor Choi',
      'Calling a teacher only by first name without permission is too casual in most cultures.',
      null,
      [ACT.culture],
    ),
    createContentItem(
      'Polite requests beat commands',
      '"Can I…?" not "Give me…"',
      'English strongly prefers requests over commands, even with peers. "Can I borrow a pen?" is friendly; "Give me a pen" sounds rude.',
      'sentence',
      '✓ Can I borrow a pen, please?\n✗ Give me a pen.',
      'Add "please" for extra politeness; never optional with strangers.',
      [
        { target: 'Can I borrow…?', note: 'standard polite request' },
        { target: 'Could you pass me…?', note: 'slightly more formal' },
        { target: 'Give me…', note: 'avoid — sounds rude in English' },
      ],
      [ACT.culture],
    ),

    // Activity 12 — Task
    createContentItem(
      'Task: Show me your desk',
      'consolidation task',
      'Roleplay: You are video-calling a friend. They ask "What\'s on your desk?" — describe it using everything from this lesson.',
      'conversation',
      'Friend: What\'s on your desk today?\nYou: [list 3–4 items with location]\nFriend: What is this? (points at something)\nYou: [identify + locate]\nFriend: Do you have an eraser?\nYou: [yes / no with appropriate answer]\nFriend: Can I borrow your notebook later?\nYou: [polite agree or decline]',
      'AI tutor will play the friend.',
      [
        { target: 'There is/are __ on/in __', note: 'existence + location' },
        { target: 'This is / That is __', note: 'identify by distance' },
        { target: 'Yes, I do / No, I don\'t', note: 'short answer pattern' },
        { target: 'Sure / Of course', note: 'polite agreement' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
