// Level 1 Unit 9 — Ordering Food (English)
// Functions: ordering at a restaurant, asking for recommendations, paying the bill.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u9-orientation',
  pronunciation: 'en-l1u9-pronunciation',
  vocabularyDishes: 'en-l1u9-vocab-dishes',
  vocabularyDrinks: 'en-l1u9-vocab-drinks',
  vocabularyTable: 'en-l1u9-vocab-table',
  grammarOrder: 'en-l1u9-grammar-order',
  grammarRequest: 'en-l1u9-grammar-request',
  grammarLikeWant: 'en-l1u9-grammar-like-want',
  reading: 'en-l1u9-reading',
  listening: 'en-l1u9-listening',
  writing: 'en-l1u9-writing',
  culture: 'en-l1u9-culture',
  task: 'en-l1u9-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Order food and drinks politely.', 'Ask for recommendations.', 'Request more / less / no / extra.', 'Pay and tip appropriately.'],
    task: 'Imagine taking a friend out to dinner — order, request, and pay confidently.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Restaurant phrases',
    goals: ['Connected speech: "Can I have" → /kənaɪ hæv/.', '"Would you like…?" — note "would you" /wʊdʒə/.'],
    task: 'Read each phrase aloud.' },
  { id: ACT.vocabularyDishes, section: 'Vocabulary I', title: 'Common dishes',
    goals: ['Name dishes in English: pasta, burger, salad, pizza, soup, sandwich.'],
    task: 'Pick three you would order tonight.' },
  { id: ACT.vocabularyDrinks, section: 'Vocabulary II', title: 'Drinks',
    goals: ['Name drinks: water, coffee, tea, soda, juice, beer, wine.'],
    task: 'Choose a drink for breakfast, lunch, dinner.' },
  { id: ACT.vocabularyTable, section: 'Vocabulary III', title: 'Table & service words',
    goals: ['Use menu, server, bill/check, tip, takeout, delivery.'],
    task: 'Read a menu and identify each part.' },
  { id: ACT.grammarOrder, section: 'Grammar I', title: '"I\'ll have…" / "Could I have…?"',
    goals: ['Use "I\'ll have / I\'ll get" to order (American).', 'Use "Could I have, please" for polite (British/formal).'],
    task: 'Make 3 orders with each form.' },
  { id: ACT.grammarRequest, section: 'Grammar II', title: 'Requests: more / less / no / extra / on the side',
    goals: ['Use "extra" for added; "no" for omit; "on the side" for separate.'],
    task: 'Customize 3 orders.' },
  { id: ACT.grammarLikeWant, section: 'Grammar III', title: '"Would you like…?" / "Do you want…?"',
    goals: ['"Would you like" — polite offer.', '"Do you want" — casual.', 'Always answer with "Yes, please" or "No, thanks".'],
    task: 'Practice offers and replies.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A restaurant review',
    goals: ['Read a 5-sentence restaurant review.'],
    task: 'Identify the restaurant, dishes, prices, and verdict.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Ordering at a restaurant',
    goals: ['Follow a full restaurant flow.'],
    task: 'Reproduce with your own choices.' },
  { id: ACT.writing, section: 'Writing', title: 'Recommend a dish',
    goals: ['Write 4–5 sentences recommending a dish or place.'],
    task: 'Write your own recommendation.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Restaurant etiquette in English-speaking countries',
    goals: ['Wait to be seated.', 'Tip 15–20% (US) on the pre-tax total.', 'Split the bill is common: "Let\'s split it."'],
    task: 'Decide who pays and how much to tip in three scenarios.' },
  { id: ACT.task, section: 'Task', title: 'Take a friend to dinner',
    goals: ['Combine ordering, customizing, paying, and tipping in one continuous scene.'],
    task: 'Roleplay a full dinner.' },
];

const lesson = {
  title: 'Level 1 · Unit 9: I\'ll have a burger — Ordering Food',
  category: 'food',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'suggesting-food', label: 'Suggesting where to eat', goal: 'Use "Let\'s go to…" or "How about…?".' },
    { id: 'ordering-food', label: 'Ordering food', goal: 'Use "I\'ll have / Could I have…".' },
    { id: 'paying-bill', label: 'Paying the bill', goal: 'Use "The bill, please" or "Could we get the check?".' },
    { id: 'customizing-order', label: 'Customizing the order', goal: 'Use "extra / no / on the side".' },
  ],
  relatedPools: ['topic-food'],
  content: [
    createContentItem('Lesson goal', 'restaurant flow', 'By end: order dishes, customize, pay, tip — full restaurant scene confidently.', 'word', 'Functions: order · customize · pay · tip.', 'Four restaurant micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'dinner with a friend', 'You\'re at a casual restaurant. The server asks "Are you ready to order?" — you order food, drinks, and a side, then pay the bill.', 'word', 'Server: "Are you ready to order?" — You: "Yes, I\'ll have the chicken sandwich and a Coke, please."', 'A typical American casual dining exchange.', null, [ACT.orientation]),

    createContentItem('Can I have → /kənaɪ/', '/kənaɪ hæv/', 'Connected speech: "Can I" runs together as /kənaɪ/.', 'word', 'Can I have a menu? /kənaɪ hæv ə ˈmɛnjuː/', 'Don\'t pause between "can" and "I".', null, [ACT.pronunciation]),
    createContentItem('Would you → /wʊdʒə/', '/wʊdʒə/', '"Would you" assimilates to /wʊdʒə/ in fast speech.', 'word', 'Would you like a drink? /wʊdʒə laɪk ə drɪŋk/', 'A typical /d/+/j/ → /dʒ/ blend.', null, [ACT.pronunciation]),
    createContentItem('check / bill', '/tʃɛk/ vs /bɪl/', 'In American English "check" is more common for the restaurant total. In British English "bill" is standard.', 'word', 'Can we have the check, please? (US) — Can we have the bill, please? (UK)', 'In context, both are understood.', null, [ACT.pronunciation]),
    createContentItem('chef /ʃɛf/', '/ʃɛf/', '/ʃ/ at the start — same as "shoe".', 'word', 'The chef recommends the pasta.', 'French-origin word.', null, [ACT.pronunciation]),

    createContentItem('burger', '/ˈbɜːrɡər/', 'a beef patty in a bun', 'word', 'I\'ll have a cheeseburger.', 'Short for "hamburger".', null, [ACT.vocabularyDishes]),
    createContentItem('sandwich', '/ˈsænwɪtʃ/', 'meat or filling between two slices of bread', 'word', 'A chicken sandwich, please.', 'Plural: sandwiches.', null, [ACT.vocabularyDishes]),
    createContentItem('pizza', '/ˈpiːtsə/', 'flat bread with toppings', 'word', 'Let\'s order pizza.', 'Often by the slice or whole pie.', null, [ACT.vocabularyDishes]),
    createContentItem('pasta', '/ˈpɑːstə/', 'Italian noodle dish', 'word', 'The pasta is delicious.', 'Uncountable; do not pluralize.', null, [ACT.vocabularyDishes]),
    createContentItem('salad', '/ˈsæləd/', 'mix of raw vegetables', 'word', 'I\'ll have a Caesar salad.', '', null, [ACT.vocabularyDishes]),
    createContentItem('soup', '/suːp/', 'liquid food, often warm', 'word', 'Tomato soup, please.', 'Uncountable usually; "a bowl of soup" is countable.', null, [ACT.vocabularyDishes]),
    createContentItem('chicken', '/ˈtʃɪkən/', 'meat from chicken', 'word', 'I\'ll have the grilled chicken.', 'Same word for the animal and the meat.', null, [ACT.vocabularyDishes]),
    createContentItem('steak', '/steɪk/', 'a thick slice of meat (usually beef)', 'word', 'Could I have a medium steak?', 'Common doneness terms: rare, medium-rare, medium, well-done.', null, [ACT.vocabularyDishes]),
    createContentItem('fries', '/fraɪz/', 'fried potato strips (US)', 'word', 'A side of fries.', 'British: "chips".', null, [ACT.vocabularyDishes]),
    createContentItem('dessert', '/dɪˈzɜːrt/', 'sweet course at end of meal', 'word', 'What\'s for dessert?', 'Distinct from "desert" /ˈdɛzərt/ (sandy area).', null, [ACT.vocabularyDishes]),

    createContentItem('water', '/ˈwɔːtər/', 'plain water', 'word', 'Could I have a glass of water?', 'Uncountable; usually free in restaurants.', null, [ACT.vocabularyDrinks]),
    createContentItem('coffee', '/ˈkɔːfi/', 'hot drink made from beans', 'word', 'A coffee, please.', 'Order styles: black, with milk, latte, cappuccino, etc.', null, [ACT.vocabularyDrinks]),
    createContentItem('tea', '/tiː/', 'hot drink made from tea leaves', 'word', 'I\'ll have an iced tea.', 'British "tea" often implies "black tea with milk".', null, [ACT.vocabularyDrinks]),
    createContentItem('soda / soft drink', '/ˈsoʊdə/', 'carbonated sweet drink (Coke, Sprite)', 'word', 'A Coke, please.', 'American "soda" / British "fizzy drink".', null, [ACT.vocabularyDrinks]),
    createContentItem('juice', '/dʒuːs/', 'fruit drink', 'word', 'Orange juice, please.', 'Often "OJ" in casual speech.', null, [ACT.vocabularyDrinks]),
    createContentItem('beer', '/bɪər/', 'alcoholic drink, fermented grain', 'word', 'Two beers, please.', 'Countable when ordering.', null, [ACT.vocabularyDrinks]),
    createContentItem('wine', '/waɪn/', 'alcoholic drink from grapes', 'word', 'A glass of red wine.', 'Types: red, white, rose.', null, [ACT.vocabularyDrinks]),
    createContentItem('milk', '/mɪlk/', 'white liquid from cows', 'word', 'Milk in my coffee, please.', 'Uncountable.', null, [ACT.vocabularyDrinks]),

    createContentItem('menu', '/ˈmɛnjuː/', 'list of available food and drinks', 'word', 'Could I see the menu?', 'Standard request when seated.', null, [ACT.vocabularyTable]),
    createContentItem('server / waiter / waitress', '/ˈsɜːrvər/', 'person who takes orders and brings food', 'word', 'Our server is friendly.', '"Server" is gender-neutral and preferred in modern usage.', null, [ACT.vocabularyTable]),
    createContentItem('bill / check', '/bɪl/ /tʃɛk/', 'the total to pay', 'word', 'Could we have the check?', 'US: "check"; UK: "bill".', null, [ACT.vocabularyTable]),
    createContentItem('tip', '/tɪp/', 'extra money for service', 'word', 'Don\'t forget the tip.', 'Verb or noun.', null, [ACT.vocabularyTable]),
    createContentItem('takeout / takeaway', '/ˈteɪkaʊt/', 'food to take home', 'word', 'For here or to go?', 'US: "takeout" / "to go"; UK: "takeaway".', null, [ACT.vocabularyTable]),
    createContentItem('delivery', '/dɪˈlɪvəri/', 'food brought to your home', 'word', 'Let\'s order delivery.', '', null, [ACT.vocabularyTable]),
    createContentItem('appetizer / starter', '/ˈæpətaɪzər/', 'first course', 'word', 'For an appetizer, I\'ll have soup.', 'US: "appetizer"; UK: "starter".', null, [ACT.vocabularyTable]),
    createContentItem('main course / entree', '/meɪn kɔːrs/', 'main dish', 'word', 'The steak is the main course.', 'US: "entree"; UK: "main course".', null, [ACT.vocabularyTable]),
    createContentItem('side / side dish', '/saɪd/', 'small dish accompanying the main', 'word', 'A side of fries, please.', '', null, [ACT.vocabularyTable]),
    createContentItem('order', '/ˈɔːrdər/', 'request food / drink', 'word', 'Are you ready to order?', 'Both noun and verb.', null, [ACT.vocabularyTable]),

    createContentItem(
      '"I\'ll have …" — standard order',
      'casual but polite',
      'The standard American/British way to order in a restaurant. Uses "will" (committed future) — you\'re deciding now.',
      'sentence',
      'I\'ll have the chicken sandwich. — I\'ll have a coffee.',
      'Add "please" for extra politeness.',
      [
        { target: 'I\'ll have …', english: 'most common order form' },
        { target: 'I\'ll get …', english: 'American casual variant' },
        { target: 'I\'ll take …', english: 'casual, slightly direct' },
      ],
      [ACT.grammarOrder],
    ),
    createContentItem(
      '"Could I have …, please?"',
      'extra polite',
      'More polite than "I\'ll have". Always pair with "please".',
      'sentence',
      'Could I have the steak, medium-rare, please?\nCould we get the menu, please?',
      'Common in formal restaurants or UK service.',
      null,
      [ACT.grammarOrder],
    ),
    createContentItem(
      '"For me, …" / ordering for a group',
      'multiple-person orders',
      'When ordering for a group, use "For me, …" or "And for me, …".',
      'sentence',
      'For me, the salad. And for him, the burger.',
      'Server may also ask each person separately.',
      null,
      [ACT.grammarOrder],
    ),

    createContentItem(
      'extra / no / on the side',
      'customizing orders',
      '"Extra" = more of. "No" = omit. "On the side" = separate, not on the dish.',
      'sentence',
      'Could I have extra cheese?\nNo onions, please.\nDressing on the side, please.',
      'These are the three magic phrases for custom orders.',
      [
        { target: 'extra …', english: 'add more of (cheese, sauce, ice)' },
        { target: 'no …', english: 'omit (onions, tomatoes, cilantro)' },
        { target: '… on the side', english: 'served separately, not mixed in' },
      ],
      [ACT.grammarRequest],
    ),
    createContentItem(
      '"Could you make it…?"',
      'adjustment requests',
      'For preparation choices.',
      'sentence',
      'Could you make it spicy? — Could you make it gluten-free?',
      'Many restaurants accommodate; politely ask.',
      null,
      [ACT.grammarRequest],
    ),
    createContentItem(
      'Allergies / dietary needs',
      'health-based requests',
      'State clearly: "I\'m allergic to…" / "I don\'t eat…" / "I\'m vegetarian/vegan".',
      'sentence',
      'I\'m allergic to peanuts. — I don\'t eat pork. — I\'m vegetarian.',
      'In allergy situations, "Could you tell me if this has …?" is essential.',
      null,
      [ACT.grammarRequest],
    ),

    createContentItem(
      '"Would you like …?"',
      'polite offer',
      'Standard server phrase. The polite alternative to "Do you want…?".',
      'sentence',
      'Would you like dessert? — Yes, please. / No, thanks.',
      'Always answer with "please" or "thanks".',
      [
        { target: 'Would you like …?', english: 'polite offer (server)' },
        { target: 'Yes, please.', english: 'polite acceptance' },
        { target: 'No, thanks. / No, thank you.', english: 'polite refusal' },
      ],
      [ACT.grammarLikeWant],
    ),
    createContentItem(
      '"Do you want …?"',
      'casual offer',
      'More casual; among friends.',
      'sentence',
      'Do you want a drink? — Sure, thanks.',
      'Less appropriate when a server uses it; more from peer to peer.',
      null,
      [ACT.grammarLikeWant],
    ),
    createContentItem(
      '"I\'d like to + verb"',
      'polite expressing wants',
      'A polite way to express what you want to do.',
      'sentence',
      'I\'d like to order. — I\'d like to pay.',
      'Politer than "I want to …".',
      null,
      [ACT.grammarLikeWant],
    ),

    createContentItem(
      'A restaurant review',
      'reading practice',
      'Read aloud, then answer.',
      'sentence',
      'We had dinner at Olive Garden last night. I ordered the spaghetti carbonara and my friend had the chicken parmesan. The pasta was amazing — really creamy. The chicken was good but a bit dry. Service was quick and the server was very friendly. The bill came to $45, including a 20% tip. We\'ll go back again.',
      'A casual restaurant review.',
      [
        { target: 'I ordered …', english: 'past tense of order' },
        { target: 'a bit dry', english: 'softened criticism' },
        { target: 'including a 20% tip', english: 'standard tip rate' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences with past tense.',
      'sentence',
      'Q1: What did the writer order? · Q2: How was the chicken? · Q3: How much was the bill?',
      'Use simple past in your answers.',
      [
        { target: 'A1: She ordered spaghetti carbonara.', english: 'past tense' },
        { target: 'A2: It was good but a bit dry.', english: 'review opinion' },
        { target: 'A3: It was $45 with tip.', english: 'total amount' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Ordering at a casual restaurant',
      'full flow',
      'Standard American casual restaurant flow.',
      'conversation',
      'Server: Hi, welcome to Joe\'s. Are you ready to order?\nCustomer: Yes. I\'ll have the chicken sandwich, please.\nServer: Great. Anything to drink?\nCustomer: A Coke, please. And could I have extra cheese on the sandwich?\nServer: Sure thing. Anything else?\nCustomer: That\'ll be it for now, thanks.\nServer: Coming right up.\n... (later)\nCustomer: Could we have the check, please?\nServer: Of course. Here you go. Have a great evening!\nCustomer: You too, thanks!',
      'Note the server\'s standard phrases.',
      [
        { target: 'Are you ready to order?', english: 'standard greeting' },
        { target: 'Anything to drink?', english: 'upsell question' },
        { target: 'extra cheese', english: 'customize request' },
        { target: 'Could we have the check?', english: 'asking for the bill' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Recommending a dish',
      'asking server advice',
      'When unsure, ask the server.',
      'conversation',
      'Customer: What do you recommend?\nServer: Our most popular dish is the salmon. The pasta is also a favorite.\nCustomer: I\'ll go with the salmon. Could I have it without the sauce?\nServer: Of course. Anything to drink?\nCustomer: Sparkling water, please.\nServer: Coming right up.',
      'Asking "What do you recommend?" is friendly and common.',
      [
        { target: 'What do you recommend?', english: 'asking for advice' },
        { target: 'I\'ll go with …', english: 'I\'ll choose …' },
        { target: 'without the sauce', english: 'omit a component' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'recommendation template',
      'Use this to recommend a dish or place.',
      'sentence',
      'I recommend [restaurant]. They have great [dish]. The [adj] was [opinion]. The [other dish] is also good. Service is [adj]. Prices are [adj]. We\'ll go back.',
      '[place] · [dish] · [opinion] · [other dish] · [service] · [prices] · [verdict].',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 4–5 sentences recommending a restaurant or dish. Include one specific dish, one opinion, and the price range.',
      'sentence',
      'Example: I recommend Olive Garden. Their pasta carbonara is amazing — really creamy. The service is friendly and the prices are reasonable. A meal costs about $20 per person. I\'ll go back next month.',
      'Check: place + dish + opinion + service + price.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Wait to be seated',
      'restaurant etiquette',
      'In most American/British sit-down restaurants, do not seat yourself — wait at the entrance for the host/hostess.',
      'sentence',
      'Sign: "Please wait to be seated."',
      'In casual cafes and fast food, you seat yourself.',
      [
        { target: 'sit-down restaurant', english: 'wait for host' },
        { target: 'cafe / fast food', english: 'seat yourself' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Tipping 15–20% (US)',
      'standard practice',
      'In US sit-down restaurants, tip 15–20% on the pre-tax total. Servers depend on tips for income. Skipping is rude.',
      'sentence',
      'Pre-tax total $40 → $6–$8 tip → final ~$46–$48.',
      'In the UK, 10% is more common; in Australia, no tip expected.',
      [
        { target: 'US: 15–20%', english: 'sit-down restaurants' },
        { target: 'UK: 10–15%', english: 'often included as "service"' },
        { target: 'Australia / NZ: optional', english: 'mostly not expected' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Splitting the bill',
      '"Let\'s split it"',
      'In English-speaking cultures, splitting the bill among friends is normal — even on dates in the US. "Let\'s split it" is the standard phrase.',
      'sentence',
      'Let\'s split the bill. — How about we split it 50/50? — I\'ll get this one; you get the next.',
      'In some Asian cultures, the senior pays; in the West, splitting is the default.',
      [
        { target: 'split the bill / go Dutch', english: 'each pays equally' },
        { target: 'I\'ll get this one', english: 'I\'ll pay this time' },
        { target: 'pay separately', english: 'each pays for their own order' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Take a friend to dinner',
      'consolidation task',
      'Roleplay: Order dinner for two at a casual American restaurant. Customize one item. Ask about the bill and tip.',
      'conversation',
      'Server: Welcome! How many in your party?\nYou: [number]\nServer: Right this way. Here are your menus.\nYou: [look + decide]\nServer: Are you ready to order?\nYou: [order with customization]\nServer: Anything to drink?\nYou: [drinks order]\n... (after meal)\nYou: [ask for check + thank]',
      'AI tutor will play the server.',
      [
        { target: 'I\'ll have …', english: 'standard order' },
        { target: 'extra / no / on the side', english: 'customize' },
        { target: 'Could we have the check?', english: 'ask for the bill' },
        { target: 'Tip ~20%', english: 'standard tip' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
