// Level 1 Unit 10 — Weather & Preferences (English)
// Functions: describing weather, expressing preferences with reasons, seasons.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u10-orientation',
  pronunciation: 'en-l1u10-pronunciation',
  vocabularyWeather: 'en-l1u10-vocab-weather',
  vocabularySeasons: 'en-l1u10-vocab-seasons',
  grammarBecause: 'en-l1u10-grammar-because',
  grammarPrefer: 'en-l1u10-grammar-prefer',
  grammarSuperlative: 'en-l1u10-grammar-best',
  reading: 'en-l1u10-reading',
  listening: 'en-l1u10-listening',
  writing: 'en-l1u10-writing',
  culture: 'en-l1u10-culture',
  task: 'en-l1u10-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe today\'s weather.', 'Name the 4 seasons + season activities.', 'State a reasoned preference with "because".', 'Pick a favorite with superlatives (the most / -est).'],
    task: 'Imagine an English-speaking friend asks which season you like best and why.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Weather words',
    goals: ['Distinguish "hot" /hɒt/ from "hat" /hæt/.', 'Pronounce "summer" /ˈsʌmər/ — note the short /ʌ/.'],
    task: 'Read each weather adjective aloud.' },
  { id: ACT.vocabularyWeather, section: 'Vocabulary I', title: 'Weather conditions',
    goals: ['Use hot, cold, warm, cool, sunny, rainy, snowy, windy, cloudy, foggy.'],
    task: 'Describe today\'s weather in one sentence.' },
  { id: ACT.vocabularySeasons, section: 'Vocabulary II', title: 'Seasons & activities',
    goals: ['Use spring, summer, fall/autumn, winter + activities.'],
    task: 'Match one activity to each season.' },
  { id: ACT.grammarBecause, section: 'Grammar I', title: 'Reasons with "because"',
    goals: ['Connect cause and effect: "I like X because Y".', 'Use "since" / "as" as more formal alternatives.'],
    task: 'Make 3 because-sentences.' },
  { id: ACT.grammarPrefer, section: 'Grammar II', title: 'Like / love / prefer / hate',
    goals: ['Use "prefer X to Y" for choosing.', 'Order: "love > like > don\'t like > hate".'],
    task: 'State 3 preferences with prefer.' },
  { id: ACT.grammarSuperlative, section: 'Grammar III', title: 'Superlatives — "the most" / "-est"',
    goals: ['Short adjectives: hot → the hottest. Long adjectives: beautiful → the most beautiful.', 'Always use "the" before the superlative.'],
    task: 'Pick the best, hottest, coldest from three options.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A favorite season',
    goals: ['Read a 5-sentence paragraph about season preferences.'],
    task: 'Identify what the writer likes and dislikes.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Comparing seasons',
    goals: ['Follow a season-preference dialogue.'],
    task: 'Reproduce with your own preferences.' },
  { id: ACT.writing, section: 'Writing', title: 'My favorite season',
    goals: ['Write 4–5 sentences about your favorite season with reasons.'],
    task: 'Write your own paragraph.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Weather small talk',
    goals: ['Know "Nice weather, isn\'t it?" — universal opener.', 'British weather small talk is famous; less common in some other English regions.'],
    task: 'Practice 3 weather small-talk openers.' },
  { id: ACT.task, section: 'Task', title: 'Plan a seasonal activity',
    goals: ['Combine season, weather, preference, and reason.'],
    task: 'Plan a seasonal trip with the AI tutor.' },
];

const lesson = {
  title: 'Level 1 · Unit 10: I love summer because it\'s warm — Weather and Preferences',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describing-weather', label: 'Describing weather', goal: 'Use "It\'s + weather adjective".' },
    { id: 'sharing-preference', label: 'Sharing preference with reason', goal: 'Use "I like/prefer + N + because…".' },
    { id: 'picking-favorite', label: 'Picking favorite', goal: 'Use superlative "the …est / the most …".' },
  ],
  relatedPools: ['topic-weather', 'topic-society'],
  content: [
    createContentItem('Lesson goal', 'weather + preference', 'By end: describe weather, name seasons, give reasoned preferences, pick favorites.', 'word', 'Functions: describe · prefer · reason · rank.', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'fall chat', 'A friend asks "Which season do you like best?" — you need to pick, explain with "because", and ask back.', 'word', 'Friend: "Which season is your favorite?" — You: "I love fall because it\'s cool and the leaves are beautiful."', 'A typical small-talk question.', null, [ACT.orientation]),

    createContentItem('hot vs hat', '/hɒt/ vs /hæt/', '/ɒ/ — open back vowel; /æ/ — front near-open.', 'word', 'It\'s hot today. — I have a new hat.', 'A common pronunciation trap.', null, [ACT.pronunciation]),
    createContentItem('summer /ˈsʌmər/', '/ˈsʌmər/', 'Short /ʌ/ as in "cup". Stress on the first syllable.', 'word', 'I love summer.', 'Distinct from "some" /sʌm/ (same vowel, different ending).', null, [ACT.pronunciation]),
    createContentItem('weather /ˈwɛðər/', '/ˈwɛðər/', '/ð/ in the middle — tongue between teeth, voiced. Sounds like "wether", not "wheather".', 'word', 'The weather is nice today.', 'Same pronunciation as "whether" (different meaning).', null, [ACT.pronunciation]),
    createContentItem('because /bɪˈkɔːz/', '/bɪˈkɔːz/', 'Stress on the SECOND syllable. Often shortened to "cause" /kɔːz/ in casual speech.', 'word', 'I love spring because the flowers bloom.', 'In speech: /bɪˈkɔːz/ → casual /kʌz/.', null, [ACT.pronunciation]),

    createContentItem('hot', '/hɒt/', 'high temperature', 'word', 'It\'s hot today.', 'Also for spicy food.', null, [ACT.vocabularyWeather]),
    createContentItem('cold', '/koʊld/', 'low temperature', 'word', 'It\'s cold in winter.', '', null, [ACT.vocabularyWeather]),
    createContentItem('warm', '/wɔːrm/', 'pleasantly heated', 'word', 'Spring is warm.', 'Between cool and hot.', null, [ACT.vocabularyWeather]),
    createContentItem('cool', '/kuːl/', 'slightly cold; pleasant', 'word', 'Fall is cool and refreshing.', 'Between cold and warm.', null, [ACT.vocabularyWeather]),
    createContentItem('sunny', '/ˈsʌni/', 'with bright sunshine', 'word', 'It\'s sunny today.', 'Adjective from "sun".', null, [ACT.vocabularyWeather]),
    createContentItem('rainy', '/ˈreɪni/', 'with rain', 'word', 'It\'s a rainy day.', 'Adjective; the noun is "rain".', null, [ACT.vocabularyWeather]),
    createContentItem('snowy', '/ˈsnoʊi/', 'with snow', 'word', 'It\'s snowy in January.', '', null, [ACT.vocabularyWeather]),
    createContentItem('windy', '/ˈwɪndi/', 'with strong wind', 'word', 'It\'s very windy today.', '', null, [ACT.vocabularyWeather]),
    createContentItem('cloudy', '/ˈklaʊdi/', 'with clouds in the sky', 'word', 'It\'s cloudy this morning.', '', null, [ACT.vocabularyWeather]),
    createContentItem('foggy', '/ˈfɒɡi/', 'with thick fog', 'word', 'It\'s foggy this morning — drive carefully.', '', null, [ACT.vocabularyWeather]),
    createContentItem('humid', '/ˈhjuːmɪd/', 'with high moisture in the air', 'word', 'Summer is humid here.', 'Heavy, sticky air.', null, [ACT.vocabularyWeather]),
    createContentItem('dry', '/draɪ/', 'with little moisture', 'word', 'Winter is dry.', 'Opposite of "humid" or "wet".', null, [ACT.vocabularyWeather]),
    createContentItem('It\'s + adj', 'sentence pattern', 'Use "It\'s + weather adjective" to describe today\'s weather.', 'sentence', 'It\'s sunny. — It\'s cold. — It\'s rainy and cool.', '"It" with no specific referent — common for weather and time.', null, [ACT.vocabularyWeather]),

    createContentItem('spring', '/sprɪŋ/', 'March–May (Northern Hemisphere)', 'word', 'I love spring.', 'Also a noun: a coil; a season.', null, [ACT.vocabularySeasons]),
    createContentItem('summer', '/ˈsʌmər/', 'June–August', 'word', 'Summer is the hottest season.', '', null, [ACT.vocabularySeasons]),
    createContentItem('fall / autumn', '/fɔːl/ /ˈɔːtəm/', 'September–November', 'word', 'Fall in Korea is beautiful.', 'US: "fall"; UK: "autumn".', null, [ACT.vocabularySeasons]),
    createContentItem('winter', '/ˈwɪntər/', 'December–February', 'word', 'Winter is cold.', '', null, [ACT.vocabularySeasons]),
    createContentItem('flowers', '/ˈflaʊərz/', 'blooming plants', 'word', 'Flowers bloom in spring.', '', null, [ACT.vocabularySeasons]),
    createContentItem('leaves', '/liːvz/', 'plural of leaf', 'word', 'The leaves change color in fall.', 'Irregular plural: leaf → leaves.', null, [ACT.vocabularySeasons]),
    createContentItem('snow', '/snoʊ/', 'frozen water that falls in winter', 'word', 'It snows a lot in January.', 'Both noun and verb.', null, [ACT.vocabularySeasons]),
    createContentItem('rain', '/reɪn/', 'water falling from the sky', 'word', 'It rains in April.', 'Both noun and verb.', null, [ACT.vocabularySeasons]),
    createContentItem('beach', '/biːtʃ/', 'sandy shore by the sea', 'word', 'We go to the beach in summer.', '', null, [ACT.vocabularySeasons]),
    createContentItem('ski', '/skiː/', 'sliding on snow with skis', 'word', 'I ski in winter.', 'Verb or noun.', null, [ACT.vocabularySeasons]),
    createContentItem('hike', '/haɪk/', 'long walk in nature', 'word', 'We hike in the mountains.', 'Verb or noun.', null, [ACT.vocabularySeasons]),
    createContentItem('barbecue / BBQ', '/ˈbɑːrbɪkjuː/', 'cooking food on an outdoor grill', 'word', 'We had a BBQ in the park.', 'Common summer activity.', null, [ACT.vocabularySeasons]),

    createContentItem(
      '"because" — link cause and effect',
      'subordinate clause',
      'Use "because" to give a reason. Place between the result and the reason.',
      'sentence',
      'I love summer because it\'s warm.\nI don\'t like winter because it\'s cold and dark.',
      'Reverse order works too: "Because it\'s warm, I love summer."',
      [
        { target: '… because + S + V', english: 'subject + verb after "because"' },
        { target: 'Because + S + V, …', english: 'opening with "because" (comma after)' },
      ],
      [ACT.grammarBecause],
    ),
    createContentItem(
      '"so" — show result',
      'opposite direction',
      '"So" goes the other way: cause + so + result.',
      'sentence',
      'It\'s cold, so I\'m wearing a coat.\nI love sunny weather, so I prefer summer.',
      '"Because" focuses on the reason; "so" focuses on the result.',
      null,
      [ACT.grammarBecause],
    ),
    createContentItem(
      'More formal: "since" / "as"',
      'alternatives',
      '"Since" and "as" can replace "because" in formal contexts.',
      'sentence',
      'Since it\'s raining, we\'ll stay home. — As you are busy, I\'ll do it myself.',
      'In casual speech, "because" is much more common.',
      null,
      [ACT.grammarBecause],
    ),

    createContentItem(
      'like / love / prefer / hate',
      'preference scale',
      'love (strong+) > like (mild+) > don\'t like (mild−) > hate (strong−). "Prefer" = like more than something else.',
      'sentence',
      'I love summer. — I like spring. — I don\'t like winter. — I hate cold weather.',
      'All take noun or -ing form: "I love swimming", not "I love to swim" (both work, but -ing is more idiomatic).',
      [
        { target: 'love + N / V-ing', english: 'strong positive' },
        { target: 'like + N / V-ing', english: 'mild positive' },
        { target: 'don\'t like + N / V-ing', english: 'mild negative' },
        { target: 'hate + N / V-ing', english: 'strong negative' },
      ],
      [ACT.grammarPrefer],
    ),
    createContentItem(
      '"prefer X to Y" — choose between two',
      'comparison preference',
      'Use "prefer X to Y" when comparing two options.',
      'sentence',
      'I prefer summer to winter. — I prefer coffee to tea.',
      'Note "to" — not "than": "prefer X to Y", NOT "prefer X than Y".',
      [
        { target: 'prefer + N + to + N', english: 'standard preference comparison' },
        { target: 'prefer + V-ing + to + V-ing', english: 'with -ing verbs' },
      ],
      [ACT.grammarPrefer],
    ),
    createContentItem(
      '"would rather + verb"',
      'preferred action',
      'For preferred action right now, use "would rather + bare verb".',
      'sentence',
      'I\'d rather stay home tonight. — I\'d rather not go.',
      '"I\'d rather" = "I would rather". Contracted form is normal.',
      null,
      [ACT.grammarPrefer],
    ),

    createContentItem(
      'Short adjectives: -est',
      'one-syllable adjectives',
      'Add -est to short adjectives. Always use "the" before.',
      'sentence',
      'Summer is the hottest season. — Winter is the coldest.',
      'Spelling rules: hot → hottest (double consonant); easy → easiest (y → iest).',
      [
        { target: 'hot → the hottest', english: 'double the consonant' },
        { target: 'big → the biggest', english: 'double the consonant' },
        { target: 'easy → the easiest', english: 'y → iest' },
      ],
      [ACT.grammarSuperlative],
    ),
    createContentItem(
      'Long adjectives: "the most …"',
      'two+ syllable adjectives',
      'For long adjectives, use "the most" + adjective.',
      'sentence',
      'Fall is the most beautiful season. — This is the most interesting book.',
      'Common error: "beautifulest" — wrong. Always "the most beautiful".',
      null,
      [ACT.grammarSuperlative],
    ),
    createContentItem(
      'Irregular superlatives',
      'good/bad/far',
      'A few adjectives are irregular.',
      'sentence',
      'This is the best meal. — That was the worst movie.',
      'Memorize: good→the best, bad→the worst, far→the farthest/furthest.',
      [
        { target: 'good → the best', english: 'irregular' },
        { target: 'bad → the worst', english: 'irregular' },
        { target: 'far → the farthest / furthest', english: 'irregular' },
      ],
      [ACT.grammarSuperlative],
    ),

    createContentItem(
      'A favorite season',
      'reading practice',
      'Read aloud and answer the questions.',
      'sentence',
      'I love fall the most. The weather is cool and not too hot. The leaves change color and the parks are beautiful. I also enjoy hiking in fall because it\'s perfect weather for outdoor activities. Summer is too humid for me, and winter is too cold. Spring is nice but it rains too much. Fall is the best season.',
      'Notice: superlatives ("the best", "the most"), prepositions, and "because".',
      [
        { target: 'I love fall the most', english: 'superlative pattern' },
        { target: 'because it\'s perfect weather', english: 'reason' },
        { target: 'too humid / too cold', english: '"too" + adjective = excessive' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences.',
      'sentence',
      'Q1: What\'s the writer\'s favorite season? · Q2: Why is fall good? · Q3: Why doesn\'t she like summer?',
      'Use "because" and "the most/best" in your answers.',
      [
        { target: 'A1: Her favorite season is fall.', english: 'pick favorite' },
        { target: 'A2: Because the weather is cool and the leaves are beautiful.', english: 'reasons' },
        { target: 'A3: Because it\'s too humid.', english: 'reason with "too"' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Comparing seasons',
      'listening',
      'Two friends compare season preferences.',
      'conversation',
      'A: Which season do you like best?\nB: I love spring. The flowers are beautiful and it\'s warm but not hot. How about you?\nA: I prefer winter. I love snow and skiing.\nB: Really? I think winter is too cold.\nA: It\'s cold, but the snow is amazing. And there are no mosquitoes!\nB: Haha, good point.',
      'Use "the best", "prefer X to Y", "because".',
      [
        { target: 'Which season do you like best?', english: 'open preference question' },
        { target: 'I prefer X to Y', english: 'comparison preference' },
        { target: 'How about you?', english: 'return the question' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Weather small talk',
      'common opener',
      'A quick weather exchange at the start of a day.',
      'conversation',
      'A: Nice weather today, isn\'t it?\nB: Yeah, it\'s gorgeous! Sunny and warm.\nA: I love days like this.\nB: Me too. Perfect for a walk in the park.',
      'Note "isn\'t it?" — the most common tag question for weather.',
      [
        { target: 'Nice weather, isn\'t it?', english: 'standard small-talk opener' },
        { target: 'Yeah / Me too / Same here', english: 'agreement markers' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'favorite season template',
      'Use this structure.',
      'sentence',
      'My favorite season is [season]. I love it because [reason]. The weather is [adj]. I usually [activity]. I don\'t like [other season] because [reason].',
      '[favorite] · [reason] · [weather] · [activity] · [least favorite + reason].',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 4–5 sentences about your favorite season. Use at least one "because" and one "the most/best".',
      'sentence',
      'Example: My favorite season is summer. I love it because the weather is warm and the days are long. The beach is the most fun place in summer. I don\'t like winter because it\'s too cold.',
      'Check: superlative + reason + activity.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Weather small talk',
      'cultural habit',
      'English-speaking cultures — especially British — use weather as universal small talk. It\'s safe, neutral, and shows you want to engage.',
      'sentence',
      'Nice day, isn\'t it? — Bit chilly, isn\'t it? — Looks like rain.',
      'Tag questions ("isn\'t it?", "doesn\'t it?") are very common in this context.',
      [
        { target: 'Nice day, isn\'t it?', english: 'positive comment + tag' },
        { target: 'Bit chilly, isn\'t it?', english: 'mild complaint + tag' },
        { target: 'Looks like rain.', english: 'observation' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Hemispheres flip seasons',
      'global awareness',
      'Northern Hemisphere (US, UK, Korea, Japan) and Southern Hemisphere (Australia, NZ, South America) have opposite seasons. Christmas in Australia is summer.',
      'sentence',
      'Korea: June = summer. Australia: June = winter.',
      'Useful to mention when talking to people from "down under".',
      null, [ACT.culture],
    ),

    createContentItem(
      'Task: Plan a seasonal activity',
      'consolidation task',
      'Roleplay: A friend wants to plan a trip to Korea. Recommend a season + activities with reasons.',
      'conversation',
      'Friend: When should I visit Korea?\nYou: [pick season + reason]\nFriend: What\'s the weather like then?\nYou: [describe weather]\nFriend: What can I do?\nYou: [activity + superlative]\nFriend: Sounds great! I\'ll go then.',
      'AI tutor will play the friend.',
      [
        { target: 'I recommend [season] because …', english: 'recommendation + reason' },
        { target: 'It\'s the [most/-est] …', english: 'superlative' },
        { target: 'The weather is …', english: 'weather description' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
