// Level 2 Adult Unit 4 — Commuting (English)
// Functions: navigating bus/train, ride-sharing, traffic, asking for directions to work.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2au4-orientation',
  pronunciation: 'en-l2au4-pronunciation',
  vocabularyTransport: 'en-l2au4-vocab-transport',
  vocabularyDirections: 'en-l2au4-vocab-directions',
  grammarHowDo: 'en-l2au4-grammar-howdo',
  grammarTake: 'en-l2au4-grammar-take',
  reading: 'en-l2au4-reading',
  listening: 'en-l2au4-listening',
  writing: 'en-l2au4-writing',
  culture: 'en-l2au4-culture',
  task: 'en-l2au4-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe your commute (bus, subway, drive, walk, bike, ride-share).', 'Ask for directions to your workplace.', 'Handle delays / traffic situations.', 'Use ride-sharing apps in English.'],
    task: 'Picture giving directions to your office to a new coworker who needs to take the bus.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Transport phrases',
    goals: ['Pronounce "Uber" /ˈuːbər/ correctly.', 'Reduce "I have to take" → "I gotta take".', '"Subway" /ˈsʌbˌweɪ/ stress on syllable 1.'],
    task: 'Read 3 transport phrases aloud.' },
  { id: ACT.vocabularyTransport, section: 'Vocabulary I', title: 'Transport modes',
    goals: ['Use bus, subway, train, light rail, ride-share (Uber/Lyft), bike, walk, drive.'],
    task: 'Describe 3 ways to get to work.' },
  { id: ACT.vocabularyDirections, section: 'Vocabulary II', title: 'Directions + traffic',
    goals: ['Use intersection, block, traffic light, stop sign, exit, highway, rush hour, traffic jam.'],
    task: 'Give 5-step directions.' },
  { id: ACT.grammarHowDo, section: 'Grammar I', title: 'Asking how to get places',
    goals: ['"How do I get to + place?" / "What\'s the best way to + place?"', '"Which line / bus / route do I take?"'],
    task: 'Ask 3 directions questions.' },
  { id: ACT.grammarTake, section: 'Grammar II', title: '"Take + transport"',
    goals: ['"Take the + bus/subway/train/Uber".', '"Get on / off at + stop".', '"Transfer to + line".'],
    task: 'Describe a 3-step commute.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'Transit map',
    goals: ['Read a subway/bus map.'],
    task: 'Plan a route.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Giving directions',
    goals: ['Follow a directions conversation.'],
    task: 'Reproduce with your own route.' },
  { id: ACT.writing, section: 'Writing', title: 'Slack message: late arrival',
    goals: ['Write a 3-line message that you\'ll be late.'],
    task: 'Write your own late-arrival message.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US transit + ride-sharing',
    goals: ['Know that most US cities are car-dependent (NYC, Boston, SF, DC exceptions).', 'Know Uber, Lyft + transit cards (MetroCard, Charlie Card, Clipper).', 'UK/AU: better public transit.'],
    task: 'Compare commuting in US/UK with your country.' },
  { id: ACT.task, section: 'Task', title: 'Directions to work',
    goals: ['Combine "how do I" + "take" + step-by-step.'],
    task: 'Roleplay giving directions to a new coworker.' },
];

const lesson = {
  title: 'Level 2 (Workplace) · Unit 4: How do I get there? — Commuting',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'asking-route-en', label: 'Asking for a route', goal: 'Use "How do I get to / What\'s the best way to".' },
    { id: 'taking-transport-en', label: 'Taking transport', goal: 'Use "Take the + transport" / "Get off at".' },
    { id: 'late-message-en', label: 'Announcing lateness', goal: 'Use "Running about + time + late, sorry!".' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'commuting', 'By end: describe commute, ask directions, handle delays, use ride-sharing.', 'word', 'Functions: navigate · direct · delay · share.', 'Four commuting micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'late on the F train', 'You\'re on the NYC F train heading to work in Brooklyn. The train stops between stations due to signal problems. You\'ll be 15-20 minutes late and need to message your team.', 'word', 'You: "Running 15 min late — F train delays. Will be in by 9:30."', 'Standard NYC commute situation.', null, [ACT.orientation]),

    createContentItem('Uber /ˈuːbər/', '/ˈuːbər/', 'Two syllables, stress on 1.', 'word', 'Take an Uber.', 'Verb too: "I\'ll Uber over".', null, [ACT.pronunciation]),
    createContentItem('"I gotta take" → /aɪ ˈɡɒtə teɪk/', '/aɪ ˈɡɒtə teɪk/', 'Casual: "I have to" → "I gotta".', 'word', 'I gotta take the L train.', 'Casual register; avoid in writing.', null, [ACT.pronunciation]),
    createContentItem('subway /ˈsʌbˌweɪ/', '/ˈsʌbˌweɪ/', 'Two syllables, stress on 1.', 'word', 'Take the subway downtown.', 'NYC, Boston, DC have subways. SF has BART.', null, [ACT.pronunciation]),

    createContentItem('bus', '/bʌs/', 'public road vehicle', 'word', 'I take the bus to work.', 'Stops: bus stop. Driver: bus driver.', null, [ACT.vocabularyTransport]),
    createContentItem('subway / metro / tube', '/ˈsʌbˌweɪ/ /ˈmɛtroʊ/ /tjuːb/', 'underground train', 'word', 'The subway is fastest in NYC.', 'US: "subway". DC: "Metro". UK: "Tube".', null, [ACT.vocabularyTransport]),
    createContentItem('train', '/treɪn/', 'long-distance rail', 'word', 'I take the train from NJ to NYC.', 'Amtrak (US), National Rail (UK).', null, [ACT.vocabularyTransport]),
    createContentItem('light rail / streetcar', '/laɪt reɪl/', 'urban surface rail', 'word', 'Portland has light rail.', 'Above-ground tram.', null, [ACT.vocabularyTransport]),
    createContentItem('ride-share / Uber / Lyft', '/raɪd ʃɛər/ /ˈuːbər/ /lɪft/', 'app-based car service', 'word', 'I Uber when buses are slow.', 'Verb-able: "I\'ll Uber".', null, [ACT.vocabularyTransport]),
    createContentItem('drive / car-pool', '/draɪv/ /ˈkɑːrˌpuːl/', 'own car / shared car', 'word', 'I car-pool with two coworkers.', 'Car-pooling saves gas + traffic.', null, [ACT.vocabularyTransport]),
    createContentItem('bike / cycle', '/baɪk/ /ˈsaɪkəl/', 'bicycle', 'word', 'I bike to work in summer.', 'Verbs too.', null, [ACT.vocabularyTransport]),
    createContentItem('walk', '/wɔːk/', 'on foot', 'word', 'I walk 15 minutes to work.', 'Common for short urban commutes.', null, [ACT.vocabularyTransport]),

    createContentItem('intersection / crossroads', '/ˌɪntərˈsɛkʃən/', 'where streets meet', 'word', 'Turn left at the next intersection.', 'US: "intersection"; UK: "crossroads" / "junction".', null, [ACT.vocabularyDirections]),
    createContentItem('block', '/blɒk/', 'distance between two streets', 'word', 'Walk three blocks north.', 'US grid-city term.', null, [ACT.vocabularyDirections]),
    createContentItem('traffic light / signal', '/ˈtræfɪk laɪt/', 'red/yellow/green', 'word', 'Wait for the traffic light.', 'UK: "traffic lights" (plural).', null, [ACT.vocabularyDirections]),
    createContentItem('stop sign', '/stɒp saɪn/', 'mandatory stop', 'word', 'There\'s a stop sign at the corner.', '4-way stop common in US suburbs.', null, [ACT.vocabularyDirections]),
    createContentItem('exit / off-ramp', '/ˈɛksɪt/ /ɒf ræmp/', 'highway exit', 'word', 'Take exit 25.', 'Highway navigation.', null, [ACT.vocabularyDirections]),
    createContentItem('highway / freeway / interstate', '/ˈhaɪweɪ/ /ˈfriːweɪ/', 'major road', 'word', 'I-95 is the East Coast highway.', 'US: "freeway" (West), "highway" (general), "interstate" (federal).', null, [ACT.vocabularyDirections]),
    createContentItem('rush hour', '/rʌʃ aʊər/', 'peak traffic time', 'word', 'Rush hour is 7-9 AM and 5-7 PM.', 'Avoid driving during rush hour.', null, [ACT.vocabularyDirections]),
    createContentItem('traffic jam / gridlock', '/ˈtræfɪk dʒæm/', 'stuck in traffic', 'word', 'There\'s a huge traffic jam on I-95.', '"Gridlock" — totally stopped.', null, [ACT.vocabularyDirections]),

    createContentItem(
      '"How do I get to + place?"',
      'directions question',
      'Standard way to ask for routes.',
      'sentence',
      'How do I get to your office? — What\'s the best way to the airport? — Which bus do I take to downtown?',
      '"How" — general; "What\'s the best" — for advice; "Which + N" — specific choice.',
      [
        { target: 'How do I get to + place?', english: 'general direction' },
        { target: 'What\'s the best way to + place?', english: 'recommendation' },
        { target: 'Which + N + do I take?', english: 'specific choice' },
      ],
      [ACT.grammarHowDo],
    ),
    createContentItem(
      '"Take + transport"',
      'instruction pattern',
      'Tell someone which mode to use.',
      'sentence',
      'Take the F train to Brooklyn. — Take an Uber if it\'s raining. — Take a left at the light.',
      'For transit: "take the + bus/train/etc.". For directions: "take a left/right".',
      [
        { target: 'Take the + bus/train', english: 'transit' },
        { target: 'Take an Uber / Lyft', english: 'ride-share' },
        { target: 'Take a left/right', english: 'turn directions' },
        { target: 'Get on / off at + stop', english: 'boarding/exit' },
        { target: 'Transfer to + line/bus', english: 'switching' },
      ],
      [ACT.grammarTake],
    ),

    createContentItem(
      'Transit map',
      'reading practice',
      'Read this NYC subway snippet.',
      'sentence',
      'F Train (Orange line, runs 24/7)\nFrom Coney Island → Manhattan → Queens.\nKey Manhattan stops: West 4th St (transfer to A, C, E, B, D, M) → 14th Street → 23rd Street → 34th-Herald Square → 42nd Street-Bryant Park.\nApprox. travel time Coney Island → 42nd St: 50 min off-peak, 70 min rush hour.',
      'Standard subway info card.',
      [
        { target: 'F Train (Orange line, runs 24/7)', english: 'line ID' },
        { target: 'Key stops + transfer points', english: 'navigation' },
        { target: 'travel time off-peak vs rush hour', english: 'timing' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Giving directions',
      'office-to-coworker',
      'Telling a new coworker how to get to your office.',
      'conversation',
      'New coworker: How do I get to the office from Brooklyn?\nYou: Easiest way is the F train. Get on at any F stop and take it to 42nd Street-Bryant Park.\nNew coworker: How long?\nYou: About 45 minutes off-peak, an hour during rush hour. Get off at 42nd and walk two blocks east — our building\'s on 5th Ave.\nNew coworker: What about Uber?\nYou: Uber works, but in traffic you could be looking at an hour and $40. Subway is way better unless it\'s pouring.\nNew coworker: Got it. Thanks!',
      'Practical transit advice.',
      [
        { target: 'How do I get to + place?', english: 'question' },
        { target: 'Get on at + stop', english: 'boarding' },
        { target: 'Take it to + destination', english: 'route' },
        { target: 'Get off at + stop and walk + direction', english: 'arrival' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Late-arrival Slack message',
      'writing model',
      'Quick team notification.',
      'sentence',
      'Hi team — running 15 min late, F train delays. Will be in by 9:30. Will join the 9 AM standup remotely if I can.',
      'Format: status + reason + ETA + plan.',
      [
        { target: 'running + duration + late', english: 'status' },
        { target: 'reason', english: 'transit / traffic' },
        { target: 'Will be in by + time', english: 'ETA' },
        { target: 'will join remotely if I can', english: 'meeting plan' },
      ],
      [ACT.writing],
    ),

    createContentItem(
      'US transit + ride-sharing',
      'cultural overview',
      'Most US cities are car-dependent. Major transit cities: NYC (subway, ~24/7), Boston (T), DC (Metro), SF (BART/Muni), Chicago (CTA). Ride-share: Uber and Lyft dominate. Transit cards: MetroCard (NYC), Charlie Card (Boston), Clipper (SF). UK: Oyster (London), wider rail network. AU: Opal (Sydney).',
      'sentence',
      'Outside major cities, most Americans drive everywhere.',
      'Public transit access varies wildly by city.',
      [
        { target: 'car-dependent cities (most of US)', english: 'driving default' },
        { target: 'subway cities: NYC, Boston, DC, SF, Chicago', english: 'transit available' },
        { target: 'Uber + Lyft', english: 'dominant ride-share' },
        { target: 'transit cards', english: 'MetroCard, Charlie Card, etc.' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Directions to work',
      'consolidation task',
      'AI tutor plays a new coworker. Give them directions from their apartment to the office.',
      'conversation',
      'Tutor: How do I get to the office?\nYou: [recommend transport]\nTutor: What\'s the route?\nYou: [3-step directions with "take" / "get off" / "transfer"]\nTutor: What about traffic?\nYou: [advise on rush hour]\nTutor: [thanks]',
      'AI tutor plays new coworker.',
      [
        { target: 'How do I get to + place?', english: 'question' },
        { target: 'Take the + transport to + stop', english: 'step 1' },
        { target: 'Transfer / Get off at + stop', english: 'step 2' },
        { target: 'Walk + direction + N blocks', english: 'step 3' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
