// Level 2 Unit 8 — Intriguing World (English)
// Grammar: "go pick up + N" (errands), "the N that S V" (descriptive relative),
// "including X, Y, and Z", "as well as / along with". Pronunciation: linking.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2u8-orientation',
  vocabulary: 'en-l2u8-vocabulary',
  pronunciation: 'en-l2u8-pronunciation',
  grammar: 'en-l2u8-grammar',
  speaking: 'en-l2u8-speaking',
  readingSpeaking: 'en-l2u8-reading-speaking',
  listeningSpeaking: 'en-l2u8-listening-speaking',
  readingWriting: 'en-l2u8-reading-writing',
  culture: 'en-l2u8-culture',
  task: 'en-l2u8-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe regional/cultural features with 4 intermediate patterns.', 'Use "go pick up + N", "the N that S V", "including X and Y", "as well as".', 'Discuss cultural diversity in English-speaking countries.'],
    task: 'Picture giving a 5-minute presentation on a unique cultural feature from your country.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Culture + diversity vocabulary',
    goals: ['Use culture, feature, region, dialect, tradition, minority, indigenous.', 'Use "per-X" structures: per region, per country, per city.'],
    task: 'Use 3 culture-related words.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Linking consonant + vowel',
    goals: ['Link final consonant + initial vowel: "go upstairs" /ɡoʊ ˈʌpsˌtɛərz/.', 'Pick up reductions: "go pick up" /ɡoʊ pɪˈkʌp/.'],
    task: 'Read 3 sentences with linking.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Description + inclusion patterns',
    goals: ['"go + V + N" / "go and + V" — errand verb pattern', '"the N that S V" — descriptive relative clauses', '"including + X, Y, and Z" — inclusion', '"as well as / along with + N" — addition'],
    task: 'Use each pattern in cultural descriptions.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Explaining a market',
    goals: ['Explain something about a famous market.'],
    task: 'Explain one fact about a market in your country.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Game explanations',
    goals: ['Read game intros.', 'Explain a game.'],
    task: 'Explain a game from your hometown.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Regional accent presentation',
    goals: ['Listen to a presentation on accents.', 'Ask questions.'],
    task: 'Ask 2 follow-up questions.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Indigenous culture writing',
    goals: ['Read about indigenous peoples.', 'Write an explanation.'],
    task: 'Write 3 sentences about an indigenous group.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US, UK, AU dialects + indigenous cultures',
    goals: ['Understand major US dialects (Southern, NYC, Boston, AAVE).', 'Understand UK dialects (Cockney, Geordie, Scouse).', 'Recognize indigenous cultures: Native American, Aboriginal, Māori.'],
    task: 'Compare a regional dialect from your country with one from US/UK/AU.' },
  { id: ACT.task, section: 'Task', title: 'Cultural presentation outline',
    goals: ['Combine 4 patterns in a presentation about your culture.'],
    task: 'Outline a 5-minute presentation.' },
];

const lesson = {
  title: 'Level 2 · Unit 8: Intriguing World',
  category: 'travel',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-followup-en', label: 'Asking follow-up questions', goal: 'Ask questions after a presentation.' },
    { id: 'descriptive-relative-en', label: 'Replying with description', goal: 'Use "the N that S V" for thoughtful answers.' },
    { id: 'inclusion-en', label: 'Listing items', goal: 'Use "including" and "as well as".' },
  ],
  relatedPools: ['topic-culture'],
  content: [
    createContentItem('Lesson goal', 'intriguing world', 'By end: present cultural features, ask questions, list with inclusion.', 'word', 'Functions: present · describe · list · contrast.', 'Four cultural-presentation micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'culture night at Kumoh', 'Your Korean classmate asks you to present your home culture at International Night. You describe one regional feature, including food, dialect, and a unique tradition.', 'word', 'You: "I\'ll talk about Busan, the city that\'s famous for seafood, dialect, and beach culture."', 'A typical international-night talk.', null, [ACT.orientation]),

    createContentItem('culture', '/ˈkʌltʃər/', 'shared way of life', 'word', 'American culture is highly individualist.', 'Adj: "cultural".', null, [ACT.vocabulary]),
    createContentItem('feature', '/ˈfiːtʃər/', 'distinctive trait', 'word', 'A unique feature of Boston is its accent.', 'Verb: to feature.', null, [ACT.vocabulary]),
    createContentItem('region', '/ˈriːdʒən/', 'geographic area', 'word', 'The Pacific Northwest is a US region.', 'Adj: "regional".', null, [ACT.vocabulary]),
    createContentItem('dialect / accent', '/ˈdaɪəlɛkt/ /ˈæksɛnt/', 'regional variation', 'word', 'Cockney is a London dialect.', 'Dialect = full variation; accent = pronunciation only.', null, [ACT.vocabulary]),
    createContentItem('tradition', '/trəˈdɪʃən/', 'long-standing practice', 'word', 'Thanksgiving is an American tradition.', 'Adj: "traditional".', null, [ACT.vocabulary]),
    createContentItem('minority / majority', '/maɪˈnɒrəti/ /məˈdʒɒrəti/', 'small / large group', 'word', 'Minority cultures enrich the country.', 'Cultural, ethnic, or religious.', null, [ACT.vocabulary]),
    createContentItem('indigenous', '/ɪnˈdɪdʒənəs/', 'native to a place', 'word', 'Indigenous peoples lived here for thousands of years.', 'More respectful than "native".', null, [ACT.vocabulary]),
    createContentItem('immigrant / immigration', '/ˈɪmɪɡrənt/', 'person who moves in / the movement', 'word', 'My grandfather was an immigrant from Ireland.', 'Emigrant = leaving; immigrant = arriving.', null, [ACT.vocabulary]),
    createContentItem('diaspora', '/daɪˈæspərə/', 'community spread across countries', 'word', 'The Korean diaspora reaches every continent.', 'Used for ethnic groups dispersed globally.', null, [ACT.vocabulary]),
    createContentItem('heritage', '/ˈhɛrɪtɪdʒ/', 'inherited cultural identity', 'word', 'I\'m proud of my Italian heritage.', 'Often appears in "cultural heritage", "World Heritage".', null, [ACT.vocabulary]),
    createContentItem('per region / per city', '/pər ˈriːdʒən/', 'one-by-each', 'word', 'Food varies per region.', 'Equivalent to Korean -별.', null, [ACT.vocabulary]),

    createContentItem('"go pick up" /ɡoʊ pɪˈkʌp/', '/ɡoʊ pɪˈkʌp/', 'Linked: "go" + "pick up" — no pause.', 'word', 'I\'ll go pick up some groceries.', 'Common errand verb.', null, [ACT.pronunciation]),
    createContentItem('"go upstairs" /ɡoʊ ˈʌpsˌtɛərz/', '/ɡoʊ ˈʌpsˌtɛərz/', 'Linking final /oʊ/ + initial /ʌ/.', 'word', 'Go upstairs and grab my jacket.', 'Consonant-vowel linking.', null, [ACT.pronunciation]),
    createContentItem('"including" /ɪnˈkluːdɪŋ/', '/ɪnˈkluːdɪŋ/', 'Stress on syllable 2; soft /d/.', 'word', 'Many places, including Boston and NYC, have unique accents.', 'Always a preposition; followed by noun(s).', null, [ACT.pronunciation]),
    createContentItem('"as well as" /əz wɛl əz/', '/əz wɛl əz/', 'Reduce both "as" to /əz/.', 'word', 'Korean food is famous in Asia as well as in the US.', 'Connector — note "as well as" + noun phrase.', null, [ACT.pronunciation]),

    createContentItem(
      '"go pick up / go grab / go get + N"',
      'errand verb pattern',
      'In English, "go" is often followed by a bare verb of action (no "and") to describe an errand.',
      'sentence',
      'I\'ll go pick up some bread. — Let\'s go grab coffee. — Can you go get the kids?',
      'Casual; standard alternative is "go and + V": "go and pick up".',
      [
        { target: 'go + bare V (errand)', english: 'casual: "go pick up"' },
        { target: 'go and + V', english: 'slightly more formal' },
        { target: 'come + bare V', english: '"come help me"' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"the N that S V" / "the N where / who"',
      'descriptive relative clauses',
      'Defining relative clauses identify the N.',
      'sentence',
      'Boston is the city that I grew up in. — The dialect that fascinates me most is Cockney. — She\'s the friend who introduced me to K-pop.',
      'Relative pronouns: that (things or people), who (people), where (places), when (times).',
      [
        { target: 'the N that + S + V', english: 'thing or person' },
        { target: 'the N who + V', english: 'person, subject' },
        { target: 'the N where + S + V', english: 'place' },
        { target: 'omit "that" when N is object', english: '"the city I grew up in"' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"including + X, Y, and Z" — inclusion',
      'list with examples',
      'Add specific examples after a general statement.',
      'sentence',
      'Many US cities, including Boston, NYC, and Chicago, have strong neighborhood identity. — Several languages are spoken at home, including Spanish, Mandarin, and Tagalog.',
      'Always preceded by a comma; followed by 2-3+ examples.',
      [
        { target: 'general + , including + examples', english: 'standard pattern' },
        { target: 'such as + examples', english: 'less formal, similar' },
        { target: 'e.g. (formal) / like (casual)', english: 'compact alternatives' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"as well as / along with + N" — addition',
      'add an item to a list',
      'Add an item in formal or written register.',
      'sentence',
      'The festival features music, as well as food and dance. — Native Americans, along with African Americans, shaped American music. — She speaks Korean as well as Japanese.',
      'Note: "as well as" + N (or V-ing); "along with" + N. Subject-verb usually agrees with the FIRST noun, not the added one.',
      [
        { target: 'A + as well as + B', english: 'A is main; B is added' },
        { target: 'along with + N', english: 'similar; slightly more concrete' },
        { target: 'in addition to + N', english: 'formal alternative' },
      ],
      [ACT.grammar],
    ),

    createContentItem(
      'Market explanation',
      'speaking practice',
      'Explain a market using "the N that" + "including".',
      'sentence',
      'Pike Place Market in Seattle is the place that I always recommend, including the fish-throwing show, the first Starbucks, and dozens of food stalls.',
      'Frame: "X is the N that I recommend, including + examples."',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Game explanation',
      'reading practice',
      'Read this short explanation.',
      'sentence',
      'Cricket is the game that defines a British summer. Played across the Commonwealth — including the UK, India, Australia, and South Africa — it has two main formats. Test cricket lasts five days, as well as one-day matches that wrap in eight hours. If you go to a match, you can go grab a pint, watch slowly, and enjoy the social atmosphere as much as the game itself.',
      'Game intro using all 4 patterns.',
      [
        { target: 'the game that defines a British summer', english: 'descriptive relative' },
        { target: 'including the UK, India, Australia, and South Africa', english: 'inclusion' },
        { target: 'as well as one-day matches', english: 'addition' },
        { target: 'go grab a pint', english: 'errand verb' },
      ],
      [ACT.readingSpeaking],
    ),

    createContentItem(
      'Accent presentation',
      'class dialogue',
      'After a presentation on UK accents.',
      'conversation',
      'Presenter: That covers the main UK accents — including Cockney, Geordie, and Scouse.\nAttendee A: Great talk. Could you say more about the Scouse accent? Is that the one that Liverpool speaks?\nPresenter: Yes — Scouse is the dialect that Liverpool is famous for. It has Irish and Welsh influences, as well as some Scandinavian.\nAttendee B: Are there accents that are dying out?\nPresenter: A few. Cockney is the accent that\'s gradually being replaced by Multicultural London English.\nAttendee A: Interesting. Can I go pick up your slide deck after class?\nPresenter: Sure, I\'ll email it.',
      'Note follow-up questions + all 4 patterns.',
      [
        { target: 'including Cockney, Geordie, and Scouse', english: 'inclusion' },
        { target: 'Is that the one that Liverpool speaks?', english: 'descriptive relative + question' },
        { target: 'as well as some Scandinavian', english: 'addition' },
        { target: 'go pick up your slide deck', english: 'errand verb' },
      ],
      [ACT.listeningSpeaking],
    ),

    createContentItem(
      'Indigenous culture article',
      'reading + writing',
      'Read this short piece.',
      'sentence',
      'The Māori are the indigenous people that have lived in New Zealand for over 700 years. Their language, te reo Māori, is one of New Zealand\'s official languages, along with English. Cultural traditions include the haka (a ceremonial dance), as well as intricate tattooing called tā moko. Visitors can go visit a marae (meeting ground) on guided cultural tours.',
      'Cultural article style.',
      [
        { target: 'the indigenous people that have lived', english: 'descriptive relative' },
        { target: 'along with English', english: 'addition' },
        { target: 'including the haka, as well as tā moko', english: 'inclusion + addition' },
        { target: 'go visit a marae', english: 'errand verb' },
      ],
      [ACT.readingWriting],
    ),
    createContentItem(
      'Writing prompt',
      'cultural sketch',
      'Write 3-4 sentences about an indigenous or minority culture from your country.',
      'sentence',
      'Example: The Ainu are the indigenous people that have lived in Hokkaido for thousands of years. Their language, along with Japanese, was once widely spoken. Traditional crafts include wood carving, as well as embroidered clothing. Visitors can go see Ainu villages near Sapporo.',
      'Use all 4 patterns.',
      null, [ACT.readingWriting],
    ),

    createContentItem(
      'Major US / UK / AU dialects',
      'cultural overview',
      'US: Southern (drawl), NYC (fast, tough), Boston (dropped R), AAVE (African American Vernacular English). UK: Cockney (London), Geordie (Newcastle), Scouse (Liverpool), Received Pronunciation (RP, formal). AU: Aussie (informal "g\'day"), Strine.',
      'sentence',
      'AAVE is a legitimate linguistic system, not "broken English".',
      'Dialects carry identity — treat them with respect.',
      [
        { target: 'Southern, NYC, Boston, AAVE (US)', english: 'major US dialects' },
        { target: 'Cockney, Geordie, Scouse, RP (UK)', english: 'major UK dialects' },
        { target: 'Aussie / Strine (AU)', english: 'distinctive AU accent' },
        { target: 'all are legitimate languages', english: 'no "right" accent' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Indigenous cultures',
      'respect & recognition',
      'US: Native American / American Indian — 574 federally recognized tribes. AU: Aboriginal + Torres Strait Islander. NZ: Māori. Canada: First Nations + Inuit + Métis. Use these terms with care; do not say "Indian" for Native American in modern English.',
      'sentence',
      'Each country has different terminology — research before you speak.',
      'Modern terms reflect respect and self-determination.',
      [
        { target: 'Native American (US)', english: 'preferred over "Indian"' },
        { target: 'Aboriginal / Torres Strait Islander (AU)', english: 'two distinct groups' },
        { target: 'Māori (NZ)', english: 'indigenous people of NZ' },
        { target: 'First Nations / Inuit / Métis (CA)', english: 'three Indigenous categories' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Cultural presentation outline',
      'consolidation task',
      'Outline a 5-minute presentation about your culture. Use all 4 patterns.',
      'conversation',
      'Tutor: What culture will you present on?\nYou: [name + descriptive relative — "the region that …"]\nTutor: What features stand out?\nYou: [list with "including" + "as well as"]\nTutor: How can people experience it?\nYou: [practical: "go visit / go try / go pick up"]\nTutor: [thanks]',
      'AI tutor will play your audience member.',
      [
        { target: 'the N that S V', english: 'descriptive relative' },
        { target: 'including + X, Y, Z', english: 'inclusion' },
        { target: 'as well as + N', english: 'addition' },
        { target: 'go + V + N', english: 'errand pattern' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
