// Level 2 Adult Unit 10 — Rules and Obligations (English)
// Functions: must/should/have to, company policies, code of conduct.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2au10-orientation',
  pronunciation: 'en-l2au10-pronunciation',
  vocabularyRules: 'en-l2au10-vocab-rules',
  vocabularyConduct: 'en-l2au10-vocab-conduct',
  grammarModals: 'en-l2au10-grammar-modals',
  grammarPolicy: 'en-l2au10-grammar-policy',
  reading: 'en-l2au10-reading',
  listening: 'en-l2au10-listening',
  writing: 'en-l2au10-writing',
  culture: 'en-l2au10-culture',
  task: 'en-l2au10-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Use must/have to/should/may correctly in workplace contexts.', 'Read a company code of conduct.', 'Acknowledge a policy violation appropriately.', 'Negotiate a flexible rule (WFH, dress code).'],
    task: 'Picture your manager explaining the dress code — and you have a question about it.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Modal rhythm',
    goals: ['Reduce "have to" → "hafta" /ˈhæftə/.', 'Stress "MUST" for emphasis; "should" weak in connected speech.', '"May" /meɪ/ vs "might" /maɪt/.'],
    task: 'Read 3 modal sentences aloud.' },
  { id: ACT.vocabularyRules, section: 'Vocabulary I', title: 'Rules + policies',
    goals: ['Use rule, policy, regulation, requirement, expectation, mandatory, optional, prohibited.'],
    task: 'Define 5 terms.' },
  { id: ACT.vocabularyConduct, section: 'Vocabulary II', title: 'Code of conduct',
    goals: ['Use harassment, discrimination, confidentiality, conflict of interest, NDA, code of conduct.'],
    task: 'List 5 conduct terms.' },
  { id: ACT.grammarModals, section: 'Grammar I', title: 'Modals: must / have to / should / may',
    goals: ['"must" = strong obligation (formal).', '"have to" = obligation (more casual).', '"should" = recommendation.', '"may / can" = permission. "may not" = prohibition (formal).'],
    task: 'Write 4 sentences, one per modal.' },
  { id: ACT.grammarPolicy, section: 'Grammar II', title: 'Policy language',
    goals: ['"Employees are expected to + V".', '"All staff must + V".', '"Violations may result in + N".'],
    task: 'Write 3 policy lines.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'Employee handbook excerpt',
    goals: ['Read a typical handbook policy.'],
    task: 'Summarize 3 rules in your own words.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Policy clarification',
    goals: ['Follow an HR clarification dialogue.'],
    task: 'Reproduce with your own question.' },
  { id: ACT.writing, section: 'Writing', title: 'Policy acknowledgment',
    goals: ['Write a 4-line acknowledgment after reading the policy.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US at-will employment',
    goals: ['Understand at-will employment (most US states).', 'Know protected classes (race, gender, religion, etc.).', 'Know NDA + non-compete basics.'],
    task: 'Compare with employment in your country.' },
  { id: ACT.task, section: 'Task', title: 'Clarify a policy',
    goals: ['Combine read + question + acknowledge.'],
    task: 'Roleplay clarifying the WFH policy with HR.' },
];

const lesson = {
  title: 'Level 2 (Workplace) · Unit 10: All staff must — Rules and Obligations',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'modal-must-en', label: 'Stating obligations', goal: 'Use "must / have to / should / may".' },
    { id: 'policy-language-en', label: 'Policy language', goal: 'Use "are expected to / must / may result in".' },
    { id: 'clarifying-policy-en', label: 'Clarifying policy', goal: 'Use "Could you clarify if + clause?".' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'rules and obligations', 'By end: use modals correctly, read handbooks, clarify rules, acknowledge policies.', 'word', 'Functions: state · read · clarify · acknowledge.', 'Four rules micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'WFH policy question', 'Your company updated its WFH policy — 3 days in-office, 2 remote. You have a question about whether Fridays count as "in-office" or "remote" by default. You ask HR.', 'word', 'You: "Could you clarify if Fridays count as in-office or remote by default?"', 'Standard policy clarification.', null, [ACT.orientation]),

    createContentItem('"hafta" /ˈhæftə/', '/ˈhæftə/', 'Casual reduction of "have to".', 'word', 'I hafta finish this report.', 'Don\'t write — speak only.', null, [ACT.pronunciation]),
    createContentItem('MUST /mʌst/', '/mʌst/', 'Strong stress for emphasis.', 'word', 'All staff MUST complete the training.', 'Heavy weight in formal speech.', null, [ACT.pronunciation]),
    createContentItem('may /meɪ/ vs might /maɪt/', '/meɪ/ vs /maɪt/', 'Different vowels, same meaning ("possible").', 'word', 'You may leave early. — It might rain.', '"May" = permission; "might" = possibility (overlap exists).', null, [ACT.pronunciation]),

    createContentItem('rule / policy', '/ruːl/ /ˈpɒləsi/', 'individual / company-wide', 'word', 'The company has a clear vacation policy.', 'Rule = specific; policy = broad.', null, [ACT.vocabularyRules]),
    createContentItem('regulation', '/ˌrɛɡjuˈleɪʃən/', 'government-set rule', 'word', 'Federal regulations require this.', 'Often legally binding.', null, [ACT.vocabularyRules]),
    createContentItem('requirement / expectation', '/rɪˈkwaɪərmənt/ /ˌɛkspɛkˈteɪʃən/', 'must / should', 'word', 'It\'s a requirement, not an expectation.', 'Requirement = mandatory; expectation = strongly recommended.', null, [ACT.vocabularyRules]),
    createContentItem('mandatory / optional', '/ˈmændətɔːri/ /ˈɒpʃənəl/', 'required / not required', 'word', 'The training is mandatory.', 'Common HR language.', null, [ACT.vocabularyRules]),
    createContentItem('prohibited / banned', '/prəˈhɪbɪtɪd/ /bænd/', 'not allowed', 'word', 'Smoking is prohibited on premises.', 'Formal: prohibited; casual: banned / not allowed.', null, [ACT.vocabularyRules]),
    createContentItem('violation', '/ˌvaɪəˈleɪʃən/', 'breach of policy', 'word', 'This is a violation of company policy.', 'Adj: in violation of.', null, [ACT.vocabularyRules]),

    createContentItem('harassment', '/həˈræsmənt/', 'unwanted, abusive behavior', 'word', 'Zero-tolerance for sexual harassment.', 'Adj: harassing.', null, [ACT.vocabularyConduct]),
    createContentItem('discrimination', '/dɪˌskrɪmɪˈneɪʃən/', 'unfair treatment based on group', 'word', 'Discrimination based on race is illegal.', 'Protected categories vary by country.', null, [ACT.vocabularyConduct]),
    createContentItem('confidentiality', '/ˌkɒnfɪˌdɛnʃiˈæləti/', 'keeping info private', 'word', 'Sign the confidentiality agreement.', 'NDA is short form.', null, [ACT.vocabularyConduct]),
    createContentItem('conflict of interest', '/ˈkɒnflɪkt ɒv ˈɪntrəst/', 'personal benefit vs job duty', 'word', 'Disclose any conflict of interest.', 'Common in legal / contracting.', null, [ACT.vocabularyConduct]),
    createContentItem('NDA (Non-Disclosure Agreement)', '/ɛn diː eɪ/', 'legal confidentiality contract', 'word', 'You\'ll sign an NDA on Day 1.', 'Standard in tech, finance, biotech.', null, [ACT.vocabularyConduct]),
    createContentItem('code of conduct', '/koʊd ɒv ˈkɒndʌkt/', 'company behavior rules', 'word', 'Read the code of conduct carefully.', 'Usually in the employee handbook.', null, [ACT.vocabularyConduct]),

    createContentItem(
      'Modal verbs',
      'workplace tone',
      'Four modal verbs cover obligation, permission, and possibility.',
      'sentence',
      'You must wear a badge in the building. (strong obligation, formal)\nYou have to clock in by 9. (obligation, casual)\nYou should review the document before the meeting. (recommendation)\nYou may take Fridays off if your work is complete. (permission)\nYou may not enter without authorization. (formal prohibition)',
      'Pick by audience: "must" in handbooks, "have to" in conversation.',
      [
        { target: 'must + bare V', english: 'strong obligation, formal' },
        { target: 'have to + bare V', english: 'obligation, casual' },
        { target: 'should + bare V', english: 'recommendation' },
        { target: 'may / can + bare V', english: 'permission' },
        { target: 'may not + bare V', english: 'formal prohibition' },
      ],
      [ACT.grammarModals],
    ),
    createContentItem(
      'Policy language',
      'standard HR phrasings',
      'Used in handbooks, codes of conduct.',
      'sentence',
      'Employees are expected to maintain confidentiality. — All staff must complete annual training. — Violations may result in disciplinary action up to and including termination.',
      'Passive voice + formal modals are standard.',
      [
        { target: 'Employees are expected to + V', english: 'norm/expectation' },
        { target: 'All staff must + V', english: 'firm rule' },
        { target: 'Violations may result in + consequence', english: 'enforcement language' },
        { target: 'up to and including + N', english: 'extreme possibility' },
      ],
      [ACT.grammarPolicy],
    ),
    createContentItem(
      'Clarifying a policy',
      'asking HR',
      'Polite, specific questions.',
      'sentence',
      'Could you clarify if Fridays count as in-office or remote? — I have a question about the bereavement policy. — Is there an exception for new hires?',
      'Be specific — vague questions get vague answers.',
      [
        { target: 'Could you clarify if + clause?', english: 'specific Q' },
        { target: 'I have a question about + policy', english: 'open Q' },
        { target: 'Is there an exception for + group?', english: 'exception Q' },
      ],
      [ACT.grammarPolicy],
    ),

    createContentItem(
      'Employee handbook excerpt',
      'reading practice',
      'Read this typical handbook policy.',
      'sentence',
      'SECTION 4.2: REMOTE WORK POLICY\n\nEffective March 1, 2024, the company adopts a hybrid work schedule. Employees are expected to be in-office Monday, Tuesday, and Thursday. Wednesday and Friday are remote-eligible. All staff must use the company\'s VPN when working remotely. Fully remote requests must be approved by your manager and HR.\n\nViolations of this policy may result in revocation of remote-work privileges and, in repeated cases, disciplinary action.',
      'Standard handbook policy.',
      [
        { target: 'Effective + date', english: 'when policy starts' },
        { target: 'Employees are expected to + V', english: 'normative' },
        { target: 'All staff must + V', english: 'firm rule' },
        { target: 'requests must be approved by + N', english: 'process' },
        { target: 'Violations may result in + consequence', english: 'enforcement' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Policy clarification',
      'HR dialogue',
      'Asking about WFH details.',
      'conversation',
      'You: Hi, I wanted to ask about the new WFH policy.\nHR: Sure, what\'s your question?\nYou: Could you clarify if Fridays count as in-office or remote by default?\nHR: Friday is remote-eligible — meaning you can choose, as long as you\'re online during business hours.\nYou: Got it. Is there an exception if my team is doing a Friday workshop in-office?\nHR: In that case, you should come in. Coordinate with your manager.\nYou: Perfect. One more — does the VPN need to be on the entire workday?\nHR: Yes, all staff must keep the VPN on while working remotely.\nYou: Thanks, that\'s clear now.',
      'Polite, specific clarification.',
      [
        { target: 'Could you clarify if + clause?', english: 'specific Q' },
        { target: 'Is there an exception if + clause?', english: 'edge case Q' },
        { target: 'all staff must + V', english: 'HR repeats rule' },
        { target: 'Thanks, that\'s clear now', english: 'polite close' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Policy acknowledgment',
      'writing model',
      'After reading the handbook.',
      'sentence',
      'Hi HR,\n\nI\'ve read and understand the updated WFH policy (Section 4.2). I acknowledge that I must be in-office Mon, Tue, Thu, and that I may work remotely on Wed and Fri (with VPN on). I have no further questions at this time.\n\nThanks,\nMin-su Kim',
      'Standard acknowledgment.',
      [
        { target: 'I\'ve read and understand + policy', english: 'acknowledgment' },
        { target: 'I acknowledge that I must + V', english: 'reaffirm obligation' },
        { target: 'and that I may + V', english: 'reaffirm permission' },
        { target: 'I have no further questions at this time', english: 'standard close' },
      ],
      [ACT.writing],
    ),

    createContentItem(
      'US at-will employment',
      'cultural overview',
      'US: at-will employment in 49 states — employer or employee can end the relationship at any time, for any legal reason, without notice. UK/EU: stronger worker protection — notice periods, severance, unfair-dismissal protections. US protected classes: race, color, religion, sex, national origin, age (40+), disability, genetic info, plus state additions.',
      'sentence',
      'At-will means you can be fired without cause — but NOT for being in a protected class.',
      'Document everything; whistleblowers are protected federally.',
      [
        { target: 'at-will employment (US)', english: 'either side can end' },
        { target: 'protected classes', english: 'discrimination protected' },
        { target: 'UK/EU: notice + severance', english: 'stronger protection' },
        { target: 'NDA + non-compete', english: 'common addendums' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Clarify the WFH policy',
      'consolidation task',
      'AI tutor plays HR. Clarify 2-3 details about the WFH policy.',
      'conversation',
      'You: [opener]\nTutor: [response]\nYou: [specific Q with "Could you clarify if"]\nTutor: [explain]\nYou: [follow-up Q with "Is there an exception"]\nTutor: [explain]\nYou: [acknowledge + close]',
      'AI tutor plays HR.',
      [
        { target: 'Could you clarify if + clause?', english: 'specific Q' },
        { target: 'Is there an exception for + N?', english: 'edge case' },
        { target: 'all staff must + V', english: 'HR repeats rule' },
        { target: 'Thanks, that\'s clear', english: 'polite close' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
