// Level 1 Unit 8 — Shopping (English)
// Functions: asking prices, paying, returning items, basic shopping conversations.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u8-orientation',
  pronunciation: 'en-l1u8-pronunciation',
  vocabularyNumbers: 'en-l1u8-vocab-nums',
  vocabularyItems: 'en-l1u8-vocab-items',
  vocabularyPayment: 'en-l1u8-vocab-payment',
  grammarPrices: 'en-l1u8-grammar-prices',
  grammarRequest: 'en-l1u8-grammar-request',
  grammarComparison: 'en-l1u8-grammar-compare',
  reading: 'en-l1u8-reading',
  listening: 'en-l1u8-listening',
  writing: 'en-l1u8-writing',
  culture: 'en-l1u8-culture',
  task: 'en-l1u8-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Ask "How much is …?" and read prices.', 'Pay with cash or card.', 'Politely request items.', 'Compare prices with -er / more.'],
    task: 'Imagine shopping at an American or British store — you ask prices, pay, and politely return an item.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Numbers + dollars',
    goals: ['Distinguish "13" /θɜːrˈtiːn/ from "30" /ˈθɜːrti/ — stress and ending differ.', 'Pronounce $2.50 as "two fifty" or "two dollars and fifty cents".'],
    task: 'Read 5 prices aloud.' },
  { id: ACT.vocabularyNumbers, section: 'Vocabulary I', title: 'Numbers 11–100',
    goals: ['Memorize 11–19 (-teen) and 20–90 (-ty) + 100.'],
    task: 'Count from 11 to 100 in tens.' },
  { id: ACT.vocabularyItems, section: 'Vocabulary II', title: 'Common shopping items',
    goals: ['Name groceries, clothes, electronics, books.'],
    task: 'List five items you bought recently.' },
  { id: ACT.vocabularyPayment, section: 'Vocabulary III', title: 'Payment & service words',
    goals: ['Use cash, card, receipt, change, refund, discount, sale.'],
    task: 'Use 5 payment-related words.' },
  { id: ACT.grammarPrices, section: 'Grammar I', title: '"How much is …?" + price answer',
    goals: ['Ask "How much is/are …?".', 'Reply with "It\'s + price" / "They\'re + price each".'],
    task: 'Make 3 price Q&A pairs.' },
  { id: ACT.grammarRequest, section: 'Grammar II', title: 'Polite requests — "Can I have…?" / "Could I get…?"',
    goals: ['Use "Can I have/get…?" for casual.', 'Use "Could I have…?" / "May I have…?" for polite/formal.', 'Add "please" always.'],
    task: 'Make 3 polite requests.' },
  { id: ACT.grammarComparison, section: 'Grammar III', title: 'Comparing prices — -er / more',
    goals: ['Short adjectives: cheap → cheaper (add -er).', 'Long adjectives: expensive → more expensive (add "more").', 'Use "than" with comparisons.'],
    task: 'Compare 3 pairs of items.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A shopping receipt',
    goals: ['Read a receipt and identify items, prices, total.'],
    task: 'Answer comprehension questions.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'At the store',
    goals: ['Follow two service dialogues.'],
    task: 'Reproduce with your own items.' },
  { id: ACT.writing, section: 'Writing', title: 'Shopping list',
    goals: ['Write 3–5 sentences about a shopping trip.'],
    task: 'Write your own shopping summary.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Shopping in English-speaking countries',
    goals: ['Know: prices are usually fixed (no haggling at chain stores).', 'Sales tax may be added at the register (US).', 'Tip nothing for retail; 15-20% for restaurants.'],
    task: 'Plan how to handle paying at a US store.' },
  { id: ACT.task, section: 'Task', title: 'Return + exchange',
    goals: ['Combine price asking + polite request + return.'],
    task: 'Roleplay returning an item at a clothing store.' },
];

const lesson = {
  title: 'Level 1 · Unit 8: How much is this? — Shopping',
  category: 'shopping',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-price', label: 'Asking the price', goal: 'Use "How much is …?".' },
    { id: 'making-purchase', label: 'Making a purchase', goal: 'Use "I\'ll take it" or "I\'ll have…".' },
    { id: 'polite-request', label: 'Polite request', goal: 'Use "Can/Could I have…?" + "please".' },
  ],
  relatedPools: ['topic-shopping', 'topic-numbers'],
  content: [
    createContentItem('Lesson goal', 'shopping basics', 'By end: ask prices, pay by card/cash, return items, compare prices.', 'word', 'Functions: ask price · pay · request · compare · return.', 'Five shopping micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'at the store', 'You\'re at a clothing store. You like a shirt but the size is wrong — you need to ask the price, then return it after buying.', 'word', 'You: "Excuse me, how much is this shirt?" — Staff: "It\'s twenty-five dollars."', 'A typical service exchange.', null, [ACT.orientation]),

    createContentItem('13 vs 30', '/θɜːrˈtiːn/ vs /ˈθɜːrti/', 'Teen numbers (13–19) stress the SECOND syllable. Tens numbers (20, 30, …) stress the FIRST.', 'word', 'thirteen /θɜːrˈtiːn/ vs thirty /ˈθɜːrti/', 'A core L2 distinction — many learners merge them.', null, [ACT.pronunciation]),
    createContentItem('14 vs 40', '/fɔːrˈtiːn/ vs /ˈfɔːrti/', 'Same stress contrast.', 'word', 'fourteen /fɔːrˈtiːn/ vs forty /ˈfɔːrti/', 'Note also: "forty" has NO "u" — spelling trap.', null, [ACT.pronunciation]),
    createContentItem('$2.50', '"two fifty" or "two dollars and fifty cents"', 'Two ways to read prices. Casual: "two fifty"; formal/clear: "two dollars and fifty cents".', 'word', '$2.50 / $1.99 / $19.99', 'Common to drop the cents in casual speech: "twenty bucks" for $20.', null, [ACT.pronunciation]),
    createContentItem('cash /kæʃ/', '/kæʃ/', 'Short, sharp /æ/ vowel, voiceless /ʃ/ at end.', 'word', 'I\'ll pay cash.', 'Distinct from "cache" (same pronunciation but different meaning: a hidden store).', null, [ACT.pronunciation]),

    createContentItem('11 eleven', '/ɪˈlɛvən/', 'eleven', 'word', 'I have eleven dollars.', 'Stress on the second syllable.', null, [ACT.vocabularyNumbers]),
    createContentItem('12 twelve', '/twɛlv/', 'twelve', 'word', 'There are twelve months.', 'One syllable.', null, [ACT.vocabularyNumbers]),
    createContentItem('13–19 -teen', '/-ˈtiːn/', 'add "-teen" with second-syllable stress', 'word', 'thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen', 'Stress is on the second syllable (the -TEEN part).', null, [ACT.vocabularyNumbers]),
    createContentItem('20 twenty', '/ˈtwɛnti/', 'twenty', 'word', 'I\'m twenty years old.', 'Stress on the first syllable.', null, [ACT.vocabularyNumbers]),
    createContentItem('30–90 -ty', '/-ti/', 'add "-ty" with first-syllable stress', 'word', 'thirty, forty, fifty, sixty, seventy, eighty, ninety', 'Note: forty (no "u"), fifty (not "fivety").', null, [ACT.vocabularyNumbers]),
    createContentItem('21–99 compound', 'twenty-one, twenty-two …', 'Two-digit numbers join with a hyphen.', 'word', 'twenty-one, thirty-five, ninety-nine', 'Always hyphenated in writing.', null, [ACT.vocabularyNumbers]),
    createContentItem('100 hundred', '/ˈhʌndrəd/', 'one hundred', 'word', 'one hundred / a hundred', 'Both "a hundred" and "one hundred" are correct.', null, [ACT.vocabularyNumbers]),
    createContentItem('1,000 thousand', '/ˈθaʊzənd/', 'one thousand', 'word', 'two thousand and twenty-six', 'British English includes "and"; American English often omits.', null, [ACT.vocabularyNumbers]),

    createContentItem('shirt', '/ʃɜːrt/', 'a clothing item for the upper body', 'word', 'This shirt is $30.', 'Plural: shirts.', null, [ACT.vocabularyItems]),
    createContentItem('pants', '/pænts/', 'a clothing item for the legs (American)', 'word', 'These pants are too tight.', 'Always plural. British: "trousers".', null, [ACT.vocabularyItems]),
    createContentItem('shoes', '/ʃuːz/', 'footwear', 'word', 'I need new shoes.', 'Always plural. Singular: "a shoe" (rare).', null, [ACT.vocabularyItems]),
    createContentItem('jacket', '/ˈdʒækət/', 'a short coat', 'word', 'My jacket is warm.', 'Plural: jackets.', null, [ACT.vocabularyItems]),
    createContentItem('hat', '/hæt/', 'head covering', 'word', 'I bought a new hat.', 'Plural: hats.', null, [ACT.vocabularyItems]),
    createContentItem('bread', '/brɛd/', 'baked food made from flour', 'word', 'I need bread.', 'Uncountable noun — no "a bread"; say "a loaf of bread".', null, [ACT.vocabularyItems]),
    createContentItem('milk', '/mɪlk/', 'white liquid from cows', 'word', 'I drink milk every morning.', 'Uncountable — no "a milk"; say "a glass of milk".', null, [ACT.vocabularyItems]),
    createContentItem('apple', '/ˈæpəl/', 'a round fruit', 'word', 'I eat an apple every day.', 'Countable; takes "an" because of vowel sound.', null, [ACT.vocabularyItems]),
    createContentItem('book', '/bʊk/', 'bound printed pages', 'word', 'This book is $15.', 'Countable: a book / two books.', null, [ACT.vocabularyItems]),
    createContentItem('phone', '/foʊn/', 'a mobile phone', 'word', 'A new phone is expensive.', 'Short for "telephone".', null, [ACT.vocabularyItems]),

    createContentItem('cash', '/kæʃ/', 'paper money + coins', 'word', 'I\'ll pay cash.', 'Uncountable; no article needed.', null, [ACT.vocabularyPayment]),
    createContentItem('card', '/kɑːrd/', 'credit or debit card', 'word', 'Can I pay by card?', 'Specify if needed: "credit card" / "debit card".', null, [ACT.vocabularyPayment]),
    createContentItem('receipt', '/rɪˈsiːt/', 'paper proof of purchase', 'word', 'Could I have a receipt, please?', 'Silent "p" in spelling.', null, [ACT.vocabularyPayment]),
    createContentItem('change', '/tʃeɪndʒ/', 'money returned after overpayment', 'word', 'Keep the change.', 'Also a verb: to change.', null, [ACT.vocabularyPayment]),
    createContentItem('refund', '/ˈriːfʌnd/', 'returned money for a returned item', 'word', 'Can I get a refund?', 'Noun and verb same form.', null, [ACT.vocabularyPayment]),
    createContentItem('exchange', '/ɪksˈtʃeɪndʒ/', 'swap one item for another', 'word', 'I\'d like to exchange this.', 'Noun and verb same form.', null, [ACT.vocabularyPayment]),
    createContentItem('discount', '/ˈdɪskaʊnt/', 'price reduction', 'word', 'Is there a discount today?', 'Stress on the first syllable.', null, [ACT.vocabularyPayment]),
    createContentItem('sale', '/seɪl/', 'period when prices are lowered', 'word', 'These shoes are on sale.', '"On sale" — reduced price. Different from "for sale" (available to buy).', null, [ACT.vocabularyPayment]),
    createContentItem('price', '/praɪs/', 'how much something costs', 'word', 'What\'s the price?', 'Synonym for "cost".', null, [ACT.vocabularyPayment]),
    createContentItem('expensive / cheap', '/ɪkˈspɛnsɪv/ /tʃiːp/', 'adjectives for high / low price', 'word', 'This bag is expensive. That one is cheap.', '"Cheap" can sometimes imply low quality.', null, [ACT.vocabularyPayment]),

    createContentItem(
      '"How much is …?"',
      'singular price',
      'Use "How much is" for one item.',
      'sentence',
      'How much is this shirt? — It\'s $25.',
      'In speech, "How much\'s" is rare; usually just "How much is".',
      [
        { target: 'How much is …?', english: 'asks for the price of one item' },
        { target: 'It\'s $X', english: 'short reply: "It is X dollars"' },
      ],
      [ACT.grammarPrices],
    ),
    createContentItem(
      '"How much are …?"',
      'plural price',
      'For multiple items or always-plural items (pants, shoes), use "How much are".',
      'sentence',
      'How much are these shoes? — They\'re $50.\nHow much are these pants? — They\'re $30 each.',
      'Note: pants and shoes are grammatically plural.',
      null,
      [ACT.grammarPrices],
    ),
    createContentItem(
      'Other price questions',
      'alternatives',
      'You can also ask: "What does this cost?" / "What\'s the price?".',
      'sentence',
      'What does this cost? — It costs $25.\nWhat\'s the price? — Twenty-five dollars.',
      'All three forms are common in shops.',
      null,
      [ACT.grammarPrices],
    ),

    createContentItem(
      'Casual: "Can I have…?" / "Can I get…?"',
      'casual request',
      'Use "Can I have/get + N + please" in casual/everyday settings.',
      'sentence',
      'Can I have a coffee, please? — Can I get the receipt?',
      'Always pair with "please" — without it, sounds rude.',
      [
        { target: 'Can I have …?', english: 'casual request' },
        { target: 'Can I get …?', english: 'slightly more American' },
      ],
      [ACT.grammarRequest],
    ),
    createContentItem(
      'Polite: "Could I have…?" / "May I have…?"',
      'polite/formal',
      '"Could I" sounds more polite. "May I" is formal — common in shops, restaurants.',
      'sentence',
      'Could I have a bag, please? — May I have a receipt, please?',
      'Adding "please" intensifies politeness further.',
      [
        { target: 'Could I have …?', english: 'polite (default for strangers)' },
        { target: 'May I have …?', english: 'formal/very polite' },
      ],
      [ACT.grammarRequest],
    ),
    createContentItem(
      '"I\'ll take it / them"',
      'commit to buy',
      'Standard phrase to commit to a purchase. "It" for singular, "them" for plural.',
      'sentence',
      'I\'ll take it. — I\'ll take these. — I\'ll take two.',
      'Alternative: "I\'ll have …" — similar meaning.',
      null,
      [ACT.grammarRequest],
    ),
    createContentItem(
      '"I\'d like to + verb"',
      'polite want',
      'A polite way to express what you want to do. "I\'d like" = "I would like".',
      'sentence',
      'I\'d like to return this. — I\'d like to exchange these shoes.',
      'More polite than "I want to …".',
      null,
      [ACT.grammarRequest],
    ),

    createContentItem(
      'Short adjectives: -er + "than"',
      'cheap → cheaper',
      'For one-syllable adjectives, add -er. For comparison, follow with "than".',
      'sentence',
      'This is cheaper than that. — Apples are cheaper than oranges.',
      'Two-syllable adjectives ending in -y: drop y, add -ier (happy → happier).',
      [
        { target: 'cheap → cheaper', english: 'add -er' },
        { target: 'big → bigger', english: 'double the consonant + -er' },
        { target: 'happy → happier', english: 'y → ier' },
      ],
      [ACT.grammarComparison],
    ),
    createContentItem(
      'Long adjectives: "more …" + "than"',
      'expensive → more expensive',
      'For adjectives of two+ syllables, use "more" + adjective.',
      'sentence',
      'This shirt is more expensive than that one. — Math is more difficult than English.',
      'Common error: "expensiver" — wrong. Always "more expensive".',
      [
        { target: 'expensive → more expensive', english: 'add "more"' },
        { target: 'beautiful → more beautiful', english: 'add "more"' },
        { target: 'interesting → more interesting', english: 'add "more"' },
      ],
      [ACT.grammarComparison],
    ),
    createContentItem(
      'Irregular comparatives',
      'good → better, bad → worse',
      'A few adjectives are irregular.',
      'sentence',
      'This is better than that. — My headache is worse today.',
      'Memorize: good→better, bad→worse, far→farther, little→less.',
      [
        { target: 'good → better', english: 'irregular' },
        { target: 'bad → worse', english: 'irregular' },
        { target: 'far → farther / further', english: 'farther = distance; further = degree' },
      ],
      [ACT.grammarComparison],
    ),

    createContentItem(
      'A shopping receipt',
      'reading practice',
      'Read this receipt aloud, then answer.',
      'sentence',
      'BIG MART · Receipt\n--------\n· Shirt (M) $29.99\n· Pants $45.00\n· Soap (x3) $4.50\n--------\nSubtotal $79.49\nTax (10%) $7.95\nTotal $87.44\nPayment: Visa credit\nThank you! Return policy: 7 days with receipt.',
      'Standard US-style receipt with subtotal, tax, total.',
      [
        { target: 'subtotal', english: 'price before tax' },
        { target: 'tax', english: 'sales tax, added in most US states' },
        { target: 'total', english: 'final amount to pay' },
        { target: 'return policy', english: 'rules for returning items' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences.',
      'sentence',
      'Q1: How much is the shirt? · Q2: How many soaps did she buy? · Q3: What\'s the total?',
      'Use prices with dollar amounts.',
      [
        { target: 'A1: It\'s $29.99.', english: 'singular item' },
        { target: 'A2: She bought three.', english: 'count' },
        { target: 'A3: It\'s $87.44.', english: 'total' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'At the cafe — ordering',
      'casual service',
      'A standard cafe exchange.',
      'conversation',
      'A: Hi, can I get a large coffee, please?\nB: Sure. Anything else?\nA: A blueberry muffin, please.\nB: That\'ll be $6.50. Cash or card?\nA: Card, please.\nB: Tap or insert. ... Thanks. Here\'s your receipt.\nA: Thank you!',
      'Common phrases: "Anything else?", "That\'ll be …", "Cash or card?".',
      [
        { target: 'Can I get …', english: 'casual request' },
        { target: 'Anything else?', english: 'standard upsell question' },
        { target: 'That\'ll be $X', english: 'standard total announcement' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Returning a shirt',
      'service interaction',
      'A customer returns an item.',
      'conversation',
      'A (customer): Hi, I\'d like to return this shirt.\nB (staff): Sure. Do you have the receipt?\nA: Yes, here it is.\nB: Was there a problem with it?\nA: It\'s the wrong size.\nB: No problem. I\'ll refund to your card. It\'ll show up in 3–5 days.\nA: Great, thank you!\nB: You\'re welcome. Have a good day.',
      'Standard return policy: receipt + reason.',
      [
        { target: 'I\'d like to return …', english: 'polite return request' },
        { target: 'Do you have the receipt?', english: 'standard staff question' },
        { target: 'wrong size', english: 'common reason' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'shopping trip template',
      'Use this to describe a shopping trip.',
      'sentence',
      'Yesterday, I went to [store]. I bought [N items] for [price]. The [item] was [adjective] — [more/less] [adj] than [comparison]. I paid by [cash/card]. The total was [price].',
      '[store] · [items + price] · [comparison] · [payment] · [total].',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 3–5 sentences about a recent shopping trip. Use at least one comparison and one price.',
      'sentence',
      'Example: Yesterday I went to the mall. I bought a shirt for $25 and shoes for $60. The shoes were more expensive than the shirt. I paid by card. The total was $85.',
      'Check: items + prices + comparisons + payment.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Fixed prices in chain stores',
      'no haggling',
      'In English-speaking chain stores, prices are fixed. Haggling is unusual and may be considered rude. Markets, antique shops, and used-item sales may allow polite negotiation.',
      'sentence',
      'At Walmart: pay the marked price. At a flea market: "Would you take $10?" is acceptable.',
      'In the UK/US, asking "Can you give me a discount?" at a chain store sounds odd.',
      [
        { target: 'fixed price', english: 'no negotiation expected' },
        { target: 'flea market / antique shop', english: 'polite haggling acceptable' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Sales tax (US)',
      'added at register',
      'In most US states, sales tax is NOT included in the marked price — it\'s added at the register. The advertised price will look cheaper than the actual cost.',
      'sentence',
      'Marked $10 + 8.875% tax = $10.89 at the register.',
      'In the UK and most other countries, VAT is already included in the price.',
      null, [ACT.culture],
    ),
    createContentItem(
      'Tipping rules',
      'who, how much',
      'Tipping varies widely. Retail stores: no tip. Restaurants in the US: 15–20%. Coffee shops: optional, $1–2. UK: more relaxed, 10% in restaurants is common.',
      'sentence',
      'Restaurant bill $50 → tip $7.50–$10 (US). Cafe with table service → $1–2 tip.',
      'Tip culture is heaviest in the US; lightest in Australia and most of Europe.',
      [
        { target: 'restaurant: 15–20% (US)', english: 'standard practice' },
        { target: 'cafe / coffee shop: optional', english: 'small tip welcomed' },
        { target: 'retail store: no tip', english: 'never expected' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Return + exchange',
      'consolidation task',
      'Roleplay: Return a shirt you bought yesterday. The size doesn\'t fit. Negotiate refund vs exchange.',
      'conversation',
      'You: Hi, I\'d like to [return / exchange] this shirt.\nStaff: Do you have the receipt?\nYou: [yes / no + reaction]\nStaff: What\'s the problem?\nYou: [reason]\nStaff: Refund to your card? Or exchange for another size?\nYou: [choose one]\nStaff: Sure. I\'ll process that now.',
      'AI tutor will play the staff.',
      [
        { target: 'I\'d like to return / exchange …', english: 'polite request' },
        { target: 'wrong size / too big / too small', english: 'common reasons' },
        { target: 'refund to my card', english: 'specify refund method' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
