// Level 2 Adult Unit 1 — Workplace Greetings (English)
// Adult / professional register: formal greetings, titles, self-intro, humble closes.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2au1-orientation',
  pronunciation: 'en-l2au1-pronunciation',
  vocabularyPeople: 'en-l2au1-vocab-people',
  vocabularyWork: 'en-l2au1-vocab-work',
  grammarFormal: 'en-l2au1-grammar-formal',
  grammarHumble: 'en-l2au1-grammar-humble',
  reading: 'en-l2au1-reading',
  listening: 'en-l2au1-listening',
  writing: 'en-l2au1-writing',
  culture: 'en-l2au1-culture',
  task: 'en-l2au1-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Use formal English greetings in a US/UK workplace.', 'Address managers and coworkers with proper titles (Mr./Ms./Dr./Professor).', 'Handle first-day-at-work scenarios with humility and professionalism.'],
    task: 'Picture your first day at a US tech company — greet your manager, introduce yourself, acknowledge any language gap politely.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Formal phrase rhythm',
    goals: ['Pronounce "How do you do" /haʊ dʒə duː/ with the reduced "you".', 'Pronounce "Pleased to meet you" with stress on "MEET".', 'Use full vowels in formal register — avoid heavy contractions.'],
    task: 'Read each formal greeting aloud.' },
  { id: ACT.vocabularyPeople, section: 'Vocabulary I', title: 'Workplace titles + people',
    goals: ['Use Mr./Ms./Mrs./Dr./Professor + last name.', 'Use manager, supervisor, colleague, coworker, intern, new hire.'],
    task: 'Address 5 different workplace roles correctly.' },
  { id: ACT.vocabularyWork, section: 'Vocabulary II', title: 'Workplace actions + places',
    goals: ['Use start work, clock in, clock out, leave work, office, factory, headquarters, on-site, remote.'],
    task: 'Describe your workday.' },
  { id: ACT.grammarFormal, section: 'Grammar I', title: 'Formal register',
    goals: ['Avoid contractions: "I am" not "I\'m", "do not" not "don\'t".', 'Use full forms: "I would like to" not "I\'d like to".', 'Use polite indirect questions: "Could you tell me where the printer is?"'],
    task: 'Rewrite 5 casual sentences in formal English.' },
  { id: ACT.grammarHumble, section: 'Grammar II', title: 'Humble + polite closers',
    goals: ['Use "I look forward to working with you" / "I appreciate your time" / "Thank you for the opportunity".', 'Use "I\'m still learning" / "Bear with me" / "Could you repeat that, please" for language acknowledgment.'],
    task: 'Use 3 humble closers.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'Workplace bulletin',
    goals: ['Read a corporate welcome bulletin about a new hire.'],
    task: 'Answer comprehension.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'First-day dialogue',
    goals: ['Follow a first-day workplace dialogue.'],
    task: 'Reproduce with your own background.' },
  { id: ACT.writing, section: 'Writing', title: 'Self-intro email',
    goals: ['Write a 4-5 line formal self-intro email.'],
    task: 'Write your own intro email.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US / UK workplace etiquette',
    goals: ['Understand handshake norms, eye contact, business cards in the West.', 'Know how to ask for first-name vs last-name preference.'],
    task: 'List 3 do\'s and don\'ts for a US/UK office.' },
  { id: ACT.task, section: 'Task', title: 'First day at the office',
    goals: ['Combine formal speech, titles, humble closers in one scene.'],
    task: 'Roleplay your first day.' },
];

const lesson = {
  title: 'Level 2 (Workplace) · Unit 1: Pleased to meet you — Workplace Greetings',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'workplace-greeting-en', label: 'Workplace greeting', goal: 'Open with formal greetings to seniors.' },
    { id: 'formal-self-intro-en', label: 'Formal self-introduction', goal: 'Introduce with full forms and titles.' },
    { id: 'acknowledging-language-en', label: 'Acknowledging language gap', goal: 'Use "I\'m still learning" / "Could you repeat that, please" humbly.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'workplace greetings', 'By end: use formal English, address titles correctly, handle first-day scenarios.', 'word', 'Functions: greet · introduce · humble · close.', 'Four workplace micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'first day at office', 'You start a new internship at a Silicon Valley company. Your manager, Dr. Smith, greets you. You must respond formally and politely acknowledge your English.', 'word', 'Manager: "Hello, welcome to the team!" — You: "Pleased to meet you, Dr. Smith. I\'m Min-su Kim, the new intern."', 'Standard first-day greeting.', null, [ACT.orientation]),

    createContentItem('How do you do /haʊ dʒə duː/', '/haʊ dʒə duː/', 'Reduced "you" → /dʒə/. Very formal, slightly old-fashioned.', 'word', 'Mr. Lee: How do you do. — You: How do you do.', 'Reply with the same phrase, NOT "I\'m fine".', null, [ACT.pronunciation]),
    createContentItem('Pleased to MEET you', '/pliːzd tuː miːt juː/', 'Stress on "MEET". Standard formal greeting.', 'word', 'Pleased to meet you, Dr. Smith.', 'More common than "How do you do" in US.', null, [ACT.pronunciation]),
    createContentItem('Nice to meet you', '/naɪs tuː miːt juː/', 'Casual/neutral version.', 'word', 'Nice to meet you.', 'Friendly but professional.', null, [ACT.pronunciation]),
    createContentItem('No contractions in formal', '/nɒ kənˈtrækʃənz/', 'In formal register, avoid contractions: "I am" not "I\'m".', 'word', 'I am pleased to be joining your team.', 'Reads more polished in writing too.', null, [ACT.pronunciation]),

    createContentItem('Mr. / Ms. / Mrs. / Dr.', '/ˈmɪstər/ /mɪz/ /ˈmɪsɪz/ /ˈdɒktər/', 'Standard titles + last name', 'word', 'Mr. Johnson, Ms. Lee, Dr. Patel.', 'Ms. = neutral marital status (default for women). Mrs. = married only.', null, [ACT.vocabularyPeople]),
    createContentItem('Professor / Prof.', '/prəˈfɛsər/', 'University title', 'word', 'Professor Kim teaches AI.', 'Used in academia + universities.', null, [ACT.vocabularyPeople]),
    createContentItem('manager / supervisor', '/ˈmænɪdʒər/ /ˈsuːpərvaɪzər/', 'direct boss', 'word', 'My manager is Sarah.', '"Manager" is more common; "supervisor" feels older.', null, [ACT.vocabularyPeople]),
    createContentItem('colleague / coworker', '/ˈkɒliːɡ/ /ˈkoʊˌwɜːrkər/', 'work peer', 'word', 'My colleagues are very helpful.', '"Colleague" — slightly more formal.', null, [ACT.vocabularyPeople]),
    createContentItem('intern / new hire', '/ˈɪntɜːrn/ /njuː haɪər/', 'short-term / newly employed', 'word', 'As a new hire, I have many questions.', '"Intern" = student program; "new hire" = new full-time.', null, [ACT.vocabularyPeople]),
    createContentItem('CEO / CFO / CTO', '/ˌsiː iː ˈoʊ/', 'C-suite executive titles', 'word', 'The CEO is presenting tomorrow.', 'Chief Executive / Financial / Technology Officer.', null, [ACT.vocabularyPeople]),
    createContentItem('HR (Human Resources)', '/eɪtʃ ɑːr/', 'people-management department', 'word', 'Talk to HR about benefits.', 'Handles hiring, complaints, benefits.', null, [ACT.vocabularyPeople]),
    createContentItem('team lead', '/tiːm liːd/', 'leader of a small team', 'word', 'My team lead is Mark.', 'Mid-level role between IC and manager.', null, [ACT.vocabularyPeople]),

    createContentItem('start work / clock in', '/stɑːrt wɜːrk/', 'begin shift', 'word', 'I start work at 9 AM.', '"Clock in" — formal time-tracking. "Punch in" — older/factory.', null, [ACT.vocabularyWork]),
    createContentItem('leave work / clock out', '/liːv wɜːrk/', 'end shift', 'word', 'I leave work at 6.', 'Salaried workers use "leave"; hourly use "clock out".', null, [ACT.vocabularyWork]),
    createContentItem('office / cubicle', '/ˈɒfɪs/ /ˈkjuːbɪkəl/', 'workplace / open work space', 'word', 'My office is on the 5th floor.', 'Cubicle = small partitioned space.', null, [ACT.vocabularyWork]),
    createContentItem('headquarters / HQ', '/ˈhɛdˌkwɔːrtərz/', 'main company office', 'word', 'Our HQ is in New York.', 'Always plural in form.', null, [ACT.vocabularyWork]),
    createContentItem('on-site / remote / hybrid', '/ɒn saɪt/ /rɪˈmoʊt/ /ˈhaɪbrɪd/', 'in-office / home / mix', 'word', 'We work hybrid: 3 days on-site, 2 remote.', 'Post-2020 vocabulary.', null, [ACT.vocabularyWork]),
    createContentItem('meeting / huddle', '/ˈmiːtɪŋ/ /ˈhʌdəl/', 'formal / quick meeting', 'word', 'I have a huddle at 2 PM.', 'Huddle = quick standup; meeting = scheduled longer.', null, [ACT.vocabularyWork]),

    createContentItem(
      'Formal register — avoid contractions',
      'professional speech',
      'Spell out contractions in formal contexts.',
      'sentence',
      'I am pleased to be joining your team. (NOT: I\'m)\nI would like to introduce myself. (NOT: I\'d)\nI cannot find the conference room. (NOT: can\'t)',
      'Casual contractions ("I\'m", "don\'t") sound informal in first-day greetings, emails to clients, etc.',
      [
        { target: 'I am / I would / I cannot', english: 'formal register' },
        { target: 'I\'m / I\'d / can\'t', english: 'casual register' },
        { target: 'context determines register', english: 'pick by audience' },
      ],
      [ACT.grammarFormal],
    ),
    createContentItem(
      'Indirect questions for politeness',
      'polite questions',
      'Use embedded clauses for politeness.',
      'sentence',
      'Could you tell me where the printer is? (vs Where\'s the printer?) — Would you mind sharing the document? (vs Share the doc.) — May I ask what time the meeting starts?',
      'Structure: "Could you tell me / Do you know / Would you mind + clause".',
      [
        { target: 'Could you tell me + clause?', english: 'most polite' },
        { target: 'Do you know + clause?', english: 'softer' },
        { target: 'Would you mind + V-ing?', english: 'soften a request' },
      ],
      [ACT.grammarFormal],
    ),
    createContentItem(
      'Polite closers',
      'humble + warm',
      'Standard ways to close a first meeting or email.',
      'sentence',
      'I look forward to working with you. — Thank you for the opportunity. — I appreciate your time. — Please let me know if you need anything.',
      'Always pair with a clear next step or warm thanks.',
      [
        { target: 'I look forward to + V-ing', english: 'standard close' },
        { target: 'Thank you for + N/V-ing', english: 'gratitude' },
        { target: 'I appreciate + N', english: 'warm appreciation' },
        { target: 'Please let me know if …', english: 'open communication' },
      ],
      [ACT.grammarHumble],
    ),
    createContentItem(
      'Acknowledging a language gap',
      'humble + competent',
      'Acknowledge limits without being self-deprecating.',
      'sentence',
      'I\'m still learning, so please bear with me. — Could you repeat that, please? — I want to make sure I understand correctly.',
      'Frame as growth, not weakness. Native English speakers respect humility paired with effort.',
      [
        { target: 'I\'m still learning, please bear with me', english: 'acknowledge + ask patience' },
        { target: 'Could you repeat that, please?', english: 'ask for clarification' },
        { target: 'Let me make sure I understand', english: 'check comprehension' },
      ],
      [ACT.grammarHumble],
    ),

    createContentItem(
      'Workplace bulletin',
      'reading practice',
      'Read this internal-comms post.',
      'sentence',
      'Welcome to TechCorp! Please join us in welcoming Min-su Kim to the engineering team. Min-su joins us from Kumoh National Institute of Technology, where he completed his bachelor\'s in computer science. He will report to Dr. Sarah Johnson, our VP of Engineering. Min-su, we look forward to working with you and supporting your growth here. Stop by his desk on the 5th floor to say hello.',
      'Standard corporate welcome post.',
      [
        { target: 'Please join us in welcoming + N', english: 'standard intro' },
        { target: 'Min-su joins us from + location/school', english: 'background' },
        { target: 'He will report to + manager', english: 'reporting structure' },
        { target: 'We look forward to working with you', english: 'warm welcome' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in formal English',
      'Use complete sentences.',
      'sentence',
      'Q1: Who is the new hire? · Q2: Where did he study? · Q3: Who will he report to? · Q4: Where is his desk?',
      'Use third person.',
      [
        { target: 'A1: Min-su Kim is the new hire.', english: 'name' },
        { target: 'A2: He studied at Kumoh National Institute of Technology.', english: 'school' },
        { target: 'A3: He will report to Dr. Sarah Johnson.', english: 'manager' },
        { target: 'A4: His desk is on the 5th floor.', english: 'location' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'First-day dialogue',
      'manager + intern',
      'A typical first-day conversation.',
      'conversation',
      'Manager: Welcome to the team! I\'m Sarah Johnson. Pleased to meet you.\nYou: Pleased to meet you, Dr. Johnson. I\'m Min-su Kim, the new intern.\nManager: Great to have you. Just call me Sarah — we\'re first-name here.\nYou: Thank you, Sarah. I look forward to working with you.\nManager: Likewise. How was your trip from Korea?\nYou: It was long, but I\'m excited to be here. I\'m still learning English, so please bear with me.\nManager: Of course. Don\'t hesitate to ask if anything\'s unclear. Let\'s get you set up at your desk.\nYou: Thank you for the opportunity, Sarah.',
      'Note formal-then-relaxed register; humble acknowledgment of language.',
      [
        { target: 'Pleased to meet you', english: 'formal greeting' },
        { target: 'Call me + first name', english: 'register shift' },
        { target: 'I look forward to working with you', english: 'standard close' },
        { target: 'I\'m still learning English, please bear with me', english: 'humble' },
        { target: 'Thank you for the opportunity', english: 'gratitude close' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Self-intro email',
      'writing model',
      'Send a self-intro on Day 1.',
      'sentence',
      'Subject: Introduction — Min-su Kim, New Engineering Intern\n\nDear Team,\n\nMy name is Min-su Kim, and I have just joined the engineering team as a new intern, reporting to Dr. Sarah Johnson. I graduated from Kumoh National Institute of Technology with a degree in computer science, and I am especially interested in machine-learning systems. I am still building my English fluency, so please bear with me as I learn — I appreciate your patience. I look forward to meeting each of you and contributing to the team.\n\nBest regards,\nMin-su Kim',
      'Standard new-hire intro email.',
      [
        { target: 'Subject: Introduction — [Name], [Role]', english: 'subject format' },
        { target: 'My name is X, and I have just joined …', english: 'opener' },
        { target: 'I graduated from … with a degree in …', english: 'background' },
        { target: 'I am still building my English fluency', english: 'humble acknowledgment' },
        { target: 'I look forward to meeting each of you', english: 'standard close' },
      ],
      [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write a 4-5 line first-day self-intro email.',
      'sentence',
      'Example: Subject: Hello from the new marketing intern\n\nDear Team, my name is [Your Name], and I have just joined the marketing team. I studied [field] at [school]. I am still learning the systems here, so please feel free to share tips. I look forward to working with you. Best, [Your Name]',
      'Use formal register, no contractions.',
      null, [ACT.writing],
    ),

    createContentItem(
      'US / UK workplace etiquette',
      'cultural overview',
      'Handshake: firm, 2-3 seconds, eye contact. Business cards: less common in US tech, still standard in UK/banking. First names: US/AU default to first names quickly; UK can be more reserved. Address: Mr./Ms. + last name on first meeting, then switch when invited.',
      'sentence',
      'In US tech, "call me by my first name" is the default.',
      'Tone is friendly + professional — not hierarchical.',
      [
        { target: 'firm handshake + eye contact', english: 'standard greeting' },
        { target: 'first names quickly (US/AU)', english: 'low hierarchy' },
        { target: 'Mr./Ms. + last name on first meeting', english: 'default formal' },
        { target: 'business cards less common in tech', english: 'banking/legal still use them' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Email etiquette',
      'register and structure',
      'Subject lines: specific, actionable. Opening: "Dear [Name]" (formal) or "Hi [Name]" (casual). Closing: "Best regards" / "Kind regards" / "Thanks" / "Best".',
      'sentence',
      'Match the closing to the opening: "Dear" goes with "Best regards"; "Hi" goes with "Thanks".',
      'Match register; mismatches feel off.',
      [
        { target: 'Dear [Name] → Best regards', english: 'formal pairing' },
        { target: 'Hi [Name] → Thanks', english: 'casual pairing' },
        { target: 'specific subject line', english: 'helps prioritization' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: First day roleplay',
      'consolidation task',
      'Roleplay your first day. AI tutor plays your manager. Greet, introduce yourself, ask 2 questions, close politely.',
      'conversation',
      'Tutor: Hi, welcome to the team!\nYou: [formal greeting + intro]\nTutor: Where did you study?\nYou: [background]\nTutor: Any questions?\nYou: [2 polite indirect questions]\nTutor: [helpful answers]\nYou: [polite close + humble language acknowledgment]',
      'AI tutor will play your manager.',
      [
        { target: 'Pleased to meet you, [Title] [Last name]', english: 'formal greeting' },
        { target: 'no contractions in formal speech', english: 'professional register' },
        { target: 'Could you tell me where + clause?', english: 'polite question' },
        { target: 'I\'m still learning, please bear with me', english: 'humble' },
        { target: 'I look forward to working with you', english: 'standard close' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
