// Level 1 Unit 12 — Past Activities (English)
// Functions: describing past events, simple past, regular vs irregular verbs.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u12-orientation',
  pronunciation: 'en-l1u12-pronunciation',
  vocabularyActivities: 'en-l1u12-vocab-act',
  vocabularyTime: 'en-l1u12-vocab-time',
  grammarRegular: 'en-l1u12-grammar-regular',
  grammarIrregular: 'en-l1u12-grammar-irregular',
  grammarNegationQuestion: 'en-l1u12-grammar-neg-q',
  reading: 'en-l1u12-reading',
  listening: 'en-l1u12-listening',
  writing: 'en-l1u12-writing',
  culture: 'en-l1u12-culture',
  task: 'en-l1u12-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Form simple past with regular verbs (-ed) and irregular verbs.', 'Talk about what you did, when, where, and with whom.', 'Form negation and questions in the past.'],
    task: 'Imagine a friend asks "How was your weekend?" — answer with 3-4 past-tense sentences.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '-ed endings',
    goals: ['Three pronunciations of -ed: /t/ after voiceless (worked /wɜːrkt/), /d/ after voiced (played /pleɪd/), /ɪd/ after t/d (wanted /ˈwɒntɪd/).'],
    task: 'Read each past-tense verb aloud.' },
  { id: ACT.vocabularyActivities, section: 'Vocabulary I', title: 'Activity verbs',
    goals: ['Use 15+ common activity verbs (regular and irregular).'],
    task: 'List 3 activities you did last weekend.' },
  { id: ACT.vocabularyTime, section: 'Vocabulary II', title: 'Past-time markers',
    goals: ['Use yesterday, last week/month/year, ago, this morning, recently.'],
    task: 'Pair an activity with a past-time marker.' },
  { id: ACT.grammarRegular, section: 'Grammar I', title: 'Regular past — verb + ed',
    goals: ['Add -ed to most verbs. Spelling rules: drop final e (live → lived); double consonant (stop → stopped); y → ied (study → studied).'],
    task: 'Conjugate 5 regular verbs.' },
  { id: ACT.grammarIrregular, section: 'Grammar II', title: 'Irregular past — memorize',
    goals: ['Know 20+ common irregular past forms (go → went, eat → ate, see → saw, etc.).'],
    task: 'Memorize the 20 most common.' },
  { id: ACT.grammarNegationQuestion, section: 'Grammar III', title: 'Did + not / Did + subject',
    goals: ['Negation: "didn\'t + bare verb".', 'Question: "Did + subject + bare verb?"', 'Short answers: "Yes, I did. / No, I didn\'t."'],
    task: 'Negate and question 3 past sentences.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A weekend diary',
    goals: ['Read a 5-sentence weekend diary.'],
    task: 'Answer: what, when, where, with whom?' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Weekend recap',
    goals: ['Follow a 5-turn weekend-recap dialogue.'],
    task: 'Reproduce with your own weekend.' },
  { id: ACT.writing, section: 'Writing', title: 'Your last weekend',
    goals: ['Write 4–5 past-tense sentences about last weekend.'],
    task: 'Write your own weekend diary.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Monday morning small talk',
    goals: ['Know "How was your weekend?" as the standard Monday opener.', 'Keep it positive even if your weekend was bad.'],
    task: 'Practice 3 polite weekend recaps.' },
  { id: ACT.task, section: 'Task', title: 'Tell me about your weekend',
    goals: ['Combine past tense, companion, location, sequence.'],
    task: 'Roleplay sharing your weekend with the AI tutor.' },
];

const lesson = {
  title: 'Level 1 · Unit 12: I went hiking with friends — Past Activities',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-what-did', label: 'Asking what someone did', goal: 'Use "What did you do?" for past activity.' },
    { id: 'describing-past-activity', label: 'Describing past activity', goal: 'Combine when + where + with whom + past verb.' },
    { id: 'chaining-actions', label: 'Chaining past actions', goal: 'Use "and then" or "after that".' },
  ],
  relatedPools: ['topic-people'],
  content: [
    createContentItem('Lesson goal', 'past tense', 'By end: conjugate past tense; describe when, where, with whom; form negation and question.', 'word', 'Functions: regular past · irregular past · neg · question.', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Monday morning', 'It\'s Monday morning. Your classmate asks "How was your weekend?" — respond with 2–3 past sentences.', 'word', 'Classmate: "How was your weekend?" — You: "Great! I went hiking with friends."', 'A typical small-talk opener.', null, [ACT.orientation]),

    createContentItem('-ed after voiceless → /t/', '/t/', 'After voiceless consonants (p, k, f, s, ʃ, tʃ), -ed sounds /t/.', 'word', 'worked /wɜːrkt/, walked /wɔːkt/, watched /wɒtʃt/', 'No buzz at the end; sounds like /t/.', null, [ACT.pronunciation]),
    createContentItem('-ed after voiced → /d/', '/d/', 'After voiced consonants and vowels, -ed sounds /d/.', 'word', 'played /pleɪd/, lived /lɪvd/, called /kɔːld/, opened /ˈoʊpənd/', 'Throat vibrates at the end.', null, [ACT.pronunciation]),
    createContentItem('-ed after t / d → /ɪd/', '/ɪd/', 'After verbs ending in /t/ or /d/, -ed is a FULL syllable /ɪd/.', 'word', 'wanted /ˈwɒntɪd/, needed /ˈniːdɪd/, started /ˈstɑːrtɪd/', 'A whole extra syllable — common error to merge.', null, [ACT.pronunciation]),
    createContentItem('Irregular pasts — varied vowel', 'memorize', 'Many irregular pasts change the vowel: get → got, write → wrote, sing → sang.', 'word', 'go → went, eat → ate, see → saw, take → took, give → gave', 'No predictable pattern — memorize the most common.', null, [ACT.pronunciation]),

    createContentItem('go (went)', '/ɡoʊ/ → /wɛnt/', 'irregular: to move; past = went', 'word', 'I went to the cafe.', '', null, [ACT.vocabularyActivities]),
    createContentItem('eat (ate)', '/iːt/ → /eɪt/', 'irregular: to consume food; past = ate', 'word', 'We ate pizza last night.', '', null, [ACT.vocabularyActivities]),
    createContentItem('see (saw)', '/siː/ → /sɔː/', 'irregular: to perceive with eyes; past = saw', 'word', 'I saw a movie.', '', null, [ACT.vocabularyActivities]),
    createContentItem('have (had)', '/hæv/ → /hæd/', 'irregular: to possess; past = had', 'word', 'I had a great time.', 'Also for meals: "I had breakfast".', null, [ACT.vocabularyActivities]),
    createContentItem('do (did)', '/duː/ → /dɪd/', 'irregular: general action; past = did', 'word', 'I did my homework.', 'Also auxiliary verb.', null, [ACT.vocabularyActivities]),
    createContentItem('come (came)', '/kʌm/ → /keɪm/', 'irregular: to move toward; past = came', 'word', 'My friend came to my place.', '', null, [ACT.vocabularyActivities]),
    createContentItem('meet (met)', '/miːt/ → /mɛt/', 'irregular: to come together; past = met', 'word', 'I met my friend.', '', null, [ACT.vocabularyActivities]),
    createContentItem('take (took)', '/teɪk/ → /tʊk/', 'irregular: to grab/use; past = took', 'word', 'I took a picture.', '', null, [ACT.vocabularyActivities]),
    createContentItem('study (studied)', '/ˈstʌdi/ → /ˈstʌdid/', 'regular: y → ied', 'word', 'I studied English.', '', null, [ACT.vocabularyActivities]),
    createContentItem('work (worked)', '/wɜːrk/ → /wɜːrkt/', 'regular: + ed (sounds /t/)', 'word', 'She worked yesterday.', '', null, [ACT.vocabularyActivities]),
    createContentItem('play (played)', '/pleɪ/ → /pleɪd/', 'regular: + ed (sounds /d/)', 'word', 'We played soccer.', '', null, [ACT.vocabularyActivities]),
    createContentItem('cook (cooked)', '/kʊk/ → /kʊkt/', 'regular: + ed (sounds /t/)', 'word', 'I cooked dinner.', '', null, [ACT.vocabularyActivities]),
    createContentItem('watch (watched)', '/wɒtʃ/ → /wɒtʃt/', 'regular: + ed (sounds /t/)', 'word', 'We watched a movie.', '', null, [ACT.vocabularyActivities]),
    createContentItem('visit (visited)', '/ˈvɪzɪt/ → /ˈvɪzɪtɪd/', 'regular: + ed (full syllable /ɪd/)', 'word', 'I visited my grandma.', '', null, [ACT.vocabularyActivities]),
    createContentItem('hike (hiked)', '/haɪk/ → /haɪkt/', 'regular: drop e, + ed', 'word', 'We hiked in the mountains.', '', null, [ACT.vocabularyActivities]),
    createContentItem('travel (traveled)', '/ˈtrævəl/ → /ˈtrævəld/', 'regular: + ed', 'word', 'I traveled to Busan.', 'US: "traveled" (one l); UK: "travelled" (two l).', null, [ACT.vocabularyActivities]),
    createContentItem('relax (relaxed)', '/rɪˈlæks/ → /rɪˈlækst/', 'regular: + ed', 'word', 'I relaxed at home.', '', null, [ACT.vocabularyActivities]),
    createContentItem('sleep (slept)', '/sliːp/ → /slɛpt/', 'irregular: vowel change', 'word', 'I slept early last night.', '', null, [ACT.vocabularyActivities]),

    createContentItem('yesterday', '/ˈjɛstərdeɪ/', 'the day before today', 'word', 'I went out yesterday.', 'Always with past tense.', null, [ACT.vocabularyTime]),
    createContentItem('the day before yesterday', '/ðə deɪ bɪˈfɔːr ˈjɛstərdeɪ/', 'two days ago', 'word', 'I saw her the day before yesterday.', 'Long phrase but standard.', null, [ACT.vocabularyTime]),
    createContentItem('last week / month / year', '/læst …/', 'the previous week/month/year', 'word', 'I traveled last week.', 'No article: "last week" (not "the last week").', null, [ACT.vocabularyTime]),
    createContentItem('last night', '/læst naɪt/', 'the previous night', 'word', 'I slept early last night.', '', null, [ACT.vocabularyTime]),
    createContentItem('ago', '/əˈɡoʊ/', '"X time before now"', 'word', 'I came here 2 years ago.', 'Always follows the time amount.', null, [ACT.vocabularyTime]),
    createContentItem('this morning / afternoon', '/ðɪs …/', 'earlier today', 'word', 'I had coffee this morning.', 'Past tense if the time has passed.', null, [ACT.vocabularyTime]),
    createContentItem('recently', '/ˈriːsəntli/', 'in the recent past', 'word', 'I recently moved to Korea.', '', null, [ACT.vocabularyTime]),
    createContentItem('just', '/dʒʌst/', 'a moment ago', 'word', 'I just had lunch.', 'Often with present perfect, but in casual speech with simple past.', null, [ACT.vocabularyTime]),

    createContentItem(
      'Regular past — add -ed',
      'verb + ed',
      'Most English verbs form the past by adding -ed.',
      'sentence',
      'I worked yesterday. — She played soccer. — They visited the museum.',
      'Three spelling rules: drop final e (live → lived); double consonant CVC (stop → stopped); y → ied after consonant (study → studied).',
      [
        { target: 'work → worked', english: 'just add -ed' },
        { target: 'live → lived', english: 'drop final e + ed' },
        { target: 'stop → stopped', english: 'double the final consonant + ed' },
        { target: 'study → studied', english: 'y → ied after consonant' },
        { target: 'play → played', english: 'y stays after vowel + ed' },
      ],
      [ACT.grammarRegular],
    ),

    createContentItem(
      'Irregular past — memorize',
      'no rule, just patterns',
      'About 150 common verbs are irregular. The top 20 must be memorized.',
      'sentence',
      'I went to school. — She ate dinner. — We saw a movie. — He had a great time.',
      'Most irregulars change the vowel — common patterns within groups.',
      [
        { target: 'be → was/were', english: 'I was / we were' },
        { target: 'go → went', english: 'most common irregular' },
        { target: 'eat → ate', english: 'food verb' },
        { target: 'see → saw', english: 'sense verb' },
        { target: 'do → did', english: 'general action' },
        { target: 'have → had', english: 'possession' },
        { target: 'take → took', english: 'action verb' },
        { target: 'give → gave', english: 'action verb' },
        { target: 'come → came', english: 'movement verb' },
        { target: 'get → got', english: 'general use' },
      ],
      [ACT.grammarIrregular],
    ),
    createContentItem(
      'be — was / were',
      'past forms of "to be"',
      'The only verb with TWO past forms. "Was" with I/he/she/it; "Were" with you/we/they.',
      'sentence',
      'I was tired. — She was happy. — We were busy. — They were late.',
      'Most common irregular past form in English.',
      [
        { target: 'I/he/she/it WAS', english: 'singular' },
        { target: 'you/we/they WERE', english: 'plural and "you"' },
      ],
      [ACT.grammarIrregular],
    ),
    createContentItem(
      'More common irregulars',
      'memorize these too',
      'Continued from the basic 10.',
      'sentence',
      'I bought / brought / caught / read / made / met / wrote / said / spoke / told / felt / lost / found / sat / stood / drove / flew',
      'Each one is a top-200 verb — memorize.',
      [
        { target: 'buy → bought', english: 'commerce verb' },
        { target: 'bring → brought', english: 'movement verb' },
        { target: 'read → read', english: 'same spelling, vowel changes /riːd/ → /rɛd/' },
        { target: 'make → made', english: 'action verb' },
        { target: 'meet → met', english: 'movement verb' },
        { target: 'write → wrote', english: 'action verb' },
        { target: 'say → said', english: '/seɪ/ → /sɛd/ — pronunciation surprise' },
        { target: 'tell → told', english: 'communication verb' },
        { target: 'feel → felt', english: 'emotion verb' },
      ],
      [ACT.grammarIrregular],
    ),

    createContentItem(
      'Past negation — didn\'t + bare verb',
      'subject + did not + bare verb',
      'Negate the past with "did not" + bare verb. Contractions: didn\'t. The main verb returns to bare form.',
      'sentence',
      'I didn\'t go to school. — She didn\'t eat lunch. — We didn\'t see a movie.',
      'Common error: "didn\'t went" — wrong. Use bare form: "didn\'t go".',
      [
        { target: 'didn\'t + bare verb', english: 'always bare form after didn\'t' },
        { target: '✗ didn\'t went', english: 'common error — don\'t do this' },
      ],
      [ACT.grammarNegationQuestion],
    ),
    createContentItem(
      'Past question — Did + subject + bare verb?',
      'inversion',
      'Form past questions with "Did + subject + bare verb?".',
      'sentence',
      'Did you go? — Yes, I did. / No, I didn\'t.\nDid she eat? — Yes, she did.',
      'Short answers: subject + did or didn\'t.',
      [
        { target: 'Did + subject + bare verb?', english: 'question pattern' },
        { target: 'Yes, [subject] did. / No, [subject] didn\'t.', english: 'short answer' },
      ],
      [ACT.grammarNegationQuestion],
    ),
    createContentItem(
      'Wh- questions in past',
      'question word + did + subject + verb',
      'For wh-questions: question word first, then did + subject + bare verb.',
      'sentence',
      'Where did you go? — I went to the cafe.\nWhat did she eat? — She ate pizza.\nWhen did they arrive? — They arrived at 8.',
      'Same structure with any question word.',
      null,
      [ACT.grammarNegationQuestion],
    ),

    createContentItem(
      'A weekend diary',
      'reading practice',
      'Read aloud and note the past-tense verbs.',
      'sentence',
      'Last weekend was great. On Saturday morning, I went hiking with my friends. We took lots of pictures on the mountain. At lunch, we ate kimbap at a restaurant. In the afternoon, I went home and rested. On Sunday, I visited my family. We had dinner together and watched a movie. It was a perfect weekend.',
      'Mix of regular and irregular past forms.',
      [
        { target: 'went / took / ate / had / watched', english: 'mostly irregular past' },
        { target: 'rested / visited', english: 'regular past' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use past tense.',
      'sentence',
      'Q1: Where did she go on Saturday? · Q2: Who did she visit on Sunday? · Q3: What did they do together?',
      'Use full past-tense answers.',
      [
        { target: 'A1: She went hiking.', english: 'past' },
        { target: 'A2: She visited her family.', english: 'past' },
        { target: 'A3: They had dinner and watched a movie.', english: 'past' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Monday morning recap',
      'listening',
      'Classmates chat Monday morning.',
      'conversation',
      'A: Hey, how was your weekend?\nB: It was great! I went hiking with my friends. How about you?\nA: I had a quiet weekend. I just stayed home and read a book.\nB: Sounds relaxing! Did you watch any movies?\nA: Yeah, I watched a new Korean drama. It was really good.\nB: Cool. What was it called?\nA: "My Name". I recommend it.',
      'Note the rhythm: question → answer → return the question.',
      [
        { target: 'How was your weekend?', english: 'standard Monday opener' },
        { target: 'How about you?', english: 'return the question' },
        { target: 'Sounds + adj', english: 'reaction phrase' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Trip recap',
      'listening',
      'Recapping a recent trip.',
      'conversation',
      'A: I traveled to Jeju last month.\nB: Oh nice! Where did you stay?\nA: I stayed at a hotel near the beach.\nB: How was it?\nA: It was beautiful. We went hiking and ate amazing seafood.\nB: I want to go too. How long did you stay?\nA: Three nights, four days.',
      'Past tense + sensory adjectives + length of stay.',
      [
        { target: 'Where did you stay?', english: 'past wh-question' },
        { target: 'How was it?', english: 'opinion question' },
        { target: 'three nights, four days', english: 'standard trip-length phrasing' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'weekend diary template',
      'Use this structure.',
      'sentence',
      'Last weekend was [adjective]. On [day], I [verb-ed] with [companion]. We [verb-ed] [place]. Then I [verb-ed]. On [day], I [verb-ed]. It was a [adjective] weekend.',
      '[opinion] · [day] · [activity] · [companion] · [place] · [next activity] · [verdict].',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 4–5 past-tense sentences about your last weekend. Use at least 3 past verbs (mix of regular and irregular).',
      'sentence',
      'Example: Last weekend was fun. On Saturday, I went to the cafe with a friend. We studied English for two hours. Then we watched a movie. On Sunday, I rested at home. It was a perfect weekend.',
      'Check: past verbs + time markers + companion.',
      null, [ACT.writing],
    ),

    createContentItem(
      '"How was your weekend?"',
      'Monday opener',
      'The universal Monday morning opener in English-speaking workplaces. Keep the answer brief and positive.',
      'sentence',
      'How was your weekend? — It was great! I just relaxed.',
      'Even if it was bad, default reply is "It was OK / fine" — full complaints reserved for close friends.',
      [
        { target: 'It was great / nice / good', english: 'standard positive' },
        { target: 'It was OK / quiet', english: 'neutral' },
        { target: 'It was busy / hectic', english: 'softened negative' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Keep weekend recaps short',
      'small talk rule',
      'A 1–2 sentence answer is the polite norm. Long detailed stories are reserved for close friends.',
      'sentence',
      '✓ "It was fun. We went hiking."\n✗ "Well, on Saturday I woke up at 7, then I drove to the mountain, then …"',
      'Save details for explicit invitation: "Tell me more!".',
      null, [ACT.culture],
    ),

    createContentItem(
      'Task: Tell me about your weekend',
      'consolidation task',
      'Roleplay: A classmate asks "How was your weekend?" — Cover at least 2 activities, one location, one companion.',
      'conversation',
      'Classmate: How was your weekend?\nYou: [adjective + 2 activities with past tense]\nClassmate: Oh nice! Where did you go?\nYou: [location + companion]\nClassmate: Did you have fun?\nYou: [yes/no + reason]\nClassmate: Sounds great!',
      'AI tutor will play the classmate.',
      [
        { target: 'It was [adj]', english: 'opinion summary' },
        { target: 'I [verb-ed] with [companion]', english: 'past + companion' },
        { target: 'I [verb-ed] [past time marker]', english: 'past + time' },
        { target: 'Did you …?', english: 'past question' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
