// Level 1 Unit 4 — Daily Routines (English)
// Functions: describing daily activities, simple present tense, time-of-day,
// adverbs of frequency.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u4-orientation',
  pronunciation: 'en-l1u4-pronunciation',
  vocabularyVerbs: 'en-l1u4-vocab-verbs',
  vocabularyTime: 'en-l1u4-vocab-time',
  grammarPresent: 'en-l1u4-grammar-present',
  grammarFrequency: 'en-l1u4-grammar-frequency',
  grammarNegation: 'en-l1u4-grammar-negation',
  reading: 'en-l1u4-reading',
  listening: 'en-l1u4-listening',
  writing: 'en-l1u4-writing',
  culture: 'en-l1u4-culture',
  task: 'en-l1u4-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Conjugate 18+ verbs in the simple present.', 'Use the third-person -s ending correctly.', 'Use frequency adverbs (always, usually, sometimes, never) to describe routines.'],
    task: 'Imagine telling an English-speaking friend what a typical day looks like for you.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Third-person -s endings',
    goals: ['Three pronunciations of -s: /s/ after voiceless (works /wɜːrks/), /z/ after voiced (goes /ɡoʊz/), /ɪz/ after sibilants (washes /ˈwɒʃɪz/).'],
    task: 'Read each verb form aloud.' },
  { id: ACT.vocabularyVerbs, section: 'Vocabulary I', title: 'Daily action verbs',
    goals: ['Learn 18+ daily verbs (dictionary form + 3rd-person form).'],
    task: 'List your top five daily actions.' },
  { id: ACT.vocabularyTime, section: 'Vocabulary II', title: 'Time-of-day & frequency words',
    goals: ['Use morning/afternoon/evening/night and frequency adverbs.'],
    task: 'Pair a frequency word with one habit.' },
  { id: ACT.grammarPresent, section: 'Grammar I', title: 'Simple present tense',
    goals: ['Conjugate verbs: I/you/we/they go; he/she/it goes.', 'Use bare form with most subjects; add -s/-es/-ies in third-person singular.'],
    task: 'Conjugate five verbs.' },
  { id: ACT.grammarFrequency, section: 'Grammar II', title: 'Adverbs of frequency',
    goals: ['Use always (100%), usually (90%), often (70%), sometimes (50%), rarely (10%), never (0%).', 'Place before main verb but AFTER "to be".'],
    task: 'Describe three habits with frequency adverbs.' },
  { id: ACT.grammarNegation, section: 'Grammar III', title: 'Negation: do not / does not',
    goals: ['Form negative: subject + do/does + not + bare verb.', 'Use contractions don\'t / doesn\'t.'],
    task: 'Negate three of your habits.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A typical Tuesday',
    goals: ['Read a daily-schedule paragraph and answer comprehension questions.'],
    task: 'Reply in English.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Weekend routines',
    goals: ['Follow a weekend-plans dialogue.', 'Reproduce with your own activities.'],
    task: 'Describe your own weekend routine.' },
  { id: ACT.writing, section: 'Writing', title: 'Write your daily schedule',
    goals: ['Write 5–6 sentences describing a typical day.'],
    task: 'Write your own daily schedule.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Work-life rhythm in English-speaking countries',
    goals: ['Know typical 9-5 office hours, after-work culture, weekend norms.'],
    task: 'Compare one part of your daily rhythm to the typical Western pattern.' },
  { id: ACT.task, section: 'Task', title: 'Compare your week with a Western friend',
    goals: ['Combine simple present, frequency adverbs, and negation in one continuous scene.'],
    task: 'Roleplay comparing weekday vs weekend routines.' },
];

const lesson = {
  title: 'Level 1 · Unit 4: I usually wake up at seven — Daily Routines',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describing-daily-activities', label: 'Describing daily activities', goal: 'Use simple present at different times of day.' },
    { id: 'asking-what-do-daily', label: 'Asking what someone does', goal: 'Use "What do you do?" / "What does she do?"' },
    { id: 'negating-action', label: 'Saying what you do NOT do', goal: 'Use do not / does not + bare verb.' },
  ],
  relatedPools: ['topic-people', 'topic-school'],
  content: [
    createContentItem('Lesson goal', 'routine speech', 'By end: describe your daily/weekly routine using simple present, frequency adverbs, and negation.', 'word', 'Functions: conjugate · frequency · negate.', 'Three skills that unlock habit talk.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'small talk', 'A classmate asks "What do you usually do on weekends?" — you should be able to answer in 2–3 sentences.', 'word', 'Classmate: "What do you do in the mornings?" — You: "I usually wake up at 7 and go to class at 9."', 'A typical small-talk exchange.', null, [ACT.orientation]),

    createContentItem('-s after voiceless → /s/', '/s/', 'After voiceless consonants (p, t, k, f, θ), the -s ending sounds /s/.', 'word', 'works /wɜːrks/, gets /ɡɛts/, hopes /hoʊps/, drinks /drɪŋks/', 'Hold throat — no buzz at the end.', null, [ACT.pronunciation]),
    createContentItem('-s after voiced → /z/', '/z/', 'After voiced consonants and vowels, the -s ending sounds /z/.', 'word', 'goes /ɡoʊz/, plays /pleɪz/, lives /lɪvz/, sees /siːz/', 'Hold throat — feel the buzz at the end.', null, [ACT.pronunciation]),
    createContentItem('-es after sibilant → /ɪz/', '/ɪz/', 'After sibilants (s, z, sh, ch, ge), -es is a full syllable /ɪz/.', 'word', 'washes /ˈwɒʃɪz/, watches /ˈwɒtʃɪz/, fixes /ˈfɪksɪz/', 'A whole extra syllable — not silent.', null, [ACT.pronunciation]),
    createContentItem('do/does — weak forms', '/də/ /dəz/', 'In questions, "do" and "does" weaken to /də/ and /dəz/.', 'word', 'Do you work? /də juː wɜːrk/ — Does she work? /dəz ʃiː wɜːrk/', 'In writing, full form; in speech, weak form.', null, [ACT.pronunciation]),

    createContentItem('wake up', '/weɪk ʌp/', 'to stop sleeping', 'word', 'I wake up at 7.', 'Phrasal verb; "up" is part of the meaning.', null, [ACT.vocabularyVerbs]),
    createContentItem('get up', '/ɡɛt ʌp/', 'to get out of bed', 'word', 'I get up at 7:15.', 'Distinct from "wake up" — "get up" implies leaving the bed.', null, [ACT.vocabularyVerbs]),
    createContentItem('sleep', '/sliːp/', 'to rest with eyes closed', 'word', 'I usually sleep at 11.', 'Irregular past: slept.', null, [ACT.vocabularyVerbs]),
    createContentItem('eat', '/iːt/', 'to take food into the mouth', 'word', 'I eat breakfast at home.', 'Irregular past: ate.', null, [ACT.vocabularyVerbs]),
    createContentItem('drink', '/drɪŋk/', 'to swallow liquid', 'word', 'I drink coffee in the morning.', 'Irregular past: drank.', null, [ACT.vocabularyVerbs]),
    createContentItem('go', '/ɡoʊ/', 'to move toward a place', 'word', 'I go to school by bus.', 'Third-person: "goes"; irregular past "went".', null, [ACT.vocabularyVerbs]),
    createContentItem('come', '/kʌm/', 'to move toward the speaker', 'word', 'She comes home at 6.', 'Irregular past: came.', null, [ACT.vocabularyVerbs]),
    createContentItem('study', '/ˈstʌdi/', 'to learn something carefully', 'word', 'I study English every day.', 'Third-person: "studies" — y → ies.', null, [ACT.vocabularyVerbs]),
    createContentItem('work', '/wɜːrk/', 'to do a job', 'word', 'My mother works at a hospital.', 'Both noun and verb.', null, [ACT.vocabularyVerbs]),
    createContentItem('rest', '/rɛst/', 'to stop activity and relax', 'word', 'I rest on weekends.', 'Both noun and verb.', null, [ACT.vocabularyVerbs]),
    createContentItem('exercise', '/ˈɛksərsaɪz/', 'to do physical activity for fitness', 'word', 'I exercise in the morning.', 'Both noun and verb.', null, [ACT.vocabularyVerbs]),
    createContentItem('watch', '/wɒtʃ/', 'to look at something for a period of time', 'word', 'I watch TV in the evening.', 'Third-person: "watches" — adds -es.', null, [ACT.vocabularyVerbs]),
    createContentItem('listen', '/ˈlɪsən/', 'to pay attention with the ears', 'word', 'I listen to music.', 'Always with "to": "listen to music".', null, [ACT.vocabularyVerbs]),
    createContentItem('meet', '/miːt/', 'to come together with someone', 'word', 'I meet my friend at the cafe.', 'Irregular past: met.', null, [ACT.vocabularyVerbs]),
    createContentItem('read', '/riːd/', 'to look at and understand written words', 'word', 'I read a book before bed.', 'Past tense spelled the same but pronounced /rɛd/.', null, [ACT.vocabularyVerbs]),
    createContentItem('write', '/raɪt/', 'to make letters or words on paper', 'word', 'I write in a journal.', 'Silent "w"; irregular past "wrote".', null, [ACT.vocabularyVerbs]),
    createContentItem('shower', '/ˈʃaʊər/', 'to wash with falling water', 'word', 'I shower in the evening.', 'Both noun and verb.', null, [ACT.vocabularyVerbs]),
    createContentItem('cook', '/kʊk/', 'to prepare food with heat', 'word', 'I cook dinner at home.', 'Also a noun ("a cook").', null, [ACT.vocabularyVerbs]),
    createContentItem('have', '/hæv/', 'to possess; also for meals: "have breakfast"', 'word', 'I have breakfast at 7.', 'Third-person: "has".', null, [ACT.vocabularyVerbs]),
    createContentItem('take a shower', '/teɪk ə ˈʃaʊər/', 'idiom: shower oneself', 'word', 'I take a shower every morning.', '"Take" is the helper verb for many daily routines.', null, [ACT.vocabularyVerbs]),

    createContentItem('morning', '/ˈmɔːrnɪŋ/', 'the time from sunrise to noon', 'word', 'I work in the morning.', 'Use "in the morning" (no article when specific day: "this morning").', null, [ACT.vocabularyTime]),
    createContentItem('afternoon', '/ˌɑːftərˈnuːn/', 'the time from noon to evening', 'word', 'I study in the afternoon.', 'Use "in the afternoon".', null, [ACT.vocabularyTime]),
    createContentItem('evening', '/ˈiːvnɪŋ/', 'the time from sunset to bedtime', 'word', 'I cook in the evening.', 'Use "in the evening".', null, [ACT.vocabularyTime]),
    createContentItem('night', '/naɪt/', 'the dark hours, after evening', 'word', 'I sleep at night.', 'Use "AT night" — unique preposition for this time.', null, [ACT.vocabularyTime]),
    createContentItem('weekday', '/ˈwiːkdeɪ/', 'Monday to Friday', 'word', 'I work on weekdays.', '"On weekdays" for habit; "on Monday" for one day.', null, [ACT.vocabularyTime]),
    createContentItem('weekend', '/ˈwiːkɛnd/', 'Saturday and Sunday', 'word', 'I rest on weekends.', 'Same pattern: "on weekends".', null, [ACT.vocabularyTime]),
    createContentItem('always', '/ˈɔːlweɪz/', '100% of the time', 'word', 'I always wake up at 7.', 'Place before the main verb.', null, [ACT.vocabularyTime]),
    createContentItem('usually', '/ˈjuːʒuəli/', 'most of the time', 'word', 'I usually have breakfast at home.', 'Same position as always.', null, [ACT.vocabularyTime]),
    createContentItem('often', '/ˈɒfən/', 'many times', 'word', 'I often go to the cafe.', 'The "t" is silent for most speakers.', null, [ACT.vocabularyTime]),
    createContentItem('sometimes', '/ˈsʌmtaɪmz/', 'occasionally', 'word', 'Sometimes I watch a movie.', 'Can also go at the start of the sentence.', null, [ACT.vocabularyTime]),
    createContentItem('rarely', '/ˈrɛərli/', 'almost never', 'word', 'I rarely eat fast food.', 'Synonym: "seldom" (more formal).', null, [ACT.vocabularyTime]),
    createContentItem('never', '/ˈnɛvər/', '0% of the time', 'word', 'I never drink coffee at night.', 'Already negative — do NOT add "not".', null, [ACT.vocabularyTime]),

    createContentItem(
      'Simple present — most subjects',
      'I/you/we/they + bare verb',
      'Most subjects use the bare verb form: no ending.',
      'sentence',
      'I work in an office. You study English. We live in Korea. They speak French.',
      'Same form as the dictionary entry.',
      null,
      [ACT.grammarPresent],
    ),
    createContentItem(
      'Third-person singular — add -s',
      'he/she/it + verb-s',
      'For he/she/it, add -s to the verb. Add -es after sibilants (s/z/sh/ch/x). Change y → ies after consonant.',
      'sentence',
      'He works in an office. She watches TV. The teacher studies grammar.',
      'Three spelling rules: -s default, -es after sibilants, -ies after consonant-y.',
      [
        { target: 'work → works', note: 'add -s' },
        { target: 'watch → watches', note: 'sibilant ending; add -es' },
        { target: 'study → studies', note: 'consonant-y; change to -ies' },
        { target: 'go → goes', note: 'irregular but follows -es pattern' },
        { target: 'have → has', note: 'irregular form' },
      ],
      [ACT.grammarPresent],
    ),
    createContentItem(
      'Yes/no question — Do / Does',
      'do/does + subject + bare verb',
      'Form questions with "Do" (most subjects) or "Does" (he/she/it) + subject + bare verb.',
      'sentence',
      'Do you work on weekends? — Yes, I do. / No, I don\'t.\nDoes she like coffee? — Yes, she does. / No, she doesn\'t.',
      'Short answers: subject + do/does or subject + don\'t/doesn\'t.',
      [
        { target: 'Do you …?', note: 'most subjects' },
        { target: 'Does he …?', note: 'third-person singular' },
        { target: 'Yes, I do. / No, I don\'t.', note: 'short answer pattern' },
      ],
      [ACT.grammarPresent],
    ),

    createContentItem(
      'Adverbs of frequency — placement',
      'before main verb',
      'Place frequency adverbs BEFORE the main verb but AFTER the verb "to be".',
      'sentence',
      'I always drink coffee. (before main verb)\nShe is usually late. (after "to be")',
      'The rule: before action verbs, after "to be" / modals.',
      [
        { target: 'I usually wake up at 7.', note: 'before "wake up"' },
        { target: 'She is always happy.', note: 'after "is"' },
        { target: 'I can sometimes help.', note: 'after modal "can"' },
      ],
      [ACT.grammarFrequency],
    ),
    createContentItem(
      'The frequency scale',
      '100% → 0%',
      'A rough scale: always > usually > often > sometimes > rarely > never.',
      'sentence',
      'always (100%) · usually (90%) · often (70%) · sometimes (50%) · rarely (10%) · never (0%)',
      'These are approximate, but useful for understanding nuance.',
      [
        { target: 'always', note: '100% — every time' },
        { target: 'usually / normally', note: '90% — most of the time' },
        { target: 'often / frequently', note: '70% — many times' },
        { target: 'sometimes', note: '50% — occasionally' },
        { target: 'rarely / seldom', note: '10% — almost never' },
        { target: 'never', note: '0% — not at all' },
      ],
      [ACT.grammarFrequency],
    ),

    createContentItem(
      'Negation — don\'t / doesn\'t + bare verb',
      'simple present negative',
      'Form the negative with do not / does not + bare verb. Contractions are standard in speech.',
      'sentence',
      'I do not work on Saturdays. → I don\'t work on Saturdays.\nShe does not eat breakfast. → She doesn\'t eat breakfast.',
      'The main verb stays in its base form — never adds -s after doesn\'t.',
      [
        { target: 'I/you/we/they don\'t + bare verb', note: 'most subjects' },
        { target: 'he/she/it doesn\'t + bare verb', note: 'third-person singular' },
        { target: 'NOT "doesn\'t works"', note: 'common error — keep verb in bare form' },
      ],
      [ACT.grammarNegation],
    ),
    createContentItem(
      '"never" is already negative',
      'no double negative',
      'Use "never" with a POSITIVE verb. Do NOT combine with "don\'t".',
      'sentence',
      '✓ I never eat fast food.\n✗ I don\'t never eat fast food. (double negative — wrong in standard English)',
      'Likewise: "rarely" + positive verb, never "don\'t rarely".',
      null,
      [ACT.grammarNegation],
    ),

    createContentItem(
      'A typical Tuesday',
      'reading practice',
      'Read aloud, then answer the questions.',
      'sentence',
      'I usually wake up at 7. I have breakfast at 8. I go to school at 9. I study English at school. At 12, I have lunch with a friend. In the afternoon, I read books at the library. In the evening, I cook at home. I usually go to bed at 11.',
      'Note the consistent simple-present forms.',
      [
        { target: 'I usually wake up at 7', note: 'frequency adverb before verb' },
        { target: 'I go to school by bus', note: 'subject + verb + place' },
        { target: 'I have lunch with a friend', note: '"have" + meal noun' },
        { target: 'I usually go to bed at 11', note: 'frequency at end of habit clause' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use simple present in your answers.',
      'sentence',
      'Q1: When do you wake up? · Q2: Where do you study? · Q3: What do you do in the evening?',
      'Use full short answers.',
      [
        { target: 'A1: I wake up at 7.', note: 'time answer' },
        { target: 'A2: I study at school.', note: 'place answer' },
        { target: 'A3: I cook at home.', note: 'action answer' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Weekend plans',
      'dialogue',
      'Two classmates talk about their weekends.',
      'conversation',
      'A: What do you usually do on weekends?\nB: I usually rest at home. I also read books. How about you?\nA: I usually meet my friends. Sometimes we watch a movie.\nB: Do you exercise on weekends?\nA: Sometimes. On Saturday mornings, I run in the park.\nB: Cool! I rarely exercise — I should start.',
      'Use frequency adverbs to talk about habits.',
      [
        { target: 'What do you usually do?', note: 'standard question for habits' },
        { target: 'How about you?', note: 'natural way to return the question' },
        { target: 'rarely / sometimes', note: 'frequency adverbs in answer' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'What are you doing today?',
      'short check-in',
      'A short same-day check-in.',
      'conversation',
      'A: What do you do in the mornings?\nB: I go to school at 9. I have a class. How about you?\nA: I work at a cafe in the mornings. In the afternoon, I study.\nB: Sounds busy!\nA: Yeah, but I love it.',
      '"In the mornings / afternoons" with plural for habit; "this morning" for one day.',
      null,
      [ACT.listening],
    ),

    createContentItem(
      'Model daily-routine paragraph',
      'writing template',
      'Use this structure for your own writing.',
      'sentence',
      'I usually wake up at [time]. I [verb] at [time]. I go to [place] in the [morning/afternoon]. At lunch, I [verb]. In the evening, I [verb]. I usually go to bed at [time].',
      '[wake] → [breakfast] → [school/work] → [lunch] → [evening] → [sleep].',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write your own 5–6 sentence daily schedule. Use at least one frequency adverb and one negation.',
      'sentence',
      'Example: I usually wake up at 6. I don\'t eat breakfast. I go to school at 9. I study English at school. I usually come home at 5. I cook in the evening.',
      'Check: time + verb + place + frequency.',
      null,
      [ACT.writing],
    ),

    createContentItem(
      'Western work-life rhythm',
      'culture',
      'In most English-speaking countries, the typical workweek is 9 AM–5 PM Monday to Friday. Saturday and Sunday are usually free. Many people separate work and personal life strictly — emails after 6 PM may not be answered.',
      'sentence',
      'I work 9 to 5 from Monday to Friday. — On weekends, I rest with my family.',
      'The phrase "work-life balance" is highly valued in Western culture.',
      [
        { target: '9-to-5', note: 'standard office hours; idiom for "normal job"' },
        { target: 'work-life balance', note: 'core Western workplace value' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Coffee culture',
      'mornings & meetings',
      'Coffee is the default morning drink in most English-speaking countries. Many people "grab a coffee" before work and meet others "for coffee" — a casual meeting.',
      'sentence',
      'I grab a coffee on my way to work. — Let\'s meet for coffee.',
      '"Tea time" is more British — afternoon tea around 3-4 PM.',
      null,
      [ACT.culture],
    ),

    createContentItem(
      'Task: Compare your week',
      'consolidation task',
      'Roleplay: an English-speaking friend asks about your week. Compare weekday vs weekend. Use vocabulary, conjugation, and at least one frequency adverb.',
      'conversation',
      'Friend: What do you usually do on weekdays?\nYou: [3 sentences about weekday]\nFriend: How about weekends?\nYou: [2 sentences + one negation]\nFriend: Do you exercise?\nYou: [answer with frequency word]',
      'AI tutor will play the friend.',
      [
        { target: 'I usually [verb] at [time]', english: 'habit sentence' },
        { target: 'On weekends, I [verb]', english: 'weekend habit' },
        { target: 'I don\'t / I never / sometimes', english: 'frequency variations' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
