// Level 1 Unit 6 — Dates & Calendar (English)
// Functions: days of the week, months, dates, asking "When?", talking about birthdays.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u6-orientation',
  pronunciation: 'en-l1u6-pronunciation',
  vocabularyDays: 'en-l1u6-vocab-days',
  vocabularyMonths: 'en-l1u6-vocab-months',
  grammarOrdinals: 'en-l1u6-grammar-ordinals',
  grammarDates: 'en-l1u6-grammar-dates',
  grammarWhen: 'en-l1u6-grammar-when',
  reading: 'en-l1u6-reading',
  listening: 'en-l1u6-listening',
  writing: 'en-l1u6-writing',
  culture: 'en-l1u6-culture',
  task: 'en-l1u6-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Name the 7 days of the week and 12 months.', 'Read and say any date.', 'Ask "When is …?" and respond.'],
    task: 'Imagine planning a birthday party — you need to confirm the date, the day, and when to meet.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Sound traps',
    goals: ['Pronounce ordinals: first /fɜːrst/, third /θɜːrd/ (note /θ/).', 'Distinguish "Tuesday" /ˈtuːzdeɪ/ vs "Thursday" /ˈθɜːrzdeɪ/.'],
    task: 'Read each day-name aloud.' },
  { id: ACT.vocabularyDays, section: 'Vocabulary I', title: 'Days of the week + relative time',
    goals: ['Use Monday–Sunday + today / yesterday / tomorrow.'],
    task: 'Say what day each was: yesterday, today, tomorrow.' },
  { id: ACT.vocabularyMonths, section: 'Vocabulary II', title: 'Months + calendar nouns',
    goals: ['Use January–December + day/week/month/year + birthday/holiday.'],
    task: 'Write the date of a holiday you know.' },
  { id: ACT.grammarOrdinals, section: 'Grammar I', title: 'Ordinal numbers — 1st, 2nd, 3rd …',
    goals: ['Say first/second/third/fourth … through thirty-first.', 'Know the spelling pattern (mostly -th).'],
    task: 'Say your floor number and birthday day.' },
  { id: ACT.grammarDates, section: 'Grammar II', title: 'Reading dates — two formats',
    goals: ['Read American format: "May 11, 2026".', 'Read British format: "the 11th of May, 2026".'],
    task: 'Write 3 dates: today, your birthday, an upcoming holiday.' },
  { id: ACT.grammarWhen, section: 'Grammar III', title: 'Questions: When? What day? On / In / At',
    goals: ['Ask "When is …?" / "What day is it?".', 'Use ON + day (on Monday), IN + month/year (in May, in 2026), AT + time (at 7).'],
    task: 'Practice the preposition rule with 6 examples.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A semester calendar',
    goals: ['Read a paragraph about a student\'s semester schedule.'],
    task: 'Answer which date each event is on.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Birthdays and plans',
    goals: ['Follow two short date-checking dialogues.'],
    task: 'Reproduce with your real birthday.' },
  { id: ACT.writing, section: 'Writing', title: 'Important dates',
    goals: ['Write 4–5 sentences listing important dates.'],
    task: 'Write your own list of important personal dates.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Birthdays and date formats around the English world',
    goals: ['Know that American format is MM/DD/YYYY; British and most others use DD/MM/YYYY.', 'Know birthday customs: cards, cake, "Happy Birthday" song.'],
    task: 'Compare a 12/05/2026 reading in US vs UK.' },
  { id: ACT.task, section: 'Task', title: 'Plan a birthday meet-up',
    goals: ['Combine days, dates, and "When?" questions in one task.'],
    task: 'Plan a birthday meet-up with the AI tutor.' },
];

const lesson = {
  title: 'Level 1 · Unit 6: My birthday is in June — Dates and Calendar',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-when-date', label: 'Asking when something happens', goal: 'Use "When is …?".' },
    { id: 'stating-birthday', label: 'Stating a birthday', goal: 'Use "My birthday is in/on …".' },
    { id: 'planning-event-date', label: 'Planning around a date', goal: 'Combine day + month + ordinal.' },
  ],
  relatedPools: [],
  content: [
    createContentItem('Lesson goal', 'dates', 'By end: say any date, name 7 weekdays + 12 months, ask & answer when events happen.', 'word', 'Functions: read date · pick day · ask when.', 'Three skills for scheduling.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'birthday plan', 'A friend asks "When\'s your birthday?" — you confirm the date and pick a day to meet.', 'word', 'Friend: "When\'s your birthday?" — You: "It\'s on June 11th."', 'A typical small-talk question.', null, [ACT.orientation]),

    createContentItem('first /fɜːrst/', '/fɜːrst/', 'r-colored vowel /ɜːr/, voiceless "st" ending.', 'word', 'the first of May', '"First" rhymes with "burst", "worst".', null, [ACT.pronunciation]),
    createContentItem('third /θɜːrd/', '/θɜːrd/', '/θ/ at the start: tongue between teeth.', 'word', 'the third of June', 'Distinct from "turd" (avoid that pronunciation!).', null, [ACT.pronunciation]),
    createContentItem('Tuesday /ˈtuːzdeɪ/', '/ˈtuːzdeɪ/', 'TWO syllables; starts with /tuː/.', 'word', 'See you on Tuesday.', 'British: /ˈtjuːzdeɪ/ with a /j/ glide.', null, [ACT.pronunciation]),
    createContentItem('Thursday /ˈθɜːrzdeɪ/', '/ˈθɜːrzdeɪ/', '/θ/ at the start: tongue between teeth.', 'word', 'See you on Thursday.', 'Distinct from "Tuesday" — different consonant.', null, [ACT.pronunciation]),
    createContentItem('February', '/ˈfɛbruɛri/', 'Often pronounced casually as /ˈfɛbjuɛri/ (with silent first "r").', 'word', 'February is the second month.', 'Both pronunciations are acceptable.', null, [ACT.pronunciation]),

    createContentItem('Monday', '/ˈmʌndeɪ/', 'first weekday in most calendars', 'word', 'I have class on Monday.', 'Use "on Monday" for habit; "this Monday" for one day.', null, [ACT.vocabularyDays]),
    createContentItem('Tuesday', '/ˈtuːzdeɪ/', 'second weekday', 'word', 'My birthday is on Tuesday.', '', null, [ACT.vocabularyDays]),
    createContentItem('Wednesday', '/ˈwɛnzdeɪ/', 'third weekday — silent "d"', 'word', 'I meet my friend on Wednesday.', 'Spelled WED-NES-DAY but said "WENZ-day".', null, [ACT.vocabularyDays]),
    createContentItem('Thursday', '/ˈθɜːrzdeɪ/', 'fourth weekday', 'word', 'I work on Thursday.', 'Starts with /θ/ — tongue between teeth.', null, [ACT.vocabularyDays]),
    createContentItem('Friday', '/ˈfraɪdeɪ/', 'fifth weekday — the last work day in many cultures', 'word', 'I love Fridays!', '"TGIF" — "Thank God It\'s Friday".', null, [ACT.vocabularyDays]),
    createContentItem('Saturday', '/ˈsætərdeɪ/', 'sixth day — start of weekend', 'word', 'I rest on Saturday.', '', null, [ACT.vocabularyDays]),
    createContentItem('Sunday', '/ˈsʌndeɪ/', 'seventh day', 'word', 'On Sunday, I see my family.', '', null, [ACT.vocabularyDays]),
    createContentItem('today', '/təˈdeɪ/', 'this day', 'word', 'Today is Monday.', 'Stress on the second syllable.', null, [ACT.vocabularyDays]),
    createContentItem('yesterday', '/ˈjɛstərdeɪ/', 'the day before today', 'word', 'Yesterday was Sunday.', 'Use past tense with "yesterday".', null, [ACT.vocabularyDays]),
    createContentItem('tomorrow', '/təˈmɒroʊ/', 'the day after today', 'word', 'Tomorrow is Tuesday.', 'Future contexts.', null, [ACT.vocabularyDays]),
    createContentItem('weekday', '/ˈwiːkdeɪ/', 'Monday–Friday', 'word', 'On weekdays, I go to school.', 'Compare with "weekend".', null, [ACT.vocabularyDays]),
    createContentItem('weekend', '/ˈwiːkɛnd/', 'Saturday + Sunday', 'word', 'I love weekends.', '', null, [ACT.vocabularyDays]),

    createContentItem('January', '/ˈdʒænjuɛri/', 'first month', 'word', 'It snows in January.', 'Abbreviation: Jan.', null, [ACT.vocabularyMonths]),
    createContentItem('February', '/ˈfɛbruɛri/', 'second month — often /ˈfɛbjuɛri/ casually', 'word', 'February has 28 or 29 days.', 'Abbreviation: Feb.', null, [ACT.vocabularyMonths]),
    createContentItem('March', '/mɑːrtʃ/', 'third month', 'word', 'Spring starts in March.', 'Abbreviation: Mar.', null, [ACT.vocabularyMonths]),
    createContentItem('April', '/ˈeɪprəl/', 'fourth month', 'word', 'It rains a lot in April.', 'Idiom: "April showers bring May flowers."', null, [ACT.vocabularyMonths]),
    createContentItem('May', '/meɪ/', 'fifth month', 'word', 'May is a beautiful month.', '', null, [ACT.vocabularyMonths]),
    createContentItem('June', '/dʒuːn/', 'sixth month', 'word', 'School ends in June.', '', null, [ACT.vocabularyMonths]),
    createContentItem('July', '/dʒuˈlaɪ/', 'seventh month — stress on the SECOND syllable', 'word', 'It\'s hot in July.', 'American Independence Day: July 4.', null, [ACT.vocabularyMonths]),
    createContentItem('August', '/ˈɔːɡəst/', 'eighth month', 'word', 'August is summer vacation.', 'Stress on the first syllable.', null, [ACT.vocabularyMonths]),
    createContentItem('September', '/sɛpˈtɛmbər/', 'ninth month', 'word', 'School starts in September.', '', null, [ACT.vocabularyMonths]),
    createContentItem('October', '/ɒkˈtoʊbər/', 'tenth month', 'word', 'Halloween is in October.', '', null, [ACT.vocabularyMonths]),
    createContentItem('November', '/noʊˈvɛmbər/', 'eleventh month', 'word', 'Thanksgiving is in November.', '', null, [ACT.vocabularyMonths]),
    createContentItem('December', '/dɪˈsɛmbər/', 'twelfth month', 'word', 'Christmas is in December.', '', null, [ACT.vocabularyMonths]),
    createContentItem('day', '/deɪ/', '24-hour period', 'word', 'Today is a good day.', 'Countable noun.', null, [ACT.vocabularyMonths]),
    createContentItem('week', '/wiːk/', '7 days', 'word', 'I work five days a week.', 'Compare: "weak" /wiːk/ — same pronunciation.', null, [ACT.vocabularyMonths]),
    createContentItem('month', '/mʌnθ/', '~30 days', 'word', 'I came here one month ago.', 'Plural: "months" /mʌnθs/.', null, [ACT.vocabularyMonths]),
    createContentItem('year', '/jɪər/', '12 months', 'word', 'This year is 2026.', '', null, [ACT.vocabularyMonths]),
    createContentItem('birthday', '/ˈbɜːrθdeɪ/', 'the anniversary of a person\'s birth', 'word', 'Happy birthday!', 'Greeting: "Happy birthday!" — universal phrase.', null, [ACT.vocabularyMonths]),
    createContentItem('holiday', '/ˈhɒlədeɪ/', 'a day off / special celebration', 'word', 'Christmas is a holiday.', 'British also: "vacation" (American).', null, [ACT.vocabularyMonths]),

    createContentItem(
      'Ordinals 1st–10th',
      'first through tenth',
      'Most ordinals add -th to the cardinal. 1st/2nd/3rd are irregular.',
      'sentence',
      '1st first, 2nd second, 3rd third, 4th fourth, 5th fifth, 6th sixth, 7th seventh, 8th eighth, 9th ninth, 10th tenth',
      'Note: 5th is "fifth" (not "fiveth"); 9th is "ninth" (no "e").',
      [
        { target: '1st first /fɜːrst/', english: 'irregular ordinal' },
        { target: '2nd second /ˈsɛkənd/', english: 'irregular ordinal' },
        { target: '3rd third /θɜːrd/', english: 'irregular ordinal' },
        { target: '4th–10th add -th', english: 'regular pattern' },
      ],
      [ACT.grammarOrdinals],
    ),
    createContentItem(
      'Ordinals 11th–20th',
      'eleventh through twentieth',
      'Most regular with -th. 12th = "twelfth"; 20th = "twentieth".',
      'sentence',
      '11th eleventh, 12th twelfth, 13th thirteenth, … 20th twentieth',
      'Watch: "twelfth" /twɛlfθ/ has a tricky /lfθ/ cluster.',
      null,
      [ACT.grammarOrdinals],
    ),
    createContentItem(
      'Ordinals 21st–31st',
      'twenty-first through thirty-first',
      'Compound ordinals: 21st = "twenty-first"; the ones-digit takes the ordinal form.',
      'sentence',
      '21st twenty-first, 22nd twenty-second, 23rd twenty-third, 30th thirtieth, 31st thirty-first',
      'Only the last digit becomes ordinal; tens stays cardinal.',
      null,
      [ACT.grammarOrdinals],
    ),

    createContentItem(
      'American date format — Month + Day + Year',
      'May 11, 2026',
      'In American English, the month comes first, then day with ordinal, then year. Comma after the day.',
      'sentence',
      'My birthday is May 11, 2026.\nThe class starts on June 3rd.',
      'Written as 5/11/2026 — month/day/year.',
      [
        { target: 'May 11(th), 2026', english: 'spoken: "May eleventh, twenty twenty-six"' },
        { target: '5/11/2026', english: 'numeric: month/day/year (US)' },
      ],
      [ACT.grammarDates],
    ),
    createContentItem(
      'British / international format — Day + Month + Year',
      'the 11th of May, 2026',
      'In British and most other English varieties, the day comes first. Use "of" before the month.',
      'sentence',
      'My birthday is the 11th of May.\nThe meeting is on the 3rd of June.',
      'Written as 11/05/2026 — day/month/year.',
      [
        { target: 'the 11th of May, 2026', english: 'spoken: "the eleventh of May, twenty twenty-six"' },
        { target: '11/5/2026', english: 'numeric: day/month/year (UK/most countries)' },
      ],
      [ACT.grammarDates],
    ),
    createContentItem(
      'Year — say it in pairs',
      'twenty twenty-six',
      'For years 2000+, say in pairs: 2026 = "twenty twenty-six". For 1900s, similar: 1985 = "nineteen eighty-five".',
      'sentence',
      '2026 → twenty twenty-six\n1985 → nineteen eighty-five\n2000 → two thousand',
      '2000 itself is irregular: "two thousand" (not "twenty hundred").',
      null,
      [ACT.grammarDates],
    ),

    createContentItem(
      '"When is …?" — asking',
      'when is / when\'s',
      'Standard question for time and date. Casual contraction: "When\'s".',
      'sentence',
      'When is your birthday? — It\'s on May 11th.\nWhen\'s the test? — It\'s next Tuesday.',
      'Use "when" for both date and time.',
      null,
      [ACT.grammarWhen],
    ),
    createContentItem(
      '"What day is it?" / "What\'s today\'s date?"',
      'day vs date',
      'Two different questions: "What day is it?" asks for the weekday; "What\'s today\'s date?" asks for the day-of-month.',
      'sentence',
      'What day is it? — It\'s Tuesday.\nWhat\'s today\'s date? — It\'s May 11th.',
      'In casual speech, "What day is it" often covers both.',
      null,
      [ACT.grammarWhen],
    ),
    createContentItem(
      'ON / IN / AT — three time prepositions',
      'preposition rules',
      'ON + day (on Monday). IN + month/year/season (in May, in 2026, in summer). AT + clock time (at 7, at noon).',
      'sentence',
      'I have class on Monday at 9 in October.',
      'These are fixed — memorize the pattern.',
      [
        { target: 'ON + day', english: 'on Monday, on May 11th, on weekends' },
        { target: 'IN + month/year/season', english: 'in May, in 2026, in summer' },
        { target: 'AT + clock time', english: 'at 7, at noon, at midnight' },
      ],
      [ACT.grammarWhen],
    ),
    createContentItem(
      'Possessive "\'s" for dates',
      'my birthday / today\'s date',
      'Use possessive "\'s" to talk about someone\'s special day or "today\'s/yesterday\'s" date.',
      'sentence',
      'My birthday is in June.\nToday\'s date is May 11th.\nYesterday\'s class was hard.',
      'Apostrophe + s — never "my birthday\'s".',
      null,
      [ACT.grammarWhen],
    ),

    createContentItem(
      'A semester calendar',
      'reading practice',
      'Read aloud, then answer.',
      'sentence',
      'This semester starts on March 2nd. The midterm is on April 22nd. Children\'s Day is on May 5th — it\'s a holiday. My birthday is on June 11th. The semester ends on June 21st. Summer vacation starts on July 1st.',
      'Note "on + date" pattern repeating.',
      [
        { target: 'semester', english: 'half-year academic period' },
        { target: 'midterm', english: 'middle-of-semester exam' },
        { target: 'summer vacation', english: 'school break in summer' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences with "on + date".',
      'sentence',
      'Q1: When does the semester start? · Q2: When is the midterm? · Q3: When is the birthday?',
      'Use full short answers.',
      [
        { target: 'A1: It starts on March 2nd.', english: 'date with preposition' },
        { target: 'A2: It\'s on April 22nd.', english: 'date with preposition' },
        { target: 'A3: It\'s on June 11th.', english: 'date with preposition' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Birthday dialogue',
      'listening',
      'Two friends exchange birthdays.',
      'conversation',
      'A: When\'s your birthday?\nB: My birthday is on June 11th. How about you?\nA: Mine\'s on December 3rd.\nB: Wow, a winter birthday!\nA: Yes — it\'s really cold but I love it.\nB: Let\'s celebrate together next week. How about Saturday the 18th?\nA: Sounds perfect!',
      'Use "on" + date; "How about you?" to return the question.',
      [
        { target: 'How about you?', english: 'return the question' },
        { target: 'Saturday the 18th', english: 'day + ordinal pattern' },
        { target: 'Sounds perfect!', english: 'casual agreement' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Forgetting the day',
      'listening',
      'Quick exchange about which day class is.',
      'conversation',
      'A: What day is it today?\nB: It\'s Tuesday. Why?\nA: I forgot when my English class is.\nB: Your English class is on Wednesday — that\'s tomorrow.\nA: Oh, right. Thanks!\nB: No problem.',
      '"What day is it?" — natural and useful.',
      null,
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'important dates template',
      'Use this to structure a list.',
      'sentence',
      'I\'m [name]. My birthday is on [date]. My sister\'s birthday is on [date]. I came to Korea in [month] [year]. Next [day], I have a test.',
      '[name] · [your birthday] · [sibling\'s birthday] · [arrival month/year] · [next event]',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 4–5 sentences listing important dates. Use "on" + date and "in" + month.',
      'sentence',
      'Example: My birthday is on July 22nd. My sister\'s is on November 4th. I came to Korea in September 2025. Next Tuesday, the 18th, I have an exam.',
      'Check: preposition + date format consistent.',
      null,
      [ACT.writing],
    ),

    createContentItem(
      'Date format confusion',
      'US vs UK',
      'The biggest trap: "5/11/2026" means May 11 in the US, but November 5 in the UK and most countries. Always write the month as a word for international communication.',
      'sentence',
      'US: 5/11/2026 = May 11, 2026\nUK: 5/11/2026 = 5 November 2026',
      'Safe practice: "11 May 2026" or "May 11, 2026" — never ambiguous.',
      [
        { target: 'US: MM/DD/YYYY', english: 'month first' },
        { target: 'UK / most: DD/MM/YYYY', english: 'day first' },
        { target: 'ISO: YYYY-MM-DD', english: 'unambiguous; used internationally' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Birthday customs',
      '"Happy Birthday!"',
      'In English-speaking cultures: birthday cards (mailed or given), cake with candles, "Happy Birthday" song, and gifts for close family. Adults often celebrate "milestone" birthdays (18, 21, 30, 50).',
      'sentence',
      'Happy birthday, Sarah! — Make a wish! — How many candles?',
      'The "song" is universal: "Happy birthday to you…".',
      [
        { target: 'Happy birthday!', english: 'standard greeting' },
        { target: 'Make a wish', english: 'before blowing candles' },
        { target: 'milestone birthday', english: '18, 21, 30, etc. — special celebration' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Plan a birthday meet-up',
      'consolidation task',
      'Roleplay: Your friend\'s birthday is coming. Confirm the date, pick a day, propose a time.',
      'conversation',
      'Friend: When\'s your birthday?\nYou: [give your birthday]\nFriend: My birthday is on [date]. Let\'s celebrate next week.\nYou: [pick a weekday and confirm]\nFriend: What time?\nYou: [propose a rough time]\nFriend: Great. See you then!',
      'AI tutor will play the friend.',
      [
        { target: 'My birthday is on [date]', english: 'state your date' },
        { target: 'Let\'s meet on [day]', english: 'propose a day' },
        { target: 'How about [time]?', english: 'propose a time' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
