// Level 2 Unit 6 — Performances and Festivals (English)
// Grammar: "Not at all / Don't mention it" (deflect), "whatever / whichever" (free choice),
// "the very + N" / "of all + N" (highlight), "anything but + adj" (emphatic negative).

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2u6-orientation',
  vocabulary: 'en-l2u6-vocabulary',
  pronunciation: 'en-l2u6-pronunciation',
  grammar: 'en-l2u6-grammar',
  speaking: 'en-l2u6-speaking',
  readingSpeaking: 'en-l2u6-reading-speaking',
  listeningSpeaking: 'en-l2u6-listening-speaking',
  readingWriting: 'en-l2u6-reading-writing',
  culture: 'en-l2u6-culture',
  task: 'en-l2u6-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Discuss performances + festivals with appreciation and recommendation.', 'Use 4 intermediate patterns: "not at all" (deflect), "whatever/whichever", "the very + N", "anything but + adj".', 'Recommend a festival confidently.'],
    task: 'Picture inviting a friend to a music festival and recommending what to see.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Festival + performance words',
    goals: ['Use performance, festival, audience, stage, singer, band, review, rating.', 'Use "things to see / do / eat" structures.'],
    task: 'Use 3 "things to + V" phrases in sentences.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Falling-rising intonation for deflection',
    goals: ['Use falling-then-rising contour for "Not at all" deflections.', 'Sound humble, not dismissive.'],
    task: 'Read 3 deflection sentences naturally.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Festival-talk patterns',
    goals: ['"Not at all / Don\'t mention it / Oh, please" — deflecting compliments', '"whatever / whichever + S + V" — free choice', '"the very + N" / "of all + N" — emphatic highlight', '"anything but + adj/N" — emphatic negative'],
    task: 'Use each pattern in a sentence.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Recommending participation',
    goals: ['Recommend a festival to a friend.'],
    task: 'Recommend one festival.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Festival intros',
    goals: ['Read festival intros.', 'Introduce one in your own words.'],
    task: 'Introduce a festival from your country.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Festival news + appreciation',
    goals: ['Listen to news intro about a festival.', 'Discuss appreciation.'],
    task: 'Discuss a performance you liked.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Performance review',
    goals: ['Read a concert review.', 'Write your own.'],
    task: 'Write 3-sentence review.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Coachella, Glastonbury, SXSW — major festivals',
    goals: ['Know Coachella (US), Glastonbury (UK), SXSW (US), Splendour in the Grass (AU).', 'Understand the music-festival economy.'],
    task: 'Compare one famous festival from English-speaking world with one from your culture.' },
  { id: ACT.task, section: 'Task', title: 'Recommend a festival',
    goals: ['Combine all 4 patterns + festival vocabulary.'],
    task: 'Recommend a festival to the AI tutor.' },
];

const lesson = {
  title: 'Level 2 · Unit 6: The very best — Performances and Festivals',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'highlighting-en', label: 'Introducing as must-see', goal: 'Use "the very + N" / "of all + N".' },
    { id: 'emphatic-negative-en', label: 'Emphatic negative', goal: 'Use "anything but + adj".' },
    { id: 'deflecting-compliment-en', label: 'Deflecting a compliment', goal: 'Use "Not at all" / "Oh, please".' },
  ],
  relatedPools: ['topic-culture'],
  content: [
    createContentItem('Lesson goal', 'performances and festivals', 'By end: recommend a festival, deflect compliments humbly, give an emphatic review.', 'word', 'Functions: recommend · deflect · highlight · evaluate.', 'Four performance-talk micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'festival invite', 'Your friend at Kumoh is visiting the US for the first time. You suggest she attend Coachella. You describe must-see acts, what to bring, and what to skip.', 'word', 'You: "Coachella is the very festival you should experience. Whatever style of music you like, there\'s something for you."', 'A typical music-festival recommendation.', null, [ACT.orientation]),

    createContentItem('performance', '/pərˈfɔːrməns/', 'a live show', 'word', 'The performance was sold out.', 'Concerts, plays, ballet — all "performances".', null, [ACT.vocabulary]),
    createContentItem('festival', '/ˈfɛstɪvəl/', 'multi-act multi-day event', 'word', 'Coachella is a music festival in California.', 'Music, food, film, arts — all festivals.', null, [ACT.vocabulary]),
    createContentItem('audience', '/ˈɔːdiəns/', 'people watching', 'word', 'The audience cheered for ten minutes.', 'Singular noun; "members of the audience" plural.', null, [ACT.vocabulary]),
    createContentItem('stage', '/steɪdʒ/', 'raised platform for performance', 'word', 'BTS took the stage at midnight.', '"Main stage" — biggest stage at a festival.', null, [ACT.vocabulary]),
    createContentItem('headliner', '/ˈhɛdlaɪnər/', 'top performer of the night', 'word', 'Beyoncé was the headliner.', 'Smaller acts: "opening act" / "support act".', null, [ACT.vocabulary]),
    createContentItem('lineup', '/ˈlaɪnʌp/', 'roster of performers', 'word', 'The lineup this year is incredible.', 'When discussing a festival.', null, [ACT.vocabulary]),
    createContentItem('encore', '/ˈɒŋkɔːr/', 'extra performance after main set', 'word', 'They played three encore songs.', 'From French "again".', null, [ACT.vocabulary]),
    createContentItem('venue', '/ˈvɛnjuː/', 'location of an event', 'word', 'Madison Square Garden is a famous venue.', 'Used for concerts, sports, weddings.', null, [ACT.vocabulary]),
    createContentItem('review / rating', '/rɪˈvjuː/ /ˈreɪtɪŋ/', 'critical assessment / score', 'word', 'The reviews were all 5 stars.', 'Verb: "review". 5-star / 4-star rating common.', null, [ACT.vocabulary]),
    createContentItem('things to see / do / eat', '/θɪŋz tuː siː/', 'attractions / activities / food', 'word', 'There are so many things to see at the festival.', 'Equivalent to Korean -거리.', null, [ACT.vocabulary]),
    createContentItem('soundcheck', '/ˈsaʊndtʃɛk/', 'pre-show audio test', 'word', 'Soundcheck is at 4 PM.', 'Performance prep.', null, [ACT.vocabulary]),
    createContentItem('mosh pit / front row', '/mɒʃ pɪt/ /frʌnt roʊ/', 'crowd area near stage', 'word', 'The mosh pit was wild.', 'Mosh = energetic rock crowd; front row = closest seats.', null, [ACT.vocabulary]),

    createContentItem('"Not at all" falling-rising', '/nɒt æt ɔːl/ ↘↗', 'For deflecting: drop on "not" then rise on "all".', 'word', '"Your show was amazing!" — "Not at all, just lucky."', 'Sounds humble, not dismissive.', null, [ACT.pronunciation]),
    createContentItem('"Oh, please" /oʊ pliːz/', '/oʊ pliːz/', 'Casual deflection; stress on "please".', 'word', '"You\'re a great singer!" — "Oh, please, I was nervous the whole time."', 'Used among friends.', null, [ACT.pronunciation]),
    createContentItem('"the very" /ðə ˈvɛri/', '/ðə ˈvɛri/', 'Strong stress on "very" for emphasis.', 'word', 'This is the very stage where Bowie performed.', 'Stress conveys "this exact one".', null, [ACT.pronunciation]),
    createContentItem('"anything but" /ˈɛniθɪŋ bʌt/', '/ˈɛniθɪŋ bʌt/', 'Pause briefly after "but"; stress on contradicting adjective.', 'word', 'The show was anything but BORING.', 'Stress = the adjective is exactly NOT true.', null, [ACT.pronunciation]),

    createContentItem(
      'Deflecting compliments',
      'humble register',
      'Standard ways to humbly deflect praise.',
      'sentence',
      '"Your performance was incredible!" — "Not at all, the band carried me."\n"You\'re so talented." — "Oh, please, I just got lucky."\n"You\'re amazing!" — "Don\'t mention it — anyone could do this."',
      'In English deflection, accept a tiny bit then redirect: "thanks but it was the team / luck / a lot of practice".',
      [
        { target: 'Not at all', english: 'strong polite deflection' },
        { target: 'Oh, please', english: 'casual modesty' },
        { target: 'Don\'t mention it', english: 'pre-empt thanks too' },
        { target: 'Thanks, but the team really did it', english: 'redirect to others' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"whatever / whichever + S + V" — free choice',
      'any option works',
      'Indicate that any choice from a set is fine.',
      'sentence',
      'Whatever style of music you like, there\'s something for you here. — Whichever stage you go to, you\'ll have fun. — Pick whatever you want.',
      'Compound: whatever (thing) / whoever (person) / wherever (place) / whenever (time) / however (way) / whichever (specific option).',
      [
        { target: 'whatever + S + V', english: 'any thing' },
        { target: 'whichever + N + S + V', english: 'any of these specific options' },
        { target: 'no matter what + S + V', english: 'similar: regardless' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"the very + N" / "of all + N" — emphatic highlight',
      'singling out',
      'Strongly emphasize that THIS exact one is the right one.',
      'sentence',
      'This is the very stage where Bowie performed. — Of all the festivals in the world, Coachella is my favorite. — He is the very person I wanted to meet.',
      '"The very" — that exact one. "Of all" — out of all options, this stands out.',
      [
        { target: 'the very + N', english: 'this exact one' },
        { target: 'of all the + N + S + V', english: 'highlighted choice' },
        { target: 'none other than + N', english: 'dramatic introduction' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"anything but + adj/N" — emphatic negative',
      'strongly NOT',
      'Stress that the subject is the opposite.',
      'sentence',
      'The show was anything but boring. — He\'s anything but lazy. — Their music is anything but mainstream.',
      'Pattern means "very much NOT". Stronger than "not + adj".',
      [
        { target: 'be + anything but + adj', english: 'strongly not' },
        { target: 'be + anything but + N', english: 'strongly not that type' },
        { target: 'far from + adj', english: 'similar meaning' },
      ],
      [ACT.grammar],
    ),

    createContentItem(
      'Recommending a festival',
      'speaking practice',
      'Use "the very + N" and "whatever".',
      'sentence',
      'Coachella is the very festival you should go to once in your life. Whatever style of music you like, you\'ll find something amazing there.',
      'Frame: "X is the very + N + you should + V. Whatever Y, you\'ll Z."',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Festival intros',
      'reading practice',
      'Read this festival intro.',
      'sentence',
      'Of all the music festivals in the world, Glastonbury is arguably the most legendary. Held annually in Somerset, England, it\'s anything but small — over 200,000 people gather for five days of music, theater, and food. The very mud that frustrates new attendees has become part of the festival\'s charm. Whatever genre you love, from rock to jazz to electronica, there\'s a stage for you. Headliners over the years have included The Rolling Stones, Beyoncé, and Adele.',
      'Standard festival intro.',
      [
        { target: 'Of all the music festivals', english: 'highlight' },
        { target: 'anything but small', english: 'emphatic negative' },
        { target: 'The very mud', english: 'emphatic positive' },
        { target: 'Whatever genre you love', english: 'free choice' },
      ],
      [ACT.readingSpeaking],
    ),

    createContentItem(
      'Concert dialogue',
      'after the show',
      'Two friends after a concert.',
      'conversation',
      'Sarah: That was incredible! You said you weren\'t a Taylor Swift fan, but you sang every word!\nMin-su: Oh, please, I just got caught up in the energy.\nSarah: Not at all — you knew the bridge of every song. Of all the concerts I\'ve been to, this was the very best.\nMin-su: It was anything but boring, I\'ll give you that.\nSarah: Whatever you say next, you\'re a closet Swiftie.\nMin-su: Fine, fine, I admit it.',
      'Note all 4 grammar patterns naturally used.',
      [
        { target: 'Oh, please', english: 'deflection' },
        { target: 'Not at all — you knew the bridge', english: 'reject deflection' },
        { target: 'Of all the concerts I\'ve been to, this was the very best', english: 'emphatic highlight' },
        { target: 'anything but boring', english: 'emphatic negative' },
        { target: 'Whatever you say', english: 'free choice' },
      ],
      [ACT.listeningSpeaking],
    ),

    createContentItem(
      'Concert review',
      'reading + writing',
      'Read this short review.',
      'sentence',
      'TAYLOR SWIFT — ERAS TOUR — LOS ANGELES, AUG 2023.\nOf all the tours this year, the Eras Tour stands alone. Anything but a simple concert, it\'s a three-hour journey through ten albums. Whatever song she chose to open with, the crowd would have screamed. The very lighting design tells a story. ★★★★★',
      'Standard concert-review style.',
      [
        { target: 'Of all the tours this year, … stands alone', english: 'highlight' },
        { target: 'Anything but a simple concert', english: 'emphatic negative' },
        { target: 'Whatever song she chose', english: 'free choice' },
        { target: 'The very lighting design', english: 'emphatic positive' },
      ],
      [ACT.readingWriting],
    ),
    createContentItem(
      'Writing prompt',
      'review',
      'Write a 3-4 line review of a concert or festival you attended.',
      'sentence',
      'Example: Of all the K-pop concerts I\'ve been to, BTS\'s 2019 show was the very best. Anything but ordinary, the lighting and choreography felt like a movie. Whatever they performed, the audience knew every word. ★★★★★',
      'Use at least one "the very", one "anything but", and one "of all".',
      null, [ACT.readingWriting],
    ),

    createContentItem(
      'Major festivals',
      'cultural overview',
      'Coachella (US, California, April) — music + influencer culture. Glastonbury (UK, June) — legendary 5-day festival. SXSW (US, Austin, March) — music + film + tech. Splendour in the Grass (AU, July) — Aussie indie/rock.',
      'sentence',
      'Festivals are a major part of summer culture in the English-speaking world.',
      'Each has its own personality.',
      [
        { target: 'Coachella (US)', english: 'influencer-heavy, two weekends in April' },
        { target: 'Glastonbury (UK)', english: 'most prestigious, June' },
        { target: 'SXSW (US, Austin)', english: 'music + film + tech, March' },
        { target: 'Splendour in the Grass (AU)', english: 'July, Aussie summer' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Festival vocabulary in context',
      'practical phrases',
      '"GA" = General Admission (no assigned seats). "VIP" = backstage / lounge access. "Camping" = on-site tent. "Day pass" vs "weekend pass" vs "season pass".',
      'sentence',
      'GA tickets are cheaper, but VIP gets you closer to the stage and shorter bathroom lines.',
      'Ticket types vary widely; know what each gets you.',
      [
        { target: 'GA = General Admission', english: 'standing-only entry' },
        { target: 'VIP = backstage / lounge', english: 'premium experience' },
        { target: 'camping pass', english: 'tent space included' },
        { target: 'day / weekend / season pass', english: 'duration of access' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Recommend a festival',
      'consolidation task',
      'Recommend a festival to the AI tutor (visiting US/UK for the first time). Use 4 target patterns.',
      'conversation',
      'Tutor: I have a free weekend in California. What festival should I see?\nYou: [highlight a festival with "of all" / "the very"]\nTutor: Is it big?\nYou: [describe with "anything but"]\nTutor: What if I don\'t like one band?\nYou: [reassure with "whatever"]\nTutor: That sounds great. Should I bring anything special?\nYou: [practical tip]',
      'AI tutor will play your visiting friend.',
      [
        { target: 'of all the festivals', english: 'highlight' },
        { target: 'the very + N', english: 'emphatic' },
        { target: 'anything but + adj', english: 'emphatic negative' },
        { target: 'whatever + S + V', english: 'free choice' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
