// Level 2 Adult Unit 3 — Food Preferences & Restrictions (English)
// Functions: dietary needs, allergies, religious restrictions in workplace meal settings.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2au3-orientation',
  pronunciation: 'en-l2au3-pronunciation',
  vocabularyDiet: 'en-l2au3-vocab-diet',
  vocabularyAllergy: 'en-l2au3-vocab-allergy',
  grammarRestriction: 'en-l2au3-grammar-restrict',
  grammarPolite: 'en-l2au3-grammar-polite',
  reading: 'en-l2au3-reading',
  listening: 'en-l2au3-listening',
  writing: 'en-l2au3-writing',
  culture: 'en-l2au3-culture',
  task: 'en-l2au3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['State dietary preferences (vegetarian, vegan, kosher, halal, gluten-free, etc.).', 'Announce food allergies clearly: "I\'m allergic to nuts" / "I have a peanut allergy".', 'Politely decline food without offense.', 'Ask about ingredients.'],
    task: 'Picture being invited to a US workplace lunch — communicate your dietary needs.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Diet & allergy phrases',
    goals: ['Pronounce "allergic" /əˈlɜːrdʒɪk/ — soft "g".', '"Vegetarian" /ˌvɛdʒɪˈtɛəriən/ — 5 syllables.', 'Stress: "GLUTEN-free", "DAIRY-free".'],
    task: 'Read 3 diet phrases aloud.' },
  { id: ACT.vocabularyDiet, section: 'Vocabulary I', title: 'Diet types',
    goals: ['Use vegetarian, vegan, pescatarian, kosher, halal, gluten-free, dairy-free, plant-based.'],
    task: 'Match 5 diet types with example foods.' },
  { id: ACT.vocabularyAllergy, section: 'Vocabulary II', title: 'Allergy + restriction vocabulary',
    goals: ['Use allergy, allergic to, intolerance, sensitivity, anaphylaxis, EpiPen, severe / mild.'],
    task: 'Describe 2 allergies.' },
  { id: ACT.grammarRestriction, section: 'Grammar I', title: 'Stating restrictions',
    goals: ['"I\'m a vegetarian / vegan / etc." vs "I don\'t eat + N".', '"I\'m allergic to + N" / "I have a + N + allergy".', '"I can\'t eat + N because + reason".'],
    task: 'State 3 restrictions.' },
  { id: ACT.grammarPolite, section: 'Grammar II', title: 'Polite decline',
    goals: ['"No, thank you, I\'m good".', '"Thanks, but I don\'t eat + N".', '"I\'ll pass on the + N, thanks".'],
    task: 'Politely decline 3 foods.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'Restaurant menu allergens',
    goals: ['Read a menu with allergen markers.'],
    task: 'Identify safe dishes.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Catering call',
    goals: ['Follow a workplace catering call.'],
    task: 'Reproduce with your own needs.' },
  { id: ACT.writing, section: 'Writing', title: 'Dietary email',
    goals: ['Write a 4-line email to event organizer about your needs.'],
    task: 'Write your own email.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US dietary culture',
    goals: ['Understand how common food restrictions are (10-20% of population).', 'Know event-RSVP etiquette: always state restrictions in advance.', 'Know FDA "top 9 allergens".'],
    task: 'Compare with food culture in your country.' },
  { id: ACT.task, section: 'Task', title: 'RSVP with restrictions',
    goals: ['Combine declaration + reason + appreciation.'],
    task: 'RSVP to a workplace dinner stating your dietary needs.' },
];

const lesson = {
  title: 'Level 2 (Workplace) · Unit 3: I\'m vegetarian — Food Preferences & Restrictions',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'stating-diet-en', label: 'Stating diet', goal: 'Use "I\'m + diet" / "I don\'t eat + N".' },
    { id: 'announcing-allergy-en', label: 'Announcing allergy', goal: 'Use "I\'m allergic to + N" / "I have a + allergy".' },
    { id: 'polite-decline-en', label: 'Polite decline', goal: 'Use "No, thank you" / "Thanks, but I don\'t eat".' },
  ],
  relatedPools: ['topic-food', 'topic-health'],
  content: [
    createContentItem('Lesson goal', 'food preferences', 'By end: state diet, announce allergies, politely decline, ask about ingredients.', 'word', 'Functions: declare · allergize · decline · ask.', 'Four food-talk micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'workplace catering', 'Your team\'s holiday lunch is catered. The organizer asks for everyone\'s dietary needs by Friday. You must list yours clearly — you\'re vegetarian and severely allergic to peanuts.', 'word', 'You: "Thanks for organizing. I\'m vegetarian and severely allergic to peanuts — please flag any dishes with peanuts."', 'Catering RSVP.', null, [ACT.orientation]),

    createContentItem('allergic /əˈlɜːrdʒɪk/', '/əˈlɜːrdʒɪk/', 'Soft "g"; stress on syllable 2.', 'word', 'I\'m allergic to shellfish.', 'Don\'t confuse with /lɜːrdʒɪk/.', null, [ACT.pronunciation]),
    createContentItem('vegetarian /ˌvɛdʒɪˈtɛəriən/', '/ˌvɛdʒɪˈtɛəriən/', '5 syllables, stress on syllable 3.', 'word', 'My friend is a strict vegetarian.', 'Note the "tar-ian" ending.', null, [ACT.pronunciation]),
    createContentItem('"GLUTEN-free"', '/ˈɡluːtən friː/', 'Compound; stress on first.', 'word', 'I need gluten-free bread.', 'Same stress pattern: DAIRY-free, NUT-free, SUGAR-free.', null, [ACT.pronunciation]),

    createContentItem('vegetarian', '/ˌvɛdʒɪˈtɛəriən/', 'no meat (some eat dairy/eggs)', 'word', 'I\'ve been vegetarian for 10 years.', 'Some vegetarians eat fish (= pescatarian).', null, [ACT.vocabularyDiet]),
    createContentItem('vegan', '/ˈviːɡən/', 'no animal products at all', 'word', 'She\'s vegan — no dairy, eggs, or honey either.', 'Stricter than vegetarian.', null, [ACT.vocabularyDiet]),
    createContentItem('pescatarian', '/ˌpɛskəˈtɛəriən/', 'vegetarian + fish', 'word', 'I\'m pescatarian — I eat fish but no meat.', 'Less common term.', null, [ACT.vocabularyDiet]),
    createContentItem('kosher', '/ˈkoʊʃər/', 'follows Jewish dietary laws', 'word', 'Kosher meals exclude pork and shellfish.', 'Religious; certified by rabbis.', null, [ACT.vocabularyDiet]),
    createContentItem('halal', '/həˈlɑːl/', 'follows Islamic dietary laws', 'word', 'Halal meat is prepared specifically.', 'Religious; common in Muslim communities.', null, [ACT.vocabularyDiet]),
    createContentItem('gluten-free', '/ˈɡluːtən friː/', 'no wheat / barley / rye gluten', 'word', 'Gluten-free is essential for celiac disease.', 'Different from "low-carb".', null, [ACT.vocabularyDiet]),
    createContentItem('dairy-free / lactose-free', '/ˈdɛəri friː/', 'no milk products', 'word', 'Dairy-free options include oat milk.', 'Lactose intolerance very common.', null, [ACT.vocabularyDiet]),
    createContentItem('plant-based', '/plænt beɪst/', 'mostly/all plants', 'word', 'I follow a plant-based diet.', 'Less ideological than "vegan"; flexible.', null, [ACT.vocabularyDiet]),

    createContentItem('allergy', '/ˈælərdʒi/', 'immune reaction to a food', 'word', 'My allergy is severe.', 'Adj: "allergic".', null, [ACT.vocabularyAllergy]),
    createContentItem('allergic to + N', '/əˈlɜːrdʒɪk tuː/', 'reactive to a specific food', 'word', 'I\'m allergic to peanuts and shellfish.', 'Standard phrasing.', null, [ACT.vocabularyAllergy]),
    createContentItem('intolerance / sensitivity', '/ɪnˈtɒlərəns/', 'milder bad reaction', 'word', 'I have a lactose intolerance.', 'Intolerance ≠ allergy — different mechanisms.', null, [ACT.vocabularyAllergy]),
    createContentItem('anaphylaxis', '/ˌænəfɪˈlæksɪs/', 'severe life-threatening reaction', 'word', 'A peanut can trigger anaphylaxis.', 'Requires immediate EpiPen + 911.', null, [ACT.vocabularyAllergy]),
    createContentItem('EpiPen', '/ˈɛpiˌpɛn/', 'emergency epinephrine injector', 'word', 'I carry an EpiPen at all times.', 'Life-saving for severe allergies.', null, [ACT.vocabularyAllergy]),
    createContentItem('top 9 allergens', '/tɒp naɪn/', 'FDA-labeled common allergens', 'word', 'Restaurants must label the top 9 allergens.', 'Milk, eggs, fish, shellfish, tree nuts, peanuts, wheat, soy, sesame.', null, [ACT.vocabularyAllergy]),

    createContentItem(
      'Stating dietary restriction',
      'declaration patterns',
      'Three standard ways.',
      'sentence',
      'I\'m a vegetarian. — I don\'t eat pork. — I can\'t eat shellfish because I\'m allergic.',
      '"I\'m a + diet" — identify category. "I don\'t eat + N" — list exclusions.',
      [
        { target: 'I\'m a/an + diet', english: 'identity-level' },
        { target: 'I don\'t eat + N', english: 'specific exclusion' },
        { target: 'I can\'t eat + N because + reason', english: 'allergy/medical' },
      ],
      [ACT.grammarRestriction],
    ),
    createContentItem(
      'Stating allergies',
      'safety-critical',
      'Be specific and concrete.',
      'sentence',
      'I\'m allergic to peanuts. — I have a severe shellfish allergy. — Even trace amounts will trigger anaphylaxis.',
      'For severe allergies, always state severity + the word "anaphylaxis" or "EpiPen".',
      [
        { target: 'I\'m allergic to + N', english: 'standard' },
        { target: 'I have a + severity + N + allergy', english: 'with severity' },
        { target: 'trace amounts will trigger …', english: 'critical info' },
      ],
      [ACT.grammarRestriction],
    ),
    createContentItem(
      'Politely declining food',
      'no offense',
      'Decline without explaining if you don\'t want to.',
      'sentence',
      'No, thank you, I\'m good. — Thanks, but I don\'t eat meat. — I\'ll pass on the salmon, thanks. — Looks great, but I just ate.',
      'Soft refusal + thanks + optional reason. No need to over-explain.',
      [
        { target: 'No, thank you, I\'m good', english: 'polite refuse' },
        { target: 'Thanks, but I don\'t eat + N', english: 'reasoned refuse' },
        { target: 'I\'ll pass on + N', english: 'casual decline' },
        { target: 'Looks great, but + reason', english: 'soft + appreciative' },
      ],
      [ACT.grammarPolite],
    ),
    createContentItem(
      'Asking about ingredients',
      'pre-eat verification',
      'Standard checks at restaurants / parties.',
      'sentence',
      'Does this contain + N? — Is there + N + in this? — Is this + diet?',
      'Pair with reason: "I\'m allergic" / "I\'m vegetarian".',
      [
        { target: 'Does this contain + N?', english: 'check ingredient' },
        { target: 'Is there + N + in this?', english: 'check presence' },
        { target: 'Is this gluten-free / vegan?', english: 'check category' },
      ],
      [ACT.grammarPolite],
    ),

    createContentItem(
      'Restaurant menu',
      'reading practice',
      'Read this allergen-labeled menu.',
      'sentence',
      'GREEN GARDEN CAFE\nCaesar Salad — chicken, romaine, parmesan, croutons (CONTAINS: dairy, gluten, eggs)\nVegan Buddha Bowl — quinoa, chickpeas, kale, tahini (VEGAN, GLUTEN-FREE)\nThai Peanut Noodles — rice noodles, vegetables, peanut sauce (VEGAN, CONTAINS: peanuts, soy)\nGrilled Salmon — wild salmon, lemon, asparagus (GLUTEN-FREE, DAIRY-FREE)',
      'Standard allergen-labeled menu.',
      [
        { target: 'CONTAINS: …', english: 'allergens to avoid' },
        { target: 'VEGAN, GLUTEN-FREE', english: 'diet categories' },
        { target: 'safe dishes for various diets', english: 'menu navigation' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Catering call',
      'workplace dialogue',
      'Coordinating workplace catering.',
      'conversation',
      'Organizer: Hi Min-su, any dietary restrictions for the lunch?\nYou: Yes, thanks for asking. I\'m vegetarian, and I have a severe peanut allergy.\nOrganizer: Got it. We\'re ordering from Green Garden Cafe — they have a vegan Buddha bowl. Will that work?\nYou: That sounds perfect. Could you confirm it doesn\'t touch peanuts in the kitchen?\nOrganizer: I\'ll ask. Anyone with anaphylaxis we should know about?\nYou: Yes — I carry an EpiPen.\nOrganizer: Good to know. I\'ll make sure your meal is labeled and separate.',
      'Note: clear, safety-first communication.',
      [
        { target: 'I\'m vegetarian and I have a severe peanut allergy', english: 'state both' },
        { target: 'Could you confirm it doesn\'t touch peanuts', english: 'cross-contamination check' },
        { target: 'I carry an EpiPen', english: 'severity signal' },
        { target: 'labeled and separate', english: 'safe prep' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Dietary email',
      'writing model',
      'Reply to event organizer.',
      'sentence',
      'Subject: Re: Holiday lunch dietary needs\n\nHi Sarah,\n\nThanks for organizing! For me: I\'m vegetarian, and I have a severe peanut allergy — please flag any dishes prepared near peanuts. If the caterer can label or separate my meal, that would help. I appreciate the accommodation.\n\nThanks,\nMin-su',
      'Standard dietary RSVP email.',
      [
        { target: 'I\'m + diet, and I have a + severity + N + allergy', english: 'state both' },
        { target: 'please flag any dishes prepared near + allergen', english: 'cross-contam check' },
        { target: 'I appreciate the accommodation', english: 'gratitude' },
      ],
      [ACT.writing],
    ),

    createContentItem(
      'US dietary culture',
      'overview',
      'Food restrictions are very common: ~10% vegetarian, ~3% vegan, ~3% kosher/halal, ~32 million Americans have food allergies. Event hosts and restaurants are expected to accommodate.',
      'sentence',
      'In the US, it\'s normal — even expected — to communicate dietary needs before events.',
      'Hosts will ALWAYS ask; don\'t feel rude declaring restrictions.',
      [
        { target: '~10% vegetarian, ~3% vegan', english: 'common diets' },
        { target: '~32 million with food allergies', english: 'wide impact' },
        { target: 'accommodation is expected', english: 'cultural norm' },
        { target: 'FDA top 9 allergens label', english: 'restaurant rule' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: RSVP with restrictions',
      'consolidation task',
      'AI tutor is the event organizer. RSVP to a workplace dinner with your dietary needs.',
      'conversation',
      'Tutor: Hi, can you confirm for the team dinner?\nYou: [confirm + state diet + allergy]\nTutor: We\'re going to a steakhouse. Will that work?\nYou: [check options or counter-propose]\nTutor: [solution]\nYou: [thanks + close]',
      'AI tutor plays organizer.',
      [
        { target: 'I\'m + diet', english: 'state diet' },
        { target: 'I have a + severity + N + allergy', english: 'state allergy' },
        { target: 'Could the venue accommodate + diet?', english: 'check' },
        { target: 'I appreciate the accommodation', english: 'gratitude' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
