// Level 2 Unit 3 — World of Sports (English)
// Grammar: "no matter what / whether", "due to / because of + N", "called / known as",
// "compared to + N". Pronunciation: contractions in sports talk. Culture: American football.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2u3-orientation',
  vocabulary: 'en-l2u3-vocabulary',
  pronunciation: 'en-l2u3-pronunciation',
  grammar: 'en-l2u3-grammar',
  speaking: 'en-l2u3-speaking',
  readingSpeaking: 'en-l2u3-reading-speaking',
  listeningSpeaking: 'en-l2u3-listening-speaking',
  readingWriting: 'en-l2u3-reading-writing',
  culture: 'en-l2u3-culture',
  task: 'en-l2u3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Recap a sports match using cause + comparison + certainty.', 'Use 4 intermediate patterns about sports/predictions.', 'Discuss US/UK/AU sports culture confidently.'],
    task: 'Picture recapping last night\'s World Cup match to your roommate.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Sports + victory/defeat words',
    goals: ['Name 12 sports.', 'Use win, lose, tie/draw, score, fan, cheer, expect, predict, beat, defeat.'],
    task: 'Recap a team\'s wins and losses.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Sports-talk contractions',
    goals: ['Reduce "going to" → "gonna" /ˈɡʌnə/.', 'Reduce "would have" → "would\'ve" /ˈwʊdəv/.', 'Use "should\'ve / could\'ve / might\'ve" naturally.'],
    task: 'Read "Korea\'s gonna win" / "He should\'ve scored" aloud.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Sports-talk patterns',
    goals: ['"No matter what / whether" — certainty regardless', '"due to / because of + N" — cause (formal/informal)', '"called / known as + N" — naming', '"compared to + N" — comparison'],
    task: 'Use each pattern in a sports sentence.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Explaining the match result',
    goals: ['Recap a match using cause + comparison.'],
    task: 'Describe a recent match.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Stadium introductions',
    goals: ['Read intros to famous stadiums.', 'Introduce a stadium from your country.'],
    task: 'Introduce Wembley Stadium or Yankee Stadium in 4 sentences.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Athlete mindsets + match predictions',
    goals: ['Discuss an athlete\'s mentality.', 'Predict match outcomes.'],
    task: 'Predict the next Premier League match.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'A new sport + match write-up',
    goals: ['Read about pickleball.', 'Write about a memorable match.'],
    task: 'Write 3 sentences about a memorable sports moment.' },
  { id: ACT.culture, section: 'Culture Note', title: 'American football, cricket, AFL',
    goals: ['Understand the basics of American football (NFL), cricket (UK/India/AU), AFL (Australian Football League).', 'Know season schedules and the Super Bowl / Ashes / Grand Final.'],
    task: 'Compare one English-speaking-country sport with one from your country.' },
  { id: ACT.task, section: 'Task', title: 'Plan a Kumoh tournament',
    goals: ['Combine vocabulary + 4 grammar patterns in one scene.'],
    task: 'Plan a small soccer tournament for Kumoh National Institute of Technology.' },
];

const lesson = {
  title: 'Level 2 · Unit 3: World of Sports',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'expressing-certainty-en', label: 'Expressing certainty', goal: 'Use "no matter what / whether" for outcomes that won\'t change.' },
    { id: 'explaining-cause-en', label: 'Explaining cause', goal: 'Use "due to / because of + N" for cause.' },
    { id: 'comparing-en', label: 'Comparing two things', goal: 'Use "compared to + N" for athletes/teams.' },
  ],
  relatedPools: ['topic-sports'],
  content: [
    createContentItem('Lesson goal', 'sports talk', 'By end: recap matches, compare teams, predict outcomes, introduce a sport and stadium.', 'word', 'Functions: recap · compare · predict · name · introduce.', 'Five sports-talk micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'World Cup recap', 'Your roommate at Kumoh missed last night\'s World Cup match. You recap it for her, explain why Korea won, and predict tomorrow\'s match.', 'word', 'You: "Korea won 2-1 thanks to Son Heung-min." — Roommate: "Whoa, who\'s their next opponent?"', 'A typical sports recap.', null, [ACT.orientation]),

    createContentItem('soccer / football', '/ˈsɒkər/ /ˈfʊtbɔːl/', 'most popular world sport', 'word', 'I play soccer on weekends.', 'US: "soccer". UK/AU: "football". US "football" = American football.', null, [ACT.vocabulary]),
    createContentItem('basketball / hoops', '/ˈbæskɪtbɔːl/ /huːps/', 'NBA in US, EuroLeague in UK', 'word', 'I watch the NBA every weekend.', '"Hoops" — casual slang for basketball.', null, [ACT.vocabulary]),
    createContentItem('baseball', '/ˈbeɪsbɔːl/', 'huge in US, Japan, Korea', 'word', 'I went to a baseball game last night.', 'Major leagues: MLB (US).', null, [ACT.vocabulary]),
    createContentItem('tennis', '/ˈtɛnɪs/', 'racket sport', 'word', 'Wimbledon is the most famous tennis tournament.', 'Grand Slams: Wimbledon, US Open, French Open, Australian Open.', null, [ACT.vocabulary]),
    createContentItem('cricket', '/ˈkrɪkɪt/', 'huge in UK, India, AU, NZ', 'word', 'The Ashes is between England and Australia.', 'Two main formats: Test (5 days), T20 (3 hours).', null, [ACT.vocabulary]),
    createContentItem('win / lose / tie', '/wɪn/ /luːz/ /taɪ/', 'three match outcomes', 'word', 'Korea won 2-1. — Italy lost in the final. — The game ended in a tie.', 'UK: "draw" is more common than "tie".', null, [ACT.vocabulary]),
    createContentItem('beat / defeat', '/biːt/ /dɪˈfiːt/', 'transitive forms of "win against"', 'word', 'Brazil beat Argentina 3-2.', '"Beat" is casual; "defeat" is more formal.', null, [ACT.vocabulary]),
    createContentItem('score / final score', '/skɔːr/', 'points and end result', 'word', 'The final score was 4-2.', 'Verb: "He scored two goals."', null, [ACT.vocabulary]),
    createContentItem('fan / supporter', '/fæn/ /səˈpɔːrtər/', 'devoted follower', 'word', 'I\'m a huge Manchester United fan.', 'UK: "supporter" — slightly more formal in football context.', null, [ACT.vocabulary]),
    createContentItem('cheer for / root for', '/tʃɪər fɔːr/ /ruːt fɔːr/', 'support a team', 'word', 'Who are you rooting for?', 'US: "root for" — very common.', null, [ACT.vocabulary]),
    createContentItem('expect / predict', '/ɪkˈspɛkt/ /prɪˈdɪkt/', 'anticipate an outcome', 'word', 'I predict a 3-1 win for Korea.', '"Expect" is gentler; "predict" is stronger.', null, [ACT.vocabulary]),
    createContentItem('underdog / favorite', '/ˈʌndərdɒɡ/ /ˈfeɪvərɪt/', 'unlikely vs likely winner', 'word', 'The underdog upset the favorite.', '"Upset" — when underdog beats favorite.', null, [ACT.vocabulary]),

    createContentItem('"gonna" → /ˈɡʌnə/', '/ˈɡʌnə/', 'Casual "going to" — for predictions.', 'word', 'Korea\'s gonna win.', 'Don\'t use in formal writing.', null, [ACT.pronunciation]),
    createContentItem('"should\'ve" → /ˈʃʊdəv/', '/ˈʃʊdəv/', 'Should + have — past regret/criticism.', 'word', 'He should\'ve scored.', 'Don\'t spell "should of" — that\'s an error.', null, [ACT.pronunciation]),
    createContentItem('"would\'ve" → /ˈwʊdəv/', '/ˈwʊdəv/', 'Would + have — hypothetical past.', 'word', 'They would\'ve won if not for the injury.', 'Same pattern: spell "would have" or "would\'ve", never "would of".', null, [ACT.pronunciation]),
    createContentItem('"could\'ve / might\'ve"', '/ˈkʊdəv/ /ˈmaɪtəv/', 'Could/might + have — past possibility.', 'word', 'Brazil might\'ve won if their goalkeeper hadn\'t slipped.', 'All modal + have contractions follow same pattern.', null, [ACT.pronunciation]),

    createContentItem(
      '"no matter + wh-word"',
      'certainty regardless',
      'Outcome won\'t change, regardless of conditions.',
      'sentence',
      'No matter what happens, I\'ll watch the final. — No matter how good they are, Brazil can\'t beat us today. — No matter who plays, they\'ll lose.',
      'Wh-word: what, who, how, when, where, why.',
      [
        { target: 'No matter + what / who / how / when …', english: 'certainty pattern' },
        { target: 'whatever / whoever / however …', english: 'one-word equivalent' },
        { target: 'regardless of + N', english: 'similar: "regardless of the weather"' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"due to / because of + N"',
      'cause (formal/informal)',
      '"Due to" — formal/written. "Because of" — neutral. Followed by a NOUN.',
      'sentence',
      'The match was canceled due to rain. — They lost because of a missed penalty. — Due to his injury, he\'ll miss the season.',
      'Differ from "because" (which takes a CLAUSE): "because + S + V".',
      [
        { target: 'due to + N (formal)', english: 'reporting/writing' },
        { target: 'because of + N (neutral)', english: 'general use' },
        { target: 'because + S + V (clause)', english: 'NOT a noun, a clause' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"called / known as + N"',
      'naming pattern',
      'Introduce something\'s name.',
      'sentence',
      'There\'s a sport called pickleball. — Son Heung-min is known as "Sonny" by his fans. — The match was so good that it\'s now called "the game of the century".',
      'Past participles ("called", "known"): work as adjectives modifying nouns.',
      [
        { target: 'a + N + called + name', english: 'naming new item' },
        { target: 'X is known as Y', english: 'commonly nicknamed' },
        { target: 'so-called + N', english: 'with skeptical tone: "his so-called fans"' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"compared to / compared with + N"',
      'comparison',
      'Standard formal comparison.',
      'sentence',
      'Compared to last year, the team is stronger. — Argentina is small compared to Brazil. — The score was low compared with previous matches.',
      'Comma when "compared to" begins the sentence. "Compared with" is more formal.',
      [
        { target: 'Compared to + N, S + V', english: 'fronted, with comma' },
        { target: 'S + V + compared to + N', english: 'end-position, no comma' },
        { target: 'in comparison with + N', english: 'more formal alternative' },
      ],
      [ACT.grammar],
    ),

    createContentItem(
      'Match recap',
      'speaking practice',
      'Recap a match using cause + certainty + comparison.',
      'sentence',
      'Last night, Korea beat Japan 2-1. They scored two goals in the first half due to great teamwork. Compared to the last game, their defense was much better. No matter who they play next, I think they\'ll win.',
      'Pattern: result + cause + comparison + prediction.',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Stadium introduction',
      'reading practice',
      'Read this stadium intro aloud.',
      'sentence',
      'Wembley Stadium, known as "the home of football", is the largest stadium in the UK with a capacity of 90,000. Compared to other European stadiums, Wembley has unique acoustics that amplify the crowd. The current stadium was built in 2007, due to the demolition of the original 1923 structure. No matter what match is held there, Wembley always feels special — it\'s the dream venue for any English footballer.',
      'Stadium intro: name + claim + capacity + comparison + history + emotional note.',
      [
        { target: 'known as "the home of football"', english: 'naming pattern' },
        { target: 'Compared to other European stadiums', english: 'comparison' },
        { target: 'due to the demolition', english: 'cause' },
        { target: 'No matter what match is held', english: 'certainty' },
      ],
      [ACT.readingSpeaking],
    ),

    createContentItem(
      'Predicting a match',
      'analyst-style dialogue',
      'Two friends discussing the upcoming match.',
      'conversation',
      'Min-su: Who do you think will win the Korea vs Germany match?\nSarah: Honestly, I think Korea will win.\nMin-su: Really? Germany is the favorite.\nSarah: Yes, but compared to four years ago, Korea has improved a lot. And no matter what their coach says, the German defense looks weak.\nMin-su: Hmm, you might be right. Especially due to Son Heung-min\'s recent form.\nSarah: Exactly. He\'s been on fire. I predict 2-1 Korea.\nMin-su: Sounds bold. Let\'s see!',
      'Note all 4 grammar patterns used naturally.',
      [
        { target: 'compared to four years ago', english: 'comparison' },
        { target: 'no matter what their coach says', english: 'certainty' },
        { target: 'due to Son Heung-min\'s recent form', english: 'cause' },
        { target: 'I predict 2-1 Korea', english: 'prediction' },
      ],
      [ACT.listeningSpeaking],
    ),

    createContentItem(
      'A new sport: pickleball',
      'reading + writing',
      'Read this short article.',
      'sentence',
      'There\'s a sport called pickleball, known as "the fastest-growing sport in America". Compared to tennis, the court is smaller and the paddles are solid (not strung). It\'s played with a perforated plastic ball, due to its slower flight. No matter your age, pickleball is easy to pick up — which is why it\'s booming among both teens and seniors.',
      'New-sport article style.',
      [
        { target: 'a sport called pickleball', english: 'naming' },
        { target: 'known as "the fastest-growing"', english: 'reputation' },
        { target: 'Compared to tennis', english: 'comparison' },
        { target: 'due to its slower flight', english: 'cause' },
        { target: 'No matter your age', english: 'certainty' },
      ],
      [ACT.readingWriting],
    ),
    createContentItem(
      'Writing prompt',
      'memorable match',
      'Write 3-4 sentences about a memorable sports moment.',
      'sentence',
      'Example: I\'ll never forget the 2002 World Cup, when Korea beat Italy in extra time. Compared to other underdog stories, this one was extraordinary. We won due to Ahn Jung-hwan\'s golden goal. No matter how many years pass, every Korean fan remembers that night.',
      'Use at least one "compared to", one "due to", and one "no matter".',
      null, [ACT.readingWriting],
    ),

    createContentItem(
      'American football basics',
      'cultural overview',
      'NFL (National Football League) — 32 teams, regular season Sep-Dec, playoffs Jan, Super Bowl in early February. Most-watched US TV event. Players wear helmets and pads. Compared to soccer, far more rules and timeouts.',
      'sentence',
      'The Super Bowl is so big in the US that even people who don\'t watch football watch the halftime show.',
      'Halftime show is a global music event — Beyoncé, Rihanna, etc.',
      [
        { target: 'NFL = National Football League', english: 'top US league' },
        { target: 'Super Bowl = championship game', english: 'early February' },
        { target: 'season: Sep-Feb', english: 'regular + playoffs + final' },
        { target: 'Compared to soccer', english: 'more rules, more timeouts' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Cricket and AFL',
      'UK / AU sports',
      'Cricket — England, India, Australia, NZ. The Ashes (England vs Australia) is the biggest test series. AFL (Australian Football League) — Australian rules football; Grand Final in September, similar emotional weight to Super Bowl.',
      'sentence',
      'In Australia, the AFL Grand Final is a public holiday in Victoria.',
      'Australians are passionate about both cricket and AFL.',
      [
        { target: 'cricket — bat-and-ball', english: 'UK, India, AU, NZ' },
        { target: 'The Ashes (Eng vs AU)', english: 'biggest cricket rivalry' },
        { target: 'AFL = Australian rules football', english: 'AU national sport' },
        { target: 'Grand Final (AFL)', english: 'AU equivalent of Super Bowl' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Plan a Kumoh soccer tournament',
      'consolidation task',
      'Plan a small soccer tournament for Kumoh — pick teams, predict winners, explain rules.',
      'conversation',
      'Tutor: How will the Kumoh tournament work?\nYou: [explain format using "called" — "a tournament called Kumoh Cup"]\nTutor: Who do you expect to win?\nYou: [predict with "compared to" + "due to"]\nTutor: What if it rains?\nYou: [respond with "no matter what / due to"]\nTutor: [closing]\nYou: [thanks + invite]',
      'AI tutor will play your co-organizer.',
      [
        { target: 'a tournament called …', english: 'naming' },
        { target: 'compared to last year', english: 'comparison' },
        { target: 'due to … the team is stronger', english: 'cause' },
        { target: 'no matter what the weather', english: 'certainty' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
