// Level 1 Unit 3 — Locations & Directions (English)
// Functions: asking where places are, giving simple directions.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u3-orientation',
  pronunciation: 'en-l1u3-pronunciation',
  vocabularyPlaces: 'en-l1u3-vocab-places',
  vocabularyDirections: 'en-l1u3-vocab-directions',
  grammarWhere: 'en-l1u3-grammar-where',
  grammarGoTo: 'en-l1u3-grammar-go-to',
  grammarDirections: 'en-l1u3-grammar-directions',
  reading: 'en-l1u3-reading',
  listening: 'en-l1u3-listening',
  writing: 'en-l1u3-writing',
  culture: 'en-l1u3-culture',
  task: 'en-l1u3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Ask "Where is…?" to find any place.', 'Give 2–3 step directions (go straight, turn left/right).', 'State the location of a building relative to another with prepositions.'],
    task: 'Imagine you are lost on a campus or in a new city — you must ask, listen, and give directions in return.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Sound traps',
    goals: ['Pronounce "Where" /wɛr/ — not /vɛr/. Lip rounding for /w/.', 'Pronounce "library" /ˈlaɪbrɛri/ (3 syllables, not /laɪbrəri/).'],
    task: 'Read each direction phrase aloud.' },
  { id: ACT.vocabularyPlaces, section: 'Vocabulary I', title: 'Places in a city / campus',
    goals: ['Name 15+ common buildings and places.'],
    task: 'List five places near where you live.' },
  { id: ACT.vocabularyDirections, section: 'Vocabulary II', title: 'Direction words',
    goals: ['Use left, right, straight, turn, corner, block.'],
    task: 'Describe a route from your house to school.' },
  { id: ACT.grammarWhere, section: 'Grammar I', title: '"Where is …?" / "It is on ___ Street."',
    goals: ['Ask "Where is the …?" and "Where are the …?".', 'Reply with "It is on / at / next to ___".'],
    task: 'Ask and answer about three places.' },
  { id: ACT.grammarGoTo, section: 'Grammar II', title: 'go to / get to + place',
    goals: ['Use "go to + place" for travel: I go to school.', 'Use "How do I get to…?" to ask directions.'],
    task: 'Make three "go to" + three "get to" sentences.' },
  { id: ACT.grammarDirections, section: 'Grammar III', title: 'Imperative directions: "Go straight. Turn left."',
    goals: ['Use imperative form: Go / Turn / Take / Walk.', 'Chain steps with "Then…".'],
    task: 'Give a three-step direction.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A campus description',
    goals: ['Read a paragraph locating buildings.'],
    task: 'Answer comprehension questions in English.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Asking for directions',
    goals: ['Follow a directions dialogue.'],
    task: 'Reproduce with your real classroom destination.' },
  { id: ACT.writing, section: 'Writing', title: 'Write directions',
    goals: ['Write 3–5 sentences guiding a visitor.'],
    task: 'Write directions from a known landmark to your favorite spot.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Asking strangers in English-speaking countries',
    goals: ['Open with "Excuse me", not just the question.', 'Thank with "Thanks" / "Thanks so much".'],
    task: 'Practice the polite opener for three scenarios.' },
  { id: ACT.task, section: 'Task', title: 'Guide a visitor on campus',
    goals: ['Combine "Where is", "How do I get to", and step directions.'],
    task: 'Roleplay directing a visitor from the main gate to the library.' },
];

const lesson = {
  title: 'Level 1 · Unit 3: Where is the library? — Locations and Directions',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-where', label: 'Asking where a place is', goal: 'Use "Where is the …?".' },
    { id: 'describing-position', label: 'Describing where something is', goal: 'Use prepositions of location.' },
    { id: 'giving-directions', label: 'Giving simple directions', goal: 'Use imperative + left/right/straight.' },
  ],
  relatedPools: ['topic-school', 'topic-city'],
  content: [
    createContentItem('Lesson goal', 'finding & directing', 'By end of lesson: ask where something is, give 2–3 step directions, describe a building\'s position relative to another.', 'word', 'Functions: ask location · describe position · give directions.', 'Three skills that unlock independent travel.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'lost on campus', 'It is your second week on campus and a new exchange student asks you where the library is.', 'word', 'Visitor: "Excuse me, where is the library?"', 'A typical campus situation.', null, [ACT.orientation]),

    createContentItem('Where /wɛr/', '/wɛr/', '/w/ uses rounded lips, not /v/ (teeth on lip). Distinct from "vary" /ˈvɛri/.', 'word', 'Where are you from? /wɛr ər juː frɒm/', 'Lip-rounding is the key — practice in a mirror.', null, [ACT.pronunciation]),
    createContentItem('library /ˈlaɪbrɛri/', '/ˈlaɪbrɛri/', 'Three syllables: LI-bra-ry. Many learners say two (/laɪbri/) — keep all three.', 'word', 'The library is on Main Street.', 'Stress on the first syllable.', null, [ACT.pronunciation]),
    createContentItem('straight /streɪt/', '/streɪt/', 'Silent "gh"; consonant cluster /str/ at the start.', 'word', 'Go straight ahead.', 'Same /eɪ/ vowel as "day".', null, [ACT.pronunciation]),
    createContentItem('right / left', '/raɪt/ /lɛft/', 'For /r/ in "right", tongue curls back, no contact. For /l/ in "left", tongue tip presses firmly behind upper teeth.', 'word', 'Turn right, then left.', 'The l/r distinction is the most common L2 trouble pair.', null, [ACT.pronunciation]),

    createContentItem('library', '/ˈlaɪbrɛri/', 'a place to borrow and read books', 'word', 'I study at the library.', 'Compound noun if "school library".', null, [ACT.vocabularyPlaces]),
    createContentItem('cafeteria', '/ˌkæfəˈtɪriə/', 'a self-service restaurant, common at schools and offices', 'word', 'Lunch at the cafeteria is cheap.', 'Stress on the third syllable.', null, [ACT.vocabularyPlaces]),
    createContentItem('classroom', '/ˈklɑːsruːm/', 'a room where students learn', 'word', 'Our classroom is on the third floor.', 'Compound noun.', null, [ACT.vocabularyPlaces]),
    createContentItem('restroom', '/ˈrɛstruːm/', 'a public toilet (American English)', 'word', 'Where is the restroom?', 'British English: "toilet" or "loo".', null, [ACT.vocabularyPlaces]),
    createContentItem('dormitory', '/ˈdɔːrmətɔːri/', 'student housing on campus', 'word', 'I live in the dormitory.', 'Short form: "dorm".', null, [ACT.vocabularyPlaces]),
    createContentItem('pharmacy', '/ˈfɑːrməsi/', 'a shop that sells medicine', 'word', 'The pharmacy is next to the clinic.', 'British English: "chemist".', null, [ACT.vocabularyPlaces]),
    createContentItem('hospital', '/ˈhɒspɪtəl/', 'a place where people receive medical care', 'word', 'The hospital is near the train station.', 'For minor issues, people go to a "clinic".', null, [ACT.vocabularyPlaces]),
    createContentItem('bank', '/bæŋk/', 'a place that keeps money and provides financial services', 'word', 'The bank closes at 5.', 'Also: the side of a river.', null, [ACT.vocabularyPlaces]),
    createContentItem('convenience store', '/kənˈviːniəns stɔːr/', 'a small shop open long hours', 'word', 'Convenience stores are open 24 hours.', 'British English: "corner shop".', null, [ACT.vocabularyPlaces]),
    createContentItem('cafe', '/ˈkæfeɪ/', 'a small place for coffee and snacks', 'word', 'Meet me at the cafe.', 'Pronunciation varies: /ˈkæfeɪ/ or /kæˈfeɪ/.', null, [ACT.vocabularyPlaces]),
    createContentItem('subway station', '/ˈsʌbweɪ ˈsteɪʃən/', 'a stop on the underground train', 'word', 'The subway station is in front of the school.', 'British English: "tube" or "underground".', null, [ACT.vocabularyPlaces]),
    createContentItem('bus stop', '/bʌs stɒp/', 'a place where buses pick up passengers', 'word', 'Wait at the bus stop.', 'Two-word compound.', null, [ACT.vocabularyPlaces]),
    createContentItem('post office', '/poʊst ˈɒfɪs/', 'a place for sending mail and packages', 'word', 'I sent the letter at the post office.', 'Compound noun.', null, [ACT.vocabularyPlaces]),
    createContentItem('park', '/pɑːrk/', 'a public outdoor area with grass and trees', 'word', 'We walk in the park on weekends.', 'Also a verb: "to park a car".', null, [ACT.vocabularyPlaces]),
    createContentItem('museum', '/mjuːˈziːəm/', 'a building displaying artifacts or art', 'word', 'The museum is free on Sundays.', 'Stress on the second syllable.', null, [ACT.vocabularyPlaces]),

    createContentItem('left', '/lɛft/', 'the side opposite the right', 'word', 'Turn left at the corner.', 'Used in directions and as a side reference.', null, [ACT.vocabularyDirections]),
    createContentItem('right', '/raɪt/', 'the side opposite the left', 'word', 'Turn right after the bank.', 'Also means "correct".', null, [ACT.vocabularyDirections]),
    createContentItem('straight', '/streɪt/', 'in the same direction, without turning', 'word', 'Go straight for two blocks.', 'Often paired with "ahead" — "go straight ahead".', null, [ACT.vocabularyDirections]),
    createContentItem('turn', '/tɜːrn/', 'to change direction', 'word', 'Turn left, then turn right.', 'Verb; common in directions.', null, [ACT.vocabularyDirections]),
    createContentItem('corner', '/ˈkɔːrnər/', 'the point where two streets meet', 'word', 'The shop is on the corner.', '"On the corner" — at the intersection.', null, [ACT.vocabularyDirections]),
    createContentItem('block', '/blɒk/', 'a square area of city streets', 'word', 'Walk two blocks and turn left.', 'American English uses blocks more than British.', null, [ACT.vocabularyDirections]),
    createContentItem('street', '/striːt/', 'a road in a town or city', 'word', 'The cafe is on Main Street.', 'Capitalize when part of a name: "Main Street".', null, [ACT.vocabularyDirections]),
    createContentItem('avenue', '/ˈævənuː/', 'a wide street, often lined with trees', 'word', 'Fifth Avenue is famous in New York.', 'Abbreviated as "Ave."', null, [ACT.vocabularyDirections]),
    createContentItem('cross', '/krɒs/', 'to go from one side to the other', 'word', 'Cross the street at the light.', 'Verb; takes a direct object.', null, [ACT.vocabularyDirections]),
    createContentItem('go past', '/ɡoʊ pæst/', 'to walk past without entering', 'word', 'Go past the bank, then turn left.', 'Phrasal — "past" links to the landmark.', null, [ACT.vocabularyDirections]),

    createContentItem(
      '"Where is …?" / "Where are …?"',
      'where is / where are',
      'Ask the location of a noun. Use "is" for singular, "are" for plural.',
      'sentence',
      'Where is the library? — It is on Main Street.\nWhere are the restrooms? — They are upstairs.',
      'In casual speech, "Where\'s" is the standard contraction.',
      [
        { target: 'Where is …', note: 'singular' },
        { target: 'Where are …', note: 'plural' },
        { target: 'Where\'s = where is', note: 'contraction' },
      ],
      [ACT.grammarWhere],
    ),
    createContentItem(
      'Reply with "It / They + be + preposition + place"',
      'It is on / next to / between',
      'Answer with a subject pronoun (it/they) + "to be" + location preposition + place.',
      'sentence',
      'Where is the cafe? — It is next to the bank.\nWhere are the books? — They are on the shelf.',
      'Use "it" for singular things, "they" for plural.',
      null,
      [ACT.grammarWhere],
    ),

    createContentItem(
      '"go to" + place — travel verb',
      'I go to school',
      'Use "go to" + place when stating you travel somewhere. With definite places, add "the": go to THE library.',
      'sentence',
      'I go to school every day. — She goes to the bank on Fridays.',
      'Some places skip the article: "school", "work", "home" — but most take "the".',
      [
        { target: 'go to school / work / home', note: 'no article — these are abstract locations' },
        { target: 'go to THE library / store', note: 'with "the" — specific physical places' },
      ],
      [ACT.grammarGoTo],
    ),
    createContentItem(
      '"How do I get to …?"',
      'asking for directions',
      'The standard question to ask for directions. More natural than "Where is…?" when you want a route.',
      'sentence',
      'How do I get to the library? — Go straight, then turn right.',
      'Use "Where is…?" to find the location; "How do I get to…?" to learn the route.',
      [
        { target: 'How do I get to …?', note: 'asks for the route' },
        { target: 'Where is …?', note: 'asks for the location only' },
      ],
      [ACT.grammarGoTo],
    ),
    createContentItem(
      'Compare: go to / come to / arrive at',
      'movement verbs',
      '"Go to" — speaker moves away; "come to" — moves toward speaker; "arrive at" — reach destination.',
      'sentence',
      'I go to school at 8. — Please come to my house. — I arrive at the office at 9.',
      '"Arrive at" with most places; "arrive in" with cities/countries.',
      null,
      [ACT.grammarGoTo],
    ),

    createContentItem(
      'Imperative directions — bare verb',
      'go / turn / take',
      'Use the bare verb form (no subject) for direct instructions. The subject "you" is implied.',
      'sentence',
      'Go straight. — Turn left. — Take the second right.',
      'Add "please" for politeness: "Please go straight ahead."',
      [
        { target: 'Go straight (ahead)', note: 'continue forward' },
        { target: 'Turn left / right', note: 'change direction' },
        { target: 'Take the (first/second) (left/right)', note: 'choose the Nth turning' },
      ],
      [ACT.grammarDirections],
    ),
    createContentItem(
      'Chain steps with "Then…"',
      'sequence connector',
      'Use "Then" to mark each next step. Other connectors: "and then", "after that", "finally".',
      'sentence',
      'Go straight for two blocks. Then turn right at the bank. Then walk for one block. The library is on your left.',
      'Each new step gets a new sentence; do not pile them all into one.',
      null,
      [ACT.grammarDirections],
    ),
    createContentItem(
      '"on your left/right"',
      'visual reference',
      'Use "on your left/right" to tell someone what side they will see something on.',
      'sentence',
      'The library is on your left. — You will see the cafe on your right.',
      'Always with possessive "your" — not "the".',
      null,
      [ACT.grammarDirections],
    ),

    createContentItem(
      'Campus description',
      'reading practice',
      'Read aloud, then answer the questions.',
      'sentence',
      'This is Massachusetts Institute of Technology. There is a bus stop in front of the main gate. When you go through the gate, the student center is on your left. The cafeteria is on the first floor of the student center. Next to the student center is the library. Behind the library is the dormitory.',
      'Use prepositions to locate each building relative to others.',
      [
        { target: 'in front of the main gate', note: 'preposition phrase' },
        { target: 'on the first floor', note: 'floor reference' },
        { target: 'next to the student center', note: 'side reference' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Answer based on the paragraph.',
      'sentence',
      'Q1: What is in front of the main gate? · Q2: Where is the cafeteria? · Q3: What is behind the library?',
      'Use full short answers.',
      [
        { target: 'A1: There is a bus stop.', note: 'use "there is/are"' },
        { target: 'A2: It is on the first floor of the student center.', note: 'use "it is on"' },
        { target: 'A3: The dormitory is behind the library.', note: 'use subject + be + preposition' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Asking for directions to the library',
      'multi-step',
      'A 6-turn dialogue showing the natural opener "Excuse me", the question, the answer, and the thanks.',
      'conversation',
      'A: Excuse me, how do I get to the library?\nB: Go straight ahead. Then turn right at the cafe.\nA: Turn right at the cafe — got it.\nB: Yes. The library is on your left, next to the student center.\nA: Thanks so much!\nB: You\'re welcome.',
      'Repeat back what you heard to confirm — natural and helpful.',
      [
        { target: 'Excuse me', note: 'standard opener for asking a stranger' },
        { target: 'Thanks so much / Thanks a lot', note: 'natural enthusiastic thanks' },
        { target: 'You\'re welcome / No problem', note: 'standard reply to thanks' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Asking for the restroom',
      'short request',
      'Quick exchange when you need the restroom in a public place.',
      'conversation',
      'A: Excuse me, where is the restroom?\nB: It is on the second floor, next to the elevator.\nA: Thank you.\nB: No problem.',
      'In British English you might hear "Where\'s the toilet?".',
      null,
      [ACT.listening],
    ),

    createContentItem(
      'Model directions',
      'writing template',
      'Use this skeleton.',
      'sentence',
      'Start at [landmark]. Go straight for [N] blocks. Turn [left/right] at [landmark]. Walk for [N] minutes. [Destination] is on your [left/right].',
      '[start] → [straight] → [turn] → [continue] → [destination].',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 3–5 sentences directing a friend from a landmark to your favorite spot. Include at least one "turn" and one "on your left/right".',
      'sentence',
      'Example: Start at the main gate. Go straight for one block. Turn right at the cafe. Walk for two minutes. The library is on your right.',
      'Each step should be one short sentence.',
      null,
      [ACT.writing],
    ),

    createContentItem(
      'Polite "Excuse me"',
      'asking strangers',
      'Always open a question to a stranger with "Excuse me". Without it, the question can sound abrupt or rude.',
      'sentence',
      '✓ Excuse me, where is the library?\n✗ Where is the library? (without opener, sounds blunt)',
      '"Excuse me" is the universal polite opener in English-speaking cultures.',
      null,
      [ACT.culture],
    ),
    createContentItem(
      'Thank — enthusiastically',
      'response habits',
      'After getting help, thank the helper warmly. "Thanks" alone is fine for peers; "Thanks so much" or "I appreciate it" is warmer.',
      'sentence',
      'Thanks so much. / Thank you very much. / I really appreciate it.',
      'A flat "Thanks" can sound cold; English speakers add emphasis.',
      null,
      [ACT.culture],
    ),
    createContentItem(
      'Using Google Maps / Apple Maps',
      'real-world coping',
      'In English-speaking countries, most people simply check maps on their phone. But asking directions still works and is friendly.',
      'sentence',
      'I checked Google Maps. — Let me use my phone.',
      'For tourist areas, locals expect questions; in business districts, people may be in a hurry.',
      null,
      [ACT.culture],
    ),

    createContentItem(
      'Task: Guide a visitor',
      'consolidation task',
      'A new exchange student texts you from the campus main gate. Guide them to the library using 3–5 sentences.',
      'conversation',
      'Visitor: I just arrived at the main gate. How do I get to the library?\nYou: [give 2-step direction]\nVisitor: I see the student center. What next?\nYou: [next step + final position]\nVisitor: Thanks so much!\nYou: [polite close]',
      'AI tutor will play the visitor.',
      [
        { target: 'Go straight from the gate.', note: 'first step' },
        { target: 'Then turn right at the cafe.', note: 'second step' },
        { target: 'The library is on your left.', note: 'final position' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
