// Level 1 Unit 19 — Cultural Holidays (English)
// Functions: talking about major English-speaking holidays, family customs, food;
// while + V-ing for simultaneous actions, if/when clauses, possessive 's.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l1u19-orientation',
  pronunciation: 'en-l1u19-pronunciation',
  vocabularyHolidays: 'en-l1u19-vocab-hol',
  vocabularyFamily: 'en-l1u19-vocab-fam',
  grammarWhile: 'en-l1u19-grammar-while',
  grammarIfWhen: 'en-l1u19-grammar-ifwhen',
  grammarPossessive: 'en-l1u19-grammar-poss',
  reading: 'en-l1u19-reading',
  listening: 'en-l1u19-listening',
  writing: 'en-l1u19-writing',
  culture: 'en-l1u19-culture',
  task: 'en-l1u19-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Name 5 major holidays in English-speaking countries: Thanksgiving, Christmas, New Year, Halloween, Easter.', 'Talk about holiday food, customs, and family gatherings.', 'Use "while + V-ing" for two simultaneous actions, "if / when" clauses for conditions, and possessive \'s for family relations.', 'Compare a holiday from your culture with one from the US, UK, or Australia.'],
    task: 'Imagine being invited to a friend\'s Thanksgiving dinner in the US — follow the customs, talk about food, and ask about family traditions.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Holiday sound traps',
    goals: ['Pronounce "Thanksgiving" /ˈθæŋksˌɡɪvɪŋ/ — voiceless /θ/ + nasal /ŋ/ cluster.', 'Pronounce "Christmas" /ˈkrɪsməs/ — silent "t" (not /ˈkrɪstməs/).', 'Reduce "and" to /ən/ in "turkey and stuffing" /ˈtɜːrki ən ˈstʌfɪŋ/.'],
    task: 'Read each holiday phrase aloud paying attention to silent letters and reductions.' },
  { id: ACT.vocabularyHolidays, section: 'Vocabulary I', title: 'Holiday names + customs',
    goals: ['Use holiday, festival, celebrate, decoration, gift, fireworks, parade, tradition, custom.'],
    task: 'Pair each food/custom with a holiday.' },
  { id: ACT.vocabularyFamily, section: 'Vocabulary II', title: 'Family relations',
    goals: ['Use family, relatives, grandparents, parents, siblings, cousins, aunt, uncle, in-laws.'],
    task: 'Name 5 family members in English.' },
  { id: ACT.grammarWhile, section: 'Grammar I', title: '"while + V-ing" — simultaneous actions',
    goals: ['Form "main clause + while + V-ing" or "While + V-ing, main clause".', 'Both actions have the SAME subject and happen at the SAME time.', 'Alternative: "during + noun" for a noun phrase.'],
    task: 'Combine 2 simultaneous actions into 3 sentences.' },
  { id: ACT.grammarIfWhen, section: 'Grammar II', title: '"if / when + clause" — condition or time',
    goals: ['Use "if + present, will + V" for first conditional ("If it rains, we will stay home").', 'Use "when + present, present" for general truths ("When Christmas comes, we decorate the tree").', 'Distinguish: "if" = condition (might not happen); "when" = time (will happen).'],
    task: 'Make three "if" sentences and three "when" sentences.' },
  { id: ACT.grammarPossessive, section: 'Grammar III', title: 'Possessive \'s and "of"',
    goals: ['Form "[person]\'s [thing]" for people, animals.', 'Use plural possessive: "the kids\' presents" — apostrophe AFTER -s.', 'Use "of" for inanimate objects ("the door of the house").'],
    task: 'Make three possessive phrases about your family.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A Thanksgiving blog post',
    goals: ['Read a 6-sentence Thanksgiving blog entry.'],
    task: 'Identify when, where, what foods, and what customs.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Holiday plans',
    goals: ['Follow a holiday planning dialogue.'],
    task: 'Reproduce with your own holiday plans.' },
  { id: ACT.writing, section: 'Writing', title: 'Compare a holiday',
    goals: ['Write 4-5 sentences comparing a holiday from your country with one from an English-speaking country.'],
    task: 'Write your own comparison.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Major holidays in the English-speaking world',
    goals: ['Know dates and core customs: Thanksgiving (US, 4th Thursday in November), Christmas (Dec 25), New Year (Jan 1), Halloween (Oct 31), Easter (spring), Independence Day (US, July 4).', 'Know UK/AU variations: Boxing Day, Bonfire Night, Australia Day.'],
    task: 'Summarize one US and one UK/AU holiday custom.' },
  { id: ACT.task, section: 'Task', title: 'Invited to Thanksgiving',
    goals: ['Combine "while + V-ing", "if / when" clauses, and possessive \'s.'],
    task: 'Roleplay being invited to a friend\'s Thanksgiving dinner.' },
];

const lesson = {
  title: 'Level 1 · Unit 19: We celebrate together — Cultural Holidays',
  category: 'cultural',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'talking-holidays-en', label: 'Talking about holidays', goal: 'Describe a holiday: when, what we eat, what we do.' },
    { id: 'while-doing-en', label: 'Describing simultaneous actions', goal: 'Use "while + V-ing" or "during + N".' },
    { id: 'if-when-clauses-en', label: 'Conditions and time', goal: 'Use "if" for condition, "when" for time.' },
  ],
  relatedPools: ['topic-culture'],
  content: [
    createContentItem('Lesson goal', 'cultural holidays', 'By end: name major English-speaking holidays, describe food and customs, use "while", "if/when", and possessive \'s.', 'word', 'Functions: name holidays · describe customs · simultaneous actions · conditions · possessive.', 'Five micro-skills around holidays.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Thanksgiving invitation', 'Your American friend invites you to her family\'s Thanksgiving dinner in New York. You eat turkey, meet relatives, and share your own culture\'s holiday traditions.', 'word', 'Friend: "What does your family do on holidays?" — You: "We gather and eat a big meal, like you."', 'Cross-cultural conversation.', null, [ACT.orientation]),

    createContentItem('Thanksgiving /ˈθæŋksɡɪvɪŋ/', '/ˈθæŋksɡɪvɪŋ/', 'Voiceless /θ/ + nasal /ŋ/ cluster.', 'word', 'Happy Thanksgiving!', 'Tongue tip between teeth for "th" — no vibration.', null, [ACT.pronunciation]),
    createContentItem('Christmas /ˈkrɪsməs/', '/ˈkrɪsməs/', 'Silent "t" — NOT /ˈkrɪstməs/.', 'word', 'Merry Christmas!', 'Many English speakers mistakenly insert "t" — don\'t.', null, [ACT.pronunciation]),
    createContentItem('Halloween /ˌhæləˈwiːn/', '/ˌhæləˈwiːn/', 'Stress on syllable 3.', 'word', 'Halloween is October 31st.', 'British speakers sometimes say /ˌhæloʊˈiːn/.', null, [ACT.pronunciation]),
    createContentItem('"turkey and stuffing"', '/ˈtɜːrki ən ˈstʌfɪŋ/', 'Reduce "and" to /ən/ in connected speech.', 'word', 'We had turkey and stuffing.', 'Function words always reduce in fast speech.', null, [ACT.pronunciation]),
    createContentItem('"to/two/too" — same sound', '/tuː/', 'These three words sound identical.', 'word', 'I went to two parties, too.', 'Context determines meaning.', null, [ACT.pronunciation]),

    createContentItem('holiday', '/ˈhɒlədeɪ/', 'a special celebration day', 'word', 'My favorite holiday is Christmas.', 'US: "holiday" = single day. UK: "holiday" can also mean "vacation".', null, [ACT.vocabularyHolidays]),
    createContentItem('festival', '/ˈfɛstɪvəl/', 'a multi-day or recurring celebration', 'word', 'The harvest festival lasts a week.', 'Often religious or cultural.', null, [ACT.vocabularyHolidays]),
    createContentItem('celebrate', '/ˈsɛlɪbreɪt/', 'mark a special occasion', 'word', 'We celebrate Christmas with our family.', 'Noun form: celebration.', null, [ACT.vocabularyHolidays]),
    createContentItem('decoration / decorate', '/ˌdɛkəˈreɪʃən/ /ˈdɛkəreɪt/', 'ornaments / put them up', 'word', 'We decorate the Christmas tree.', 'Common decorations: lights, ornaments, wreaths.', null, [ACT.vocabularyHolidays]),
    createContentItem('gift / present', '/ɡɪft/ /ˈprɛzənt/', 'something given to someone', 'word', 'I bought a gift for my mom.', '"Gift" — slightly more formal; "present" — slightly more casual. Interchangeable.', null, [ACT.vocabularyHolidays]),
    createContentItem('fireworks', '/ˈfaɪərwɜːrks/', 'colorful explosives in the sky', 'word', 'We watched fireworks on the 4th of July.', 'Always plural.', null, [ACT.vocabularyHolidays]),
    createContentItem('parade', '/pəˈreɪd/', 'public procession with floats', 'word', 'The Macy\'s Thanksgiving parade is famous.', 'Famous parades: Macy\'s, Pride, Rose Parade.', null, [ACT.vocabularyHolidays]),
    createContentItem('tradition / custom', '/trəˈdɪʃən/ /ˈkʌstəm/', 'something done year after year', 'word', 'Eating turkey is a Thanksgiving tradition.', 'Near-synonyms; "tradition" is more cultural, "custom" more behavioral.', null, [ACT.vocabularyHolidays]),
    createContentItem('Thanksgiving', '/ˈθæŋksɡɪvɪŋ/', 'US holiday, 4th Thursday in November', 'word', 'Thanksgiving is about gratitude and family.', 'Canada celebrates Thanksgiving on the 2nd Monday in October.', null, [ACT.vocabularyHolidays]),
    createContentItem('Christmas', '/ˈkrɪsməs/', 'Christian holiday, December 25', 'word', 'Christmas Eve is December 24.', 'Now widely secular too.', null, [ACT.vocabularyHolidays]),
    createContentItem('New Year\'s', '/njuː jɪərz/', 'January 1 / Eve = December 31', 'word', 'We had a party on New Year\'s Eve.', '"New Year\'s Eve" (Dec 31) vs "New Year\'s Day" (Jan 1).', null, [ACT.vocabularyHolidays]),
    createContentItem('Halloween', '/ˌhæləˈwiːn/', 'October 31; costumes, candy, "trick or treat"', 'word', 'Kids go trick-or-treating on Halloween.', 'Children visit houses in costume; adults give candy.', null, [ACT.vocabularyHolidays]),
    createContentItem('Easter', '/ˈiːstər/', 'spring Christian holiday', 'word', 'Easter is in spring.', 'Customs: Easter eggs, Easter egg hunts, Easter Bunny.', null, [ACT.vocabularyHolidays]),
    createContentItem('Independence Day / 4th of July', '/ˌɪndɪˈpɛndəns deɪ/', 'US holiday, July 4', 'word', 'On the 4th of July we watch fireworks.', 'Also called "the 4th".', null, [ACT.vocabularyHolidays]),
    createContentItem('Valentine\'s Day', '/ˈvælənˌtaɪnz deɪ/', 'February 14; love, flowers, cards', 'word', 'I gave my partner flowers on Valentine\'s Day.', 'Customs: chocolates, roses, cards.', null, [ACT.vocabularyHolidays]),
    createContentItem('Mother\'s / Father\'s Day', '/ˈmʌðərz deɪ/', 'honor parents in spring/early summer', 'word', 'I called my mom on Mother\'s Day.', 'US: Mother\'s Day = 2nd Sunday in May; Father\'s Day = 3rd Sunday in June.', null, [ACT.vocabularyHolidays]),

    createContentItem('family', '/ˈfæməli/', 'related people you grew up with', 'word', 'My family is small.', 'Includes parents + siblings + sometimes extended.', null, [ACT.vocabularyFamily]),
    createContentItem('relatives', '/ˈrɛlətɪvz/', 'all family beyond immediate household', 'word', 'I have relatives in Boston.', 'Includes cousins, aunts, uncles, etc.', null, [ACT.vocabularyFamily]),
    createContentItem('grandparents', '/ˈɡrænpɛrənts/', 'parents of parents', 'word', 'My grandparents live in Florida.', 'Singular: grandfather/grandmother. Casual: grandpa/grandma.', null, [ACT.vocabularyFamily]),
    createContentItem('parents', '/ˈpɛrənts/', 'mother and father', 'word', 'My parents are visiting this weekend.', 'Plural form most common in this word.', null, [ACT.vocabularyFamily]),
    createContentItem('siblings', '/ˈsɪblɪŋz/', 'brothers and sisters', 'word', 'I have two siblings.', 'Gender-neutral. "Brother" / "sister" if specifying.', null, [ACT.vocabularyFamily]),
    createContentItem('brother / sister', '/ˈbrʌðər/ /ˈsɪstər/', 'male / female sibling', 'word', 'My older brother is in college.', '"Older / younger" instead of separate words like Korean 형/누나.', null, [ACT.vocabularyFamily]),
    createContentItem('cousins', '/ˈkʌzənz/', 'children of your aunts and uncles', 'word', 'I have eight cousins.', 'Gender-neutral.', null, [ACT.vocabularyFamily]),
    createContentItem('aunt / uncle', '/ænt/ /ˈʌŋkəl/', 'parent\'s sibling', 'word', 'My aunt lives next door.', 'US: /ænt/. UK: /ɑːnt/.', null, [ACT.vocabularyFamily]),
    createContentItem('in-laws', '/ˈɪnˌlɔːz/', 'family by marriage', 'word', 'My in-laws are coming for Thanksgiving.', 'Mother-in-law, father-in-law, brother-in-law, sister-in-law.', null, [ACT.vocabularyFamily]),
    createContentItem('niece / nephew', '/niːs/ /ˈnɛfjuː/', 'sibling\'s child (f/m)', 'word', 'My niece is six years old.', 'Niece (girl) / nephew (boy).', null, [ACT.vocabularyFamily]),
    createContentItem('partner / spouse', '/ˈpɑːrtnər/ /spaʊs/', 'romantic partner / married partner', 'word', 'My partner and I host Christmas.', '"Partner" — gender-neutral, also includes unmarried.', null, [ACT.vocabularyFamily]),

    createContentItem(
      '"while + V-ing" — at the same time',
      'simultaneous actions',
      'Two actions, same subject, same time.',
      'sentence',
      'I cook turkey while listening to music. — While decorating the tree, we drank hot chocolate.',
      'Word order: either "main + while" OR "While …, main". Comma after fronted "While".',
      [
        { target: 'main clause + while + V-ing', english: 'standard order' },
        { target: 'While + V-ing, main clause', english: 'fronted, with comma' },
        { target: '"during + noun"', english: 'alternative: "during the meal"' },
      ],
      [ACT.grammarWhile],
    ),
    createContentItem(
      '"during + noun"',
      'noun-form alternative',
      'Use "during + noun" when the second part is a noun (event, time).',
      'sentence',
      'During Christmas, we eat a lot. — She slept during the movie.',
      'Use "while" with a verb; "during" with a noun.',
      null,
      [ACT.grammarWhile],
    ),
    createContentItem(
      'Common holiday simultaneous actions',
      'examples',
      'High-frequency holiday combinations.',
      'sentence',
      'We open presents while drinking coffee. — Kids watch fireworks while eating ice cream. — My family laughs while telling stories.',
      'Pattern: action 1 + while + action 2 (-ing).',
      null,
      [ACT.grammarWhile],
    ),

    createContentItem(
      '"if + present, will + V" — first conditional',
      'real possibility',
      'For something that might happen.',
      'sentence',
      'If it snows, we\'ll have a white Christmas. — If my cousins come, we\'ll play games.',
      'Comma after "if" clause when "if" is first. No comma when "if" comes second.',
      [
        { target: 'If + present, will + V', english: 'standard pattern' },
        { target: 'will + V if + present', english: 'inverted, no comma' },
        { target: 'can/may also after "if"', english: '"If you want, you can come"' },
      ],
      [ACT.grammarIfWhen],
    ),
    createContentItem(
      '"when + present, present" — general truth',
      'always happens',
      'For something that always happens.',
      'sentence',
      'When Christmas comes, we put up the tree. — When my grandparents visit, we cook a big meal.',
      'Both halves in simple present — describes habits, not single events.',
      [
        { target: 'When + present, present', english: 'habitual / general truth' },
        { target: 'When + past, past', english: 'past habit: "When I was little, we lit candles"' },
      ],
      [ACT.grammarIfWhen],
    ),
    createContentItem(
      '"if" vs "when" — uncertain vs certain',
      'key contrast',
      '"if" = may or may not happen. "when" = will definitely happen.',
      'sentence',
      'If it rains tomorrow, we\'ll stay inside. (maybe) — When summer comes, we go camping. (definitely)',
      'Use "if" for conditions, "when" for time.',
      null,
      [ACT.grammarIfWhen],
    ),

    createContentItem(
      'Possessive \'s — singular',
      'individual ownership',
      'Add \'s to any singular noun, even if it ends in -s.',
      'sentence',
      'my mom\'s cookies — my brother\'s gift — Sarah\'s house — James\'s car',
      'Even for names ending in -s: James\'s. (Some style guides allow just "James\'", but "James\'s" is more common.)',
      [
        { target: 'noun + \'s', english: 'singular possessive' },
        { target: 'name ending in -s + \'s', english: 'still adds \'s: "James\'s"' },
        { target: 'compound: brother-in-law\'s', english: 'add \'s to whole phrase' },
      ],
      [ACT.grammarPossessive],
    ),
    createContentItem(
      'Possessive — plural',
      'group ownership',
      'For regular plural nouns (ending in -s), add only the apostrophe.',
      'sentence',
      'the kids\' presents — my parents\' house — the Smiths\' Christmas party',
      'Plural irregular (children, women): add \'s — "the children\'s toys".',
      [
        { target: 'plural -s + \'', english: 'apostrophe after -s' },
        { target: 'irregular plural + \'s', english: 'children\'s, women\'s, men\'s' },
      ],
      [ACT.grammarPossessive],
    ),
    createContentItem(
      'Possessive — "of" for things',
      'inanimate ownership',
      'Use "of" instead of \'s for objects/places.',
      'sentence',
      'the door of the house (NOT "the house\'s door") — the end of the year — the name of the holiday',
      'For people/animals, prefer \'s. For things/abstract, prefer "of".',
      [
        { target: 'people/animals → \'s', english: 'my friend\'s book' },
        { target: 'things → of', english: 'the cover of the book' },
        { target: 'time can use \'s', english: 'today\'s news, yesterday\'s game' },
      ],
      [ACT.grammarPossessive],
    ),

    createContentItem(
      'A Thanksgiving blog post',
      'reading practice',
      'Read this Thanksgiving entry aloud.',
      'sentence',
      'Last Thursday was Thanksgiving. My whole family came to my parents\' house in New Jersey. My mom and I cooked a big turkey while my dad set the table. We had stuffing, mashed potatoes, cranberry sauce, and pumpkin pie. Before eating, we each said one thing we were thankful for. When dinner was over, the kids played games while the adults watched football. It was a perfect day.',
      'Standard family Thanksgiving description.',
      [
        { target: 'Last Thursday was Thanksgiving', english: 'past time marker' },
        { target: 'cooked while … set the table', english: 'simultaneous actions' },
        { target: 'said one thing we were thankful for', english: 'the gratitude tradition' },
        { target: 'kids played while adults watched', english: 'two simultaneous actions' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences.',
      'sentence',
      'Q1: When was Thanksgiving? · Q2: Who cooked the turkey? · Q3: What did they do before eating? · Q4: What did the kids do after dinner?',
      'Use past tense in answers.',
      [
        { target: 'A1: Last Thursday.', english: 'time' },
        { target: 'A2: Mom and the narrator cooked the turkey.', english: 'cook' },
        { target: 'A3: They said one thing they were thankful for.', english: 'gratitude' },
        { target: 'A4: They played games.', english: 'kids\' activity' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Planning Thanksgiving dinner',
      'family dialogue',
      'Two siblings planning who brings what.',
      'conversation',
      'Sarah: So, Thanksgiving is in two weeks. Are you coming to Mom\'s?\nMike: Of course. What should I bring?\nSarah: Mom\'s making the turkey, so don\'t worry about that. Could you bring dessert?\nMike: Sure. Pumpkin pie or apple pie?\nSarah: Both, if you can! Aunt Linda is coming with her kids, and they\'ll eat anything.\nMike: Got it. Will Grandpa come?\nSarah: Yes, but only if Dad picks him up. Grandpa doesn\'t drive anymore.\nMike: OK. See you at 2?\nSarah: 2 sharp. While we\'re eating, the kids will watch the parade on TV.\nMike: Perfect. See you then.',
      'Note: "Mom\'s making" (possessive + present continuous future), "if Dad picks him up" (conditional), "while we\'re eating" (simultaneous).',
      [
        { target: 'Mom\'s making the turkey', english: 'present continuous future' },
        { target: 'only if Dad picks him up', english: 'first conditional' },
        { target: 'while we\'re eating, kids will watch', english: 'simultaneous actions' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'New Year\'s plans',
      'casual dialogue',
      'Friends discussing New Year\'s Eve plans.',
      'conversation',
      'Alex: What are you doing for New Year\'s?\nJamie: My partner\'s family is having a party. You?\nAlex: We\'re staying home, watching the ball drop in Times Square on TV.\nJamie: Classic. Any resolutions?\nAlex: I want to exercise more. If I keep it up for three months, it might stick.\nJamie: Good goal. When midnight comes, what do you do?\nAlex: We toast with champagne, then kiss. You?\nJamie: Same. It\'s a tradition.',
      'Note: "When midnight comes, what do you do?" — general/habitual when.',
      [
        { target: 'partner\'s family', english: 'possessive \'s' },
        { target: 'If I keep it up for three months', english: 'first conditional' },
        { target: 'When midnight comes', english: 'time / habitual when' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'comparison template',
      'Compare a holiday from your country with a Western one.',
      'sentence',
      'In my country, our biggest holiday is [name]. We celebrate it in [season/month]. On this day, we [main activity]. We eat [foods]. Family members [what they do]. Compared to [Western holiday], it is similar in [one way] but different in [one way].',
      'Five sections: name · timing · main activity · food · comparison.',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write a 4-5 sentence comparison between a holiday from your country and Thanksgiving or Christmas.',
      'sentence',
      'Example: In Korea, our biggest holiday is Chuseok. We celebrate it in autumn, on the 15th day of the 8th lunar month. We eat songpyeon and visit our grandparents\' graves. Like Thanksgiving, Chuseok is about gratitude and family. Different from Thanksgiving, we wear traditional clothes called hanbok.',
      'Use "like / different from / similar to" for comparison.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Major US holidays',
      'cultural overview',
      'New Year\'s Day (Jan 1) · Martin Luther King Day (Jan, 3rd Mon) · Valentine\'s Day (Feb 14) · Memorial Day (May, last Mon) · Independence Day (Jul 4) · Labor Day (Sep, 1st Mon) · Halloween (Oct 31) · Thanksgiving (Nov, 4th Thu) · Christmas (Dec 25).',
      'sentence',
      'Thanksgiving + Christmas + New Year\'s = "the holidays" / "holiday season".',
      'Americans often call the Nov-Jan stretch "the holidays".',
      [
        { target: 'Thanksgiving = gratitude + family', english: 'US, 4th Thu of Nov' },
        { target: 'Christmas = lights + gifts + family', english: 'Dec 25' },
        { target: '4th of July = fireworks + BBQ + flag', english: 'patriotism' },
        { target: 'Halloween = costumes + candy', english: 'fun, not religious' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'UK / Australia variations',
      'regional differences',
      'UK: Boxing Day (Dec 26) · Bonfire Night / Guy Fawkes (Nov 5) · no Thanksgiving · Christmas crackers. Australia: Christmas in summer · Boxing Day · Australia Day (Jan 26) · ANZAC Day (Apr 25).',
      'sentence',
      'UK: "Happy Christmas". US: "Merry Christmas". Both work, but country preference differs.',
      'Aussies often spend Christmas at the beach.',
      [
        { target: 'Boxing Day (UK, AU, CA)', english: 'Dec 26, shopping + relaxing' },
        { target: 'Bonfire Night (UK)', english: 'fireworks, Nov 5' },
        { target: 'Christmas in summer (AU)', english: 'beach BBQs, no snow' },
        { target: 'Australia Day (AU)', english: 'national day, Jan 26' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Invited to Thanksgiving',
      'consolidation task',
      'Roleplay: Your friend invites you to her family\'s Thanksgiving. Ask about customs, share your culture.',
      'conversation',
      'Friend: So glad you could come! Hungry?\nYou: [polite reply + question about the food]\nFriend: [describes turkey + sides + uses "while"]\nYou: [share one holiday from your country, using possessive \'s and "while"]\nFriend: [asks "if/when" question]\nYou: [answer with "if" or "when"]\nFriend: [closing]\nYou: [thanks]',
      'AI tutor will play your friend.',
      [
        { target: 'In my country, my family\'s biggest …', english: 'possessive \'s' },
        { target: 'While we eat, we …', english: 'simultaneous' },
        { target: 'When … comes, we …', english: 'when-clause' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
