// Level 1 Unit 11 — Scheduling & Invitations (English)
// Functions: telling time, making plans, accepting/declining politely.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u11-orientation',
  pronunciation: 'en-l1u11-pronunciation',
  vocabularyTime: 'en-l1u11-vocab-time',
  vocabularyEvents: 'en-l1u11-vocab-events',
  grammarTime: 'en-l1u11-grammar-time',
  grammarInvite: 'en-l1u11-grammar-invite',
  grammarDecline: 'en-l1u11-grammar-decline',
  reading: 'en-l1u11-reading',
  listening: 'en-l1u11-listening',
  writing: 'en-l1u11-writing',
  culture: 'en-l1u11-culture',
  task: 'en-l1u11-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Tell time accurately.', 'Make and accept invitations.', 'Politely decline with a reason.', 'Propose alternative times.'],
    task: 'Imagine inviting a classmate to study together — propose time/place, accept/decline.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Time phrases',
    goals: ['"quarter past" / "half past" / "a quarter to".', '"3 PM" — say /θriː piː ɛm/, not /θriː ɛm/.'],
    task: 'Read 5 times aloud in two formats.' },
  { id: ACT.vocabularyTime, section: 'Vocabulary I', title: 'Time vocabulary',
    goals: ['Use o\'clock, half past, quarter past, quarter to, AM/PM, sharp.'],
    task: 'Say 5 times in casual and formal forms.' },
  { id: ACT.vocabularyEvents, section: 'Vocabulary II', title: 'Events & invitations',
    goals: ['Use party, dinner, coffee, movie, study session, hangout, plans.'],
    task: 'Pair an event with a typical time.' },
  { id: ACT.grammarTime, section: 'Grammar I', title: 'Telling time + prepositions',
    goals: ['Use "at + time" (at 7), "on + day" (on Monday), "in + month/year" (in May).', 'Know two time formats: digital and "past/to".'],
    task: 'Give 5 time + day + place combinations.' },
  { id: ACT.grammarInvite, section: 'Grammar II', title: 'Invitations — "Want to…?" / "Would you like to…?"',
    goals: ['"Want to + verb?" — casual invite.', '"Would you like to + verb?" — polite invite.', 'Reply: "Sure!", "I\'d love to", "Sounds good".'],
    task: 'Make 3 invitations + acceptances.' },
  { id: ACT.grammarDecline, section: 'Grammar III', title: 'Polite decline + counter-proposal',
    goals: ['Use "Sorry, I can\'t" + reason + counter.', 'Suggest alternative with "How about…?".'],
    task: 'Decline one invitation and propose a different time.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A text message exchange',
    goals: ['Read a short text exchange about plans.'],
    task: 'Identify when, where, and what they will do.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Two invitations',
    goals: ['Follow an acceptance dialogue and a decline-with-counter dialogue.'],
    task: 'Reproduce with your own schedule.' },
  { id: ACT.writing, section: 'Writing', title: 'Inviting a friend',
    goals: ['Write a 3–4 sentence text invitation.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Punctuality and confirmation',
    goals: ['English-speaking cultures value punctuality.', 'Confirm plans a day before — "Just checking — still on for tomorrow?"'],
    task: 'Decide an appropriate confirmation message.' },
  { id: ACT.task, section: 'Task', title: 'Set up a study session',
    goals: ['Combine time, invitation, accept/decline, alternatives.'],
    task: 'Plan a Saturday study session with the AI tutor.' },
];

const lesson = {
  title: 'Level 1 · Unit 11: Want to grab coffee? — Scheduling and Invitations',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'making-invitation', label: 'Making an invitation', goal: 'Use "Want to…?" or "Would you like to…?".' },
    { id: 'asking-availability', label: 'Asking availability', goal: 'Use "Are you free?" / "Do you have time?".' },
    { id: 'accepting-declining', label: 'Accepting / declining politely', goal: 'Reply with reason if declining.' },
    { id: 'proposing-alternative', label: 'Proposing an alternative', goal: 'Use "How about…?".' },
  ],
  relatedPools: ['topic-school', 'topic-people'],
  content: [
    createContentItem('Lesson goal', 'plans', 'By end: tell time, invite, ask availability, accept, decline, and propose alternatives.', 'word', 'Functions: time · invite · ask · accept/decline · propose.', 'Full scheduling toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'study session', 'A classmate texts you "Want to study together on Saturday?" — you read, reply, and propose a time/place.', 'word', 'Friend: "Want to study together?" — You: "Sure! How about 2 PM at the library?"', 'A typical text message exchange.', null, [ACT.orientation]),

    createContentItem('quarter past', '/ˈkwɔːrtər pæst/', '15 minutes after the hour. UK preferred.', 'word', '7:15 = a quarter past seven', 'In US, also "seven fifteen" is fine.', null, [ACT.pronunciation]),
    createContentItem('half past', '/hæf pæst/', '30 minutes after the hour. UK preferred.', 'word', '7:30 = half past seven', 'US also: "seven thirty".', null, [ACT.pronunciation]),
    createContentItem('quarter to', '/ˈkwɔːrtər tu/', '15 minutes before the hour.', 'word', '6:45 = a quarter to seven', 'Watch the math: 6:45 is "to seven", not "to six".', null, [ACT.pronunciation]),
    createContentItem('AM / PM', '/eɪ ɛm/ /piː ɛm/', 'Latin abbreviations. AM = before noon; PM = noon to midnight.', 'word', '9 AM / 3 PM', 'Say each letter — never /eɪm/.', null, [ACT.pronunciation]),

    createContentItem('o\'clock', '/əˈklɒk/', 'used only with whole hours', 'word', 'It\'s 5 o\'clock.', 'Don\'t use with minutes: ✗ "5:15 o\'clock".', null, [ACT.vocabularyTime]),
    createContentItem('sharp', '/ʃɑːrp/', 'exactly at the time', 'word', 'Meet me at 3 PM sharp.', 'Emphasizes punctuality.', null, [ACT.vocabularyTime]),
    createContentItem('noon / midnight', '/nuːn/ /ˈmɪdnaɪt/', '12 PM / 12 AM', 'word', 'Lunch is at noon.', 'Avoid "12 AM/PM" ambiguity — use these terms.', null, [ACT.vocabularyTime]),
    createContentItem('morning', '/ˈmɔːrnɪŋ/', 'time from sunrise to noon', 'word', 'I have class in the morning.', 'Use "in the morning".', null, [ACT.vocabularyTime]),
    createContentItem('afternoon', '/ˌɑːftərˈnuːn/', 'time from noon to evening', 'word', 'See you this afternoon.', 'Use "in the afternoon" or "this afternoon".', null, [ACT.vocabularyTime]),
    createContentItem('evening', '/ˈiːvnɪŋ/', 'time from sunset to bedtime', 'word', 'Dinner is in the evening.', 'Use "in the evening".', null, [ACT.vocabularyTime]),
    createContentItem('night', '/naɪt/', 'after evening, dark hours', 'word', 'I sleep at night.', 'Use "AT night" — unique preposition.', null, [ACT.vocabularyTime]),
    createContentItem('a.m. / p.m.', '/eɪ ɛm/ /piː ɛm/', 'morning / afternoon-evening designators', 'word', '9 a.m. / 3 p.m.', 'In writing, lowercase with periods or uppercase no periods.', null, [ACT.vocabularyTime]),

    createContentItem('party', '/ˈpɑːrti/', 'social gathering', 'word', 'There\'s a party on Friday.', '', null, [ACT.vocabularyEvents]),
    createContentItem('dinner', '/ˈdɪnər/', 'evening meal', 'word', 'Want to grab dinner?', '"Grab" = casual "have".', null, [ACT.vocabularyEvents]),
    createContentItem('lunch', '/lʌntʃ/', 'midday meal', 'word', 'Let\'s have lunch tomorrow.', '', null, [ACT.vocabularyEvents]),
    createContentItem('coffee', '/ˈkɔːfi/', 'casual meeting (over coffee)', 'word', 'Want to grab coffee?', '"Coffee" often means a short social meeting, not just the drink.', null, [ACT.vocabularyEvents]),
    createContentItem('movie', '/ˈmuːvi/', 'film at a theater or home', 'word', 'Let\'s watch a movie.', 'US: "movie"; UK: "film".', null, [ACT.vocabularyEvents]),
    createContentItem('study session', '/ˈstʌdi ˈsɛʃən/', 'organized time to study together', 'word', 'I have a study session at the library.', '', null, [ACT.vocabularyEvents]),
    createContentItem('hangout', '/ˈhæŋaʊt/', 'casual meet-up with friends', 'word', 'It was a fun hangout.', 'Noun; "hang out" as a verb.', null, [ACT.vocabularyEvents]),
    createContentItem('plans', '/plænz/', 'arranged activities', 'word', 'Do you have plans tonight?', 'Always plural in this sense.', null, [ACT.vocabularyEvents]),
    createContentItem('busy', '/ˈbɪzi/', 'with many things to do', 'word', 'I\'m busy tomorrow.', 'Used to politely decline.', null, [ACT.vocabularyEvents]),
    createContentItem('free', '/friː/', 'without plans', 'word', 'I\'m free on Saturday.', 'Opposite of "busy".', null, [ACT.vocabularyEvents]),

    createContentItem(
      'Two ways to tell time',
      'digital + past/to',
      'Digital style: "It\'s seven fifteen". Past/to style: "It\'s a quarter past seven".',
      'sentence',
      '7:15 = "seven fifteen" or "a quarter past seven"\n7:30 = "seven thirty" or "half past seven"\n7:45 = "seven forty-five" or "a quarter to eight"',
      'Both are correct; digital is more common in the US, past/to in the UK.',
      [
        { target: 'digital format', english: 'just say the numbers' },
        { target: 'past/to format', english: 'use minutes relative to the hour' },
      ],
      [ACT.grammarTime],
    ),
    createContentItem(
      'AT + time, ON + day, IN + month',
      'time preposition rules',
      'AT for clock times; ON for days/dates; IN for months/years/seasons.',
      'sentence',
      'See you at 5 PM, on Friday, in May.',
      'Three different prepositions, three different time scales.',
      [
        { target: 'AT + time', english: 'at 5, at noon, at midnight' },
        { target: 'ON + day/date', english: 'on Monday, on May 5th' },
        { target: 'IN + month/year/season', english: 'in May, in 2026, in summer' },
      ],
      [ACT.grammarTime],
    ),
    createContentItem(
      'What time / when',
      'asking time',
      '"What time is it?" — asks the current time. "When is …?" — asks the time of an event.',
      'sentence',
      'What time is it? — It\'s 3 PM.\nWhen is the meeting? — At 4 o\'clock.',
      'Use the right one for the right situation.',
      null,
      [ACT.grammarTime],
    ),

    createContentItem(
      '"Want to …?" — casual invitation',
      'subject + want to + verb',
      'Standard casual invite. "Want to grab coffee?" is friendlier than "Do you want to grab coffee?" but means the same.',
      'sentence',
      'Want to grab coffee tomorrow? — Sure!\nWant to study together?',
      'Casual omits the auxiliary "do" at the start.',
      [
        { target: 'Want to + V?', english: 'casual invite' },
        { target: 'Wanna + V?', english: 'very casual contraction' },
        { target: 'Do you want to + V?', english: 'slightly more formal' },
      ],
      [ACT.grammarInvite],
    ),
    createContentItem(
      '"Would you like to …?"',
      'polite invitation',
      'Polite invite — appropriate for first meetings or formal settings.',
      'sentence',
      'Would you like to join us for dinner? — I\'d love to!',
      'Reply with "I\'d love to" (= I would love to).',
      [
        { target: 'Would you like to + V?', english: 'polite invite' },
        { target: 'I\'d love to / I\'d like that', english: 'polite acceptance' },
      ],
      [ACT.grammarInvite],
    ),
    createContentItem(
      'Acceptance phrases',
      'positive replies',
      'Standard ways to say yes: "Sure", "Sounds good", "Sounds great", "I\'d love to", "Count me in".',
      'sentence',
      'A: Want to study? — B: Sure, let\'s do it!\nA: Pizza tonight? — B: Count me in!',
      'Match the formality of the invitation.',
      [
        { target: 'Sure / Sounds good', english: 'casual' },
        { target: 'I\'d love to', english: 'polite enthusiastic' },
        { target: 'Count me in', english: 'casual enthusiastic' },
      ],
      [ACT.grammarInvite],
    ),

    createContentItem(
      'Polite decline + reason',
      '"Sorry, I can\'t" + reason',
      'Always soften with "sorry" + give a short reason.',
      'sentence',
      'Sorry, I can\'t — I have a lot of work.\nThanks for inviting me, but I have other plans.',
      'Never just "No" — it sounds rude in English.',
      [
        { target: 'Sorry, I can\'t', english: 'basic decline opener' },
        { target: 'Thanks for inviting me, but …', english: 'polite decline' },
        { target: 'I\'d love to, but …', english: 'reluctant decline' },
      ],
      [ACT.grammarDecline],
    ),
    createContentItem(
      'Counter-proposal — "How about …?"',
      'offer alternative',
      'After declining, propose another time/date.',
      'sentence',
      'Sorry, I can\'t on Friday. How about Saturday?\nI\'m busy at 3. How about 5?',
      'Always offer an alternative if you want to keep the invitation open.',
      [
        { target: 'How about + N/V-ing?', english: 'propose alternative' },
        { target: 'What about + N/V-ing?', english: 'same meaning' },
      ],
      [ACT.grammarDecline],
    ),
    createContentItem(
      'Confirming the new plan',
      'pin it down',
      'After settling, confirm with specific time and place.',
      'sentence',
      'OK, see you Saturday at 2 PM at the library. — Great, see you then!',
      'Confirmation prevents misunderstanding.',
      null,
      [ACT.grammarDecline],
    ),

    createContentItem(
      'A KakaoTalk-style text exchange',
      'reading practice',
      'Read this exchange aloud, then answer the questions.',
      'sentence',
      'Minsu: Hey Sarah, want to study together this weekend?\nSarah: Sure! When works for you?\nMinsu: How about Saturday at 2 PM?\nSarah: Hmm, I have plans then. How about 4?\nMinsu: 4 works! Where?\nSarah: The library? 1st floor entrance.\nMinsu: Perfect. See you Saturday at 4 at the library!',
      'A typical back-and-forth scheduling text.',
      [
        { target: 'When works for you?', english: 'standard scheduling question' },
        { target: 'How about + time?', english: 'propose time' },
        { target: '[time] works!', english: 'confirm a time' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences.',
      'sentence',
      'Q1: What day will they meet? · Q2: What time? · Q3: Where?',
      'Use prepositions correctly.',
      [
        { target: 'A1: On Saturday.', english: 'use "on" + day' },
        { target: 'A2: At 4 PM.', english: 'use "at" + time' },
        { target: 'A3: At the library.', english: 'place answer' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Accepting an invitation',
      'listening',
      'Standard "yes" dialogue.',
      'conversation',
      'A: Sarah, are you free this Saturday?\nB: Yeah, Saturday\'s good. What\'s up?\nA: Want to grab coffee? Maybe at the new place downtown?\nB: Sure! What time?\nA: How about 2 PM?\nB: 2 works for me. See you there!',
      'Note "Saturday\'s good" — short for "Saturday is good".',
      [
        { target: 'Are you free?', english: 'check availability' },
        { target: 'What\'s up?', english: 'ask the purpose' },
        { target: '[time] works for me', english: 'confirm time' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Declining with counter-proposal',
      'listening',
      'Polite "no, but …" dialogue.',
      'conversation',
      'A: Want to grab dinner tonight?\nB: Aw, I\'d love to, but I\'ve got a lot of work. How about tomorrow?\nA: Tomorrow works! What time?\nB: 7?\nA: Great, 7 it is. See you then!',
      '"Aw" softens the decline.',
      [
        { target: 'I\'d love to, but …', english: 'reluctant decline' },
        { target: 'How about [time/day]?', english: 'counter-proposal' },
        { target: '[time] it is!', english: 'confirm new time' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'text invitation template',
      'Use this for a text/email invite.',
      'sentence',
      'Hey [name], want to [activity] on [day]? Maybe at [time]? [Place]? Let me know!',
      '[name] · [activity] · [day] · [time] · [place].',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write a 3–4 sentence text invitation. Include day, time, place, activity.',
      'sentence',
      'Example: Hey Sarah, want to grab coffee on Saturday? Maybe at 2 PM at the new cafe downtown? Let me know!',
      'Check: greeting + activity + time + place + closing.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Punctuality matters',
      'Western timing norms',
      'English-speaking cultures generally value punctuality. Arrive within 5 minutes of the agreed time for social plans; 0 minutes for business meetings.',
      'sentence',
      'If late, text early: "Running 10 min late, sorry!"',
      'Some cultures accept 15+ minute leeway; English-speaking ones do not.',
      [
        { target: 'on time', english: 'exactly when agreed' },
        { target: 'a few minutes late', english: 'usually acceptable for social' },
        { target: 'running late', english: 'common phrase for delay' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Confirming plans',
      '"Still on for …?"',
      'A day before, it\'s common to confirm: "Still on for tomorrow at 2?" Prevents missed connections.',
      'sentence',
      'Hey, still on for tomorrow at 2 PM?',
      'Casual but expected, especially for week-old plans.',
      null, [ACT.culture],
    ),

    createContentItem(
      'Task: Set up a study session',
      'consolidation task',
      'Roleplay: Invite a classmate to study Saturday. Use casual invitation, accept/decline, confirm time + place.',
      'conversation',
      'You: Hey [name], want to study together this weekend?\nClassmate: Sure! When works?\nYou: [propose time + place]\nClassmate: [accept or decline + counter]\nYou: [confirm or re-propose]\nClassmate: See you then!',
      'AI tutor will play the classmate.',
      [
        { target: 'Want to + verb?', english: 'casual invite' },
        { target: 'When works for you?', english: 'open-ended time' },
        { target: 'How about [time]?', english: 'propose time' },
        { target: 'See you then!', english: 'confirm' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
