// Level 2 Adult Unit 9 — Weekend / Small Talk (English)
// Functions: small talk, weekend recaps, hobbies, casual conversation.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2au9-orientation',
  pronunciation: 'en-l2au9-pronunciation',
  vocabularyHobbies: 'en-l2au9-vocab-hobbies',
  vocabularyTopics: 'en-l2au9-vocab-topics',
  grammarSmallTalk: 'en-l2au9-grammar-smalltalk',
  grammarShareReturn: 'en-l2au9-grammar-share',
  reading: 'en-l2au9-reading',
  listening: 'en-l2au9-listening',
  writing: 'en-l2au9-writing',
  culture: 'en-l2au9-culture',
  task: 'en-l2au9-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Open small talk with coworkers (weather, weekend, news).', 'Recap your weekend in 2-3 sentences.', 'Ask follow-up questions naturally.', 'Avoid taboo topics (politics, salary, religion at first).'],
    task: 'Picture chatting with your coworkers on Monday morning at the coffee machine.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Small-talk rhythm',
    goals: ['Use rising intonation for friendly questions.', 'Reduce "How was your weekend?" → /haʊ wəz jər ˈwiːkˌɛnd/.', 'Casual: "How\'d the weekend go?".'],
    task: 'Read 3 small-talk phrases naturally.' },
  { id: ACT.vocabularyHobbies, section: 'Vocabulary I', title: 'Hobbies + activities',
    goals: ['Use hiking, biking, gaming, reading, cooking, gardening, working out, brunch, road trip.'],
    task: 'List 5 hobbies.' },
  { id: ACT.vocabularyTopics, section: 'Vocabulary II', title: 'Safe small-talk topics',
    goals: ['Weather, weekend plans, sports, food, travel, pets, kids/family.', 'AVOID at first: politics, salary, religion, relationships.'],
    task: 'List 5 safe topics.' },
  { id: ACT.grammarSmallTalk, section: 'Grammar I', title: 'Small-talk openers',
    goals: ['"How was your weekend?" / "How\'d the weekend go?"', '"Doing anything fun tonight?" / "Got plans?"', '"Did you catch the game?"'],
    task: 'Open 3 small-talk conversations.' },
  { id: ACT.grammarShareReturn, section: 'Grammar II', title: 'Sharing + returning',
    goals: ['Share: 2-3 sentences max.', 'Return the question: "How about you?" / "And you?"', 'Follow up: "Oh nice!" / "That sounds great" / "How was it?"'],
    task: 'Practice 3 share-and-return exchanges.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'Coffee break chats',
    goals: ['Read example weekend recaps.'],
    task: 'Identify what made each chat work.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Coffee machine chat',
    goals: ['Follow a Monday-morning chat.'],
    task: 'Reproduce with your own weekend.' },
  { id: ACT.writing, section: 'Writing', title: 'Slack water-cooler message',
    goals: ['Write a 3-line "fun fact" / weekend share in #random.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US/UK small-talk norms',
    goals: ['Know small talk is expected in US offices, valued in UK.', 'Know weather (UK), sports (US), weekend (both) are universal.', 'Know what NOT to ask.'],
    task: 'Compare with your country.' },
  { id: ACT.task, section: 'Task', title: 'Monday-morning chat',
    goals: ['Open + share + return + follow-up + exit.'],
    task: 'Roleplay a 3-minute coffee-machine chat.' },
];

const lesson = {
  title: 'Level 2 (Workplace) · Unit 9: How was your weekend? — Small Talk',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'small-talk-opener-en', label: 'Opening small talk', goal: 'Use "How was your weekend?".' },
    { id: 'sharing-return-en', label: 'Sharing + returning', goal: 'Use "How about you?".' },
    { id: 'follow-up-en', label: 'Follow-up', goal: 'Use "Oh nice!" / "That sounds great".' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'small talk', 'By end: open small talk, recap a weekend, return questions, exit politely.', 'word', 'Functions: open · share · return · follow-up · exit.', 'Five small-talk micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Monday coffee', 'You\'re making coffee in the office kitchen Monday morning. Sarah from marketing walks in. You exchange a quick weekend chat — fast, friendly, then back to work.', 'word', 'Sarah: "Min-su! How was your weekend?" — You: "Pretty good — I went hiking on Sunday. You?"', 'Office coffee-machine chat.', null, [ACT.orientation]),

    createContentItem('"How was your weekend?" /haʊ wəz jər ˈwiːkˌɛnd/', '/haʊ wəz jər ˈwiːkˌɛnd/', 'Reduce "your" to /jər/; rising tone.', 'word', 'How was your weekend? ↗', 'Universal Monday opener.', null, [ACT.pronunciation]),
    createContentItem('"How\'d the weekend go?" /haʊd ðə ˈwiːkˌɛnd ɡoʊ/', '/haʊd ðə ˈwiːkˌɛnd ɡoʊ/', 'Casual contraction "How did" → "How\'d".', 'word', 'How\'d the weekend go?', 'Slightly more casual.', null, [ACT.pronunciation]),
    createContentItem('"Got plans?" /ɡɒt plænz/', '/ɡɒt plænz/', 'Dropped subject: "[Have you] got plans?".', 'word', 'Got plans for the weekend?', 'Very casual Friday afternoon.', null, [ACT.pronunciation]),

    createContentItem('hiking', '/ˈhaɪkɪŋ/', 'walking trails', 'word', 'I went hiking on Sunday.', 'Popular US outdoor activity.', null, [ACT.vocabularyHobbies]),
    createContentItem('biking / cycling', '/ˈbaɪkɪŋ/ /ˈsaɪklɪŋ/', 'bicycle riding', 'word', 'I went biking on the trails.', 'Both common.', null, [ACT.vocabularyHobbies]),
    createContentItem('gaming', '/ˈɡeɪmɪŋ/', 'playing video games', 'word', 'I was gaming all weekend.', 'Acceptable hobby at work now.', null, [ACT.vocabularyHobbies]),
    createContentItem('working out / gym', '/ˈwɜːrkɪŋ aʊt/', 'exercising', 'word', 'I hit the gym Saturday morning.', '"Hit the gym" — common phrase.', null, [ACT.vocabularyHobbies]),
    createContentItem('brunch', '/brʌntʃ/', 'late breakfast/lunch combo', 'word', 'We had brunch at this new spot.', 'Weekend social ritual.', null, [ACT.vocabularyHobbies]),
    createContentItem('road trip', '/roʊd trɪp/', 'long drive vacation', 'word', 'We did a road trip to Yosemite.', 'Classic US weekend.', null, [ACT.vocabularyHobbies]),
    createContentItem('binge-watching', '/bɪndʒ ˈwɒtʃɪŋ/', 'TV marathon', 'word', 'I binge-watched the new season.', 'Modern weekend default.', null, [ACT.vocabularyHobbies]),
    createContentItem('chilling / chillin\'', '/ˈtʃɪlɪŋ/', 'relaxing', 'word', 'Just chilling at home.', 'Very casual.', null, [ACT.vocabularyHobbies]),

    createContentItem('weather', '/ˈwɛðər/', 'safest of all topics (esp UK)', 'word', 'Beautiful weather today!', 'UK national pastime.', null, [ACT.vocabularyTopics]),
    createContentItem('sports', '/spɔːrts/', 'safe US topic', 'word', 'Did you catch the Giants game?', 'Default US small talk.', null, [ACT.vocabularyTopics]),
    createContentItem('travel', '/ˈtrævəl/', 'recent trips', 'word', 'Have you been to Iceland?', 'Get-to-know-you topic.', null, [ACT.vocabularyTopics]),
    createContentItem('food / restaurants', '/fuːd/', 'recent meals', 'word', 'Tried a new ramen spot Saturday.', 'Always works.', null, [ACT.vocabularyTopics]),
    createContentItem('pets', '/pɛts/', 'dogs / cats', 'word', 'I got a puppy last month!', 'Universally welcome.', null, [ACT.vocabularyTopics]),
    createContentItem('AVOID: politics / salary / religion', '/əˈvɔɪd/', 'taboo first-meeting topics', 'word', 'Don\'t ask politics in week 1.', 'Wait until you know someone well.', null, [ACT.vocabularyTopics]),

    createContentItem(
      'Small-talk openers',
      'standard phrases',
      'Universal openers.',
      'sentence',
      'How was your weekend? — Got plans tonight? — Doing anything fun this weekend? — Did you catch the game last night? — Crazy weather we\'re having!',
      'Match by time of week: Monday = weekend recap; Friday = weekend ahead.',
      [
        { target: 'How was your weekend?', english: 'Monday standard' },
        { target: 'Got plans for the weekend?', english: 'Friday standard' },
        { target: 'Did you catch + N?', english: 'sports / show' },
        { target: 'Crazy weather!', english: 'safe universal' },
      ],
      [ACT.grammarSmallTalk],
    ),
    createContentItem(
      'Share + return',
      'reciprocity rule',
      'Share briefly, then return the question.',
      'sentence',
      'Pretty good — went hiking on Sunday. How about you? — Same old, just chilling. You? — A bit hectic — friends in town. And you?',
      '2-3 sentences max, then return question = "How about you?" / "You?".',
      [
        { target: 'share 2-3 sentences', english: 'don\'t monologue' },
        { target: 'How about you?', english: 'standard return' },
        { target: 'And you?', english: 'shorter return' },
        { target: 'Same old', english: 'when nothing special happened' },
      ],
      [ACT.grammarShareReturn],
    ),
    createContentItem(
      'Follow-up phrases',
      'show interest',
      'Brief reactions that keep the conversation flowing.',
      'sentence',
      'Oh nice! — That sounds great! — How was it? — No way! — Sounds fun. — Oh man, that\'s a lot.',
      'These are quick — don\'t take over.',
      [
        { target: 'Oh nice! / Sounds great!', english: 'positive reaction' },
        { target: 'How was it?', english: 'open follow-up' },
        { target: 'No way! / Wow!', english: 'surprise' },
        { target: 'Oh man, that\'s a lot', english: 'sympathy / acknowledge' },
      ],
      [ACT.grammarShareReturn],
    ),
    createContentItem(
      'Polite exit',
      'wrap up gracefully',
      'Standard phrases to leave a chat.',
      'sentence',
      'Anyway, better get back to it. — Catch you later! — Have a good one. — Talk to you soon.',
      'Always exit on a positive note. No need to explain.',
      [
        { target: 'Anyway, better get back to it', english: 'reason to leave' },
        { target: 'Catch you later', english: 'casual exit' },
        { target: 'Have a good one', english: 'standard goodbye' },
      ],
      [ACT.grammarShareReturn],
    ),

    createContentItem(
      'Sample weekend recaps',
      'reading practice',
      'Read these short recaps.',
      'sentence',
      'A: "Pretty quiet — caught up on sleep and binge-watched the new Netflix series. Loved it. You?"\nB: "Crazy busy — friends from college were in town, did brunch on Saturday and a Giants game Sunday. So tired."\nC: "Took my dog hiking in Marin on Sunday. Beautiful weather. You?"',
      'Each: 2-3 sentences + return question.',
      [
        { target: '2-3 sentences max', english: 'brief' },
        { target: 'concrete verb + noun', english: 'specific' },
        { target: 'You? / And you?', english: 'return' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Coffee-machine chat',
      'Monday morning',
      'Classic Monday-morning recap.',
      'conversation',
      'Sarah: Min-su! How was your weekend?\nYou: Pretty good — went hiking up Mt. Tam on Sunday. The fog cleared at the top. You?\nSarah: Oh nice! Mine was hectic — friends from out of town. Did brunch on Saturday and saw the new Marvel movie.\nYou: Oh, how was it?\nSarah: Not bad — fun if you like Marvel, skip if you don\'t.\nYou: Got it. Anyway, better get back to my inbox. Catch you later!\nSarah: Have a good one!',
      'Open + share + return + follow-up + exit.',
      [
        { target: 'How was your weekend?', english: 'opener' },
        { target: 'went hiking … fog cleared at top', english: 'concrete share' },
        { target: 'You?', english: 'return' },
        { target: 'Oh nice! / Oh, how was it?', english: 'follow-up' },
        { target: 'better get back to my inbox / catch you later', english: 'exit' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Slack #random message',
      'writing model',
      'Casual share.',
      'sentence',
      'Took the dog on his first beach trip yesterday — he was scared of the waves but went full zoomies on the sand. 10/10 weekend ([photo]).',
      'Casual register: contractions, emojis, photo welcome.',
      [
        { target: 'concrete activity + reaction', english: 'tells a tiny story' },
        { target: 'casual contractions OK', english: 'register match' },
        { target: 'optional photo / link', english: 'multimedia welcome' },
      ],
      [ACT.writing],
    ),

    createContentItem(
      'US/UK small-talk norms',
      'cultural overview',
      'US: small talk expected at work — silence = rudeness. Topics: sports, weekend, weather. UK: weather is king; understated tone. Both: avoid politics, salary, religion, relationships until you know someone. Australia: very casual, may even include light banter quickly.',
      'sentence',
      'In the UK, a 5-minute weather discussion is socially complete.',
      'Small talk lubricates Western workplaces — skip it at your reputational peril.',
      [
        { target: 'US: silence is rude', english: 'expect chat' },
        { target: 'UK: weather is universal', english: 'safe topic' },
        { target: 'AVOID politics / salary / religion / relationships at first', english: 'taboo for new acquaintances' },
        { target: 'AU: casual + banter', english: 'quick to joke' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Monday-morning chat',
      'consolidation task',
      'AI tutor plays a coworker. Have a 3-minute coffee-machine chat.',
      'conversation',
      'Tutor: Hey! How was your weekend?\nYou: [2-3 sentence share + return]\nTutor: [share + follow-up]\nYou: [follow-up + brief comment]\nTutor: [comment]\nYou: [polite exit]\nTutor: [farewell]',
      'AI tutor plays coworker.',
      [
        { target: 'How was your weekend?', english: 'open' },
        { target: 'share 2-3 sentences', english: 'concrete' },
        { target: 'You?', english: 'return' },
        { target: 'Oh nice / How was it?', english: 'follow-up' },
        { target: 'Better get back to it / Catch you later', english: 'exit' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
