// Level 2 Adult Unit 12 — Housing Search (English)
// Functions: apartment search, lease negotiation, deposit, move-in/out.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2au12-orientation',
  pronunciation: 'en-l2au12-pronunciation',
  vocabularyListing: 'en-l2au12-vocab-listing',
  vocabularyLease: 'en-l2au12-vocab-lease',
  grammarTouring: 'en-l2au12-grammar-touring',
  grammarLease: 'en-l2au12-grammar-lease',
  reading: 'en-l2au12-reading',
  listening: 'en-l2au12-listening',
  writing: 'en-l2au12-writing',
  culture: 'en-l2au12-culture',
  task: 'en-l2au12-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Read a US/UK apartment listing.', 'Tour an apartment and ask the right questions.', 'Sign a lease and understand key clauses.', 'Get your security deposit back at move-out.'],
    task: 'Picture searching for an apartment near your new job in San Francisco.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Housing terms',
    goals: ['Pronounce "studio" /ˈstjuːdioʊ/, "1-bedroom" /wʌn ˈbɛdˌruːm/.', '"Utilities included" /juːˈtɪlətiz ɪnˈkluːdɪd/.', '"Square feet" /skwɛər fiːt/ — quick.'],
    task: 'Read 3 listing phrases aloud.' },
  { id: ACT.vocabularyListing, section: 'Vocabulary I', title: 'Listing vocabulary',
    goals: ['Use studio, 1-bedroom, 1-bath, square feet (sqft), walk-up, elevator, in-unit laundry, pet-friendly.'],
    task: 'Decode 3 listing abbreviations.' },
  { id: ACT.vocabularyLease, section: 'Vocabulary II', title: 'Lease + move-in vocabulary',
    goals: ['Use lease, sublet, deposit, application fee, first/last month\'s rent, utilities, move-in date, walkthrough.'],
    task: 'Explain 5 lease terms.' },
  { id: ACT.grammarTouring, section: 'Grammar I', title: 'Apartment-tour questions',
    goals: ['"How much is rent?" / "Are utilities included?"', '"Is there parking?" / "Is the building pet-friendly?"', '"How\'s the neighborhood at night?"'],
    task: 'Write 5 tour questions.' },
  { id: ACT.grammarLease, section: 'Grammar II', title: 'Lease + negotiation',
    goals: ['"Would you consider waiving the + fee?"', '"Could we negotiate on + N?"', '"What\'s your standard lease term?"'],
    task: 'Negotiate one lease term.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'Apartment listing',
    goals: ['Read a Zillow-style listing.'],
    task: 'Identify must-know details.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Apartment tour',
    goals: ['Follow a tour conversation.'],
    task: 'Reproduce with your own preferences.' },
  { id: ACT.writing, section: 'Writing', title: 'Application email',
    goals: ['Write a 5-line application email to a landlord.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US/UK rental market',
    goals: ['Know rent stress (US: 30% income recommended, often 40-50% in big cities).', 'Know application requirements (credit check, income proof at 2.5-3x rent).', 'Know roommate culture and Craigslist/SpareRoom apps.'],
    task: 'Compare with housing in your country.' },
  { id: ACT.task, section: 'Task', title: 'Apartment tour',
    goals: ['Combine listing + tour questions + negotiation + application.'],
    task: 'Roleplay touring an apartment and applying.' },
];

const lesson = {
  title: 'Level 2 (Workplace) · Unit 12: Looking for a place — Housing Search',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'tour-questions-en', label: 'Tour questions', goal: 'Use "How much is rent?" / "Are utilities included?".' },
    { id: 'lease-negotiation-en', label: 'Lease negotiation', goal: 'Use "Would you consider + V-ing?".' },
    { id: 'application-email-en', label: 'Application email', goal: 'Concise self-intro with stable details.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'housing search', 'By end: read listings, tour apartments, sign a lease, get deposit back.', 'word', 'Functions: read · tour · negotiate · apply.', 'Four housing micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'SF apartment hunt', 'You just got a job offer in San Francisco starting in 6 weeks. You\'re searching for a 1-bedroom under $2,800/month. Today you\'re touring 3 places and need to ask the right questions before applying.', 'word', 'You: "How much is rent, are utilities included, and what\'s the typical move-in cost?"', 'Standard SF apartment hunt.', null, [ACT.orientation]),

    createContentItem('"studio" /ˈstjuːdioʊ/', '/ˈstjuːdioʊ/', 'Stress on syllable 1.', 'word', 'I\'m looking at a studio downtown.', 'One open room + bath.', null, [ACT.pronunciation]),
    createContentItem('"1-bedroom" /wʌn ˈbɛdˌruːm/', '/wʌn ˈbɛdˌruːm/', 'Compound: stress on "bed".', 'word', 'A 1-bedroom in this area is $2,800.', 'Listings written "1BR" / "1B/1B".', null, [ACT.pronunciation]),
    createContentItem('"utilities included" /juːˈtɪlətiz ɪnˈkluːdɪd/', '/juːˈtɪlətiz ɪnˈkluːdɪd/', 'Key phrase when comparing prices.', 'word', 'Are utilities included in rent?', 'Critical: water + electric + gas + heat + internet.', null, [ACT.pronunciation]),

    createContentItem('studio', '/ˈstjuːdioʊ/', 'one-room apartment + bath', 'word', 'A studio is cheaper than a 1-bedroom.', 'Cheapest layout.', null, [ACT.vocabularyListing]),
    createContentItem('1-bedroom / 1-bath (1B/1B)', '/wʌn ˈbɛdˌruːm/', 'standard listing format', 'word', '1B/1B in Brooklyn = $3,500.', 'B = bed; Ba = bath.', null, [ACT.vocabularyListing]),
    createContentItem('square feet / sqft', '/skwɛər fiːt/', 'apartment size', 'word', '650 sqft for $2,800.', '1 sqft = 0.09 sqm.', null, [ACT.vocabularyListing]),
    createContentItem('walk-up vs elevator building', '/wɔːk ʌp/', 'no elevator vs has elevator', 'word', 'Walk-up = cheaper but no elevator.', 'Important for high floors.', null, [ACT.vocabularyListing]),
    createContentItem('in-unit laundry / shared laundry', '/ɪn ˈjuːnɪt ˈlɔːndri/', 'washer-dryer in apartment vs shared', 'word', 'In-unit laundry is a luxury in NYC.', 'Premium amenity.', null, [ACT.vocabularyListing]),
    createContentItem('pet-friendly', '/pɛt ˈfrɛndli/', 'allows pets', 'word', 'This building is pet-friendly with a $500 pet deposit.', 'Often has extra deposit + monthly fee.', null, [ACT.vocabularyListing]),
    createContentItem('utilities (water / gas / electric / internet)', '/juːˈtɪlətiz/', 'monthly services', 'word', 'Utilities run about $200/month.', 'Sometimes included, often separate.', null, [ACT.vocabularyListing]),
    createContentItem('parking / garage / street', '/ˈpɑːrkɪŋ/', 'parking options', 'word', 'Parking is +$200/month, garage only.', 'Street parking free, but no guarantee.', null, [ACT.vocabularyListing]),
    createContentItem('neighborhood / safe area', '/ˈneɪbərhʊd/', 'where the building is', 'word', 'The neighborhood is quiet at night.', 'Ask current residents; check crime maps.', null, [ACT.vocabularyListing]),

    createContentItem('lease', '/liːs/', 'rental contract', 'word', 'I signed a 12-month lease.', 'Verb + noun.', null, [ACT.vocabularyLease]),
    createContentItem('sublet / sublease', '/ˈsʌbˌlɛt/ /ˈsʌbˌliːs/', 'rent from a current tenant', 'word', 'I\'m subletting for 3 months.', 'Often furnished, short-term.', null, [ACT.vocabularyLease]),
    createContentItem('security deposit / deposit', '/sɪˈkjʊərəti dɪˈpɒzɪt/', 'refundable upfront', 'word', 'Deposit is one month\'s rent.', 'Returned at move-out (minus damage).', null, [ACT.vocabularyLease]),
    createContentItem('application fee', '/ˌæplɪˈkeɪʃən fiː/', 'non-refundable processing fee', 'word', 'Application fee is $50 per applicant.', 'Covers credit check.', null, [ACT.vocabularyLease]),
    createContentItem('first / last month\'s rent', '/fɜːrst lɑːst mʌnθs rɛnt/', 'common move-in cost', 'word', 'Move-in = first month + last month + deposit.', 'Common combination.', null, [ACT.vocabularyLease]),
    createContentItem('move-in / move-out date', '/muːv ɪn/ /muːv aʊt/', 'lease start/end dates', 'word', 'Move-in is June 1.', 'Lease defines both.', null, [ACT.vocabularyLease]),
    createContentItem('walkthrough', '/ˈwɔːkˌθruː/', 'inspection at move-in/out', 'word', 'Do a walkthrough with the landlord — document everything.', 'Take photos!', null, [ACT.vocabularyLease]),
    createContentItem('credit check / proof of income', '/ˈkrɛdɪt tʃɛk/', 'application requirements', 'word', 'Bring your last 2 pay stubs as proof of income.', 'Often 2.5-3x rent required.', null, [ACT.vocabularyLease]),

    createContentItem(
      'Apartment tour questions',
      'must-ask list',
      'Questions to ask during every tour.',
      'sentence',
      'How much is rent? — Are utilities included? — What\'s the move-in cost? — How long is the lease? — Is the building pet-friendly? — Is there in-unit laundry? — How\'s the neighborhood at night? — When can I move in?',
      'Ask them all — landlords answer freely during tours.',
      [
        { target: 'How much is rent?', english: 'core question' },
        { target: 'Are utilities included?', english: 'true cost' },
        { target: 'What\'s the move-in cost?', english: 'upfront total' },
        { target: 'How long is the lease?', english: 'term length' },
        { target: 'How\'s the neighborhood at night?', english: 'safety check' },
      ],
      [ACT.grammarTouring],
    ),
    createContentItem(
      'Lease negotiation',
      'gentle pushback',
      'Most US landlords have a little flex.',
      'sentence',
      'Would you consider waiving the application fee for multiple applicants? — Could we negotiate on the move-in date? — Is there any flexibility on the deposit if I provide a co-signer?',
      'Frame as collaborative; ask once, then accept the answer.',
      [
        { target: 'Would you consider + V-ing?', english: 'soft ask' },
        { target: 'Could we negotiate on + N?', english: 'identify flex' },
        { target: 'Is there flexibility on + N?', english: 'open question' },
      ],
      [ACT.grammarLease],
    ),

    createContentItem(
      'Apartment listing',
      'reading practice',
      'Read this Zillow-style listing.',
      'sentence',
      'SUNNY 1B/1B, MISSION DISTRICT — $2,750/mo\n650 sqft · 3rd floor walk-up · in-unit laundry · pet-friendly (deposit + $50/mo)\nUtilities: water + trash included; tenant pays electric + internet (~$120/mo).\nLease: 12 months · Deposit: 1 month\'s rent · Application fee: $40\nAvailable: June 1, 2024\nIncome requirement: 2.5x rent. Credit check required.',
      'Standard urban listing.',
      [
        { target: '$2,750/mo, 650 sqft, 3rd floor walk-up', english: 'core info' },
        { target: 'utilities: water + trash included', english: 'partial' },
        { target: 'tenant pays electric + internet (~$120)', english: 'true cost' },
        { target: 'Lease: 12 months, Deposit: 1 month', english: 'lease terms' },
        { target: 'Income: 2.5x rent, credit check', english: 'application requirements' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Apartment tour',
      'landlord conversation',
      'Tour a 1-bedroom in San Francisco.',
      'conversation',
      'Landlord: Welcome! Let me show you around. This is the living area, 650 sqft total.\nYou: Nice and bright. How much is rent?\nLandlord: $2,750. First month + deposit due at signing.\nYou: Are utilities included?\nLandlord: Water and trash, yes. You pay electric and internet — about $120/month combined.\nYou: How long is the lease?\nLandlord: 12 months. Some flexibility on month-to-month after.\nYou: Is in-unit laundry included? I see a washer-dryer.\nLandlord: Yes, included.\nYou: How\'s the neighborhood at night?\nLandlord: Pretty quiet — mostly young professionals. There\'s a small park down the street.\nYou: Would you consider waiving the $40 application fee?\nLandlord: Unfortunately no, but the deposit is just one month\'s rent — that\'s competitive for the area.\nYou: Fair enough. I\'d like to apply.',
      'Standard tour Q&A + small negotiation.',
      [
        { target: 'How much is rent? + Are utilities included?', english: 'core Q' },
        { target: 'How long is the lease?', english: 'term Q' },
        { target: 'How\'s the neighborhood at night?', english: 'safety Q' },
        { target: 'Would you consider waiving + fee?', english: 'soft negotiation' },
        { target: 'I\'d like to apply', english: 'commit' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Application email',
      'writing model',
      'Initial application email to a landlord.',
      'sentence',
      'Subject: Application — 1B/1B Mission District, June move-in\n\nHi Sarah,\n\nI\'m applying for the 1B/1B at 123 Valencia St (listed at $2,750/mo). I\'m a software engineer starting at TechCorp on June 1; gross income is $130K/year (about 4x rent), and I have an 800+ credit score. I\'ve attached my last 2 pay stubs, offer letter, and rental references. Move-in date: flexible from May 25 to June 5. Please let me know what other documentation you need.\n\nThanks,\nMin-su Kim',
      'Concise + stable + documented.',
      [
        { target: 'Subject: Application — unit + move-in', english: 'specific subject' },
        { target: 'I\'m a + role + starting at + company on + date', english: 'employment proof' },
        { target: 'gross income is $X (about Nx rent)', english: 'income ratio' },
        { target: 'credit score, pay stubs, offer letter, references', english: 'standard docs' },
        { target: 'Move-in date: flexible from X to Y', english: 'date flexibility' },
      ],
      [ACT.writing],
    ),

    createContentItem(
      'US/UK rental market',
      'cultural overview',
      'US: rent 30% of income recommended; often 40-50% in big cities (NYC, SF). Application: credit check + 2.5-3x rent income + references. Standard upfront cost = first month + last month + deposit + app fee (sometimes 3-4 months rent total!). UK: assured shorthold tenancy 6-12 months, often furnished, deposit 1 month\'s rent (held in govt-protected scheme).',
      'sentence',
      'Moving into an SF or NYC apartment can require $10,000+ upfront.',
      'Roommate culture is huge in expensive cities; Craigslist/SpareRoom are go-to apps.',
      [
        { target: 'rent 30% of income (recommended)', english: 'budget rule' },
        { target: 'credit score 700+ ideal', english: 'application standard' },
        { target: 'first + last + deposit + app fee', english: 'move-in math' },
        { target: 'Craigslist / SpareRoom / Zillow', english: 'rental search' },
        { target: 'roommate culture in expensive cities', english: 'cost-sharing' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Apartment tour',
      'consolidation task',
      'AI tutor plays a landlord. Tour an apartment and decide whether to apply.',
      'conversation',
      'Tutor: Welcome! Let me show you around.\nYou: [3 tour questions]\nTutor: [answers]\nYou: [1 negotiation question]\nTutor: [response]\nYou: [decide + close]',
      'AI tutor plays landlord.',
      [
        { target: 'How much is rent + utilities + lease?', english: 'core Qs' },
        { target: 'How\'s the neighborhood at night?', english: 'safety Q' },
        { target: 'Would you consider + V-ing?', english: 'negotiation' },
        { target: 'I\'d like to apply / I need to think about it', english: 'decide' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
