// Level 3 Cluster 1 — English Connectors
// Patterns: and / so + because / but + although / then + therefore / however.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l3c1-orientation',
  patternsOverview: 'en-l3c1-patterns',
  andSo: 'en-l3c1-andso',
  becauseSince: 'en-l3c1-because',
  butYet: 'en-l3c1-butyet',
  althoughEvenThough: 'en-l3c1-although',
  thereforeHowever: 'en-l3c1-conjadv',
  comparison: 'en-l3c1-comparison',
  reading: 'en-l3c1-reading',
  speaking: 'en-l3c1-speaking',
  writing: 'en-l3c1-writing',
  task: 'en-l3c1-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Use 5 layers of English connectors fluently.', 'Distinguish coordinating (and, but, so) from subordinating (because, although) connectors.', 'Use conjunctive adverbs (however, therefore, moreover) with correct punctuation.'],
    task: 'Picture writing an analysis paragraph for class — your sentences need to chain ideas naturally and signal logical relationships.' },
  { id: ACT.patternsOverview, section: 'Patterns', title: 'Connector inventory',
    goals: ['Recognize coordinating, subordinating, and adverbial connectors by function.'],
    task: 'Match each connector to its function.' },
  { id: ACT.andSo, section: 'Connector 1', title: '"and / so" — addition + result',
    goals: ['Use "and" for parallel/sequence.', 'Use "so" for result (comma before, casual).'],
    task: 'Make 3 "and" and 3 "so" sentences.' },
  { id: ACT.becauseSince, section: 'Connector 2', title: '"because / since / as" — cause',
    goals: ['Use "because" — direct cause.', 'Use "since / as" — slightly softer, given info.'],
    task: 'Make 3 cause sentences.' },
  { id: ACT.butYet, section: 'Connector 3', title: '"but / yet" — contrast',
    goals: ['Use "but" — direct contrast.', 'Use "yet" — surprising/contradictory contrast.'],
    task: 'Make 3 contrast sentences.' },
  { id: ACT.althoughEvenThough, section: 'Connector 4', title: '"although / even though / despite" — concession',
    goals: ['Use "although / even though" + clause.', 'Use "despite / in spite of" + N/V-ing.', 'No "but" after "although" — choose one.'],
    task: 'Make 3 concession sentences.' },
  { id: ACT.thereforeHowever, section: 'Connector 5', title: '"therefore / however / moreover" — adverbial connectors',
    goals: ['Use ; before + , after: ";therefore," / ";however,".', 'Use sentence-initial with comma: "However, …".'],
    task: 'Punctuate 3 adverbial-connector sentences.' },
  { id: ACT.comparison, section: 'Comparison', title: 'When to use which',
    goals: ['Pick the right connector by formality + relationship.'],
    task: 'Disambiguate 5 examples.' },
  { id: ACT.reading, section: 'Reading', title: 'Paragraph with all 5 layers',
    goals: ['Read an analytical paragraph and identify each connector.'],
    task: 'Label each connector.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Speaking with connectors',
    goals: ['Produce flowing speech using all 5 connectors.'],
    task: 'Tell a 4-step story.' },
  { id: ACT.writing, section: 'Writing', title: 'Multi-clause paragraph',
    goals: ['Write a 5-6 sentence paragraph using all 5 connectors with correct punctuation.'],
    task: 'Write your own.' },
  { id: ACT.task, section: 'Task', title: 'Chained debate',
    goals: ['Combine all 5 connectors in extended speech.'],
    task: 'Debate a topic with the AI tutor.' },
];

const lesson = {
  title: 'Level 3 · Cluster 1: Connectors — and / so / but / although / however',
  category: 'daily-life',
  difficulty: 'advanced',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'grammar',
  activities,
  expressionPractice: [
    { id: 'using-connector-en', label: 'Using a connector', goal: 'Pick the right connector for "and / so / but / although / however" in context.' },
    { id: 'concession-en', label: 'Concession', goal: 'Use "although / even though" without doubling with "but".' },
    { id: 'cause-effect-en', label: 'Cause-effect', goal: 'Use "because / so" correctly without overlap.' },
  ],
  relatedPools: ['topic-grammar'],
  content: [
    createContentItem('Lesson goal', 'connectors', 'By end: chain ideas with 5 layers of English connectors.', 'word', 'Functions: add · cause · contrast · concede · pivot.', 'Five connector micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'analysis paragraph', 'You\'re writing a class essay about climate policy. You need to balance evidence, contrast, and concession — all within one paragraph.', 'word', 'Example: "Carbon taxes work, but they hurt low-income households; therefore, rebates are essential. Although critics worry about administrative complexity, the data supports the approach."', 'A typical academic paragraph.', null, [ACT.orientation]),

    createContentItem('Coordinating vs subordinating', 'patterns', 'Coordinating (FANBOYS: for, and, nor, but, or, yet, so) — link equal clauses. Subordinating (because, although, since, while) — make one clause depend on another.', 'word', 'And, but, so → coordinating. Because, although → subordinating.', 'Critical distinction for punctuation + register.', null, [ACT.patternsOverview]),
    createContentItem('Conjunctive adverbs', 'patterns', 'However, therefore, moreover, furthermore, nonetheless — punctuate with ; before and , after when joining clauses.', 'word', 'I tried hard; however, I failed. → semicolon + comma.', 'Most common error: comma splice with "however".', null, [ACT.patternsOverview]),

    createContentItem(
      '"and" — addition / sequence',
      'parallel clauses',
      'Connect equal clauses with same subject (often) or related ideas.',
      'sentence',
      'I studied and slept. — She works in Seoul, and her husband works in Tokyo. — He woke up, brushed his teeth, and left for work.',
      'Comma before "and" when joining two independent clauses (Oxford comma optional in series).',
      [
        { target: 'S + V + and + V', english: 'same subject' },
        { target: 'S + V, and + S + V', english: 'two independent clauses' },
        { target: 'list: A, B, and C', english: 'series (Oxford comma optional)' },
      ],
      [ACT.andSo],
    ),
    createContentItem(
      '"so" — result',
      'cause → effect',
      'Show the second clause is the result of the first.',
      'sentence',
      'It was raining, so we stayed in. — She was tired, so she went to bed.',
      'Casual register. Always comma before "so" between clauses.',
      [
        { target: 'cause, so + result', english: 'standard' },
        { target: 'NOT: cause, so that + purpose', english: 'different: "so that" = in order to' },
      ],
      [ACT.andSo],
    ),

    createContentItem(
      '"because / since / as" — cause',
      'direct cause',
      'Three near-synonyms.',
      'sentence',
      'I stayed home because I was sick. (most direct) — Since you\'re here, can you help? (given info) — As I was walking, I saw a friend. (also "while").',
      '"Because" — direct cause. "Since" — when reason is already known/given. "As" — softer, often time-related.',
      [
        { target: 'because + S + V', english: 'most direct cause' },
        { target: 'since + S + V', english: 'given/known info' },
        { target: 'as + S + V', english: 'softer; can mean "while" too' },
      ],
      [ACT.becauseSince],
    ),
    createContentItem(
      '"because of / due to + N"',
      'cause + noun',
      'Use for nouns instead of clauses.',
      'sentence',
      'The flight was delayed because of the storm. — Due to traffic, I was late.',
      '"Because of" — casual. "Due to" — formal, often passive.',
      [
        { target: 'because of + N', english: 'casual cause' },
        { target: 'due to + N', english: 'formal cause' },
      ],
      [ACT.becauseSince],
    ),

    createContentItem(
      '"but / yet" — contrast',
      'direct contrast',
      'Show opposition between clauses.',
      'sentence',
      'It\'s cold, but I\'ll go anyway. — He\'s rich, yet unhappy.',
      '"But" — neutral; "yet" — surprising/contradictory.',
      [
        { target: 'X, but Y', english: 'standard contrast' },
        { target: 'X, yet Y', english: 'surprising contrast' },
        { target: 'NOT: "but" at sentence start in formal writing', english: 'OK casually' },
      ],
      [ACT.butYet],
    ),

    createContentItem(
      '"although / even though + clause"',
      'concession with clause',
      'Acknowledge a counterpoint, then push past it.',
      'sentence',
      'Although it was raining, we went hiking. — Even though she\'s tired, she keeps working.',
      'Never pair with "but" in the same sentence: NOT "Although it was raining, but we went". Choose ONE.',
      [
        { target: 'Although + S + V, S + V', english: 'concession clause' },
        { target: 'Even though + S + V', english: 'stronger concession' },
        { target: 'NEVER + "but" later', english: 'common error' },
      ],
      [ACT.althoughEvenThough],
    ),
    createContentItem(
      '"despite / in spite of + N/V-ing"',
      'concession with noun',
      'Use with a noun phrase, not a full clause.',
      'sentence',
      'Despite the rain, we went hiking. — In spite of being tired, she finished the project.',
      'Cannot take a full clause: NOT "Despite it was raining". Use "despite the fact that + S + V" for clausal feel.',
      [
        { target: 'despite + N / V-ing', english: 'concession with noun' },
        { target: 'in spite of + N / V-ing', english: 'identical meaning' },
        { target: 'despite the fact that + S + V', english: 'clausal version' },
      ],
      [ACT.althoughEvenThough],
    ),

    createContentItem(
      '"however / therefore / moreover" — punctuation',
      'conjunctive adverbs',
      'When joining two clauses, use semicolon before and comma after.',
      'sentence',
      'I studied hard; however, I failed the exam. — She prepared thoroughly; therefore, she passed. — The plan is risky; moreover, it\'s expensive.',
      'Most common error: comma splice ("I studied hard, however, I failed" — wrong).',
      [
        { target: 'S + V; however, S + V', english: 'standard punctuation' },
        { target: 'However, + S + V', english: 'sentence-initial, comma' },
        { target: '...; therefore, ...', english: 'result' },
        { target: '...; moreover, ...', english: 'addition' },
      ],
      [ACT.thereforeHowever],
    ),
    createContentItem(
      'Conjunctive adverb meanings',
      'cheat sheet',
      'Map each to its connector function.',
      'sentence',
      'however = but (formal) — therefore = so (formal) — moreover = and (formal) — furthermore = moreover — nevertheless = but still — consequently = therefore — meanwhile = at the same time',
      'Use sparingly in speech; common in essays.',
      [
        { target: 'however', english: 'formal "but"' },
        { target: 'therefore / consequently', english: 'formal "so"' },
        { target: 'moreover / furthermore', english: 'formal "and"' },
        { target: 'nevertheless / nonetheless', english: 'formal "but still"' },
      ],
      [ACT.thereforeHowever],
    ),

    createContentItem(
      'When to use which',
      'register choice',
      'Pick by formality + length.',
      'sentence',
      'Casual chat: "I studied hard but I failed." — Email: "I studied hard, but I failed." — Essay: "Despite studying hard, I failed." — Academic: "I studied hard; however, the exam was beyond the scope of the syllabus."',
      'Casual → coordinating + short. Formal → subordinating + conjunctive adverbs.',
      [
        { target: 'casual: and/but/so', english: 'short coordinating' },
        { target: 'formal: although/despite + clause', english: 'subordinating' },
        { target: 'academic: however/therefore', english: 'conjunctive adverbs' },
      ],
      [ACT.comparison],
    ),

    createContentItem(
      'Sample paragraph',
      'reading practice',
      'Identify each connector.',
      'sentence',
      'Climate policy is contested. On one hand, carbon taxes reduce emissions efficiently, and economists across the political spectrum support them. On the other hand, they hit low-income families disproportionately; therefore, rebates are essential. Although critics complain about administrative complexity, evidence from Canada shows the rebate approach is viable. Because the climate challenge is urgent, delay is not an option. Despite the political risk, leaders must act now.',
      'All 5 connector types used.',
      [
        { target: 'and (coordinating: addition)', english: 'pair facts' },
        { target: 'therefore (conjunctive adverb: result)', english: 'consequence' },
        { target: 'although (subordinating: concession)', english: 'counterpoint' },
        { target: 'because (subordinating: cause)', english: 'reason' },
        { target: 'despite (preposition: concession)', english: 'noun-form concession' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Speaking with connectors',
      'extended turn',
      'Tell a 4-step story.',
      'sentence',
      'Last weekend I tried a new restaurant. The food was excellent, and the service was friendly. But the prices were high, so I won\'t go often. Although it\'s expensive, I\'ll definitely take my parents there. Despite the cost, the experience is worth it.',
      'Frame: setup + addition + contrast + concession + conclusion.',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Writing prompt',
      'analytical paragraph',
      'Write a 5-6 sentence paragraph on any topic. Use all 5 connector layers + correct punctuation.',
      'sentence',
      'Example: Remote work is here to stay. Many workers prefer flexibility, and productivity has held steady or risen. But isolation and burnout are real risks; therefore, hybrid models are gaining ground. Although some leaders push full return-to-office, the data favors flexibility. Despite ongoing debate, the trend is clear.',
      'Required: 1 coordinating (and/but/so), 1 cause (because/since), 1 concession (although/despite), 1 conjunctive adverb (however/therefore).',
      null, [ACT.writing],
    ),

    createContentItem(
      'Task: Chained debate',
      'consolidation task',
      'AI tutor takes one side. You take the other. 4 turns each, using connectors.',
      'conversation',
      'Tutor: AI will replace many jobs.\nYou: [agreement + concession with "although"]\nTutor: [counter]\nYou: [contrast + cause with "but" + "because"]\nTutor: [further point]\nYou: [conclude with "therefore" or "despite"]',
      'AI tutor plays your debate partner.',
      [
        { target: 'and / so', english: 'coordinating' },
        { target: 'because / since', english: 'cause' },
        { target: 'but / yet', english: 'contrast' },
        { target: 'although / despite', english: 'concession' },
        { target: 'however / therefore', english: 'adverbial pivot' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
