// Level 2 Unit 4 — Modern Relationships & Generational Norms (English)
// Grammar: "let alone / far from", "bound to / sure to", "whereas / while (contrast)",
// "have no choice but to / can't help + V-ing". Pronunciation: stress in argument tone.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2u4-orientation',
  vocabulary: 'en-l2u4-vocabulary',
  pronunciation: 'en-l2u4-pronunciation',
  grammar: 'en-l2u4-grammar',
  speaking: 'en-l2u4-speaking',
  readingSpeaking: 'en-l2u4-reading-speaking',
  listeningSpeaking: 'en-l2u4-listening-speaking',
  readingWriting: 'en-l2u4-reading-writing',
  culture: 'en-l2u4-culture',
  task: 'en-l2u4-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Voice frustration and predict outcomes confidently.', 'Use 4 intermediate patterns: let alone, bound to, whereas, have no choice but to.', 'Discuss generational and gender norms across cultures.'],
    task: 'Picture a friendly debate about modern dating norms — you need to disagree, predict, and contrast generations.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Attitudes, complaints, abilities',
    goals: ['Use attitude, complaint, ability, difference, gender, generation, expectation, stereotype.', 'Form -ish adjectives (childish, boyish, girlish, snobbish).'],
    task: 'Pick three -ish adjectives and use each.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Stress in argument tone',
    goals: ['Stress key contrast words: "bound to", "let alone", "whereas".', 'Use falling-then-rising contour for contrast clauses.'],
    task: 'Read three contrasting sentences with proper stress.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Argument and exception patterns',
    goals: ['"let alone + N/V" / "far from + V-ing" — far from doing X', '"be bound to / sure to + V" — surely will', '"whereas / while + S + V" — contrast', '"have no choice but to + V" / "can\'t help + V-ing" — cannot but'],
    task: 'Use each pattern once.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Complaining politely',
    goals: ['Voice a complaint with target grammar.'],
    task: 'Complain about a small frustration using "let alone".' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Comparing generations',
    goals: ['Read a generational comparison.', 'Discuss your reaction.'],
    task: 'Read and respond with your opinion.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Clashing opinions',
    goals: ['Listen to a complaint.', 'Argue your view politely.'],
    task: 'Defend an opinion about modern dating.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Opinion piece on a study',
    goals: ['Read an opinion piece.', 'Write a short analysis.'],
    task: 'Write three sentences analyzing a study.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Changing norms in US/UK/AU workplaces',
    goals: ['Understand "glass ceiling", "work-life balance", and shifting parental leave norms.', 'Compare with East Asian norms.'],
    task: 'Discuss one stereotype your country is moving past.' },
  { id: ACT.task, section: 'Task', title: 'Debate a generational difference',
    goals: ['Argue both sides using 4 patterns.'],
    task: 'Take one side of a friendly debate.' },
];

const lesson = {
  title: 'Level 2 · Unit 4: Modern Relationships & Generations',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'predicting-en', label: 'Predicting outcome', goal: 'Use "bound to / sure to + V".' },
    { id: 'expressing-dissatisfaction-en', label: 'Expressing dissatisfaction', goal: 'Use "let alone" / "far from + V-ing".' },
    { id: 'contrasting-groups-en', label: 'Contrasting two groups', goal: 'Use "whereas / while + S + V".' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'modern relationships', 'By end: discuss generational and gender differences, voice complaints, predict outcomes, contrast groups.', 'word', 'Functions: complain · predict · contrast · concede.', 'Four argument micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'dating-app debate', 'You\'re chatting with a classmate at Kumoh about modern dating apps. She thinks they\'re ruining real connection; you disagree. You need to make your case using contrast and prediction.', 'word', 'Friend: "Apps are bound to fail — they\'re too superficial." — You: "Whereas you see superficiality, I see opportunity."', 'A polite cross-generational debate.', null, [ACT.orientation]),

    createContentItem('attitude', '/ˈætɪtjuːd/', 'a settled way of thinking', 'word', 'His attitude toward work changed after the promotion.', 'Often paired with "toward".', null, [ACT.vocabulary]),
    createContentItem('stereotype', '/ˈstɛriətaɪp/', 'an oversimplified group image', 'word', 'Many gender stereotypes are outdated.', 'Verb: "stereotype". Adj: "stereotypical".', null, [ACT.vocabulary]),
    createContentItem('expectation', '/ˌɛkspɛkˈteɪʃən/', 'what is anticipated', 'word', 'Family expectations can be heavy.', 'Often plural.', null, [ACT.vocabulary]),
    createContentItem('generation', '/ˌdʒɛnəˈreɪʃən/', 'group born around same time', 'word', 'My generation grew up online.', 'Boomer, Gen X, Millennial, Gen Z, Gen Alpha.', null, [ACT.vocabulary]),
    createContentItem('gender role', '/ˈdʒɛndər roʊl/', 'expected behavior for a gender', 'word', 'Gender roles have shifted in the past 50 years.', '"Role" — what one is expected to do.', null, [ACT.vocabulary]),
    createContentItem('equality / inequality', '/ɪˈkwɒləti/ /ˌɪnɪˈkwɒləti/', 'sameness / unfairness', 'word', 'Pay equality is still a major issue.', 'Adj: equal, unequal.', null, [ACT.vocabulary]),
    createContentItem('childish', '/ˈtʃaɪldɪʃ/', 'immature (-ish)', 'word', 'Stop being so childish.', '-ish — slightly negative tone.', null, [ACT.vocabulary]),
    createContentItem('boyish / girlish', '/ˈbɔɪɪʃ/ /ˈɡɜːrlɪʃ/', 'youthful / feminine', 'word', 'He has a boyish charm.', '"Boyish" — often complimentary; "girlish" — neutral/feminine.', null, [ACT.vocabulary]),
    createContentItem('snobbish', '/ˈsnɒbɪʃ/', 'looking down on others', 'word', 'Don\'t be snobbish about your degree.', 'Also: "stuck-up".', null, [ACT.vocabulary]),
    createContentItem('judgmental', '/dʒʌdʒˈmɛntəl/', 'quick to criticize', 'word', 'Try not to be judgmental.', 'Common modern critique.', null, [ACT.vocabulary]),
    createContentItem('open-minded', '/ˌoʊpən ˈmaɪndɪd/', 'receptive to new ideas', 'word', 'My grandmother is surprisingly open-minded.', 'Opposite: "close-minded".', null, [ACT.vocabulary]),
    createContentItem('compromise', '/ˈkɒmprəmaɪz/', 'mutual concession', 'word', 'Every relationship needs compromise.', 'Verb and noun. Key relationship word.', null, [ACT.vocabulary]),

    createContentItem('"let alone" /lɛt əˈloʊn/', '/lɛt əˈloʊn/', 'Used after a negative to dismiss something even more obvious.', 'word', 'He can\'t cook, let alone bake.', 'Falling stress on "let", rising on "ALONE".', null, [ACT.pronunciation]),
    createContentItem('"bound to" /baʊnd tuː/', '/baʊnd tuː/', 'Heavy stress on "bound" for strong prediction.', 'word', 'You\'re BOUND to succeed.', 'Stress = emphasis on certainty.', null, [ACT.pronunciation]),
    createContentItem('"whereas" /ˌwɛərˈæz/', '/ˌwɛərˈæz/', 'Two syllables, stress on syllable 2.', 'word', 'I love coffee, whereas she prefers tea.', 'Slightly formal — written and academic register.', null, [ACT.pronunciation]),
    createContentItem('"can\'t help" /kænt hɛlp/', '/kænt hɛlp/', 'Fixed phrase; "help" here means "avoid".', 'word', 'I can\'t help laughing.', 'Followed by V-ing.', null, [ACT.pronunciation]),

    createContentItem(
      '"let alone + N/V" — far from',
      'dismiss + extreme example',
      'Negative statement + something even more obviously not true.',
      'sentence',
      'He doesn\'t cook, let alone bake. — I haven\'t finished my essay, let alone started the next one. — She can\'t walk, let alone run a marathon.',
      'Both items must be in the same category, with the second being more extreme.',
      [
        { target: 'negative + let alone + extreme', english: 'standard pattern' },
        { target: 'far from + V-ing / N', english: 'similar: "far from finishing"' },
        { target: 'nowhere near + V-ing', english: 'casual: "nowhere near done"' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"be bound to + V" / "be sure to + V"',
      'strong prediction',
      'Almost certain outcome.',
      'sentence',
      'You\'re bound to feel nervous before the interview. — He\'s sure to call back. — The truth is bound to come out.',
      '"Bound" — stronger certainty. "Sure" — slightly softer.',
      [
        { target: 'be bound to + V', english: 'strong: "bound to happen"' },
        { target: 'be sure to + V', english: 'softer prediction' },
        { target: 'be likely to + V', english: 'mild prediction' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"whereas / while + S + V" — contrast',
      'two-sided comparison',
      'Connect two contrasting clauses.',
      'sentence',
      'My grandparents value loyalty, whereas my generation values freedom. — While women in the 1950s stayed home, today most have careers. — She\'s extroverted, whereas her brother is shy.',
      '"Whereas" — slightly formal; "while" — slightly more casual.',
      [
        { target: 'whereas + S + V', english: 'formal contrast' },
        { target: 'while + S + V', english: 'casual contrast' },
        { target: 'on the other hand', english: 'sentence connector for contrast' },
        { target: 'in contrast (to)', english: 'formal alternative' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"have no choice but to + V" / "can\'t help + V-ing"',
      'cannot but',
      'No alternative / involuntary reaction.',
      'sentence',
      'After her parents died, she had no choice but to move home. — I can\'t help feeling sad when I think about it. — He couldn\'t help laughing at the joke.',
      'Two patterns, slightly different: "have no choice but to" = no alternative (forced); "can\'t help + V-ing" = involuntary feeling/action.',
      [
        { target: 'have no choice but to + bare V', english: 'forced / no alternative' },
        { target: 'can\'t help + V-ing', english: 'involuntary feeling' },
        { target: 'can\'t help but + bare V', english: 'same as can\'t help V-ing' },
      ],
      [ACT.grammar],
    ),

    createContentItem(
      'Voicing a complaint',
      'speaking practice',
      'Use "let alone" to amplify a complaint.',
      'sentence',
      'My roommate didn\'t make dinner, let alone clean the kitchen. I can\'t help getting annoyed every time.',
      'Frame: complaint + "let alone" + extreme + reaction.',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Generational comparison',
      'reading practice',
      'Read this opinion piece.',
      'sentence',
      'Boomers grew up with one stable career, whereas Gen Z faces a gig-economy reality. While our parents bought houses by 30, today\'s 30-year-olds often have no choice but to rent. Boomers say young people are entitled — let alone seeing they\'re lazy. But young people can\'t help feeling cheated by skyrocketing housing prices. The truth is bound to be more nuanced: every generation faces its own challenges.',
      'Note all four target patterns used.',
      [
        { target: 'whereas Gen Z faces …', english: 'contrast' },
        { target: 'have no choice but to rent', english: 'cannot but' },
        { target: 'let alone seeing they\'re lazy', english: 'extreme dismissal' },
        { target: 'can\'t help feeling cheated', english: 'involuntary feeling' },
        { target: 'truth is bound to be …', english: 'prediction' },
      ],
      [ACT.readingSpeaking],
    ),

    createContentItem(
      'Dating-app debate',
      'two friends',
      'Two friends disagree about dating apps.',
      'conversation',
      'Min-su: I think dating apps are ruining real connection.\nSarah: Whereas I think they\'re expanding options. People who\'d never have met can now meet.\nMin-su: Maybe, but most matches are bound to ghost you eventually.\nSarah: True, but in offline dating you can\'t even start a conversation, let alone exchange numbers.\nMin-su: Fair. Still, I can\'t help feeling that swiping turns people into commodities.\nSarah: I get that. So maybe we have no choice but to be intentional about how we use them.\nMin-su: Yeah. Intentional is the key word.',
      'Note polite disagreement using target grammar.',
      [
        { target: 'Whereas I think they\'re expanding options', english: 'polite contrast' },
        { target: 'matches are bound to ghost', english: 'negative prediction' },
        { target: 'let alone exchange numbers', english: 'extreme dismissal' },
        { target: 'can\'t help feeling that …', english: 'involuntary feeling' },
        { target: 'have no choice but to be intentional', english: 'concede + solution' },
      ],
      [ACT.listeningSpeaking],
    ),

    createContentItem(
      'Study analysis',
      'reading + writing',
      'Read this short piece.',
      'sentence',
      'A 2023 Pew Research study found that 70% of Gen Z women feel pressure to "do it all" — career, family, social media. While their mothers fought for career access, today\'s women fight against burnout. Gen Z men, whereas, report less role pressure but more loneliness. Researchers say young people are bound to redefine gender roles in unexpected ways. They have no choice but to, given the changing economy.',
      'Standard opinion-research style.',
      [
        { target: 'While their mothers fought for …, today\'s women fight against …', english: 'two-time contrast' },
        { target: 'Gen Z men, whereas, report …', english: 'inserted contrast' },
        { target: 'bound to redefine gender roles', english: 'strong prediction' },
        { target: 'have no choice but to', english: 'no alternative' },
      ],
      [ACT.readingWriting],
    ),
    createContentItem(
      'Writing prompt',
      'analyze a study',
      'Write 3-4 sentences analyzing a real or made-up study.',
      'sentence',
      'Example: A recent Gallup poll showed that 80% of Korean millennials want a 4-day workweek, whereas only 40% of boomers agreed. Young workers say they have no choice but to push for change, since burnout is everywhere. Companies are bound to feel the pressure soon. You can\'t help feeling that this shift was overdue.',
      'Use all four target patterns.',
      null, [ACT.readingWriting],
    ),

    createContentItem(
      'Changing workplace norms',
      'cultural overview',
      'US/UK/AU: Glass ceiling — invisible barrier to women\'s advancement. Pay gap — women average 80-85¢ for every $1 men earn. Parental leave: US has no federal paid leave (rare); UK + AU have generous statutory leave. WFH (work from home) since 2020.',
      'sentence',
      'Most US tech companies now offer paid parental leave for both parents.',
      'Norms vary widely by country and company.',
      [
        { target: 'glass ceiling', english: 'invisible barrier to women\'s top promotion' },
        { target: 'pay gap', english: '~15% lower for women in US' },
        { target: 'parental leave', english: 'US has no federal paid; UK/AU do' },
        { target: 'WFH (work from home)', english: 'major post-2020 shift' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Generational labels',
      'reference',
      'Boomer (1946-1964) · Gen X (1965-1980) · Millennial (1981-1996) · Gen Z (1997-2012) · Gen Alpha (2013-2025). Each label carries stereotypes — use carefully.',
      'sentence',
      'Boomers built wealth in the post-war economy; Gen Z is bound to face climate and economic challenges they didn\'t create.',
      'Labels are a shorthand — they don\'t describe individuals.',
      [
        { target: 'Boomer (1946-1964)', english: 'post-war' },
        { target: 'Gen X (1965-1980)', english: 'small, "forgotten" generation' },
        { target: 'Millennial (1981-1996)', english: 'first internet generation' },
        { target: 'Gen Z (1997-2012)', english: 'true digital natives' },
        { target: 'Gen Alpha (2013-)', english: 'iPad kids' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Debate a generational difference',
      'consolidation task',
      'Take a side: "Young people work harder than ever" OR "Young people are bound to fail without older mentors". Use 4 target patterns to argue your case.',
      'conversation',
      'Tutor: Today\'s young people are entitled, lazy, and bound to disappoint.\nYou: [push back with "whereas" + "can\'t help"]\nTutor: [counter-argument]\nYou: [concede with "have no choice but to" + "let alone"]\nTutor: [final position]\nYou: [closing — find common ground]',
      'AI tutor will play your debate partner.',
      [
        { target: 'whereas + S + V', english: 'contrast generations' },
        { target: 'bound to / sure to', english: 'predict' },
        { target: 'let alone + extreme', english: 'amplify negative' },
        { target: 'have no choice but to + V', english: 'concede + reframe' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
