// Level 3 Cluster 3 — Modality
// Patterns: could / would / should / might / may + bare V; modal perfect (could have / would have).

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l3c3-orientation',
  overview: 'en-l3c3-overview',
  could: 'en-l3c3-could',
  would: 'en-l3c3-would',
  should: 'en-l3c3-should',
  mightMay: 'en-l3c3-mightmay',
  modalPerfect: 'en-l3c3-modal-perfect',
  reading: 'en-l3c3-reading',
  speaking: 'en-l3c3-speaking',
  writing: 'en-l3c3-writing',
  task: 'en-l3c3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Use the 5 modal verbs of probability, ability, permission, and advice.', 'Master modal perfect: could have / would have / should have / might have / may have.', 'Express past regret, alternative pasts, and graded uncertainty.'],
    task: 'Picture telling a story about a near-miss — your version needs "would have" + "could have" naturally.' },
  { id: ACT.overview, section: 'Patterns', title: 'Modal verbs overview',
    goals: ['Recognize 5 modals + their meanings: ability, permission, advice, probability, alternative.'],
    task: 'Map each modal to its meanings.' },
  { id: ACT.could, section: 'Modal 1', title: '"could" — past ability + soft possibility',
    goals: ['Past ability: "I could run fast as a kid".', 'Soft possibility: "It could rain later".', 'Polite request: "Could you help?"'],
    task: 'Make 3 "could" sentences.' },
  { id: ACT.would, section: 'Modal 2', title: '"would" — past habit + hypothetical',
    goals: ['Past habit: "When I was a kid, we would visit grandma every Sunday".', 'Hypothetical: "I would travel more if I had time".', 'Polite request: "Would you mind?"'],
    task: 'Make 3 "would" sentences.' },
  { id: ACT.should, section: 'Modal 3', title: '"should" — advice + expectation',
    goals: ['Advice: "You should rest".', 'Expectation: "He should be here by 3".'],
    task: 'Make 3 "should" sentences.' },
  { id: ACT.mightMay, section: 'Modal 4-5', title: '"might / may" — possibility',
    goals: ['"Might" — less certain.', '"May" — slightly more formal/possible.', 'Both ~30-50% likely.'],
    task: 'Make 3 sentences with each.' },
  { id: ACT.modalPerfect, section: 'Modal perfect', title: '"could/would/should/might have + PP"',
    goals: ['Could have = was possible (didn\'t happen).', 'Would have = alternative past.', 'Should have = past regret.', 'Might/may have = past possibility.'],
    task: 'Make 5 modal-perfect sentences.' },
  { id: ACT.reading, section: 'Reading', title: 'A near-miss story',
    goals: ['Read a story using all modal perfects.'],
    task: 'Label each modal perfect.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Tell your own near-miss',
    goals: ['Use modal perfects in a personal story.'],
    task: 'Tell a 2-minute near-miss story.' },
  { id: ACT.writing, section: 'Writing', title: 'Regret paragraph',
    goals: ['Write a 5-sentence paragraph using all modal perfects.'],
    task: 'Write your own.' },
  { id: ACT.task, section: 'Task', title: 'Counterfactual conversation',
    goals: ['Combine all 5 modals + modal perfects in extended speech.'],
    task: 'Discuss a counterfactual with the AI tutor.' },
];

const lesson = {
  title: 'Level 3 · Cluster 3: Modality — could / would / should / might + modal perfect',
  category: 'daily-life',
  difficulty: 'advanced',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'grammar',
  activities,
  expressionPractice: [
    { id: 'modal-could-en', label: 'Using "could"', goal: 'Past ability, soft possibility, polite request.' },
    { id: 'modal-perfect-en', label: 'Modal perfect', goal: 'Past regret with "should have" + alternative past with "would have".' },
    { id: 'graded-uncertainty-en', label: 'Graded uncertainty', goal: 'might / may / could → probably → must.' },
  ],
  relatedPools: ['topic-grammar'],
  content: [
    createContentItem('Lesson goal', 'modality', 'By end: use 5 modals + modal perfect; express probability, regret, alternative pasts.', 'word', 'Functions: ability · possibility · advice · regret · counterfactual.', 'Five modal micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'near-miss story', 'You almost missed your flight: traffic, late check-in, but you ran through the gate just in time. You tell the story with "could have", "would have", "should have", "might have".', 'word', 'You: "I could have missed it. If I\'d left ten minutes later, I would have been stuck in Seoul. I should have taken the early train."', 'Classic counterfactual storytelling.', null, [ACT.orientation]),

    createContentItem('5 modal verbs', 'patterns', 'CAN/COULD (ability + permission + possibility). WILL/WOULD (future + habit + hypothetical). SHALL/SHOULD (advice + expectation). MAY/MIGHT (permission + possibility). MUST (obligation + strong inference).', 'word', 'Each modal has multiple meanings — context decides.', 'Pairs: can-could, will-would, may-might.', null, [ACT.overview]),

    createContentItem(
      '"could" — three uses',
      'past + possible + polite',
      'Three core meanings.',
      'sentence',
      'PAST ABILITY: I could run a 5K in my twenties.\nSOFT POSSIBILITY: It could rain tomorrow.\nPOLITE REQUEST: Could you pass the salt?',
      'For "be able to" in single past event, use "was/were able to": NOT "I could pass the test" — say "I was able to pass".',
      [
        { target: 'past ability (general)', english: 'I could run a 5K' },
        { target: 'single past success → was able to', english: 'I was able to pass the exam' },
        { target: 'possibility (~30-50%)', english: 'It could rain' },
        { target: 'polite request', english: 'Could you help?' },
      ],
      [ACT.could],
    ),

    createContentItem(
      '"would" — three uses',
      'past habit + hypothetical + polite',
      'Three core meanings.',
      'sentence',
      'PAST HABIT: When I was a kid, we would visit grandma every Sunday.\nHYPOTHETICAL: I would travel more if I had time.\nPOLITE REQUEST: Would you mind closing the door?',
      'Past habit "would" works only with action verbs (not states). For states, use "used to": NOT "I would live there"; use "I used to live there".',
      [
        { target: 'past habit (with action verbs)', english: 'we would visit' },
        { target: 'past state → used to', english: 'I used to live there' },
        { target: 'hypothetical', english: 'if I had time, I would' },
        { target: 'polite request', english: 'Would you mind?' },
      ],
      [ACT.would],
    ),

    createContentItem(
      '"should" — advice + expectation',
      'two uses',
      'Two core meanings.',
      'sentence',
      'ADVICE: You should see a doctor. — You should try the new ramen place.\nEXPECTATION: She should be here by 3. — The package should arrive tomorrow.',
      'Advice = friendly recommendation, NOT obligation. Use "must / have to" for stronger.',
      [
        { target: 'advice (friendly recommendation)', english: 'You should rest' },
        { target: 'expectation (probable future)', english: 'The bus should arrive at 3' },
        { target: 'compare: must = obligation', english: 'stronger' },
        { target: 'compare: ought to = should (slightly stronger)', english: 'old-fashioned variant' },
      ],
      [ACT.should],
    ),

    createContentItem(
      '"might / may" — possibility',
      'graded uncertainty',
      'Both express ~30-50% likelihood.',
      'sentence',
      'It might rain later. — It may rain later. (slightly more formal)\nShe might join us. — She may join us. (more formal)',
      '"May" is also formal permission: "May I leave early?"',
      [
        { target: 'might + bare V', english: 'possibility, neutral' },
        { target: 'may + bare V', english: 'possibility, slightly more formal' },
        { target: 'May I + V?', english: 'formal permission' },
        { target: 'mightn\'t (uncommon)', english: 'use "might not" instead' },
      ],
      [ACT.mightMay],
    ),
    createContentItem(
      'Graded probability ladder',
      'least to most certain',
      'Choose by certainty.',
      'sentence',
      'might/may/could (~30-50%) < should/ought to (~70%) < will/would (~90%) < must (~99%).',
      'In speech, certainty often shifts: "She might come" → "She\'ll probably come" → "She must be on her way".',
      [
        { target: 'might/may/could', english: '30-50% likely' },
        { target: 'should / ought to', english: '~70% likely' },
        { target: 'probably / likely will', english: '~90% likely' },
        { target: 'must (inference)', english: '~99% certain' },
      ],
      [ACT.mightMay],
    ),

    createContentItem(
      'Modal perfect: "could have + PP"',
      'past possibility (didn\'t happen)',
      'Something was possible in the past but didn\'t happen.',
      'sentence',
      'I could have missed the flight. — She could have won, but she stopped competing. — We could have been rich if we\'d bought Bitcoin in 2010.',
      'Often pronounced /ˈkʊdəv/ — "could\'ve", not "could of".',
      [
        { target: 'could have + PP', english: 'was possible, didn\'t happen' },
        { target: 'could\'ve = could have', english: 'standard contraction' },
        { target: 'NOT "could of"', english: 'common spelling error' },
      ],
      [ACT.modalPerfect],
    ),
    createContentItem(
      'Modal perfect: "would have + PP"',
      'alternative past',
      'What would have happened (under different conditions).',
      'sentence',
      'I would have gone if you\'d invited me. — She would have called, but her phone died. — We would have been late if the bus hadn\'t come on time.',
      'Standard partner of past conditional: "If + had + PP, would have + PP".',
      [
        { target: 'would have + PP', english: 'alternative past outcome' },
        { target: 'If + had + PP, would have + PP', english: 'past conditional (3rd)' },
        { target: 'would\'ve = would have', english: 'standard contraction' },
      ],
      [ACT.modalPerfect],
    ),
    createContentItem(
      'Modal perfect: "should have + PP"',
      'past regret / criticism',
      'Something SHOULD have happened but didn\'t (or vice versa).',
      'sentence',
      'I should have studied more. — You should have called me. — She should have apologized.',
      'Heavy emotional weight: regret, criticism, second-guessing.',
      [
        { target: 'should have + PP', english: 'past regret' },
        { target: 'shouldn\'t have + PP', english: 'past regret about something done' },
        { target: 'should\'ve = should have', english: 'standard contraction' },
      ],
      [ACT.modalPerfect],
    ),
    createContentItem(
      'Modal perfect: "might/may have + PP"',
      'past possibility (uncertain)',
      'It\'s possible something happened (you don\'t know).',
      'sentence',
      'She might have left already. — They may have heard the news. — He might have been working late.',
      'Use for past uncertainty — what you don\'t know happened.',
      [
        { target: 'might have + PP', english: 'past uncertain possibility' },
        { target: 'may have + PP', english: 'identical, slightly formal' },
        { target: 'must have + PP', english: 'strong past inference' },
      ],
      [ACT.modalPerfect],
    ),
    createContentItem(
      'Modal perfect: "must have + PP"',
      'strong past inference',
      'You\'re ~99% sure something happened.',
      'sentence',
      'She must have forgotten — she never showed up. — They must have left already — the office is empty.',
      'Inference from evidence, not knowledge.',
      [
        { target: 'must have + PP', english: 'strong past inference' },
        { target: 'must\'ve = must have', english: 'standard contraction' },
        { target: 'opposite: can\'t have + PP', english: '"She can\'t have done it" — strong denial' },
      ],
      [ACT.modalPerfect],
    ),

    createContentItem(
      'Near-miss story',
      'reading practice',
      'Identify each modal perfect.',
      'sentence',
      'Last Tuesday I almost missed my flight to Tokyo. I should have left for the airport an hour earlier, but I lingered over breakfast. By the time I reached the highway, traffic was crawling — I could have been stuck for an hour. I would have missed the flight if a sympathetic Uber driver hadn\'t taken the side streets. I must have run through the terminal — my legs ached for two days. Looking back, I might have just rebooked, but the meeting was too important to miss.',
      'All 5 modal perfects.',
      [
        { target: 'should have left earlier', english: 'past regret' },
        { target: 'could have been stuck', english: 'past possibility' },
        { target: 'would have missed', english: 'alternative past' },
        { target: 'must have run', english: 'strong inference' },
        { target: 'might have rebooked', english: 'past uncertain possibility' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Speaking — your near-miss',
      'extended turn',
      'Tell a 2-minute near-miss story using modal perfects.',
      'sentence',
      'Last year I almost missed my final exam. I should have set my alarm earlier. I could have failed the class — that would have delayed my graduation. I must have looked panicked when I sprinted in. The professor might have let me retake it, but I made it just in time.',
      'Frame: setup + regret + possibility + alternative + inference.',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Writing prompt',
      'regret paragraph',
      'Write a 5-sentence regret paragraph using all 5 modal perfects.',
      'sentence',
      'Example: I regret not learning English earlier. I should have started in high school. If I had, I could have applied to international universities. I would have studied abroad. I might have lived a completely different life. But I must have needed this slower path to appreciate it.',
      'Required: should have / could have / would have / might have / must have.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Task: Counterfactual conversation',
      'consolidation task',
      'AI tutor presents a scenario. Discuss what might/should/would have happened.',
      'conversation',
      'Tutor: What if you hadn\'t gone to college?\nYou: [hypothetical: would have + PP]\nTutor: Could it have been better?\nYou: [could have / might have + PP]\nTutor: Any regrets?\nYou: [should have + PP]\nTutor: [closing]',
      'AI tutor plays your dialogue partner.',
      [
        { target: 'could have + PP', english: 'possibility' },
        { target: 'would have + PP', english: 'alternative past' },
        { target: 'should have + PP', english: 'regret' },
        { target: 'might/may have + PP', english: 'uncertain' },
        { target: 'must have + PP', english: 'inference' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
