// Level 1 Unit 14 — Ability (English)
// Functions: stating what you can / can't do, modesty, skill levels.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'en-l1u14-orientation',
  pronunciation: 'en-l1u14-pronunciation',
  vocabularySkills: 'en-l1u14-vocab-skills',
  vocabularyAdverbs: 'en-l1u14-vocab-adv',
  grammarCan: 'en-l1u14-grammar-can',
  grammarKnowHow: 'en-l1u14-grammar-know-how',
  grammarGood: 'en-l1u14-grammar-good',
  reading: 'en-l1u14-reading',
  listening: 'en-l1u14-listening',
  writing: 'en-l1u14-writing',
  culture: 'en-l1u14-culture',
  task: 'en-l1u14-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['State abilities with "can / can\'t".', 'Grade with "well", "a little", "not very well".', 'Use "be good at + V-ing".', 'Reply modestly to compliments.'],
    task: 'Imagine a job interview where someone asks "Can you speak English?" — answer truthfully but modestly.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'can vs can\'t',
    goals: ['"can" is weak /kən/ in positive; "can\'t" is strong /kænt/ in negative.', 'Stress carries the negation — easy to miss.'],
    task: 'Read 5 can/can\'t pairs aloud.' },
  { id: ACT.vocabularySkills, section: 'Vocabulary I', title: 'Skill verbs',
    goals: ['Use 12+ skill verbs (cook, drive, swim, sing, dance, draw, play music, etc.).'],
    task: 'Pick 3 skills and self-rate.' },
  { id: ACT.vocabularyAdverbs, section: 'Vocabulary II', title: 'Skill-grading adverbs',
    goals: ['Use "well", "very well", "a little", "not very well", "not at all".'],
    task: 'Pair each adverb with a skill.' },
  { id: ACT.grammarCan, section: 'Grammar I', title: '"can / can\'t" + bare verb',
    goals: ['Form "subject + can/can\'t + bare verb".', 'No -s in third person: "she can swim" (not "she cans swim").', 'Question: "Can + subject + verb?".'],
    task: 'Make 4 ability sentences.' },
  { id: ACT.grammarKnowHow, section: 'Grammar II', title: '"know how to + verb"',
    goals: ['Alternative to "can": "I know how to swim".', 'More emphasis on learned skill than physical ability.'],
    task: 'Convert 3 "can" sentences to "know how to".' },
  { id: ACT.grammarGood, section: 'Grammar III', title: '"be good / bad at + V-ing"',
    goals: ['Form "subject + be + good/bad + at + V-ing".', 'Use V-ing form (not infinitive).'],
    task: 'State 3 things you\'re good at and bad at.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A skill profile',
    goals: ['Read a 5-sentence skill self-evaluation.'],
    task: 'Identify what she can / can\'t do.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Comparing abilities',
    goals: ['Follow a skills + hobbies dialogue.'],
    task: 'Reproduce with your own skills.' },
  { id: ACT.writing, section: 'Writing', title: 'My skills',
    goals: ['Write 4–5 sentences listing skills + grades.'],
    task: 'Write your own skill paragraph.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Modesty in English-speaking cultures',
    goals: ['Know: English-speaking cultures (especially British, Australian) value modesty.', 'Reply to compliments with "Thanks, but…" not "Yes I am great".'],
    task: 'Reply modestly to 3 compliments.' },
  { id: ACT.task, section: 'Task', title: 'Job interview — skills',
    goals: ['Combine can/can\'t + good at + grade + modesty.'],
    task: 'Roleplay a skills section of a job interview.' },
];

const lesson = {
  title: 'Level 1 · Unit 14: I can cook — Ability',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-can-you', label: 'Asking ability', goal: 'Use "Can you …?".' },
    { id: 'stating-skill', label: 'Stating ability with grade', goal: 'Combine "can" + adverb (well / a little).' },
    { id: 'modest-reply', label: 'Modest reply to a compliment', goal: 'Use "Thanks, but I\'m not very good".' },
  ],
  relatedPools: ['topic-people'],
  content: [
    createContentItem('Lesson goal', 'ability', 'By end: state abilities at every grade, distinguish "can" from "know how to", reply modestly to compliments.', 'word', 'Functions: ability · grade · modesty.', 'Three micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'job interview', 'An interviewer asks "Can you speak English?" — you should answer truthfully but modestly.', 'word', 'Interviewer: "Can you speak English?" — You: "Yes, I can speak a little. I\'m still learning."', 'A typical job interview moment.', null, [ACT.orientation]),

    createContentItem('can — weak /kən/', '/kən/', 'In affirmative sentences, "can" is unstressed and weak.', 'word', 'I can swim. /aɪ kən swɪm/', 'Stress is on the main verb, not "can".', null, [ACT.pronunciation]),
    createContentItem('can\'t — strong /kænt/', '/kænt/', '"Can\'t" is always stressed and clearly pronounced.', 'word', 'I can\'t swim. /aɪ ˈkænt swɪm/', 'The /t/ helps distinguish from "can".', null, [ACT.pronunciation]),
    createContentItem('British "can\'t" /kɑːnt/', '/kɑːnt/', 'British English uses a longer /ɑː/ vowel.', 'word', 'British: I can\'t. /aɪ kɑːnt/', 'American: /kænt/; British: /kɑːnt/.', null, [ACT.pronunciation]),
    createContentItem('good at /ɡʊd æt/', '/ɡʊd æt/', 'Linking: "good at" runs together as /ɡʊdæt/.', 'word', 'I\'m good at cooking. /aɪm ɡʊdæt ˈkʊkɪŋ/', 'Vowel + vowel boundary blends naturally.', null, [ACT.pronunciation]),

    createContentItem('cook', '/kʊk/', 'prepare food with heat', 'word', 'I can cook.', 'Past: cooked.', null, [ACT.vocabularySkills]),
    createContentItem('drive', '/draɪv/', 'control a car', 'word', 'She can drive a car.', 'Past: drove.', null, [ACT.vocabularySkills]),
    createContentItem('swim', '/swɪm/', 'move through water', 'word', 'I can swim well.', 'Past: swam.', null, [ACT.vocabularySkills]),
    createContentItem('sing', '/sɪŋ/', 'make musical sounds with voice', 'word', 'She can sing beautifully.', 'Past: sang.', null, [ACT.vocabularySkills]),
    createContentItem('dance', '/dæns/', 'move rhythmically to music', 'word', 'I can\'t dance.', 'Both verb and noun.', null, [ACT.vocabularySkills]),
    createContentItem('draw', '/drɔː/', 'make a picture with pencil/pen', 'word', 'He draws very well.', 'Past: drew.', null, [ACT.vocabularySkills]),
    createContentItem('paint', '/peɪnt/', 'make a picture with paints', 'word', 'I can paint a little.', '', null, [ACT.vocabularySkills]),
    createContentItem('play the piano / guitar', '/pleɪ/', 'perform on an instrument', 'word', 'I can play the piano.', 'Use "the" with instruments: play THE guitar.', null, [ACT.vocabularySkills]),
    createContentItem('speak (a language)', '/spiːk/', 'communicate in a language', 'word', 'I speak English and Korean.', 'For known languages: "I speak X"; for ability: "I can speak X".', null, [ACT.vocabularySkills]),
    createContentItem('read / write', '/riːd/ /raɪt/', 'reading and writing skills', 'word', 'I can read English but I can\'t write well.', 'Two different sub-skills.', null, [ACT.vocabularySkills]),
    createContentItem('ride a bike', '/raɪd/', 'control a bicycle', 'word', 'I can ride a bike.', 'Common childhood milestone.', null, [ACT.vocabularySkills]),
    createContentItem('code / program', '/koʊd/ /ˈproʊɡræm/', 'write computer programs', 'word', 'I can code in Python.', 'Common tech skill verb.', null, [ACT.vocabularySkills]),
    createContentItem('type', '/taɪp/', 'write on a keyboard', 'word', 'I can type fast.', 'Past: typed.', null, [ACT.vocabularySkills]),
    createContentItem('ski', '/skiː/', 'slide on snow with skis', 'word', 'I can\'t ski.', 'Past: skied.', null, [ACT.vocabularySkills]),

    createContentItem('well', '/wɛl/', 'in a good way', 'word', 'I cook well.', 'Adverb form of "good".', null, [ACT.vocabularyAdverbs]),
    createContentItem('very well', '/ˈvɛri wɛl/', 'extremely well', 'word', 'She sings very well.', 'Strong positive.', null, [ACT.vocabularyAdverbs]),
    createContentItem('a little', '/ə ˈlɪtəl/', 'somewhat / a small amount', 'word', 'I speak French a little.', 'Soft positive.', null, [ACT.vocabularyAdverbs]),
    createContentItem('not very well', '/nɒt ˈvɛri wɛl/', 'not skillfully', 'word', 'I sing, but not very well.', 'Modest negative.', null, [ACT.vocabularyAdverbs]),
    createContentItem('not at all', '/nɒt æt ɔːl/', 'in no way', 'word', 'I can\'t dance at all.', 'Strong negative.', null, [ACT.vocabularyAdverbs]),
    createContentItem('really well', '/ˈrɪəli wɛl/', 'extremely well', 'word', 'He plays guitar really well.', 'Synonym of "very well", more casual.', null, [ACT.vocabularyAdverbs]),
    createContentItem('pretty well', '/ˈprɪti wɛl/', 'fairly well, decent', 'word', 'I cook pretty well.', '"Pretty" as intensifier — casual.', null, [ACT.vocabularyAdverbs]),
    createContentItem('barely', '/ˈbɛərli/', 'only just; almost not', 'word', 'I can barely read French.', 'Marks minimal ability.', null, [ACT.vocabularyAdverbs]),

    createContentItem(
      '"can / can\'t + bare verb"',
      'modal of ability',
      'Use "can" + bare verb to express ability. Same form for all subjects — no -s in third person.',
      'sentence',
      'I can swim. — She can drive. — They can speak English.',
      'Negative: "can\'t" (contracted) or "cannot" (formal). Both are common.',
      [
        { target: 'subject + can + bare verb', english: 'positive' },
        { target: 'subject + can\'t + bare verb', english: 'negative' },
        { target: 'No -s for he/she/it', english: '"she CAN swim" — NOT "she cans swim"' },
      ],
      [ACT.grammarCan],
    ),
    createContentItem(
      'Question: "Can + subject + verb?"',
      'inversion',
      'Invert subject and "can".',
      'sentence',
      'Can you swim? — Yes, I can. / No, I can\'t.\nCan she drive? — Yes, she can.',
      'Short answers: subject + can / can\'t.',
      [
        { target: 'Can + subject + verb?', english: 'question pattern' },
        { target: 'Yes, [subject] can. / No, [subject] can\'t.', english: 'short answer' },
      ],
      [ACT.grammarCan],
    ),
    createContentItem(
      'Past ability: "could / couldn\'t"',
      'past form of can',
      'For past ability, use "could" / "couldn\'t".',
      'sentence',
      'I could swim when I was 5. — She couldn\'t come yesterday.',
      'Same patterns as "can" — no -s, bare verb after.',
      null,
      [ACT.grammarCan],
    ),

    createContentItem(
      '"know how to + verb"',
      'learned skill',
      'Alternative to "can". Slightly more emphasis on a LEARNED skill (vs raw ability).',
      'sentence',
      'I know how to swim. — She knows how to drive.',
      'For physical/natural abilities, "can" is more natural; for learned skills, both work.',
      [
        { target: 'know how to + bare verb', english: 'learned skill' },
        { target: 'can + bare verb', english: 'general ability' },
      ],
      [ACT.grammarKnowHow],
    ),
    createContentItem(
      'Compare: "can" vs "know how to"',
      'subtle difference',
      'Both work for skills like cooking, swimming, driving. But "can" can also mean "have permission" or "be possible".',
      'sentence',
      '"Can you swim?" — physical ability\n"Do you know how to swim?" — learned the skill\nBoth fine, slight nuance.',
      'For everyday speech, "can" is more common and natural.',
      null,
      [ACT.grammarKnowHow],
    ),

    createContentItem(
      '"be good / bad at + V-ing"',
      'skill descriptor',
      'Form: "subject + be + good/bad + at + V-ing". Always use the -ing form.',
      'sentence',
      'I\'m good at cooking. — She\'s bad at math. — They\'re good at speaking English.',
      'Common error: "good at cook" — wrong. Always -ing.',
      [
        { target: 'good at + V-ing', english: 'positive skill' },
        { target: 'bad at + V-ing', english: 'negative skill' },
        { target: 'not good at + V-ing', english: 'softer negative' },
        { target: 'great / terrible at', english: 'stronger versions' },
      ],
      [ACT.grammarGood],
    ),
    createContentItem(
      'With a noun',
      'good at + N',
      'You can also use a noun: "good at math, good at sports".',
      'sentence',
      'I\'m good at English. — She\'s bad at sports.',
      'When the noun is countable, often used with plural or general form.',
      null,
      [ACT.grammarGood],
    ),
    createContentItem(
      'Comparison: "better at" / "worse at"',
      'comparative form',
      'For comparing two skills or two people.',
      'sentence',
      'I\'m better at cooking than my brother. — She\'s worse at math than at English.',
      'Same pattern as comparatives: better/worse + at + N/V-ing.',
      null,
      [ACT.grammarGood],
    ),

    createContentItem(
      'A skill profile',
      'reading practice',
      'Read aloud, then identify what she can and can\'t do.',
      'sentence',
      'I\'m Sarah. I can speak three languages — English, French, and a little Korean. I\'m good at cooking, but I can\'t bake well. I can drive a car, but I can\'t ride a bike. I\'m really good at playing the piano. I love to sing, but I\'m not very good at it.',
      'Mix of "can", "be good at", and modesty markers.',
      [
        { target: 'I can speak …', english: 'language ability' },
        { target: 'I\'m good at …', english: 'skill descriptor' },
        { target: 'not very good at …', english: 'modest negative' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full ability sentences.',
      'sentence',
      'Q1: How many languages does she speak? · Q2: Can she ride a bike? · Q3: What is she really good at?',
      'Use "can / be good at" in your answers.',
      [
        { target: 'A1: She speaks three.', english: 'language count' },
        { target: 'A2: No, she can\'t.', english: 'short negative' },
        { target: 'A3: She\'s really good at piano.', english: 'skill descriptor' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Comparing abilities',
      'listening dialogue',
      'Two friends compare skills.',
      'conversation',
      'A: Can you cook?\nB: Yeah, I can cook a little. How about you?\nA: I love cooking. I make Italian food really well.\nB: Wow, that\'s impressive! I\'m terrible at cooking.\nA: Really? I\'m sure you\'re good at something else.\nB: Well, I\'m good at playing guitar.\nA: Cool! Maybe you can teach me — I can\'t play any instrument.',
      'Note: "really well", "terrible at", modesty.',
      [
        { target: 'I can [verb] a little', english: 'modest positive' },
        { target: 'I make [N] really well', english: 'specific skill' },
        { target: 'I\'m terrible at …', english: 'strong negative (modest)' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Interview-style ability question',
      'professional context',
      'A job interview moment.',
      'conversation',
      'Interviewer: Can you speak any other languages?\nCandidate: Yes, I speak Spanish fluently and a little French.\nInterviewer: That\'s great. Are you good at public speaking?\nCandidate: I\'m pretty good at it, yes. I gave several presentations at university.\nInterviewer: Excellent.',
      'Strike a balance: confident but not arrogant.',
      [
        { target: 'I speak X fluently', english: 'strong language claim' },
        { target: 'a little [language]', english: 'modest claim' },
        { target: 'I\'m pretty good at it', english: 'confident but not arrogant' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'skill paragraph template',
      'Use this structure.',
      'sentence',
      'I can [strong skill] very well. I\'m also good at [V-ing]. I can [mid skill] a little. I can\'t [weak skill] well. I want to learn [future skill].',
      '[strong] · [good at] · [mid] · [weak] · [future].',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 4–5 sentences listing your real skills. Use all 4 grades (very well / a little / not very well / can\'t).',
      'sentence',
      'Example: I can speak English well. I can also speak Korean a little. I\'m really good at cooking. I can\'t play any musical instruments. I want to learn the guitar.',
      'Check: skills + grades + future intent.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Modest self-evaluation',
      'cultural norm',
      'English-speaking cultures (especially British, Australian) value modesty. Directly bragging about skills sounds arrogant. When someone compliments you, deflect lightly.',
      'sentence',
      'A: "You speak English really well!"\nB: ✓ "Thanks, I\'m still learning."\nB: ✗ "Yes, I am very good." (sounds arrogant)',
      'Modest deflection is the norm: "Thanks, I\'m still learning" / "Oh, you\'re too kind".',
      [
        { target: 'Thanks, I\'m still learning', english: 'standard modest deflection' },
        { target: 'You\'re too kind', english: 'polite deflection' },
        { target: 'I\'m pretty good at it', english: 'OK to be confident, with hedge' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'But also: be confident in interviews',
      'context matters',
      'In job interviews and professional settings, balance modesty with directness. "I\'m strong at X" is fine. Avoid extreme self-deprecation.',
      'sentence',
      'Interview: "I\'m strong at communication and project management."\nCasual: "I\'m pretty good at communicating."',
      'Tone shift: interview is direct + confident; casual is hedged + modest.',
      null, [ACT.culture],
    ),

    createContentItem(
      'Task: Job interview — skills',
      'consolidation task',
      'Roleplay: An interviewer asks about your skills. Combine "can", "good at", grade adverbs, and modest replies.',
      'conversation',
      'Interviewer: Can you speak any languages?\nYou: [list with grades]\nInterviewer: Are you good at teamwork?\nYou: [yes/no with reason]\nInterviewer: Can you code?\nYou: [yes/no + level]\nInterviewer: That\'s impressive!\nYou: [modest deflection]',
      'AI tutor will play the interviewer.',
      [
        { target: 'I can [verb] [grade]', english: 'ability + grade' },
        { target: 'I\'m good at [V-ing]', english: 'skill descriptor' },
        { target: 'Thanks, I\'m still learning', english: 'modest reply' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
