// Level 2 Adult Unit 11 — Job Hunting (English)
// Functions: resume, cover letter, interview, salary negotiation.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2au11-orientation',
  pronunciation: 'en-l2au11-pronunciation',
  vocabularyJob: 'en-l2au11-vocab-job',
  vocabularyInterview: 'en-l2au11-vocab-interview',
  grammarSelfPitch: 'en-l2au11-grammar-pitch',
  grammarSalary: 'en-l2au11-grammar-salary',
  reading: 'en-l2au11-reading',
  listening: 'en-l2au11-listening',
  writing: 'en-l2au11-writing',
  culture: 'en-l2au11-culture',
  task: 'en-l2au11-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Write a US-style resume/CV.', 'Answer common interview questions ("Tell me about yourself").', 'Discuss salary expectations professionally.', 'Send a polite thank-you email after an interview.'],
    task: 'Picture interviewing for a software engineer role at a Silicon Valley startup.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Interview-tone phrases',
    goals: ['Pronounce "Tell me about yourself" calmly /tɛl miː əˈbaʊt jərˈsɛlf/.', 'Reduce "would have" → "would\'ve" /ˈwʊdəv/.', 'Stress own achievements: "I LED a team of 5".'],
    task: 'Read 3 interview phrases aloud.' },
  { id: ACT.vocabularyJob, section: 'Vocabulary I', title: 'Job search vocabulary',
    goals: ['Use resume, CV, cover letter, job posting, application, recruiter, hiring manager, ATS.'],
    task: 'List 5 job-search terms.' },
  { id: ACT.vocabularyInterview, section: 'Vocabulary II', title: 'Interview + offer vocabulary',
    goals: ['Use interview, behavioral question, technical question, panel interview, offer letter, salary, base, bonus, equity.'],
    task: 'Define 5 terms.' },
  { id: ACT.grammarSelfPitch, section: 'Grammar I', title: 'Self-pitch patterns',
    goals: ['"I have + N years of experience in + field".', '"My background is in + field".', '"I\'m known for + N/V-ing".'],
    task: 'Write a 3-sentence self-pitch.' },
  { id: ACT.grammarSalary, section: 'Grammar II', title: 'Salary negotiation',
    goals: ['"I was hoping for + range".', '"Based on my experience and market rate, I\'m looking at + $X".', '"Is there room to negotiate on + N?"'],
    task: 'Negotiate a 5K raise.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'Job posting',
    goals: ['Read a typical job posting.'],
    task: 'Identify required vs preferred skills.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Behavioral interview',
    goals: ['Follow STAR-format answers.'],
    task: 'Reproduce with your own example.' },
  { id: ACT.writing, section: 'Writing', title: 'Thank-you email',
    goals: ['Write a 5-line post-interview thank-you email.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: 'US tech interview pipeline',
    goals: ['Know stages: recruiter screen → technical → behavioral → onsite → offer.', 'Know STAR method (Situation/Task/Action/Result).', 'Know typical timelines and salary components (base + bonus + equity).'],
    task: 'Compare with hiring in your country.' },
  { id: ACT.task, section: 'Task', title: 'Mock interview',
    goals: ['Combine self-pitch + 2 STAR answers + salary discussion.'],
    task: 'Roleplay a 30-minute behavioral interview.' },
];

const lesson = {
  title: 'Level 2 (Workplace) · Unit 11: Tell me about yourself — Job Hunting',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'self-pitch-en', label: 'Self-pitch', goal: 'Use "I have N years in + field".' },
    { id: 'star-answer-en', label: 'STAR answer', goal: 'Structure: Situation, Task, Action, Result.' },
    { id: 'salary-negotiation-en', label: 'Salary negotiation', goal: 'Use "I was hoping for + range".' },
  ],
  relatedPools: ['topic-career'],
  content: [
    createContentItem('Lesson goal', 'job hunting', 'By end: write a resume, answer interview questions with STAR, negotiate salary, send thank-you.', 'word', 'Functions: resume · STAR · negotiate · follow-up.', 'Four job-hunt micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'startup interview', 'You\'re interviewing for a software engineer role at a Series B startup in San Francisco. The hiring manager opens with "Tell me about yourself" and the offer discussion follows.', 'word', 'Hiring manager: "Tell me about yourself." — You: "I\'m a software engineer with 3 years of experience in backend systems. Most recently at Samsung, I led the migration of our payment service to microservices…"', 'A standard SF startup interview.', null, [ACT.orientation]),

    createContentItem('"Tell me about yourself" /tɛl miː əˈbaʊt jərˈsɛlf/', '/tɛl miː əˈbaʊt jərˈsɛlf/', 'Calm, measured pace.', 'word', 'Tell me about yourself.', 'The universal interview opener.', null, [ACT.pronunciation]),
    createContentItem('"would\'ve" /ˈwʊdəv/', '/ˈwʊdəv/', 'Reduced "would have"; for STAR answers about past actions.', 'word', 'I would\'ve approached it differently in hindsight.', 'Don\'t write "would of" — common error.', null, [ACT.pronunciation]),
    createContentItem('"I LED a team" emphasis', '/aɪ lɛd ə tiːm/', 'Stress "LED" for leadership claims.', 'word', 'I LED a team of 5 engineers.', 'Stress shows ownership.', null, [ACT.pronunciation]),

    createContentItem('resume / CV', '/ˈrɛzəˌmeɪ/ /siː viː/', 'job-application document', 'word', 'I sent my resume yesterday.', 'US: resume (1-2 pages). UK/Academia: CV (longer).', null, [ACT.vocabularyJob]),
    createContentItem('cover letter', '/ˈkʌvər ˈlɛtər/', 'personalized intro letter', 'word', 'Most jobs no longer require a cover letter.', 'Less common in tech; still required in some fields.', null, [ACT.vocabularyJob]),
    createContentItem('job posting / opening / req', '/dʒɒb ˈpoʊstɪŋ/', 'open position ad', 'word', 'The job posting closes Friday.', '"Req" — internal recruiter shorthand for "requisition".', null, [ACT.vocabularyJob]),
    createContentItem('application', '/ˌæplɪˈkeɪʃən/', 'submission', 'word', 'I submitted my application online.', 'Verb: "apply for".', null, [ACT.vocabularyJob]),
    createContentItem('recruiter / hiring manager', '/rɪˈkruːtər/ /ˈhaɪərɪŋ ˈmænɪdʒər/', 'sourcing / deciding roles', 'word', 'The recruiter set up the call.', 'Recruiter screens; hiring manager decides.', null, [ACT.vocabularyJob]),
    createContentItem('ATS (Applicant Tracking System)', '/eɪ tiː ɛs/', 'resume-parsing software', 'word', 'Use keywords for ATS.', 'Most large companies use one (e.g. Workday, Greenhouse).', null, [ACT.vocabularyJob]),
    createContentItem('referral', '/rɪˈfɜːrəl/', 'internal recommendation', 'word', 'I got the interview through a referral.', 'Often the strongest entry path.', null, [ACT.vocabularyJob]),

    createContentItem('interview', '/ˈɪntərvjuː/', 'evaluation conversation', 'word', 'My next interview is Friday.', 'Types: phone, video, onsite.', null, [ACT.vocabularyInterview]),
    createContentItem('behavioral question', '/bɪˈheɪvjərəl ˈkwɛstʃən/', 'past-experience question', 'word', 'Tell me about a time when …', 'Use STAR.', null, [ACT.vocabularyInterview]),
    createContentItem('technical question', '/ˈtɛknɪkəl ˈkwɛstʃən/', 'skill-test question', 'word', 'Coding interviews focus on technical questions.', 'Test specific knowledge.', null, [ACT.vocabularyInterview]),
    createContentItem('panel interview', '/ˈpænəl/', 'multi-interviewer session', 'word', 'My panel had 4 interviewers.', 'Common at senior level.', null, [ACT.vocabularyInterview]),
    createContentItem('offer letter', '/ˈɒfər ˈlɛtər/', 'formal job offer', 'word', 'I got my offer letter yesterday!', 'Includes role + comp + start date.', null, [ACT.vocabularyInterview]),
    createContentItem('salary / base / bonus / equity', '/ˈsæləri/ /beɪs/ /ˈboʊnəs/ /ˈɛkwəti/', 'compensation components', 'word', 'Base $120K, 15% bonus, 0.1% equity.', 'Total compensation = sum of all.', null, [ACT.vocabularyInterview]),
    createContentItem('benefits package', '/ˈbɛnəfɪts ˈpækɪdʒ/', 'non-cash compensation', 'word', 'Great benefits package — full health, 401k match.', 'Health, retirement, PTO, perks.', null, [ACT.vocabularyInterview]),

    createContentItem(
      'Self-pitch',
      'opening interview answer',
      '60-90 seconds: background + recent + why this role.',
      'sentence',
      'I\'m a software engineer with 3 years of experience in backend systems. My background is in fintech — most recently at Samsung Pay, I led the migration of our payment service to microservices, which reduced latency by 40%. I\'m drawn to your team because of your work on distributed systems, and I\'m looking to deepen my expertise in that area.',
      'Background + recent achievement + reason for this role.',
      [
        { target: 'I have/am + N years + experience in + field', english: 'background' },
        { target: 'My background is in + N', english: 'positioning' },
        { target: 'Most recently at + company, I + achievement', english: 'recent win' },
        { target: 'I\'m drawn to + reason / I\'m looking to + V', english: 'why this role' },
      ],
      [ACT.grammarSelfPitch],
    ),
    createContentItem(
      'STAR method',
      'behavioral answer format',
      'For "Tell me about a time when…" questions.',
      'sentence',
      'Situation: At my last job, we had a recurring outage every Friday afternoon. Task: I was asked to root-cause and fix it. Action: I instrumented the system, traced the issue to a cron job, refactored the queue logic, and rolled out a fix. Result: Zero outages for the next 6 months, and the team adopted my monitoring approach.',
      'Four parts; spend most time on Action and Result.',
      [
        { target: 'Situation: context', english: 'what was happening' },
        { target: 'Task: what was asked', english: 'your responsibility' },
        { target: 'Action: what you did', english: 'most detail here' },
        { target: 'Result: outcome + metric', english: 'measurable impact' },
      ],
      [ACT.grammarSelfPitch],
    ),
    createContentItem(
      'Salary negotiation',
      'professional script',
      'Ask the offer, then propose a counter.',
      'sentence',
      'I was hoping for something in the $140-150K range, based on my experience and market rate. — Is there room to negotiate on equity? — Could we revisit the base if equity is fixed?',
      'Anchor with research. Frame as collaborative.',
      [
        { target: 'I was hoping for + range', english: 'soft anchor' },
        { target: 'based on market rate + experience', english: 'justification' },
        { target: 'Is there room on + component?', english: 'identify flex' },
        { target: 'Could we revisit + N?', english: 'specific re-open' },
      ],
      [ACT.grammarSalary],
    ),

    createContentItem(
      'Job posting',
      'reading practice',
      'Read this typical posting.',
      'sentence',
      'BACKEND ENGINEER — Series B Startup, San Francisco\n\nResponsibilities:\n• Design and build scalable backend services in Go.\n• Collaborate with product and design.\n• Mentor junior engineers.\n\nRequired:\n• 3+ years of backend experience\n• Strong Go or similar language (Java, C++)\n• Distributed systems experience\n\nPreferred:\n• Kubernetes experience\n• Open-source contributions\n\nCompensation: $130-160K base + 0.1-0.5% equity + medical/dental/401k.\nHybrid: 3 days in-office, San Francisco HQ.',
      'Standard tech job posting.',
      [
        { target: 'Responsibilities', english: 'what you\'ll do' },
        { target: 'Required vs Preferred', english: 'must-have vs nice-to-have' },
        { target: 'Compensation range', english: 'salary transparency (CA law)' },
        { target: 'Hybrid: 3 days in-office', english: 'WFH policy' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Behavioral interview',
      'STAR in action',
      'Tell me about a time when…',
      'conversation',
      'Interviewer: Tell me about a time you handled a difficult teammate.\nYou: Sure. (S) At Samsung, we had a senior engineer who blocked all code reviews — sometimes for a week. (T) I needed to ship a payment-service migration on a tight deadline. (A) I scheduled a 30-min coffee with him, asked what was slowing him down, and learned he was burned out with too many reviews. I proposed splitting the load — half to me, half to him. (R) Reviews cleared within 24 hours, and the migration shipped on time. We also rolled out a team-wide review rotation that\'s still in place.\nInterviewer: Great. What did you learn?\nYou: That blockers are often communication problems, not capability problems.',
      'Standard STAR answer.',
      [
        { target: 'S: context', english: 'situation' },
        { target: 'T: task', english: 'task' },
        { target: 'A: detailed actions', english: 'most time here' },
        { target: 'R: measurable result + lasting change', english: 'impact' },
        { target: 'reflection: what I learned', english: 'follow-up' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Thank-you email',
      'writing model',
      'Send within 24 hours after the interview.',
      'sentence',
      'Subject: Thank you — Backend Engineer interview\n\nHi Sarah,\n\nThanks for taking the time to chat today. I really enjoyed our conversation about the payments-team roadmap, and your work on the rate-limiting service is exactly the kind of challenge I\'m looking to take on. Please let me know if there\'s any other information you need from me. Looking forward to next steps.\n\nBest,\nMin-su Kim',
      'Standard post-interview thank-you.',
      [
        { target: 'Subject: Thank you — + role', english: 'specific subject' },
        { target: 'Thanks for taking the time', english: 'standard opener' },
        { target: 'I really enjoyed our conversation about + specific topic', english: 'shows you listened' },
        { target: 'your work on X is + reason', english: 'demonstrates interest' },
        { target: 'Looking forward to next steps', english: 'standard close' },
      ],
      [ACT.writing],
    ),

    createContentItem(
      'US tech interview pipeline',
      'cultural overview',
      'Stages: 1) Recruiter screen (30 min phone). 2) Technical phone screen (45-60 min coding). 3) Behavioral with hiring manager (30-45 min). 4) Onsite / virtual onsite (3-5 hours of interviews). 5) Reference check + offer. Timeline: 2-6 weeks. Comp = base + signing bonus + annual bonus + equity (often 4-year vest).',
      'sentence',
      'Most tech companies post salary ranges by law now in CA, NY, WA, CO.',
      'Negotiation is expected — companies build in 5-15% room.',
      [
        { target: 'recruiter screen → technical → behavioral → onsite', english: 'standard pipeline' },
        { target: 'STAR method', english: 'behavioral answer format' },
        { target: 'base + bonus + equity', english: 'total comp' },
        { target: '4-year vesting', english: 'standard equity timeline' },
        { target: 'salary transparency laws', english: 'CA, NY, WA, CO require ranges' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Mock interview',
      'consolidation task',
      'AI tutor plays the hiring manager. 1) self-pitch, 2) STAR answer, 3) salary discussion.',
      'conversation',
      'Tutor: Tell me about yourself.\nYou: [60-sec self-pitch]\nTutor: Tell me about a time you led a project.\nYou: [STAR answer]\nTutor: What are your salary expectations?\nYou: [research-backed range with justification]\nTutor: [counter-offer or next steps]\nYou: [thank + close]',
      'AI tutor plays hiring manager.',
      [
        { target: 'self-pitch: background + recent + reason', english: '60-90 seconds' },
        { target: 'STAR: situation, task, action, result', english: 'behavioral format' },
        { target: 'I was hoping for + range, based on …', english: 'salary anchor' },
        { target: 'Looking forward to next steps', english: 'close' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
