// Level 2 Unit 5 — English Proverbs & Body-Part Idioms
// Grammar: "what with X and Y" (multiple reasons), "as they say / as the saying goes",
// "bound to / sure to" (review), "the more S V, the more S V". Culture: animal proverbs.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l2u5-orientation',
  vocabulary: 'en-l2u5-vocabulary',
  pronunciation: 'en-l2u5-pronunciation',
  grammar: 'en-l2u5-grammar',
  speaking: 'en-l2u5-speaking',
  readingSpeaking: 'en-l2u5-reading-speaking',
  listeningSpeaking: 'en-l2u5-listening-speaking',
  readingWriting: 'en-l2u5-reading-writing',
  culture: 'en-l2u5-culture',
  task: 'en-l2u5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Use 10+ English proverbs and body-part idioms.', 'Console + quote using "as they say", "what with X and Y", "the more X the more Y".', 'Sound native by sprinkling sayings into speech.'],
    task: 'Picture consoling a friend at Kumoh who failed a midterm — use a proverb to lift her mood.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Proverbs + body-part idioms',
    goals: ['10+ proverbs + 5+ body-part idioms (foot, eye, hand, ear, mouth, head).'],
    task: 'Pick 3 proverbs and explain their meaning in English.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Idiom rhythm & stress',
    goals: ['Stress key content words in proverbs: "A STITCH in TIME saves NINE".', 'Use sentence rhythm to make idioms sound natural.'],
    task: 'Read 4 proverbs with proper stress.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Quoting + consoling patterns',
    goals: ['"what with X and Y" — multiple stacked reasons', '"as they say / as the saying goes" — quoting a proverb', '"bound to + V" — is bound to (review)', '"the more S V, the more S V" — correlative comparative'],
    task: 'Use each pattern in a sentence.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Explaining a frustration with multiple reasons',
    goals: ['Use "what with X and Y" to stack reasons.'],
    task: 'Tell a small frustration with two or three causes.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Personality descriptions',
    goals: ['Read a personality profile using body-part idioms.', 'Describe a friend in 4 sentences.'],
    task: 'Describe a classmate using 2 idioms.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Consoling with a proverb',
    goals: ['Listen to a friend\'s problem.', 'Console with an appropriate proverb.'],
    task: 'Console using one proverb + "as they say".' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Quoting proverbs in writing',
    goals: ['Read short articles citing proverbs.', 'Write a piece quoting one.'],
    task: 'Write 3 sentences quoting an English proverb.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Animals in English proverbs',
    goals: ['Recognize recurring animals: dog, cat, bird, horse, fox.', 'Compare with proverbs from your culture.'],
    task: 'Find a similar saying from your culture.' },
  { id: ACT.task, section: 'Task', title: 'Proverb pantomime / charades',
    goals: ['Pantomime a proverb so others can guess.'],
    task: 'Pick 3 proverbs and describe without using their key words.' },
];

const lesson = {
  title: 'Level 2 · Unit 5: As they say — Proverbs and Idioms',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'quoting-proverb-en', label: 'Quoting a proverb', goal: 'Use "as they say / as the saying goes".' },
    { id: 'consoling-en', label: 'Consoling someone', goal: 'Use a proverb + "bound to".' },
    { id: 'correlative-comparative-en', label: 'Correlative comparison', goal: 'Use "the more S V, the more S V".' },
  ],
  relatedPools: ['topic-proverbs-idioms'],
  content: [
    createContentItem('Lesson goal', 'proverbs and idioms', 'By end: quote 10+ proverbs, use 5+ idioms, console a friend with a saying.', 'word', 'Functions: quote · console · describe character · stack reasons.', 'Four native-fluency micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'consoling a friend', 'Your classmate at Kumoh failed her midterm. She\'s crushed. You console her with an English proverb that captures the bigger picture.', 'word', 'You: "Hey, every cloud has a silver lining. As they say, what doesn\'t kill you makes you stronger."', 'A typical consoling moment.', null, [ACT.orientation]),

    createContentItem('A stitch in time saves nine', '/ə stɪtʃ ɪn taɪm seɪvz naɪn/', 'Fix small problems early — they grow if neglected.', 'word', 'I checked my car before the road trip. A stitch in time saves nine.', 'About prevention.', null, [ACT.vocabulary]),
    createContentItem('When in Rome, do as the Romans do', '/wɛn ɪn roʊm/', 'Adapt to local customs when traveling.', 'word', 'When in Rome, do as the Romans do — try the kimchi.', 'About cultural adaptation.', null, [ACT.vocabulary]),
    createContentItem('The early bird catches the worm', '/ðiː ˈɜːrli bɜːrd/', 'Those who start early get the rewards.', 'word', 'I arrived at 6 AM for the sale. The early bird catches the worm.', 'About diligence.', null, [ACT.vocabulary]),
    createContentItem('Don\'t count your chickens before they hatch', '/doʊnt kaʊnt jʊər ˈtʃɪkɪnz/', 'Don\'t assume success too early.', 'word', 'I haven\'t got the job yet — don\'t count your chickens before they hatch.', 'About caution.', null, [ACT.vocabulary]),
    createContentItem('Every cloud has a silver lining', '/ˈɛvri klaʊd/', 'Every bad situation has a positive side.', 'word', 'Losing my job led me to a better one — every cloud has a silver lining.', 'About optimism.', null, [ACT.vocabulary]),
    createContentItem('Practice makes perfect', '/ˈpræktɪs meɪks ˈpɜːrfɪkt/', 'Consistent effort leads to mastery.', 'word', 'My English is improving — practice makes perfect.', 'About persistence.', null, [ACT.vocabulary]),
    createContentItem('Two heads are better than one', '/tuː hɛdz/', 'Collaboration beats solo work.', 'word', 'Let\'s solve this together — two heads are better than one.', 'About teamwork.', null, [ACT.vocabulary]),
    createContentItem('Actions speak louder than words', '/ˈækʃənz spiːk ˈlaʊdər/', 'What you do matters more than what you say.', 'word', 'He apologized but kept doing it — actions speak louder than words.', 'About integrity.', null, [ACT.vocabulary]),
    createContentItem('Don\'t judge a book by its cover', '/doʊnt dʒʌdʒ ə bʊk/', 'Don\'t evaluate based on appearance.', 'word', 'She seems shy, but she\'s brilliant — don\'t judge a book by its cover.', 'About judgment.', null, [ACT.vocabulary]),
    createContentItem('What doesn\'t kill you makes you stronger', '/wʌt ˈdʌzənt kɪl juː/', 'Hardship builds resilience.', 'word', 'After the breakup I felt awful, but what doesn\'t kill you makes you stronger.', 'About resilience.', null, [ACT.vocabulary]),

    createContentItem('cold feet', '/koʊld fiːt/', 'sudden hesitation / nervousness', 'word', 'He got cold feet before the wedding.', 'Especially about commitments.', null, [ACT.vocabulary]),
    createContentItem('keep an eye on', '/kiːp æn aɪ ɒn/', 'monitor / watch', 'word', 'Keep an eye on the soup while I run upstairs.', 'About vigilance.', null, [ACT.vocabulary]),
    createContentItem('lend a hand', '/lɛnd ə hænd/', 'help', 'word', 'Could you lend a hand with this box?', '"Give me a hand" — same meaning.', null, [ACT.vocabulary]),
    createContentItem('play it by ear', '/pleɪ ɪt baɪ ɪər/', 'improvise / not plan ahead', 'word', 'Let\'s play it by ear — see how the weather is.', 'Originally about music.', null, [ACT.vocabulary]),
    createContentItem('a slip of the tongue', '/ə slɪp ɒv ðə tʌŋ/', 'an accidental utterance', 'word', 'I called him by the wrong name — total slip of the tongue.', 'About verbal mistakes.', null, [ACT.vocabulary]),
    createContentItem('use your head', '/juːz jʊər hɛd/', 'think carefully', 'word', 'Use your head — don\'t click that link.', 'Imperative for problem-solving.', null, [ACT.vocabulary]),

    createContentItem('"A stitch in TIME saves NINE"', 'stress: TIME, NINE', 'Rhythm: x x x STRESS x x STRESS.', 'word', 'Read with strong stress on content words.', 'Proverbs use rhythm — feel the beat.', null, [ACT.pronunciation]),
    createContentItem('"WHEN in ROME, DO as the ROMANS do"', 'multiple stresses', 'Three main stresses; pace evenly.', 'word', 'WHEN in ROME, DO as the ROMANS do.', 'Cadence almost like a beat.', null, [ACT.pronunciation]),
    createContentItem('"PRACTICE makes PERFECT"', 'two clear stresses', 'Two-stress proverbs — common pattern.', 'word', 'PRACTICE makes PERFECT.', 'These rhythmic patterns help memory.', null, [ACT.pronunciation]),
    createContentItem('"TWO HEADS are BETTER than ONE"', 'four stresses', 'Important: contrast TWO vs ONE.', 'word', 'TWO HEADS are BETTER than ONE.', 'Numbers / contrasts get extra stress.', null, [ACT.pronunciation]),

    createContentItem(
      '"what with X and Y" — stacked reasons',
      'multiple causes',
      'List several reasons for a state or situation.',
      'sentence',
      'What with exams, work, and family stress, I\'m exhausted. — She didn\'t come, what with the rain and her bad cold.',
      'Always followed by a list of reasons (usually 2-3 noun phrases).',
      [
        { target: 'what with + N, N, and N', english: 'list reasons' },
        { target: 'between X and Y', english: 'simpler: "between work and family"' },
        { target: 'on top of N', english: 'add: "on top of being sick"' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"as they say / as the saying goes" — quoting',
      'introduce a proverb',
      'Frame a proverb in conversation.',
      'sentence',
      'As they say, every cloud has a silver lining. — As the saying goes, practice makes perfect.',
      'Casual: "you know what they say…".',
      [
        { target: 'as they say', english: 'casual frame for proverb' },
        { target: 'as the saying goes', english: 'slightly more formal' },
        { target: 'you know what they say', english: 'very casual' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"bound to + V" — strong prediction (review)',
      'inevitable outcome',
      'For something almost certain to happen.',
      'sentence',
      'You\'re bound to learn from this experience. — Mistakes are bound to happen — don\'t worry.',
      'Reviewed from Unit 4; common in consoling.',
      [
        { target: 'be bound to + V', english: 'strong: nearly certain' },
        { target: 'is bound to happen', english: 'consoling phrase' },
      ],
      [ACT.grammar],
    ),
    createContentItem(
      '"the more S V, the more S V" — correlative',
      'parallel growth',
      'Two parallel changes that go together.',
      'sentence',
      'The more I study, the more I forget. — The more you practice, the better you get. — The harder I try, the worse it gets.',
      'Two clauses, both starting with "the + comparative". Mid-comma.',
      [
        { target: 'the more + S + V, the more + S + V', english: 'standard pattern' },
        { target: 'the harder, the better', english: 'with adj/adv' },
        { target: 'the sooner, the better', english: 'fixed casual phrase' },
      ],
      [ACT.grammar],
    ),

    createContentItem(
      'Stacking frustrations',
      'speaking practice',
      'Use "what with X and Y" to stack reasons.',
      'sentence',
      'What with three midterms next week, my sick roommate, and my broken laptop, I\'m losing my mind.',
      'Frame: "what with + 2-3 reasons + main statement".',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Personality with idioms',
      'reading practice',
      'Read this profile.',
      'sentence',
      'Sarah is one of those rare people who always uses her head before speaking. She\'ll lend a hand to anyone, but she can also play it by ear when plans fall apart. She got cold feet about her wedding last year, but as she says, "When in Rome, do as the Romans do" — so she went through with the small ceremony. The more I get to know her, the more I admire her.',
      'Personality profile using 5 idioms.',
      [
        { target: 'uses her head before speaking', english: 'thinks first' },
        { target: 'lend a hand', english: 'help' },
        { target: 'play it by ear', english: 'improvise' },
        { target: 'got cold feet', english: 'hesitated' },
        { target: 'When in Rome, do as the Romans do', english: 'proverb' },
        { target: 'The more I get to know her, the more I admire her', english: 'correlative' },
      ],
      [ACT.readingSpeaking],
    ),

    createContentItem(
      'Consoling a friend',
      'dialogue',
      'Two friends after a failure.',
      'conversation',
      'Sarah: I failed my midterm. I studied so hard.\nMin-su: Oh no, I\'m sorry. What with the new professor and the surprise topic, no wonder it was tough.\nSarah: I\'m bound to fail the final too.\nMin-su: Hey, don\'t count your chickens before they hatch. The more you panic, the harder it gets.\nSarah: True.\nMin-su: And as they say, every cloud has a silver lining. Maybe this teaches you what to focus on.\nSarah: Yeah. Practice makes perfect, I guess.\nMin-su: Exactly. You\'ll bounce back.',
      'Note 4 grammar patterns + 3 proverbs used.',
      [
        { target: 'What with the new professor and the surprise topic', english: 'stack reasons' },
        { target: 'don\'t count your chickens before they hatch', english: 'proverb' },
        { target: 'The more you panic, the harder it gets', english: 'correlative' },
        { target: 'as they say, every cloud has a silver lining', english: 'quote a proverb' },
      ],
      [ACT.listeningSpeaking],
    ),

    createContentItem(
      'Article quoting a proverb',
      'reading + writing',
      'Read this short opinion piece.',
      'sentence',
      'A new study on burnout shows that 60% of young professionals work more than 50 hours a week. What with high rent, student loans, and rising prices, many feel they have no choice. But as the saying goes, "all work and no play makes Jack a dull boy". Researchers say work-life balance is bound to become the next great career skill. The more we ignore burnout, the more it grows.',
      'Opinion piece using all 4 patterns + a proverb.',
      [
        { target: 'What with high rent, …', english: 'stack reasons' },
        { target: 'as the saying goes', english: 'quote frame' },
        { target: 'bound to become', english: 'prediction' },
        { target: 'The more we ignore …, the more it grows', english: 'correlative' },
      ],
      [ACT.readingWriting],
    ),
    createContentItem(
      'Writing prompt',
      'quote a proverb',
      'Write 3-4 sentences quoting an English or Korean proverb to make a point.',
      'sentence',
      'Example: I had a tough month — what with the deadline, my flu, and a family emergency. But as the saying goes, "what doesn\'t kill you makes you stronger". The harder this year is, the more grateful I\'ll be for next year. Things are bound to get better.',
      'Use at least one "what with", one "as they say", and one "the more…the more".',
      null, [ACT.readingWriting],
    ),

    createContentItem(
      'Animals in English proverbs',
      'cultural overview',
      'Common animals in English proverbs: dog (let sleeping dogs lie), cat (curiosity killed the cat), bird (the early bird catches the worm), horse (don\'t look a gift horse in the mouth), fox (sly as a fox).',
      'sentence',
      'Compared to Korean proverbs (heavy on tigers and oxen), English proverbs lean on dogs and birds.',
      'Different cultures pick different "moral animals".',
      [
        { target: 'let sleeping dogs lie', english: 'don\'t stir up trouble' },
        { target: 'curiosity killed the cat', english: 'be careful asking too much' },
        { target: 'don\'t look a gift horse in the mouth', english: 'accept gifts gratefully' },
        { target: 'a bird in the hand is worth two in the bush', english: 'value what you have' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Idiom vs proverb',
      'definitions',
      'Idiom = phrase with non-literal meaning ("cold feet"). Proverb = complete saying with wisdom ("a stitch in time saves nine").',
      'sentence',
      'Idioms slot into sentences; proverbs stand alone.',
      'Both make speech sound native — sprinkle, don\'t overload.',
      [
        { target: 'idiom = short phrase (non-literal)', english: 'fits in sentences' },
        { target: 'proverb = complete saying (wisdom)', english: 'stands alone' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Proverb pantomime',
      'consolidation task',
      'Pick 3 English proverbs; describe each without using its key words. AI tutor guesses.',
      'conversation',
      'You: This one is about getting up early.\nTutor: "The early bird catches the worm"?\nYou: Yes! Next: this is about not assuming success.\nTutor: "Don\'t count your chickens before they hatch".\nYou: Right. Last: helping each other is better than alone.\nTutor: "Two heads are better than one".',
      'AI tutor will play the guessing partner.',
      [
        { target: 'as they say', english: 'frame proverb' },
        { target: 'bound to', english: 'prediction' },
        { target: 'the more X the more Y', english: 'correlative' },
        { target: 'what with X and Y', english: 'stack reasons' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
