// Level 1 Unit 20 — Suggestions & Plans (English)
// Functions: making suggestions, agreeing, counter-proposing, planning a movie/cafe outing.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l1u20-orientation',
  pronunciation: 'en-l1u20-pronunciation',
  vocabularyMovie: 'en-l1u20-vocab-movie',
  vocabularyOutings: 'en-l1u20-vocab-outings',
  grammarPoliteShall: 'en-l1u20-grammar-shall',
  grammarCasualWanna: 'en-l1u20-grammar-wanna',
  grammarAgreeing: 'en-l1u20-grammar-agree',
  reading: 'en-l1u20-reading',
  listening: 'en-l1u20-listening',
  writing: 'en-l1u20-writing',
  culture: 'en-l1u20-culture',
  task: 'en-l1u20-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Make polite suggestions with "Shall we …?" / "Why don\'t we …?" and casual ones with "Wanna …?" / "Let\'s …".', 'Agree quickly ("Sounds good", "Sure"), refuse politely ("Sorry, I can\'t"), or counter-propose ("How about …?").', 'Plan a movie or cafe outing with time, place, and how to meet.', 'Read a cinema listing and pick a showtime.'],
    task: 'Picture inviting a classmate at Massachusetts Institute of Technology to see a movie on Friday — pick the film, the time, the meeting spot, and how to pay.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Suggestion phrase sounds',
    goals: ['Reduce "want to" → "wanna" /ˈwɒnə/ in casual speech: "Wanna grab coffee?".', 'Reduce "going to" → "gonna" /ˈɡʌnə/: "We\'re gonna see a movie".', 'Use rising intonation on suggestion questions: "Shall we go? ↗".'],
    task: 'Read each suggestion form aloud with the correct intonation.' },
  { id: ACT.vocabularyMovie, section: 'Vocabulary I', title: 'Movie & entertainment',
    goals: ['Use movie, theater / cinema, ticket, showtime, screening, book / reserve, subtitles, dubbed.'],
    task: 'Plan one movie outing using 5 of these words.' },
  { id: ACT.vocabularyOutings, section: 'Vocabulary II', title: 'Outing places + activities',
    goals: ['Use cafe, mall, park, museum, bar, concert + grab coffee, hang out, catch up, check out, see.'],
    task: 'Pair places with activities.' },
  { id: ACT.grammarPoliteShall, section: 'Grammar I', title: '"Shall we …?" / "Why don\'t we …?" — polite suggestion',
    goals: ['Use "Shall we + bare verb?" (slightly formal/UK).', 'Use "Why don\'t we + bare verb?" (very common).', 'Use "How about + V-ing / N?" for soft suggestion.'],
    task: 'Make three polite suggestions.' },
  { id: ACT.grammarCasualWanna, section: 'Grammar II', title: '"Wanna …?" / "Let\'s …" — casual',
    goals: ['Use "Wanna + bare verb?" (very casual).', 'Use "Let\'s + bare verb" (suggestion as a group).', '"Let\'s not + V" for negative.'],
    task: 'Make three casual invitations.' },
  { id: ACT.grammarAgreeing, section: 'Grammar III', title: 'Agreeing, refusing, counter-proposing',
    goals: ['Accept: "Sounds good / Sure / I\'d love to".', 'Refuse politely: "Sorry, I can\'t / Maybe next time".', 'Counter-propose: "How about + N/V-ing?" / "What if we + V?".'],
    task: 'Practice 3 accept/refuse/counter exchanges.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A movie listing',
    goals: ['Read a cinema schedule.'],
    task: 'Identify movie, times, prices, format.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Movie plan',
    goals: ['Follow a 6-turn movie-planning dialogue.'],
    task: 'Reproduce with your own plan.' },
  { id: ACT.writing, section: 'Writing', title: 'A text invite',
    goals: ['Write a 3-4 line text/chat message invite.'],
    task: 'Write your own invite.' },
  { id: ACT.culture, section: 'Culture Note', title: 'AMC, Regal, Cineworld and English-speaking movie culture',
    goals: ['Know AMC/Regal/Cinemark (US), Cineworld/Vue/Odeon (UK), Hoyts/Event (AU).', 'Understand subscription passes (AMC A-List, Cineworld Unlimited).'],
    task: 'Pick which chain and option you would choose.' },
  { id: ACT.task, section: 'Task', title: 'Plan a Friday movie',
    goals: ['Combine suggestion, agreement, time, place, ticket-booking.'],
    task: 'Plan a Friday movie with the AI tutor.' },
];

const lesson = {
  title: 'Level 1 · Unit 20: Shall we see a movie? — Suggestions & Plans',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'making-suggestions-en', label: 'Making suggestions', goal: 'Use "Shall we / Why don\'t we / Let\'s / Wanna" by register.' },
    { id: 'accepting-refusing-en', label: 'Accepting or refusing', goal: 'Use "Sounds good / Sorry, I can\'t".' },
    { id: 'counter-proposing-en', label: 'Counter-proposing', goal: 'Use "How about …?" / "What if …?".' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'suggestions and plans', 'By end: invite someone out, accept/refuse, counter-propose, and plan time/place.', 'word', 'Functions: invite · accept · refuse · counter · plan time/place.', 'Five social planning micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Friday movie plan', 'You see a movie poster outside the student union at MIT and want to invite a classmate to watch it on Friday after class.', 'word', 'You: "Wanna grab the new Marvel movie Friday?" — Friend: "Sounds great. What time?"', 'A typical young-adult invitation.', null, [ACT.orientation]),

    createContentItem('"Wanna" → /ˈwɒnə/', '/ˈwɒnə/', 'Casual contraction of "want to". For invitations.', 'word', 'Wanna grab coffee?', 'Don\'t use in formal writing.', null, [ACT.pronunciation]),
    createContentItem('"Gonna" → /ˈɡʌnə/', '/ˈɡʌnə/', 'Casual contraction of "going to" (future).', 'word', 'We\'re gonna see a movie.', 'Don\'t use in formal writing.', null, [ACT.pronunciation]),
    createContentItem('Rising intonation on Yes/No questions', '/ˈʃæl wi ɡoʊ/ ↗', 'Suggestion questions END with rising pitch.', 'word', 'Shall we go? ↗ — Want to grab coffee? ↗', 'Falling pitch = statement; rising = open question.', null, [ACT.pronunciation]),
    createContentItem('"Let\'s" /lɛts/', '/lɛts/', 'Contraction of "let us". Always /lɛts/, one syllable.', 'word', 'Let\'s eat. — Let\'s go.', 'Never spelled or pronounced "let us" in this idiom.', null, [ACT.pronunciation]),

    createContentItem('movie / film', '/ˈmuːvi/ /fɪlm/', 'a feature-length show', 'word', 'I want to see the new movie.', 'US: "movie". UK: "film".', null, [ACT.vocabularyMovie]),
    createContentItem('theater / cinema', '/ˈθiːətər/ /ˈsɪnəmə/', 'place to watch movies', 'word', 'The theater is downtown.', 'US: "movie theater". UK: "cinema".', null, [ACT.vocabularyMovie]),
    createContentItem('ticket', '/ˈtɪkɪt/', 'paper or e-pass to enter', 'word', 'How much is a ticket?', '"Movie ticket" or just "ticket".', null, [ACT.vocabularyMovie]),
    createContentItem('showtime / screening', '/ˈʃoʊtaɪm/ /ˈskriːnɪŋ/', 'the time a movie plays', 'word', 'The 7:30 showtime is sold out.', '"Screening" is more formal.', null, [ACT.vocabularyMovie]),
    createContentItem('book / reserve', '/bʊk/ /rɪˈzɜːrv/', 'arrange in advance', 'word', 'I\'ll book the tickets online.', 'UK: "book". US: "book" or "reserve" — both common.', null, [ACT.vocabularyMovie]),
    createContentItem('subtitles', '/ˈsʌbtaɪtəlz/', 'translated text on screen', 'word', 'Are there English subtitles?', 'Always plural.', null, [ACT.vocabularyMovie]),
    createContentItem('dubbed', '/dʌbd/', 'voice-acted in another language', 'word', 'Is the movie dubbed or subbed?', '"Sub-titled" vs "dubbed" — common contrast.', null, [ACT.vocabularyMovie]),
    createContentItem('genre', '/ˈʒɒnrə/', 'type of movie', 'word', 'What genre do you like?', 'Action, comedy, drama, horror, romance, sci-fi, thriller.', null, [ACT.vocabularyMovie]),
    createContentItem('popcorn / snacks', '/ˈpɒpkɔːrn/', 'concession-stand food', 'word', 'Want some popcorn?', 'Common combo: popcorn + soda.', null, [ACT.vocabularyMovie]),
    createContentItem('IMAX / 3D / 4DX', '/ˈaɪmæks/', 'premium movie formats', 'word', 'Let\'s see it in IMAX.', 'Premium = larger screen, motion seats, higher price.', null, [ACT.vocabularyMovie]),

    createContentItem('cafe / coffee shop', '/kæˈfeɪ/ /ˈkɒfi ʃɒp/', 'casual drink + light food', 'word', 'Let\'s meet at the cafe.', 'Cafe and coffee shop are interchangeable.', null, [ACT.vocabularyOutings]),
    createContentItem('mall / shopping center', '/mɔːl/', 'enclosed shopping complex', 'word', 'Let\'s go to the mall.', 'US: "mall". UK: "shopping centre".', null, [ACT.vocabularyOutings]),
    createContentItem('park', '/pɑːrk/', 'green public space', 'word', 'Want to walk in the park?', 'Often used for relaxing dates.', null, [ACT.vocabularyOutings]),
    createContentItem('museum / gallery', '/mjuːˈziːəm/ /ˈɡæləri/', 'cultural attraction', 'word', 'There\'s a new exhibit at the museum.', 'Museum = artifacts; gallery = art focus.', null, [ACT.vocabularyOutings]),
    createContentItem('bar / pub', '/bɑːr/ /pʌb/', 'drinks venue', 'word', 'Wanna grab a drink at the pub?', 'UK: "pub" — casual, often serves food. US: "bar".', null, [ACT.vocabularyOutings]),
    createContentItem('concert / show', '/ˈkɒnsərt/ /ʃoʊ/', 'live music or theater', 'word', 'I have concert tickets.', '"Show" is broader (concert, comedy, theater).', null, [ACT.vocabularyOutings]),
    createContentItem('grab + N', '/ɡræb/', 'casual: have/get casually', 'word', 'Wanna grab lunch? — Let\'s grab a drink.', 'Very common casual register.', null, [ACT.vocabularyOutings]),
    createContentItem('hang out', '/hæŋ aʊt/', 'spend casual time together', 'word', 'Let\'s hang out this weekend.', 'Unstructured time, no specific activity.', null, [ACT.vocabularyOutings]),
    createContentItem('catch up', '/kætʃ ʌp/', 'reconnect / share news', 'word', 'We need to catch up — it\'s been months.', 'Used when you haven\'t seen someone in a while.', null, [ACT.vocabularyOutings]),
    createContentItem('check out + N', '/tʃɛk aʊt/', 'casual: visit / try', 'word', 'Let\'s check out that new cafe.', 'Implies novelty/exploration.', null, [ACT.vocabularyOutings]),

    createContentItem(
      '"Shall we + bare verb?"',
      'polite/formal suggestion',
      'Standard polite suggestion form, especially in UK.',
      'sentence',
      'Shall we go to the movies tonight? — Shall we meet at 7?',
      'Slightly formal in US but normal in UK. Use with new friends, professional contexts.',
      [
        { target: 'Shall we + bare V?', english: 'polite suggestion' },
        { target: 'Shall I + V?', english: 'offering to do something' },
      ],
      [ACT.grammarPoliteShall],
    ),
    createContentItem(
      '"Why don\'t we + bare verb?"',
      'very common polite suggestion',
      'Soft, friendly suggestion. Works in any register.',
      'sentence',
      'Why don\'t we see a movie? — Why don\'t we meet at the cafe instead?',
      'Despite the negative form, it\'s positive — proposing an idea.',
      [
        { target: 'Why don\'t we + V?', english: 'soft suggestion' },
        { target: 'Why don\'t you + V?', english: 'advice for one person' },
      ],
      [ACT.grammarPoliteShall],
    ),
    createContentItem(
      '"How about + V-ing / noun?"',
      'lightest suggestion',
      'Open-ended; offers an idea without pressure.',
      'sentence',
      'How about seeing a movie? — How about coffee instead?',
      'Followed by V-ing OR a noun. Most polite/neutral form.',
      [
        { target: 'How about + V-ing?', english: 'verb suggestion' },
        { target: 'How about + N?', english: 'thing suggestion' },
        { target: 'What about + V-ing/N?', english: 'identical meaning' },
      ],
      [ACT.grammarPoliteShall],
    ),

    createContentItem(
      '"Wanna + bare verb?"',
      'very casual',
      'Friends only. Most casual register.',
      'sentence',
      'Wanna grab coffee? — Wanna catch the new Marvel movie?',
      'Don\'t use with professors or strangers. Written: avoid in formal contexts.',
      [
        { target: 'Wanna + V?', english: 'casual invitation' },
        { target: 'You wanna + V?', english: 'slightly clearer subject' },
      ],
      [ACT.grammarCasualWanna],
    ),
    createContentItem(
      '"Let\'s + bare verb"',
      'group suggestion',
      'Includes speaker AND listener. Default group-action form.',
      'sentence',
      'Let\'s go! — Let\'s meet at 6. — Let\'s eat first, then movie.',
      'Not a question — a statement of plan. Reply usually accepts ("Sounds good").',
      [
        { target: 'Let\'s + V', english: 'group action' },
        { target: 'Let\'s not + V', english: 'negative: "Let\'s not be late"' },
        { target: 'Let\'s + V, shall we?', english: 'tag for confirmation' },
      ],
      [ACT.grammarCasualWanna],
    ),
    createContentItem(
      '"Do you want to + V?"',
      'standard neutral invitation',
      'Direct, neutral form. Works in any register.',
      'sentence',
      'Do you want to see a movie? — Do you want to grab dinner first?',
      'Often contracts to "Wanna" in speech.',
      null,
      [ACT.grammarCasualWanna],
    ),

    createContentItem(
      'Accepting an invitation',
      'standard yes-replies',
      'Choose by enthusiasm.',
      'sentence',
      'Sounds great! — Sure! — I\'d love to. — Sounds good. — Yeah, let\'s do it.',
      'Match the invitation\'s register: casual invite → casual yes.',
      [
        { target: 'Sounds good / great', english: 'standard enthusiastic accept' },
        { target: 'I\'d love to', english: 'warm, polite' },
        { target: 'Sure / OK', english: 'neutral accept' },
      ],
      [ACT.grammarAgreeing],
    ),
    createContentItem(
      'Refusing politely',
      'standard no-replies',
      'Always soften with reason + future opener.',
      'sentence',
      'Sorry, I can\'t this Friday. — Thanks, but I have other plans. — Maybe next week?',
      'Plain "No" is rude. Always: apology + reason + alternative.',
      [
        { target: 'Sorry, I can\'t (because …)', english: 'soft refuse + reason' },
        { target: 'Maybe next time', english: 'leave door open' },
        { target: 'Thanks, but …', english: 'polite refuse' },
      ],
      [ACT.grammarAgreeing],
    ),
    createContentItem(
      'Counter-proposing',
      'offering an alternative',
      'After refusing or wanting to change, offer another option.',
      'sentence',
      'Sorry Friday is bad — how about Saturday? — How about we do dinner instead? — What if we move it to 8?',
      '"How about + N/V-ing" or "What if + clause" — both standard.',
      [
        { target: 'How about + alternative?', english: 'simple counter' },
        { target: 'What if we + V?', english: 'hypothetical counter' },
        { target: '... instead?', english: 'tag for swap' },
      ],
      [ACT.grammarAgreeing],
    ),

    createContentItem(
      'A cinema listing',
      'reading practice',
      'Read this cinema schedule.',
      'sentence',
      'AMC Times Square 25\nDune: Part Two (PG-13, 2h 46m)\nFri Nov 22\n2:00 PM (Standard) · 5:30 PM (IMAX) · 9:00 PM (4DX)\nTickets: Standard $15 · IMAX $22 · 4DX $28\nSubtitles: English (closed captions available)',
      'Standard US cinema listing format.',
      [
        { target: 'PG-13', english: 'rating' },
        { target: '2h 46m', english: 'runtime' },
        { target: 'Standard / IMAX / 4DX', english: 'format options' },
        { target: 'closed captions', english: 'subtitles for hearing-impaired' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Comprehension',
      'answer in English',
      'Use full sentences.',
      'sentence',
      'Q1: What movie is showing? · Q2: How long is it? · Q3: What\'s the cheapest format? · Q4: Are there subtitles?',
      'Use present tense.',
      [
        { target: 'A1: Dune: Part Two is showing.', english: 'movie name' },
        { target: 'A2: 2 hours and 46 minutes.', english: 'runtime' },
        { target: 'A3: Standard, at $15.', english: 'cheapest format' },
        { target: 'A4: Yes, English closed captions.', english: 'subtitles' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Planning a movie',
      'two friends',
      'A casual planning dialogue.',
      'conversation',
      'Alex: Hey, wanna catch the new Dune Friday?\nJordan: Ooh, sounds great! What time?\nAlex: How about 7:30? They have IMAX.\nJordan: Let\'s do it. Should we book online?\nAlex: Yeah, IMAX sells out fast. I\'ll book if you Venmo me later.\nJordan: Deal. Want to grab dinner first?\nAlex: Sure — meet at 5:30 at the burger place?\nJordan: Perfect. See you Friday!',
      'Note: "wanna" (casual), "Let\'s do it" (accept), "Want to grab" (alternative), "Sure" (accept).',
      [
        { target: 'wanna catch the new Dune', english: 'casual invitation' },
        { target: 'How about 7:30?', english: 'counter / specify' },
        { target: 'Should we book online?', english: 'logistics question' },
        { target: 'meet at 5:30 at the burger place?', english: 'time + place' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'Polite plan',
      'formal register',
      'A polite plan between newer acquaintances.',
      'conversation',
      'Min-su: Sarah, would you like to see a movie this weekend?\nSarah: That sounds lovely! Which one?\nMin-su: How about the new Marvel one? I heard it\'s good.\nSarah: Marvel\'s not really my thing — would a comedy work?\nMin-su: Sure, there\'s a new Pixar comedy at AMC.\nSarah: Perfect. Shall we say Saturday at 6?\nMin-su: Saturday at 6 works. I\'ll book the tickets.\nSarah: Thanks, I\'ll cover dinner after.',
      'Note: "would you like to" (formal), "Shall we say…" (polite time-setting), counter-proposing politely.',
      [
        { target: 'would you like to see', english: 'polite invitation' },
        { target: 'Marvel\'s not really my thing', english: 'soft refuse' },
        { target: 'would a comedy work?', english: 'counter-propose' },
        { target: 'Shall we say Saturday at 6?', english: 'polite time-set' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'Writing model',
      'text invite template',
      'Casual text/chat invite.',
      'sentence',
      'Hey [name]! Wanna [activity] [day]? I was thinking [time/place]. Let me know!',
      'Four elements: hey + invite + suggestion + open close.',
      null, [ACT.writing],
    ),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write a 3-4 line text invite to a friend.',
      'sentence',
      'Example: Hey Min-su! Wanna catch the new Marvel movie Saturday? I was thinking the 7 PM at AMC Gumi. Dinner first? Let me know!',
      'Keep tone friendly and concrete.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Cinema chains',
      'US / UK / AU overview',
      'US: AMC, Regal, Cinemark — major chains. UK: Cineworld, Vue, Odeon. AU: Hoyts, Event Cinemas. Subscription passes (AMC A-List, Cineworld Unlimited) — unlimited movies per month for a fixed fee.',
      'sentence',
      'AMC A-List: 3 movies/week for ~$25/month — popular among movie fans.',
      'Subscription plans have transformed how often Americans go to the movies.',
      [
        { target: 'AMC / Regal / Cinemark (US)', english: 'biggest US chains' },
        { target: 'Cineworld / Vue / Odeon (UK)', english: 'biggest UK chains' },
        { target: 'subscription passes', english: 'unlimited movies for monthly fee' },
        { target: 'IMAX, 4DX, Dolby', english: 'premium formats' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Movie etiquette',
      'norms',
      'Phones on silent or off; no talking; no kicking seats; eat quietly. Many theaters offer reserved seating — pick when buying.',
      'sentence',
      'Most US theaters now have reclining seats and reserved seating.',
      'Concession food (popcorn, soda) is expected; outside food is technically banned.',
      [
        { target: 'phones silent or off', english: 'standard etiquette' },
        { target: 'reserved seating', english: 'pick seat at booking' },
        { target: 'no outside food (technically)', english: 'rarely enforced strictly' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'Task: Plan a Friday movie',
      'consolidation task',
      'Roleplay: Invite the AI tutor to see a movie. Negotiate time, place, format.',
      'conversation',
      'You: [casual or polite invitation]\nTutor: [accept or counter-propose]\nYou: [specify time/place/format]\nTutor: [logistics question]\nYou: [answer + offer to book or share cost]\nTutor: [confirm]\nYou: [closing]',
      'AI tutor will play your friend.',
      [
        { target: 'Wanna / Shall we / How about', english: 'pick by register' },
        { target: 'How about + alternative', english: 'counter-propose' },
        { target: 'I\'ll book the tickets', english: 'logistics' },
        { target: 'See you Friday!', english: 'closing' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
