// Level 3 Cluster 5 — Modifiers
// Patterns: adjective order, adverbs of degree, intensifiers + hedges, comparatives + superlatives.

const createContentItem = (
  target, ipa, note, type = 'word',
  example = '', exampleNote = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: target, romanization: ipa, nativeText: note, pronunciation: ipa,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.english, korean: b.target, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'en-l3c5-orientation',
  overview: 'en-l3c5-overview',
  adjectiveOrder: 'en-l3c5-adj-order',
  adverbDegree: 'en-l3c5-adv-degree',
  intensifiersHedges: 'en-l3c5-int-hedge',
  comparatives: 'en-l3c5-comp',
  reading: 'en-l3c5-reading',
  speaking: 'en-l3c5-speaking',
  writing: 'en-l3c5-writing',
  task: 'en-l3c5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Order English adjectives correctly (Opinion-Size-Age-Shape-Color-Origin-Material-Purpose).', 'Use adverbs of degree precisely (quite, rather, fairly, pretty).', 'Use intensifiers (absolutely, totally) and hedges (sort of, kind of).', 'Form comparatives + superlatives + parallel comparison.'],
    task: 'Picture writing a vivid product review — your description needs precise modifiers.' },
  { id: ACT.overview, section: 'Patterns', title: 'Modifiers overview',
    goals: ['Recognize 4 layers of modifier grammar.'],
    task: 'Map each modifier type to its function.' },
  { id: ACT.adjectiveOrder, section: 'Pattern 1', title: 'Adjective order: OSASCOMP',
    goals: ['Order: Opinion-Size-Age-Shape-Color-Origin-Material-Purpose + Noun.', '"A beautiful, small, old, round, brown, Italian, wooden coffee table."'],
    task: 'Order 5 adjectives.' },
  { id: ACT.adverbDegree, section: 'Pattern 2', title: 'Adverbs of degree',
    goals: ['British nuance: "quite" = "very" (UK) or "moderately" (US).', '"Rather" — moderate + slightly negative.', '"Fairly / pretty" — moderate.', '"Very / really" — strong.'],
    task: 'Use 4 different degrees.' },
  { id: ACT.intensifiersHedges, section: 'Pattern 3', title: 'Intensifiers + hedges',
    goals: ['Intensifiers with non-gradable adj: "absolutely amazing", "totally exhausted".', 'Hedges: "sort of / kind of + adj/V".', 'Hedge softens; intensifier amplifies.'],
    task: 'Intensify 3 + hedge 3.' },
  { id: ACT.comparatives, section: 'Pattern 4', title: 'Comparatives + superlatives + parallel',
    goals: ['Form: -er/more + than; the + -est/most.', 'Parallel: "the more X, the more Y" (correlative).', 'Irregular: good→better→best; bad→worse→worst.'],
    task: 'Compare 3 things with each pattern.' },
  { id: ACT.reading, section: 'Reading', title: 'Product review',
    goals: ['Read a vivid product review.'],
    task: 'Identify each modifier type.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Vivid description',
    goals: ['Describe an object with adjective order + degree adverbs.'],
    task: 'Describe a personal possession in detail.' },
  { id: ACT.writing, section: 'Writing', title: 'Review paragraph',
    goals: ['Write a 5-sentence review using all 4 modifier types.'],
    task: 'Write your own review.' },
  { id: ACT.task, section: 'Task', title: 'Product review interview',
    goals: ['Combine all 4 modifier patterns in an interview.'],
    task: 'Review a product with the AI tutor.' },
];

const lesson = {
  title: 'Level 3 · Cluster 5: Modifiers — adjective order + degree + intensifiers + comparison',
  category: 'daily-life',
  difficulty: 'advanced',
  targetLang: 'en', nativeLang: 'en',
  track: 'textbook', lessonType: 'grammar',
  activities,
  expressionPractice: [
    { id: 'adj-order-en', label: 'Adjective order', goal: 'OSASCOMP — Opinion-Size-Age-Shape-Color-Origin-Material-Purpose.' },
    { id: 'degree-adverbs-en', label: 'Degree adverbs', goal: 'Distinguish quite (UK vs US), rather, fairly, pretty.' },
    { id: 'intensifier-hedge-en', label: 'Intensifier vs hedge', goal: 'absolutely vs sort of.' },
  ],
  relatedPools: ['topic-grammar'],
  content: [
    createContentItem('Lesson goal', 'modifiers', 'By end: order adjectives correctly, use degree adverbs precisely, intensify + hedge, compare.', 'word', 'Functions: order · grade · intensify · compare.', 'Four modifier micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'product review', 'You\'re writing an Amazon review for the wireless earbuds you bought. Your description needs precise modifiers: opinion + size + color, then "really good for the price", then a comparison to AirPods.', 'word', 'You: "These are fairly small, sleek, black wireless earbuds. They\'re absolutely incredible for the price — almost as good as AirPods Pro but half the cost."', 'Standard product review.', null, [ACT.orientation]),

    createContentItem('Four modifier layers', 'patterns', 'OSASCOMP order (adjective sequence). Degree adverbs (how much). Intensifiers + hedges (amplifier/softener). Comparatives + superlatives (relative degree).', 'word', 'Each modifier type has its own rules.', 'Layer them carefully.', null, [ACT.overview]),

    createContentItem(
      'OSASCOMP adjective order',
      'standard English order',
      'Opinion → Size → Age → Shape → Color → Origin → Material → Purpose.',
      'sentence',
      'a beautiful, small, old, round, brown, Italian, wooden coffee table.\nOrder: Opinion (beautiful) → Size (small) → Age (old) → Shape (round) → Color (brown) → Origin (Italian) → Material (wooden) → Purpose (coffee).',
      'Native speakers feel wrong order instantly. Memorize OSASCOMP.',
      [
        { target: 'O: Opinion (beautiful, lovely)', english: 'first' },
        { target: 'S: Size (small, big)', english: 'second' },
        { target: 'A: Age (old, new, young)', english: 'third' },
        { target: 'S: Shape (round, square)', english: 'fourth' },
        { target: 'C: Color (red, brown)', english: 'fifth' },
        { target: 'O: Origin (Italian, Korean)', english: 'sixth' },
        { target: 'M: Material (wooden, plastic)', english: 'seventh' },
        { target: 'P: Purpose (coffee, sleeping)', english: 'eighth, closest to noun' },
      ],
      [ACT.adjectiveOrder],
    ),
    createContentItem(
      'Commas in adjective lists',
      'comma vs no comma',
      'Use commas between coordinate adjectives (same category); no commas between cumulative (different categories).',
      'sentence',
      'COORDINATE (commas): a kind, generous, loyal friend (all opinion → commas).\nCUMULATIVE (no commas): a small old wooden chair (size + age + material → no commas).',
      'Test: if you can swap order or insert "and", use a comma.',
      [
        { target: 'coordinate adjs (same type) → commas', english: 'opinion + opinion + opinion' },
        { target: 'cumulative adjs (different types) → no commas', english: 'OSASCOMP cascade' },
      ],
      [ACT.adjectiveOrder],
    ),

    createContentItem(
      'Degree adverbs',
      'how much',
      'Fine-grained: each has a specific range.',
      'sentence',
      'a little / slightly / somewhat (weak) < fairly / pretty / rather (moderate) < quite (UK strong; US moderate) < very / really (strong) < extremely / incredibly (extreme).',
      'UK "quite" ≈ "very". US "quite" ≈ "moderately". The same word splits in meaning across dialects.',
      [
        { target: 'slightly / a little', english: 'mild' },
        { target: 'fairly / pretty', english: 'moderate' },
        { target: 'rather (slightly negative)', english: 'moderate-negative' },
        { target: 'quite (UK strong, US moderate)', english: 'register-specific' },
        { target: 'very / really', english: 'strong' },
        { target: 'extremely / incredibly', english: 'extreme' },
      ],
      [ACT.adverbDegree],
    ),
    createContentItem(
      '"rather" vs "quite" vs "fairly"',
      'subtle differences',
      'Three near-synonyms with different feels.',
      'sentence',
      'The food was rather disappointing. (slightly negative)\nThe food was quite good. (UK = very good; US = moderate)\nThe food was fairly priced. (moderate, neutral)',
      'Use "rather" when something is unexpectedly negative. "Fairly" is the neutral default.',
      [
        { target: 'rather + adj = mildly + (often negative)', english: 'mild + negative' },
        { target: 'quite + adj = very (UK) / moderately (US)', english: 'dialect split' },
        { target: 'fairly + adj = neutrally moderate', english: 'safe neutral' },
      ],
      [ACT.adverbDegree],
    ),

    createContentItem(
      'Intensifiers with non-gradable adjectives',
      'absolute words',
      'Non-gradable adjectives (perfect, amazing, terrible, exhausted) take "absolutely", not "very".',
      'sentence',
      'CORRECT: absolutely amazing, totally exhausted, completely impossible.\nWRONG: very perfect, very amazing, very terrified.',
      'Non-gradable adjectives are already at the extreme — "very" makes no sense.',
      [
        { target: 'absolutely / totally / completely', english: 'with non-gradable adj' },
        { target: 'utterly / entirely', english: 'formal intensifiers' },
        { target: 'NOT: very + non-gradable', english: 'common ESL error' },
      ],
      [ACT.intensifiersHedges],
    ),
    createContentItem(
      'Hedges — softening',
      'sort of / kind of',
      'Make a statement less certain or definite.',
      'sentence',
      'It\'s sort of weird. (mild "weird")\nI\'m kind of tired. (somewhat tired)\nThe movie was, like, kind of confusing? (very casual, hedged)',
      'Casual speech. Avoid in writing.',
      [
        { target: 'sort of / kind of + adj', english: 'soften adjective' },
        { target: 'sort of / kind of + V', english: 'soften verb: "I sort of agreed"' },
        { target: 'NOT in formal writing', english: 'avoid in essays' },
      ],
      [ACT.intensifiersHedges],
    ),

    createContentItem(
      'Comparatives + superlatives',
      'forming patterns',
      '-er for short adjectives, "more" for long. Same with -est / "most".',
      'sentence',
      'short (1-2 syllables): tall → taller → tallest. happy → happier → happiest.\nlong (2+ syllables): expensive → more expensive → most expensive. interesting → more interesting → most interesting.',
      'Irregular: good → better → best. Bad → worse → worst. Little → less → least. Many/much → more → most.',
      [
        { target: 'short adj + -er / -est', english: 'tall, taller, tallest' },
        { target: 'long adj + more / most', english: 'expensive, more expensive' },
        { target: 'irregular: good/bad/many', english: 'better/worse/more' },
        { target: 'than (after comparative)', english: '"taller than her"' },
      ],
      [ACT.comparatives],
    ),
    createContentItem(
      'Parallel comparison: "the + comp, the + comp"',
      'correlative',
      'Two parallel changes that go together.',
      'sentence',
      'The harder you work, the more you earn. — The older I get, the wiser I feel. — The faster, the better.',
      'Used reviewed from L2 Unit 5 — common high-register move.',
      [
        { target: 'the + comp + S + V, the + comp + S + V', english: 'standard parallel' },
        { target: 'the + comp, the + comp', english: 'short form: "the more, the merrier"' },
        { target: 'common idioms: the sooner the better', english: 'fixed phrases' },
      ],
      [ACT.comparatives],
    ),
    createContentItem(
      '"as + adj + as" — equality',
      'equal comparison',
      'Compare two equal things.',
      'sentence',
      'She\'s as tall as her brother. — These earbuds are almost as good as AirPods. — Not as expensive as I thought.',
      'Negative: "not as + adj + as".',
      [
        { target: 'as + adj + as + N', english: 'equality' },
        { target: 'not as + adj + as + N', english: 'less than' },
        { target: 'almost / nearly / quite as + adj + as', english: 'soften' },
      ],
      [ACT.comparatives],
    ),

    createContentItem(
      'Product review',
      'reading practice',
      'Identify each modifier type.',
      'sentence',
      'I bought these small, sleek, black wireless earbuds last month. They\'re absolutely incredible — quite a surprise for the price. The bass is fairly strong, though slightly less defined than the AirPods Pro I owned before. The case is rather small, almost as compact as a tube of lip balm. The battery life is the best I\'ve tested at this price point. The more I use them, the more impressed I am.',
      'All 4 modifier patterns.',
      [
        { target: 'small, sleek, black wireless earbuds', english: 'OSASCOMP order' },
        { target: 'absolutely incredible / quite a surprise', english: 'intensifier + degree' },
        { target: 'fairly strong / slightly less defined / rather small', english: 'degree adverbs' },
        { target: 'almost as compact as', english: 'equality with softener' },
        { target: 'the best I\'ve tested', english: 'superlative' },
        { target: 'the more I use them, the more impressed I am', english: 'parallel' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'Speaking — describe a possession',
      'extended turn',
      'Describe an object with precise modifiers.',
      'sentence',
      'My favorite mug is a small, old, chipped, white ceramic coffee mug. It\'s nothing special, but I find it absolutely charming. It\'s slightly heavier than modern mugs, which makes it feel more substantial. It holds heat better than any mug I\'ve owned. The older it gets, the more I love it.',
      'Frame: OSASCOMP + intensifier + degree + comparative + parallel.',
      null,
      [ACT.speaking],
    ),

    createContentItem(
      'Writing prompt',
      'review paragraph',
      'Write a 5-sentence product review using all 4 modifier patterns.',
      'sentence',
      'Example: I just got this gorgeous, large, modern, black leather work bag. It\'s absolutely perfect for my commute. The straps are slightly thicker than my old bag, making it more comfortable on long walks. It\'s by far the most spacious bag I\'ve owned. The more I carry it, the more I appreciate the design.',
      'Required: OSASCOMP order, intensifier, degree adverb, comparative/superlative.',
      null, [ACT.writing],
    ),

    createContentItem(
      'Task: Product review interview',
      'consolidation task',
      'AI tutor interviews you about a product you recently bought.',
      'conversation',
      'Tutor: What did you buy?\nYou: [OSASCOMP description]\nTutor: How is it?\nYou: [intensifier or hedge]\nTutor: How does it compare to alternatives?\nYou: [comparative]\nTutor: [follow-up]\nYou: [parallel comparison]',
      'AI tutor plays the reviewer.',
      [
        { target: 'OSASCOMP order', english: 'adjective sequencing' },
        { target: 'degree adverb', english: 'precise grading' },
        { target: 'intensifier / hedge', english: 'amplify or soften' },
        { target: 'comparative / superlative', english: 'relative degree' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
