// Comprehensive Korean vocabulary database (838+ words)
// Organized by category for better learning

const flashcardData = [
  // GREETINGS (140)
  { korean: "안녕하세요", english: "Hello", romanization: "annyeonghaseyo", category: "greetings" },
  { korean: "안녕", english: "Hi (informal)", romanization: "annyeong", category: "greetings" },
  { korean: "안녕히 가세요", english: "Goodbye (to leaving person)", romanization: "annyeonghi gaseyo", category: "greetings" },
  { korean: "안녕히 계세요", english: "Goodbye (when you leave)", romanization: "annyeonghi gyeseyo", category: "greetings" },
  { korean: "감사합니다", english: "Thank you", romanization: "gamsahamnida", category: "greetings" },
  { korean: "고맙습니다", english: "Thank you (alternative)", romanization: "gomapseumnida", category: "greetings" },
  { korean: "죄송합니다", english: "I'm sorry", romanization: "joesonghamnida", category: "greetings" },
  { korean: "미안합니다", english: "I'm sorry (less formal)", romanization: "mianhamnida", category: "greetings" },
  { korean: "실례합니다", english: "Excuse me", romanization: "sillyehamnida", category: "greetings" },
  { korean: "괜찮아요", english: "It's okay", romanization: "gwaenchanayo", category: "greetings" },
  { korean: "천만에요", english: "You're welcome", romanization: "cheonmaneyo", category: "greetings" },
  { korean: "만나서 반갑습니다", english: "Nice to meet you", romanization: "mannaseo bangapseumnida", category: "greetings" },
  { korean: "잘 지냈어요?", english: "How have you been?", romanization: "jal jinaesseoyo", category: "greetings" },
  { korean: "오래간만입니다", english: "Long time no see", romanization: "oraegamanimnida", category: "greetings" },
  { korean: "좋은 아침입니다", english: "Good morning", romanization: "joeun achimimnida", category: "greetings" },
  { korean: "안녕히 주무세요", english: "Good night", romanization: "annyeonghi jumuseyo", category: "greetings" },
  { korean: "축하합니다", english: "Congratulations", romanization: "chukhahamnida", category: "greetings" },
  { korean: "환영합니다", english: "Welcome", romanization: "hwanyeonghamnida", category: "greetings" },
  { korean: "수고하셨습니다", english: "Thank you for your hard work", romanization: "sugohasyeotseumnida", category: "greetings" },
  { korean: "잘 먹겠습니다", english: "I will eat well (before meal)", romanization: "jal meokgetseumnida", category: "greetings" },
  { korean: "잘 먹었습니다", english: "I ate well (after meal)", romanization: "jal meogeotseumnida", category: "greetings" },
  { korean: "건배", english: "Cheers", romanization: "geonbae", category: "greetings" },
  { korean: "다녀오겠습니다", english: "I'm leaving (said when leaving home)", romanization: "danyeogetseumnida", category: "greetings" },
  { korean: "다녀왔습니다", english: "I'm back", romanization: "danyeowasseumnida", category: "greetings" },
  { korean: "조심히 가세요", english: "Go safely", romanization: "josimhi gaseyo", category: "greetings" },
  { korean: "잘 가", english: "Bye (informal)", romanization: "jal ga", category: "greetings" },
  { korean: "또 봐요", english: "See you again", romanization: "tto bwayo", category: "greetings" },
  { korean: "나중에 봐요", english: "See you later", romanization: "najunge bwayo", category: "greetings" },
  { korean: "내일 봐요", english: "See you tomorrow", romanization: "naeil bwayo", category: "greetings" },
  { korean: "고마워", english: "Thanks (informal)", romanization: "gomawo", category: "greetings" },
  { korean: "고마워요", english: "Thanks (casual)", romanization: "gomawoyo", category: "greetings" },
  { korean: "아니에요", english: "Not at all", romanization: "anieyo", category: "greetings" },
  { korean: "미안해", english: "Sorry (informal)", romanization: "mianhae", category: "greetings" },
  { korean: "미안해요", english: "Sorry (casual)", romanization: "mianhaeyo", category: "greetings" },
  { korean: "반가워요", english: "Nice to meet you (casual)", romanization: "bangawoyo", category: "greetings" },
  { korean: "처음 뵙겠습니다", english: "How do you do (first meeting)", romanization: "cheoeum boepgetseumnida", category: "greetings" },
  { korean: "어떻게 지내세요?", english: "How are you?", romanization: "eotteoke jinaeseyo?", category: "greetings" },
  { korean: "잘 지내요?", english: "How are you? (casual)", romanization: "jal jinaeyo?", category: "greetings" },
  { korean: "어떠세요?", english: "How is it? / How are you?", romanization: "eotteoseyo?", category: "greetings" },
  { korean: "잘 지내요", english: "I\\", romanization: "jal jinaeyo", category: "greetings" },
  { korean: "잘 지냈어요", english: "I\\", romanization: "jal jinaesseoyo", category: "greetings" },
  { korean: "그냥 그래요", english: "So-so / Just okay", romanization: "geunyang geuraeyo", category: "greetings" },
  { korean: "주세요", english: "Please give me", romanization: "juseyo", category: "greetings" },
  { korean: "해 주세요", english: "Please do it", romanization: "hae juseyo", category: "greetings" },
  { korean: "도와주세요", english: "Please help me", romanization: "dowajuseyo", category: "greetings" },
  { korean: "가르쳐 주세요", english: "Please teach me", romanization: "gareuchyeo juseyo", category: "greetings" },
  { korean: "수고하세요", english: "Thank you for your work / Good luck", romanization: "sugohaseyo", category: "greetings" },
  { korean: "조심하세요", english: "Be careful / Take care", romanization: "josimhaseyo", category: "greetings" },
  { korean: "잘 자요", english: "Sleep well (casual)", romanization: "jal jayo", category: "greetings" },
  { korean: "좋은 아침이에요", english: "Good morning", romanization: "joeun achimieyo", category: "greetings" },
  { korean: "좋은 하루 되세요", english: "Have a good day", romanization: "joeun haru doeseyo", category: "greetings" },
  { korean: "즐거운 주말 보내세요", english: "Have a great weekend", romanization: "jeulgeoun jumal bonaeseyo", category: "greetings" },
  { korean: "한국 사람", english: "Korean person", romanization: "hanguk saram", category: "greetings" },
  { korean: "미국 사람", english: "American person", romanization: "miguk saram", category: "greetings" },
  { korean: "모르겠어요", english: "I don\\", romanization: "moreugesseoyo", category: "greetings" },
  { korean: "오랜만이에요", english: "Long time no see (casual)", romanization: "oraenmanieyo", category: "greetings" },
  { korean: "오랜만", english: "Long time (informal)", romanization: "oraenman", category: "greetings" },
  { korean: "수고 많으셨어요", english: "You worked hard", romanization: "sugo manheusyeosseoyo", category: "greetings" },
  { korean: "고생하셨어요", english: "You\\", romanization: "gosaenghasyeosseoyo", category: "greetings" },
  { korean: "애쓰셨어요", english: "You worked hard / Thanks for your effort", romanization: "aesseusyeosseoyo", category: "greetings" },
  { korean: "부탁드립니다", english: "I request / Please", romanization: "butakdeurimnida", category: "greetings" },
  { korean: "부탁해요", english: "Please (casual)", romanization: "butakaeyo", category: "greetings" },
  { korean: "도와주시겠어요?", english: "Could you help me?", romanization: "dowajusigesseoyo?", category: "greetings" },
  { korean: "괜찮으시면", english: "If it\\", romanization: "gwaenchanheusimyeon", category: "greetings" },
  { korean: "가능하시면", english: "If possible", romanization: "ganeunghasimyeon", category: "greetings" },
  { korean: "감사의 말씀 드립니다", english: "I express my gratitude", romanization: "gamsaui malsseum deurimnida", category: "greetings" },
  { korean: "정말 감사합니다", english: "Thank you very much", romanization: "jeongmal gamsahamnida", category: "greetings" },
  { korean: "대단히 감사합니다", english: "Thank you very much", romanization: "daedanhi gamsahamnida", category: "greetings" },
  { korean: "너무 고마워요", english: "Thank you so much", romanization: "neomu gomawoyo", category: "greetings" },
  { korean: "신세 졌습니다", english: "I\\", romanization: "sinse jyeotseumnida", category: "greetings" },
  { korean: "대단히 죄송합니다", english: "I\\", romanization: "daedanhi joesonghamnida", category: "greetings" },
  { korean: "진심으로 사과드립니다", english: "I sincerely apologize", romanization: "jinsimeuro sagwadeurimnida", category: "greetings" },
  { korean: "제 잘못입니다", english: "It\\", romanization: "je jalmositseumnida", category: "greetings" },
  { korean: "용서해 주세요", english: "Please forgive me", romanization: "yongseohae juseyo", category: "greetings" },
  { korean: "실례했습니다", english: "I was rude / Excuse me", romanization: "sillyehaetseumnida", category: "greetings" },
  { korean: "몸 조심하세요", english: "Take care of your health", romanization: "mom josimhaseyo", category: "greetings" },
  { korean: "건강하세요", english: "Stay healthy", romanization: "geonganghaseyo", category: "greetings" },
  { korean: "무리하지 마세요", english: "Don\\", romanization: "murihaji maseyo", category: "greetings" },
  { korean: "편히 쉬세요", english: "Rest comfortably", romanization: "pyeonhi swiseyo", category: "greetings" },
  { korean: "걱정하지 마세요", english: "Don\\", romanization: "geokjeonghaji maseyo", category: "greetings" },
  { korean: "축하해요", english: "Congratulations (casual)", romanization: "chukahaeyo", category: "greetings" },
  { korean: "잘했어요", english: "Well done", romanization: "jalhaesseoyo", category: "greetings" },
  { korean: "대단하시네요", english: "That\\", romanization: "daedanhasineyo", category: "greetings" },
  { korean: "유감입니다", english: "I\\", romanization: "yugamimnida", category: "greetings" },
  { korean: "어서 오세요", english: "Welcome", romanization: "eoseo oseyo", category: "greetings" },
  { korean: "오신 것을 환영합니다", english: "We welcome your visit", romanization: "osin geoseul hwanyeonghamnida", category: "greetings" },
  { korean: "새해 복 많이 받으세요", english: "Happy New Year", romanization: "saehae bok manhi badeuseyo", category: "greetings" },
  { korean: "즐거운 크리스마스 보내세요", english: "Merry Christmas", romanization: "jeulgeoun keuriseumaseu bonaeseyo", category: "greetings" },
  { korean: "추석 잘 보내세요", english: "Have a good Chuseok", romanization: "chuseok jal bonaeseyo", category: "greetings" },
  { korean: "확실해요", english: "I\\", romanization: "hwaksilhaeyo", category: "greetings" },
  { korean: "그렇지 않아요", english: "That\\", romanization: "geureochi anayo", category: "greetings" },
  { korean: "관심 있어요", english: "I\\", romanization: "gwansim isseoyo", category: "greetings" },
  { korean: "덥네요", english: "It\\", romanization: "deopneyo", category: "greetings" },
  { korean: "춥네요", english: "It\\", romanization: "chupneyo", category: "greetings" },
  { korean: "비가 와요", english: "It\\", romanization: "biga wayo", category: "greetings" },
  { korean: "눈이 와요", english: "It\\", romanization: "nuni wayo", category: "greetings" },
  { korean: "기분이 안 좋아요", english: "I don\\", romanization: "gibuni an johayo", category: "greetings" },
  { korean: "행복해요", english: "I\\", romanization: "haengbokhaeyo", category: "greetings" },
  { korean: "슬퍼요", english: "I\\", romanization: "seulpeoyo", category: "greetings" },
  { korean: "화가 나요", english: "I\\", romanization: "hwaga nayo", category: "greetings" },
  { korean: "피곤해요", english: "I\\", romanization: "pigonhaeyo", category: "greetings" },
  { korean: "지루해요", english: "I\\", romanization: "jiruhaeyo", category: "greetings" },
  { korean: "걱정돼요", english: "I\\", romanization: "geokjeongdwaeyo", category: "greetings" },
  { korean: "전화 주셔서 감사합니다", english: "Thank you for calling", romanization: "jeonhwa jusyeoseo gamsahamnida", category: "greetings" },
  { korean: "다시 전화할게요", english: "I\\", romanization: "dasi jeonhwahalgeyo", category: "greetings" },
  { korean: "귀한 시간 내주셔서 감사합니다", english: "Thank you for your precious time", romanization: "gwihan sigan naejusyeoseo gamsahamnida", category: "greetings" },
  { korean: "폐를 끼쳐 드려 죄송합니다", english: "I apologize for causing you trouble", romanization: "pyereul kkichyeo deuryeo joesonghamnida", category: "greetings" },
  { korean: "성원에 감사드립니다", english: "Thank you for your support", romanization: "seongwone gamsadeurimnida", category: "greetings" },
  { korean: "계시다", english: "To be (honorific)", romanization: "gyesida", category: "greetings" },
  { korean: "진심으로 감사드립니다", english: "I sincerely thank you", romanization: "jinsimeuro gamsadeurimnida", category: "greetings" },
  { korean: "깊이 감사드립니다", english: "I deeply thank you", romanization: "gipi gamsadeurimnida", category: "greetings" },
  { korean: "보답하겠습니다", english: "I will repay you", romanization: "bodapagetseumnida", category: "greetings" },
  { korean: "심려를 끼쳐 드려 죄송합니다", english: "I\\", romanization: "simnyeoreul kkichyeo deuryeo joesonghamnida", category: "greetings" },
  { korean: "불편을 드려 죄송합니다", english: "I apologize for the inconvenience", romanization: "bulpyeoneul deuryeo joesonghamnida", category: "greetings" },
  { korean: "용서를 구합니다", english: "I ask for forgiveness", romanization: "yongseoreul guhamnida", category: "greetings" },
  { korean: "삼가 고인의 명복을 빕니다", english: "May the deceased rest in peace", romanization: "samga goinui myeongbogeul bimnida", category: "greetings" },
  { korean: "조의를 표합니다", english: "I express my condolences", romanization: "jouireul pyohamnida", category: "greetings" },
  { korean: "위로의 말씀을 드립니다", english: "I offer my condolences", romanization: "wiroui malsseumeul deurimnida", category: "greetings" },
  { korean: "경사를 축하드립니다", english: "Congratulations on your celebration", romanization: "gyeongsareul chukadeurimnida", category: "greetings" },
  { korean: "영광스러운 날을 축하합니다", english: "Congratulations on this glorious day", romanization: "yeonggwangseureon nareul chukahamnida", category: "greetings" },
  { korean: "무궁한 발전을 기원합니다", english: "I wish you endless development", romanization: "mugunghan baljeoneul giwonhamnida", category: "greetings" },
  { korean: "개회사를 드리겠습니다", english: "I will give the opening speech", romanization: "gaehoesareul deurigetseumnida", category: "greetings" },
  { korean: "폐회를 선언합니다", english: "I declare the closing", romanization: "pyehoereul seoneonhamnida", category: "greetings" },
  { korean: "박수를 부탁드립니다", english: "Please give a round of applause", romanization: "baksureul butakdeurimnida", category: "greetings" },
  { korean: "초대에 응해 주셔서 감사합니다", english: "Thank you for accepting the invitation", romanization: "chodaee eunghae jusyeoseo gamsahamnida", category: "greetings" },
  { korean: "참석해 주시기 바랍니다", english: "Please attend", romanization: "chamseokae jusigi baramnida", category: "greetings" },
  { korean: "광림하여 주시면 감사하겠습니다", english: "We would appreciate your presence", romanization: "gwangnimhayeo jusimyeon gamsahagetseumnida", category: "greetings" },
  { korean: "주제넘은 말씀이지만", english: "This may be presumptuous, but", romanization: "jujeneobeun malsseumijiman", category: "greetings" },
  { korean: "바라마지 않습니다", english: "I sincerely hope", romanization: "baramaji anseumnida", category: "greetings" },
  { korean: "기원합니다", english: "I wish / I pray", romanization: "giwonhamnida", category: "greetings" },
  { korean: "부족하지만", english: "Though I\\", romanization: "bujokajiman", category: "greetings" },
  { korean: "미흡하지만", english: "Though inadequate", romanization: "miheupajiman", category: "greetings" },
  { korean: "과분한 칭찬입니다", english: "You praise me too much", romanization: "gwabunhan chingchanimnida", category: "greetings" },
  { korean: "선배님", english: "Senior (honorific)", romanization: "seonbaenim", category: "greetings" },
  { korean: "염치불구하고", english: "Shamelessly / Presumptuously", romanization: "yeomchibulguhago", category: "greetings" },
  { korean: "누를 끼치다", english: "To cause trouble", romanization: "nureul kkichida", category: "greetings" },
  { korean: "신세를 지다", english: "To be indebted", romanization: "sinsereul jida", category: "greetings" },
  { korean: "면목이 없다", english: "To have no face / To be ashamed", romanization: "myeonmogi eopda", category: "greetings" },
  { korean: "망극하다", english: "To be extremely grateful / overwhelmed", romanization: "manggeukada", category: "greetings" },
  { korean: "경청하다", english: "To listen attentively", romanization: "gyeongcheonghada", category: "greetings" },

  // NUMBERS (25)
  { korean: "하나", english: "One (native)", romanization: "hana", category: "numbers" },
  { korean: "둘", english: "Two (native)", romanization: "dul", category: "numbers" },
  { korean: "셋", english: "Three (native)", romanization: "set", category: "numbers" },
  { korean: "넷", english: "Four (native)", romanization: "net", category: "numbers" },
  { korean: "다섯", english: "Five (native)", romanization: "daseot", category: "numbers" },
  { korean: "여섯", english: "Six (native)", romanization: "yeoseot", category: "numbers" },
  { korean: "일곱", english: "Seven (native)", romanization: "ilgop", category: "numbers" },
  { korean: "여덟", english: "Eight (native)", romanization: "yeodeol", category: "numbers" },
  { korean: "아홉", english: "Nine (native)", romanization: "ahop", category: "numbers" },
  { korean: "열", english: "Ten (native)", romanization: "yeol", category: "numbers" },
  { korean: "일", english: "One (sino)", romanization: "il", category: "numbers" },
  { korean: "이", english: "Two (sino)", romanization: "i", category: "numbers" },
  { korean: "삼", english: "Three (sino)", romanization: "sam", category: "numbers" },
  { korean: "사", english: "Four (sino)", romanization: "sa", category: "numbers" },
  { korean: "오", english: "Five (sino)", romanization: "o", category: "numbers" },
  { korean: "육", english: "Six (sino)", romanization: "yuk", category: "numbers" },
  { korean: "칠", english: "Seven (sino)", romanization: "chil", category: "numbers" },
  { korean: "팔", english: "Eight (sino)", romanization: "pal", category: "numbers" },
  { korean: "구", english: "Nine (sino)", romanization: "gu", category: "numbers" },
  { korean: "십", english: "Ten (sino)", romanization: "sip", category: "numbers" },
  { korean: "백", english: "Hundred", romanization: "baek", category: "numbers" },
  { korean: "천", english: "Thousand", romanization: "cheon", category: "numbers" },
  { korean: "만", english: "Ten thousand", romanization: "man", category: "numbers" },
  { korean: "억", english: "Hundred million", romanization: "eok", category: "numbers" },
  { korean: "첫째", english: "First", romanization: "cheotjjae", category: "numbers" },

  // FAMILY (28)
  { korean: "가족", english: "Family", romanization: "gajok", category: "family" },
  { korean: "아버지", english: "Father", romanization: "abeoji", category: "family" },
  { korean: "어머니", english: "Mother", romanization: "eomeoni", category: "family" },
  { korean: "아빠", english: "Dad", romanization: "appa", category: "family" },
  { korean: "엄마", english: "Mom", romanization: "eomma", category: "family" },
  { korean: "부모님", english: "Parents", romanization: "bumonim", category: "family" },
  { korean: "형", english: "Older brother (male speaker)", romanization: "hyeong", category: "family" },
  { korean: "오빠", english: "Older brother (female speaker)", romanization: "oppa", category: "family" },
  { korean: "누나", english: "Older sister (male speaker)", romanization: "nuna", category: "family" },
  { korean: "언니", english: "Older sister (female speaker)", romanization: "eonni", category: "family" },
  { korean: "동생", english: "Younger sibling", romanization: "dongsaeng", category: "family" },
  { korean: "남동생", english: "Younger brother", romanization: "namdongsaeng", category: "family" },
  { korean: "여동생", english: "Younger sister", romanization: "yeodongsaeng", category: "family" },
  { korean: "할아버지", english: "Grandfather", romanization: "harabeoji", category: "family" },
  { korean: "할머니", english: "Grandmother", romanization: "halmeoni", category: "family" },
  { korean: "손자", english: "Grandson", romanization: "sonja", category: "family" },
  { korean: "손녀", english: "Granddaughter", romanization: "sonnyeo", category: "family" },
  { korean: "삼촌", english: "Uncle", romanization: "samchon", category: "family" },
  { korean: "이모", english: "Aunt (mother's side)", romanization: "imo", category: "family" },
  { korean: "고모", english: "Aunt (father's side)", romanization: "gomo", category: "family" },
  { korean: "사촌", english: "Cousin", romanization: "sachon", category: "family" },
  { korean: "남편", english: "Husband", romanization: "nampyeon", category: "family" },
  { korean: "아내", english: "Wife", romanization: "anae", category: "family" },
  { korean: "부부", english: "Married couple", romanization: "bubu", category: "family" },
  { korean: "아들", english: "Son", romanization: "adeul", category: "family" },
  { korean: "딸", english: "Daughter", romanization: "ttal", category: "family" },
  { korean: "자녀", english: "Children", romanization: "janyeo", category: "family" },
  { korean: "조카", english: "Niece/Nephew", romanization: "joka", category: "family" },

  // FOOD (50)
  { korean: "음식", english: "Food", romanization: "eumsik", category: "food" },
  { korean: "밥", english: "Rice/Meal", romanization: "bap", category: "food" },
  { korean: "김치", english: "Kimchi", romanization: "gimchi", category: "food" },
  { korean: "불고기", english: "Bulgogi", romanization: "bulgogi", category: "food" },
  { korean: "비빔밥", english: "Bibimbap", romanization: "bibimbap", category: "food" },
  { korean: "삼겹살", english: "Pork belly", romanization: "samgyeopsal", category: "food" },
  { korean: "갈비", english: "Ribs", romanization: "galbi", category: "food" },
  { korean: "찌개", english: "Stew", romanization: "jjigae", category: "food" },
  { korean: "국", english: "Soup", romanization: "guk", category: "food" },
  { korean: "김밥", english: "Gimbap", romanization: "gimbap", category: "food" },
  { korean: "떡볶이", english: "Tteokbokki", romanization: "tteokbokki", category: "food" },
  { korean: "라면", english: "Ramen", romanization: "ramyeon", category: "food" },
  { korean: "만두", english: "Dumplings", romanization: "mandu", category: "food" },
  { korean: "치킨", english: "Chicken", romanization: "chikin", category: "food" },
  { korean: "피자", english: "Pizza", romanization: "pija", category: "food" },
  { korean: "햄버거", english: "Hamburger", romanization: "haembeogeo", category: "food" },
  { korean: "빵", english: "Bread", romanization: "ppang", category: "food" },
  { korean: "과일", english: "Fruit", romanization: "gwail", category: "food" },
  { korean: "사과", english: "Apple", romanization: "sagwa", category: "food" },
  { korean: "배", english: "Pear", romanization: "bae", category: "food" },
  { korean: "바나나", english: "Banana", romanization: "banana", category: "food" },
  { korean: "딸기", english: "Strawberry", romanization: "ttalgi", category: "food" },
  { korean: "포도", english: "Grapes", romanization: "podo", category: "food" },
  { korean: "수박", english: "Watermelon", romanization: "subak", category: "food" },
  { korean: "귤", english: "Tangerine", romanization: "gyul", category: "food" },
  { korean: "야채", english: "Vegetables", romanization: "yachae", category: "food" },
  { korean: "고기", english: "Meat", romanization: "gogi", category: "food" },
  { korean: "생선", english: "Fish", romanization: "saengseon", category: "food" },
  { korean: "달걀", english: "Egg", romanization: "dalgyal", category: "food" },
  { korean: "우유", english: "Milk", romanization: "uyu", category: "food" },
  { korean: "물", english: "Water", romanization: "mul", category: "food" },
  { korean: "커피", english: "Coffee", romanization: "keopi", category: "food" },
  { korean: "차", english: "Tea", romanization: "cha", category: "food" },
  { korean: "주스", english: "Juice", romanization: "juseu", category: "food" },
  { korean: "맥주", english: "Beer", romanization: "maekju", category: "food" },
  { korean: "소주", english: "Soju", romanization: "soju", category: "food" },
  { korean: "와인", english: "Wine", romanization: "wain", category: "food" },
  { korean: "설탕", english: "Sugar", romanization: "seoltang", category: "food" },
  { korean: "소금", english: "Salt", romanization: "sogeum", category: "food" },
  { korean: "후추", english: "Pepper", romanization: "huchu", category: "food" },
  { korean: "된장", english: "Soybean paste", romanization: "doenjang", category: "food" },
  { korean: "고추장", english: "Red pepper paste", romanization: "gochujang", category: "food" },
  { korean: "간장", english: "Soy sauce", romanization: "ganjang", category: "food" },
  { korean: "참기름", english: "Sesame oil", romanization: "chamgireum", category: "food" },
  { korean: "마늘", english: "Garlic", romanization: "maneul", category: "food" },
  { korean: "양파", english: "Onion", romanization: "yangpa", category: "food" },
  { korean: "당근", english: "Carrot", romanization: "danggeun", category: "food" },
  { korean: "감자", english: "Potato", romanization: "gamja", category: "food" },
  { korean: "고구마", english: "Sweet potato", romanization: "goguma", category: "food" },
  { korean: "버섯", english: "Mushroom", romanization: "beoseot", category: "food" },

  // COLORS (12)
  { korean: "색깔", english: "Color", romanization: "saekkkal", category: "colors" },
  { korean: "빨강", english: "Red", romanization: "ppalgang", category: "colors" },
  { korean: "파랑", english: "Blue", romanization: "parang", category: "colors" },
  { korean: "노랑", english: "Yellow", romanization: "norang", category: "colors" },
  { korean: "초록", english: "Green", romanization: "chorok", category: "colors" },
  { korean: "검정", english: "Black", romanization: "geomjeong", category: "colors" },
  { korean: "하양", english: "White", romanization: "hayang", category: "colors" },
  { korean: "주황", english: "Orange", romanization: "juhwang", category: "colors" },
  { korean: "보라", english: "Purple", romanization: "bora", category: "colors" },
  { korean: "분홍", english: "Pink", romanization: "bunhong", category: "colors" },
  { korean: "회색", english: "Gray", romanization: "hoesaek", category: "colors" },
  { korean: "갈색", english: "Brown", romanization: "galsaek", category: "colors" },

  // BODY (17)
  { korean: "몸", english: "Body", romanization: "mom", category: "body" },
  { korean: "머리", english: "Head/Hair", romanization: "meori", category: "body" },
  { korean: "얼굴", english: "Face", romanization: "eolgul", category: "body" },
  { korean: "눈", english: "Eye", romanization: "nun", category: "body" },
  { korean: "코", english: "Nose", romanization: "ko", category: "body" },
  { korean: "입", english: "Mouth", romanization: "ip", category: "body" },
  { korean: "귀", english: "Ear", romanization: "gwi", category: "body" },
  { korean: "목", english: "Neck/Throat", romanization: "mok", category: "body" },
  { korean: "어깨", english: "Shoulder", romanization: "eokkae", category: "body" },
  { korean: "손", english: "Hand", romanization: "son", category: "body" },
  { korean: "손가락", english: "Finger", romanization: "son-garak", category: "body" },
  { korean: "다리", english: "Leg", romanization: "dari", category: "body" },
  { korean: "발", english: "Foot", romanization: "bal", category: "body" },
  { korean: "등", english: "Back", romanization: "deung", category: "body" },
  { korean: "가슴", english: "Chest", romanization: "gaseum", category: "body" },
  { korean: "심장", english: "Heart", romanization: "simjang", category: "body" },
  { korean: "피", english: "Blood", romanization: "pi", category: "body" },

  // PLACES (32)
  { korean: "장소", english: "Place", romanization: "jangso", category: "places" },
  { korean: "집", english: "House/Home", romanization: "jip", category: "places" },
  { korean: "학교", english: "School", romanization: "hakgyo", category: "places" },
  { korean: "회사", english: "Company", romanization: "hoesa", category: "places" },
  { korean: "병원", english: "Hospital", romanization: "byeongwon", category: "places" },
  { korean: "약국", english: "Pharmacy", romanization: "yakguk", category: "places" },
  { korean: "은행", english: "Bank", romanization: "eunhaeng", category: "places" },
  { korean: "우체국", english: "Post office", romanization: "ucheguk", category: "places" },
  { korean: "경찰서", english: "Police station", romanization: "gyeongchalseo", category: "places" },
  { korean: "소방서", english: "Fire station", romanization: "sobangseo", category: "places" },
  { korean: "공항", english: "Airport", romanization: "gonghang", category: "places" },
  { korean: "역", english: "Station", romanization: "yeok", category: "places" },
  { korean: "버스 정류장", english: "Bus stop", romanization: "beoseu jeongnyujang", category: "places" },
  { korean: "식당", english: "Restaurant", romanization: "sikdang", category: "places" },
  { korean: "카페", english: "Cafe", romanization: "kape", category: "places" },
  { korean: "슈퍼마켓", english: "Supermarket", romanization: "syupeomaket", category: "places" },
  { korean: "백화점", english: "Department store", romanization: "baekhwajeom", category: "places" },
  { korean: "시장", english: "Market", romanization: "sijang", category: "places" },
  { korean: "편의점", english: "Convenience store", romanization: "pyeonuijeom", category: "places" },
  { korean: "서점", english: "Bookstore", romanization: "seojeom", category: "places" },
  { korean: "도서관", english: "Library", romanization: "doseogwan", category: "places" },
  { korean: "박물관", english: "Museum", romanization: "bangmulgwan", category: "places" },
  { korean: "미술관", english: "Art museum", romanization: "misulgwan", category: "places" },
  { korean: "극장", english: "Theater", romanization: "geukjang", category: "places" },
  { korean: "영화관", english: "Cinema", romanization: "yeonghwagwan", category: "places" },
  { korean: "호텔", english: "Hotel", romanization: "hotel", category: "places" },
  { korean: "공원", english: "Park", romanization: "gongwon", category: "places" },
  { korean: "해변", english: "Beach", romanization: "haebyeon", category: "places" },
  { korean: "산", english: "Mountain", romanization: "san", category: "places" },
  { korean: "바다", english: "Sea/Ocean", romanization: "bada", category: "places" },
  { korean: "강", english: "River", romanization: "gang", category: "places" },
  { korean: "호수", english: "Lake", romanization: "hosu", category: "places" },

  // TRANSPORTATION (13)
  { korean: "교통", english: "Transportation", romanization: "gyotong", category: "transportation" },
  { korean: "자동차", english: "Car", romanization: "jadongcha", category: "transportation" },
  { korean: "버스", english: "Bus", romanization: "beoseu", category: "transportation" },
  { korean: "택시", english: "Taxi", romanization: "taeksi", category: "transportation" },
  { korean: "지하철", english: "Subway", romanization: "jihacheol", category: "transportation" },
  { korean: "기차", english: "Train", romanization: "gicha", category: "transportation" },
  { korean: "비행기", english: "Airplane", romanization: "bihaenggi", category: "transportation" },
  { korean: "자전거", english: "Bicycle", romanization: "jajeongeo", category: "transportation" },
  { korean: "오토바이", english: "Motorcycle", romanization: "otobai", category: "transportation" },
  { korean: "트럭", english: "Truck", romanization: "teureok", category: "transportation" },
  { korean: "표", english: "Ticket", romanization: "pyo", category: "transportation" },
  { korean: "운전", english: "Driving", romanization: "unjeon", category: "transportation" },
  { korean: "주차", english: "Parking", romanization: "jucha", category: "transportation" },

  // TIME (37)
  { korean: "시간", english: "Time/Hour", romanization: "sigan", category: "time" },
  { korean: "오늘", english: "Today", romanization: "oneul", category: "time" },
  { korean: "어제", english: "Yesterday", romanization: "eoje", category: "time" },
  { korean: "내일", english: "Tomorrow", romanization: "naeil", category: "time" },
  { korean: "모레", english: "Day after tomorrow", romanization: "more", category: "time" },
  { korean: "그저께", english: "Day before yesterday", romanization: "geujeokke", category: "time" },
  { korean: "이번 주", english: "This week", romanization: "ibeon ju", category: "time" },
  { korean: "지난 주", english: "Last week", romanization: "jinan ju", category: "time" },
  { korean: "다음 주", english: "Next week", romanization: "daeum ju", category: "time" },
  { korean: "이번 달", english: "This month", romanization: "ibeon dal", category: "time" },
  { korean: "지난 달", english: "Last month", romanization: "jinan dal", category: "time" },
  { korean: "다음 달", english: "Next month", romanization: "daeum dal", category: "time" },
  { korean: "올해", english: "This year", romanization: "olhae", category: "time" },
  { korean: "작년", english: "Last year", romanization: "jangnyeon", category: "time" },
  { korean: "내년", english: "Next year", romanization: "naenyeon", category: "time" },
  { korean: "아침", english: "Morning", romanization: "achim", category: "time" },
  { korean: "점심", english: "Lunch/Noon", romanization: "jeomsim", category: "time" },
  { korean: "저녁", english: "Evening/Dinner", romanization: "jeonyeok", category: "time" },
  { korean: "밤", english: "Night", romanization: "bam", category: "time" },
  { korean: "낮", english: "Daytime", romanization: "nat", category: "time" },
  { korean: "새벽", english: "Dawn", romanization: "saebyeok", category: "time" },
  { korean: "월요일", english: "Monday", romanization: "woryoil", category: "time" },
  { korean: "화요일", english: "Tuesday", romanization: "hwayoil", category: "time" },
  { korean: "수요일", english: "Wednesday", romanization: "suyoil", category: "time" },
  { korean: "목요일", english: "Thursday", romanization: "mogyoil", category: "time" },
  { korean: "금요일", english: "Friday", romanization: "geumyoil", category: "time" },
  { korean: "토요일", english: "Saturday", romanization: "toyoil", category: "time" },
  { korean: "일요일", english: "Sunday", romanization: "iryoil", category: "time" },
  { korean: "주말", english: "Weekend", romanization: "jumal", category: "time" },
  { korean: "평일", english: "Weekday", romanization: "pyeongil", category: "time" },
  { korean: "저는", english: "I am / As for me", romanization: "jeoneun", category: "time" },
  { korean: "아직", english: "Yet / Still", romanization: "ajik", category: "time" },
  { korean: "지금", english: "Now", romanization: "jigeum", category: "time" },
  { korean: "오전", english: "Morning / AM", romanization: "ojeon", category: "time" },
  { korean: "오후", english: "Afternoon / PM", romanization: "ohu", category: "time" },
  { korean: "조만간", english: "Soon / Before long", romanization: "jomangan", category: "time" },
  { korean: "당장", english: "Right now / Immediately", romanization: "dangjang", category: "time" },

  // WEATHER (19)
  { korean: "날씨", english: "Weather", romanization: "nalssi", category: "weather" },
  { korean: "맑음", english: "Clear/Sunny", romanization: "malgeum", category: "weather" },
  { korean: "흐림", english: "Cloudy", romanization: "heurim", category: "weather" },
  { korean: "비", english: "Rain", romanization: "bi", category: "weather" },
  { korean: "바람", english: "Wind", romanization: "baram", category: "weather" },
  { korean: "태풍", english: "Typhoon", romanization: "taepung", category: "weather" },
  { korean: "번개", english: "Lightning", romanization: "beongae", category: "weather" },
  { korean: "천둥", english: "Thunder", romanization: "cheondung", category: "weather" },
  { korean: "안개", english: "Fog", romanization: "angae", category: "weather" },
  { korean: "더위", english: "Heat", romanization: "deowi", category: "weather" },
  { korean: "추위", english: "Cold", romanization: "chuwi", category: "weather" },
  { korean: "습도", english: "Humidity", romanization: "seupdo", category: "weather" },
  { korean: "온도", english: "Temperature", romanization: "ondo", category: "weather" },
  { korean: "봄", english: "Spring", romanization: "bom", category: "weather" },
  { korean: "여름", english: "Summer", romanization: "yeoreum", category: "weather" },
  { korean: "가을", english: "Fall/Autumn", romanization: "gaeul", category: "weather" },
  { korean: "겨울", english: "Winter", romanization: "gyeoul", category: "weather" },
  { korean: "날씨가 좋아요", english: "The weather is nice", romanization: "nalssiga johayo", category: "weather" },
  { korean: "날씨가 나빠요", english: "The weather is bad", romanization: "nalssiga nappayo", category: "weather" },

  // ADJECTIVES (50)
  { korean: "좋다", english: "Good", romanization: "jota", category: "adjectives" },
  { korean: "나쁘다", english: "Bad", romanization: "nappeuda", category: "adjectives" },
  { korean: "크다", english: "Big", romanization: "keuda", category: "adjectives" },
  { korean: "작다", english: "Small", romanization: "jakda", category: "adjectives" },
  { korean: "많다", english: "Many/Much", romanization: "manta", category: "adjectives" },
  { korean: "적다", english: "Few/Little", romanization: "jeokda", category: "adjectives" },
  { korean: "길다", english: "Long", romanization: "gilda", category: "adjectives" },
  { korean: "짧다", english: "Short", romanization: "jjalda", category: "adjectives" },
  { korean: "높다", english: "High/Tall", romanization: "nopda", category: "adjectives" },
  { korean: "낮다", english: "Low", romanization: "natda", category: "adjectives" },
  { korean: "빠르다", english: "Fast", romanization: "ppareuda", category: "adjectives" },
  { korean: "느리다", english: "Slow", romanization: "neurida", category: "adjectives" },
  { korean: "뜨겁다", english: "Hot", romanization: "tteugeomda", category: "adjectives" },
  { korean: "차갑다", english: "Cold", romanization: "chagapda", category: "adjectives" },
  { korean: "따뜻하다", english: "Warm", romanization: "ttatteuthada", category: "adjectives" },
  { korean: "시원하다", english: "Cool/Refreshing", romanization: "siwonhada", category: "adjectives" },
  { korean: "맛있다", english: "Delicious", romanization: "masitda", category: "adjectives" },
  { korean: "맛없다", english: "Not delicious", romanization: "maseopda", category: "adjectives" },
  { korean: "예쁘다", english: "Pretty", romanization: "yeppeuda", category: "adjectives" },
  { korean: "못생기다", english: "Ugly", romanization: "motsaenggida", category: "adjectives" },
  { korean: "아름답다", english: "Beautiful", romanization: "areumdapta", category: "adjectives" },
  { korean: "귀엽다", english: "Cute", romanization: "gwiyeopda", category: "adjectives" },
  { korean: "멋있다", english: "Cool/Stylish", romanization: "meositda", category: "adjectives" },
  { korean: "행복하다", english: "Happy", romanization: "haengbokhada", category: "adjectives" },
  { korean: "슬프다", english: "Sad", romanization: "seulpeuda", category: "adjectives" },
  { korean: "화나다", english: "Angry", romanization: "hwanada", category: "adjectives" },
  { korean: "기쁘다", english: "Joyful", romanization: "gippeuda", category: "adjectives" },
  { korean: "무섭다", english: "Scary", romanization: "museopda", category: "adjectives" },
  { korean: "재미있다", english: "Fun/Interesting", romanization: "jaemiitda", category: "adjectives" },
  { korean: "재미없다", english: "Boring", romanization: "jaemieopda", category: "adjectives" },
  { korean: "어렵다", english: "Difficult", romanization: "eoryeopda", category: "adjectives" },
  { korean: "쉽다", english: "Easy", romanization: "swipda", category: "adjectives" },
  { korean: "비싸다", english: "Expensive", romanization: "bissada", category: "adjectives" },
  { korean: "싸다", english: "Cheap", romanization: "ssada", category: "adjectives" },
  { korean: "새롭다", english: "New", romanization: "saeropda", category: "adjectives" },
  { korean: "오래되다", english: "Old", romanization: "oraedoeda", category: "adjectives" },
  { korean: "깨끗하다", english: "Clean", romanization: "kkaekkeutada", category: "adjectives" },
  { korean: "더럽다", english: "Dirty", romanization: "deureopda", category: "adjectives" },
  { korean: "조용하다", english: "Quiet", romanization: "joyonghada", category: "adjectives" },
  { korean: "시끄럽다", english: "Noisy", romanization: "sikkeeureopda", category: "adjectives" },
  { korean: "바쁘다", english: "Busy", romanization: "bappeuda", category: "adjectives" },
  { korean: "한가하다", english: "Free/Leisurely", romanization: "hangahada", category: "adjectives" },
  { korean: "피곤하다", english: "Tired", romanization: "pigonhada", category: "adjectives" },
  { korean: "건강하다", english: "Healthy", romanization: "geonganghada", category: "adjectives" },
  { korean: "아프다", english: "Sick/Hurt", romanization: "apeuda", category: "adjectives" },
  { korean: "똑똑하다", english: "Smart", romanization: "ttokttokada", category: "adjectives" },
  { korean: "바보같다", english: "Foolish", romanization: "babogatda", category: "adjectives" },
  { korean: "친절하다", english: "Kind", romanization: "chinjelhada", category: "adjectives" },
  { korean: "불친절하다", english: "Unkind", romanization: "bulchinjelhada", category: "adjectives" },
  { korean: "편하다", english: "Comfortable", romanization: "pyeonhada", category: "adjectives" },

  // VERBS (91)
  { korean: "가다", english: "Go", romanization: "gada", category: "verbs" },
  { korean: "오다", english: "Come", romanization: "oda", category: "verbs" },
  { korean: "먹다", english: "Eat", romanization: "meokda", category: "verbs" },
  { korean: "마시다", english: "Drink", romanization: "masida", category: "verbs" },
  { korean: "자다", english: "Sleep", romanization: "jada", category: "verbs" },
  { korean: "일어나다", english: "Wake up", romanization: "ireonada", category: "verbs" },
  { korean: "보다", english: "See/Watch", romanization: "boda", category: "verbs" },
  { korean: "듣다", english: "Hear/Listen", romanization: "deutda", category: "verbs" },
  { korean: "읽다", english: "Read", romanization: "ikda", category: "verbs" },
  { korean: "쓰다", english: "Write", romanization: "sseuda", category: "verbs" },
  { korean: "말하다", english: "Speak/Say", romanization: "malhada", category: "verbs" },
  { korean: "배우다", english: "Learn", romanization: "baeuda", category: "verbs" },
  { korean: "가르치다", english: "Teach", romanization: "gareuchida", category: "verbs" },
  { korean: "공부하다", english: "Study", romanization: "gongbuhada", category: "verbs" },
  { korean: "일하다", english: "Work", romanization: "ilhada", category: "verbs" },
  { korean: "놀다", english: "Play", romanization: "nolda", category: "verbs" },
  { korean: "쉬다", english: "Rest", romanization: "swida", category: "verbs" },
  { korean: "운동하다", english: "Exercise", romanization: "undonghada", category: "verbs" },
  { korean: "걷다", english: "Walk", romanization: "geotda", category: "verbs" },
  { korean: "뛰다", english: "Run", romanization: "ttwida", category: "verbs" },
  { korean: "타다", english: "Ride", romanization: "tada", category: "verbs" },
  { korean: "사다", english: "Buy", romanization: "sada", category: "verbs" },
  { korean: "팔다", english: "Sell", romanization: "palda", category: "verbs" },
  { korean: "주다", english: "Give", romanization: "juda", category: "verbs" },
  { korean: "받다", english: "Receive", romanization: "batda", category: "verbs" },
  { korean: "만들다", english: "Make", romanization: "mandeulda", category: "verbs" },
  { korean: "요리하다", english: "Cook", romanization: "yorihada", category: "verbs" },
  { korean: "씻다", english: "Wash", romanization: "ssitda", category: "verbs" },
  { korean: "청소하다", english: "Clean", romanization: "cheongsohada", category: "verbs" },
  { korean: "빨래하다", english: "Do laundry", romanization: "ppallaehada", category: "verbs" },
  { korean: "입다", english: "Wear (clothes)", romanization: "ipda", category: "verbs" },
  { korean: "벗다", english: "Take off", romanization: "beotda", category: "verbs" },
  { korean: "신다", english: "Wear (shoes)", romanization: "sinda", category: "verbs" },
  { korean: "열다", english: "Open", romanization: "yeolda", category: "verbs" },
  { korean: "닫다", english: "Close", romanization: "datda", category: "verbs" },
  { korean: "켜다", english: "Turn on", romanization: "kyeoda", category: "verbs" },
  { korean: "끄다", english: "Turn off", romanization: "kkeuda", category: "verbs" },
  { korean: "찾다", english: "Find/Look for", romanization: "chatda", category: "verbs" },
  { korean: "잃다", english: "Lose", romanization: "ilta", category: "verbs" },
  { korean: "알다", english: "Know", romanization: "alda", category: "verbs" },
  { korean: "모르다", english: "Not know", romanization: "moreuda", category: "verbs" },
  { korean: "생각하다", english: "Think", romanization: "saenggakhada", category: "verbs" },
  { korean: "기억하다", english: "Remember", romanization: "gieokhada", category: "verbs" },
  { korean: "잊다", english: "Forget", romanization: "itda", category: "verbs" },
  { korean: "시작하다", english: "Start", romanization: "sijakhada", category: "verbs" },
  { korean: "끝나다", english: "End/Finish", romanization: "kkeunnada", category: "verbs" },
  { korean: "계속하다", english: "Continue", romanization: "gyesokhada", category: "verbs" },
  { korean: "멈추다", english: "Stop", romanization: "meomchuda", category: "verbs" },
  { korean: "웃다", english: "Laugh/Smile", romanization: "utda", category: "verbs" },
  { korean: "울다", english: "Cry", romanization: "ulda", category: "verbs" },
  { korean: "좋아하다", english: "Like", romanization: "joahada", category: "verbs" },
  { korean: "싫어하다", english: "Dislike", romanization: "sireohada", category: "verbs" },
  { korean: "사랑하다", english: "Love", romanization: "saranghada", category: "verbs" },
  { korean: "미워하다", english: "Hate", romanization: "miwohada", category: "verbs" },
  { korean: "만나다", english: "Meet", romanization: "mannada", category: "verbs" },
  { korean: "헤어지다", english: "Break up/Separate", romanization: "heeojida", category: "verbs" },
  { korean: "결혼하다", english: "Get married", romanization: "gyeolhonhada", category: "verbs" },
  { korean: "이혼하다", english: "Divorce", romanization: "ihonhada", category: "verbs" },
  { korean: "전화하다", english: "Call (phone)", romanization: "jeonhwahada", category: "verbs" },
  { korean: "문자하다", english: "Text", romanization: "munjahada", category: "verbs" },
  { korean: "보내다", english: "Send", romanization: "bonaeda", category: "verbs" },
  { korean: "돕다", english: "Help", romanization: "dopda", category: "verbs" },
  { korean: "묻다", english: "Ask", romanization: "mutda", category: "verbs" },
  { korean: "대답하다", english: "Answer", romanization: "daedaphada", category: "verbs" },
  { korean: "설명하다", english: "Explain", romanization: "seolmyeonghada", category: "verbs" },
  { korean: "이해하다", english: "Understand", romanization: "ihaehada", category: "verbs" },
  { korean: "약속하다", english: "Promise", romanization: "yaksokhada", category: "verbs" },
  { korean: "좋아요", english: "Good / I\\", romanization: "johayo", category: "verbs" },
  { korean: "의사", english: "Doctor", romanization: "uisa", category: "verbs" },
  { korean: "있어요", english: "There is / Have", romanization: "isseoyo", category: "verbs" },
  { korean: "없어요", english: "There isn\\", romanization: "eopseoyo", category: "verbs" },
  { korean: "가요", english: "Go", romanization: "gayo", category: "verbs" },
  { korean: "와요", english: "Come", romanization: "wayo", category: "verbs" },
  { korean: "먹어요", english: "Eat", romanization: "meogeoyo", category: "verbs" },
  { korean: "마셔요", english: "Drink", romanization: "masyeoyo", category: "verbs" },
  { korean: "해요", english: "Do", romanization: "haeyo", category: "verbs" },
  { korean: "봐요", english: "See / Watch", romanization: "bwayo", category: "verbs" },
  { korean: "읽어요", english: "Read", romanization: "ilgeoyo", category: "verbs" },
  { korean: "써요", english: "Write / Use", romanization: "sseoyo", category: "verbs" },
  { korean: "알았어요", english: "I got it / I understand", romanization: "arasseoyo", category: "verbs" },
  { korean: "몰라요", english: "I don\\", romanization: "mollayo", category: "verbs" },
  { korean: "이미", english: "Already", romanization: "imi", category: "verbs" },
  { korean: "벌써", english: "Already", romanization: "beolsseo", category: "verbs" },
  { korean: "할까요?", english: "Shall we do it?", romanization: "halkkayo?", category: "verbs" },
  { korean: "싫어해요", english: "I don\\", romanization: "sireohaeyo", category: "verbs" },
  { korean: "드시다", english: "To eat (honorific)", romanization: "deusida", category: "verbs" },
  { korean: "뵙다", english: "To see/meet (humble)", romanization: "boepda", category: "verbs" },
  { korean: "눕다", english: "To lie down", romanization: "nupda", category: "verbs" },
  { korean: "하다", english: "To do", romanization: "hada", category: "verbs" },
  { korean: "있다", english: "To be/exist/have", romanization: "itda", category: "verbs" },
  { korean: "없다", english: "To not be/not have", romanization: "eopda", category: "verbs" },

  // PRONOUNS (13)
  { korean: "나", english: "I/Me (informal)", romanization: "na", category: "pronouns" },
  { korean: "저", english: "I/Me (formal)", romanization: "jeo", category: "pronouns" },
  { korean: "너", english: "You (informal)", romanization: "neo", category: "pronouns" },
  { korean: "당신", english: "You (formal)", romanization: "dangsin", category: "pronouns" },
  { korean: "우리", english: "We/Us", romanization: "uri", category: "pronouns" },
  { korean: "그", english: "He/Him", romanization: "geu", category: "pronouns" },
  { korean: "그녀", english: "She/Her", romanization: "geunyeo", category: "pronouns" },
  { korean: "그들", english: "They/Them", romanization: "geudeul", category: "pronouns" },
  { korean: "이것", english: "This", romanization: "igeot", category: "pronouns" },
  { korean: "그것", english: "That", romanization: "geugeot", category: "pronouns" },
  { korean: "저것", english: "That (over there)", romanization: "jeogeot", category: "pronouns" },
  { korean: "제 이름은", english: "My name is", romanization: "je ireumeun", category: "pronouns" },
  { korean: "나는", english: "I (informal)", romanization: "naneun", category: "pronouns" },

  // COMMON (67)
  { korean: "여기", english: "Here", romanization: "yeogi", category: "common" },
  { korean: "거기", english: "There", romanization: "geogi", category: "common" },
  { korean: "저기", english: "Over there", romanization: "jeogi", category: "common" },
  { korean: "어디", english: "Where", romanization: "eodi", category: "common" },
  { korean: "언제", english: "When", romanization: "eonje", category: "common" },
  { korean: "누구", english: "Who", romanization: "nugu", category: "common" },
  { korean: "무엇", english: "What", romanization: "mueot", category: "common" },
  { korean: "왜", english: "Why", romanization: "wae", category: "common" },
  { korean: "어떻게", english: "How", romanization: "eotteoke", category: "common" },
  { korean: "얼마", english: "How much", romanization: "eolma", category: "common" },
  { korean: "얼마나", english: "How many/long", romanization: "eolmana", category: "common" },
  { korean: "네", english: "Yes", romanization: "ne", category: "common" },
  { korean: "아니요", english: "No", romanization: "aniyo", category: "common" },
  { korean: "그래", english: "Yeah (informal)", romanization: "geurae", category: "common" },
  { korean: "아니", english: "No (informal)", romanization: "ani", category: "common" },
  { korean: "맞아요", english: "That's right", romanization: "majayo", category: "common" },
  { korean: "틀려요", english: "That's wrong", romanization: "teullyeoyo", category: "common" },
  { korean: "아마도", english: "Maybe/Perhaps", romanization: "amado", category: "common" },
  { korean: "확실히", english: "Certainly", romanization: "hwaksilhi", category: "common" },
  { korean: "정말", english: "Really", romanization: "jeongmal", category: "common" },
  { korean: "진짜", english: "Real/Really", romanization: "jinjja", category: "common" },
  { korean: "거짓말", english: "Lie", romanization: "geojinmal", category: "common" },
  { korean: "사실", english: "Fact/Truth", romanization: "sasil", category: "common" },
  { korean: "아주", english: "Very", romanization: "aju", category: "common" },
  { korean: "매우", english: "Very/Extremely", romanization: "maeu", category: "common" },
  { korean: "너무", english: "Too/Very", romanization: "neomu", category: "common" },
  { korean: "조금", english: "A little", romanization: "jogeum", category: "common" },
  { korean: "많이", english: "A lot", romanization: "mani", category: "common" },
  { korean: "전혀", english: "Not at all", romanization: "jeonhyeo", category: "common" },
  { korean: "항상", english: "Always", romanization: "hangsang", category: "common" },
  { korean: "자주", english: "Often", romanization: "jaju", category: "common" },
  { korean: "가끔", english: "Sometimes", romanization: "gakkeum", category: "common" },
  { korean: "절대", english: "Never/Absolutely", romanization: "jeoldae", category: "common" },
  { korean: "빨리", english: "Quickly", romanization: "ppalli", category: "common" },
  { korean: "천천히", english: "Slowly", romanization: "cheoncheonhi", category: "common" },
  { korean: "같이", english: "Together", romanization: "gachi", category: "common" },
  { korean: "혼자", english: "Alone", romanization: "honja", category: "common" },
  { korean: "다시", english: "Again", romanization: "dasi", category: "common" },
  { korean: "먼저", english: "First", romanization: "meonjeo", category: "common" },
  { korean: "이름이 뭐예요?", english: "What is your name?", romanization: "ireumi mwoyeyo?", category: "common" },
  { korean: "성함이 어떻게 되세요?", english: "What is your name? (formal)", romanization: "seonghami eotteoke doeseyo?", category: "common" },
  { korean: "예", english: "Yes (formal)", romanization: "ye", category: "common" },
  { korean: "어디에서 왔어요?", english: "Where are you from?", romanization: "eodieseo wasseoyo?", category: "common" },
  { korean: "어느 나라 사람이에요?", english: "What nationality are you?", romanization: "eoneu nara saramieyo?", category: "common" },
  { korean: "알겠습니다", english: "I understand", romanization: "algetseumnida", category: "common" },
  { korean: "나이가 어떻게 되세요?", english: "How old are you?", romanization: "naiga eotteoke doeseyo?", category: "common" },
  { korean: "몇 살이에요?", english: "How old are you?", romanization: "myeot sarieyo?", category: "common" },
  { korean: "직업이 뭐예요?", english: "What is your job?", romanization: "jigeobi mwoyeyo?", category: "common" },
  { korean: "무슨 일 하세요?", english: "What do you do?", romanization: "museun il haseyo?", category: "common" },
  { korean: "어디에 사세요?", english: "Where do you live?", romanization: "eodie saseyo?", category: "common" },
  { korean: "고향이 어디예요?", english: "Where is your hometown?", romanization: "gohyangi eodiyeyo?", category: "common" },
  { korean: "어때요?", english: "How about it?", romanization: "eottaeyo?", category: "common" },
  { korean: "같이 갈까요?", english: "Shall we go together?", romanization: "gachi galkkayo?", category: "common" },
  { korean: "그렇게 생각해요", english: "I think so", romanization: "geureoke saenggakaeyo", category: "common" },
  { korean: "그럴 수도 있어요", english: "That could be", romanization: "geureol sudo isseoyo", category: "common" },
  { korean: "좋아해요", english: "I like it", romanization: "johahaeyo", category: "common" },
  { korean: "별로예요", english: "Not really / Not particularly", romanization: "byeolloyeyo", category: "common" },
  { korean: "샤워하다", english: "To shower", romanization: "syawohada", category: "common" },
  { korean: "목욕하다", english: "To bathe", romanization: "mogyokada", category: "common" },
  { korean: "달리다", english: "To run", romanization: "dallida", category: "common" },
  { korean: "앉다", english: "To sit", romanization: "anda", category: "common" },
  { korean: "서다", english: "To stand", romanization: "seoda", category: "common" },
  { korean: "우산", english: "Umbrella", romanization: "usan", category: "common" },
  { korean: "열쇠", english: "Key", romanization: "yeolsoe", category: "common" },
  { korean: "TV", english: "TV", romanization: "tibi", category: "common" },
  { korean: "계란", english: "Egg", romanization: "gyeran", category: "common" },
  { korean: "걸리다", english: "To take (time)", romanization: "geollida", category: "common" },

  // CLOTHING (20)
  { korean: "옷", english: "Clothes", romanization: "ot", category: "clothing" },
  { korean: "셔츠", english: "Shirt", romanization: "syeocheu", category: "clothing" },
  { korean: "티셔츠", english: "T-shirt", romanization: "tisyeocheu", category: "clothing" },
  { korean: "바지", english: "Pants", romanization: "baji", category: "clothing" },
  { korean: "청바지", english: "Jeans", romanization: "cheongbaji", category: "clothing" },
  { korean: "치마", english: "Skirt", romanization: "chima", category: "clothing" },
  { korean: "원피스", english: "Dress", romanization: "wonpiseu", category: "clothing" },
  { korean: "재킷", english: "Jacket", romanization: "jaekit", category: "clothing" },
  { korean: "코트", english: "Coat", romanization: "koteu", category: "clothing" },
  { korean: "신발", english: "Shoes", romanization: "sinbal", category: "clothing" },
  { korean: "양말", english: "Socks", romanization: "yangmal", category: "clothing" },
  { korean: "모자", english: "Hat", romanization: "moja", category: "clothing" },
  { korean: "안경", english: "Glasses", romanization: "angyeong", category: "clothing" },
  { korean: "선글라스", english: "Sunglasses", romanization: "seonggeullaseu", category: "clothing" },
  { korean: "가방", english: "Bag", romanization: "gabang", category: "clothing" },
  { korean: "지갑", english: "Wallet", romanization: "jigap", category: "clothing" },
  { korean: "시계", english: "Watch/Clock", romanization: "sigye", category: "clothing" },
  { korean: "반지", english: "Ring", romanization: "banji", category: "clothing" },
  { korean: "목걸이", english: "Necklace", romanization: "mokgeori", category: "clothing" },
  { korean: "귀걸이", english: "Earrings", romanization: "gwigeori", category: "clothing" },

  // TECHNOLOGY (24)
  { korean: "컴퓨터", english: "Computer", romanization: "keompyuteo", category: "technology" },
  { korean: "노트북", english: "Laptop", romanization: "noteubuk", category: "technology" },
  { korean: "휴대폰", english: "Cell phone", romanization: "hyudaepon", category: "technology" },
  { korean: "스마트폰", english: "Smartphone", romanization: "seumateupon", category: "technology" },
  { korean: "전화", english: "Phone/Telephone", romanization: "jeonhwa", category: "technology" },
  { korean: "텔레비전", english: "Television", romanization: "tellebijeon", category: "technology" },
  { korean: "티비", english: "TV", romanization: "tibi", category: "technology" },
  { korean: "라디오", english: "Radio", romanization: "radio", category: "technology" },
  { korean: "카메라", english: "Camera", romanization: "kamera", category: "technology" },
  { korean: "인터넷", english: "Internet", romanization: "inteonet", category: "technology" },
  { korean: "이메일", english: "Email", romanization: "imeil", category: "technology" },
  { korean: "문자", english: "Text message", romanization: "munja", category: "technology" },
  { korean: "앱", english: "App", romanization: "aep", category: "technology" },
  { korean: "웹사이트", english: "Website", romanization: "wepsaiteu", category: "technology" },
  { korean: "비밀번호", english: "Password", romanization: "bimilbeonho", category: "technology" },
  { korean: "아이디", english: "ID/Username", romanization: "aidi", category: "technology" },
  { korean: "키보드", english: "Keyboard", romanization: "kibodeu", category: "technology" },
  { korean: "마우스", english: "Mouse", romanization: "mauseu", category: "technology" },
  { korean: "화면", english: "Screen", romanization: "hwamyeon", category: "technology" },
  { korean: "배터리", english: "Battery", romanization: "baeteori", category: "technology" },
  { korean: "여보세요", english: "Hello (on phone)", romanization: "yeoboseyo", category: "technology" },
  { korean: "메시지 남겨 주세요", english: "Please leave a message", romanization: "mesiji namgyeo juseyo", category: "technology" },
  { korean: "통화 중이에요", english: "The line is busy", romanization: "tonghwa jungieyo", category: "technology" },
  { korean: "핸드폰", english: "Cell phone", romanization: "haendeupon", category: "technology" },

  // EMOTIONS (22)
  { korean: "감정", english: "Emotion/Feeling", romanization: "gamjeong", category: "emotions" },
  { korean: "기분", english: "Mood/Feeling", romanization: "gibun", category: "emotions" },
  { korean: "사랑", english: "Love", romanization: "sarang", category: "emotions" },
  { korean: "미움", english: "Hate", romanization: "mium", category: "emotions" },
  { korean: "행복", english: "Happiness", romanization: "haengbok", category: "emotions" },
  { korean: "슬픔", english: "Sadness", romanization: "seulpeum", category: "emotions" },
  { korean: "분노", english: "Anger", romanization: "bunno", category: "emotions" },
  { korean: "기쁨", english: "Joy", romanization: "gippeum", category: "emotions" },
  { korean: "두려움", english: "Fear", romanization: "duryeoum", category: "emotions" },
  { korean: "걱정", english: "Worry", romanization: "geokjeong", category: "emotions" },
  { korean: "희망", english: "Hope", romanization: "huimang", category: "emotions" },
  { korean: "실망", english: "Disappointment", romanization: "silmang", category: "emotions" },
  { korean: "후회", english: "Regret", romanization: "huhoe", category: "emotions" },
  { korean: "스트레스", english: "Stress", romanization: "seuteuleseu", category: "emotions" },
  { korean: "괜찮으세요?", english: "Are you okay?", romanization: "gwaenchaneuseyo?", category: "emotions" },
  { korean: "힘내세요", english: "Cheer up / Keep it up", romanization: "himnaeseyo", category: "emotions" },
  { korean: "화이팅", english: "Fighting / You can do it", romanization: "hwaiting", category: "emotions" },
  { korean: "잘 될 거예요", english: "It will be okay", romanization: "jal doel geoyeyo", category: "emotions" },
  { korean: "할 수 있어요", english: "You can do it", romanization: "hal su isseoyo", category: "emotions" },
  { korean: "안됐네요", english: "That\\", romanization: "andwaenneyo", category: "emotions" },
  { korean: "힘드시겠어요", english: "It must be hard", romanization: "himdeuisigesseoyo", category: "emotions" },
  { korean: "기분이 좋아요", english: "I feel good", romanization: "gibuni johayo", category: "emotions" },

  // EDUCATION (21)
  { korean: "교육", english: "Education", romanization: "gyoyuk", category: "education" },
  { korean: "학생", english: "Student", romanization: "haksaeng", category: "education" },
  { korean: "선생님", english: "Teacher", romanization: "seonsaengnim", category: "education" },
  { korean: "교수님", english: "Professor", romanization: "gyosunim", category: "education" },
  { korean: "수업", english: "Class/Lesson", romanization: "sueop", category: "education" },
  { korean: "시험", english: "Exam/Test", romanization: "siheom", category: "education" },
  { korean: "숙제", english: "Homework", romanization: "sukje", category: "education" },
  { korean: "책", english: "Book", romanization: "chaek", category: "education" },
  { korean: "노트", english: "Notebook", romanization: "noteu", category: "education" },
  { korean: "연필", english: "Pencil", romanization: "yeonpil", category: "education" },
  { korean: "펜", english: "Pen", romanization: "pen", category: "education" },
  { korean: "지우개", english: "Eraser", romanization: "jiugae", category: "education" },
  { korean: "칠판", english: "Blackboard", romanization: "chilpan", category: "education" },
  { korean: "책상", english: "Desk", romanization: "chaeksang", category: "education" },
  { korean: "의자", english: "Chair", romanization: "uija", category: "education" },
  { korean: "교실", english: "Classroom", romanization: "gyosil", category: "education" },
  { korean: "대학교", english: "University", romanization: "daehakgyo", category: "education" },
  { korean: "고등학교", english: "High school", romanization: "godeunghakgyo", category: "education" },
  { korean: "중학교", english: "Middle school", romanization: "junghakgyo", category: "education" },
  { korean: "초등학교", english: "Elementary school", romanization: "chodeunghakgyo", category: "education" },
  { korean: "회사원", english: "Office worker", romanization: "hoesawon", category: "education" },

  // HOBBIES (20)
  { korean: "취미", english: "Hobby", romanization: "chwimi", category: "hobbies" },
  { korean: "운동", english: "Exercise/Sports", romanization: "undong", category: "hobbies" },
  { korean: "축구", english: "Soccer", romanization: "chukgu", category: "hobbies" },
  { korean: "야구", english: "Baseball", romanization: "yagu", category: "hobbies" },
  { korean: "농구", english: "Basketball", romanization: "nonggu", category: "hobbies" },
  { korean: "수영", english: "Swimming", romanization: "suyeong", category: "hobbies" },
  { korean: "등산", english: "Hiking", romanization: "deungsan", category: "hobbies" },
  { korean: "요가", english: "Yoga", romanization: "yoga", category: "hobbies" },
  { korean: "독서", english: "Reading", romanization: "dokseo", category: "hobbies" },
  { korean: "음악", english: "Music", romanization: "eumak", category: "hobbies" },
  { korean: "노래", english: "Song", romanization: "norae", category: "hobbies" },
  { korean: "영화", english: "Movie", romanization: "yeonghwa", category: "hobbies" },
  { korean: "드라마", english: "Drama", romanization: "deurama", category: "hobbies" },
  { korean: "게임", english: "Game", romanization: "geim", category: "hobbies" },
  { korean: "여행", english: "Travel", romanization: "yeohaeng", category: "hobbies" },
  { korean: "사진", english: "Photo", romanization: "sajin", category: "hobbies" },
  { korean: "그림", english: "Picture/Drawing", romanization: "geurim", category: "hobbies" },
  { korean: "춤", english: "Dance", romanization: "chum", category: "hobbies" },
  { korean: "요리", english: "Cooking", romanization: "yori", category: "hobbies" },
  { korean: "쇼핑", english: "Shopping", romanization: "syoping", category: "hobbies" },

  // NATURE (25)
  { korean: "자연", english: "Nature", romanization: "jayeon", category: "nature" },
  { korean: "나무", english: "Tree", romanization: "namu", category: "nature" },
  { korean: "꽃", english: "Flower", romanization: "kkot", category: "nature" },
  { korean: "잎", english: "Leaf", romanization: "ip", category: "nature" },
  { korean: "풀", english: "Grass", romanization: "pul", category: "nature" },
  { korean: "하늘", english: "Sky", romanization: "haneul", category: "nature" },
  { korean: "구름", english: "Cloud", romanization: "gureum", category: "nature" },
  { korean: "별", english: "Star", romanization: "byeol", category: "nature" },
  { korean: "달", english: "Moon", romanization: "dal", category: "nature" },
  { korean: "해", english: "Sun", romanization: "hae", category: "nature" },
  { korean: "동물", english: "Animal", romanization: "dongmul", category: "nature" },
  { korean: "개", english: "Dog", romanization: "gae", category: "nature" },
  { korean: "고양이", english: "Cat", romanization: "goyangi", category: "nature" },
  { korean: "새", english: "Bird", romanization: "sae", category: "nature" },
  { korean: "물고기", english: "Fish", romanization: "mulgogi", category: "nature" },
  { korean: "소", english: "Cow", romanization: "so", category: "nature" },
  { korean: "돼지", english: "Pig", romanization: "dwaeji", category: "nature" },
  { korean: "닭", english: "Chicken", romanization: "dak", category: "nature" },
  { korean: "말", english: "Horse", romanization: "mal", category: "nature" },
  { korean: "토끼", english: "Rabbit", romanization: "tokki", category: "nature" },
  { korean: "곰", english: "Bear", romanization: "gom", category: "nature" },
  { korean: "호랑이", english: "Tiger", romanization: "horangi", category: "nature" },
  { korean: "사자", english: "Lion", romanization: "saja", category: "nature" },
  { korean: "코끼리", english: "Elephant", romanization: "kokkiri", category: "nature" },
  { korean: "원숭이", english: "Monkey", romanization: "wonsungi", category: "nature" },

  // HOUSEHOLD (29)
  { korean: "집안", english: "Indoors/Household", romanization: "jiban", category: "household" },
  { korean: "방", english: "Room", romanization: "bang", category: "household" },
  { korean: "침실", english: "Bedroom", romanization: "chimsil", category: "household" },
  { korean: "거실", english: "Living room", romanization: "geosil", category: "household" },
  { korean: "부엌", english: "Kitchen", romanization: "bueok", category: "household" },
  { korean: "화장실", english: "Bathroom/Restroom", romanization: "hwajangsil", category: "household" },
  { korean: "문", english: "Door", romanization: "mun", category: "household" },
  { korean: "창문", english: "Window", romanization: "changmun", category: "household" },
  { korean: "벽", english: "Wall", romanization: "byeok", category: "household" },
  { korean: "천장", english: "Ceiling", romanization: "cheonjang", category: "household" },
  { korean: "바닥", english: "Floor", romanization: "badak", category: "household" },
  { korean: "침대", english: "Bed", romanization: "chimdae", category: "household" },
  { korean: "소파", english: "Sofa", romanization: "sopa", category: "household" },
  { korean: "탁자", english: "Table", romanization: "takja", category: "household" },
  { korean: "냉장고", english: "Refrigerator", romanization: "naengjanggo", category: "household" },
  { korean: "세탁기", english: "Washing machine", romanization: "setakgi", category: "household" },
  { korean: "에어컨", english: "Air conditioner", romanization: "eeokon", category: "household" },
  { korean: "선풍기", english: "Fan", romanization: "seonpunggi", category: "household" },
  { korean: "전등", english: "Light", romanization: "jeondeung", category: "household" },
  { korean: "거울", english: "Mirror", romanization: "geoul", category: "household" },
  { korean: "전화기", english: "Telephone", romanization: "jeonhwagi", category: "household" },
  { korean: "리모컨", english: "Remote control", romanization: "rimokon", category: "household" },
  { korean: "청소기", english: "Vacuum cleaner", romanization: "cheongsogi", category: "household" },
  { korean: "빗", english: "Comb", romanization: "bit", category: "household" },
  { korean: "수건", english: "Towel", romanization: "sugeon", category: "household" },
  { korean: "비누", english: "Soap", romanization: "binu", category: "household" },
  { korean: "샴푸", english: "Shampoo", romanization: "syampu", category: "household" },
  { korean: "칫솔", english: "Toothbrush", romanization: "chitsol", category: "household" },
  { korean: "치약", english: "Toothpaste", romanization: "chiyak", category: "household" },

  // BUSINESS (83)
  { korean: "사업", english: "Business", romanization: "saeop", category: "business" },
  { korean: "직업", english: "Job/Occupation", romanization: "jigeop", category: "business" },
  { korean: "직장", english: "Workplace", romanization: "jikjang", category: "business" },
  { korean: "상사", english: "Boss", romanization: "sangsa", category: "business" },
  { korean: "동료", english: "Colleague", romanization: "dongryo", category: "business" },
  { korean: "직원", english: "Employee", romanization: "jigwon", category: "business" },
  { korean: "사장님", english: "President/CEO", romanization: "sajangnim", category: "business" },
  { korean: "부장님", english: "Department head", romanization: "bujangnim", category: "business" },
  { korean: "과장님", english: "Section chief", romanization: "gwajangnim", category: "business" },
  { korean: "대리", english: "Assistant manager", romanization: "daeri", category: "business" },
  { korean: "회의", english: "Meeting", romanization: "hoeui", category: "business" },
  { korean: "프로젝트", english: "Project", romanization: "peuroejekteu", category: "business" },
  { korean: "계약", english: "Contract", romanization: "gyeyak", category: "business" },
  { korean: "급여", english: "Salary", romanization: "geupyeo", category: "business" },
  { korean: "월급", english: "Monthly salary", romanization: "wolgeup", category: "business" },
  { korean: "보너스", english: "Bonus", romanization: "bonseoseu", category: "business" },
  { korean: "휴가", english: "Vacation", romanization: "hyuga", category: "business" },
  { korean: "야근", english: "Overtime work", romanization: "yageun", category: "business" },
  { korean: "출장", english: "Business trip", romanization: "chuljang", category: "business" },
  { korean: "퇴근", english: "Leaving work", romanization: "toegeun", category: "business" },
  { korean: "출근", english: "Going to work", romanization: "chulgeun", category: "business" },
  { korean: "명함", english: "Business card", romanization: "myeongham", category: "business" },
  { korean: "동의합니다", english: "I agree", romanization: "donguihamnida", category: "business" },
  { korean: "뵙게 되어 영광입니다", english: "It\\", romanization: "boepge doeeo yeonggwangimnida", category: "business" },
  { korean: "오랫동안 기다려 왔습니다", english: "I\\", romanization: "oraetdongan gidaryeo watseumnida", category: "business" },
  { korean: "번거롭게 해드려 죄송합니다", english: "I\\", romanization: "beongeoreopge haedeuryeo joesonghamnida", category: "business" },
  { korean: "명함을 주고받다", english: "To exchange business cards", romanization: "myeonghameul jugobatda", category: "business" },
  { korean: "명함 받으시겠습니까?", english: "Would you like my card?", romanization: "myeongham badeusigetsseumnikka?", category: "business" },
  { korean: "앞으로 잘 부탁드립니다", english: "I look forward to working with you", romanization: "apeuro jal butakdeurimnida", category: "business" },
  { korean: "귀사의 발전을 기원합니다", english: "I wish your company prosperity", romanization: "gwisaui baljeon-eul giwonhamnida", category: "business" },
  { korean: "회의 시작하겠습니다", english: "Let\\", romanization: "hoeui sijakhagetseumnida", category: "business" },
  { korean: "의견을 말씀해 주시기 바랍니다", english: "Please share your opinion", romanization: "uigyeoneul malssumhae jusigi baramnida", category: "business" },
  { korean: "검토해 보시겠습니까?", english: "Would you like to review it?", romanization: "geomtohae bosigetsseumnikka?", category: "business" },
  { korean: "결정을 내려야 합니다", english: "We need to make a decision", romanization: "gyeoljeongeul naeryeoya hamnida", category: "business" },
  { korean: "주무시다", english: "To sleep (honorific)", romanization: "jumusida", category: "business" },
  { korean: "말씀하시다", english: "To speak (honorific)", romanization: "malsseumasida", category: "business" },
  { korean: "여쭙다", english: "To ask (humble)", romanization: "yeojjipda", category: "business" },
  { korean: "드리다", english: "To give (humble)", romanization: "deurida", category: "business" },
  { korean: "은혜를 잊지 않겠습니다", english: "I won\\", romanization: "eunhyereul itji anketseumnida", category: "business" },
  { korean: "변명의 여지가 없습니다", english: "There\\", romanization: "byeonmyeongui yeojiga eopseumnida", category: "business" },
  { korean: "부디", english: "Please (formal)", romanization: "budi", category: "business" },
  { korean: "삼가 부탁드립니다", english: "I humbly request", romanization: "samga butakdeurimnida", category: "business" },
  { korean: "고려해 주시기 바랍니다", english: "Please consider", romanization: "goryeohae jusigi baramnida", category: "business" },
  { korean: "협조해 주시면 감사하겠습니다", english: "I would appreciate your cooperation", romanization: "hyeopjohae jusimyeon gamsahagetseumnida", category: "business" },
  { korean: "건배를 제의합니다", english: "I propose a toast", romanization: "geonbaereul jeuihamnida", category: "business" },
  { korean: "실례지만", english: "Excuse me, but", romanization: "sillyejiman", category: "business" },
  { korean: "송구스럽지만", english: "I\\", romanization: "songguseureopjiman", category: "business" },
  { korean: "감히 말씀드리자면", english: "If I may dare to say", romanization: "gamhi malsseumdeurijamyeon", category: "business" },
  { korean: "재고해 보시겠습니까?", english: "Would you reconsider?", romanization: "jaegohae bosigetsseumnikka?", category: "business" },
  { korean: "조정이 가능하십니까?", english: "Is adjustment possible?", romanization: "jojeongi ganeunghashipnikka?", category: "business" },
  { korean: "타협점을 찾아야 합니다", english: "We need to find a compromise", romanization: "tahyeopjeomdareul chajaya hamnida", category: "business" },
  { korean: "검토 후 연락드리겠습니다", english: "I will contact you after review", romanization: "geomto hu yeonrakdeurigetseumnida", category: "business" },
  { korean: "소견으로는", english: "In my opinion", romanization: "sogyeoneuro-neun", category: "business" },
  { korean: "사료됩니다", english: "It is thought / considered", romanization: "saryodoeemnida", category: "business" },
  { korean: "제안하는 바입니다", english: "This is what I propose", romanization: "jeanhaneun baimnida", category: "business" },
  { korean: "견해를 밝히자면", english: "To express my view", romanization: "gyeonhaereul balkhijamyeon", category: "business" },
  { korean: "전적으로 동의합니다", english: "I completely agree", romanization: "jeonjeogeuro donguihamnida", category: "business" },
  { korean: "이의가 없습니다", english: "I have no objection", romanization: "uiga eopseumnida", category: "business" },
  { korean: "찬성합니다", english: "I agree / I\\", romanization: "chanseonghamnida", category: "business" },
  { korean: "승인하겠습니다", english: "I will approve", romanization: "seunginhagesseumnida", category: "business" },
  { korean: "유감스럽게도", english: "Unfortunately / Regrettably", romanization: "yugamseureopgedo", category: "business" },
  { korean: "다소 의견이 다릅니다", english: "My opinion differs somewhat", romanization: "daso uigyeoni dareubnida", category: "business" },
  { korean: "재고가 필요하다고 봅니다", english: "I think reconsideration is needed", romanization: "jaegoga piryohadago bomnida", category: "business" },
  { korean: "기대하고 있습니다", english: "I\\", romanization: "gidaehago itseumnida", category: "business" },
  { korean: "마지막으로", english: "Finally / Lastly", romanization: "majimageuro", category: "business" },
  { korean: "결론적으로", english: "In conclusion", romanization: "gyeollonjeogeuro", category: "business" },
  { korean: "요약하자면", english: "To summarize", romanization: "yoyaghajamyeon", category: "business" },
  { korean: "이상으로 마치겠습니다", english: "I will conclude with this", romanization: "isangeuro machigetseumnida", category: "business" },
  { korean: "송구스럽습니다", english: "I\\", romanization: "songguseureopseumnida", category: "business" },
  { korean: "차후에", english: "Later / In the future", romanization: "chahue", category: "business" },
  { korean: "언젠가", english: "Someday", romanization: "eonjenga", category: "business" },
  { korean: "회장님", english: "Chairman (honorific)", romanization: "hoejangnim", category: "business" },
  { korean: "배려해 주시다", english: "To be considerate", romanization: "baeryeohae jusida", category: "business" },
  { korean: "하명하시다", english: "To command / To order (very respectful)", romanization: "hamyeonghashida", category: "business" },
  { korean: "지시하시다", english: "To instruct (honorific)", romanization: "jishihashida", category: "business" },
  { korean: "승낙하시다", english: "To consent (honorific)", romanization: "seungnakhashida", category: "business" },
  { korean: "양해를 구하다", english: "To ask for understanding", romanization: "yanghaereul guhada", category: "business" },
  { korean: "관대하게 봐주시다", english: "To look upon generously", romanization: "gwandaehage bwajusida", category: "business" },
  { korean: "각별히 부탁드리다", english: "To especially request", romanization: "gakbyeolhi butakdeurida", category: "business" },
  { korean: "더할 나위 없이", english: "Extremely / Couldn\\", romanization: "deohal nawi eopsi", category: "business" },
  { korean: "황송하다", english: "To be honored beyond measure", romanization: "hwangsonghada", category: "business" },
  { korean: "숙고하다", english: "To consider deeply", romanization: "sukgohada", category: "business" },
  { korean: "헤아려 주시다", english: "To understand / To sympathize", romanization: "hearyeo jusida", category: "business" },
];

module.exports = flashcardData;
