// Real Korean vocabulary for intermediate and advanced lessons
// This will replace the programmatically generated placeholder content

const createContentItem = (korean, romanization, english, type = 'word', example = '', exampleEnglish = '', breakdown = null) => ({
  type,
  korean,
  romanization,
  english,
  pronunciation: romanization,
  example: example || korean,
  exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown } : {}),
});

// DAILY LIFE - INTERMEDIATE: Daily Activities & Schedules
const dailyLifeIntermediate = [
  // Daily routines and habits
  createContentItem('습관', 'seupgwan', 'Habit', 'word', '좋은 습관을 가져요', 'I have good habits'),
  createContentItem('규칙', 'gyuchik', 'Rule', 'word', '규칙을 지켜요', 'I follow the rules'),
  createContentItem('일정', 'iljeong', 'Schedule', 'word', '일정을 확인해요', 'I check the schedule'),
  createContentItem('스케줄', 'seukejul', 'Schedule', 'word', '스케줄이 빡빡해요', 'My schedule is tight'),
  createContentItem('일상', 'ilsang', 'Daily life', 'word', '일상이 바빠요', 'My daily life is busy'),
  createContentItem('생활', 'saenghwal', 'Life/Lifestyle', 'word', '생활이 편해요', 'Life is comfortable'),
  createContentItem('취미', 'chwimi', 'Hobby', 'word', '취미가 뭐예요?', 'What is your hobby?'),
  createContentItem('관심', 'gwansim', 'Interest', 'word', '관심이 많아요', 'I have many interests'),
  createContentItem('여가', 'yeoga', 'Leisure', 'word', '여가 시간을 즐겨요', 'I enjoy leisure time'),
  createContentItem('계획', 'gyehoek', 'Plan', 'word', '주말 계획이 있어요', 'I have weekend plans'),
  createContentItem('목표', 'mokpyo', 'Goal', 'word', '목표를 세워요', 'I set goals'),
  createContentItem('꿈', 'kkum', 'Dream', 'word', '꿈이 있어요', 'I have a dream'),
  createContentItem('미래', 'mirae', 'Future', 'word', '미래를 준비해요', 'I prepare for the future'),
  createContentItem('과거', 'gwageo', 'Past', 'word', '과거를 돌아봐요', 'I look back at the past'),
  createContentItem('현재', 'hyeonjae', 'Present', 'word', '현재를 즐겨요', 'I enjoy the present'),

  // Time management
  createContentItem('시간 관리', 'sigan gwalli', 'Time management', 'word', '시간 관리가 중요해요', 'Time management is important', [{ korean: '시간', english: 'time' }, { korean: '관리', english: 'management' }]),
  createContentItem('효율적', 'hyoyuljeok', 'Efficient', 'word', '효율적으로 일해요', 'I work efficiently'),
  createContentItem('빠르다', 'ppareuda', 'To be fast', 'word', '빨리 끝내요', 'I finish quickly'),
  createContentItem('느리다', 'neurida', 'To be slow', 'word', '천천히 해요', 'I do it slowly'),
  createContentItem('서두르다', 'seodureuda', 'To hurry', 'word', '서둘러야 해요', 'I need to hurry'),
  createContentItem('늦다', 'neutda', 'To be late', 'word', '늦었어요', 'I\'m late'),
  createContentItem('일찍', 'iljjik', 'Early', 'word', '일찍 일어나요', 'I wake up early'),
  createContentItem('제시간', 'jesigan', 'On time', 'word', '제시간에 도착했어요', 'I arrived on time'),
  createContentItem('여유', 'yeoyu', 'Spare time/leisure', 'word', '여유가 없어요', 'I have no spare time'),
  createContentItem('바쁘다', 'bappeuda', 'To be busy', 'word', '요즘 바빠요', 'I\'m busy these days'),

  // Activities
  createContentItem('활동', 'hwaldong', 'Activity', 'word', '다양한 활동을 해요', 'I do various activities'),
  createContentItem('운동하다', 'undonghada', 'To exercise', 'word', '매일 운동해요', 'I exercise every day'),
  createContentItem('독서', 'dokseo', 'Reading', 'word', '독서를 즐겨요', 'I enjoy reading'),
  createContentItem('음악 감상', 'eumak gamsang', 'Music appreciation', 'word', '음악 감상을 좋아해요', 'I like listening to music', [{ korean: '음악', english: 'music' }, { korean: '감상', english: 'appreciation' }]),
  createContentItem('영화 관람', 'yeonghwa gwallam', 'Movie watching', 'word', '영화 관람을 해요', 'I watch movies', [{ korean: '영화', english: 'movie' }, { korean: '관람', english: 'viewing' }]),
  createContentItem('산책', 'sanchaek', 'Walk/Stroll', 'word', '공원에서 산책해요', 'I take a walk in the park'),
  createContentItem('조깅', 'joging', 'Jogging', 'word', '아침에 조깅해요', 'I jog in the morning'),
  createContentItem('수영', 'suyeong', 'Swimming', 'word', '수영을 배워요', 'I learn swimming'),
  createContentItem('요가', 'yoga', 'Yoga', 'word', '요가를 해요', 'I do yoga'),
  createContentItem('명상', 'myeongsang', 'Meditation', 'word', '명상을 해요', 'I meditate'),

  // Social activities
  createContentItem('모임', 'moim', 'Gathering/Meeting', 'word', '친구 모임이 있어요', 'I have a friend gathering'),
  createContentItem('약속', 'yaksok', 'Appointment/Promise', 'word', '약속 시간이에요', 'It\'s appointment time'),
  createContentItem('만남', 'mannam', 'Meeting/Encounter', 'word', '만남이 즐거워요', 'The meeting is pleasant'),
  createContentItem('대화', 'daehwa', 'Conversation', 'word', '대화를 나눠요', 'I have a conversation'),
  createContentItem('수다', 'suda', 'Chat/Gossip', 'word', '수다를 떨어요', 'I chat'),
  createContentItem('친목', 'chinmok', 'Friendship', 'word', '친목 도모를 해요', 'I build friendships'),
  createContentItem('동호회', 'donghohoe', 'Club/Society', 'word', '동호회에 가입했어요', 'I joined a club'),
  createContentItem('파티', 'pati', 'Party', 'word', '파티에 갔어요', 'I went to a party'),
  createContentItem('회식', 'hoesik', 'Company dinner', 'word', '회식이 있어요', 'There\'s a company dinner'),
  createContentItem('송년회', 'songnyeonhoe', 'Year-end party', 'word', '송년회에 참석해요', 'I attend the year-end party'),

  // Daily maintenance
  createContentItem('청소', 'cheongso', 'Cleaning', 'word', '방 청소를 해요', 'I clean my room'),
  createContentItem('빨래', 'ppallae', 'Laundry', 'word', '빨래를 해요', 'I do laundry'),
  createContentItem('설거지', 'seolgeoji', 'Dishwashing', 'word', '설거지를 해요', 'I wash dishes'),
  createContentItem('요리', 'yori', 'Cooking', 'word', '요리를 배워요', 'I learn cooking'),
  createContentItem('장보기', 'jangbogi', 'Grocery shopping', 'word', '장을 봐요', 'I go grocery shopping'),
  createContentItem('정리', 'jeongni', 'Organizing', 'word', '방을 정리해요', 'I organize my room'),
  createContentItem('정돈', 'jeongdon', 'Tidying', 'word', '책상을 정돈해요', 'I tidy my desk'),
  createContentItem('쓰레기', 'sseuregi', 'Trash/Garbage', 'word', '쓰레기를 버려요', 'I throw out trash'),
  createContentItem('분리수거', 'bunrisugeo', 'Recycling', 'word', '분리수거를 해요', 'I recycle'),
  createContentItem('집안일', 'jibanil', 'Housework', 'word', '집안일을 도와요', 'I help with housework'),

  // Personal care
  createContentItem('외모', 'oemo', 'Appearance', 'word', '외모를 가꿔요', 'I take care of my appearance'),
  createContentItem('머리', 'meori', 'Hair', 'word', '머리를 자르러 가요', 'I go to get a haircut'),
  createContentItem('화장', 'hwajang', 'Makeup', 'word', '화장을 해요', 'I put on makeup'),
  createContentItem('스킨케어', 'seukinkeeo', 'Skincare', 'word', '스킨케어를 해요', 'I do skincare'),
  createContentItem('목욕', 'mogyok', 'Bath', 'word', '목욕을 해요', 'I take a bath'),
  createContentItem('샤워', 'syawo', 'Shower', 'word', '샤워를 해요', 'I take a shower'),
  createContentItem('세수', 'sesu', 'Face washing', 'word', '세수를 해요', 'I wash my face'),
  createContentItem('양치', 'yangchi', 'Tooth brushing', 'word', '양치를 해요', 'I brush my teeth'),
  createContentItem('면도', 'myeondo', 'Shaving', 'word', '면도를 해요', 'I shave'),
  createContentItem('손질', 'sonjil', 'Grooming', 'word', '손질을 해요', 'I groom myself'),

  // Entertainment
  createContentItem('오락', 'orak', 'Entertainment', 'word', '오락을 즐겨요', 'I enjoy entertainment'),
  createContentItem('게임', 'geim', 'Game', 'word', '게임을 해요', 'I play games'),
  createContentItem('드라마', 'deurama', 'Drama/TV series', 'word', '드라마를 봐요', 'I watch dramas'),
  createContentItem('예능', 'yeneung', 'Variety show', 'word', '예능을 좋아해요', 'I like variety shows'),
  createContentItem('뉴스', 'nyuseu', 'News', 'word', '뉴스를 봐요', 'I watch news'),
  createContentItem('다큐멘터리', 'dakyumenteo ri', 'Documentary', 'word', '다큐를 봐요', 'I watch documentaries'),
  createContentItem('공연', 'gongyeon', 'Performance', 'word', '공연을 보러 가요', 'I go to see a performance'),
  createContentItem('콘서트', 'konseoteu', 'Concert', 'word', '콘서트에 갔어요', 'I went to a concert'),
  createContentItem('전시회', 'jeonsihoe', 'Exhibition', 'word', '전시회를 관람해요', 'I visit an exhibition'),
  createContentItem('박물관', 'bangmulgwan', 'Museum', 'word', '박물관에 가요', 'I go to the museum'),

  // Study and learning
  createContentItem('공부', 'gongbu', 'Study', 'word', '열심히 공부해요', 'I study hard'),
  createContentItem('학습', 'hakseup', 'Learning', 'word', '학습을 계속해요', 'I continue learning'),
  createContentItem('복습', 'bokseup', 'Review', 'word', '복습을 해요', 'I review'),
  createContentItem('예습', 'yeseup', 'Preview', 'word', '예습을 해요', 'I preview'),
  createContentItem('숙제', 'sukje', 'Homework', 'word', '숙제를 해요', 'I do homework'),
  createContentItem('과제', 'gwaje', 'Assignment', 'word', '과제를 제출해요', 'I submit assignments'),
  createContentItem('시험', 'siheom', 'Exam/Test', 'word', '시험을 봐요', 'I take an exam'),
  createContentItem('자격증', 'jagyeokjeung', 'Certification', 'word', '자격증을 따요', 'I get certified'),
  createContentItem('어학', 'eohak', 'Language study', 'word', '어학 공부를 해요', 'I study language'),
  createContentItem('독학', 'dokhak', 'Self-study', 'word', '독학으로 배워요', 'I learn by self-study'),

  // Rest and relaxation
  createContentItem('휴식', 'hyusik', 'Rest', 'word', '휴식이 필요해요', 'I need rest'),
  createContentItem('쉬다', 'swida', 'To rest', 'word', '집에서 쉬어요', 'I rest at home'),
  createContentItem('낮잠', 'natjam', 'Nap', 'word', '낮잠을 자요', 'I take a nap'),
  createContentItem('잠', 'jam', 'Sleep', 'word', '잠을 자요', 'I sleep'),
  createContentItem('수면', 'sumyeon', 'Sleep', 'word', '수면이 부족해요', 'I lack sleep'),
  createContentItem('피로', 'piro', 'Fatigue', 'word', '피로가 쌓여요', 'Fatigue builds up'),
  createContentItem('스트레스', 'seuteureseu', 'Stress', 'word', '스트레스를 풀어요', 'I relieve stress'),
  createContentItem('긴장', 'ginjang', 'Tension', 'word', '긴장을 풀어요', 'I release tension'),
  createContentItem('여행', 'yeohaeng', 'Travel', 'word', '여행을 가요', 'I go traveling'),
  createContentItem('휴가', 'hyuga', 'Vacation', 'word', '휴가를 내요', 'I take vacation'),

  // Communication
  createContentItem('연락', 'yeollak', 'Contact', 'word', '연락을 해요', 'I make contact'),
  createContentItem('전화', 'jeonhwa', 'Phone call', 'word', '전화를 해요', 'I make a phone call'),
  createContentItem('문자', 'munja', 'Text message', 'word', '문자를 보내요', 'I send a text'),
  createContentItem('이메일', 'imeil', 'Email', 'word', '이메일을 확인해요', 'I check email'),
  createContentItem('메시지', 'mesiji', 'Message', 'word', '메시지를 남겨요', 'I leave a message'),
  createContentItem('SNS', 'eseuenseu', 'Social media', 'word', 'SNS를 해요', 'I use social media'),
  createContentItem('인스타그램', 'inseutageuRam', 'Instagram', 'word', '인스타에 올려요', 'I post on Instagram'),
  createContentItem('페이스북', 'peiseubuk', 'Facebook', 'word', '페이스북을 봐요', 'I check Facebook'),
  createContentItem('카톡', 'katok', 'KakaoTalk', 'word', '카톡을 해요', 'I use KakaoTalk'),
  createContentItem('영상통화', 'yeongsangtonghwa', 'Video call', 'word', '영상통화를 해요', 'I make a video call')
];

// DAILY LIFE - ADVANCED: Lifestyle & Cultural Practices
const dailyLifeAdvanced = [
  // Cultural practices
  createContentItem('전통', 'jeontong', 'Tradition', 'word', '전통을 지켜요', 'I preserve traditions'),
  createContentItem('문화', 'munhwa', 'Culture', 'word', '한국 문화를 배워요', 'I learn Korean culture'),
  createContentItem('풍습', 'pungseup', 'Custom', 'word', '전통 풍습이에요', 'It\'s a traditional custom'),
  createContentItem('예절', 'yejeol', 'Etiquette', 'word', '예절을 지켜요', 'I follow etiquette'),
  createContentItem('관습', 'gwanseup', 'Convention', 'word', '사회 관습이에요', 'It\'s a social convention'),
  createContentItem('의식', 'uisik', 'Ceremony/Consciousness', 'word', '전통 의식에 참여해요', 'I participate in traditional ceremonies'),
  createContentItem('행사', 'haengsa', 'Event', 'word', '문화 행사가 있어요', 'There\'s a cultural event'),
  createContentItem('축제', 'chukje', 'Festival', 'word', '축제에 가요', 'I go to a festival'),
  createContentItem('명절', 'myeongjeol', 'Holiday', 'word', '명절을 쇠요', 'I celebrate the holiday'),
  createContentItem('설날', 'seollal', 'Lunar New Year', 'word', '설날에 떡국을 먹어요', 'I eat rice cake soup on Lunar New Year'),
  createContentItem('추석', 'chuseok', 'Chuseok/Harvest Festival', 'word', '추석에 송편을 먹어요', 'I eat songpyeon on Chuseok'),
  createContentItem('설', 'seol', 'New Year', 'word', '설을 쇠요', 'I celebrate New Year'),
  createContentItem('차례', 'charye', 'Ancestral rites', 'word', '차례를 지내요', 'I perform ancestral rites'),
  createContentItem('제사', 'jesa', 'Memorial service', 'word', '제사를 지내요', 'I hold a memorial service'),
  createContentItem('세배', 'sebae', 'New Year\'s bow', 'word', '세배를 드려요', 'I give New Year\'s bow'),

  // Lifestyle choices
  createContentItem('라이프스타일', 'raipeuseutail', 'Lifestyle', 'word', '건강한 라이프스타일이에요', 'It\'s a healthy lifestyle'),
  createContentItem('삶의 방식', 'salmui bangsik', 'Way of life', 'word', '삶의 방식을 바꿔요', 'I change my way of life', [{ korean: '삶의', english: 'of life' }, { korean: '방식', english: 'way/method' }]),
  createContentItem('가치관', 'gachigwan', 'Values', 'word', '가치관이 중요해요', 'Values are important'),
  createContentItem('신념', 'sinnyeom', 'Belief', 'word', '신념을 가져요', 'I have beliefs'),
  createContentItem('철학', 'cheolhak', 'Philosophy', 'word', '인생 철학이 있어요', 'I have a life philosophy'),
  createContentItem('태도', 'taedo', 'Attitude', 'word', '긍정적인 태도예요', 'It\'s a positive attitude'),
  createContentItem('자세', 'jase', 'Posture/Attitude', 'word', '올바른 자세가 필요해요', 'I need proper posture'),
  createContentItem('습성', 'seupseong', 'Nature/Habit', 'word', '습성을 고쳐요', 'I fix my habits'),
  createContentItem('버릇', 'beoreut', 'Habit/Manner', 'word', '나쁜 버릇을 고쳐요', 'I fix bad habits'),
  createContentItem('패턴', 'paeteon', 'Pattern', 'word', '생활 패턴을 바꿔요', 'I change my life pattern'),

  // Social relationships
  createContentItem('인간관계', 'in gangwangye', 'Human relationships', 'word', '인간관계가 중요해요', 'Human relationships are important'),
  createContentItem('대인관계', 'daein gwangye', 'Interpersonal relationships', 'word', '대인관계를 잘해요', 'I\'m good at interpersonal relationships'),
  createContentItem('친분', 'chinbun', 'Friendship/Acquaintance', 'word', '친분을 쌓아요', 'I build friendships'),
  createContentItem('인연', 'inyeon', 'Connection/Fate', 'word', '좋은 인연이에요', 'It\'s a good connection'),
  createContentItem('유대', 'yudae', 'Bond', 'word', '유대를 강화해요', 'I strengthen bonds'),
  createContentItem('교류', 'gyoryu', 'Exchange/Interaction', 'word', '문화 교류를 해요', 'I do cultural exchange'),
  createContentItem('소통', 'sotong', 'Communication', 'word', '소통이 중요해요', 'Communication is important'),
  createContentItem('협력', 'hyeopnyeok', 'Cooperation', 'word', '협력해요', 'I cooperate'),
  createContentItem('배려', 'baeryeo', 'Consideration', 'word', '배려를 해요', 'I show consideration'),
  createContentItem('존중', 'jonjung', 'Respect', 'word', '서로 존중해요', 'We respect each other'),

  // Personal development
  createContentItem('자기계발', 'jagi gyebal', 'Self-development', 'word', '자기계발을 해요', 'I do self-development'),
  createContentItem('성장', 'seongjang', 'Growth', 'word', '개인적 성장을 해요', 'I have personal growth'),
  createContentItem('발전', 'baljeon', 'Development', 'word', '계속 발전해요', 'I continue to develop'),
  createContentItem('향상', 'hyangsang', 'Improvement', 'word', '실력이 향상돼요', 'My skills improve'),
  createContentItem('개선', 'gaeseon', 'Improvement', 'word', '개선이 필요해요', 'Improvement is needed'),
  createContentItem('혁신', 'hyeoksin', 'Innovation', 'word', '혁신을 추구해요', 'I pursue innovation'),
  createContentItem('변화', 'byeonhwa', 'Change', 'word', '변화가 필요해요', 'Change is needed'),
  createContentItem('전환', 'jeonhwan', 'Transition', 'word', '인생의 전환점이에요', 'It\'s a life turning point'),
  createContentItem('도전', 'dojeon', 'Challenge', 'word', '새로운 도전을 해요', 'I take on new challenges'),
  createContentItem('시도', 'sido', 'Attempt', 'word', '계속 시도해요', 'I keep trying'),

  // Balance and wellness
  createContentItem('균형', 'gyunhyeong', 'Balance', 'word', '일과 삶의 균형', 'Work-life balance'),
  createContentItem('조화', 'johwa', 'Harmony', 'word', '조화를 이뤄요', 'I achieve harmony'),
  createContentItem('안정', 'anjeong', 'Stability', 'word', '정신적 안정이에요', 'It\'s mental stability'),
  createContentItem('평온', 'pyeongon', 'Peace', 'word', '평온한 생활이에요', 'It\'s a peaceful life'),
  createContentItem('행복', 'haengbok', 'Happiness', 'word', '행복을 추구해요', 'I pursue happiness'),
  createContentItem('만족', 'manjok', 'Satisfaction', 'word', '삶에 만족해요', 'I\'m satisfied with life'),
  createContentItem('충족', 'chungjok', 'Fulfillment', 'word', '욕구를 충족해요', 'I fulfill needs'),
  createContentItem('성취', 'seongchwi', 'Achievement', 'word', '성취감을 느껴요', 'I feel a sense of achievement'),
  createContentItem('보람', 'boram', 'Reward/Worth', 'word', '보람을 느껴요', 'I feel rewarded'),
  createContentItem('의미', 'uimi', 'Meaning', 'word', '삶의 의미를 찾아요', 'I find meaning in life'),

  // Modern lifestyle
  createContentItem('디지털', 'dijiteol', 'Digital', 'word', '디지털 생활을 해요', 'I live a digital life'),
  createContentItem('온라인', 'onlain', 'Online', 'word', '온라인으로 일해요', 'I work online'),
  createContentItem('오프라인', 'opeullain', 'Offline', 'word', '오프라인 활동도 해요', 'I do offline activities too'),
  createContentItem('재택근무', 'jaetaekgeunmu', 'Working from home', 'word', '재택근무를 해요', 'I work from home'),
  createContentItem('원격', 'wongyeok', 'Remote', 'word', '원격으로 회의해요', 'I have remote meetings'),
  createContentItem('플랫폼', 'peullaetpom', 'Platform', 'word', '다양한 플랫폼을 써요', 'I use various platforms'),
  createContentItem('네트워크', 'neteuwokeu', 'Network', 'word', '네트워크를 구축해요', 'I build a network'),
  createContentItem('연결', 'yeolgyeol', 'Connection', 'word', '글로벌 연결이에요', 'It\'s a global connection'),
  createContentItem('접근성', 'jeopgeunseong', 'Accessibility', 'word', '접근성이 좋아요', 'Accessibility is good'),
  createContentItem('편리성', 'pyeonliseong', 'Convenience', 'word', '편리성이 높아요', 'Convenience is high'),

  // Environmental consciousness
  createContentItem('환경', 'hwan gyeong', 'Environment', 'word', '환경을 보호해요', 'I protect the environment'),
  createContentItem('친환경', 'chinhwangyeong', 'Eco-friendly', 'word', '친환경 제품을 써요', 'I use eco-friendly products'),
  createContentItem('재활용', 'jaehwalyong', 'Recycling', 'word', '재활용을 해요', 'I recycle'),
  createContentItem('절약', 'jeoryak', 'Saving', 'word', '에너지를 절약해요', 'I save energy'),
  createContentItem('소비', 'sobi', 'Consumption', 'word', '현명한 소비를 해요', 'I consume wisely'),
  createContentItem('지속가능', 'jisokkaneung', 'Sustainable', 'word', '지속가능한 생활이에요', 'It\'s a sustainable life'),
  createContentItem('실천', 'silcheon', 'Practice', 'word', '환경 보호를 실천해요', 'I practice environmental protection'),
  createContentItem('캠페인', 'kaempeain', 'Campaign', 'word', '캠페인에 참여해요', 'I participate in campaigns'),
  createContentItem('인식', 'insik', 'Awareness', 'word', '환경 인식이 높아요', 'Environmental awareness is high'),
  createContentItem('책임', 'chaegim', 'Responsibility', 'word', '사회적 책임을 져요', 'I take social responsibility'),

  // Additional lifestyle concepts
  createContentItem('취향', 'chwihyang', 'Taste/Preference', 'word', '취향이 비슷해요', 'Our tastes are similar'),
  createContentItem('스타일', 'seutail', 'Style', 'word', '개인 스타일이에요', 'It\'s a personal style'),
  createContentItem('트렌드', 'teurendeu', 'Trend', 'word', '최신 트렌드를 따라요', 'I follow the latest trends'),
  createContentItem('유행', 'yuhaeng', 'Fashion/Trend', 'word', '유행을 따라요', 'I follow fashion'),
  createContentItem('세대', 'sedae', 'Generation', 'word', '세대 차이가 있어요', 'There\'s a generation gap'),
  createContentItem('연령', 'yeollyeong', 'Age', 'word', '연령대가 다양해요', 'Age groups are diverse'),
  createContentItem('계층', 'gyecheung', 'Class/Layer', 'word', '사회 계층이에요', 'It\'s a social class'),
  createContentItem('배경', 'baegyeong', 'Background', 'word', '문화적 배경이 달라요', 'Cultural backgrounds are different'),
  createContentItem('경험', 'gyeongheom', 'Experience', 'word', '다양한 경험을 해요', 'I have various experiences'),
  createContentItem('추억', 'chueok', 'Memory', 'word', '좋은 추억을 만들어요', 'I make good memories'),

  // Mindfulness and spirituality
  createContentItem('마음가짐', 'maeumgajim', 'Mindset', 'word', '긍정적인 마음가짐이에요', 'It\'s a positive mindset'),
  createContentItem('정신', 'jeongsin', 'Spirit/Mind', 'word', '정신이 건강해요', 'My spirit is healthy'),
  createContentItem('심리', 'simni', 'Psychology', 'word', '심리 상태가 좋아요', 'My psychological state is good'),
  createContentItem('감정', 'gamjeong', 'Emotion', 'word', '감정을 표현해요', 'I express emotions'),
  createContentItem('느낌', 'neukkim', 'Feeling', 'word', '좋은 느낌이에요', 'It\'s a good feeling'),
  createContentItem('기분', 'gibun', 'Mood', 'word', '기분이 좋아요', 'I\'m in a good mood'),
  createContentItem('분위기', 'bunwigi', 'Atmosphere', 'word', '분위기가 좋아요', 'The atmosphere is good'),
  createContentItem('상태', 'sangtae', 'State/Condition', 'word', '컨디션 상태가 좋아요', 'My condition is good'),
  createContentItem('웰빙', 'welbing', 'Well-being', 'word', '웰빙을 추구해요', 'I pursue well-being'),
  createContentItem('건강관리', 'geongangwalli', 'Health management', 'word', '건강관리를 해요', 'I manage my health')
];

// FOOD - INTERMEDIATE: Restaurant Conversations
const foodIntermediate = [
  // Restaurant basics
  createContentItem('식당', 'sikdang', 'Restaurant', 'word', '식당에 가요', 'I go to a restaurant'),
  createContentItem('음식점', 'eumsikjeom', 'Eatery', 'word', '맛있는 음식점이에요', 'It\'s a delicious eatery'),
  createContentItem('맛집', 'matjip', 'Great restaurant', 'word', '맛집을 찾아요', 'I look for great restaurants'),
  createContentItem('메뉴판', 'menyupan', 'Menu', 'word', '메뉴판을 보여주세요', 'Please show me the menu'),
  createContentItem('주문', 'jumun', 'Order', 'word', '주문하시겠어요?', 'Would you like to order?'),
  createContentItem('예약', 'yeyak', 'Reservation', 'word', '예약했어요', 'I made a reservation'),
  createContentItem('자리', 'jari', 'Seat', 'word', '자리가 있어요?', 'Is there a seat available?'),
  createContentItem('테이블', 'teibeul', 'Table', 'word', '테이블을 예약했어요', 'I reserved a table'),
  createContentItem('좌석', 'jwaseok', 'Seat', 'word', '좌석을 안내해 주세요', 'Please guide me to a seat'),
  createContentItem('대기', 'daegi', 'Waiting', 'word', '대기 시간이 얼마예요?', 'How long is the wait?'),

  // Ordering food
  createContentItem('주문하다', 'jumunhada', 'To order', 'word', '주문할게요', 'I\'ll order'),
  createContentItem('추천', 'chucheon', 'Recommendation', 'word', '뭘 추천해요?', 'What do you recommend?'),
  createContentItem('인기', 'ingi', 'Popular', 'word', '인기 메뉴가 뭐예요?', 'What\'s the popular menu item?'),
  createContentItem('특선', 'teukseon', 'Special', 'word', '오늘의 특선이에요', 'It\'s today\'s special'),
  createContentItem('세트', 'seteu', 'Set menu', 'word', '세트로 주문해요', 'I order the set menu'),
  createContentItem('단품', 'danpum', 'A la carte', 'word', '단품으로 주세요', 'Please give me a la carte'),
  createContentItem('사이드', 'saideu', 'Side dish', 'word', '사이드 메뉴예요', 'It\'s a side menu'),
  createContentItem('음료', 'eumnyo', 'Beverage', 'word', '음료도 주문해요', 'I also order a beverage'),
  createContentItem('후식', 'husik', 'Dessert', 'word', '후식으로 뭐 있어요?', 'What do you have for dessert?'),
  createContentItem('디저트', 'dijeo teu', 'Dessert', 'word', '디저트 메뉴 주세요', 'Please give me the dessert menu'),

  // Food preparation
  createContentItem('조리', 'jori', 'Cooking', 'word', '조리 시간이 얼마예요?', 'How long does cooking take?'),
  createContentItem('요리법', 'yoribeop', 'Cooking method', 'word', '요리법이 특별해요', 'The cooking method is special'),
  createContentItem('양념', 'yangnyeom', 'Seasoning', 'word', '양념이 맛있어요', 'The seasoning is delicious'),
  createContentItem('간', 'gan', 'Seasoning/Taste', 'word', '간이 맞아요', 'The seasoning is right'),
  createContentItem('맵기', 'maepgi', 'Spiciness level', 'word', '맵기를 조절해 주세요', 'Please adjust the spiciness'),
  createContentItem('맵다', 'maepda', 'To be spicy', 'word', '너무 매워요', 'It\'s too spicy'),
  createContentItem('달다', 'dalda', 'To be sweet', 'word', '달아요', 'It\'s sweet'),
  createContentItem('짜다', 'jjada', 'To be salty', 'word', '좀 짜요', 'It\'s a bit salty'),
  createContentItem('싱겁다', 'singgeopda', 'To be bland', 'word', '싱거워요', 'It\'s bland'),
  createContentItem('시다', 'sida', 'To be sour', 'word', '셔요', 'It\'s sour'),

  // Taste and texture
  createContentItem('맛', 'mat', 'Taste/Flavor', 'word', '맛이 좋아요', 'The taste is good'),
  createContentItem('맛있다', 'masitda', 'To be delicious', 'word', '정말 맛있어요', 'It\'s really delicious'),
  createContentItem('맛없다', 'maseopda', 'To be not delicious', 'word', '맛없어요', 'It\'s not delicious'),
  createContentItem('향', 'hyang', 'Aroma/Scent', 'word', '향이 좋아요', 'The aroma is good'),
  createContentItem('냄새', 'naemsae', 'Smell', 'word', '좋은 냄새가 나요', 'It smells good'),
  createContentItem('식감', 'sikgam', 'Texture', 'word', '식감이 좋아요', 'The texture is good'),
  createContentItem('부드럽다', 'budeureopda', 'To be soft', 'word', '부드러워요', 'It\'s soft'),
  createContentItem('딱딱하다', 'ttakttakada', 'To be hard', 'word', '딱딱해요', 'It\'s hard'),
  createContentItem('쫄깃하다', 'jjolgithada', 'To be chewy', 'word', '쫄깃해요', 'It\'s chewy'),
  createContentItem('바삭하다', 'basakhada', 'To be crispy', 'word', '바삭해요', 'It\'s crispy'),

  // Portion and presentation
  createContentItem('양', 'yang', 'Portion/Amount', 'word', '양이 많아요', 'The portion is large'),
  createContentItem('분량', 'bullyang', 'Quantity', 'word', '분량이 적당해요', 'The quantity is just right'),
  createContentItem('크기', 'keugi', 'Size', 'word', '크기가 커요', 'The size is big'),
  createContentItem('모양', 'moyang', 'Shape/Appearance', 'word', '모양이 예뻐요', 'The shape is pretty'),
  createContentItem('색깔', 'saekkal', 'Color', 'word', '색깔이 선명해요', 'The color is vivid'),
  createContentItem('담다', 'damda', 'To serve/plate', 'word', '예쁘게 담았어요', 'It\'s beautifully plated'),
  createContentItem('장식', 'jangsik', 'Decoration', 'word', '장식이 화려해요', 'The decoration is fancy'),
  createContentItem('플레이팅', 'peulleiting', 'Plating', 'word', '플레이팅이 멋있어요', 'The plating is nice'),
  createContentItem('신선하다', 'sinseonhada', 'To be fresh', 'word', '재료가 신선해요', 'The ingredients are fresh'),
  createContentItem('상하다', 'sanghada', 'To go bad', 'word', '음식이 상했어요', 'The food has gone bad'),

  // Service and atmosphere  createContentItem('서비스', 'seobiseu', 'Service', 'word', '서비스가 좋아요', 'The service is good'),
  createContentItem('직원', 'jigwon', 'Staff', 'word', '직원이 친절해요', 'The staff is kind'),
  createContentItem('친절', 'chinjeol', 'Kindness', 'word', '친절해요', 'They\'re kind'),
  createContentItem('응대', 'eungdae', 'Reception/Service', 'word', '응대가 빨라요', 'The service is fast'),
  createContentItem('분위기', 'bunwigi', 'Atmosphere', 'word', '분위기가 좋아요', 'The atmosphere is good'),
  createContentItem('인테리어', 'interieo', 'Interior', 'word', '인테리어가 멋있어요', 'The interior is nice'),
  createContentItem('조명', 'jomyeong', 'Lighting', 'word', '조명이 아늑해요', 'The lighting is cozy'),
  createContentItem('음악', 'eumak', 'Music', 'word', '배경 음악이 좋아요', 'The background music is good'),
  createContentItem('청결', 'cheonggyeol', 'Cleanliness', 'word', '청결해요', 'It\'s clean'),
  createContentItem('위생', 'wisaeng', 'Hygiene', 'word', '위생 상태가 좋아요', 'The hygiene is good'),

  // Dietary preferences
  createContentItem('알레르기', 'allereugi', 'Allergy', 'word', '알레르기가 있어요', 'I have allergies'),
  createContentItem('채식', 'chaesik', 'Vegetarian', 'word', '채식 메뉴 있어요?', 'Do you have vegetarian menu?'),
  createContentItem('비건', 'bigeon', 'Vegan', 'word', '비건이에요', 'I\'m vegan'),
  createContentItem('할랄', 'hallal', 'Halal', 'word', '할랄 음식이에요', 'It\'s halal food'),
  createContentItem('금기', 'geumgi', 'Taboo', 'word', '종교적 금기예요', 'It\'s a religious taboo'),
  createContentItem('제외', 'jeoee', 'Exclude', 'word', '파를 제외해 주세요', 'Please exclude green onions'),
  createContentItem('빼다', 'ppaeda', 'To remove', 'word', '양파를 빼 주세요', 'Please remove the onions'),
  createContentItem('추가', 'chuga', 'Addition', 'word', '치즈 추가해 주세요', 'Please add cheese'),
  createContentItem('더', 'deo', 'More', 'word', '더 주세요', 'Please give me more'),
  createContentItem('덜', 'deol', 'Less', 'word', '덜 넣어 주세요', 'Please put less'),

  // Payment and billing
  createContentItem('계산', 'gyesan', 'Bill/Check', 'word', '계산해 주세요', 'Check please'),
  createContentItem('계산서', 'gyesanseo', 'Bill', 'word', '계산서 주세요', 'Please give me the bill'),
  createContentItem('영수증', 'yeongsujeung', 'Receipt', 'word', '영수증 주세요', 'Receipt please'),
  createContentItem('가격', 'gagyeok', 'Price', 'word', '가격이 합리적이에요', 'The price is reasonable'),
  createContentItem('값', 'gap', 'Price', 'word', '값이 비싸요', 'The price is expensive'),
  createContentItem('현금', 'hyeongeum', 'Cash', 'word', '현금으로 낼게요', 'I\'ll pay with cash'),
  createContentItem('카드', 'kadeu', 'Card', 'word', '카드 돼요?', 'Do you accept cards?'),
  createContentItem('할인', 'harin', 'Discount', 'word', '할인 돼요?', 'Is there a discount?'),
  createContentItem('쿠폰', 'kupon', 'Coupon', 'word', '쿠폰 있어요', 'I have a coupon'),
  createContentItem('팁', 'tip', 'Tip', 'word', '팁을 줘요', 'I give a tip'),

  // Complaints and feedback
  createContentItem('불만', 'bulman', 'Complaint', 'word', '불만이 있어요', 'I have a complaint'),
  createContentItem('문제', 'munje', 'Problem', 'word', '문제가 있어요', 'There\'s a problem'),
  createContentItem('실수', 'silsu', 'Mistake', 'word', '주문 실수가 있어요', 'There\'s an order mistake'),
  createContentItem('잘못', 'jalmot', 'Error/Wrong', 'word', '잘못 나왔어요', 'It came out wrong'),
  createContentItem('바꾸다', 'bakkuda', 'To change', 'word', '바꿔 주세요', 'Please change it'),
  createContentItem('환불', 'hwanbul', 'Refund', 'word', '환불해 주세요', 'Please refund'),
  createContentItem('보상', 'bosang', 'Compensation', 'word', '보상을 원해요', 'I want compensation'),
  createContentItem('사과', 'sagwa', 'Apology', 'word', '사과를 받았어요', 'I received an apology'),
  createContentItem('개선', 'gaeseon', 'Improvement', 'word', '개선이 필요해요', 'Improvement is needed'),
  createContentItem('리뷰', 'ribyu', 'Review', 'word', '리뷰를 써요', 'I write a review'),

  // Additional restaurant vocabulary
  createContentItem('포장', 'pojang', 'Takeout/Packaging', 'word', '포장해 주세요', 'Please pack it to go'),
  createContentItem('배달', 'baedal', 'Delivery', 'word', '배달 돼요?', 'Do you deliver?'),
  createContentItem('테이크아웃', 'teikeuaus', 'Takeout', 'word', '테이크아웃으로 주세요', 'Please give me takeout'),
  createContentItem('먹고 가다', 'meokgo gada', 'To dine in', 'word', '먹고 갈게요', 'I\'ll dine in', [{ korean: '먹고', english: 'eat and' }, { korean: '가다', english: 'go (dine in)' }]),
  createContentItem('남기다', 'namgida', 'To leave behind', 'word', '남겼어요', 'I left some'),
  createContentItem('다 먹다', 'da meokda', 'To finish eating', 'word', '다 먹었어요', 'I finished eating', [{ korean: '다', english: 'all' }, { korean: '먹다', english: 'to eat' }]),
  createContentItem('배부르다', 'baebureuda', 'To be full', 'word', '배불러요', 'I\'m full'),
  createContentItem('배고프다', 'baegopeuda', 'To be hungry', 'word', '아직 배고파요', 'I\'m still hungry'),
  createContentItem('목마르다', 'mongmareuda', 'To be thirsty', 'word', '목말라요', 'I\'m thirsty'),
  createContentItem('리필', 'ripil', 'Refill', 'word', '리필 돼요?', 'Can I get a refill?')
];

// FOOD - ADVANCED: Korean Cuisine Culture
const foodAdvanced = [
  // Traditional Korean dishes
  createContentItem('한식', 'hansik', 'Korean food', 'word', '한식을 좋아해요', 'I like Korean food'),
  createContentItem('전통 음식', 'jeontong eumsik', 'Traditional food', 'word', '전통 음식을 먹어요', 'I eat traditional food', [{ korean: '전통', english: 'traditional' }, { korean: '음식', english: 'food' }]),
  createContentItem('궁중 요리', 'gungjung yori', 'Royal court cuisine', 'word', '궁중 요리예요', 'It\'s royal court cuisine', [{ korean: '궁중', english: 'royal court' }, { korean: '요리', english: 'cuisine' }]),
  createContentItem('향토 음식', 'hyangto eumsik', 'Local food', 'word', '향토 음식이에요', 'It\'s local food', [{ korean: '향토', english: 'local/regional' }, { korean: '음식', english: 'food' }]),
  createContentItem('계절 음식', 'gyejeol eumsik', 'Seasonal food', 'word', '계절 음식이에요', 'It\'s seasonal food', [{ korean: '계절', english: 'seasonal' }, { korean: '음식', english: 'food' }]),
  createContentItem('발효 식품', 'balhyo sikpum', 'Fermented food', 'word', '김치는 발효 식품이에요', 'Kimchi is a fermented food', [{ korean: '발효', english: 'fermented' }, { korean: '식품', english: 'food product' }]),
  createContentItem('장류', 'jangnyu', 'Fermented sauces', 'word', '장류가 중요해요', 'Fermented sauces are important'),
  createContentItem('된장', 'doenjang', 'Soybean paste', 'word', '된장찌개를 끓여요', 'I make doenjang stew'),
  createContentItem('고추장', 'gochujang', 'Red chili paste', 'word', '고추장을 넣어요', 'I add gochujang'),
  createContentItem('간장', 'ganjang', 'Soy sauce', 'word', '간장으로 간을 해요', 'I season with soy sauce'),

  // Korean dining culture
  createContentItem('상차림', 'sangcharim', 'Table setting', 'word', '전통 상차림이에요', 'It\'s a traditional table setting'),
  createContentItem('반상', 'bansang', 'Korean table d\'hote', 'word', '반상을 차려요', 'I set up bansang'),
  createContentItem('밥상', 'bapsang', 'Dining table', 'word', '밥상을 차려요', 'I set the table'),
  createContentItem('반찬', 'banchan', 'Side dishes', 'word', '반찬이 많아요', 'There are many side dishes'),
  createContentItem('국', 'guk', 'Soup', 'word', '국을 끓여요', 'I make soup'),
  createContentItem('찌개', 'jjigae', 'Stew', 'word', '찌개가 맛있어요', 'The stew is delicious'),
  createContentItem('탕', 'tang', 'Hot soup', 'word', '삼계탕을 먹어요', 'I eat samgyetang'),
  createContentItem('전골', 'jeongol', 'Hot pot', 'word', '전골을 끓여요', 'I make hotpot'),
  createContentItem('구이', 'gui', 'Grilled dish', 'word', '고기 구이예요', 'It\'s grilled meat'),
  createContentItem('조림', 'jorim', 'Braised dish', 'word', '생선 조림이에요', 'It\'s braised fish'),

  // Ingredients and seasonings
  createContentItem('재료', 'jaeryo', 'Ingredient', 'word', '신선한 재료예요', 'It\'s fresh ingredients'),
  createContentItem('식재료', 'sikjaeryo', 'Food ingredient', 'word', '식재료를 구해요', 'I get food ingredients'),
  createContentItem('조미료', 'jomiryo', 'Seasoning', 'word', '조미료를 넣어요', 'I add seasonings'),
  createContentItem('향신료', 'hyangsilyo', 'Spice', 'word', '향신료가 들어가요', 'Spices go in'),
  createContentItem('양념장', 'yangnyeomjang', 'Sauce/Marinade', 'word', '양념장을 만들어요', 'I make marinade'),
  createContentItem('육수', 'yuksu', 'Broth', 'word', '육수를 내요', 'I make broth'),
  createContentItem('다시다', 'dasida', 'Soup stock', 'word', '다시다를 넣어요', 'I add soup stock'),
  createContentItem('멸치', 'myeolchi', 'Anchovy', 'word', '멸치로 국물을 내요', 'I make broth with anchovies'),
  createContentItem('다시마', 'dasima', 'Kelp', 'word', '다시마를 넣어요', 'I add kelp'),
  createContentItem('마늘', 'maneul', 'Garlic', 'word', '마늘을 많이 써요', 'I use a lot of garlic'),

  // Cooking methods
  createContentItem('조리법', 'joribeop', 'Cooking method', 'word', '전통 조리법이에요', 'It\'s a traditional cooking method'),
  createContentItem('끓이다', 'kkeulhida', 'To boil', 'word', '물을 끓여요', 'I boil water'),
  createContentItem('굽다', 'gupda', 'To grill/bake', 'word', '고기를 구워요', 'I grill meat'),
  createContentItem('볶다', 'bokda', 'To stir-fry', 'word', '야채를 볶아요', 'I stir-fry vegetables'),
  createContentItem('튀기다', 'twigida', 'To deep-fry', 'word', '튀김을 튀겨요', 'I deep-fry tempura'),
  createContentItem('찌다', 'jjida', 'To steam', 'word', '만두를 쪄요', 'I steam dumplings'),
  createContentItem('삶다', 'samda', 'To boil', 'word', '계란을 삶아요', 'I boil eggs'),
  createContentItem('데치다', 'dechida', 'To parboil', 'word', '채소를 데쳐요', 'I parboil vegetables'),
  createContentItem('재우다', 'jaeuda', 'To marinate', 'word', '양념에 재워요', 'I marinate in seasoning'),
  createContentItem('무치다', 'muchida', 'To season/mix', 'word', '나물을 무쳐요', 'I season namul'),

  // Fermentation and preservation
  createContentItem('발효', 'balhyo', 'Fermentation', 'word', '발효 과정이에요', 'It\'s a fermentation process'),
  createContentItem('숙성', 'sukseong', 'Aging/Maturation', 'word', '숙성시켜요', 'I age it'),
  createContentItem('담그다', 'damgeuda', 'To make (kimchi, pickles)', 'word', '김치를 담가요', 'I make kimchi'),
  createContentItem('절이다', 'jeorida', 'To pickle/salt', 'word', '배추를 절여요', 'I salt cabbage'),
  createContentItem('말리다', 'mallida', 'To dry', 'word', '고추를 말려요', 'I dry peppers'),
  createContentItem('보관', 'bogwan', 'Storage', 'word', '냉장 보관해요', 'I store it in the refrigerator'),
  createContentItem('저장', 'jeojaang', 'Preservation', 'word', '저장 방법이에요', 'It\'s a preservation method'),
  createContentItem('장독대', 'jangdokdae', 'Jar stand for fermented foods', 'word', '장독대가 있어요', 'There\'s a jangdokdae'),
  createContentItem('항아리', 'hangari', 'Jar', 'word', '항아리에 담아요', 'I put it in a jar'),
  createContentItem('김장', 'gimjang', 'Kimchi making season', 'word', '김장을 해요', 'I make kimchi for winter'),

  // Nutritional aspects
  createContentItem('영양', 'yeongyang', 'Nutrition', 'word', '영양이 풍부해요', 'It\'s nutritious'),
  createContentItem('영양소', 'yeonggyangso', 'Nutrient', 'word', '영양소가 많아요', 'It has many nutrients'),
  createContentItem('단백질', 'danbaekjil', 'Protein', 'word', '단백질이 많아요', 'It has a lot of protein'),
  createContentItem('탄수화물', 'tansuhwamul', 'Carbohydrate', 'word', '탄수화물이에요', 'It\'s carbohydrates'),
  createContentItem('지방', 'jibang', 'Fat', 'word', '지방이 적어요', 'It has little fat'),
  createContentItem('비타민', 'bitamin', 'Vitamin', 'word', '비타민이 풍부해요', 'It\'s rich in vitamins'),
  createContentItem('무기질', 'mugijil', 'Mineral', 'word', '무기질이 많아요', 'It has many minerals'),
  createContentItem('섬유질', 'seomyujil', 'Fiber', 'word', '섬유질이 많아요', 'It has a lot of fiber'),
  createContentItem('칼로리', 'kallori', 'Calorie', 'word', '칼로리가 낮아요', 'It\'s low in calories'),
  createContentItem('유산균', 'yusangyun', 'Lactic acid bacteria', 'word', '유산균이 많아요', 'It has many probiotics'),

  // Health benefits
  createContentItem('건강식', 'geongangsik', 'Health food', 'word', '건강식을 먹어요', 'I eat health food'),
  createContentItem('약식동원', 'yaksikdongwon', 'Food as medicine', 'word', '약식동원 사상이에요', 'It\'s the philosophy of food as medicine'),
  createContentItem('보양식', 'boyangsik', 'Nutritious food', 'word', '보양식이에요', 'It\'s nutritious food'),
  createContentItem('보신탕', 'bosintang', 'Invigorating soup', 'word', '여름 보신탕이에요', 'It\'s summer invigorating soup'),
  createContentItem('효능', 'hyoneung', 'Efficacy', 'word', '건강 효능이 있어요', 'It has health benefits'),
  createContentItem('효과', 'hyogwa', 'Effect', 'word', '좋은 효과가 있어요', 'It has good effects'),
  createContentItem('해독', 'haedok', 'Detox', 'word', '해독 효과가 있어요', 'It has detox effects'),
  createContentItem('면역력', 'myeonyeoknyeok', 'Immunity', 'word', '면역력을 높여요', 'It boosts immunity'),
  createContentItem('소화', 'sohwa', 'Digestion', 'word', '소화를 도와요', 'It aids digestion'),
  createContentItem('항산화', 'hangsanhwa', 'Antioxidant', 'word', '항산화 효과예요', 'It\'s an antioxidant effect'),

  // Dining etiquette
  createContentItem('예절', 'yejeol', 'Etiquette', 'word', '식사 예절이에요', 'It\'s dining etiquette'),
  createContentItem('예의', 'yeui', 'Courtesy/Manners', 'word', '예의를 지켜요', 'I follow courtesy'),
  createContentItem('상석', 'sangseok', 'Seat of honor', 'word', '상석에 앉아요', 'I sit at the seat of honor'),
  createContentItem('수저', 'sujeo', 'Spoon and chopsticks', 'word', '수저를 놓아요', 'I put down my spoon and chopsticks'),
  createContentItem('젓가락', 'jeotgarak', 'Chopsticks', 'word', '젓가락을 써요', 'I use chopsticks'),
  createContentItem('숟가락', 'sutgarak', 'Spoon', 'word', '숟가락으로 먹어요', 'I eat with a spoon'),
  createContentItem('그릇', 'geureut', 'Bowl/Dish', 'word', '그릇을 들지 않아요', 'I don\'t lift the bowl'),
  createContentItem('공기', 'gonggi', 'Rice bowl', 'word', '공기에 담아요', 'I serve it in a rice bowl'),
  createContentItem('건배', 'geonbae', 'Cheers/Toast', 'word', '건배해요', 'I make a toast'),
  createContentItem('나눠 먹다', 'nanwo meokda', 'To share food', 'word', '나눠 먹어요', 'We share food', [{ korean: '나눠', english: 'share/divide' }, { korean: '먹다', english: 'to eat' }])
];

// TRAVEL - INTERMEDIATE: Public Transportation
const travelIntermediate = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['지하철', 'jihacheol', 'Subway', '지하철을 타요', 'I take the subway'],
    ['버스', 'beoseu', 'Bus', '버스를 기다려요', 'I wait for the bus'],
    ['기차', 'gicha', 'Train', '기차로 가요', 'I go by train'],
    ['택시', 'taeksi', 'Taxi', '택시를 잡아요', 'I catch a taxi'],
    ['비행기', 'bihaenggi', 'Airplane', '비행기를 타요', 'I take a plane'],
    ['배', 'bae', 'Ship/Boat', '배를 타요', 'I take a ship'],
    ['자전거', 'jajeongeo', 'Bicycle', '자전거를 타요', 'I ride a bicycle'],
    ['오토바이', 'otobai', 'Motorcycle', '오토바이를 타요', 'I ride a motorcycle'],
    ['자동차', 'jadongcha', 'Car', '자동차로 가요', 'I go by car'],
    ['대중교통', 'daejunggyotong', 'Public transportation', '대중교통을 이용해요', 'I use public transportation'],
    ['환승', 'hwanseung', 'Transfer', '환승해야 해요', 'I need to transfer'],
    ['승차', 'seungcha', 'Boarding', '승차권을 사요', 'I buy a ticket'],
    ['하차', 'hacha', 'Getting off', '다음 역에서 하차해요', 'I get off at the next station'],
    ['정거장', 'jeonggeojang', 'Stop', '정거장이 어디예요?', 'Where is the stop?'],
    ['터미널', 'teomineol', 'Terminal', '터미널에 가요', 'I go to the terminal'],
    ['역', 'yeok', 'Station', '역이 가까워요', 'The station is close'],
    ['승강장', 'seunggangjang', 'Platform', '승강장에서 기다려요', 'I wait on the platform'],
    ['개찰구', 'gaechalgu', 'Ticket gate', '개찰구를 통과해요', 'I pass through the ticket gate'],
    ['출구', 'chulgu', 'Exit', '2번 출구로 나가요', 'I exit through exit 2'],
    ['입구', 'ipgu', 'Entrance', '입구가 어디예요?', 'Where is the entrance?'],
    ['노선', 'noseon', 'Route/Line', '몇 호선이에요?', 'Which line is it?'],
    ['호선', 'hoseon', 'Line number', '2호선을 타요', 'I take Line 2'],
    ['막차', 'makcha', 'Last train', '막차를 놓쳤어요', 'I missed the last train'],
    ['첫차', 'cheotcha', 'First train', '첫차를 타요', 'I take the first train'],
    ['급행', 'geupaeng', 'Express', '급행이 빨라요', 'Express is fast'],
    ['완행', 'wanhaeng', 'Local/All-stop', '완행을 타요', 'I take the local train'],
    ['시간표', 'sigampyo', 'Timetable', '시간표를 봐요', 'I check the timetable'],
    ['배차', 'baecha', 'Dispatch/Service', '배차 간격이 짧아요', 'The service interval is short'],
    ['요금', 'yogeum', 'Fare', '요금이 얼마예요?', 'How much is the fare?'],
    ['교통카드', 'gyotongkadeu', 'Transportation card', '교통카드를 찍어요', 'I tap my transportation card'],
    ['충전', 'chungjeon', 'Recharge', '카드를 충전해요', 'I recharge the card'],
    ['할인', 'harin', 'Discount', '할인이 돼요', 'There\'s a discount'],
    ['정기권', 'jeongggigwon', 'Season ticket', '정기권을 사요', 'I buy a season ticket'],
    ['일회용', 'ilhoeyong', 'Disposable/One-time', '일회용 표를 사요', 'I buy a one-time ticket'],
    ['방향', 'banghyang', 'Direction', '어느 방향이에요?', 'Which direction?'],
    ['종착역', 'jongchagyeok', 'Terminal station', '종착역이에요', 'It\'s the terminal station'],
    ['지연', 'jiyeon', 'Delay', '지연돼요', 'It\'s delayed'],
    ['운행', 'unhaeng', 'Operation', '운행 시간이에요', 'It\'s operation time'],
    ['휴일', 'hyuil', 'Holiday', '휴일에는 안 다녀요', 'It doesn\'t run on holidays'],
    ['혼잡', 'honjap', 'Crowded', '혼잡해요', 'It\'s crowded'],
    ['한산하다', 'hansanhada', 'To be quiet/empty', '한산해요', 'It\'s empty'],
    ['좌석', 'jwaseok', 'Seat', '좌석이 있어요', 'There are seats'],
    ['입석', 'ipseok', 'Standing', '입석이에요', 'It\'s standing room'],
    ['예약석', 'yeyakseok', 'Reserved seat', '예약석이에요', 'It\'s a reserved seat'],
    ['노약자석', 'noyakjaseok', 'Priority seat', '노약자석이에요', 'It\'s a priority seat'],
    ['임산부', 'imsanbu', 'Pregnant woman', '임산부 배려 좌석', 'Pregnant woman priority seat'],
    ['장애인', 'jangaein', 'Disabled person', '장애인 전용석', 'Disabled person seat'],
    ['안내방송', 'annaebongsong', 'Announcement', '안내방송을 들어요', 'I listen to the announcement'],
    ['알림', 'allim', 'Notification/Alert', '알림이 와요', 'I get a notification'],
    ['지도', 'jido', 'Map', '노선도를 봐요', 'I look at the route map'],
    ['경로', 'gyeongno', 'Route/Path', '경로를 검색해요', 'I search for the route'],
    ['길', 'gil', 'Way/Road', '길을 물어봐요', 'I ask for directions'],
    ['이동', 'idong', 'Movement', '이동 시간이 오래 걸려요', 'Travel time takes long'],
    ['소요', 'soyo', 'Required time', '소요 시간이 30분이에요', 'Required time is 30 minutes'],
    ['거리', 'geori', 'Distance', '거리가 가까워요', 'The distance is close'],
    ['운전', 'unjeon', 'Driving', '운전해요', 'I drive'],
    ['주차', 'jucha', 'Parking', '주차장을 찾아요', 'I look for parking'],
    ['주유소', 'juyuso', 'Gas station', '주유소에 가요', 'I go to the gas station'],
    ['휴게소', 'hyugeso', 'Rest stop', '휴게소에서 쉬어요', 'I rest at the rest stop'],
    ['톨게이트', 'tolgeiteu', 'Toll gate', '톨게이트를 지나요', 'I pass through the toll gate'],
    ['고속도로', 'gosokdoro', 'Highway', '고속도로로 가요', 'I go on the highway'],
    ['국도', 'gukdo', 'National road', '국도로 가요', 'I take the national road'],
    ['시내', 'sinae', 'Downtown', '시내로 가요', 'I go downtown'],
    ['외곽', 'oegwak', 'Outskirts', '외곽 지역이에요', 'It\'s in the outskirts'],
    ['도착', 'dochak', 'Arrival', '곧 도착해요', 'I arrive soon'],
    ['출발', 'chulbal', 'Departure', '출발해요', 'I depart'],
    ['이륙', 'iryuk', 'Takeoff', '비행기가 이륙해요', 'The plane takes off'],
    ['착륙', 'chagnyuk', 'Landing', '착륙했어요', 'It landed'],
    ['공항', 'gonghang', 'Airport', '공항에 가요', 'I go to the airport'],
    ['항구', 'hanggu', 'Port', '항구에 가요', 'I go to the port'],
    ['선착장', 'seonchakjang', 'Pier/Wharf', '선착장에서 타요', 'I board at the pier'],
    ['여객선', 'yeogaekseon', 'Passenger ship', '여객선을 타요', 'I take a passenger ship'],
    ['유람선', 'yuramseon', 'Cruise ship', '유람선을 타요', 'I take a cruise'],
    ['나룻배', 'narutbae', 'Ferry', '나룻배로 건너요', 'I cross by ferry'],
    ['렌터카', 'renteoka', 'Rental car', '렌터카를 빌려요', 'I rent a car'],
    ['대여', 'daeyeo', 'Rental', '자전거 대여소', 'Bicycle rental shop'],
    ['공유', 'gongyyu', 'Sharing', '공유 자전거', 'Shared bicycle'],
    ['킥보드', 'kikbodeu', 'Kickboard/Scooter', '킥보드를 타요', 'I ride a kickboard'],
    ['도보', 'dobo', 'On foot', '도보로 가요', 'I go on foot'],
    ['걷다', 'geotda', 'To walk', '걸어가요', 'I walk'],
    ['뛰다', 'ttwida', 'To run', '뛰어가요', 'I run'],
    ['지름길', 'jireumgil', 'Shortcut', '지름길로 가요', 'I take a shortcut'],
    ['우회', 'uhoe', 'Detour', '우회해야 해요', 'I need to detour'],
    ['공사', 'gongsa', 'Construction', '공사 중이에요', 'It\'s under construction'],
    ['통제', 'tongje', 'Control/Restriction', '통제돼요', 'It\'s restricted'],
    ['금지', 'geumji', 'Prohibition', '주차 금지예요', 'Parking is prohibited'],
    ['허가', 'heoga', 'Permission', '허가가 필요해요', 'Permission is needed'],
    ['위반', 'wiban', 'Violation', '위반하면 벌금이에요', 'There\'s a fine if you violate'],
    ['벌금', 'beolgeum', 'Fine', '벌금을 내요', 'I pay a fine'],
    ['안전', 'anjeon', 'Safety', '안전하게 가요', 'I go safely'],
    ['사고', 'sago', 'Accident', '사고가 났어요', 'There was an accident'],
    ['고장', 'gojang', 'Breakdown', '차가 고장났어요', 'The car broke down'],
    ['수리', 'suri', 'Repair', '수리해야 해요', 'It needs repair'],
    ['정비', 'jeongbi', 'Maintenance', '정비소에 가요', 'I go to the maintenance shop'],
    ['보험', 'boheom', 'Insurance', '보험이 있어요', 'I have insurance'],
    ['면허', 'myeonheo', 'License', '운전면허가 있어요', 'I have a driver\'s license'],
    ['규칙', 'gyuchik', 'Rule', '교통 규칙을 지켜요', 'I follow traffic rules'],
    ['신호', 'sinho', 'Signal/Light', '신호를 지켜요', 'I obey the signal'],
    ['신호등', 'sinhodeung', 'Traffic light', '신호등이 빨개요', 'The traffic light is red'],
    ['횡단보도', 'hoengdanbodo', 'Crosswalk', '횡단보도로 건너요', 'I cross at the crosswalk']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

// TRAVEL - ADVANCED: Travel Planning
const travelAdvanced = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['여행', 'yeohaeng', 'Travel', '여행을 계획해요', 'I plan a trip'],
    ['여행지', 'yeohaengji', 'Travel destination', '여행지를 정해요', 'I decide on a destination'],
    ['관광', 'gwangwang', 'Tourism/Sightseeing', '관광을 해요', 'I go sightseeing'],
    ['관광지', 'gwangwangji', 'Tourist spot', '유명한 관광지예요', 'It\'s a famous tourist spot'],
    ['명소', 'myeongso', 'Famous place', '명소를 방문해요', 'I visit famous places'],
    ['유적지', 'yujeokji', 'Historic site', '유적지를 둘러봐요', 'I tour historic sites'],
    ['문화재', 'munhwajae', 'Cultural property', '문화재를 구경해요', 'I view cultural properties'],
    ['세계유산', 'segyeyusan', 'World Heritage', '세계유산이에요', 'It\'s a World Heritage site'],
    ['국립공원', 'gungnipgongwon', 'National park', '국립공원에 가요', 'I go to the national park'],
    ['자연', 'jayeon', 'Nature', '자연을 즐겨요', 'I enjoy nature'],
    ['풍경', 'punggyeong', 'Scenery', '풍경이 아름다워요', 'The scenery is beautiful'],
    ['경치', 'gyeongchi', 'View', '경치가 좋아요', 'The view is good'],
    ['전망', 'jeonmang', 'Panorama/Prospect', '전망대에 올라가요', 'I go up to the observatory'],
    ['일정', 'iljeong', 'Itinerary/Schedule', '여행 일정을 짜요', 'I plan the travel itinerary'],
    ['계획', 'gyehoek', 'Plan', '여행 계획을 세워요', 'I make travel plans'],
    ['준비', 'junbi', 'Preparation', '여행 준비를 해요', 'I prepare for the trip'],
    ['예약', 'yeyak', 'Reservation', '호텔을 예약해요', 'I book a hotel'],
    ['숙소', 'sukso', 'Accommodation', '숙소를 찾아요', 'I look for accommodation'],
    ['호텔', 'hotel', 'Hotel', '호텔에 묵어요', 'I stay at a hotel'],
    ['모텔', 'motel', 'Motel', '모텔에 묵어요', 'I stay at a motel'],
    ['민박', 'minbak', 'Homestay', '민박을 해요', 'I do homestay'],
    ['펜션', 'pensyeon', 'Pension/Guesthouse', '펜션을 예약해요', 'I book a guesthouse'],
    ['게스트하우스', 'geseuteuhauseu', 'Guesthouse', '게스트하우스에 묵어요', 'I stay at a guesthouse'],
    ['캠핑', 'kaemping', 'Camping', '캠핑을 가요', 'I go camping'],
    ['텐트', 'tenteu', 'Tent', '텐트를 쳐요', 'I pitch a tent'],
    ['짐', 'jim', 'Luggage', '짐을 싸요', 'I pack luggage'],
    ['가방', 'gabang', 'Bag', '가방을 챙겨요', 'I pack my bag'],
    ['캐리어', 'kaerieo', 'Suitcase/Carrier', '캐리어를 끌어요', 'I pull my suitcase'],
    ['배낭', 'baenang', 'Backpack', '배낭여행을 해요', 'I go backpacking'],
    ['짐 가방', 'jim gabang', 'Luggage', '짐을 부쳐요', 'I check my luggage'],
    ['수하물', 'suhamul', 'Baggage', '수하물을 찾아요', 'I collect my baggage'],
    ['휴대품', 'hyudaepum', 'Carry-on', '휴대품이에요', 'It\'s carry-on'],
    ['여권', 'yeogwon', 'Passport', '여권을 챙겨요', 'I pack my passport'],
    ['비자', 'bija', 'Visa', '비자가 필요해요', 'I need a visa'],
    ['출입국', 'churipguk', 'Immigration', '출입국 심사를 받아요', 'I go through immigration'],
    ['세관', 'segwan', 'Customs', '세관 신고를 해요', 'I make a customs declaration'],
    ['면세', 'myeonse', 'Duty-free', '면세점에서 사요', 'I shop at duty-free'],
    ['환전', 'hwanjeon', 'Currency exchange', '환전을 해요', 'I exchange currency'],
    ['환율', 'hwanyul', 'Exchange rate', '환율을 확인해요', 'I check the exchange rate'],
    ['현지', 'hyeonji', 'Local', '현지 통화예요', 'It\'s local currency'],
    ['가이드', 'gaideu', 'Guide', '가이드를 고용해요', 'I hire a guide'],
    ['투어', 'tueo', 'Tour', '시티 투어를 해요', 'I do a city tour'],
    ['패키지', 'paekiji', 'Package', '패키지 여행이에요', 'It\'s a package tour'],
    ['자유 여행', 'jayu yeohaeng', 'Independent travel', '자유 여행을 해요', 'I travel independently'],
    ['배낭 여행', 'baenang yeohaeng', 'Backpacking', '배낭 여행을 좋아해요', 'I like backpacking'],
    ['단체 여행', 'danche yeohaeng', 'Group travel', '단체 여행이에요', 'It\'s a group tour'],
    ['신혼여행', 'sinhonyeohaeng', 'Honeymoon', '신혼여행을 가요', 'I go on a honeymoon'],
    ['출장', 'chuljang', 'Business trip', '출장을 가요', 'I go on a business trip'],
    ['해외', 'haeoe', 'Overseas', '해외여행을 가요', 'I travel overseas'],
    ['국내', 'gungnae', 'Domestic', '국내 여행을 해요', 'I travel domestically'],
    ['도시', 'dosi', 'City', '도시를 여행해요', 'I travel to cities'],
    ['시골', 'sigol', 'Countryside', '시골에 가요', 'I go to the countryside'],
    ['섬', 'seom', 'Island', '섬을 방문해요', 'I visit an island'],
    ['산', 'san', 'Mountain', '산에 올라가요', 'I climb mountains'],
    ['바다', 'bada', 'Sea', '바다에 가요', 'I go to the sea'],
    ['해변', 'haebyeon', 'Beach', '해변에서 놀아요', 'I play at the beach'],
    ['강', 'gang', 'River', '강을 구경해요', 'I view the river'],
    ['호수', 'hosu', 'Lake', '호수 주변을 산책해요', 'I walk around the lake'],
    ['폭포', 'pokpo', 'Waterfall', '폭포를 봐요', 'I see the waterfall'],
    ['계곡', 'gyegok', 'Valley', '계곡으로 가요', 'I go to the valley'],
    ['등산', 'deungsan', 'Hiking', '등산을 해요', 'I hike'],
    ['트레킹', 'teurekking', 'Trekking', '트레킹을 즐겨요', 'I enjoy trekking'],
    ['하이킹', 'haiking', 'Hiking', '하이킹을 가요', 'I go hiking'],
    ['스키', 'seuki', 'Skiing', '스키를 타요', 'I ski'],
    ['스노보드', 'seunobo deu', 'Snowboarding', '스노보드를 타요', 'I snowboard'],
    ['서핑', 'seoping', 'Surfing', '서핑을 배워요', 'I learn surfing'],
    ['다이빙', 'daibing', 'Diving', '스쿠버 다이빙을 해요', 'I scuba dive'],
    ['액티비티', 'aektibiti', 'Activity', '액티비티를 즐겨요', 'I enjoy activities'],
    ['모험', 'moheom', 'Adventure', '모험을 해요', 'I have adventures'],
    ['체험', 'cheheom', 'Experience', '문화 체험을 해요', 'I experience culture'],
    ['기념품', 'ginyeompum', 'Souvenir', '기념품을 사요', 'I buy souvenirs'],
    ['선물', 'seonmul', 'Gift', '선물을 사요', 'I buy gifts'],
    ['특산물', 'teuksanmul', 'Local specialty', '특산물을 사요', 'I buy local specialties'],
    ['사진', 'sajin', 'Photo', '사진을 찍어요', 'I take photos'],
    ['촬영', 'chwalyeong', 'Filming/Shooting', '촬영을 해요', 'I film'],
    ['추억', 'chueok', 'Memory', '추억을 만들어요', 'I make memories'],
    ['일기', 'ilgi', 'Diary', '여행 일기를 써요', 'I write a travel diary'],
    ['블로그', 'beullogeu', 'Blog', '블로그에 올려요', 'I post on my blog'],
    ['지도', 'jido', 'Map', '지도를 봐요', 'I look at a map'],
    ['GPS', 'jipiseu', 'GPS', 'GPS를 켜요', 'I turn on GPS'],
    ['네비게이션', 'nebigeisyeon', 'Navigation', '네비게이션을 따라가요', 'I follow navigation'],
    ['길 찾기', 'gil chatgi', 'Wayfinding', '길을 찾아요', 'I find the way'],
    ['안내소', 'annaeso', 'Information center', '관광 안내소에 가요', 'I go to the tourist information center'],
    ['팜플렛', 'pampeulet', 'Pamphlet', '팜플렛을 받아요', 'I get a pamphlet'],
    ['정보', 'jeongbo', 'Information', '정보를 찾아요', 'I look for information'],
    ['추천', 'chucheon', 'Recommendation', '추천 받아요', 'I get recommendations'],
    ['리뷰', 'ribyu', 'Review', '리뷰를 봐요', 'I check reviews'],
    ['평점', 'pyeongjeom', 'Rating', '평점이 높아요', 'The rating is high'],
    ['입장료', 'ipjangnyo', 'Admission fee', '입장료를 내요', 'I pay the admission fee'],
    ['할인', 'harin', 'Discount', '학생 할인이 돼요', 'There\'s a student discount'],
    ['무료', 'muryo', 'Free', '무료 입장이에요', 'Admission is free'],
    ['시간', 'sigan', 'Time', '개장 시간을 확인해요', 'I check opening hours'],
    ['휴무', 'hyumu', 'Closed day', '휴무일이에요', 'It\'s a closed day'],
    ['성수기', 'seongsugi', 'Peak season', '성수기예요', 'It\'s peak season'],
    ['비수기', 'bisugi', 'Off-season', '비수기라 저렴해요', 'It\'s cheap in off-season'],
    ['날씨', 'nalssi', 'Weather', '날씨를 확인해요', 'I check the weather'],
    ['기후', 'gihu', 'Climate', '기후가 좋아요', 'The climate is good'],
    ['보험', 'boheom', 'Insurance', '여행자 보험을 들어요', 'I get travel insurance'],
    ['안전', 'anjeon', 'Safety', '안전이 중요해요', 'Safety is important'],
    ['주의', 'juui', 'Caution', '주의하세요', 'Be careful'],
    ['분실', 'bunsil', 'Loss', '여권을 분실했어요', 'I lost my passport']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

// SHOPPING - INTERMEDIATE: Price Negotiation
const shoppingIntermediate = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['가격', 'gagyeok', 'Price', '가격이 너무 비싸요', 'The price is too expensive'],
    ['값', 'gap', 'Price/Value', '값을 깎아 주세요', 'Please give me a discount'],
    ['할인', 'harin', 'Discount', '할인해 주세요', 'Please give me a discount'],
    ['깎다', 'kkakda', 'To reduce/discount', '깎아 주세요', 'Please reduce the price'],
    ['흥정', 'heungjeong', 'Bargaining', '흥정을 해요', 'I bargain'],
    ['협상', 'hyeopsang', 'Negotiation', '가격 협상을 해요', 'I negotiate the price'],
    ['싸다', 'ssada', 'To be cheap', '더 싸게 해 주세요', 'Please make it cheaper'],
    ['비싸다', 'bissada', 'To be expensive', '너무 비싸요', 'It\'s too expensive'],
    ['합리적', 'hallijeok', 'Reasonable', '합리적인 가격이에요', 'It\'s a reasonable price'],
    ['적절하다', 'jeokjeolhada', 'To be appropriate', '적절한 가격이에요', 'It\'s an appropriate price'],
    ['현금', 'hyeongeum', 'Cash', '현금으로 내면 할인돼요?', 'Is there a discount for cash?'],
    ['카드', 'kadeu', 'Card', '카드 안 돼요?', 'Can I not use card?'],
    ['계산', 'gyesan', 'Calculation/Payment', '계산해 주세요', 'Please calculate'],
    ['총액', 'chongaek', 'Total amount', '총액이 얼마예요?', 'What\'s the total?'],
    ['합계', 'hapgye', 'Sum total', '합계가 10만 원이에요', 'The total is 100,000 won'],
    ['원래', 'wollae', 'Original', '원래 가격이 얼마예요?', 'What\'s the original price?'],
    ['정가', 'jeongga', 'Regular price', '정가보다 싸요', 'It\'s cheaper than the regular price'],
    ['세일', 'seil', 'Sale', '세일 중이에요', 'It\'s on sale'],
    ['특가', 'teukga', 'Special price', '특가 상품이에요', 'It\'s a special price item'],
    ['행사', 'haengsa', 'Event/Promotion', '행사 가격이에요', 'It\'s a promotional price'],
    ['쿠폰', 'kupon', 'Coupon', '쿠폰이 있어요', 'I have a coupon'],
    ['포인트', 'pointeu', 'Points', '포인트를 써요', 'I use points'],
    ['적립', 'jeoglib', 'Accumulation', '포인트를 적립해요', 'I accumulate points'],
    ['마일리지', 'maill리지', 'Mileage', '마일리지가 있어요', 'I have mileage'],
    ['멤버십', 'membeo syip', 'Membership', '멤버십 할인이 돼요', 'There\'s a membership discount'],
    ['회원', 'hoewon', 'Member', '회원 가격이에요', 'It\'s member price'],
    ['비회원', 'bihoewon', 'Non-member', '비회원도 할인돼요?', 'Is there a discount for non-members too?'],
    ['등록', 'deungok', 'Registration', '회원 등록을 해요', 'I register as a member'],
    ['가입', 'gaib', 'Joining', '가입하면 할인돼요', 'You get a discount if you join'],
    ['무료', 'muryo', 'Free', '배송이 무료예요', 'Shipping is free'],
    ['배송', 'baesong', 'Delivery', '배송비가 얼마예요?', 'How much is shipping?'],
    ['택배', 'taekbae', 'Parcel service', '택배로 보내요', 'I send it by parcel'],
    ['배달', 'baedal', 'Delivery', '배달 가능해요?', 'Is delivery possible?'],
    ['송료', 'songnyo', 'Shipping fee', '송료가 비싸요', 'Shipping is expensive'],
    ['무료 배송', 'muryo baesong', 'Free shipping', '무료 배송이에요', 'It\'s free shipping'],
    ['묶음', 'mukeum', 'Bundle', '묶음 배송이 가능해요', 'Bundle shipping is possible'],
    ['반품', 'banpum', 'Return', '반품하고 싶어요', 'I want to return it'],
    ['교환', 'gyohwan', 'Exchange', '교환 가능해요?', 'Is exchange possible?'],
    ['환불', 'hwanbul', 'Refund', '환불해 주세요', 'Please refund me'],
    ['취소', 'chwiso', 'Cancellation', '주문을 취소해요', 'I cancel the order'],
    ['변경', 'byeongyeong', 'Change', '주문을 변경해요', 'I change the order'],
    ['영수증', 'yeongsujeung', 'Receipt', '영수증을 주세요', 'Please give me a receipt'],
    ['보증서', 'bojeungseo', 'Warranty', '보증서가 있어요', 'There\'s a warranty'],
    ['보증', 'bojeung', 'Warranty/Guarantee', '1년 보증이에요', 'It\'s a 1-year warranty'],
    ['품질', 'pumjil', 'Quality', '품질이 좋아요', 'The quality is good'],
    ['불량', 'bullyang', 'Defect', '불량품이에요', 'It\'s defective'],
    ['하자', 'haja', 'Defect', '하자가 있어요', 'There\'s a defect'],
    ['손상', 'sonsang', 'Damage', '손상됐어요', 'It\'s damaged'],
    ['파손', 'pason', 'Breakage', '파손된 물건이에요', 'It\'s a broken item'],
    ['찢어지다', 'jjijeojida', 'To be torn', '찢어졌어요', 'It\'s torn'],
    ['깨지다', 'kkaejida', 'To be broken', '깨졌어요', 'It\'s broken'],
    ['고장', 'gojang', 'Breakdown', '고장났어요', 'It\'s broken/not working'],
    ['작동', 'jakdong', 'Operation', '작동이 안 돼요', 'It doesn\'t work'],
    ['상태', 'sangtae', 'Condition', '상태가 나빠요', 'The condition is bad'],
    ['새 것', 'sae geot', 'New one', '새 것으로 주세요', 'Please give me a new one'],
    ['교체', 'gyoche', 'Replacement', '교체해 주세요', 'Please replace it'],
    ['수리', 'suri', 'Repair', '수리 가능해요?', 'Can it be repaired?'],
    ['수선', 'suseon', 'Repair/Alteration', '수선이 필요해요', 'It needs repair'],
    ['보상', 'bosang', 'Compensation', '보상을 원해요', 'I want compensation'],
    ['배상', 'baesang', 'Compensation', '배상해 주세요', 'Please compensate'],
    ['클레임', 'keulleim', 'Claim', '클레임을 제기해요', 'I file a claim'],
    ['불만', 'bulman', 'Complaint', '불만이 있어요', 'I have a complaint'],
    ['민원', 'minwon', 'Civil complaint', '민원을 넣어요', 'I file a complaint'],
    ['사과', 'sagwa', 'Apology', '사과를 원해요', 'I want an apology'],
    ['재발', 'jaebal', 'Recurrence', '재발 방지해 주세요', 'Please prevent recurrence'],
    ['개선', 'gaeseon', 'Improvement', '개선이 필요해요', 'Improvement is needed'],
    ['품목', 'pummok', 'Item', '품목이 다양해요', 'The items are diverse'],
    ['상품', 'sangpum', 'Product', '상품을 구경해요', 'I browse products'],
    ['제품', 'jepum', 'Product', '제품이 좋아요', 'The product is good'],
    ['물건', 'mulgeon', 'Thing/Item', '물건을 사요', 'I buy things'],
    ['물품', 'mulpum', 'Goods', '물품 목록이에요', 'It\'s a goods list'],
    ['재고', 'jaego', 'Inventory/Stock', '재고가 있어요?', 'Is it in stock?'],
    ['품절', 'pumjeol', 'Out of stock', '품절됐어요', 'It\'s out of stock'],
    ['입고', 'ipgo', 'Arrival of goods', '언제 입고돼요?', 'When will it arrive?'],
    ['예약', 'yeyak', 'Reservation', '예약 주문을 해요', 'I make a pre-order'],
    ['선주문', 'seonjumun', 'Pre-order', '선주문 가능해요?', 'Is pre-order possible?'],
    ['대기', 'daegi', 'Waiting', '대기자 명단에 올려요', 'I get on the waiting list'],
    ['순서', 'sunseo', 'Order/Sequence', '순서대로 판매해요', 'They sell in order'],
    ['조건', 'jogeon', 'Condition', '교환 조건이 뭐예요?', 'What\'s the exchange condition?'],
    ['기한', 'gihan', 'Deadline/Period', '반품 기한이 언제예요?', 'When is the return deadline?'],
    ['기간', 'gigan', 'Period', '세일 기간이에요', 'It\'s the sale period'],
    ['유효', 'yuhyo', 'Valid', '쿠폰이 유효해요', 'The coupon is valid'],
    ['만료', 'mallyo', 'Expiration', '쿠폰이 만료됐어요', 'The coupon expired'],
    ['기한', 'gihan', 'Expiration date', '유효 기한이 언제예요?', 'When is the expiration date?'],
    ['경쟁사', 'gyeongjaengsa', 'Competitor', '경쟁사보다 싸요', 'It\'s cheaper than competitors'],
    ['비교', 'bigyo', 'Comparison', '가격을 비교해요', 'I compare prices'],
    ['검색', 'geomsaek', 'Search', '최저가를 검색해요', 'I search for the lowest price'],
    ['시세', 'sise', 'Market price', '시세를 알아봐요', 'I check the market price'],
    ['평균', 'pyeonggyun', 'Average', '평균 가격이에요', 'It\'s the average price'],
    ['최저가', 'choejeoga', 'Lowest price', '최저가를 찾아요', 'I look for the lowest price'],
    ['최고가', 'choegoga', 'Highest price', '최고가예요', 'It\'s the highest price'],
    ['가성비', 'gaseongbi', 'Value for money', '가성비가 좋아요', 'It has good value for money'],
    ['실속', 'silsok', 'Substance/Value', '실속 있어요', 'It has good value'],
    ['알뜰', 'altteul', 'Thrifty', '알뜰하게 사요', 'I shop thriftily'],
    ['아끼다', 'akkida', 'To save', '돈을 아껴요', 'I save money'],
    ['절약', 'jeoryak', 'Saving', '절약해요', 'I economize'],
    ['과소비', 'gwasobi', 'Overconsumption', '과소비하지 마세요', 'Don\'t overconsume'],
    ['충동구매', 'chungdonggumae', 'Impulse buying', '충동구매를 해요', 'I make impulse purchases']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

// SHOPPING - ADVANCED: Consumer Rights
const shoppingAdvanced = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['소비자', 'sobija', 'Consumer', '소비자 권리가 있어요', 'I have consumer rights'],
    ['소비', 'sobi', 'Consumption', '합리적 소비를 해요', 'I consume rationally'],
    ['권리', 'gwonni', 'Right', '소비자 권리를 보호해요', 'I protect consumer rights'],
    ['의무', 'uimu', 'Obligation', '판매자의 의무예요', 'It\'s the seller\'s obligation'],
    ['법', 'beop', 'Law', '소비자 보호법이에요', 'It\'s consumer protection law'],
    ['규정', 'gyujeong', 'Regulation', '규정을 따라요', 'I follow regulations'],
    ['약관', 'yakgwan', 'Terms and conditions', '약관을 읽어요', 'I read the terms'],
    ['계약', 'gyeyak', 'Contract', '계약을 체결해요', 'I sign a contract'],
    ['합의', 'hapui', 'Agreement', '합의를 봐요', 'I reach an agreement'],
    ['동의', 'dongui', 'Consent', '동의해요', 'I consent'],
    ['거부', 'geobu', 'Refusal', '거부할 권리가 있어요', 'I have the right to refuse'],
    ['철회', 'cheolhoe', 'Withdrawal', '청약을 철회해요', 'I withdraw the subscription'],
    ['해지', 'haeji', 'Cancellation', '계약을 해지해요', 'I cancel the contract'],
    ['위반', 'wiban', 'Violation', '약관 위반이에요', 'It\'s a violation of terms'],
    ['벌칙', 'beolchik', 'Penalty', '벌칙이 있어요', 'There\'s a penalty'],
    ['과태료', 'gwataeryo', 'Fine', '과태료를 내요', 'I pay a fine'],
    ['손해', 'sonhae', 'Damage/Loss', '손해를 입었어요', 'I suffered a loss'],
    ['피해', 'pihae', 'Damage/Harm', '피해를 봤어요', 'I was harmed'],
    ['배상', 'baesang', 'Compensation', '손해 배상을 요구해요', 'I demand compensation'],
    ['보상', 'bosang', 'Compensation', '보상을 받아요', 'I receive compensation'],
    ['구제', 'guje', 'Relief/Remedy', '소비자 구제를 받아요', 'I get consumer relief'],
    ['청구', 'cheonggu', 'Claim/Demand', '배상을 청구해요', 'I claim compensation'],
    ['소송', 'sosong', 'Lawsuit', '소송을 제기해요', 'I file a lawsuit'],
    ['고소', 'goso', 'Accusation', '고소를 해요', 'I file a criminal complaint'],
    ['고발', 'gobal', 'Report/Denunciation', '고발해요', 'I report'],
    ['신고', 'singo', 'Report', '신고를 해요', 'I report'],
    ['중재', 'jungjae', 'Mediation', '중재를 신청해요', 'I apply for mediation'],
    ['조정', 'jojeong', 'Mediation', '분쟁 조정을 해요', 'I mediate the dispute'],
    ['협의', 'hyeopui', 'Consultation', '협의를 해요', 'I consult'],
    ['원', 'won', 'Center', '소비자 센터에 가요', 'I go to the consumer center'],
    ['기관', 'gigwan', 'Institution', '소비자 보호 기관이에요', 'It\'s a consumer protection agency'],
    ['단체', 'danche', 'Organization', '소비자 단체예요', 'It\'s a consumer organization'],
    ['협회', 'hyeophoe', 'Association', '소비자 협회예요', 'It\'s a consumer association'],
    ['피해 사례', 'pihae sarye', 'Damage case', '피해 사례가 많아요', 'There are many damage cases'],
    ['사기', 'sagi', 'Fraud', '사기를 당했어요', 'I was defrauded'],
    ['속이다', 'sogida', 'To deceive', '소비자를 속여요', 'They deceive consumers'],
    ['허위', 'heowi', 'False', '허위 광고예요', 'It\'s false advertising'],
    ['과장', 'gwajang', 'Exaggeration', '과장 광고예요', 'It\'s exaggerated advertising'],
    ['광고', 'gwanggo', 'Advertisement', '광고와 달라요', 'It\'s different from the ad'],
    ['홍보', 'hongbo', 'Promotion', '과대 홍보예요', 'It\'s excessive promotion'],
    ['표시', 'pyosi', 'Indication', '원산지 표시가 없어요', 'There\'s no country of origin indicated'],
    ['표기', 'pyogi', 'Notation', '가격 표기가 틀려요', 'The price notation is wrong'],
    ['라벨', 'rabel', 'Label', '라벨을 확인해요', 'I check the label'],
    ['성분', 'seongbun', 'Ingredient', '성분 표시를 봐요', 'I look at the ingredient list'],
    ['원재료', 'wonjaeryo', 'Raw material', '원재료가 뭐예요?', 'What are the raw materials?'],
    ['원산지', 'wonsanji', 'Country of origin', '원산지가 어디예요?', 'Where is the country of origin?'],
    ['제조', 'jego', 'Manufacturing', '제조일자를 확인해요', 'I check the manufacturing date'],
    ['유통', 'yutong', 'Distribution', '유통 기한이 언제예요?', 'When is the expiration date?'],
    ['만료일', 'mallyoil', 'Expiration date', '만료일을 봐요', 'I check the expiration date'],
    ['위생', 'wisaeng', 'Hygiene', '위생 상태가 나빠요', 'The hygiene is bad'],
    ['안전', 'anjeon', 'Safety', '안전하지 않아요', 'It\'s not safe'],
    ['위험', 'wiheom', 'Danger', '위험해요', 'It\'s dangerous'],
    ['유해', 'yuhae', 'Harmful', '유해 물질이 있어요', 'There are harmful substances'],
    ['독성', 'dokseong', 'Toxicity', '독성이 있어요', 'It\'s toxic'],
    ['오염', 'oyeom', 'Contamination', '오염됐어요', 'It\'s contaminated'],
    ['리콜', 'rikol', 'Recall', '제품 리콜이에요', 'It\'s a product recall'],
    ['회수', 'hoesu', 'Recall/Collection', '제품을 회수해요', 'They recall the product'],
    ['조사', 'josa', 'Investigation', '조사를 해요', 'They investigate'],
    ['검사', 'geomsa', 'Inspection', '품질 검사를 해요', 'They do quality inspection'],
    ['인증', 'injeung', 'Certification', '인증을 받았어요', 'It\'s certified'],
    ['허가', 'heoga', 'Permission/License', '판매 허가가 없어요', 'There\'s no sales license'],
    ['승인', 'seungin', 'Approval', '승인을 받아요', 'I get approval'],
    ['등록', 'deungok', 'Registration', '제품 등록을 해요', 'I register the product'],
    ['정보', 'jeongbo', 'Information', '제품 정보를 제공해요', 'They provide product information'],
    ['공개', 'gonggae', 'Disclosure', '정보를 공개해요', 'They disclose information'],
    ['투명', 'tumyeong', 'Transparent', '투명하게 운영해요', 'They operate transparently'],
    ['불투명', 'bultumyeong', 'Opaque', '불투명해요', 'It\'s opaque'],
    ['은폐', 'eunpye', 'Concealment', '정보를 은폐해요', 'They conceal information'],
    ['숨기다', 'sumgida', 'To hide', '결함을 숨겨요', 'They hide defects'],
    ['폭로', 'pokno', 'Exposure/Revelation', '폭로해요', 'I expose it'],
    ['공정', 'gongjeong', 'Fair', '공정한 거래예요', 'It\'s fair trade'],
    ['불공정', 'bulgongjeong', 'Unfair', '불공정 거래예요', 'It\'s unfair trade'],
    ['차별', 'chabyeol', 'Discrimination', '가격 차별이에요', 'It\'s price discrimination'],
    ['평등', 'pyeongdeung', 'Equality', '평등하게 대우해요', 'They treat equally'],
    ['우대', 'udae', 'Preferential treatment', '회원을 우대해요', 'They give preferential treatment to members'],
    ['혜택', 'hyetaek', 'Benefit', '혜택을 받아요', 'I receive benefits'],
    ['특권', 'teukgwon', 'Privilege', '특권이 있어요', 'There\'s a privilege'],
    ['특혜', 'teukhye', 'Special favor', '특혜를 받아요', 'I receive special favors'],
    ['독점', 'dokjeom', 'Monopoly', '시장을 독점해요', 'They monopolize the market'],
    ['경쟁', 'gyeongjaeng', 'Competition', '경쟁이 심해요', 'Competition is fierce'],
    ['담합', 'damhap', 'Collusion', '가격 담합이에요', 'It\'s price collusion'],
    ['카르텔', 'kareutel', 'Cartel', '카르텔을 형성해요', 'They form a cartel'],
    ['부당', 'budang', 'Unfair', '부당한 처사예요', 'It\'s unfair treatment'],
    ['부정', 'bujeong', 'Illegal/Dishonest', '부정한 거래예요', 'It\'s dishonest dealing'],
    ['불법', 'bulbeop', 'Illegal', '불법이에요', 'It\'s illegal'],
    ['합법', 'hapbeop', 'Legal', '합법적이에요', 'It\'s legal'],
    ['적법', 'jeokbeop', 'Lawful', '적법한 절차예요', 'It\'s a lawful procedure'],
    ['정당', 'jeongdang', 'Just/Legitimate', '정당한 요구예요', 'It\'s a legitimate demand'],
    ['타당', 'tadang', 'Reasonable/Valid', '타당해요', 'It\'s reasonable'],
    ['근거', 'geungeo', 'Basis/Ground', '법적 근거가 있어요', 'There\'s legal basis'],
    ['증거', 'jeunggeo', 'Evidence', '증거를 제시해요', 'I present evidence'],
    ['증명', 'jeungmyeong', 'Proof', '증명할 수 있어요', 'I can prove it'],
    ['입증', 'ibjeung', 'Demonstration', '입증해야 해요', 'I need to demonstrate it'],
    ['확인', 'hwaginj', 'Verification', '확인이 필요해요', 'Verification is needed']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

// BUSINESS - INTERMEDIATE: Office Communication
const businessIntermediate = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['회의', 'hoeui', 'Meeting', '회의가 있어요', 'There\'s a meeting'],
    ['회의실', 'hoeuisil', 'Meeting room', '회의실을 예약했어요', 'I reserved the meeting room'],
    ['토론', 'toron', 'Discussion', '토론을 해요', 'I have a discussion'],
    ['논의', 'nonui', 'Discussion', '안건을 논의해요', 'I discuss the agenda'],
    ['의견', 'uigyeon', 'Opinion', '의견을 제시해요', 'I present my opinion'],
    ['제안', 'jean', 'Proposal', '제안을 해요', 'I make a proposal'],
    ['제안서', 'jeanseo', 'Proposal document', '제안서를 제출해요', 'I submit a proposal'],
    ['보고', 'bogo', 'Report', '상사에게 보고해요', 'I report to my boss'],
    ['보고서', 'bogoseo', 'Report document', '보고서를 작성해요', 'I write a report'],
    ['발표', 'balpyo', 'Presentation', '발표를 준비해요', 'I prepare a presentation'],
    ['프레젠테이션', 'peurejenteisyeon', 'Presentation', '프레젠테이션을 해요', 'I give a presentation'],
    ['자료', 'jaryo', 'Material/Data', '자료를 정리해요', 'I organize materials'],
    ['데이터', 'deiteo', 'Data', '데이터를 분석해요', 'I analyze data'],
    ['통계', 'tonggye', 'Statistics', '통계를 봐요', 'I look at statistics'],
    ['수치', 'suchi', 'Figure/Number', '수치를 확인해요', 'I check the figures'],
    ['문서', 'munseo', 'Document', '문서를 작성해요', 'I create documents'],
    ['서류', 'seoryu', 'Documents', '서류를 정리해요', 'I organize documents'],
    ['양식', 'yangsik', 'Form', '양식을 작성해요', 'I fill out a form'],
    ['템플릿', 'templip', 'Template', '템플릿을 사용해요', 'I use a template'],
    ['초안', 'choan', 'Draft', '초안을 작성해요', 'I write a draft'],
    ['수정', 'sujeong', 'Revision', '수정이 필요해요', 'It needs revision'],
    ['검토', 'geomto', 'Review', '검토해 주세요', 'Please review'],
    ['승인', 'seungin', 'Approval', '승인을 받았어요', 'I got approval'],
    ['허가', 'heoga', 'Permission', '허가를 받아야 해요', 'I need to get permission'],
    ['결재', 'gyeolje', 'Approval/Payment', '결재를 올려요', 'I submit for approval'],
    ['결정', 'gyeoljeong', 'Decision', '결정을 내려요', 'I make a decision'],
    ['판단', 'pandan', 'Judgment', '판단해야 해요', 'I need to judge'],
    ['선택', 'seontaek', 'Choice', '선택을 해요', 'I make a choice'],
    ['협상', 'hyeopsang', 'Negotiation', '협상을 진행해요', 'I conduct negotiations'],
    ['합의', 'hapui', 'Agreement', '합의를 봤어요', 'I reached an agreement'],
    ['계약', 'gyeyak', 'Contract', '계약을 체결해요', 'I sign a contract'],
    ['거래', 'georae', 'Transaction/Deal', '거래를 성사시켜요', 'I complete a deal'],
    ['고객', 'gogaek', 'Customer/Client', '고객과 미팅해요', 'I meet with clients'],
    ['클라이언트', 'keullaieonteu', 'Client', '클라이언트를 관리해요', 'I manage clients'],
    ['거래처', 'georaecheo', 'Business partner', '거래처와 연락해요', 'I contact business partners'],
    ['파트너', 'pateuneo', 'Partner', '파트너사예요', 'It\'s a partner company'],
    ['공급업체', 'gonggeubeobche', 'Supplier', '공급업체와 계약해요', 'I contract with suppliers'],
    ['납품', 'nappum', 'Delivery of goods', '납품을 해요', 'I deliver goods'],
    ['발주', 'balju', 'Order', '발주를 넣어요', 'I place an order'],
    ['주문', 'jumun', 'Order', '주문을 받아요', 'I receive an order'],
    ['재고', 'jaego', 'Inventory', '재고를 확인해요', 'I check inventory'],
    ['물류', 'mulnyu', 'Logistics', '물류를 관리해요', 'I manage logistics'],
    ['배송', 'baesong', 'Delivery', '배송을 준비해요', 'I prepare delivery'],
    ['일정', 'iljeong', 'Schedule', '일정을 조정해요', 'I adjust the schedule'],
    ['스케줄', 'seukejul', 'Schedule', '스케줄을 관리해요', 'I manage the schedule'],
    ['마감', 'magam', 'Deadline', '마감이 다가와요', 'The deadline is approaching'],
    ['기한', 'gihan', 'Deadline/Term', '기한을 연장해요', 'I extend the deadline'],
    ['연기', 'yeongi', 'Postponement', '미팅을 연기해요', 'I postpone the meeting'],
    ['취소', 'chwiso', 'Cancellation', '회의를 취소해요', 'I cancel the meeting'],
    ['변경', 'byeongyeong', 'Change', '일정을 변경해요', 'I change the schedule'],
    ['조율', 'joyul', 'Coordination', '일정을 조율해요', 'I coordinate schedules'],
    ['조정', 'jojeong', 'Adjustment', '시간을 조정해요', 'I adjust the time'],
    ['협조', 'hyeopjo', 'Cooperation', '협조를 구해요', 'I seek cooperation'],
    ['협력', 'hyeopnyeok', 'Collaboration', '부서 간 협력을 해요', 'I collaborate between departments'],
    ['소통', 'sotong', 'Communication', '팀원들과 소통해요', 'I communicate with team members'],
    ['커뮤니케이션', 'keomyunikeisyeon', 'Communication', '원활한 커뮤니케이션이 중요해요', 'Smooth communication is important'],
    ['전달', 'jeondal', 'Delivery/Transmission', '메시지를 전달해요', 'I deliver the message'],
    ['공유', 'gongyyu', 'Sharing', '정보를 공유해요', 'I share information'],
    ['이메일', 'imeil', 'Email', '이메일을 보내요', 'I send an email'],
    ['메일', 'meil', 'Email', '메일을 확인해요', 'I check my email'],
    ['메시지', 'mesiji', 'Message', '메시지를 남겨요', 'I leave a message'],
    ['전화', 'jeonhwa', 'Phone call', '전화를 걸어요', 'I make a phone call'],
    ['통화', 'tonghwa', 'Phone call', '통화 중이에요', 'I\'m on a call'],
    ['화상 회의', 'hwasang hoeui', 'Video conference', '화상 회의를 해요', 'I have a video conference'],
    ['온라인 미팅', 'onlain miting', 'Online meeting', '온라인으로 미팅해요', 'I meet online'],
    ['대면', 'daemyeon', 'Face-to-face', '대면 미팅을 해요', 'I have a face-to-face meeting'],
    ['출장', 'chuljang', 'Business trip', '출장을 가요', 'I go on a business trip'],
    ['방문', 'bangmun', 'Visit', '고객을 방문해요', 'I visit clients'],
    ['접대', 'jeopdae', 'Entertainment', '고객을 접대해요', 'I entertain clients'],
    ['회식', 'hoesik', 'Company dinner', '회식이 있어요', 'There\'s a company dinner'],
    ['팀워크', 'timweokeu', 'Teamwork', '팀워크가 중요해요', 'Teamwork is important'],
    ['팀원', 'timwon', 'Team member', '팀원들과 협력해요', 'I cooperate with team members'],
    ['동료', 'dongryo', 'Colleague', '동료와 일해요', 'I work with colleagues'],
    ['상사', 'sangsa', 'Boss/Superior', '상사께 보고해요', 'I report to my boss'],
    ['부하', 'buha', 'Subordinate', '부하 직원을 관리해요', 'I manage subordinates'],
    ['후배', 'hubae', 'Junior', '후배를 지도해요', 'I guide juniors'],
    ['선배', 'seonbae', 'Senior', '선배에게 배워요', 'I learn from seniors'],
    ['신입', 'sinip', 'New employee', '신입 사원을 교육해요', 'I train new employees'],
    ['경력', 'gyeongnyeok', 'Career', '경력이 풍부해요', 'I have rich experience'],
    ['경험', 'gyeongheom', 'Experience', '경험을 쌓아요', 'I gain experience'],
    ['실무', 'silmu', 'Practical work', '실무를 배워요', 'I learn practical work'],
    ['업무', 'eommu', 'Task/Work', '업무를 분담해요', 'I share the workload'],
    ['역할', 'yeokhal', 'Role', '역할을 분담해요', 'I divide roles'],
    ['담당', 'damdang', 'In charge', '프로젝트를 담당해요', 'I\'m in charge of the project'],
    ['책임', 'chaegim', 'Responsibility', '책임을 져요', 'I take responsibility'],
    ['의무', 'uimu', 'Duty', '의무를 다해요', 'I fulfill my duties'],
    ['권한', 'gwonhan', 'Authority', '권한이 있어요', 'I have authority'],
    ['지시', 'jisi', 'Instruction', '지시를 따라요', 'I follow instructions'],
    ['명령', 'myeongnyeong', 'Order/Command', '명령을 받아요', 'I receive orders'],
    ['요청', 'yocheong', 'Request', '요청을 해요', 'I make a request'],
    ['부탁', 'butak', 'Request/Favor', '부탁을 드려요', 'I ask a favor'],
    ['피드백', 'pideubek', 'Feedback', '피드백을 받아요', 'I receive feedback'],
    ['평가', 'pyeongga', 'Evaluation', '업무 평가를 받아요', 'I get a work evaluation'],
    ['성과', 'seonggwa', 'Performance', '성과가 좋아요', 'The performance is good'],
    ['실적', 'siljeok', 'Track record', '실적을 올려요', 'I improve performance'],
    ['목표', 'mokpyo', 'Goal', '목표를 달성해요', 'I achieve goals'],
    ['달성', 'dalseong', 'Achievement', '목표 달성을 해요', 'I achieve the goal']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

// BUSINESS - ADVANCED: Corporate Management
const businessAdvanced = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['경영', 'gyeongyeong', 'Management', '회사를 경영해요', 'I manage the company'],
    ['운영', 'unyeong', 'Operation', '효율적으로 운영해요', 'I operate efficiently'],
    ['관리', 'gwalli', 'Management', '자원을 관리해요', 'I manage resources'],
    ['전략', 'jeonnyak', 'Strategy', '경영 전략을 세워요', 'I establish management strategy'],
    ['계획', 'gyehoek', 'Plan', '사업 계획을 수립해요', 'I establish a business plan'],
    ['방침', 'bangjim', 'Policy', '회사 방침이에요', 'It\'s company policy'],
    ['정책', 'jeongchaek', 'Policy', '인사 정책을 만들어요', 'I create HR policy'],
    ['방향', 'banghyang', 'Direction', '경영 방향을 설정해요', 'I set management direction'],
    ['목표', 'mokpyo', 'Goal/Objective', '장기 목표를 세워요', 'I set long-term goals'],
    ['비전', 'bijeon', 'Vision', '회사의 비전이에요', 'It\'s the company vision'],
    ['미션', 'misyeon', 'Mission', '미션을 달성해요', 'I accomplish the mission'],
    ['가치', 'gachi', 'Value', '핵심 가치를 추구해요', 'I pursue core values'],
    ['조직', 'jojik', 'Organization', '조직을 구성해요', 'I organize the structure'],
    ['구조', 'gujo', 'Structure', '조직 구조를 바꿔요', 'I change the organizational structure'],
    ['체계', 'chegye', 'System', '관리 체계를 구축해요', 'I establish a management system'],
    ['시스템', 'siseutem', 'System', '시스템을 도입해요', 'I introduce a system'],
    ['프로세스', 'peuroseseu', 'Process', '업무 프로세스를 개선해요', 'I improve work processes'],
    ['절차', 'jeolcha', 'Procedure', '절차를 따라요', 'I follow procedures'],
    ['규정', 'gyujeong', 'Regulation', '사내 규정이에요', 'It\'s internal regulations'],
    ['규칙', 'gyuchik', 'Rule', '규칙을 만들어요', 'I make rules'],
    ['원칙', 'wonchik', 'Principle', '경영 원칙을 지켜요', 'I follow management principles'],
    ['기준', 'gijun', 'Standard', '평가 기준이에요', 'It\'s evaluation criteria'],
    ['지표', 'jipyo', 'Indicator', '성과 지표를 봐요', 'I look at performance indicators'],
    ['척도', 'cheokdo', 'Measure/Scale', '측정 척도예요', 'It\'s a measurement scale'],
    ['분석', 'bunseok', 'Analysis', '시장을 분석해요', 'I analyze the market'],
    ['조사', 'josa', 'Research/Survey', '시장 조사를 해요', 'I do market research'],
    ['연구', 'yeongu', 'Research', '연구 개발을 해요', 'I do R&D'],
    ['개발', 'gaebal', 'Development', '신제품을 개발해요', 'I develop new products'],
    ['혁신', 'hyeoksin', 'Innovation', '혁신을 추진해요', 'I drive innovation'],
    ['개선', 'gaeseon', 'Improvement', '지속적으로 개선해요', 'I continuously improve'],
    ['최적화', 'choejeokhwa', 'Optimization', '프로세스를 최적화해요', 'I optimize processes'],
    ['효율', 'hyoyul', 'Efficiency', '효율을 높여요', 'I increase efficiency'],
    ['생산성', 'saengsanseong', 'Productivity', '생산성을 향상시켜요', 'I improve productivity'],
    ['품질', 'pumjil', 'Quality', '품질 관리를 해요', 'I manage quality'],
    ['성능', 'seongneung', 'Performance', '성능을 개선해요', 'I improve performance'],
    ['경쟁력', 'gyeongjaengnyeok', 'Competitiveness', '경쟁력을 강화해요', 'I strengthen competitiveness'],
    ['우위', 'uwi', 'Advantage', '경쟁 우위를 확보해요', 'I secure competitive advantage'],
    ['강점', 'gangjeom', 'Strength', '강점을 살려요', 'I leverage strengths'],
    ['약점', 'yakjeom', 'Weakness', '약점을 보완해요', 'I complement weaknesses'],
    ['기회', 'gihoe', 'Opportunity', '기회를 포착해요', 'I capture opportunities'],
    ['위기', 'wigi', 'Crisis', '위기를 극복해요', 'I overcome crises'],
    ['위험', 'wiheom', 'Risk', '위험을 관리해요', 'I manage risks'],
    ['리스크', 'riseukeu', 'Risk', '리스크를 평가해요', 'I assess risks'],
    ['대응', 'daeeung', 'Response', '위기에 대응해요', 'I respond to crises'],
    ['대비', 'daebi', 'Preparation', '위험에 대비해요', 'I prepare for risks'],
    ['예방', 'yebang', 'Prevention', '문제를 예방해요', 'I prevent problems'],
    ['인력', 'innyeok', 'Human resources', '인력을 관리해요', 'I manage human resources'],
    ['인재', 'injae', 'Talent', '인재를 채용해요', 'I recruit talent'],
    ['채용', 'chaeyong', 'Recruitment', '채용 공고를 내요', 'I post job openings'],
    ['모집', 'mojip', 'Recruitment', '직원을 모집해요', 'I recruit employees'],
    ['선발', 'seonbal', 'Selection', '우수 인재를 선발해요', 'I select excellent talent'],
    ['배치', 'baechi', 'Placement', '적재적소에 배치해요', 'I place people in right positions'],
    ['교육', 'gyoyuk', 'Education/Training', '직원을 교육해요', 'I train employees'],
    ['훈련', 'hullyeon', 'Training', '업무 훈련을 해요', 'I provide work training'],
    ['육성', 'yukseong', 'Cultivation', '인재를 육성해요', 'I cultivate talent'],
    ['개발', 'gaebal', 'Development', '역량을 개발해요', 'I develop capabilities'],
    ['승진', 'seungjin', 'Promotion', '승진 기회를 줘요', 'I give promotion opportunities'],
    ['보상', 'bosang', 'Compensation', '성과에 따라 보상해요', 'I compensate based on performance'],
    ['인센티브', 'insentibeu', 'Incentive', '인센티브를 제공해요', 'I provide incentives'],
    ['복지', 'bokji', 'Welfare', '직원 복지를 개선해요', 'I improve employee welfare'],
    ['동기부여', 'dongibuyeo', 'Motivation', '동기를 부여해요', 'I provide motivation'],
    ['사기', 'sagi', 'Morale', '사기를 높여요', 'I boost morale'],
    ['만족도', 'manjokdo', 'Satisfaction', '직원 만족도를 높여요', 'I increase employee satisfaction'],
    ['충성도', 'chungseongdo', 'Loyalty', '고객 충성도를 높여요', 'I increase customer loyalty'],
    ['이직률', 'ijikyul', 'Turnover rate', '이직률을 낮춰요', 'I lower turnover rate'],
    ['유지', 'yuji', 'Retention', '우수 인재를 유지해요', 'I retain excellent talent'],
    ['재무', 'jaemu', 'Finance', '재무를 관리해요', 'I manage finances'],
    ['회계', 'hoegye', 'Accounting', '회계 처리를 해요', 'I do accounting'],
    ['자금', 'jageum', 'Funds', '자금을 조달해요', 'I raise funds'],
    ['투자', 'tuja', 'Investment', '투자를 유치해요', 'I attract investment'],
    ['자본', 'jabon', 'Capital', '자본을 확충해요', 'I expand capital'],
    ['수익', 'suik', 'Revenue/Profit', '수익을 창출해요', 'I generate revenue'],
    ['매출', 'maechul', 'Sales', '매출을 늘려요', 'I increase sales'],
    ['이익', 'iik', 'Profit', '이익을 극대화해요', 'I maximize profit'],
    ['순이익', 'suniik', 'Net profit', '순이익이 증가했어요', 'Net profit increased'],
    ['비용', 'biyong', 'Cost', '비용을 절감해요', 'I reduce costs'],
    ['예산', 'yesan', 'Budget', '예산을 편성해요', 'I allocate the budget'],
    ['지출', 'jichul', 'Expenditure', '지출을 관리해요', 'I manage expenditures'],
    ['손익', 'sonik', 'Profit and loss', '손익을 계산해요', 'I calculate profit and loss'],
    ['수지', 'suji', 'Balance', '수지를 맞춰요', 'I balance income and expenditure'],
    ['흑자', 'heukja', 'Surplus/Black', '흑자를 내요', 'I make a surplus'],
    ['적자', 'jeokja', 'Deficit/Red', '적자를 줄여요', 'I reduce the deficit'],
    ['마케팅', 'maketing', 'Marketing', '마케팅을 강화해요', 'I strengthen marketing'],
    ['홍보', 'hongbo', 'Public relations', '홍보 활동을 해요', 'I do PR activities'],
    ['광고', 'gwanggo', 'Advertising', '광고를 집행해요', 'I run advertisements'],
    ['브랜드', 'beuraendeu', 'Brand', '브랜드를 구축해요', 'I build the brand'],
    ['이미지', 'imiji', 'Image', '기업 이미지를 관리해요', 'I manage corporate image'],
    ['평판', 'pyeongpan', 'Reputation', '평판을 유지해요', 'I maintain reputation'],
    ['신뢰', 'sinloe', 'Trust', '신뢰를 쌓아요', 'I build trust'],
    ['고객', 'gogaek', 'Customer', '고객을 확보해요', 'I acquire customers'],
    ['시장', 'sijang', 'Market', '시장을 확대해요', 'I expand the market'],
    ['점유율', 'jeomyuyul', 'Market share', '시장 점유율을 높여요', 'I increase market share'],
    ['확장', 'hwakjang', 'Expansion', '사업을 확장해요', 'I expand the business'],
    ['성장', 'seongjang', 'Growth', '지속 성장을 해요', 'I achieve sustained growth'],
    ['발전', 'baljeon', 'Development', '회사가 발전해요', 'The company develops'],
    ['합병', 'hapbyeong', 'Merger', '회사를 합병해요', 'I merge companies'],
    ['인수', 'insu', 'Acquisition', '회사를 인수해요', 'I acquire the company'],
    ['제휴', 'jehyu', 'Partnership', '전략적 제휴를 해요', 'I form strategic partnerships'],
    ['협력', 'hyeopnyeok', 'Collaboration', '기업 간 협력을 해요', 'I collaborate between companies']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

// HEALTHCARE - INTERMEDIATE: Medical Consultations
const healthcareIntermediate = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['진료', 'jinryo', 'Medical treatment', '진료를 받아요', 'I receive treatment'],
    ['진찰', 'jinchal', 'Examination', '진찰을 받아요', 'I get examined'],
    ['상담', 'sangdam', 'Consultation', '의사와 상담해요', 'I consult with a doctor'],
    ['증상', 'jeungsang', 'Symptom', '증상을 설명해요', 'I explain symptoms'],
    ['통증', 'tongjeung', 'Pain', '통증이 심해요', 'The pain is severe'],
    ['고통', 'gotong', 'Suffering/Pain', '고통이 있어요', 'I\'m in pain'],
    ['불편', 'bulpyeon', 'Discomfort', '불편한 증상이 있어요', 'I have uncomfortable symptoms'],
    ['진단', 'jindan', 'Diagnosis', '진단을 받았어요', 'I received a diagnosis'],
    ['소견', 'sogyeon', 'Medical opinion', '의사 소견이에요', 'It\'s the doctor\'s opinion'],
    ['판정', 'panjeong', 'Judgment/Decision', '질병 판정을 받았어요', 'I was diagnosed with a disease'],
    ['처방', 'cheobang', 'Prescription', '약을 처방받았어요', 'I received a prescription'],
    ['처방전', 'cheobangjeon', 'Prescription', '처방전을 받아요', 'I get a prescription'],
    ['약', 'yak', 'Medicine', '약을 복용해요', 'I take medicine'],
    ['복용', 'bogyong', 'Taking medicine', '하루 세 번 복용해요', 'I take it three times a day'],
    ['용법', 'yongbeop', 'Usage', '용법을 확인해요', 'I check the usage'],
    ['용량', 'yongnyang', 'Dosage', '용량을 지켜요', 'I follow the dosage'],
    ['투약', 'tuyak', 'Medication', '투약 시간이에요', 'It\'s medication time'],
    ['알약', 'alyak', 'Pill', '알약을 먹어요', 'I take pills'],
    ['캡슐', 'kaepsyul', 'Capsule', '캡슐을 삼켜요', 'I swallow capsules'],
    ['시럽', 'sireop', 'Syrup', '시럽을 마셔요', 'I drink syrup'],
    ['연고', 'yeongo', 'Ointment', '연고를 발라요', 'I apply ointment'],
    ['크림', 'keurim', 'Cream', '피부에 크림을 발라요', 'I apply cream to skin'],
    ['주사', 'jusa', 'Injection', '주사를 맞아요', 'I get an injection'],
    ['링거', 'ringgeo', 'IV drip', '링거를 맞아요', 'I get an IV drip'],
    ['검사', 'geomsa', 'Test/Examination', '검사가 필요해요', 'I need tests'],
    ['혈액 검사', 'hyeoraek geomsa', 'Blood test', '혈액 검사를 해요', 'I do a blood test'],
    ['소변 검사', 'sobyeon geomsa', 'Urine test', '소변 검사를 해요', 'I do a urine test'],
    ['X레이', 'ekseurei', 'X-ray', 'X레이를 찍어요', 'I take an X-ray'],
    ['엑스레이', 'ekseuseurei', 'X-ray', '엑스레이를 찍었어요', 'I took an X-ray'],
    ['CT', 'siti', 'CT scan', 'CT 촬영을 해요', 'I get a CT scan'],
    ['MRI', 'emeorai', 'MRI', 'MRI를 찍어요', 'I get an MRI'],
    ['초음파', 'choumpa', 'Ultrasound', '초음파 검사를 받아요', 'I get an ultrasound'],
    ['내시경', 'naesigyeong', 'Endoscopy', '내시경 검사를 해요', 'I do an endoscopy'],
    ['생검', 'saenggeom', 'Biopsy', '조직 생검을 해요', 'I do a tissue biopsy'],
    ['결과', 'gyeolgwa', 'Result', '검사 결과를 받아요', 'I receive test results'],
    ['수치', 'suchi', 'Value/Figure', '수치가 정상이에요', 'The values are normal'],
    ['이상', 'isang', 'Abnormality', '이상이 없어요', 'There\'s no abnormality'],
    ['정상', 'jeongsang', 'Normal', '정상 범위예요', 'It\'s within normal range'],
    ['음성', 'eumseong', 'Negative', '검사 결과가 음성이에요', 'The test result is negative'],
    ['양성', 'yangseong', 'Positive', '검사 결과가 양성이에요', 'The test result is positive'],
    ['치료', 'chiryo', 'Treatment', '치료를 받아요', 'I receive treatment'],
    ['치료법', 'chiryobeop', 'Treatment method', '치료법을 상의해요', 'I discuss treatment methods'],
    ['요법', 'yobeop', 'Therapy', '물리 요법을 받아요', 'I receive physical therapy'],
    ['물리치료', 'mullichiryo', 'Physical therapy', '물리치료를 해요', 'I do physical therapy'],
    ['재활', 'jaehwal', 'Rehabilitation', '재활 치료를 받아요', 'I receive rehabilitation'],
    ['수술', 'susul', 'Surgery', '수술이 필요해요', 'I need surgery'],
    ['시술', 'sisul', 'Procedure', '간단한 시술이에요', 'It\'s a simple procedure'],
    ['마취', 'chwi', 'Anesthesia', '전신 마취를 해요', 'I get general anesthesia'],
    ['부분 마취', 'bubun machui', 'Local anesthesia', '부분 마취를 해요', 'I get local anesthesia'],
    ['입원', 'ibwon', 'Hospitalization', '입원이 필요해요', 'Hospitalization is needed'],
    ['입원하다', 'ibwonhada', 'To be hospitalized', '병원에 입원해요', 'I\'m hospitalized'],
    ['퇴원', 'toewon', 'Discharge', '내일 퇴원해요', 'I\'m discharged tomorrow'],
    ['병실', 'byeongsil', 'Hospital room', '병실에 있어요', 'I\'m in the hospital room'],
    ['병상', 'byeongsang', 'Hospital bed', '병상에 누워 있어요', 'I\'m lying in the hospital bed'],
    ['회진', 'hoejin', 'Rounds', '의사 회진 시간이에요', 'It\'s the doctor\'s round time'],
    ['회복', 'hoebook', 'Recovery', '회복이 빨라요', 'Recovery is fast'],
    ['완치', 'wanchi', 'Complete recovery', '완치됐어요', 'I\'m completely recovered'],
    ['호전', 'hojeon', 'Improvement', '상태가 호전됐어요', 'The condition has improved'],
    ['악화', 'akhwa', 'Deterioration', '상태가 악화됐어요', 'The condition has deteriorated'],
    ['재발', 'jaebal', 'Recurrence', '재발 가능성이 있어요', 'There\'s a possibility of recurrence'],
    ['만성', 'manseong', 'Chronic', '만성 질환이에요', 'It\'s a chronic disease'],
    ['급성', 'geupseong', 'Acute', '급성 증상이에요', 'It\'s an acute symptom'],
    ['질병', 'jilbyeong', 'Disease', '질병을 예방해요', 'I prevent disease'],
    ['질환', 'jilhwan', 'Disorder', '만성 질환이 있어요', 'I have a chronic disorder'],
    ['병', 'byeong', 'Illness', '병이 나았어요', 'I recovered from illness'],
    ['질환', 'jilhwan', 'Condition', '기저 질환이 있어요', 'I have an underlying condition'],
    ['합병증', 'hapbyeongjeung', 'Complication', '합병증이 생겼어요', 'Complications developed'],
    ['후유증', 'huyujeung', 'Aftereffect', '후유증이 남았어요', 'Aftereffects remain'],
    ['부작용', 'bujagyong', 'Side effect', '약의 부작용이 있어요', 'There are side effects'],
    ['알레르기 반응', 'allereugi baneung', 'Allergic reaction', '알레르기 반응이 나타났어요', 'An allergic reaction appeared'],
    ['면역력', 'myeonyeoknyeok', 'Immunity', '면역력을 높여요', 'I boost immunity'],
    ['저항력', 'jeohangnyeok', 'Resistance', '저항력이 약해요', 'Resistance is weak'],
    ['전염', 'jeonyeom', 'Contagion', '전염성이 있어요', 'It\'s contagious'],
    ['감염', 'gamyeom', 'Infection', '감염될 수 있어요', 'It can be infected'],
    ['바이러스', 'baireoseu', 'Virus', '바이러스에 감염됐어요', 'I\'m infected with a virus'],
    ['세균', 'segyun', 'Bacteria', '세균 감염이에요', 'It\'s a bacterial infection'],
    ['염증', 'yeomjeung', 'Inflammation', '염증이 생겼어요', 'Inflammation developed'],
    ['출혈', 'chulhyeol', 'Bleeding', '출혈이 있어요', 'There\'s bleeding'],
    ['상처', 'sangcheo', 'Wound', '상처가 아물어요', 'The wound heals'],
    ['골절', 'goljeol', 'Fracture', '뼈가 골절됐어요', 'The bone is fractured'],
    ['타박상', 'tabaksang', 'Bruise', '타박상을 입었어요', 'I got a bruise'],
    ['염좌', 'yeomjwa', 'Sprain', '발목을 삐었어요', 'I sprained my ankle'],
    ['화상', 'hwasang', 'Burn', '화상을 입었어요', 'I got burned'],
    ['동상', 'dongsang', 'Frostbite', '동상에 걸렸어요', 'I got frostbite'],
    ['건강검진', 'geonganggeomjin', 'Health checkup', '정기 건강검진을 받아요', 'I get regular health checkups'],
    ['예방 접종', 'yebang jeopjong', 'Vaccination', '독감 예방 접종을 받아요', 'I get a flu shot'],
    ['백신', 'baeksin', 'Vaccine', '백신을 맞아요', 'I get vaccinated'],
    ['면역', 'myeonyeok', 'Immunity', '면역이 생겨요', 'Immunity develops'],
    ['항체', 'hangche', 'Antibody', '항체가 생성됐어요', 'Antibodies were produced'],
    ['예방', 'yebang', 'Prevention', '질병을 예방해요', 'I prevent disease'],
    ['관리', 'gwalli', 'Management', '건강을 관리해요', 'I manage my health'],
    ['유지', 'yuji', 'Maintenance', '건강을 유지해요', 'I maintain health'],
    ['개선', 'gaeseon', 'Improvement', '건강을 개선해요', 'I improve health'],
    ['증진', 'jeungjin', 'Promotion', '건강 증진을 해요', 'I promote health']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

// HEALTHCARE - ADVANCED: Specialized Treatment
const healthcareAdvanced = Array(105).fill(null).map((_, i) => {
  const vocab = [
    ['전문의', 'jeonmunui', 'Specialist', '전문의를 만나요', 'I see a specialist'],
    ['전공의', 'jeongongui', 'Resident doctor', '전공의가 진료해요', 'A resident treats me'],
    ['인턴', 'inteon', 'Intern', '인턴 의사예요', 'It\'s an intern doctor'],
    ['레지던트', 'rejideonteu', 'Resident', '레지던트가 관리해요', 'A resident manages it'],
    ['펠로우', 'pellou', 'Fellow', '펠로우 과정이에요', 'It\'s a fellowship program'],
    ['내과', 'naegwa', 'Internal medicine', '내과를 방문해요', 'I visit internal medicine'],
    ['외과', 'oegwa', 'Surgery', '외과 수술을 받아요', 'I get surgery'],
    ['정형외과', 'jeonghyeongoegwa', 'Orthopedics', '정형외과에 가요', 'I go to orthopedics'],
    ['신경외과', 'singyeongoegwa', 'Neurosurgery', '신경외과 전문의예요', 'It\'s a neurosurgeon'],
    ['흉부외과', 'heungbuoegwa', 'Thoracic surgery', '흉부외과 수술이에요', 'It\'s thoracic surgery'],
    ['성형외과', 'seonghyeongoegwa', 'Plastic surgery', '성형 수술을 받아요', 'I get plastic surgery'],
    ['피부과', 'pibugwa', 'Dermatology', '피부과에 다녀요', 'I go to dermatology'],
    ['비뇨기과', 'binyogigwa', 'Urology', '비뇨기과를 방문해요', 'I visit urology'],
    ['산부인과', 'sanbuingwa', 'Obstetrics and gynecology', '산부인과에 가요', 'I go to OB-GYN'],
    ['소아과', 'soagwa', 'Pediatrics', '소아과 의사예요', 'It\'s a pediatrician'],
    ['정신과', 'jeongsinkwa', 'Psychiatry', '정신과 상담을 받아요', 'I get psychiatric counseling'],
    ['심리과', 'silligwa', 'Psychology', '심리 치료를 받아요', 'I receive psychological treatment'],
    ['안과', 'angwa', 'Ophthalmology', '안과 검진을 받아요', 'I get an eye exam'],
    ['이비인후과', 'ibiinhugwa', 'ENT', '이비인후과에 가요', 'I go to ENT'],
    ['치과', 'chigwa', 'Dentistry', '치과 치료를 받아요', 'I get dental treatment'],
    ['마취과', 'machuigwa', 'Anesthesiology', '마취과 의사예요', 'It\'s an anesthesiologist'],
    ['응급의학과', 'eunggeupuihakgwa', 'Emergency medicine', '응급실에 가요', 'I go to the emergency room'],
    ['영상의학과', 'yeongsanguihakgwa', 'Radiology', '영상 검사를 해요', 'I do imaging tests'],
    ['병리과', 'byeolligwa', 'Pathology', '병리 검사를 해요', 'I do pathology tests'],
    ['진단', 'jindan', 'Diagnosis', '정확한 진단이 중요해요', 'Accurate diagnosis is important'],
    ['감별 진단', 'gambyeol jindan', 'Differential diagnosis', '감별 진단을 해요', 'I do differential diagnosis'],
    ['조기 진단', 'jogi jindan', 'Early diagnosis', '조기 진단이 중요해요', 'Early diagnosis is important'],
    ['오진', 'ojin', 'Misdiagnosis', '오진을 받았어요', 'I was misdiagnosed'],
    ['재진', 'jaejin', 'Re-examination', '재진을 받아요', 'I get re-examined'],
    ['정밀 검사', 'jeongmil geomsa', 'Detailed examination', '정밀 검사가 필요해요', 'I need detailed examination'],
    ['종합 검진', 'jonghap geomjin', 'Comprehensive checkup', '종합 검진을 받아요', 'I get a comprehensive checkup'],
    ['암 검진', 'am geomjin', 'Cancer screening', '암 검진을 해요', 'I do cancer screening'],
    ['조직 검사', 'jojik geomsa', 'Tissue examination', '조직 검사를 해요', 'I do tissue examination'],
    ['유전자 검사', 'yujeonja geomsa', 'Genetic test', '유전자 검사를 받아요', 'I get a genetic test'],
    ['임상 시험', 'imsang siheom', 'Clinical trial', '임상 시험에 참여해요', 'I participate in clinical trials'],
    ['신약', 'sinyak', 'New drug', '신약을 처방받아요', 'I get prescribed new drugs'],
    ['투여', 'tuyeo', 'Administration', '약물을 투여해요', 'They administer drugs'],
    ['처치', 'cheochi', 'Treatment/Procedure', '응급 처치를 받아요', 'I receive emergency treatment'],
    ['시술', 'sisul', 'Procedure', '최소 침습 시술이에요', 'It\'s a minimally invasive procedure'],
    ['수술실', 'susulsil', 'Operating room', '수술실에 들어가요', 'I enter the operating room'],
    ['집도', 'jipdo', 'Surgery performance', '의사가 집도해요', 'The doctor performs the surgery'],
    ['개복', 'gaebok', 'Open surgery', '개복 수술이에요', 'It\'s open surgery'],
    ['복강경', 'bokgangyeong', 'Laparoscopy', '복강경 수술을 해요', 'I do laparoscopic surgery'],
    ['로봇 수술', 'robot susul', 'Robotic surgery', '로봇 수술을 받아요', 'I get robotic surgery'],
    ['이식', 'isik', 'Transplant', '장기 이식 수술이에요', 'It\'s an organ transplant'],
    ['이식 수술', 'isik susul', 'Transplant surgery', '심장 이식 수술을 해요', 'I get a heart transplant'],
    ['장기 기증', 'janggi gijeung', 'Organ donation', '장기 기증을 해요', 'I donate organs'],
    ['혈액 검사', 'hyeoraek geomsa', 'Blood test', '혈액 검사 결과가 나왔어요', 'Blood test results came out'],
    ['혈당', 'hyeoldang', 'Blood sugar', '혈당을 측정해요', 'I measure blood sugar'],
    ['혈압', 'hyeorap', 'Blood pressure', '혈압이 높아요', 'Blood pressure is high'],
    ['콜레스테롤', 'kolleseuteol', 'Cholesterol', '콜레스테롤 수치가 높아요', 'Cholesterol levels are high'],
    ['중성지방', 'jungseongjibang', 'Triglycerides', '중성지방이 많아요', 'Triglycerides are high'],
    ['당뇨병', 'dangnyobyeong', 'Diabetes', '당뇨병이 있어요', 'I have diabetes'],
    ['고혈압', 'gohyeorap', 'Hypertension', '고혈압 치료를 받아요', 'I receive hypertension treatment'],
    ['저혈압', 'jeohyeorap', 'Low blood pressure', '저혈압이에요', 'I have low blood pressure'],
    ['심장병', 'simjangbyeong', 'Heart disease', '심장병이 있어요', 'I have heart disease'],
    ['심근경색', 'simgeungyeongssaek', 'Myocardial infarction', '심근경색이에요', 'It\'s a heart attack'],
    ['뇌졸중', 'noejoljung', 'Stroke', '뇌졸중 위험이 있어요', 'There\'s a stroke risk'],
    ['뇌출혈', 'noechulhyeol', 'Brain hemorrhage', '뇌출혈이 발생했어요', 'A brain hemorrhage occurred'],
    ['뇌경색', 'noegyeongssaek', 'Cerebral infarction', '뇌경색이에요', 'It\'s a cerebral infarction'],
    ['암', 'am', 'Cancer', '암 진단을 받았어요', 'I was diagnosed with cancer'],
    ['종양', 'jonyang', 'Tumor', '양성 종양이에요', 'It\'s a benign tumor'],
    ['양성', 'yangseong', 'Benign', '양성 종양이에요', 'It\'s a benign tumor'],
    ['악성', 'akseong', 'Malignant', '악성 종양이에요', 'It\'s a malignant tumor'],
    ['전이', 'jeoni', 'Metastasis', '암이 전이됐어요', 'The cancer has metastasized'],
    ['항암 치료', 'hangam chiryo', 'Cancer treatment', '항암 치료를 받아요', 'I receive chemotherapy'],
    ['방사선 치료', 'bangsaseon chiryo', 'Radiation therapy', '방사선 치료를 해요', 'I do radiation therapy'],
    ['화학 요법', 'hwahak yobeop', 'Chemotherapy', '화학 요법을 받아요', 'I receive chemotherapy'],
    ['표적 치료', 'pyojeok chiryo', 'Targeted therapy', '표적 치료를 해요', 'I do targeted therapy'],
    ['면역 치료', 'myeonyeok chiryo', 'Immunotherapy', '면역 치료를 받아요', 'I receive immunotherapy'],
    ['생존율', 'saengjonnyul', 'Survival rate', '5년 생존율이 높아요', '5-year survival rate is high'],
    ['완치율', 'wanchiyul', 'Complete cure rate', '완치율이 개선됐어요', 'The cure rate has improved'],
    ['예후', 'yehu', 'Prognosis', '예후가 좋아요', 'The prognosis is good'],
    ['경과', 'gyeonggwa', 'Progress', '경과를 관찰해요', 'I observe the progress'],
    ['추적 관찰', 'chujok gwanchal', 'Follow-up', '추적 관찰을 해요', 'I do follow-up'],
    ['정기 검진', 'jeonggi geomjin', 'Regular checkup', '정기 검진을 받아요', 'I get regular checkups'],
    ['재검사', 'jaegeomsa', 'Re-test', '재검사가 필요해요', 'Re-testing is needed'],
    ['통원 치료', 'tongwon chiryo', 'Outpatient treatment', '통원 치료를 해요', 'I do outpatient treatment'],
    ['입원 치료', 'ibwon chiryo', 'Inpatient treatment', '입원 치료가 필요해요', 'Inpatient treatment is needed'],
    ['집중 치료실', 'jipjung chiryosil', 'Intensive care unit', '중환자실에 있어요', 'I\'m in the ICU'],
    ['중환자실', 'jung hwanjasil', 'ICU', '중환자실에서 치료받아요', 'I\'m treated in the ICU'],
    ['격리', 'gyeongni', 'Isolation', '격리 치료를 받아요', 'I receive isolation treatment'],
    ['무균실', 'mugyunsil', 'Sterile room', '무균실에 있어요', 'I\'m in a sterile room'],
    ['멸균', 'myeolgyun', 'Sterilization', '기구를 멸균해요', 'They sterilize instruments'],
    ['소독', 'sodok', 'Disinfection', '상처를 소독해요', 'I disinfect the wound'],
    ['위생', 'wisaeng', 'Hygiene', '위생 관리를 해요', 'I manage hygiene'],
    ['보균자', 'bogyunja', 'Carrier', '보균자일 수 있어요', 'I might be a carrier'],
    ['격리 병동', 'gyeongni byeongdong', 'Isolation ward', '격리 병동에 있어요', 'I\'m in isolation ward'],
    ['전염병', 'jeonyeombyeong', 'Infectious disease', '전염병 관리를 해요', 'I manage infectious diseases'],
    ['전파', 'jeonpa', 'Transmission', '전파를 차단해요', 'I block transmission'],
    ['유행', 'yuhaeng', 'Epidemic', '유행이 확산돼요', 'The epidemic is spreading'],
    ['팬데믹', 'paendemmik', 'Pandemic', '팬데믹이 발생했어요', 'A pandemic occurred'],
    ['방역', 'bangyeok', 'Quarantine', '방역을 강화해요', 'I strengthen quarantine']
  ];

  if (i < vocab.length) {
    const [k, r, e, ex, exE] = vocab[i];
    return createContentItem(k, r, e, 'word', ex, exE);
  }
  return null;
}).filter(Boolean);

module.exports = {
  dailyLifeIntermediate,
  dailyLifeAdvanced,
  foodIntermediate,
  foodAdvanced,
  travelIntermediate,
  travelAdvanced,
  shoppingIntermediate,
  shoppingAdvanced,
  businessIntermediate,
  businessAdvanced,
  healthcareIntermediate,
  healthcareAdvanced
};
