// Sentence-based lessons for all categories
// These are Q&A style sentences in Korean

const createContentItem = (korean, romanization, english, type = 'sentence', example = '', exampleEnglish = '', breakdown = null) => ({
  type,
  korean,
  romanization,
  english,
  pronunciation: romanization,
  example: example || korean,
  exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown } : {}),
});

// GREETINGS - Sentences (Q&A format)
const greetingsSentences = [
  ['안녕하세요?', 'Annyeonghaseyo?', 'Hello, how are you?'],
  ['잘 지냈어요?', 'Jal jinaesseoyo?', 'How have you been?'],
  ['네, 잘 지냈어요.', 'Ne, jal jinaesseoyo.', 'Yes, I have been well.'],
  ['오랜만이에요.', 'Oraenmanieyo.', 'Long time no see.'],
  ['정말 오랜만이네요.', 'Jeongmal oraenmanineyo.', 'It has been a really long time.'],
  ['어떻게 지내세요?', 'Eotteoke jinaeseyo?', 'How are you doing?'],
  ['덕분에 잘 지내요.', 'Deokbune jal jinaeyo.', 'I am doing well, thanks to you.'],
  ['만나서 반가워요.', 'Mannaseo bangawoyo.', 'Nice to meet you.'],
  ['저도 반가워요.', 'Jeodo bangawoyo.', 'Nice to meet you too.'],
  ['이름이 뭐예요?', 'Ireumi mwoyeyo?', 'What is your name?'],
  ['제 이름은 김민수예요.', 'Je ireumeun Kim Minsuyeyo.', 'My name is Kim Minsu.'],
  ['어디서 오셨어요?', 'Eodiseo osyeosseoyo?', 'Where are you from?'],
  ['저는 미국에서 왔어요.', 'Jeoneun migugeseo wasseoyo.', 'I am from America.'],
  ['한국말 잘하시네요.', 'Hangungmal jalhasineyo.', 'You speak Korean well.'],
  ['아니에요, 아직 배우고 있어요.', 'Anieyo, ajik baeugo isseoyo.', 'No, I am still learning.'],
  ['직업이 뭐예요?', 'Jigeobi mwoyeyo?', 'What is your job?'],
  ['저는 학생이에요.', 'Jeoneun haksaengieyo.', 'I am a student.'],
  ['몇 살이에요?', 'Myeot sarieyo?', 'How old are you?'],
  ['스물다섯 살이에요.', 'Seumuldaseot sarieyo.', 'I am twenty-five years old.'],
  ['취미가 뭐예요?', 'Chwimiga mwoyeyo?', 'What is your hobby?'],
  ['음악 듣는 것을 좋아해요.', 'Eumak deutneun geoseul joahaeyo.', 'I like listening to music.'],
  ['가족이 몇 명이에요?', 'Gajogi myeot myeongieyo?', 'How many people are in your family?'],
  ['네 명이에요.', 'Ne myeongieyo.', 'There are four people.'],
  ['형제자매가 있어요?', 'Hyeongje jamae ga isseoyo?', 'Do you have siblings?'],
  ['네, 언니가 한 명 있어요.', 'Ne, eonniga han myeong isseoyo.', 'Yes, I have one older sister.'],
  ['주말에 뭐 했어요?', 'Jumare mwo haesseoyo?', 'What did you do on the weekend?'],
  ['친구들하고 영화를 봤어요.', 'Chingudeurhago yeonghwareul bwasseoyo.', 'I watched a movie with friends.'],
  ['오늘 날씨가 좋네요.', 'Oneul nalssiga joneyo.', 'The weather is nice today.'],
  ['네, 정말 좋아요.', 'Ne, jeongmal joayo.', 'Yes, it is really nice.'],
  ['내일 시간 있어요?', 'Naeil sigan isseoyo?', 'Do you have time tomorrow?'],
  ['네, 시간 있어요.', 'Ne, sigan isseoyo.', 'Yes, I have time.'],
  ['커피 한잔 할까요?', 'Keopi hanjan halkkayo?', 'Shall we have a cup of coffee?'],
  ['좋아요, 그럽시다.', 'Joayo, geureopsida.', 'Sounds good, let\'s do that.'],
  ['전화번호가 어떻게 되세요?', 'Jeonhwa beonhoga eotteoke doeseyo?', 'What is your phone number?'],
  ['010-1234-5678이에요.', '010-1234-5678ieyo.', 'It is 010-1234-5678.'],
  ['연락 드릴게요.', 'Yeollak deurilgeyo.', 'I will contact you.'],
  ['네, 연락 주세요.', 'Ne, yeollak juseyo.', 'Yes, please contact me.'],
  ['요즘 어떠세요?', 'Yojeum eotteoseyo?', 'How are things these days?'],
  ['바쁘지만 괜찮아요.', 'Bappeujiman gwaenchanhayo.', 'I am busy but okay.'],
  ['건강은 어떠세요?', 'Geongangeun eotteoseyo?', 'How is your health?'],
  ['건강해요, 감사합니다.', 'Geonganghaeyo, gamsahamnida.', 'I am healthy, thank you.'],
  ['한국은 처음이에요?', 'Hangugeun cheoumieyo?', 'Is this your first time in Korea?'],
  ['네, 처음이에요.', 'Ne, cheoumieyo.', 'Yes, it is my first time.'],
  ['한국 음식 좋아하세요?', 'Hanguk eumsik joahaseyo?', 'Do you like Korean food?'],
  ['네, 아주 좋아해요.', 'Ne, aju joahaeyo.', 'Yes, I like it very much.'],
  ['김치 먹을 수 있어요?', 'Gimchi meogeul su isseoyo?', 'Can you eat kimchi?'],
  ['네, 김치 좋아해요.', 'Ne, gimchi joahaeyo.', 'Yes, I like kimchi.'],
  ['한국어 공부한 지 얼마나 됐어요?', 'Hangugeo gongbuhan ji eolmana dwaesseoyo?', 'How long have you been studying Korean?'],
  ['1년 정도 됐어요.', '1nyeon jeongdo dwaesseoyo.', 'About one year.'],
  ['한국어가 어려워요?', 'Hangugeoga eoryeowoyo?', 'Is Korean difficult?'],
  ['조금 어렵지만 재미있어요.', 'Jogeum eoryeopjiman jaemiisseoyo.', 'It is a bit difficult but interesting.'],
  ['한국에서 뭐 하세요?', 'Hangugeseo mwo haseyo?', 'What do you do in Korea?'],
  ['영어를 가르쳐요.', 'Yeongeoreul gareuchyeoyo.', 'I teach English.'],
  ['한국 생활은 어때요?', 'Hanguk saenghwareun eottaeyo?', 'How is life in Korea?'],
  ['정말 좋아요.', 'Jeongmal joayo.', 'It is really good.'],
  ['한국에 얼마나 있을 거예요?', 'Hanguge eolmana isseul geoyeyo?', 'How long will you be in Korea?'],
  ['2년 정도 있을 거예요.', '2nyeon jeongdo isseul geoyeyo.', 'I will be here for about 2 years.'],
  ['주말에 보통 뭐 해요?', 'Jumare botong mwo haeyo?', 'What do you usually do on weekends?'],
  ['보통 집에서 쉬어요.', 'Botong jibeseo swieoyo.', 'I usually rest at home.'],
  ['언제 한국에 왔어요?', 'Eonje hanguge wasseoyo?', 'When did you come to Korea?'],
  ['작년에 왔어요.', 'Jangnyeone wasseoyo.', 'I came last year.'],
  ['어디에 살아요?', 'Eodie sarayo?', 'Where do you live?'],
  ['서울에 살아요.', 'Seoure sarayo.', 'I live in Seoul.'],
  ['서울 어디에 살아요?', 'Seoul eodie sarayo?', 'Where in Seoul do you live?'],
  ['강남에 살아요.', 'Gangnamen sarayo.', 'I live in Gangnam.'],
  ['혼자 살아요?', 'Honja sarayo?', 'Do you live alone?'],
  ['아니요, 룸메이트와 살아요.', 'Aniyo, rummeiteuwa sarayo.', 'No, I live with a roommate.'],
  ['집이 어때요?', 'Jibi eottaeyo?', 'How is your house?'],
  ['작지만 괜찮아요.', 'Jakjiman gwaenchanhayo.', 'It is small but okay.'],
  ['회사는 어디예요?', 'Hoesaneun eodiyeyo?', 'Where is your company?'],
  ['강남역 근처예요.', 'Gangnam yeok geuncheoyeyo.', 'It is near Gangnam station.'],
  ['출퇴근 시간이 얼마나 걸려요?', 'Chultoegeun sigani eolmana geollyeoyo?', 'How long is your commute?'],
  ['한 시간 정도 걸려요.', 'Han sigan jeongdo geollyeoyo.', 'It takes about one hour.'],
  ['무슨 요일에 쉬어요?', 'Museun yoire swieoyo?', 'What day do you have off?'],
  ['토요일하고 일요일에 쉬어요.', 'Toyoilhago iryoire swieoyo.', 'I have off on Saturday and Sunday.'],
  ['오늘 바빠요?', 'Oneul bappayo?', 'Are you busy today?'],
  ['아니요, 안 바빠요.', 'Aniyo, an bappayo.', 'No, I am not busy.'],
  ['같이 점심 먹을래요?', 'Gachi jeomsim meogeullaeyo?', 'Do you want to eat lunch together?'],
  ['좋아요, 같이 먹어요.', 'Joayo, gachi meogeoyo.', 'Sounds good, let\'s eat together.'],
  ['뭐 먹고 싶어요?', 'Mwo meokgo sipeoyo?', 'What do you want to eat?'],
  ['한식이 먹고 싶어요.', 'Hansigi meokgo sipeoyo.', 'I want to eat Korean food.'],
  ['지금 시간 있어요?', 'Jigeum sigan isseoyo?', 'Do you have time now?'],
  ['미안해요, 지금은 바빠요.', 'Mianhaeyo, jigeumeun bappayo.', 'Sorry, I am busy now.'],
  ['나중에 연락할게요.', 'Najunge yeonlakhalgeyo.', 'I will contact you later.'],
  ['네, 나중에 봐요.', 'Ne, najunge bwayo.', 'Okay, see you later.'],
  ['잘 가요.', 'Jal gayo.', 'Goodbye (to someone leaving).'],
  ['안녕히 가세요.', 'Annyeonghi gaseyo.', 'Goodbye (formal, to someone leaving).'],
  ['안녕히 계세요.', 'Annyeonghi gyeseyo.', 'Goodbye (to someone staying).'],
  ['또 만나요.', 'Tto mannayo.', 'See you again.'],
  ['내일 봐요.', 'Naeil bwayo.', 'See you tomorrow.'],
  ['다음 주에 봐요.', 'Daeum jue bwayo.', 'See you next week.'],
  ['좋은 하루 보내세요.', 'Joeun haru bonaeseyo.', 'Have a good day.'],
  ['감사합니다, 당신도요.', 'Gamsahamnida, dangsindo yo.', 'Thank you, you too.'],
  ['수고하셨어요.', 'Sugohasseosseoyo.', 'Good job (acknowledgment of hard work).'],
  ['감사합니다.', 'Gamsahamnida.', 'Thank you.'],
  ['실례합니다.', 'Sillyehamnida.', 'Excuse me.'],
  ['괜찮아요.', 'Gwaenchanhayo.', 'It\'s okay.'],
  ['죄송합니다.', 'Joesonghamnida.', 'I am sorry.'],
  ['괜찮아요, 신경 쓰지 마세요.', 'Gwaenchanhayo, singyeong sseuji maseyo.', 'It\'s okay, don\'t worry about it.'],
  ['도와주셔서 감사합니다.', 'Dowajusyeoseo gamsahamnida.', 'Thank you for helping.'],
  ['천만에요.', 'Cheonmaneyo.', 'You\'re welcome.'],
  ['잠깐만 기다려 주세요.', 'Jamkkanman gidaryeo juseyo.', 'Please wait a moment.'],
  ['네, 알겠습니다.', 'Ne, algesseumnida.', 'Yes, I understand.'],
  ['다시 한번 말씀해 주세요.', 'Dasi hanbeon malsseum hae juseyo.', 'Please say it one more time.'],
  ['천천히 말씀해 주세요.', 'Cheoncheonhi malsseum hae juseyo.', 'Please speak slowly.'],
  ['무슨 뜻이에요?', 'Museun ddeusieyo?', 'What does it mean?'],
  ['잘 모르겠어요.', 'Jal moreugesseoyo.', 'I don\'t know well.'],
  ['이해했어요?', 'Ihaehaesseoyo?', 'Did you understand?'],
  ['네, 이해했어요.', 'Ne, ihaehaesseoyo.', 'Yes, I understood.'],
].map(([k, r, e]) => createContentItem(k, r, e, 'sentence', k, e));

// DAILY LIFE - Sentences
const dailyLifeSentences = [
  // Morning routine
  ['아침에 몇 시에 일어나요?', 'Achime myeot sie ireonayo?', 'What time do you wake up in the morning?', [
    { korean: '아침에', english: 'in the morning' },
    { korean: '몇 시에', english: 'at what time' },
    { korean: '일어나요?', english: 'do you wake up?' },
  ]],
  ['보통 7시에 일어나요.', 'Botong 7sie ireonayo.', 'I usually wake up at 7 o\'clock.', [
    { korean: '보통', english: 'usually' },
    { korean: '7시에', english: 'at 7 o\'clock' },
    { korean: '일어나요', english: 'I wake up' },
  ]],
  ['아침은 뭐 먹어요?', 'Achimeun mwo meogeoyo?', 'What do you eat for breakfast?', [
    { korean: '아침은', english: 'for breakfast' },
    { korean: '뭐', english: 'what' },
    { korean: '먹어요?', english: 'do you eat?' },
  ]],
  ['보통 빵하고 커피를 먹어요.', 'Botong ppanghago keopireul meogeoyo.', 'I usually eat bread and coffee.', [
    { korean: '보통', english: 'usually' },
    { korean: '빵하고', english: 'bread and' },
    { korean: '커피를', english: 'coffee' },
    { korean: '먹어요', english: 'I eat' },
  ]],

  // Work routine
  ['출근 시간이 언제예요?', 'Chulgeun sigani eonjeyeyo?', 'When is your work start time?', [
    { korean: '출근 시간이', english: 'work start time' },
    { korean: '언제예요?', english: 'when is it?' },
  ]],
  ['9시에 출근해요.', '9sie chulgeunhaeyo.', 'I start work at 9 o\'clock.', [
    { korean: '9시에', english: 'at 9 o\'clock' },
    { korean: '출근해요', english: 'I go to work' },
  ]],
  ['어떻게 출근해요?', 'Eotteoke chulgeunhaeyo?', 'How do you commute to work?', [
    { korean: '어떻게', english: 'how' },
    { korean: '출근해요?', english: 'do you commute?' },
  ]],
  ['지하철로 출근해요.', 'Jihacheolro chulgeunhaeyo.', 'I commute by subway.', [
    { korean: '지하철로', english: 'by subway' },
    { korean: '출근해요', english: 'I commute' },
  ]],
  ['점심은 어디서 먹어요?', 'Jeomsimeun eodiseo meogeoyo?', 'Where do you eat lunch?', [
    { korean: '점심은', english: 'lunch' },
    { korean: '어디서', english: 'where' },
    { korean: '먹어요?', english: 'do you eat?' },
  ]],
  ['회사 근처 식당에서 먹어요.', 'Hoesa geuncheo sikdangeseo meogeoyo.', 'I eat at a restaurant near the office.', [
    { korean: '회사 근처', english: 'near the office' },
    { korean: '식당에서', english: 'at a restaurant' },
    { korean: '먹어요', english: 'I eat' },
  ]],
  ['퇴근 시간이 언제예요?', 'Toegeun sigani eonjeyeyo?', 'When do you finish work?', [
    { korean: '퇴근 시간이', english: 'finish work time' },
    { korean: '언제예요?', english: 'when is it?' },
  ]],
  ['6시에 퇴근해요.', '6sie toegeunhaeyo.', 'I finish work at 6 o\'clock.', [
    { korean: '6시에', english: 'at 6 o\'clock' },
    { korean: '퇴근해요', english: 'I finish work' },
  ]],
  ['퇴근 후에 뭐 해요?', 'Toegeun hue mwo haeyo?', 'What do you do after work?', [
    { korean: '퇴근 후에', english: 'after work' },
    { korean: '뭐', english: 'what' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['보통 집에 가서 쉬어요.', 'Botong jibe gaseo swieoyo.', 'I usually go home and rest.', [
    { korean: '보통', english: 'usually' },
    { korean: '집에 가서', english: 'go home and' },
    { korean: '쉬어요', english: 'rest' },
  ]],

  // Evening and dinner
  ['저녁은 몇 시에 먹어요?', 'Jeonyeogeun myeot sie meogeoyo?', 'What time do you eat dinner?', [
    { korean: '저녁은', english: 'dinner' },
    { korean: '몇 시에', english: 'at what time' },
    { korean: '먹어요?', english: 'do you eat?' },
  ]],
  ['7시쯤 먹어요.', '7sijjeum meogeoyo.', 'I eat around 7 o\'clock.', [
    { korean: '7시쯤', english: 'around 7 o\'clock' },
    { korean: '먹어요', english: 'I eat' },
  ]],
  ['저녁 식사는 누가 준비해요?', 'Jeonyeok siksaneun nuga junbihaeyo?', 'Who prepares dinner?', [
    { korean: '저녁 식사는', english: 'dinner' },
    { korean: '누가', english: 'who' },
    { korean: '준비해요?', english: 'prepares?' },
  ]],
  ['제가 직접 요리해요.', 'Jega jikjeop yorihaeyo.', 'I cook it myself.', [
    { korean: '제가', english: 'I' },
    { korean: '직접', english: 'myself / directly' },
    { korean: '요리해요', english: 'cook' },
  ]],
  ['요리하는 것을 좋아해요?', 'Yorihaneun geoseul joahaeyo?', 'Do you like cooking?', [
    { korean: '요리하는 것을', english: 'cooking' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['네, 요리하는 것을 좋아해요.', 'Ne, yorihaneun geoseul joahaeyo.', 'Yes, I like cooking.', [
    { korean: '네', english: 'yes' },
    { korean: '요리하는 것을', english: 'cooking' },
    { korean: '좋아해요', english: 'I like' },
  ]],

  // Sleep routine
  ['보통 몇 시에 자요?', 'Botong myeot sie jayo?', 'What time do you usually go to bed?', [
    { korean: '보통', english: 'usually' },
    { korean: '몇 시에', english: 'at what time' },
    { korean: '자요?', english: 'do you sleep?' },
  ]],
  ['11시쯤 자요.', '11sijjeum jayo.', 'I go to bed around 11 o\'clock.', [
    { korean: '11시쯤', english: 'around 11 o\'clock' },
    { korean: '자요', english: 'I sleep' },
  ]],
  ['잠은 잘 자요?', 'Jameun jal jayo?', 'Do you sleep well?', [
    { korean: '잠은', english: 'sleep' },
    { korean: '잘', english: 'well' },
    { korean: '자요?', english: 'do you sleep?' },
  ]],
  ['네, 보통 잘 자요.', 'Ne, botong jal jayo.', 'Yes, I usually sleep well.', [
    { korean: '네', english: 'yes' },
    { korean: '보통', english: 'usually' },
    { korean: '잘 자요', english: 'I sleep well' },
  ]],

  // Weekend activities
  ['주말에는 뭐 해요?', 'Jumareneun mwo haeyo?', 'What do you do on weekends?', [
    { korean: '주말에는', english: 'on weekends' },
    { korean: '뭐', english: 'what' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['친구들을 만나거나 집에서 쉬어요.', 'Chingudeureul mannageona jibeseo swieoyo.', 'I meet friends or rest at home.', [
    { korean: '친구들을 만나거나', english: 'meet friends or' },
    { korean: '집에서', english: 'at home' },
    { korean: '쉬어요', english: 'rest' },
  ]],

  // Housework
  ['집안일은 언제 해요?', 'Jibanireun eonje haeyo?', 'When do you do housework?', [
    { korean: '집안일은', english: 'housework' },
    { korean: '언제', english: 'when' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['주말에 해요.', 'Jumare haeyo.', 'I do it on weekends.', [
    { korean: '주말에', english: 'on weekends' },
    { korean: '해요', english: 'I do it' },
  ]],
  ['빨래는 얼마나 자주 해요?', 'Ppallaeneun eolmana jaju haeyo?', 'How often do you do laundry?', [
    { korean: '빨래는', english: 'laundry' },
    { korean: '얼마나 자주', english: 'how often' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['일주일에 한 번 해요.', 'Iljuire han beon haeyo.', 'I do it once a week.', [
    { korean: '일주일에', english: 'in a week' },
    { korean: '한 번', english: 'once' },
    { korean: '해요', english: 'I do it' },
  ]],
  ['청소는 얼마나 자주 해요?', 'Cheongsoneun eolmana jaju haeyo?', 'How often do you clean?', [
    { korean: '청소는', english: 'cleaning' },
    { korean: '얼마나 자주', english: 'how often' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['일주일에 두 번 정도 해요.', 'Iljuire du beon jeongdo haeyo.', 'I do it about twice a week.', [
    { korean: '일주일에', english: 'in a week' },
    { korean: '두 번 정도', english: 'about twice' },
    { korean: '해요', english: 'I do it' },
  ]],

  // Grocery shopping
  ['장은 어디서 봐요?', 'Jangeun eodiseo bwayo?', 'Where do you go grocery shopping?', [
    { korean: '장은', english: 'grocery shopping' },
    { korean: '어디서', english: 'where' },
    { korean: '봐요?', english: 'do you do?' },
  ]],
  ['근처 마트에서 봐요.', 'Geuncheo mateu eseo bwayo.', 'I shop at a nearby mart.', [
    { korean: '근처', english: 'nearby' },
    { korean: '마트에서', english: 'at the mart' },
    { korean: '봐요', english: 'I shop' },
  ]],
  ['장은 얼마나 자주 봐요?', 'Jangeun eolmana jaju bwayo?', 'How often do you go grocery shopping?', [
    { korean: '장은', english: 'grocery shopping' },
    { korean: '얼마나 자주', english: 'how often' },
    { korean: '봐요?', english: 'do you do?' },
  ]],
  ['일주일에 한 번 봐요.', 'Iljuire han beon bwayo.', 'I go once a week.', [
    { korean: '일주일에', english: 'in a week' },
    { korean: '한 번', english: 'once' },
    { korean: '봐요', english: 'I go' },
  ]],

  // Exercise
  ['운동은 언제 해요?', 'Undongeun eonje haeyo?', 'When do you exercise?', [
    { korean: '운동은', english: 'exercise' },
    { korean: '언제', english: 'when' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['저녁에 운동해요.', 'Jeonyeoge undonghaeyo.', 'I exercise in the evening.', [
    { korean: '저녁에', english: 'in the evening' },
    { korean: '운동해요', english: 'I exercise' },
  ]],
  ['무슨 운동을 해요?', 'Museun undongeul haeyo?', 'What exercise do you do?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '운동을', english: 'exercise' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['조깅을 해요.', 'Joggingeul haeyo.', 'I go jogging.', [
    { korean: '조깅을', english: 'jogging' },
    { korean: '해요', english: 'I do' },
  ]],
  ['일주일에 몇 번 운동해요?', 'Iljuire myeot beon undonghaeyo?', 'How many times a week do you exercise?', [
    { korean: '일주일에', english: 'in a week' },
    { korean: '몇 번', english: 'how many times' },
    { korean: '운동해요?', english: 'do you exercise?' },
  ]],
  ['일주일에 세 번 정도 해요.', 'Iljuire se beon jeongdo haeyo.', 'I do it about three times a week.', [
    { korean: '일주일에', english: 'in a week' },
    { korean: '세 번 정도', english: 'about three times' },
    { korean: '해요', english: 'I do it' },
  ]],

  // Hobbies - Reading
  ['취미가 뭐예요?', 'Chwimiga mwoyeyo?', 'What is your hobby?', [
    { korean: '취미가', english: 'hobby' },
    { korean: '뭐예요?', english: 'what is it?' },
  ]],
  ['책 읽는 것을 좋아해요.', 'Chaek ingneun geoseul joahaeyo.', 'I like reading books.', [
    { korean: '책 읽는 것을', english: 'reading books' },
    { korean: '좋아해요', english: 'I like' },
  ]],
  ['무슨 책을 좋아해요?', 'Museun chaekeul joahaeyo?', 'What kind of books do you like?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '책을', english: 'books' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['소설을 좋아해요.', 'Soseoreul joahaeyo.', 'I like novels.', [
    { korean: '소설을', english: 'novels' },
    { korean: '좋아해요', english: 'I like' },
  ]],

  // Hobbies - Movies
  ['영화는 자주 봐요?', 'Yeonghwaneun jaju bwayo?', 'Do you often watch movies?', [
    { korean: '영화는', english: 'movies' },
    { korean: '자주', english: 'often' },
    { korean: '봐요?', english: 'do you watch?' },
  ]],
  ['네, 영화를 자주 봐요.', 'Ne, yeonghwareul jaju bwayo.', 'Yes, I watch movies often.', [
    { korean: '네', english: 'yes' },
    { korean: '영화를', english: 'movies' },
    { korean: '자주', english: 'often' },
    { korean: '봐요', english: 'I watch' },
  ]],
  ['무슨 영화를 좋아해요?', 'Museun yeonghwareul joahaeyo?', 'What kind of movies do you like?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '영화를', english: 'movies' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['액션 영화를 좋아해요.', 'Aeksyeon yeonghwareul joahaeyo.', 'I like action movies.', [
    { korean: '액션 영화를', english: 'action movies' },
    { korean: '좋아해요', english: 'I like' },
  ]],

  // Hobbies - Music
  ['음악을 자주 들어요?', 'Eumagul jaju deureoyo?', 'Do you often listen to music?', [
    { korean: '음악을', english: 'music' },
    { korean: '자주', english: 'often' },
    { korean: '들어요?', english: 'do you listen?' },
  ]],
  ['네, 매일 들어요.', 'Ne, maeil deureoyo.', 'Yes, I listen every day.', [
    { korean: '네', english: 'yes' },
    { korean: '매일', english: 'every day' },
    { korean: '들어요', english: 'I listen' },
  ]],
  ['무슨 음악을 좋아해요?', 'Museun eumagul joahaeyo?', 'What kind of music do you like?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '음악을', english: 'music' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['케이팝을 좋아해요.', 'Keipapeul joahaeyo.', 'I like K-pop.', [
    { korean: '케이팝을', english: 'K-pop' },
    { korean: '좋아해요', english: 'I like' },
  ]],

  // Hobbies - Games
  ['게임을 해요?', 'Geimeul haeyo?', 'Do you play games?', [
    { korean: '게임을', english: 'games' },
    { korean: '해요?', english: 'do you play?' },
  ]],
  ['네, 가끔 해요.', 'Ne, gakkeum haeyo.', 'Yes, I play sometimes.', [
    { korean: '네', english: 'yes' },
    { korean: '가끔', english: 'sometimes' },
    { korean: '해요', english: 'I do' },
  ]],
  ['무슨 게임을 해요?', 'Museun geimeul haeyo?', 'What games do you play?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '게임을', english: 'games' },
    { korean: '해요?', english: 'do you play?' },
  ]],
  ['RPG 게임을 해요.', 'RPG geimeul haeyo.', 'I play RPG games.', [
    { korean: 'RPG 게임을', english: 'RPG games' },
    { korean: '해요', english: 'I play' },
  ]],

  // Hobbies - TV
  ['TV는 자주 봐요?', 'TVneun jaju bwayo?', 'Do you often watch TV?', [
    { korean: 'TV는', english: 'TV' },
    { korean: '자주', english: 'often' },
    { korean: '봐요?', english: 'do you watch?' },
  ]],
  ['아니요, 잘 안 봐요.', 'Aniyo, jal an bwayo.', 'No, I don\'t watch it much.', [
    { korean: '아니요', english: 'no' },
    { korean: '잘 안', english: 'not much' },
    { korean: '봐요', english: 'I watch' },
  ]],
  ['무슨 프로그램을 좋아해요?', 'Museun peurogeuraemeul joahaeyo?', 'What programs do you like?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '프로그램을', english: 'programs' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['예능 프로그램을 좋아해요.', 'Yeneung peurogeuraemeul joahaeyo.', 'I like variety shows.', [
    { korean: '예능 프로그램을', english: 'variety shows' },
    { korean: '좋아해요', english: 'I like' },
  ]],

  // Travel
  ['여행을 자주 가요?', 'Yeohaengeul jaju gayo?', 'Do you travel often?', [
    { korean: '여행을', english: 'travel' },
    { korean: '자주', english: 'often' },
    { korean: '가요?', english: 'do you go?' },
  ]],
  ['일년에 한두 번 정도 가요.', 'Ilnyeone handu beon jeongdo gayo.', 'I go about once or twice a year.', [
    { korean: '일년에', english: 'in a year' },
    { korean: '한두 번 정도', english: 'about once or twice' },
    { korean: '가요', english: 'I go' },
  ]],
  ['어디로 여행 가고 싶어요?', 'Eodiro yeohaeng gago sipeoyo?', 'Where do you want to travel?', [
    { korean: '어디로', english: 'where to' },
    { korean: '여행', english: 'travel' },
    { korean: '가고 싶어요?', english: 'do you want to go?' },
  ]],
  ['제주도에 가고 싶어요.', 'Jejudoe gago sipeoyo.', 'I want to go to Jeju Island.', [
    { korean: '제주도에', english: 'to Jeju Island' },
    { korean: '가고 싶어요', english: 'I want to go' },
  ]],

  // Pets
  ['반려동물이 있어요?', 'Ballyeodongmuri isseoyo?', 'Do you have a pet?', [
    { korean: '반려동물이', english: 'pet' },
    { korean: '있어요?', english: 'do you have?' },
  ]],
  ['네, 고양이가 있어요.', 'Ne, goyangiga isseoyo.', 'Yes, I have a cat.', [
    { korean: '네', english: 'yes' },
    { korean: '고양이가', english: 'a cat' },
    { korean: '있어요', english: 'I have' },
  ]],
  ['이름이 뭐예요?', 'Ireumi mwoyeyo?', 'What is its name?', [
    { korean: '이름이', english: 'name' },
    { korean: '뭐예요?', english: 'what is it?' },
  ]],
  ['이름은 나비예요.', 'Ireumeun nabiyeyo.', 'Its name is Nabi.', [
    { korean: '이름은', english: 'the name' },
    { korean: '나비예요', english: 'is Nabi' },
  ]],

  // Stress management
  ['스트레스 받을 때 뭐 해요?', 'Seuteureseu badeul ttae mwo haeyo?', 'What do you do when you are stressed?', [
    { korean: '스트레스 받을 때', english: 'when stressed' },
    { korean: '뭐', english: 'what' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['음악을 듣거나 산책을 해요.', 'Eumagul deutgeona sanchaegeul haeyo.', 'I listen to music or go for a walk.', [
    { korean: '음악을 듣거나', english: 'listen to music or' },
    { korean: '산책을 해요', english: 'go for a walk' },
  ]],

  // Cafes and beverages
  ['카페에 자주 가요?', 'Kapee jaju gayo?', 'Do you often go to cafes?', [
    { korean: '카페에', english: 'to cafes' },
    { korean: '자주', english: 'often' },
    { korean: '가요?', english: 'do you go?' },
  ]],
  ['네, 일주일에 두세 번 가요.', 'Ne, iljuire duse beon gayo.', 'Yes, I go two or three times a week.', [
    { korean: '네', english: 'yes' },
    { korean: '일주일에', english: 'in a week' },
    { korean: '두세 번', english: 'two or three times' },
    { korean: '가요', english: 'I go' },
  ]],
  ['무슨 커피를 좋아해요?', 'Museun keopireul joahaeyo?', 'What kind of coffee do you like?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '커피를', english: 'coffee' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['아메리카노를 좋아해요.', 'Amerikanoreul joahaeyo.', 'I like Americano.', [
    { korean: '아메리카노를', english: 'Americano' },
    { korean: '좋아해요', english: 'I like' },
  ]],

  // Alcohol
  ['술을 자주 마셔요?', 'Sureul jaju masyeoyo?', 'Do you often drink alcohol?', [
    { korean: '술을', english: 'alcohol' },
    { korean: '자주', english: 'often' },
    { korean: '마셔요?', english: 'do you drink?' },
  ]],
  ['가끔 친구들하고 마셔요.', 'Gakkeum chingudeurhago masyeoyo.', 'I sometimes drink with friends.', [
    { korean: '가끔', english: 'sometimes' },
    { korean: '친구들하고', english: 'with friends' },
    { korean: '마셔요', english: 'I drink' },
  ]],
  ['무슨 술을 좋아해요?', 'Museun sureul joahaeyo?', 'What kind of alcohol do you like?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '술을', english: 'alcohol' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['맥주를 좋아해요.', 'Maekjureul joahaeyo.', 'I like beer.', [
    { korean: '맥주를', english: 'beer' },
    { korean: '좋아해요', english: 'I like' },
  ]],

  // Smoking
  ['담배를 피워요?', 'Dambaereul piwoyo?', 'Do you smoke?', [
    { korean: '담배를', english: 'cigarettes' },
    { korean: '피워요?', english: 'do you smoke?' },
  ]],
  ['아니요, 안 피워요.', 'Aniyo, an piwoyo.', 'No, I don\'t smoke.', [
    { korean: '아니요', english: 'no' },
    { korean: '안 피워요', english: 'I don\'t smoke' },
  ]],

  // Health
  ['건강을 위해 뭐 해요?', 'Geongangeul wihae mwo haeyo?', 'What do you do for your health?', [
    { korean: '건강을 위해', english: 'for health' },
    { korean: '뭐', english: 'what' },
    { korean: '해요?', english: 'do you do?' },
  ]],
  ['운동하고 건강한 음식을 먹어요.', 'Undonghago geongganghan eumsigeul meogeoyo.', 'I exercise and eat healthy food.', [
    { korean: '운동하고', english: 'exercise and' },
    { korean: '건강한 음식을', english: 'healthy food' },
    { korean: '먹어요', english: 'I eat' },
  ]],
  ['병원에 자주 가요?', 'Byeongwone jaju gayo?', 'Do you often go to the hospital?', [
    { korean: '병원에', english: 'to the hospital' },
    { korean: '자주', english: 'often' },
    { korean: '가요?', english: 'do you go?' },
  ]],
  ['아니요, 건강해서 잘 안 가요.', 'Aniyo, geongganghaeseo jal an gayo.', 'No, I am healthy so I don\'t go often.', [
    { korean: '아니요', english: 'no' },
    { korean: '건강해서', english: 'because I\'m healthy' },
    { korean: '잘 안 가요', english: 'I don\'t go often' },
  ]],
  ['약은 잘 먹어요?', 'Yageun jal meogeoyo?', 'Do you take medicine regularly?', [
    { korean: '약은', english: 'medicine' },
    { korean: '잘', english: 'regularly' },
    { korean: '먹어요?', english: 'do you take?' },
  ]],
  ['아니요, 특별히 먹는 약은 없어요.', 'Aniyo, teukbyeolhi meongneun yageun eopseoyo.', 'No, I don\'t take any medicine in particular.', [
    { korean: '아니요', english: 'no' },
    { korean: '특별히', english: 'in particular' },
    { korean: '먹는 약은', english: 'medicine I take' },
    { korean: '없어요', english: 'there is none' },
  ]],
  ['알레르기가 있어요?', 'Allerugiga isseoyo?', 'Do you have allergies?', [
    { korean: '알레르기가', english: 'allergies' },
    { korean: '있어요?', english: 'do you have?' },
  ]],
  ['아니요, 없어요.', 'Aniyo, eopseoyo.', 'No, I don\'t.', [
    { korean: '아니요', english: 'no' },
    { korean: '없어요', english: 'I don\'t have' },
  ]],

  // Sleep quality
  ['잠을 잘 자요?', 'Jameul jal jayo?', 'Do you sleep well?', [
    { korean: '잠을', english: 'sleep' },
    { korean: '잘', english: 'well' },
    { korean: '자요?', english: 'do you sleep?' },
  ]],
  ['네, 보통 잘 자요.', 'Ne, botong jal jayo.', 'Yes, I usually sleep well.', [
    { korean: '네', english: 'yes' },
    { korean: '보통', english: 'usually' },
    { korean: '잘 자요', english: 'I sleep well' },
  ]],
  ['꿈을 자주 꿔요?', 'Kkumeul jaju kkwoyo?', 'Do you often dream?', [
    { korean: '꿈을', english: 'dreams' },
    { korean: '자주', english: 'often' },
    { korean: '꿔요?', english: 'do you dream?' },
  ]],
  ['가끔 꿔요.', 'Gakkeum kkwoyo.', 'I dream sometimes.', [
    { korean: '가끔', english: 'sometimes' },
    { korean: '꿔요', english: 'I dream' },
  ]],
  ['악몽을 꾸는 적 있어요?', 'Angmongeul kkuneun jeok isseoyo?', 'Have you ever had nightmares?', [
    { korean: '악몽을', english: 'nightmares' },
    { korean: '꾸는 적', english: 'ever had' },
    { korean: '있어요?', english: 'have you?' },
  ]],
  ['가끔 있어요.', 'Gakkeum isseoyo.', 'Sometimes I do.', [
    { korean: '가끔', english: 'sometimes' },
    { korean: '있어요', english: 'I do / there is' },
  ]],
  ['아침형 인간이에요, 저녁형 인간이에요?', 'Achimhyeong inganieyo, jeonyeokhyeong inganieyo?', 'Are you a morning person or evening person?', [
    { korean: '아침형 인간이에요', english: 'a morning person' },
    { korean: '저녁형 인간이에요?', english: 'an evening person?' },
  ]],
  ['저녁형 인간이에요.', 'Jeonyeokhyeong inganieyo.', 'I am an evening person.', [
    { korean: '저녁형', english: 'evening type' },
    { korean: '인간이에요', english: 'I am a person' },
  ]],
  ['낮잠을 자요?', 'Natjameul jayo?', 'Do you take naps?', [
    { korean: '낮잠을', english: 'naps' },
    { korean: '자요?', english: 'do you take?' },
  ]],
  ['주말에 가끔 자요.', 'Jumare gakkeum jayo.', 'I sometimes do on weekends.', [
    { korean: '주말에', english: 'on weekends' },
    { korean: '가끔', english: 'sometimes' },
    { korean: '자요', english: 'I sleep' },
  ]],

  // Beverages
  ['커피를 많이 마셔요?', 'Keopireul mani masyeoyo?', 'Do you drink a lot of coffee?', [
    { korean: '커피를', english: 'coffee' },
    { korean: '많이', english: 'a lot' },
    { korean: '마셔요?', english: 'do you drink?' },
  ]],
  ['네, 하루에 두세 잔 마셔요.', 'Ne, harue duse jan masyeoyo.', 'Yes, I drink two or three cups a day.', [
    { korean: '네', english: 'yes' },
    { korean: '하루에', english: 'in a day' },
    { korean: '두세 잔', english: 'two or three cups' },
    { korean: '마셔요', english: 'I drink' },
  ]],
  ['물은 많이 마셔요?', 'Mureun mani masyeoyo?', 'Do you drink a lot of water?', [
    { korean: '물은', english: 'water' },
    { korean: '많이', english: 'a lot' },
    { korean: '마셔요?', english: 'do you drink?' },
  ]],
  ['네, 하루에 2리터 정도 마셔요.', 'Ne, harue 2riteo jeongdo masyeoyo.', 'Yes, I drink about 2 liters a day.', [
    { korean: '네', english: 'yes' },
    { korean: '하루에', english: 'in a day' },
    { korean: '2리터 정도', english: 'about 2 liters' },
    { korean: '마셔요', english: 'I drink' },
  ]],

  // Snacks and diet
  ['간식을 자주 먹어요?', 'Gansigeul jaju meogeoyo?', 'Do you often eat snacks?', [
    { korean: '간식을', english: 'snacks' },
    { korean: '자주', english: 'often' },
    { korean: '먹어요?', english: 'do you eat?' },
  ]],
  ['가끔 먹어요.', 'Gakkeum meogeoyo.', 'I eat them sometimes.', [
    { korean: '가끔', english: 'sometimes' },
    { korean: '먹어요', english: 'I eat' },
  ]],
  ['무슨 간식을 좋아해요?', 'Museun gansigeul joahaeyo?', 'What snacks do you like?', [
    { korean: '무슨', english: 'what kind of' },
    { korean: '간식을', english: 'snacks' },
    { korean: '좋아해요?', english: 'do you like?' },
  ]],
  ['과자를 좋아해요.', 'Gwajareul joahaeyo.', 'I like cookies.', [
    { korean: '과자를', english: 'cookies' },
    { korean: '좋아해요', english: 'I like' },
  ]],
  ['다이어트를 해요?', 'Daieteureul haeyo?', 'Are you on a diet?', [
    { korean: '다이어트를', english: 'diet' },
    { korean: '해요?', english: 'are you doing?' },
  ]],
  ['아니요, 지금은 안 해요.', 'Aniyo, jigeumeun an haeyo.', 'No, I am not right now.', [
    { korean: '아니요', english: 'no' },
    { korean: '지금은', english: 'right now' },
    { korean: '안 해요', english: 'I\'m not doing' },
  ]],
].map(([k, r, e, b]) => createContentItem(k, r, e, 'sentence', k, e, b));

// FOOD - Sentences
const foodSentences = [
  ['배고파요?', 'Baegopayo?', 'Are you hungry?'],
  ['네, 배고파요.', 'Ne, baegopayo.', 'Yes, I am hungry.'],
  ['뭐 먹고 싶어요?', 'Mwo meokgo sipeoyo?', 'What do you want to eat?'],
  ['한식이 먹고 싶어요.', 'Hansigi meokgo sipeoyo.', 'I want to eat Korean food.'],
  ['매운 음식을 먹을 수 있어요?', 'Maeun eumsigul meogeul su isseoyo?', 'Can you eat spicy food?'],
  ['네, 매운 음식을 좋아해요.', 'Ne, maeun eumsigul joahaeyo.', 'Yes, I like spicy food.'],
  ['이 식당은 어때요?', 'I sikdangeun eottaeyo?', 'How about this restaurant?'],
  ['좋아요, 여기서 먹어요.', 'Joayo, yeogiseo meogeoyo.', 'Sounds good, let\'s eat here.'],
  ['메뉴판 좀 주세요.', 'Menyupan jom juseyo.', 'Please give me the menu.'],
  ['여기 있습니다.', 'Yeogi itseumnida.', 'Here you are.'],
  ['주문하시겠어요?', 'Jumunhasi gesseoyo?', 'Are you ready to order?'],
  ['네, 주문할게요.', 'Ne, jumunhalgeyo.', 'Yes, I will order.'],
  ['뭘 주문하시겠어요?', 'Mwol jumunhasi gesseoyo?', 'What would you like to order?'],
  ['비빔밥 하나 주세요.', 'Bibimbap hana juseyo.', 'One bibimbap please.'],
  ['음료수는 뭐 드릴까요?', 'Eumnyosuneun mwo deurilkkayo?', 'What would you like to drink?'],
  ['물 주세요.', 'Mul juseyo.', 'Water please.'],
  ['조금만 기다려 주세요.', 'Jogeumman gidaryeo juseyo.', 'Please wait a moment.'],
  ['네, 천천히 하세요.', 'Ne, cheoncheonhi haseyo.', 'Okay, take your time.'],
  ['여기 나왔습니다.', 'Yeogi nawatseumnida.', 'Here is your food.'],
  ['감사합니다.', 'Gamsahamnida.', 'Thank you.'],
  ['맛있게 드세요.', 'Masitge deuseyo.', 'Enjoy your meal.'],
  ['잘 먹겠습니다.', 'Jal meokgetseumnida.', 'I will eat well (before eating).'],
  ['맛있어요?', 'Masisseoyo?', 'Is it delicious?'],
  ['네, 정말 맛있어요.', 'Ne, jeongmal masisseoyo.', 'Yes, it is really delicious.'],
  ['이거 뭐예요?', 'Igeo mwoyeyo?', 'What is this?'],
  ['이거는 김치찌개예요.', 'Igeoneun gimchi jjigaeyeyo.', 'This is kimchi stew.'],
  ['좀 더 드시겠어요?', 'Jom deo deusigesseaayo?', 'Would you like more?'],
  ['아니요, 배불러요.', 'Aniyo, baebulleoyo.', 'No, I am full.'],
  ['잘 먹었습니다.', 'Jal meogeotseumnida.', 'I ate well (after eating).'],
  ['계산할게요.', 'Gyesanhalgeyo.', 'I will pay.'],
  ['여기서 계산하나요?', 'Yeogiseo gyesanhananayo?', 'Do I pay here?'],
  ['아니요, 저쪽에서 계산하세요.', 'Aniyo, jeojjogeseo gyesanhaseyo.', 'No, please pay over there.'],
  ['얼마예요?', 'Eolmayeyo?', 'How much is it?'],
  ['2만원입니다.', '2manwon imnida.', 'It is 20,000 won.'],
  ['카드로 할게요.', 'Kadeuro halgeyo.', 'I will pay by card.'],
  ['네, 여기 카드 넣으세요.', 'Ne, yeogi kadeu neoeuseyayo.', 'Yes, please insert your card here.'],
  ['영수증 주세요.', 'Yeongseujeung juseyo.', 'Please give me the receipt.'],
  ['여기 있습니다.', 'Yeogi itseumnida.', 'Here you are.'],
  ['포장 가능해요?', 'Pojang ganeunghaeyo?', 'Can I get it to go?'],
  ['네, 포장해 드릴게요.', 'Ne, pojanghae deurilgeyo.', 'Yes, I will pack it for you.'],
  ['배달이 돼요?', 'Baedari dwaeyo?', 'Do you deliver?'],
  ['네, 배달 가능합니다.', 'Ne, baedal ganeunghamnida.', 'Yes, delivery is available.'],
  ['배달 시간이 얼마나 걸려요?', 'Baedal sigani eolmana geollyeoyo?', 'How long does delivery take?'],
  ['30분 정도 걸립니다.', '30bun jeongdo geollimnida.', 'It takes about 30 minutes.'],
  ['예약이 필요해요?', 'Yeyagi pillyohaeyo?', 'Do I need a reservation?'],
  ['주말에는 예약하시는 게 좋아요.', 'Jumareneun yeyakhasineun ge joayo.', 'It is better to make a reservation on weekends.'],
  ['예약하고 싶은데요.', 'Yeyakhago sipeundeyo.', 'I would like to make a reservation.'],
  ['몇 분이세요?', 'Myeot buniseyo?', 'How many people?'],
  ['4명이에요.', '4myeongieyo.', 'There are 4 people.'],
  ['몇 시에 오시겠어요?', 'Myeot sie osigesseayo?', 'What time will you come?'],
  ['7시에 갈게요.', '7sie galgeyo.', 'I will come at 7 o\'clock.'],
  ['성함이 어떻게 되세요?', 'Seonghami eotteoke doeseyo?', 'What is your name?'],
  ['김민수입니다.', 'Kim Minsumnida.', 'It is Kim Minsu.'],
  ['전화번호를 남겨 주세요.', 'Jeonhwa beonhoreul namgyeo juseyo.', 'Please leave your phone number.'],
  ['010-1234-5678이에요.', '010-1234-5678ieyo.', 'It is 010-1234-5678.'],
  ['예약 확인해 드렸습니다.', 'Yeyak hwaginhae deuryeotseumnida.', 'I have confirmed your reservation.'],
  ['감사합니다.', 'Gamsahamnida.', 'Thank you.'],
  ['채식주의자예요?', 'Chaesikjuuijayeyo?', 'Are you a vegetarian?'],
  ['아니요, 다 먹어요.', 'Aniyo, da meogeoyo.', 'No, I eat everything.'],
  ['고기를 안 먹어요?', 'Gogireul an meogeoyo?', 'Don\'t you eat meat?'],
  ['네, 고기는 안 먹어요.', 'Ne, gogineun an meogeoyo.', 'Yes, I don\'t eat meat.'],
  ['알레르기가 있으세요?', 'Allereugiga iseuseyo?', 'Do you have any allergies?'],
  ['땅콩 알레르기가 있어요.', 'Ttangkong allereugiga isseoyo.', 'I have a peanut allergy.'],
  ['이 음식에 땅콩이 들어가요?', 'I eumsige ttangkongi deureogayo?', 'Does this food contain peanuts?'],
  ['아니요, 안 들어가요.', 'Aniyo, an deureogayo.', 'No, it doesn\'t contain peanuts.'],
  ['맵지 않게 해 주세요.', 'Maepji anke hae juseyo.', 'Please make it not spicy.'],
  ['네, 덜 맵게 해 드릴게요.', 'Ne, deol maepge hae deurilgeyo.', 'Yes, I will make it less spicy.'],
  ['싱거워요.', 'Singeowoyo.', 'It is bland.'],
  ['소금 좀 더 넣어 드릴까요?', 'Sogeum jom deo neoeo deurilkkayo?', 'Shall I add more salt?'],
  ['짜요.', 'Jjayo.', 'It is salty.'],
  ['죄송합니다.', 'Joesonghamnida.', 'I am sorry.'],
  ['물 좀 더 주세요.', 'Mul jom deo juseyo.', 'Please give me more water.'],
  ['네, 가져다 드릴게요.', 'Ne, gajyeoda deurilgeyo.', 'Yes, I will bring it to you.'],
  ['반찬 좀 더 주세요.', 'Banchan jom deo juseyo.', 'Please give me more side dishes.'],
  ['여기 있습니다.', 'Yeogi itseumnida.', 'Here you are.'],
  ['숟가락 하나 더 주세요.', 'Sutgarak hana deo juseyo.', 'Please give me one more spoon.'],
  ['네, 바로 가져다 드릴게요.', 'Ne, baro gajyeoda deurilgeyo.', 'Yes, I will bring it right away.'],
  ['휴지 있어요?', 'Hyuji isseoyo?', 'Do you have tissue?'],
  ['여기 휴지 있습니다.', 'Yeogi hyuji itseumnida.', 'Here is tissue.'],
  ['화장실이 어디예요?', 'Hwajangsiri eodiyeyo?', 'Where is the bathroom?'],
  ['저쪽 끝에 있어요.', 'Jeojjok kkeute isseoyo.', 'It is at the end over there.'],
  ['추천 메뉴가 뭐예요?', 'Chucheon menyuga mwoyeyo?', 'What is the recommended menu?'],
  ['삼계탕이 맛있어요.', 'Samgyetangi masisseoyo.', 'Samgyetang is delicious.'],
  ['여기 유명한 음식이 뭐예요?', 'Yeogi yumyeonghan eumsigi mwoyeyo?', 'What is the famous food here?'],
  ['갈비찜이 유명해요.', 'Galbi jjimi yumyeonghaeyo.', 'Galbi-jjim is famous.'],
  ['세트 메뉴가 있어요?', 'Seteu menyuga isseoyo?', 'Do you have a set menu?'],
  ['네, 세트 메뉴 있습니다.', 'Ne, seteu menyu itseumnida.', 'Yes, we have set menus.'],
  ['오늘의 특별 메뉴가 뭐예요?', 'Oneurui teukbyeol menyuga mwoyeyo?', 'What is today\'s special menu?'],
  ['오늘은 불고기가 특별 메뉴예요.', 'Oneureun bulgogiga teukbyeol menyuyeyo.', 'Today\'s special is bulgogi.'],
  ['얼마나 기다려야 해요?', 'Eolmana gidaryeoya haeyo?', 'How long do I have to wait?'],
  ['15분 정도 기다리셔야 해요.', '15bun jeongdo gidarisyeoya haeyo.', 'You have to wait about 15 minutes.'],
  ['테이블이 비어 있어요?', 'Teibeuri bieo isseoyo?', 'Is there an empty table?'],
  ['죄송하지만 지금은 자리가 없어요.', 'Joesonghajiman jigeumeun jariga eopseoyo.', 'I\'m sorry but there are no seats now.'],
  ['대기하면 얼마나 기다려야 해요?', 'Daeghamyeon eolmana gidaryeoya haeyo?', 'If I wait, how long will it take?'],
  ['30분 정도 걸릴 것 같아요.', '30bun jeongdo geollil geot gatayo.', 'It will probably take about 30 minutes.'],
  ['리필 돼요?', 'Ripil dwaeyo?', 'Can I get a refill?'],
  ['네, 무료로 리필 가능해요.', 'Ne, muryoro ripil ganeunghaeyo.', 'Yes, refills are free.'],
  ['이거 주문 안 했는데요.', 'Igeo jumun an haenneundeyo.', 'I didn\'t order this.'],
  ['죄송합니다, 확인해 보겠습니다.', 'Joesonghamnida, hwaginhae bogetseumnida.', 'I\'m sorry, I will check.'],
  ['주문이 잘못 나왔어요.', 'Jumuni jalmot nawasseoyo.', 'The order came out wrong.'],
  ['죄송합니다, 바로 바꿔 드릴게요.', 'Joesonghamnida, baro bakkwo deurilgeyo.', 'I\'m sorry, I will change it right away.'],
  ['너무 오래 기다렸어요.', 'Neomu orae gidaryeosseoyo.', 'I waited too long.'],
  ['정말 죄송합니다.', 'Jeongmal joesonghamnida.', 'I am truly sorry.'],
].map(([k, r, e]) => createContentItem(k, r, e, 'sentence', k, e));

// TRAVEL - Sentences
const travelSentences = [
  ['여기가 어디예요?', 'Yeogiga eodiyeyo?', 'Where is this place?'],
  ['여기는 명동이에요.', 'Yeogineun myeongdongieyo.', 'This is Myeongdong.'],
  ['지하철역이 어디예요?', 'Jihacheol yeogi eodiyeyo?', 'Where is the subway station?'],
  ['저기 보이는 건물 옆에 있어요.', 'Jeogi boineun geonmul yeope isseoyo.', 'It is next to that building you can see.'],
  ['몇 번 출구로 나가야 해요?', 'Myeot beon chulguro nagaya haeyo?', 'Which exit should I take?'],
  ['3번 출구로 나가세요.', '3beon chulguro nagaseyo.', 'Take exit 3.'],
  ['어떻게 가요?', 'Eotteoke gayo?', 'How do I get there?'],
  ['지하철을 타고 가세요.', 'Jihacheoreul tago gaseyo.', 'Take the subway.'],
  ['몇 호선이에요?', 'Myeot hosenieyo?', 'Which line is it?'],
  ['2호선이에요.', '2hosenieyo.', 'It is line 2.'],
  ['어디서 갈아타야 해요?', 'Eodiseo garataya haeyo?', 'Where do I need to transfer?'],
  ['시청역에서 갈아타세요.', 'Sicheong yeokeseo garatasayo.', 'Transfer at City Hall station.'],
  ['몇 정거장이에요?', 'Myeot jeonggeojangieyo?', 'How many stops is it?'],
  ['다섯 정거장이에요.', 'Daseot jeonggeojangieyo.', 'It is five stops.'],
  ['시간이 얼마나 걸려요?', 'Sigani eolmana geollyeoyo?', 'How long does it take?'],
  ['20분 정도 걸려요.', '20bun jeongdo geollyeoyo.', 'It takes about 20 minutes.'],
  ['요금이 얼마예요?', 'Yogeumi eolmayeyo?', 'How much is the fare?'],
  ['1,250원이에요.', '1,250wonieyo.', 'It is 1,250 won.'],
  ['교통카드로 할 수 있어요?', 'Gyotongkadeuro hal su isseoyo?', 'Can I use a transportation card?'],
  ['네, 교통카드 사용 가능해요.', 'Ne, gyotongkadeu sayong ganeunghaeyo.', 'Yes, you can use a transportation card.'],
  ['교통카드는 어디서 살 수 있어요?', 'Gyotongkadeuneun eodiseo sal su isseoyo?', 'Where can I buy a transportation card?'],
  ['편의점에서 살 수 있어요.', 'Pyeonuijeomeseo sal su isseoyo.', 'You can buy it at a convenience store.'],
  ['충전은 어디서 해요?', 'Chungjeuneun eodiseo haeyo?', 'Where do I charge it?'],
  ['지하철역이나 편의점에서 할 수 있어요.', 'Jihacheol yeokina pyeonuijeomeseo hal su isseoyo.', 'You can do it at subway stations or convenience stores.'],
  ['택시를 타고 싶어요.', 'Taeksireul tago sipeoyo.', 'I want to take a taxi.'],
  ['저기 택시 정류장이 있어요.', 'Jeogi taeksi jeongnyujangi isseoyo.', 'There is a taxi stand over there.'],
  ['택시비가 얼마나 나올까요?', 'Taeksibiga eolmana naolkkayo?', 'How much will the taxi fare be?'],
  ['2만원 정도 나올 거예요.', '2manwon jeongdo naol geoyeyo.', 'It will be about 20,000 won.'],
  ['여기서 내려 주세요.', 'Yeogiseo naeryeo juseyo.', 'Please let me off here.'],
  ['네, 알겠습니다.', 'Ne, algetseumnida.', 'Yes, I understand.'],
  ['버스는 몇 번이에요?', 'Beoseuneun myeot beonieyo?', 'Which bus number is it?'],
  ['472번 버스예요.', '472beon beoseuyeyo.', 'It is bus number 472.'],
  ['버스 정류장이 어디예요?', 'Beoseu jeongnyujangi eodiyeyo?', 'Where is the bus stop?'],
  ['저 앞에 있어요.', 'Jeo ape isseoyo.', 'It is up ahead.'],
  ['이 버스 명동 가요?', 'I beoseu myeongdong gayo?', 'Does this bus go to Myeongdong?'],
  ['네, 명동 가요.', 'Ne, myeongdong gayo.', 'Yes, it goes to Myeongdong.'],
  ['여기서 내리면 돼요?', 'Yeogiseo naerimyeon dwaeyo?', 'Should I get off here?'],
  ['아니요, 다음 정류장에서 내리세요.', 'Aniyo, daeum jeongnyujangeyayo naerisayo.', 'No, get off at the next stop.'],
  ['관광지가 어디 있어요?', 'Gwangwangjiga eodi isseoyo?', 'Where are the tourist attractions?'],
  ['경복궁이 유명해요.', 'Gyeongbokgungi yumyeonghaeyo.', 'Gyeongbokgung is famous.'],
  ['입장료가 얼마예요?', 'Ipjangnyoga eolmayeyo?', 'How much is the entrance fee?'],
  ['3,000원이에요.', '3,000wonieyo.', 'It is 3,000 won.'],
  ['개장 시간이 언제예요?', 'Gaejang sigani eonjeyeyo?', 'What time does it open?'],
  ['9시에 열어요.', '9sie yeoreoyo.', 'It opens at 9 o\'clock.'],
  ['폐장 시간이 언제예요?', 'Pyejang sigani eonjeyeyo?', 'What time does it close?'],
  ['6시에 닫아요.', '6sie dadayo.', 'It closes at 6 o\'clock.'],
  ['사진 찍어도 돼요?', 'Sajin jjigeodo dwaeyo?', 'Can I take pictures?'],
  ['네, 사진 찍어도 돼요.', 'Ne, sajin jjigeodo dwaeyo.', 'Yes, you can take pictures.'],
  ['가이드 투어가 있어요?', 'Gaideu tueoga isseoyo?', 'Is there a guided tour?'],
  ['네, 오전 10시에 있어요.', 'Ne, ojeon 10sie isseoyo.', 'Yes, there is one at 10 AM.'],
  ['한국어 가이드만 있어요?', 'Hangugeo gaideunan isseoyo?', 'Is there only a Korean guide?'],
  ['아니요, 영어 가이드도 있어요.', 'Aniyo, yeongeo gaideu do isseoyo.', 'No, there is also an English guide.'],
  ['지도 있어요?', 'Jido isseoyo?', 'Do you have a map?'],
  ['네, 여기 있어요.', 'Ne, yeogi isseoyo.', 'Yes, here it is.'],
  ['화장실이 어디예요?', 'Hwajangsiri eodiyeyo?', 'Where is the bathroom?'],
  ['1층에 있어요.', '1cheunge isseoyo.', 'It is on the first floor.'],
  ['식당이 있어요?', 'Sikdangi isseoyo?', 'Is there a restaurant?'],
  ['2층에 있어요.', '2cheunge isseoyo.', 'It is on the second floor.'],
  ['기념품 가게가 어디예요?', 'Ginyeompum gagega eodiyeyo?', 'Where is the souvenir shop?'],
  ['출구 옆에 있어요.', 'Chulgu yeope isseoyo.', 'It is next to the exit.'],
  ['할인이 있어요?', 'Harini isseoyo?', 'Is there a discount?'],
  ['학생 할인이 있어요.', 'Haksaeng harini isseoyo.', 'There is a student discount.'],
  ['학생증 있으세요?', 'Haksaengjeung iseuseyo?', 'Do you have a student ID?'],
  ['네, 여기 있어요.', 'Ne, yeogi isseoyo.', 'Yes, here it is.'],
  ['단체 할인도 있어요?', 'Danche harindo isseoyo?', 'Is there also a group discount?'],
  ['네, 10명 이상이면 할인돼요.', 'Ne, 10myeong isangimyeon harindwaeyo.', 'Yes, there is a discount for 10 or more people.'],
  ['호텔 추천해 주세요.', 'Hotel chucheonhae juseyo.', 'Please recommend a hotel.'],
  ['명동 근처 호텔이 좋아요.', 'Myeongdong geuncheo hoteli joayo.', 'Hotels near Myeongdong are good.'],
  ['예약했어요.', 'Yeyakhaesseoyo.', 'I made a reservation.'],
  ['예약자 성함이 어떻게 되세요?', 'Yeyakja seonghami eotteoke doeseyo?', 'What is the name on the reservation?'],
  ['김민수예요.', 'Kim Minsuyeyo.', 'It is Kim Minsu.'],
  ['확인됐습니다, 여기 키가 있어요.', 'Hwagindwaetseumnida, yeogi kiga isseoyo.', 'Confirmed. Here is your key.'],
  ['아침 식사가 포함되어 있어요?', 'Achim siksaga pohamdoeeo isseoyo?', 'Is breakfast included?'],
  ['네, 1층 식당에서 7시부터예요.', 'Ne, 1cheung sikdangeseo 7sibuteo yeyo.', 'Yes, it is from 7 AM at the first floor restaurant.'],
  ['체크아웃은 몇 시예요?', 'Chekeuauteun myeot siyeyo?', 'What time is check-out?'],
  ['11시예요.', '11siyeyo.', 'It is 11 o\'clock.'],
  ['짐 맡길 수 있어요?', 'Jim matgil su isseoyo?', 'Can I leave my luggage?'],
  ['네, 여기 맡기세요.', 'Ne, yeogi matgiseyo.', 'Yes, leave it here.'],
  ['와이파이 비밀번호가 뭐예요?', 'Waipai bimilbeonhoga mwoyeyo?', 'What is the WiFi password?'],
  ['여기 적혀 있어요.', 'Yeogi jeokyeo isseoyo.', 'It is written here.'],
  ['방이 너무 춥워요.', 'Bangi neomu chuwoyo.', 'The room is too cold.'],
  ['온도를 올려 드릴게요.', 'Ondoreul ollyeo deurilgeyo.', 'I will raise the temperature.'],
  ['뜨거운 물이 안 나와요.', 'Tteugeoun muri an nawayo.', 'Hot water is not coming out.'],
  ['죄송합니다, 바로 고쳐 드리겠습니다.', 'Joesonghamnida, baro gochyeo deurigetseumnida.', 'I\'m sorry, I will fix it right away.'],
  ['환전은 어디서 해요?', 'Hwanjeuneun eodiseo haeyo?', 'Where do I exchange money?'],
  ['은행이나 환전소에서 하세요.', 'Eunhaengina hwanjeonsoyayo haseyo.', 'Do it at a bank or money exchange.'],
  ['환율이 어떻게 돼요?', 'Hwanyuri eotteoke dwaeyo?', 'What is the exchange rate?'],
  ['오늘은 1달러에 1,200원이에요.', 'Oneureun 1dalleoe 1,200wonieyo.', 'Today it is 1,200 won per dollar.'],
  ['신용카드 쓸 수 있어요?', 'Sinyongkadeu sseul su isseoyo?', 'Can I use a credit card?'],
  ['네, 카드 결제 가능해요.', 'Ne, kadeu gyeolje ganeunghaeyo.', 'Yes, card payment is possible.'],
  ['현금만 받아요?', 'Hyeongeunman badayo?', 'Do you only accept cash?'],
  ['아니요, 카드도 돼요.', 'Aniyo, kadeu do dwaeyo.', 'No, card is okay too.'],
  ['ATM이 어디 있어요?', 'ATMi eodi isseoyo?', 'Where is an ATM?'],
  ['편의점 안에 있어요.', 'Pyeonuijeom ane isseoyo.', 'It is inside the convenience store.'],
  ['영어 할 줄 아세요?', 'Yeongeo hal jul aseyo?', 'Do you speak English?'],
  ['조금 할 줄 알아요.', 'Jogeum hal jul arayo.', 'I speak a little.'],
  ['길을 잃었어요.', 'Gireul ireosseoyo.', 'I am lost.'],
  ['어디로 가시려고 하세요?', 'Eodiro gasiryeogo haseyo?', 'Where are you trying to go?'],
  ['도와주셔서 감사합니다.', 'Dowajusyeoseo gamsahamnida.', 'Thank you for helping.'],
  ['천만에요, 조심히 가세요.', 'Cheonmaneyo, josimhi gaseyo.', 'You\'re welcome, go safely.'],
].map(([k, r, e]) => createContentItem(k, r, e, 'sentence', k, e));

// SHOPPING - Sentences
const shoppingSentences = [
  ['이거 얼마예요?', 'Igeo eolmayeyo?', 'How much is this?'],
  ['3만원이에요.', '3manwonieyo.', 'It is 30,000 won.'],
  ['너무 비싸요.', 'Neomu bissayo.', 'It is too expensive.'],
  ['할인할 수 있어요?', 'Harinhal su isseoyo?', 'Can you give a discount?'],
  ['10% 할인해 드릴게요.', '10% harinhae deurilgeyo.', 'I will give you a 10% discount.'],
  ['다른 색깔 있어요?', 'Dareun saekkal isseoyo?', 'Do you have other colors?'],
  ['네, 빨강색하고 파란색 있어요.', 'Ne, ppalgansaekhago paransaek isseoyo.', 'Yes, we have red and blue.'],
  ['입어 봐도 돼요?', 'Ibeo bwado dwaeyo?', 'Can I try it on?'],
  ['네, 탈의실이 저쪽에 있어요.', 'Ne, taruisiri jeojjoge isseoyo.', 'Yes, the fitting room is over there.'],
  ['사이즈가 안 맞아요.', 'Saijeu ga an majayo.', 'The size doesn\'t fit.'],
  ['큰 사이즈 드릴까요?', 'Keun saijeu deurilkkayo?', 'Shall I give you a larger size?'],
  ['작은 사이즈 있어요?', 'Jageun saijeu isseoyo?', 'Do you have a smaller size?'],
  ['죄송하지만 다 팔렸어요.', 'Joesonghajiman da pallyeosseoyo.', 'I\'m sorry but it is all sold out.'],
  ['이거 살게요.', 'Igeo salgeyo.', 'I will buy this.'],
  ['포장해 드릴까요?', 'Pojanghae deurilkkayo?', 'Shall I wrap it?'],
  ['네, 포장해 주세요.', 'Ne, pojanghae juseyo.', 'Yes, please wrap it.'],
  ['영수증 드릴까요?', 'Yeongseujeung deurilkkayo?', 'Shall I give you a receipt?'],
  ['네, 주세요.', 'Ne, juseyo.', 'Yes, please.'],
  ['교환 가능해요?', 'Gyohwan ganeunghaeyo?', 'Is exchange possible?'],
  ['구매 후 7일 이내면 가능해요.', 'Gumae hu 7il inaemyeon ganeunghaeyo.', 'It is possible within 7 days after purchase.'],
  ['환불 받고 싶어요.', 'Hwanbul batgo sipeoyo.', 'I want a refund.'],
  ['영수증 있으세요?', 'Yeongseujeung iseuseyo?', 'Do you have the receipt?'],
  ['네, 여기 있어요.', 'Ne, yeogi isseoyo.', 'Yes, here it is.'],
  ['무슨 문제가 있으세요?', 'Museun munjega iseuseyo?', 'What is the problem?'],
  ['불량품이에요.', 'Bullyangpumieyo.', 'It is defective.'],
  ['죄송합니다, 바꿔 드릴게요.', 'Joesonghamnida, bakkwo deurilgeyo.', 'I\'m sorry, I will exchange it.'],
  ['환불은 얼마나 걸려요?', 'Hwanbureun eolmana geollyeoyo?', 'How long does the refund take?'],
  ['3-5일 정도 걸려요.', '3-5il jeongdo geollyeoyo.', 'It takes about 3-5 days.'],
  ['세일 중이에요?', 'Seil jungieyo?', 'Is it on sale?'],
  ['네, 지금 50% 할인 중이에요.', 'Ne, jigeum 50% harin jungieyo.', 'Yes, it is currently 50% off.'],
  ['언제까지 세일해요?', 'Eonjekkaji seilhaeyo?', 'Until when is the sale?'],
  ['이번 주말까지예요.', 'Ibeon jumalkkajiyeyo.', 'It is until this weekend.'],
  ['쿠폰 있어요?', 'Kupon isseoyo?', 'Do you have a coupon?'],
  ['네, 여기 쿠폰 쓸 수 있어요.', 'Ne, yeogi kupon sseul su isseoyo.', 'Yes, you can use a coupon here.'],
  ['회원이에요?', 'Hoewoniyeyo?', 'Are you a member?'],
  ['아니요, 회원 가입하고 싶어요.', 'Aniyo, hoewon gaipago sipeoyo.', 'No, I want to become a member.'],
  ['회원 가입하면 혜택이 있어요?', 'Hoewon gaipamyeon hyetaeki isseoyo?', 'Are there benefits for membership?'],
  ['네, 10% 할인 받아요.', 'Ne, 10% harin badayo.', 'Yes, you get a 10% discount.'],
  ['포인트 적립되나요?', 'Pointeu jeokripneuannayo?', 'Do points accumulate?'],
  ['네, 구매 금액의 5% 적립돼요.', 'Ne, gumae geumaeui 5% jeokripttwaeyo.', 'Yes, 5% of the purchase amount is accumulated.'],
  ['포인트 사용할 수 있어요?', 'Pointeu sayonghal su isseoyo?', 'Can I use points?'],
  ['네, 1,000포인트 이상이면 사용 가능해요.', 'Ne, 1,000pointeu isangimyeon sayong ganeunghaeyo.', 'Yes, you can use them if you have more than 1,000 points.'],
  ['카드 할인도 되나요?', 'Kadeu harindo doenayo?', 'Is there also a card discount?'],
  ['특정 카드는 추가 할인돼요.', 'Teukjeong kadeuneun chuga harindwaeyo.', 'Certain cards get an additional discount.'],
  ['무이자 할부 되나요?', 'Muija halbu doenayo?', 'Is there interest-free installment?'],
  ['네, 3개월 무이자 가능해요.', 'Ne, 3gaewol muija ganeunghaeyo.', 'Yes, 3 months interest-free is possible.'],
  ['배송 가능해요?', 'Baesong ganeunghaeyo?', 'Is delivery possible?'],
  ['네, 배송비는 3,000원이에요.', 'Ne, baesongbineun 3,000wonieyo.', 'Yes, the delivery fee is 3,000 won.'],
  ['무료 배송 되나요?', 'Muryo baesong doenayo?', 'Is there free delivery?'],
  ['5만원 이상 구매하시면 무료예요.', '5manwon isang gumaesimyeon muryoyeyo.', 'It is free if you purchase more than 50,000 won.'],
  ['배송 기간이 얼마나 걸려요?', 'Baesong gigani eolmana geollyeoyo?', 'How long is the delivery period?'],
  ['2-3일 정도 걸려요.', '2-3il jeongdo geollyeoyo.', 'It takes about 2-3 days.'],
  ['당일 배송 가능해요?', 'Dangil baesong ganeunghaeyo?', 'Is same-day delivery possible?'],
  ['서울 지역만 가능해요.', 'Seoul jiyeongman ganeunghaeyo.', 'It is only possible in the Seoul area.'],
  ['선물 포장 가능해요?', 'Seonmul pojang ganeunghaeyo?', 'Is gift wrapping possible?'],
  ['네, 2,000원 추가예요.', 'Ne, 2,000won chugayeyo.', 'Yes, it is an additional 2,000 won.'],
  ['메시지 카드 넣을 수 있어요?', 'Mesiji kadeu neoeul su isseoyo?', 'Can you put a message card?'],
  ['네, 뭐라고 쓸까요?', 'Ne, mworago sseulkkayo?', 'Yes, what should I write?'],
  ['생일 축하해요라고 써 주세요.', 'Saengil chukahaeyo rago sseo juseyo.', 'Please write "Happy Birthday".'],
  ['알겠습니다.', 'Algetseumnida.', 'I understand.'],
  ['온라인으로도 살 수 있어요?', 'Onlaneurodo sal su isseoyo?', 'Can I buy it online too?'],
  ['네, 인터넷 쇼핑몰에서 살 수 있어요.', 'Ne, inteonet syopingmoreyayo sal su isseoyo.', 'Yes, you can buy it at the online shopping mall.'],
  ['웹사이트 주소가 뭐예요?', 'Websaiteu jusoga mwoyeyo?', 'What is the website address?'],
  ['여기 카드에 적혀 있어요.', 'Yeogi kadeue jeokyeo isseoyo.', 'It is written on this card.'],
  ['앱이 있어요?', 'Aebi isseoyo?', 'Do you have an app?'],
  ['네, 앱 다운받으면 쿠폰 받아요.', 'Ne, aep daunbadeumyeon kupon badayo.', 'Yes, you get a coupon if you download the app.'],
  ['재입고 언제 돼요?', 'Jaeipgo eonje dwaeyo?', 'When will it be restocked?'],
  ['다음 주 입고 예정이에요.', 'Daeum ju ipgo yejeongyeyo.', 'It is scheduled to arrive next week.'],
  ['입고되면 연락 주실 수 있어요?', 'Ipgodoemyeon yeollak jusil su isseoyo?', 'Can you contact me when it arrives?'],
  ['네, 전화번호 남겨 주세요.', 'Ne, jeonhwa beonho namgyeo juseyo.', 'Yes, please leave your phone number.'],
  ['이거 인기 많아요?', 'Igeo ingi manayo?', 'Is this popular?'],
  ['네, 요즘 많이 팔려요.', 'Ne, yojeum mani pallyeoyo.', 'Yes, it sells a lot these days.'],
  ['후기가 좋아요?', 'Hugiga joayo?', 'Are the reviews good?'],
  ['네, 만족도가 높아요.', 'Ne, manjokdoga nopayo.', 'Yes, the satisfaction is high.'],
  ['품질이 어때요?', 'Pumjiri eottaeyo?', 'How is the quality?'],
  ['품질이 아주 좋아요.', 'Pumjiri aju joayo.', 'The quality is very good.'],
  ['추천해 주시겠어요?', 'Chucheonhae jusigesseaayo?', 'Would you recommend it?'],
  ['네, 강력 추천해요.', 'Ne, gangnyeok chucheonhaeyo.', 'Yes, I highly recommend it.'],
  ['비교해 볼 수 있어요?', 'Bigyohae bol su isseoyo?', 'Can I compare?'],
  ['네, 이거하고 비교해 보세요.', 'Ne, igeohago bigyohae boseyo.', 'Yes, compare it with this.'],
  ['차이가 뭐예요?', 'Chaiga mwoyeyo?', 'What is the difference?'],
  ['이거는 더 가볍고 저거는 더 튼튼해요.', 'Igeoneun deo gabyeopgo jeogeneun deo teunteunhaeyo.', 'This one is lighter and that one is sturdier.'],
  ['어느 게 더 나아요?', 'Eoneu ge deo naayo?', 'Which one is better?'],
  ['용도에 따라 다르지만 이거를 추천해요.', 'Yongdoe ttara dareu jiman igeoreul chucheonhaeyo.', 'It depends on the purpose, but I recommend this one.'],
  ['가격 차이는 얼마예요?', 'Gagyeok chaineun eolmayeyo?', 'How much is the price difference?'],
  ['1만원 차이예요.', '1manwon chaiyeyo.', 'It is a 10,000 won difference.'],
  ['고민되네요.', 'Gomindoeneyo.', 'I am not sure.'],
  ['천천히 생각하세요.', 'Cheoncheonhi saenggakaseyo.', 'Take your time to think.'],
  ['나중에 다시 올게요.', 'Najunge dasi olgeyo.', 'I will come back later.'],
  ['네, 언제든지 오세요.', 'Ne, eonjedeuji oseyo.', 'Yes, come anytime.'],
].map(([k, r, e]) => createContentItem(k, r, e, 'sentence', k, e));

// BUSINESS - Sentences
const businessSentences = [
  ['회의가 몇 시에 있어요?', 'Hoeiga myeot sie isseoyo?', 'What time is the meeting?'],
  ['오전 10시에 있어요.', 'Ojeon 10sie isseoyo.', 'It is at 10 AM.'],
  ['회의실이 어디예요?', 'Hoeuisiri eodiyeyo?', 'Where is the meeting room?'],
  ['3층 회의실이에요.', '3cheung hoeuisiriyeyo.', 'It is the meeting room on the 3rd floor.'],
  ['회의 자료 준비했어요?', 'Hoeui jaryo junbihaesseoyo?', 'Did you prepare the meeting materials?'],
  ['네, 다 준비했어요.', 'Ne, da junbihaesseoyo.', 'Yes, I prepared everything.'],
  ['프레젠테이션 잘 부탁해요.', 'Peurejenteieyeon jal butakhaeyo.', 'Please do well with the presentation.'],
  ['최선을 다하겠습니다.', 'Choeseuneul dahagetseumnida.', 'I will do my best.'],
  ['보고서는 언제까지 제출해야 해요?', 'Bogoseoneun eonjekkaji jechulhaeya haeyo?', 'When do I have to submit the report?'],
  ['금요일까지 제출하세요.', 'Geumyoilkkaji jechulhaseyo.', 'Please submit it by Friday.'],
  ['마감 시간을 연장할 수 있어요?', 'Magam siganeul yeonjanghal su isseoyo?', 'Can you extend the deadline?'],
  ['이번만 월요일까지 주세요.', 'Ibeonman wolyoilkkaji juseyo.', 'Just this time, I will give you until Monday.'],
  ['출장 가야 해요?', 'Chuljang gaya haeyo?', 'Do I have to go on a business trip?'],
  ['네, 다음 주에 부산 출장이 있어요.', 'Ne, daeum jue busan chuljangi isseoyo.', 'Yes, there is a business trip to Busan next week.'],
  ['며칠 동안이에요?', 'Myeochil donganiyo?', 'For how many days?'],
  ['2박 3일이에요.', '2bak 3irieyo.', 'It is 2 nights and 3 days.'],
  ['출장비는 어떻게 청구해요?', 'Chuljangbineun eotteoke cheonguhaeyo?', 'How do I claim the business trip expenses?'],
  ['영수증 모아서 제출하세요.', 'Yeongseujeung moaseo jechulhaseyo.', 'Collect the receipts and submit them.'],
  ['연차 쓰고 싶어요.', 'Yeoncha sseugo sipeoyo.', 'I want to use vacation days.'],
  ['언제 쓰실 거예요?', 'Eonje sseusil geoyeyo?', 'When will you use them?'],
  ['다음 주 금요일이요.', 'Daeum ju geumyoiriyo.', 'Next Friday.'],
  ['승인했습니다.', 'Seunginhaetseumnida.', 'It has been approved.'],
  ['조퇴해도 될까요?', 'Jotoehae do doelkkayo?', 'May I leave early?'],
  ['무슨 일 있으세요?', 'Museun il iseuseyo?', 'Is something wrong?'],
  ['병원에 가야 해요.', 'Byeongwone gaya haeyo.', 'I have to go to the hospital.'],
  ['네, 다녀오세요.', 'Ne, danyeooseyo.', 'Yes, go ahead.'],
  ['야근해야 해요?', 'Yageunhaeya haeyo?', 'Do I have to work overtime?'],
  ['이번 주는 야근 많을 거예요.', 'Ibeon juneun yaheun maneul geoyeyo.', 'There will be a lot of overtime this week.'],
  ['초과 근무 수당 받아요?', 'Chogwa geunmu sudang badayo?', 'Do I get overtime pay?'],
  ['네, 급여에 포함돼요.', 'Ne, geubyeo e pohamdwaeyo.', 'Yes, it is included in the salary.'],
  ['회식이 언제예요?', 'Hoesigi eonjeyeyo?', 'When is the company dinner?'],
  ['이번 주 금요일이에요.', 'Ibeon ju geumyoirieyo.', 'It is this Friday.'],
  ['참석해야 해요?', 'Chamseokhaeya haeyo?', 'Do I have to attend?'],
  ['가능하면 참석해 주세요.', 'Ganeunghamyeon chamseokae juseyo.', 'Please attend if possible.'],
  ['이메일 확인했어요?', 'Imeir hwakinhaesseoyo?', 'Did you check the email?'],
  ['네, 확인했어요.', 'Ne, hwakinhaesseoyo.', 'Yes, I checked it.'],
  ['답장 보냈어요?', 'Dapjang bonaesseoyo?', 'Did you send a reply?'],
  ['아직 안 보냈어요.', 'Ajik an bonaesseoyo.', 'I haven\'t sent it yet.'],
  ['빨리 답장 보내세요.', 'Ppalli dapjang bonaeseyo.', 'Please send a reply quickly.'],
  ['지금 바로 보낼게요.', 'Jigeum baro bonaelgeyo.', 'I will send it right now.'],
  ['전화 좀 받아 주세요.', 'Jeonhwa jom bada juseyo.', 'Please answer the phone.'],
  ['지금 통화 중이에요.', 'Jigeum tonghwa jungieyo.', 'I am on a call now.'],
  ['메시지 남겨 드릴까요?', 'Mesiji namgyeo deurilkkayo?', 'Shall I leave a message?'],
  ['네, 전화 달라고 전해 주세요.', 'Ne, jeonhwa dallago jeonhae juseyo.', 'Yes, please tell them to call back.'],
  ['팩스 보냈어요?', 'Paekseu bonaesseoyo?', 'Did you send the fax?'],
  ['네, 방금 보냈어요.', 'Ne, banggeum bonaesseoyo.', 'Yes, I just sent it.'],
  ['복사 좀 해 주세요.', 'Boksa jom hae juseyo.', 'Please make some copies.'],
  ['몇 부 필요하세요?', 'Myeot bu pillyohaseyo?', 'How many copies do you need?'],
  ['10부 부탁해요.', '10bu butakhaeyo.', 'Please make 10 copies.'],
  ['컬러로 할까요?', 'Keolleoro halkkayo?', 'Should I do it in color?'],
  ['아니요, 흑백으로 하세요.', 'Aniyo, heukbaekuro haseyo.', 'No, do it in black and white.'],
  ['프린터가 고장 났어요.', 'Peurinteoga gojang nasseoyo.', 'The printer is broken.'],
  ['수리 요청했어요?', 'Suri yocheonghaesseoyo?', 'Did you request a repair?'],
  ['네, 기사님이 오실 거예요.', 'Ne, gisanimi osil geoyeyo.', 'Yes, the technician will come.'],
  ['컴퓨터가 안 켜져요.', 'Keompyuteoga an kyeojyeoyo.', 'The computer won\'t turn on.'],
  ['IT팀에 연락하세요.', 'IT time yeollakhaseyo.', 'Contact the IT team.'],
  ['인터넷이 느려요.', 'Inteonesi neuryeoyo.', 'The internet is slow.'],
  ['다시 접속해 보세요.', 'Dasi jeopsok ae boseyo.', 'Try connecting again.'],
  ['파일이 안 열려요.', 'Pairi an yeollyeoyo.', 'The file won\'t open.'],
  ['다른 프로그램으로 열어 보세요.', 'Dareun peurogeuraemuro yeoreo boseyo.', 'Try opening it with another program.'],
  ['백업했어요?', 'Baekeophaesseoyo?', 'Did you back it up?'],
  ['아직 안 했어요.', 'Ajik an haesseoyo.', 'I haven\'t done it yet.'],
  ['자주 백업하세요.', 'Jaju baekeopaseyo.', 'Back up frequently.'],
  ['비밀번호를 잊어버렸어요.', 'Bimilbeonhoreul ijeobeolyeosseoyo.', 'I forgot the password.'],
  ['재설정하세요.', 'Jaeseoljeonghaseyo.', 'Reset it.'],
  ['신입 사원이 들어왔어요.', 'Sinip sawoni deureowasseoyo.', 'A new employee joined.'],
  ['잘 부탁드립니다.', 'Jal butakdeurimnida.', 'I look forward to working with you.'],
  ['교육은 언제 받아요?', 'Gyoyugeun eonje badayo?', 'When do I receive training?'],
  ['다음 주부터 시작해요.', 'Daeum jubuteo sijakaeyo.', 'It starts from next week.'],
  ['멘토가 누구예요?', 'Mentoga nuguyeyo?', 'Who is the mentor?'],
  ['김 과장님이에요.', 'Kim gwajangnimieyo.', 'It is Manager Kim.'],
  ['업무 인수인계 받았어요?', 'Eopmu insuingye badasseoyo?', 'Did you receive the work handover?'],
  ['네, 다 받았어요.', 'Ne, da badasseoyo.', 'Yes, I received everything.'],
  ['퇴사하신다고요?', 'Toesahasindagoyo?', 'Are you resigning?'],
  ['네, 다음 달에 퇴사해요.', 'Ne, daeum dare toesahaeyo.', 'Yes, I am resigning next month.'],
  ['새 직장 구하셨어요?', 'Sae jikjang guhasleosseoyo?', 'Did you find a new job?'],
  ['네, 더 좋은 기회를 얻었어요.', 'Ne, deo joeun gihoereul eodeosseoyo.', 'Yes, I got a better opportunity.'],
  ['승진 축하해요.', 'Seungjin chukahaeyo.', 'Congratulations on the promotion.'],
  ['감사합니다.', 'Gamsahamnida.', 'Thank you.'],
  ['계약서에 서명했어요?', 'Gyeyakseoe seomyeonghaesseoyo?', 'Did you sign the contract?'],
  ['네, 서명하고 제출했어요.', 'Ne, seomyeonghago jechulhaesseoyo.', 'Yes, I signed and submitted it.'],
  ['급여일이 언제예요?', 'Geubyeoiri eonjeyeyo?', 'When is payday?'],
  ['매월 25일이에요.', 'Maewol 25irieyo.', 'It is the 25th of every month.'],
  ['상여금 받았어요?', 'Sangyeogeum badasseoyo?', 'Did you receive a bonus?'],
  ['네, 이번 달에 받았어요.', 'Ne, ibeon dare badasseoyo.', 'Yes, I received it this month.'],
  ['복지 혜택이 뭐가 있어요?', 'Bokji hyetaegi mwoga isseoyo?', 'What benefits are there?'],
  ['식비 지원하고 건강검진 있어요.', 'Sikbi jiwonhago geonganggeomjin isseoyo.', 'There is meal support and health checkups.'],
  ['점심 식사 어디서 해요?', 'Jeomsim siksa eodiseo haeyo?', 'Where do you have lunch?'],
  ['구내식당에서 먹어요.', 'Gunae sikdangeseo meogeoyo.', 'I eat at the company cafeteria.'],
  ['같이 점심 먹을래요?', 'Gachi jeomsim meogeullaeyo?', 'Do you want to have lunch together?'],
  ['좋아요, 같이 가요.', 'Joayo, gachi gayo.', 'Sounds good, let\'s go together.'],
].map(([k, r, e]) => createContentItem(k, r, e, 'sentence', k, e));

// HEALTHCARE - Sentences
const healthcareSentences = [
  ['어디가 아파요?', 'Eodiga apayo?', 'Where does it hurt?'],
  ['머리가 아파요.', 'Meoriga apayo.', 'My head hurts.'],
  ['언제부터 아팠어요?', 'Eonjebuteo apasseoyo?', 'Since when has it been hurting?'],
  ['어제부터 아팠어요.', 'Eojebuteo apasseoyo.', 'It has been hurting since yesterday.'],
  ['열이 나요?', 'Yeori nayo?', 'Do you have a fever?'],
  ['네, 열이 조금 나요.', 'Ne, yeori jogeum nayo.', 'Yes, I have a slight fever.'],
  ['체온이 몇 도예요?', 'Cheoni myeot doyeyo?', 'What is your temperature?'],
  ['38도예요.', '38doyeyo.', 'It is 38 degrees.'],
  ['기침이 나요?', 'Gichimi nayo?', 'Do you have a cough?'],
  ['네, 기침이 심해요.', 'Ne, gichimi simhaeyo.', 'Yes, my cough is severe.'],
  ['가래가 나와요?', 'Garaega nawayo?', 'Is there phlegm?'],
  ['네, 노란 가래가 나와요.', 'Ne, noran garaega nawayo.', 'Yes, there is yellow phlegm.'],
  ['목이 아파요?', 'Mogi apayo?', 'Does your throat hurt?'],
  ['네, 목이 많이 아파요.', 'Ne, mogi mani apayo.', 'Yes, my throat hurts a lot.'],
  ['콧물이 나요?', 'Kkonmuri nayo?', 'Do you have a runny nose?'],
  ['네, 계속 나와요.', 'Ne, gyesok nawayo?', 'Yes, it keeps running.'],
  ['코가 막혔어요?', 'Koga makeoasseoyo?', 'Is your nose stuffy?'],
  ['네, 숨쉬기 힘들어요.', 'Ne, sumswigi himdeureoyo.', 'Yes, it is hard to breathe.'],
  ['배가 아파요?', 'Baega apayo?', 'Does your stomach hurt?'],
  ['네, 배가 많이 아파요.', 'Ne, baega mani apayo.', 'Yes, my stomach hurts a lot.'],
  ['설사를 해요?', 'Seolsareul haeyo?', 'Do you have diarrhea?'],
  ['네, 하루에 여러 번 해요.', 'Ne, harue yeoreo beon haeyo.', 'Yes, several times a day.'],
  ['구토했어요?', 'Gutohaesseoyo?', 'Did you vomit?'],
  ['네, 아침에 한 번 했어요.', 'Ne, achime han beon haesseoyo.', 'Yes, I did once in the morning.'],
  ['식욕이 있어요?', 'Sigyogi isseoyo?', 'Do you have an appetite?'],
  ['아니요, 먹고 싶지 않아요.', 'Aniyo, meokgo sipji anayo.', 'No, I don\'t want to eat.'],
  ['어지러워요?', 'Eojireowowo?', 'Are you dizzy?'],
  ['네, 가끔 어지러워요.', 'Ne, gakkeum eojireowowo.', 'Yes, I am sometimes dizzy.'],
  ['잠을 잘 자요?', 'Jameul jal jayo?', 'Do you sleep well?'],
  ['아니요, 잠을 잘 못 자요.', 'Aniyo, jameul jal mot jayo.', 'No, I don\'t sleep well.'],
  ['스트레스 받아요?', 'Seuteureseu badayo?', 'Are you stressed?'],
  ['네, 요즘 스트레스가 많아요.', 'Ne, yojeum seuteureseuga manayo.', 'Yes, I have a lot of stress these days.'],
  ['운동은 하세요?', 'Undongeun haseyo?', 'Do you exercise?'],
  ['아니요, 요즘 못 하고 있어요.', 'Aniyo, yojeum mot hago isseoyo.', 'No, I haven\'t been able to lately.'],
  ['담배 피우세요?', 'Dambae piuseyo?', 'Do you smoke?'],
  ['아니요, 안 피워요.', 'Aniyo, an piwoyo.', 'No, I don\'t smoke.'],
  ['술 자주 마시세요?', 'Sul jaju masiseyo?', 'Do you drink alcohol often?'],
  ['가끔 마셔요.', 'Gakkeum masyeoyo.', 'I drink occasionally.'],
  ['알레르기가 있으세요?', 'Allereugiga iseuseyo?', 'Do you have allergies?'],
  ['아니요, 없어요.', 'Aniyo, eopseoyo.', 'No, I don\'t.'],
  ['복용 중인 약이 있어요?', 'Bogyong jungin yagi isseoyo?', 'Are you taking any medication?'],
  ['네, 혈압약을 먹어요.', 'Ne, hyeorabyageul meogeoyo.', 'Yes, I take blood pressure medicine.'],
  ['가족 중에 당뇨병 환자 있어요?', 'Gajok junge dangyobyeong hwanja isseoyo?', 'Is there anyone with diabetes in your family?'],
  ['네, 아버지가 당뇨병이에요.', 'Ne, abeojiga dangyobyeongieyo.', 'Yes, my father has diabetes.'],
  ['검사를 받아야 해요.', 'Geomsareul badaya haeyo.', 'You need to get tested.'],
  ['무슨 검사를 해야 해요?', 'Museun geomsareul haeya haeyo?', 'What test do I need to take?'],
  ['혈액 검사하고 소변 검사 해요.', 'Hyeoraek geomsahago sobyeon geomsa haeyo.', 'Blood test and urine test.'],
  ['검사 결과는 언제 나와요?', 'Geomsa gyeolgwaneun eonje nawayo?', 'When will the test results be ready?'],
  ['3일 후에 나와요.', '3il hue nawayo.', 'They will be ready in 3 days.'],
  ['엑스레이를 찍어야 해요.', 'Ekseu reireul jjigeoya haeyo.', 'You need to get an X-ray.'],
  ['어디를 찍어요?', 'Eodireul jjigeoyo?', 'Where do you take it?'],
  ['가슴을 찍어요.', 'Gaseumeul jjigeoyo.', 'We take it of your chest.'],
  ['CT 촬영이 필요해요.', 'CT chwalyeongi pillyohaeyo.', 'A CT scan is needed.'],
  ['비용이 얼마예요?', 'Biyongi eolmayeyo?', 'How much does it cost?'],
  ['보험 적용되면 2만원이에요.', 'Boheom jeok yongdoemyeon 2manwonieyo.', 'With insurance, it is 20,000 won.'],
  ['처방전 받았어요?', 'Cheobangjeon badasseoyo?', 'Did you get a prescription?'],
  ['네, 여기 있어요.', 'Ne, yeogi isseoyo.', 'Yes, here it is.'],
  ['약은 어디서 받아요?', 'Yageun eodiseo badayo?', 'Where do I get the medicine?'],
  ['1층 약국에서 받으세요.', '1cheung yakgugeseo badeuseyo.', 'Get it at the pharmacy on the first floor.'],
  ['하루에 몇 번 먹어요?', 'Harue myeot beon meogeoyo?', 'How many times a day do I take it?'],
  ['하루 세 번, 식후에 드세요.', 'Haru se beon, sikhu e deuseyo.', 'Three times a day, after meals.'],
  ['부작용이 있어요?', 'Bujagyongi isseoyo?', 'Are there side effects?'],
  ['졸릴 수 있어요.', 'Jollil su isseoyo.', 'You may feel drowsy.'],
  ['술과 같이 먹으면 안 돼요?', 'Sulgwa gachi meokeumyeon an dwaeyo?', 'Can I not take it with alcohol?'],
  ['네, 술은 피하세요.', 'Ne, sureun pihaseyo.', 'Yes, avoid alcohol.'],
  ['며칠 동안 먹어야 해요?', 'Myeochil dongan meogeoya haeyo?', 'For how many days should I take it?'],
  ['일주일 동안 드세요.', 'Iljuil dongan deuseyo.', 'Take it for one week.'],
  ['약 다 먹고도 안 나으면요?', 'Yak da meokgodo an naeumyeonyo?', 'What if I don\'t get better after finishing the medicine?'],
  ['다시 오세요.', 'Dasi oseyo.', 'Come back again.'],
  ['재진 예약할까요?', 'Jaejin yeyakhalkkayo?', 'Shall I make a follow-up appointment?'],
  ['네, 다음 주에 예약해 주세요.', 'Ne, daeum jue yeyak ae juseyo.', 'Yes, please make an appointment for next week.'],
  ['입원해야 해요?', 'Ibwonhaeya haeyo?', 'Do I need to be hospitalized?'],
  ['아니요, 통원 치료로 괜찮아요.', 'Aniyo, tongwon chiryoro gwaenchanhayo.', 'No, outpatient treatment is fine.'],
  ['수술이 필요해요?', 'Susuri pillyohaeyo?', 'Is surgery needed?'],
  ['네, 수술하는 게 좋겠어요.', 'Ne, susulhaneun ge joesseoyo.', 'Yes, it would be good to have surgery.'],
  ['수술 비용이 얼마예요?', 'Susul biyongi eolmayeyo?', 'How much does the surgery cost?'],
  ['보험 적용되면 50만원이에요.', 'Boheom jeogyongdoemyeon 50manwonieyo.', 'With insurance, it is 500,000 won.'],
  ['회복 기간이 얼마나 걸려요?', 'Hoebook gigani eolmana geollyeoyo?', 'How long is the recovery period?'],
  ['2주 정도 걸려요.', '2ju jeongdo geollyeoyo.', 'It takes about 2 weeks.'],
  ['퇴원은 언제 할 수 있어요?', 'Toegwoneun eonje hal su isseoyo?', 'When can I be discharged?'],
  ['모레 퇴원 가능해요.', 'More toegwon ganeunghaeyo.', 'You can be discharged the day after tomorrow.'],
  ['물리 치료 받아야 해요?', 'Mulli chiryo badaya haeyo?', 'Do I need physical therapy?'],
  ['네, 주 2회 받으세요.', 'Ne, ju 2hoe badeuseyo.', 'Yes, receive it twice a week.'],
  ['예약했는데 취소하고 싶어요.', 'Yeyakhaenneunde chwisohago sipeoyo.', 'I made an appointment but want to cancel.'],
  ['전화로 취소하시면 돼요.', 'Jeonhwaro chwisohasimyeon dwaeyo.', 'You can cancel by phone.'],
  ['진료비가 얼마예요?', 'Jillyobiga eolmayeyo?', 'How much is the medical fee?'],
  ['5만원입니다.', '5manwon imnida.', 'It is 50,000 won.'],
  ['보험 되나요?', 'Boheom doenayo?', 'Is it covered by insurance?'],
  ['네, 보험 적용 가능해요.', 'Ne, boheom jeokyong ganeunghaeyo.', 'Yes, insurance coverage is possible.'],
  ['건강검진 받고 싶어요.', 'Geongganggeomjin batgo sipeoyo.', 'I want to get a health checkup.'],
  ['예약하시겠어요?', 'Yeyakhasigesseayo?', 'Would you like to make an appointment?'],
  ['네, 가능한 날짜 알려 주세요.', 'Ne, ganeunghan naljja allyeo juseyo.', 'Yes, please tell me the available dates.'],
  ['다음 주 월요일 어때요?', 'Daeum ju wolyoil eottaeyo?', 'How about next Monday?'],
  ['좋아요, 그날로 예약할게요.', 'Joayo, geunallo yeyakhalgeyo.', 'Sounds good, I will make an appointment for that day.'],
].map(([k, r, e]) => createContentItem(k, r, e, 'sentence', k, e));

module.exports = {
  greetingsSentences,
  dailyLifeSentences,
  foodSentences,
  travelSentences,
  shoppingSentences,
  businessSentences,
  healthcareSentences
};
