// Level 1 Unit 2 — Classroom & Asking Questions (Turkish)
// Functions: asking about classroom objects, the "var/yok" existence pattern,
// expressing possession through possessive suffixes, numbers 1-20,
// pluralization, and locative -de/-da for "in/at" the classroom.

const createContentItem = (
  target,
  pronunciation,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization: pronunciation,
  nativeText: note,
  pronunciation,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'tr-l1u2-orientation',
  pronunciation: 'tr-l1u2-pronunciation',
  vocabularyObjects: 'tr-l1u2-vocab-objects',
  vocabularyNumbers: 'tr-l1u2-vocab-numbers',
  grammarVarYok: 'tr-l1u2-grammar-var-yok',
  grammarLocative: 'tr-l1u2-grammar-locative',
  grammarPlural: 'tr-l1u2-grammar-plural',
  reading: 'tr-l1u2-reading',
  listening: 'tr-l1u2-listening',
  writing: 'tr-l1u2-writing',
  culture: 'tr-l1u2-culture',
  task: 'tr-l1u2-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Name 20 classroom objects (kitap, kalem, defter, tahta, sıra…) and ask "what is this?" / "what is that?" using bu / şu / o.',
      'State whether something exists or not using the var/yok existential pattern — Turkish\'s replacement for "there is / there is not".',
      'Apply the locative case -de/-da/-te/-ta to say where something is: "Kitap masada." (The book is on the table.)',
    ],
    task: 'Picture your first day in a Boğaziçi classroom — point to objects, ask the instructor what they are called, and learn to say where each one is.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in classroom vocabulary',
    goals: [
      'Pronounce "öğretmen" (öy-RET-men) with the ğ acting as a y-glide and final-syllable stress — a common classroom word.',
      'Apply the d→t assimilation rule audibly: "kitap-ta" (NOT kitap-da), "sınıf-ta" (NOT sınıf-da) — voiceless final consonants demand the t-form.',
      'Distinguish "var" (vahr, tapped r) from "var-mı?" (the question), keeping the tap on the r even before the question particle.',
    ],
    task: 'Read 10 classroom sentences applying d→t assimilation and the ğ-glide where needed.',
  },
  {
    id: ACT.vocabularyObjects,
    section: 'Vocabulary I',
    title: 'Classroom objects',
    goals: [
      'Memorize 20 classroom-related nouns: kitap, kalem, defter, tahta, masa, sandalye, sınıf, çanta, silgi, cetvel, sıra, kalemtraş…',
      'Recognize how each noun pluralizes (kitap → kitaplar; defter → defterler) by the back/front vowel of the final syllable.',
    ],
    task: 'Walk through a classroom and name every object you see, then pluralize each name correctly.',
  },
  {
    id: ACT.vocabularyNumbers,
    section: 'Vocabulary II',
    title: 'Numbers 1–20',
    goals: [
      'Count from 1 to 20 in Turkish: bir, iki, üç, dört, beş, altı, yedi, sekiz, dokuz, on, on bir, on iki, … yirmi.',
      'Use a number directly before a NOUN without making the noun plural: "üç kitap" (three book, NOT "üç kitaplar"). This is a hard-and-fast Turkish rule.',
    ],
    task: 'Count classroom objects: "Kaç tane kitap var?" — "Beş tane kitap var." — practice with five different objects.',
  },
  {
    id: ACT.grammarVarYok,
    section: 'Grammar I',
    title: 'The var / yok existence pattern',
    goals: [
      'Use "var" (exists / there is) and "yok" (does not exist / there is not) — the Turkish replacement for "there is / there is not". Comes at the END of the sentence.',
      'Form yes/no questions with "var mı?" / "yok mu?" — the question particle still obeys harmony but is invariant in word order.',
      'Express ownership with the same pattern: "Benim kitabım var" (literally "my book exists" = "I have a book").',
    ],
    task: 'Write five sentences using var/yok for both "there is/not" and "I have/don\'t have" meanings.',
  },
  {
    id: ACT.grammarLocative,
    section: 'Grammar II',
    title: 'The locative case — -de / -da / -te / -ta',
    goals: [
      'Apply the locative suffix -de/-da (after voiced/vowel) or -te/-ta (after voiceless) to express "in/at/on": evde (at home), masada (on the table), sınıfta (in class).',
      'Distinguish locative -de (in/at) from ablative -den (from) — two related but distinct cases, both following the same harmony.',
    ],
    task: 'Combine 8 nouns with the locative suffix and identify which ones trigger d→t assimilation.',
  },
  {
    id: ACT.grammarPlural,
    section: 'Grammar III',
    title: 'The plural suffix -ler / -lar',
    goals: [
      'Apply the two-form plural -ler (after front vowels) / -lar (after back vowels): defterler, kitaplar, öğretmenler, sıralar.',
      'Know that the plural is dropped after a numeral (üç kitap, not üç kitaplar) AND in generic statements (Kitap güzel. = Books are good.).',
    ],
    task: 'Pluralize 12 nouns and identify the three cases where Turkish drops the plural.',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Describe a classroom',
    goals: [
      'Read a short paragraph describing a Boğaziçi classroom and identify every var/yok pattern and locative case.',
      'Answer four comprehension questions about object counts, locations, and what is absent.',
    ],
    task: 'Read aloud, then answer the four questions in complete sentences.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'A student asks the teacher',
    goals: [
      'Follow a 4-turn dialogue between a student and a teacher about missing classroom objects ("Silgi yok mu?").',
      'Reproduce the dialogue with different objects swapped in (cetvel, kalem, kitap, tahta silgisi).',
    ],
    task: 'Practice the dialogue twice — once reading, once with substitutions.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Describe your study space',
    goals: [
      'Write 4–6 sentences describing your study space using var/yok and locative.',
      'Use at least 3 numbers, 2 plurals, and 2 var/yok statements.',
    ],
    task: 'Write your own description following the template.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'The Turkish classroom: hoca culture and the Atatürk portrait',
    goals: [
      'Recognize the deep respect students show their hoca — standing up when the teacher enters, using siz, and never interrupting.',
      'Know that every Turkish classroom features the Turkish flag and an Atatürk portrait by law (Law No. 2429).',
      'Understand that Turkish primary classrooms recite "Andımız" (Our Oath) at the start of each week — a patriotic ritual reformed in 2013 but still part of cultural memory.',
    ],
    task: 'Decide how you would politely address (1) your hoca in class, (2) a fellow öğrenci, (3) the school principal (müdür).',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'Classroom inventory at Boğaziçi',
    goals: [
      'Walk through a virtual Boğaziçi classroom with the AI tutor and identify, count, and locate every object using var/yok and locative.',
      'Use the proper register (siz) when addressing the AI-tutor-as-teacher.',
    ],
    task: 'Run an 8-turn classroom inventory dialogue with the AI tutor playing the öğretim üyesi.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 2: Sınıfta — Classroom and Asking Questions',
  category: 'classroom',
  difficulty: 'beginner',
  targetLang: 'tr',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'naming-objects', label: 'Naming classroom objects', goal: 'Point and ask "Bu ne?" then answer with the correct noun.' },
    { id: 'asking-existence', label: 'Asking if something exists', goal: 'Use "X var mı?" / "Yok mu?" to check availability.' },
    { id: 'stating-location', label: 'Stating location', goal: 'Use locative -de/-da/-te/-ta to say where things are.' },
    { id: 'counting-objects', label: 'Counting objects', goal: 'Use a number + singular noun + var to count.' },
  ],
  relatedPools: ['topic-classroom', 'topic-numbers'],
  content: [
    createContentItem('sınıf', 'sı-NIF', 'Classroom; also "grade" (1. sınıf = 1st grade). Back-unrounded root → takes -ta locative (sınıfta, voiceless final f). Plural: sınıflar.', 'word', 'Sınıfta yirmi öğrenci var.', '"There are 20 students in the class" — using locative and var.', null, [ACT.vocabularyObjects]),
    createContentItem('kitap', 'ki-TAP', 'Book. Back-unrounded vowels but irregular: kitap ends in voiceless p, so kitapta (LOC), but softens to b before vowel-initial: kitabı (ACC). Most common classroom noun.', 'word', 'Bu kitap çok güzel.', '"This book is very nice." — bu (this) demonstrative.', null, [ACT.vocabularyObjects]),
    createContentItem('kalem', 'ka-LEM', 'Pen / pencil — a single word covers both. Borrowed from Arabic. Front-unrounded last vowel → -ler plural, -de locative: kalemler, kalemde.', 'word', 'Kalemin nerede?', '"Where is your pen?" — kalem + -in (your) + nerede (where).', null, [ACT.vocabularyObjects]),
    createContentItem('defter', 'def-TER', 'Notebook. Front-unrounded → -ler plural (defterler). Common classroom noun, often paired with kalem.', 'word', 'Defter ve kalem getir.', '"Bring notebook and pen" — ve (and) is the universal conjunction.', null, [ACT.vocabularyObjects]),
    createContentItem('masa', 'ma-SA', 'Table, desk. Vowel-final root → buffer y before vowel suffixes: masayı (ACC), masaya (DAT). Back-unrounded harmony.', 'word', 'Kitap masada.', '"The book is on the table." — locative -da.', null, [ACT.vocabularyObjects]),
    createContentItem('sandalye', 'san-dal-YE', 'Chair. Back vowels until final -ye, but the last vowel is front "e" → -ler plural (sandalyeler). The "y" is part of the root, not a buffer.', 'word', 'Sandalyeye oturun lütfen.', '"Sit on the chair please" — sandalye + DAT -ye (with buffer).', null, [ACT.vocabularyObjects]),
    createContentItem('tahta', 'tah-TA', 'Blackboard / whiteboard. Back-unrounded → -da locative... but root ends in voiceless t? No — root ends in vowel a, so locative is -da (no assimilation). Plural: tahtalar.', 'word', 'Öğretmen tahtaya yazıyor.', '"The teacher is writing on the board." — tahtaya = tahta + DAT -ya (back buffer).', null, [ACT.vocabularyObjects]),
    createContentItem('çanta', 'chan-TA', 'Bag / backpack. Back-unrounded → -da locative (no assim because final a). Common compound: okul çantası (school bag).', 'word', 'Çantamda kitap var.', '"There is a book in my bag." — çanta + -m (my) + -da (in) + kitap var.', null, [ACT.vocabularyObjects]),
    createContentItem('silgi', 'sil-Gİ', 'Eraser. Front vowels → -i ACC, -de LOC. Word formation: sil- (to wipe) + -gi (instrument suffix).', 'word', 'Silgin var mı?', '"Do you have an eraser?" — silgi + -n (your) + var + mı.', null, [ACT.vocabularyObjects]),
    createContentItem('cetvel', 'jet-VEL', 'Ruler. Note c is pronounced "j" (jet, not "set"). Front vowel → -ler plural, -de LOC.', 'word', 'Cetveli alabilir miyim?', '"Can I take the ruler?" — using ability -ebil-/-abil-.', null, [ACT.vocabularyObjects]),
    createContentItem('sıra', 'sı-RA', 'School desk / row. Back-unrounded → -da locative, -lar plural. Common in primary classrooms (rows of paired desks).', 'word', 'Birinci sırada oturuyorum.', '"I sit in the first row." — birinci (first) + sırada (in the row).', null, [ACT.vocabularyObjects]),
    createContentItem('kalemtraş', 'ka-lem-TRASH', 'Pencil sharpener. Persian-origin compound (kalem + traş). Often shortened in fast speech.', 'word', 'Kalemtraş kullanabilir miyim?', '"May I use the sharpener?"', null, [ACT.vocabularyObjects]),
    createContentItem('öğretmen', 'öy-RET-men', 'Teacher (primary/secondary). Front-unrounded → -ler plural. Address form "öğretmenim" (my teacher).', 'word', 'Öğretmen sınıfa geldi.', '"The teacher came to the class." — sınıfa (DAT, into the class).', null, [ACT.vocabularyObjects]),
    createContentItem('öğrenci', 'öy-REN-ji', 'Student. Vowel-final root → buffer y before vowel suffixes. Plural öğrenciler.', 'word', 'Öğrenciler kütüphanede.', '"The students are at the library." — kütüphane (library) + LOC.', null, [ACT.vocabularyObjects]),
    createContentItem('tahta silgisi', 'tah-TA sil-gi-Sİ', 'Board eraser (the felt block for the blackboard). Compound noun using izafet: tahta (board) + silgi (eraser) + -si (3rd person possessive).', 'word', 'Tahta silgisi kayıp.', '"The board eraser is lost/missing."', null, [ACT.vocabularyObjects]),
    createContentItem('proje', 'pro-JE', 'Project. j here is the zh-sound (French). Common in modern classrooms.', 'word', 'Bu proje çok ilginç.', '"This project is very interesting." — ilginç (interesting).', null, [ACT.vocabularyObjects]),
    createContentItem('soru', 'so-RU', 'Question. Back-rounded → -lar plural, -da LOC, -yu ACC (with buffer).', 'word', 'Sorum var, hocam.', '"I have a question, teacher."', null, [ACT.vocabularyObjects]),
    createContentItem('cevap', 'je-VAP', 'Answer. c = j. Back-unrounded → -ları plural with possessive, p softens to b before vowel: cevabı (the answer, ACC).', 'word', 'Cevap doğru.', '"The answer is correct." — doğru with ğ-lengthening.', null, [ACT.vocabularyObjects]),
    createContentItem('ders', 'DERS', 'Lesson / class period. Front-unrounded → -ler plural (dersler). Schedule item — every class is a ders.', 'word', 'Bugün üç dersim var.', '"I have three classes today." — üç + ders (no plural after number) + im (my) + var.', null, [ACT.vocabularyObjects]),
    createContentItem('üniversite', 'ü-ni-ver-si-TE', 'University. Front-unrounded → -ler plural. Boğaziçi Üniversitesi is the flagship Istanbul institution.', 'word', 'Boğaziçi Üniversitesi\'nde öğrenciyim.', '"I am a student at Boğaziçi University."', null, [ACT.vocabularyObjects]),

    // Numbers 1-20
    createContentItem('bir', 'BİR', 'One. Also functions as the indefinite article "a/an": bir kitap (a book). High-frequency.', 'word', 'Bir kitap var.', '"There is a book / one book."', null, [ACT.vocabularyNumbers]),
    createContentItem('iki', 'i-Kİ', 'Two. Front-unrounded.', 'word', 'İki kalem.', '"Two pens" — number + singular noun (NEVER plural after number).', null, [ACT.vocabularyNumbers]),
    createContentItem('üç', 'ÜCH', 'Three. Front-rounded (ü). End-ç voiceless triggers assimilation: üçte (at three o\'clock).', 'word', 'Üç öğrenci.', '"Three students" — never üç öğrenciler.', null, [ACT.vocabularyNumbers]),
    createContentItem('dört', 'DÖRT', 'Four. Front-rounded with ö + voiceless t (assimilation trigger). One of the most frequent numbers.', 'word', 'Saat dört.', '"It is four o\'clock."', null, [ACT.vocabularyNumbers]),
    createContentItem('beş', 'BESH', 'Five. Front-unrounded. Voiceless ş final.', 'word', 'Beş defter.', '"Five notebooks" — number + singular.', null, [ACT.vocabularyNumbers]),
    createContentItem('altı', 'al-TI', 'Six. Back-unrounded (a then ı).', 'word', 'Altı saat çalıştım.', '"I studied for six hours."', null, [ACT.vocabularyNumbers]),
    createContentItem('yedi', 'ye-Dİ', 'Seven. Front-unrounded.', 'word', 'Yedi gün.', '"Seven days" — referring to a week.', null, [ACT.vocabularyNumbers]),
    createContentItem('sekiz', 'se-KİZ', 'Eight. Front-unrounded.', 'word', 'Sekiz dakika kaldı.', '"Eight minutes left."', null, [ACT.vocabularyNumbers]),
    createContentItem('dokuz', 'do-KUZ', 'Nine. Back-rounded (o + u).', 'word', 'Dokuz numara.', '"Number nine."', null, [ACT.vocabularyNumbers]),
    createContentItem('on', 'ON', 'Ten. Single syllable, back-rounded. Used as a building block: on bir (11), on iki (12), on üç (13)…', 'word', 'On dakika.', '"Ten minutes."', null, [ACT.vocabularyNumbers]),
    createContentItem('on bir', 'on BİR', 'Eleven. Compound: on (10) + bir (1). Written as two words.', 'word', 'On bir yaşındayım.', '"I am 11 years old."', null, [ACT.vocabularyNumbers]),
    createContentItem('on iki', 'on i-Kİ', 'Twelve. on + iki.', 'word', 'On iki ay var.', '"There are 12 months."', null, [ACT.vocabularyNumbers]),
    createContentItem('yirmi', 'yir-Mİ', 'Twenty. Front-unrounded. Building block for 20s: yirmi bir (21), yirmi iki (22)…', 'word', 'Yirmi kişi var.', '"There are 20 people."', null, [ACT.vocabularyNumbers]),

    // var / yok
    createContentItem(
      'var',
      'VAR',
      'Existential particle "there is / exists". Comes at the END of the sentence. Same word for "I have" when combined with a possessive: "Benim kitabım var" = "my book exists" = "I have a book".',
      'sentence',
      'Sınıfta tahta var. (There is a board in the class.)\nBenim kalemim var. (I have a pen.)',
      'No equivalent of English "to have" verb — Turkish uses var + possessive.',
      [
        { target: 'X var (existence)', note: '"There is X" — sınıfta öğrenci var' },
        { target: 'Possessive + var (possession)', note: '"X has Y" — benim arabam var ("I have a car")' },
      ],
      [ACT.grammarVarYok],
    ),
    createContentItem(
      'yok',
      'YOK',
      'Negative existential "there is not / does not exist". Mirror of var. "Yok" by itself can also be a casual "no" or "nope".',
      'sentence',
      'Sınıfta silgi yok. (There is no eraser in the class.)\nBenim arabam yok. (I don\'t have a car.)',
      'Compact and high-frequency; "yok" alone is a common one-word answer.',
      null,
      [ACT.grammarVarYok],
    ),
    createContentItem(
      'var mı? / yok mu?',
      'var mı? / yok mu?',
      'Question forms — add the harmony-matched -mı/-mu particle after var/yok. "Silgi var mı?" (Is there an eraser?) — typically answered "Var" or "Yok".',
      'sentence',
      '— Silgi var mı? — Var. / Yok.\n— Kalemin var mı? — Evet, var.',
      'Common conversational shortcut: respond with just "Var" or "Yok" rather than full sentence.',
      null,
      [ACT.grammarVarYok],
    ),
    createContentItem(
      'Sahiplik kalıbı',
      'possession pattern',
      'The "I have X" pattern: [POSSESSOR-GEN] [NOUN-POSS] var/yok. "Benim kitabım var" = "My book exists" = "I have a book". The possessor genitive (benim, senin) is often dropped because the possessive suffix already marks it.',
      'sentence',
      'Benim kitabım var. (I have a book.)\nKitabım var. (Same meaning, more natural.)\nSenin kalemin yok mu? (Don\'t you have a pen?)',
      'Drop "benim/senin" unless emphasizing whose; the possessive suffix carries the meaning.',
      [
        { target: 'X-(I)m var', note: 'I have X — kitabım var, kalemim var' },
        { target: 'X-(I)n var', note: 'you (sg) have X — kitabın var, kalemin var' },
        { target: 'X-(s)I var', note: 'he/she has X — kitabı var, kalemi var' },
      ],
      [ACT.grammarVarYok],
    ),

    // Locative
    createContentItem(
      'Lokatif -de / -da',
      'locative -de / -da',
      'The locative case marks "in/at/on". Two basic forms by big harmony: -de (after front vowels), -da (after back vowels). Plus the assimilated -te/-ta after voiceless consonants.',
      'sentence',
      'evde (at home), masada (on the table), sınıfta (in class), kitapta (in the book)',
      'Locative is one of the most frequently used cases; second only to accusative.',
      [
        { target: '-de (front, voiced)', note: 'evde, gözde, üniversitede' },
        { target: '-da (back, voiced)', note: 'masada, odada, arabada' },
        { target: '-te (front, voiceless)', note: 'cepte (in the pocket), gözükte? (no — gözde), sınıfta is back' },
        { target: '-ta (back, voiceless)', note: 'kitapta, sokakta, ağaçta' },
      ],
      [ACT.grammarLocative],
    ),
    createContentItem(
      'Lokatif soruları',
      'locative questions',
      'Form "where" questions with "nerede": "Kitap nerede?" (Where is the book?). Answer with locative + noun: "Masada." (On the table.).',
      'sentence',
      '— Kalemin nerede? — Çantamda.\n— Boğaziçi Üniversitesi nerede? — İstanbul\'da.',
      'Nerede itself is locative: ner-e (where) + -de (in/at).',
      null,
      [ACT.grammarLocative],
    ),
    createContentItem(
      'Apostrof + özel isim',
      'apostrophe + proper noun',
      'Proper nouns (place names, brand names) take case suffixes attached with an APOSTROPHE: İstanbul\'da (in Istanbul), Türkiye\'de (in Turkey), Boğaziçi\'nde (at Boğaziçi).',
      'sentence',
      'İstanbul\'da yaşıyorum. (I live in Istanbul.)\nTürkiye\'ye gidiyorum. (I am going to Turkey.)',
      'Apostrophe separates the noun from the suffix — improves readability for proper nouns.',
      null,
      [ACT.grammarLocative],
    ),

    // Plural
    createContentItem(
      'Çoğul eki -ler / -lar',
      'plural suffix -ler / -lar',
      'Two-form plural: -ler after front vowels, -lar after back vowels. The most basic harmony pattern.',
      'sentence',
      'kitap → kitaplar, kalem → kalemler, defter → defterler, masa → masalar, çocuk → çocuklar, öğrenci → öğrenciler',
      'Mechanical: just check the last vowel of the root.',
      null,
      [ACT.grammarPlural],
    ),
    createContentItem(
      'Sayı + tekil',
      'number + singular',
      'IMPORTANT: After a numeral, the noun stays SINGULAR. "Üç kitap" (three book), NOT "üç kitaplar". This is a strict Turkish rule that English speakers regularly violate.',
      'sentence',
      'CORRECT: üç kitap, beş öğrenci, on kalem.\nWRONG: üç kitaplar, beş öğrenciler, on kalemler.',
      'A learner-error magnet; drill until automatic.',
      null,
      [ACT.grammarPlural],
    ),
    createContentItem(
      'Genel çoğul yok',
      'no generic plural',
      'For generic statements, Turkish typically uses SINGULAR rather than English-style plural: "Kitap güzeldir." (Books are nice.). Plural would change the meaning to "specific books".',
      'sentence',
      'GENERIC: Kitap güzeldir. (Books are nice.)\nSPECIFIC: Kitaplar masada. (The books are on the table.)',
      'A subtle but pervasive difference; learn to spot when English plural maps to Turkish singular.',
      null,
      [ACT.grammarPlural],
    ),

    // Reading
    createContentItem(
      'Boğaziçi sınıfı',
      'a Boğaziçi classroom',
      'A short paragraph describing a classroom at Boğaziçi.',
      'paragraph',
      'Bu sınıf büyük. Sınıfta yirmi öğrenci ve bir öğretmen var. Tahta ön tarafta, sıralar da düzenli. Her sırada iki öğrenci oturuyor. Benim sıramda kitabım, defterim ve kalemim var. Silgi yok ama arkadaşımın silgisi var. Pencereden Boğaz görünüyor — manzara harika.',
      'Translation: "This classroom is big. There are 20 students and one teacher in the class. The board is in the front, the desks are arranged. Two students sit at each desk. On my desk I have my book, my notebook, and my pen. There is no eraser but my friend has one. The Bosphorus is visible from the window — the view is wonderful."',
      [
        { target: 'sınıfta var', note: 'locative + existential; the basic "there is X in Y" frame' },
        { target: 'her sırada', note: '"at each desk"; her = every, sırada = LOC of sıra' },
        { target: 'arkadaşımın silgisi var', note: 'compound noun (izafet) with genitive + possessive: my-friend-of eraser-his exists = my friend has an eraser' },
        { target: 'Boğaz', note: 'the Bosphorus strait — the central feature of the Boğaziçi campus view' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'Sorular',
      'questions',
      'Comprehension questions about the paragraph.',
      'sentence',
      'Q1: Sınıfta kaç öğrenci var? Q2: Tahta nerede? Q3: Senin sıranda ne var? Q4: Silgi var mı?',
      'Practice with var/yok and locative.',
      [
        { target: 'A1: Yirmi öğrenci var.', note: 'number + singular noun + var' },
        { target: 'A2: Ön tarafta.', note: 'locative answer with -ta' },
        { target: 'A3: Kitabım, defterim, kalemim var.', note: 'list of possessions with var' },
        { target: 'A4: Hayır, yok.', note: 'short negative answer' },
      ],
      [ACT.reading],
    ),

    // Listening
    createContentItem(
      'Sınıfta diyalog',
      'classroom dialogue',
      'A short dialogue between a student and a teacher about classroom objects.',
      'conversation',
      'Öğrenci: Hocam, silgi var mı?\nÖğretmen: Sırada bak, silgi orada.\nÖğrenci: Sırada silgi yok hocam.\nÖğretmen: O zaman çantanda olabilir.\nÖğrenci: Ah, çantamda buldum, teşekkür ederim.\nÖğretmen: Rica ederim. Şimdi dersimize devam edelim.',
      'A realistic teacher-student exchange using all this unit\'s grammar.',
      [
        { target: 'silgi var mı', note: 'classic var-question' },
        { target: 'sırada', note: 'LOC of sıra' },
        { target: 'çantanda', note: 'çanta + -n (your) + -da (in)' },
        { target: 'devam edelim', note: '"let\'s continue" — verb + 1pl optative' },
      ],
      [ACT.listening],
    ),

    // Writing
    createContentItem(
      'Çalışma alanım',
      'my study space',
      'A template paragraph for describing your own study space.',
      'sentence',
      'Şablon: Benim çalışma alanım [konum]. Masada [n tane nesne] var. [Bir nesne] yok. Genelde burada [bir aktivite] yapıyorum.',
      'Fill in the four slots with your own details.',
      [
        { target: '[konum]', note: 'where: evde, kütüphanede, ofiste' },
        { target: '[n tane nesne] var', note: 'list of what is there with quantities' },
        { target: '[Bir nesne] yok', note: 'one thing that is missing' },
        { target: '[bir aktivite]', note: 'activity: ders çalışıyorum, kitap okuyorum' },
      ],
      [ACT.writing],
    ),

    // Culture
    createContentItem(
      'hoca kültürü',
      'hoca culture',
      'In Turkish education, the hoca holds high authority. Students traditionally stand when the teacher enters, use siz, and never interrupt. Calling a teacher by first name is unthinkable in primary/secondary school.',
      'sentence',
      'Hocam, izin verir misiniz? (Teacher, may I have permission?)',
      'Even in university, "hocam" remains the warmest and most respectful student-to-professor address — far more common than "Profesör".',
      [
        { target: 'standing when teacher enters', note: 'traditional but still observed in many schools' },
        { target: 'siz to hoca', note: 'always; never sen' },
        { target: 'hocam, hocacığım', note: 'warmer diminutive forms' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Atatürk portresi',
      'Atatürk portrait',
      'By Turkish law (Law No. 2429), every classroom must display the Turkish flag, an Atatürk portrait, and Atatürk\'s "Gençliğe Hitabe" (Address to the Youth) and "İstiklal Marşı" (Independence March) on the wall.',
      'sentence',
      'Sınıfın ön duvarında Türk bayrağı ve Atatürk portresi var.',
      'Universal across Turkish public schools, military bases, government offices, and many private institutions.',
      null,
      [ACT.culture],
    ),
    createContentItem(
      'Andımız',
      'Andımız (Our Oath)',
      'A patriotic oath recited Monday mornings in Turkish primary schools, beginning "Türk\'üm, doğruyum, çalışkanım" (I am Turkish, I am righteous, I am hardworking). Removed from the curriculum in 2013, reinstated controversially in 2018, and dropped again in 2021. Politically charged.',
      'sentence',
      'Türk\'üm, doğruyum, çalışkanım.',
      'A line of cultural memory rather than current practice — but politically loaded; avoid in first-meeting small talk.',
      null,
      [ACT.culture],
    ),

    // Task
    createContentItem(
      'Görev: sınıf envanteri',
      'task: classroom inventory',
      'Run an 8-turn inventory dialogue with the AI tutor playing the öğretim üyesi (faculty member). Identify, count, and locate objects.',
      'conversation',
      'Hoca: [object1] var mı?\nSen: [evet/hayır] + count + location\nHoca: Peki [object2]?\nSen: ...\n(8 turns total)',
      'Use var/yok, locative, numbers, and singular-after-number across all 8 turns.',
      null,
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
