const createContentItem = (targetText, romanization, nativeText, type = 'word', exampleTarget = '', exampleNative = '', breakdown = null) => ({
  type,
  targetText,
  romanization,
  nativeText,
  pronunciation: romanization,
  exampleTarget: exampleTarget || targetText,
  exampleNative: exampleNative || nativeText,
  korean: targetText,
  english: nativeText,
  example: exampleTarget || targetText,
  exampleEnglish: exampleNative || nativeText,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean || b.target, native: b.english || b.native, korean: b.korean || b.target, english: b.english || b.native })) } : {}),
});

// ==================== GREETINGS ====================
const greetings = {
  title: 'Basic Greetings & Introductions',
  category: 'greetings',
  difficulty: 'beginner',
  targetLang: 'tr',
  content: [
    createContentItem('Merhaba', '', 'Hello', 'word', 'Merhaba, nasılsınız?', 'Hello, how are you?'),
    createContentItem('Günaydın', '', 'Good morning', 'word', 'Günaydın, iyi uykular mı?', 'Good morning, did you sleep well?'),
    createContentItem('İyi akşamlar', '', 'Good evening', 'word', 'İyi akşamlar, hoş geldiniz.', 'Good evening, welcome.'),
    createContentItem('İyi geceler', '', 'Good night', 'word', 'İyi geceler, yarın görüşürüz.', 'Good night, see you tomorrow.'),
    createContentItem('Hoş geldiniz', '', 'Welcome', 'word', 'Hoş geldiniz, buyurun oturun.', 'Welcome, please have a seat.'),
    createContentItem('Hoş bulduk', '', 'Glad to be here (response to welcome)', 'word', 'Hoş bulduk, teşekkür ederim.', 'Glad to be here, thank you.'),
    createContentItem('Nasılsınız?', '', 'How are you? (formal)', 'word', 'Merhaba, nasılsınız?', 'Hello, how are you?'),
    createContentItem('Nasılsın?', '', 'How are you? (informal)', 'word', 'Selam, nasılsın?', 'Hi, how are you?'),
    createContentItem('İyiyim, teşekkürler', '', 'I am fine, thanks', 'sentence', 'İyiyim, teşekkürler. Siz nasılsınız?', 'I am fine, thanks. How are you?', [
      { target: 'İyiyim', native: 'I am fine' },
      { target: 'teşekkürler', native: 'thanks' },
    ]),
    createContentItem('Benim adım...', '', 'My name is...', 'sentence', 'Benim adım Ali, tanıştığıma memnun oldum.', 'My name is Ali, nice to meet you.', [
      { target: 'Benim', native: 'My' },
      { target: 'adım', native: 'name is' },
    ]),
    createContentItem('Tanıştığıma memnun oldum', '', 'Nice to meet you', 'sentence', 'Tanıştığıma memnun oldum, ben Ayşe.', 'Nice to meet you, I am Ayse.', [
      { target: 'Tanıştığıma', native: 'to have met' },
      { target: 'memnun oldum', native: 'I am pleased' },
    ]),
    createContentItem('Selam', '', 'Hi (informal)', 'word', 'Selam, ne yapıyorsun?', 'Hi, what are you doing?'),
    createContentItem('Güle güle', '', 'Goodbye (said by the one staying)', 'word', 'Güle güle, yine bekleriz.', 'Goodbye, we hope to see you again.'),
    createContentItem('Hoşça kal', '', 'Goodbye (said by the one leaving)', 'word', 'Hoşça kal, görüşürüz.', 'Goodbye, see you later.'),
    createContentItem('Görüşürüz', '', 'See you later', 'word', 'Yarın görüşürüz.', 'See you tomorrow.'),
    createContentItem('Teşekkür ederim', '', 'Thank you', 'word', 'Yardımınız için teşekkür ederim.', 'Thank you for your help.'),
    createContentItem('Rica ederim', '', 'You are welcome', 'word', 'Rica ederim, önemli değil.', 'You are welcome, no problem.'),
    createContentItem('Lütfen', '', 'Please', 'word', 'Lütfen burada oturun.', 'Please sit here.'),
    createContentItem('Özür dilerim', '', 'I am sorry', 'word', 'Özür dilerim, geç kaldım.', 'I am sorry, I am late.'),
    createContentItem('Affedersiniz', '', 'Excuse me', 'word', 'Affedersiniz, saat kaç?', 'Excuse me, what time is it?'),
    createContentItem('Evet', '', 'Yes', 'word', 'Evet, anlıyorum.', 'Yes, I understand.'),
    createContentItem('Hayır', '', 'No', 'word', 'Hayır, teşekkürler.', 'No, thank you.'),
    createContentItem('Nerelisiniz?', '', 'Where are you from? (formal)', 'sentence', 'Nerelisiniz? Ben İstanbul\'dayım.', 'Where are you from? I am from Istanbul.', [
      { target: 'Nereli', native: 'From where' },
      { target: 'siniz', native: 'are you (formal)' },
    ]),
    createContentItem('Türkçe bilmiyorum', '', 'I do not speak Turkish', 'sentence', 'Özür dilerim, Türkçe bilmiyorum.', 'I am sorry, I do not speak Turkish.', [
      { target: 'Türkçe', native: 'Turkish' },
      { target: 'bilmiyorum', native: 'I do not know' },
    ]),
    createContentItem('İngilizce biliyor musunuz?', '', 'Do you speak English?', 'sentence', 'Affedersiniz, İngilizce biliyor musunuz?', 'Excuse me, do you speak English?', [
      { target: 'İngilizce', native: 'English' },
      { target: 'biliyor musunuz', native: 'do you know (formal)' },
    ]),
  ],
};

// ==================== DAILY LIFE ====================
const dailyLife = {
  title: 'Everyday Life & Activities',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'tr',
  content: [
    createContentItem('Ev', '', 'House / Home', 'word', 'Evimiz çok büyük.', 'Our house is very big.'),
    createContentItem('Aile', '', 'Family', 'word', 'Ailem İstanbul\'da yaşıyor.', 'My family lives in Istanbul.'),
    createContentItem('Anne', '', 'Mother', 'word', 'Annem çok iyi yemek yapar.', 'My mother cooks very well.'),
    createContentItem('Baba', '', 'Father', 'word', 'Babam öğretmen.', 'My father is a teacher.'),
    createContentItem('Kardeş', '', 'Sibling', 'word', 'İki kardeşim var.', 'I have two siblings.'),
    createContentItem('Arkadaş', '', 'Friend', 'word', 'En iyi arkadaşım Mehmet.', 'My best friend is Mehmet.'),
    createContentItem('Okul', '', 'School', 'word', 'Okul saat sekizde başlıyor.', 'School starts at eight.'),
    createContentItem('İş', '', 'Work / Job', 'word', 'İşe otobüsle gidiyorum.', 'I go to work by bus.'),
    createContentItem('Sabah', '', 'Morning', 'word', 'Her sabah kahve içerim.', 'I drink coffee every morning.'),
    createContentItem('Akşam', '', 'Evening', 'word', 'Akşam yemeği saat yedide.', 'Dinner is at seven.'),
    createContentItem('Gece', '', 'Night', 'word', 'Gece erken yatıyorum.', 'I go to bed early at night.'),
    createContentItem('Bugün', '', 'Today', 'word', 'Bugün hava çok güzel.', 'The weather is very nice today.'),
    createContentItem('Yarın', '', 'Tomorrow', 'word', 'Yarın tatil.', 'Tomorrow is a holiday.'),
    createContentItem('Dün', '', 'Yesterday', 'word', 'Dün sinemaya gittim.', 'I went to the cinema yesterday.'),
    createContentItem('Saat kaç?', '', 'What time is it?', 'sentence', 'Affedersiniz, saat kaç?', 'Excuse me, what time is it?', [
      { target: 'Saat', native: 'Hour / Clock' },
      { target: 'kaç', native: 'how many / what' },
    ]),
    createContentItem('Her gün işe gidiyorum', '', 'I go to work every day', 'sentence', 'Her gün işe otobüsle gidiyorum.', 'I go to work by bus every day.', [
      { target: 'Her gün', native: 'Every day' },
      { target: 'işe', native: 'to work' },
      { target: 'gidiyorum', native: 'I go' },
    ]),
    createContentItem('Su', '', 'Water', 'word', 'Bir bardak su lütfen.', 'A glass of water please.'),
    createContentItem('Yemek', '', 'Food / Meal', 'word', 'Yemek hazır mı?', 'Is the food ready?'),
    createContentItem('Uyumak', '', 'To sleep', 'word', 'Erken uyumak istiyorum.', 'I want to sleep early.'),
    createContentItem('Kalkmak', '', 'To get up', 'word', 'Sabah erken kalkıyorum.', 'I get up early in the morning.'),
    createContentItem('Telefon', '', 'Phone', 'word', 'Telefonum nerede?', 'Where is my phone?'),
    createContentItem('Hava nasıl?', '', 'How is the weather?', 'sentence', 'Bugün hava nasıl?', 'How is the weather today?', [
      { target: 'Hava', native: 'Weather' },
      { target: 'nasıl', native: 'how' },
    ]),
    createContentItem('Yağmur yağıyor', '', 'It is raining', 'sentence', 'Dışarıda yağmur yağıyor.', 'It is raining outside.', [
      { target: 'Yağmur', native: 'Rain' },
      { target: 'yağıyor', native: 'is falling / raining' },
    ]),
    createContentItem('Güneş', '', 'Sun', 'word', 'Güneş çok sıcak.', 'The sun is very hot.'),
    createContentItem('Araba', '', 'Car', 'word', 'Arabam beyaz.', 'My car is white.'),
  ],
};

// ==================== FOOD ====================
const food = {
  title: 'Food, Drinks & Dining',
  category: 'food',
  difficulty: 'beginner',
  targetLang: 'tr',
  content: [
    createContentItem('Ekmek', '', 'Bread', 'word', 'Taze ekmek aldım.', 'I bought fresh bread.'),
    createContentItem('Su', '', 'Water', 'word', 'Soğuk su istiyorum.', 'I want cold water.'),
    createContentItem('Çay', '', 'Tea', 'word', 'Bir bardak çay lütfen.', 'A glass of tea please.'),
    createContentItem('Kahve', '', 'Coffee', 'word', 'Türk kahvesi çok lezzetli.', 'Turkish coffee is very delicious.'),
    createContentItem('Süt', '', 'Milk', 'word', 'Her sabah süt içerim.', 'I drink milk every morning.'),
    createContentItem('Peynir', '', 'Cheese', 'word', 'Beyaz peynir severim.', 'I like white cheese.'),
    createContentItem('Yumurta', '', 'Egg', 'word', 'Kahvaltıda yumurta yiyorum.', 'I eat eggs for breakfast.'),
    createContentItem('Et', '', 'Meat', 'word', 'Bu et çok taze.', 'This meat is very fresh.'),
    createContentItem('Tavuk', '', 'Chicken', 'word', 'Tavuk çorbası yapıyorum.', 'I am making chicken soup.'),
    createContentItem('Balık', '', 'Fish', 'word', 'Akşam balık yiyelim.', 'Let us eat fish tonight.'),
    createContentItem('Sebze', '', 'Vegetable', 'word', 'Taze sebze aldım.', 'I bought fresh vegetables.'),
    createContentItem('Meyve', '', 'Fruit', 'word', 'Bu meyveler çok tatlı.', 'These fruits are very sweet.'),
    createContentItem('Pilav', '', 'Rice', 'word', 'Pilav çok güzel olmuş.', 'The rice turned out very nice.'),
    createContentItem('Çorba', '', 'Soup', 'word', 'Mercimek çorbası istiyorum.', 'I want lentil soup.'),
    createContentItem('Salata', '', 'Salad', 'word', 'Çoban salatası lütfen.', 'Shepherd salad please.'),
    createContentItem('Tatlı', '', 'Dessert / Sweet', 'word', 'Baklava çok tatlı.', 'Baklava is very sweet.'),
    createContentItem('Hesap lütfen', '', 'Check please', 'sentence', 'Hesap lütfen, ayrı ayrı ödeyeceğiz.', 'Check please, we will pay separately.', [
      { target: 'Hesap', native: 'Bill / Check' },
      { target: 'lütfen', native: 'please' },
    ]),
    createContentItem('Afiyet olsun', '', 'Bon appetit / Enjoy your meal', 'word', 'Buyurun, afiyet olsun.', 'Here you go, enjoy your meal.'),
    createContentItem('Çok lezzetli', '', 'Very delicious', 'sentence', 'Bu yemek çok lezzetli.', 'This food is very delicious.', [
      { target: 'Çok', native: 'Very' },
      { target: 'lezzetli', native: 'delicious' },
    ]),
    createContentItem('Acı', '', 'Spicy / Hot', 'word', 'Bu çok acı mı?', 'Is this very spicy?'),
    createContentItem('Tuzlu', '', 'Salty', 'word', 'Bu çorba biraz tuzlu.', 'This soup is a bit salty.'),
    createContentItem('Bir porsiyon kebap', '', 'One portion of kebab', 'sentence', 'Bir porsiyon Adana kebap lütfen.', 'One portion of Adana kebab please.', [
      { target: 'Bir', native: 'One' },
      { target: 'porsiyon', native: 'portion' },
      { target: 'kebap', native: 'kebab' },
    ]),
    createContentItem('Kahvaltı', '', 'Breakfast', 'word', 'Kahvaltıda ne var?', 'What is there for breakfast?'),
    createContentItem('Öğle yemeği', '', 'Lunch', 'word', 'Öğle yemeğine çıkalım.', 'Let us go out for lunch.'),
    createContentItem('Akşam yemeği', '', 'Dinner', 'word', 'Akşam yemeği hazır.', 'Dinner is ready.'),
    createContentItem('Menü', '', 'Menu', 'word', 'Menüyü görebilir miyim?', 'May I see the menu?'),
    createContentItem('Garson', '', 'Waiter', 'word', 'Garson, bir çay daha lütfen.', 'Waiter, one more tea please.'),
    createContentItem('Sipariş vermek istiyorum', '', 'I would like to order', 'sentence', 'Sipariş vermek istiyorum lütfen.', 'I would like to order please.', [
      { target: 'Sipariş', native: 'Order' },
      { target: 'vermek', native: 'to give' },
      { target: 'istiyorum', native: 'I want' },
    ]),
  ],
};

// ==================== TRAVEL ====================
const travel = {
  title: 'Travel & Transportation',
  category: 'travel',
  difficulty: 'beginner',
  targetLang: 'tr',
  content: [
    createContentItem('Havalimanı', '', 'Airport', 'word', 'Havalimanına nasıl gidebilirim?', 'How can I get to the airport?'),
    createContentItem('Otobüs', '', 'Bus', 'word', 'Otobüs saat kaçta?', 'What time is the bus?'),
    createContentItem('Taksi', '', 'Taxi', 'word', 'Bir taksi çağırabilir misiniz?', 'Can you call a taxi?'),
    createContentItem('Tren', '', 'Train', 'word', 'Ankara treni kalktı mı?', 'Has the Ankara train departed?'),
    createContentItem('Metro', '', 'Metro / Subway', 'word', 'En yakın metro istasyonu nerede?', 'Where is the nearest metro station?'),
    createContentItem('Otel', '', 'Hotel', 'word', 'Otel rezervasyonum var.', 'I have a hotel reservation.'),
    createContentItem('Bilet', '', 'Ticket', 'word', 'İki bilet lütfen.', 'Two tickets please.'),
    createContentItem('Pasaport', '', 'Passport', 'word', 'Pasaportunuz lütfen.', 'Your passport please.'),
    createContentItem('Bavul', '', 'Suitcase / Luggage', 'word', 'Bavulum çok ağır.', 'My suitcase is very heavy.'),
    createContentItem('Harita', '', 'Map', 'word', 'Şehir haritası var mı?', 'Do you have a city map?'),
    createContentItem('Nerede?', '', 'Where?', 'word', 'Tuvalet nerede?', 'Where is the toilet?'),
    createContentItem('Sağ', '', 'Right', 'word', 'Sağa dönün.', 'Turn right.'),
    createContentItem('Sol', '', 'Left', 'word', 'Sola dönün.', 'Turn left.'),
    createContentItem('Düz', '', 'Straight', 'word', 'Düz gidin.', 'Go straight.'),
    createContentItem('Yakın', '', 'Near / Close', 'word', 'Buraya yakın mı?', 'Is it near here?'),
    createContentItem('Uzak', '', 'Far', 'word', 'Havalimanı çok uzak.', 'The airport is very far.'),
    createContentItem('Buraya nasıl gidebilirim?', '', 'How can I get here?', 'sentence', 'Bu adrese nasıl gidebilirim?', 'How can I get to this address?', [
      { target: 'Buraya', native: 'Here / To here' },
      { target: 'nasıl', native: 'how' },
      { target: 'gidebilirim', native: 'can I go' },
    ]),
    createContentItem('Boş odanız var mı?', '', 'Do you have a vacant room?', 'sentence', 'Boş odanız var mı? İki gece kalacağız.', 'Do you have a vacant room? We will stay two nights.', [
      { target: 'Boş', native: 'Empty / Vacant' },
      { target: 'odanız', native: 'your room' },
      { target: 'var mı', native: 'is there / do you have' },
    ]),
    createContentItem('Müze', '', 'Museum', 'word', 'Arkeoloji müzesi nerede?', 'Where is the archaeology museum?'),
    createContentItem('Cami', '', 'Mosque', 'word', 'Sultanahmet Camii çok güzel.', 'The Sultanahmet Mosque is very beautiful.'),
    createContentItem('Deniz', '', 'Sea', 'word', 'Deniz çok güzel.', 'The sea is very beautiful.'),
    createContentItem('Plaj', '', 'Beach', 'word', 'Bu plaj çok temiz.', 'This beach is very clean.'),
    createContentItem('Ne zaman?', '', 'When?', 'word', 'Uçak ne zaman kalkıyor?', 'When does the plane depart?'),
    createContentItem('Gidiş-dönüş bilet', '', 'Round-trip ticket', 'sentence', 'İstanbul\'a gidiş-dönüş bilet istiyorum.', 'I want a round-trip ticket to Istanbul.', [
      { target: 'Gidiş', native: 'Departure / Going' },
      { target: 'dönüş', native: 'Return' },
      { target: 'bilet', native: 'ticket' },
    ]),
    createContentItem('Kayıp eşya', '', 'Lost property', 'word', 'Kayıp eşya bürosu nerede?', 'Where is the lost property office?'),
  ],
};

// ==================== SHOPPING ====================
const shopping = {
  title: 'Shopping & Money',
  category: 'shopping',
  difficulty: 'beginner',
  targetLang: 'tr',
  content: [
    createContentItem('Mağaza', '', 'Store / Shop', 'word', 'Bu mağaza saat kaçta kapanıyor?', 'What time does this store close?'),
    createContentItem('Pazar', '', 'Market / Bazaar', 'word', 'Salı pazarına gidelim.', 'Let us go to the Tuesday market.'),
    createContentItem('Fiyat', '', 'Price', 'word', 'Bu fiyat çok yüksek.', 'This price is very high.'),
    createContentItem('Para', '', 'Money', 'word', 'Param yok.', 'I have no money.'),
    createContentItem('Ucuz', '', 'Cheap', 'word', 'Daha ucuz var mı?', 'Is there a cheaper one?'),
    createContentItem('Pahalı', '', 'Expensive', 'word', 'Bu çok pahalı.', 'This is very expensive.'),
    createContentItem('İndirim', '', 'Discount', 'word', 'İndirim var mı?', 'Is there a discount?'),
    createContentItem('Kasa', '', 'Cash register / Checkout', 'word', 'Kasa nerede?', 'Where is the checkout?'),
    createContentItem('Bu ne kadar?', '', 'How much is this?', 'sentence', 'Affedersiniz, bu ne kadar?', 'Excuse me, how much is this?', [
      { target: 'Bu', native: 'This' },
      { target: 'ne kadar', native: 'how much' },
    ]),
    createContentItem('Kredi kartı', '', 'Credit card', 'word', 'Kredi kartı geçiyor mu?', 'Do you accept credit cards?'),
    createContentItem('Nakit', '', 'Cash', 'word', 'Sadece nakit ödeme.', 'Cash payment only.'),
    createContentItem('Beden', '', 'Size (clothing)', 'word', 'Bu beden bana büyük.', 'This size is too big for me.'),
    createContentItem('Denemek istiyorum', '', 'I want to try it on', 'sentence', 'Bunu denemek istiyorum.', 'I want to try this on.', [
      { target: 'Denemek', native: 'To try' },
      { target: 'istiyorum', native: 'I want' },
    ]),
    createContentItem('Renk', '', 'Color', 'word', 'Başka renk var mı?', 'Is there another color?'),
    createContentItem('Kırmızı', '', 'Red', 'word', 'Kırmızı renk güzel.', 'The red color is nice.'),
    createContentItem('Mavi', '', 'Blue', 'word', 'Mavi olanı istiyorum.', 'I want the blue one.'),
    createContentItem('Siyah', '', 'Black', 'word', 'Siyah çanta var mı?', 'Is there a black bag?'),
    createContentItem('Beyaz', '', 'White', 'word', 'Beyaz gömlek istiyorum.', 'I want a white shirt.'),
    createContentItem('Büyük', '', 'Big / Large', 'word', 'Bir büyük boy lütfen.', 'One large size please.'),
    createContentItem('Küçük', '', 'Small', 'word', 'Daha küçük var mı?', 'Is there a smaller one?'),
    createContentItem('Poşet', '', 'Bag (plastic)', 'word', 'Poşet istemiyorum, teşekkürler.', 'I do not want a bag, thank you.'),
    createContentItem('Fiş', '', 'Receipt', 'word', 'Fiş alabilir miyim?', 'May I have the receipt?'),
    createContentItem('İade etmek istiyorum', '', 'I want to return this', 'sentence', 'Bu ürünü iade etmek istiyorum.', 'I want to return this product.', [
      { target: 'İade', native: 'Return / Refund' },
      { target: 'etmek', native: 'to do / to make' },
      { target: 'istiyorum', native: 'I want' },
    ]),
    createContentItem('Hediye', '', 'Gift', 'word', 'Bu bir hediye, paket yapabilir misiniz?', 'This is a gift, can you wrap it?'),
    createContentItem('Çarşı', '', 'Bazaar / Market area', 'word', 'Kapalıçarşı çok büyük.', 'The Grand Bazaar is very big.'),
  ],
};

// ==================== BUSINESS ====================
const business = {
  title: 'Business & Work',
  category: 'business',
  difficulty: 'beginner',
  targetLang: 'tr',
  content: [
    createContentItem('Ofis', '', 'Office', 'word', 'Ofisim beşinci katta.', 'My office is on the fifth floor.'),
    createContentItem('Toplantı', '', 'Meeting', 'word', 'Saat üçte toplantımız var.', 'We have a meeting at three.'),
    createContentItem('Müdür', '', 'Manager / Director', 'word', 'Müdür bey şu an meşgul.', 'The manager is busy right now.'),
    createContentItem('Şirket', '', 'Company', 'word', 'Şirketimiz İstanbul\'da.', 'Our company is in Istanbul.'),
    createContentItem('Çalışmak', '', 'To work', 'word', 'Bu şirkette çalışıyorum.', 'I work at this company.'),
    createContentItem('Maaş', '', 'Salary', 'word', 'Maaşlar ayın birinde yatıyor.', 'Salaries are deposited on the first of the month.'),
    createContentItem('Sözleşme', '', 'Contract', 'word', 'Sözleşmeyi imzaladım.', 'I signed the contract.'),
    createContentItem('E-posta', '', 'Email', 'word', 'E-posta adresiniz nedir?', 'What is your email address?'),
    createContentItem('Randevu', '', 'Appointment', 'word', 'Yarın için randevum var.', 'I have an appointment for tomorrow.'),
    createContentItem('Proje', '', 'Project', 'word', 'Bu proje çok önemli.', 'This project is very important.'),
    createContentItem('Bir randevu almak istiyorum', '', 'I would like to make an appointment', 'sentence', 'Müdür bey ile bir randevu almak istiyorum.', 'I would like to make an appointment with the manager.', [
      { target: 'Bir', native: 'A / One' },
      { target: 'randevu', native: 'appointment' },
      { target: 'almak', native: 'to take / to get' },
      { target: 'istiyorum', native: 'I want' },
    ]),
    createContentItem('Meslektaş', '', 'Colleague', 'word', 'Meslektaşlarım çok iyi.', 'My colleagues are very good.'),
    createContentItem('Patron', '', 'Boss', 'word', 'Patronum bugün izinli.', 'My boss is on leave today.'),
    createContentItem('İş görüşmesi', '', 'Job interview', 'word', 'Yarın iş görüşmem var.', 'I have a job interview tomorrow.'),
    createContentItem('Özgeçmiş', '', 'Resume / CV', 'word', 'Özgeçmişimi gönderdim.', 'I sent my resume.'),
    createContentItem('Mesai saatleri', '', 'Working hours', 'word', 'Mesai saatlerimiz dokuzdan altıya.', 'Our working hours are nine to six.'),
    createContentItem('Fatura', '', 'Invoice / Bill', 'word', 'Faturayı e-posta ile gönderin lütfen.', 'Please send the invoice by email.'),
    createContentItem('Toplantı saat kaçta?', '', 'What time is the meeting?', 'sentence', 'Toplantı saat kaçta başlıyor?', 'What time does the meeting start?', [
      { target: 'Toplantı', native: 'Meeting' },
      { target: 'saat kaçta', native: 'at what time' },
      { target: 'başlıyor', native: 'starts' },
    ]),
    createContentItem('İmza', '', 'Signature', 'word', 'Buraya imza atın lütfen.', 'Please sign here.'),
    createContentItem('Kartvizit', '', 'Business card', 'word', 'Kartvizitiniz var mı?', 'Do you have a business card?'),
    createContentItem('Anlaşma', '', 'Agreement / Deal', 'word', 'Anlaşma tamam.', 'The deal is done.'),
    createContentItem('Sunum', '', 'Presentation', 'word', 'Yarın bir sunum yapacağım.', 'I will give a presentation tomorrow.'),
    createContentItem('Belge', '', 'Document', 'word', 'Bu belgeleri imzalayın lütfen.', 'Please sign these documents.'),
    createContentItem('Teslim tarihi ne zaman?', '', 'When is the deadline?', 'sentence', 'Projenin teslim tarihi ne zaman?', 'When is the project deadline?', [
      { target: 'Teslim', native: 'Delivery / Submission' },
      { target: 'tarihi', native: 'date' },
      { target: 'ne zaman', native: 'when' },
    ]),
    createContentItem('İzin', '', 'Leave / Permission', 'word', 'Yarın izin almak istiyorum.', 'I want to take leave tomorrow.'),
  ],
};

// ==================== HEALTHCARE ====================
const healthcare = {
  title: 'Health & Medical',
  category: 'healthcare',
  difficulty: 'beginner',
  targetLang: 'tr',
  content: [
    createContentItem('Hastane', '', 'Hospital', 'word', 'En yakın hastane nerede?', 'Where is the nearest hospital?'),
    createContentItem('Doktor', '', 'Doctor', 'word', 'Doktora gitmem lazım.', 'I need to go to the doctor.'),
    createContentItem('Eczane', '', 'Pharmacy', 'word', 'Nöbetçi eczane nerede?', 'Where is the on-duty pharmacy?'),
    createContentItem('İlaç', '', 'Medicine', 'word', 'Bu ilacı günde üç kez içiniz.', 'Take this medicine three times a day.'),
    createContentItem('Ağrı', '', 'Pain', 'word', 'Şiddetli ağrım var.', 'I have severe pain.'),
    createContentItem('Baş ağrısı', '', 'Headache', 'word', 'Baş ağrım var.', 'I have a headache.'),
    createContentItem('Ateş', '', 'Fever', 'word', 'Ateşim çok yüksek.', 'My fever is very high.'),
    createContentItem('Öksürük', '', 'Cough', 'word', 'Öksürüğüm geçmiyor.', 'My cough is not going away.'),
    createContentItem('Grip', '', 'Flu', 'word', 'Grip oldum.', 'I got the flu.'),
    createContentItem('Alerji', '', 'Allergy', 'word', 'Polen alerjim var.', 'I have a pollen allergy.'),
    createContentItem('Reçete', '', 'Prescription', 'word', 'Doktor reçete yazdı.', 'The doctor wrote a prescription.'),
    createContentItem('Ambulans', '', 'Ambulance', 'word', 'Ambulans çağırın lütfen!', 'Please call an ambulance!'),
    createContentItem('Kendimi iyi hissetmiyorum', '', 'I do not feel well', 'sentence', 'Kendimi iyi hissetmiyorum, doktora gitmem lazım.', 'I do not feel well, I need to go to the doctor.', [
      { target: 'Kendimi', native: 'Myself' },
      { target: 'iyi', native: 'well / good' },
      { target: 'hissetmiyorum', native: 'I do not feel' },
    ]),
    createContentItem('Mide', '', 'Stomach', 'word', 'Midem ağrıyor.', 'My stomach hurts.'),
    createContentItem('Diş', '', 'Tooth', 'word', 'Dişim çok ağrıyor.', 'My tooth hurts a lot.'),
    createContentItem('Göz', '', 'Eye', 'word', 'Gözlerim yanıyor.', 'My eyes are burning.'),
    createContentItem('Kulak', '', 'Ear', 'word', 'Kulak ağrım var.', 'I have an earache.'),
    createContentItem('Boğaz', '', 'Throat', 'word', 'Boğazım ağrıyor.', 'My throat hurts.'),
    createContentItem('Kan', '', 'Blood', 'word', 'Kan tahlili yaptırmam gerekiyor.', 'I need to get a blood test.'),
    createContentItem('Sigorta', '', 'Insurance', 'word', 'Sağlık sigortanız var mı?', 'Do you have health insurance?'),
    createContentItem('Acil', '', 'Emergency', 'word', 'Acil servis nerede?', 'Where is the emergency room?'),
    createContentItem('Yaralıyım', '', 'I am injured', 'word', 'Kolum yaralı.', 'My arm is injured.'),
    createContentItem('Nefes almak zor', '', 'Difficult to breathe', 'sentence', 'Nefes almak çok zor.', 'It is very difficult to breathe.', [
      { target: 'Nefes', native: 'Breath' },
      { target: 'almak', native: 'to take' },
      { target: 'zor', native: 'difficult' },
    ]),
    createContentItem('Randevu almak istiyorum', '', 'I want to make an appointment', 'sentence', 'Doktor için randevu almak istiyorum.', 'I want to make an appointment with the doctor.', [
      { target: 'Randevu', native: 'Appointment' },
      { target: 'almak', native: 'to take / to get' },
      { target: 'istiyorum', native: 'I want' },
    ]),
    createContentItem('Hamile', '', 'Pregnant', 'word', 'Hamile misiniz?', 'Are you pregnant?'),
  ],
};

module.exports = { greetings, dailyLife, food, travel, shopping, business, healthcare };
