// Localized transactional-email strings for Lingo Booth.
//
// Placeholders inside strings use {name} and are filled at send time.
// Detail labels for the new-device email (labelWhen/labelWhere/labelDevice) are
// paired with runtime values by the email builder, not interpolated here.
//
// Every language falls back to `en` for any missing key. When adding a new email
// type, add its keys under `en` first (that is the canonical source), then each
// other language.

const STRINGS = {
  en: {
    welcome: {
      subject: "Welcome to Lingo Booth!",
      heading: "Welcome to Lingo Booth",
      greeting: "Hi {name}, welcome aboard!",
      body: "We're thrilled to have you. Lingo Booth helps you learn a language for real conversations — and a little practice every day goes a long way. Ready to dive in?",
      button: "Start learning",
    },
    login: {
      subject: "Welcome back to Lingo Booth",
      heading: "Welcome back!",
      greeting: "Hi {name}, great to see you again.",
      body: "Pick up right where you left off and keep your streak alive. Just a few minutes of practice today keeps your momentum going.",
      button: "Continue learning",
    },
    newDevice: {
      subject: "New sign-in to your Lingo Booth account",
      heading: "New device sign-in",
      greeting: "Hi {name}, we noticed a new sign-in to your Lingo Booth account.",
      detailsIntro: "Here are the details:",
      labelWhen: "When",
      labelWhere: "Where",
      labelDevice: "Device",
      reassure: "If this was you, no action is needed.",
      warn: "If you don't recognize this activity, reset your password right away to keep your account secure.",
      button: "Secure my account",
    },
    reset: {
      subject: "Reset your Lingo Booth password",
      heading: "Reset your password",
      greeting: "Hi {name}, we received a request to reset your password. Click the button below to choose a new one.",
      button: "Reset password",
      copyLink: "Or copy and paste this link into your browser:",
      expiry: "This link expires in 1 hour. If you didn't request a password reset, you can safely ignore this email.",
      textIntro: "Hi {name}, we received a request to reset your Lingo Booth password. Visit this link to choose a new one:",
      textExpiry: "This link expires in 1 hour. If you didn't request a password reset, you can safely ignore this email.",
    },
  },

  ko: {
    welcome: {
      subject: "Lingo Booth에 오신 것을 환영합니다!",
      heading: "Lingo Booth에 오신 것을 환영합니다",
      greeting: "{name}님, 반갑습니다! 가입을 환영합니다.",
      body: "함께하게 되어 정말 기쁩니다. Lingo Booth는 실제 대화에 필요한 언어를 배울 수 있도록 도와드립니다. 매일 조금씩 연습하면 큰 변화를 만들 수 있어요. 지금 시작해 볼까요?",
      button: "학습 시작하기",
    },
    login: {
      subject: "Lingo Booth에 다시 오신 것을 환영합니다",
      heading: "다시 만나서 반가워요!",
      greeting: "{name}님, 다시 뵙게 되어 반갑습니다.",
      body: "중단했던 곳부터 이어서 학습하고 연속 학습 기록을 이어가세요. 오늘 몇 분만 연습해도 지금의 흐름을 유지할 수 있습니다.",
      button: "이어서 학습하기",
    },
    newDevice: {
      subject: "Lingo Booth 계정에 새로운 로그인이 있었습니다",
      heading: "새 기기 로그인",
      greeting: "{name}님, 회원님의 Lingo Booth 계정에 새로운 로그인이 감지되었습니다.",
      detailsIntro: "자세한 내용은 다음과 같습니다:",
      labelWhen: "일시",
      labelWhere: "위치",
      labelDevice: "기기",
      reassure: "본인이 로그인하신 경우 별도로 조치하실 필요가 없습니다.",
      warn: "이 활동이 본인의 것이 아니라면, 계정 보안을 위해 즉시 비밀번호를 재설정해 주십시오.",
      button: "내 계정 보호하기",
    },
    reset: {
      subject: "Lingo Booth 비밀번호 재설정",
      heading: "비밀번호 재설정",
      greeting: "{name}님, 비밀번호 재설정 요청을 접수했습니다. 아래 버튼을 클릭하여 새 비밀번호를 설정하세요.",
      button: "비밀번호 재설정",
      copyLink: "또는 아래 링크를 복사하여 브라우저에 붙여넣으세요:",
      expiry: "이 링크는 1시간 후에 만료됩니다. 비밀번호 재설정을 요청하지 않으셨다면 이 이메일을 무시하셔도 됩니다.",
      textIntro: "{name}님, Lingo Booth 비밀번호 재설정 요청을 접수했습니다. 아래 링크에 접속하여 새 비밀번호를 설정하세요:",
      textExpiry: "이 링크는 1시간 후에 만료됩니다. 비밀번호 재설정을 요청하지 않으셨다면 이 이메일을 무시하셔도 됩니다.",
    },
  },

  ja: {
    welcome: {
      subject: "Lingo Boothへようこそ！",
      heading: "Lingo Boothへようこそ",
      greeting: "{name}さん、ようこそ！",
      body: "ご登録いただき、うれしく思います。Lingo Boothは、実際の会話で使える言語の習得をお手伝いします。毎日少しずつ練習することが、大きな上達につながります。さっそく始めてみませんか？",
      button: "学習を始める",
    },
    login: {
      subject: "おかえりなさい、Lingo Boothへ",
      heading: "おかえりなさい！",
      greeting: "{name}さん、またお会いできてうれしいです。",
      body: "前回の続きから学習を再開して、連続学習記録をキープしましょう。今日はほんの数分の練習でも、勢いを保つことができます。",
      button: "学習を続ける",
    },
    newDevice: {
      subject: "Lingo Boothアカウントへの新しいサインイン",
      heading: "新しいデバイスからのサインイン",
      greeting: "{name}さん、お客様のLingo Boothアカウントへの新しいサインインを確認しました。",
      detailsIntro: "詳細は以下のとおりです：",
      labelWhen: "日時",
      labelWhere: "場所",
      labelDevice: "デバイス",
      reassure: "お心当たりがある場合は、特に操作は必要ありません。",
      warn: "この操作にお心当たりがない場合は、アカウントの安全を守るため、直ちにパスワードを再設定してください。",
      button: "アカウントを保護する",
    },
    reset: {
      subject: "Lingo Boothのパスワードを再設定",
      heading: "パスワードの再設定",
      greeting: "{name}さん、パスワード再設定のリクエストを受け付けました。下のボタンをクリックして、新しいパスワードを設定してください。",
      button: "パスワードを再設定",
      copyLink: "または、以下のリンクをコピーしてブラウザに貼り付けてください：",
      expiry: "このリンクは1時間で有効期限が切れます。パスワードの再設定をリクエストしていない場合は、このメールを無視していただいて問題ありません。",
      textIntro: "{name}さん、Lingo Boothのパスワード再設定のリクエストを受け付けました。以下のリンクにアクセスして、新しいパスワードを設定してください：",
      textExpiry: "このリンクは1時間で有効期限が切れます。パスワードの再設定をリクエストしていない場合は、このメールを無視していただいて問題ありません。",
    },
  },

  zh: {
    welcome: {
      subject: "欢迎加入 Lingo Booth！",
      heading: "欢迎来到 Lingo Booth",
      greeting: "{name}，欢迎加入！",
      body: "很高兴有你的加入。Lingo Booth 帮助你学习能够用于真实对话的语言，每天坚持一点点练习，就能收获很大进步。准备好开始了吗？",
      button: "开始学习",
    },
    login: {
      subject: "欢迎回到 Lingo Booth",
      heading: "欢迎回来！",
      greeting: "{name}，很高兴再次见到你。",
      body: "从上次中断的地方继续，保持你的连续学习记录。今天只需练习几分钟，就能让学习势头延续下去。",
      button: "继续学习",
    },
    newDevice: {
      subject: "你的 Lingo Booth 账户有新的登录",
      heading: "新设备登录",
      greeting: "{name}，我们发现你的 Lingo Booth 账户有一次新的登录。",
      detailsIntro: "详细信息如下：",
      labelWhen: "时间",
      labelWhere: "地点",
      labelDevice: "设备",
      reassure: "如果这是你本人的操作，则无需采取任何措施。",
      warn: "如果你不认识此项活动，请立即重置密码，以确保账户安全。",
      button: "保护我的账户",
    },
    reset: {
      subject: "重置你的 Lingo Booth 密码",
      heading: "重置密码",
      greeting: "{name}，我们收到了重置你密码的请求。请点击下方按钮设置新密码。",
      button: "重置密码",
      copyLink: "或将以下链接复制并粘贴到你的浏览器中：",
      expiry: "此链接将在 1 小时后失效。如果你没有请求重置密码，可以放心忽略此邮件。",
      textIntro: "{name}，我们收到了重置你 Lingo Booth 密码的请求。请访问以下链接设置新密码：",
      textExpiry: "此链接将在 1 小时后失效。如果你没有请求重置密码，可以放心忽略此邮件。",
    },
  },

  es: {
    welcome: {
      subject: "¡Te damos la bienvenida a Lingo Booth!",
      heading: "Te damos la bienvenida a Lingo Booth",
      greeting: "Hola {name}, ¡bienvenido a bordo!",
      body: "Nos encanta tenerte aquí. Lingo Booth te ayuda a aprender un idioma para conversaciones reales, y un poco de práctica cada día marca una gran diferencia. ¿Listo para empezar?",
      button: "Empezar a aprender",
    },
    login: {
      subject: "Bienvenido de nuevo a Lingo Booth",
      heading: "¡Bienvenido de nuevo!",
      greeting: "Hola {name}, qué alegría verte de nuevo.",
      body: "Retoma justo donde lo dejaste y mantén tu racha viva. Con solo unos minutos de práctica hoy conservas el impulso.",
      button: "Seguir aprendiendo",
    },
    newDevice: {
      subject: "Nuevo inicio de sesión en tu cuenta de Lingo Booth",
      heading: "Inicio de sesión desde un nuevo dispositivo",
      greeting: "Hola {name}, detectamos un nuevo inicio de sesión en tu cuenta de Lingo Booth.",
      detailsIntro: "Estos son los detalles:",
      labelWhen: "Cuándo",
      labelWhere: "Dónde",
      labelDevice: "Dispositivo",
      reassure: "Si fuiste tú, no es necesario hacer nada.",
      warn: "Si no reconoces esta actividad, restablece tu contraseña de inmediato para mantener tu cuenta segura.",
      button: "Proteger mi cuenta",
    },
    reset: {
      subject: "Restablece tu contraseña de Lingo Booth",
      heading: "Restablece tu contraseña",
      greeting: "Hola {name}, recibimos una solicitud para restablecer tu contraseña. Haz clic en el botón de abajo para elegir una nueva.",
      button: "Restablecer contraseña",
      copyLink: "O copia y pega este enlace en tu navegador:",
      expiry: "Este enlace caduca en 1 hora. Si no solicitaste restablecer la contraseña, puedes ignorar este correo sin problema.",
      textIntro: "Hola {name}, recibimos una solicitud para restablecer tu contraseña de Lingo Booth. Visita este enlace para elegir una nueva:",
      textExpiry: "Este enlace caduca en 1 hora. Si no solicitaste restablecer la contraseña, puedes ignorar este correo sin problema.",
    },
  },

  pt: {
    welcome: {
      subject: "Boas-vindas ao Lingo Booth!",
      heading: "Boas-vindas ao Lingo Booth",
      greeting: "Olá {name}, que bom ter você com a gente!",
      body: "Estamos muito felizes em ter você por aqui. O Lingo Booth ajuda você a aprender um idioma para conversas de verdade, e um pouco de prática todo dia faz toda a diferença. Vamos começar?",
      button: "Começar a aprender",
    },
    login: {
      subject: "Que bom ter você de volta ao Lingo Booth",
      heading: "Que bom ter você de volta!",
      greeting: "Olá {name}, é ótimo ver você de novo.",
      body: "Continue exatamente de onde parou e mantenha sua sequência ativa. Bastam alguns minutos de prática hoje para não perder o ritmo.",
      button: "Continuar aprendendo",
    },
    newDevice: {
      subject: "Novo acesso à sua conta do Lingo Booth",
      heading: "Acesso de um novo dispositivo",
      greeting: "Olá {name}, detectamos um novo acesso à sua conta do Lingo Booth.",
      detailsIntro: "Veja os detalhes:",
      labelWhen: "Quando",
      labelWhere: "Onde",
      labelDevice: "Dispositivo",
      reassure: "Se foi você, não é preciso fazer nada.",
      warn: "Se você não reconhece esta atividade, redefina sua senha imediatamente para manter sua conta segura.",
      button: "Proteger minha conta",
    },
    reset: {
      subject: "Redefina sua senha do Lingo Booth",
      heading: "Redefina sua senha",
      greeting: "Olá {name}, recebemos uma solicitação para redefinir sua senha. Clique no botão abaixo para escolher uma nova.",
      button: "Redefinir senha",
      copyLink: "Ou copie e cole este link no seu navegador:",
      expiry: "Este link expira em 1 hora. Se você não solicitou a redefinição de senha, pode ignorar este e-mail com tranquilidade.",
      textIntro: "Olá {name}, recebemos uma solicitação para redefinir sua senha do Lingo Booth. Acesse este link para escolher uma nova:",
      textExpiry: "Este link expira em 1 hora. Se você não solicitou a redefinição de senha, pode ignorar este e-mail com tranquilidade.",
    },
  },

  it: {
    welcome: {
      subject: "Ti diamo il benvenuto su Lingo Booth!",
      heading: "Ti diamo il benvenuto su Lingo Booth",
      greeting: "Ciao {name}, benvenuto a bordo!",
      body: "Siamo felicissimi di averti con noi. Lingo Booth ti aiuta a imparare una lingua per conversazioni reali, e un po' di pratica ogni giorno fa una grande differenza. Pronto a iniziare?",
      button: "Inizia a imparare",
    },
    login: {
      subject: "Bentornato su Lingo Booth",
      heading: "Bentornato!",
      greeting: "Ciao {name}, è bello rivederti.",
      body: "Riprendi esattamente da dove avevi lasciato e mantieni viva la tua serie. Bastano pochi minuti di pratica oggi per non perdere lo slancio.",
      button: "Continua a imparare",
    },
    newDevice: {
      subject: "Nuovo accesso al tuo account Lingo Booth",
      heading: "Accesso da un nuovo dispositivo",
      greeting: "Ciao {name}, abbiamo rilevato un nuovo accesso al tuo account Lingo Booth.",
      detailsIntro: "Ecco i dettagli:",
      labelWhen: "Quando",
      labelWhere: "Dove",
      labelDevice: "Dispositivo",
      reassure: "Se sei stato tu, non è necessario fare nulla.",
      warn: "Se non riconosci questa attività, reimposta subito la password per mantenere sicuro il tuo account.",
      button: "Proteggi il mio account",
    },
    reset: {
      subject: "Reimposta la tua password di Lingo Booth",
      heading: "Reimposta la tua password",
      greeting: "Ciao {name}, abbiamo ricevuto una richiesta di reimpostazione della password. Fai clic sul pulsante qui sotto per sceglierne una nuova.",
      button: "Reimposta password",
      copyLink: "Oppure copia e incolla questo link nel tuo browser:",
      expiry: "Questo link scade tra 1 ora. Se non hai richiesto la reimpostazione della password, puoi ignorare tranquillamente questa email.",
      textIntro: "Ciao {name}, abbiamo ricevuto una richiesta di reimpostazione della tua password di Lingo Booth. Visita questo link per sceglierne una nuova:",
      textExpiry: "Questo link scade tra 1 ora. Se non hai richiesto la reimpostazione della password, puoi ignorare tranquillamente questa email.",
    },
  },

  fr: {
    welcome: {
      subject: "Bienvenue sur Lingo Booth !",
      heading: "Bienvenue sur Lingo Booth",
      greeting: "Bonjour {name}, bienvenue parmi nous !",
      body: "Nous sommes ravis de vous compter parmi nous. Lingo Booth vous aide à apprendre une langue pour de vraies conversations — et un peu de pratique chaque jour fait toute la différence. Prêt à vous lancer ?",
      button: "Commencer à apprendre",
    },
    login: {
      subject: "Bon retour sur Lingo Booth",
      heading: "Bon retour !",
      greeting: "Bonjour {name}, ravis de vous revoir.",
      body: "Reprenez là où vous vous étiez arrêté et préservez votre série. Quelques minutes de pratique aujourd'hui suffisent à garder votre élan.",
      button: "Continuer à apprendre",
    },
    newDevice: {
      subject: "Nouvelle connexion à votre compte Lingo Booth",
      heading: "Connexion depuis un nouvel appareil",
      greeting: "Bonjour {name}, nous avons remarqué une nouvelle connexion à votre compte Lingo Booth.",
      detailsIntro: "Voici les détails :",
      labelWhen: "Quand",
      labelWhere: "Où",
      labelDevice: "Appareil",
      reassure: "S'il s'agit bien de vous, aucune action n'est nécessaire.",
      warn: "Si vous ne reconnaissez pas cette activité, réinitialisez votre mot de passe immédiatement afin de protéger votre compte.",
      button: "Sécuriser mon compte",
    },
    reset: {
      subject: "Réinitialisez votre mot de passe Lingo Booth",
      heading: "Réinitialisez votre mot de passe",
      greeting: "Bonjour {name}, nous avons reçu une demande de réinitialisation de votre mot de passe. Cliquez sur le bouton ci-dessous pour en choisir un nouveau.",
      button: "Réinitialiser le mot de passe",
      copyLink: "Ou copiez-collez ce lien dans votre navigateur :",
      expiry: "Ce lien expire dans 1 heure. Si vous n'avez pas demandé de réinitialisation de mot de passe, vous pouvez ignorer cet e-mail en toute sécurité.",
      textIntro: "Bonjour {name}, nous avons reçu une demande de réinitialisation de votre mot de passe Lingo Booth. Rendez-vous sur ce lien pour en choisir un nouveau :",
      textExpiry: "Ce lien expire dans 1 heure. Si vous n'avez pas demandé de réinitialisation de mot de passe, vous pouvez ignorer cet e-mail en toute sécurité.",
    },
  },

  de: {
    welcome: {
      subject: "Willkommen bei Lingo Booth!",
      heading: "Willkommen bei Lingo Booth",
      greeting: "Hallo {name}, willkommen an Bord!",
      body: "Wir freuen uns sehr, dass du dabei bist. Lingo Booth hilft dir, eine Sprache für echte Gespräche zu lernen — und ein bisschen Übung jeden Tag bringt dich weit. Bereit, loszulegen?",
      button: "Jetzt lernen",
    },
    login: {
      subject: "Willkommen zurück bei Lingo Booth",
      heading: "Willkommen zurück!",
      greeting: "Hallo {name}, schön, dich wiederzusehen.",
      body: "Mach genau da weiter, wo du aufgehört hast, und halte deine Serie am Leben. Schon ein paar Minuten Übung heute halten deinen Schwung aufrecht.",
      button: "Weiterlernen",
    },
    newDevice: {
      subject: "Neue Anmeldung bei deinem Lingo Booth-Konto",
      heading: "Anmeldung von einem neuen Gerät",
      greeting: "Hallo {name}, wir haben eine neue Anmeldung bei deinem Lingo Booth-Konto festgestellt.",
      detailsIntro: "Hier sind die Details:",
      labelWhen: "Wann",
      labelWhere: "Wo",
      labelDevice: "Gerät",
      reassure: "Wenn du das warst, ist nichts weiter zu tun.",
      warn: "Falls du diese Aktivität nicht kennst, setze dein Passwort umgehend zurück, um dein Konto zu schützen.",
      button: "Mein Konto sichern",
    },
    reset: {
      subject: "Setze dein Lingo Booth-Passwort zurück",
      heading: "Passwort zurücksetzen",
      greeting: "Hallo {name}, wir haben eine Anfrage zum Zurücksetzen deines Passworts erhalten. Klicke auf die Schaltfläche unten, um ein neues zu wählen.",
      button: "Passwort zurücksetzen",
      copyLink: "Oder kopiere diesen Link und füge ihn in deinen Browser ein:",
      expiry: "Dieser Link läuft in 1 Stunde ab. Wenn du kein Zurücksetzen des Passworts angefordert hast, kannst du diese E-Mail bedenkenlos ignorieren.",
      textIntro: "Hallo {name}, wir haben eine Anfrage zum Zurücksetzen deines Lingo Booth-Passworts erhalten. Öffne diesen Link, um ein neues zu wählen:",
      textExpiry: "Dieser Link läuft in 1 Stunde ab. Wenn du kein Zurücksetzen des Passworts angefordert hast, kannst du diese E-Mail bedenkenlos ignorieren.",
    },
  },

  nl: {
    welcome: {
      subject: "Welkom bij Lingo Booth!",
      heading: "Welkom bij Lingo Booth",
      greeting: "Hoi {name}, welkom aan boord!",
      body: "We zijn erg blij dat je er bent. Lingo Booth helpt je een taal te leren voor échte gesprekken — en elke dag een beetje oefenen maakt een groot verschil. Klaar om te beginnen?",
      button: "Begin met leren",
    },
    login: {
      subject: "Welkom terug bij Lingo Booth",
      heading: "Welkom terug!",
      greeting: "Hoi {name}, fijn om je weer te zien.",
      body: "Ga verder waar je gebleven was en houd je reeks in stand. Een paar minuten oefenen vandaag houdt je op dreef.",
      button: "Ga verder met leren",
    },
    newDevice: {
      subject: "Nieuwe aanmelding bij je Lingo Booth-account",
      heading: "Aanmelding vanaf een nieuw apparaat",
      greeting: "Hoi {name}, we hebben een nieuwe aanmelding bij je Lingo Booth-account opgemerkt.",
      detailsIntro: "Hier zijn de details:",
      labelWhen: "Wanneer",
      labelWhere: "Waar",
      labelDevice: "Apparaat",
      reassure: "Als jij dit was, hoef je niets te doen.",
      warn: "Herken je deze activiteit niet, stel dan meteen je wachtwoord opnieuw in om je account te beveiligen.",
      button: "Mijn account beveiligen",
    },
    reset: {
      subject: "Stel je Lingo Booth-wachtwoord opnieuw in",
      heading: "Wachtwoord opnieuw instellen",
      greeting: "Hoi {name}, we hebben een verzoek ontvangen om je wachtwoord opnieuw in te stellen. Klik op de knop hieronder om een nieuw wachtwoord te kiezen.",
      button: "Wachtwoord opnieuw instellen",
      copyLink: "Of kopieer en plak deze link in je browser:",
      expiry: "Deze link verloopt over 1 uur. Als je geen wachtwoordherstel hebt aangevraagd, kun je deze e-mail veilig negeren.",
      textIntro: "Hoi {name}, we hebben een verzoek ontvangen om je Lingo Booth-wachtwoord opnieuw in te stellen. Ga naar deze link om een nieuw wachtwoord te kiezen:",
      textExpiry: "Deze link verloopt over 1 uur. Als je geen wachtwoordherstel hebt aangevraagd, kun je deze e-mail veilig negeren.",
    },
  },

  ru: {
    welcome: {
      subject: "Добро пожаловать в Lingo Booth!",
      heading: "Добро пожаловать в Lingo Booth",
      greeting: "Привет, {name}, рады видеть вас с нами!",
      body: "Мы очень рады, что вы присоединились. Lingo Booth помогает учить язык для настоящих разговоров, а немного практики каждый день приносит большие результаты. Готовы начать?",
      button: "Начать обучение",
    },
    login: {
      subject: "С возвращением в Lingo Booth",
      heading: "С возвращением!",
      greeting: "Привет, {name}, рады снова вас видеть.",
      body: "Продолжайте с того места, на котором остановились, и не прерывайте свою серию. Всего несколько минут практики сегодня помогут сохранить набранный темп.",
      button: "Продолжить обучение",
    },
    newDevice: {
      subject: "Новый вход в ваш аккаунт Lingo Booth",
      heading: "Вход с нового устройства",
      greeting: "Здравствуйте, {name}. Мы заметили новый вход в ваш аккаунт Lingo Booth.",
      detailsIntro: "Вот подробности:",
      labelWhen: "Когда",
      labelWhere: "Где",
      labelDevice: "Устройство",
      reassure: "Если это были вы, никаких действий предпринимать не нужно.",
      warn: "Если вы не узнаёте эту активность, немедленно смените пароль, чтобы защитить ваш аккаунт.",
      button: "Защитить аккаунт",
    },
    reset: {
      subject: "Сброс пароля Lingo Booth",
      heading: "Сброс пароля",
      greeting: "Привет, {name}, мы получили запрос на сброс вашего пароля. Нажмите кнопку ниже, чтобы выбрать новый.",
      button: "Сбросить пароль",
      copyLink: "Или скопируйте и вставьте эту ссылку в браузер:",
      expiry: "Срок действия ссылки истекает через 1 час. Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.",
      textIntro: "Привет, {name}, мы получили запрос на сброс вашего пароля Lingo Booth. Перейдите по этой ссылке, чтобы выбрать новый:",
      textExpiry: "Срок действия ссылки истекает через 1 час. Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.",
    },
  },

  ar: {
    welcome: {
      subject: "مرحبًا بك في Lingo Booth!",
      heading: "مرحبًا بك في Lingo Booth",
      greeting: "مرحبًا {name}، أهلًا بك معنا!",
      body: "يسعدنا انضمامك إلينا كثيرًا. يساعدك Lingo Booth على تعلّم لغة تصلح للمحادثات الحقيقية، وقليل من التدرّب كل يوم يحدث فرقًا كبيرًا. هل أنت مستعد للبدء؟",
      button: "ابدأ التعلّم",
    },
    login: {
      subject: "مرحبًا بعودتك إلى Lingo Booth",
      heading: "مرحبًا بعودتك!",
      greeting: "مرحبًا {name}، يسعدنا رؤيتك من جديد.",
      body: "تابع من حيث توقّفت وحافظ على سلسلة إنجازاتك. بضع دقائق من التدرّب اليوم تكفي لتبقى في المسار الصحيح.",
      button: "واصل التعلّم",
    },
    newDevice: {
      subject: "تسجيل دخول جديد إلى حسابك في Lingo Booth",
      heading: "تسجيل دخول من جهاز جديد",
      greeting: "مرحبًا {name}، لاحظنا تسجيل دخول جديد إلى حسابك في Lingo Booth.",
      detailsIntro: "إليك التفاصيل:",
      labelWhen: "الوقت",
      labelWhere: "المكان",
      labelDevice: "الجهاز",
      reassure: "إذا كنت أنت من قام بذلك، فلا حاجة لاتخاذ أي إجراء.",
      warn: "إذا لم تتعرّف على هذا النشاط، فأعد تعيين كلمة المرور فورًا للحفاظ على أمان حسابك.",
      button: "تأمين حسابي",
    },
    reset: {
      subject: "إعادة تعيين كلمة مرور Lingo Booth الخاصة بك",
      heading: "إعادة تعيين كلمة المرور",
      greeting: "مرحبًا {name}، تلقّينا طلبًا لإعادة تعيين كلمة المرور الخاصة بك. انقر على الزر أدناه لاختيار كلمة مرور جديدة.",
      button: "إعادة تعيين كلمة المرور",
      copyLink: "أو انسخ هذا الرابط والصقه في متصفحك:",
      expiry: "تنتهي صلاحية هذا الرابط خلال ساعة واحدة. إذا لم تطلب إعادة تعيين كلمة المرور، فيمكنك تجاهل هذا البريد الإلكتروني بأمان.",
      textIntro: "مرحبًا {name}، تلقّينا طلبًا لإعادة تعيين كلمة مرور Lingo Booth الخاصة بك. زُر هذا الرابط لاختيار كلمة مرور جديدة:",
      textExpiry: "تنتهي صلاحية هذا الرابط خلال ساعة واحدة. إذا لم تطلب إعادة تعيين كلمة المرور، فيمكنك تجاهل هذا البريد الإلكتروني بأمان.",
    },
  },

  he: {
    welcome: {
      subject: "ברוכים הבאים ל-Lingo Booth!",
      heading: "ברוכים הבאים ל-Lingo Booth",
      greeting: "היי {name}, שמחים שהצטרפת!",
      body: "אנחנו נרגשים שאת/ה איתנו. Lingo Booth עוזר לך ללמוד שפה לשיחות אמיתיות, וקצת תרגול בכל יום עושה הבדל גדול. מוכן/ה להתחיל?",
      button: "התחלת למידה",
    },
    login: {
      subject: "ברוכים השבים ל-Lingo Booth",
      heading: "ברוכים השבים!",
      greeting: "היי {name}, כיף לראות אותך שוב.",
      body: "המשך/י בדיוק מהמקום שבו עצרת ושמור/י על רצף התרגול שלך. כמה דקות של תרגול היום ישמרו על המומנטום שלך.",
      button: "המשך למידה",
    },
    newDevice: {
      subject: "כניסה חדשה לחשבון Lingo Booth שלך",
      heading: "כניסה ממכשיר חדש",
      greeting: "היי {name}, שמנו לב לכניסה חדשה לחשבון Lingo Booth שלך.",
      detailsIntro: "אלה הפרטים:",
      labelWhen: "מתי",
      labelWhere: "היכן",
      labelDevice: "מכשיר",
      reassure: "אם זה היית את/ה, אין צורך לעשות דבר.",
      warn: "אם אינך מזהה פעילות זו, אפס/י את הסיסמה שלך מיד כדי לשמור על אבטחת החשבון.",
      button: "אבטחת החשבון שלי",
    },
    reset: {
      subject: "איפוס הסיסמה שלך ב-Lingo Booth",
      heading: "איפוס הסיסמה",
      greeting: "היי {name}, קיבלנו בקשה לאיפוס הסיסמה שלך. לחץ/י על הכפתור למטה כדי לבחור סיסמה חדשה.",
      button: "איפוס סיסמה",
      copyLink: "או העתק/י והדבק/י את הקישור הזה בדפדפן שלך:",
      expiry: "תוקף הקישור פג בעוד שעה. אם לא ביקשת לאפס את הסיסמה, אפשר להתעלם ממייל זה בבטחה.",
      textIntro: "היי {name}, קיבלנו בקשה לאיפוס הסיסמה שלך ב-Lingo Booth. היכנס/י לקישור הזה כדי לבחור סיסמה חדשה:",
      textExpiry: "תוקף הקישור פג בעוד שעה. אם לא ביקשת לאפס את הסיסמה, אפשר להתעלם ממייל זה בבטחה.",
    },
  },

  tr: {
    welcome: {
      subject: "Lingo Booth'a hoş geldin!",
      heading: "Lingo Booth'a hoş geldin",
      greeting: "Merhaba {name}, aramıza hoş geldin!",
      body: "Aramızda olmandan büyük mutluluk duyuyoruz. Lingo Booth, gerçek konuşmalar için bir dil öğrenmene yardımcı olur ve her gün biraz pratik uzun vadede çok fark yaratır. Başlamaya hazır mısın?",
      button: "Öğrenmeye başla",
    },
    login: {
      subject: "Lingo Booth'a tekrar hoş geldin",
      heading: "Tekrar hoş geldin!",
      greeting: "Merhaba {name}, seni yeniden görmek harika.",
      body: "Kaldığın yerden devam et ve serini bozma. Bugün birkaç dakikalık pratik, motivasyonunu canlı tutar.",
      button: "Öğrenmeye devam et",
    },
    newDevice: {
      subject: "Lingo Booth hesabınıza yeni giriş",
      heading: "Yeni cihazdan giriş",
      greeting: "Merhaba {name}, Lingo Booth hesabınıza yeni bir giriş yapıldığını fark ettik.",
      detailsIntro: "Ayrıntılar aşağıdadır:",
      labelWhen: "Ne zaman",
      labelWhere: "Nerede",
      labelDevice: "Cihaz",
      reassure: "Bu işlemi siz yaptıysanız herhangi bir işlem yapmanıza gerek yoktur.",
      warn: "Bu etkinliği tanımıyorsanız, hesabınızın güvenliğini korumak için parolanızı hemen sıfırlayın.",
      button: "Hesabımı güvene al",
    },
    reset: {
      subject: "Lingo Booth parolanızı sıfırlayın",
      heading: "Parolanızı sıfırlayın",
      greeting: "Merhaba {name}, parolanızı sıfırlama talebi aldık. Yeni bir parola seçmek için aşağıdaki düğmeye tıklayın.",
      button: "Parolayı sıfırla",
      copyLink: "Ya da bu bağlantıyı kopyalayıp tarayıcınıza yapıştırın:",
      expiry: "Bu bağlantının süresi 1 saat içinde dolar. Parola sıfırlama talebinde bulunmadıysanız bu e-postayı güvenle yok sayabilirsiniz.",
      textIntro: "Merhaba {name}, Lingo Booth parolanızı sıfırlama talebi aldık. Yeni bir parola seçmek için bu bağlantıyı ziyaret edin:",
      textExpiry: "Bu bağlantının süresi 1 saat içinde dolar. Parola sıfırlama talebinde bulunmadıysanız bu e-postayı güvenle yok sayabilirsiniz.",
    },
  },

  id: {
    welcome: {
      subject: "Selamat datang di Lingo Booth!",
      heading: "Selamat datang di Lingo Booth",
      greeting: "Hai {name}, selamat bergabung!",
      body: "Kami sangat senang kamu ada di sini. Lingo Booth membantumu belajar bahasa untuk percakapan sehari-hari — dan latihan sedikit demi sedikit setiap hari akan membawa hasil yang besar. Siap untuk memulai?",
      button: "Mulai belajar",
    },
    login: {
      subject: "Selamat datang kembali di Lingo Booth",
      heading: "Selamat datang kembali!",
      greeting: "Hai {name}, senang bertemu denganmu lagi.",
      body: "Lanjutkan dari tempat terakhir kamu berhenti dan jaga agar streak-mu tetap hidup. Cukup beberapa menit latihan hari ini untuk menjaga semangatmu tetap terjaga.",
      button: "Lanjutkan belajar",
    },
    newDevice: {
      subject: "Login baru ke akun Lingo Booth Anda",
      heading: "Login dari perangkat baru",
      greeting: "Halo {name}, kami mendeteksi adanya login baru ke akun Lingo Booth Anda.",
      detailsIntro: "Berikut rinciannya:",
      labelWhen: "Waktu",
      labelWhere: "Lokasi",
      labelDevice: "Perangkat",
      reassure: "Jika ini memang Anda, tidak ada tindakan yang perlu dilakukan.",
      warn: "Jika Anda tidak mengenali aktivitas ini, segera atur ulang kata sandi Anda untuk menjaga keamanan akun.",
      button: "Amankan akun saya",
    },
    reset: {
      subject: "Atur ulang kata sandi Lingo Booth Anda",
      heading: "Atur ulang kata sandi Anda",
      greeting: "Halo {name}, kami menerima permintaan untuk mengatur ulang kata sandi Anda. Klik tombol di bawah ini untuk memilih kata sandi baru.",
      button: "Atur ulang kata sandi",
      copyLink: "Atau salin dan tempel tautan ini ke browser Anda:",
      expiry: "Tautan ini kedaluwarsa dalam 1 jam. Jika Anda tidak meminta pengaturan ulang kata sandi, Anda dapat mengabaikan email ini dengan aman.",
      textIntro: "Halo {name}, kami menerima permintaan untuk mengatur ulang kata sandi Lingo Booth Anda. Kunjungi tautan ini untuk memilih kata sandi baru:",
      textExpiry: "Tautan ini kedaluwarsa dalam 1 jam. Jika Anda tidak meminta pengaturan ulang kata sandi, Anda dapat mengabaikan email ini dengan aman.",
    },
  },

  ms: {
    welcome: {
      subject: "Selamat datang ke Lingo Booth!",
      heading: "Selamat datang ke Lingo Booth",
      greeting: "Hai {name}, selamat menyertai kami!",
      body: "Kami amat gembira anda menyertai kami. Lingo Booth membantu anda belajar bahasa untuk perbualan sebenar — dan latihan sedikit setiap hari akan membawa kemajuan yang besar. Bersedia untuk mula?",
      button: "Mula belajar",
    },
    login: {
      subject: "Selamat kembali ke Lingo Booth",
      heading: "Selamat kembali!",
      greeting: "Hai {name}, gembira dapat berjumpa anda lagi.",
      body: "Sambung semula dari tempat anda berhenti dan kekalkan streak anda. Beberapa minit latihan hari ini sudah cukup untuk mengekalkan momentum anda.",
      button: "Sambung belajar",
    },
    newDevice: {
      subject: "Log masuk baharu ke akaun Lingo Booth anda",
      heading: "Log masuk dari peranti baharu",
      greeting: "Salam {name}, kami mengesan log masuk baharu ke akaun Lingo Booth anda.",
      detailsIntro: "Berikut adalah butirannya:",
      labelWhen: "Masa",
      labelWhere: "Lokasi",
      labelDevice: "Peranti",
      reassure: "Jika ini memang anda, tiada tindakan diperlukan.",
      warn: "Jika anda tidak mengenali aktiviti ini, tetapkan semula kata laluan anda dengan segera untuk memastikan keselamatan akaun anda.",
      button: "Amankan akaun saya",
    },
    reset: {
      subject: "Tetapkan semula kata laluan Lingo Booth anda",
      heading: "Tetapkan semula kata laluan anda",
      greeting: "Salam {name}, kami menerima permintaan untuk menetapkan semula kata laluan anda. Klik butang di bawah untuk memilih kata laluan baharu.",
      button: "Tetapkan semula kata laluan",
      copyLink: "Atau salin dan tampal pautan ini ke pelayar anda:",
      expiry: "Pautan ini akan tamat tempoh dalam masa 1 jam. Jika anda tidak meminta penetapan semula kata laluan, anda boleh mengabaikan e-mel ini dengan selamat.",
      textIntro: "Salam {name}, kami menerima permintaan untuk menetapkan semula kata laluan Lingo Booth anda. Layari pautan ini untuk memilih kata laluan baharu:",
      textExpiry: "Pautan ini akan tamat tempoh dalam masa 1 jam. Jika anda tidak meminta penetapan semula kata laluan, anda boleh mengabaikan e-mel ini dengan selamat.",
    },
  },

  fil: {
    welcome: {
      subject: "Maligayang pagdating sa Lingo Booth!",
      heading: "Maligayang pagdating sa Lingo Booth",
      greeting: "Hi {name}, maligayang pagsali sa amin!",
      body: "Tuwang-tuwa kaming makasama ka. Tinutulungan ka ng Lingo Booth na matuto ng wika para sa tunay na pag-uusap — at ang kaunting pagsasanay araw-araw ay malaki ang naitutulong. Handa ka na bang magsimula?",
      button: "Simulan ang pag-aaral",
    },
    login: {
      subject: "Maligayang pagbabalik sa Lingo Booth",
      heading: "Maligayang pagbabalik!",
      greeting: "Hi {name}, masaya kaming makita kang muli.",
      body: "Ituloy mo lang kung saan ka huminto at panatilihing buhay ang iyong streak. Ilang minuto lang ng pagsasanay ngayon ay sapat na para mapanatili ang iyong momentum.",
      button: "Ipagpatuloy ang pag-aaral",
    },
    newDevice: {
      subject: "Bagong pag-sign in sa iyong Lingo Booth account",
      heading: "Pag-sign in mula sa bagong device",
      greeting: "Hi {name}, may napansin kaming bagong pag-sign in sa iyong Lingo Booth account.",
      detailsIntro: "Narito ang mga detalye:",
      labelWhen: "Kailan",
      labelWhere: "Saan",
      labelDevice: "Device",
      reassure: "Kung ikaw ito, hindi na kailangang gumawa ng anuman.",
      warn: "Kung hindi mo nakikilala ang aktibidad na ito, agad na i-reset ang iyong password upang manatiling ligtas ang iyong account.",
      button: "Protektahan ang aking account",
    },
    reset: {
      subject: "I-reset ang iyong Lingo Booth password",
      heading: "I-reset ang iyong password",
      greeting: "Hi {name}, nakatanggap kami ng kahilingan na i-reset ang iyong password. I-click ang button sa ibaba upang pumili ng bago.",
      button: "I-reset ang password",
      copyLink: "O kopyahin at i-paste ang link na ito sa iyong browser:",
      expiry: "Mag-e-expire ang link na ito sa loob ng 1 oras. Kung hindi ka humiling ng pag-reset ng password, maaari mong balewalain nang ligtas ang email na ito.",
      textIntro: "Hi {name}, nakatanggap kami ng kahilingan na i-reset ang iyong Lingo Booth password. Bisitahin ang link na ito upang pumili ng bago:",
      textExpiry: "Mag-e-expire ang link na ito sa loob ng 1 oras. Kung hindi ka humiling ng pag-reset ng password, maaari mong balewalain nang ligtas ang email na ito.",
    },
  },

  hi: {
    welcome: {
      subject: "Lingo Booth में आपका स्वागत है!",
      heading: "Lingo Booth में आपका स्वागत है",
      greeting: "नमस्ते {name}, आपका स्वागत है!",
      body: "आपके जुड़ने से हम बहुत खुश हैं। Lingo Booth आपको असल बातचीत के लिए भाषा सीखने में मदद करता है — और रोज़ थोड़ा-सा अभ्यास बहुत आगे तक ले जाता है। शुरू करने के लिए तैयार हैं?",
      button: "सीखना शुरू करें",
    },
    login: {
      subject: "Lingo Booth में आपका फिर से स्वागत है",
      heading: "फिर से स्वागत है!",
      greeting: "नमस्ते {name}, आपको दोबारा देखकर बहुत अच्छा लगा।",
      body: "जहाँ छोड़ा था वहीं से आगे बढ़ें और अपनी स्ट्रीक बनाए रखें। आज बस कुछ मिनटों का अभ्यास आपकी गति को बनाए रखेगा।",
      button: "सीखना जारी रखें",
    },
    newDevice: {
      subject: "आपके Lingo Booth खाते में नया साइन-इन",
      heading: "नए डिवाइस से साइन-इन",
      greeting: "नमस्ते {name}, हमने आपके Lingo Booth खाते में एक नया साइन-इन देखा।",
      detailsIntro: "विवरण इस प्रकार हैं:",
      labelWhen: "कब",
      labelWhere: "कहाँ",
      labelDevice: "डिवाइस",
      reassure: "अगर यह आप ही थे, तो कोई कार्रवाई करने की आवश्यकता नहीं है।",
      warn: "अगर आप इस गतिविधि को नहीं पहचानते, तो अपने खाते को सुरक्षित रखने के लिए तुरंत अपना पासवर्ड रीसेट करें।",
      button: "मेरा खाता सुरक्षित करें",
    },
    reset: {
      subject: "अपना Lingo Booth पासवर्ड रीसेट करें",
      heading: "अपना पासवर्ड रीसेट करें",
      greeting: "नमस्ते {name}, हमें आपका पासवर्ड रीसेट करने का अनुरोध मिला है। नया पासवर्ड चुनने के लिए नीचे दिए गए बटन पर क्लिक करें।",
      button: "पासवर्ड रीसेट करें",
      copyLink: "या इस लिंक को कॉपी करके अपने ब्राउज़र में पेस्ट करें:",
      expiry: "यह लिंक 1 घंटे में समाप्त हो जाएगा। अगर आपने पासवर्ड रीसेट का अनुरोध नहीं किया था, तो आप इस ईमेल को अनदेखा कर सकते हैं।",
      textIntro: "नमस्ते {name}, हमें आपका Lingo Booth पासवर्ड रीसेट करने का अनुरोध मिला है। नया पासवर्ड चुनने के लिए इस लिंक पर जाएँ:",
      textExpiry: "यह लिंक 1 घंटे में समाप्त हो जाएगा। अगर आपने पासवर्ड रीसेट का अनुरोध नहीं किया था, तो आप इस ईमेल को अनदेखा कर सकते हैं।",
    },
  },

  bn: {
    welcome: {
      subject: "Lingo Booth-এ স্বাগতম!",
      heading: "Lingo Booth-এ স্বাগতম",
      greeting: "হ্যালো {name}, স্বাগতম!",
      body: "আপনাকে পেয়ে আমরা দারুণ খুশি। Lingo Booth আপনাকে বাস্তব কথোপকথনের জন্য একটি ভাষা শিখতে সাহায্য করে — আর প্রতিদিন একটুখানি অনুশীলন অনেক দূর এগিয়ে দেয়। শুরু করতে প্রস্তুত?",
      button: "শেখা শুরু করুন",
    },
    login: {
      subject: "Lingo Booth-এ আবার স্বাগতম",
      heading: "আবার স্বাগতম!",
      greeting: "হ্যালো {name}, আপনাকে আবার দেখে খুব ভালো লাগছে।",
      body: "যেখানে থেমেছিলেন ঠিক সেখান থেকেই আবার শুরু করুন এবং আপনার স্ট্রিক ধরে রাখুন। আজ কেবল কয়েক মিনিটের অনুশীলনই আপনার গতি বজায় রাখবে।",
      button: "শেখা চালিয়ে যান",
    },
    newDevice: {
      subject: "আপনার Lingo Booth অ্যাকাউন্টে নতুন সাইন-ইন",
      heading: "নতুন ডিভাইস থেকে সাইন-ইন",
      greeting: "হ্যালো {name}, আমরা আপনার Lingo Booth অ্যাকাউন্টে একটি নতুন সাইন-ইন লক্ষ্য করেছি।",
      detailsIntro: "বিস্তারিত তথ্য নিচে দেওয়া হলো:",
      labelWhen: "কখন",
      labelWhere: "কোথায়",
      labelDevice: "ডিভাইস",
      reassure: "যদি এটি আপনিই করে থাকেন, তাহলে কোনো পদক্ষেপ নেওয়ার প্রয়োজন নেই।",
      warn: "যদি আপনি এই কার্যকলাপ চিনতে না পারেন, তাহলে আপনার অ্যাকাউন্ট সুরক্ষিত রাখতে এখনই আপনার পাসওয়ার্ড রিসেট করুন।",
      button: "আমার অ্যাকাউন্ট সুরক্ষিত করুন",
    },
    reset: {
      subject: "আপনার Lingo Booth পাসওয়ার্ড রিসেট করুন",
      heading: "আপনার পাসওয়ার্ড রিসেট করুন",
      greeting: "হ্যালো {name}, আমরা আপনার পাসওয়ার্ড রিসেট করার একটি অনুরোধ পেয়েছি। নতুন একটি পাসওয়ার্ড বেছে নিতে নিচের বোতামে ক্লিক করুন।",
      button: "পাসওয়ার্ড রিসেট করুন",
      copyLink: "অথবা এই লিঙ্কটি কপি করে আপনার ব্রাউজারে পেস্ট করুন:",
      expiry: "এই লিঙ্কটি ১ ঘণ্টার মধ্যে মেয়াদ শেষ হয়ে যাবে। যদি আপনি পাসওয়ার্ড রিসেটের অনুরোধ না করে থাকেন, তাহলে আপনি নিশ্চিন্তে এই ইমেলটি উপেক্ষা করতে পারেন।",
      textIntro: "হ্যালো {name}, আমরা আপনার Lingo Booth পাসওয়ার্ড রিসেট করার একটি অনুরোধ পেয়েছি। নতুন একটি পাসওয়ার্ড বেছে নিতে এই লিঙ্কে যান:",
      textExpiry: "এই লিঙ্কটি ১ ঘণ্টার মধ্যে মেয়াদ শেষ হয়ে যাবে। যদি আপনি পাসওয়ার্ড রিসেটের অনুরোধ না করে থাকেন, তাহলে আপনি নিশ্চিন্তে এই ইমেলটি উপেক্ষা করতে পারেন।",
    },
  },

  ta: {
    welcome: {
      subject: "Lingo Booth-க்கு வரவேற்கிறோம்!",
      heading: "Lingo Booth-க்கு வரவேற்கிறோம்",
      greeting: "வணக்கம் {name}, உங்களை வரவேற்கிறோம்!",
      body: "நீங்கள் இணைந்ததில் நாங்கள் மிகவும் மகிழ்ச்சி அடைகிறோம். உண்மையான உரையாடல்களுக்காக ஒரு மொழியைக் கற்க Lingo Booth உதவுகிறது — தினமும் சிறிது பயிற்சி பெரிய மாற்றத்தை ஏற்படுத்தும். தொடங்கத் தயாரா?",
      button: "கற்கத் தொடங்குங்கள்",
    },
    login: {
      subject: "Lingo Booth-க்கு மீண்டும் வரவேற்கிறோம்",
      heading: "மீண்டும் வரவேற்கிறோம்!",
      greeting: "வணக்கம் {name}, உங்களை மீண்டும் சந்திப்பதில் மகிழ்ச்சி.",
      body: "நீங்கள் நிறுத்திய இடத்திலிருந்தே தொடர்ந்து உங்கள் தொடர் சாதனையைத் தக்கவைத்துக் கொள்ளுங்கள். இன்று சில நிமிடப் பயிற்சியே உங்கள் வேகத்தைத் தொடர்ந்து வைத்திருக்கும்.",
      button: "கற்றலைத் தொடருங்கள்",
    },
    newDevice: {
      subject: "உங்கள் Lingo Booth கணக்கில் புதிய உள்நுழைவு",
      heading: "புதிய சாதனத்திலிருந்து உள்நுழைவு",
      greeting: "வணக்கம் {name}, உங்கள் Lingo Booth கணக்கில் ஒரு புதிய உள்நுழைவை நாங்கள் கவனித்தோம்.",
      detailsIntro: "விவரங்கள் இதோ:",
      labelWhen: "எப்போது",
      labelWhere: "எங்கே",
      labelDevice: "சாதனம்",
      reassure: "இது நீங்களே செய்திருந்தால், எந்த நடவடிக்கையும் தேவையில்லை.",
      warn: "இந்தச் செயல்பாட்டை நீங்கள் அறியாதிருந்தால், உங்கள் கணக்கைப் பாதுகாப்பாக வைத்திருக்க உடனடியாக உங்கள் கடவுச்சொல்லை மீட்டமைக்கவும்.",
      button: "என் கணக்கைப் பாதுகாக்கவும்",
    },
    reset: {
      subject: "உங்கள் Lingo Booth கடவுச்சொல்லை மீட்டமைக்கவும்",
      heading: "உங்கள் கடவுச்சொல்லை மீட்டமைக்கவும்",
      greeting: "வணக்கம் {name}, உங்கள் கடவுச்சொல்லை மீட்டமைக்க ஒரு கோரிக்கையை நாங்கள் பெற்றோம். புதிய கடவுச்சொல்லைத் தேர்ந்தெடுக்க கீழே உள்ள பொத்தானைக் கிளிக் செய்யவும்.",
      button: "கடவுச்சொல்லை மீட்டமைக்கவும்",
      copyLink: "அல்லது இந்த இணைப்பை நகலெடுத்து உங்கள் உலாவியில் ஒட்டவும்:",
      expiry: "இந்த இணைப்பு 1 மணி நேரத்தில் காலாவதியாகும். நீங்கள் கடவுச்சொல் மீட்டமைப்பைக் கோரவில்லை என்றால், இந்த மின்னஞ்சலைப் பாதுகாப்பாகப் புறக்கணிக்கலாம்.",
      textIntro: "வணக்கம் {name}, உங்கள் Lingo Booth கடவுச்சொல்லை மீட்டமைக்க ஒரு கோரிக்கையை நாங்கள் பெற்றோம். புதிய கடவுச்சொல்லைத் தேர்ந்தெடுக்க இந்த இணைப்பைப் பார்வையிடவும்:",
      textExpiry: "இந்த இணைப்பு 1 மணி நேரத்தில் காலாவதியாகும். நீங்கள் கடவுச்சொல் மீட்டமைப்பைக் கோரவில்லை என்றால், இந்த மின்னஞ்சலைப் பாதுகாப்பாகப் புறக்கணிக்கலாம்.",
    },
  },
};

// Footer tagline per language (mirrors the verification email footer).
const FOOTERS = {
  en: "Learn languages for real conversations",
  ko: "실제 대화를 위한 언어 학습",
  ja: "実際の会話のための語学学習",
  zh: "学习语言，进行真实对话",
  es: "Aprende idiomas para conversaciones reales",
  pt: "Aprenda idiomas para conversas reais",
  it: "Impara le lingue per conversazioni reali",
  fr: "Apprenez des langues pour de vraies conversations",
  de: "Sprachen lernen für echte Gespräche",
  nl: "Leer talen voor echte gesprekken",
  ru: "Учите языки для реальных разговоров",
  ar: "تعلم اللغات للمحادثات الحقيقية",
  he: "למד שפות לשיחות אמיתיות",
  tr: "Gerçek konuşmalar için dil öğrenin",
  id: "Belajar bahasa untuk percakapan nyata",
  ms: "Belajar bahasa untuk perbualan sebenar",
  fil: "Matuto ng mga wika para sa totoong pag-uusap",
  hi: "वास्तविक बातचीत के लिए भाषाएँ सीखें",
  bn: "বাস্তব কথোপকথনের জন্য ভাষা শিখুন",
  ta: "உண்மையான உரையாடல்களுக்கான மொழிகளைக் கற்றுக்கொள்ளுங்கள்",
};

// Return the localized strings for an email type, falling back to English for
// any missing language or key.
function getEmailStrings(type, lang) {
  const langBlock = STRINGS[lang] || STRINGS.en;
  return { ...STRINGS.en[type], ...(langBlock[type] || {}) };
}

function getFooter(lang) {
  return FOOTERS[lang] || FOOTERS.en;
}

module.exports = { STRINGS, FOOTERS, getEmailStrings, getFooter };
