// Level 1 Unit 3 — Locations & Existence (Modern Hebrew)
// Functions: saying where things are, using prepositions of place,
// asking and answering "where is...?", existence yesh/ein.

const createContentItem = (target, translit, note, type = 'word', example = '', exampleNote = '', breakdown = null, activityIds = []) => ({
  type, activityIds, targetText: target, romanization: translit, nativeText: note, pronunciation: translit,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'he-l1u3-orientation', pronunciation: 'he-l1u3-pronunciation',
  vocabPlaces: 'he-l1u3-vocab-places', vocabPrepositions: 'he-l1u3-vocab-prepositions',
  grammarYesh: 'he-l1u3-grammar-yesh', grammarLocative: 'he-l1u3-grammar-locative',
  grammarQuestionEifo: 'he-l1u3-grammar-question-eifo',
  reading: 'he-l1u3-reading', listening: 'he-l1u3-listening', writing: 'he-l1u3-writing',
  culture: 'he-l1u3-culture', task: 'he-l1u3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do', goals: ['Name 12 places in a typical Israeli city (cafe, bus stop, post office, market).', 'Use prepositions of place to say where something is.', 'Use יש (yesh) and אין (ein) to describe what exists or doesn\'t in a location.'], task: 'By the end you should describe your apartment, your university, and your neighborhood in Hebrew.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Prepositions and reduced vowels', goals: ['Reduce ב- (be-, in) and ל- (le-, to) to schwa in casual speech.', 'Pronounce the merged ב + ה- → בַּ (ba-) and ל + ה- → לַ (la-) when defining.', 'Apply chet correctly in חדר (cheder, room), חוף (chof, beach), and חוץ (chutz, outside).'], task: 'Read the prepositional pairs aloud, contrasting indefinite be-/le- with definite ba-/la-.' },
  { id: ACT.vocabPlaces, section: 'Vocabulary I', title: 'Places in a city', goals: ['Memorize 12 places with their gender.', 'Use each place in a "where is...?" question.'], task: 'Identify each place type and say one sentence about where it is in your city.' },
  { id: ACT.vocabPrepositions, section: 'Vocabulary II', title: 'Prepositions of place', goals: ['Use על (al, on), ב- (be-, in), ליד (lyad, next to), מתחת ל- (mitachat le-, under), מעל (me\'al, above), מאחורי (me-achorei, behind), לפני (lifnei, in front of).', 'Combine prepositions with possessive endings: לידי (lyadi, next to me), בו (bo, in him/it).'], task: 'Describe the location of 8 objects in a room using different prepositions.' },
  { id: ACT.grammarYesh, section: 'Grammar I', title: 'יש and אין — Existence', goals: ['Use יש (yesh, "there is") to assert existence: יש קפה בשולחן (yesh kafe ba-shulchan, "there\'s coffee on the table").', 'Use אין (ein, "there is not") to negate existence: אין זמן (ein zman, "there\'s no time").', 'Apply the same pattern for possession: יש לי (yesh li, "I have"), אין לי (ein li, "I don\'t have").'], task: 'Write 6 sentences with yesh/ein covering both existence and possession.' },
  { id: ACT.grammarLocative, section: 'Grammar II', title: 'Locative ב- and ל-', goals: ['Use ב- (be-) for "in/at" stationary location: בבית (ba-bayit, at home), באוניברסיטה (ba-universita, at the university).', 'Use ל- (le-) for "to" direction: לבית (la-bayit, to home), לאוניברסיטה (la-universita, to the university).', 'Apply the merger with definite: be + ha → ba (בַּ); le + ha → la (לַ).'], task: 'Convert 5 indefinite location phrases (in a house) to definite (in the house).' },
  { id: ACT.grammarQuestionEifo, section: 'Grammar III', title: 'Asking איפה / לאן / מאיפה', goals: ['Use איפה (eifo, where) for stationary location: איפה הספר? (eifo ha-sefer?).', 'Use לאן (le\'an, to where) for direction toward: לאן אתה הולך? (le\'an ata holech?).', 'Use מאיפה (me\'efo, from where) for origin: מאיפה את? (me\'efo at?).'], task: 'Ask the AI tutor three location questions using each of the three forms.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'A walk through Jerusalem', goals: ['Read a paragraph describing a walk from Hebrew University down to the Old City.', 'Identify all location markers and prepositions.'], task: 'Read aloud once, then answer five questions about the route.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Asking for directions', goals: ['Follow a dialogue where a tourist asks for directions to the Western Wall.', 'Reproduce the conversation substituting your own location.'], task: 'Listen and answer the locals\' clarifying questions.' },
  { id: ACT.writing, section: 'Writing', title: 'Describe your neighborhood', goals: ['Write 5 sentences about places near your home.', 'Use at least three prepositions and three definite/indefinite contrasts.'], task: 'Compose your neighborhood description.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Israeli geography in conversation', goals: ['Recognize the three major Israeli cities: Jerusalem (capital), Tel Aviv (commercial/cultural), Haifa (port/tech).', 'Understand the casual division of Israel into "tzafon" (north), "merkaz" (center), "darom" (south).'], task: 'Place five Israeli cities on a mental map using north/center/south.' },
  { id: ACT.task, section: 'Task', title: 'Finding your way at Hebrew University', goals: ['Combine location vocabulary, yesh/ein, and prepositions in a wayfinding scene.', 'Ask the AI tutor where three specific places are on the Mount Scopus campus.'], task: 'Roleplay arriving at Hebrew University and asking another student for directions to the library, the cafeteria, and your seminar room.' },
];

const lesson = {
  title: 'Level 1 · Unit 3: איפה? — Locations and Existence',
  category: 'locations', difficulty: 'beginner', targetLang: 'he', nativeLang: 'en', track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-where', label: 'Asking where', goal: 'Use eifo/le\'an/me\'efo correctly for stationary, direction, and origin questions.' },
    { id: 'describing-location', label: 'Describing location', goal: 'Use prepositions and yesh/ein to describe what is where.' },
    { id: 'giving-directions', label: 'Giving directions', goal: 'Direct someone to a nearby place using basic prepositions and verbs of motion.' },
  ],
  relatedPools: ['topic-places', 'topic-geography'],
  content: [
    createContentItem('איפה אנחנו?', 'eifo anachnu?', 'A simple location question: "where are we?" — uses the basic question word איפה for stationary location. The grammar will spread to all locational expressions: at home, in the library, next to the table.', 'word', 'איפה אנחנו? — בכיתה. — eifo anachnu? — ba-kita — "Where are we?" "In the classroom."', 'איפה specifically asks about stationary location; for direction-to use לאן.', null, [ACT.orientation]),
    createContentItem('בבית', 'ba-bayit', 'In the house / at home. The classic example of ב + ה merging to בַּ (ba-). Bayit = "house"; ha-bayit = "the house"; ba-bayit = "in/at the house" (with the definite article absorbed).', 'word', 'אני בבית. — ani ba-bayit — "I am at home."', 'Israelis use ba-bayit as "at home" without needing a possessive — context implies "my home".', null, [ACT.pronunciation]),
    createContentItem('בכיתה', 'ba-kita', 'In the classroom. Same pattern: be + ha + kita → ba-kita. The classroom is feminine, but the contraction is the same as for masculine nouns.', 'word', 'אני בכיתה ומחכה. — ani ba-kita u-mechake — "I am in the classroom and waiting."', 'The merger be + ha → ba is one of the first contractions Hebrew learners master; identical pattern with le + ha → la.', null, [ACT.pronunciation]),
    createContentItem('חדר', 'cheder (CHE-der)', 'Room. Masculine segolate noun (mil\'el stress). Plural: חדרים (chadarim, with vowel shift). The initial chet /kh/ is throat-back.', 'word', 'החדר שלי קטן. — ha-cheder sheli katan — "My room is small."', 'Same root ח-ד-ר gives the verb לחדור (lachdor, to penetrate).', null, [ACT.pronunciation]),
    createContentItem('בית', 'bayit', 'House, home. Masculine. Plural: בתים (batim, irregular).', 'word', 'הבית שלנו בתל אביב. — ha-bayit shelanu be-tel aviv — "Our house is in Tel Aviv."', 'The construct form בית (beit) appears in many compounds: בית ספר (beit sefer, school), בית קפה (beit kafe, cafe).', null, [ACT.vocabPlaces]),
    createContentItem('אוניברסיטה', 'universita', 'University. Feminine. Borrowed; mil\'ra. The Hebrew University = האוניברסיטה העברית.', 'word', 'אני באוניברסיטה. — ani ba-universita — "I am at the university."', 'Each Israeli university has a nickname: האוניברסיטה (the university — typically refers to Hebrew U), הטכניון (Technion), אוני׳ת״א (Tel Aviv U).', null, [ACT.vocabPlaces]),
    createContentItem('ספריה', 'sifriya', 'Library. Feminine. From the root ס-פ-ר (book, write).', 'word', 'הספריה פתוחה עד עשר. — ha-sifriya ptucha ad eser — "The library is open until ten."', 'The National Library of Israel (הספרייה הלאומית) is on the Givat Ram campus of Hebrew U.', null, [ACT.vocabPlaces]),
    createContentItem('בית קפה', 'beit kafe', 'Cafe. Construct phrase: literally "house of coffee". Masculine (matching beit).', 'word', 'נפגש בבית קפה. — nipagesh be-veit kafe — "Let\'s meet at a cafe."', 'Israeli cafe culture is intense; cafes are workplaces, meeting spots, and social hubs.', null, [ACT.vocabPlaces]),
    createContentItem('מסעדה', 'mis\'ada', 'Restaurant. Feminine. From the root ס-ע-ד (to dine, support).', 'word', 'יש מסעדה טובה ליד. — yesh mis\'ada tova le-yad — "There\'s a good restaurant nearby."', 'Israeli mis\'adot range from upscale Tel Aviv chef restaurants to neighborhood hummus joints.', null, [ACT.vocabPlaces]),
    createContentItem('שוק', 'shuk', 'Market. Masculine. Plural: שווקים (shvakim).', 'word', 'הולכים לשוק? — holchim la-shuk? — "Going to the market?"', 'Famous markets: שוק מחנה יהודה (Mahane Yehuda, Jerusalem), שוק הכרמל (HaCarmel, Tel Aviv).', null, [ACT.vocabPlaces]),
    createContentItem('דואר', 'do\'ar', 'Post office. Masculine.', 'word', 'אני צריך לדואר. — ani tzarich la-do\'ar — "I need to go to the post office."', 'Israel Post (דואר ישראל) handles mail, packages, and some banking services.', null, [ACT.vocabPlaces]),
    createContentItem('בנק', 'bank', 'Bank. Masculine. Borrowed.', 'word', 'הבנק סגור. — ha-bank sagur — "The bank is closed."', 'Israeli banks: בנק לאומי (Leumi), בנק הפועלים (Hapoalim), בנק דיסקונט (Discount). Hours typically 8:30–13:30 weekdays.', null, [ACT.vocabPlaces]),
    createContentItem('בית חולים', 'beit cholim', 'Hospital. Construct: "house of sick people". Masculine.', 'word', 'הדרדה ההדסה. — beit cholim Hadassah — "Hadassah Hospital."', 'Hadassah Medical Center is affiliated with Hebrew University; one of Israel\'s top hospitals.', null, [ACT.vocabPlaces]),
    createContentItem('חוף', 'chof', 'Beach, shore. Masculine. Plural: חופים (chofim). Initial chet /kh/.', 'word', 'אני אוהבת את החוף בתל אביב. — ani ohevet et ha-chof be-tel aviv — "I love the beach in Tel Aviv."', 'Tel Aviv\'s Mediterranean coast is famous; the beaches stretch from Jaffa to Herzliya.', null, [ACT.vocabPlaces]),
    createContentItem('תחנת אוטובוס', 'tachanat otobus', 'Bus stop. Construct: "station of bus". Feminine (tachana).', 'word', 'תחנת האוטובוס בפינה. — tachanat ha-otobus ba-pina — "The bus stop is at the corner."', 'Egged is the main Israeli bus company; Dan operates in the Tel Aviv metro area.', null, [ACT.vocabPlaces]),
    createContentItem('פארק', 'park', 'Park. Masculine. Borrowed.', 'word', 'נלך לפארק. — nelech la-park — "Let\'s go to the park."', 'Famous parks: Gan Sacher (Jerusalem), HaYarkon (Tel Aviv), HaAyalon (Ramat Gan).', null, [ACT.vocabPlaces]),
    createContentItem('רחוב', 'rechov', 'Street. Masculine. Plural: רחובות (rechovot).', 'word', 'אני גר ברחוב יפו. — ani gar bi-rechov Yafo — "I live on Jaffa Street."', 'Israeli streets are often named after biblical figures, prime ministers, and historical events.', null, [ACT.vocabPlaces]),

    createContentItem('על', 'al', 'Preposition "on". Used for surface placement. Combined with possessive endings: עליי (alai, on me), עליך (alecha, on you-m).', 'sentence', 'הספר על השולחן. — ha-sefer al ha-shulchan — "The book is on the table."', 'Also used metaphorically: לדבר על (ledaber al, "to talk about"), חבל על (chaval al, "shame about").', null, [ACT.vocabPrepositions]),
    createContentItem('ב-', 'be- / ba-', 'Preposition "in/at". Attaches directly to the noun. ב + indef = be-; ב + ha- (definite) = ba-.', 'sentence', 'בבית — ba-bayit — "in/at the house"\nבכיתה — ba-kita — "in/at the classroom"', 'The most common Hebrew preposition; covers both stationary location and time (בבוקר, ba-boker, "in the morning").', null, [ACT.vocabPrepositions]),
    createContentItem('ל-', 'le- / la-', 'Preposition "to/for". Attaches directly. le- (indef) → la- (with definite article).', 'sentence', 'לבית — la-bayit — "to/for the house"\nאני הולך לאוניברסיטה — ani holech la-universita — "I\'m going to the university"', 'Also used as the infinitive prefix: ללכת (lalechet, to walk), לאכול (le\'echol, to eat).', null, [ACT.vocabPrepositions]),
    createContentItem('ליד', 'lyad', 'Next to, beside. Compound from ל + יד ("to + hand"). Combined: לידי (lyadi, next to me).', 'sentence', 'הוא יושב לידי. — hu yoshev lyadi — "He sits next to me."', 'The pictorial origin (lyad = "to-hand") is still felt in some idioms.', null, [ACT.vocabPrepositions]),
    createContentItem('מתחת ל-', 'mitachat le-', 'Under. Two-part preposition: מתחת + ל-.', 'sentence', 'התיק מתחת לשולחן. — ha-tik mitachat la-shulchan — "The bag is under the table."', 'The opposite of mitachat is מעל (me\'al, above).', null, [ACT.vocabPrepositions]),
    createContentItem('מעל', 'me\'al', 'Above, over. Often paired with ל- when followed by an object: מעל ל-.', 'sentence', 'המנורה מעל השולחן. — ha-menorah me\'al ha-shulchan — "The lamp is above the table."', 'Also used metaphorically: מעל ומעבר (me\'al u-me\'ever, "above and beyond").', null, [ACT.vocabPrepositions]),
    createContentItem('מאחורי', 'me-achorei', 'Behind. Compound from "from + back of".', 'sentence', 'החתול מאחורי הכיסא. — ha-chatul me-achorei ha-kise — "The cat is behind the chair."', 'The pair me-achorei (behind) / lifnei (in front of) is the basic spatial axis.', null, [ACT.vocabPrepositions]),
    createContentItem('לפני', 'lifnei', 'In front of, before (time). Same word for spatial "in front of" and temporal "before".', 'sentence', 'יש מכונית לפני הבית. — yesh mechonit lifnei ha-bayit — "There\'s a car in front of the house."\nלפני השיעור. — lifnei ha-shiur — "Before the lesson."', 'The dual meaning (space + time) is parallel to English "before".', null, [ACT.vocabPrepositions]),

    createContentItem('יש', 'yesh', 'There is / there are — the universal existence marker. Same form regardless of number or gender of the noun. Often combined with locational phrases.', 'sentence', 'יש קפה במטבח. — yesh kafe ba-mitbach — "There\'s coffee in the kitchen."\nיש לי שאלה. — yesh li she\'ela — "I have a question" (literally "there is to me a question")', 'Possession in Hebrew uses yesh + ל- (to) + person: yesh li (I have), yesh lecha (you-m have), yesh lah (she has).', null, [ACT.grammarYesh]),
    createContentItem('אין', 'ein', 'There is not / there are not — the negation of yesh. Same usage pattern; combined with ל- for "don\'t have".', 'sentence', 'אין מים. — ein mayim — "There is no water."\nאין לי כסף. — ein li kesef — "I have no money."', 'The pair yesh/ein is one of the most-used Hebrew constructions; you\'ll hear it dozens of times a day.', null, [ACT.grammarYesh]),
    createContentItem('יש ל- + person', 'yesh le- + person', 'Possession construction: "there is to X" = "X has". Combines yesh + ל- + suffix. Singular: yesh li (I have), yesh lecha/lach (you-m/f have), yesh lo (he has), yesh la (she has). Plural: yesh lanu (we have), yesh lachem/lachen (you-pl m/f), yesh lahem/lahen (they-m/f).', 'sentence', 'יש לי חבר בישראל. — yesh li chaver be-yisrael — "I have a friend in Israel."', 'Hebrew has no "to have" verb in present; yesh + ל- carries the meaning instead.', [
      { target: 'יש לי yesh li', note: '"I have"; possessive suffix -i = "me"' },
      { target: 'יש לך yesh lecha/lach', note: '"you-m/f have"' },
      { target: 'יש לו / לה yesh lo / la', note: '"he/she has"' },
    ], [ACT.grammarYesh]),

    createContentItem('איפה', 'eifo', 'Where (stationary). The basic location question word. Always used for asking where something is, not where it\'s going.', 'sentence', 'איפה הספריה? — eifo ha-sifriya? — "Where is the library?"\nאיפה אתה? — eifo ata? — "Where are you?"', 'For "where to/from", use לאן/מאיפה respectively.', null, [ACT.grammarQuestionEifo]),
    createContentItem('לאן', 'le\'an', 'Where to (direction). Used when asking the destination of motion.', 'sentence', 'לאן אתה הולך? — le\'an ata holech? — "Where are you going?"', 'Often paired with verbs of motion: ללכת (lalechet, to walk/go), לנסוע (linso\'a, to travel).', null, [ACT.grammarQuestionEifo]),
    createContentItem('מאיפה', 'me\'efo', 'Where from (origin). Used for asking the source of motion or where someone comes from.', 'sentence', 'מאיפה אתה? — me\'efo ata? — "Where are you from?"', 'The most common follow-up after a name introduction; Israelis almost always ask this within the first 30 seconds.', null, [ACT.grammarQuestionEifo]),

    createContentItem('מהאוניברסיטה לעיר העתיקה', 'me-ha-universita la-ir ha-atika', 'A walk from Hebrew University Mount Scopus down to Jerusalem\'s Old City. Read the paragraph and trace the route.', 'sentence', 'אני סטודנט באוניברסיטה העברית, בקמפוס הר הצופים. מהקמפוס אני יורד ברגל לעיר העתיקה. לפני העיר העתיקה יש שער שכם. אחרי השער, יש שווקים, רחובות צרים, וכנסיות. בסוף אני מגיע לכותל המערבי. ליד הכותל יש כיכר גדולה. שם אני יושב על ספסל ושותה מים.', 'Translation: "I am a student at Hebrew University, on the Mount Scopus campus. From the campus I walk down to the Old City. Before the Old City there is Damascus Gate. After the gate there are markets, narrow streets, and churches. At the end I arrive at the Western Wall. Next to the Wall there is a big plaza. There I sit on a bench and drink water."', [
      { target: 'הר הצופים har ha-tzofim', note: '"Mount Scopus"; Hebrew U\'s historic campus, overlooking the Old City' },
      { target: 'שער שכם sha\'ar shchem', note: 'Damascus Gate; the main northern entrance to the Old City' },
      { target: 'הכותל המערבי ha-kotel ha-ma\'aravi', note: 'the Western Wall (Wailing Wall); Judaism\'s holiest accessible site' },
      { target: 'ברגל ba-regel', note: '"by foot, walking"; literally "in the foot"' },
    ], [ACT.reading]),

    createContentItem('בקשת הנחיות', 'bakashat hanchayot', 'A tourist asks an Israeli for directions to the Western Wall. The dialogue shows direction-asking and basic location-giving.', 'conversation', 'תייר: סליחה, איפה הכותל המערבי?\nישראלי: הכותל בעיר העתיקה.\nתייר: זה רחוק?\nישראלי: לא, כעשר דקות ברגל. אתה הולך ישר, ואז שמאלה.\nתייר: ישר ואז שמאלה?\nישראלי: כן. אחרי השוק, יש כיכר. שם הכותל.\nתייר: תודה רבה!\nישראלי: בבקשה. בהצלחה!', 'Note the Israeli\'s use of compass directions (ישר ישר shamala) and the casual "bakacha / bevakasha" closing.', [
      { target: 'ישר yashar', note: 'straight ahead' },
      { target: 'שמאלה smola', note: 'to the left; -a suffix = directional ("toward")' },
      { target: 'ימינה yamina', note: 'to the right' },
      { target: 'בהצלחה behatzlacha', note: '"good luck / all the best"; standard farewell after giving help' },
    ], [ACT.listening]),

    createContentItem('תרגיל כתיבה', 'targil ktiva', 'Write 5 sentences about places near your home. Use at least three prepositions and three definite/indefinite contrasts.', 'sentence', 'דוגמה: אני גר בירושלים, ברחוב הנביאים. ליד הבית שלי יש בית קפה ובית מרקחת. מאחורי הבית יש פארק קטן. אני אוהב לקרוא בפארק. הספריה לא רחוקה מהבית.', 'Translation: "I live in Jerusalem, on the Street of Prophets. Next to my house there is a cafe and pharmacy. Behind the house there is a small park. I love reading in the park. The library is not far from the house."', null, [ACT.writing]),

    createContentItem('שלוש ערים', 'shalosh arim', 'Israel\'s three major cities: ירושלים (Jerusalem, capital, religious/political center), תל אביב (Tel Aviv, commercial/cultural capital), חיפה (Haifa, port/tech city, Israel\'s "San Francisco"). Each has distinct cultural personalities.', 'sentence', 'ירושלים זה הבירה. תל אביב זה המרכז העסקי. חיפה זה הצפון.', 'Israelis say "Yerushalayim mit\'paleget, Tel Aviv mit\'havelet, Cheifa ovedet" — "Jerusalem prays, Tel Aviv plays, Haifa works."', null, [ACT.culture]),
    createContentItem('צפון מרכז דרום', 'tzafon merkaz darom', 'Casual geographical division of Israel: tzafon (north — Haifa, Galilee), merkaz (center — Tel Aviv, Jerusalem, Sharon plain), darom (south — Be\'er Sheva, Negev, Eilat). Israelis routinely orient by these labels.', 'sentence', 'אני גרה בדרום, בבאר שבע. — ani gara ba-darom, be-Be\'er Sheva — "I live in the south, in Be\'er Sheva."', 'Each region has distinct character: north is greener, center is densest, south is desert.', null, [ACT.culture]),

    createContentItem('משימה: מציאת דרך בקמפוס', 'mesima: metzi\'at derech ba-kampus', 'Roleplay arriving at Hebrew University Mount Scopus campus and asking a student for directions to three places: the library, the cafeteria, and your seminar room. Use eifo, ba-, prepositions of place, and yesh/ein.', 'conversation', '[Mount Scopus campus, first day]\nאתה: סליחה, איפה הספריה?\nסטודנט: הספריה בבניין הראשי, בקומה השנייה.\nאתה: ואיפה הקפיטריה?\nסטודנט: יש קפיטריה לפני הספריה, ועוד אחת מאחורי הבניין.\nאתה: יש לך מפה?\nסטודנט: אין לי, אבל יש מפה ליד הכניסה.\nאתה: תודה!\nסטודנט: בבקשה. בהצלחה!', 'Six-turn exchange; the AI tutor will respond to your phrasing and adapt directions to the campus layout.', null, [ACT.task]),
  ],
};

module.exports = lesson;
