// Level 1 Unit 5 — Life in Israel (Modern Hebrew)
// Functions: talking about Israeli culture, places, food, family, daily life;
// answering "what is life like in Israel?" with vocabulary anchored to real places.

const createContentItem = (target, translit, note, type = 'word', example = '', exampleNote = '', breakdown = null, activityIds = []) => ({
  type, activityIds, targetText: target, romanization: translit, nativeText: note, pronunciation: translit,
  exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'he-l1u5-orientation', pronunciation: 'he-l1u5-pronunciation',
  vocabCities: 'he-l1u5-vocab-cities', vocabFood: 'he-l1u5-vocab-food', vocabFamily: 'he-l1u5-vocab-family',
  grammarPossession: 'he-l1u5-grammar-possession', grammarAdjectives: 'he-l1u5-grammar-adjectives',
  reading: 'he-l1u5-reading', listening: 'he-l1u5-listening', writing: 'he-l1u5-writing',
  culture: 'he-l1u5-culture', task: 'he-l1u5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do', goals: ['Name 10 major Israeli cities and the regions they\'re in.', 'Describe 10 iconic Israeli foods.', 'Name 12 family relations with gender.'], task: 'By the end you should describe Israeli daily life vividly to a friend at home.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Names with Hebrew sounds', goals: ['Pronounce city names with correct stress: yeruSHALaim, tel aVIV, cheiFA, be\'ER SHEva.', 'Apply chet in Cheifa and Hanukkah words.', 'Pronounce family terms with stress: aba (a-BA), ima (i-MA), achot (a-CHOT, mil\'ra).'], task: 'Pronounce 8 names and family terms with correct stress.' },
  { id: ACT.vocabCities, section: 'Vocabulary I', title: 'Israeli cities & places', goals: ['Memorize 10 cities and 5 famous sites.', 'Pair each with the region (north/center/south).'], task: 'Locate each city on a mental map of Israel.' },
  { id: ACT.vocabFood, section: 'Vocabulary II', title: 'Israeli foods', goals: ['Memorize 10 iconic Israeli foods (hummus, shakshuka, falafel, sabich).', 'Know the origin of each (Arab, Mizrahi Jewish, Yemenite, etc.).'], task: 'Order three Israeli dishes in Hebrew.' },
  { id: ACT.vocabFamily, section: 'Vocabulary III', title: 'Family vocabulary', goals: ['Memorize 12 family terms with gender (father, mother, sibling, child, etc.).', 'Apply possessive endings: my dad (aba sheli), her mom (ima shela).'], task: 'Introduce 4 family members with their relations.' },
  { id: ACT.grammarPossession, section: 'Grammar I', title: 'Possession with של', goals: ['Use של (shel, "of") to mark possession: הספר של דני (ha-sefer shel Dani, "Dani\'s book").', 'Combine של with pronoun endings: שלי (sheli, mine), שלך (shelcha/shelach), שלו (shelo), שלה (shela).', 'Distinguish from the older construct possession (smichut) — Level 3 topic.'], task: 'Construct 6 possessive phrases for family members and possessions.' },
  { id: ACT.grammarAdjectives, section: 'Grammar II', title: 'Adjective agreement', goals: ['Apply masculine/feminine and singular/plural agreement to adjectives.', 'Use טוב (tov) → tova / tovim / tovot; גדול (gadol) → gdola / gdolim / gdolot.', 'Place adjectives AFTER the noun (not before): בית גדול (bayit gadol, big house) not gadol bayit.'], task: 'Describe 5 nouns with appropriate adjective agreement.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: 'My Israel', goals: ['Read a paragraph by an immigrant describing their Israel.', 'Identify all city, food, and family references.'], task: 'Read aloud and answer six comprehension questions.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: 'Tour guide overview', goals: ['Follow a brief tour-guide introduction to Israel\'s regions.', 'Identify the cities and what each is famous for.'], task: 'Match each region to one cultural feature.' },
  { id: ACT.writing, section: 'Writing', title: 'A letter home about Israel', goals: ['Write 8 sentences about your impressions of Israel.', 'Use possessives, adjective agreement, and vocabulary from this unit.'], task: 'Compose your letter.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Israel\'s ethnic mosaic', goals: ['Understand the basic Jewish ethnic divisions: Ashkenazi (European-origin), Mizrahi/Sephardi (Middle Eastern/Iberian), Ethiopian.', 'Know about Arab Israelis (~20% of population), Druze, Bedouin, and Christian communities.', 'Recognize religious-secular continuum: chiloni (secular), masorti (traditional), dati (religious), charedi (ultra-orthodox).'], task: 'Match three Israeli foods to their ethnic origin.' },
  { id: ACT.task, section: 'Task', title: 'Introduce Israel to a visitor', goals: ['Combine cities, food, family, and culture vocabulary in a continuous Israel-overview.', 'Speak for ~2 minutes describing Israel to a foreigner.'], task: 'Roleplay as a tour guide showing a foreign student Israel\'s highlights.' },
];

const lesson = {
  title: 'Level 1 · Unit 5: החיים בישראל — Life in Israel',
  category: 'culture', difficulty: 'beginner', targetLang: 'he', nativeLang: 'en', track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describing-cities', label: 'Describing cities', goal: 'Name a city, locate it, and say one famous feature.' },
    { id: 'ordering-food', label: 'Ordering iconic food', goal: 'Order falafel, hummus, or shakshuka and add a drink.' },
    { id: 'introducing-family', label: 'Introducing family', goal: 'Present 3 family members with names, ages, and roles.' },
  ],
  relatedPools: ['topic-culture', 'topic-geography', 'topic-family'],
  content: [
    createContentItem('ישראל', 'Yisrael', 'The State of Israel — מדינת ישראל (medinat Yisrael). Founded 1948, capital Jerusalem (Yerushalayim). Population ~9.5M; languages Hebrew (official), Arabic (official, demoted to "special status" in 2018), English (de facto). The lesson covers the country\'s cities, food, family terms, and ethnic mosaic.', 'word', 'אני בישראל. — ani be-yisrael — "I am in Israel."', 'Note: ישראלי (yisre\'eli) is the nationality (Israeli); יהודי (yehudi) is the religion/ethnicity (Jewish); not the same.', null, [ACT.orientation]),

    createContentItem('ירושלים', 'Yerushalayim (ye-ru-sha-LAYIM)', 'Jerusalem — Israel\'s capital, ancient holy city of Judaism, Christianity, and Islam. Hebrew University is here on Mount Scopus (Har ha-Tzofim) and Givat Ram. The name ends with the dual suffix -ayim (interpreted as "city of double peace").', 'word', 'ירושלים יפה מאוד. — yerushalayim yafa me\'od — "Jerusalem is very beautiful."', 'Old City divided into Jewish, Muslim, Christian, and Armenian quarters; the Western Wall (ha-Kotel), Dome of the Rock, and Church of the Holy Sepulchre are within walking distance.', null, [ACT.vocabCities]),
    createContentItem('תל אביב', 'Tel Aviv (tel a-VIV)', 'Israel\'s commercial and cultural capital — modern, secular, beach-front. Founded 1909. Home to Tel Aviv University. Nickname: "the city that never sleeps". The Bauhaus White City is a UNESCO heritage site.', 'word', 'אני גרה בתל אביב. — ani gara be-tel aviv — "I live in Tel Aviv."', 'Tel Aviv = "Hill of Spring"; the name was given by founders to evoke renewal.', null, [ACT.vocabCities]),
    createContentItem('חיפה', 'Cheifa (CHEI-fa)', 'Haifa — Israel\'s third-largest city, major port on the Mediterranean. Home to the Technion (Israel Institute of Technology) and the Baha\'i World Center. Built on Mount Carmel.', 'word', 'חיפה היא עיר נמל. — Cheifa hi ir namal — "Haifa is a port city."', 'Haifa has a strong Arab-Jewish coexistence reputation; Hebrew U-Haifa is also here.', null, [ACT.vocabCities]),
    createContentItem('באר שבע', 'Be\'er Sheva (be-ER SHE-va)', 'Be\'er Sheva — capital of the Negev desert in the south. Home to Ben-Gurion University. Mentioned in the Bible as Abraham\'s well; literal meaning "Well of the Seven (oath)".', 'word', 'באר שבע בדרום. — Be\'er Sheva ba-darom — "Be\'er Sheva is in the south."', 'The fastest-growing city in Israel; a major high-tech hub now too.', null, [ACT.vocabCities]),
    createContentItem('אילת', 'Eilat (ei-LAT)', 'Eilat — Israel\'s southernmost city, a Red Sea resort. Tax-free zone; major tourism hub for scuba diving and beach holidays.', 'word', 'אנחנו נוסעים לאילת בקיץ. — anachnu nos\'im le-eilat ba-kayitz — "We\'re going to Eilat in the summer."', 'The Red Sea coral reefs at Eilat are among the northernmost on Earth.', null, [ACT.vocabCities]),
    createContentItem('נצרת', 'Natzeret', 'Nazareth — major Arab Israeli city in the Galilee; childhood home of Jesus. Predominantly Christian Arab and Muslim Arab population.', 'word', 'נצרת בצפון. — Natzeret ba-tzafon — "Nazareth is in the north."', 'Nazareth Illit (Upper Nazareth, now Nof ha-Galil) is the Jewish twin city.', null, [ACT.vocabCities]),
    createContentItem('צפת', 'Tzfat', 'Safed — small mountain city in the Upper Galilee, famous as the historic center of Kabbalah (Jewish mysticism). Artists\' colony and tourist destination.', 'word', 'צפת היא עיר עתיקה. — Tzfat hi ir atika — "Safed is an ancient city."', 'One of the Four Holy Cities of Judaism (with Jerusalem, Hebron, Tiberias).', null, [ACT.vocabCities]),
    createContentItem('הכותל המערבי', 'ha-Kotel ha-ma\'aravi', 'The Western Wall (Wailing Wall) — remnant of the Second Temple\'s retaining wall. Judaism\'s holiest accessible site. Located in the Old City of Jerusalem.', 'word', 'אנשים מתפללים בכותל. — anashim mit\'palelim ba-kotel — "People pray at the Wall."', 'Often just called הכותל (ha-Kotel) without the modifier.', null, [ACT.vocabCities]),
    createContentItem('ים המלח', 'Yam ha-Melach', 'The Dead Sea — saltwater lake, lowest point on Earth (~430m below sea level). Border with Jordan. Famous for therapeutic salts and floating.', 'word', 'אנשים צפים בים המלח. — anashim tzafim be-yam ha-melach — "People float in the Dead Sea."', 'The Dead Sea is shrinking ~1m/year due to water diversion; major environmental issue.', null, [ACT.vocabCities]),
    createContentItem('מצדה', 'Metzada', 'Masada — ancient fortress in the Judean Desert. Site of the 73 CE Jewish revolt against Rome; symbol of Israeli national identity.', 'word', 'עליתי על מצדה לראות את הזריחה. — aliti al Metzada lirot et ha-zricha — "I climbed Masada to see the sunrise."', 'The IDF traditionally held swearing-in ceremonies at Masada with the slogan "Masada shall not fall again".', null, [ACT.vocabCities]),

    createContentItem('חומוס', 'chumus (CHU-mus)', 'Hummus — the iconic Israeli/Levantine chickpea spread. Eaten as a meal with pita, salads, falafel, or pickles. Initial chet /kh/.', 'word', 'בא לי חומוס בפיתה. — ba li chumus be-pita — "I feel like having hummus in a pita."', 'Israel\'s hummus wars (with Lebanon and Palestinian claims) are deeply felt; everyone has a favorite hummusiya (hummus joint).', null, [ACT.vocabFood]),
    createContentItem('פלאפל', 'falafel', 'Falafel — deep-fried chickpea balls in pita, with salads, tehina, and hot sauce. Israel\'s street food and national dish (along with hummus).', 'word', 'פלאפל בפיתה, חריף, בלי עגבניות. — falafel be-pita, charif, bli agvaniyot — "Falafel in pita, spicy, no tomatoes."', 'Origin disputed — Egyptian, Yemenite, or Palestinian. In Israel, eaten standing at a falafel stand for ~20 shekels.', null, [ACT.vocabFood]),
    createContentItem('שקשוקה', 'shakshuka', 'Shakshuka — eggs poached in a spicy tomato-pepper sauce. North African (Tunisian/Libyan) origin, brought by Mizrahi Jews. Standard breakfast or brunch dish.', 'word', 'שקשוקה בבוקר! — shakshuka ba-boker — "Shakshuka for breakfast!"', 'Best shakshuka in Israel is famously at Dr. Shakshuka in Jaffa; debate is endless.', null, [ACT.vocabFood]),
    createContentItem('סביח', 'sabich', 'Sabich — pita stuffed with fried eggplant, boiled egg, tehina, salads. Iraqi-Jewish origin; sabich began as the Shabbat-morning breakfast carried to synagogue, became Israeli street food in the 1960s.', 'word', 'סביח עם תהינה ועמבה. — sabich im techina ve-amba — "Sabich with tehina and amba."', 'Amba is a pickled mango sauce, also of Iraqi-Jewish origin; signature of sabich.', null, [ACT.vocabFood]),
    createContentItem('שווארמה', 'shawarma', 'Shawarma — sliced spit-roasted meat in pita or laffa. Levantine origin, ubiquitous in Israel. Usually chicken or turkey; lamb in higher-end places.', 'word', 'שווארמה בלאפה. — shawarma be-laffa — "Shawarma in laffa (large flatbread)."', 'The Hebrew form שווארמה is borrowed from Arabic shawurma.', null, [ACT.vocabFood]),
    createContentItem('בורקס', 'bourekas', 'Bourekas — flaky pastries stuffed with cheese, potato, or spinach. Sephardi/Balkan origin. Israeli breakfast staple.', 'word', 'אני אוהבת בורקס גבינה. — ani ohevet bourekas gvina — "I love cheese bourekas."', 'Bakeries (מאפיות, ma\'afiyot) sell fresh bourekas daily; Friday-morning bourekas-and-coffee is a national ritual.', null, [ACT.vocabFood]),
    createContentItem('פיתה', 'pita', 'Pita — round flatbread with a pocket. The basic bread for hummus, falafel, sabich, shawarma. From Greek/Arabic.', 'word', 'פיתה חמה. — pita chama — "Hot pita."', 'Israeli pitas are larger and softer than the dry pita chips of US supermarkets.', null, [ACT.vocabFood]),
    createContentItem('תהינה', 'techina', 'Tahini — sesame paste sauce. Used on falafel, sabich, shawarma, and as a standalone dip. Made from raw or roasted sesame.', 'word', 'תהינה עם לימון. — techina im lemon — "Tahini with lemon."', 'Israeli technina is typically thinned with lemon, garlic, and water before serving.', null, [ACT.vocabFood]),
    createContentItem('סלט ישראלי', 'salat yisre\'eli', 'Israeli salad — finely chopped tomato, cucumber, onion, parsley, olive oil, lemon. Side dish or breakfast staple.', 'word', 'תני לי סלט ישראלי, בבקשה. — tni li salat yisre\'eli, bevakasha — "Give me an Israeli salad, please."', 'Origin: Palestinian/Levantine; the Israeli version emphasizes very fine chopping.', null, [ACT.vocabFood]),
    createContentItem('מלאווח', 'malawach', 'Malawach — Yemenite flaky fried flatbread. Often served with hard-boiled egg and tomato-chili sauce.', 'word', 'מלאווח חם. — malawach cham — "Hot malawach."', 'Brought by Yemenite Jews; one of the most distinctive Yemenite contributions to Israeli food.', null, [ACT.vocabFood]),

    createContentItem('אבא / אמא', 'aba / ima', 'Father / mother. Universal terms for dad/mom. From Aramaic. Used in all registers — Israelis call their parents aba/ima from toddlerhood through adulthood. Mil\'ra: a-BA, i-MA.', 'word', 'אבא שלי הוא מהנדס. — aba sheli hu mehandes — "My dad is an engineer."', 'No formal vs casual; Hebrew lacks the "father/dad" or "mother/mom" register split of English.', null, [ACT.vocabFamily]),
    createContentItem('אח / אחות', 'ach / achot', 'Brother / sister. Singular masc ach (mil\'ra: ACH), fem achot (mil\'ra: a-CHOT). Plural: achim (m) / achayot (f, irregular).', 'word', 'יש לי אח גדול ואחות קטנה. — yesh li ach gadol ve-achot ktana — "I have a big brother and little sister."', 'אח (ach) also means "brother" in the figurative sense — Israelis use it as casual address (achi = "bro").', null, [ACT.vocabFamily]),
    createContentItem('בן / בת', 'ben / bat', 'Son / daughter. Also "boy/girl" in younger contexts. Plural: בנים (banim) / בנות (banot).', 'word', 'הבן שלי בכיתה ג׳. — ha-ben sheli ba-kita gimel — "My son is in third grade."', 'Ben/Bat is used in age-stating: ben 21 (ben esrim ve-echad) = "21 years old" (m); bat 21 = same (f).', null, [ACT.vocabFamily]),
    createContentItem('סבא / סבתא', 'saba / savta', 'Grandfather / grandmother. From Aramaic. Mil\'el: SA-ba, SAV-ta.', 'word', 'סבא וסבתא שלי גרים בחיפה. — saba ve-savta sheli garim be-cheifa — "My grandpa and grandma live in Haifa."', 'Israeli kids often have strong relationships with savta and saba; intergenerational Friday dinners are common.', null, [ACT.vocabFamily]),
    createContentItem('דוד / דודה', 'dod / doda', 'Uncle / aunt. Doda is also used to refer to any older woman in casual address ("auntie").', 'word', 'הדודה שלי מבקרת בקיץ. — ha-doda sheli mevakeret ba-kayitz — "My aunt visits in the summer."', 'No distinction between paternal and maternal uncle/aunt — same word.', null, [ACT.vocabFamily]),
    createContentItem('בן דוד / בת דודה', 'ben dod / bat doda', 'Cousin — masculine ben dod ("son of uncle"), feminine bat doda ("daughter of aunt"). Hebrew specifies the cousin relation through the parent.', 'word', 'נפגשתי עם בני הדודים שלי. — nifgashti im b\'nei ha-dodim sheli — "I met with my cousins."', 'Plural: b\'nei dodim (cousins, mixed); b\'not dodim (female cousins).', null, [ACT.vocabFamily]),
    createContentItem('בעל / אישה', 'ba\'al / isha', 'Husband / wife. Ba\'al also means "owner, master"; isha also means "woman". Plural: be\'alim / nashim.', 'word', 'הבעל שלי טייס. — ha-ba\'al sheli tayas — "My husband is a pilot."', 'Modern Hebrew increasingly uses זוגיות (zugiyut, "couplehood") and בן/בת זוג (ben/bat zug, partner) instead of ba\'al/isha, especially for unmarried couples.', null, [ACT.vocabFamily]),
    createContentItem('ילד / ילדה / ילדים', 'yeled / yalda / yeladim', 'Child (m) / child (f) / children. Yeled is mil\'el (YE-led), the classic segolate noun. Yeladim covers any group of children.', 'word', 'יש לי שני ילדים. — yesh li sh\'nei yeladim — "I have two children."', 'In modern Hebrew, yeladim also informally means "guys/folks" addressing a group.', null, [ACT.vocabFamily]),

    createContentItem('של', 'shel', 'The possessive marker "of". Place between the possessed noun and the owner: הספר של דני (ha-sefer shel Dani, "the book of Dani / Dani\'s book"). The standard everyday possessive — much more common than the construct state (smichut).', 'sentence', 'הבית של אמא — ha-bayit shel ima — "Mom\'s house"\nהמכונית של חברי — ha-mechonit shel chaveri — "my friend\'s car"', 'Note: the possessed noun is usually definite (with ha-), and shel + owner follows.', null, [ACT.grammarPossession]),
    createContentItem('של + suffix', 'shel + pronoun suffix', 'Shel combines with pronoun endings to form personal possessives: שלי (sheli, mine), שלך (shelcha m / shelach f, yours), שלו (shelo, his), שלה (shela, hers), שלנו (shelanu, ours), שלכם/שלכן (shelachem/shelachen, yours-pl), שלהם/שלהן (shelahem/shelahen, theirs).', 'sentence', 'הספר שלי. — ha-sefer sheli — "my book"\nהמשפחה שלה. — ha-mishpacha shela — "her family"', 'Note the same -i/-cha/-o etc. pronoun-suffix system attaches to many Hebrew prepositions.', [
      { target: 'שלי sheli', note: 'mine; -i = my' },
      { target: 'שלך shelcha (m) / shelach (f)', note: 'yours; gender-marked' },
      { target: 'שלו / שלה shelo / shela', note: 'his / hers' },
      { target: 'שלנו shelanu', note: 'ours' },
    ], [ACT.grammarPossession]),

    createContentItem('שמות תואר', 'shemot to\'ar', 'Adjectives. Hebrew adjectives agree with the noun in gender AND number. They come AFTER the noun (not before, as in English). Pattern: masc-sg (gadol), fem-sg (gdola), masc-pl (gdolim), fem-pl (gdolot).', 'sentence', 'בית גדול / דירה גדולה / בתים גדולים / דירות גדולות — bayit gadol / dira gdola / batim gdolim / dirot gdolot — big house / big apartment / big houses / big apartments.', 'In definite phrases, BOTH noun and adjective take ha-: הבית הגדול (ha-bayit ha-gadol, "the big house").', [
      { target: 'masc-sg adjective', note: 'unmarked form: gadol (big), tov (good), yafe (beautiful)' },
      { target: 'fem-sg adjective', note: '-a ending: gdola, tova, yafa' },
      { target: 'plural -im / -ot', note: 'masculine plural in -im, feminine in -ot' },
    ], [ACT.grammarAdjectives]),

    createContentItem('הישראל שלי', 'ha-yisra\'el sheli', 'A paragraph by an immigrant student describing the Israel she has come to know. Read aloud for vocabulary practice.', 'sentence', 'אני באה לישראל לפני שנתיים. אני סטודנטית באוניברסיטה העברית בירושלים. הירושלים שלי היא העיר העתיקה והשוק מחנה יהודה. אבל אני נוסעת לתל אביב בסוף השבוע, לחוף הים. המשפחה שלי בארצות הברית, אבל יש לי כאן חברים טובים. אני אוהבת את האוכל הישראלי, במיוחד שקשוקה וחומוס.', 'Translation: "I came to Israel two years ago. I am a student at Hebrew University in Jerusalem. My Jerusalem is the Old City and the Mahane Yehuda market. But I travel to Tel Aviv on weekends, to the beach. My family is in the United States, but I have good friends here. I love Israeli food, especially shakshuka and hummus."', null, [ACT.reading]),

    createContentItem('סיור באזורים', 'siyur ba-ezorim', 'A tour guide gives a brief overview of Israel\'s regions. Listen for the regional vocabulary.', 'conversation', 'מדריך: ברוכים הבאים לישראל! ארץ קטנה, אבל מגוונת.\nמדריך: בצפון יש את חיפה, הגליל, ואת הכינרת.\nמדריך: במרכז יש את תל אביב, את שדה התעופה, ואת ירושלים.\nמדריך: בדרום יש את ים המלח, את הנגב, ואת אילת.\nמדריך: בכל אזור יש אוכל אחר, מבטא אחר, ואופי אחר.\nמדריך: יש שאלות?', 'A natural Israeli tour guide opening — short, packed, and inviting questions.', [
      { target: 'מגוון megavan', note: '"diverse, varied"; from the root ג-ו-ן (color, variety)' },
      { target: 'מבטא mivta', note: '"accent" — Israelis are aware of strong regional and ethnic accents' },
      { target: 'אופי ofi', note: '"character, personality"' },
    ], [ACT.listening]),

    createContentItem('תרגיל כתיבה', 'targil ktiva', 'Write 8 sentences about your impressions of Israel. Use possessives, adjective agreement, and unit vocabulary.', 'sentence', 'דוגמה: אני בישראל שני חודשים. הירושלים שלי יפה ומיוחדת. החברים שלי כאן מאד נחמדים. אני אוהב את האוכל — במיוחד את החומוס והפיתה הטרייה. בסוף השבוע אני נוסע לתל אביב, לחוף. תל אביב היא עיר גדולה ועצבנית. ים המלח הוא מקום מעניין. אני שמח שאני כאן.', 'Translation: "I have been in Israel two months. My Jerusalem is beautiful and special. My friends here are very nice. I love the food — especially the hummus and the fresh pita. On weekends I travel to Tel Aviv, to the beach. Tel Aviv is a big and intense city. The Dead Sea is an interesting place. I\'m glad I am here."', null, [ACT.writing]),

    createContentItem('עדות בישראל', 'edot be-yisrael', 'Israel\'s ethnic mosaic. Jewish ethnic groups: אשכנזים (Ashkenazim, European origin), ספרדים/מזרחים (Sefardim/Mizrachim, Iberian/Middle Eastern origin), אתיופים (Etyopim, Ethiopian). Plus ערבים (Aravim, Arab Israelis, ~20%), דרוזים (Druzim, Druze), בדואים (Bedu\'im, Bedouin).', 'sentence', 'בישראל יש עדות רבות — yhudim, aravim, druzim, ve-od. — "In Israel there are many communities — Jews, Arabs, Druze, and more."', 'Each group has its food, music, accent, and customs; modern Israel is a layered mosaic, not a melting pot.', null, [ACT.culture]),
    createContentItem('דתי או חילוני', 'dati o chiloni', 'Religious continuum: חילוני (chiloni, secular), מסורתי (masorti, traditional), דתי (dati, religious/modern orthodox), חרדי (charedi, ultra-orthodox/Haredi). Each has distinct dress, schooling, and Shabbat observance.', 'sentence', 'אני חילוני, אבל המשפחה שלי מסורתית. — ani chiloni, aval ha-mishpacha sheli masorti — "I am secular, but my family is traditional."', 'About 45% chiloni, 25% masorti, 16% dati, 14% charedi (rough numbers, shifting); secular Tel Aviv vs religious Jerusalem is a classic dichotomy.', null, [ACT.culture]),

    createContentItem('משימה: סיור לאורח', 'mesima: siyur le-ore\'ach', 'Roleplay as a tour guide showing a foreign visitor Israel\'s highlights. Use cities, food, family, and culture vocabulary.', 'conversation', '[Tel Aviv beach, Friday afternoon]\nאורח: מה רואים בישראל?\nאתה: יש המון! בצפון — חיפה והגליל. במרכז — תל אביב וירושלים. בדרום — ים המלח ואילת.\nאורח: ומה אוכלים?\nאתה: [שלוש מנות איקוניות]\nאורח: ומה עושים בסוף השבוע?\nאתה: [מתאר ערב שישי בבית]\nאורח: וואו, תודה רבה!', 'Eight-turn exchange covering regions, food, weekend life.', null, [ACT.task]),
  ],
};

module.exports = lesson;
