const { selectProfileCoreItems } = require('./richCurriculumFactory');

const defaultExpressionPractice = (slug, label) => [
  { id: `${slug}-main`, label: 'Using the main pattern', goal: `Use the central ${label} pattern naturally in a personally relevant answer.` },
  { id: `${slug}-extend`, label: 'Extending the answer', goal: 'Add one reason, contrast, or example so the answer sounds lived-in rather than memorized.' },
  { id: `${slug}-repair`, label: 'Repairing a likely mistake', goal: `Notice one nearby ${label} form learners often confuse with this pattern and choose the better option.` },
];

const configs = {
  ko: {
    label: 'Korean',
    orientation: '학습 목표',
    pronunciation: '발음 점검',
    reading: '읽기 모델',
    listening: '대화 모델',
    writing: '쓰기 연습',
    culture: '사용과 맥락',
    task: '최종 과제',
    error: '자주 하는 실수',
    register: '말투',
    fluency: '유창성',
    transfer: '응용',
    recall: '회상',
    extension: '확장',
    comparison: '대조',
    pronunciationRepair: '발음 교정',
    dialogueVariation: '대화 변형',
    sentenceBuilding: '문장 만들기',
    miniQuiz: '빠른 점검',
    reflection: '되돌아보기',
    listeningCheck: '듣기 점검',
    shortAnswer: '짧은 답',
    longAnswer: '긴 답',
    minimalPair: '최소 대조',
    rewrite: '다시 쓰기',
    newSituation: '새 상황',
    selfCorrection: '자기 수정',
    oralOutput: '말하기 출력',
    collocation: '함께 쓰는 말',
    formCheck: '형태 점검',
    repairPrompt: '수정 연습',
    contextCheck: '맥락 점검',
    completionCheck: '완성 점검',
    pronunciationGoal: 'Keep 받침, sound changes, tense-versus-aspirated contrasts, and speech-level endings clear enough that Korean grammar remains audible in real speech.',
    registerGoal: 'Check whether the setting calls for casual, polite, formal, honorific, or service-register Korean before choosing the final wording.',
    cultureGoal: 'Notice the age, relationship, formality, or service setting that changes how this Korean is naturally used.',
    errorGoal: 'Watch for literal-translation mistakes around particles, speech levels, omission, word order, and endings that Korean uses to carry meaning.',
    sentenceLayerGoal: 'Build the sentence in layers: anchor phrase first, particle or ending next, then the detail that makes it personal.',
    writingCheckGoal: 'Reproduce the form from memory, then compare particles, spacing, endings, and honorific choices against the model.',
  },
  en: {
    label: 'English',
    orientation: 'Lesson goal',
    pronunciation: 'Sound check',
    reading: 'Reading model',
    listening: 'Dialogue model',
    writing: 'Writing practice',
    culture: 'Use and context',
    task: 'Final task',
    error: 'Common mistake',
    register: 'Register',
    fluency: 'Fluency',
    transfer: 'Transfer',
    recall: 'Recall',
    extension: 'Extension',
    comparison: 'Contrast',
    pronunciationRepair: 'Pronunciation repair',
    dialogueVariation: 'Dialogue variation',
    sentenceBuilding: 'Sentence building',
    miniQuiz: 'Quick check',
    reflection: 'Reflection',
    listeningCheck: 'Listening check',
    shortAnswer: 'Short answer',
    longAnswer: 'Long answer',
    minimalPair: 'Minimal contrast',
    rewrite: 'Rewrite',
    newSituation: 'New situation',
    selfCorrection: 'Self-correction',
    oralOutput: 'Oral output',
    collocation: 'Collocation',
    formCheck: 'Form check',
    repairPrompt: 'Repair prompt',
    contextCheck: 'Context check',
    completionCheck: 'Completion check',
    pronunciationGoal: 'Keep stress, reductions, linking, and the contrastive sounds that carry meaning clear enough that English stays easy to follow at natural speed.',
    registerGoal: 'Check whether the setting calls for casual, polite, professional, formal, or written English before choosing the final wording.',
    cultureGoal: 'Notice the register, relationship, or interactional convention that changes how this English is naturally used.',
    errorGoal: 'Watch for literal-translation mistakes around articles, subject requirements, tense, word order, and register that English marks explicitly.',
    sentenceLayerGoal: 'Build the sentence in layers: core clause first, grammar carrier next, then the detail that makes it precise and natural.',
    writingCheckGoal: 'Reproduce the form from memory, then compare articles, agreement, tense, punctuation, and word order against the model.',
  },
};

const sourcePools = (lesson) => lesson.relatedPools?.length ? lesson.relatedPools : [`topic-${lesson.category || 'daily-life'}`];

const pick = (entry, fallback = '') => entry || fallback;

function makeCoreDepthProfile(lang, lessonId, lesson) {
  const config = configs[lang];
  if (!config) throw new Error(`No core depth profile config for ${lang}`);

  const slug = `${lang}-${lessonId.toLowerCase()}`;
  const {
    first,
    second,
    last,
  } = selectProfileCoreItems(lesson);
  const overview = lesson.activities?.[0]?.goals?.[0]
    || `Use the central skill of ${lesson.title} accurately in context.`;
  const task = lesson.activities?.[lesson.activities.length - 1]?.task
    || `Complete one connected exchange that demonstrates the main skill of ${lesson.title}.`;

  return {
    slug,
    overview,
    task,
    orientationAnchor: config.orientation,
    orientationExample: config.orientation,
    orientationExampleNote: `The whole lesson is built toward this outcome: ${task}`,
    pronunciationGoal: config.pronunciationGoal,
    pronunciationAnchor: config.pronunciation,
    pronunciationExample: pick(first.exampleTarget, first.targetText),
    pronunciationExampleNote: pick(first.exampleNative, first.nativeText),
    vocabularyGoal: `Use the key language of ${lesson.title} with the register and setting that the lesson requires.`,
    vocabularyAnchor: first.targetText,
    vocabularyExample: pick(first.exampleTarget, first.targetText),
    vocabularyExampleNote: pick(first.exampleNative, first.nativeText),
    secondaryVocabularyGoal: `Distinguish the nearby wording choices that make ${lesson.title} sound precise rather than merely understandable.`,
    secondaryVocabularyAnchor: second.targetText,
    secondaryVocabularyExample: pick(second.exampleTarget, second.targetText),
    secondaryVocabularyExampleNote: pick(second.exampleNative, second.nativeText),
    grammarGoal: overview,
    grammarAnchor: first.targetText,
    grammarExample: pick(first.exampleTarget, first.targetText),
    grammarExampleNote: pick(first.exampleNative, first.nativeText),
    secondaryGrammarGoal: `Contrast the main pattern in ${lesson.title} with one nearby ${config.label} form so the learner can avoid literal translation.`,
    secondaryGrammarAnchor: second.targetText,
    secondaryGrammarExample: pick(second.exampleTarget, second.targetText),
    secondaryGrammarExampleNote: pick(second.exampleNative, second.nativeText),
    readingAnchor: config.reading,
    readingExample: pick(last.exampleTarget, last.targetText),
    readingExampleNote: pick(last.exampleNative, last.nativeText),
    listeningAnchor: config.listening,
    listeningExample: pick(last.exampleTarget, last.targetText),
    listeningExampleNote: pick(last.exampleNative, last.nativeText),
    writingAnchor: config.writing,
    writingExample: pick(first.exampleTarget, first.targetText),
    writingExampleNote: 'Adapt the model to your own life while keeping the lesson pattern intact.',
    cultureGoal: config.cultureGoal,
    cultureAnchor: config.culture,
    cultureExample: pick(second.exampleTarget, second.targetText),
    cultureExampleNote: pick(second.exampleNative, second.nativeText),
    taskAnchor: config.task,
    taskExample: pick(last.exampleTarget, last.targetText),
    taskExampleNote: task,
    errorAnchor: config.error,
    errorGoal: config.errorGoal,
    errorExample: pick(second.exampleTarget, second.targetText),
    errorExampleNote: `Use the model to repair the likely mistake before it becomes automatic: ${pick(second.exampleNative, second.nativeText)}`,
    registerAnchor: config.register,
    registerGoal: config.registerGoal,
    registerExample: pick(first.exampleTarget, first.targetText),
    registerExampleNote: pick(first.exampleNative, first.nativeText),
    fluencyAnchor: config.fluency,
    fluencyGoal: `Say the idea as one connected ${config.label} message rather than as separate translated fragments.`,
    fluencyExample: pick(last.exampleTarget, last.targetText),
    fluencyExampleNote: pick(last.exampleNative, last.nativeText),
    transferAnchor: config.transfer,
    transferGoal: 'Move the lesson pattern into a new personal situation while preserving the same grammatical job and social tone.',
    transferExample: pick(first.exampleTarget, first.targetText),
    transferExampleNote: 'The learner should be able to leave the model behind without losing the form.',
    recallAnchor: config.recall,
    recallGoal: 'Retrieve the key form from memory before rereading the model; retrieval is where durable control begins.',
    recallExample: first.targetText,
    recallExampleNote: first.nativeText,
    extensionAnchor: config.extension,
    extensionGoal: 'Extend the answer with one cause, contrast, time marker, or social detail so the language becomes useful beyond a single memorized line.',
    extensionExample: pick(last.exampleTarget, last.targetText),
    extensionExampleNote: 'A strong answer usually says one useful thing more than the minimum.',
    comparisonAnchor: config.comparison,
    comparisonGoal: `Compare the central form in ${lesson.title} with the closest nearby alternative so the learner knows not only what to say, but why this wording wins here.`,
    comparisonExample: pick(second.exampleTarget, second.targetText),
    comparisonExampleNote: pick(second.exampleNative, second.nativeText),
    pronunciationRepairAnchor: config.pronunciationRepair,
    pronunciationRepairGoal: config.pronunciationGoal,
    pronunciationRepairExample: pick(first.exampleTarget, first.targetText),
    pronunciationRepairExampleNote: pick(first.exampleNative, first.nativeText),
    dialogueVariationAnchor: config.dialogueVariation,
    dialogueVariationGoal: 'Change one participant, one setting, and one detail while keeping the lesson form natural.',
    dialogueVariationExample: pick(last.exampleTarget, last.targetText),
    dialogueVariationExampleNote: pick(last.exampleNative, last.nativeText),
    sentenceBuildingAnchor: config.sentenceBuilding,
    sentenceBuildingGoal: config.sentenceLayerGoal,
    sentenceBuildingExample: pick(first.exampleTarget, first.targetText),
    sentenceBuildingExampleNote: pick(first.exampleNative, first.nativeText),
    miniQuizAnchor: config.miniQuiz,
    miniQuizGoal: 'Choose the better of two nearby forms and say aloud what clue made the decision.',
    miniQuizExample: pick(second.exampleTarget, second.targetText),
    miniQuizExampleNote: pick(second.exampleNative, second.nativeText),
    reflectionAnchor: config.reflection,
    reflectionGoal: 'Name the one feature from this lesson that would most easily betray literal translation if ignored.',
    reflectionExample: pick(last.exampleTarget, last.targetText),
    reflectionExampleNote: pick(last.exampleNative, last.nativeText),
    listeningCheckAnchor: config.listeningCheck,
    listeningCheckGoal: `Listen inside "${pick(first.exampleTarget, first.targetText)}" for the exact sound, ending, function word, or omission that changes the meaning of the model ${config.label} sentence.`,
    shortAnswerAnchor: config.shortAnswer,
    shortAnswerGoal: `Answer first with the shortest correct ${config.label} form that still fits "${pick(first.exampleTarget, first.targetText)}", then add one useful extension.`,
    longAnswerAnchor: config.longAnswer,
    longAnswerGoal: `Turn "${pick(last.exampleTarget, last.targetText)}" into a fuller answer by adding cause, time, contrast, or social detail without losing the core grammar.`,
    minimalPairAnchor: config.minimalPair,
    minimalPairGoal: `Compare "${pick(second.exampleTarget, second.targetText)}" with the nearest form a learner might confuse it with and explain what changes.`,
    rewriteAnchor: config.rewrite,
    rewriteGoal: config.writingCheckGoal,
    newSituationAnchor: config.newSituation,
    newSituationGoal: `Move "${pick(last.exampleTarget, last.targetText)}" into a new setting so the learner proves transfer rather than repetition.`,
    selfCorrectionAnchor: config.selfCorrection,
    selfCorrectionGoal: `Name one error you might make while producing "${pick(second.exampleTarget, second.targetText)}", then repair it before looking back at the model.`,
    oralOutputAnchor: config.oralOutput,
    oralOutputGoal: `Speak for twenty seconds by linking at least two lesson forms around "${pick(last.exampleTarget, last.targetText)}" in one connected ${config.label} answer.`,
    collocationAnchor: config.collocation,
    collocationGoal: 'Say one word or phrase that naturally travels with this form so it is learned as usable language, not a stranded flashcard.',
    formCheckAnchor: config.formCheck,
    formCheckGoal: 'Identify the smallest form detail that carries the lesson meaning, then explain what would break if it changed.',
    repairPromptAnchor: config.repairPrompt,
    repairPromptGoal: 'Repair one translated-sounding sentence so the final version fits the target-language pattern and register.',
    contextCheckAnchor: config.contextCheck,
    contextCheckGoal: 'Choose the wording that best fits the speaker, setting, and purpose before focusing on grammar alone.',
    completionCheckAnchor: config.completionCheck,
    completionCheckGoal: 'Finish with one full answer that combines form, meaning, and tone without leaning on the model sentence.',
    expressionPractice: lesson.expressionPractice?.length ? lesson.expressionPractice : defaultExpressionPractice(slug, config.label),
    relatedPools: sourcePools(lesson),
  };
}

module.exports = {
  makeCoreDepthProfile,
};
