// Level 1 Unit 1 — Greetings & Self-Introduction (Modern Standard Arabic)
// Functions: greeting, introducing yourself, asking where someone is from,
// correcting a wrong assumption, farewells.
// This lesson is the canonical TEMPLATE for all Arabic thematic Level 1 lessons.
//
// All content is authored with Arabic script (target, RTL) + IPA-based
// transliteration (romanization) + English glosses (canonical source).
// The AI conversation tutor reads this curriculum and delivers it to each
// learner in their preferred native language at runtime — never assume a
// specific L1 in this file.
//
// Glosses follow the rich-gloss rule (AGENTS.md → "Gloss Richness"):
// every nativeText, exampleNative, and breakdown.native carries register,
// usage context, or contrast info — not a bare definition.

const createContentItem = (
  target,
  romanization,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization,
  nativeText: note,
  pronunciation: romanization,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'ar-l1u1-orientation',
  pronunciation: 'ar-l1u1-pronunciation',
  vocabularyGreetings: 'ar-l1u1-vocab-greetings',
  vocabularyPeople: 'ar-l1u1-vocab-people',
  grammarPronouns: 'ar-l1u1-grammar-pronouns',
  grammarNominalSentence: 'ar-l1u1-grammar-nominal-sentence',
  grammarNegation: 'ar-l1u1-grammar-negation',
  reading: 'ar-l1u1-reading',
  listening: 'ar-l1u1-listening',
  writing: 'ar-l1u1-writing',
  culture: 'ar-l1u1-culture',
  task: 'ar-l1u1-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Greet someone in Arabic and farewell in three registers (Islamic-universal, polite-secular, casual) so you can match the situation.',
      'Introduce yourself with your name, country, and one role (student / teacher / engineer) using the nominal-sentence pattern أنا … and اسمي … .',
      'Ask another person their name and where they are from, then respond appropriately to their answer using the polite ما اسمك؟ / من أين أنت؟ patterns.',
    ],
    task: 'Picture your first day at King Saud University in Riyadh — you walk into a research meeting and meet a visiting scholar from Cairo. By the end of this lesson you should handle the whole exchange in MSA without rehearsing each line.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in this lesson',
    goals: [
      'Produce the pharyngeal ع clearly in عَلَيْكُمْ ʿalaykum and مَعَ maʿa — the single most distinctive Arabic sound and the one most often mispronounced as a glottal stop.',
      'Apply sun-letter assimilation in السَّلَامُ as-salāmu — the ل of الـ is silent and س doubles in speech, even though the writing shows both.',
      'Distinguish the emphatic ص in مِصْر Miṣr (Egypt) from the plain س in سَعِيد saʿīd (happy) — emphasis affects both the consonant and the surrounding vowel.',
    ],
    task: 'Read each example aloud and identify whether sun-letter assimilation applies, then pronounce the spoken version with the assimilation, not the written letters.',
  },
  {
    id: ACT.vocabularyGreetings,
    section: 'Vocabulary I',
    title: 'Greetings, farewells, and first-meeting phrases',
    goals: [
      'Memorize 12 greetings and farewells across three registers, with the right phrase for each situation.',
      'Distinguish السَّلَامُ عَلَيْكُمْ (Islamic, universal) from أَهْلًا (secular, casual) from صَبَاح الخَيْر (time-of-day, neutral) — using the wrong one signals cultural or social mismatch.',
    ],
    task: 'Say each phrase out loud three times with correct pharyngeals and emphatics, then pair each one with the situation where you would use it.',
  },
  {
    id: ACT.vocabularyPeople,
    section: 'Vocabulary II',
    title: 'People, roles, and nationalities',
    goals: [
      'Use the 12 personal pronouns (أنا أنتَ أنتِ هو هي نحن أنتم أنتن هم هن plus dual أنتما هما) correctly, paying attention to gender distinction in 2nd and 3rd person.',
      'State your role (طالب / طالبة / أستاذ / مهندس) and nationality (country adjective with nisba ending ـي/ـية) in a complete short nominal sentence.',
    ],
    task: 'Say your own role and nationality using the أنا + role + nisba-adjective pattern, then describe one classmate using هو/هي + nationality.',
  },
  {
    id: ACT.grammarPronouns,
    section: 'Grammar I',
    title: 'الضمائر — Personal pronouns and gender',
    goals: [
      'Distinguish أنتَ (you-MASC) from أنتِ (you-FEM) — Arabic marks gender in the 2nd person, unlike English. Using the wrong form is a noticeable social error.',
      'Use the nominal-sentence pattern: pronoun + predicate, with NO copula. أنا طالب = "I [am] a student"; Arabic has no equivalent of English "to be" in the present tense.',
      'Recognize the dual forms (أنتما, هما) and the gender-marked plurals (هم MASC, هن FEM, أنتم MASC, أنتن FEM) — features that have no direct equivalent in most European languages.',
    ],
    task: 'Write six sentences using six different personal pronouns + role/nationality, paying attention to gender agreement on the adjective.',
  },
  {
    id: ACT.grammarNominalSentence,
    section: 'Grammar II',
    title: 'الجملة الاسمية — The nominal sentence (no copula)',
    goals: [
      'Form a complete sentence with NO verb in the present tense: subject (مبتدأ) + predicate (خبر), e.g., أنا طالب = "I [am] a student".',
      'Make the predicate agree with the subject in gender and number: هو طالب (he is a student-M) vs هي طالبة (she is a student-F) vs هم طلاب (they-M are students).',
      'Form a yes/no question by adding the particle هل at the beginning: هل أنت طالب؟ ("Are you a student?"). Or use أ before a noun in formal questions.',
    ],
    task: 'Write six nominal sentences identifying yourself, then convert three into yes/no questions with هل.',
  },
  {
    id: ACT.grammarNegation,
    section: 'Grammar III',
    title: 'Negation with لَيْسَ and the لَيْسَ … بَلْ correction pattern',
    goals: [
      'Negate a nominal sentence with لَيْسَ (laysa), the special "verb-like" negator: أنا لَسْتُ مِنْ مِصْر = "I am not from Egypt". لَيْسَ conjugates for person (لستُ I, لستَ you-M, لستِ you-F, ليسَ he, ليستْ she, لسنا we, لستم you-pl).',
      'Apply the لَيْسَ … بَلْ pattern to correct someone\'s wrong guess politely: لَسْتُ مِصْرِيًّا، بَلْ سُورِيّ = "I\'m not Egyptian, rather (I am) Syrian".',
    ],
    task: 'Imagine a classmate guesses your nationality wrong; correct them in one polite sentence using the لَيْسَ … بَلْ pattern with the correct conjugation of لَيْسَ.',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Read a self-introduction',
    goals: [
      'Read a short self-introduction paragraph aloud with correct emphatics, pharyngeals, sun-letter assimilation, and vowel length.',
      'Answer comprehension questions about the speaker\'s name, country, role, and field of study using nominal-sentence short answers.',
    ],
    task: 'Read the paragraph below aloud once, then answer four comprehension questions in complete short sentences.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'A first meeting',
    goals: [
      'Follow a 4-turn first-meeting dialogue and recognize the polite register markers (السلام عليكم, تشرفنا, حضرتك, kunyaa with Abu/Umm).',
      'Reproduce the dialogue with your own name and country, swapping in the relevant phrases naturally.',
    ],
    task: 'Read the polite dialogue along with the AI tutor first, then perform it again with your own information swapped in.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Write your own self-introduction',
    goals: [
      'Write 3–5 sentences in Arabic script covering greeting, name, country, role, and one extra fact.',
      'Use nominal sentences (no copula) at least twice and one nisba adjective (country-adjective ending in ـي/ـية) so the writing demonstrates the core grammar of this lesson.',
    ],
    task: 'Write your own self-introduction in 3–5 sentences using the model on the left, then read it aloud with correct emphatics and pharyngeals.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'السلام عليكم, kunya, and gender-marked address',
    goals: [
      'Use the universal Islamic greeting السلام عليكم across all 22 Arab countries — works in any register and is the safest first-meeting phrase. Reply with وعليكم السلام.',
      'Understand the kunya naming convention: أبو + first son\'s name = "father of" (Abu Ahmad = "father of Ahmad"); أم + first son\'s name = "mother of". Used as a respectful nickname even before someone has a son.',
      'Address professionals with title + name: الأستاذ محمد (Professor/Mr. Muhammad), الدكتور سامي (Dr. Sami) — and remember to switch from أنت to حضرتك or سيادتك for very senior people.',
    ],
    task: 'Decide how you would address (1) a classmate named عمر, (2) a professor named د. فاطمة, (3) a senior researcher Abu-Khalid — give the full Arabic form for each.',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'First day at King Saud University — in Arabic',
    goals: [
      'Combine everything from this lesson into one continuous scene with no break between greeting, introduction, question, answer, correction, and farewell.',
      'Use the correct register (Islamic-universal السلام عليكم vs casual أهلًا) based on the relationship; pay attention to gender agreement throughout.',
    ],
    task: 'Roleplay your first day at King Saud University with the AI tutor playing a visiting scholar from Cairo; aim for a 6-turn exchange in MSA.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 1: السلام عليكم — Greetings and Self-Introduction',
  category: 'greetings',
  difficulty: 'beginner',
  targetLang: 'ar',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'greeting-someone', label: 'Greeting someone', goal: 'Open and close a brief encounter politely (السلام عليكم / أهلًا / مع السلامة) and match the register to the relationship.' },
    { id: 'introducing-yourself', label: 'Introducing yourself', goal: 'Give your name, nationality, and one fact about yourself in two short nominal sentences using أنا … and اسمي ….' },
    { id: 'asking-where-from', label: 'Asking where someone is from', goal: 'Ask من أين أنت؟ or ما جنسيتك؟ and respond naturally with country + nisba ending.' },
    { id: 'correcting-assumption', label: 'Correcting an assumption', goal: 'Use the لَيْسَ … بَلْ pattern to politely correct a wrong guess about your nationality or role.' },
  ],
  relatedPools: ['topic-people', 'topic-society'],
  content: [
    // Activity 1 — Orientation
    createContentItem(
      'أهداف الدرس',
      'ahdāf ad-dars',
      'By the end of this lesson, you can greet someone in MSA, give your name, say where you are from, ask the same back, and farewell — all in one short conversation without pausing to think.',
      'word',
      'Functional language: تَحِيَّة taḥiyya (greet) · تَعَارُف taʿāruf (introducing oneself) · سُؤَال عَن الجِنْسِيَّة suʾāl ʿan al-jinsiyya (ask origin) · نَفْي nafy (negate) · وَدَاع wadāʿ (farewell)',
      'These five micro-skills are the spine of every social encounter in the Arab world — once they\'re automatic, every later lesson layers on top.',
      null,
      [ACT.orientation],
    ),
    createContentItem(
      'السياق الحقيقي',
      'as-siyāq al-ḥaqīqī',
      'You are at King Saud University in Riyadh on your first day and a visiting scholar from Cairo turns to you in the lab. The whole encounter takes about 30 seconds and you will need every micro-skill from this lesson.',
      'word',
      'الزائر: "السَّلَامُ عَلَيْكُمْ! اِسْمِي أَحْمَد. مِنْ أَيْنَ أَنْتَ؟"',
      'A typical opener from a Cairene visiting scholar: the universal Islamic greeting + name introduction + immediate origin question — a common Arab academic pattern.',
      [
        { target: 'السلام عليكم as-salāmu ʿalaykum', note: 'universal Islamic greeting; works in any register and any Arab country; reply وعليكم السلام' },
        { target: 'اسمي … ismī …', note: 'self-introduction "my name is …"; the ـي suffix means "my"' },
        { target: 'من أين أنت؟ min ayna anta?', note: 'literal: "from where (are) you?"; the standard origin question; use أنتِ if asking a woman' },
      ],
      [ACT.orientation],
    ),
    createContentItem(
      'ثلاثة مستويات للأدب',
      'thalāthat mustawayāt li-l-adab',
      'Arabic distinguishes three rough politeness/register tiers. Islamic-universal (any context, any Arab country): السلام عليكم / وعليكم السلام. Polite-secular (workplace, neutral): أهلًا وسهلًا / صباح الخير / مساء الخير. Casual (peers, friends): أهلًا / مرحبا / كيفك.',
      'word',
      'Islamic: السلام عليكم · Polite: أهلًا وسهلًا · Casual: أهلًا',
      'The Islamic greeting السلام عليكم is universally accepted across all registers and is the safest default; only purely-secular contexts may prefer أهلًا.',
      [
        { target: 'ISLAMIC: السلام عليكم', note: 'works with anyone — Muslim or not, peer or senior, in any of the 22 Arab countries' },
        { target: 'POLITE: أهلًا وسهلًا', note: 'literally "[you are] family and on smooth ground"; used as a warm welcome' },
        { target: 'CASUAL: أهلًا / مرحبا', note: 'short, friendly; for peers and informal contexts' },
      ],
      [ACT.orientation],
    ),

    // Activity 2 — Pronunciation
    createContentItem(
      'السلام',
      'as-salām (written: al-salām)',
      'Sun-letter assimilation: the ل of الـ is silent before the sun letter س, and س is geminated (doubled). Written form keeps ل visible; spoken form drops it and doubles the next letter.',
      'word',
      'السلام → spoken: as-salām /asːalaːm/',
      'The single most heard sun-letter assimilation in Arabic; appears every time you say the universal greeting.',
      [
        { target: 'written: الس', note: 'with visible ل' },
        { target: 'spoken: as-s (ل silent, س doubled)', note: 'sun-letter rule; س starts with تشديد in the actual speech' },
        { target: 'sun letters', note: 'all 14 tongue-tip consonants trigger this — ت ث د ذ ر ز س ش ص ض ط ظ ل ن' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'عليكم',
      'ʿalaykum',
      'Contains the pharyngeal ع, the diphthong /ay/ written ـَيـ, and the masculine-plural ending ـكم. The ع must be a real pharyngeal — not a glottal stop, not a vowel — or the word sounds non-Arab.',
      'word',
      'عَلَيْكُمْ ʿalaykum /ʕalajkum/',
      'Critical: ع is voiced and continuous (tight throat with vibration), not the momentary catch of hamza.',
      [
        { target: 'ع ʿayn', note: 'pharyngeal voiced fricative; the iconic Arabic sound' },
        { target: 'ـَيـ /ay/', note: 'diphthong formed by fatha + يـ' },
        { target: 'ـكم -kum', note: '2nd-person masculine-plural pronoun suffix; for one man use ـك -ka or -ak' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'صباح الخير',
      'ṣabāḥ al-khayr',
      'Three sound traps: the emphatic ص in صباح, the pharyngeal ح at the end of صباح, and the velar fricative خ at the start of خير. Each one is meaning-bearing and getting any wrong sounds non-native.',
      'word',
      'صَبَاح الخَيْر ṣabāḥ al-khayr — "morning of goodness"',
      'Reply: صباح النور ṣabāḥ an-nūr ("morning of light") — the conventional polite response.',
      [
        { target: 'ص ṣād', note: 'emphatic /sˤ/ — tongue retracted, vowel darkened' },
        { target: 'ح ḥāʾ', note: 'voiceless pharyngeal — whispered breath from the throat' },
        { target: 'خ khāʾ', note: 'voiceless velar fricative — like Scottish "loch"' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'مصر',
      'Miṣr',
      'The MSA name for Egypt. The ص is emphatic (deep, retracted) and "darkens" the kasra before it. Egyptians in colloquial speech often pronounce ص more softly, but in MSA always keep the full emphasis.',
      'word',
      'أَنَا مِنْ مِصْر anā min Miṣr ("I am from Egypt")',
      'Contrast with سَر sirr "secret" — emphasis on ص changes the sound dramatically.',
      [
        { target: 'مِ', note: 'kasra darkened by following emphatic — sounds more like /mɨ/ than /mi/' },
        { target: 'ص ṣād', note: 'emphatic sād — back of tongue raised' },
        { target: 'ـرْ -r with sukun', note: 'no vowel after — closes the syllable' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'ما اسمك؟',
      'mā smuk? (not mā ismuk)',
      'Hamzat al-waṣl elision: the hamza at the start of اِسْم is silent when it follows another vowel. ما اسمك "what (is) your name" elides to /mā smuk/ — not /mā ismuk/. This is a high-frequency phrase to drill.',
      'word',
      'ما اسمك؟ mā smuk? ("What is your name?", to a man)',
      'For a woman: ما اسمكِ؟ mā smuki? — the suffix changes from masc -ka to fem -ki.',
      [
        { target: 'ما mā', note: 'question word "what" — used for objects; for people use مَن "who"' },
        { target: 'ا elides', note: 'hamzat al-waṣl drops because previous word ends in a vowel (ā)' },
        { target: 'اسم ism + ـك -ka/-ki', note: 'noun + 2nd-person possessive suffix' },
      ],
      [ACT.pronunciation],
    ),

    // Activity 3 — Vocabulary I: Greetings & farewells
    createContentItem('السلام عليكم', 'as-salāmu ʿalaykum', 'Universal Islamic greeting "peace be upon you" — works in any register and any Arab country; the safest default for first meetings, workplace, and formal situations. Reply: وعليكم السلام wa-ʿalaykum as-salām.', 'word', 'السلام عليكم! اسمي سارة.', 'Universal opener paired with a self-introduction; the standard first turn in any Arab conversation.', null, [ACT.vocabularyGreetings]),
    createContentItem('وعليكم السلام', 'wa-ʿalaykumu s-salām', 'The standard reply to السلام عليكم. Literally "and upon you (be) peace". Extended polite forms add: ورحمة الله وبركاته wa-raḥmatu llāhi wa-barakātuh ("and the mercy of God and His blessings").', 'word', 'وعليكم السلام ورحمة الله.', 'Adding ورحمة الله raises the politeness; common with elders and in formal settings.', null, [ACT.vocabularyGreetings]),
    createContentItem('أهلًا وسهلًا', 'ahlan wa-sahlan', 'A warm welcome phrase, roughly "[you are] family and on easy ground". Used to receive guests — at home, at the workplace, by hotel staff. The shortened أهلًا alone is more casual.', 'word', 'أهلًا وسهلًا بك في الرياض!', 'Standard welcome to a visitor; replaces "welcome" in both casual and formal contexts.', null, [ACT.vocabularyGreetings]),
    createContentItem('مرحبا', 'marḥaban', 'A friendly secular greeting "hello/welcome". More casual than السلام عليكم; used freely among peers, in shops, on the phone. Reply: مرحبتين marḥabtayn ("two-hellos") or just مرحبا.', 'word', 'مرحبا! كيف الحال؟', 'Casual opener paired with "how are you?" — typical peer-to-peer turn.', null, [ACT.vocabularyGreetings]),
    createContentItem('صباح الخير', 'ṣabāḥ al-khayr', 'A polite-to-formal morning greeting "morning of goodness", used roughly from sunrise to noon. The conventional reply is صباح النور ṣabāḥ an-nūr ("morning of light") — a poetic exchange.', 'word', 'صباح الخير، أستاذ! — صباح النور.', 'Polite morning greeting to a professor; the reply pair feels formulaic but warm.', null, [ACT.vocabularyGreetings]),
    createContentItem('مساء الخير', 'masāʾ al-khayr', 'A polite-to-formal evening greeting "evening of goodness", used from afternoon through night. Reply: مساء النور masāʾ an-nūr. Same template as the morning pair.', 'word', 'مساء الخير، أهلًا بك. — مساء النور.', 'Polite afternoon/evening greeting; common in restaurants, shops, formal arrivals.', null, [ACT.vocabularyGreetings]),
    createContentItem('كيف حالك', 'kayfa ḥāluk(a)? (M) / kayfa ḥāluki? (F)', 'The standard "how are you?" — heavier than the colloquial كيفك. Note gender: -ka for a man, -ki for a woman. Reply الحمد لله al-ḥamdu li-llāh ("praise be to God"), with optional بخير bi-khayr ("well").', 'word', 'كيف حالك؟ — الحمد لله، بخير.', 'High-frequency formula; الحمد لله is the default reply regardless of how you actually feel.', null, [ACT.vocabularyGreetings]),
    createContentItem('الحمد لله', 'al-ḥamdu li-llāh', '"Praise be to God." The default reply to كيف حالك and a constant filler of Arab conversation. Even non-Muslims in Arab countries use it freely; it carries no proselytizing meaning and signals gratitude for any positive state.', 'word', 'كيف حالك؟ — الحمد لله، بخير، وأنت؟', 'Standard reply followed by "and you?" to return the question.', null, [ACT.vocabularyGreetings]),
    createContentItem('تشرفت بمعرفتك', 'tasharraftu bi-maʿrifatik', '"I am honored by your acquaintance" — a formal first-meeting phrase. Higher register than the casual فرصة سعيدة. Reply: الشرف لي ash-sharafu lī ("the honor is mine").', 'word', 'تشرفت بمعرفتك، يا أستاذ. — الشرف لي.', 'Formal exchange; standard for meeting senior colleagues, dignitaries, or in business introductions.', null, [ACT.vocabularyGreetings]),
    createContentItem('فرصة سعيدة', 'furṣa saʿīda', '"Happy opportunity" — a polite first-meeting phrase, roughly equivalent to "nice to meet you". Less formal than تشرفت but warmer than a bare greeting. Reply often أنا أسعد anā asʿad ("I am happier") or السعادة لي.', 'word', 'فرصة سعيدة، اسمي خالد. — أنا أسعد، اسمي عمر.', 'Polite peer-level first-meeting exchange; common at conferences and academic events.', null, [ACT.vocabularyGreetings]),
    createContentItem('مع السلامة', 'maʿa s-salāma', 'The standard farewell "with safety/peace". Used in any register — workplace, customer service, family. Slightly more deliberate than إلى اللقاء.', 'word', 'مع السلامة! نشوفك غدًا. — مع السلامة.', 'Polite farewell paired with "see you tomorrow"; مع السلامة also serves as the reply.', null, [ACT.vocabularyGreetings]),
    createContentItem('إلى اللقاء', 'ilā l-liqāʾ', '"Until the meeting" — a slightly more formal farewell, common in writing and at the end of formal events. In speech, مع السلامة is more frequent.', 'word', 'إلى اللقاء، وشكرًا لكم.', 'Formal closing of a meeting or letter; pairs well with thanking.', null, [ACT.vocabularyGreetings]),
    createContentItem('في أمان الله', 'fī amāni llāh', '"In God\'s safekeeping" — a warm, slightly religious farewell common with family and close friends. Reply: في أمان الكريم fī amāni l-Karīm ("in the Generous One\'s safekeeping").', 'word', 'في أمان الله، يا أمي.', 'Family-warm farewell; less common in pure business but acceptable in any non-secular context.', null, [ACT.vocabularyGreetings]),

    // Activity 4 — Vocabulary II: People, roles, nationalities
    createContentItem('أنا', 'anā', 'First-person singular pronoun "I". Gender-neutral; same for men and women. Appears in nominal sentences with no copula: أنا طالب = "I am a student".', 'word', 'أنا طالب في الجامعة.', 'The simplest possible self-introduction: pronoun + role; note no "am".', null, [ACT.vocabularyPeople]),
    createContentItem('أنتَ', 'anta', 'Second-person MASCULINE singular pronoun "you". Always carries the fatha-marked ـتَ ending in MSA, distinguishing it from feminine أنتِ. Use only with men.', 'word', 'أنت طالب أم أستاذ؟', '"Are you a student or a professor?" addressed to a man.', null, [ACT.vocabularyPeople]),
    createContentItem('أنتِ', 'anti', 'Second-person FEMININE singular pronoun "you", with kasra-marked ـتِ ending. Use only with women. Mixing up أنتَ and أنتِ is a noticeable beginner error.', 'word', 'أنتِ طالبة في الجامعة؟', '"Are you a student at the university?" addressed to a woman.', null, [ACT.vocabularyPeople]),
    createContentItem('هو', 'huwa', 'Third-person masculine singular pronoun "he/it". Used for any male person and for some grammatically masculine inanimate nouns.', 'word', 'هو صديقي من سوريا.', '"He is my friend from Syria."', null, [ACT.vocabularyPeople]),
    createContentItem('هي', 'hiya', 'Third-person feminine singular pronoun "she/it". Used for any female person and for grammatically feminine nouns (including most ة-ending nouns and irregular feminines).', 'word', 'هي أستاذة في جامعة القاهرة.', '"She is a professor at Cairo University." — note feminine ـة on أستاذة.', null, [ACT.vocabularyPeople]),
    createContentItem('نحن', 'naḥnu', 'First-person plural pronoun "we". Gender-neutral. The predicate noun agrees in plural form: نحن طلاب = "we are students-M" or نحن طالبات for women.', 'word', 'نحن طلاب من نيجيريا.', 'Plural self-identification using broken plural طلاب of طالب.', null, [ACT.vocabularyPeople]),
    createContentItem('أنتم', 'antum', 'Second-person MASCULINE plural pronoun "you all". Used for groups of men or mixed-gender groups (Arabic defaults to masculine in mixed groups). For all-women groups use أنتن antunna.', 'word', 'أنتم طلاب من أين؟', '"You-pl are students from where?" — addressed to a mixed-gender or male group.', null, [ACT.vocabularyPeople]),
    createContentItem('هم', 'hum', 'Third-person MASCULINE plural pronoun "they". Used for male or mixed-gender groups. For all-women: هن hunna.', 'word', 'هم أصدقائي من المغرب.', '"They are my friends from Morocco."', null, [ACT.vocabularyPeople]),
    createContentItem('اسم', 'ism', 'Name (given name or full name). Combines with possessive suffixes: اسمي ismī (my name), اسمك ismuk (your name-M)/ismuki (your name-F), اسمه ismuh (his name), اسمها ismuhā (her name).', 'word', 'ما اسمك؟ — اسمي يوسف.', '"What is your name? — My name is Yusuf." — the most common name-introduction exchange.', null, [ACT.vocabularyPeople]),
    createContentItem('سيد', 'sayyid', 'Title "Mr." used before a man\'s name (السيد محمد = Mr. Muhammad). Reserved for adult men in formal contexts; in academic and professional settings الأستاذ is often preferred.', 'word', 'السيد أحمد مدير الشركة.', '"Mr. Ahmad is the manager of the company."', null, [ACT.vocabularyPeople]),
    createContentItem('سيدة', 'sayyida', 'Title "Mrs./Ms." used before a woman\'s name (السيدة فاطمة). Marital status is not strongly implied — modern usage is generally Ms.', 'word', 'السيدة منى أستاذة في الجامعة.', '"Ms. Mona is a professor at the university."', null, [ACT.vocabularyPeople]),
    createContentItem('آنسة', 'ānisa', 'Title "Miss" used for unmarried young women. Less common in modern formal usage; many contexts prefer the neutral سيدة. Still common in school/university contexts addressing female teachers.', 'word', 'الآنسة سارة، شكرًا لك.', '"Miss Sara, thank you." — common in a classroom-teacher context.', null, [ACT.vocabularyPeople]),
    createContentItem('أستاذ', 'ustādh', 'Title "Professor/Mr./Master". Used for university faculty AND as a respectful address for any adult man (similar to "sir" but warmer). الأستاذ + first name is a polite default in many professional contexts.', 'word', 'الأستاذ محمد يشرح الدرس.', '"Professor Muhammad is explaining the lesson."', null, [ACT.vocabularyPeople]),
    createContentItem('أستاذة', 'ustādha', 'Feminine of أستاذ: "Professor/Ms./Madam". الأستاذة + first name is the standard polite address for any adult woman in academic and professional settings.', 'word', 'الأستاذة فاطمة عالمة في الفيزياء.', '"Professor Fatima is a scientist in physics."', null, [ACT.vocabularyPeople]),
    createContentItem('دكتور', 'duktūr', 'Title "Doctor" — used for both medical doctors AND PhD holders, like in English. الدكتور + first name is standard in academic and medical contexts.', 'word', 'الدكتور سامي طبيب القلب.', '"Dr. Sami is a cardiologist." — قلب means "heart".', null, [ACT.vocabularyPeople]),
    createContentItem('طالب', 'ṭālib', 'A male student. Literal meaning: "one who seeks" — from the root ط ل ب "to seek/request". Active participle pattern فَاعِل.', 'word', 'أنا طالب في جامعة الملك سعود.', '"I am a student at King Saud University." — note the إضافة construction "university of King Saud".', null, [ACT.vocabularyPeople]),
    createContentItem('طالبة', 'ṭāliba', 'A female student. Formed by adding ـة to طالب — the standard masculine→feminine derivation for human-reference nouns.', 'word', 'أنا طالبة في كلية الهندسة.', '"I am a student (F) in the College of Engineering."', null, [ACT.vocabularyPeople]),
    createContentItem('مهندس', 'muhandis', 'An engineer (any discipline). Pattern مُفَعِّل (Form II active participle, but lexicalized). For a woman: مهندسة muhandisa.', 'word', 'أبي مهندس كهرباء.', '"My father is an electrical engineer." — كهرباء "electricity".', null, [ACT.vocabularyPeople]),
    createContentItem('طبيب', 'ṭabīb', 'A medical doctor. Synonym of دكتور in the medical sense but more formal/literary. Feminine: طبيبة ṭabība.', 'word', 'أمي طبيبة أطفال.', '"My mother is a pediatrician." — أطفال "children".', null, [ACT.vocabularyPeople]),
    createContentItem('عربي / عربية', 'ʿarabī / ʿarabiyya', 'An Arab person (M/F) — formed by attaching the nisba ending ـيّ (M) / ـيّة (F) to the noun عرب "Arabs". This pattern works for nationalities and many other affiliations.', 'word', 'أنا عربي من المغرب. / أنا عربية من تونس.', '"I am Arab, from Morocco." / "I am Arab, from Tunisia."', null, [ACT.vocabularyPeople]),
    createContentItem('مصري / مصرية', 'miṣrī / miṣriyya', 'Egyptian (M/F). Nisba from مصر Miṣr (Egypt). Like all nisba adjectives, the final ـيّ/ـيّة attaches to the country noun.', 'word', 'صديقي مصري من القاهرة.', '"My friend is Egyptian, from Cairo." — القاهرة is Cairo.', null, [ACT.vocabularyPeople]),
    createContentItem('سعودي / سعودية', 'saʿūdī / saʿūdiyya', 'Saudi (M/F). Nisba from آل سعود Āl Suʿūd, the Saudi royal family — the country is named after them. السعودية also serves as the short name of the country (Saudi Arabia).', 'word', 'أنا طالب سعودي في جامعة الملك سعود.', '"I am a Saudi student at King Saud University."', null, [ACT.vocabularyPeople]),
    createContentItem('سوري / سورية', 'sūrī / sūriyya', 'Syrian (M/F). Nisba from سوريا Sūriyā.', 'word', 'صديقتي سورية من دمشق.', '"My friend (F) is Syrian, from Damascus."', null, [ACT.vocabularyPeople]),
    createContentItem('لبناني / لبنانية', 'lubnānī / lubnāniyya', 'Lebanese (M/F). Nisba from لبنان Lubnān (Lebanon).', 'word', 'هو لبناني من بيروت.', '"He is Lebanese, from Beirut." — بيروت Bayrūt.', null, [ACT.vocabularyPeople]),
    createContentItem('أردني / أردنية', 'urdunī / urduniyya', 'Jordanian (M/F). Nisba from الأردن al-Urdun.', 'word', 'الأستاذ خالد أردني من عمان.', '"Professor Khalid is Jordanian, from Amman."', null, [ACT.vocabularyPeople]),
    createContentItem('فلسطيني / فلسطينية', 'filasṭīnī / filasṭīniyya', 'Palestinian (M/F). Nisba from فلسطين Filasṭīn.', 'word', 'أصلي فلسطيني من القدس.', '"My origin is Palestinian, from Jerusalem." — القدس "Jerusalem".', null, [ACT.vocabularyPeople]),
    createContentItem('عراقي / عراقية', 'ʿirāqī / ʿirāqiyya', 'Iraqi (M/F). Nisba from العراق al-ʿIrāq.', 'word', 'هو عراقي من بغداد.', '"He is Iraqi, from Baghdad." — بغداد Baghdād.', null, [ACT.vocabularyPeople]),
    createContentItem('إماراتي / إماراتية', 'imārātī / imārātiyya', 'Emirati (M/F). Nisba from الإمارات al-Imārāt (the Emirates, short for UAE).', 'word', 'صديقي إماراتي من دبي.', '"My friend is Emirati, from Dubai." — دبي Dubay.', null, [ACT.vocabularyPeople]),
    createContentItem('أمريكي / أمريكية', 'amrīkī / amrīkiyya', 'American (M/F). Nisba from أمريكا Amrīkā.', 'word', 'هي أمريكية من نيويورك.', '"She is American, from New York."', null, [ACT.vocabularyPeople]),
    createContentItem('نيجيري / نيجيرية', 'nayjīrī / nayjīriyya', 'Nigerian (M/F). Nisba from نيجيريا Nayjīriyā.', 'word', 'أنا نيجيري من لاغوس.', '"I am Nigerian, from Lagos."', null, [ACT.vocabularyPeople]),
    createContentItem('كوري / كورية', 'kūrī / kūriyya', 'Korean (M/F). Nisba from كوريا Kūriyā.', 'word', 'هو كوري من سيول.', '"He is Korean, from Seoul." — سيول Sūl.', null, [ACT.vocabularyPeople]),
    createContentItem('صيني / صينية', 'ṣīnī / ṣīniyya', 'Chinese (M/F). Nisba from الصين aṣ-Ṣīn (China). Note the emphatic ص.', 'word', 'صديقتي صينية من بكين.', '"My friend (F) is Chinese, from Beijing."', null, [ACT.vocabularyPeople]),

    // Activity 5 — Grammar I: Personal pronouns and gender
    createContentItem(
      'الضمائر المنفصلة',
      'aḍ-ḍamāʾir al-munfaṣila',
      'MSA has 12 personal pronouns covering 3 persons × 3 numbers (singular/dual/plural) × gender. The dual forms (أنتما, هما) have no English equivalent — they refer specifically to TWO people. Gender is marked from the 2nd person onward.',
      'sentence',
      'SG: أنا, أنتَ/أنتِ, هو/هي · DUAL: أنتما, هما · PL: نحن, أنتم/أنتن, هم/هن',
      'Twelve pronouns total — but in casual MSA the dual is rare in speech and 5 forms cover 90% of needs.',
      [
        { target: 'أنا anā (I, M/F)', note: 'gender-neutral in the 1st person' },
        { target: 'أنتَ anta / أنتِ anti', note: '2nd-person singular — masc and fem forms' },
        { target: 'هو huwa / هي hiya', note: '3rd-person singular — he/she' },
        { target: 'نحن naḥnu (we, M/F)', note: '1st-person plural — gender-neutral' },
        { target: 'أنتم antum / أنتن antunna', note: '2nd-person plural — masc and fem' },
        { target: 'هم hum / هن hunna', note: '3rd-person plural — masc and fem' },
        { target: 'أنتما, هما (dual)', note: 'used when addressing or referring to exactly two people' },
      ],
      [ACT.grammarPronouns],
    ),
    createContentItem(
      'التمييز بين أنتَ و أنتِ',
      'at-tamyīz bayna anta wa-anti',
      'Critical gender contrast: أنتَ (anta, /-ta/) for a man, أنتِ (anti, /-ti/) for a woman. The vowel mark is the only written difference but the meaning is binary. Using the wrong form with someone you know is a noticeable error.',
      'sentence',
      'To a man: ما اسمك؟ mā smuka? · To a woman: ما اسمكِ؟ mā smuki?',
      'The whole grammatical system propagates gender: the pronoun, the verb, the adjective, and the suffixes all change.',
      [
        { target: 'أنتَ anta (M)', note: 'fatha on ت — masculine' },
        { target: 'أنتِ anti (F)', note: 'kasra on ت — feminine' },
        { target: 'صديقكَ / صديقكِ', note: '"your friend" — same gender split on the suffix' },
      ],
      [ACT.grammarPronouns],
    ),
    createContentItem(
      'مطابقة الجنس في الخبر',
      'muṭābaqat al-jins fī al-khabar',
      'Gender agreement in the predicate: the predicate noun or adjective MUST match the subject in gender. هو طالب (he is a student-M); هي طالبة (she is a student-F); هم طلاب (they-M are students); هن طالبات (they-F are students).',
      'sentence',
      'M: هو مصري / F: هي مصرية · M-pl: هم مصريون / F-pl: هن مصريات',
      'Every adjective, every participle, every nominal predicate must agree — failing to do so is the most common beginner error.',
      [
        { target: 'M sg: طالب / مصري', note: 'no ـة' },
        { target: 'F sg: طالبة / مصرية', note: 'ـة or ـيّة' },
        { target: 'M pl: طلاب / مصريون', note: 'broken plural or sound masculine plural ـون' },
        { target: 'F pl: طالبات / مصريات', note: 'sound feminine plural ـات' },
      ],
      [ACT.grammarPronouns],
    ),

    // Activity 6 — Grammar II: Nominal sentence
    createContentItem(
      'الجملة الاسمية',
      'al-jumla al-ismiyya',
      'The "nominal sentence" — Arabic\'s most distinctive feature for English speakers: in the PRESENT tense, there is NO copula (no "am/is/are"). A sentence is just subject (مبتدأ) + predicate (خبر).',
      'sentence',
      'أنا طالب = "I [am] a student"\nالكتاب جميل = "The book [is] beautiful"\nأحمد في الجامعة = "Ahmad [is] at the university"',
      'In past or future tense, the copula كان appears; in the present, it is completely absent.',
      [
        { target: 'مبتدأ (subject)', note: 'usually starts the sentence; usually definite (with الـ) or a proper noun/pronoun' },
        { target: 'خبر (predicate)', note: 'usually indefinite (no الـ); follows the subject directly' },
        { target: 'no copula', note: 'Arabic has no "to be" verb in the present tense' },
      ],
      [ACT.grammarNominalSentence],
    ),
    createContentItem(
      'تعريف المبتدأ',
      'taʿrīf al-mubtadaʾ',
      'The subject (مبتدأ) is usually DEFINITE: a proper noun (أحمد), a personal pronoun (أنا), or a noun with الـ (الكتاب). The predicate is usually INDEFINITE (no الـ). Reversing this can flip the meaning.',
      'sentence',
      'الطالب طالب (definite + indefinite) = "The student is a student" — sensible nominal sentence\nطالب الطالب (indefinite + definite) = "A student of the student" — an إضافة construction, NOT a sentence!',
      'A common parsing trap: definite + indefinite makes a sentence; indefinite + definite makes a noun phrase.',
      null,
      [ACT.grammarNominalSentence],
    ),
    createContentItem(
      'سؤال نعم/لا بـ هل',
      'suʾāl naʿam/lā bi-hal',
      'Form a yes/no question by placing هل (hal) at the start of any nominal sentence. Word order does NOT change. Alternative: أَ before the first word (more literary).',
      'sentence',
      'Statement: أنت طالب\nYes/no Q: هل أنت طالب؟ ("Are you a student?")\nLiterary Q: أَأَنْت طالب؟',
      'هل is the everyday MSA question word; أَ appears more in literary and classical Arabic.',
      [
        { target: 'هل + sentence', note: 'the standard yes/no question opener' },
        { target: 'reply: نعم naʿam', note: 'yes' },
        { target: 'reply: لا lā', note: 'no' },
      ],
      [ACT.grammarNominalSentence],
    ),
    createContentItem(
      'كلمات الاستفهام',
      'kalimāt al-istifhām',
      'Information questions use a question word at the START of the sentence: مَن man (who), ما mā (what, for non-humans), أَيْن ayna (where), مِنْ أَيْن min ayna (from where), كَيْف kayf (how), مَتَى matā (when), لِمَاذَا limādhā (why), كَمْ kam (how many).',
      'sentence',
      'ما اسمك؟ "What is your name?"\nمن أين أنت؟ "Where are you from?"\nكيف حالك؟ "How are you?"\nمن هذا؟ "Who is this?"',
      'Word order: question word first, then the rest of the nominal sentence with no inversion needed.',
      [
        { target: 'ما mā', note: 'what — for objects, abstracts, non-humans' },
        { target: 'من man', note: 'who — for humans' },
        { target: 'أين ayna', note: 'where' },
        { target: 'كيف kayf', note: 'how' },
        { target: 'متى matā', note: 'when' },
      ],
      [ACT.grammarNominalSentence],
    ),

    // Activity 7 — Grammar III: Negation
    createContentItem(
      'النفي بـ ليس',
      'an-nafy bi-laysa',
      'To negate a nominal sentence in MSA, use the special verb-like negator ليس (laysa). It conjugates for person and gender like a past-tense verb, but its meaning is present negation.',
      'sentence',
      'أنا لستُ طالبًا = "I am not a student"\nهو ليس مصريًا = "He is not Egyptian"\nهي ليست هنا = "She is not here"',
      'Note that the predicate after ليس takes the accusative case (ـًا) — ليس governs its predicate like a verb governs its object.',
      [
        { target: 'لستُ lastu (I am not)', note: '1st person singular' },
        { target: 'لستَ lasta (you-M are not)', note: '2nd masc singular' },
        { target: 'لستِ lasti (you-F are not)', note: '2nd fem singular' },
        { target: 'ليس laysa (he is not)', note: '3rd masc singular — the "citation form"' },
        { target: 'ليست laysat (she is not)', note: '3rd fem singular' },
        { target: 'لسنا lasnā (we are not)', note: '1st plural' },
        { target: 'لستم lastum (you-pl-M are not)', note: '2nd masc plural' },
        { target: 'ليسوا laysū (they-M are not)', note: '3rd masc plural' },
      ],
      [ACT.grammarNegation],
    ),
    createContentItem(
      'حالة الخبر بعد ليس',
      'ḥālat al-khabar baʿd laysa',
      'IMPORTANT: the predicate after ليس must be in the ACCUSATIVE case (manṣūb), marked with ـًا (tanwīn al-fatḥ) on indefinite singular nouns. This is unique to ليس and a few other "verbs of being and becoming" (kāna wa-akhawātuhā).',
      'sentence',
      'هو طالب (nominative, no negation) → هو ليس طالبًا (accusative, after ليس)\nهي مصرية → هي ليست مصريةً',
      'In rapid speech the case ending is often dropped, but in MSA written form and careful speech it is required.',
      [
        { target: 'بدون ليس: nominative', note: 'predicate carries ـٌ or no marking; default form' },
        { target: 'بعد ليس: accusative', note: 'predicate carries ـًا — manṣūb case' },
      ],
      [ACT.grammarNegation],
    ),
    createContentItem(
      'ليس … بل …',
      'laysa … bal …',
      'The polite "not X, but Y" correction pattern: لستُ X، بل Y. Used to politely deny a wrong guess and offer the correct alternative. The conjunction بل (bal) means "rather/but".',
      'sentence',
      'A: هل أنت مصري؟ — B: لا، لستُ مصريًا، بل سوري.\n("Are you Egyptian? — No, I am not Egyptian, rather I am Syrian.")',
      'The three-part rhythm (denial + wrong item + correct alternative) makes the correction feel natural rather than blunt.',
      [
        { target: 'لا (initial denial)', note: '"no" — opens the correction politely' },
        { target: 'لستُ X (negation with case)', note: 'predicate in accusative ـًا' },
        { target: 'بل Y (alternative)', note: 'closes the loop with the correct answer' },
      ],
      [ACT.grammarNegation],
    ),

    // Activity 8 — Reading & Speaking
    createContentItem(
      'التعارف',
      'at-taʿāruf',
      'A complete five-sentence self-introduction in MSA. Read it aloud with correct emphatics, pharyngeals, sun-letter assimilation, and vowel length. Notice the parallel nominal-sentence structure.',
      'sentence',
      'السلامُ عليكم! اسمي سارة، وأنا أمريكية. أنا طالبة في جامعة الملك سعود في الرياض. تخصصي هندسة الحاسوب. تشرفت بمعرفتكم.',
      'Translation: "Peace be upon you! My name is Sarah, and I am American. I am a student at King Saud University in Riyadh. My major is computer engineering. I am honored to meet you."',
      [
        { target: 'اسمي سارة ismī Sāra', note: 'name introduction with ـي "my" possessive suffix' },
        { target: 'أنا أمريكية anā amrīkiyya', note: 'nationality with nisba ending; feminine form because the speaker is a woman' },
        { target: 'طالبة في جامعة الملك سعود', note: '"student at King Saud University" — إضافة chain: جامعة + الملك + سعود' },
        { target: 'تخصصي هندسة الحاسوب', note: '"my major is computer engineering" — تخصص (specialization) + ـي possessive' },
        { target: 'تشرفت بمعرفتكم', note: 'formal closing of a first-meeting introduction; ـكم plural addresses a mixed audience' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'أسئلة الفهم',
      'asʾilat al-fahm',
      'Four standard comprehension questions matching the paragraph. Answer each in a short nominal sentence — Arabic does not require full sentences for natural conversational answers.',
      'sentence',
      'Q1: ما اسمها؟ Q2: ما جنسيتها؟ Q3: في أي جامعة هي تدرس؟ Q4: ما تخصصها؟',
      'Two information questions, one location question, one specific-detail — covering all the patterns from this lesson.',
      [
        { target: 'A1: اسمها سارة.', note: 'name answer with ـها "her" possessive' },
        { target: 'A2: هي أمريكية.', note: 'nationality answer with feminine nisba' },
        { target: 'A3: في جامعة الملك سعود.', note: 'prepositional phrase short answer' },
        { target: 'A4: هندسة الحاسوب.', note: 'noun-phrase short answer — full sentence not required' },
      ],
      [ACT.reading],
    ),

    // Activity 9 — Listening & Speaking
    createContentItem(
      'لقاء أول (حوار — مهذب)',
      'liqāʾ awwal (ḥiwār — muhadhdhab)',
      'A natural polite-register first-meeting conversation between two students at King Saud University. Covers all the patterns from this lesson: greetings, names, origins, roles, and farewells.',
      'conversation',
      'أ: السلام عليكم! اسمي خالد.\nب: وعليكم السلام، يا خالد! اسمي سارة. فرصة سعيدة.\nأ: من أين أنتِ؟\nب: أنا من أمريكا. وأنت؟\nأ: أنا سعودي من الرياض. هل أنتِ طالبة هنا؟\nب: نعم، أنا طالبة في كلية الهندسة. وأنت؟\nأ: أنا أيضًا في كلية الهندسة! ما تخصصك؟\nب: هندسة الحاسوب. ممتاز، أراك في الفصل!',
      'A natural exchange between peers using the polite-but-warm register — the default for student-age interactions in the Arab world.',
      [
        { target: 'فرصة سعيدة', note: '"happy opportunity" — first-meeting polite phrase; appears as Sara\'s opening response' },
        { target: 'وأنت؟ wa-anta? / وأنتِ؟ wa-anti?', note: '"and you?" — standard return-the-question; note gender form' },
        { target: 'من أين أنتِ؟', note: 'origin question with the feminine pronoun because asking a woman' },
        { target: 'أنا أيضًا anā ayḍan', note: '"I too / me also" — adverbial use of أيضًا' },
        { target: 'ممتاز mumtāz', note: '"excellent" — common positive reaction word' },
        { target: 'أراك في الفصل', note: '"I\'ll see you in class" — first-person present verb أرى + ـك suffix' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'لقاء أول (حوار — رسمي)',
      'liqāʾ awwal (ḥiwār — rasmī)',
      'A formal first-meeting conversation suitable for academic or professional contexts. Notice the formal vocabulary: حضرتك, تشرفت, الأستاذ + name — register markers signaling a more deliberate interaction.',
      'conversation',
      'الطالب: السلام عليكم، يا أستاذ! تشرفت بمعرفتكم. اسمي عمر فاروق.\nالأستاذ: وعليكم السلام، يا عمر. أهلًا وسهلًا بك في الجامعة. الشرف لي.\nالطالب: شكرًا لكم، يا أستاذ. أتطلع إلى حضور محاضراتكم.\nالأستاذ: من أين حضرتك؟\nالطالب: أنا من نيجيريا، من لاغوس.\nالأستاذ: ممتاز. أتمنى لك التوفيق في دراستك.\nالطالب: شكرًا جزيلًا، يا أستاذ. مع السلامة.',
      'Same information as the polite version but with formal phrasing throughout — appropriate for hierarchical (student-professor) relationships in the Arab academic world.',
      [
        { target: 'تشرفت بمعرفتكم tasharraftu bi-maʿrifatikum', note: 'formal first-meeting phrase; the ـكم suffix shows respect (treating a single senior person as plural)' },
        { target: 'حضرتك ḥaḍratuk', note: 'formal "you" used with senior people; literally "your presence" — replaces أنت/أنتِ' },
        { target: 'أتطلع إلى حضور محاضراتكم', note: '"I look forward to attending your lectures" — formal academic phrasing' },
        { target: 'أتمنى لك التوفيق atamannā laka t-tawfīq', note: '"I wish you success" — standard formal good-wishing phrase' },
        { target: 'شكرًا جزيلًا shukran jazīlan', note: '"thank you very much" — uses the accusative tanwīn ـًا' },
      ],
      [ACT.listening],
    ),

    // Activity 10 — Writing
    createContentItem(
      'قالب الكتابة',
      'qālab al-kitāba',
      'A reusable five-sentence template for any MSA self-introduction. Fill in the bracketed slots with your own information — the structure carries the rest.',
      'sentence',
      'السلام عليكم! اسمي [الاسم]. أنا [الجنسية بصيغة المذكر/المؤنث]. أنا [الدور] في [المؤسسة]. [حقيقة إضافية واحدة]. تشرفت بمعرفتكم.',
      'Five sentences cover the core: greeting, name, nationality, role, personal fact, closing — the minimum complete self-introduction.',
      [
        { target: '[الاسم]', note: 'your name — given name in casual contexts, full name in formal' },
        { target: '[الجنسية]', note: 'your nationality with correct gender nisba ending (ـي for men, ـيّة for women)' },
        { target: '[الدور]', note: 'طالب/طالبة / أستاذ/أستاذة / مهندس/مهندسة — the noun for your role' },
        { target: '[المؤسسة]', note: 'institution name — usually with إضافة construction (جامعة + city/founder)' },
        { target: '[حقيقة إضافية]', note: 'something specific (hobby, major, favorite thing); avoid generic facts' },
      ],
      [ACT.writing],
    ),
    createContentItem(
      'تمرين الكتابة',
      'tamrīn al-kitāba',
      'Write your own 3–5 sentence self-introduction in Arabic script using the template. Use at least two nominal sentences and one nisba adjective so the writing demonstrates the core grammar.',
      'sentence',
      'مثال: السلام عليكم! اسمي كيم جي-سو. أنا كورية. أنا طالبة في جامعة الملك سعود. أحب اللغة العربية والموسيقى. تشرفت بمعرفتكم!',
      'Translation: "Peace be upon you! My name is Kim Ji-soo. I am Korean. I am a student at King Saud University. I love the Arabic language and music. I am honored to meet you!"',
      null,
      [ACT.writing],
    ),

    // Activity 11 — Culture Note
    createContentItem(
      'السلام عليكم — تحية عالمية',
      'as-salāmu ʿalaykum — taḥiyya ʿālamiyya',
      'The greeting السلام عليكم is universal across all 22 Arab countries, all registers (casual to formal), and all relationships (peer to senior). Even non-Muslims in Arab countries use and receive this greeting freely; it carries no proselytizing meaning and is the safest first-meeting phrase a learner can use.',
      'sentence',
      'A: السلام عليكم — B: وعليكم السلام / وعليكم السلام ورحمة الله / وعليكم السلام ورحمة الله وبركاته',
      'The reply can be extended for extra warmth: adding ورحمة الله ("and God\'s mercy") or further ورحمة الله وبركاته ("and His blessings") raises the politeness level.',
      [
        { target: 'short reply: وعليكم السلام', note: 'standard, neutral' },
        { target: 'medium: وعليكم السلام ورحمة الله', note: 'slightly warmer' },
        { target: 'full: وعليكم السلام ورحمة الله وبركاته', note: 'most formal — used with elders and in religious contexts' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'الكنية — أبو فلان / أم فلان',
      'al-kunya — Abū fulān / Umm fulān',
      'The kunya is a teknonymy: a respectful nickname formed from "father/mother of" + the eldest son\'s name. أبو أحمد Abu Ahmad = "father of Ahmad". Used even before a man has a son, often based on his own father\'s name or a culturally appropriate son\'s name. Common in social and business contexts as a warmer, more respectful form of address.',
      'sentence',
      'أبو خالد Abū Khālid (father of Khalid) · أم محمد Umm Muḥammad (mother of Muhammad)',
      'In some Arab countries (Gulf, Levant), the kunya is preferred over the first name in many contexts — calling a man Abu-Khalid signals respect.',
      [
        { target: 'أبو + son name', note: 'father of (a man\'s kunya)' },
        { target: 'أم + son name', note: 'mother of (a woman\'s kunya)' },
        { target: 'usage', note: 'respectful address, especially in Gulf and Levantine social contexts' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'الألقاب — أستاذ/دكتور + الاسم',
      'al-alqāb — ustādh/duktūr + al-ism',
      'Professionals are addressed by title + first name, much more commonly than by first name alone. الأستاذ محمد (Mr./Professor Muhammad), الدكتور سامي (Dr. Sami), المهندس خالد (Engineer Khalid). The title الـ + name format is the polite default in any professional Arab context.',
      'sentence',
      'الأستاذ محمد (Professor/Mr. Muhammad) · الدكتورة فاطمة (Dr. Fatima, F) · المهندس عمر (Engineer Omar) · الشيخ عبد الله (Sheikh Abdullah)',
      'Job titles often double as honorifics — calling someone by title + name is more respectful than just their first name.',
      [
        { target: 'الأستاذ + name', note: 'professors, adult men in formal/professional contexts — also "sir"-like' },
        { target: 'الدكتور + name', note: 'medical doctors AND PhD holders' },
        { target: 'المهندس + name', note: 'engineers (a high-prestige title in the Gulf)' },
        { target: 'الشيخ + name', note: 'religious scholars OR senior/elder men of standing' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'حضرتك / سيادتك',
      'ḥaḍratuk / siyādatuk',
      'Formal "you" substitutes used to show extra respect. حضرتك (literally "your presence") replaces أنت/أنتِ when addressing customers, elders, professors, or anyone you wish to honor. سيادتك (literally "your sovereignty") is even more formal, used with very senior officials, judges, and high-ranking professionals.',
      'sentence',
      'كيف حال حضرتك؟ ("How is your-presence?", i.e., "How are you?" said respectfully)\nسيادتك معاليّ الوزير ("Your sovereignty, His Excellency the Minister")',
      'Switching from أنت to حضرتك mid-conversation signals increased respect; the reverse signals familiarity.',
      [
        { target: 'حضرتك (general formal)', note: 'replaces أنت/أنتِ with seniors, customers, elders' },
        { target: 'سيادتك (very formal)', note: 'for officials, judges, top management' },
        { target: 'معاليّ maʿālī', note: '"Your Excellency" — for ministers' },
        { target: 'سُمُوّ sumūw', note: '"Your Highness" — for royalty in Gulf countries' },
      ],
      [ACT.culture],
    ),

    // Activity 12 — Task / Consolidation
    createContentItem(
      'المهمة: اليوم الأول في جامعة الملك سعود',
      'al-mahamma: al-yawm al-awwal fī jāmiʿat al-Malik Suʿūd',
      'Roleplay your first day at King Saud University with the AI tutor playing a friendly visiting scholar from Cairo. Use every skill from this lesson in one continuous scene — greet, introduce, ask, answer, farewell.',
      'conversation',
      '[في مختبر جامعة الملك سعود]\nالزائر: السلام عليكم! تشرفت بمعرفتك. اسمي أحمد.\nأنت: [تحية + تعارف]\nالزائر: من أين أنت؟\nأنت: [اذكر بلدك ومدينتك]\nالزائر: هل أنت طالب هنا؟\nأنت: [تأكيد + تخصصك]\nالزائر: ممتاز. ما تخصصك؟\nأنت: [أجب]\nالزائر: تشرفت بمعرفتك. أراك في المحاضرة.\nأنت: [وداع]',
      'Six turns of fluent exchange; the AI tutor will prompt you and respond naturally to whatever you say. Pay attention to gender agreement throughout.',
      [
        { target: 'تحية', note: 'وعليكم السلام / أهلًا — match the register of the visitor\'s opening' },
        { target: 'تعارف', note: 'اسمي … / أنا … — use the simplest nominal pattern' },
        { target: 'بلد', note: 'أنا من … / أنا [nisba] — choose city or country, watch gender' },
        { target: 'تخصص', note: 'تخصصي … or أدرس … — state your major' },
        { target: 'وداع', note: 'مع السلامة / إلى اللقاء — match the register you opened with' },
      ],
      [ACT.task],
    ),
    createContentItem(
      'التحدي — تصحيح افتراض',
      'at-taḥaddī — taṣḥīḥ iftirāḍ',
      'Stretch goal: in the same scene, the visiting scholar guesses your country incorrectly. Politely correct using the ليس … بل … pattern. Closes the loop without making the asker lose face.',
      'conversation',
      'الزائر: هل أنت مصري؟\nأنت: لا، لستُ مصريًا، بل أنا كوري من سيول.\nالزائر: عفوًا، آسف، أخطأت في الافتراض.\nأنت: لا بأس، لا بأس!',
      '"لا بأس" (lā baʾs) is a casual reassurance — "no harm/no problem" — standard after any small mistake or apology.',
      [
        { target: 'ليس … بل …', note: 'standard three-part polite correction pattern from Grammar III' },
        { target: 'لا بأس lā baʾs', note: 'casual reassurance; alternative to لا مشكلة' },
        { target: 'عفوًا ʿafwan', note: '"excuse me / pardon" — used for small apologies' },
        { target: 'آسف āsif (M) / آسفة āsifa (F)', note: '"sorry" — gender-marked' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
