// Level 1 Unit 3 — Locations & Places (Dutch)
// Functions: naming places, asking where things are, using location prepositions,
// describing your neighborhood, giving simple directions.

const createContentItem = (
  target,
  romanization,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization,
  nativeText: note,
  pronunciation: romanization,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'nl-l1u3-orientation',
  pronunciation: 'nl-l1u3-pronunciation',
  vocabularyPlaces: 'nl-l1u3-vocab-places',
  vocabularyPrepositions: 'nl-l1u3-vocab-prepositions',
  grammarWaar: 'nl-l1u3-grammar-waar',
  grammarStaanLiggen: 'nl-l1u3-grammar-staan-liggen',
  grammarDirections: 'nl-l1u3-grammar-directions',
  reading: 'nl-l1u3-reading',
  listening: 'nl-l1u3-listening',
  writing: 'nl-l1u3-writing',
  culture: 'nl-l1u3-culture',
  task: 'nl-l1u3-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Name 20+ everyday places (huis, school, café, station, bibliotheek, gracht, plein) and the city locations of Amsterdam, Utrecht, Den Haag, Rotterdam.',
      'Ask "Waar is...?" and answer with prepositional phrases (in, op, aan, naast, tegenover, achter, voor, onder, boven).',
      'Distinguish the locative verbs "staan" (stand, vertical), "liggen" (lie, horizontal), and "hangen" (hang) — Dutch is precise about object positioning.',
      'Give simple walking directions in Dutch: "Ga rechtdoor, sla rechtsaf bij de gracht, en het ligt aan je linkerhand."',
    ],
    task: 'Picture asking a passerby on Spui square in Amsterdam how to get to the UvA — by the end of this lesson, you handle the whole exchange in Dutch.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in location Dutch',
    goals: [
      'Pronounce "gracht" /xrɑxt/ — two velar fricatives in a four-letter word; an Amsterdam-specific sound test.',
      'Distinguish "links" /lɪŋks/ (left) from "rechts" /rɛxts/ (right) — both with -ks/-xts clusters and short vowels.',
      'Pronounce the locative-prepositional cluster "in de gracht" /ɪn də xrɑxt/ with natural rhythm.',
    ],
    task: 'Read each example aloud paying attention to the fricatives and consonant clusters.',
  },
  {
    id: ACT.vocabularyPlaces,
    section: 'Vocabulary I',
    title: 'Everyday places',
    goals: [
      'Memorize 20+ place nouns with their articles.',
      'Recognize iconic Dutch place categories: gracht (canal), markt (market), brug (bridge), plein (square).',
    ],
    task: 'List 15 places near your home with their correct articles.',
  },
  {
    id: ACT.vocabularyPrepositions,
    section: 'Vocabulary II',
    title: 'Location prepositions',
    goals: [
      'Use the 10 most common location prepositions: in, op, aan, naast, tegenover, achter, voor, onder, boven, tussen.',
      'Distinguish "in" (inside/enclosed) from "op" (on top of, also for islands and streets) — a perennial trap.',
      'Use "aan" (at, on the edge of) for things ON a wall or AT an institution: "aan de muur", "aan de UvA".',
    ],
    task: 'Describe your room using 8 different prepositions.',
  },
  {
    id: ACT.grammarWaar,
    section: 'Grammar I',
    title: '"Waar is...?" and "Hoe kom ik bij...?"',
    goals: [
      'Use "Waar is...?" for static location questions ("Where is the library?").',
      'Use "Hoe kom ik bij...?" or "Waar is hier de weg naar...?" for directional questions ("How do I get to...?").',
      'Answer with prepositional phrases: "Het is op de Spui" / "Het ligt aan de gracht" / "Het staat naast het station".',
    ],
    task: 'Ask 5 "Waar is...?" questions and answer each with a different preposition.',
  },
  {
    id: ACT.grammarStaanLiggen,
    section: 'Grammar II',
    title: 'staan / liggen / hangen — locative verbs',
    goals: [
      'Use "staan" /staːn/ for VERTICAL things: a glass on a table, a building, a person.',
      'Use "liggen" /ˈlɪɣə(n)/ for HORIZONTAL things: a book on a table, a city on a coast, a person in bed.',
      'Use "hangen" /ˈhɑŋə(n)/ for things that HANG: a painting on a wall, a coat on a hook, a fog over a city.',
      'Avoid "zijn" (to be) for location when context allows a locative verb — sounds flat. Dutch is precise: "Het boek ligt op de tafel" is better than "Het boek is op de tafel".',
    ],
    task: 'Describe 6 objects in your room using staan/liggen/hangen instead of generic "is".',
  },
  {
    id: ACT.grammarDirections,
    section: 'Grammar III',
    title: 'Giving simple directions',
    goals: [
      'Use directional verbs: gaan (to go), lopen (to walk), fietsen (to cycle), rijden (to drive).',
      'Use directional prepositions: naar (to/toward), langs (along), over (over/across), door (through), tot (until).',
      'Build a direction sentence: "Ga rechtdoor, sla rechtsaf bij de gracht, en de UvA ligt aan je linkerhand."',
    ],
    task: 'Give a 3-step direction from your home to the nearest train station.',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Read a neighborhood description',
    goals: [
      'Read a paragraph describing an Amsterdam neighborhood with the location vocabulary.',
      'Answer comprehension questions about the locations described.',
    ],
    task: 'Read the paragraph aloud, then answer four comprehension questions.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'Asking and giving directions',
    goals: [
      'Follow a 6-turn dialogue between a tourist and a local on Spui in Amsterdam.',
      'Reproduce the dialogue with a different destination.',
    ],
    task: 'Read the dialogue, then perform it with a new destination.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Describe your neighborhood',
    goals: [
      'Write 4-5 sentences about your neighborhood using locations, prepositions, and locative verbs.',
    ],
    task: 'Write the description and read it aloud.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'Amsterdam canals and city layout',
    goals: [
      'Recognize the Amsterdam canal-belt layout: Singel, Herengracht, Keizersgracht, Prinsengracht — UNESCO World Heritage.',
      'Understand the Dutch "fietsen" (cycling) culture: most movement around cities is by bike, not car.',
      'Recognize key Dutch cities: Amsterdam (capital, finance), Rotterdam (port), Den Haag (government), Utrecht (central rail hub), Eindhoven (tech/Philips).',
    ],
    task: 'Identify the 4 main Amsterdam canals and one major Dutch city for each function (finance, port, government, tech).',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'Asking for directions on Spui',
    goals: [
      'Combine the vocabulary and grammar into one continuous direction-asking scene.',
    ],
    task: 'Roleplay asking a passerby on Spui for directions to the UvA Library.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 3: Waar woon je? — Locations and Places',
  category: 'locations',
  difficulty: 'beginner',
  targetLang: 'nl',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'naming-places', label: 'Naming places', goal: 'Name 10 places in your city with correct article and a one-line description.' },
    { id: 'asking-where', label: 'Asking where', goal: 'Ask "Waar is...?" and parse the directional response.' },
    { id: 'locative-verbs', label: 'Staan / liggen / hangen', goal: 'Describe objects with the precise locative verb instead of generic "is".' },
    { id: 'directions', label: 'Giving directions', goal: 'Give 3-step walking directions in clear Dutch.' },
  ],
  relatedPools: ['topic-places', 'topic-city'],
  content: [
    createContentItem('lesdoelen', 'LES-doo-lə(n)', 'Today you learn to navigate a Dutch city in Dutch: name places, ask where things are, give directions, and describe a neighborhood. By the end, you can ask a stranger for the way and parse their answer.', 'word', 'Functies: plekken benoemen, vragen waar iets is, route uitleggen, buurt beschrijven.', 'Four micro-skills for everyday city life.', null, [ACT.orientation]),
    createContentItem('echte situatie', 'EKH-tə si-tu-AA-tsi', 'You stand on Spui square in central Amsterdam, lost. You stop a passerby with "Excuseer, mag ik u iets vragen?" and ask "Waar is de UvA-bibliotheek?". They answer in Dutch — and you need to follow.', 'word', 'Voorbijganger: "Ga rechtdoor, sla rechtsaf bij de gracht, dan zie je het."', 'A typical Amsterdam exchange — short, precise, fricative-heavy.', null, [ACT.orientation]),
    createContentItem('Amsterdam zelf', 'AAM-stər-dam zelf', 'Amsterdam has a unique radial canal-belt layout. The four big canals (Singel, Herengracht, Keizersgracht, Prinsengracht) form rings around the Centrum. Most addresses include a canal name; learning their order is the foundation of Amsterdam orientation.', 'word', 'Centrum → Singel → Herengracht → Keizersgracht → Prinsengracht → Jordaan/Plantage', 'A mnemonic: "Singel-Heren-Keizers-Prinsen" from inside out — known to every Amsterdammer.', null, [ACT.orientation]),

    createContentItem('gracht', 'KHRAKHT', 'A canal (common gender, plural: grachten). Two velar fricatives in 6 letters. The defining feature of Amsterdam streets — every major old street is along a canal.', 'word', 'Aan de Prinsengracht staat het Anne Frank Huis.', 'A famous example: the Anne Frank House on the Prinsengracht.', null, [ACT.pronunciation]),
    createContentItem('links / rechts', 'LINKS / REKHTS', 'Left /lɪŋks/ vs right /rɛxts/. Both short-vowel + consonant cluster. Easy to confuse for English speakers because "links" sounds like English "links". Drill the contrast.', 'word', 'Sla linksaf bij de brug, dan ga je rechts.', 'Combined directional sentence with both terms.', null, [ACT.pronunciation]),
    createContentItem('rechtdoor', 'rekht-DOR', 'Straight ahead /rɛxt.ˈdoːr/ — stress on the second syllable. Often used at the start of direction sentences.', 'word', 'Ga rechtdoor tot aan het plein.', '"Go straight until the square" — typical first instruction.', null, [ACT.pronunciation]),
    createContentItem('uitspraak: aa vs a', 'AA versus A', 'Compare maan (moon, long aa) vs man (man, short a). In location words: straat /straːt/ (street, long) vs stad /stɑt/ (city, short, final t devoiced).', 'word', 'In de straat van mijn stad woont mijn vriend.', 'Three vowel lengths in sequence; drill straat-stad contrast.', null, [ACT.pronunciation]),

    createContentItem('het huis', 'hət HŒYS', 'A house (neuter, plural: huizen — z voices in plural). The ui diphthong /œy/.', 'word', 'Mijn huis staat aan de gracht.', '"My house stands on the canal" — staan because building is vertical.', null, [ACT.vocabularyPlaces]),
    createContentItem('de school', 'də SKHOOL', 'A school (common, plural: scholen). Long oo, sch- cluster /sx/.', 'word', 'De school ligt naast het park.', '"The school lies next to the park" — liggen because building can be either; convention varies.', null, [ACT.vocabularyPlaces]),
    createContentItem('het café', 'hət ka-FEE', 'A café (neuter, French loan, plural: cafés). Note the accent. Dutch "café" includes traditional bruine kroegen (brown bars).', 'word', 'In het café drinken we koffie.', '"In the café we drink coffee" — V2 inversion after locative.', null, [ACT.vocabularyPlaces]),
    createContentItem('het station', 'hət sta-SHON', 'A train station (neuter, plural: stations). Stress on second syllable. The big four: Amsterdam Centraal, Rotterdam Centraal, Den Haag Centraal, Utrecht Centraal.', 'word', 'Het station staat in het centrum van de stad.', '"The station stands in the center of the city".', null, [ACT.vocabularyPlaces]),
    createContentItem('de bibliotheek', 'də bi-bli-yoo-TEEK', 'The library (common, plural: bibliotheken). Long word with multiple unstressed syllables. UvA has its own Universiteitsbibliotheek (UB).', 'word', 'De UB ligt aan het Singel.', 'UB = Universiteitsbibliotheek; on the Singel canal in Amsterdam.', null, [ACT.vocabularyPlaces]),
    createContentItem('de winkel', 'də VIN-kəl', 'A shop (common, plural: winkels). Plural with -s because ending in -el. Also: kledingwinkel (clothing shop), boekwinkel (bookshop).', 'word', 'Er is een winkel om de hoek.', '"There is a shop around the corner" — "om de hoek" = around the corner.', null, [ACT.vocabularyPlaces]),
    createContentItem('het park', 'hət PARK', 'A park (neuter, plural: parken). Vondelpark is the famous Amsterdam park.', 'word', 'In het Vondelpark fietsen we elke zondag.', '"In Vondelpark we cycle every Sunday".', null, [ACT.vocabularyPlaces]),
    createContentItem('de markt', 'də MARKT', 'A market (common, plural: markten). Famous: Albert Cuyp markt (Amsterdam), Markt in Brugge.', 'word', 'Op de markt kopen we kaas.', '"At the market we buy cheese" — op (not in/aan) for markets.', null, [ACT.vocabularyPlaces]),
    createContentItem('het plein', 'hət PLEIN', 'A square (neuter, plural: pleinen). Iconic: Dam square (de Dam), Spui, Leidseplein, Rembrandtplein.', 'word', 'Op het Leidseplein zitten veel cafés.', '"On Leidseplein sit many cafés" — op for squares.', null, [ACT.vocabularyPlaces]),
    createContentItem('de brug', 'də BRUKH', 'A bridge (common, plural: bruggen — consonant doubles). Amsterdam has 1500+ bridges; the Magere Brug (Skinny Bridge) is the famous one.', 'word', 'We lopen over de Magere Brug.', '"We walk over the Skinny Bridge" — "over" for crossing.', null, [ACT.vocabularyPlaces]),
    createContentItem('de gracht', 'də KHRAKHT', 'A canal (common, plural: grachten). The four Amsterdam canals form the UNESCO-protected Grachtengordel (Canal Belt).', 'word', 'De huizen aan de gracht zijn oud en mooi.', '"The houses on the canal are old and beautiful".', null, [ACT.vocabularyPlaces]),
    createContentItem('het centrum', 'hət SEN-trum', 'The center (of a city, neuter, plural: centra). Latin loan. Distinct from "centraal" (adjective, central) as in Amsterdam Centraal (station).', 'word', 'Ik woon in het centrum van Amsterdam.', '"I live in the center of Amsterdam".', null, [ACT.vocabularyPlaces]),
    createContentItem('de buurt', 'də BUURT', 'A neighborhood (common, plural: buurten). De Pijp, De Jordaan, De Plantage — famous Amsterdam buurten.', 'word', 'Mijn buurt heet De Pijp.', '"My neighborhood is called De Pijp" — note "heet" (is called).', null, [ACT.vocabularyPlaces]),
    createContentItem('de straat', 'də STRAAT', 'A street (common, plural: straten). Long aa, plural drops one a (open-syllable rule). Damrak is THE main street from Centraal to Dam.', 'word', 'Damrak is een drukke straat.', '"Damrak is a busy street" — "druk" = busy.', null, [ACT.vocabularyPlaces]),
    createContentItem('het stadhuis', 'hət STAT-hœys', 'A city hall (neuter, plural: stadhuizen). Compound: stad (city) + huis (house). The Amsterdam stadhuis is in the Stopera complex.', 'word', 'Het stadhuis staat op de Dam.', '"The city hall stands on the Dam".', null, [ACT.vocabularyPlaces]),
    createContentItem('het ziekenhuis', 'hət ZIE-kə(n)-hœys', 'A hospital (neuter, plural: ziekenhuizen). Compound: ziek (sick) + huis (house) — literally "sick-house". AMC and OLVG are major Amsterdam hospitals.', 'word', 'Ze werkt in het AMC, een groot ziekenhuis.', '"She works at the AMC, a big hospital".', null, [ACT.vocabularyPlaces]),
    createContentItem('Amsterdam / Rotterdam / Den Haag / Utrecht', 'cities', 'The four major Randstad cities. Amsterdam (capital, ~850k), Rotterdam (port city, ~660k), Den Haag (government seat, ~550k), Utrecht (central rail hub, ~360k). Each has distinct character.', 'word', 'Amsterdam is hoofdstad, maar Den Haag is de regeringszetel.', 'A core NL civics fact: Amsterdam is capital, Den Haag is government.', null, [ACT.vocabularyPlaces]),
    createContentItem('Antwerpen / Gent / Brussel', 'kheeren', 'Three major Flemish/Belgian cities. Antwerpen (largest Flemish, port + diamond), Gent (university city), Brussel (capital, French/Dutch bilingual). Useful for cross-border discussion.', 'word', 'Mijn vriend studeert in Gent, aan UGent.', 'UGent = Universiteit Gent, one of the top Flemish universities.', null, [ACT.vocabularyPlaces]),
    createContentItem('Eindhoven', 'EIND-hoh-və(n)', 'Tech capital of NL (~240k). Home of Philips and the High Tech Campus. Outside the Randstad; in the south (Brabant), so soft-g territory.', 'word', 'In Eindhoven werkt zij bij ASML.', 'ASML — world\'s leading chip-lithography company, based near Eindhoven.', null, [ACT.vocabularyPlaces]),

    createContentItem('in', 'IN', 'In (inside/enclosed). The default for enclosed spaces: in het huis, in de kamer, in de bibliotheek. Also: countries (in Nederland), enclosed regions (in Europa).', 'word', 'Ik ben in de keuken.', '"I am in the kitchen".', null, [ACT.vocabularyPrepositions]),
    createContentItem('op', 'OP', 'On top of, or on flat surfaces and certain spaces. "op de tafel" (on the table), "op het plein" (on the square), "op straat" (on the street). Also for islands: "op Vlieland" (on Vlieland — Frisian island).', 'word', 'Het boek ligt op de tafel.', 'Standard "on top of" usage; "liggen" because horizontal.', null, [ACT.vocabularyPrepositions]),
    createContentItem('aan', 'AAN', 'At, on the edge of. Used for things ON walls ("aan de muur"), AT institutions ("aan de UvA"), ON canals/rivers ("aan de gracht"), AT phones ("aan de telefoon").', 'word', 'Het schilderij hangt aan de muur.', '"The painting hangs on the wall" — aan for wall-mounted; hangen because hanging.', null, [ACT.vocabularyPrepositions]),
    createContentItem('naast', 'NAAST', 'Next to (lateral adjacency). Direct equivalent of English "next to". So "naast het station" = next to the station.', 'word', 'De bibliotheek staat naast het stadhuis.', '"The library stands next to the city hall".', null, [ACT.vocabularyPrepositions]),
    createContentItem('tegenover', 'tə-khə(n)-OO-vər', 'Opposite, across from. "tegenover het station" = across from the station. Stress on -ó-.', 'word', 'Mijn huis ligt tegenover het park.', '"My house lies opposite the park".', null, [ACT.vocabularyPrepositions]),
    createContentItem('achter', 'AKH-tər', 'Behind. So "achter het huis" = behind the house. Note the velar fricative /x/.', 'word', 'De fiets staat achter de schuur.', '"The bicycle stands behind the shed" — "schuur" = shed/garage.', null, [ACT.vocabularyPrepositions]),
    createContentItem('voor', 'VOR', 'In front of (location); also "before" (time). So "voor het huis" = in front of the house. Two-way meaning; context disambiguates.', 'word', 'Mijn auto staat voor de deur.', '"My car stands in front of the door".', null, [ACT.vocabularyPrepositions]),
    createContentItem('onder', 'ON-dər', 'Under, beneath. So "onder de brug" = under the bridge. Same as English "under".', 'word', 'De fiets ligt onder de brug.', '"The bicycle lies under the bridge".', null, [ACT.vocabularyPrepositions]),
    createContentItem('boven', 'BOO-və(n)', 'Above, over. So "boven de stad" = above the city (e.g., a plane). Also figurative: "boven verwachting" = beyond expectation.', 'word', 'Boven de gracht hangt een grijze lucht.', '"Above the canal hangs a grey sky" — typical Dutch winter description.', null, [ACT.vocabularyPrepositions]),
    createContentItem('tussen', 'TUS-sə(n)', 'Between (two or more things). So "tussen het café en het station" = between the café and the station.', 'word', 'De boekwinkel ligt tussen twee cafés.', '"The bookshop lies between two cafés".', null, [ACT.vocabularyPrepositions]),
    createContentItem('naar', 'NAAR', 'To, toward (directional). Distinct from "in/op/aan" which are static. So "naar Amsterdam" = to Amsterdam, "naar school" = to school. Used with movement verbs (gaan, lopen, fietsen, rijden).', 'word', 'Ik ga naar de UvA.', '"I am going to the UvA" — directional with gaan.', null, [ACT.vocabularyPrepositions]),
    createContentItem('langs', 'LANGS', 'Along (passing). So "langs de gracht" = along the canal. Used with movement verbs to describe a path.', 'word', 'We lopen langs de gracht.', '"We walk along the canal".', null, [ACT.vocabularyPrepositions]),
    createContentItem('over', 'OO-vər', 'Over, across (also: about, regarding). So "over de brug" = across the bridge. Two-way meaning depends on context.', 'word', 'Loop over de brug en je bent er.', '"Walk over the bridge and you are there".', null, [ACT.vocabularyPrepositions]),
    createContentItem('door', 'DOR', 'Through. So "door het park" = through the park. Also: "door de week" = during the week (idiomatic).', 'word', 'Fiets door het Vondelpark.', '"Cycle through Vondelpark".', null, [ACT.vocabularyPrepositions]),
    createContentItem('tot', 'TOT', 'Until, up to. So "tot de brug" = until the bridge. Also temporal: "tot morgen" = until tomorrow.', 'word', 'Ga rechtdoor tot het plein.', '"Go straight until the square".', null, [ACT.vocabularyPrepositions]),

    createContentItem(
      'waar is...?',
      'vaar IS',
      'The standard static location question. Wh-word "waar" (where) + verb (is/zijn/staat/ligt/hangt) + subject. V2 word order: wh-word first, verb second.',
      'sentence',
      'Waar is de UvA-bibliotheek?\nWaar ligt het Anne Frank Huis?\nWaar staat het station?',
      'Note the variation: "is" is generic; "ligt/staat/hangt" specifies the object\'s positioning.',
      [
        { target: 'waar + is (generic)', note: 'works for any location query; flat but acceptable' },
        { target: 'waar + ligt/staat/hangt', note: 'precise locative verbs; preferred Dutch style' },
      ],
      [ACT.grammarWaar],
    ),
    createContentItem(
      'hoe kom ik bij...?',
      'hu kom ik bei',
      'The standard directional question — "how do I get to...?". Uses "bij" (at/by) + place. Alternative: "Hoe kom ik bij de UvA?" or "Wat is de weg naar...?".',
      'sentence',
      'Hoe kom ik bij de UvA-bibliotheek?\nHoe kom ik bij het station?\nWat is de weg naar Vondelpark?',
      'A core tourist question. Note the "bij" preposition specific to this question pattern.',
      [
        { target: 'Hoe kom ik bij...', note: 'most casual; works everywhere' },
        { target: 'Wat is de weg naar...', note: 'slightly more formal/literary' },
        { target: 'Excuseer, mag ik u iets vragen?', note: 'polite preamble before asking a stranger; signals foreign visitor or polite local' },
      ],
      [ACT.grammarWaar],
    ),
    createContentItem(
      'answers',
      'ANT-vor-də(n)',
      'Three standard answer patterns. (1) Static: "De UB ligt aan het Singel." (2) Directional 2-step: "Ga rechtdoor, dan zie je het." (3) Directional 3-step: "Ga rechtdoor tot de brug, sla linksaf, en het ligt aan je rechterhand."',
      'sentence',
      'STATIC: De UB ligt aan het Singel.\n2-STEP: Ga rechtdoor, dan zie je het.\n3-STEP: Ga rechtdoor tot de brug, sla linksaf, en het ligt aan je rechterhand.',
      'Three patterns: pick based on how clear the destination is from the asker\'s position.',
      null,
      [ACT.grammarWaar],
    ),

    createContentItem(
      'staan / liggen / hangen',
      'staan / liggen / hangen',
      'The three locative verbs that distinguish Dutch positional precision from English "to be". STAAN: vertical/upright (een glas staat op de tafel — a glass stands on the table). LIGGEN: horizontal/flat (een boek ligt op de tafel — a book lies on the table). HANGEN: suspended (een schilderij hangt aan de muur — a painting hangs on the wall).',
      'sentence',
      'Het glas STAAT op de tafel. (vertical)\nHet boek LIGT op de tafel. (horizontal)\nHet schilderij HANGT aan de muur. (suspended)',
      'A characteristic Dutch precision: "het glas is op de tafel" sounds flat and slightly foreign; native speakers use the locative verb.',
      [
        { target: 'staan — vertical objects', note: 'buildings, people, bottles, lamps, trees, cars (parked)' },
        { target: 'liggen — horizontal objects', note: 'books, papers, food, cities (geographically), pets resting' },
        { target: 'hangen — suspended objects', note: 'paintings, coats, lights, fog (figurative), reputations' },
      ],
      [ACT.grammarStaanLiggen],
    ),
    createContentItem(
      'cities lie',
      'steden liggen',
      'A characteristic Dutch usage: cities, countries, and places "liggen" (lie). "Amsterdam ligt in Noord-Holland" (Amsterdam lies in North Holland). NOT "Amsterdam is in Noord-Holland" — that would sound foreign.',
      'sentence',
      'Amsterdam ligt in Noord-Holland.\nNederland ligt in Europa.\nDe UvA ligt in het centrum.',
      'Geographic location uses liggen; the convention is fixed.',
      null,
      [ACT.grammarStaanLiggen],
    ),
    createContentItem(
      'people too — staan or zitten',
      'mensen ook',
      'People also use locative verbs. Standing: "Hij staat bij het raam" (he stands at the window). Sitting: "Zij zit op de stoel" (she sits on the chair). Lying: "Het kind ligt in bed" (the child lies in bed). Generic "is" sounds incomplete.',
      'sentence',
      'Hij staat bij het raam. (standing)\nZij zit op de stoel. (sitting)\nHet kind ligt in bed. (lying)',
      'Verbal precision extends to people: choose the verb that matches the body posture.',
      [
        { target: 'staan — standing person', note: 'a person standing, waiting, in line' },
        { target: 'zitten — sitting person', note: 'a person sitting at table, on a chair, in a meeting' },
        { target: 'liggen — lying person', note: 'a person in bed, sunbathing, sick' },
      ],
      [ACT.grammarStaanLiggen],
    ),

    createContentItem(
      'directional verbs',
      'richtingswerkwoorden',
      'The four high-frequency directional verbs: gaan (to go, generic), lopen (to walk), fietsen (to cycle), rijden (to drive/ride). Each takes "naar" for destination. Dutch favors specific over generic: "Ik fiets naar UvA" is better than "Ik ga naar UvA" when biking.',
      'sentence',
      'Ik ga naar het station. (generic)\nIk loop naar het station. (walking)\nIk fiets naar het station. (cycling — most common in Amsterdam)\nIk rij naar het station. (driving — by car)',
      'Most Amsterdammers default to "fietsen" — bikes outnumber people in Amsterdam.',
      [
        { target: 'gaan (generic) — go', note: 'when transport mode is unspecified or irrelevant' },
        { target: 'lopen (walk)', note: 'on foot; for short distances or in city center' },
        { target: 'fietsen (cycle)', note: 'most common in NL cities; the cultural default' },
        { target: 'rijden (drive)', note: 'by car, motorcycle, or as a passenger; less common in centers' },
      ],
      [ACT.grammarDirections],
    ),
    createContentItem(
      'imperative directions',
      'gebiedende wijs',
      'Use imperatives for giving directions. Form by dropping -en from infinitive: gaan → ga! lopen → loop! fietsen → fiets! sla! (slaan, to turn). Polite directions can add "alstublieft" (please) or use "u" form: "Gaat u rechtdoor".',
      'sentence',
      'Ga rechtdoor. (Go straight.)\nSla linksaf. (Turn left.)\nLoop over de brug. (Walk across the bridge.)\nFiets door het park. (Cycle through the park.)',
      'Direct imperatives are normal in Dutch direction-giving; not rude.',
      [
        { target: 'ga (gaan → go)', note: 'most generic directional command' },
        { target: 'sla (slaan → strike/turn)', note: 'used in "slaan linksaf/rechtsaf" = turn left/right' },
        { target: 'loop (lopen → walk)', note: 'walking direction' },
        { target: 'fiets (fietsen → cycle)', note: 'cycling direction' },
      ],
      [ACT.grammarDirections],
    ),
    createContentItem(
      'linksaf / rechtsaf',
      'links-AF / rekhts-AF',
      'The directional adverbs for turning. "linksaf slaan" = turn left; "rechtsaf slaan" = turn right. The "-af" suffix marks "off the current direction". Common pattern: imperative "Sla" + linksaf/rechtsaf + "bij" + landmark.',
      'sentence',
      'Sla linksaf bij de gracht.\nSla rechtsaf na de brug.\nGa de tweede straat rechtsaf.',
      '"Bij" means at; "na" means after. Mix them up and you turn one street too early/late.',
      [
        { target: 'linksaf slaan', note: 'turn left' },
        { target: 'rechtsaf slaan', note: 'turn right' },
        { target: 'bij + landmark', note: 'at the landmark — turn HERE' },
        { target: 'na + landmark', note: 'after the landmark — turn AFTER' },
      ],
      [ACT.grammarDirections],
    ),

    createContentItem(
      'mijn buurt',
      'mein BUURT',
      'A description of an Amsterdam neighborhood using location vocabulary and locative verbs.',
      'sentence',
      'Ik woon in De Pijp, een gezellige buurt in Amsterdam-Zuid. Mijn huis staat aan de Albert Cuypstraat, vlak bij de markt. Naast mijn huis ligt een klein café waar ik elke ochtend koffie drink. Tegenover ons huis hangt een grote Nederlandse vlag aan een gevel. Aan het eind van de straat zie je het Sarphatipark. Het is een levendige buurt: er zijn winkels, restaurants, en veel fietsers.',
      'Translation: "I live in De Pijp, a cozy neighborhood in Amsterdam-South. My house stands on Albert Cuypstraat, right next to the market. Next to my house lies a small café where I drink coffee every morning. Opposite our house hangs a big Dutch flag on a facade. At the end of the street you see Sarphatipark. It is a lively neighborhood: there are shops, restaurants, and many cyclists."',
      [
        { target: 'De Pijp', note: 'a popular Amsterdam-Zuid neighborhood; the name means "the pipe"' },
        { target: 'Albert Cuypstraat', note: 'famous street with the largest street market in NL' },
        { target: 'vlak bij', note: '"right next to" — "vlak" intensifies proximity' },
        { target: 'staan / ligt / hangt', note: 'all three locative verbs in one paragraph; Dutch precision in action' },
        { target: 'levendige buurt', note: '"lively neighborhood"; -e ending on "levendig" because preceded by article' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'begripsvragen',
      'bə-KHRIPS-vraa-khə(n)',
      'Four comprehension questions about the paragraph.',
      'sentence',
      'V1: In welke buurt woont de spreker? V2: Wat ligt naast het huis? V3: Wat hangt tegenover het huis? V4: Wat is er in De Pijp?',
      'Mix of which, what, and existential questions.',
      [
        { target: 'A1: In De Pijp.', note: 'short prepositional answer' },
        { target: 'A2: Een klein café.', note: 'noun phrase answer using locative liggen' },
        { target: 'A3: Een grote Nederlandse vlag.', note: 'noun phrase with two adjectives' },
        { target: 'A4: Winkels, restaurants, en veel fietsers.', note: 'list answer from the existential sentence' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'op het Spui — vraag aan voorbijganger',
      'op hət SPŒY',
      'A 6-turn directions exchange between a tourist and a local on Spui square. Covers the polite asking pattern, the answer with two directional steps, and a friendly close.',
      'conversation',
      'Toerist: Excuseer, mag ik u iets vragen?\nVoorbijganger: Ja hoor, wat is er?\nToerist: Hoe kom ik bij de UvA-bibliotheek?\nVoorbijganger: Ga eerst rechtdoor over het Spui. Bij de gracht slaat u rechtsaf.\nToerist: Rechtdoor en dan rechtsaf bij de gracht?\nVoorbijganger: Precies. Het is een groot gebouw aan je linkerhand, je kunt het niet missen.\nToerist: Heel erg bedankt!\nVoorbijganger: Geen dank, succes!',
      'Note the polite preamble "Mag ik u iets vragen?" and the helpful confirming repetition by the tourist.',
      [
        { target: 'Excuseer, mag ik u iets vragen?', note: 'polite preamble for strangers; signals respect' },
        { target: 'Ja hoor', note: '"Yes sure"; "hoor" is the friendly particle softening the response' },
        { target: 'Bij de gracht slaat u rechtsaf', note: 'V2 inversion with locative phrase first; "slaat u" formal' },
        { target: 'je kunt het niet missen', note: '"you cannot miss it" — common Dutch direction-giving closer' },
        { target: 'Geen dank', note: '"Don\'t mention it" / "you\'re welcome" — standard response to bedankt' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'tussen vrienden — naar het café',
      'tʏs-sə(n) VREE-ndə(n)',
      'A casual peer exchange — two friends arranging to meet at a café in the Jordaan.',
      'conversation',
      'Sara: Hé Pieter, waar ligt dat café waar je het over had?\nPieter: Het ligt in de Jordaan, aan de Prinsengracht.\nSara: Hoe kom ik daar?\nPieter: Fiets vanaf de UvA langs de gracht, sla bij de derde brug rechtsaf, en het café staat op de hoek.\nSara: Top, tot zo!\nPieter: Tot zo!',
      'Casual register throughout; "tot zo" = "see you in a bit".',
      [
        { target: 'Hé', note: 'casual attention-getter; warmer than "hey" in English' },
        { target: 'waar je het over had', note: '"that you talked about"; relative clause with split preposition' },
        { target: 'de Jordaan', note: 'famous canal-belt neighborhood west of Centrum' },
        { target: 'op de hoek', note: '"on the corner" — fixed location phrase' },
        { target: 'Top', note: 'casual "great!"; very common in NL urban speech' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'mijn buurt template',
      'TEM-plaat',
      'A reusable template for describing your neighborhood. Fill in brackets with your own data.',
      'sentence',
      'Ik woon in [buurt] in [stad]. Mijn huis staat aan de [straat]. Naast mijn huis ligt [iets]. Tegenover is [iets anders]. Aan het eind van de straat zie je [landmark]. Het is een [bijvoeglijk naamwoord] buurt.',
      'Six sentences covering location, neighbors, and atmosphere.',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'schrijfoefening',
      'SKHREIF-oo-fə-ning',
      'Write your own 4-5 sentence neighborhood description using at least one staan, one liggen, and one hangen.',
      'sentence',
      'Voorbeeld: Ik woon in Oost in Amsterdam. Mijn huis staat aan de Eerste van Swindenstraat. Naast mijn huis ligt een Turkse supermarkt. Tegenover hangt een Marokkaans theehuis-bord. Aan het eind van de straat zie je het Oosterpark. Het is een diverse en levendige buurt.',
      'Translation: "I live in East in Amsterdam. My house stands on Eerste van Swindenstraat. Next to my house lies a Turkish supermarket. Opposite hangs a Moroccan tea-house sign. At the end of the street you see Oosterpark. It is a diverse and lively neighborhood."',
      null,
      [ACT.writing],
    ),

    createContentItem(
      'Amsterdamse grachten',
      'AAM-stər-dam-sə KHRAKHTƏN',
      'The Amsterdam canal belt (Grachtengordel) was built in the 17th-century Golden Age. The four main canals — Singel (innermost), Herengracht, Keizersgracht, Prinsengracht (outermost) — form concentric semicircles around the Centrum. UNESCO World Heritage since 2010. Every Amsterdammer can recite them in order.',
      'sentence',
      'Singel → Herengracht → Keizersgracht → Prinsengracht (van binnen naar buiten)',
      'A mnemonic: "Singel, Herengracht, Keizersgracht, Prinsengracht" = "Single, Gentleman, Emperor, Prince" — the social hierarchy of Golden Age Amsterdam.',
      [
        { target: 'Singel', note: 'innermost canal; "single" because it was once the city moat' },
        { target: 'Herengracht', note: '"Gentleman canal"; the most prestigious 17th-century address' },
        { target: 'Keizersgracht', note: '"Emperor canal"; named for Maximilian I' },
        { target: 'Prinsengracht', note: '"Prince canal"; outermost; the Anne Frank House is here' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'fietsen-cultuur',
      'FEET-sə(n)-kul-tuur',
      'Cycling is the defining Amsterdam (and Dutch) urban transport. Amsterdam has more bikes than people (~880k bikes for ~850k inhabitants). Bike lanes (fietspaden) are everywhere; bike traffic has its own rules. Saying "ik fiets naar..." is more common than "ik ga naar..." for any short-distance trip in NL cities.',
      'sentence',
      'Ik fiets elke dag naar de UvA. Het kost vijftien minuten.',
      '"I cycle to UvA every day. It takes fifteen minutes." — a typical Amsterdam student\'s commute.',
      [
        { target: 'fietsstad', note: '"bike city"; Amsterdam, Utrecht, Groningen, Eindhoven all qualify' },
        { target: 'fietspad', note: 'dedicated bike path; mandatory if present (you cannot cycle on the road if there is a fietspad)' },
        { target: 'fietsenstalling', note: 'bicycle parking; major train stations have huge multi-story ones' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'vier Randstad-steden',
      'vier RANT-stat-stee-də(n)',
      'The Randstad ("ring city") is the heavily urbanized core of NL: Amsterdam, Rotterdam, Den Haag, Utrecht. Together ~8 million people. Each has a distinct identity: Amsterdam (culture, finance), Rotterdam (port, modern), Den Haag (government, international courts), Utrecht (transport hub, university).',
      'sentence',
      'Amsterdam: hoofdstad, financien, cultuur.\nRotterdam: haven, moderne architectuur.\nDen Haag: regering, internationale rechtbanken.\nUtrecht: spoorwegknooppunt, oudste universiteit.',
      'A NL civics fact every learner should know — these four cities sit within 80km of each other.',
      [
        { target: 'Amsterdam (hoofdstad)', note: 'capital (formal); culture and finance; biggest city' },
        { target: 'Rotterdam', note: 'rebuilt after WW2; Europe\'s largest port; ultra-modern' },
        { target: 'Den Haag', note: 'seat of government, parliament, royal residence; international city' },
        { target: 'Utrecht', note: 'most central; major rail hub; medieval city center' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'Vlaanderen vs Nederland',
      'VLAAN-də-rə(n) versus NEE-dər-lant',
      'Geographic Dutch-speaking world: NL (the Netherlands, ~17.5 million) and Flanders (Vlaanderen, the northern half of Belgium, ~6.5 million). Major Flemish cities: Antwerpen, Gent, Brussel (officially bilingual), Leuven, Brugge. KU Leuven is the oldest Flemish university (1425). Brussel hosts the EU headquarters.',
      'sentence',
      'NL: Amsterdam, Rotterdam, Den Haag, Utrecht, Eindhoven\nBE (Vlaanderen): Antwerpen, Gent, Brussel, Leuven, Brugge',
      'Cross-border cultural fact: many Dutch speakers consume Flemish media (and vice versa) — same language, different cultures.',
      [
        { target: 'Antwerpen', note: 'largest Flemish city; port, diamonds, fashion (Antwerp Six)' },
        { target: 'Gent', note: 'Universiteit Gent; medieval canals; second-largest Flemish city' },
        { target: 'Brussel', note: 'officially bilingual; ~75% French in daily speech; capital of BE and EU' },
        { target: 'Leuven', note: 'university town; KU Leuven from 1425; Stella Artois brewery' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'opdracht: vraag naar de weg',
      'OP-drakht: vraag naar de veh',
      'Roleplay asking a passerby on Spui in Amsterdam for directions to the UvA Library. Use the polite opener, the question, parse the answer, confirm, and close.',
      'conversation',
      '[Spui plein, Amsterdam, 14:00]\nJij: [begin met polite opener]\nVoorbijganger: Ja, wat kan ik voor u doen?\nJij: [vraag naar de UvA-bibliotheek]\nVoorbijganger: Ga rechtdoor over het Spui, bij de Singel slaat u rechtsaf.\nJij: [herhaal om te bevestigen]\nVoorbijganger: Klopt. Het is een groot gebouw, je kunt het niet missen.\nJij: [bedank en sluit af]',
      'Six turns; the AI tutor plays the passerby.',
      [
        { target: 'polite opener', note: 'Excuseer / Pardon / Mag ik u iets vragen?' },
        { target: 'vraag', note: 'Hoe kom ik bij...? / Waar is...?' },
        { target: 'herhaal om te bevestigen', note: 'Echo back the key step: "Rechtdoor en dan rechtsaf bij de Singel?"' },
        { target: 'bedank en sluit af', note: 'Heel erg bedankt! / Dank u wel! / Fijne dag nog' },
      ],
      [ACT.task],
    ),
    createContentItem(
      'uitdaging — verloren in de Jordaan',
      'œyt-DAA-khing',
      'Stretch goal: you got lost in the Jordaan looking for the Anne Frank House. The passerby gives a longer 3-step direction; parse it and confirm.',
      'conversation',
      'Jij: Excuseer, weet u waar het Anne Frank Huis is?\nVoorbijganger: Ja, dat ligt aan de Prinsengracht. Ga eerst rechtdoor tot de eerste brug. Sla daar linksaf. Loop dan langs de gracht tot je een lange rij ziet — dat is het.\nJij: Dus eerst rechtdoor, eerste brug linksaf, dan langs de gracht tot ik de rij zie?\nVoorbijganger: Precies. Veel succes!\nJij: Dank u wel!',
      'Three direction steps + confirming echo. "Lange rij" (long queue) is the in-joke about the Anne Frank House — always a queue.',
      [
        { target: 'tot de eerste brug', note: '"until the first bridge" — using "tot" for endpoint' },
        { target: 'lange rij', note: '"long queue"; the Anne Frank House is always busy — the queue itself is the landmark' },
        { target: 'Veel succes', note: '"good luck"; standard close after a direction giving' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
