// Level 1 Unit 2 — In the Classroom (Dutch)
// Functions: classroom objects, classroom commands, asking questions in class,
// describing your study materials, naming a list of things (er-construction).

const createContentItem = (
  target,
  romanization,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization,
  nativeText: note,
  pronunciation: romanization,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'nl-l1u2-orientation',
  pronunciation: 'nl-l1u2-pronunciation',
  vocabularyObjects: 'nl-l1u2-vocab-objects',
  vocabularyVerbs: 'nl-l1u2-vocab-verbs',
  grammarDeHet: 'nl-l1u2-grammar-de-het',
  grammarPlurals: 'nl-l1u2-grammar-plurals',
  grammarErExistential: 'nl-l1u2-grammar-er-existential',
  reading: 'nl-l1u2-reading',
  listening: 'nl-l1u2-listening',
  writing: 'nl-l1u2-writing',
  culture: 'nl-l1u2-culture',
  task: 'nl-l1u2-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Name 20+ classroom objects (boek, pen, tafel, stoel, bord, krijt) with the correct gender (de/het) so you can introduce them with the right article.',
      'Use four classroom command verbs (luister, schrijf, lees, herhaal) and four polite request forms (mag ik..., kunt u..., kan ik...).',
      'Ask questions in class with proper Dutch politeness: "Mag ik een vraag stellen?", "Hoe spel je dat?", "Wat betekent...?"',
      'Use the existential "er is" / "er zijn" construction to list what is in a classroom.',
    ],
    task: 'Picture your first morning lecture at UvA — the docent walks in, gives instructions, and you need to follow them while asking one clarifying question.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in classroom Dutch',
    goals: [
      'Pronounce "boek" /buk/ (book) vs "buk" /bʏk/ (bend down imperative) — the oe vs short u contrast trips up many learners.',
      'Pronounce "schrijven" /ˈsxrɛivə(n)/ (to write) — opening sch cluster /sx/ followed by long ij; one of the longest consonant clusters in beginner Dutch.',
      'Recognize the unstressed "er" /ər/ that opens existential sentences: "Er is een bord" /ər ɪs ə(n) bɔrt/.',
    ],
    task: 'Read each example aloud paying special attention to the oe vs short-u contrast and the sch- cluster.',
  },
  {
    id: ACT.vocabularyObjects,
    section: 'Vocabulary I',
    title: 'Classroom objects',
    goals: [
      'Memorize 20+ classroom-object nouns with their correct articles (de boek? het boek!).',
      'Distinguish "de"-words from "het"-words by intuition — about 75% of nouns are "de", about 25% are "het". Diminutives and most abstract concepts are "het".',
    ],
    task: 'Say each object with its correct article three times until "het boek" and "de pen" sound automatic.',
  },
  {
    id: ACT.vocabularyVerbs,
    section: 'Vocabulary II',
    title: 'Classroom verbs and commands',
    goals: [
      'Use four imperative forms: luister! (listen!), schrijf! (write!), lees! (read!), herhaal! (repeat!) — all formed by dropping the -en from the infinitive.',
      'Use polite request forms: "Mag ik..." (May I...), "Kunt u..." (Could you...formal), "Kan ik..." (Can I...).',
    ],
    task: 'Give three commands and three polite requests using the verbs above.',
  },
  {
    id: ACT.grammarDeHet,
    section: 'Grammar I',
    title: 'de / het — common vs neuter gender',
    goals: [
      'Recognize that Dutch has TWO genders: "common" (de, ~75% of nouns) and "neuter" (het, ~25%). The historical masculine/feminine merged into "common" centuries ago.',
      'Learn the high-confidence het-word categories: diminutives (-je, -tje, -pje, -kje), languages (het Nederlands), metals (het goud, het zilver, het ijzer), most words for substances and abstract concepts.',
      'Accept that for many nouns, gender MUST be memorized with the word — "de tafel" but "het bord" has no rule reason. Native children take years to fully master this.',
    ],
    task: 'Sort 12 classroom nouns into de- vs het-piles, then say each with its article.',
  },
  {
    id: ACT.grammarPlurals,
    section: 'Grammar II',
    title: 'Plurals — -en, -s, and irregulars',
    goals: [
      'Use the -en plural (most common): boek → boeken, pen → pennen, tafel → tafels (-s), stoel → stoelen.',
      'Use the -s plural for nouns ending in unstressed -e, -el, -em, -en, -er, -aar, -ie + most loanwords: tafel → tafels, computer → computers, koffie → koffies.',
      'Recognize the small set of irregular plurals: kind → kinderen (child → children), man → mannen (with consonant doubling), stad → steden (vowel change).',
      'Apply the open-syllable spelling rule: boek → boeken (no doubling needed, root vowel oe), maar man → mannen (consonant doubles to keep short a).',
    ],
    task: 'Pluralize 10 nouns from this lesson and check that each plural form spells the vowel length correctly.',
  },
  {
    id: ACT.grammarErExistential,
    section: 'Grammar III',
    title: '"Er is" / "Er zijn" — the existential construction',
    goals: [
      'Use "Er is + singular noun" or "Er zijn + plural noun" to express existence — the Dutch equivalent of English "there is/are". So "Er is een bord" (There is a board), "Er zijn drie ramen" (There are three windows).',
      'Place "er" in first position; the verb stays in second position (V2): "Er is een bord", "In het lokaal zijn drie ramen".',
      'Use "er" in questions: "Is er een toilet?", "Zijn er pennen?" — invert er-verb-subject.',
    ],
    task: 'Describe three things in your classroom using er is / er zijn, then ask one question with "Is er...?".',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Reading a classroom description',
    goals: [
      'Read a short classroom-description paragraph aloud with correct articles and plural forms.',
      'Answer comprehension questions about what is in the room and where it is located.',
    ],
    task: 'Read the paragraph aloud, then answer the four comprehension questions in complete short sentences.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'A classroom interaction',
    goals: [
      'Follow a 6-turn classroom exchange between a docent and a student with classroom commands and questions.',
      'Reproduce the dialogue swapping in different objects and verbs.',
    ],
    task: 'Read the dialogue with the AI tutor first, then perform it again with new content.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Describe your classroom',
    goals: [
      'Write 4-5 sentences describing your classroom or study space using er-constructions and correct articles.',
    ],
    task: 'Write the description and read it aloud.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'Dutch classroom norms',
    goals: [
      'Recognize Dutch classroom norms: questions welcomed, debate expected, first-name address by week two, no-formality dress code at universities.',
      'Understand the "huiswerk" (homework) culture — much less than East Asian systems, more independent reading expected.',
    ],
    task: 'Identify one classroom norm difference between Dutch and your own school culture.',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'First lecture at UvA',
    goals: [
      'Combine the classroom vocabulary, commands, and questions into one continuous scene.',
    ],
    task: 'Roleplay a first morning lecture at UvA with the AI tutor as the docent.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 2: In het Klaslokaal — Classroom & Materials',
  category: 'classroom',
  difficulty: 'beginner',
  targetLang: 'nl',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'naming-objects', label: 'Naming classroom objects', goal: 'Point at 10 classroom objects and name each with the correct article.' },
    { id: 'classroom-commands', label: 'Following commands', goal: 'Respond appropriately to imperative-form classroom commands.' },
    { id: 'asking-questions', label: 'Asking in class', goal: 'Politely ask "Mag ik een vraag stellen?" and three follow-up clarifying questions.' },
    { id: 'er-existential', label: 'Listing what is there', goal: 'Use er is / er zijn to describe the contents of a room.' },
  ],
  relatedPools: ['topic-education', 'topic-objects'],
  content: [
    createContentItem('lesdoelen', 'LES-doo-lə(n)', 'Today you learn to function inside a Dutch classroom: name objects, follow commands, ask polite questions, and describe a room. By the end, you can survive a 90-minute UvA lecture without staring blankly at a wall.', 'word', 'In het klaslokaal: spreken, luisteren, vragen stellen, en notities maken.', 'These four classroom micro-skills come up every single day of study.', null, [ACT.orientation]),
    createContentItem('echte situatie', 'EKH-tə si-tu-AA-tsi', 'It is Monday 9am at the UvA. Your docent walks in carrying a stack of papers, says "Goedemorgen, doe je boeken open op pagina 12", and you need to know what "doe open" means, where pagina 12 is, and whether you can ask "kunt u dat herhalen?" without sounding rude.', 'word', 'Docent: "Doe je boeken open op pagina 12. Vandaag praten we over Nederlandse grammatica."', 'A typical Dutch classroom opener combining an imperative (doe...open) with a content preview.', null, [ACT.orientation]),
    createContentItem('register: docent en student', 'rə-XHIS-tər', 'At a Dutch university, the docent uses "jullie" (you-plural) for the class and "je" for individuals after first contact. Students initially use "u" with new docents but can switch to "je" by mid-semester. The casual register is the default; formal "u" persists in customer-service settings (study advisor offices).', 'word', 'Docent (week 1): "Welkom in de cursus. Hoe heet u?" → Docent (week 3): "Hoi Sara, heb je de tekst gelezen?"', 'Note the register shift after acquaintance — typical of NL university culture.', null, [ACT.orientation]),

    createContentItem('boek vs buk', 'BUUK versus BUK', 'A classic Dutch beginner pair: boek /buk/ (book) uses the long oe vowel, while buk /bʏk/ (bend down — imperative of bukken) uses the short u. Both occur in classroom Dutch and confusing them sends the wrong signal.', 'word', 'Doe je boek open. (Open your book.)  vs  Buk! (Duck!)', 'Two real classroom utterances; vowel-length confusion changes the meaning entirely.', [{ target: 'boek /buk/', note: 'long oe, "book"' }, { target: 'buk /bʏk/', note: 'short u, "bend!" imperative' }], [ACT.pronunciation]),
    createContentItem('schrijven', 'SKHREI-və(n)', 'The verb "schrijven" /ˈsxrɛivə(n)/ — opening sch /sx/ cluster, long ij /ɛi/, voiced v that devoices to f when stem-final (schrijven → schrijf). Three sounds beginners struggle with packed into one verb.', 'word', 'Schrijven → ik schrijf, jij schrijft, wij schrijven.', 'A high-frequency irregular: stem schrijf has v→f spelling change.', null, [ACT.pronunciation]),
    createContentItem('er is een...', 'ər IS ən', 'The existential phrase "er is een" /ər ɪs ən/ has THREE unstressed syllables in a row — schwa, short, schwa. Native rhythm: rapid, almost contracted to "rzən". Foreign learners pronounce each syllable equally and sound slow.', 'word', 'Er is een bord. (There is a board.)', 'Natural fast speech: /ərɪsənbɔrt/ — almost one prosodic unit.', null, [ACT.pronunciation]),
    createContentItem('herhalen', 'hər-HAA-lə(n)', 'The verb "herhalen" (to repeat) — stress on the SECOND syllable, not the first. Many Germanic-language learners default to first-syllable stress and produce HER-halen which sounds wrong.', 'word', 'Kunt u dat herhalen, alstublieft?', 'Standard polite "could you repeat that, please?" — note "alstublieft" = "please".', null, [ACT.pronunciation]),

    createContentItem('het boek', 'hət BUK', 'A book (neuter gender — note "het", not "de"). Plural: boeken. A core classroom object. The diminutive "boekje" /ˈbukjə/ means "booklet" and is also neuter (all diminutives are het-words).', 'word', 'Ik heb mijn boek bij me.', 'Standard classroom phrase: "I have my book with me."', null, [ACT.vocabularyObjects]),
    createContentItem('de pen', 'də PEN', 'A pen (common gender). Plural: pennen (consonant doubles to keep short e). Distinguish from "potlood" /ˈpɔtloːt/ (pencil) which is het-word.', 'word', 'Mag ik je pen lenen?', '"May I borrow your pen?" — "lenen" = to borrow/lend.', null, [ACT.vocabularyObjects]),
    createContentItem('het potlood', 'hət POT-loot', 'A pencil (neuter gender — note "het", not "de"). Plural: potloden (final d returns when vowel follows). Common in art and math classrooms.', 'word', 'Het potlood is scherp.', '"The pencil is sharp" — "scherp" /sxɛrp/ = sharp.', null, [ACT.vocabularyObjects]),
    createContentItem('de tafel', 'də TAA-fəl', 'A table or desk (common gender). Plural: tafels (-s plural because ends in -el). The most common classroom seating arrangement is desks in rows or U-shape.', 'word', 'Op de tafel ligt een boek.', '"On the table lies a book" — "ligt" from "liggen" (to lie, position).', null, [ACT.vocabularyObjects]),
    createContentItem('de stoel', 'də STUL', 'A chair (common gender). Plural: stoelen. Note the oe vowel /u/. Distinct from "fauteuil" /foːˈtœj/ (armchair, French loan).', 'word', 'Ga zitten op je stoel.', '"Sit down on your chair" — imperative ga + zitten (infinitive).', null, [ACT.vocabularyObjects]),
    createContentItem('het bord', 'hət BORT', 'A blackboard / whiteboard / board (neuter). Plural: borden. Final d devoices to t. Also "schoolbord" (school board) for the specific classroom version. In modern UvA lecture halls, "het scherm" (the screen) is more common than physical chalkboards.', 'word', 'De docent schrijft op het bord.', '"The teacher writes on the board" — standard classroom action.', null, [ACT.vocabularyObjects]),
    createContentItem('het krijt', 'hət KREIT', 'Chalk (neuter, mass noun). No common plural; uncountable. Pronounced /krɛit/ — k + r + long ij + t. Modern lecture halls use whiteboard markers ("stiften") more than krijt.', 'word', 'Er is geen krijt meer.', '"There is no more chalk" — "geen" + "meer" = "no more".', null, [ACT.vocabularyObjects]),
    createContentItem('de stift', 'də STIFT', 'A marker pen (common). Plural: stiften. Modern equivalent of krijt for whiteboards. Different colors: zwart (black), blauw (blue), rood (red), groen (green).', 'word', 'Kun je me een rode stift geven?', '"Can you give me a red marker?" — "rode" attributive adjective form of "rood".', null, [ACT.vocabularyObjects]),
    createContentItem('het papier', 'hət pa-PEER', 'Paper (neuter). Stress on -peer. Often used as a mass noun ("papier" = paper in general) but also countable (een vel papier = a sheet of paper). Plural: papieren (also means "documents" idiomatically).', 'word', 'Ik heb papier nodig.', '"I need paper" — "nodig hebben" = to need.', null, [ACT.vocabularyObjects]),
    createContentItem('de map', 'də MAP', 'A folder / binder (common). Plural: mappen. Also means "map" in computer-folder sense. Distinct from "kaart" (map = geographic chart).', 'word', 'Mijn aantekeningen zitten in de map.', '"My notes are in the folder" — "aantekeningen" = notes.', null, [ACT.vocabularyObjects]),
    createContentItem('het schrift', 'hət SKHRIFT', 'A notebook (neuter). Plural: schriften. From the verb "schrijven" (to write). Sometimes called "schoolschrift" specifically for student notebooks.', 'word', 'Schrijf het op in je schrift.', '"Write it down in your notebook" — separable verb "opschrijven" splits.', null, [ACT.vocabularyObjects]),
    createContentItem('de tas', 'də TAS', 'A bag / backpack (common). Plural: tassen. The Dutch student fiet-tas (bicycle bag) is iconic — racks of bikes with bags hooked over them outside every UvA building.', 'word', 'Mijn tas hangt aan de stoel.', '"My bag hangs on the chair" — verb "hangen".', null, [ACT.vocabularyObjects]),
    createContentItem('de laptop', 'də LEP-top', 'A laptop (common, English loan). Plural: laptops (with -s, English-style). Now the dominant note-taking tool in NL university lectures; many docents request "geen laptops in de eerste rij" (no laptops in the front row).', 'word', 'Open je laptop maar.', '"Just open your laptop" — "maar" softens the imperative.', null, [ACT.vocabularyObjects]),
    createContentItem('het scherm', 'hət SXKHƏRM', 'A screen (neuter). Plural: schermen. Used for laptop screens, projector screens, and the central display in modern lecture halls. Note sch- + rm cluster.', 'word', 'Kijk op het scherm.', '"Look at the screen" — "kijken op" with preposition op.', null, [ACT.vocabularyObjects]),
    createContentItem('de muur', 'də MYUR', 'A wall (common). Plural: muren. The long uu /yː/. Distinguish from "wand" (interior wall, also common) and "gevel" (facade).', 'word', 'Aan de muur hangt een poster.', '"On the wall hangs a poster" — V2 inversion after locative phrase.', null, [ACT.vocabularyObjects]),
    createContentItem('het raam', 'hət RAAM', 'A window (neuter). Plural: ramen (open-syllable spelling: aa → a). Note long aa. Combined: "raamkozijn" = window frame.', 'word', 'Open het raam, het is warm hier.', '"Open the window, it is warm here" — note final-devoiced d in "kozijn" (-n).', null, [ACT.vocabularyObjects]),
    createContentItem('de deur', 'də DEUR', 'A door (common). Plural: deuren. The eu vowel /øː/. The most common classroom door in NL is sliding, often with a small window.', 'word', 'Doe de deur dicht.', '"Close the door" — "dichtdoen" is a separable verb; here split.', null, [ACT.vocabularyObjects]),
    createContentItem('de klas', 'də KLAS', 'A class (the group of students, common). Plural: klassen. Distinct from "lokaal" (the room) and "les" (the lesson). So "Mijn klas heeft 30 studenten" = my class (group) has 30 students.', 'word', 'Mijn klas is groot.', '"My class (group) is big".', null, [ACT.vocabularyObjects]),
    createContentItem('het lokaal', 'hət LOH-kaal', 'A classroom / lecture room (neuter). Plural: lokalen. From Latin "locus" — a "locale". UvA buildings have lokaal numbers like "lokaal A1.05" — building A, floor 1, room 05.', 'word', 'We zitten in lokaal A1.05.', '"We are in room A1.05" — standard UvA classroom numbering.', null, [ACT.vocabularyObjects]),
    createContentItem('de docent', 'də doh-SENT', 'A teacher (common, both genders). Plural: docenten. Used for secondary and university teachers; "leraar/lerares" for primary school. Female variant: docente.', 'word', 'Onze docent is meneer De Vries.', '"Our teacher is Mr. De Vries" — "onze" because docent is de-word.', null, [ACT.vocabularyObjects]),

    createContentItem('luisteren', 'LŒY-stə-rə(n)', 'To listen (regular verb). Stem: luister. Imperative: Luister! Used in classroom commands: "Luister goed!" (Listen carefully).', 'word', 'Luister naar de docent.', '"Listen to the teacher" — "naar" is the preposition with "luisteren" (listen TO).', null, [ACT.vocabularyVerbs]),
    createContentItem('schrijven', 'SKHREI-və(n)', 'To write (irregular: stem schrijf, with v→f devoicing). Imperative: Schrijf! Past tense: schreef. Past participle: geschreven.', 'word', 'Schrijf je naam op het bord.', '"Write your name on the board" — typical first-day classroom command.', null, [ACT.vocabularyVerbs]),
    createContentItem('lezen', 'LEE-zə(n)', 'To read (irregular: vowel change in past — las, plural lazen). Stem: lees (long ee in closed syllable). Past participle: gelezen.', 'word', 'Lees deze tekst voor morgen.', '"Read this text for tomorrow" — typical homework command.', null, [ACT.vocabularyVerbs]),
    createContentItem('herhalen', 'hər-HAA-lə(n)', 'To repeat (regular). Stress on second syllable. Imperative: Herhaal! Polite request: "Kunt u dat herhalen?" — extremely common when you missed something.', 'word', 'Herhaal de zin alstublieft.', '"Repeat the sentence please" — formal polite request.', null, [ACT.vocabularyVerbs]),
    createContentItem('vragen', 'VRAA-khə(n)', 'To ask (regular). Stem: vraag. Imperative: Vraag! Noun: "vraag" (a question), plural "vragen". So "Heb je vragen?" = "Do you have questions?".', 'word', 'Mag ik een vraag stellen?', '"May I ask a question?" — note "stellen" (to pose) used with "vraag", not "vragen".', null, [ACT.vocabularyVerbs]),
    createContentItem('antwoorden', 'ANT-vor-də(n)', 'To answer (regular). Stem: antwoord. Noun: "antwoord" (an answer). Pattern: "antwoord geven op een vraag" = give an answer to a question.', 'word', 'Wie wil deze vraag beantwoorden?', '"Who wants to answer this question?" — "beantwoorden" with prefix be- is the more formal verb.', null, [ACT.vocabularyVerbs]),
    createContentItem('begrijpen', 'bə-KHREI-pə(n)', 'To understand (regular, but non-separable prefix be-). Stem: begrijp. Past: begreep. Past participle: begrepen. NOT separable: "ik begrijp" stays one word.', 'word', 'Ik begrijp het niet.', '"I do not understand" — "het" is the dummy object; "niet" negates.', null, [ACT.vocabularyVerbs]),
    createContentItem('uitleggen', 'ŒYT-leh-khə(n)', 'To explain (regular, SEPARABLE verb with prefix uit-). The prefix "uit" separates in main clauses: "Ik leg het uit" (I explain it). Stays together in subordinate clauses and infinitives.', 'word', 'Kunt u dat uitleggen?', '"Could you explain that?" — in this infinitive use, "uit" stays attached.', null, [ACT.vocabularyVerbs]),
    createContentItem('opletten', 'OP-leh-tə(n)', 'To pay attention (SEPARABLE, prefix op-). Splits: "Let goed op!" (Pay close attention!). The prefix "op" goes to the end of the main clause.', 'word', 'Let op, dit is belangrijk.', '"Pay attention, this is important" — "op" at the end of the imperative clause.', null, [ACT.vocabularyVerbs]),
    createContentItem('herhalen vs uitleggen vs opletten', 'compare verbs', 'Three classroom verbs side by side: herhalen (non-separable, just "herhaal" as imperative), uitleggen (separable, splits "uit" off), opletten (separable, splits "op" off). The prefix behavior is the dividing line.', 'sentence', 'Herhaal de zin. / Leg de zin uit. / Let goed op de zin.', 'Three actions on the same sentence, three different verb behaviors.', null, [ACT.vocabularyVerbs]),
    createContentItem('mag ik...', 'mahkh ik', 'The polite request modal "mag ik..." = "may I...". From the modal verb "mogen" (to be permitted to). Standard for asking permission in class: "Mag ik even naar de wc?" (May I go to the bathroom briefly?).', 'word', 'Mag ik je pen lenen?', '"May I borrow your pen?" — polite request among peers.', null, [ACT.vocabularyVerbs]),
    createContentItem('kunt u / kun je', 'kunt uu / kun jə', 'Polite request "could you" — formal "kunt u" with the formal pronoun, informal "kun je". From the modal "kunnen" (to be able to). Used for asking someone to do something.', 'word', 'Kunt u dat nog eens zeggen?', '"Could you say that again?" — formal classroom clarification request.', null, [ACT.vocabularyVerbs]),

    createContentItem(
      'de en het',
      'də en hət',
      'Dutch has TWO genders: "common" (de-words, ~75% of nouns) and "neuter" (het-words, ~25%). The historical masculine/feminine merged into "common" centuries ago. Plural articles are ALWAYS "de" regardless of singular gender. So "het boek" (singular) → "de boeken" (plural).',
      'sentence',
      'de tafel (common) → de tafels (plural)\nhet boek (neuter) → de boeken (plural)\nhet meisje (neuter, dim.) → de meisjes (plural)',
      'A core difficulty: many de/het pairs have NO rule reason — "de stoel" but "het bord" must be memorized. Native children take years to fully master.',
      [
        { target: 'de — common (~75%)', note: 'most concrete nouns, abstract nouns, professions; plural always uses de' },
        { target: 'het — neuter (~25%)', note: 'all diminutives, languages, metals, many small/abstract nouns' },
        { target: 'plural is always de', note: 'irrespective of singular gender; "de boeken" not "het boeken"' },
      ],
      [ACT.grammarDeHet],
    ),
    createContentItem(
      'het-categories (memorize these)',
      'hət-categorieën',
      'High-confidence het-word categories: (1) ALL diminutives in -je/-tje/-pje/-kje (het meisje, het boekje, het hondje). (2) Languages (het Nederlands, het Engels). (3) Most metals (het goud, het zilver, het ijzer). (4) Many substance/abstract words (het water, het wonder).',
      'sentence',
      '(1) -je dim.: het meisje, het boekje, het hondje\n(2) Languages: het Nederlands, het Engels, het Chinees\n(3) Metals: het goud, het zilver, het ijzer\n(4) Substances: het water, het zand, het hout',
      'Memorize these four categories; outside them, gender must be learned word-by-word.',
      [
        { target: 'all diminutives → het', note: 'no exceptions; even "de man" becomes "het mannetje"' },
        { target: 'languages → het', note: 'when referring to the language as a system; het Nederlands, het Frans' },
        { target: 'metals → het', note: 'het goud, het zilver, het ijzer, het koper' },
      ],
      [ACT.grammarDeHet],
    ),
    createContentItem(
      'classroom objects by gender',
      'klaslokaal per gender',
      'A practical sorting of this lesson\'s vocab: DE: pen, tafel, stoel, stift, map, tas, klas, muur, deur, laptop, docent. HET: boek, potlood, bord, krijt, papier, schrift, scherm, raam, lokaal, schoolbord. The het-list contains more "object/abstract" items; the de-list more "concrete tools".',
      'sentence',
      'DE: de pen, de tafel, de stoel, de stift, de map, de tas, de muur, de deur, de laptop\nHET: het boek, het potlood, het bord, het krijt, het papier, het schrift, het scherm, het raam, het lokaal',
      'Drill this list until "de boek" sounds wrong instantly — that visceral wrongness is the goal.',
      null,
      [ACT.grammarDeHet],
    ),

    createContentItem(
      '-en plural',
      'meervoud op -en',
      'The most common Dutch plural: add -en to the singular. Apply the open/closed syllable spelling rule. boek → boeken (vowel oe stays the same; n added). pen → pennen (consonant doubled to keep short e). tafel → tafels (this one is -s; see next item). stoel → stoelen.',
      'sentence',
      'boek → boeken (long oe, no change)\npen → pennen (consonant double to keep short)\nstoel → stoelen (long oe, no change)\nman → mannen (short, double consonant)\nbus → bussen (short, double s)',
      'About 60% of Dutch nouns take -en. Spelling rules drive whether vowels/consonants change.',
      [
        { target: 'short vowel → double consonant', note: 'pen → pennen, man → mannen, bus → bussen' },
        { target: 'long vowel in closed → single vowel in open', note: 'maan → manen, boot → boten' },
        { target: 'no change for most others', note: 'boek → boeken, stoel → stoelen, kind → … (irregular kinderen)' },
      ],
      [ACT.grammarPlurals],
    ),
    createContentItem(
      '-s plural',
      'meervoud op -s',
      'About 30% of Dutch nouns take -s. Common contexts: nouns ending in unstressed -e (tante → tantes), in -el/-em/-en/-er/-aar (tafel → tafels, computer → computers), in -ie (koffie → koffies), and most loanwords (foto → foto\'s with apostrophe).',
      'sentence',
      'tafel → tafels\ncomputer → computers\nkoffie → koffies\nfoto → foto\'s (apostrophe inserted to mark long vowel)\nopa → opa\'s, oma → oma\'s',
      'Apostrophe inserted before -s when the singular ends in a, o, u, y — to mark vowel length: foto\'s, taxi\'s, paraplu\'s.',
      [
        { target: 'after unstressed -e', note: 'tante, oncle, klassen-mate' },
        { target: 'after -el/-em/-er', note: 'tafel, bezem, computer, leraar' },
        { target: 'apostrophe before -s after vowel', note: 'foto\'s, taxi\'s, opa\'s, oma\'s, menu\'s' },
      ],
      [ACT.grammarPlurals],
    ),
    createContentItem(
      'irregular plurals',
      'onregelmatige meervouden',
      'A small set of irregular plurals to memorize: kind → kinderen (children, with -eren), ei → eieren (eggs), man → mannen (regular pattern but worth noting), stad → steden (vowel change a → e), schip → schepen (vowel change i → e), lid → leden (vowel change i → e).',
      'sentence',
      'kind → kinderen\nei → eieren\nstad → steden\nschip → schepen\nlid → leden',
      'About 10% of nouns have an irregular plural; the -eren and vowel-change patterns are the main groups.',
      [
        { target: '-eren', note: 'kind → kinderen, ei → eieren, blad → bladeren (leaves), volk → volkeren' },
        { target: 'vowel change a→e, i→e', note: 'stad → steden, dag → dagen (regular), schip → schepen' },
      ],
      [ACT.grammarPlurals],
    ),

    createContentItem(
      'er is / er zijn',
      'ər ɪs / ər zɛin',
      'The existential construction. "Er is + singular noun" = "there is...", "Er zijn + plural noun" = "there are...". The "er" sits in first position (the V2 slot is then filled by the verb in second). Used to introduce new entities into discourse — what is in the room, what items are available.',
      'sentence',
      'Er is een bord in het lokaal.\nEr zijn twintig stoelen.\nEr is geen krijt meer.',
      'The Dutch equivalent of English "there is/are"; "er" carries no real meaning — purely structural.',
      [
        { target: 'er is + singular', note: 'used with one of something, or mass noun' },
        { target: 'er zijn + plural', note: 'used with multiple of something' },
        { target: 'er + negation', note: 'Er is geen krijt — geen negates the noun' },
      ],
      [ACT.grammarErExistential],
    ),
    createContentItem(
      'er in questions',
      'ər in vragen',
      'In yes/no questions, invert the verb to first position; "er" stays right after the verb: "Is er een toilet?" "Zijn er pennen?". In wh-questions, the wh-word fronts, the verb follows, then "er": "Wat is er aan de hand?" (What is wrong?).',
      'sentence',
      'Is er een toilet hier?\nZijn er nog vragen?\nWat is er nieuw?',
      'Note that "er" follows the verb in inversion — a fixed position to memorize.',
      [
        { target: 'Is er...? / Zijn er...?', note: 'standard yes/no existential question' },
        { target: 'wh + verb + er', note: 'wat is er, wie is er, waar is er' },
        { target: 'Is er nog vragen?', note: 'common end-of-lecture phrase: "Are there still questions?"' },
      ],
      [ACT.grammarErExistential],
    ),
    createContentItem(
      'er with quantity',
      'ər met aantal',
      'When fronting a quantity in a sentence, Dutch sometimes uses "er" anaphorically: "Hoeveel boeken heb je?" — "Ik heb er drie" (How many books do you have? — I have three of them). Here "er" replaces "boeken". This is the "quantitative er" — preview only for now; full treatment in Level 2.',
      'sentence',
      'Hoeveel pennen heb je? — Ik heb er twee.\nHoeveel kinderen heeft u? — Ik heb er geen.',
      '"Er" before a quantity refers back to a previously mentioned countable noun. A characteristically Dutch construction (no exact English equivalent).',
      null,
      [ACT.grammarErExistential],
    ),

    createContentItem(
      'het klaslokaal',
      'hət KLAS-loh-kaal',
      'A short paragraph describing a typical UvA classroom — using er-constructions, articles, plurals, and the classroom vocab.',
      'sentence',
      'Dit is mijn klaslokaal aan de UvA. Er zijn twintig tafels en veertig stoelen. Aan de muur hangt een groot bord. Op de tafels staan laptops en boeken. Er is ook een raam met uitzicht op de gracht. Het lokaal is licht en gezellig.',
      'Translation: "This is my classroom at the UvA. There are twenty tables and forty chairs. On the wall hangs a big board. On the tables stand laptops and books. There is also a window with a view of the canal. The room is light and cozy."',
      [
        { target: 'aan de UvA', note: '"at the UvA" — "aan de" is the standard preposition for university affiliation' },
        { target: 'twintig tafels en veertig stoelen', note: 'numbers + plurals; two students per table is typical' },
        { target: 'hangt een groot bord', note: 'V2 inversion after locative phrase; adjective inflection (groot bord → because het-word singular indefinite, groot stays uninflected)' },
        { target: 'uitzicht op de gracht', note: '"view of the canal" — typical Amsterdam classroom feature' },
        { target: 'licht en gezellig', note: 'two attributive adjectives; "gezellig" is the untranslatable cozy/sociable' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'begripsvragen',
      'bə-KHRIPS-vraa-khə(n)',
      'Four comprehension questions about the paragraph.',
      'sentence',
      'V1: Waar is dit klaslokaal? V2: Hoeveel tafels zijn er? V3: Wat hangt aan de muur? V4: Is het lokaal donker?',
      'Mix of where, how-many, what, and yes/no questions covering all the patterns.',
      [
        { target: 'A1: Aan de UvA.', note: 'short location answer' },
        { target: 'A2: Twintig.', note: 'short number answer' },
        { target: 'A3: Een groot bord.', note: 'short noun-phrase answer' },
        { target: 'A4: Nee, het lokaal is licht.', note: 'negation with new fact; "donker" = dark' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'klassikaal gesprek',
      'klas-si-KAAL khə-SPREK',
      'A 6-turn classroom exchange between a docent and a student. Covers commands, polite requests, and clarification questions.',
      'conversation',
      'Docent: Goedemorgen iedereen. Doe je boeken open op pagina 15.\nStudent: Sorry, welke pagina?\nDocent: Pagina vijftien.\nStudent: Dank u. Mag ik een vraag stellen?\nDocent: Natuurlijk, ga je gang.\nStudent: Kunt u "gezellig" nog eens uitleggen?\nDocent: Zeker. "Gezellig" betekent... [explains]',
      'A classroom interaction using all the lesson patterns.',
      [
        { target: 'iedereen', note: '"everyone"; collective address' },
        { target: 'welke pagina?', note: 'wh-question with welke (which); fronted' },
        { target: 'Mag ik een vraag stellen?', note: 'formal polite question request' },
        { target: 'Ga je gang', note: '"go ahead" — idiomatic encouragement' },
        { target: 'nog eens uitleggen', note: 'separable verb (uitleggen) in infinitive — stays together; "nog eens" = "once more"' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'tweede gesprek (formeel)',
      'twee-də khə-SPREK',
      'A more formal student-docent exchange about a homework question, using "u" throughout.',
      'conversation',
      'Student: Goedemorgen meneer Bakker. Mag ik u iets vragen?\nDocent: Goedemorgen. Vraag maar.\nStudent: Ik begrijp opdracht drie niet. Kunt u het uitleggen?\nDocent: Natuurlijk. Pak je schrift erbij.\nStudent: Hier is mijn schrift.\nDocent: Goed. Lees de opdracht eerst hardop voor.',
      'Note: full "u" register throughout; "Vraag maar" softens with the casual particle "maar".',
      [
        { target: 'meneer Bakker', note: 'last-name + title address; formal' },
        { target: 'Vraag maar', note: '"just ask"; "maar" is the casualizing particle' },
        { target: 'opdracht drie', note: '"task three"; "opdracht" = assignment/task' },
        { target: 'erbij pakken', note: 'separable verb "erbij pakken" = "grab/take it with you"' },
        { target: 'hardop voorlezen', note: '"read aloud"; double-separable construction' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'mijn studieplek',
      'mein STUH-dee-plek',
      'A four-sentence writing template describing your study space — uses er-constructions, articles, and classroom vocab.',
      'sentence',
      'Mijn studieplek is [in mijn kamer / in de bibliotheek / in het café]. Er is een [tafel/bureau] en een stoel. Op de tafel staan mijn [laptop, boeken, koffie]. Het is [rustig / gezellig / licht] hier.',
      'Fill in the brackets with your own situation; the structure carries the rest.',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'schrijfoefening',
      'SKHREIF-oo-fə-ning',
      'Write your own 4-5 sentence description of your study space. Use at least one "er is/zijn" sentence, two different articles (de + het), and two plurals.',
      'sentence',
      'Voorbeeld: Mijn studieplek is in de UvA-bibliotheek. Er zijn lange tafels en veel stoelen. Op mijn tafel staan een laptop, een schrift en een kopje koffie. Aan de muur hangen kaarten van Amsterdam. Het is een rustige plek.',
      'Translation: "My study spot is in the UvA library. There are long tables and many chairs. On my table stand a laptop, a notebook, and a cup of coffee. On the wall hang maps of Amsterdam. It is a quiet spot."',
      null,
      [ACT.writing],
    ),

    createContentItem(
      'Nederlandse klascultuur',
      'klas-kul-TUUR',
      'Dutch classrooms — especially at universities — value debate, questions, and independent thought. Disagreeing with the docent is welcome; staying silent is unusual. The Socratic style is common: docents ask "Wat denk je?" (What do you think?) and expect a real opinion.',
      'sentence',
      'Docent: "Wat vinden jullie van dit idee?"  Student: "Ik ben het er niet mee eens, want..." (I disagree, because...)',
      'A "niet mee eens" (disagree) is a normal student contribution — not rude. Silence reads as disengagement.',
      [
        { target: 'questions welcomed', note: 'stop the docent mid-sentence to clarify; not rude' },
        { target: 'disagreement is okay', note: '"ik ben het niet mee eens" is a contribution, not a confrontation' },
        { target: 'silence is unusual', note: 'a fully silent student reads as not engaged, possibly not prepared' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'huiswerk-cultuur',
      'HŒYS-verk',
      'Dutch homework culture is lighter than East Asian or American models for university students, heavier than Mediterranean. Universities expect 20-25 hours independent study per week alongside lectures; primary/secondary school homework is moderate. The emphasis is on READING and writing, less on rote drilling.',
      'sentence',
      'Wekelijkse leeslijst: 80-120 pagina\'s aan vakliteratuur per cursus.',
      'Reading load at UvA averages 80-120 pages per course per week — relatively high but spread out.',
      [
        { target: 'lectures + zelfstudie', note: 'lectures are the introduction; real learning is independent reading' },
        { target: 'minder drilling', note: 'less repetition-based homework; more open-ended writing tasks' },
        { target: 'lees-cultuur', note: 'reading is highly valued; books matter even in tech fields' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'aanspreekvormen',
      'aan-SPREEK-vor-mə(n)',
      'Forms of address in NL university classrooms. First lecture: "professor X" or "meneer/mevrouw X". After invitation (often during the first tutorial): switch to first name. Most UvA docents prefer first-name address by week 3. This is unusual to learners from Germany, Korea, or the US.',
      'sentence',
      'Week 1: "Professor De Vries, mag ik..." → Week 3: "Anna, kun je..."',
      'A small but real cultural shift; many international students miss the invitation and stay overly formal.',
      [
        { target: 'first lecture: professor X', note: 'formal, last-name based' },
        { target: 'invitation arrives', note: '"zeg maar je tegen me" or first name used by docent' },
        { target: 'after that: first name', note: 'no need to ask permission again; the invitation is permanent' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'opdracht: eerste college',
      'OP-drakht: EERS-tə kol-LEH-khə',
      'Roleplay your first morning lecture at UvA with the AI tutor playing the docent. Follow commands, ask one clarifying question, and respond to the docent\'s greeting and homework instruction.',
      'conversation',
      '[UvA, lokaal A1.05, 9:00 \'s ochtends]\nDocent: Goedemorgen iedereen, welkom in Nederlands 101.\nJij: [begroet de docent]\nDocent: Doe je boeken open op pagina twintig.\nJij: [vraag verduidelijking als nodig]\nDocent: Vandaag oefenen we de werkwoorden. Pak ook je schrift erbij.\nJij: [bevestig dat je het hebt]\nDocent: Goed. Eerst luisteren, dan schrijven. Klaar?\nJij: [zeg dat je klaar bent]',
      'Six turns covering greeting, command-following, clarification, confirmation, and readiness.',
      [
        { target: 'begroet de docent', note: 'goedemorgen + title or name, polite register' },
        { target: 'vraag verduidelijking', note: 'Welke pagina? / Sorry, kunt u dat herhalen?' },
        { target: 'bevestig', note: 'Ja, ik heb het / Ja, hier' },
        { target: 'zeg dat je klaar bent', note: 'Ja, ik ben klaar / Ja hoor' },
      ],
      [ACT.task],
    ),
    createContentItem(
      'uitdaging — verloren boek',
      'œyt-DAA-khing — verloren boek',
      'Stretch goal: you forgot your book. Politely tell the docent and ask whether you can borrow one or share with a neighbor.',
      'conversation',
      'Jij: Sorry meneer, ik heb mijn boek vergeten. Mag ik even bij een klasgenoot kijken?\nDocent: Natuurlijk. Sara, kun je je boek even delen met je buurman?\nKlasgenoot: Geen probleem.\nJij: Dank je wel!',
      'A real classroom situation; "vergeten" (to forget), "delen" (to share), "buurman/buurvrouw" (neighbor).',
      [
        { target: 'mijn boek vergeten', note: 'past participle "vergeten" stays the same as infinitive (irregular)' },
        { target: 'bij een klasgenoot kijken', note: '"kijken bij" = "look at/with"; klasgenoot = classmate' },
        { target: 'kun je delen?', note: 'casual peer-to-peer with je' },
        { target: 'buurman / buurvrouw', note: 'literally "neighbor man / neighbor woman"; here = seat-neighbor' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
