// Level 1 Unit 4 — Daily Routines (Dutch)
// Functions: telling time, describing your day, using time adverbs,
// separable verbs in daily activities (opstaan, aankomen, uitgaan).

const createContentItem = (
  target,
  romanization,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization,
  nativeText: note,
  pronunciation: romanization,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'nl-l1u4-orientation',
  pronunciation: 'nl-l1u4-pronunciation',
  vocabularyTime: 'nl-l1u4-vocab-time',
  vocabularyRoutines: 'nl-l1u4-vocab-routines',
  grammarTimeExpressions: 'nl-l1u4-grammar-time-expressions',
  grammarSeparableVerbs: 'nl-l1u4-grammar-separable-verbs',
  grammarV2Word: 'nl-l1u4-grammar-v2-word',
  reading: 'nl-l1u4-reading',
  listening: 'nl-l1u4-listening',
  writing: 'nl-l1u4-writing',
  culture: 'nl-l1u4-culture',
  task: 'nl-l1u4-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Tell time on a 24-hour and 12-hour clock: "Het is half drie" (= half past two — Dutch counts FORWARD to the next hour), "Het is kwart voor zeven" (= quarter to seven).',
      'Describe a typical day using 15+ daily-activity verbs, many of them separable (opstaan, aankomen, uitgaan, opbellen).',
      'Use time adverbs to sequence a day: \'s ochtends, \'s middags, \'s avonds, \'s nachts, dan, daarna, eerst, tenslotte.',
      'Apply Dutch V2 word order with time expressions: "Om acht uur sta ik op" (At 8 o\'clock I get up), inverting subject and verb.',
    ],
    task: 'Picture yourself describing your typical Tuesday at UvA to a new classmate — by the end of this lesson, you tell the whole day in Dutch.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in time and routine Dutch',
    goals: [
      'Pronounce "half drie" /hɑlf dri/ — note the f before the long ie. The Dutch "half" feels deceptively close to English.',
      'Pronounce separable verbs in their split state: "ik sta om acht uur op" — the prefix "op" goes to the end, but is still part of the verb.',
      'Recognize the contracted "\'s ochtends" /sɔxtənts/ — the "des" of older Dutch survives as "\'s" before time words.',
    ],
    task: 'Read each example aloud paying attention to the split-verb rhythm.',
  },
  {
    id: ACT.vocabularyTime,
    section: 'Vocabulary I',
    title: 'Time expressions',
    goals: [
      'Tell the hour: "Het is één uur, twee uur, drie uur..." up to twelve.',
      'Tell the half hour using the Dutch FORWARD-counting system: "half drie" = 2:30 (literally "half three" = halfway to three).',
      'Tell quarter hours: "kwart over twee" (quarter past two), "kwart voor drie" (quarter to three).',
      'Tell minutes past/to: "tien over twee" (ten past two), "vijf voor half drie" (five to half-three = 2:25), "vijf over half drie" (five past half-three = 2:35).',
    ],
    task: 'Tell 6 different times in Dutch, including at least one half-hour and one quarter-hour.',
  },
  {
    id: ACT.vocabularyRoutines,
    section: 'Vocabulary II',
    title: 'Daily activity verbs',
    goals: [
      'Use 15+ daily-routine verbs including separable forms: opstaan (get up), ontbijten (have breakfast), aankleden (get dressed), uitgaan (go out), thuiskomen (come home), naar bed gaan (go to bed).',
      'Distinguish regular verbs (eten, drinken, slapen) from separable verbs (opstaan, aankomen, uitgaan).',
    ],
    task: 'Make a chronological list of 10 daily activities you do, each with its verb.',
  },
  {
    id: ACT.grammarTimeExpressions,
    section: 'Grammar I',
    title: 'Time expressions and "\'s"',
    goals: [
      'Use the genitive remnant "\'s" before time-of-day words: \'s ochtends, \'s middags, \'s avonds, \'s nachts (in the morning/afternoon/evening/at night). The "\'s" is a frozen genitive ending — not a possessive.',
      'Use "om" + clock time: "om acht uur" (at 8 o\'clock), "om half drie" (at 2:30).',
      'Use days of the week with "op": "op maandag" (on Monday) — note no capital letter.',
    ],
    task: 'Build 6 sentences combining a time-of-day phrase, a clock time, and a day of the week.',
  },
  {
    id: ACT.grammarSeparableVerbs,
    section: 'Grammar II',
    title: 'Separable verbs — the prefix goes to the end',
    goals: [
      'Recognize that Dutch has many SEPARABLE verbs: an infinitive like "opstaan" (to get up) splits in main clauses. "Ik sta om zeven uur op" — verb root in second position, prefix at the end.',
      'Recognize that the prefix STAYS ATTACHED in subordinate clauses and infinitives: "Ik wil opstaan" (infinitive, attached), "...dat ik opsta" (subordinate clause, attached).',
      'Identify which verbs are separable by their prefix: op-, aan-, uit-, in-, mee-, terug-, weg-, voor-, na-, door-, over- are common SEPARABLE prefixes. Be-, ver-, ont-, ge-, her-, er- are NON-separable.',
    ],
    task: 'Conjugate 4 separable verbs in main-clause split form, then in infinitive (attached) form. Identify the difference.',
  },
  {
    id: ACT.grammarV2Word,
    section: 'Grammar III',
    title: 'V2 word order with time fronting',
    goals: [
      'Apply Dutch V2 word order: when ANY element other than the subject comes first, the verb stays in second position and the subject moves AFTER the verb. So "Ik sta op om zeven uur" (default) → "Om zeven uur sta ik op" (time fronted, subject inverted).',
      'Recognize that V2 applies in all main clauses: SVO is the default, but fronting time/place/object triggers inversion.',
      'Avoid the English-speaker trap of producing "Om zeven uur ik sta op" — Dutch never allows the subject to stay second when the verb must.',
    ],
    task: 'Take 3 sentences in default SVO order and rewrite each with the time phrase fronted (V2 inversion).',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Read a daily-routine paragraph',
    goals: [
      'Read a 6-sentence daily routine with split separable verbs, time expressions, and V2 inversion.',
      'Answer comprehension questions about the routine.',
    ],
    task: 'Read aloud, then answer four comprehension questions.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'Two students compare days',
    goals: [
      'Follow a 6-turn dialogue between two UvA students comparing their weekday vs weekend routines.',
      'Reproduce the dialogue with your own activities and times.',
    ],
    task: 'Read the dialogue, then perform it with your own routine.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Describe your typical day',
    goals: [
      'Write 6-8 sentences describing your typical weekday using at least 3 separable verbs and 2 fronted time expressions (V2 inversion).',
    ],
    task: 'Write the description and read it aloud.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'Dutch time culture',
    goals: [
      'Recognize the Dutch obsession with punctuality: 15 minutes early is "on time", on time is "late", and being late means you should call ahead.',
      'Understand the "agenda" (planner) culture: meetings — even social ones — are scheduled days or weeks in advance.',
      'Recognize the "koffiepauze" (coffee break) — typically around 10:30 — as a fixed social institution at most NL workplaces.',
    ],
    task: 'Identify three Dutch time-culture norms that differ from your own.',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'My day at UvA',
    goals: [
      'Combine all the time, routine, and grammar elements into one continuous description.',
    ],
    task: 'Describe your typical Tuesday at UvA to the AI tutor in 8+ sentences.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 4: Mijn Dag — Daily Routines and Time',
  category: 'daily-routines',
  difficulty: 'beginner',
  targetLang: 'nl',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'telling-time', label: 'Telling time', goal: 'Tell any hour, half hour, quarter, or 5-minute interval in Dutch.' },
    { id: 'separable-verbs', label: 'Splitting verbs', goal: 'Split separable verbs correctly in main clauses (opstaan → sta...op).' },
    { id: 'v2-inversion', label: 'V2 fronting', goal: 'Front a time phrase and invert subject/verb correctly.' },
    { id: 'routine-description', label: 'Describing your day', goal: 'Sequence 6+ activities with time adverbs.' },
  ],
  relatedPools: ['topic-time', 'topic-routines'],
  content: [
    createContentItem('lesdoelen', 'LES-doo-lə(n)', 'Today you learn to tell time, describe your day, and master one of the hardest Dutch grammar features: separable verbs that split in main clauses. By the end, you describe a full day in Dutch with correct V2 word order.', 'word', 'Functies: tijd vertellen, dagindeling beschrijven, scheidbare werkwoorden splitsen, V2 toepassen.', 'Four micro-skills, one of which (separable verbs) is genuinely tricky.', null, [ACT.orientation]),
    createContentItem('echte situatie', 'EKH-tə si-tu-AA-tsi', 'It is your second week at UvA. A new classmate asks "Hoe ziet jouw dinsdag eruit?" (What does your Tuesday look like?). You need to tell your whole day — wake up, classes, lunch, library, dinner, bed — using split separable verbs and V2 word order.', 'word', 'Klasgenoot: "Om hoe laat sta jij \'s ochtends op?"', 'A typical peer question — note the split "sta...op" with "op" at the end, and the wh-fronted time question.', null, [ACT.orientation]),
    createContentItem('Nederlandse tijdscultuur', 'tieds-kul-TUUR', 'Dutch culture is famously punctual. Showing up 15 minutes early to a meeting is "on time". Being 5 minutes late triggers an apology AND a call ahead. Social events are also scheduled — "spontaneous" coffee in NL means "agenda check first, then coffee".', 'word', 'Dutch saying: "Wie te laat komt, eet de botjes" (those who come late eat the bones).', 'Time-keeping is a core element of Dutch professionalism and respect — not pedantry.', null, [ACT.orientation]),

    createContentItem('half drie', 'HALF DRIE', 'CRITICAL DUTCH TIME FACT: "half" + number = HALFWAY TO THAT NUMBER, not "half past". So "half drie" /hɑlf driː/ = 2:30 (halfway to 3), NOT 3:30. This is the single most common time-related learner mistake.', 'word', '14:30 = half drie\n14:30 NIET = "half twee" (which would mean 1:30)', 'A Dutch-German shared system — German also uses "halb drei" for 2:30.', null, [ACT.pronunciation]),
    createContentItem('split verb rhythm', 'split werkwoord rit-mə', 'When a separable verb splits in main clauses, the prefix lands at the END of the sentence and carries clear stress. "Ik sta om zeven uur OP" — final "op" gets prosodic prominence. Practicing this stress pattern fixes the rhythm.', 'sentence', 'Ik sta om zeven uur OP.\nIk bel mijn moeder elke avond OP.\nIk kom om vijf uur THUIS.', 'The end-stress of the prefix is what makes separable verbs sound natural.', null, [ACT.pronunciation]),
    createContentItem('\'s ochtends', 'sOKH-tənts', 'The contracted form "\'s ochtends" /ˈsɔxtənts/ — a frozen genitive remnant from older Dutch ("des ochtends" = "of the morning"). Pronounced as one phonological unit, with the s-cluster at the start.', 'word', '\'s ochtends sta ik om zeven uur op.', 'A V2 sentence with the time-of-day adverb in first position; subject "ik" inverts after verb "sta".', null, [ACT.pronunciation]),

    createContentItem('één uur', 'EEN UUR', 'One o\'clock. The double é (één) distinguishes "one" (numeral) from "een" (article, "a"). Both look the same without accents in casual writing, but in formal text the numeral takes accents.', 'word', 'Het is één uur.', '"It is one o\'clock" — note "het is" for telling time, not "er is".', null, [ACT.vocabularyTime]),
    createContentItem('twee uur', 'TVEE UUR', 'Two o\'clock. Pattern: number + "uur" (hour) without article. For 24-hour times: veertien uur = 14:00.', 'word', 'Het is twee uur \'s middags.', '"It is two in the afternoon" — combining clock time and time-of-day for clarity.', null, [ACT.vocabularyTime]),
    createContentItem('half drie / half vier', 'HALF DRIE / HALF VIER', 'Half-hour times: "half drie" = 2:30, "half vier" = 3:30, "half twaalf" = 11:30. ALWAYS halfway to the NEXT hour, never halfway after the previous.', 'sentence', 'half drie = 2:30 (halfway to 3)\nhalf zes = 5:30 (halfway to 6)\nhalf twaalf = 11:30 (halfway to 12)', 'The most error-prone time pattern for learners; English speakers consistently get it wrong by one hour.', null, [ACT.vocabularyTime]),
    createContentItem('kwart over twee', 'kvart OO-vər tvee', 'Quarter past two = 2:15. Pattern: "kwart over" + hour. "Kwart" /kʋɑrt/ = quarter.', 'word', 'Het is kwart over twee.', '"It is quarter past two" = 2:15.', null, [ACT.vocabularyTime]),
    createContentItem('kwart voor drie', 'kvart VOR drie', 'Quarter to three = 2:45. Pattern: "kwart voor" + (next hour). "Voor" /voːr/ = before/to.', 'word', 'Het is kwart voor drie.', '"It is quarter to three" = 2:45.', null, [ACT.vocabularyTime]),
    createContentItem('tien over twee', 'tien OO-vər tvee', 'Ten past two = 2:10. Pattern: minutes + "over" + hour. Used for 5/10/20/25 past the hour.', 'word', 'Het is tien over twee.', '"It is ten past two" = 2:10.', null, [ACT.vocabularyTime]),
    createContentItem('tien voor drie', 'tien VOR drie', 'Ten to three = 2:50. Pattern: minutes + "voor" + (next hour). Used for 5/10/20/25 to the next hour.', 'word', 'Het is tien voor drie.', '"It is ten to three" = 2:50.', null, [ACT.vocabularyTime]),
    createContentItem('vijf voor half drie', 'veif vor HALF drie', 'Five to half-three = 2:25. The famously confusing Dutch construction: counting backward from the half-hour. "Vijf voor half drie" = 5 minutes before 2:30 = 2:25.', 'sentence', 'vijf voor half drie = 2:25 (5 minutes before 2:30)\nvijf over half drie = 2:35 (5 minutes after 2:30)', 'Native Dutch speakers use this construction fluently; learners often retreat to "het is twee uur vijfentwintig" (2:25) which is correct but feels less natural.', null, [ACT.vocabularyTime]),
    createContentItem('\'s ochtends', 'sOKH-tənts', 'In the morning (roughly 6am-12pm). The "\'s" is the frozen genitive ending; "ochtends" = of-the-morning.', 'word', '\'s ochtends drink ik koffie.', '"In the morning I drink coffee" — V2 inversion after the time-of-day adverb.', null, [ACT.vocabularyTime]),
    createContentItem('\'s middags', 'sMID-dakhs', 'In the afternoon (roughly 12pm-6pm). From "des middags".', 'word', '\'s middags eet ik in de UvA-kantine.', '"In the afternoon I eat in the UvA cafeteria".', null, [ACT.vocabularyTime]),
    createContentItem('\'s avonds', 'sAA-vonts', 'In the evening (roughly 6pm-11pm). From "des avonds".', 'word', '\'s avonds lees ik een boek.', '"In the evening I read a book".', null, [ACT.vocabularyTime]),
    createContentItem('\'s nachts', 'sNAKHTS', 'At night (roughly 11pm-6am). From "des nachts".', 'word', '\'s nachts slaap ik diep.', '"At night I sleep deeply".', null, [ACT.vocabularyTime]),
    createContentItem('vandaag / morgen / gisteren', 'van-DAAKH / MOR-khə(n) / KHIS-tə-rə(n)', 'Today / tomorrow / yesterday. Three core time-relation words. "Morgen" doubles as "morning" (with the apostrophe-s).', 'word', 'Vandaag is dinsdag. Morgen is woensdag. Gisteren was maandag.', 'Three-day sequence using the past tense "was" (was) — preview only.', null, [ACT.vocabularyTime]),
    createContentItem('eerst / dan / daarna / tenslotte', 'eerst / dan / daar-NAA / ten-SLOH-tə', 'Four sequencing adverbs for ordering a routine: first, then, after that, finally. Used to chain activities.', 'sentence', 'Eerst sta ik op. Dan ontbijt ik. Daarna fiets ik naar UvA. Tenslotte kom ik thuis.', 'A 4-step routine using all four sequence words.', null, [ACT.vocabularyTime]),

    createContentItem('opstaan', 'OP-staan', 'SEPARABLE: to get up (out of bed). Prefix "op" + stem "staan". Main clause: "Ik sta om zeven uur op". Infinitive: "Ik wil opstaan".', 'word', 'Ik sta elke ochtend om zeven uur op.', '"I get up every morning at seven o\'clock" — split verb with "op" at end.', null, [ACT.vocabularyRoutines]),
    createContentItem('ontbijten', 'ONT-bei-tə(n)', 'Non-separable (prefix ont- is fixed): to have breakfast. "Ik ontbijt om acht uur". Noun: "het ontbijt" (the breakfast).', 'word', 'We ontbijten met brood en kaas.', '"We have breakfast with bread and cheese" — classic Dutch ontbijt.', null, [ACT.vocabularyRoutines]),
    createContentItem('aankleden', 'AAN-klee-də(n)', 'SEPARABLE reflexive: to get dressed (oneself). Prefix "aan" + stem "kleden". Main clause: "Ik kleed me \'s ochtends aan". Reflexive: needs "me/je/zich".', 'word', 'Ik kleed me snel aan.', '"I get dressed quickly" — note reflexive "me" + final "aan".', null, [ACT.vocabularyRoutines]),
    createContentItem('weggaan', 'VEH-khaan', 'SEPARABLE: to leave (go away). Prefix "weg" + stem "gaan". Main clause: "Ik ga om acht uur weg". Past: "Ik ging weg".', 'word', 'Om acht uur ga ik weg naar de UvA.', '"At eight o\'clock I leave for the UvA" — V2 inversion + separable.', null, [ACT.vocabularyRoutines]),
    createContentItem('aankomen', 'AAN-koh-mə(n)', 'SEPARABLE: to arrive. Prefix "aan" + stem "komen". Main clause: "Ik kom om half negen aan". Used for both physical arrival and "arriving at a conclusion".', 'word', 'De trein komt om kwart over zeven aan.', '"The train arrives at quarter past seven".', null, [ACT.vocabularyRoutines]),
    createContentItem('beginnen', 'bə-GIN-nə(n)', 'Non-separable (prefix be- fixed): to begin. "De les begint om negen uur".', 'word', 'Mijn eerste college begint om half tien.', '"My first lecture begins at 9:30".', null, [ACT.vocabularyRoutines]),
    createContentItem('eten', 'EE-tə(n)', 'Regular: to eat. Stem: eet. Past: at. Past participle: gegeten. NL eats lunch ("lunchen") around 12-1pm, dinner ("avondeten") around 6pm — earlier than southern Europe.', 'word', 'Ik eet om zes uur \'s avonds.', '"I eat at six o\'clock in the evening".', null, [ACT.vocabularyRoutines]),
    createContentItem('drinken', 'DRIN-kə(n)', 'Regular: to drink. Stem: drink. Past: dronk. Past participle: gedronken.', 'word', 'Ik drink elke ochtend koffie.', '"I drink coffee every morning".', null, [ACT.vocabularyRoutines]),
    createContentItem('werken', 'VEHR-kə(n)', 'Regular: to work. Stem: werk. Past: werkte (weak verb). Past participle: gewerkt.', 'word', 'Ik werk \'s middags in een café.', '"I work in a café in the afternoon".', null, [ACT.vocabularyRoutines]),
    createContentItem('studeren', 'stuh-DEE-rə(n)', 'Regular: to study. Stem: studeer (long ee in closed syllable). Past: studeerde. Past participle: gestudeerd.', 'word', 'Ik studeer informatica aan de UvA.', '"I study computer science at the UvA".', null, [ACT.vocabularyRoutines]),
    createContentItem('opbellen', 'OP-bel-lə(n)', 'SEPARABLE: to call (on the phone). Prefix "op" + stem "bellen". Main clause: "Ik bel mijn moeder elke avond op". Same meaning as just "bellen" but slightly more emphatic.', 'word', 'Ik bel mijn vriend om acht uur op.', '"I call my friend at 8 — the prefix op goes to the end".', null, [ACT.vocabularyRoutines]),
    createContentItem('uitgaan', 'ŒYT-khaan', 'SEPARABLE: to go out (party, social). Prefix "uit" + stem "gaan". Main clause: "Wij gaan zaterdag uit". Different from "weggaan" (leave): "uitgaan" is specifically going out for fun.', 'word', 'Vrijdagavond gaan wij uit.', '"Friday evening we go out (partying)".', null, [ACT.vocabularyRoutines]),
    createContentItem('thuiskomen', 'TŒYS-koh-mə(n)', 'SEPARABLE: to come home. Prefix "thuis" + stem "komen". Main clause: "Ik kom om vijf uur thuis". Distinct from "naar huis gaan" (go home, generic).', 'word', 'Ik kom \'s avonds laat thuis.', '"I come home late in the evening".', null, [ACT.vocabularyRoutines]),
    createContentItem('slapen', 'SLAA-pə(n)', 'Strong irregular: to sleep. Stem: slaap (double aa). Past: sliep (vowel change). Past participle: geslapen.', 'word', 'Ik slaap acht uur per nacht.', '"I sleep eight hours per night".', null, [ACT.vocabularyRoutines]),
    createContentItem('naar bed gaan', 'naar BET khaan', 'Compound phrase: "to go to bed". NOT a separable verb — it is a verb + prepositional phrase. Main clause: "Ik ga om elf uur naar bed".', 'word', 'Ik ga vroeg naar bed.', '"I go to bed early".', null, [ACT.vocabularyRoutines]),

    createContentItem(
      '\'s ochtends / \'s middags / \'s avonds / \'s nachts',
      'genitief fossielen',
      'The four "\'s + time" expressions are fossilized genitive forms — "\'s" = "des" (of the). They occur at the start of sentences as time adverbs, triggering V2 inversion. The "\'s" attaches phonologically to the next word.',
      'sentence',
      '\'s ochtends sta ik om zeven uur op.\n\'s middags eet ik in de kantine.\n\'s avonds lees ik een boek.\n\'s nachts slaap ik diep.',
      'Four fronted time adverbs, four V2 inversions — every subject moves after the verb.',
      [
        { target: '\'s ochtends', note: 'in the morning; ~6am-12pm' },
        { target: '\'s middags', note: 'in the afternoon; ~12pm-6pm' },
        { target: '\'s avonds', note: 'in the evening; ~6pm-11pm' },
        { target: '\'s nachts', note: 'at night; ~11pm-6am' },
      ],
      [ACT.grammarTimeExpressions],
    ),
    createContentItem(
      'om + clock time',
      'om + tijd',
      'The preposition "om" introduces clock times: "om acht uur" (at 8 o\'clock), "om half drie" (at 2:30), "om kwart voor zeven" (at 6:45). NOT "op acht uur" — "op" is for days.',
      'sentence',
      'Om zeven uur sta ik op.\nOm half negen ben ik op de UvA.\nOm zes uur eet ik thuis.',
      '"Om" is the dedicated clock-time preposition; for days use "op".',
      null,
      [ACT.grammarTimeExpressions],
    ),
    createContentItem(
      'op + day of week',
      'op + dag',
      'The preposition "op" introduces days: "op maandag" (on Monday), "op zaterdag" (on Saturday). The days are NOT capitalized in Dutch (unlike English). The 7 days: maandag, dinsdag, woensdag, donderdag, vrijdag, zaterdag, zondag.',
      'sentence',
      'Op maandag heb ik college om negen uur.\nOp zaterdag werk ik in de winkel.\nOp zondag rust ik.',
      'Days lowercase, "op" preposition fixed.',
      [
        { target: 'maandag — Monday', note: 'from "Maan" (moon)' },
        { target: 'dinsdag — Tuesday', note: 'from "Tiu" (Germanic god, like English "Tuesday")' },
        { target: 'woensdag — Wednesday', note: 'from "Woden" (chief Germanic god, like English "Wednesday")' },
        { target: 'donderdag — Thursday', note: 'from "Donar/Thor" (thunder god)' },
        { target: 'vrijdag — Friday', note: 'from "Freya" or "free"' },
        { target: 'zaterdag — Saturday', note: 'from "Saturn"' },
        { target: 'zondag — Sunday', note: 'from "Zon" (sun)' },
      ],
      [ACT.grammarTimeExpressions],
    ),

    createContentItem(
      'scheidbare werkwoorden',
      'SKHEID-baa-rə VEHR-k-vor-də(n)',
      'SEPARABLE VERBS are a defining feature of Dutch (and German). The infinitive has a prefix glued on: opstaan, aankomen, uitgaan, opbellen. In a MAIN CLAUSE, the prefix SEPARATES from the stem and moves to the END of the sentence. In SUBORDINATE clauses and INFINITIVE uses, the prefix stays attached.',
      'sentence',
      'INFINITIVE: opstaan\nMAIN CLAUSE: Ik sta om zeven uur OP.\nINFINITIVE USE: Ik wil opstaan.\nSUBORDINATE: Ik zeg dat ik om zeven uur opsta.',
      'The split is the single most distinctive Dutch syntactic feature beginners must master. Drill it relentlessly.',
      [
        { target: 'main clause → split', note: 'verb stem in V2 slot; prefix at sentence end' },
        { target: 'subordinate clause → attached', note: 'verb at end, prefix glued back on' },
        { target: 'after modal verb → attached', note: 'modal + infinitive; prefix stays glued (Ik wil opstaan)' },
      ],
      [ACT.grammarSeparableVerbs],
    ),
    createContentItem(
      'separable prefixes',
      'voorvoegsels',
      'COMMON SEPARABLE PREFIXES (always separable): op- (opstaan, opbellen), aan- (aankomen, aankleden), uit- (uitgaan, uitleggen), in- (inhalen, instappen), mee- (meedoen, meegaan), terug- (terugkomen, terugbellen), weg- (weggaan, wegrijden), voor- (voorlezen, voorstellen — for "introduce someone"), na- (nakijken, nadenken), door- (doorzetten, doorlezen), over- (overstappen).',
      'sentence',
      'op-: opstaan, opbellen, oppakken\naan-: aankomen, aankleden, aankijken\nuit-: uitgaan, uitleggen, uitvinden\nin-: instappen, inhalen, inkopen',
      'These 11 prefixes cover ~80% of separable verbs you will meet.',
      null,
      [ACT.grammarSeparableVerbs],
    ),
    createContentItem(
      'non-separable prefixes',
      'niet-scheidbare voorvoegsels',
      'NON-SEPARABLE PREFIXES (never separate): be- (begrijpen, beginnen, beslissen), ver- (vergeten, verbinden, verkopen), ont- (ontbijten, ontmoeten, ontwikkelen), ge- (gebeuren — rare as productive), her- (herhalen, herinneren), er- (erkennen — rare).',
      'sentence',
      'be-: begrijpen, beginnen, beslissen\nver-: vergeten, verkopen, verliezen\nont-: ontbijten, ontmoeten, ontwikkelen\nher-: herhalen, herinneren',
      'These prefixes are FIXED — verbs with them never split.',
      [
        { target: 'be- → fixed', note: 'begrijpen (understand), beslissen (decide), bevatten (contain)' },
        { target: 'ver- → fixed', note: 'verliezen (lose), vertellen (tell), vergeten (forget)' },
        { target: 'ont- → fixed', note: 'ontmoeten (meet), ontwikkelen (develop), ontbijten (have breakfast)' },
      ],
      [ACT.grammarSeparableVerbs],
    ),
    createContentItem(
      'stress test for separable',
      'klemtoon-test',
      'A useful diagnostic: SEPARABLE prefixes are STRESSED (OP-staan, AAN-komen, UIT-gaan). NON-SEPARABLE prefixes are UNSTRESSED (be-GRIJ-pen, ver-LIE-zen, ont-MOE-ten). Listen to stress; it tells you whether the verb will split.',
      'sentence',
      'STRESSED prefix → separates: ÓP-staan → "Ik sta op"\nUNSTRESSED prefix → fixed: be-GRIJ-pen → "Ik begrijp"',
      'A 95% reliable shortcut: stress predicts separability.',
      null,
      [ACT.grammarSeparableVerbs],
    ),

    createContentItem(
      'V2 word order',
      'V-twee',
      'Dutch is a V2 (verb-second) language. The finite verb is ALWAYS in the second position of a main clause — never first (unless yes/no question), never third or later. The first position can be the subject (default SVO) OR a time/place/object phrase (which triggers subject-verb inversion).',
      'sentence',
      'DEFAULT (subject first): Ik sta om zeven uur op.\nTIME FRONTED: Om zeven uur sta ik op.\nOBJECT FRONTED: Mijn koffie drink ik \'s ochtends.\nPLACE FRONTED: In de UvA-bibliotheek studeer ik.',
      'Same content, four positions for the first element. The verb stays second; everything else rearranges around it.',
      [
        { target: 'pos 1 = anything', note: 'subject, time, place, object — but only ONE element' },
        { target: 'pos 2 = finite verb', note: 'always; this is the unshakeable rule' },
        { target: 'subject after verb in inversion', note: 'when pos 1 is non-subject, subject moves to pos 3' },
      ],
      [ACT.grammarV2Word],
    ),
    createContentItem(
      'inversion examples',
      'inversie',
      'Three pairs showing V2 inversion. Default (subject first) → fronted (time/place first, subject after verb).',
      'sentence',
      'Ik fiets om half negen naar UvA. → Om half negen fiets ik naar UvA.\nWij eten \'s avonds thuis. → \'s Avonds eten wij thuis.\nIk werk op zaterdag in de winkel. → Op zaterdag werk ik in de winkel.',
      'The subject "ik/wij" moves to position 3 when time/place takes position 1.',
      null,
      [ACT.grammarV2Word],
    ),
    createContentItem(
      'word order in clause',
      'word-order',
      'Inside the clause after V2: typical Dutch order is Time-Manner-Place (TMP). "Ik werk \'s avonds (T) hard (M) in de bibliotheek (P)". This is the inverse of English Place-Manner-Time. Learners often produce English-style order and sound foreign.',
      'sentence',
      'DUTCH: Ik werk \'s avonds (T) hard (M) in de bibliotheek (P).\nENGLISH translation order: Ik werk in de bibliotheek hard \'s avonds.',
      'TMP order is a strong Dutch preference — not always rigidly enforced but very common.',
      null,
      [ACT.grammarV2Word],
    ),

    createContentItem(
      'mijn dag',
      'mein dakh',
      'A 7-sentence daily routine using split separable verbs, V2 inversion, and time expressions.',
      'sentence',
      'Mijn dag begint vroeg. \'s Ochtends sta ik om zeven uur op, en ik kleed me snel aan. Daarna ontbijt ik met brood en kaas. Om kwart over acht ga ik weg, en ik fiets naar de UvA. Mijn eerste college begint om half tien. \'s Middags eet ik in de kantine en studeer ik in de bibliotheek. Tenslotte kom ik om zes uur \'s avonds thuis en bel ik mijn moeder op.',
      'Translation: "My day begins early. In the morning I get up at seven, and I get dressed quickly. After that I have breakfast with bread and cheese. At quarter past eight I leave, and I cycle to the UvA. My first lecture begins at 9:30. In the afternoon I eat in the cafeteria and study in the library. Finally I come home at six in the evening and call my mother."',
      [
        { target: 'sta ik om zeven uur op', note: 'separable opstaan split — V2 verb + final "op"' },
        { target: 'kleed me snel aan', note: 'reflexive separable aankleden split — V2 + reflexive + final "aan"' },
        { target: 'ga ik weg', note: 'separable weggaan split' },
        { target: 'kom ik om zes uur thuis', note: 'separable thuiskomen split' },
        { target: 'bel ik mijn moeder op', note: 'separable opbellen split' },
        { target: '\'s Ochtends... \'s Middags...', note: 'fronted time adverbs triggering V2 inversion' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      'begripsvragen',
      'bə-KHRIPS-vraa-khə(n)',
      'Four comprehension questions about the daily routine.',
      'sentence',
      'V1: Hoe laat staat de spreker op? V2: Wat eet hij/zij \'s ochtends? V3: Wanneer begint het eerste college? V4: Wat doet de spreker \'s avonds?',
      'Mix of when, what, and how-late questions.',
      [
        { target: 'A1: Om zeven uur.', note: 'short clock answer using "om"' },
        { target: 'A2: Brood en kaas.', note: 'short food answer' },
        { target: 'A3: Om half tien.', note: 'clock answer using "om" and half-hour' },
        { target: 'A4: Eet thuis en belt zijn/haar moeder op.', note: 'composite answer with two activities' },
      ],
      [ACT.reading],
    ),

    createContentItem(
      'twee studenten vergelijken dagen',
      'twee stuhDENTEN',
      'A 6-turn dialogue between two UvA students comparing their weekday vs weekend routines.',
      'conversation',
      'Sara: Hoe ziet jouw maandag eruit?\nPieter: Druk! Ik sta om zes uur op en fiets om half acht naar UvA. Jij?\nSara: Ik begin later. Om negen uur sta ik op en ga om half elf weg.\nPieter: En in het weekend?\nSara: In het weekend slaap ik uit, sta om elf uur op, en ga \'s avonds met vrienden uit.\nPieter: Lekker! Ik werk meestal op zaterdag in een café.',
      'Casual peer exchange comparing routines; notice "uitslapen" (sleep in), "uitgaan" (go out), "werken" — all relevant routine verbs.',
      [
        { target: 'Hoe ziet jouw X eruit?', note: '"What does your X look like?" — common Dutch construction with separable "eruit zien"' },
        { target: 'Druk!', note: '"Busy!" — single-word emphatic answer; very common' },
        { target: 'uitslapen', note: 'separable: to sleep in / late; splits to "slaap...uit"' },
        { target: 'in het weekend', note: '"on the weekend"; note "in" + "het", not "op"' },
        { target: 'Lekker!', note: 'multipurpose enthusiastic agreement; here "nice!" or "sweet!"' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      'professionele dag',
      'pro-fes-yo-NEE-lə dakh',
      'A more formal version: a UvA professor describing their day to a visitor.',
      'conversation',
      'Bezoeker: Hoe ziet uw werkdag er meestal uit?\nProfessor: Ik sta om half zeven op, lees de krant, en ben om half negen op de UvA.\nBezoeker: En \'s middags?\nProfessor: \'s Middags geef ik colleges, en \'s avonds werk ik thuis aan onderzoek.\nBezoeker: Klinkt druk.\nProfessor: Het valt mee. Op zondag rust ik.',
      'Formal register: "u" address, longer sentences, more substantive vocabulary.',
      [
        { target: 'Hoe ziet uw werkdag er meestal uit?', note: '"What does your typical workday look like?" — formal version with "uw" (formal possessive)' },
        { target: 'lees de krant', note: '"read the newspaper" — Dutch idiom for morning routine' },
        { target: 'colleges geven', note: '"give lectures"; "college" here = university lecture' },
        { target: 'onderzoek', note: '"research" — neuter noun, no plural in this sense' },
        { target: 'Het valt mee', note: '"it\'s not so bad" — common Dutch understatement' },
      ],
      [ACT.listening],
    ),

    createContentItem(
      'mijn typische dinsdag',
      'mein TIE-pi-sə dinz-dakh',
      'A reusable template for describing your typical Tuesday. Fill in brackets.',
      'sentence',
      'Mijn dinsdag begint om [tijd]. \'s Ochtends [activiteit] ik. Om [tijd] ga ik [bestemming]. Mijn eerste college is over [vak]. \'s Middags eet ik [eten]. Tenslotte kom ik om [tijd] thuis en [activiteit] ik.',
      'Six sentences covering morning, leaving, classes, lunch, return.',
      null,
      [ACT.writing],
    ),
    createContentItem(
      'schrijfoefening',
      'SKHREIF-oo-fə-ning',
      'Write your own 6-8 sentence Tuesday using at least 3 split separable verbs and 2 fronted time expressions.',
      'sentence',
      'Voorbeeld: Mijn dinsdag begint om zeven uur. Ik sta op, kleed me aan, en ontbijt met yoghurt. Om half negen fiets ik naar de UvA. Om half tien begint mijn eerste college over algoritmes. \'s Middags eet ik een tosti in de kantine en studeer ik in de UB tot vier uur. Tenslotte kom ik om half zes thuis en bel ik mijn vriendin op.',
      'Translation: "My Tuesday begins at seven. I get up, get dressed, and have breakfast with yogurt. At half past eight I cycle to the UvA. At 9:30 my first lecture on algorithms begins. In the afternoon I eat a tosti in the cafeteria and study in the UB until four. Finally I come home at half past five and call my girlfriend."',
      null,
      [ACT.writing],
    ),

    createContentItem(
      'op tijd komen',
      'op TEID koh-mə(n)',
      'Dutch punctuality is famous and real. Showing up 15 minutes EARLY is "on time" for a job interview or important meeting. Arriving "on the dot" can already feel late. Being 5 minutes late triggers an apology and a call ahead. Many international workers find this rigorously punctual — it is.',
      'sentence',
      'Saying: "Wie te laat komt, eet de botjes" — "those who come late eat the bones" (i.e., miss the meal).',
      'A core Dutch professional norm; learners should adjust expectations rather than fight it.',
      [
        { target: '15 minutes early = on time', note: 'job interviews, doctor appointments, important meetings' },
        { target: 'on time = "te laat" feeling', note: 'arriving at the exact minute can feel late socially' },
        { target: '5+ minutes late = call ahead', note: 'apologize and notify; otherwise considered disrespectful' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'agenda-cultuur',
      'a-KHEN-da-kul-tuur',
      'The "agenda" (planner/calendar) is sacred in Dutch culture. Even social events — coffees, drinks, dinner with friends — are scheduled days or weeks in advance. Spontaneous "let\'s meet up tonight" is rare. NL friends will say "Ik kijk in mijn agenda" (I\'ll check my calendar) before agreeing to ANY social plan.',
      'sentence',
      'Sara: Zullen we koffie drinken? — Pieter: Ja, leuk. Ik kijk even in mijn agenda. Vrijdag om vier uur?',
      'A typical NL coffee-arrangement exchange — scheduled four days ahead.',
      [
        { target: 'agenda check is standard', note: 'before any social plan; not rude, just thorough' },
        { target: 'plans days/weeks ahead', note: 'coffee on Friday is planned on Monday; dinner next month is planned now' },
        { target: '"spontaneous" requires planning', note: 'a Dutch joke: "spontaan op vrijdag" = "spontaneously on Friday" but planned Tuesday' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'koffiepauze',
      'KOF-fee-pou-zə',
      'The coffee break — typically around 10:30 in offices — is a fixed social institution. Colleagues gather at the espresso machine for 10-15 minutes, exchange news, and return to work. Skipping the koffiepauze regularly marks you as antisocial. Most workplaces have a specific koffiepauze culture documented in HR onboarding.',
      'sentence',
      'Om half elf is koffiepauze. Iedereen komt samen bij de koffiemachine.',
      'A core NL workplace ritual; learn it within your first week of any Dutch job.',
      [
        { target: '10:30 ish — fixed slot', note: 'the canonical NL office coffee break time' },
        { target: 'social, not just caffeine', note: 'the conversation matters as much as the coffee' },
        { target: 'skipping = antisocial signal', note: 'doing it once is fine; making it a pattern is noticed' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      'eettijden',
      'EET-tei-də(n)',
      'Dutch meal times are EARLY by Mediterranean standards. Lunch ("lunchen") is 12-1pm — typically a sandwich (boterham) at the desk or in the cafeteria. Dinner ("avondeten" or "warm eten") is 6-7pm — the warm main meal of the day. Many shops close at 18:00 because everyone is at home eating.',
      'sentence',
      'Lunch: 12:00-13:00, vaak een boterham of tosti.\nAvondeten: 18:00-19:00, het warme hoofdgerecht.',
      'Adjusting to Dutch meal times is one of the first cultural shifts for southern European newcomers.',
      [
        { target: 'lunch 12-1pm — boterham', note: 'sandwich-based; quick; often eaten at desk' },
        { target: 'avondeten 6-7pm — warm meal', note: 'main meal; family-oriented; warm food' },
        { target: 'shops close 18:00', note: 'most supermarkets and shops; everyone home for dinner' },
      ],
      [ACT.culture],
    ),

    createContentItem(
      'opdracht: vertel over je dinsdag',
      'OP-drakht: vər-TEL',
      'Roleplay describing your typical Tuesday at UvA to the AI tutor. Include at least 3 split separable verbs, 2 fronted time expressions, and a sequence of activities.',
      'conversation',
      'AI-tutor: Vertel eens over je dinsdag aan de UvA.\nJij: [begin met "Mijn dinsdag begint om..."]\nAI-tutor: En \'s middags?\nJij: [beschrijf middag]\nAI-tutor: Wat doe je \'s avonds?\nJij: [beschrijf avond + slaap]\nAI-tutor: Klinkt een drukke dag!\nJij: [reageer]',
      'Six turns; tutor prompts you through the day.',
      [
        { target: 'Vertel eens over...', note: '"Tell me about..."; "eens" softens to invitation' },
        { target: 'Mijn dinsdag begint om...', note: 'standard opener with "om" + clock time' },
        { target: 'Klinkt een drukke dag', note: '"sounds like a busy day"; common Dutch reaction' },
        { target: 'reageer', note: 'agree (Ja, heel druk) or disagree (Valt mee, gewoon vol)' },
      ],
      [ACT.task],
    ),
    createContentItem(
      'uitdaging — anders in het weekend',
      'œyt-DAA-khing',
      'Stretch goal: now describe how your weekend is DIFFERENT from your weekday. Use "anders" (different), "in plaats van" (instead of), and at least one fronted "In het weekend..." sentence.',
      'conversation',
      'AI-tutor: En hoe is je weekend anders?\nJij: In het weekend slaap ik uit tot tien uur, in plaats van zeven uur. Ik ontbijt rustig met mijn vriendin, en \'s middags gaan we naar de markt. \'s Avonds gaan we vaak uit naar een café in de Jordaan. Het is heel anders dan de werkweek.',
      'Showcase fronted time + separable + comparative.',
      [
        { target: 'In het weekend...', note: 'fronted time phrase triggers V2 inversion' },
        { target: 'in plaats van', note: '"instead of"; takes a noun complement' },
        { target: 'rustig', note: '"calm, peaceful"; signals slower weekend pace' },
        { target: 'heel anders dan', note: '"very different from"; "dan" is the comparative particle' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
