// Level 1 Unit 5 — Life in the Philippines (Filipino/Tagalog)
// Functions: describing Philippine geography, regional identities, food, transit
// systems, climate, OFW culture, jeepney/tricycle ecosystem.

const createContentItem = (target, pron, note, type = 'word', example = '', exampleNote = '', breakdown = null, activityIds = []) => ({
  type, activityIds, targetText: target, romanization: pron, nativeText: note,
  pronunciation: pron, exampleTarget: example || target, exampleNative: exampleNote || note,
  korean: target, english: note, example: example || target, exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'fil-l1u5-orientation',
  pronunciation: 'fil-l1u5-pronunciation',
  vocabularyGeography: 'fil-l1u5-vocab-geography',
  vocabularyCulture: 'fil-l1u5-vocab-culture',
  vocabularyFood: 'fil-l1u5-vocab-food',
  grammarTaga: 'fil-l1u5-grammar-taga',
  grammarMay: 'fil-l1u5-grammar-may',
  grammarComparison: 'fil-l1u5-grammar-comparison',
  reading: 'fil-l1u5-reading',
  listening: 'fil-l1u5-listening',
  writing: 'fil-l1u5-writing',
  culture: 'fil-l1u5-culture',
  task: 'fil-l1u5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'Your Philippines snapshot', goals: ['Name the three main island groups (Luzon, Visayas, Mindanao) and 5-6 major cities (Manila, QC, Cebu, Davao, Iloilo, Baguio).', 'Describe Philippine climate (tag-init / tag-ulan), basic geography (7,641 islands), and core cultural concepts (pamilya, bayanihan, OFW).', 'Identify regional languages (Cebuano, Ilocano, Hiligaynon) culturally without conflating them with Filipino/Tagalog.'], task: 'By lesson end you can hold a 2-minute introduction to the Philippines for a friend abroad in Filipino — geography, food, culture.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Place-name stress', goals: ['Apply correct stress on Philippine place names: Maynila (ma-NI-la), Cebu (se-BU), Iloilo (i-lo-I-lo), Davao (da-VAU/da-VAO), Baguio (BAG-yo).', 'Pronounce regional/indigenous place names with original phonology rather than English-style stress.'], task: 'Read each city name aloud with native stress.' },
  { id: ACT.vocabularyGeography, section: 'Vocabulary I', title: 'Geography & climate', goals: ['Memorize 12 geography/climate words covering islands, regions, weather seasons, and natural features.'], task: 'Locate each on a Philippine map.' },
  { id: ACT.vocabularyCulture, section: 'Vocabulary II', title: 'Cultural concepts', goals: ['Memorize 8 culturally specific words (bayanihan, OFW, pamilya, ninong/ninang, fiesta, balikbayan, utang na loob, hiyà).', 'Recognize that several are UNTRANSLATABLE — they take a paragraph to explain.'], task: 'Choose 3 concepts and explain each in 2 Filipino sentences.' },
  { id: ACT.vocabularyFood, section: 'Vocabulary III', title: 'Iconic Filipino food', goals: ['Memorize 10 iconic dishes (adobo, sinigang, lechon, halo-halo, lumpia, pancit, kare-kare, sisig, tinola, balut).'], task: 'Pick 5 you have or want to try; describe each.' },
  { id: ACT.grammarTaga, section: 'Grammar I', title: 'Taga- prefix (review + extension)', goals: ['Use taga- with regional places: Taga-Cebu (Cebuano person/origin), taga-Mindanao.', 'Distinguish taga- (origin) from -an/-non (suffix forming regional adjective in some dialects, e.g., Cebuano-non but not standard Tagalog).'], task: 'Form taga- phrases for 5 Philippine cities.' },
  { id: ACT.grammarMay, section: 'Grammar II', title: 'May / Walâ for existence (review)', goals: ['Use may to describe what the Philippines has: "May 7,641 islands ang Pilipinas".', 'Use walâ for what is absent: "Walâ kaming nieve".'], task: 'Make 5 may/walâ statements about the Philippines.' },
  { id: ACT.grammarComparison, section: 'Grammar III', title: 'Mas + adjective + sa for comparison', goals: ['Form comparative "more than X": Mas malaki ang Manila kaysa sa Cebu. (Manila is bigger than Cebu).', 'Form superlative: Pinakamalaki ang Quezon City. (Quezon City is the biggest.)'], task: 'Compare 3 pairs of Philippine cities.' },
  { id: ACT.reading, section: 'Reading', title: 'Philippines snapshot paragraph', goals: ['Read a paragraph about the Philippines and answer comprehension.'], task: 'Read; answer.' },
  { id: ACT.listening, section: 'Listening', title: 'Talking about home with a foreign friend', goals: ['Follow a dialogue between a Filipino student and a foreign exchange friend.'], task: 'Listen; perform.' },
  { id: ACT.writing, section: 'Writing', title: 'Introduce the Philippines to a pen pal', goals: ['Write 6-8 sentences introducing the Philippines abroad using geography, culture, and food vocabulary.'], task: 'Write and read.' },
  { id: ACT.culture, section: 'Culture', title: 'Filipinos abroad — OFW culture', goals: ['Know that ~10% of Filipinos work abroad (OFWs); they send remittances (~$36B/year) that sustain millions of families.', 'Understand balikbayan culture: returning OFWs bring boxes (balikbayan boxes) full of goods.', 'Recognize fiesta culture: every barangay has its annual patron-saint fiesta.'], task: 'Describe one OFW connection in your own circle (if any) or a fiesta you would attend.' },
  { id: ACT.task, section: 'Task', title: 'Talk about the Philippines with a foreign friend', goals: ['Combine geography + culture + food in a 2-minute self-led narrative with an AI tutor playing a curious foreign friend.'], task: 'Roleplay; AI asks 4-5 questions.' },
];

const lesson = {
  title: 'Level 1 · Unit 5: Buhay sa Pilipinas — Life in the Philippines',
  category: 'life-philippines',
  difficulty: 'beginner',
  targetLang: 'fil',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describing-philippines', label: 'Describing the Philippines', goal: 'Combine geography, climate, and cultural facts in fluent paragraphs.' },
    { id: 'regional-origin', label: 'Talking about regional origin', goal: 'Use taga- with regional names and reference Cebuano/Ilocano/Hiligaynon cultures.' },
    { id: 'comparing', label: 'Comparing places', goal: 'Use mas + adj + sa and pinaka- for superlative.' },
    { id: 'cultural-concepts', label: 'Explaining cultural concepts', goal: 'Define bayanihan, OFW, pamilya, fiesta in your own Filipino sentences.' },
  ],
  relatedPools: ['topic-philippines', 'topic-culture'],
  content: [
    createContentItem('Pilipinas', 'pi-li-PI-nas', '"The Philippines". An archipelago of 7,641 islands in Southeast Asia. Population ~115 million. Official languages: Filipino and English. Capital: Manila. Spanish colonial period 1565-1898; American period 1898-1946; independent since 1946 (July 4) / 1898 (June 12 — official Independence Day).', 'word', 'Ang Pilipinas ay may 7,641 isla.', 'Foundational identity statement; the famous "7,107 islands" was the older count before satellite surveys revealed more.', null, [ACT.orientation, ACT.vocabularyGeography]),
    createContentItem('Luzon', 'LU-son', 'The largest and northernmost island group. Home to Metro Manila, Baguio, the Cordillera region (Igorot peoples), Ilocos region, Bicol region. Population ~60 million.', 'word', 'Taga-Luzon ang nanay ko, taga-Maynila.', '"My mom is from Luzon, specifically Manila."', null, [ACT.vocabularyGeography]),
    createContentItem('Visayas', 'bi-SA-yas', 'The central island group: Cebu, Iloilo, Bacolod, Tacloban. Primary languages: Cebuano (Bisaya), Hiligaynon (Ilonggo), Waray. ~20 million people. Famous for beaches (Boracay, Bohol), the Sinulog festival, and historical sites (Magellan landed in Cebu 1521).', 'word', 'Pumunta kami sa Boracay sa Visayas noong summer.', '"We went to Boracay in the Visayas during summer."', null, [ACT.vocabularyGeography]),
    createContentItem('Mindanao', 'min-da-NAW', 'The southern island group: Davao, Cagayan de Oro, Zamboanga. Most ethnolinguistically diverse: Visayan, Maguindanao, Maranao, Tausug, indigenous Lumad peoples. ~25 million people. Davao is the largest city by area in the country.', 'word', 'Taga-Davao si Pangulong Duterte.', '"President Duterte was from Davao" — Mindanao political prominence.', null, [ACT.vocabularyGeography]),
    createContentItem('Maynila', 'may-NI-la', '"Manila". Capital. The historic center of the Philippines; Intramuros is the walled Spanish-era city. Population ~2 million (city proper); Metro Manila ~13 million.', 'word', 'Taga-Maynila ako.', '"I am from Manila."', null, [ACT.vocabularyGeography]),
    createContentItem('Quezon City', 'KE-son SI-ti', '"Quezon City (QC)". The largest city in Metro Manila by area and population (~3 million). UP Diliman is here. Named after President Manuel L. Quezon. Often the political-administrative center.', 'word', 'Sa Quezon City ang UP Diliman.', '"UP Diliman is in Quezon City."', null, [ACT.vocabularyGeography]),
    createContentItem('Cebu', 'se-BU', '"Cebu". The major city in the Visayas. Population ~1 million (city); ~4 million (metro). Cebuano is the regional language. Famous for the Sinulog festival, the cross of Magellan, and beach resorts.', 'word', 'Taga-Cebu siya, Cebuano ang lenggwahe niya.', '"He is from Cebu, his language is Cebuano."', null, [ACT.vocabularyGeography]),
    createContentItem('Davao', 'da-VAW', '"Davao". The largest city in Mindanao and by area in the country. Home to Mt. Apo (highest peak). President Rodrigo Duterte\'s base before national politics.', 'word', 'Maganda ang Davao, may Mt. Apo.', '"Davao is beautiful, has Mt. Apo."', null, [ACT.vocabularyGeography]),
    createContentItem('Iloilo', 'i-lo-I-lo', '"Iloilo". Major Visayan city, capital of Iloilo province. Hiligaynon (Ilonggo) is the regional language. Famous for the Dinagyang festival and historical churches (Miag-ao).', 'word', 'Taga-Iloilo si lola, kaya nagsasalita siya ng Hiligaynon.', '"Grandma is from Iloilo, that\'s why she speaks Hiligaynon."', null, [ACT.vocabularyGeography]),
    createContentItem('Baguio', 'BAG-yo', '"Baguio City". The summer capital, at 1,500m elevation in the Cordillera mountains. Cool climate (rare for the Philippines), pine forests, strawberry fields.', 'word', 'Pumunta kami sa Baguio para sa malamig na panahon.', '"We went to Baguio for the cool weather."', null, [ACT.vocabularyGeography]),
    createContentItem('isla', 'IS-la', '"Island". From Spanish "isla". The Philippines has 7,641 islands. Compound: kapuluan (archipelago, native).', 'word', 'May 7,641 isla sa Pilipinas.', 'Foundational geographical fact.', null, [ACT.vocabularyGeography]),
    createContentItem('dagat', 'DA-gat', '"Sea / ocean". Native word. The Philippines is surrounded by water — Pacific Ocean (east), South China Sea / West Philippine Sea (west), Sulu Sea (southwest).', 'word', 'Sa tabi ng dagat ang bahay namin.', '"Our house is by the sea."', null, [ACT.vocabularyGeography]),
    createContentItem('bundok', 'bun-DOK', '"Mountain". Native word. Famous: Mt. Mayon (perfect cone, Bicol), Mt. Apo (highest), Mt. Pinatubo (1991 eruption).', 'word', 'Maraming bundok sa Cordillera.', '"There are many mountains in the Cordillera."', null, [ACT.vocabularyGeography]),
    createContentItem('ilog', 'I-log', '"River". Native word. The Pasig River flows through Manila; the Cagayan River is the longest in Luzon.', 'word', 'Tinatawid ng tulay ang ilog.', '"The bridge crosses the river."', null, [ACT.vocabularyGeography]),
    createContentItem('tag-init', 'TAG-i-nit', '"Hot season / summer". Native compound: tag- (season prefix) + init (heat). Roughly March-May, peak heat 35-38°C. Schools have summer break April-May.', 'word', 'Tag-init na, mainit nang sobra.', '"It\'s summer now, very hot."', null, [ACT.vocabularyGeography]),
    createContentItem('tag-ulan', 'TAG-u-LAN', '"Rainy season". Tag- + ulan (rain). June-October. Includes typhoons (bagyo) — the Philippines is hit by ~20 typhoons per year.', 'word', 'Tuwing tag-ulan, marami ang bagyo.', '"During the rainy season, there are many typhoons."', null, [ACT.vocabularyGeography]),
    createContentItem('bagyo', 'BAG-yo', '"Typhoon". From Spanish "vahío" or possibly native. ~20 typhoons hit the Philippines yearly; major ones (Yolanda 2013, Odette 2021) cause massive destruction. Each is named alphabetically (Auring, Bising, Crising…).', 'word', 'Malakas ang bagyong Yolanda noong 2013.', '"Typhoon Yolanda (Haiyan) in 2013 was very strong."', null, [ACT.vocabularyGeography]),

    createContentItem('pamilya', 'pa-MIL-ya', 'Already foundational; in this unit, situate it as a CORE Filipino cultural value. The extended family — including ninongs/ninangs (godparents), titos/titas, lolo/lola — is the basic social unit. Decisions are family decisions.', 'word', 'Ang pamilya ang pinakamahalaga sa Filipino kultura.', '"Family is the most important in Filipino culture."', null, [ACT.vocabularyCulture]),
    createContentItem('bayanihan', 'ba-ya-NI-han', '"Community cooperative spirit / mutual aid". An iconic Filipino value. The classic image: villagers carrying a nipa hut on bamboo poles to relocate it together. Modern usage: neighbors helping neighbors, communities pooling efforts.', 'word', 'Ang bayanihan ay tradisyon ng tulungan.', '"Bayanihan is the tradition of mutual help."', [
      { target: 'origin: bayan (community)', note: 'plus -ihan suffix forming a noun of communal action' },
      { target: 'iconic image', note: 'neighbors carrying a house together — symbol of the value' },
      { target: 'modern usage', note: 'disaster response, community fund drives, neighborhood projects' },
    ], [ACT.vocabularyCulture]),
    createContentItem('OFW', 'OF-W (or O-FW spelled out)', '"Overseas Filipino Worker". ~10% of Filipinos work abroad (Saudi, UAE, HK, Singapore, USA, etc.) and send ~$36B/year in remittances. OFW culture shapes a generation of "barkada" raised partly by relatives. The Department of Migrant Workers handles their welfare.', 'word', 'OFW si tatay sa Saudi.', '"Dad is an OFW in Saudi (Arabia)" — typical family configuration.', null, [ACT.vocabularyCulture]),
    createContentItem('balikbayan', 'ba-LIK-ba-YAN', '"Returning Filipino (from abroad)". Bali- + bayan. Specifically: OFWs and migrant Filipinos returning to visit/retire. Famous for the "balikbayan box" — a large cardboard box stuffed with goods for family back home.', 'word', 'Dumating ang balikbayan na tito ko galing California.', '"My balikbayan uncle arrived from California."', null, [ACT.vocabularyCulture]),
    createContentItem('balikbayan box', 'ba-LIK-ba-YAN BOKS', 'A large cardboard box (typically 24" x 18" x 18") that OFWs and migrants stuff with goods (clothes, chocolates, electronics, canned goods) and ship back home. A near-universal Filipino-diaspora cultural artifact. Often arrives by sea cargo, takes 2-3 months.', 'word', 'May padalang balikbayan box galing tita sa Dubai.', '"There\'s a balikbayan box sent by tita from Dubai."', null, [ACT.vocabularyCulture]),
    createContentItem('fiesta', 'fy-ES-ta', '"Town festival". From Spanish. Every Catholic barangay/town has an annual patron-saint fiesta — major social event with food, parades, fireworks, beauty pageants. Famous: Sinulog (Cebu), Ati-Atihan (Aklan), Pahiyas (Lucban), Moriones (Marinduque).', 'word', 'Sa Mayo ang pista ng aming bayan.', '"Our town\'s fiesta is in May."', null, [ACT.vocabularyCulture]),
    createContentItem('utang na loob', 'U-tang na lo-OB', '"Debt of gratitude / inner debt". An UNTRANSLATABLE concept. Going beyond a transactional favor — a deep moral indebtedness that comes from being helped, requiring lifelong reciprocity. Underlies many Filipino social obligations.', 'word', 'Malaki ang utang na loob ko sa kanya.', '"I have a great debt of gratitude to her."', null, [ACT.vocabularyCulture]),
    createContentItem('hiyà', 'HI-yaʔ', '"Sense of propriety / shame / face". Another untranslatable concept. Drives the avoidance of public embarrassment for self and others. Related to the indirect communication style; refusing directly causes hiyà.', 'word', 'Nakaka-hiyà sa kanya.', '"It\'s embarrassing for her (out of consideration)."', null, [ACT.vocabularyCulture]),

    createContentItem('adobo', 'a-DO-bo', '"Adobo". The national dish — meat (usually chicken or pork) braised in vinegar, soy sauce, garlic, peppercorns, bay leaves. Hundreds of regional variations. The cooking method, not a specific recipe, is what defines adobo.', 'word', 'Ang paborito kong ulam ay adobo.', '"My favorite viand is adobo."', null, [ACT.vocabularyFood]),
    createContentItem('sinigang', 'si-ni-GANG', '"Sour soup". A tangy soup with tamarind (sampalok) base, fish/pork/shrimp, vegetables. Distinctly Filipino — the sour broth is unlike most Asian cuisines. Common variants: sinigang sa baboy (pork), sinigang na hipon (shrimp), sinigang sa miso.', 'word', 'Sa malamig na panahon, masarap ang mainit na sinigang.', '"In cool weather, hot sinigang is delicious."', null, [ACT.vocabularyFood]),
    createContentItem('lechon', 'le-CHON', '"Roast whole pig". From Spanish "lechón". The centerpiece of Filipino fiestas, especially in Cebu (Cebu lechon is famously the best). A whole pig roasted on a spit over coals — crispy skin (balat), juicy meat.', 'word', 'Walang fiesta na walang lechon.', '"No fiesta without lechon."', null, [ACT.vocabularyFood]),
    createContentItem('halo-halo', 'HA-lo-HA-lo', '"Mixed (dessert)". Reduplication of halo "mix". An iconic shaved-ice dessert: ube, leche flan, nata de coco, sweet beans, sago, jellies, sweet corn, sometimes ice cream. Served in a tall glass; you halo (mix) before eating.', 'word', 'Sa tag-init, paborito ko ang halo-halo.', '"In summer, my favorite is halo-halo."', null, [ACT.vocabularyFood]),
    createContentItem('lumpia', 'LUM-pya', '"Spring roll". From Chinese (Hokkien). Two main types: lumpiang shanghai (small, fried, ground meat) and lumpiang sariwa (fresh, larger, vegetable). Universal Filipino party food.', 'word', 'Sa birthday, palagi may lumpia.', '"At birthdays, there\'s always lumpia."', null, [ACT.vocabularyFood]),
    createContentItem('pancit', 'PAN-sit', '"Noodles". From Chinese "pian-i-sit" (something convenient). Various types: pancit canton, pancit bihon, pancit malabon, pancit palabok. Birthday food — long noodles for long life (Chinese influence).', 'word', 'Tuwing kaarawan, kumakain kami ng pancit.', '"On birthdays, we eat pancit" — for long life.', null, [ACT.vocabularyFood]),
    createContentItem('kare-kare', 'KA-re-KA-re', '"Peanut stew with oxtail and vegetables". Pampanga-region origin. Served with bagoong (fermented shrimp paste) on the side. Reduplication of kare (curry?) suggests rich color/flavor.', 'word', 'Masarap ang kare-kare na may bagoong.', '"Kare-kare with bagoong is delicious."', null, [ACT.vocabularyFood]),
    createContentItem('sisig', 'SI-sig', '"Sizzling chopped pork (or chicken/fish)". Pampanga origin. Pork face/ears chopped, seasoned, served on a sizzling plate with onions and a calamansi squeeze. Beer food. Anthony Bourdain made it globally famous.', 'word', 'Sa beer house, sisig ang ulam.', '"At the beer house, sisig is the viand."', null, [ACT.vocabularyFood]),
    createContentItem('tinola', 'ti-NO-la', '"Ginger chicken soup". Native chicken, ginger, papaya or sayote, chili leaves. Light, healthy, traditional. Common when someone is sick (palugaw alternative).', 'word', 'Pag may sipon, tinola ang inutusan.', '"When you have a cold, tinola is what\'s recommended."', null, [ACT.vocabularyFood]),
    createContentItem('balut', 'ba-LUT', '"Fertilized duck egg". A famous (and infamous) Filipino street food: a partially developed duck embryo (17-21 days) boiled and eaten with salt and vinegar. High in protein; sold by walking vendors at night ("Baluuut!"). Cebuanos sometimes call it "the Filipino courage food".', 'word', 'Sa gabi, may nagbebenta ng balut sa kanto.', '"At night, someone sells balut at the corner."', null, [ACT.vocabularyFood]),

    createContentItem('Taga-Cebu', 'TA-ga-se-BU', 'Origin word for Cebu. The person is a Cebuano (the ethnic-linguistic identity). Cebuano language has tens of millions of speakers — actually more first-language speakers than Tagalog. But Filipino (Tagalog-based) is the national language.', 'sentence', 'Taga-Cebu siya at Cebuano ang unang wika niya.', '"She is from Cebu and Cebuano is her first language" — distinguishes regional origin and language.', [
      { target: 'taga- + region', note: 'origin/native of (an area)' },
      { target: 'language vs identity', note: 'Cebuano is a language; taga-Cebu is an origin' },
      { target: 'Cebuano has more L1 speakers', note: '~20M+ first-language Cebuano speakers vs ~24M for Tagalog' },
    ], [ACT.grammarTaga]),
    createContentItem('Taga-Mindanao', 'TA-ga-min-da-NAW', 'Origin word for Mindanao. Encompasses many ethnic groups (Visayan, Maranao, Maguindanao, Tausug, Lumad indigenous peoples).', 'sentence', 'Taga-Mindanao ang mga magulang ko.', '"My parents are from Mindanao."', null, [ACT.grammarTaga]),
    createContentItem('Taga-probinsya', 'TA-ga-pro-BIN-sya', '"From the province / from outside Metro Manila". A common cultural identifier: "probinsya" = anywhere outside Metro Manila. Slight tension between Manila and probinsya cultural perspectives.', 'sentence', 'Taga-probinsya pero nagtatrabaho sa Manila.', '"From the province but works in Manila" — common modern Filipino biography.', null, [ACT.grammarTaga]),

    createContentItem('Mas malaki kaysa sa', 'MAS ma-la-KI KAY-sa sa', 'Comparative pattern: mas + adjective + kaysa + sa + comparison target. "X is more (adj) than Y". Variation: mas + adj + sa Y (drop kaysa).', 'sentence', 'Mas malaki ang Manila kaysa sa Cebu.', '"Manila is bigger than Cebu" — comparative; ang marks the subject (Manila).', null, [ACT.grammarComparison]),
    createContentItem('Pinakamalaki', 'pi-na-ka-ma-la-KI', 'Superlative: pinaka- + adjective = "the most (adj)". Pinakamalaki = "the biggest". Pinakamabuti = "the best".', 'sentence', 'Pinakamalaki ang Quezon City sa Metro Manila.', '"Quezon City is the largest in Metro Manila."', null, [ACT.grammarComparison]),
    createContentItem('Mas mahal sa', 'MAS ma-HAL sa', '"More expensive than". Mahal = expensive (and also "dear/beloved" — context distinguishes).', 'sentence', 'Mas mahal ang Maynila kaysa sa probinsya.', '"Manila is more expensive than the province" — typical observation.', null, [ACT.grammarComparison]),

    createContentItem('May 7,641 isla', 'may pi-tong-libo-anim-na-raan-apatnaput-isa na IS-la', 'The Philippines has 7,641 islands (per modern satellite count). Foundational existence statement using may.', 'sentence', 'May 7,641 isla ang Pilipinas.', 'Existential statement using may + count + noun.', null, [ACT.grammarMay]),
    createContentItem('Walang niyebe', 'wa-LANG ni-YE-be', '"No snow". The Philippines is tropical; there is no snow at any altitude (Baguio gets cool, never frosty).', 'sentence', 'Walang niyebe sa Pilipinas, mainit lagi.', '"No snow in the Philippines, always warm."', null, [ACT.grammarMay]),
    createContentItem('May dalawang panahon', 'may da-la-WANG pa-na-HON', '"Has two seasons". Tag-init (hot, March-May) and tag-ulan (rainy, June-November). No spring or fall, just hot vs wet.', 'sentence', 'May dalawang panahon lang: tag-init at tag-ulan.', '"There are only two seasons: dry/hot and rainy."', null, [ACT.grammarMay]),

    createContentItem('Pagbasa', 'pag-BA-sa', 'Read: Ang Pilipinas ay isang archipelago na may 7,641 isla, nahahati sa tatlong grupo: Luzon, Visayas, at Mindanao. Manila ang kabisera, pero Quezon City ang pinakamalaking lungsod sa Metro Manila. Mainit ang panahon — walang taglamig, may dalawang panahon lang: tag-init at tag-ulan. Sa tag-ulan, maraming bagyo. Ang adobo, sinigang, at lechon ang mga pinakapaboritong pagkain. Mahal ng Filipino ang pamilya, kaya ang bayanihan ay isang importanteng halaga. Marami ring OFW na nagpapadala ng pera sa pamilya.', 'sentence', 'The Philippines is an archipelago of 7,641 islands, divided into three groups: Luzon, Visayas, and Mindanao. Manila is the capital, but Quezon City is the largest city in Metro Manila. The weather is hot — no winter, only two seasons: hot and rainy. In the rainy season, there are many typhoons. Adobo, sinigang, and lechon are the most favorite foods. Filipinos love family, so bayanihan is an important value. There are also many OFWs sending money to their families.', 'Use of may, mas, pinaka-, mga, taga-, vocabulary set.', null, [ACT.reading]),

    createContentItem('Diyalogo', 'di-YA-lo-go', 'Dialogue: Foreign friend: "What is the Philippines like?" / Filipino: "Maganda. May 7,641 isla, kaya marami kang mapuntahan. Sa Maynila ang aming kabisera, pero Quezon City ang pinakamalaki. Mainit dito, walang niyebe. Ang adobo at sinigang ang dapat mong tikman." / Friend: "What about culture?" / Filipino: "Ang pamilya ang pinakamahalaga. Bayanihan kung magtutulungan. Tuwing fiesta, lechon ang ulam."', 'sentence', 'Friend: "What is the Philippines like?" / Filipino: "Beautiful. 7,641 islands, so much to visit. Manila is our capital, but QC is the biggest. It\'s hot here, no snow. Adobo and sinigang are what you must try." / Friend: "What about culture?" / Filipino: "Family is most important. Bayanihan when helping each other. At fiesta, lechon is the dish."', 'Mixed register: friendly peer-to-peer; comparative pinaka-; cultural concepts.', null, [ACT.listening]),

    createContentItem('Pagsulat', 'pag-SU-lat', 'Write 6-8 sentences introducing the Philippines to a foreign pen pal. Required: at least 3 geographical facts (using may), 2 cultural concepts, 2 food references, 1 comparative.', 'sentence', 'Modelo: "Ako po si [pangalan]. Galing po ako sa Pilipinas. May 7,641 isla ang aming bansa. Manila ang kabisera, pero Quezon City ang pinakamalaki. Mainit dito tuwing tag-init. Ang adobo at sinigang ang aming pinakapaboritong pagkain. Importante ang pamilya at bayanihan. Sa fiesta, lechon ang ulam."', 'Sample about 7 sentences using foundational vocabulary.', null, [ACT.writing]),

    createContentItem('OFW culture', 'OF-W cul-ture', 'About 10 million Filipinos work abroad (~10% of population). Top destinations: Saudi Arabia (2.5M), UAE (1M), Hong Kong (~250K), Singapore, Kuwait, Qatar, USA, Canada, Italy, Japan. They send ~$36 billion/year in remittances — about 10% of GDP. Many families have at least one OFW; children may be raised by grandparents or relatives. The Department of Migrant Workers (DMW) handles welfare.', 'word', 'Sa Pasko, umuuwi ang mga OFW.', '"At Christmas, OFWs come home" — peak homecoming season.', [
      { target: '~10M OFWs', note: '10% of the Filipino population works abroad' },
      { target: '$36B/year remittances', note: '~10% of GDP; sustains millions of families' },
      { target: 'balikbayan box', note: 'classic returning OFW artifact — large cardboard box of goods' },
      { target: 'Pasko peak homecoming', note: 'most OFWs return for Christmas' },
    ], [ACT.culture]),
    createContentItem('Fiesta culture', 'FYES-ta cul-ture', 'Every Catholic barangay/town has an annual patron-saint fiesta — a multi-day celebration with mass, parades, beauty contests, fireworks, communal meals (lechon). Famous: Sinulog (Cebu, Jan), Ati-Atihan (Aklan, Jan), Pahiyas (Lucban, May), Moriones (Marinduque, Holy Week), Higantes (Angono, Nov).', 'word', 'Maraming bisita tuwing fiesta — open house ang lahat.', '"Many visitors at fiesta — every house is open."', null, [ACT.culture]),

    createContentItem('Gawain', 'ga-WA-in', 'Task: Roleplay introducing the Philippines to a foreign friend. AI tutor plays a curious foreigner asking 4-5 questions about geography, food, culture, and OFW. 6+ turns. Required: at least 2 comparative (mas/pinaka-), 1 cultural concept explained, 1 dish described.', 'sentence', 'Modelo: "Galing po ako sa Pilipinas. May 7,641 isla, nahahati sa Luzon, Visayas, Mindanao. Pinakamalaki ang QC sa Metro Manila. Mas mainit dito kaysa sa Korea. Ang adobo ay aming national dish — manok o baboy sa suka, toyo, bawang. Mahalaga ang pamilya, kaya laging may bayanihan."', '"I\'m from the Philippines. 7,641 islands, divided into Luzon/Visayas/Mindanao. QC is biggest in Metro Manila. Hotter here than Korea. Adobo is our national dish — chicken or pork in vinegar, soy sauce, garlic. Family is important, so there\'s always bayanihan."', null, [ACT.task]),
  ],
};

module.exports = lesson;
