// Level 2 Unit 9 — 流行文化 (Pop Culture) — Mandarin Chinese
// Functions: discussing Chinese pop culture, internet celebrities, livestreaming,
// gen-Z slang, fandom intensity, and platform ecosystems with native-like
// sophistication. Built as a thematic Level 2 lesson, mirroring the Korean
// L2U9 source for topic only.
//
// All content is authored with Hanzi (target) + Pinyin (romanization) +
// rich English glosses (canonical source). The AI conversation tutor reads
// this curriculum and delivers it to each learner in their preferred native
// language at runtime — never assume a specific L1 in this file.
//
// Glosses follow the rich-gloss rule (AGENTS.md → "Gloss Richness"):
// every nativeText, exampleNative, and breakdown.native carries register,
// usage context, or contrast info — not a bare definition.

const createContentItem = (
  target,
  pinyin,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization: pinyin,
  nativeText: note,
  pronunciation: pinyin,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  // Legacy keys for UI fallback — same convention as level1Unit01Greetings:
  // the "korean" slot holds the target text, the "english" slot holds the note.
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'zh-l2u9-orientation',
  pronunciation: 'zh-l2u9-pronunciation',
  vocabularyCore: 'zh-l2u9-vocab-core',
  vocabularyPlatforms: 'zh-l2u9-vocab-platforms',
  vocabularySlang: 'zh-l2u9-vocab-slang',
  grammarHuoLe: 'zh-l2u9-grammar-huo-le',
  grammarYiyang: 'zh-l2u9-grammar-yiyang',
  grammarJihu: 'zh-l2u9-grammar-jihu',
  reading: 'zh-l2u9-reading',
  listening: 'zh-l2u9-listening',
  culture: 'zh-l2u9-culture',
  task: 'zh-l2u9-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Discuss Chinese pop culture, internet celebrities, and livestreaming with the right vocabulary instead of falling back on English loanwords.',
      'Use three intermediate patterns: V + 火/红 + 了 (became viral), A 跟/和 B 一样 (A is the same as B), 几乎 / 差不多 (almost / about the same).',
      'Explain one Chinese internet trend to a foreign classmate at Tsinghua University in a single short paragraph — what it is, why it is popular, and one slang term they should learn.',
    ],
    task: 'Picture a coffee break at Tsinghua: a classmate from abroad asks why 抖音 in China is different from TikTok overseas. By the end of this lesson you can explain a trend, give one slang word, and back it up with one comparison sentence.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in pop-culture vocabulary',
    goals: [
      'Pronounce the high-frequency pair 偶像 (ǒuxiàng, "idol") and 网红 (wǎnghóng, "internet celebrity") with clean third+fourth and third+second tone contours — both are buried inside almost every sentence in this unit.',
      'Distinguish 直播 (zhíbō, "livestream") from 主播 (zhǔbō, "livestream host") — same final, different tone on the first syllable: rising vs dip-rise.',
      'Read the English-letter slang yyds out loud as four English letters "Y-Y-D-S", not as a Pinyin syllable — modern Chinese internet language code-mixes letters, numbers (666, 233), and Hanzi freely.',
    ],
    task: 'Read each pronunciation card aloud and label the trap: which syllable carries the tone confusion, or whether the item is read as Hanzi vs as English letters.',
  },
  {
    id: ACT.vocabularyCore,
    section: 'Vocabulary I',
    title: 'Core pop-culture and social-media vocabulary',
    goals: [
      'Memorize 20 core pop-culture terms covering idols, fans, livestreams, virality, trending lists, and public failure (翻车, 塌房).',
      'Distinguish 偶像 (a sincere/aspirational idol) from 明星 (any celebrity) and 网红 (specifically internet-born), and know when each is the right word.',
    ],
    task: 'Read each item aloud, then group the 20 words into four buckets: people, actions, status changes, and abstract trends.',
  },
  {
    id: ACT.vocabularyPlatforms,
    section: 'Vocabulary II',
    title: 'Major Chinese platforms',
    goals: [
      'Recognize the six dominant Chinese platforms (微博, 抖音, 小红书, B站, 知乎, 快手) and know what kind of content each one hosts — getting the platform wrong in a sentence sounds as off as confusing Reddit with Pinterest in English.',
      'Use the platform names naturally with action verbs: 刷抖音 (scroll Douyin), 发微博 (post on Weibo), 上B站看视频 (go on Bilibili to watch videos).',
    ],
    task: 'For each of the six platforms, name one type of content it is known for and one verb you would pair with it.',
  },
  {
    id: ACT.vocabularySlang,
    section: 'Vocabulary III',
    title: 'Gen-Z slang and acronyms',
    goals: [
      'Use eight high-frequency gen-Z slang items: yyds, 绝绝子, 破防, 太卷了, 摆烂, 整顿, 内卷, 躺平 — knowing what each one signals about the speaker matters more than a literal translation.',
      'Match each slang item to the emotional register it carries (praise, exhaustion, mock-defeat, sarcasm) so you do not use a praise term in a complaint context.',
    ],
    task: 'For each slang item, give the rough meaning, the register, and one situation where it would be the natural reaction.',
  },
  {
    id: ACT.grammarHuoLe,
    section: 'Grammar I',
    title: 'V + 火/红 + 了 — became viral / became famous',
    goals: [
      'Use the resultative construction V + 火了 or V + 红了 to say something became popular as a result of an action: 这首歌唱火了 ("this song was sung into virality").',
      'Distinguish 火了 (became viral / hot — short, intense surge) from 红了 (became famous / popular — broader, more lasting). Both are extremely common; choosing the right one signals real fluency.',
    ],
    task: 'Write three sentences using V + 火了 / 红了 about a song, a video, and a person, then convert one to a question with 怎么 (how) to ask why it went viral.',
  },
  {
    id: ACT.grammarYiyang,
    section: 'Grammar II',
    title: 'A 跟/和 B 一样 — A is the same as B',
    goals: [
      'Compare two trends, platforms, or people with the A 跟 B 一样 + (adjective) pattern: 抖音跟TikTok一样火 ("Douyin is just as viral as TikTok").',
      'Negate with 不一样 placed at the end: A 跟 B 不一样 ("A is not the same as B") — useful for explaining why Chinese platforms differ from Western counterparts.',
    ],
    task: 'Write three comparison sentences using A 跟 B 一样 (or 不一样) about platforms (抖音 vs TikTok), idols (中国偶像 vs 韩国偶像), and slang (yyds vs GOAT).',
  },
  {
    id: ACT.grammarJihu,
    section: 'Grammar III',
    title: '几乎 / 差不多 — almost / about the same',
    goals: [
      'Use 几乎 (jīhū, "almost / nearly") for near-universal generalizations: 几乎每个学生都刷抖音 ("almost every student scrolls Douyin").',
      'Use 差不多 (chàbuduō, "about the same / roughly") for approximate equivalence: 微博跟Twitter差不多 ("Weibo is roughly the same as Twitter"). Know that 几乎 leans toward "nearly 100%" while 差不多 leans toward "close enough".',
    ],
    task: 'Write two generalizations using 几乎 and two approximations using 差不多, all about Chinese internet trends.',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: 'Read a trend explainer',
    goals: [
      'Read a short Hanzi paragraph explaining one Chinese internet trend (e.g., 网红打卡 or 直播带货) with correct tones and natural rhythm.',
      'Summarize the trend in your own words in two short sentences, using at least one pattern from this lesson.',
    ],
    task: 'Read the explainer aloud once, then close the book and re-explain the trend in your own Mandarin to the AI tutor.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: 'A conversation about a viral video',
    goals: [
      'Follow a four-turn conversation between two Tsinghua students about a video that just went viral on 抖音, catching the slang and the V+火了 construction in context.',
      'Reproduce the conversation with your own example: a different video, a different platform, a different slang word.',
    ],
    task: 'Read the dialogue along with the AI tutor, then perform it again with a real viral clip you actually know.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: 'Chinese fandom hyper-intensity and platform regulation',
    goals: [
      'Understand the scale of Chinese fandom culture (粉圈, 应援, 集资) and why it has drawn government attention — large fandoms in China crowdfund birthday celebrations, buy out billboards, and stream-farm chart positions at a scale Western platforms rarely match.',
      'Know the two major regulatory moments: the 2021 选秀 talent-show shutdown (banning idol-survival shows after the Qing Chun You Ni milk-dumping scandal) and the 限娱令 series of entertainment-industry restrictions on celebrity earnings, fan-club organization, and minor performers.',
      'Distinguish the Chinese 抖音 algorithm experience from Western TikTok — same parent company, different content ecosystem and stricter content moderation — and recognize 国风 (guófēng, traditional-modern aesthetic) as a major homegrown trend.',
    ],
    task: 'Pick one of the three culture points (粉圈 / 限娱令 / 国风) and explain it in two Mandarin sentences to a foreign classmate.',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'Explain one Chinese trend to a Tsinghua classmate',
    goals: [
      'Combine vocabulary, three grammar patterns, and at least one slang item into one continuous explanation of a Chinese internet trend a foreigner would not immediately get.',
      'Cover three beats: what the trend is (definition), why it is popular (one comparison or generalization), and one slang term the classmate should learn (with a usage example).',
    ],
    task: 'Roleplay a coffee break at Tsinghua with the AI tutor playing a foreign classmate; explain one Chinese trend in a 6-turn exchange.',
  },
];

const lesson = {
  title: 'Level 2 · Unit 9: 流行文化 — Chinese Pop Culture, Internet Celebrities, and Gen-Z Slang',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'zh',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'explain-trend', label: 'Explaining a trend', goal: 'Define one Chinese internet trend in two short Mandarin sentences so a foreign classmate gets why it matters.' },
    { id: 'compare-platforms', label: 'Comparing platforms', goal: 'Use A 跟/和 B 一样 (or 不一样) to compare a Chinese platform with its Western counterpart in one sentence.' },
    { id: 'teach-slang', label: 'Teaching one slang term', goal: 'Pick one gen-Z slang item (yyds, 绝绝子, 躺平, 内卷, etc.), give its register, and demonstrate it in one natural-sounding example.' },
    { id: 'react-to-viral', label: 'Reacting to a viral clip', goal: 'Respond to news that a video just went viral using V + 火/红 + 了 plus one slang reaction word.' },
  ],
  relatedPools: ['topic-culture', 'topic-internet'],
  content: [
    // ────────────────────────────────────────────────────────────────────
    // Activity 1 — Orientation
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '本课目标',
      'běn kè mùbiāo',
      'By the end of this lesson, you can talk about Chinese pop culture, internet celebrities, viral videos, and gen-Z slang without falling back on English borrowings — and you can explain one specifically Chinese internet trend to a foreign classmate in clean, sentence-level Mandarin.',
      'word',
      'Functions: 介绍潮流 jièshào cháoliú (introduce a trend) · 比较平台 bǐjiào píngtái (compare platforms) · 用网络流行语 yòng wǎngluò liúxíngyǔ (use internet slang) · 描述火爆 miáoshù huǒbào (describe virality).',
      'These four micro-skills cover roughly 80 percent of casual conversation about pop culture among Chinese university students today.',
      null,
      [ACT.orientation],
    ),
    createContentItem(
      '真实场景',
      'zhēnshí chǎngjǐng',
      'You are taking a coffee break at Tsinghua University and a classmate from abroad asks: "Why is Chinese 抖音 so different from the TikTok I use at home?" You need a real answer that names the difference, gives one example, and teaches one slang word — all in Mandarin.',
      'word',
      '外国同学: "为什么中国的抖音跟我们的TikTok不一样啊?"\n你: "其实差不多，但中国版的内容更卷，几乎每个网红都在直播带货……"',
      'A typical Tsinghua hallway exchange — the foreign student frames the question in English-influenced phrasing; you respond with native pop-culture vocabulary and one of this unit\'s grammar patterns.',
      [
        { target: '抖音跟TikTok不一样', note: 'A 跟 B 不一样 pattern — comparison-negation from Grammar II' },
        { target: '差不多', note: '"about the same" — Grammar III approximation marker' },
        { target: '几乎每个网红', note: '"almost every internet celebrity" — Grammar III generalization' },
        { target: '直播带货', note: '"livestream e-commerce" — the single most distinctive Chinese internet trend, deserves its own slot in the explainer' },
      ],
      [ACT.orientation],
    ),
    createContentItem(
      '三大支柱',
      'sān dà zhīzhù',
      'Modern Chinese pop culture rests on three pillars that this lesson will equip you to talk about. (1) Platforms (抖音, 小红书, B站, 微博) define what content even exists. (2) People (偶像, 明星, 网红, 粉丝) are the human side. (3) Language (yyds, 绝绝子, 躺平, 内卷) signals belonging and tone — using the wrong term marks you instantly as an outsider.',
      'word',
      '平台 (platforms) + 人物 (people) + 语言 (language) = 流行文化的全貌',
      'Get all three pillars right in one sentence and you sound like a Tsinghua student talking about pop culture; miss any one and the sentence sounds textbook-stiff.',
      null,
      [ACT.orientation],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 2 — Pronunciation
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '偶像',
      'ǒuxiàng (3+4)',
      'Third tone + fourth tone. Apply the third-tone shortening: in fluent speech the first 偶 is just a low-pitch start, not a full dip-and-rise. The fourth-tone 像 then falls sharply. Mispronouncing as 4+4 (òuxiàng) or 1+4 (ōuxiàng) yields a non-word.',
      'word',
      '我的偶像是周杰伦。Wǒ de ǒuxiàng shì Zhōu Jiélún. ("My idol is Jay Chou.")',
      'Heard in nearly every fan-related sentence; the tone pair is also the same as 老板 (lǎobǎn, "boss") — drilling one drills the other.',
      [
        { target: '偶 (ǒu, 3rd)', note: 'shortened low-pitch in connected speech; full dip-rise only in isolation' },
        { target: '像 (xiàng, 4th)', note: 'sharp fall; the syllable that carries the stress of the word' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      '网红',
      'wǎnghóng (3+2)',
      'Third tone + second tone. The third-tone 网 stays at a low pitch; then the second-tone 红 rises clearly to high. This is the most common tone pair in pop-culture vocabulary — almost every "internet X" compound starts with this rhythm.',
      'word',
      '她是B站上的大网红。Tā shì B-zhàn shàng de dà wǎnghóng. ("She is a big internet celebrity on Bilibili.")',
      'A bare 网红 means any internet-born celebrity; adding 大 (dà, "big") signals top-tier reach.',
      [
        { target: '网 (wǎng, 3rd)', note: 'low-pitch start; 网 = "net", the building block of dozens of internet compounds (网友, 网络, 网店)' },
        { target: '红 (hóng, 2nd)', note: 'clear rise; literal "red", figuratively "famous / popular"' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      '直播 vs 主播',
      'zhíbō (2+1) vs zhǔbō (3+1)',
      'Same final 播, different first syllable. 直播 (zhíbō, "livestream", second + first) is the activity; 主播 (zhǔbō, "host of a livestream", third + first) is the person. Mixing them up turns "I love watching livestreams" into "I love watching hosts" — close, but not quite.',
      'word',
      '我每天看直播。 vs 那个主播很有名。 ("I watch livestreams every day." vs "That host is famous.")',
      'The minimal pair is high-payoff: drilling these two tones together solves a category of confusions across the unit.',
      [
        { target: '直 (zhí, 2nd) — rise', note: '"direct"; the rising tone signals the action/event sense' },
        { target: '主 (zhǔ, 3rd) — dip', note: '"main / host"; the third tone signals the human/role sense' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      '热搜',
      'rèsōu (4+1)',
      'Fourth tone + first tone. The 4+1 contour drops then holds high — sharp fall on 热 (hot), then steady high on 搜 (search). The whole word means "trending hot search" and is the headline format for what is currently viral in China.',
      'word',
      '上热搜了! Shàng rèsōu le! ("It made the trending list!")',
      'A complete one-clause reaction sentence — short and very high-frequency on social media.',
      [
        { target: '热 (rè, 4th)', note: 'sharp falling; literal "hot", figuratively "trending"' },
        { target: '搜 (sōu, 1st)', note: 'high level; from 搜索 (sōusuǒ, "to search")' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      'yyds — 读字母',
      'Y-Y-D-S (English letter reading)',
      'Read each letter individually as if speaking English — "Y-Y-D-S". The full Pinyin source is 永远的神 (yǒngyuǎn de shén, "eternal god"), but in conversation the abbreviation is spoken letter-by-letter, not as Pinyin. This code-mixing of English letters into spoken Mandarin is a defining feature of post-2020 gen-Z speech.',
      'word',
      '周杰伦yyds! Zhōu Jiélún Y-Y-D-S! ("Jay Chou is the GOAT!")',
      'Same pattern applies to other letter slang: cpdd (求处对象, "looking for a date"), nsdd (你说得对, "you are right"). All read as English letters in flow.',
      [
        { target: 'yyds = 永远的神', note: 'literal "eternal god"; functional equivalent of English "GOAT" (greatest of all time)' },
        { target: 'read as letters, not Pinyin', note: 'spoken "Y-Y-D-S" — never pronounced as a Hanzi sequence in speech' },
      ],
      [ACT.pronunciation],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 3 — Vocabulary I: Core pop-culture terms
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '流行文化',
      'liúxíng wénhuà',
      'Pop culture as an abstract noun — the umbrella term covering music, drama, internet celebrities, slang, and trends. Used in essays, news headlines, and academic discussion; in casual speech, the unmarked 流行 ("popular") often appears alone.',
      'word',
      '中国流行文化在海外越来越火。',
      '"Chinese pop culture is getting more and more popular overseas." — note the resultative 越来越 ("more and more") + the slang-friendly 火 ("hot / viral").',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '偶像',
      'ǒuxiàng',
      'An idol in the sincere, aspirational sense — typically a singer, actor, or athlete the speaker actively looks up to. Carries an emotional warmth that 明星 (any celebrity) does not; saying "我的偶像是…" signals personal devotion, not just recognition.',
      'word',
      '我从小的偶像就是李宇春。',
      '"My idol since childhood has been Li Yuchun." — note 从小 ("since I was little") + the equational 是, the standard self-introduction shape for fandom.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '明星',
      'míngxīng',
      'A celebrity — any famous person in entertainment, sports, or business. Neutral and unmarked, the way English "celebrity" or "star" is. Use when 偶像 (too devotional) and 网红 (specifically internet-born) would both be wrong.',
      'word',
      '那家餐厅经常有明星去吃饭。',
      '"That restaurant often has celebrities eating there." — paparazzi-adjacent usage, no emotional warmth attached.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '粉丝',
      'fěnsī',
      'Fans — a phonetic loan from English "fans" that homophones with 粉丝 ("rice noodles"), which is the source of constant fandom puns. A single fan is 一个粉丝 or 一名粉丝; for a fandom collectively, 粉丝群 or 粉圈 (see culture note).',
      'word',
      '她的粉丝特别多，几乎每个学生都关注她。',
      '"She has a lot of fans — almost every student follows her." — combines 粉丝 with the 几乎 generalization pattern from Grammar III.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '网红',
      'wǎnghóng',
      'Literally "internet red / famous" — a celebrity whose fame originated and lives primarily online. Distinct from 明星 (traditional entertainment industry); a 网红 can become a 明星 by signing with an agency, but the reverse direction is rare. Slightly less prestigious than 明星 in formal contexts.',
      'word',
      '他从直播起家，现在是大网红。',
      '"He started out livestreaming and is now a major internet celebrity." — 从…起家 ("to start out from…") is a high-frequency biographical pattern.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '网红打卡',
      'wǎnghóng dǎkǎ',
      'Going to an "Instagrammable" location — literally "internet-red punch-card" — specifically to take photos and post them. A defining millennial/gen-Z behavior in Chinese urban culture: cafés, museums, even highway rest stops are designed for 打卡 traffic.',
      'word',
      '这家咖啡店是上海最火的网红打卡地。',
      '"This café is the hottest IG-spot in Shanghai." — 打卡地 ("punch-in spot") is the noun form; 去打卡 is the verb form.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '直播',
      'zhíbō',
      'Livestream — a live video broadcast, typically interactive with real-time comments. In China the dominant context is 直播带货 ("livestream e-commerce"), where streamers sell products in real time at scales no Western livestreamer reaches. Verb (我在直播) or noun (看直播) depending on context.',
      'word',
      '李佳琦的直播一晚上能卖几个亿。',
      '"Li Jiaqi\'s livestream can sell hundreds of millions in one night." — 几个亿 (jǐ gè yì, "several hundred million") is the casual large-number form.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '短视频',
      'duǎn shìpín',
      'Short video — the format that defines 抖音 and 快手. Typically 15 seconds to one minute; the algorithm-served vertical-scroll experience that has reshaped Chinese internet attention. Distinct from 长视频 (B站/优酷, longer-form content).',
      'word',
      '我每天刷短视频刷两个小时，太上瘾了。',
      '"I scroll short videos for two hours every day, it is too addictive." — 刷 ("brush / scroll") is the dedicated verb for algorithmic feeds.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '关注',
      'guānzhù',
      'To follow (on social media) — also the noun "follow / attention". In a social-media context, 关注他 means "follow him"; in news context, 关注这件事 means "pay attention to this matter". Same verb covers both registers; the Western app-equivalent is "follow".',
      'word',
      '我关注了一千多个博主。',
      '"I follow over a thousand bloggers." — 博主 (bózhǔ, "blogger / content creator") pairs naturally with 关注.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '点赞',
      'diǎnzàn',
      'To like (a post / video / comment) — literally "point-praise". The action is 点赞 (verb), the count is 赞数 (noun). The thumb-up reaction across nearly every Chinese platform; a video with 一百万赞 (one million likes) is doing well.',
      'word',
      '帮我点个赞呗! Bāng wǒ diǎn gè zàn bei!',
      '"Like my post for me, would you?" — the sentence-final 呗 (bei) softens it into a casual ask between friends.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '转发',
      'zhuǎnfā',
      'To repost / share — forwarding a post to your own followers. 转 = turn, 发 = send. On 微博 a viral post is measured by 转发量 (repost count); 一条微博 with millions of 转发 is a national event.',
      'word',
      '这条微博转发量过了一百万。',
      '"This Weibo post has been reshared over a million times." — 过 here means "exceeded", a high-frequency quantifying verb.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '评论',
      'pínglùn',
      'Comment / to comment — both noun and verb. Comment sections in China are extremely high-engagement: a top comment (热评 rèpíng) can shape how the rest of the audience reads the original post. 评论区 (the comment section) is itself a content space.',
      'word',
      '评论区比视频还好看!',
      '"The comment section is even better than the video!" — a stock reaction phrase praising a lively comment thread.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '屏蔽',
      'píngbì',
      'To block / mute — hide a user\'s posts from your feed without notifying them. Softer than 拉黑 (blacklist): 屏蔽 just hides the content, the relationship stays nominally intact. Commonly applied to relatives whose pings you do not want.',
      'word',
      '我把我妈屏蔽了，朋友圈终于清净了。',
      '"I muted my mom and now my WeChat Moments is finally quiet." — 朋友圈 (péngyouquān) is WeChat\'s social feed.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '拉黑',
      'lāhēi',
      'To blacklist — a hard block that prevents the other user from messaging or seeing your content. Stronger than 屏蔽; 拉黑 is a relationship ender. The verb is 拉 ("pull") + 黑 ("black / blacklist"), with 黑名单 (hēi míngdān) as the noun form.',
      'word',
      '前男友我早就拉黑了。',
      '"I blacklisted my ex a long time ago." — 早就 ("already long ago") adds the closure tone that fits the action.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '火',
      'huǒ',
      'Viral / hot / popular — adjective with a short-burst intensity. Used for songs, videos, trends, restaurants, and people that have surged in popularity recently. The verb form V + 火了 is treated in Grammar I; the bare adjective fits patterns like 最近很火 ("very hot recently").',
      'word',
      '这首歌最近特别火。',
      '"This song is super hot recently." — 特别 ("especially") + 火 is a textbook intensifier+adjective shape.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '热搜',
      'rèsōu',
      'Trending search list — specifically the Weibo top-search ranking, the single most influential trending board in the Chinese internet. Making 热搜 means a topic has crossed from niche to mass attention; politicians, brands, and idols actively manage their relationship with 热搜.',
      'word',
      '昨天那个新闻直接上了热搜第一。',
      '"That news story went straight to number one on the trending list yesterday." — 直接 ("directly") + 上 ("ascend") is the verb cluster of choice.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '上热搜',
      'shàng rèsōu',
      'To hit the trending list — the verb form of the previous item. The topic that 上热搜 is now a national conversation; brands pay for placement, fan armies organize to push their idol up the rankings. The opposite is 下热搜 ("fall off the trending list").',
      'word',
      '我们家偶像今天又上热搜了!',
      '"Our idol made the trending list again today!" — 我们家 ("our house\'s") is fan-group possessive slang for their favored celebrity.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '翻车',
      'fānchē',
      'To fail publicly / mess up on camera — literally "the car flipped over". Originally describes a crashed e-commerce livestream (product malfunctions, host says something stupid); now generalized to any public failure that goes viral for the wrong reasons. Less serious than 塌房.',
      'word',
      '那个主播昨天直播翻车了，被全网嘲笑。',
      '"That livestreamer crashed and burned on stream yesterday — the whole internet is mocking him." — 全网 (quánwǎng, "the whole internet") is the standard scale-of-mockery word.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '塌房',
      'tāfáng',
      'A celebrity\'s public moral collapse — literally "the house caved in", with the 偶像 (idol) being the house and the fans being the inhabitants left homeless. Scandals (cheating, tax evasion, criminal charges) cause 塌房; the term carries the emotional devastation of fans who feel personally betrayed.',
      'word',
      '我的偶像塌房了，粉籍我退了。',
      '"My idol fell from grace — I quit my fan-club membership." — 粉籍 (fěnjí, "fan-club registration") is itself fandom-specific vocabulary.',
      null,
      [ACT.vocabularyCore],
    ),
    createContentItem(
      '流量',
      'liúliàng',
      'Traffic / popularity / engagement — literally "flow quantity". In a media context, refers to the audience attention a celebrity or post can attract. 流量明星 (a "traffic star") is a celebrity whose value rests on raw popularity rather than craft — slightly pejorative when used to dismiss someone\'s acting or singing ability.',
      'word',
      '他没什么作品，全靠流量。',
      '"He has no real work to his name — he runs entirely on hype." — 全靠 ("entirely depending on") is the standard dismissal cluster.',
      null,
      [ACT.vocabularyCore],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 4 — Vocabulary II: Platforms
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '微博',
      'Wēibó',
      'Weibo — the dominant Chinese microblogging platform, broadly equivalent to Twitter/X in function but with longer posts and a much heavier celebrity-fandom ecosystem. The home of 热搜; if something is trending nationally, it is trending on 微博 first. Verb: 发微博 (post on Weibo).',
      'word',
      '她发了一条微博，立刻上了热搜。',
      '"She posted on Weibo and instantly made the trending list." — note the measure word 条 (tiáo) for posts, and the 立刻 ("instantly") + V+了 sequence.',
      null,
      [ACT.vocabularyPlatforms],
    ),
    createContentItem(
      '抖音',
      'Dǒuyīn',
      'Douyin — the Chinese version of TikTok (both owned by ByteDance, but with separate content ecosystems and stricter moderation in China). The dominant short-video app for Mainland users. Verb: 刷抖音 (scroll Douyin).',
      'word',
      '我下班回家就开始刷抖音，根本停不下来。',
      '"I get home from work and start scrolling Douyin — I literally cannot stop." — 根本 ("at all / fundamentally") + negation is a standard intensifier.',
      null,
      [ACT.vocabularyPlatforms],
    ),
    createContentItem(
      '小红书',
      'Xiǎohóngshū',
      'Xiaohongshu / RedNote / Little Red Book — a lifestyle, fashion, beauty, and travel platform combining Instagram-style photo posts with Pinterest-style discovery and Amazon-style commerce. Skews female and young-professional; the go-to platform for 网红打卡 recommendations and product research.',
      'word',
      '我去之前先在小红书上搜了一下攻略。',
      '"Before going I first looked up a guide on Xiaohongshu." — 攻略 (gōnglüè, "strategy guide") is the universal word for any consumer how-to post.',
      null,
      [ACT.vocabularyPlatforms],
    ),
    createContentItem(
      'B站',
      'Bī-zhàn',
      'Bilibili — the Chinese answer to YouTube, born from anime/manga/gaming subculture and now broadly a long-video platform with a famously chatty comment scroll (弹幕 dànmù, on-screen scrolling comments). Beloved by gen-Z; younger and more subculture-coded than 微博.',
      'word',
      '这个视频在B站有几百万播放量。',
      '"This video has several million views on Bilibili." — 播放量 (bōfàng liàng, "play count") is the YouTube-equivalent view-count metric.',
      null,
      [ACT.vocabularyPlatforms],
    ),
    createContentItem(
      '知乎',
      'Zhīhū',
      'Zhihu — a Chinese Q&A platform broadly equivalent to Quora but with notably longer, more essay-style answers. Skews educated and professional; the platform where people ask "如何看待…?" ("how should one view…?") and receive 3,000-character takes.',
      'word',
      '我在知乎上看了一个很长的回答，特别有道理。',
      '"I read a very long answer on Zhihu — it made a lot of sense." — 有道理 (yǒu dàoli, "makes sense / has logic") is the standard endorsement.',
      null,
      [ACT.vocabularyPlatforms],
    ),
    createContentItem(
      '快手',
      'Kuàishǒu',
      'Kuaishou — a short-video platform older than 抖音, traditionally stronger in lower-tier cities and rural China. The class divide between 快手 (working-class, regional) and 抖音 (urban, polished) is itself a meme inside Chinese internet culture, though the gap has narrowed.',
      'word',
      '我爸只刷快手，不刷抖音。',
      '"My dad only scrolls Kuaishou, not Douyin." — the generational and regional split captured in one sentence.',
      null,
      [ACT.vocabularyPlatforms],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 5 — Vocabulary III: Gen-Z slang
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      'yyds',
      'Y-Y-D-S (= 永远的神)',
      'The Chinese GOAT (greatest of all time). Initialism of 永远的神 ("eternal god"); used as a one-word verdict of supreme praise for a singer, athlete, dish, anything. Spoken as four English letters, not as Pinyin. Heavily overused — using it constantly marks you as either earnestly fan-ish or mildly ironic.',
      'word',
      '周杰伦yyds! 这首歌十年了还是好听。',
      '"Jay Chou is the GOAT — this song is ten years old and still slaps." — 还是好听 ("still nice to listen to") completes the verdict-then-justification rhythm.',
      null,
      [ACT.vocabularySlang],
    ),
    createContentItem(
      '绝绝子',
      'juéjuézi',
      'Absolutely amazing / mind-blowing. Doubled 绝 ("supreme / extreme") + the gen-Z suffix 子. Spread from Xiaohongshu beauty reviews into general use around 2021. Has the same overuse problem as English "literally" — beloved by enthusiasts, eye-roll-inducing for skeptics.',
      'word',
      '这个口红颜色绝绝子!',
      '"This lipstick color is GORGEOUS!" — Xiaohongshu-style product reaction in its natural habitat.',
      null,
      [ACT.vocabularySlang],
    ),
    createContentItem(
      '破防',
      'pòfáng',
      'Emotionally moved to the point of breaking down — literally "defenses breached", originally a video-game term for losing your shield. Now describes any moment when an emotional scene, song, or memory cuts through your composure. Heavier than English "hit me hard"; closer to "tears just started".',
      'word',
      '看到那段视频我直接破防了。',
      '"Watching that clip just broke me." — 直接 ("just / outright") emphasizes the immediate involuntary reaction.',
      null,
      [ACT.vocabularySlang],
    ),
    createContentItem(
      '太卷了',
      'tài juǎn le',
      'Too competitive / hyper-grindy. Adjectival form of 内卷 (involution — see next entry). Describes a workplace, school, or scene where everyone is putting in extra hours / effort just to keep up with everyone else putting in extra hours. The universal complaint of Chinese university students about Tsinghua, Peking, and the job market.',
      'word',
      '清华真的太卷了，每个人都熬夜学习。',
      '"Tsinghua is genuinely too cutthroat — everyone pulls all-nighters studying." — note 真的 ("truly") + 太…了 (too…) intensifier pair.',
      null,
      [ACT.vocabularySlang],
    ),
    createContentItem(
      '摆烂',
      'bǎilàn',
      'To give up trying / let things rot — literally "arrange the rotten". The active counterpart of 躺平: instead of just lying flat in passive resistance, the 摆烂 person actively performs failure (handing in trash work, missing deadlines on purpose) to signal that the game is not worth playing. Gen-Z\'s favorite mock-defeatist verb.',
      'word',
      '今天作业太多，我决定摆烂了。',
      '"Too much homework today — I have decided to just give up." — 决定 ("decide to") frames it as an active stance, which is the joke.',
      null,
      [ACT.vocabularySlang],
    ),
    createContentItem(
      '整顿',
      'zhěngdùn',
      'To set straight / clean up / rectify — originally a formal verb used by the government for regulating an industry. In gen-Z slang, repurposed for the meme 整顿职场 ("setting the workplace straight"), where young employees refuse traditional overwork norms and push back on bad management. Carries a mock-heroic tone.',
      'word',
      '我们00后是来整顿职场的!',
      '"We post-2000 kids are here to set the workplace straight!" — 00后 (líng-líng-hòu, "the post-2000 generation") is the gen-Z self-label.',
      null,
      [ACT.vocabularySlang],
    ),
    createContentItem(
      '内卷',
      'nèijuǎn',
      'Involution — escalating effort with no proportional reward. Originally an anthropological term (from Clifford Geertz on Indonesian agriculture); now the buzzword of choice for diagnosing modern Chinese life. Education, real estate, white-collar work — all 内卷. Adjectival form 卷 (juǎn) means "in a state of involution".',
      'word',
      '现在的教育太内卷了，孩子从小就开始补课。',
      '"Education these days is too involuted — kids start cram school as toddlers." — 从小 ("from small / since childhood") + V 就 ("then V") is the standard escalation shape.',
      null,
      [ACT.vocabularySlang],
    ),
    createContentItem(
      '躺平',
      'tǎngpíng',
      'Lying flat — a passive resistance stance: refuse to compete, refuse to overwork, refuse to chase 996 schedules, owning property, or marriage. The opposite of 内卷 — gave the world a one-word meme for gen-Z opt-out in 2021. Real ideological force, not just a joke.',
      'word',
      '工作太卷了，我决定躺平。',
      '"Work is too involuted — I have decided to lie flat." — declarative-of-resignation paired with 决定 ("decide to") makes it sound like a considered position, which is the political joke.',
      null,
      [ACT.vocabularySlang],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 6 — Grammar I: V + 火/红 + 了
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      'V + 火了 — V-ed into virality',
      'V + huǒ le',
      'Resultative pattern: VERB + 火 + 了 = "became viral as a result of V-ing". The verb describes the action; 火了 carries the outcome (going hot). Most natural with action verbs like 唱 (sing), 演 (perform), 拍 (film), 发 (post), 跳 (dance). The 火 here is the adjective from Vocabulary I, slotting into a resultative complement position.',
      'sentence',
      '这首歌一晚上就唱火了。 ("This song became viral after just one night of singing.")\n这个视频发出来三天就火了。 ("This video went viral three days after being posted.")',
      'The pattern compresses cause and effect into one clause — much more native-sounding than two separate sentences ("X did Y. Then X became famous.").',
      [
        { target: 'V (action)', note: 'the action that triggered virality — 唱 sing / 演 act / 发 post / 拍 film' },
        { target: '火 (resultative)', note: '"became hot / viral" — slotted as a complement after the verb' },
        { target: '了 (aspect)', note: 'marks the change of state — "now in the viral state"' },
      ],
      [ACT.grammarHuoLe],
    ),
    createContentItem(
      'V + 红了 — V-ed into fame',
      'V + hóng le',
      'Same shape as V + 火了 but with 红 ("famous / popular") replacing 火 ("viral / hot"). 红了 describes a broader, more lasting rise in fame — a singer who 唱红了 a song is one who built a career off it; 唱火了 emphasizes the song\'s short-burst surge. Both are extremely common; choosing 红 vs 火 calibrates the time-scale.',
      'sentence',
      '周杰伦凭这首歌红了二十年。 ("Jay Chou rode this one song to twenty years of fame.")\nVS\n这首歌昨天突然火了。 ("This song suddenly went viral yesterday.")',
      '红 = enduring fame. 火 = momentary viral surge. The contrast is real and lets you say something more precise than English "popular".',
      [
        { target: '红 (enduring fame)', note: 'long-term popularity built up over time; pairs with biographical timeframes' },
        { target: '火 (viral surge)', note: 'short-term spike in attention; pairs with "yesterday / this week / one night"' },
        { target: '同一动词，不同结果', note: 'the same verb (sang) yields different time-scales of result depending on choice of 红 / 火' },
      ],
      [ACT.grammarHuoLe],
    ),
    createContentItem(
      '怎么 + V + 火/红 + 的 — how did X go viral',
      'zěnme V huǒ/hóng de',
      'Ask "how did X become viral / famous?" with 怎么 + V + 火了/红了 (+ 的) in the 是…的 cleft. The 的 marks past circumstances. A high-frequency question shape in pop-culture conversation: people love asking how something blew up.',
      'sentence',
      '这首歌是怎么唱火的? ("How did this song get sung into virality?")\n他到底是怎么火起来的? ("How exactly did he become famous in the first place?")',
      'The cleft with 是…的 foregrounds the manner/path of viralization — not "did it go viral" but "how, by what route, through whose effort".',
      [
        { target: '是…的 cleft', note: 'foregrounds the manner, time, or agent of a past event' },
        { target: '怎么 (manner)', note: '"how / by what means" — slots in before the verb' },
        { target: '火起来 / 红起来', note: 'directional complement 起来 ("up / into a state of") adds the inception sense' },
      ],
      [ACT.grammarHuoLe],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 7 — Grammar II: A 跟/和 B 一样
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      'A 跟/和 B 一样 — A is the same as B',
      'A gēn/hé B yīyàng',
      'Equational comparison: A 跟 B 一样 = "A is the same as B". 跟 (gēn) and 和 (hé) are interchangeable in this slot; 跟 leans casual/spoken, 和 leans neutral/written. Often expanded with an adjective: A 跟 B 一样 + ADJ = "A is just as ADJ as B".',
      'sentence',
      '抖音跟TikTok一样火。 ("Douyin is just as viral as TikTok.")\n小红书和Instagram一样受欢迎。 ("Xiaohongshu is just as popular as Instagram.")',
      'The single most efficient comparison pattern in Mandarin — covers what English splits across "the same as" / "just as ADJ as" / "like".',
      [
        { target: 'A + 跟/和 + B', note: 'set up the two items being compared' },
        { target: '一样 (the same)', note: 'the core equational marker' },
        { target: '+ ADJ (optional)', note: 'specifies the dimension of equality — 一样火 (equally viral), 一样有名 (equally famous)' },
      ],
      [ACT.grammarYiyang],
    ),
    createContentItem(
      'A 跟/和 B 不一样 — A is not the same as B',
      'A gēn/hé B bù yīyàng',
      'Negation: place 不 directly before 一样. A 跟 B 不一样 = "A is not the same as B". Apply the 不 sandhi from Foundation: bù becomes bú before the fourth-tone 一. To specify the dimension of difference, add 在…(方面) ("in terms of…"): A 跟 B 在内容方面不一样 ("A and B differ in content").',
      'sentence',
      '中国的抖音跟海外的TikTok不一样，内容审核严格多了。',
      '"Chinese Douyin is not the same as overseas TikTok — content moderation is much stricter." — the second clause specifies the dimension of difference.',
      [
        { target: '不一样 (not the same)', note: '不 placed before 一样; apply bú sandhi (bú yíyàng spoken)' },
        { target: '在…方面 (in terms of)', note: 'pinpoints the dimension where the two differ' },
        { target: '严格多了 (much stricter)', note: 'comparative complement 多了 = "much more"' },
      ],
      [ACT.grammarYiyang],
    ),
    createContentItem(
      '跟…差不多 — A is about the same as B',
      'gēn … chàbuduō',
      'For approximate equivalence (not perfect equality), use A 跟 B 差不多 instead of A 跟 B 一样. 差不多 literally "differ-not-much"; weakens the comparison to "roughly equal / about the same". Very high-frequency in spoken Mandarin where exact claims feel too strong.',
      'sentence',
      '微博跟Twitter差不多，都是发短文章。',
      '"Weibo is about the same as Twitter — both are for posting short messages." — the 都 ("both") clause justifies the approximation.',
      [
        { target: '差不多 (roughly)', note: 'softens the comparison to "approximate" rather than "identical"' },
        { target: '都是… (both are…)', note: 'parallel clause showing the shared property; standard support for a 差不多 claim' },
      ],
      [ACT.grammarYiyang],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 8 — Grammar III: 几乎 / 差不多
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '几乎 — almost / nearly',
      'jīhū',
      'Adverb meaning "almost / nearly". Placed before a verb or adjective. 几乎 leans toward "approaching 100 percent" — used for sweeping generalizations where the speaker is willing to claim near-universality. Often paired with 每 (every) or 所有 (all) for a quantified-universal: 几乎每个 = "almost every".',
      'sentence',
      '几乎每个大学生都刷抖音。 ("Almost every university student scrolls Douyin.")\n这件事几乎全网都知道。 ("Almost the whole internet knows about this matter.")',
      'Pairs naturally with 都 (all) and 每 (every) to produce big-N generalizations — the staple of pop-culture commentary.',
      [
        { target: '几乎 + 每 + N + 都', note: '"almost every N is/does…" — the universal-with-exception shape' },
        { target: '几乎 + ADJ', note: '"almost ADJ" — e.g., 几乎一样 (almost the same)' },
        { target: '近 100% claim', note: 'leans high — only use if the claim really is near-universal; otherwise switch to 差不多' },
      ],
      [ACT.grammarJihu],
    ),
    createContentItem(
      '差不多 — about the same / roughly',
      'chàbuduō',
      'Adverb / adjective meaning "about the same / roughly / nearly". Lower-key than 几乎 — claims approximate equivalence rather than near-universal coverage. Position varies: 差不多 + V/ADJ for "roughly V" or "roughly ADJ"; standalone 差不多 = "close enough".',
      'sentence',
      '我们俩的粉丝量差不多。 ("Our two follower counts are about the same.")\n差不多了，可以发了。 ("Close enough — we can post it now.")',
      'In casual conversation, 差不多 is one of the most frequent fillers — "good enough", "more or less", "close to it" all map to this single word.',
      [
        { target: '差不多 + V/ADJ', note: 'roughly V / roughly ADJ; modifies the predicate' },
        { target: 'standalone 差不多了', note: '"close enough" / "almost done" — a complete one-word verdict' },
        { target: '差不多 vs 几乎', note: '差不多 = roughly equal; 几乎 = nearly universal. Pick by whether you mean equivalence or coverage' },
      ],
      [ACT.grammarJihu],
    ),
    createContentItem(
      '几乎 + 不/没 — almost not',
      'jīhū bù/méi',
      '几乎 can also pair with negation: 几乎不 ("almost never / hardly") and 几乎没 ("almost no / hardly any"). Used to claim near-zero rather than near-universal. The contrast with positive 几乎 (almost all) lets you bracket a topic from both ends.',
      'sentence',
      '我几乎不发微博，太麻烦了。 ("I almost never post on Weibo — too much hassle.")\n这个新平台几乎没有粉丝。 ("This new platform has almost no users.")',
      'Note that 几乎没 takes 没 (not 不) when negating 有 (have / exist), per the standard 不/没 split.',
      [
        { target: '几乎不 + V', note: '"almost never V" — for habitual actions' },
        { target: '几乎没 + V (past) / 没有 N', note: '"almost did not V" or "almost has no N" — for existence and past actions' },
      ],
      [ACT.grammarJihu],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 9 — Reading and Speaking
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '潮流解读 — 直播带货',
      'cháoliú jiědú — zhíbō dài huò',
      'A short trend-explainer paragraph about livestream e-commerce — the single most distinctive Chinese internet phenomenon for foreign observers. Read it aloud, then summarize the trend in two sentences using at least one pattern from this lesson.',
      'sentence',
      '直播带货是中国最火的一种网络生意。主播在直播里推销产品，粉丝可以一边看一边下单。李佳琦跟薇娅就是凭直播带货红起来的，他们一晚上能卖几个亿。这种模式跟海外的电视购物差不多，但规模大多了，几乎所有大品牌都在做。如果你想了解中国电商，就一定要看一场直播。',
      'Translation: "Livestream e-commerce is the hottest type of internet business in China. Hosts pitch products during a livestream, and fans can order while watching. Li Jiaqi and Viya rode livestream e-commerce to fame — they can sell hundreds of millions in one night. The model is roughly the same as overseas TV shopping, but at a much larger scale; almost every major brand does it. If you want to understand Chinese e-commerce, you have to watch a livestream once."',
      [
        { target: '凭…红起来', note: 'V + 红了 pattern from Grammar I — rode X to fame' },
        { target: '跟…差不多', note: 'Grammar II + III combined — roughly the same as' },
        { target: '几乎所有大品牌都', note: 'Grammar III 几乎 + universal — almost every major brand' },
        { target: '一边看一边下单', note: 'simultaneous-actions 一边…一边… ("V1 while V2-ing") — bonus Level 2 pattern in context' },
        { target: '李佳琦 / 薇娅', note: 'the two most famous Chinese livestreamers; 薇娅 (Wēi Yà / Viya) was banned in 2021 for tax evasion — a classic 塌房 case' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      '理解问题',
      'lǐjiě wèntí',
      'Four standard comprehension questions about the trend explainer. Answer each in one or two Mandarin sentences, using vocabulary and at least one grammar pattern from this lesson.',
      'sentence',
      'Q1: 直播带货是什么? Q2: 李佳琦是怎么红起来的? Q3: 中国直播带货跟海外电视购物有什么区别? Q4: 为什么几乎所有大品牌都在做直播带货?',
      'Two definitional, one biographical, one comparison, one explanatory — covering all three grammar patterns from this unit.',
      [
        { target: 'A1: 直播带货是…(definition)', note: 'restate the trend in your own words using core vocabulary' },
        { target: 'A2: 他是凭直播带货红起来的。', note: 'use V + 红了 from Grammar I' },
        { target: 'A3: 跟海外电视购物差不多，但规模大多了。', note: 'use A 跟 B 差不多 from Grammar II' },
        { target: 'A4: 因为流量很大，几乎每个用户都看直播。', note: 'use 几乎 + universal from Grammar III' },
      ],
      [ACT.reading],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 10 — Listening and Speaking
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '对话 — 一个视频火了',
      'duìhuà — yī gè shìpín huǒ le',
      'A natural four-turn conversation between two Tsinghua students reacting to a video that just went viral on 抖音. Covers V + 火了, comparison, generalization, and three slang terms in context.',
      'conversation',
      'A: 你看那个视频了吗? 昨天晚上突然就火了!\nB: 看了看了! 那个网红跳舞跳火的对吧? 太yyds了!\nA: 对! 一晚上点赞过了五百万，直接上热搜第一。\nB: 几乎我朋友圈每个人都在转发，我都看了八遍了。\nA: 这个跟韩国那个舞蹈视频差不多，但中国版的更卷，背景都是国风的。\nB: 哈哈，现在的网红真的太能整活了，咱们就躺平看戏吧。',
      'Translation: "A: Did you see that video? It went viral suddenly last night! B: I saw it, I saw it! The internet celebrity who danced their way to fame, right? Totally GOAT! A: Yes! Over five million likes in one night, straight to number one on the trending list. B: Almost everyone on my Moments is resharing it — I have watched it eight times already. A: It is roughly the same as that Korean dance video, but the Chinese version is more cutthroat — the background is all traditional-Chinese aesthetic. B: Haha, internet celebrities these days are too good at stirring things up. Let us just lie flat and watch the show."',
      [
        { target: '突然就火了', note: 'V + 火了 from Grammar I; 突然就 ("suddenly just") adds the surprise sense' },
        { target: '跳舞跳火的', note: 'V + V + 火了 + 的 — the cleft form, "the one who danced their way to viral"' },
        { target: '几乎…每个人都在转发', note: 'Grammar III universal — almost every person on my feed is resharing' },
        { target: '跟…差不多，但…更…', note: 'Grammar II equational + comparative — roughly the same but more X' },
        { target: 'yyds / 国风 / 躺平 / 卷', note: 'four slang/culture markers in two turns — the natural density of gen-Z speech' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      '换你说',
      'huàn nǐ shuō',
      'Now reproduce the conversation with your own example: a different viral video, a different platform, a different slang word. Aim for two turns: react to it going viral (using V + 火了), then make one comparison or generalization.',
      'conversation',
      '你: 你听说那个 [视频/歌/挑战] 了吗? 昨天 [平台] 上突然就火了!\n对方: 真的假的? 怎么火的?\n你: [用 V + 火了 解释]\n对方: 跟之前那个 [类似的东西] 一样吗?\n你: [用 一样 或 差不多 比较]，但是 [一个不同点]。',
      'A scaffold for free production — fill in the bracketed slots with your own pop-culture content; the structure carries the rest.',
      [
        { target: '[视频/歌/挑战]', note: 'a real video, song, or challenge you actually know' },
        { target: '[平台]', note: '抖音 / 微博 / 小红书 / B站 — pick the platform that fits the content' },
        { target: '[用 V + 火了 解释]', note: 'use Grammar I to explain how it went viral' },
        { target: '[用 一样 或 差不多 比较]', note: 'use Grammar II to compare it to something the listener already knows' },
        { target: '[一个不同点]', note: 'one specific difference that makes the Chinese version distinctive' },
      ],
      [ACT.listening],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 11 — Culture Note
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '粉圈文化',
      'fěnquān wénhuà',
      'Chinese fan-circle culture is uniquely intense by global standards. Fandoms (粉圈, fěnquān) are formally organized: each major idol has 后援会 (hòuyuánhuì, "support clubs") that coordinate 应援 (yìngyuán, organized cheering at events, banner-buying, billboard rentals) and 集资 (jízī, crowd-fundraising for birthdays, chart-pushing, and album-stockpiling). At its peak, a single idol\'s fandom can raise millions of yuan in a few days. This intensity led to the 2021 regulatory crackdown described in the next entry.',
      'sentence',
      '我们家偶像生日，粉圈集资买了三块大屏广告。',
      '"For our idol\'s birthday, the fandom crowdfunded three big-screen advertisements." — 我们家 ("our house\'s") is itself fandom in-group possessive; 大屏广告 (LED billboard ads) are a standard 应援 deliverable.',
      [
        { target: '粉圈 fěnquān', note: 'organized fan-circle; the unit of Chinese fandom social structure' },
        { target: '应援 yìngyuán', note: 'organized cheering, banner-waving, light-stick coordination at concerts and airports' },
        { target: '集资 jízī', note: 'crowdfunding among fans, typically for idol birthdays, chart manipulation, or album mass-purchase' },
        { target: '后援会 hòuyuánhuì', note: 'official fan-club; the formal organizational layer above casual fans' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      '2021年的选秀整顿',
      'èrlíng-èryī nián de xuǎnxiù zhěngdùn',
      'In 2021 Chinese authorities banned idol-survival shows (选秀节目, talent-competition shows where fans vote contestants into a debut group) after the "Qing Chun You Ni 3" scandal — fans had bought enormous quantities of branded milk to unlock vote-codes printed inside the caps, then dumped the unopened bottles into ditches. Footage went viral; regulators responded by canceling the genre and banning the underlying pay-to-vote mechanic. Iconic example of when 粉圈 intensity crosses into regulatory action.',
      'sentence',
      '2021年以后，几乎所有选秀节目都被叫停了。',
      '"After 2021, almost all talent-survival shows were halted." — combines the 几乎 generalization (Grammar III) with the passive 被…叫停 ("got called to a stop").',
      [
        { target: '选秀 xuǎnxiù', note: 'talent-survival show; the format banned after 2021' },
        { target: '倒奶事件 dào nǎi shìjiàn', note: '"milk-dumping incident" — the trigger event' },
        { target: '整顿 zhěngdùn', note: 'regulatory rectification — the same 整顿 from the gen-Z slang section, here in its original official sense' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      '限娱令',
      'xiàn yú lìng',
      'Literally "entertainment-restriction order" — a series of regulations issued since 2011 (and tightened sharply in 2021) restricting the Chinese entertainment industry. Covers celebrity earnings caps, a ban on minor performers on talent shows, restrictions on fan-club organization, mandatory "positive energy" content quotas, and limits on celebrity-driven variety shows. The 限娱令 is the single biggest reason Chinese pop culture looks different from Korean or Japanese pop culture in the 2020s.',
      'sentence',
      '限娱令出来以后，明星跟以前不一样了，要更小心。',
      '"After the entertainment-restriction order came out, celebrities are not the same as before — they have to be more careful." — uses the 跟 不一样 negative comparison (Grammar II).',
      [
        { target: '限娱令 xiàn yú lìng', note: 'the umbrella name for the regulatory regime governing celebrities, talent shows, and fan clubs' },
        { target: '正能量 zhèng néngliàng', note: '"positive energy" — the content type the regulations actively promote' },
        { target: '塌房 tāfáng connection', note: 'the regulations have driven a wave of 塌房 incidents as celebrities are publicly punished for tax evasion, scandals, or political missteps' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      '中国抖音 vs 海外TikTok',
      'Zhōngguó Dǒuyīn vs hǎiwài TikTok',
      'Same parent company (ByteDance), almost identical interface — but two separate apps with separate content ecosystems and separate moderation regimes. Mainland 抖音 has stricter content moderation, more education and parenting content, in-app daily time limits for minors, and a heavier integration with e-commerce (直播带货). Overseas TikTok skews younger, less educational, and has weaker e-commerce integration. The two apps cannot directly see each other\'s content.',
      'sentence',
      '中国抖音跟海外TikTok其实差不多，但内容审核严格多了，几乎看不到不当言论。',
      '"Chinese Douyin is actually about the same as overseas TikTok, but content moderation is much stricter — you almost never see inappropriate speech." — chains 差不多 + 几乎不, both from Grammar III.',
      [
        { target: '内容审核 nèiróng shěnhé', note: '"content moderation"; significantly stricter on Mainland 抖音' },
        { target: '青少年模式 qīngshàonián móshì', note: '"teen mode" — daily time limits for minors, mandatory on Mainland 抖音' },
        { target: '直播带货 zhíbō dài huò', note: 'livestream e-commerce — much heavier on Mainland 抖音 than on overseas TikTok' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      '国风',
      'guófēng',
      'Literally "national wind / national style" — the major Chinese pop-culture aesthetic that fuses traditional Chinese elements (Hanfu clothing, gufeng music, calligraphy, traditional dance) with modern pop production. Hugely popular on B站, 抖音, and 小红书 since 2018. A defining Chinese-internet aesthetic that has no exact Korean or Japanese equivalent; the cultural marker that distinguishes Chinese viral content from K-pop or J-pop visual styles.',
      'sentence',
      '现在国风视频几乎每天都上热搜，跟以前完全不一样了。',
      '"Right now traditional-style videos make the trending list almost every day — completely different from before." — combines 几乎 universal + 跟…不一样 negative comparison.',
      [
        { target: '汉服 hànfú', note: 'traditional Han Chinese clothing; the visual centerpiece of much 国风 content' },
        { target: '古风音乐 gǔfēng yīnyuè', note: '"ancient-style music" — fusion of pop production with traditional Chinese instruments and pentatonic melodies' },
        { target: '国潮 guócháo', note: '"national trend" — the sibling concept covering Chinese-domestic-brand consumerism with traditional aesthetics; often paired with 国风 in marketing' },
      ],
      [ACT.culture],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 12 — Task / Consolidation
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '任务: 给外国同学讲一个中国潮流',
      'rènwù: gěi wàiguó tóngxué jiǎng yī gè Zhōngguó cháoliú',
      'Roleplay a coffee break at Tsinghua University with the AI tutor playing a foreign classmate who has just arrived in Beijing. Pick ONE Chinese internet trend (直播带货, 网红打卡, 国风, 躺平 culture, or another from this unit) and explain it to them in a 6-turn exchange covering three beats: (1) what it is, (2) why it is popular, (3) one slang term they should learn.',
      'conversation',
      '[Coffee break, Tsinghua campus]\n外国同学: 我来中国之前听说有一个很特别的现象，你能给我讲讲吗?\n你: [挑一个潮流 + 定义]\n外国同学: 这跟我们国家的什么差不多吗?\n你: [用 跟…一样/差不多/不一样 比较]\n外国同学: 为什么这么火?\n你: [用 V + 火了 或 几乎…都 解释]\n外国同学: 有什么相关的网络用语我应该学一下吗?\n你: [教一个 yyds / 躺平 / 内卷 / 绝绝子 等，加例句]\n外国同学: 谢谢! 我回去就刷抖音看看!\n你: [告别 + 鼓励]',
      'A six-turn exchange covering all three grammar patterns and at least one slang item. The AI tutor will prompt and respond naturally to whatever trend you pick.',
      [
        { target: '定义 (define)', note: 'use core vocabulary from Activity 3 — name the trend in one sentence with a concrete behavior or example' },
        { target: '比较 (compare)', note: 'use Grammar II (跟…一样/差不多/不一样) to bridge it to something the foreign classmate already knows' },
        { target: '解释火爆 (explain virality)', note: 'use Grammar I (V + 火了/红了) or Grammar III (几乎…都) to give the why' },
        { target: '教用语 (teach a slang term)', note: 'pick ONE term from Activity 5, give its rough meaning, register, and one usage example' },
        { target: '告别', note: '回头见 / 拜拜 / 下次喝咖啡 — match the register you opened with' },
      ],
      [ACT.task],
    ),
    createContentItem(
      '挑战 — 解释一个塌房案例',
      'tiǎozhàn — jiěshì yī gè tāfáng ànlì',
      'Stretch goal: in the same scene, the foreign classmate asks why so many Chinese celebrities seem to disappear suddenly. Explain one 塌房 (idol falling from grace) case in 2-3 sentences, mentioning the 限娱令 regulatory context. Tests whether you can combine pop-culture vocabulary, culture-note content, and grammar patterns in a real-world explanatory paragraph.',
      'conversation',
      '外国同学: 为什么有些中国明星突然就消失了? 我前几天搜一个演员，发现他完全没了。\n你: 这种情况叫"塌房"。明星出了丑闻或者违法的事，几乎一夜之间就被全网封杀。\n外国同学: 真的吗? 跟海外的cancel culture差不多吗?\n你: 差不多，但中国还有限娱令，所以处罚比海外严格多了。明星塌房以后，几乎所有作品都会下架。\n外国同学: 太惨了! 那粉丝怎么办?\n你: 粉丝就只能退粉籍，重新找一个偶像。这就是为什么大家说追星有风险。',
      'Translation: "Foreign classmate: Why do some Chinese celebrities suddenly disappear? I searched for an actor a few days ago and he is completely gone. You: That situation is called \'house caved in\'. When a celebrity has a scandal or breaks the law, they are blacklisted across the whole internet almost overnight. Foreign classmate: Really? Roughly the same as overseas cancel culture? You: Roughly the same, but China also has the entertainment-restriction order, so punishments are much stricter than overseas. After a celebrity falls from grace, almost all their works get pulled. Foreign classmate: How awful! What about the fans? You: Fans just have to leave the fan club and find a new idol. That is why people say fandom carries risks."',
      [
        { target: '塌房 + 封杀', note: '"fall from grace" (Vocab) + "blacklist / ban across the platform" — the action chain' },
        { target: '几乎一夜之间 / 几乎所有作品都', note: 'two uses of 几乎 from Grammar III in one paragraph' },
        { target: '跟…差不多，但…严格多了', note: 'Grammar II comparison + comparative complement — the structural backbone of the explanation' },
        { target: '退粉籍', note: 'fan-circle vocabulary from the culture note — "leave the fan-club registration"' },
        { target: '限娱令', note: 'the regulatory framework that distinguishes Chinese cancellation from Western cancel culture' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
