// Level 1 Unit 19 — Chinese Holidays (Mandarin Chinese)
// Functions: naming China's major holidays, describing dates / foods / activities / greetings,
// asking when a holiday falls, saying who you celebrate with and where, and explaining
// a Chinese holiday to a foreign friend at Tsinghua.
//
// All content is authored with Hanzi (target) + Pinyin (romanization) +
// English glosses (canonical source). The AI conversation tutor reads this
// curriculum and delivers it to each learner in their preferred native
// language at runtime — never assume a specific L1 in this file.
//
// Glosses follow the rich-gloss rule (AGENTS.md → "Gloss Richness"):
// every nativeText, exampleNative, and breakdown.native carries register,
// usage context, or contrast info — not a bare definition.

const createContentItem = (
  target,
  pinyin,
  note,
  type = 'word',
  example = '',
  exampleNote = '',
  breakdown = null,
  activityIds = [],
) => ({
  type,
  activityIds,
  targetText: target,
  romanization: pinyin,
  nativeText: note,
  pronunciation: pinyin,
  exampleTarget: example || target,
  exampleNative: exampleNote || note,
  korean: target,
  english: note,
  example: example || target,
  exampleEnglish: exampleNote || note,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.target, native: b.note, korean: b.target, english: b.note })) } : {}),
});

const ACT = {
  orientation: 'zh-l1u19-orientation',
  pronunciation: 'zh-l1u19-pronunciation',
  vocabularyHolidays: 'zh-l1u19-vocab-holidays',
  vocabularyFoodCustoms: 'zh-l1u19-vocab-food-customs',
  grammarShiDe: 'zh-l1u19-grammar-shi-de',
  grammarGenYiqi: 'zh-l1u19-grammar-gen-yiqi',
  grammarVZai: 'zh-l1u19-grammar-v-zai',
  reading: 'zh-l1u19-reading',
  listening: 'zh-l1u19-listening',
  writing: 'zh-l1u19-writing',
  culture: 'zh-l1u19-culture',
  task: 'zh-l1u19-task',
};

const activities = [
  {
    id: ACT.orientation,
    section: 'Orientation',
    title: 'What you will be able to do',
    goals: [
      'Name China\'s nine most important traditional and national holidays and place each on the lunar or solar calendar so you can answer "when is it?".',
      'Use the 是 + 时间 + 的 emphatic pattern to ask and answer when an event happened or falls (中秋节是几月几号?).',
      'Explain one Chinese holiday to a foreign friend at Tsinghua — date, food, activity, and a holiday greeting — in one continuous mini-monologue.',
    ],
    task: 'Picture yourself at Tsinghua a week before 中秋节 — a classmate from abroad asks "what is this Mid-Autumn thing?". By the end of this lesson you should answer in Mandarin without rehearsing each line.',
  },
  {
    id: ACT.pronunciation,
    section: 'Pronunciation',
    title: 'Sound traps in holiday vocabulary',
    goals: [
      'Distinguish the palatal initials j/q/x in 节 (jié), 庆 (qìng), and 春 (chūn) from the retroflex zh/ch/sh/r in 中 (zhōng) and 春 (chūn) — both occur back-to-back in holiday words.',
      'Apply the third-tone sandhi in 五 (wǔ) before another third tone, as in 五一 → 五一 (wǔyī, no sandhi because 一 here reads first tone in context) but contrast with 你好 sandhi already learned.',
      'Master the rising-falling contour of 月饼 (yuèbǐng, 4-3) and 红包 (hóngbāo, 2-1) — the two most common holiday food and gift words.',
    ],
    task: 'Read each holiday word aloud three times and identify which tone-combination pattern (e.g., 4-2, 2-1, 1-2) each one follows.',
  },
  {
    id: ACT.vocabularyHolidays,
    section: 'Vocabulary I',
    title: 'The nine major Chinese holidays',
    goals: [
      'Use 节日 (jiérì, holiday) and the names of nine major holidays: 春节, 元宵节, 清明节, 端午节, 中秋节, 国庆节, 劳动节, 七夕节, 重阳节.',
      'Sort each holiday by calendar type: lunar (春节, 元宵节, 端午节, 中秋节, 七夕节, 重阳节) vs solar/fixed (清明节 ≈4月5日, 国庆节 10月1日, 劳动节 5月1日).',
    ],
    task: 'Match each holiday name with its date and say one sentence about why the date matters using 是…的 emphasis.',
  },
  {
    id: ACT.vocabularyFoodCustoms,
    section: 'Vocabulary II',
    title: 'Holiday foods, activities, and greetings',
    goals: [
      'Pair each major holiday with its signature food: 饺子 (Spring Festival), 汤圆 (Lantern Festival), 粽子 (Dragon Boat), 月饼 (Mid-Autumn).',
      'Use the standard activity verbs: 过年 (celebrate New Year), 吃 (eat + food), 看 (watch + 春晚), 发 (send + 红包), 赏月 (admire the moon), 团圆 (family reunion).',
      'Give the right greeting for the right holiday: 新年快乐 / 恭喜发财 (Spring Festival), 中秋快乐 (Mid-Autumn), 端午安康 (Dragon Boat — note 安康 "safe and healthy" replaces 快乐 for this one for cultural reasons).',
    ],
    task: 'For each of four major holidays, name food + activity + greeting in a single sentence.',
  },
  {
    id: ACT.grammarShiDe,
    section: 'Grammar I',
    title: '是 + 时间 + 的 — emphasizing when something happened',
    goals: [
      'Use 是 + 时间 + 的 to ASK or ANSWER specifically when an event occurred or recurs: 中秋节是几月几号? / 中秋节是农历八月十五.',
      'Distinguish this pattern from the plain copula 是: the 是…的 frame puts spotlight on the time/date/manner detail; dropping 是…的 makes the sentence neutral.',
      'Use it for both past events (你是什么时候来中国的? "When did you come to China?") and recurring annual dates (国庆节是十月一号).',
    ],
    task: 'Write five questions and answers about Chinese holidays using the 是 + 时间 + 的 pattern.',
  },
  {
    id: ACT.grammarGenYiqi,
    section: 'Grammar II',
    title: '跟 X 一起 + V — doing something together with X',
    goals: [
      'Use the 跟 X 一起 + V frame ("together with X, do V"): 跟家人一起过年 ("celebrate New Year with family") — the social verb anchoring all reunion-type holidays.',
      'Know that 和 (hé) and 跟 (gēn) are largely interchangeable in this frame; 跟 is more colloquial, 和 slightly more formal/written.',
      'Negate by placing 不 before 跟: 我今年不跟家人一起过年, 我跟朋友一起过 ("This year I am not celebrating with family; I am with friends").',
    ],
    task: 'Write three sentences using 跟 X 一起 + V to describe who you celebrate three different holidays with.',
  },
  {
    id: ACT.grammarVZai,
    section: 'Grammar III',
    title: 'V + 在 + place — doing V at a place',
    goals: [
      'Use the V + 在 + place pattern to say where an action happens: 我在北京过春节 ("I celebrate Spring Festival in Beijing"). 在 follows the verb when the verb is the focus.',
      'Distinguish from 在 + place + V (preverbal): 我在家吃月饼 ("I eat mooncakes at home") — both word orders are valid, with subtle focus differences.',
      'Use this with the question word 哪儿/哪里 to ask "where": 你在哪儿过年? ("Where are you celebrating New Year?").',
    ],
    task: 'Write three sentences saying where you celebrate three different holidays using the V + 在 + place pattern.',
  },
  {
    id: ACT.reading,
    section: 'Reading and Speaking',
    title: '读和说 — A Mid-Autumn blog post',
    goals: [
      'Read a 6-sentence Mid-Autumn (中秋节) blog entry aloud with correct tones, sandhi, and natural rhythm.',
      'Answer comprehension questions about date, food, activity, and the writer\'s feelings using 是 / 是…的 short answers.',
    ],
    task: 'Read the paragraph below aloud once, then answer four comprehension questions in complete short sentences.',
  },
  {
    id: ACT.listening,
    section: 'Listening and Speaking',
    title: '听和说 — Spring Festival plans',
    goals: [
      'Follow a 7-turn dialogue between a Chinese student and a foreign classmate planning the 春节 holiday at Tsinghua.',
      'Reproduce the dialogue with your own holiday plans, swapping in 跟…一起 and 在…过 patterns.',
    ],
    task: 'Read the dialogue along with the tutor first, then perform it again with your own holiday and travel plan swapped in.',
  },
  {
    id: ACT.writing,
    section: 'Writing',
    title: 'Compare a holiday from your country',
    goals: [
      'Write 4–5 sentences in Hanzi comparing a holiday from your country with a Chinese holiday: name, date, food, activity, greeting.',
      'Use 是…的 at least once and 跟…一起 at least once so the writing demonstrates the core grammar of this lesson.',
    ],
    task: 'Write your own comparison using the model below; read it aloud with correct tones when finished.',
  },
  {
    id: ACT.culture,
    section: 'Culture Note',
    title: '春节 vs Western New Year — lunar calendar, 春运, and 红包',
    goals: [
      'Distinguish the lunar Spring Festival (春节, January/February) from solar New Year (元旦 yuándàn, January 1) — both exist but 春节 is the family-reunion holiday and 元旦 is just a calendar marker.',
      'Know about 春运 (chūnyùn), the annual ~3-billion-trip migration around 春节, and the centrality of 团圆饭 (the New Year\'s Eve family-reunion dinner) and the CCTV 春晚 gala.',
      'Understand 红包 (red envelopes) — traditionally cash given by elders to children, increasingly digital 微信红包 since the mid-2010s; and 黄金周 (Golden Week), the 7-day national vacations around 春节 and 国庆节.',
    ],
    task: 'Summarize one cultural fact each about 春节, 红包, and 春运 in 1 sentence each.',
  },
  {
    id: ACT.task,
    section: 'Task',
    title: 'Explain a Chinese holiday to a foreign friend at Tsinghua',
    goals: [
      'Combine vocabulary + 是…的 + 跟…一起 + V…在… in one continuous mini-monologue explaining ONE Chinese holiday to a classmate who has never heard of it.',
      'Invite the friend to celebrate together using the 跟我一起 + V pattern, closing with the correct holiday greeting.',
    ],
    task: 'Roleplay: a foreign classmate at Tsinghua asks "中秋节是什么?". Pick one Chinese holiday and explain date/food/activity, then invite them to celebrate it together — 6-turn exchange with the tutor.',
  },
];

const lesson = {
  title: 'Level 1 · Unit 19: 中国的节日 — Chinese Holidays',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'zh',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-holiday-date', label: 'Asking when a holiday falls', goal: 'Use 是 + 时间 + 的 to ask and answer when a Chinese holiday occurs (中秋节是几月几号?).' },
    { id: 'describing-holiday-customs', label: 'Describing holiday customs', goal: 'Pair a holiday with its food, activity, and greeting in one fluent sentence.' },
    { id: 'celebrating-together', label: 'Celebrating with someone', goal: 'Use 跟 X 一起 + V to say who you celebrate a holiday with.' },
    { id: 'comparing-cultures', label: 'Comparing cultures', goal: 'Compare a holiday from your country with a Chinese one using parallel structure.' },
  ],
  relatedPools: ['topic-culture', 'topic-society'],
  content: [
    // ────────────────────────────────────────────────────────────────────
    // Activity 1 — Orientation
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '本课目标',
      'běn kè mùbiāo',
      'By the end of this lesson you can name China\'s nine main holidays, give each one\'s date, food, activity, and greeting, and explain one of them in fluent Mandarin to a foreign friend at Tsinghua.',
      'word',
      'Functions: 说节日 shuō jiérì (name holidays) · 问日期 wèn rìqī (ask the date) · 说习俗 shuō xísú (describe customs) · 邀请 yāoqǐng (invite together) · 比较文化 bǐjiào wénhuà (compare cultures)',
      'Five micro-skills form the spine of any culture-exchange conversation; the holiday topic is a natural rehearsal ground because every learner has equivalents to compare.',
      null,
      [ACT.orientation],
    ),
    createContentItem(
      '真实场景',
      'zhēnshí chǎngjǐng',
      'You are at Tsinghua University a week before 中秋节. A foreign classmate sees a stack of mooncake boxes in the cafeteria and asks "中秋节是什么?". You need to explain the date, the food, the activity, and offer to celebrate together.',
      'word',
      '外国同学: "这是什么? 中秋节是什么?"\n你: "中秋节是农历八月十五，我们吃月饼、赏月。今年跟我一起过吧!"',
      'A typical exchange around any major Chinese holiday on a university campus; explaining tradition + inviting together is the single most useful holiday script.',
      [
        { target: '中秋节是什么?', note: 'literal: "Mid-Autumn-Festival is what?"; the most common opener from a foreigner about a Chinese holiday' },
        { target: '农历八月十五', note: '"the 15th day of the 8th lunar month"; the lunar-calendar date — note 农历 (nónglì) means "lunar calendar"' },
        { target: '跟我一起过吧!', note: '"celebrate it together with me!"; 过 (guò) is the all-purpose verb for "spend / celebrate" a holiday' },
      ],
      [ACT.orientation],
    ),
    createContentItem(
      '两种日历',
      'liǎng zhǒng rìlì',
      'Chinese holidays split into two calendar systems. Lunar (农历 nónglì) holidays move on the Western calendar each year: 春节, 元宵节, 端午节, 中秋节, 七夕节, 重阳节. Solar/fixed (公历 gōnglì) holidays have set Western dates: 清明节 (≈Apr 4–6), 劳动节 (May 1), 国庆节 (Oct 1).',
      'word',
      '农历 (nónglì, lunar) vs 公历 (gōnglì, Gregorian solar) — both calendars are used side by side in modern China.',
      'Knowing which calendar a holiday follows tells you whether its Western date stays the same or shifts every year.',
      [
        { target: '农历 nónglì', note: 'the lunisolar Chinese calendar; dates shift on the Western calendar each year' },
        { target: '公历 gōnglì', note: 'the Gregorian (Western) calendar; used officially and for solar holidays' },
        { target: '黄历 huánglì', note: 'the traditional almanac that also lists lucky and unlucky days; consulted for weddings and major decisions' },
      ],
      [ACT.orientation],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 2 — Pronunciation
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '春节',
      'chūnjié',
      'Spring Festival — first-tone 春 (high level) + second-tone 节 (rising). The initial 春 is retroflex ch- with a curled-back tongue; do not let it slide into the palatal q-. Final 节 is the palatal j- with the tongue flat against the front teeth.',
      'word',
      '春节快乐! Chūnjié kuàilè! ("Happy Spring Festival!")',
      'The single most heard holiday word in Mandarin; getting the ch- vs j- contrast right matters in many holiday compounds.',
      [
        { target: '春 chūn (1st)', note: 'retroflex ch-, high level pitch; "spring" — also appears in 春天 (chūntiān, springtime) and 春运 (chūnyùn, Spring Festival migration)' },
        { target: '节 jié (2nd)', note: 'palatal j-, rising pitch; "festival/segment" — building block of nearly every Chinese holiday name' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      '中秋',
      'zhōngqiū',
      'Mid-Autumn — first-tone 中 (high level) + first-tone 秋 (high level). Both syllables high and steady; the two-first-tone pattern gives the word a flat, formal sound. Initial 中 uses retroflex zh-; initial 秋 uses palatal q-.',
      'word',
      '中秋快乐! Zhōngqiū kuàilè! ("Happy Mid-Autumn!")',
      'Hold both tones level — beginners often let the second syllable drop, which sounds dialectal.',
      [
        { target: '中 zhōng (1st)', note: 'retroflex zh-, high level; "middle" — also in 中国 (Zhōngguó, China) and 中文 (Zhōngwén, Chinese language)' },
        { target: '秋 qiū (1st)', note: 'palatal q- (aspirated, no English equivalent — soft "ch" with a puff of air), high level; "autumn"' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      '月饼',
      'yuèbǐng',
      'Mooncake — fourth-tone 月 (sharp falling) + third-tone 饼 (dip-and-rise). The 4-3 contour is dramatic: a hard drop on 月 followed by the dipping rise on 饼. Initial 月 uses the rounded front vowel üe (no English equivalent).',
      'word',
      '我喜欢吃月饼。Wǒ xǐhuan chī yuèbǐng. ("I like eating mooncakes.")',
      'The üe vowel in 月 is one of the trickiest finals; practice 月 (yuè) → 学 (xué) → 缺 (quē) to drill the same vowel after different initials.',
      [
        { target: '月 yuè (4th)', note: 'sharp falling tone; "moon/month" — also in 月亮 (yuèliang, the moon) and 月光 (yuèguāng, moonlight)' },
        { target: '饼 bǐng (3rd)', note: 'full dip-and-rise; "round flat cake" — also in 烧饼 (shāobǐng, baked flatbread) and 煎饼 (jiānbǐng, savory crepe)' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      '红包',
      'hóngbāo',
      'Red envelope — second-tone 红 (rising) + first-tone 包 (high level). The 2-1 contour glides up then stays high. Both syllables use familiar English-like consonants; the only trap is keeping 包 high and level after the rise of 红.',
      'word',
      '过年的时候大家发红包。Guònián de shíhou dàjiā fā hóngbāo. ("During New Year everyone gives red envelopes.")',
      'High-frequency cultural term; appears in 红包 (cash gift), 微信红包 (WeChat digital red envelope), and 抢红包 (qiǎng hóngbāo, "grabbing" digital red envelopes — a holiday game).',
      [
        { target: '红 hóng (2nd)', note: 'rising tone; "red" — the auspicious color in Chinese culture, used for weddings, New Year, and celebrations' },
        { target: '包 bāo (1st)', note: 'high level; "wrap/package/bag" — also in 书包 (shūbāo, schoolbag) and 面包 (miànbāo, bread)' },
      ],
      [ACT.pronunciation],
    ),
    createContentItem(
      '元宵 / 汤圆',
      'yuánxiāo / tāngyuán',
      'Two names for the sweet glutinous-rice balls eaten at Lantern Festival. 元宵 (yuánxiāo, 2-1) is the northern term and the festival name; 汤圆 (tāngyuán, 1-2) is the southern term and what the dish is more commonly called when ordered. Both refer to the same dessert.',
      'word',
      '元宵节吃汤圆。Yuánxiāo jié chī tāngyuán. ("On Lantern Festival we eat sweet rice balls.")',
      'Same food, two regional names — a common pattern in Chinese food vocabulary.',
      [
        { target: '元 yuán (2nd)', note: 'rising tone; "first/origin/round" — also the unit of Chinese currency (元 = RMB)' },
        { target: '宵 xiāo (1st)', note: 'high level; "night/evening" — appears almost exclusively in 元宵 and 通宵 (tōngxiāo, all night)' },
        { target: '汤 tāng (1st)', note: 'high level; "soup" — the balls are served in a sweet broth, hence the name' },
        { target: '圆 yuán (2nd)', note: 'rising tone; "round" — also the root of 团圆 (tuányuán, family reunion), the holiday\'s central theme' },
      ],
      [ACT.pronunciation],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 3 — Vocabulary I: The nine major Chinese holidays
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '节日',
      'jiérì',
      'General word for "holiday / festival". Combines 节 (jié, festival/segment) + 日 (rì, day). Covers both traditional lunar holidays and modern national ones; not used for personal events like birthdays (which take 生日 shēngrì instead).',
      'word',
      '中国有很多重要的节日。Zhōngguó yǒu hěn duō zhòngyào de jiérì.',
      '"China has many important holidays" — the standard opener for any holiday topic conversation.',
      null,
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '春节',
      'Chūnjié',
      'Spring Festival — the lunar new year, China\'s biggest and most important holiday. Falls on the first day of the first lunar month, usually late January or early February. Officially a 7-day public vacation (黄金周 Golden Week) and the year\'s largest family-reunion period.',
      'word',
      '春节是农历正月初一。Chūnjié shì nónglì zhēngyuè chū yī.',
      '"Spring Festival is the first day of the first lunar month" — the canonical date statement.',
      [
        { target: '春节 Chūnjié', note: 'literally "spring festival"; the lunar new year and biggest Chinese holiday' },
        { target: '过年 guònián', note: '"to celebrate the new year"; the verb most natively used for Spring Festival' },
        { target: '黄金周 huángjīn zhōu', note: '"golden week"; the 7-day national vacation around 春节 and again around 国庆节' },
      ],
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '元宵节',
      'Yuánxiāo Jié',
      'Lantern Festival — the 15th day of the first lunar month, marking the official end of the Spring Festival period. Celebrated with lantern displays, riddles posted on lanterns, and eating 汤圆 (sweet rice balls). Not a public holiday, but widely observed culturally.',
      'word',
      '元宵节是正月十五。Yuánxiāo Jié shì zhēngyuè shíwǔ.',
      '"Lantern Festival is the 15th of the first lunar month" — exactly two weeks after Spring Festival.',
      null,
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '清明节',
      'Qīngmíng Jié',
      'Tomb-Sweeping Day — falls around April 4–6 on the solar calendar, one of the few traditional holidays tied to the solar year. Families visit ancestors\' graves to clean them and make offerings. A 3-day public holiday in mainland China since 2008.',
      'word',
      '清明节大家去扫墓。Qīngmíng Jié dàjiā qù sǎomù.',
      '"On Qingming everyone goes to sweep the graves" — 扫墓 (sǎomù) is the canonical Qingming verb.',
      [
        { target: '清明节 Qīngmíng Jié', note: 'literally "clear and bright festival"; the tomb-sweeping holiday' },
        { target: '扫墓 sǎomù', note: '"sweep the graves"; the central Qingming activity, including cleaning, offerings, and burning paper money' },
      ],
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '端午节',
      'Duānwǔ Jié',
      'Dragon Boat Festival — the 5th day of the 5th lunar month, typically in late May or June. Commemorates the poet 屈原 (Qū Yuán, ~340–278 BCE) who drowned himself in protest. Celebrated by eating 粽子 (zòngzi, sticky rice in bamboo leaves) and racing dragon boats. A 3-day public holiday.',
      'word',
      '端午节是农历五月初五。Duānwǔ Jié shì nónglì wǔyuè chū wǔ.',
      '"Dragon Boat Festival is the 5th of the 5th lunar month" — the only major holiday where the customary greeting is 安康 (ān kāng, "safety and health") not 快乐 (kuàilè, "happiness"), because of its mournful origin.',
      [
        { target: '端午节 Duānwǔ Jié', note: 'literally "start of the wǔ-month festival"; commemorates the poet Qu Yuan' },
        { target: '划龙舟 huá lóngzhōu', note: '"row dragon boats"; the traditional Duanwu race performed in rivers across southern China' },
      ],
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '中秋节',
      'Zhōngqiū Jié',
      'Mid-Autumn Festival — the 15th day of the 8th lunar month, usually in September. The second-biggest family-reunion holiday after Spring Festival. Celebrated by eating 月饼 (mooncakes) and admiring the full moon (赏月). A 3-day public holiday.',
      'word',
      '中秋节是农历八月十五。Zhōngqiū Jié shì nónglì bāyuè shíwǔ.',
      '"Mid-Autumn is the 15th of the 8th lunar month" — the full moon date, central to the holiday\'s symbolism of completeness and reunion.',
      [
        { target: '中秋节 Zhōngqiū Jié', note: 'literally "mid-autumn festival"; the moon-and-mooncake holiday' },
        { target: '赏月 shǎngyuè', note: '"appreciate the moon"; the central Mid-Autumn activity along with eating mooncakes' },
      ],
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '国庆节',
      'Guóqìng Jié',
      'National Day — October 1, marking the founding of the People\'s Republic of China in 1949. A 7-day public vacation (the second 黄金周) and one of China\'s biggest travel periods. Major military parades are held on milestone years (every 10).',
      'word',
      '国庆节是十月一号。Guóqìng Jié shì shíyuè yī hào.',
      '"National Day is October 1" — a fixed solar date, easy to remember.',
      [
        { target: '国庆节 Guóqìng Jié', note: 'literally "national celebration festival"; the founding day of the PRC' },
        { target: '十一 shí yī', note: 'literally "10-1"; colloquial nickname for 国庆节, much like Americans say "the 4th" for Independence Day' },
      ],
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '劳动节',
      'Láodòng Jié',
      'Labor Day — May 1, an international workers\' holiday observed in most socialist and former-socialist countries. In China, a 5-day public vacation (mini Golden Week) and a major domestic-tourism peak. Often called 五一 (Wǔyī, "May 1") in casual speech.',
      'word',
      '劳动节是五月一号。Láodòng Jié shì wǔyuè yī hào.',
      '"Labor Day is May 1" — together with 国庆节 and 春节, one of the three main vacation periods of the Chinese calendar.',
      null,
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '七夕节',
      'Qīxī Jié',
      'Qixi Festival (Chinese Valentine\'s) — the 7th day of the 7th lunar month, in August. Based on the ancient legend of the cowherd 牛郎 and weaver girl 织女 who can only meet once a year across the Milky Way. Now widely commercialized as Chinese Valentine\'s Day, with couples exchanging gifts and going on dates.',
      'word',
      '七夕节是中国的情人节。Qīxī Jié shì Zhōngguó de qíngrénjié.',
      '"Qixi is the Chinese Valentine\'s Day" — a useful explanation for foreign friends; 情人节 (qíngrénjié) literally means "lover\'s festival".',
      null,
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '重阳节',
      'Chóngyáng Jié',
      'Double Ninth Festival — the 9th day of the 9th lunar month. Traditionally a day for climbing mountains (登高 dēnggāo) and showing respect to elders. Since 1989, also officially designated as 老人节 (Lǎorén Jié, Elders\' Day) — like Mother\'s Day but for all seniors.',
      'word',
      '重阳节也叫老人节。Chóngyáng Jié yě jiào Lǎorén Jié.',
      '"Double Ninth is also called Elders\' Day" — a good fact to know if you have elderly Chinese friends or colleagues.',
      null,
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '农历',
      'nónglì',
      'The traditional Chinese lunisolar calendar — literally "agricultural calendar". Used to determine all traditional festival dates (春节, 端午, 中秋, etc.) and many wedding dates. Modern China uses 公历 (the Gregorian solar calendar) for daily life but 农历 for cultural events.',
      'word',
      '中秋节是农历八月十五。Zhōngqiū Jié shì nónglì bāyuè shíwǔ.',
      '"Mid-Autumn is the 15th of the 8th lunar month" — the 农历 prefix tells you the date is on the lunar calendar.',
      [
        { target: '农历 nónglì', note: 'lunisolar calendar; tracks both lunar months and solar terms — more accurate for agriculture than a pure lunar calendar' },
        { target: '公历 gōnglì', note: 'Gregorian (solar) calendar; used for official and daily purposes' },
        { target: '阴历 yīnlì', note: 'pure lunar calendar; sometimes used interchangeably with 农历 in casual speech, though technically different' },
      ],
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '元旦',
      'Yuándàn',
      'New Year\'s Day on the solar calendar (January 1). A 1-day public holiday in mainland China, but culturally minor compared to 春节. Important for new-year office parties, fireworks in big cities, and resolution-making, but family-reunion meals are saved for 春节.',
      'word',
      '元旦是公历一月一号。Yuándàn shì gōnglì yīyuè yī hào.',
      '"Yuandan is January 1 on the Gregorian calendar" — useful contrast with 春节 (the lunar new year).',
      null,
      [ACT.vocabularyHolidays],
    ),
    createContentItem(
      '过',
      'guò',
      'The all-purpose verb for "celebrate/spend" a holiday. 过春节 ("celebrate Spring Festival"), 过中秋 ("celebrate Mid-Autumn"), 过生日 ("celebrate a birthday"), 过年 ("celebrate New Year"). Use 过 + holiday name as the default — much more natural than 庆祝 (qìngzhù, formal "celebrate"), which sounds bookish for personal celebrations.',
      'word',
      '今年我在北京过春节。Jīnnián wǒ zài Běijīng guò Chūnjié.',
      '"This year I am celebrating Spring Festival in Beijing" — combines 过 with the V + 在 + place pattern from Grammar III.',
      [
        { target: '过年 guònián', note: '"celebrate New Year"; the default verb for Spring Festival activities' },
        { target: '过节 guòjié', note: '"celebrate a holiday"; generic, can apply to any festival' },
        { target: '庆祝 qìngzhù', note: '"celebrate" (formal); used for official events, anniversaries, ceremonies — sounds stiff for family holidays' },
      ],
      [ACT.vocabularyHolidays],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 4 — Vocabulary II: Foods, activities, greetings
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '饺子',
      'jiǎozi',
      'Dumplings — crescent-shaped pockets of dough filled with ground meat and vegetables. The signature Spring Festival food, especially in northern China. Families wrap them together on New Year\'s Eve (包饺子 bāo jiǎozi) — a major bonding activity. Their shape resembles ancient gold ingots, symbolizing wealth.',
      'word',
      '春节的时候我们一起包饺子。Chūnjié de shíhou wǒmen yìqǐ bāo jiǎozi.',
      '"During Spring Festival we wrap dumplings together" — wrapping is as much the activity as eating.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '汤圆',
      'tāngyuán',
      'Sweet glutinous-rice balls in a light broth — the signature food of Lantern Festival (元宵节). The roundness symbolizes family reunion (团圆 tuányuán — note the shared 圆 character). Common fillings: black sesame, peanut, red bean. Northern variant 元宵 is rolled rather than wrapped.',
      'word',
      '元宵节我们吃汤圆。Yuánxiāo Jié wǒmen chī tāngyuán.',
      '"On Lantern Festival we eat sweet rice balls" — the food and the holiday share the theme of completeness and family unity.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '粽子',
      'zòngzi',
      'Pyramid-shaped pockets of sticky rice with sweet or savory fillings, wrapped in bamboo or reed leaves and steamed. The signature Dragon Boat Festival food. Traditionally thrown into the river to feed fish so they would not eat the body of the drowned poet 屈原. North/south split: savory (meat, salted egg yolk) vs sweet (red bean).',
      'word',
      '端午节大家吃粽子。Duānwǔ Jié dàjiā chī zòngzi.',
      '"On Dragon Boat Festival everyone eats zongzi" — the north-south filling debate is a perennial topic of friendly argument.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '月饼',
      'yuèbǐng',
      'Mooncakes — dense round pastries with sweet fillings (lotus seed paste, red bean, salted egg yolk), eaten during Mid-Autumn Festival. The round shape mirrors the full moon. Modern variations include ice-cream, durian, and ham-and-egg mooncakes. Often given as gifts in elaborate boxes — a major corporate gifting season.',
      'word',
      '中秋节我们吃月饼，赏月。Zhōngqiū Jié wǒmen chī yuèbǐng, shǎngyuè.',
      '"On Mid-Autumn we eat mooncakes and admire the moon" — the two canonical activities of the holiday.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '年糕',
      'niángāo',
      'Sticky rice cake — a Spring Festival sweet. The name 年糕 (niángāo) puns on 年高 (niángāo, "year higher"), so eating it promises rising fortune in the new year. Found in many regional variants: sweet (north), savory and stir-fried (Shanghai), or in 红糖年糕 (brown-sugar steamed cake, south).',
      'word',
      '过年的时候吃年糕，年年高升。Guònián de shíhou chī niángāo, niánnián gāoshēng.',
      '"During New Year we eat niangao to rise higher every year" — the homophone is the whole point of the dish.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '红包',
      'hóngbāo',
      'Red envelope containing cash — traditionally given by elders to children and unmarried adults at Spring Festival, weddings, and birthdays. The red color symbolizes good fortune. Since the mid-2010s, 微信红包 (WeChat digital red envelopes) have transformed the custom: friends and colleagues now exchange them year-round, and "grabbing" group red envelopes is a holiday game.',
      'word',
      '过年的时候大家发红包。Guònián de shíhou dàjiā fā hóngbāo.',
      '"During New Year everyone gives red envelopes" — 发 (fā) is the verb for "issue/give out" red envelopes.',
      [
        { target: '发红包 fā hóngbāo', note: '"give out red envelopes" — the verb used by the giver' },
        { target: '收红包 shōu hóngbāo', note: '"receive red envelopes" — the verb used by the recipient' },
        { target: '微信红包 Wēixìn hóngbāo', note: 'WeChat digital red envelopes; the dominant modern form of the custom' },
      ],
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '团圆饭',
      'tuányuán fàn',
      'The Spring Festival Eve family-reunion dinner — the most important meal of the Chinese year. The whole family gathers, often after long-distance travel; the table is laden with symbolic dishes (fish for surplus, dumplings for wealth). Watching the CCTV gala (春晚) afterward is a national tradition.',
      'word',
      '除夕的晚上全家一起吃团圆饭。Chúxī de wǎnshang quánjiā yìqǐ chī tuányuán fàn.',
      '"On New Year\'s Eve the whole family eats the reunion dinner together" — 除夕 (chúxī) means "New Year\'s Eve".',
      [
        { target: '团圆 tuányuán', note: '"family reunion"; the emotional center of every major Chinese holiday' },
        { target: '除夕 chúxī', note: '"New Year\'s Eve" (the night before 春节); often a more important moment than the day itself' },
      ],
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '春晚',
      'Chūnwǎn',
      'The CCTV New Year Gala — a four-hour variety show broadcast every 除夕 (Spring Festival Eve) since 1983. The most-watched television program on earth, with around 1 billion viewers. Watching it together at the team table after dinner is a near-universal Chinese custom, even if it is widely complained about for being predictable.',
      'word',
      '除夕晚上我们看春晚。Chúxī wǎnshang wǒmen kàn Chūnwǎn.',
      '"On New Year\'s Eve we watch the Spring Festival Gala" — the canonical evening activity.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '春运',
      'chūnyùn',
      'Spring Festival transportation rush — the ~40-day travel period around 春节 when ~3 billion trips are made as urban workers return to hometown villages and cities. The largest annual human migration on earth. Train tickets sell out months in advance and the government runs special schedules across all modes of transport.',
      'word',
      '春运是世界上最大的人口迁移。Chūnyùn shì shìjiè shàng zuì dà de rénkǒu qiānyí.',
      '"Chunyun is the world\'s largest human migration" — a useful explanation for foreign friends asking why Chinese cities empty out in February.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '赏月',
      'shǎngyuè',
      'To admire / appreciate the moon — the canonical Mid-Autumn activity. The verb 赏 (shǎng) means "appreciate aesthetically" and pairs only with a small set of nouns (花 flowers, 月 moon, 雪 snow). Often paired with eating mooncakes outdoors with family.',
      'word',
      '中秋节晚上一家人一起赏月。Zhōngqiū Jié wǎnshang yìjiārén yìqǐ shǎngyuè.',
      '"On Mid-Autumn night the whole family admires the moon together" — outdoor or balcony viewing is traditional.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '放鞭炮',
      'fàng biānpào',
      'To set off firecrackers — a traditional Spring Festival activity to scare away evil spirits and welcome the new year. Now banned or restricted in most large Chinese cities for safety and air-quality reasons, replaced by electronic versions or large municipal fireworks displays.',
      'word',
      '以前过年的时候大家放鞭炮，现在很多城市禁止了。Yǐqián guònián de shíhou dàjiā fàng biānpào, xiànzài hěn duō chéngshì jìnzhǐle.',
      '"In the past everyone set off firecrackers at New Year; now many cities have banned them" — a good register-shifting cultural fact.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '新年快乐',
      'Xīnnián kuàilè',
      'The universal new year greeting — works for both 元旦 (solar) and 春节 (lunar). Literal meaning "new year happiness". Said to anyone you meet around either holiday; safe in all registers from casual to formal.',
      'word',
      '新年快乐! 万事如意! Xīnnián kuàilè! Wànshì rúyì!',
      '"Happy New Year! May all things go as you wish!" — the second phrase 万事如意 is a more elaborate well-wish often appended.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '恭喜发财',
      'Gōngxǐ fācái',
      'A Spring-Festival-specific greeting meaning "congratulations, may you prosper". The standard call-and-response is 恭喜发财，红包拿来! ("Congrats and prosperity — now hand over the red envelope!"), said playfully by children to elders. More culturally specific than 新年快乐.',
      'word',
      '恭喜发财! 红包拿来! Gōngxǐ fācái! Hóngbāo nálái!',
      '"Congrats and prosperity! Red envelope, please!" — the playful child-to-elder phrase you will hear thousands of times during 春节.',
      [
        { target: '恭喜 gōngxǐ', note: '"congratulations"; the same root used in 恭喜你 (congratulations to you)' },
        { target: '发财 fācái', note: '"get rich / prosper"; financial prosperity is a very common Chinese well-wish, reflecting cultural value of business success' },
      ],
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '中秋快乐',
      'Zhōngqiū kuàilè',
      'The standard Mid-Autumn greeting — "Happy Mid-Autumn". Said when giving mooncake gifts, at family gatherings, or in messages. Universal across all registers; the safe default for the holiday.',
      'word',
      '中秋快乐! 阖家团圆! Zhōngqiū kuàilè! Héjiā tuányuán!',
      '"Happy Mid-Autumn! May the whole family reunite!" — the second phrase 阖家团圆 (the formal "whole household reunite") is a common pairing.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),
    createContentItem(
      '端午安康',
      'Duānwǔ ānkāng',
      'The Dragon Boat Festival greeting — note that 安康 (ān kāng, "safety and health") REPLACES the usual 快乐 (kuàilè, "happiness"). This is because 端午 commemorates the suicide of the poet 屈原 and the start of an unlucky season, so wishing happiness was traditionally felt to be in poor taste. Saying 端午快乐 is not strictly wrong but feels tone-deaf to some.',
      'word',
      '端午安康! Duānwǔ ānkāng!',
      '"Wishing you a safe and healthy Dragon Boat Festival" — the culturally appropriate greeting.',
      null,
      [ACT.vocabularyFoodCustoms],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 5 — Grammar I: 是 + 时间 + 的 emphatic
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '是 + 时间 + 的',
      'shì + time + de',
      'The 是…的 frame puts spotlight on a specific detail (time, place, manner, who-with). For times: 是 + time + 的 = "the time is…" or "(it) happened at…". Use it both for one-time events (你是什么时候来的? "When did you come?") and for recurring annual dates (中秋节是什么时候?).',
      'sentence',
      '中秋节是什么时候? — 中秋节是农历八月十五。\nQ: When is Mid-Autumn? A: Mid-Autumn is the 15th of the 8th lunar month.',
      'The most common question-answer pattern for any "when" question about holidays.',
      [
        { target: '是 + 时间 + 的', note: 'the emphatic frame; spotlight on the time information' },
        { target: '是几月几号?', note: '"is what month, what date?" — the standard short form for asking holiday dates' },
        { target: '是星期几?', note: '"is what day of the week?" — for asking weekdays' },
      ],
      [ACT.grammarShiDe],
    ),
    createContentItem(
      '是…的 for past events',
      'shì…de for past events',
      'For past one-time events, 是…的 highlights WHEN/WHERE/HOW something happened, assuming the listener already knows IT happened. 你是什么时候来中国的? ("When did you come to China?") presupposes you DID come; only the time is in question. Drop 是…的 and the sentence becomes neutral.',
      'sentence',
      '你是什么时候来中国的? — 我是去年九月来的。\nQ: When did you come to China? A: I came last September.',
      'A very high-frequency frame; appears in any "when/where/how" question about a known past event.',
      [
        { target: '是 + when + 的', note: 'frames the WHEN of a past event already known to have happened' },
        { target: '是 + where + 的', note: '你是在哪儿出生的? "Where were you born?"' },
        { target: '是 + with whom + 的', note: '你是跟谁一起来的? "Who did you come with?"' },
      ],
      [ACT.grammarShiDe],
    ),
    createContentItem(
      '是…的 for recurring dates',
      'shì…de for recurring annual dates',
      'For RECURRING annual events (holidays, anniversaries), 是…的 is often optional — both 中秋节是八月十五 and 中秋节是八月十五的 are acceptable, with the 的 form slightly more emphatic. For dates with 农历, the 的 is usually omitted in spoken Mandarin.',
      'sentence',
      '国庆节是十月一号。Guóqìng Jié shì shíyuè yī hào.\n春节是农历正月初一。Chūnjié shì nónglì zhēngyuè chū yī.',
      'These are statements of fact; 是 alone is sufficient. The 的 is added only for extra emphasis or contrast.',
      [
        { target: '是 + 月 + 号', note: 'for solar dates: 是十月一号 ("is October 1")' },
        { target: '是农历 + 月 + 日', note: 'for lunar dates: 是农历八月十五 ("is the 15th of the 8th lunar month")' },
        { target: '初一/初二/…', note: 'the special pre-fix 初 is used for days 1–10 of a lunar month: 初一 (1st), 初二 (2nd), … 初十 (10th)' },
      ],
      [ACT.grammarShiDe],
    ),
    createContentItem(
      '什么时候 vs 几月几号',
      'shénme shíhou vs jǐyuè jǐ hào',
      'Two ways to ask "when": 什么时候 is the broad "when" (any time scale — date, year, time of day). 几月几号 is the specific "what month, what date" (precise calendar date). Use 什么时候 when you want flexibility, 几月几号 when you specifically want a date.',
      'sentence',
      '你什么时候来? (any time scale)\n中秋节是几月几号? (specifically date)',
      'A subtle but useful distinction; both are heard daily but they cue different kinds of answers.',
      [
        { target: '什么时候 shénme shíhou', note: 'broad "when"; flexible answer (next week / tonight / in March)' },
        { target: '几月几号 jǐyuè jǐ hào', note: 'specific "what month, what date"; answer must be a calendar date' },
        { target: '星期几 xīngqī jǐ', note: '"what day of the week"; for weekday-specific questions' },
      ],
      [ACT.grammarShiDe],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 6 — Grammar II: 跟 X 一起 + V
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '跟 X 一起 + V',
      'gēn X yìqǐ + V',
      'The "together with X, do V" frame. 跟 (gēn, "with") marks the companion; 一起 (yìqǐ, "together") cements the joint action. The verb follows. 跟家人一起过年 = "celebrate New Year with family". The frame is the standard way to express any joint activity in Mandarin.',
      'sentence',
      '我跟家人一起过年。Wǒ gēn jiārén yìqǐ guònián.',
      '"I celebrate New Year with my family" — the canonical Spring Festival statement.',
      [
        { target: '跟 + X + 一起 + V', note: 'the full frame; X is the companion, V is the joint action' },
        { target: '一起 yìqǐ', note: '"together"; reinforces the joint nature; sometimes optional in fast speech but standard in careful sentences' },
        { target: 'NO 一起 → just companionship', note: '我跟朋友吃饭 = "I eat with friends" — without 一起, it sounds slightly less joint and more like a fact' },
      ],
      [ACT.grammarGenYiqi],
    ),
    createContentItem(
      '跟 vs 和',
      'gēn vs hé',
      '跟 (gēn) and 和 (hé) are largely interchangeable as "with" in this frame. 跟 is more colloquial and northern; 和 slightly more formal/written and pan-regional. In speech, use whichever feels natural; in writing, 和 is the safer default.',
      'sentence',
      '我跟朋友一起去看电影。(more colloquial)\n我和朋友一起去看电影。(more formal/written)\n"I go to see a movie with friends."',
      'Beginners can pick one and stick with it; native speakers freely alternate.',
      [
        { target: '跟 gēn', note: '"with"; colloquial, northern, common in speech' },
        { target: '和 hé', note: '"with/and"; pan-regional, common in writing, also serves as "and" between nouns' },
        { target: '同 tóng', note: '"with"; formal/literary, found in written or polished speech' },
      ],
      [ACT.grammarGenYiqi],
    ),
    createContentItem(
      'Negation: 不跟…一起',
      'bù gēn…yìqǐ',
      'Negate the joint action by placing 不 BEFORE 跟: 我今年不跟家人一起过年 ("this year I am not celebrating with family"). The pattern 不跟 X 一起，跟 Y 一起 is a polite way to substitute one companion for another.',
      'sentence',
      '今年我不跟家人一起过年，我跟朋友一起过。\nJīnnián wǒ bù gēn jiārén yìqǐ guònián, wǒ gēn péngyou yìqǐ guò.',
      '"This year I am not celebrating with family, I am celebrating with friends" — a useful frame for any explanation of changed plans.',
      [
        { target: '不跟 X 一起', note: 'negates the companion; 不 goes BEFORE 跟' },
        { target: 'X，Y 一起 contrast', note: '"not with X, with Y" — the natural substitution pattern' },
      ],
      [ACT.grammarGenYiqi],
    ),
    createContentItem(
      '跟…一起 questions',
      'gēn…yìqǐ questions',
      'To ask WHO someone celebrates with, use 跟谁一起 + V: 你跟谁一起过年? ("Who are you celebrating New Year with?"). The question word 谁 (shéi/shuí) stays in the same position as the answer noun — Mandarin keeps question-word position consistent.',
      'sentence',
      'Q: 你跟谁一起过中秋节? — A: 我跟我的家人一起过。\nQ: Who do you celebrate Mid-Autumn with? A: I celebrate it with my family.',
      'Standard exchange around any holiday topic; one of the first questions Chinese friends will ask you.',
      [
        { target: '跟谁一起 + V?', note: '"with whom together do V?"; the question form' },
        { target: '跟…一起 + V', note: 'the answer keeps the same word order, just swapping 谁 for the actual companion' },
      ],
      [ACT.grammarGenYiqi],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 7 — Grammar III: V + 在 + place
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      'V + 在 + place',
      'V + zài + place',
      'The V + 在 + place pattern: the verb comes FIRST, then 在 (zài, "at/in"), then the place. This word order emphasizes the action; the place is incidental information. 我住在北京 ("I live in Beijing") — the focus is on living, with Beijing as the location.',
      'sentence',
      '我住在北京。Wǒ zhù zài Běijīng.\n他出生在上海。Tā chūshēng zài Shànghǎi.',
      '"I live in Beijing" / "He was born in Shanghai" — the V + 在 + place order is common with stative verbs (live, stay, sit, stand).',
      [
        { target: 'V + 在 + place', note: 'verb first, then location — emphasizes the action' },
        { target: '住在 zhù zài', note: '"live at"; one of the most common V + 在 combinations' },
        { target: '坐在 zuò zài', note: '"sit at"; describing seated position' },
      ],
      [ACT.grammarVZai],
    ),
    createContentItem(
      '在 + place + V (alternative)',
      'zài + place + V (alternative)',
      'Alternative word order: 在 + place + V (preverbal). 我在北京住 also works but is less common than 我住在北京. The preverbal 在 + place + V order is preferred when the location is the FOCUS (e.g., contrasting with another place). 我在家吃月饼 ("I eat mooncakes AT HOME (not outside)").',
      'sentence',
      '我在家吃月饼。(preverbal — place is focus)\n我吃月饼在家。(ungrammatical — this order is WRONG with eat-type verbs)',
      'Caution: for action verbs (eat, drink, work, study), preverbal 在…V is the SAFER default; V + 在 is mostly used with stative verbs.',
      [
        { target: '在 + place + V', note: 'preverbal location; the safer order for action verbs; emphasizes the place' },
        { target: 'V + 在 + place', note: 'postverbal location; used with stative verbs (live, sit, stand, be located)' },
        { target: 'rule of thumb', note: 'for "eat / study / work / play", use 在 + place + V; for "live / sit / stand", use V + 在 + place' },
      ],
      [ACT.grammarVZai],
    ),
    createContentItem(
      '哪儿 / 哪里 — where',
      'nǎr / nǎlǐ — where',
      'Ask "where" with 哪儿 (nǎr, northern colloquial) or 哪里 (nǎlǐ, southern / written). Both occupy the same position as the answer place. 你在哪儿过年? ("Where are you celebrating New Year?") — answer: 我在北京过年.',
      'sentence',
      '你在哪儿过中秋节? — 我在清华过。\nWhere are you celebrating Mid-Autumn? — I am celebrating it at Tsinghua.',
      'A very high-frequency holiday question; the answer simply replaces 哪儿 with the actual place.',
      [
        { target: '哪儿 nǎr', note: '"where"; northern colloquial, common in Beijing and Mainland speech' },
        { target: '哪里 nǎlǐ', note: '"where"; southern / Taiwan / written; both forms are universally understood' },
        { target: '在哪儿过 zài nǎr guò', note: '"celebrate where" — the holiday-specific use of 在 + place + V' },
      ],
      [ACT.grammarVZai],
    ),
    createContentItem(
      'Holiday location patterns',
      'holiday + 在 + place patterns',
      'High-frequency holiday + place sentence patterns: 在家过 (celebrate at home), 在北京过 (celebrate in Beijing), 在学校过 (celebrate at school), 在朋友家过 (celebrate at a friend\'s house). The verb 过 (guò) is the all-purpose "spend/celebrate".',
      'sentence',
      '今年我在清华过中秋节，因为我不能回家。\nJīnnián wǒ zài Qīnghuá guò Zhōngqiū Jié, yīnwèi wǒ bù néng huíjiā.',
      '"This year I am celebrating Mid-Autumn at Tsinghua because I cannot go home" — a common situation for international students.',
      [
        { target: '在家过 zài jiā guò', note: '"celebrate at home"; the default expectation for major holidays' },
        { target: '在朋友家过', note: '"celebrate at a friend\'s house"; common when away from family' },
        { target: '回家过 huíjiā guò', note: '"go home and celebrate"; the 春运 migration captures exactly this verb' },
      ],
      [ACT.grammarVZai],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 8 — Reading & Speaking
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '我的中秋节',
      'Wǒ de Zhōngqiū Jié',
      'A 6-sentence Mid-Autumn blog post. Read it aloud with correct tones, sandhi, and natural rhythm. Notice how the writer uses 是…的, 跟…一起, and 在…过 — the three grammar patterns from this lesson — to anchor the description.',
      'sentence',
      '今天是中秋节。中秋节是农历八月十五，是中国一个很重要的节日。今年我在清华大学过中秋节。我跟我的朋友一起吃月饼、赏月。我们也跟家人视频聊天。月亮很圆，很漂亮。我希望明年可以跟家人一起过。',
      'Translation: "Today is Mid-Autumn. Mid-Autumn is the 15th of the 8th lunar month, a very important Chinese holiday. This year I celebrated Mid-Autumn at Tsinghua. I ate mooncakes and admired the moon with my friends. We also video-chatted with family. The moon was round and beautiful. I hope next year I can celebrate it with my family."',
      [
        { target: '是中国一个很重要的节日', note: '"is a very important Chinese holiday"; the 是 + noun phrase + 的 structure' },
        { target: '在清华大学过中秋节', note: '"celebrate Mid-Autumn at Tsinghua University"; the 在 + place + V pattern' },
        { target: '跟我的朋友一起', note: '"with my friends together"; the 跟 X 一起 frame' },
        { target: '视频聊天 shìpín liáotiān', note: '"video chat"; a near-universal modern Chinese family practice during holidays' },
        { target: '希望 xīwàng', note: '"hope"; common verb to close a reflection or wish' },
      ],
      [ACT.reading],
    ),
    createContentItem(
      '阅读理解',
      'yuèdú lǐjiě',
      'Four standard comprehension questions matching the paragraph. Answer each in a short sentence using the 是 / 是…的 / 跟…一起 patterns from this lesson.',
      'sentence',
      'Q1: 中秋节是几月几号? Q2: 作者在哪儿过中秋节? Q3: 作者跟谁一起过节? Q4: 作者希望明年怎么过?',
      'Q1 asks the date, Q2 the place, Q3 the companion, Q4 the wish — covering the four grammar patterns of this lesson.',
      [
        { target: 'A1: 中秋节是农历八月十五。', note: 'date answer using 是 + date; the 农历 prefix marks lunar calendar' },
        { target: 'A2: 作者在清华大学过中秋节。', note: 'place answer using 在 + place + V' },
        { target: 'A3: 作者跟朋友一起过节。', note: 'companion answer using 跟 X 一起 frame' },
        { target: 'A4: 作者希望明年跟家人一起过。', note: 'combines hope verb + 跟 X 一起 frame' },
      ],
      [ACT.reading],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 9 — Listening & Speaking
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '春节计划',
      'Chūnjié jìhuà',
      'A 7-turn dialogue between Wang Wei (Chinese student) and Sarah (foreign classmate) at Tsinghua a week before Spring Festival. Covers all three grammar patterns plus holiday vocabulary in a natural conversational flow.',
      'conversation',
      '王伟: 莎拉，下周就是春节了，你有什么计划?\n莎拉: 我还没决定。春节是几月几号?\n王伟: 今年春节是二月十号。是中国最重要的节日!\n莎拉: 你回家过年吗?\n王伟: 当然，我要回北京跟家人一起过。我们家除夕一起吃团圆饭、看春晚、发红包。莎拉，你要不要跟我一起回家?\n莎拉: 真的吗? 我可以吗?\n王伟: 当然可以! 我妈妈做的饺子特别好吃。',
      'A typical campus invitation; international students invited to a Chinese friend\'s family for Spring Festival is a very common and welcomed gesture.',
      [
        { target: '春节是几月几号?', note: 'the canonical "when is Spring Festival?" question using 是 + date' },
        { target: '回家过年', note: '"go home and celebrate New Year"; the canonical Spring Festival phrase' },
        { target: '跟家人一起过', note: '"celebrate together with family"; the 跟 X 一起 + V frame' },
        { target: '吃团圆饭、看春晚、发红包', note: 'three-part list of standard 除夕 (New Year\'s Eve) activities' },
        { target: '跟我一起回家?', note: '"come home with me?"; the inviting form of 跟…一起 + V' },
      ],
      [ACT.listening],
    ),
    createContentItem(
      '中秋节邀请',
      'Zhōngqiū Jié yāoqǐng',
      'A shorter 5-turn dialogue for Mid-Autumn invitation. Notice the lighter register — Mid-Autumn at a friend\'s house is less of a big deal than Spring Festival, so the invitation is more casual.',
      'conversation',
      '李明: 这周末是中秋节，你有空吗?\n汤姆: 有空。中秋节有什么活动?\n李明: 我们一般跟家人一起吃月饼、赏月。我家人今年不在北京，所以我跟同学一起在宿舍过。你也来吧!\n汤姆: 好啊! 我可以带什么?\n李明: 带一盒月饼就行。中秋快乐!',
      '"This weekend is Mid-Autumn, are you free?" — a casual student-to-student invitation; appropriate among peers.',
      [
        { target: '一般跟家人一起', note: '"usually together with family"; the canonical Mid-Autumn norm' },
        { target: '在宿舍过', note: '"celebrate in the dorm"; common alternative when away from family — uses 在 + place + V' },
        { target: '带一盒月饼', note: '"bring a box of mooncakes"; the standard contribution when visiting for Mid-Autumn' },
        { target: '中秋快乐!', note: 'the standard Mid-Autumn greeting; said as a parting wish or message close' },
      ],
      [ACT.listening],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 10 — Writing
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '写作模板 — 比较节日',
      'xiězuò múbǎn — bǐjiào jiérì',
      'A reusable 5-sentence template for comparing a holiday from your country with a Chinese holiday. Fill the slots with your own information; the structure carries the rest.',
      'sentence',
      '在我的国家，我们有一个重要的节日叫 [节日名字]。它是 [日期]。这个节日我们一般跟 [家人/朋友] 一起 [活动]。我们吃 [食物]。它跟中国的 [中国节日] 有点像，但是 [差异].',
      'Five sentences cover: introduction + date + companion + food + comparison — the minimum complete cultural comparison.',
      [
        { target: '[节日名字]', note: 'the name of your country\'s holiday in Chinese transliteration or translation (感恩节 Thanksgiving, 圣诞节 Christmas, 排灯节 Diwali)' },
        { target: '[日期]', note: 'date using 是 + month + day pattern' },
        { target: '[家人/朋友]', note: 'companion using 跟 X 一起 frame' },
        { target: '[活动]', note: 'verb describing the central activity (吃 X / 看 X / 玩 X)' },
        { target: '[食物]', note: 'signature holiday food from your country' },
        { target: '[差异]', note: 'one specific difference — date, food, or activity — keeps the comparison concrete' },
      ],
      [ACT.writing],
    ),
    createContentItem(
      '写作练习',
      'xiězuò liànxí',
      'Write your own 4–5 sentence comparison in Hanzi using the template. Use 是…的 at least once, 跟…一起 at least once, and 在…过 at least once so the writing demonstrates the core grammar of this lesson.',
      'sentence',
      '示例: 在我的国家，我们有感恩节。感恩节是十一月的第四个星期四。这一天我们跟家人一起在家吃火鸡。它跟中秋节有点像，都是家人团圆的节日，但是我们不吃月饼。',
      'Translation: "In my country we have Thanksgiving. Thanksgiving is the fourth Thursday of November. On this day we eat turkey at home with family. It is a bit like Mid-Autumn — both are family-reunion holidays — but we do not eat mooncakes."',
      null,
      [ACT.writing],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 11 — Culture Note
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '春节 vs 元旦',
      'Chūnjié vs Yuándàn',
      'Two different "new years" coexist in China. 元旦 (Yuándàn, January 1) is the solar new year — a 1-day public holiday, but culturally minor. 春节 (Chūnjié, the lunar new year, late January or February) is the BIG one — the 7-day Golden Week, the family reunion dinner, the red envelopes, the world\'s largest annual migration. When Chinese people say "过年" they almost always mean 春节, not 元旦.',
      'sentence',
      '元旦是公历一月一号，春节是农历正月初一 — 两个都叫新年，但春节才是真正的家庭团圆节日。',
      '"Yuandan is January 1 on the solar calendar; Spring Festival is the 1st of the 1st lunar month — both are called New Year, but Spring Festival is the real family-reunion holiday."',
      [
        { target: '元旦 Yuándàn', note: 'solar new year (January 1); 1-day holiday, culturally minor' },
        { target: '春节 Chūnjié', note: 'lunar new year (late Jan/early Feb); 7-day Golden Week, the major family-reunion holiday' },
        { target: '团圆饭 tuányuán fàn', note: 'New Year\'s Eve family-reunion dinner; the emotional and culinary peak of 春节' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      '春运',
      'chūnyùn',
      'The Spring Festival travel rush — ~40 days around 春节 when ~3 billion trips are made nationwide. The world\'s largest annual human migration. Urban migrant workers return to their hometown villages, students return from universities, and city offices empty out. Train tickets sell out within minutes of opening; the government runs special schedules and adds temporary capacity across rail, road, and air.',
      'sentence',
      '春运是世界上最大的人口迁移。每年大约有30亿次出行。\nChūnyùn shì shìjiè shàng zuì dà de rénkǒu qiānyí. Měi nián dàyuē yǒu 30 yì cì chūxíng.',
      '"Chunyun is the world\'s largest human migration. Around 3 billion trips are made each year." — a useful fact for explaining the scale of Spring Festival to foreigners.',
      [
        { target: '春运 chūnyùn', note: '"Spring Festival transportation"; the migration period itself' },
        { target: '抢票 qiǎngpiào', note: '"grab tickets"; the competitive online ticket-buying ritual that opens 60 days before each travel date' },
        { target: '回家 huíjiā', note: '"go home"; the verb that captures the whole migration in two characters' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      '红包 (现金 → 微信)',
      'hóngbāo (cash → WeChat)',
      'Red envelopes started as physical red paper packets of cash given by elders to children at Spring Festival. Since 2014, when WeChat launched its 微信红包 feature, the custom has been transformed: now friends, colleagues, and family members exchange digital red envelopes year-round, especially in WeChat groups. "Grabbing" group red envelopes (抢红包) at midnight on New Year\'s Eve has become a major holiday game, with billions of envelopes sent.',
      'sentence',
      '现在大家用微信红包过年 — 一秒钟就能发出去。Xiànzài dàjiā yòng Wēixìn hóngbāo guònián — yī miǎozhōng jiù néng fā chūqù.',
      '"Now everyone uses WeChat red envelopes for New Year — you can send one in a second" — a sentence that captures the modernization of the tradition.',
      [
        { target: '红包 hóngbāo', note: 'traditional red envelope; physical paper version still used at weddings and for children' },
        { target: '微信红包', note: 'WeChat digital red envelope; the dominant modern form' },
        { target: '抢红包 qiǎng hóngbāo', note: '"grab red envelopes"; the competitive game in WeChat groups where the fastest tappers get the biggest shares' },
      ],
      [ACT.culture],
    ),
    createContentItem(
      '黄金周',
      'huángjīn zhōu',
      'Golden Week — the 7-day national vacations attached to 春节 (late Jan/Feb) and 国庆节 (Oct 1). Established in 1999 to boost domestic tourism, they are the two main times when most Chinese workers get extended time off. The result: massive crowds at tourist sites, sold-out trains and flights, and a quarter of annual domestic tourism revenue concentrated in these two weeks.',
      'sentence',
      '十一黄金周大家都去旅游，景点人很多。Shíyī huángjīn zhōu dàjiā dōu qù lǚyóu, jǐngdiǎn rén hěn duō.',
      '"During the National Day Golden Week everyone travels, scenic spots are very crowded" — a typical observation about the holiday.',
      [
        { target: '黄金周 huángjīn zhōu', note: '"golden week"; the 7-day national vacation' },
        { target: '十一 shí yī', note: '"the 10-1"; nickname for 国庆节 and its Golden Week' },
        { target: '景点 jǐngdiǎn', note: '"scenic spot / tourist attraction"; major Golden Week destination type' },
      ],
      [ACT.culture],
    ),

    // ────────────────────────────────────────────────────────────────────
    // Activity 12 — Task / Consolidation
    // ────────────────────────────────────────────────────────────────────
    createContentItem(
      '任务: 给外国朋友介绍中国节日',
      'rènwù: gěi wàiguó péngyou jièshào Zhōngguó jiérì',
      'Roleplay: a foreign classmate at Tsinghua asks you to explain a Chinese holiday they have never heard of. Pick one (春节, 中秋节, 端午节, or 元宵节), explain the date, food, and activity, then invite them to celebrate together. Use every skill from this lesson in one continuous scene.',
      'conversation',
      '[Tsinghua, cafeteria, a week before 中秋节]\n外国同学: 我看到很多月饼。中秋节是什么?\n你: [explain what 中秋节 is + give the date using 是 + 时间 + 的]\n外国同学: 这一天你们做什么?\n你: [explain food + activity using 吃 / 赏月 / 跟家人一起]\n外国同学: 听起来很好。你今年在哪儿过?\n你: [answer using 在 + place + 过]\n外国同学: 我也很想试试月饼。\n你: [invite them using 跟我一起 + V + the appropriate greeting]',
      'Six turns of fluent exchange; the tutor will prompt you and respond naturally. Use 是…的, 跟…一起, and 在…过 at least once each.',
      [
        { target: 'introduce holiday', note: '是 + name + 的 + 节日 — frame the holiday\'s identity' },
        { target: 'date', note: '是 + 农历/公历 + month + day + 的 — give the calendar date' },
        { target: 'food + activity', note: '吃 X、做 Y — pair signature food with central activity' },
        { target: 'where', note: '在 + place + 过 — answer the location question' },
        { target: 'invite', note: '跟我一起 + V — close with an invitation' },
        { target: 'greeting', note: '中秋快乐 / 新年快乐 / 端午安康 — match greeting to holiday' },
      ],
      [ACT.task],
    ),
    createContentItem(
      '挑战 — 比较两个节日',
      'tiǎozhàn — bǐjiào liǎng gè jiérì',
      'Stretch goal: in the same conversation, the foreign friend asks "你们国家有没有类似的节日?" ("Does your country have a similar holiday?"). Compare ONE Chinese holiday with a holiday from your country: similar in WHAT (family reunion, food, date pattern), different in WHAT (specific food, specific activity).',
      'conversation',
      '外国同学: 你们国家有没有类似的节日?\n你: 有。我们国家有 [节日 X], 跟中秋节有点像 — 我们也跟家人一起吃饭。但是我们不吃月饼，我们吃 [food]。日期也不一样，[节日 X] 是 [日期].',
      '"My country has [holiday X], it is a bit like Mid-Autumn — we also eat with family. But we do not eat mooncakes, we eat [food]. The date is also different, [X] is on [date]." — a model of comparison that uses parallel structure.',
      [
        { target: '跟 X 有点像', note: '"a bit similar to X"; the standard comparison opener' },
        { target: '也跟家人一起 V', note: '"also with family do V"; uses 也 to mark a shared trait' },
        { target: '但是…不一样', note: '"but…different"; standard contrast frame' },
        { target: 'parallel structure', note: 'mirror the original sentence pattern when describing the comparison item — makes the contrast clearer' },
      ],
      [ACT.task],
    ),
  ],
};

module.exports = lesson;
