// Level 1 Unit 5 — Life in Korea & first impressions
// Source: Book 1B·5 (한국 생활이 어때요?)
// Functions: sharing opinions about life in Korea, asking 어때요?

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u5-orientation',
  pronunciation: 'l1u5-pronunciation',
  vocabularyAdjectives: 'l1u5-vocab-adj',
  vocabularyLife: 'l1u5-vocab-life',
  grammarHow: 'l1u5-grammar-how',
  grammarAdjective: 'l1u5-grammar-adj',
  grammarLike: 'l1u5-grammar-like',
  reading: 'l1u5-reading',
  listening: 'l1u5-listening',
  writing: 'l1u5-writing',
  culture: 'l1u5-culture',
  task: 'l1u5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Ask 어때요? to invite an opinion.', 'Share opinions about Korean food, weather, people, and language.', 'Say what you like and dislike with 좋아하다 / 싫어하다.'],
    task: 'Imagine a Korean friend asks how your life in Korea is going.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Sound changes in adjectives',
    goals: ['Apply ㅎ-deletion in 좋아요 → [조아요].', 'Handle ㅂ-irregular conjugations: 맵다 → 매워요, 어렵다 → 어려워요.'],
    task: 'Read each adjective form aloud.' },
  { id: ACT.vocabularyAdjectives, section: 'Vocabulary I', title: 'Adjectives for opinions',
    goals: ['Learn 15+ descriptive adjectives in opposing pairs.'],
    task: 'Pick five and use each in a short sentence.' },
  { id: ACT.vocabularyLife, section: 'Vocabulary II', title: 'Life-in-Korea topics',
    goals: ['Use 음식·날씨·사람들·학교·기숙사·집·물가·교통 as topic nouns.'],
    task: 'List the three topics you have the strongest opinions about.' },
  { id: ACT.grammarHow, section: 'Grammar I', title: 'N이/가 어때요? — How is N?',
    goals: ['Invite an opinion about any topic.', 'Answer with adjective + -아/어요.'],
    task: 'Make three N이/가 어때요? questions and answer each.' },
  { id: ACT.grammarAdjective, section: 'Grammar II', title: 'Adjective conjugation + ㅂ-irregular',
    goals: ['Conjugate regular adjectives like verbs (ㅏ/ㅗ → -아요, else → -어요).', 'Handle ㅂ-irregular: 맵다 → 매워요, 어렵다 → 어려워요, 쉽다 → 쉬워요.'],
    task: 'Conjugate five adjectives, including at least two ㅂ-irregular.' },
  { id: ACT.grammarLike, section: 'Grammar III', title: '좋다 vs 좋아하다 (and 싫다 vs 싫어하다)',
    goals: ['Use 좋다 (adjective: "be good"): N이/가 좋아요.', 'Use 좋아하다 (verb: "like"): N을/를 좋아해요.', 'Same distinction for 싫다 / 싫어하다.'],
    task: 'Use each form correctly in two sentences each.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A foreign student\'s impressions',
    goals: ['Read a short opinion paragraph.', 'Identify which things the writer likes/finds difficult.'],
    task: 'Answer comprehension questions.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Trading impressions',
    goals: ['Follow a 4-turn opinion exchange.', 'Reproduce with your own opinions.'],
    task: 'Tell the AI tutor one thing you like and one thing that is hard.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Your first impressions',
    goals: ['Write 4-5 sentences sharing what you like and find difficult about Korea.'],
    task: 'Write your own first-impressions paragraph.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Politeness levels: 반말 / 존댓말',
    goals: ['Understand 반말 (casual), -아/어요 (polite), -ㅂ니다 (formal).', 'Know who you should NEVER use 반말 with.'],
    task: 'Decide which form fits a job interview, a chat with a classmate, and a chat with a younger sibling.' },
  { id: ACT.task, section: 'Task', title: '과제 — Share your first month in Korea',
    goals: ['Combine vocabulary, adjective conjugation, and 좋아하다 in one continuous scene.'],
    task: 'Roleplay sharing your first month with the AI tutor.' },
];

const lesson = {
  title: '레벨 1 · 5과: 한국 생활이 어때요? (Life in Korea)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'sharing-opinion', label: 'Sharing opinions', goal: 'Use adjective -아/어요 to share a short opinion.' },
    { id: 'asking-how-is', label: 'Asking how something is', goal: 'Use N이/가 어때요? to invite an opinion.' },
    { id: 'saying-what-you-like', label: 'Saying what you like', goal: 'Use N을/를 좋아해요 and N이/가 좋아요 correctly.' },
  ],
  relatedPools: ['topic-people', 'topic-society', 'topic-food'],
  content: [
    createContentItem('Lesson goal', 'opinions', 'By end: trade opinions about life in Korea, conjugate adjectives, distinguish 좋다 vs 좋아하다.', 'word', 'Functions: ask · share opinion · state preference', 'Three skills that unlock conversational opinions.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'one-month chat', 'A Korean classmate asks how you have been finding life in Korea.', 'word', 'Classmate: 한국 생활이 어때요? — You: 재미있어요. 그런데 음식이 좀 매워요.', 'Classmate: How is life in Korea? — You: It is fun. But the food is a bit spicy.', null, [ACT.orientation]),

    createContentItem('좋아요 → [조아요]', 'joayo', 'ㅎ-deletion: the ㅎ받침 of 좋 disappears before 아.', 'word', '날씨가 좋아요. → [날씨가 조아요]', 'The weather is nice.', null, [ACT.pronunciation]),
    createContentItem('맵다 → 매워요', 'maewoyo', 'ㅂ-irregular: ㅂ at the end of an adjective stem changes to ㅜ + 어요 → 워요.', 'word', '음식이 매워요.', 'The food is spicy.', [{ korean: '맵 + 어요', english: 'ㅂ → 우 → 매우어요 → 매워요' }], [ACT.pronunciation]),
    createContentItem('어렵다 → 어려워요', 'eoryeowoyo', 'Same ㅂ-irregular rule.', 'word', '한국어가 어려워요.', 'Korean is difficult.', null, [ACT.pronunciation]),
    createContentItem('쉽다 → 쉬워요', 'swiwoyo', 'ㅂ-irregular.', 'word', '문제가 쉬워요.', 'The problem is easy.', null, [ACT.pronunciation]),
    createContentItem('어때요? → [어때요]', 'eottaeyo', 'No change — but stress the 때 syllable for a natural rhythm.', 'word', '한국 생활이 어때요?', 'How is life in Korea?', null, [ACT.pronunciation]),

    createContentItem('재미있다', 'jaemiitda', 'to be fun / interesting', 'word', '한국어 공부가 재미있어요.', 'Studying Korean is fun.', null, [ACT.vocabularyAdjectives]),
    createContentItem('재미없다', 'jaemieopda', 'to be boring', 'word', '그 영화는 재미없어요.', 'That movie is boring.', null, [ACT.vocabularyAdjectives]),
    createContentItem('맛있다', 'masitda', 'to be delicious', 'word', '김치찌개가 맛있어요.', 'Kimchi stew is delicious.', null, [ACT.vocabularyAdjectives]),
    createContentItem('맛없다', 'maseopda', 'to taste bad', 'word', '이 음식은 좀 맛없어요.', 'This food does not taste good.', null, [ACT.vocabularyAdjectives]),
    createContentItem('맵다', 'maepda', 'to be spicy', 'word', '한국 음식은 좀 매워요.', 'Korean food is a bit spicy.', null, [ACT.vocabularyAdjectives]),
    createContentItem('짜다', 'jjada', 'to be salty', 'word', '국이 좀 짜요.', 'The soup is a bit salty.', null, [ACT.vocabularyAdjectives]),
    createContentItem('달다', 'dalda', 'to be sweet', 'word', '케이크가 달아요.', 'The cake is sweet.', null, [ACT.vocabularyAdjectives]),
    createContentItem('어렵다', 'eoryeopda', 'to be difficult', 'word', '한국어 문법이 좀 어려워요.', 'Korean grammar is a bit difficult.', null, [ACT.vocabularyAdjectives]),
    createContentItem('쉽다', 'swipda', 'to be easy', 'word', '이 문제는 쉬워요.', 'This problem is easy.', null, [ACT.vocabularyAdjectives]),
    createContentItem('좋다', 'jota', 'to be good', 'word', '오늘 날씨가 좋아요.', 'The weather is nice today.', null, [ACT.vocabularyAdjectives]),
    createContentItem('나쁘다', 'nappeuda', 'to be bad', 'word', '날씨가 좀 나빠요.', 'The weather is a bit bad.', null, [ACT.vocabularyAdjectives]),
    createContentItem('친절하다', 'chinjeolhada', 'to be kind', 'word', '교수님이 친절하세요.', 'The professor is kind.', null, [ACT.vocabularyAdjectives]),
    createContentItem('바쁘다', 'bappeuda', 'to be busy', 'word', '요즘 너무 바빠요.', 'I am very busy these days.', null, [ACT.vocabularyAdjectives]),
    createContentItem('비싸다', 'bissada', 'to be expensive', 'word', '서울 집은 비싸요.', 'Houses in Seoul are expensive.', null, [ACT.vocabularyAdjectives]),
    createContentItem('싸다', 'ssada', 'to be cheap', 'word', '편의점 도시락은 싸요.', 'Convenience-store meals are cheap.', null, [ACT.vocabularyAdjectives]),
    createContentItem('덥다', 'deopda', 'to be hot (weather)', 'word', '여름이 너무 더워요.', 'Summer is very hot.', null, [ACT.vocabularyAdjectives]),
    createContentItem('춥다', 'chupda', 'to be cold (weather)', 'word', '겨울이 정말 추워요.', 'Winter is really cold.', null, [ACT.vocabularyAdjectives]),

    createContentItem('한국 생활', 'hanguk saenghwal', 'life in Korea', 'word', '한국 생활이 재미있어요.', 'Life in Korea is fun.', null, [ACT.vocabularyLife]),
    createContentItem('음식', 'eumsik', 'food', 'word', '한국 음식이 맛있어요.', 'Korean food is delicious.', null, [ACT.vocabularyLife]),
    createContentItem('날씨', 'nalssi', 'weather', 'word', '오늘 날씨가 좋아요.', 'The weather is nice today.', null, [ACT.vocabularyLife]),
    createContentItem('사람들', 'saramdeul', 'people', 'word', '한국 사람들이 친절해요.', 'Korean people are kind.', null, [ACT.vocabularyLife]),
    createContentItem('학교', 'hakgyo', 'school', 'word', '우리 학교가 커요.', 'Our school is big.', null, [ACT.vocabularyLife]),
    createContentItem('기숙사', 'gisuksa', 'dormitory', 'word', '기숙사가 깨끗해요.', 'The dorm is clean.', null, [ACT.vocabularyLife]),
    createContentItem('물가', 'mulga', 'cost of living / prices', 'word', '한국 물가가 좀 비싸요.', 'Prices in Korea are a bit high.', null, [ACT.vocabularyLife]),
    createContentItem('교통', 'gyotong', 'transportation / traffic', 'word', '한국 교통이 편해요.', 'Transportation in Korea is convenient.', null, [ACT.vocabularyLife]),
    createContentItem('한국어 공부', 'hangugeo gongbu', 'studying Korean', 'word', '한국어 공부가 어려워요.', 'Studying Korean is difficult.', null, [ACT.vocabularyLife]),

    createContentItem('N이/가 어때요?', 'eottaeyo', 'Ask an opinion about any noun. Uses subject 이/가.', 'sentence', '한국 생활이 어때요?', 'How is life in Korea?',
      [{ korean: '한국 생활이', english: 'life in Korea + subject' }, { korean: '어때요?', english: 'how is it? (polite opinion)' }], [ACT.grammarHow]),
    createContentItem('Answer template', 'N은/는 + 형용사', 'Switch the subject to a topic 은/는 and add an adjective.', 'sentence', '한국 생활은 정말 재미있어요.', 'Life in Korea is really fun.',
      [{ korean: '한국 생활은', english: 'life in Korea (topic, switched)' }, { korean: '정말 재미있어요', english: 'really fun' }], [ACT.grammarHow]),
    createContentItem('Soft answer with 좀', 'jom', 'Use 좀 (a bit) to soften a negative opinion politely.', 'sentence', '음식은 맛있어요. 그런데 좀 매워요.', 'The food is delicious. But it is a bit spicy.',
      [{ korean: '좀', english: 'a bit (softener)' }, { korean: '그런데', english: 'but / however' }], [ACT.grammarHow]),

    createContentItem('Regular adjectives', '-아요/-어요', 'Conjugate adjectives exactly like verbs.', 'sentence', '좋다 → 좋아요 · 작다 → 작아요 · 재미있다 → 재미있어요', 'Same -아/어요 rule.',
      [{ korean: '좋 (ㅗ) + 아요', english: '→ 좋아요' }, { korean: '재미있 (ㅣ) + 어요', english: '→ 재미있어요' }], [ACT.grammarAdjective]),
    createContentItem('ㅂ-irregular adjectives', '쉽다 → 쉬워요', 'When the stem ends in ㅂ, the ㅂ changes to 우 and combines with 어요 → -워요.', 'sentence', '쉽다 → 쉬워요 · 어렵다 → 어려워요 · 맵다 → 매워요 · 춥다 → 추워요 · 덥다 → 더워요', 'Memorize the pattern.',
      [{ korean: '맵 + 어요', english: 'ㅂ → 우 → 매우어요 → 매워요' }, { korean: '어렵 + 어요', english: '어려우어요 → 어려워요' }], [ACT.grammarAdjective]),
    createContentItem('Other irregulars to know', '바쁘다 → 바빠요', '으-irregular: when the stem\'s last vowel is ㅡ, drop the ㅡ before -아/어요.', 'sentence', '바쁘다 → 바빠요 · 예쁘다 → 예뻐요 · 크다 → 커요', 'Drop the ㅡ.',
      [{ korean: '바쁘 → 바ㅃ + 아요 (because previous vowel ㅏ)', english: '→ 바빠요' }, { korean: '예쁘 → 예ㅃ + 어요 (no ㅏ/ㅗ before)', english: '→ 예뻐요' }], [ACT.grammarAdjective]),

    createContentItem('좋다 — "to be good"', 'jota (adjective)', 'Subject + 이/가 + 좋아요. The thing IS good.', 'sentence', '한국 음식이 좋아요.', 'Korean food is good (= I like Korean food).',
      [{ korean: '한국 음식이', english: 'Korean food + subject 이' }, { korean: '좋아요', english: 'is good' }], [ACT.grammarLike]),
    createContentItem('좋아하다 — "to like"', 'joahada (verb)', 'Topic + N + 을/를 + 좋아해요. The person LIKES the thing.', 'sentence', '저는 한국 음식을 좋아해요.', 'I like Korean food.',
      [{ korean: '저는', english: 'I (topic)' }, { korean: '한국 음식을', english: 'Korean food + OBJECT 을' }, { korean: '좋아해요', english: 'like (verb)' }], [ACT.grammarLike]),
    createContentItem('싫다 vs 싫어하다', 'same pattern, negative', 'Same distinction: 싫다 = "to be unpleasant" (with 이/가), 싫어하다 = "to dislike" (with 을/를).', 'sentence', '저는 매운 음식이 싫어요. = 저는 매운 음식을 싫어해요.', 'I dislike spicy food.',
      [{ korean: '~이/가 싫어요', english: 'is unpleasant to me' }, { korean: '~을/를 싫어해요', english: 'I dislike ~' }], [ACT.grammarLike]),
    createContentItem('Common mistake', '좋아요 vs 좋아해요', 'A is good (좋아요) vs I like A (좋아해요). Particle changes too — 이/가 vs 을/를.', 'sentence', '커피가 좋아요. (Coffee is good.) vs 저는 커피를 좋아해요. (I like coffee.)', 'Same idea, different grammar.', null, [ACT.grammarLike]),

    createContentItem('A foreign student\'s impressions', 'reading',
      'Read aloud, then answer the questions.',
      'sentence',
      '저는 사라예요. 미국에서 왔어요. 한국에 온 지 한 달이 됐어요. 한국 사람들은 정말 친절해요. 음식도 맛있어요. 김치찌개를 좋아해요. 그런데 좀 매워요. 한국어 공부는 어려워요. 그래도 재미있어서 매일 공부해요.',
      'I am Sarah. I came from the USA. It has been a month since I arrived in Korea. Korean people are really kind. The food is also delicious. I like kimchi stew. But it is a bit spicy. Studying Korean is difficult. But it is fun, so I study every day.',
      [
        { korean: '한국에 온 지 한 달', english: 'one month since coming to Korea' },
        { korean: '~을/를 좋아해요', english: 'I like ~' },
        { korean: '어려워요 (ㅂ-irreg)', english: 'is difficult' },
        { korean: '재미있어서', english: 'because it is fun' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'answer in Korean', 'Use full -아/어요 sentences.', 'sentence',
      'Q1: 사라는 한국에 얼마나 있어요? · Q2: 한국 사람들은 어때요? · Q3: 한국어 공부가 어때요?',
      'Q1: How long has Sarah been in Korea? Q2: How are Korean people? Q3: How is studying Korean?',
      [
        { korean: 'A1: 한 달이에요.', english: 'One month.' },
        { korean: 'A2: 친절해요.', english: 'They are kind.' },
        { korean: 'A3: 어려워요. 그래도 재미있어요.', english: 'It is difficult. But it is fun.' },
      ],
      [ACT.reading]),

    createContentItem('Trading impressions', 'listening',
      'Two students exchange opinions.',
      'conversation',
      'A: 한국 생활이 어때요?\nB: 정말 재미있어요. 사람들도 친절해요.\nA: 음식은요?\nB: 음식은 맛있어요. 그런데 좀 매워요.\nA: 한국어 공부도 해요?\nB: 네. 좀 어려워요. 그래도 좋아요.\nA: 저도 그래요.',
      'A: How is life in Korea?\nB: Really fun. People are kind too.\nA: How about the food?\nB: Delicious. But a bit spicy.\nA: Studying Korean too?\nB: Yes. A bit hard. But I like it.\nA: Same for me.',
      [
        { korean: '~은요?', english: 'and ~? (continuing the topic)' },
        { korean: '그런데 / 그래도', english: 'but / nevertheless' },
        { korean: '저도 그래요', english: 'same for me' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'template',
      'Use this skeleton.',
      'sentence',
      '저는 [이름]이에요/예요. [국적]에서 왔어요. 한국 사람들은 [형용사]. 한국 음식은 [형용사], 그런데 [형용사]. 한국어 공부는 [형용사]. 저는 [N]을/를 좋아해요.',
      '[name] · [country] · [people opinion] · [food opinion] + softener · [study opinion] · [favorite].',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 sentences sharing your real impressions of Korea. Include at least one 좋아하다 and one 좀 + adjective.',
      'sentence', 'Example: 저는 음식을 좋아해요. 한국 음식이 정말 맛있어요. 그런데 좀 매워요. 한국어는 어려워요. 그래도 재미있어요.',
      'Example: I like food. Korean food is really delicious. But a bit spicy. Korean is hard. But it is fun.',
      null, [ACT.writing]),

    createContentItem('반말 vs 존댓말', 'speech levels',
      '한국어 has three main levels: 반말 (casual, with close friends and younger), 해요체 (-아/어요, daily polite), 합쇼체 (-ㅂ니다, formal). Get the level wrong and Koreans WILL notice.',
      'sentence', '존댓말은 처음 만난 사람과 윗사람에게 써요. 친한 친구에게는 반말을 써요.',
      'Use 존댓말 with strangers and seniors. Use 반말 with close friends.',
      [
        { korean: '반말', english: 'casual (no -요)' },
        { korean: '해요체', english: 'polite (-아/어요)' },
        { korean: '합쇼체', english: 'formal (-ㅂ니다)' },
        { korean: '존댓말', english: 'honorific speech (general term)' },
      ],
      [ACT.culture]),
    createContentItem('Never use 반말 with...', 'social rule',
      'Strangers · anyone visibly older · your professor · your boss · customers. Default to 해요체 until invited to use 반말. Wrong-level speech is the #1 mistake foreigners make.',
      'sentence', '말 놓아도 돼요? — "Can I drop the polite speech?" — asked before switching to 반말.', 'Always wait to be invited down to 반말.',
      null, [ACT.culture]),

    createContentItem('과제: First month in Korea', 'task',
      'Roleplay: Tell a Korean friend about your first month. Cover food, weather, people, and Korean study. Use 좋아하다 / 좋다, ㅂ-irregular adjectives, and at least one 좀.',
      'conversation',
      'Friend: 한국 생활이 어때요?\nYou: [2 sentences positive]\nFriend: 음식은 어때요?\nYou: [opinion + softener]\nFriend: 한국어 공부는요?\nYou: [opinion + reason you keep going]\nFriend: 좋네요. 잘 적응하시네요.',
      'Friend: How is life? You: ... Friend: How about food? You: ... Friend: Korean study? You: ...',
      [
        { korean: '재미있어요 / 친절해요', english: 'fun / kind' },
        { korean: '좀 매워요 / 좀 어려워요', english: 'a bit spicy / a bit hard' },
        { korean: '저는 ~을/를 좋아해요', english: 'I like ~' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
