// Level 2 Track-Adult Unit 4 — 버스를 어디서 탑니까? (Commuting)
// Source: Book 2A·4.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au4-orientation',
  pronunciation: 'l2au4-pronunciation',
  vocabularyTransit: 'l2au4-vocab-transit',
  vocabularyVerbs: 'l2au4-vocab-verbs',
  grammarMeans: 'l2au4-grammar-means',
  grammarMust: 'l2au4-grammar-must',
  reading: 'l2au4-reading',
  listening: 'l2au4-listening',
  writing: 'l2au4-writing',
  culture: 'l2au4-culture',
  task: 'l2au4-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe commute formally.', 'Ask + understand bus/subway directions.', 'Use 교통카드 and pay in cash if needed.'],
    task: 'Imagine commuting to a new factory from Gumi Station — you need to ask the right bus, transfer correctly, pay.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Transit phrases',
    goals: ['Apply 경음화: 출근합니다 → [출근함니다].'],
    task: 'Read each commute phrase.' },
  { id: ACT.vocabularyTransit, section: 'Vocabulary I', title: 'Transit + places',
    goals: ['Use 정류장·지하철역·환승·교통카드·출구·셔틀·통근.'],
    task: 'Describe your commute.' },
  { id: ACT.vocabularyVerbs, section: 'Vocabulary II', title: 'Transit verbs',
    goals: ['Use 타다·내리다·환승하다·충전하다·찍다·걸리다.'],
    task: 'Use 5 verbs in sentences.' },
  { id: ACT.grammarMeans, section: 'Grammar I', title: 'N(으)로 + 출근합니다 — by means of N',
    goals: ['Mark transport with N(으)로.', 'Use 걸어서 for "on foot".'],
    task: 'State 3 ways you commute.' },
  { id: ACT.grammarMust, section: 'Grammar II', title: 'V-아/어야 하다/되다 — must V',
    goals: ['Express necessity in formal speech.'],
    task: 'Express 3 commute obligations.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Bus route info',
    goals: ['Read a bus route info sheet.'],
    task: 'Plan a route based on the info.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Asking the bus route',
    goals: ['Follow a route-asking dialogue.'],
    task: 'Reproduce with your destination.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Commute description',
    goals: ['Write 3-4 lines describing your commute.'],
    task: 'Write your commute.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — 티머니, 카카오버스, Naver Map',
    goals: ['Know 티머니카드 (universal transit card).', 'Know 카카오버스 / 네이버 지도 for real-time route info.'],
    task: 'Compare with your home country.' },
  { id: ACT.task, section: 'Task', title: '과제 — Ask + take a bus',
    goals: ['Combine asking, transferring, paying.'],
    task: 'Ask + take a bus to a specific destination.' },
];

const lesson = {
  title: '레벨 2 (직장) · 4과: 버스를 어디서 탑니까? (Commuting)',
  category: 'travel',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'asking-route', label: 'Asking a route', goal: 'Use 어디서 + 타다/내리다.' },
    { id: 'stating-commute', label: 'Stating commute', goal: 'Use N(으)로 + 출근하다.' },
    { id: 'asking-transfer', label: 'Asking about transfer', goal: 'Use ~에서 환승해야 합니까?' },
  ],
  relatedPools: ['topic-travel'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: state commute formally, ask bus route, handle transfer + payment.', 'word', 'Functions: state · ask · transfer · pay', 'Commute toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'Your factory is in 산업단지. You must commute from Gumi Station — which bus, where to transfer, how to pay.', 'word', 'You: 어디서 100번 버스를 탑니까? — Local: 저기에서요.', 'Where do I take bus 100? — Over there.', null, [ACT.orientation]),

    createContentItem('출근합니다 → [출근함니다]', 'chulgeunhamnida', '비음화.', 'word', '버스로 출근합니다.', 'Commute by bus.', null, [ACT.pronunciation]),
    createContentItem('환승 → [환승]', 'hwanseung', 'No major change.', 'word', '환승해야 합니다.', 'Must transfer.', null, [ACT.pronunciation]),
    createContentItem('지하철역 → [지하철력]', 'jihacheolyeok', '연음 + 경음화.', 'word', '지하철역까지 가요.', 'To the subway station.', null, [ACT.pronunciation]),
    createContentItem('100번 → [백뻔]', 'baekppeon', '경음화 in compound numbers.', 'word', '100번 버스를 탑니다.', 'I take bus 100.', null, [ACT.pronunciation]),

    createContentItem('버스 정류장', 'beoseu jeongnyujang', 'bus stop', 'word', '버스 정류장이 어디입니까?', 'Where is the bus stop?', null, [ACT.vocabularyTransit]),
    createContentItem('지하철역', 'jihacheolyeok', 'subway station', 'word', '지하철역까지 가깝습니다.', 'Subway station is close.', null, [ACT.vocabularyTransit]),
    createContentItem('환승', 'hwanseung', 'transfer', 'word', '환승해야 합니다.', 'Must transfer.', null, [ACT.vocabularyTransit]),
    createContentItem('교통카드', 'gyotongkadeu', 'transit card', 'word', '교통카드를 충전합니다.', 'I recharge the card.', null, [ACT.vocabularyTransit]),
    createContentItem('티머니', 'timeoni', 'T-money card', 'word', '티머니로 결제합니다.', 'I pay with T-money.', null, [ACT.vocabularyTransit]),
    createContentItem('출구', 'chulgu', 'exit', 'word', '2번 출구로 나오세요.', 'Exit 2.', null, [ACT.vocabularyTransit]),
    createContentItem('회사 셔틀', 'hoesa syeoteul', 'company shuttle', 'word', '셔틀을 탑니다.', 'I take the shuttle.', null, [ACT.vocabularyTransit]),
    createContentItem('통근', 'tonggeun', 'commute', 'word', '통근 시간이 1시간입니다.', 'Commute is 1 hour.', null, [ACT.vocabularyTransit]),
    createContentItem('현금', 'hyeongeum', 'cash', 'word', '현금으로 내세요.', 'Pay in cash.', null, [ACT.vocabularyTransit]),
    createContentItem('운전기사', 'unjeon gisa', 'bus driver', 'word', '운전기사에게 물어보세요.', 'Ask the driver.', null, [ACT.vocabularyTransit]),

    createContentItem('타다', 'tada', 'to ride / take', 'word', '버스를 탑니다.', 'I take the bus.', null, [ACT.vocabularyVerbs]),
    createContentItem('내리다', 'naerida', 'to get off', 'word', '다음 정류장에서 내리세요.', 'Get off at the next stop.', null, [ACT.vocabularyVerbs]),
    createContentItem('환승하다', 'hwanseunghada', 'to transfer', 'word', '구미역에서 환승합니다.', 'I transfer at Gumi Station.', null, [ACT.vocabularyVerbs]),
    createContentItem('충전하다', 'chungjeonhada', 'to recharge', 'word', '편의점에서 충전합니다.', 'Recharge at convenience store.', null, [ACT.vocabularyVerbs]),
    createContentItem('찍다', 'jjikda', 'to tap (card)', 'word', '카드를 찍으세요.', 'Tap the card.', null, [ACT.vocabularyVerbs]),
    createContentItem('걸리다', 'geollida', 'to take (time)', 'word', '30분 걸립니다.', 'Takes 30 min.', null, [ACT.vocabularyVerbs]),
    createContentItem('걸어서', 'georeoseo', 'on foot', 'word', '회사까지 걸어서 갑니다.', 'I walk to work.', null, [ACT.vocabularyVerbs]),
    createContentItem('내다', 'naeda', 'to pay (cash)', 'word', '현금으로 냅니다.', 'I pay cash.', null, [ACT.vocabularyVerbs]),

    createContentItem('N(으)로 — by means of', 'transport', '으로 after consonant, 로 after vowel/ㄹ.', 'sentence', '버스로 출근합니다.', 'Commute by bus.',
      [
        { korean: '버스 + 로', english: 'vowel → 로' },
        { korean: '지하철 + 로', english: 'ㄹ → 로 (direct)' },
        { korean: '자전거 + 로', english: 'vowel → 로' },
      ],
      [ACT.grammarMeans]),
    createContentItem('걸어서 — on foot', 'exception', 'Always use 걸어서, not 걸로.', 'sentence', '회사까지 걸어서 갑니다.', 'I walk to work.',
      null, [ACT.grammarMeans]),
    createContentItem('자가용 — own car', 'context', 'Use 자가용으로 to say "by own car".', 'sentence', '자가용으로 출근합니다.', 'I drive my own car.',
      null, [ACT.grammarMeans]),

    createContentItem('V-아/어야 합니다 — must V', 'necessity formal', 'Express obligation in formal speech.', 'sentence', '환승해야 합니다.', 'I must transfer.',
      [{ korean: '환승하 + 어야 합니다', english: 'must transfer' }, { korean: '내리 + 어야 합니다', english: 'must get off' }, { korean: '갈아타 + 야 합니다', english: 'must switch' }], [ACT.grammarMust]),
    createContentItem('V-아/어야 됩니다 — must V (synonym)', 'alternative', '됩니다 is interchangeable with 합니다.', 'sentence', '카드를 찍어야 됩니다.', 'I must tap the card.',
      null, [ACT.grammarMust]),
    createContentItem('Question form', 'Q', '~ 해야 합니까? to ask necessity.', 'sentence', '환승해야 합니까?', 'Must I transfer?',
      null, [ACT.grammarMust]),

    createContentItem('Bus route info', 'reading',
      'Read this Gumi-area route sheet.',
      'sentence',
      '100번 버스 안내\n· 출발: 구미역\n· 도착: 산업단지\n· 운행 시간: 06:00 ~ 22:00 (10분 간격)\n· 환승 안내: 없음 (직행)\n· 요금: 1,500원 / 교통카드 1,400원\n· 충전 안내: 모든 편의점에서 가능',
      'Bus 100 Info:\n- Start: Gumi Station\n- End: Industrial Complex\n- Hours: 6 AM - 10 PM (10-min intervals)\n- Transfers: none (direct)\n- Fare: 1,500 KRW / Card 1,400\n- Recharge: all convenience stores.',
      [
        { korean: '간격', english: 'interval' },
        { korean: '직행', english: 'direct' },
        { korean: '요금', english: 'fare' },
      ],
      [ACT.reading]),

    createContentItem('Asking bus route', 'listening',
      'Asking a passerby.',
      'conversation',
      'A: 실례합니다. 구미역에 가려면 어디서 버스를 탑니까?\nB: 저기 보이는 정류장에서 100번 버스를 타십시오.\nA: 환승해야 합니까?\nB: 아니요, 한 번에 갑니다. 약 20분 걸립니다.\nA: 교통카드를 사용할 수 있습니까?\nB: 네, 카드를 찍으면 됩니다. 안 가지고 계시면 운전기사에게 현금으로 내십시오.\nA: 감사합니다.',
      'A: Excuse me. To Gumi Station, where take bus? B: Bus 100 at that stop. A: Transfer? B: No, direct. 20 min. A: Card OK? B: Yes, tap. If no card, pay driver in cash. A: Thanks.',
      [
        { korean: '~으려면', english: 'in order to' },
        { korean: '한 번에 가다', english: 'go directly' },
        { korean: '카드를 찍다', english: 'tap card' },
      ],
      [ACT.listening]),

    createContentItem('Commute description', 'writing',
      'Sample paragraph.',
      'sentence',
      '저는 매일 8시에 출근합니다. 집에서 버스 정류장까지 걸어서 10분 걸립니다. 그리고 100번 버스를 타고 구미역에 갑니다. 구미역에서 회사 셔틀로 환승해야 합니다. 모두 약 1시간 걸립니다. 교통카드를 자주 충전해야 합니다.',
      'I clock in daily at 8. From home to the bus stop takes 10 min on foot. Then I take bus 100 to Gumi Station. At Gumi Station I must transfer to the company shuttle. Total about 1 hour. I have to recharge my transit card often.',
      null, [ACT.writing]),

    createContentItem('Korean transit ecosystem', 'culture',
      '티머니 카드 works on bus + subway + taxi nationwide. Apps: 카카오버스 (real-time bus arrival), 네이버 지도 (best for walking + subway directions). Some companies provide 회사 셔틀 (free shuttle from major stations) for factory workers.',
      'sentence', '한국의 대중교통은 티머니 카드 하나로 다 됩니다.',
      'Korea\'s public transit works with one T-money card.',
      [
        { korean: '티머니 카드', english: 'T-money card' },
        { korean: '카카오버스', english: 'KakaoBus app' },
        { korean: '회사 셔틀', english: 'company shuttle' },
      ],
      [ACT.culture]),

    createContentItem('과제: Take a bus', 'task',
      'Roleplay: Ask + take a bus to a Gumi factory.',
      'conversation',
      'You: 실례합니다. ~ 에 가려면 어디서 버스를 탑니까?\nLocal: ~번 버스를 타십시오.\nYou: 환승해야 합니까? / 얼마 걸립니까?\nLocal: [reply]\nYou: 교통카드를 쓸 수 있습니까?\nLocal: [reply]\nYou: 감사합니다.',
      'AI tutor will play the local.',
      [
        { korean: '~ 가려면', english: 'in order to go' },
        { korean: '~ 어디서 ~ 탑니까?', english: 'where to take?' },
        { korean: '~ 해야 합니까?', english: 'must I?' },
        { korean: '~으로 / 카드로', english: 'by means of / by card' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
