// Level 2 Unit 9 — 한국의 대중문화 (Korea's popular culture)
// Source: Book 2D Unit 9.
// Grammar: A/V-거든, A/V-았/었더라면, A/V-(으)ㅁ, A-(으)ㄴ 듯하다 / V-는 듯하다.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2u9-orientation',
  vocabulary: 'l2u9-vocabulary',
  pronunciation: 'l2u9-pronunciation',
  grammar: 'l2u9-grammar',
  speaking: 'l2u9-speaking',
  readingSpeaking: 'l2u9-reading-speaking',
  listeningSpeaking: 'l2u9-listening-speaking',
  readingWriting: 'l2u9-reading-writing',
  culture: 'l2u9-culture',
  task: 'l2u9-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Discuss K-pop/K-drama with native-like sophistication.', 'Use 4 advanced patterns: ~거든, ~았/었더라면, ~ㅁ, ~ 듯하다.', 'Conduct or answer an interview.'],
    task: 'Imagine being interviewed about your favorite K-drama or K-pop group.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Pop culture + -히 adverbs',
    goals: ['Use 대중문화·드라마·가요·아이돌·연예인·작품·기분·감동적.', 'Use the -히 adverb suffix: 조용히·차분히·확실히·간단히.'],
    task: 'Use 3 -히 adverbs.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Intonation of -거든',
    goals: ['Rising-then-explanatory contour, often follows a 왜? question.'],
    task: 'Read 3 -거든 sentences with proper intonation.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Pop-culture patterns',
    goals: ['A/V-거든 — because (you see)', 'A/V-았/었더라면 — if only had ~', 'A/V-(으)ㅁ — nominalization', 'A-(으)ㄴ 듯하다 / V-는 듯하다 — seems likely'],
    task: 'Use each pattern about a celebrity.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Boasting about your experience',
    goals: ['Share a K-pop / K-drama experience proudly.'],
    task: 'Boast about a celebrity encounter.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Celebrity profile',
    goals: ['Read a profile.', 'Introduce a celebrity.'],
    task: 'Introduce 1 celebrity.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Drama + interviews',
    goals: ['Listen to a drama clip.', 'Conduct an interview.'],
    task: 'Ask 3 questions about a character.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'TV-program guide',
    goals: ['Read intros.', 'Write your own intro.'],
    task: 'Write 3 sentences introducing a TV show.' },
  { id: ACT.culture, section: 'Culture Note', title: 'K-Pop industry essentials',
    goals: ['Understand 데뷔, 컴백, 팬덤, 소속사 (Big 3 + 4).'],
    task: 'Recommend a K-pop group.' },
  { id: ACT.task, section: 'Task', title: 'Celebrity interview',
    goals: ['Combine 4 patterns in an interview.'],
    task: 'Roleplay as a celebrity being interviewed.' },
];

const lesson = {
  title: '레벨 2 · 9과: 한국의 대중문화 (K-Pop and Popular Culture)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'interview-asking', label: 'Asking interview questions', goal: 'Ask 3 interview-style questions.' },
    { id: 'interview-answering', label: 'Answering with softening', goal: 'Use A-(으)ㄴ 듯하다 / V-는 듯하다 to soften answers.' },
    { id: 'expressing-regret', label: 'Expressing regret', goal: 'Use ~았/었더라면 to express past counterfactual regret.' },
  ],
  relatedPools: ['topic-culture'],
  content: [
    createContentItem('Lesson goal', 'pop culture', 'By end: discuss K-pop/K-drama with native-like sophistication.', 'word', 'Functions: explain reason · regret · nominalize · soft infer', 'Interview-ready toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'celebrity interview', 'You are interviewed by a Korean magazine about your favorite K-drama. They ask hard questions; you need to soften, regret, infer.', 'word', 'Interviewer: 왜 그 드라마예요? — You: 주인공이 정말 멋있거든요.', 'Why that drama? — Because the protagonist is really cool, you see.', null, [ACT.orientation]),

    createContentItem('대중문화', 'daejungmunhwa', 'popular culture', 'word', '한국 대중문화가 인기예요.', 'Korean pop culture is popular.', null, [ACT.vocabulary]),
    createContentItem('드라마', 'deurama', 'drama / TV series', 'word', '한국 드라마를 좋아해요.', 'I like K-drama.', null, [ACT.vocabulary]),
    createContentItem('영화', 'yeonghwa', 'movie', 'word', '한국 영화가 세계적이에요.', 'Korean films are world-class.', null, [ACT.vocabulary]),
    createContentItem('가요', 'gayo', 'pop song', 'word', '가요 프로그램이 인기예요.', 'Music shows are popular.', null, [ACT.vocabulary]),
    createContentItem('아이돌', 'aidol', 'idol', 'word', '아이돌 콘서트에 가요.', 'I go to idol concerts.', null, [ACT.vocabulary]),
    createContentItem('연예인', 'yeonyein', 'celebrity', 'word', '연예인이 되는 게 꿈이에요.', 'Becoming a celebrity is my dream.', null, [ACT.vocabulary]),
    createContentItem('인터뷰', 'inteobyu', 'interview', 'word', '연예인 인터뷰를 봤어요.', 'I watched an interview.', null, [ACT.vocabulary]),
    createContentItem('작품', 'jakpum', 'artistic work', 'word', '이 작품이 정말 좋아요.', 'This work is great.', null, [ACT.vocabulary]),
    createContentItem('데뷔하다', 'debwihada', 'to debut', 'word', '내년에 데뷔해요.', 'They debut next year.', null, [ACT.vocabulary]),
    createContentItem('컴백', 'keombaek', 'comeback (new release)', 'word', '곧 컴백이에요.', 'Comeback soon.', null, [ACT.vocabulary]),
    createContentItem('팬덤', 'paendeom', 'fandom', 'word', '팬덤이 정말 커요.', 'Huge fandom.', null, [ACT.vocabulary]),
    createContentItem('소속사', 'sosoksa', 'agency / label', 'word', '큰 소속사예요.', 'A big label.', null, [ACT.vocabulary]),
    createContentItem('기분', 'gibun', 'feeling / mood', 'word', '오늘 기분이 좋아요.', 'I feel good today.', null, [ACT.vocabulary]),
    createContentItem('감동적', 'gamdongjeok', 'moving', 'word', '감동적인 영화예요.', 'A moving film.', null, [ACT.vocabulary]),
    createContentItem('떨리다', 'tteollida', 'to be nervous (lit. tremble)', 'word', '떨리는 마음이에요.', 'A nervous heart.', null, [ACT.vocabulary]),
    createContentItem('차분히', 'chabunhi', 'calmly (-히)', 'word', '차분히 이야기하세요.', 'Speak calmly.', null, [ACT.vocabulary]),
    createContentItem('조용히', 'joyonghi', 'quietly (-히)', 'word', '조용히 들어 주세요.', 'Listen quietly please.', null, [ACT.vocabulary]),
    createContentItem('확실히', 'hwaksilhi', 'certainly (-히)', 'word', '확실히 알아요.', 'I know for sure.', null, [ACT.vocabulary]),
    createContentItem('간단히', 'gandanhi', 'briefly (-히)', 'word', '간단히 설명해 주세요.', 'Briefly explain please.', null, [ACT.vocabulary]),
    createContentItem('K-Pop', 'k-pop', 'K-pop', 'word', 'K-Pop이 세계적으로 인기예요.', 'K-pop is globally popular.', null, [ACT.vocabulary]),

    createContentItem('-거든 → rising-explanatory', 'geodeun intonation', 'After offering a reason, intonation rises slightly then falls. Tone says "you see, this is why".', 'word', '비가 왔거든요. → [거든요] rising-then-explain.', 'Because it rained, you see.', null, [ACT.pronunciation]),
    createContentItem('갔더라면 → [갇떠라면]', 'gatddeoramyeon', '경음화: ㅆ받침 + ㄷ → tense ㄸ.', 'word', '갔더라면 좋았을 텐데. → [갇떠라면]', 'If only I had gone.', null, [ACT.pronunciation]),
    createContentItem('-(으)ㅁ → [smooth]', 'm-nominalization', 'No sound change. Just attach.', 'word', '다양함, 즐거움, 행복함', 'variety, joy, happiness.', null, [ACT.pronunciation]),
    createContentItem('듯해요 → [드태요]', 'deutaeyo', '격음화: ㅅ + ㅎ → ㅌ; 연음.', 'word', '~ 듯해요. → [드태요]', 'Seems like.', null, [ACT.pronunciation]),

    createContentItem('A/V-거든 — because (you see)', 'geodeun', 'Offer a reason for what you just did/said. Soft, explanatory.', 'sentence', '왜 안 왔냐고요? 비가 와서 못 왔거든요.', 'Why did I not come? It rained, you see.',
      [{ korean: 'A-거든(요)', english: 'adjective' }, { korean: 'V-거든(요)', english: 'verb' }, { korean: 'tone', english: 'explanatory, soft' }], [ACT.grammar]),
    createContentItem('A/V-았/었더라면 — if only had', 'past counterfactual', 'Imagine a past that did not happen. Pair with -았/었을 텐데.', 'sentence', '그때 갔더라면 만났을 텐데요.', 'If only I had gone then, I would have met them.',
      [{ korean: 'V-았/었더라면', english: 'past counterfactual' }, { korean: '-았/었을 텐데', english: 'would have ~' }], [ACT.grammar]),
    createContentItem('A/V-(으)ㅁ — nominalization', 'noun-making', 'Convert a verb/adjective into a noun. Formal/written.', 'sentence', '한국 음악의 매력은 다양함에 있어요.', 'The appeal of Korean music lies in its variety.',
      [
        { korean: '다양하 + ㅁ → 다양함', english: 'variety' },
        { korean: '행복하 + ㅁ → 행복함', english: 'happiness' },
        { korean: '있 + 음 → 있음', english: 'existence' },
      ],
      [ACT.grammar]),
    createContentItem('A-(으)ㄴ 듯하다 / V-는 듯하다 — seems', 'duthada', 'Soft inference. Less certain than 같다.', 'sentence', '저 가수는 곧 컴백할 듯해요.', 'That singer seems likely to come back soon.',
      [{ korean: 'A-(으)ㄴ 듯하다', english: 'adjective' }, { korean: 'V-는 듯하다', english: 'verb' }, { korean: 'V-(으)ㄹ 듯하다', english: 'future' }], [ACT.grammar]),

    createContentItem('Boasting experience', 'speaking',
      'Use ~ 거든 to explain.',
      'sentence', '저 한국 가수 콘서트에 가 봤거든요. 정말 감동적이었어요.',
      'I have been to that singer\'s concert, you see. It was truly moving.',
      null, [ACT.speaking]),

    createContentItem('Celebrity profile', 'reading',
      'Read this profile.',
      'sentence',
      '소희는 2018년에 데뷔한 K-Pop 아이돌이에요. 대형 소속사 소속이며 큰 팬덤을 가지고 있는 듯해요. 데뷔 전에 음악 학교를 다녔거든요. 만약 데뷔하지 않았더라면 음악 교사가 되었을 거예요. 작품의 다양함이 그녀의 매력이에요.',
      'Sohee is a K-pop idol who debuted in 2018. She is with a big agency and seems to have a large fandom. She attended music school before debut, you see. If she had not debuted, she would have become a music teacher. The variety of her work is her appeal.',
      [
        { korean: '~ 거든요', english: 'you see' },
        { korean: '~ 았더라면 ~ 었을 거예요', english: 'past counterfactual' },
        { korean: '다양함', english: 'variety (nominalized)' },
        { korean: '~ 는 듯하다', english: 'seems' },
      ],
      [ACT.readingSpeaking]),

    createContentItem('K-Pop interview', 'listening',
      'Magazine interview with a K-pop singer.',
      'conversation',
      'A (인터뷰어): 데뷔하기 전에 어떤 기분이었어요?\nB (가수): 너무 떨렸거든요. 잘할 수 있을지 걱정했어요.\nA: 지금은 어때요?\nB: 지금은 차분해진 듯해요. 팬분들 덕분이에요.\nA: 만약 데뷔를 안 했더라면 뭘 했을 것 같아요?\nB: 음... 음악 선생님이 됐을 것 같아요.\nA: 마지막으로 팬분들에게 한 말씀 부탁드려요.\nB: 항상 응원해 주셔서 감사해요. 더 좋은 작품으로 보답할게요.',
      'A: How did you feel before debut? B: So nervous, you see. Worried I could not do it well. A: How is it now? B: Seem to have become calmer. Thanks to my fans. A: If you had not debuted? B: I think I would have become a music teacher. A: A word for fans? B: Thanks for always supporting me. I will repay with better works.',
      [
        { korean: '~ 거든요', english: 'you see' },
        { korean: '~ ㄴ 듯해요', english: 'seem to have' },
        { korean: '~ 았더라면', english: 'if had' },
      ],
      [ACT.listeningSpeaking]),

    createContentItem('TV show intro', 'reading + writing',
      'Sample show intro.',
      'sentence',
      '"런닝맨"이라는 예능 프로그램은 2010년에 시작했어요. 매주 일요일 저녁에 방송하거든요. 출연자들이 미션을 수행하며 경쟁하는 듯한 프로그램이에요. 만약 더 일찍 봤더라면 한국어를 더 빨리 배웠을 것 같아요. 재미있음을 추천해요.',
      'The variety show "Running Man" started in 2010. It airs every Sunday evening, you see. It is a show where contestants seem to compete by completing missions. If I had watched it earlier, I think I would have learned Korean faster. I recommend its fun.',
      null, [ACT.readingWriting]),

    createContentItem('K-pop industry', 'culture',
      'K-pop is dominated by 4 big agencies: HYBE (BTS), SM (NCT, aespa), JYP (Stray Kids, TWICE), YG (BLACKPINK). Stages: 연습생 → 데뷔 → 컴백 → 솔로 활동. Fans organize as 팬덤 with official names (ARMY, BLINK, ONCE).',
      'sentence', 'K-Pop은 4대 소속사를 중심으로 움직여요.',
      'K-pop revolves around 4 major agencies.',
      [
        { korean: '연습생', english: 'trainee' },
        { korean: '데뷔', english: 'debut' },
        { korean: '컴백', english: 'comeback' },
        { korean: '팬덤', english: 'fandom' },
        { korean: '소속사', english: 'agency' },
      ],
      [ACT.culture]),

    createContentItem('과제: Celebrity interview', 'task',
      'Roleplay: Be interviewed as a K-pop singer. Use all 4 patterns.',
      'conversation',
      'Interviewer: 데뷔 전 기분은요?\nYou: ~ 았거든요.\nInterviewer: 지금은요?\nYou: ~ ㄴ 듯해요.\nInterviewer: 안 했더라면?\nYou: ~ 았/었을 거예요.\nInterviewer: 매력은요?\nYou: 다양함에 있어요.',
      'AI tutor will play the interviewer.',
      [
        { korean: '~ 거든요', english: 'you see' },
        { korean: '~ 았더라면', english: 'if had' },
        { korean: '~ ㅁ', english: 'nominalize' },
        { korean: '~ 듯하다', english: 'seems' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
