// Level 1 Unit 18 — Health & body
// Source: Book 1B·15 (머리가 아파요)
// Functions: describing pain, talking to a doctor, taking medicine.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u18-orientation',
  pronunciation: 'l1u18-pronunciation',
  vocabularyBody: 'l1u18-vocab-body',
  vocabularySymptoms: 'l1u18-vocab-symp',
  grammarPain: 'l1u18-grammar-pain',
  grammarProhibit: 'l1u18-grammar-prohibit',
  grammarPermit: 'l1u18-grammar-permit',
  reading: 'l1u18-reading',
  listening: 'l1u18-listening',
  writing: 'l1u18-writing',
  culture: 'l1u18-culture',
  task: 'l1u18-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe pain in any body part.', 'Understand prohibition (V-지 마세요) and permission (V-아/어도 돼요?).', 'Visit a Korean clinic confidently.'],
    task: 'Imagine catching a cold in Korea — you need to describe symptoms, take a prescription, and ask if certain activities are OK.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Medical phrases',
    goals: ['Apply 비음화: 콧물 → [콘물].', 'Apply 격음화: 못 + 해요 → [모태요].'],
    task: 'Read each medical phrase aloud.' },
  { id: ACT.vocabularyBody, section: 'Vocabulary I', title: 'Body parts',
    goals: ['Name 12+ body parts.'],
    task: 'Touch and name 5 body parts.' },
  { id: ACT.vocabularySymptoms, section: 'Vocabulary II', title: 'Symptoms & illnesses',
    goals: ['Use 아프다·열·기침·콧물·감기·소화불량·두통·복통.'],
    task: 'Describe three symptoms.' },
  { id: ACT.grammarPain, section: 'Grammar I', title: 'N이/가 아프다 — N hurts',
    goals: ['Use the irregular 아프다 → 아파요 (으-irregular).', 'Pair with 이/가.', 'Add intensity: 너무, 좀, 많이.'],
    task: 'Describe pain in 3 body parts.' },
  { id: ACT.grammarProhibit, section: 'Grammar II', title: 'V-지 마세요 — do not',
    goals: ['Attach -지 마세요 to a verb stem.', 'Use in medical advice, signs, parents.'],
    task: 'Give three "do not" instructions.' },
  { id: ACT.grammarPermit, section: 'Grammar III', title: 'V-아/어도 돼요? — may I?',
    goals: ['Attach -아도 돼요? (after ㅏ/ㅗ) or -어도 돼요? (others) to ask permission.', 'Reply 네, 돼요 / 아니요, 안 돼요.'],
    task: 'Ask permission for three things.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A prescription',
    goals: ['Read a doctor\'s instruction note.'],
    task: 'Identify the meds, dose, and dos/don\'ts.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — At the clinic',
    goals: ['Follow a doctor-patient consultation.'],
    task: 'Reproduce with your own symptoms.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Symptom note',
    goals: ['Write 3-4 sentences to give to the doctor.'],
    task: 'Write your symptom note.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean clinics & pharmacies',
    goals: ['Know that small clinics (의원) are walk-in and cheap.', 'Know to go to a 약국 after the clinic.'],
    task: 'Describe the flow: clinic → pharmacy → home.' },
  { id: ACT.task, section: 'Task', title: '과제 — Clinic visit',
    goals: ['Combine symptom + ask permission + receive advice in one continuous scene.'],
    task: 'Visit a clinic for a cold.' },
];

const lesson = {
  title: '레벨 1 · 18과: 머리가 아파요 (Health and Body)',
  category: 'healthcare',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describing-symptoms', label: 'Describing symptoms', goal: 'Use N이/가 아파요 + symptom words.' },
    { id: 'asking-permission', label: 'Asking permission at the clinic', goal: 'Use V-아/어도 돼요? to ask if you may eat/drink/exercise.' },
    { id: 'receiving-prohibition', label: 'Receiving a prohibition', goal: 'Understand V-지 마세요 from the doctor.' },
  ],
  relatedPools: ['topic-health'],
  content: [
    createContentItem('Lesson goal', 'health', 'By end: describe symptoms, understand doctor\'s prohibitions, ask permission.', 'word', 'Functions: describe pain · understand prohibition · ask permission', 'Three clinic micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'cold at the clinic', 'You wake up with a fever and a sore throat. You need to visit a 의원 (small clinic) near campus.', 'word', 'Doctor: 어디가 아파요? — You: 목이 아프고 열이 나요.', 'Doctor: Where hurts? — You: My throat hurts and I have a fever.', null, [ACT.orientation]),

    createContentItem('아파요', 'apayo', '으-irregular: 아프 → drop ㅡ → 아파요.', 'word', '머리가 아파요.', 'My head hurts.', [{ korean: '아프 + 아요', english: 'drop ㅡ before 아 → 아파요' }], [ACT.pronunciation]),
    createContentItem('콧물 → [콘물]', 'konmul', '비음화: ㅅ받침 + ㅁ → ㄴ + ㅁ.', 'word', '콧물이 나요. → [콘무리 나요]', 'I have a runny nose.', null, [ACT.pronunciation]),
    createContentItem('걸렸어요 → [걸려써요]', 'geollyeosseoyo', '연음 + tense ㅆ: smooth past form.', 'word', '감기에 걸렸어요. → [걸려써요]', 'I caught a cold.', null, [ACT.pronunciation]),
    createContentItem('마셔도 → [마셔도]', 'masyeodo', 'No major change; just smooth.', 'word', '커피 마셔도 돼요?', 'May I drink coffee?', null, [ACT.pronunciation]),

    createContentItem('머리', 'meori', 'head', 'word', '머리가 아파요.', 'My head hurts.', null, [ACT.vocabularyBody]),
    createContentItem('얼굴', 'eolgul', 'face', 'word', '얼굴이 빨개요.', 'My face is red.', null, [ACT.vocabularyBody]),
    createContentItem('눈', 'nun', 'eye', 'word', '눈이 가려워요.', 'My eye itches.', null, [ACT.vocabularyBody]),
    createContentItem('코', 'ko', 'nose', 'word', '코가 막혔어요.', 'My nose is congested.', null, [ACT.vocabularyBody]),
    createContentItem('입', 'ip', 'mouth', 'word', '입 안이 아파요.', 'My mouth is sore.', null, [ACT.vocabularyBody]),
    createContentItem('목', 'mok', 'neck / throat', 'word', '목이 아파요.', 'My throat hurts.', null, [ACT.vocabularyBody]),
    createContentItem('배', 'bae', 'stomach / belly', 'word', '배가 아파요.', 'My stomach hurts.', null, [ACT.vocabularyBody]),
    createContentItem('다리', 'dari', 'leg', 'word', '다리가 아파요.', 'My leg hurts.', null, [ACT.vocabularyBody]),
    createContentItem('팔', 'pal', 'arm', 'word', '팔이 아파요.', 'My arm hurts.', null, [ACT.vocabularyBody]),
    createContentItem('어깨', 'eokkae', 'shoulder', 'word', '어깨가 아파요.', 'My shoulder hurts.', null, [ACT.vocabularyBody]),
    createContentItem('등', 'deung', 'back', 'word', '등이 아파요.', 'My back hurts.', null, [ACT.vocabularyBody]),
    createContentItem('이', 'i', 'tooth', 'word', '이가 아파요.', 'My tooth hurts.', null, [ACT.vocabularyBody]),

    createContentItem('아프다', 'apeuda', 'to hurt / be in pain', 'word', '많이 아파요.', 'It hurts a lot.', null, [ACT.vocabularySymptoms]),
    createContentItem('열', 'yeol', 'fever', 'word', '열이 나요.', 'I have a fever.', null, [ACT.vocabularySymptoms]),
    createContentItem('기침', 'gichim', 'cough', 'word', '기침이 심해요.', 'My cough is severe.', null, [ACT.vocabularySymptoms]),
    createContentItem('콧물', 'konmul', 'runny nose', 'word', '콧물이 나요.', 'I have a runny nose.', null, [ACT.vocabularySymptoms]),
    createContentItem('감기', 'gamgi', 'a cold', 'word', '감기에 걸렸어요.', 'I caught a cold.', null, [ACT.vocabularySymptoms]),
    createContentItem('두통', 'dutong', 'headache', 'word', '두통이 있어요.', 'I have a headache.', null, [ACT.vocabularySymptoms]),
    createContentItem('복통', 'boktong', 'stomachache', 'word', '복통이 심해요.', 'My stomachache is severe.', null, [ACT.vocabularySymptoms]),
    createContentItem('소화불량', 'sohwa bullyang', 'indigestion', 'word', '소화불량이에요.', 'I have indigestion.', null, [ACT.vocabularySymptoms]),
    createContentItem('병원', 'byeongwon', 'hospital / clinic', 'word', '병원에 가야 해요.', 'I have to go to the clinic.', null, [ACT.vocabularySymptoms]),
    createContentItem('의원', 'uiwon', 'small clinic', 'word', '동네 의원에 갔어요.', 'I went to the neighborhood clinic.', null, [ACT.vocabularySymptoms]),
    createContentItem('의사', 'uisa', 'doctor', 'word', '의사 선생님이세요.', 'You are the doctor.', null, [ACT.vocabularySymptoms]),
    createContentItem('약', 'yak', 'medicine', 'word', '약을 먹어요.', 'I take medicine.', null, [ACT.vocabularySymptoms]),
    createContentItem('약국', 'yakguk', 'pharmacy', 'word', '약국에서 약을 사요.', 'I buy medicine at the pharmacy.', null, [ACT.vocabularySymptoms]),
    createContentItem('처방전', 'cheobangjeon', 'prescription', 'word', '처방전을 받았어요.', 'I got a prescription.', null, [ACT.vocabularySymptoms]),

    createContentItem('N이/가 아프다', 'i/ga apeuda', 'Subject + 아프다. The body part takes 이/가.', 'sentence', '머리가 아파요.', 'My head hurts.',
      [
        { korean: '머리가', english: 'head + subject 가' },
        { korean: '아파요', english: 'hurts (으-irreg conjugation of 아프다)' },
      ],
      [ACT.grammarPain]),
    createContentItem('Intensity adverbs', 'how much', 'Add 너무 (too) / 많이 (a lot) / 좀 (a bit) / 조금 (a little).', 'sentence', '머리가 너무 아파요.', 'My head hurts a lot.',
      [{ korean: '너무', english: 'too / very' }, { korean: '많이', english: 'a lot' }, { korean: '좀', english: 'a bit' }], [ACT.grammarPain]),
    createContentItem('Multiple symptoms with -고', 'chaining', 'Use -고 to chain multiple symptoms.', 'sentence', '머리가 아프고 열이 나요.', 'My head hurts and I have a fever.',
      null, [ACT.grammarPain]),

    createContentItem('V-지 마세요 — do not', 'prohibition', 'Attach -지 마세요 to verb stem. Used by doctors, signs, parents.', 'sentence', '오늘은 운동하지 마세요.', 'Do not exercise today.',
      [
        { korean: '운동하 + 지 마세요', english: '운동하지 마세요' },
        { korean: '마시 + 지 마세요', english: '마시지 마세요 (do not drink)' },
        { korean: '먹 + 지 마세요', english: '먹지 마세요 (do not eat)' },
      ],
      [ACT.grammarProhibit]),
    createContentItem('Casual: V-지 마', 'prohibition casual', 'Drop 세요 for casual. Use with friends only.', 'sentence', '그거 먹지 마. 매워.', 'Do not eat that. It is spicy.',
      null, [ACT.grammarProhibit]),
    createContentItem('Compare with 안 V', 'prohibit vs negate', 'V-지 마세요 = "do not (an instruction)". 안 V = "do not (statement)". Don\'t mix them.', 'sentence', '운동하지 마세요. (Doctor says) vs 운동 안 해요. (I do not exercise.)', 'Imperative vs declarative.',
      null, [ACT.grammarProhibit]),

    createContentItem('V-아/어도 돼요? — May I V?', 'asking permission', 'Attach -아도 돼요? (ㅏ/ㅗ) or -어도 돼요? (others). Reply 네, 돼요 / 아니요, 안 돼요.', 'sentence', '커피를 마셔도 돼요?', 'May I drink coffee?',
      [
        { korean: '마시 + 어도 돼요?', english: '마셔도 돼요?' },
        { korean: '가 + 아도 돼요?', english: '가도 돼요?' },
        { korean: '먹 + 어도 돼요?', english: '먹어도 돼요?' },
      ],
      [ACT.grammarPermit]),
    createContentItem('Statement: V-아/어도 돼요 — may V', 'permission given', 'Same form without ? — a statement of permission.', 'sentence', '내일은 운동해도 돼요.', 'You may exercise tomorrow.',
      null, [ACT.grammarPermit]),
    createContentItem('Negation: 안 돼요 / V-(으)면 안 돼요', 'not OK', 'For "no", reply 안 돼요. For a written rule, V-(으)면 안 돼요.', 'sentence', '오늘은 술을 마시면 안 돼요.', 'Today you must not drink alcohol.',
      null, [ACT.grammarPermit]),

    createContentItem('A prescription', 'reading',
      'Read the doctor\'s note aloud.',
      'sentence',
      '환자: 사라 / 진단: 감기 / 처방: 감기약 3일분 / 복용법: 하루 3번, 식후 30분 / 주의 사항: 1) 푹 쉬세요. 2) 운동하지 마세요. 3) 술을 마시지 마세요. 4) 따뜻한 물을 많이 드세요.',
      'Patient: Sarah / Diagnosis: Cold / Prescription: 3 days of cold meds / Dosage: 3 times a day, 30 min after meals / Cautions: 1) Rest well. 2) No exercise. 3) No alcohol. 4) Drink lots of warm water.',
      [
        { korean: '진단', english: 'diagnosis' },
        { korean: '처방', english: 'prescription' },
        { korean: '복용법', english: 'dosage' },
        { korean: '주의 사항', english: 'cautions' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Answer from the prescription.', 'sentence',
      'Q1: 약을 며칠 분 받았어요? · Q2: 하루에 몇 번 먹어요? · Q3: 뭐 하지 마세요?',
      'Q1: How many days of medicine? Q2: How many times a day? Q3: What must not be done?',
      [
        { korean: 'A1: 3일분이에요.', english: 'Three days worth.' },
        { korean: 'A2: 하루 3번이에요.', english: 'Three times a day.' },
        { korean: 'A3: 운동하지 마세요. 술 마시지 마세요.', english: 'Do not exercise. Do not drink alcohol.' },
      ],
      [ACT.reading]),

    createContentItem('At the clinic', 'listening',
      'Doctor-patient dialogue.',
      'conversation',
      'A (의사): 어디가 아파요?\nB (환자): 머리가 아프고 열도 나요. 기침도 심해요.\nA: 언제부터 아팠어요?\nB: 그저께부터요. 감기 같아요.\nA: 네, 감기예요. 3일 동안 약을 드시고 푹 쉬세요. 운동은 하지 마세요.\nB: 커피는 마셔도 돼요?\nA: 따뜻한 차가 더 좋아요.\nB: 알겠습니다. 감사합니다.\nA: 다음 주에 다시 오세요.',
      'A: Where hurts? B: Head hurts and fever, severe cough. A: When did it start? B: Day before yesterday. Cold? A: Yes, cold. Meds for 3 days, rest. No exercise. B: May I drink coffee? A: Warm tea is better. B: Understood. Thanks. A: Come back next week.',
      [
        { korean: '어디가 아파요?', english: 'where hurts?' },
        { korean: '언제부터', english: 'since when' },
        { korean: '~ 동안', english: 'for (duration)' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'symptom note',
      'Use this to describe symptoms.',
      'sentence',
      '저는 [신체]이/가 아파요. [증상]도 있어요. [시간]부터 아팠어요. [질문]도 있어요. ~해도 돼요?',
      '[body part] · [extra symptoms] · [since when] · [question]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 3-4 sentences about your symptoms. Use 아프다 + symptom + asking permission.',
      'sentence', 'Example: 어제부터 머리가 아파요. 콧물도 나고 기침도 좀 해요. 감기 같아요. 커피를 마셔도 돼요?',
      'Example: My head has hurt since yesterday. Runny nose, slight cough. Feels like a cold. May I drink coffee?',
      null, [ACT.writing]),

    createContentItem('Clinic flow', 'culture',
      'In Korea, you visit a 의원 (small clinic — no appointment needed) for minor issues. Doctor gives a 처방전. You take it to a nearby 약국 to get the meds. The whole thing typically costs under 10,000원 with 건강보험 (national insurance).',
      'sentence', '한국에서는 의원에서 진료받고 약국에서 약을 사요.',
      'In Korea, you see the doctor at a clinic and buy medicine at the pharmacy.',
      [{ korean: '의원', english: 'small clinic' }, { korean: '처방전', english: 'prescription' }, { korean: '약국', english: 'pharmacy' }, { korean: '건강보험', english: 'health insurance' }], [ACT.culture]),
    createContentItem('국민건강보험', 'culture',
      'All foreign residents on a long-term visa must enroll in 국민건강보험 (NHI). A simple clinic visit costs about 3,000-5,000 won with insurance. Without insurance it can be 5x more.',
      'sentence', '외국인 학생도 국민건강보험에 가입해야 해요.',
      'Foreign students must also join National Health Insurance.',
      null, [ACT.culture]),

    createContentItem('과제: Clinic visit', 'task',
      'Roleplay: You caught a cold. Visit the 의원. Describe symptoms, ask permission for one activity, receive prohibitions, thank the doctor.',
      'conversation',
      'Doctor: 어디가 아파요?\nYou: [describe 2 symptoms with -고]\nDoctor: 언제부터요?\nYou: [since when]\nDoctor: [prohibition + advice]\nYou: [ask permission for one activity]\nDoctor: [allow or deny]\nYou: 감사합니다.',
      'AI tutor will play the doctor.',
      [
        { korean: '~이/가 아프고 ~이/가 나요', english: 'X hurts and Y appears' },
        { korean: '~지 마세요', english: 'do not ~' },
        { korean: '~ 해도 돼요?', english: 'may I ~?' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
