// Level 1 Unit 6 — Dates & calendar
// Source: Book 1B·6 (제 생일은 6월 11일이에요)
// Functions: dates, days of the week, asking about birthdays, Sino-Korean numbers.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u6-orientation',
  pronunciation: 'l1u6-pronunciation',
  vocabularyDays: 'l1u6-vocab-days',
  vocabularyMonths: 'l1u6-vocab-months',
  grammarNumbers: 'l1u6-grammar-numbers',
  grammarDates: 'l1u6-grammar-dates',
  grammarWhen: 'l1u6-grammar-when',
  reading: 'l1u6-reading',
  listening: 'l1u6-listening',
  writing: 'l1u6-writing',
  culture: 'l1u6-culture',
  task: 'l1u6-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Read and say any date in Korean (year/month/day).', 'Name the 7 days of the week.', 'Ask and answer when something happens.'],
    task: 'Imagine planning a Korean friend\'s birthday party — you need to coordinate the date, the day, and when to meet.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Sino-Korean number sounds',
    goals: ['Pronounce 6 → 육, 10 → 십, and ㄴ→ㄹ rule in 십육 → [심뉵].'],
    task: 'Read the numbers 1-31 aloud applying any sound changes.' },
  { id: ACT.vocabularyDays, section: 'Vocabulary I', title: 'Days of the week + relative time',
    goals: ['Learn 월·화·수·목·금·토·일 + 오늘·어제·내일·모레.'],
    task: 'Say what day each was: yesterday, today, tomorrow.' },
  { id: ACT.vocabularyMonths, section: 'Vocabulary II', title: 'Months + calendar nouns',
    goals: ['Use 1월–12월 (always Sino-Korean number + 월).', 'Use 년·월·일·주·생일·시험·휴일·명절.'],
    task: 'Write the date of an important holiday in Korea.' },
  { id: ACT.grammarNumbers, section: 'Grammar I', title: 'Sino-Korean numbers 1-99',
    goals: ['Read 일·이·삼·사·오·육·칠·팔·구·십.', 'Build any 2-digit number: 11 = 십일, 25 = 이십오, 99 = 구십구.'],
    task: 'Say your age, phone-number\'s last 4 digits, and the year you started learning Korean.' },
  { id: ACT.grammarDates, section: 'Grammar II', title: 'Reading dates: N년 N월 N일',
    goals: ['Build dates: 2026년 5월 11일.', 'Use Sino-Korean numbers ONLY for dates (never native numbers).'],
    task: 'Write three dates: today, your birthday, and an upcoming holiday.' },
  { id: ACT.grammarWhen, section: 'Grammar III', title: '언제 / 며칠 / 무슨 요일',
    goals: ['Ask 언제 (when), 며칠 (what date), 무슨 요일 (what day of the week).', 'Use the possessive 의 (often dropped in speech).'],
    task: 'Ask and answer all three question words.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A semester calendar',
    goals: ['Read a paragraph about a student\'s semester schedule.'],
    task: 'Answer comprehension about which date each event is on.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Birthdays and plans',
    goals: ['Follow two short date-checking dialogues.'],
    task: 'Reproduce the dialogue with your real birthday.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Important dates in my life',
    goals: ['Write 4-5 sentences listing important dates.'],
    task: 'Write your own list of important personal dates.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Lunar calendar (음력) and Korean age',
    goals: ['Know that 설날·추석 follow the 음력.', 'Know that Korean age = international age + 1-2 (but the law changed in 2023).'],
    task: 'Compare a 양력 birthday vs a 음력 birthday.' },
  { id: ACT.task, section: 'Task', title: '과제 — Plan a birthday meet-up',
    goals: ['Combine days, dates, and 언제 questions in one task.'],
    task: 'Roleplay planning a birthday meet-up with the AI tutor.' },
];

const lesson = {
  title: '레벨 1 · 6과: 제 생일은 6월 11일이에요 (Dates and Calendar)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-when-date', label: 'Asking when something happens', goal: 'Use 언제예요? to ask for the date or day.' },
    { id: 'stating-birthday', label: 'Stating a birthday', goal: 'Give a date in N월 N일 format.' },
    { id: 'planning-event-date', label: 'Planning around a date', goal: 'Combine 무슨 요일 + N월 N일 to plan a meet-up.' },
  ],
  relatedPools: [],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: say any Korean date, name the 7 weekdays, ask & answer when events happen.', 'word', 'Functions: read date · pick day · ask when', 'Three skills for scheduling in Korean.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'Your Korean friend\'s birthday is coming up. You need to confirm the date and pick a day to meet.', 'word', 'Friend: 생일이 언제예요? — You: 6월 11일이에요.', 'Friend: When is your birthday? — You: It is June 11.', null, [ACT.orientation]),

    createContentItem('6 → [육]', 'yuk', '6 is 육. Watch for liaison with adjacent numbers.', 'word', '6월 → [유월]', 'June is irregular: 육 + 월 → 유월.', null, [ACT.pronunciation]),
    createContentItem('10 → [십]', 'sip', '10 is 십. Always tense after a stop받침.', 'word', '학생 십 명 → [학쌩 심 명]', 'ten students.', null, [ACT.pronunciation]),
    createContentItem('Irregular months', '6월 → 유월, 10월 → 시월', 'June and October DROP a sound: 6월 = 유월 (not 육월), 10월 = 시월 (not 십월).', 'word', '유월 / 시월', 'June / October — irregular.',
      [{ korean: '6월', english: '유월 (drop the ㄱ)' }, { korean: '10월', english: '시월 (drop the ㅂ)' }], [ACT.pronunciation]),
    createContentItem('받침 + 월 → 비음화', 'cluster', 'For most months, the ㄴ/ㄹ받침 of the number flows into 월 naturally.', 'word', '7월 → [칠월], 8월 → [팔월]', 'July, August.', null, [ACT.pronunciation]),

    createContentItem('월요일', 'woryoil', 'Monday', 'word', '월요일에 학교에 가요.', 'I go to school on Monday.', null, [ACT.vocabularyDays]),
    createContentItem('화요일', 'hwayoil', 'Tuesday', 'word', '화요일에 한국어 수업이 있어요.', 'I have Korean class on Tuesday.', null, [ACT.vocabularyDays]),
    createContentItem('수요일', 'suyoil', 'Wednesday', 'word', '수요일에 친구를 만나요.', 'I meet a friend on Wednesday.', null, [ACT.vocabularyDays]),
    createContentItem('목요일', 'mogyoil', 'Thursday', 'word', '목요일에 일해요.', 'I work on Thursday.', null, [ACT.vocabularyDays]),
    createContentItem('금요일', 'geumyoil', 'Friday', 'word', '금요일이 좋아요.', 'I like Fridays.', null, [ACT.vocabularyDays]),
    createContentItem('토요일', 'toyoil', 'Saturday', 'word', '토요일에 쉬어요.', 'I rest on Saturday.', null, [ACT.vocabularyDays]),
    createContentItem('일요일', 'iryoil', 'Sunday', 'word', '일요일에 가족과 같이 있어요.', 'On Sunday I am with my family.', null, [ACT.vocabularyDays]),
    createContentItem('오늘', 'oneul', 'today', 'word', '오늘은 월요일이에요.', 'Today is Monday.', null, [ACT.vocabularyDays]),
    createContentItem('어제', 'eoje', 'yesterday', 'word', '어제는 일요일이었어요.', 'Yesterday was Sunday.', null, [ACT.vocabularyDays]),
    createContentItem('내일', 'naeil', 'tomorrow', 'word', '내일은 화요일이에요.', 'Tomorrow is Tuesday.', null, [ACT.vocabularyDays]),
    createContentItem('모레', 'more', 'the day after tomorrow', 'word', '모레 만나요.', 'Let us meet the day after tomorrow.', null, [ACT.vocabularyDays]),
    createContentItem('이번 주', 'ibeon ju', 'this week', 'word', '이번 주에 시험이 있어요.', 'I have an exam this week.', null, [ACT.vocabularyDays]),
    createContentItem('지난주', 'jinanju', 'last week', 'word', '지난주에 친구를 만났어요.', 'I met a friend last week.', null, [ACT.vocabularyDays]),
    createContentItem('다음 주', 'daeum ju', 'next week', 'word', '다음 주에 한국에 가요.', 'I go to Korea next week.', null, [ACT.vocabularyDays]),
    createContentItem('주말', 'jumal', 'weekend', 'word', '주말이 좋아요.', 'I like weekends.', null, [ACT.vocabularyDays]),

    createContentItem('1월–12월', 'January-December', 'Each month is just the Sino-Korean number + 월. EXCEPT 6월 = 유월, 10월 = 시월.', 'word', '1월·2월·3월·4월·5월·유월·7월·8월·9월·시월·11월·12월', 'All twelve months.',
      [
        { korean: '1월 (일월)', english: 'January' },
        { korean: '6월 (유월)', english: 'June — irregular' },
        { korean: '10월 (시월)', english: 'October — irregular' },
        { korean: '12월 (십이월)', english: 'December' },
      ],
      [ACT.vocabularyMonths]),
    createContentItem('생일', 'saengil', 'birthday', 'word', '제 생일은 6월이에요.', 'My birthday is in June.', null, [ACT.vocabularyMonths]),
    createContentItem('년', 'nyeon', 'year (counter)', 'word', '2026년이에요.', 'It is 2026.', null, [ACT.vocabularyMonths]),
    createContentItem('월', 'wol', 'month (counter)', 'word', '6월은 더워요.', 'June is hot.', null, [ACT.vocabularyMonths]),
    createContentItem('일', 'il', 'day (counter)', 'word', '오늘은 11일이에요.', 'Today is the 11th.', null, [ACT.vocabularyMonths]),
    createContentItem('주', 'ju', 'week (counter)', 'word', '한 주에 한 번 만나요.', 'We meet once a week.', null, [ACT.vocabularyMonths]),
    createContentItem('시험', 'siheom', 'exam', 'word', '시험이 다음 주예요.', 'The exam is next week.', null, [ACT.vocabularyMonths]),
    createContentItem('휴일', 'hyuil', 'holiday', 'word', '내일은 휴일이에요.', 'Tomorrow is a holiday.', null, [ACT.vocabularyMonths]),
    createContentItem('명절', 'myeongjeol', 'traditional holiday (Korean)', 'word', '추석은 큰 명절이에요.', 'Chuseok is a big traditional holiday.', null, [ACT.vocabularyMonths]),

    createContentItem('Sino-Korean numbers 1-10', 'count', 'Memorize these — they appear in EVERY date, phone number, price, address.', 'sentence', '일 (1) · 이 (2) · 삼 (3) · 사 (4) · 오 (5) · 육 (6) · 칠 (7) · 팔 (8) · 구 (9) · 십 (10)',
      'The Sino-Korean (한자어) number system.',
      [
        { korean: '일 / 이 / 삼', english: '1 / 2 / 3' },
        { korean: '사 / 오 / 육', english: '4 / 5 / 6' },
        { korean: '칠 / 팔 / 구', english: '7 / 8 / 9' },
        { korean: '십', english: '10' },
      ],
      [ACT.grammarNumbers]),
    createContentItem('Building 11-99', 'compose', '10s digit + 1s digit. 11 = 십일, 25 = 이십오, 99 = 구십구.', 'sentence', '십 (10) → 십일 (11) → 이십 (20) → 이십오 (25) → 구십구 (99)',
      'Place value works like English: tens-place + ones-place.',
      [
        { korean: '15 → 십오', english: '10 + 5' },
        { korean: '20 → 이십', english: '2 × 10' },
        { korean: '31 → 삼십일', english: '3 × 10 + 1' },
      ],
      [ACT.grammarNumbers]),
    createContentItem('Use Sino-Korean for...', 'always', 'Dates, money (won), phone numbers, addresses, math, minutes, seconds. (Native numbers are for hours, ages, counting things.)', 'sentence', 'Dates → Sino-Korean. Hours → Native.', 'Crucial distinction in Korean.', null, [ACT.grammarNumbers]),

    createContentItem('N월 N일 — date', 'M D', 'Always Sino-Korean number + 월 + Sino-Korean number + 일.', 'sentence', '6월 11일 → [유월 십일릴]', 'June 11th.',
      [{ korean: '6월', english: 'June (유월 — irregular)' }, { korean: '11일', english: '11th day (십일일)' }], [ACT.grammarDates]),
    createContentItem('Full date with year', 'YYYY M D', 'Year + 년 + month + 월 + day + 일.', 'sentence', '2026년 5월 11일', 'May 11, 2026.',
      [{ korean: '2026년', english: '이천이십육년' }, { korean: '5월', english: '오월' }, { korean: '11일', english: '십일일' }], [ACT.grammarDates]),
    createContentItem('Date in a sentence', 'usage', 'Use the copula 이에요 to state when something is.', 'sentence', '제 생일은 6월 11일이에요.', 'My birthday is June 11.',
      [{ korean: '제 생일은', english: 'my birthday (topic)' }, { korean: '6월 11일', english: 'date' }, { korean: '이에요', english: 'is' }], [ACT.grammarDates]),

    createContentItem('언제 — when (general)', 'eonje', 'Ask the time of any event. Loose question, accepts day OR date answer.', 'sentence', '시험이 언제예요? — 다음 주 금요일이에요.', 'When is the exam? — Next Friday.',
      [{ korean: '시험이', english: 'exam + subject' }, { korean: '언제예요?', english: 'when is it?' }], [ACT.grammarWhen]),
    createContentItem('며칠 — what date', 'myeochil', 'Specifically asks for the date number.', 'sentence', '오늘은 며칠이에요? — 11월 9일이에요.', 'What is today\'s date? — November 9.',
      [{ korean: '며칠', english: 'what date / what day-number' }], [ACT.grammarWhen]),
    createContentItem('무슨 요일 — what day of the week', 'museun yoil', 'Specifically asks for the weekday name.', 'sentence', '오늘은 무슨 요일이에요? — 화요일이에요.', 'What day is it today? — Tuesday.',
      [{ korean: '무슨 요일', english: 'what day of the week' }], [ACT.grammarWhen]),
    createContentItem('의 — possessive', 'ui', 'Mark possession: N1의 N2 = "N1\'s N2". Often dropped in everyday speech.', 'sentence', '친구의 생일은 5월이에요. = 친구 생일은 5월이에요.', 'My friend\'s birthday is in May.',
      [{ korean: '친구의 생일', english: 'friend\'s birthday (formal)' }, { korean: '친구 생일', english: 'friend\'s birthday (everyday — 의 dropped)' }], [ACT.grammarWhen]),

    createContentItem('A semester schedule', 'reading',
      'Read aloud, then answer.',
      'sentence',
      '이번 학기는 3월 2일에 시작해요. 중간시험은 4월 22일이에요. 어린이날은 5월 5일이에요. 휴일이에요. 제 생일은 6월 11일이에요. 학기는 6월 21일에 끝나요. 여름방학은 7월 1일에 시작해요.',
      'This semester starts on March 2. The midterm is on April 22. Children\'s Day is May 5. It is a holiday. My birthday is June 11. The semester ends on June 21. Summer vacation starts on July 1.',
      [
        { korean: '학기', english: 'semester' },
        { korean: '시작해요 / 끝나요', english: 'starts / ends' },
        { korean: '중간시험', english: 'midterm' },
        { korean: '어린이날', english: 'Children\'s Day' },
        { korean: '여름방학', english: 'summer vacation' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'answer in Korean',
      'Use full -이에요 sentences.',
      'sentence',
      'Q1: 이번 학기는 언제 시작해요? · Q2: 중간시험은 며칠이에요? · Q3: 생일이 언제예요?',
      'Q1: When does the semester start? Q2: What date is the midterm? Q3: When is the birthday?',
      [
        { korean: 'A1: 3월 2일에 시작해요.', english: 'It starts March 2.' },
        { korean: 'A2: 4월 22일이에요.', english: 'April 22.' },
        { korean: 'A3: 6월 11일이에요.', english: 'June 11.' },
      ],
      [ACT.reading]),

    createContentItem('Birthday dialogue', 'listening',
      'Two friends exchange birthdays.',
      'conversation',
      'A: 생일이 언제예요?\nB: 제 생일은 6월 11일이에요. 사라 씨는요?\nA: 저는 12월 3일이에요.\nB: 와, 겨울 생일이네요!\nA: 네, 그래서 케이크를 따뜻하게 데워서 먹어요.\nB: 하하, 재밌네요. 다음 달 11일에 같이 생일 파티 해요.\nA: 좋아요!',
      'A: When is your birthday?\nB: June 11. And you, Sarah?\nA: December 3.\nB: Wow, a winter birthday!\nA: Yes, so I warm the cake before eating it.\nB: Haha, funny. Let us do a birthday party on the 11th of next month.\nA: Great!',
      [
        { korean: '겨울 생일', english: 'winter birthday' },
        { korean: '다음 달', english: 'next month' },
        { korean: '같이 ~ 해요', english: 'let us do ~ together' },
      ],
      [ACT.listening]),
    createContentItem('Forgetting the day', 'listening',
      'Quick exchange about which day class is.',
      'conversation',
      'A: 오늘은 무슨 요일이에요?\nB: 화요일이에요. 왜요?\nA: 한국어 수업이 언제인지 잊어버렸어요.\nB: 한국어 수업은 수요일이에요. 내일이에요.\nA: 아, 그렇군요. 내일 9시에 시작해요?\nB: 네, 맞아요.\nA: 고마워요.',
      'A: What day is it today?\nB: Tuesday. Why?\nA: I forgot when Korean class is.\nB: Korean class is Wednesday. Tomorrow.\nA: Oh, I see. Does it start at 9 tomorrow?\nB: Yes.\nA: Thanks.',
      [
        { korean: '잊어버리다', english: 'to forget' },
        { korean: '~인지', english: 'whether ~ (embedded question)' },
        { korean: '아, 그렇군요', english: 'oh, I see' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'template',
      'Use this to write your own important-dates paragraph.',
      'sentence',
      '저는 [국적] 사람이에요. 제 생일은 [N월 N일]이에요. 한국에 [N월 N일]에 왔어요. 이번 학기는 [N월 N일]에 시작해요. 중요한 시험은 [N월 N일]이에요.',
      '[nationality · birthday · arrival date · semester start · exam date]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 sentences listing important dates in your life. Use 년·월·일 and at least one weekday.',
      'sentence', 'Example: 제 생일은 7월 22일이에요. 동생 생일은 11월 4일이에요. 한국에 작년 9월에 왔어요. 다음 주 금요일에 시험이 있어요.',
      'Example: My birthday is July 22. My sibling\'s is November 4. I came to Korea last September. I have an exam next Friday.',
      null, [ACT.writing]),

    createContentItem('Lunar calendar (음력)', 'culture',
      'Korea uses two calendars side by side: 양력 (Gregorian, used daily) and 음력 (lunar, used for traditional holidays like 설날 = Lunar New Year and 추석 = mid-autumn festival). Many older Koreans celebrate their birthday on the 음력 date.',
      'sentence', '설날과 추석은 음력 명절이에요. 매년 양력 날짜가 달라요.',
      'Seollal and Chuseok are lunar holidays. Their Gregorian dates change every year.',
      [{ korean: '양력', english: 'Gregorian / solar calendar' }, { korean: '음력', english: 'lunar calendar' }], [ACT.culture]),
    createContentItem('Korean age (한국 나이)', 'culture',
      'Traditionally a Korean was "1 year old" at birth and gained a year every Lunar New Year, so Korean age = international age + 1-2. Since June 2023 the law standardized 만 나이 (international age), but many people still casually use the old system.',
      'sentence', '저는 만 22살이에요. 그런데 한국 나이로는 23살이에요.',
      'I am 22 (international). But in Korean age I am 23.',
      [{ korean: '만 나이', english: 'international age (legal since 2023)' }, { korean: '한국 나이', english: 'traditional Korean age' }], [ACT.culture]),

    createContentItem('과제: Plan a birthday meet-up', 'task',
      'Roleplay: Your Korean friend\'s birthday is coming. Confirm the date, pick a day to meet, propose a time.',
      'conversation',
      'Friend: 생일이 언제예요?\nYou: [give your birthday]\nFriend: 제 생일은 [date]이에요. 다음 주에 만나요.\nYou: [pick a weekday and confirm]\nFriend: [agree] 좋아요. 몇 시에 만나요?\nYou: [propose a rough time]\nFriend: 좋아요. 그날 봐요.',
      'AI tutor will play the friend.',
      [
        { korean: '생일이 언제예요?', english: 'when is your birthday?' },
        { korean: 'N월 N일이에요', english: 'it is M D' },
        { korean: '무슨 요일 / 며칠', english: 'what day / what date' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
