// Level 3 Cluster — Position, Endings/Register, Word Builders, Irregulars
// Combines TTMIK Workbook Lessons 3 (position), 16/25/27/28 (endings),
// 23/30 (Hanja word builders), and 11/24/26/29 (irregulars).

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l3c6-orientation',
  position: 'l3c6-position',
  endings: 'l3c6-endings',
  register: 'l3c6-register',
  hanja: 'l3c6-hanja',
  irregulars: 'l3c6-irregulars',
  reading: 'l3c6-reading',
  speaking: 'l3c6-speaking',
  writing: 'l3c6-writing',
  task: 'l3c6-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Use 5 position words.', 'Suggest with 청유형, observe with -네요, switch between 반말 and 존댓말.', 'Decode words with Hanja 학(學) and 실(室).', 'Conjugate 4 irregular-verb classes (ㅂ, 르, ㄷ, ㅅ).'],
    task: 'Imagine teaching a beginner — you cover position, register, common words, and conjugation tricks.' },
  { id: ACT.position, section: 'Position & Direction', title: '앞·뒤·옆·위·밑·안·밖',
    goals: ['Use position words with 에.'],
    task: 'Describe 3 spatial relations.' },
  { id: ACT.endings, section: 'Endings', title: '청유형 / -네요 / -자',
    goals: ['Use 청유형 -아/어요 (let\'s).', '-네요 (mild observation).', '-자 (반말 let\'s).'],
    task: 'Convert 1 suggestion across all 3 forms.' },
  { id: ACT.register, section: 'Register', title: '반말 vs 존댓말',
    goals: ['Switch register based on relationship.'],
    task: 'Rewrite 3 sentences in both registers.' },
  { id: ACT.hanja, section: 'Word Builders', title: 'Hanja roots — 학(學) and 실(室)',
    goals: ['Recognize 학(學) in 학교, 학생, 학습.', 'Recognize 실(室) in 교실, 사무실, 거실.'],
    task: 'Decode 5 compound words.' },
  { id: ACT.irregulars, section: 'Irregulars', title: 'ㅂ / 르 / ㄷ / ㅅ irregular verbs',
    goals: ['Apply each irregular conjugation.'],
    task: 'Conjugate 1 verb of each type.' },
  { id: ACT.reading, section: 'Reading', title: '읽기 — All-in-one paragraph',
    goals: ['Read a paragraph with positions + endings + Hanja + irregulars.'],
    task: 'Label features.' },
  { id: ACT.speaking, section: 'Speaking', title: '말하기 — Teach a beginner',
    goals: ['Explain Korean to a beginner.'],
    task: 'Teach 3 features.' },
  { id: ACT.writing, section: 'Writing', title: '쓰기 — Mini Korean lesson',
    goals: ['Write a 5-6 sentence lesson on one feature.'],
    task: 'Write your own.' },
  { id: ACT.task, section: 'Task', title: '과제 — Korean tutor',
    goals: ['Be a Korean tutor for one session.'],
    task: 'Tutor the AI on Korean basics.' },
];

const lesson = {
  title: 'Level 3 · Position, Endings, Word Builders, Irregulars (combined cluster)',
  category: 'daily-life',
  difficulty: 'advanced',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'grammar',
  activities,
  expressionPractice: [
    { id: 'switching-register', label: 'Switching register', goal: 'Convert between 존댓말 and 반말.' },
    { id: 'decoding-hanja', label: 'Decoding Hanja', goal: 'Spot 학 or 실 in compounds.' },
    { id: 'conjugating-irregular', label: 'Conjugating irregulars', goal: 'Apply ㅂ/르/ㄷ/ㅅ correctly.' },
  ],
  relatedPools: ['pos-prefix-suffix', 'pos-hanja-phrases'],
  content: [
    createContentItem('Cluster goal', 'mixed grammar', 'By end: master position, register switching, Hanja recognition, irregular verbs.', 'word', '5 areas combined', 'Mixed cluster.', null, [ACT.orientation]),

    createContentItem('앞에', 'ape', 'in front', 'word', '학교 앞에 카페가 있어요.', 'Cafe in front of school.', null, [ACT.position]),
    createContentItem('뒤에', 'dwie', 'behind', 'word', '집 뒤에 산이 있어요.', 'Mountain behind house.', null, [ACT.position]),
    createContentItem('옆에', 'yeope', 'next to', 'word', '카페 옆에 도서관이 있어요.', 'Library next to cafe.', null, [ACT.position]),
    createContentItem('위에', 'wie', 'on top', 'word', '책상 위에 책이 있어요.', 'Book on desk.', null, [ACT.position]),
    createContentItem('밑에', 'mite', 'under', 'word', '의자 밑에 가방이 있어요.', 'Bag under chair.', null, [ACT.position]),
    createContentItem('안에', 'ane', 'inside', 'word', '가방 안에 책이 있어요.', 'Book inside bag.', null, [ACT.position]),
    createContentItem('밖에', 'bakke', 'outside', 'word', '집 밖에서 만나요.', 'Meet outside.', null, [ACT.position]),

    createContentItem('청유형 -아/어요 — let\'s', 'cheongyu', 'Suggest action with polite form.', 'sentence', '같이 점심 먹어요!', 'Let us eat lunch!',
      [{ korean: '먹 + 어요!', english: 'let us eat!' }, { korean: '가 + 아요!', english: 'let us go!' }], [ACT.endings]),
    createContentItem('-네요 — mild observation', 'neyo', 'Express mild surprise / observation.', 'sentence', '비가 오네요!', 'Oh, it is raining!',
      [{ korean: 'A-네요', english: 'adjective' }, { korean: 'V-네요', english: 'verb' }, { korean: 'tone', english: 'natural observation' }], [ACT.endings]),
    createContentItem('-자 — casual let\'s', 'ja', 'Casual let\'s form, used with close friends.', 'sentence', '같이 가자!', 'Let us go (casual)!',
      [{ korean: '가 + 자', english: 'let us go (반말)' }, { korean: '먹 + 자', english: 'let us eat (반말)' }], [ACT.endings]),

    createContentItem('존댓말', 'jondaetmal', 'polite/formal speech', 'word', '안녕하세요? — 식사하셨어요?', 'Hello — have you eaten?', null, [ACT.register]),
    createContentItem('반말', 'banmal', 'casual / informal speech', 'word', '안녕? — 밥 먹었어?', 'Hi — did you eat?', null, [ACT.register]),
    createContentItem('Switching contexts', 'when to switch', 'Use 존댓말 with strangers, older, professional. 반말 with close friends.', 'sentence', '같이 가요 (polite) → 같이 가 (casual)', 'Drop the 요 for casual.',
      [{ korean: '~요 → ~ (drop)', english: 'simplest switch' }, { korean: '~ㅂ니다 → ~다', english: 'formal to plain' }], [ACT.register]),

    createContentItem('학(學) — study/learning', 'hak', 'Hanja root meaning study.', 'word', '학교, 학생, 학습, 학자', 'school, student, study, scholar.',
      [{ korean: '학교 (學校)', english: 'school' }, { korean: '학생 (學生)', english: 'student' }, { korean: '학습 (學習)', english: 'study/learn' }, { korean: '학자 (學者)', english: 'scholar' }], [ACT.hanja]),
    createContentItem('실(室) — room', 'sil', 'Hanja root meaning room.', 'word', '교실, 사무실, 거실, 침실', 'classroom, office, living room, bedroom.',
      [{ korean: '교실 (敎室)', english: 'classroom' }, { korean: '사무실 (事務室)', english: 'office' }, { korean: '거실 (居室)', english: 'living room' }, { korean: '침실 (寢室)', english: 'bedroom' }], [ACT.hanja]),
    createContentItem('학습', 'hakseup', 'study/learn (學習)', 'word', '한국어 학습이 어려워요.', 'Korean study is hard.', null, [ACT.hanja]),
    createContentItem('Decoding strategy', 'meaning from parts', 'Even unfamiliar Hanja words: if you know the parts, you can guess.', 'sentence', '실험실 = 실험 (experiment) + 실 (room) = lab.', 'Combine known roots.',
      null, [ACT.hanja]),

    createContentItem('ㅂ-irregular: 덥다 → 더워요', 'beop', 'Stem-ending ㅂ → 우 before vowel.', 'sentence', '오늘 정말 더워요.', 'Really hot today.',
      [{ korean: '덥 + 어요 → 더워요', english: 'hot' }, { korean: '쉽 + 어요 → 쉬워요', english: 'easy' }, { korean: '맵 + 어요 → 매워요', english: 'spicy' }], [ACT.irregulars]),
    createContentItem('르-irregular: 모르다 → 몰라요', 'reu', '르 stem doubles to ㄹㄹ before vowel.', 'sentence', '죄송해요, 잘 몰라요.', 'Sorry, I do not know.',
      [{ korean: '모르 + 아요 → 몰라요', english: 'do not know' }, { korean: '빠르 + 아요 → 빨라요', english: 'fast' }, { korean: '부르 + 어요 → 불러요', english: 'call/sing' }], [ACT.irregulars]),
    createContentItem('ㄷ-irregular: 듣다 → 들어요', 'd', 'Stem-ending ㄷ → ㄹ before vowel.', 'sentence', '매일 음악을 들어요.', 'I listen to music daily.',
      [{ korean: '듣 + 어요 → 들어요', english: 'listen' }, { korean: '걷 + 어요 → 걸어요', english: 'walk' }], [ACT.irregulars]),
    createContentItem('ㅅ-irregular: 짓다 → 지어요', 's', 'Stem-ending ㅅ drops before vowel.', 'sentence', '시를 지어요.', 'I compose a poem.',
      [{ korean: '짓 + 어요 → 지어요', english: 'build/compose' }, { korean: '낫 + 아요 → 나아요', english: 'recover' }], [ACT.irregulars]),

    createContentItem('All-in-one paragraph', 'reading',
      'Read this paragraph using all 5 features.',
      'sentence',
      '저는 학교에서 한국어를 공부해요. 학교 앞에 카페가 있고 학교 뒤에는 도서관이 있어요. 한국어가 정말 어려워요 (ㅂ-irreg)! 그래도 매일 음악을 들으면서 (ㄷ-irreg) 공부해요. 오늘은 친구하고 카페에 같이 가자! 비가 오네요. 우산 가져와!',
      'I study Korean at school. There is a cafe in front and library behind. Korean is really hard! But I study daily while listening to music. Today let us go to the cafe with a friend! Oh, it is raining. Bring umbrella!',
      [
        { korean: '학교 앞 / 뒤', english: 'position' },
        { korean: '어려워요', english: 'ㅂ-irreg' },
        { korean: '들으면서', english: 'ㄷ-irreg' },
        { korean: '가자', english: '반말 -자' },
        { korean: '오네요', english: '-네요' },
      ],
      [ACT.reading]),

    createContentItem('Teach a beginner', 'speaking',
      'Explain a feature.',
      'sentence', '한국어에서는 학(學)이 학생, 학교, 학습에 다 있어요. 학생은 \'배우는 사람\'을 뜻해요. 그래서 한국어 단어를 배울 때 학 같은 한자를 알면 도움이 돼요.',
      'In Korean, 학 appears in student, school, study. 학생 means "one who studies". So knowing Hanja like 학 helps when learning Korean vocab.',
      null, [ACT.speaking]),

    createContentItem('Mini Korean lesson', 'writing',
      'Sample lesson on ㅂ-irregular.',
      'sentence',
      '오늘은 ㅂ 불규칙 동사를 배워 볼게요. 한국어 형용사 중에는 ㅂ으로 끝나는 게 많아요. 예를 들어 덥다, 춥다, 맵다, 어렵다 등이에요. 이 단어들은 모음 앞에서 ㅂ이 \'우\'로 변해요. 그래서 \'덥다\'는 \'더워요\'가 돼요. \'어렵다\'는 \'어려워요\'예요. 처음에는 어려운데 자주 쓰면 익숙해져요.',
      'Today let us learn ㅂ-irregular verbs. Many Korean adjectives end in ㅂ. e.g., hot, cold, spicy, hard. Before vowel, ㅂ changes to 우. So 덥다 becomes 더워요. 어렵다 becomes 어려워요. Hard at first but you get used to it.',
      null, [ACT.writing]),

    createContentItem('과제: Korean tutor', 'task',
      'Roleplay: Tutor the AI on one Korean feature (your choice).',
      'conversation',
      'AI: 한국어 어떤 것을 가르쳐 주실 수 있어요?\nYou: ~ 가르쳐 드릴게요. (pick: position / endings / hanja / irregulars)\nAI: 예를 들어 주세요.\nYou: [example with all elements]\nAI: 잘 알겠어요. 감사합니다!',
      'AI tutor will play the learner.',
      [
        { korean: '5 features', english: 'pick one' },
        { korean: '청유형 / -네요 / 반말', english: 'register switching' },
        { korean: '학 / 실', english: 'Hanja roots' },
        { korean: 'ㅂ/르/ㄷ/ㅅ irreg', english: 'conjugation' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
