// Level 1 Unit 21 — Hopes & dreams
// Source: Book 1A·16 (유명한 수영 선수가 되었으면 좋겠어)
// Functions: career hopes, expressing wishes, planning the future.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u21-orientation',
  pronunciation: 'l1u21-pronunciation',
  vocabularyJobs: 'l1u21-vocab-jobs',
  vocabularyFuture: 'l1u21-vocab-fut',
  grammarWish: 'l1u21-grammar-wish',
  grammarBecome: 'l1u21-grammar-become',
  grammarAfter: 'l1u21-grammar-after',
  reading: 'l1u21-reading',
  listening: 'l1u21-listening',
  writing: 'l1u21-writing',
  culture: 'l1u21-culture',
  task: 'l1u21-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Talk about your future and dream job.', 'Express wishes with V-았/었으면 좋겠다.', 'Sequence events with V-(으)ㄴ 후에 / 전에.'],
    task: 'Imagine telling your professor what you hope to become after graduating from Kumoh.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Wish phrase sounds',
    goals: ['Apply 격음화 + 연음 in 됐으면 → [돼쓰면] / 좋겠어요 → [조케써요].'],
    task: 'Read each wish form aloud.' },
  { id: ACT.vocabularyJobs, section: 'Vocabulary I', title: 'Jobs & professions',
    goals: ['Name 12+ common jobs.'],
    task: 'Pick three jobs you might pursue.' },
  { id: ACT.vocabularyFuture, section: 'Vocabulary II', title: 'Future & aspiration words',
    goals: ['Use 꿈·미래·목표·계획·졸업·취업·노력하다.'],
    task: 'Pair each future word with an action.' },
  { id: ACT.grammarWish, section: 'Grammar I', title: 'V-았/었으면 좋겠다 — I wish that',
    goals: ['Attach -았/었으면 + 좋겠다 to wish for an outcome.', 'Note: past form, but means wish/hope (present/future).'],
    task: 'Make three wish sentences.' },
  { id: ACT.grammarBecome, section: 'Grammar II', title: 'N이/가 되다 — become N',
    goals: ['Use the subject particle 이/가 with 되다, not 을/를.', 'Combine with 고 싶다 → "want to become".', 'Use descriptive 유명한 / 좋은 to modify the job.'],
    task: 'State three "want to become" sentences.' },
  { id: ACT.grammarAfter, section: 'Grammar III', title: 'V-(으)ㄴ 후에 / 전에 — after / before',
    goals: ['Use V-(으)ㄴ 후에 for "after V-ing".', 'Use V-기 전에 for "before V-ing".', 'Use N 후에 / 전에 with nouns.'],
    task: 'Sequence three events.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A career letter',
    goals: ['Read a personal-statement-style paragraph.'],
    task: 'Identify the writer\'s dream + path + reason.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Sharing dreams',
    goals: ['Follow a 6-turn dream-sharing dialogue.'],
    task: 'Reproduce with your own dream.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — My dream',
    goals: ['Write 5-6 sentences about your dream + plan.'],
    task: 'Write your own future plan.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean career pressure',
    goals: ['Understand 취업 (job hunting) pressure.', 'Know 대기업 / 중소기업 / 공무원 hierarchy.'],
    task: 'Compare Korean career culture with your own.' },
  { id: ACT.task, section: 'Task', title: '과제 — Tell your professor your dream',
    goals: ['Combine wish, become, and time-sequence in a continuous scene.'],
    task: 'Tell the AI tutor (playing your professor) your career dream.' },
];

const lesson = {
  title: '레벨 1 · 21과: 유명한 수영 선수가 되었으면 좋겠어요 (Hopes and Dreams)',
  category: 'career',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'expressing-wish', label: 'Expressing a wish', goal: 'Use V-았/었으면 좋겠다.' },
    { id: 'stating-dream', label: 'Stating a future job', goal: 'Use N이/가 되고 싶다.' },
    { id: 'sequencing-future', label: 'Sequencing future events', goal: 'Use V-(으)ㄴ 후에 / V-기 전에.' },
  ],
  relatedPools: ['topic-people', 'topic-society'],
  content: [
    createContentItem('Lesson goal', 'future', 'By end: state your career dream, express wishes, sequence future events.', 'word', 'Functions: dream · wish · become · sequence', 'Career-talk toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'professor chat', 'Your Korean professor asks about your post-graduation plan. You should be able to state your dream + path + reason in 3-4 sentences.', 'word', 'Professor: 졸업 후에 뭐 하고 싶어요? — You: 한국에서 소프트웨어 개발자가 되고 싶어요.', 'Prof: What after graduation? — You: I want to become a software developer in Korea.', null, [ACT.orientation]),

    createContentItem('됐으면 → [돼쓰면]', 'dwaesseumyeon', '연음 + ㅆ: smooth past-conditional form.', 'word', '의사가 됐으면 좋겠어요. → [돼쓰면 조케써요]', 'I wish to become a doctor.', null, [ACT.pronunciation]),
    createContentItem('좋겠어요 → [조케써요]', 'jokesseoyo', '격음화: ㅎ + ㄱ → ㅋ.', 'word', '좋겠어요. → [조케써요]', 'It would be good.', null, [ACT.pronunciation]),
    createContentItem('졸업한 → [조러판]', 'joreopan', '격음화: ㅂ + ㅎ → ㅍ; 연음 elsewhere.', 'word', '졸업한 후에', 'After graduating.', null, [ACT.pronunciation]),
    createContentItem('유명한 → [유명한]', 'yumyeonghan', 'No major change. Clear ㄴ받침.', 'word', '유명한 가수', 'famous singer.', null, [ACT.pronunciation]),

    createContentItem('의사', 'uisa', 'doctor', 'word', '의사가 되고 싶어요.', 'I want to be a doctor.', null, [ACT.vocabularyJobs]),
    createContentItem('변호사', 'byeonhosa', 'lawyer', 'word', '변호사도 멋있어요.', 'Being a lawyer is also cool.', null, [ACT.vocabularyJobs]),
    createContentItem('선생님', 'seonsaengnim', 'teacher', 'word', '한국어 선생님이 되고 싶어요.', 'I want to be a Korean teacher.', null, [ACT.vocabularyJobs]),
    createContentItem('교수', 'gyosu', 'professor', 'word', '대학 교수가 되고 싶어요.', 'I want to be a professor.', null, [ACT.vocabularyJobs]),
    createContentItem('가수', 'gasu', 'singer', 'word', '가수가 꿈이에요.', 'My dream is to be a singer.', null, [ACT.vocabularyJobs]),
    createContentItem('배우', 'baeu', 'actor / actress', 'word', '배우가 되고 싶어요.', 'I want to be an actor.', null, [ACT.vocabularyJobs]),
    createContentItem('운동선수', 'undongseonsu', 'athlete', 'word', '유명한 운동선수가 되고 싶어요.', 'I want to be a famous athlete.', null, [ACT.vocabularyJobs]),
    createContentItem('수영 선수', 'suyeong seonsu', 'swimmer', 'word', '수영 선수가 되었으면 좋겠어요.', 'I wish to become a swimmer.', null, [ACT.vocabularyJobs]),
    createContentItem('소프트웨어 개발자', 'sopeuteuwe-eo gaebalja', 'software developer', 'word', '소프트웨어 개발자가 되고 싶어요.', 'I want to be a developer.', null, [ACT.vocabularyJobs]),
    createContentItem('엔지니어', 'enjinieo', 'engineer', 'word', '엔지니어를 꿈꾸고 있어요.', 'I dream of being an engineer.', null, [ACT.vocabularyJobs]),
    createContentItem('회사원', 'hoesawon', 'office worker', 'word', '대기업 회사원이 되고 싶어요.', 'I want to work for a big company.', null, [ACT.vocabularyJobs]),
    createContentItem('공무원', 'gongmuwon', 'civil servant', 'word', '공무원도 안정적이에요.', 'Civil servant is also stable.', null, [ACT.vocabularyJobs]),
    createContentItem('기자', 'gija', 'journalist / reporter', 'word', '기자가 멋있어요.', 'Being a journalist is cool.', null, [ACT.vocabularyJobs]),
    createContentItem('요리사', 'yorisa', 'chef', 'word', '요리사가 되고 싶어요.', 'I want to be a chef.', null, [ACT.vocabularyJobs]),

    createContentItem('꿈', 'kkum', 'dream / aspiration', 'word', '제 꿈은 의사예요.', 'My dream is to be a doctor.', null, [ACT.vocabularyFuture]),
    createContentItem('미래', 'mirae', 'future', 'word', '미래에 대해 생각해요.', 'I think about the future.', null, [ACT.vocabularyFuture]),
    createContentItem('목표', 'mokpyo', 'goal', 'word', '제 목표는 토픽 6급이에요.', 'My goal is TOPIK level 6.', null, [ACT.vocabularyFuture]),
    createContentItem('계획', 'gyehoek', 'plan', 'word', '계획을 세워요.', 'I make a plan.', null, [ACT.vocabularyFuture]),
    createContentItem('되다', 'doeda', 'to become', 'word', '의사가 되고 싶어요.', 'I want to become a doctor.', null, [ACT.vocabularyFuture]),
    createContentItem('졸업', 'joreop', 'graduation', 'word', '내년에 졸업해요.', 'I graduate next year.', null, [ACT.vocabularyFuture]),
    createContentItem('취업', 'chwieop', 'getting a job', 'word', '취업이 어려워요.', 'Getting a job is hard.', null, [ACT.vocabularyFuture]),
    createContentItem('직업', 'jigeop', 'job', 'word', '직업을 정해야 해요.', 'I have to choose a job.', null, [ACT.vocabularyFuture]),
    createContentItem('노력하다', 'noryeokhada', 'to work hard / make an effort', 'word', '꿈을 위해 노력해요.', 'I work hard for my dream.', null, [ACT.vocabularyFuture]),
    createContentItem('유명하다', 'yumyeonghada', 'to be famous', 'word', '유명한 가수예요.', 'A famous singer.', null, [ACT.vocabularyFuture]),
    createContentItem('성공하다', 'seonggonghada', 'to succeed', 'word', '성공하고 싶어요.', 'I want to succeed.', null, [ACT.vocabularyFuture]),

    createContentItem('V-았/었으면 좋겠다 — I wish that', 'wish', 'Attach -았/었으면 to verb stem + 좋겠다. The form is past but expresses a present wish.', 'sentence', '수영 선수가 되었으면 좋겠어요.', 'I wish I could become a swimmer.',
      [
        { korean: '되 + 었으면 → 되었으면', english: 'becoming → if becoming' },
        { korean: '갖 + 었으면 → 가졌으면', english: 'wish I had' },
        { korean: '+ 좋겠어요', english: 'it would be good' },
      ],
      [ACT.grammarWish]),
    createContentItem('Present-form variant', 'V-(으)면 좋겠다', 'You can also use the simpler form V-(으)면 좋겠다 (present-form). Same meaning.', 'sentence', '한국어를 잘하면 좋겠어요.', 'I wish I could speak Korean well.',
      null, [ACT.grammarWish]),
    createContentItem('Negative wish', '안 V-았/었으면', 'For "I wish X did NOT happen", use 안 V-았/었으면.', 'sentence', '내일 비가 안 왔으면 좋겠어요.', 'I wish it would not rain tomorrow.',
      null, [ACT.grammarWish]),

    createContentItem('N이/가 되다 — become N', 'become', 'Use SUBJECT particle 이/가 with 되다, NOT object 을/를.', 'sentence', '의사가 되고 싶어요. (NOT 의사를 되고 싶어요)', 'I want to become a doctor.',
      [{ korean: '의사 + 가 + 되다', english: 'consonant noun → 이' }, { korean: '가수 + 가 + 되다', english: 'vowel noun → 가' }], [ACT.grammarBecome]),
    createContentItem('Combine with -고 싶다', 'want to become', '-(이)가 + 되고 싶다 = "want to become".', 'sentence', '한국어 선생님이 되고 싶어요.', 'I want to become a Korean teacher.',
      null, [ACT.grammarBecome]),
    createContentItem('Use descriptive form', 'famous/good + job', 'Add A-(으)ㄴ + N + 이/가 + 되다 to specify the type of job.', 'sentence', '유명한 가수가 되었으면 좋겠어요.', 'I wish to become a famous singer.',
      [{ korean: '유명한 가수', english: 'famous singer' }, { korean: '좋은 의사', english: 'good doctor' }, { korean: '훌륭한 선생님', english: 'excellent teacher' }], [ACT.grammarBecome]),

    createContentItem('V-(으)ㄴ 후에 — after V-ing', 'after', 'Attach -ㄴ 후에 (vowel) or -은 후에 (consonant) to verb stem.', 'sentence', '졸업한 후에 한국에서 일하고 싶어요.', 'After graduating I want to work in Korea.',
      [{ korean: '졸업하 + ㄴ 후에', english: '졸업한 후에' }, { korean: '먹 + 은 후에', english: '먹은 후에 (after eating)' }], [ACT.grammarAfter]),
    createContentItem('V-기 전에 — before V-ing', 'before', 'Attach -기 전에 to verb stem (no irregular changes).', 'sentence', '졸업하기 전에 한국어 시험을 보고 싶어요.', 'Before graduating I want to take the Korean test.',
      [{ korean: '졸업하 + 기 전에', english: '졸업하기 전에' }, { korean: '자 + 기 전에', english: '자기 전에 (before sleeping)' }], [ACT.grammarAfter]),
    createContentItem('N + 후에 / 전에', 'with nouns', 'For nouns, just attach 후에 or 전에 directly (no verb stem).', 'sentence', '수업 후에 / 시험 전에', 'After class / before the exam.',
      null, [ACT.grammarAfter]),

    createContentItem('A career letter', 'reading',
      'Read aloud.',
      'sentence',
      '제 이름은 사라예요. 미국에서 왔어요. 금오공과대학교에서 컴퓨터공학을 공부하고 있어요. 제 꿈은 소프트웨어 개발자가 되는 거예요. 졸업한 후에 한국 회사에서 일하고 싶어요. 한국어를 더 잘했으면 좋겠어요. 그래서 매일 공부해요.',
      'My name is Sarah. I came from the USA. I study Computer Engineering at Kumoh National Institute of Technology. My dream is to become a software developer. After graduating I want to work at a Korean company. I wish I were better at Korean. So I study every day.',
      [
        { korean: '꿈은 ~ 거예요', english: 'my dream is ~' },
        { korean: '졸업한 후에', english: 'after graduating' },
        { korean: '잘했으면 좋겠어요', english: 'wish I were better' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Use the wish/become forms.', 'sentence',
      'Q1: 사라의 꿈이 뭐예요? · Q2: 어느 학교에서 공부해요? · Q3: 졸업 후에 뭐 하고 싶어요?',
      'Q1: Sarah\'s dream? Q2: Which school? Q3: After graduating?',
      [
        { korean: 'A1: 소프트웨어 개발자가 되는 거예요.', english: 'To be a software developer.' },
        { korean: 'A2: 금오공과대학교에서요.', english: 'Kumoh National Institute of Technology.' },
        { korean: 'A3: 한국 회사에서 일하고 싶어요.', english: 'Work at a Korean company.' },
      ],
      [ACT.reading]),

    createContentItem('Sharing dreams', 'listening',
      'Two students share their futures.',
      'conversation',
      'A: 사라 씨 꿈이 뭐예요?\nB: 저는 한국어 선생님이 되고 싶어요. 외국 학생들에게 한국어를 가르치고 싶어요.\nA: 멋있네요! 졸업한 후에 한국에서 일할 거예요?\nB: 네, 그러고 싶어요. 민수 씨는요?\nA: 저는 소프트웨어 개발자가 되었으면 좋겠어요. 금오공대에서 컴퓨터공학을 공부하고 있어요.\nB: 그럼 저는 한국어를 가르치고, 민수 씨는 앱을 만들어요. 좋네요!',
      'A: Sarah, your dream? B: I want to be a Korean teacher. Teach foreign students. A: Cool! Work in Korea after graduating? B: Yes, I hope so. You? A: I wish to become a software developer. I study CompEng at Kumoh. B: Then I teach Korean, you make apps. Great!',
      [
        { korean: '꿈이 뭐예요?', english: 'what is your dream?' },
        { korean: '가르치고 싶어요', english: 'want to teach' },
        { korean: '~ 되었으면 좋겠어요', english: 'wish to become ~' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'dream essay',
      'Use this structure.',
      'sentence',
      '제 꿈은 [직업]이/가 되는 거예요. 지금 [학교/회사]에서 [활동]을/를 하고 있어요. 졸업한 후에 [목표]을/를 하고 싶어요. [한국어를 더 잘했으면 좋겠어요]. 그래서 매일 노력해요.',
      '[dream job] · [current activity] · [post-graduation goal] · [language wish] · [effort]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 5-6 sentences about your dream. Use 되고 싶다, V-(으)ㄴ 후에, and one -았/었으면 좋겠다.',
      'sentence', 'Example: 제 꿈은 의사가 되는 거예요. 지금 의학을 공부해요. 졸업한 후에 좋은 병원에서 일하고 싶어요. 한국 의사 시험에 합격했으면 좋겠어요. 매일 열심히 공부해요.',
      'Example: My dream is to be a doctor. Now I study medicine. After graduating I want to work at a good hospital. I wish to pass the Korean medical exam. I study hard daily.',
      null, [ACT.writing]),

    createContentItem('Korean career culture', 'culture',
      '취업 (job hunting) is a major life event in Korea. Top tier: 대기업 (Samsung, Hyundai, LG) → high pay, prestige. Middle: 중소기업 (SMEs) → lower pay. Stability tier: 공무원 (civil servant) → low pay but guaranteed for life. Many students take "공무원 시험" — a fierce annual exam.',
      'sentence', '한국에서는 대기업, 공무원, 전문직이 인기 있어요.',
      'In Korea, big companies, civil service, and professional jobs are popular.',
      [
        { korean: '대기업', english: 'big company (Samsung etc.)' },
        { korean: '중소기업', english: 'SME' },
        { korean: '공무원', english: 'civil servant' },
        { korean: '취업', english: 'job hunting' },
      ],
      [ACT.culture]),
    createContentItem('TOPIK and career', 'culture',
      '토픽 (TOPIK = Test of Proficiency in Korean) is the official Korean test. Levels 1-6. Levels 3-4 are needed for most Korean jobs; level 6 is essential for academic / professional roles.',
      'sentence', '한국 회사에 취직하려면 토픽 4급 이상이 필요해요.',
      'For Korean companies you need TOPIK 4 or higher.',
      [{ korean: '토픽', english: 'TOPIK' }, { korean: '4급 이상', english: 'level 4 or higher' }], [ACT.culture]),

    createContentItem('과제: Tell your professor your dream', 'task',
      'Roleplay: Your Korean professor asks about your post-graduation plan. Use 되고 싶다, V-(으)ㄴ 후에, V-았/었으면 좋겠다, descriptive A-(으)ㄴ N.',
      'conversation',
      'Professor: 졸업한 후에 뭐 하고 싶어요?\nYou: [dream + 되고 싶어요]\nProfessor: 어떤 ~이/가 되고 싶어요?\nYou: [descriptive + 되고 싶어요]\nProfessor: 한국에서 일하고 싶어요?\nYou: [yes + reason + 좋겠어요]\nProfessor: 잘 준비하세요.',
      'AI tutor will play the professor.',
      [
        { korean: '~이/가 되고 싶어요', english: 'I want to become ~' },
        { korean: '졸업한 후에 ~', english: 'after graduating ~' },
        { korean: '~ 했으면 좋겠어요', english: 'I wish to ~' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
