// Level 1 Unit 12 — Past activities
// Source: Book 1B·9 (주말에 친구하고 등산했어요)
// Functions: describing what you did, talking about who you did it with.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u12-orientation',
  pronunciation: 'l1u12-pronunciation',
  vocabularyActivities: 'l1u12-vocab-act',
  vocabularyTime: 'l1u12-vocab-time',
  grammarPast: 'l1u12-grammar-past',
  grammarCompanion: 'l1u12-grammar-with',
  grammarSequence: 'l1u12-grammar-seq',
  reading: 'l1u12-reading',
  listening: 'l1u12-listening',
  writing: 'l1u12-writing',
  culture: 'l1u12-culture',
  task: 'l1u12-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Conjugate V-았/었어요 (past polite).', 'Talk about what you did, when, where, and with whom.', 'Connect two past actions with -고.'],
    task: 'Imagine a Korean friend asks 주말에 뭐 했어요? — you should give 3 sentences with when, where, and with whom.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Past-tense endings',
    goals: ['Apply -았/었어요 → [-아써요/-어써요] (tensification + 연음).', 'Apply 등산하다 → 등산했어요 → [등산해써요].'],
    task: 'Read each past-tense verb aloud.' },
  { id: ACT.vocabularyActivities, section: 'Vocabulary I', title: 'Activity verbs',
    goals: ['Learn 12+ activity verbs typical of weekends.'],
    task: 'List three activities you did last weekend.' },
  { id: ACT.vocabularyTime, section: 'Vocabulary II', title: 'Past-time markers',
    goals: ['Use 어제·그저께·지난주·지난주말·지난달·작년.'],
    task: 'Pair an activity with a past-time marker.' },
  { id: ACT.grammarPast, section: 'Grammar I', title: 'V-았/었어요 — past polite',
    goals: ['Apply: ㅏ/ㅗ stem → -았어요, other vowels → -었어요, 하다 → 했어요.', 'Conjugate 5+ verbs into past polite.'],
    task: 'Conjugate five verbs into past polite.' },
  { id: ACT.grammarCompanion, section: 'Grammar II', title: 'N하고/와/과/(이)랑 + 같이 — with someone',
    goals: ['Pick the right "with" particle.', 'Add 같이 for emphasis.'],
    task: 'Make two "with someone" past sentences.' },
  { id: ACT.grammarSequence, section: 'Grammar III', title: 'V-고 — and then',
    goals: ['Connect two same-tense actions with -고.', 'Difference from -아/어서 (sequence with NO causal link).'],
    task: 'Combine two past actions with -고.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A weekend diary',
    goals: ['Read a 5-sentence weekend diary.'],
    task: 'Answer Q: What, when, where, with whom?' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Weekend recap',
    goals: ['Follow a 5-turn weekend-recap dialogue.'],
    task: 'Reproduce with your own weekend.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Your last weekend',
    goals: ['Write 4-5 past-tense sentences about last weekend.'],
    task: 'Write your own weekend diary.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — 등산 culture and Korean weekends',
    goals: ['Know why 등산 is a Korean national pastime.', 'Understand 단풍놀이, 벚꽃놀이 outings.'],
    task: 'Pick one Korean weekend outing you would try.' },
  { id: ACT.task, section: 'Task', title: '과제 — Tell me about your weekend',
    goals: ['Combine past tense, companion, location, and sequence in one continuous scene.'],
    task: 'Roleplay sharing your weekend with the AI tutor.' },
];

const lesson = {
  title: '레벨 1 · 12과: 주말에 친구하고 등산했어요 (Past Activities)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-what-did', label: 'Asking what someone did', goal: 'Use 뭐 했어요? for past activity.' },
    { id: 'describing-past-activity', label: 'Describing past activity', goal: 'Combine when + with whom + where + V-았/었어요.' },
    { id: 'chaining-actions', label: 'Chaining two past actions', goal: 'Connect two same-tense verbs with -고.' },
  ],
  relatedPools: ['topic-people'],
  content: [
    createContentItem('Lesson goal', 'past tense', 'By end: conjugate past tense; describe when, where, with whom, and connect two past actions.', 'word', 'Functions: past conjugation · companion · location · sequence', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Monday morning', 'It is Monday morning. Your classmate asks "주말에 뭐 했어요?" — you should respond with 2-3 past sentences.', 'word', 'Classmate: 주말에 뭐 했어요? — You: 친구하고 등산했어요.', 'Classmate: What did you do on the weekend? — You: I went hiking with a friend.', null, [ACT.orientation]),

    createContentItem('했어요 → [해써요]', 'haesseoyo', '연음 + tensification: ㅆ받침 of 했 jumps to 어요.', 'word', '운동했어요. → [운동해써요]', 'I exercised.', null, [ACT.pronunciation]),
    createContentItem('갔어요 → [가써요]', 'gasseoyo', 'Same pattern: ㅆ받침 of 갔 jumps to 어요.', 'word', '학교에 갔어요. → [학꾜에 가써요]', 'I went to school.', null, [ACT.pronunciation]),
    createContentItem('먹었어요 → [머거써요]', 'meogeosseoyo', '연음: ㄱ받침 of 먹 jumps to 었; ㅆ받침 jumps to 어요.', 'word', '점심을 먹었어요. → [머거써요]', 'I ate lunch.', null, [ACT.pronunciation]),
    createContentItem('만났어요 → [만나써요]', 'mannasseoyo', 'No major change — just say the past form smoothly.', 'word', '친구를 만났어요.', 'I met a friend.', null, [ACT.pronunciation]),

    createContentItem('등산', 'deungsan', 'hiking', 'word', '주말에 등산을 했어요.', 'I went hiking on the weekend.', null, [ACT.vocabularyActivities]),
    createContentItem('산책', 'sanchaek', 'a walk / stroll', 'word', '저녁에 산책을 했어요.', 'I took a walk in the evening.', null, [ACT.vocabularyActivities]),
    createContentItem('운동', 'undong', 'exercise / sports', 'word', '아침에 운동을 했어요.', 'I exercised in the morning.', null, [ACT.vocabularyActivities]),
    createContentItem('영화', 'yeonghwa', 'movie', 'word', '영화를 봤어요.', 'I watched a movie.', null, [ACT.vocabularyActivities]),
    createContentItem('여행', 'yeohaeng', 'trip / travel', 'word', '부산으로 여행을 갔어요.', 'I traveled to Busan.', null, [ACT.vocabularyActivities]),
    createContentItem('요리하다', 'yorihada', 'to cook', 'word', '집에서 요리했어요.', 'I cooked at home.', null, [ACT.vocabularyActivities]),
    createContentItem('청소하다', 'cheongsohada', 'to clean', 'word', '방을 청소했어요.', 'I cleaned my room.', null, [ACT.vocabularyActivities]),
    createContentItem('쉬다', 'swida', 'to rest', 'word', '집에서 쉬었어요.', 'I rested at home.', null, [ACT.vocabularyActivities]),
    createContentItem('사진을 찍다', 'sajin-eul jjikda', 'to take photos', 'word', '사진을 많이 찍었어요.', 'I took lots of photos.', null, [ACT.vocabularyActivities]),
    createContentItem('자전거를 타다', 'jajeongeo-reul tada', 'to ride a bicycle', 'word', '주말에 자전거를 탔어요.', 'I rode a bike on the weekend.', null, [ACT.vocabularyActivities]),
    createContentItem('쇼핑하다', 'syopinghada', 'to go shopping', 'word', '백화점에서 쇼핑했어요.', 'I shopped at the department store.', null, [ACT.vocabularyActivities]),
    createContentItem('만나다', 'mannada', 'to meet', 'word', '친구를 만났어요.', 'I met a friend.', null, [ACT.vocabularyActivities]),

    createContentItem('어제', 'eoje', 'yesterday', 'word', '어제 친구를 만났어요.', 'I met a friend yesterday.', null, [ACT.vocabularyTime]),
    createContentItem('그저께', 'geujeokke', 'the day before yesterday', 'word', '그저께 시험을 봤어요.', 'I took an exam two days ago.', null, [ACT.vocabularyTime]),
    createContentItem('지난주', 'jinanju', 'last week', 'word', '지난주에 시험을 봤어요.', 'I took an exam last week.', null, [ACT.vocabularyTime]),
    createContentItem('지난주말', 'jinanjumal', 'last weekend', 'word', '지난주말에 등산을 갔어요.', 'I went hiking last weekend.', null, [ACT.vocabularyTime]),
    createContentItem('지난달', 'jinandal', 'last month', 'word', '지난달에 여행을 했어요.', 'I traveled last month.', null, [ACT.vocabularyTime]),
    createContentItem('작년', 'jangnyeon', 'last year', 'word', '작년에 한국에 왔어요.', 'I came to Korea last year.', null, [ACT.vocabularyTime]),
    createContentItem('아까', 'akka', 'a while ago (today)', 'word', '아까 친구를 만났어요.', 'I met a friend a little while ago.', null, [ACT.vocabularyTime]),
    createContentItem('전에', 'jeone', 'before / ago', 'word', '2년 전에 시작했어요.', 'I started 2 years ago.', null, [ACT.vocabularyTime]),

    createContentItem('Rule 1 — ㅏ/ㅗ stem → -았어요', 'past 1', 'If the verb stem\'s last vowel is ㅏ or ㅗ, attach -았어요.', 'sentence', '가다 → 갔어요 · 보다 → 봤어요 · 만나다 → 만났어요', 'Stem ㅏ/ㅗ → 았.',
      [
        { korean: '가 + 았어요 → 갔어요', english: 'went' },
        { korean: '보 + 았어요 → 봤어요', english: 'saw' },
        { korean: '만나 + 았어요 → 만났어요', english: 'met' },
      ],
      [ACT.grammarPast]),
    createContentItem('Rule 2 — other vowels → -었어요', 'past 2', 'For all other stems, attach -었어요.', 'sentence', '먹다 → 먹었어요 · 마시다 → 마셨어요 · 읽다 → 읽었어요', 'Other vowels → 었.',
      [
        { korean: '먹 + 었어요 → 먹었어요', english: 'ate' },
        { korean: '마시 + 었어요 → 마셨어요', english: 'drank (contracts)' },
      ],
      [ACT.grammarPast]),
    createContentItem('Rule 3 — 하다 → 했어요', 'past 3', 'Every -하다 verb becomes -했어요.', 'sentence', '공부하다 → 공부했어요 · 운동하다 → 운동했어요', 'Always -했어요.',
      [
        { korean: '공부했어요', english: 'studied' },
        { korean: '청소했어요', english: 'cleaned' },
        { korean: '요리했어요', english: 'cooked' },
      ],
      [ACT.grammarPast]),
    createContentItem('Negation in past', '안 V-았/었어요', 'Add 안 before the past verb. For -하다, the 안 goes inside: 운동 안 했어요.', 'sentence', '안 갔어요. · 안 먹었어요. · 운동 안 했어요.', 'Negative past.',
      null, [ACT.grammarPast]),
    createContentItem('Past of N이에요/예요', 'N이었어요/였어요', 'Copula past: 학생이에요 → 학생이었어요. After vowel: -였어요.', 'sentence', '저는 학생이었어요. · 친구였어요.', 'Was a student. Was a friend.',
      null, [ACT.grammarPast]),

    createContentItem('하고 — with (everyday)', 'hago', 'Universal "with" — works for any noun, in any context.', 'sentence', '친구하고 같이 갔어요.', 'I went with my friend.',
      null, [ACT.grammarCompanion]),
    createContentItem('와/과 — with (formal)', 'wa/gwa', '와 after vowel, 과 after consonant. Common in writing.', 'sentence', '동생과 같이 갔어요.', 'I went with my sibling.',
      [{ korean: '친구 + 와', english: 'after vowel' }, { korean: '동생 + 과', english: 'after consonant' }], [ACT.grammarCompanion]),
    createContentItem('(이)랑 — with (casual)', 'irang/rang', '이랑 after consonant, 랑 after vowel. Friend-to-friend speech.', 'sentence', '친구랑 같이 갔어요.', 'I went with my friend.',
      null, [ACT.grammarCompanion]),
    createContentItem('같이 — together', 'gachi', 'Pair with the "with" particle for emphasis.', 'sentence', '친구하고 같이 영화를 봤어요.', 'I watched a movie with my friend.',
      null, [ACT.grammarCompanion]),

    createContentItem('V-고 — and then (same tense)', 'go', 'Attach -고 to the first verb stem to connect two same-tense actions.', 'sentence', '아침을 먹고 학교에 갔어요.', 'I ate breakfast and went to school.',
      [
        { korean: '먹 + 고', english: '먹고 (and ate)' },
        { korean: '두 행동을 시간 순서로', english: 'two actions in time order' },
      ],
      [ACT.grammarSequence]),
    createContentItem('-고 vs -아/어서', 'comparing', '-고 = just-and. -아/어서 = and-then-naturally / because-of-that.', 'sentence', '운동하고 점심을 먹었어요. (just sequence) · 운동해서 배가 고파요. (because of that)', 'Both link actions; -아/어서 implies cause.',
      null, [ACT.grammarSequence]),
    createContentItem('Past tense + -고', 'no tense on first verb', 'When using -고, you only tense the LAST verb. The first verb is in the bare stem form.', 'sentence', '청소하고 쉬었어요. (NOT 청소했고 쉬었어요)', 'Only the last verb shows past.',
      null, [ACT.grammarSequence]),

    createContentItem('A weekend diary', 'reading',
      'Read aloud.',
      'sentence',
      '지난주말은 정말 좋았어요. 토요일 오전에 친구하고 등산을 했어요. 산에서 사진도 많이 찍었어요. 점심에 산 아래 식당에서 비빔밥을 먹었어요. 오후에는 집에서 쉬고 영화를 봤어요. 일요일에는 가족과 같이 카페에 갔어요. 모두 행복한 시간이었어요.',
      'Last weekend was really good. Saturday morning I went hiking with a friend. I took lots of photos on the mountain. At lunch we ate bibimbap at a restaurant at the base. In the afternoon I rested at home and watched a movie. On Sunday I went to a cafe with my family. It was all happy times.',
      [
        { korean: '친구하고 등산했어요', english: 'hiked with a friend' },
        { korean: '사진을 찍었어요', english: 'took photos' },
        { korean: '쉬고 영화를 봤어요', english: 'rested and watched a movie (-고)' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Use past tense.', 'sentence',
      'Q1: 토요일에 누구하고 뭐 했어요? · Q2: 점심에 어디에서 먹었어요? · Q3: 일요일에 어디에 갔어요?',
      'Q1: Whom and what on Saturday? Q2: Where for lunch? Q3: Where on Sunday?',
      [
        { korean: 'A1: 친구하고 등산했어요.', english: 'I hiked with a friend.' },
        { korean: 'A2: 산 아래 식당에서 먹었어요.', english: 'At a restaurant at the base.' },
        { korean: 'A3: 카페에 갔어요.', english: 'I went to a cafe.' },
      ],
      [ACT.reading]),

    createContentItem('Weekend recap', 'listening',
      'Monday-morning chat.',
      'conversation',
      'A: 지난주말에 뭐 했어요?\nB: 친구하고 등산했어요. 사라 씨는요?\nA: 저는 집에서 쉬었어요. 그리고 한국 영화를 봤어요.\nB: 무슨 영화요?\nA: "기생충"이요. 정말 재미있었어요.\nB: 저도 그 영화 좋아해요.',
      'A: What did you do last weekend? B: Hiked with a friend. You? A: Rested at home and watched a Korean movie. B: What movie? A: "Parasite". It was great. B: I love that movie too.',
      [
        { korean: '~씨는요?', english: 'how about you?' },
        { korean: '재미있었어요', english: 'was fun (past)' },
      ],
      [ACT.listening]),
    createContentItem('Trip story', 'listening',
      'Recapping a recent trip.',
      'conversation',
      'A: 지난달에 여행을 갔어요.\nB: 어디로 갔어요?\nA: 제주도에 갔어요. 가족과 같이요.\nB: 어땠어요?\nA: 정말 좋았어요. 바다도 예쁘고 음식도 맛있었어요.\nB: 저도 가고 싶어요. 며칠 다녀왔어요?\nA: 3박 4일 다녀왔어요.',
      'A: I traveled last month. B: Where? A: Jeju Island. With family. B: How was it? A: Really good. The sea was pretty and food delicious. B: I want to go. How many days? A: 3 nights / 4 days.',
      [
        { korean: '어디로 갔어요?', english: 'where did you go?' },
        { korean: '어땠어요?', english: 'how was it?' },
        { korean: '3박 4일', english: '3 nights 4 days' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'diary template',
      'Use this structure for your own diary.',
      'sentence',
      '지난주말에는 [요일]에 [동행자]하고 [장소]에서 [동사]했어요. [순서접속사] [동사]. 정말 [형용사]+았/었어요.',
      '[day] · [with whom] · [place] · [verb] · [linker] · [next verb] · [feeling]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 past-tense sentences about your last weekend. Use at least one -고 connector and one companion phrase.',
      'sentence', 'Example: 지난주말에 친구하고 같이 영화를 봤어요. 그리고 식당에서 김치찌개를 먹었어요. 일요일에는 집에서 청소하고 쉬었어요. 정말 좋은 주말이었어요.',
      'Example: Last weekend I watched a movie with a friend. Then we ate kimchi stew at a restaurant. On Sunday I cleaned and rested at home. A really good weekend.',
      null, [ACT.writing]),

    createContentItem('등산 culture', 'culture',
      '등산 (hiking) is practically a Korean national sport. Mid-life Koreans hike most weekends, wearing full hiking gear (등산복) even for easy trails. The most famous hikes are 한라산 (Jeju), 설악산 (Gangwon), and 북한산 (Seoul).',
      'sentence', '한국 사람들은 주말에 등산을 정말 좋아해요.', 'Koreans really love hiking on weekends.',
      [{ korean: '북한산', english: 'Bukhan-san (Seoul)' }, { korean: '설악산', english: 'Seorak-san (Gangwon)' }, { korean: '한라산', english: 'Halla-san (Jeju)' }], [ACT.culture]),
    createContentItem('Seasonal outings', 'culture',
      '벚꽃놀이 (cherry-blossom outings, April) · 단풍놀이 (autumn-leaves outings, October) · 해수욕 (sea bathing, July-August). These are major social events for Korean families.',
      'sentence', '봄에는 벚꽃놀이, 가을에는 단풍놀이를 가요.', 'Spring: cherry blossoms. Autumn: leaves.',
      null, [ACT.culture]),

    createContentItem('과제: Tell me about your weekend', 'task',
      'Roleplay: A classmate asks 주말에 뭐 했어요? Cover at least 2 activities, one location, one companion, and link two actions with -고.',
      'conversation',
      'Classmate: 지난주말에 뭐 했어요?\nYou: [activity + with whom + where in past]\nClassmate: 와, 좋았어요?\nYou: [feeling + 2nd activity linked with -고]\nClassmate: 다음에 같이 가요!',
      'AI tutor will play the classmate.',
      [
        { korean: '~ 하고 ~에서 ~했어요', english: 'with X at Y did Z' },
        { korean: '~ 하고 ~ 했어요 (with -고)', english: 'did X and Y' },
        { korean: '정말 좋았어요', english: 'really good' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
