// Level 1 Unit 17 — Sending & post office
// Sources: Book 1B·13 + 1B·14 (소포를 보내고 싶어요)
// Functions: mailing packages, sending gifts, expressing want with -고 싶다.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u17-orientation',
  pronunciation: 'l1u17-pronunciation',
  vocabularyPost: 'l1u17-vocab-post',
  vocabularyShipping: 'l1u17-vocab-ship',
  grammarWant: 'l1u17-grammar-want',
  grammarTry: 'l1u17-grammar-try',
  grammarFor: 'l1u17-grammar-for',
  reading: 'l1u17-reading',
  listening: 'l1u17-listening',
  writing: 'l1u17-writing',
  culture: 'l1u17-culture',
  task: 'l1u17-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Express wants with V-고 싶다.', 'Send a package, letter, or gift from a Korean post office.', 'Choose between 항공/일반/등기.'],
    task: 'Imagine sending a Chuseok gift back home from the Korean post office.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Post-office phrases',
    goals: ['Apply 비음화: 보내고 싶어요 → [보내고 시퍼요].', 'Apply 연음 in 우체국 → [우체국].'],
    task: 'Read each phrase aloud.' },
  { id: ACT.vocabularyPost, section: 'Vocabulary I', title: 'Post-office items',
    goals: ['Use 우체국·소포·편지·우표·봉투·주소·무게.'],
    task: 'List three post-office words you use.' },
  { id: ACT.vocabularyShipping, section: 'Vocabulary II', title: 'Shipping methods + verbs',
    goals: ['Use 항공·일반·등기·국제·국내·보내다·받다·재다·도착하다.'],
    task: 'Pair a method with a destination.' },
  { id: ACT.grammarWant, section: 'Grammar I', title: 'V-고 싶다 — want to V',
    goals: ['Attach -고 싶다 to verb stem.', 'Use 싶어요 (polite) / 싶습니다 (formal).', 'For 3rd person, use V-고 싶어 하다.'],
    task: 'Make three "want to V" sentences.' },
  { id: ACT.grammarTry, section: 'Grammar II', title: 'V-아/어 보다 — try doing',
    goals: ['Attach -아 보다 (ㅏ/ㅗ) or -어 보다 (others) to a verb stem.', 'Use to suggest trying something.'],
    task: 'Suggest trying three new things.' },
  { id: ACT.grammarFor, section: 'Grammar III', title: 'N에게/한테 + 보내다/주다 — for someone',
    goals: ['Use 에게/한테/께 for the recipient.'],
    task: 'Send 3 things to 3 different recipients.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A package label',
    goals: ['Read a package label.'],
    task: 'Identify sender, recipient, shipping method.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Sending to the Philippines',
    goals: ['Follow a post-office transaction.'],
    task: 'Reproduce with your own country.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Write a postcard',
    goals: ['Write a short 3-4 line postcard to a family member.'],
    task: 'Write your own postcard.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Chuseok gifts and Korean post culture',
    goals: ['Know that 추석/설날 gifts are commonly mailed.', 'Know 한진택배 / 우체국 택배 (couriers).'],
    task: 'Pick one Chuseok gift you would mail.' },
  { id: ACT.task, section: 'Task', title: '과제 — Send a Chuseok gift',
    goals: ['Combine want, shipping method, recipient, and try-form in one scene.'],
    task: 'Send a Chuseok gift package abroad.' },
];

const lesson = {
  title: '레벨 1 · 17과: 소포를 보내고 싶어요 (Sending and Post Office)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'expressing-want', label: 'Expressing what you want to do', goal: 'Use V-고 싶다 to say what you want.' },
    { id: 'asking-shipping-method', label: 'Asking shipping methods', goal: 'Ask 어떻게 보내요? and pick 항공/등기/일반.' },
    { id: 'sending-gift', label: 'Sending a gift', goal: 'Use 에게/한테 + 보내다 for a recipient.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: send package, pick method, address it correctly, say what you want.', 'word', 'Functions: want · ship · receive · try', 'Four post-office micro-skills.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'It is mid-September — 추석 (mid-autumn festival). You want to mail Korean snacks to your family back home.', 'word', 'Clerk: 안에 뭐가 있어요? — You: 한국 과자예요. 가족 선물이에요.', 'Clerk: What\'s inside? — You: Korean snacks. A gift for my family.', null, [ACT.orientation]),

    createContentItem('보내고 → [보내고]', 'bonaego', 'No major change. Smooth flow.', 'word', '소포를 보내고 싶어요.', 'I want to send a package.', null, [ACT.pronunciation]),
    createContentItem('싶어요 → [시퍼요]', 'sipeoyo', '연음: ㅂ받침 of 싶 jumps to 어요.', 'word', '보내고 싶어요. → [보내고 시퍼요]', 'I want to send.', null, [ACT.pronunciation]),
    createContentItem('등기로 → [등기로]', 'deunggi-ro', 'Smooth, no change.', 'word', '등기로 보내 주세요.', 'Send by registered mail.', null, [ACT.pronunciation]),
    createContentItem('우표 → [우표]', 'upyo', 'No change. Practice the ㅠ vowel.', 'word', '우표 하나 주세요.', 'One stamp please.', null, [ACT.pronunciation]),

    createContentItem('우체국', 'ucheguk', 'post office', 'word', '우체국에 가요.', 'I am going to the post office.', null, [ACT.vocabularyPost]),
    createContentItem('소포', 'sopo', 'package', 'word', '소포를 보내고 싶어요.', 'I want to send a package.', null, [ACT.vocabularyPost]),
    createContentItem('편지', 'pyeonji', 'letter', 'word', '편지를 썼어요.', 'I wrote a letter.', null, [ACT.vocabularyPost]),
    createContentItem('엽서', 'yeopseo', 'postcard', 'word', '엽서를 보낼게요.', 'I will send a postcard.', null, [ACT.vocabularyPost]),
    createContentItem('우표', 'upyo', 'stamp', 'word', '우표 하나 주세요.', 'One stamp please.', null, [ACT.vocabularyPost]),
    createContentItem('봉투', 'bongtu', 'envelope', 'word', '봉투에 주소를 써요.', 'I write the address on the envelope.', null, [ACT.vocabularyPost]),
    createContentItem('주소', 'juso', 'address', 'word', '주소가 어떻게 되세요?', 'May I have your address?', null, [ACT.vocabularyPost]),
    createContentItem('무게', 'muge', 'weight', 'word', '무게를 재 주세요.', 'Please weigh it.', null, [ACT.vocabularyPost]),
    createContentItem('우편번호', 'upyeon beonho', 'postal code', 'word', '우편번호가 뭐예요?', 'What is the postal code?', null, [ACT.vocabularyPost]),
    createContentItem('선물', 'seonmul', 'gift / present', 'word', '가족에게 선물을 보내요.', 'I send a gift to my family.', null, [ACT.vocabularyPost]),

    createContentItem('보내다', 'bonaeda', 'to send', 'word', '필리핀에 보내요.', 'I am sending to the Philippines.', null, [ACT.vocabularyShipping]),
    createContentItem('받다', 'batda', 'to receive', 'word', '소포를 받았어요.', 'I received a package.', null, [ACT.vocabularyShipping]),
    createContentItem('항공', 'hanggong', 'airmail', 'word', '항공으로 보내 주세요.', 'Please send by airmail.', null, [ACT.vocabularyShipping]),
    createContentItem('일반', 'ilban', 'regular (mail)', 'word', '일반으로 보내요.', 'Send regular.', null, [ACT.vocabularyShipping]),
    createContentItem('등기', 'deunggi', 'registered mail', 'word', '등기로 보낼게요.', 'I will send registered.', null, [ACT.vocabularyShipping]),
    createContentItem('국제', 'gukje', 'international', 'word', '국제 우편이에요.', 'It is international mail.', null, [ACT.vocabularyShipping]),
    createContentItem('국내', 'gungnae', 'domestic', 'word', '국내 배송이에요.', 'It is domestic delivery.', null, [ACT.vocabularyShipping]),
    createContentItem('재다', 'jaeda', 'to measure / weigh', 'word', '무게를 재 주세요.', 'Please weigh it.', null, [ACT.vocabularyShipping]),
    createContentItem('도착하다', 'dochakhada', 'to arrive', 'word', '소포가 도착했어요.', 'The package arrived.', null, [ACT.vocabularyShipping]),
    createContentItem('가족', 'gajok', 'family', 'word', '가족이 보고 싶어요.', 'I miss my family.', null, [ACT.vocabularyShipping]),

    createContentItem('V-고 싶다 — want to V', '-go sipda', 'Attach -고 싶다 to a verb stem. Use 싶어요 (polite) or 싶습니다 (formal).', 'sentence', '가족에게 선물을 보내고 싶어요.', 'I want to send a gift to my family.',
      [
        { korean: '보내 + 고 싶다 → 보내고 싶다', english: 'want to send' },
        { korean: '먹 + 고 싶다 → 먹고 싶다', english: 'want to eat' },
        { korean: '가 + 고 싶다 → 가고 싶다', english: 'want to go' },
      ],
      [ACT.grammarWant]),
    createContentItem('3rd person — V-고 싶어 하다', 'others want', 'For someone else\'s wants, use V-고 싶어 하다.', 'sentence', '동생은 한국에 오고 싶어 해요.', 'My sibling wants to come to Korea.',
      null, [ACT.grammarWant]),
    createContentItem('Past — wanted', 'V-고 싶었어요', 'Past form: -고 싶었어요.', 'sentence', '어제 영화를 보고 싶었어요. 그런데 못 봤어요.', 'I wanted to see a movie yesterday. But I could not.',
      null, [ACT.grammarWant]),

    createContentItem('V-아/어 보다 — try doing', 'try', 'Attach -아 보다 (after ㅏ/ㅗ) or -어 보다 (others). Suggests trying.', 'sentence', '등기로 보내 보세요.', 'Try sending it by registered mail.',
      [
        { korean: '보내 + 어 보다 → 보내 보다', english: 'try sending' },
        { korean: '먹 + 어 보다 → 먹어 보다', english: 'try eating' },
        { korean: '가 + 아 보다 → 가 보다', english: 'try going' },
      ],
      [ACT.grammarTry]),
    createContentItem('Past — have you tried', 'V-아/어 봤어요?', 'Past form asks "have you tried ~?"', 'sentence', '김치 먹어 봤어요?', 'Have you tried kimchi?',
      null, [ACT.grammarTry]),

    createContentItem('N에게 / 한테 + 보내다 — send to', 'to whom', 'Recipient particle + verb of transfer (review from Unit 15).', 'sentence', '가족에게 선물을 보내요.', 'I send a gift to my family.',
      [{ korean: '가족에게', english: 'to family (formal)' }, { korean: '친구한테', english: 'to friend (casual)' }, { korean: '교수님께', english: 'to professor (honorific)' }], [ACT.grammarFor]),

    createContentItem('A package label', 'reading',
      'Read the package label aloud.',
      'sentence',
      '받는 사람: Sarah Garcia / 주소: 1234 Mabini St, Manila, Philippines / 보내는 사람: 김민수 / 주소: 경상북도 구미시 대학로 61 / 내용물: 한국 과자, 옷 / 무게: 2kg / 방법: 항공 / 가격: 25,000원',
      'Recipient: Sarah Garcia / Address: 1234 Mabini St, Manila, Philippines / Sender: Kim Minsu / Address: Daehak-ro 61, Gumi, Gyeongbuk / Contents: Korean snacks, clothes / Weight: 2kg / Method: Airmail / Price: 25,000 KRW',
      [
        { korean: '받는 사람', english: 'recipient' },
        { korean: '보내는 사람', english: 'sender' },
        { korean: '내용물', english: 'contents' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Read the label.', 'sentence',
      'Q1: 누가 보내요? · Q2: 어느 나라에 가요? · Q3: 무게는 얼마예요?',
      'Q1: Who sends? Q2: Which country? Q3: Weight?',
      [
        { korean: 'A1: 김민수가 보내요.', english: 'Kim Minsu sends.' },
        { korean: 'A2: 필리핀에 가요.', english: 'To the Philippines.' },
        { korean: 'A3: 2킬로예요.', english: '2 kg.' },
      ],
      [ACT.reading]),

    createContentItem('Sending abroad', 'listening',
      'At the post office sending abroad.',
      'conversation',
      'A (손님): 안녕하세요. 이 소포를 필리핀에 보내고 싶어요.\nB (직원): 안에 뭐가 있어요?\nA: 옷하고 한국 과자예요. 가족 선물이에요.\nB: 무게가 2킬로네요. 항공으로요, 일반으로요?\nA: 항공으로요. 얼마나 걸려요?\nB: 약 5일 걸려요. 25,000원이에요.\nA: 등기로 보내 주세요.\nB: 네, 등기는 추가로 5,000원이에요. 모두 30,000원입니다.',
      'A: Hello. Send this package to Philippines. B: What\'s inside? A: Clothes + Korean snacks. Family gift. B: 2 kg. Air or regular? A: Air. How long? B: 5 days, 25,000 won. A: Register it please. B: Registered +5,000. Total 30,000.',
      [
        { korean: '안에 뭐가 있어요?', english: 'what\'s inside?' },
        { korean: '항공으로요, 일반으로요?', english: 'air or regular?' },
        { korean: '추가로', english: 'in addition' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'postcard template',
      'Use this for a postcard.',
      'sentence',
      '사랑하는 [수신자]에게, 잘 지내요? 한국 생활은 [형용사]+아/어요. 여기 [장소]에서 엽서 보내요. 이번 추석에 선물도 보낼 거예요. 받으면 답장해 줘요. — [발신자]',
      '[recipient] · [greeting] · [Korean life] · [place] · [gift plan] · [sign-off]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write a 3-4 sentence postcard to a family member. Use V-고 싶다 and 보내다.',
      'sentence', 'Example: 사랑하는 엄마, 잘 지내요? 한국에서 잘 있어요. 추석에 한국 과자를 보내고 싶어요. 곧 도착할 거예요. — 사라',
      'Example: Dear Mom, well? I am OK in Korea. I want to send Korean snacks for Chuseok. They will arrive soon. — Sarah',
      null, [ACT.writing]),

    createContentItem('Chuseok gifts', 'culture',
      'Mid-September Chuseok (추석) is gift-giving season in Korea. Common items: 한과 (traditional snacks), 송편 (rice cakes), Korean cosmetics. Office workers also exchange 명절 선물 sets.',
      'sentence', '추석에는 가족과 친척에게 선물을 보내요.',
      'On Chuseok, people send gifts to family and relatives.',
      [{ korean: '추석', english: 'Chuseok (mid-autumn festival)' }, { korean: '명절 선물', english: 'holiday gift' }, { korean: '한과', english: 'traditional snacks' }], [ACT.culture]),
    createContentItem('Korean couriers', 'culture',
      'For domestic shipping, 우체국 택배 is cheap and reliable. Private couriers like 한진택배 and CJ대한통운 deliver next-day. For international, 우체국 EMS is the standard.',
      'sentence', '국내 배송은 우체국 택배가 싸요. 국제는 EMS를 써요.',
      'Domestic shipping is cheap with the post office. For international, use EMS.',
      null, [ACT.culture]),

    createContentItem('과제: Send a Chuseok gift', 'task',
      'Roleplay: Send Korean snacks to your family abroad. Use 보내고 싶어요, 등기/항공, 가족에게.',
      'conversation',
      'Clerk: 어떻게 도와드릴까요?\nYou: [say what you want to send + 고 싶어요]\nClerk: 안에 뭐가 있어요?\nYou: [contents]\nClerk: 항공/일반/등기 중에 뭐요?\nYou: [pick]\nClerk: [price + time]\nYou: 그럼 ~로 부탁드려요.',
      'AI tutor will play the clerk.',
      [
        { korean: '~ 보내고 싶어요', english: 'I want to send ~' },
        { korean: '가족에게 ~ 보내요', english: 'send ~ to family' },
        { korean: '항공으로/등기로 부탁해요', english: 'by air / registered please' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
