// Level 1 Unit 11 — Scheduling & invitations
// Source: Book 1A·11 (토요일에 같이 공부할 수 있어?)
// Functions: telling time, suggesting plans, accepting/declining invitations.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u11-orientation',
  pronunciation: 'l1u11-pronunciation',
  vocabularyTime: 'l1u11-vocab-time',
  vocabularyMeet: 'l1u11-vocab-meet',
  grammarAbility: 'l1u11-grammar-ability',
  grammarSuggest: 'l1u11-grammar-suggest',
  grammarDecline: 'l1u11-grammar-decline',
  reading: 'l1u11-reading',
  listening: 'l1u11-listening',
  writing: 'l1u11-writing',
  culture: 'l1u11-culture',
  task: 'l1u11-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Tell time using Native (hours) + Sino (minutes).', 'Invite + ask availability with V-(으)ㄹ 수 있어요? and V-(으)ㄹ까요?.', 'Accept or politely decline with a reason.'],
    task: 'Imagine inviting a Korean classmate to study together at the library.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Time and modal endings',
    goals: ['Apply 경음화: 공부할 수 → [공부할쑤].', 'Apply 연음 + tensification in 6시 → [여섯시].'],
    task: 'Read each time aloud.' },
  { id: ACT.vocabularyTime, section: 'Vocabulary I', title: 'Telling time',
    goals: ['Use 시 (Native) + 분 (Sino) format.', 'Use 오전·오후·반·정각·쯤.'],
    task: 'Say five different times correctly.' },
  { id: ACT.vocabularyMeet, section: 'Vocabulary II', title: 'Meeting & invitation words',
    goals: ['Use 약속·시간·같이·만나다·시간이 있다/없다·바쁘다.'],
    task: 'Use each word once in a self-made sentence.' },
  { id: ACT.grammarAbility, section: 'Grammar I', title: 'V-(으)ㄹ 수 있다/없다 — can / cannot',
    goals: ['Attach -ㄹ 수 있다 (vowel) or -을 수 있다 (consonant) to express ability/possibility.', 'Negate with 없다.'],
    task: 'Make three "can / cannot" sentences.' },
  { id: ACT.grammarSuggest, section: 'Grammar II', title: 'V-(으)ㄹ까요? + 같이',
    goals: ['Make polite suggestions with V-(으)ㄹ까요?.', 'Add 같이 to mean "together".'],
    task: 'Invite the AI to three activities.' },
  { id: ACT.grammarDecline, section: 'Grammar III', title: 'Polite decline + counter-proposal',
    goals: ['Use 죄송한데 / 미안한데 + -아/어서 + 못 V or 약속이 있어요.', 'Offer an alternative with 대신에 or 그럼 ~ 어때요?.'],
    task: 'Decline one invitation and propose a different time.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A messaging exchange',
    goals: ['Read a short text-message exchange between two friends.'],
    task: 'Identify when, where, what they will do.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Two invitations',
    goals: ['Follow an acceptance dialogue and a decline-with-counter-proposal dialogue.'],
    task: 'Reproduce either with your own schedule.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Inviting a friend',
    goals: ['Write a 3-4 sentence invitation including day, time, place, and what to do.'],
    task: 'Write your own invitation message.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — KakaoTalk, 칼퇴, and 약속 culture',
    goals: ['Know that Koreans plan via KakaoTalk (카톡).', 'Understand 칼퇴 (leaving work on time) and why post-work plans must be flexible.'],
    task: 'Decide an appropriate way to invite a Korean classmate via 카톡.' },
  { id: ACT.task, section: 'Task', title: '과제 — Set up a study meeting',
    goals: ['Combine ability, suggestion, time, place, and confirmation in one scene.'],
    task: 'Roleplay setting up a Saturday study meeting at the library.' },
];

const lesson = {
  title: '레벨 1 · 11과: 토요일에 같이 공부할 수 있어요? (Scheduling and Invitations)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'making-invitation', label: 'Making an invitation', goal: 'Use V-(으)ㄹ까요? + 같이 to suggest doing something together.' },
    { id: 'asking-availability', label: 'Asking availability', goal: 'Use 시간 있어요? / V-(으)ㄹ 수 있어요? to check if someone is free.' },
    { id: 'accepting-declining', label: 'Accepting or declining politely', goal: 'Respond yes/no with a brief reason if declining.' },
    { id: 'proposing-alternative', label: 'Proposing an alternative', goal: 'After declining, offer a different day/time.' },
  ],
  relatedPools: ['topic-school', 'topic-people'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: tell time, invite, ask availability, accept, decline, and propose alternatives.', 'word', 'Functions: time · invite · ask · accept/decline · propose', 'Full scheduling toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'A classmate sends you a 카톡 message: "토요일에 같이 공부할 수 있어요?" — you need to read, reply, and propose a time/place.', 'word', 'Friend: 토요일에 같이 공부할 수 있어요? — You: 좋아요. 2시 어때요?', 'Friend: Can we study Saturday? — You: Sure. How about 2?', null, [ACT.orientation]),

    createContentItem('공부할 수 → [공부할쑤]', 'gongbuhal ssu', '경음화: ㄹ받침 + ㅅ → ㄹ + ㅆ.', 'word', '같이 공부할 수 있어요? → [공부할쑤 이써요]', 'Can we study together?', null, [ACT.pronunciation]),
    createContentItem('여섯 시 → [여섣씨]', 'yeoseot ssi', '경음화: ㅅ받침 + ㅅ → tensification.', 'word', '여섯 시에 만나요. → [여섣씨에]', 'Let us meet at 6.', null, [ACT.pronunciation]),
    createContentItem('약속이 → [약쏘기]', 'yaksogi', '경음화 + 연음: ㄱ받침 of 약 tensifies the ㅅ; the second ㄱ받침 jumps to 이.', 'word', '약속이 있어요. → [약쏘기 이써요]', 'I have plans.', null, [ACT.pronunciation]),
    createContentItem('만날까요 → [만날까요]', 'mannalkkayo', '경음화: ㄹ받침 + ㄲ stays tense.', 'word', '몇 시에 만날까요?', 'What time shall we meet?', null, [ACT.pronunciation]),

    createContentItem('시', 'si', 'o\'clock — Native number + 시', 'word', '한 시 (1시) · 두 시 (2시) · 세 시 (3시) · 네 시 (4시) · 다섯 시 (5시)', 'Hours always use Native numbers.',
      [
        { korean: '1시', english: '한 시 (hana → 한)' },
        { korean: '2시', english: '두 시 (dul → 두)' },
        { korean: '12시', english: '열두 시' },
      ],
      [ACT.vocabularyTime]),
    createContentItem('분', 'bun', 'minute — Sino number + 분', 'word', '5분 (오분) · 30분 (삼십분) · 45분 (사십오분)', 'Minutes always use Sino-Korean numbers.',
      [{ korean: '15분', english: '십오분' }, { korean: '30분', english: '삼십분' }, { korean: '45분', english: '사십오분' }], [ACT.vocabularyTime]),
    createContentItem('Full time format', 'Native + Sino', 'Hour (Native) + 시 + Minute (Sino) + 분.', 'sentence', '오후 2시 30분 = 오후 두 시 삼십 분', '2:30 PM.',
      null, [ACT.vocabularyTime]),
    createContentItem('반 — half past', 'ban', 'After the hour, you can say 반 (half) instead of 30분.', 'sentence', '3시 반 = 세 시 반 = 3:30', 'Half past three.',
      null, [ACT.vocabularyTime]),
    createContentItem('정각 / 쯤', 'sharp / around', '정각 = "on the dot". 쯤 = "around / about".', 'sentence', '3시 정각 (3 sharp) · 3시쯤 (around 3)', 'Two precision modifiers.',
      null, [ACT.vocabularyTime]),
    createContentItem('오전 / 오후', 'AM / PM', 'Korean often uses 오전 (AM) and 오후 (PM) BEFORE the time, unlike English.', 'sentence', '오전 10시 = 10 AM · 오후 7시 = 7 PM', 'Order: 오전/오후 then time.',
      null, [ACT.vocabularyTime]),

    createContentItem('시간', 'sigan', 'time', 'word', '시간이 있어요?', 'Do you have time?', null, [ACT.vocabularyMeet]),
    createContentItem('약속', 'yaksok', 'appointment / plan', 'word', '오늘 저녁에 약속이 있어요.', 'I have plans tonight.', null, [ACT.vocabularyMeet]),
    createContentItem('같이', 'gachi', 'together', 'word', '같이 점심 먹을까요?', 'Shall we have lunch together?', null, [ACT.vocabularyMeet]),
    createContentItem('만나다', 'mannada', 'to meet', 'word', '몇 시에 만날까요?', 'What time shall we meet?', null, [ACT.vocabularyMeet]),
    createContentItem('약속하다', 'yaksokhada', 'to make a plan/promise', 'word', '내일 만나기로 약속했어요.', 'We promised to meet tomorrow.', null, [ACT.vocabularyMeet]),
    createContentItem('바쁘다', 'bappeuda', 'to be busy', 'word', '오늘 좀 바빠요.', 'I am a bit busy today.', null, [ACT.vocabularyMeet]),
    createContentItem('시간이 있다/없다', 'free / busy', 'Standard way to ask/say "I am free/busy".', 'word', '내일은 시간이 없어요.', 'I do not have time tomorrow.', null, [ACT.vocabularyMeet]),
    createContentItem('한가하다', 'hangahada', 'to be free / open', 'word', '주말에는 한가해요.', 'I am free on weekends.', null, [ACT.vocabularyMeet]),
    createContentItem('취소하다', 'chwisohada', 'to cancel', 'word', '약속을 취소해도 돼요?', 'May I cancel?', null, [ACT.vocabularyMeet]),
    createContentItem('변경하다', 'byeongyeonghada', 'to change / reschedule', 'word', '시간을 변경할까요?', 'Shall we change the time?', null, [ACT.vocabularyMeet]),
    createContentItem('주중', 'jujung', 'weekday', 'word', '주중에는 바빠요.', 'I am busy on weekdays.', null, [ACT.vocabularyMeet]),
    createContentItem('주말', 'jumal', 'weekend', 'word', '주말에 시간 있어요?', 'Are you free on the weekend?', null, [ACT.vocabularyMeet]),

    createContentItem('V-(으)ㄹ 수 있다 — can do', 'modal of ability', 'Attach -ㄹ 수 있다 (vowel) or -을 수 있다 (consonant). Express ability AND possibility.', 'sentence', '한국어를 할 수 있어요.', 'I can speak Korean.',
      [
        { korean: '하 + ㄹ 수 있다', english: '하 (vowel) → 할 수 있다' },
        { korean: '먹 + 을 수 있다', english: '먹 (consonant) → 먹을 수 있다' },
      ],
      [ACT.grammarAbility]),
    createContentItem('V-(으)ㄹ 수 없다 / 못 V', 'cannot', '없다 makes it "cannot". Alternatively, 못 + V is shorter and more common.', 'sentence', '못 가요. = 갈 수 없어요.', 'I cannot go. (both forms)',
      [{ korean: '못 가요', english: 'cannot go (short, common)' }, { korean: '갈 수 없어요', english: 'cannot go (long, emphatic)' }], [ACT.grammarAbility]),
    createContentItem('Polite question form', 'check availability', 'Use V-(으)ㄹ 수 있어요? to ask if someone is able.', 'sentence', '토요일에 같이 공부할 수 있어요?', 'Can you study Saturday?',
      null, [ACT.grammarAbility]),

    createContentItem('V-(으)ㄹ까요? — Shall we?', 'kkayo', 'Suggesting; review from Unit 9.', 'sentence', '몇 시에 만날까요?', 'What time shall we meet?',
      null, [ACT.grammarSuggest]),
    createContentItem('같이 — together', 'with you', 'Add 같이 for emphasis on togetherness. Common in invitations.', 'sentence', '같이 영화 볼까요?', 'Shall we watch a movie together?',
      null, [ACT.grammarSuggest]),
    createContentItem('Confirming a plan', 'pinning it down', 'After a yes, pin down time + place: 그럼 X시에 Y에서 봐요.', 'sentence', '그럼 토요일 2시에 도서관에서 봐요.', 'Then see you Saturday 2 at the library.',
      null, [ACT.grammarSuggest]),

    createContentItem('Polite decline with reason', '미안한데/죄송한데', 'Soft opener + reason + apology.', 'sentence', '미안한데, 그날은 약속이 있어요.', 'Sorry, I have plans that day.',
      [
        { korean: '미안한데', english: 'I am sorry but ~ (casual)' },
        { korean: '죄송한데', english: 'I am sorry but ~ (formal)' },
        { korean: '~ 약속이 있어서요', english: 'because I have plans' },
      ],
      [ACT.grammarDecline]),
    createContentItem('Counter-proposal', '그럼 ~ 어때요?', 'Always offer an alternative when declining.', 'sentence', '그럼 다음 주는 어때요?', 'Then how about next week?',
      [{ korean: '그럼', english: 'then' }, { korean: '~ 어때요?', english: 'how about ~?' }, { korean: '대신에', english: 'instead' }], [ACT.grammarDecline]),

    createContentItem('A KakaoTalk exchange', 'reading',
      'Read this message exchange aloud, then answer the questions.',
      'sentence',
      '민수: 사라 씨, 토요일에 시간 있어요? 같이 공부할까요?\n사라: 토요일이요? 잠깐만요... 토요일 오후는 한가해요.\n민수: 그럼 오후 2시에 도서관에서 만날까요?\n사라: 좋아요. 1층 입구에서 봐요.\n민수: 네! 카페에서 커피도 마실까요?\n사라: 좋아요. 그럼 1시 30분에 카페에서 만나요. 그 다음에 도서관 가요.\n민수: 완벽해요. 토요일에 봐요.',
      'Minsu: Sarah, are you free Saturday? Shall we study together?\nSarah: Saturday? Hold on... Saturday afternoon is open.\nMinsu: Then shall we meet at the library at 2 PM?\nSarah: Sounds good. See you at the 1st-floor entrance.\nMinsu: OK! Shall we get coffee at the cafe too?\nSarah: Yes. Then let us meet at 1:30 at the cafe. Then go to the library.\nMinsu: Perfect. See you Saturday.',
      [
        { korean: '시간 있어요?', english: 'are you free?' },
        { korean: '잠깐만요', english: 'one moment' },
        { korean: '한가하다', english: 'be free' },
        { korean: '완벽해요', english: 'perfect' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A',
      'Answer based on the messages.',
      'sentence',
      'Q1: 몇 시에 만나요? · Q2: 어디에서 만나요? · Q3: 뭐 할 거예요?',
      'Q1: What time? Q2: Where? Q3: What will they do?',
      [
        { korean: 'A1: 1시 30분에 만나요.', english: 'At 1:30.' },
        { korean: 'A2: 카페에서 만나요.', english: 'At the cafe.' },
        { korean: 'A3: 커피 마시고 공부할 거예요.', english: 'Drink coffee and study.' },
      ],
      [ACT.reading]),

    createContentItem('Accepting an invitation', 'listening',
      'Standard "yes" dialogue.',
      'conversation',
      'A: 사라 씨, 토요일에 같이 공부할 수 있어요?\nB: 토요일이요? 토요일은 시간 있어요. 몇 시에요?\nA: 오후 2시 어때요? 도서관에서요.\nB: 좋아요. 도서관 입구에서 만나요.\nA: 네, 그럼 토요일 2시에 봐요.\nB: 네, 그럼 그때 봐요.',
      'A: Sarah, study together Saturday? B: Saturday? I am free. What time? A: 2 PM at the library? B: Sure, meet at the entrance. A: OK, see you Saturday 2. B: Yes, see you then.',
      [
        { korean: '몇 시에요?', english: 'what time?' },
        { korean: '입구에서 만나요', english: 'meet at the entrance' },
      ],
      [ACT.listening]),
    createContentItem('Declining with counter-proposal', 'listening',
      'Polite "no, but..." dialogue.',
      'conversation',
      'A: 오늘 저녁에 영화 보러 갈래요?\nB: 미안해요, 오늘은 약속이 있어요.\nA: 아, 알겠어요. 그럼 내일은 어때요?\nB: 내일은 괜찮아요. 몇 시예요?\nA: 7시요.\nB: 좋아요. 그럼 내일 7시에 봐요. 영화관에서요?\nA: 네, 영화관 앞에서요.',
      'A: Want to see a movie tonight? B: Sorry, I have plans. A: Oh, OK. Tomorrow? B: Tomorrow is fine. What time? A: 7 PM. B: OK, 7 tomorrow. At the theater? A: Yes, in front.',
      [
        { korean: '~ 갈래요?', english: 'want to go ~?' },
        { korean: '괜찮아요', english: 'is okay' },
        { korean: '~ 앞에서', english: 'in front of ~' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'invitation template',
      'Use this to write your own KakaoTalk invitation.',
      'sentence',
      '[이름] 씨, [요일]에 시간 있어요? 같이 [활동]할까요? [장소]에서 [시간]에 만나요. 시간 괜찮으면 답장해 주세요.',
      '[name] · [day] · [activity] · [place] · [time]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write a 3-4 sentence invitation message. Include day, time, place, activity, and ask for confirmation.',
      'sentence', 'Example: 민수 씨, 토요일에 시간 있어요? 같이 한국어 공부할까요? 도서관에서 오후 2시에 만나요. 답장 기다릴게요.',
      'Example: Minsu, free Saturday? Let us study Korean. Meet at the library 2 PM. Waiting for your reply.',
      null, [ACT.writing]),

    createContentItem('KakaoTalk culture', 'culture',
      'Korean planning happens almost entirely on 카카오톡 (Kakao Talk = 카톡). Use 약속 잡다 ("set a plan") and stickers (이모티콘). Calling is reserved for urgency.',
      'sentence', '한국에서는 약속을 카톡으로 잡아요. 전화는 급한 일에만 써요.',
      'Koreans set plans via KakaoTalk. Phone calls are for urgent matters.',
      [{ korean: '카톡', english: 'KakaoTalk' }, { korean: '약속 잡다', english: 'make a plan' }, { korean: '이모티콘', english: 'sticker' }], [ACT.culture]),
    createContentItem('칼퇴 and after-work', 'culture',
      '칼퇴 = "knife-sharp leaving" = clocking out exactly on time. Many Koreans cannot guarantee evening plans because of unpredictable overtime. Saturday and Sunday plans are more reliable.',
      'sentence', '평일 저녁은 야근 때문에 약속을 잡기 어려워요.', 'Weekday evenings are hard to plan because of overtime.',
      null, [ACT.culture]),

    createContentItem('과제: Set up a study meeting', 'task',
      'Roleplay: Invite a classmate to study Saturday. Use V-(으)ㄹ 수 있어요?, V-(으)ㄹ까요?, and confirm time + place.',
      'conversation',
      'You: [invite + day + activity]\nClassmate: 토요일은 시간 있어요. 몇 시요?\nYou: [propose time + place]\nClassmate: [accept OR decline + counter-propose]\nYou: [confirm OR re-propose]\nClassmate: 좋아요. 그럼 그때 봐요.',
      'AI tutor will play the classmate.',
      [
        { korean: '~ 할 수 있어요?', english: 'can you do ~?' },
        { korean: '몇 시에 만날까요?', english: 'what time shall we meet?' },
        { korean: '그럼 ~에 봐요', english: 'then see you at ~' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
