// Level 1 Unit 20 — Suggestions & plans
// Source: Book 1B·16 (같이 영화 보러 갈까요?)
// Functions: making suggestions, agreeing, planning a movie/cafe outing.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u20-orientation',
  pronunciation: 'l1u20-pronunciation',
  vocabularyMovie: 'l1u20-vocab-movie',
  vocabularyOutings: 'l1u20-vocab-outings',
  grammarSuggest: 'l1u20-grammar-suggest',
  grammarCasual: 'l1u20-grammar-casual',
  grammarAgreeing: 'l1u20-grammar-agree',
  reading: 'l1u20-reading',
  listening: 'l1u20-listening',
  writing: 'l1u20-writing',
  culture: 'l1u20-culture',
  task: 'l1u20-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Make polite suggestions with V-(으)ㄹ까요? and casual ones with V-(으)ㄹ래요?.', 'Agree or counter-propose politely.', 'Plan time + place for a meet-up.'],
    task: 'Imagine inviting a Korean classmate to see a movie on Friday.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Suggestion endings',
    goals: ['Apply 경음화: 갈까요 → [갈까요].', 'Pronounce -ㄹ래요 with smooth ㄹ.'],
    task: 'Read each suggestion form aloud.' },
  { id: ACT.vocabularyMovie, section: 'Vocabulary I', title: 'Movie & entertainment',
    goals: ['Use 영화·영화관·표·매표소·상영 시간·예매·관람·자막.'],
    task: 'Suggest one movie outing.' },
  { id: ACT.vocabularyOutings, section: 'Vocabulary II', title: 'Outing places + activities',
    goals: ['Use 카페·노래방·PC방·공원·박물관 + 보다·먹다·놀다.'],
    task: 'Pair places with activities.' },
  { id: ACT.grammarSuggest, section: 'Grammar I', title: 'V-(으)ㄹ까요? — polite "shall we?"',
    goals: ['Polite/neutral suggestion form (review from Unit 9).', 'Tag wh-words: 어디·뭐·언제 갈까요?'],
    task: 'Make three V-(으)ㄹ까요? questions.' },
  { id: ACT.grammarCasual, section: 'Grammar II', title: 'V-(으)ㄹ래요? — casual "wanna?"',
    goals: ['Casual suggestion/invitation form among peers/close friends.', 'Reply 네, 그럴래요 / 아니요, 그러지 마요.'],
    task: 'Make three casual invitations.' },
  { id: ACT.grammarAgreeing, section: 'Grammar III', title: 'Agreeing + counter-proposing',
    goals: ['Quickly accept: 좋아요 / 그래요.', 'Counter-propose: ~ 어때요? / ~ 대신 ~ 할까요?'],
    task: 'Accept + counter in 3 exchanges.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A movie listing',
    goals: ['Read a cinema schedule and pick a showtime.'],
    task: 'Identify movie, times, prices.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Movie plan',
    goals: ['Follow a 6-turn movie-plan dialogue.'],
    task: 'Reproduce with your own plan.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Kakao invite',
    goals: ['Write a 3-4 line KakaoTalk invite to a friend.'],
    task: 'Write your own invite.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — CGV, 메가박스, and Korean movie culture',
    goals: ['Know CGV·메가박스·롯데시네마 chains.', 'Understand 예매 (online booking) and 4DX/IMAX premium options.'],
    task: 'Pick which chain and option you would choose.' },
  { id: ACT.task, section: 'Task', title: '과제 — Plan a Friday movie',
    goals: ['Combine suggestion, agreement, time, place, ticket-booking.'],
    task: 'Plan a Friday movie with the AI tutor.' },
];

const lesson = {
  title: '레벨 1 · 20과: 같이 영화 보러 갈까요? (Suggestions and Plans)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'making-suggestion', label: 'Making a suggestion', goal: 'Use V-(으)ㄹ까요? to invite politely.' },
    { id: 'casual-suggestion', label: 'Casual suggestion', goal: 'Use V-(으)ㄹ래요? with friends.' },
    { id: 'agreeing-counter', label: 'Agreeing or counter-proposing', goal: 'Respond 좋아요 or counter with ~ 어때요?' },
  ],
  relatedPools: ['topic-people'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: invite politely + casually, agree, counter-propose, set time/place.', 'word', 'Functions: suggest · invite · accept/counter · plan', 'Suggestion toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'A new Korean film just released. You want to invite Sarah this Friday. Politely or casually?', 'word', 'You: 금요일에 같이 영화 보러 갈래요? — Sarah: 좋아요!', 'You: Wanna see a movie Friday? — Sarah: Sure!', null, [ACT.orientation]),

    createContentItem('갈까요 → [갈까요]', 'galkkayo', '경음화: ㄹ받침 + ㄲ stays tense.', 'word', '같이 갈까요? → [갈까요]', 'Shall we go?', null, [ACT.pronunciation]),
    createContentItem('갈래요 → [갈래요]', 'gallaeyo', 'No major change. ㄹ받침 + ㄹ becomes a long ㄹ.', 'word', '같이 갈래요?', 'Wanna go?', null, [ACT.pronunciation]),
    createContentItem('보러 → [보러]', 'boreo', 'No change. Smooth.', 'word', '영화 보러 가요.', 'Going to see a movie.', null, [ACT.pronunciation]),
    createContentItem('영화 → [영화]', 'yeonghwa', 'Clear ㅎ stays.', 'word', '한국 영화', 'Korean movie.', null, [ACT.pronunciation]),

    createContentItem('영화', 'yeonghwa', 'movie', 'word', '영화를 봐요.', 'I watch a movie.', null, [ACT.vocabularyMovie]),
    createContentItem('영화관', 'yeonghwagwan', 'movie theater', 'word', '영화관에 가요.', 'I go to the theater.', null, [ACT.vocabularyMovie]),
    createContentItem('표', 'pyo', 'ticket', 'word', '영화 표 두 장 주세요.', 'Two movie tickets please.', null, [ACT.vocabularyMovie]),
    createContentItem('매표소', 'maepyoso', 'ticket office', 'word', '매표소에서 표를 사요.', 'I buy tickets at the office.', null, [ACT.vocabularyMovie]),
    createContentItem('예매', 'yemae', 'reservation / advance booking', 'word', '온라인으로 예매했어요.', 'I booked online.', null, [ACT.vocabularyMovie]),
    createContentItem('상영 시간', 'sangyeong sigan', 'showtime', 'word', '상영 시간이 어떻게 돼요?', 'What is the showtime?', null, [ACT.vocabularyMovie]),
    createContentItem('자막', 'jamak', 'subtitles', 'word', '영어 자막 있어요?', 'Are there English subtitles?', null, [ACT.vocabularyMovie]),
    createContentItem('한국 영화', 'hanguk yeonghwa', 'Korean movie', 'word', '한국 영화 보러 갈까요?', 'Shall we see a Korean movie?', null, [ACT.vocabularyMovie]),
    createContentItem('액션', 'aeksyeon', 'action genre', 'word', '액션 영화를 좋아해요.', 'I like action movies.', null, [ACT.vocabularyMovie]),
    createContentItem('로맨스', 'romaenseu', 'romance', 'word', '로맨스 영화 어때요?', 'How about a romance?', null, [ACT.vocabularyMovie]),
    createContentItem('코미디', 'komidi', 'comedy', 'word', '코미디 영화가 재미있어요.', 'Comedies are fun.', null, [ACT.vocabularyMovie]),

    createContentItem('카페', 'kape', 'cafe', 'word', '카페에 갈까요?', 'Shall we go to a cafe?', null, [ACT.vocabularyOutings]),
    createContentItem('노래방', 'noraebang', 'karaoke (Korean style)', 'word', '노래방에 가요.', 'We go to a karaoke room.', null, [ACT.vocabularyOutings]),
    createContentItem('PC방', 'PC bang', 'PC bang (internet cafe)', 'word', '친구하고 PC방에 가요.', 'I go to a PC bang with friends.', null, [ACT.vocabularyOutings]),
    createContentItem('공원', 'gongwon', 'park', 'word', '주말에 공원에서 산책해요.', 'I walk in the park on weekends.', null, [ACT.vocabularyOutings]),
    createContentItem('박물관', 'bangmulgwan', 'museum', 'word', '박물관에 갈까요?', 'Shall we go to the museum?', null, [ACT.vocabularyOutings]),
    createContentItem('만나다', 'mannada', 'to meet', 'word', '6시에 만나요.', 'Let us meet at 6.', null, [ACT.vocabularyOutings]),
    createContentItem('기다리다', 'gidarida', 'to wait', 'word', '입구에서 기다릴게요.', 'I will wait at the entrance.', null, [ACT.vocabularyOutings]),
    createContentItem('미리', 'miri', 'in advance', 'word', '미리 예매할게요.', 'I will book in advance.', null, [ACT.vocabularyOutings]),
    createContentItem('약속', 'yaksok', 'appointment / plan', 'word', '약속을 정해요.', 'Let us set a plan.', null, [ACT.vocabularyOutings]),
    createContentItem('새로 나오다', 'saero naoda', 'to be newly released', 'word', '새로 나온 영화예요.', 'It is a newly released movie.', null, [ACT.vocabularyOutings]),

    createContentItem('V-(으)ㄹ까요? — polite "shall we?"', 'kkayo', 'Polite, neutral. Works for all peers and gentle suggestions.', 'sentence', '같이 영화 보러 갈까요?', 'Shall we go see a movie?',
      [{ korean: '가 + ㄹ까요', english: '가 → 갈까요' }, { korean: '먹 + 을까요', english: '먹 → 먹을까요' }, { korean: '하 + ㄹ까요', english: '하 → 할까요' }], [ACT.grammarSuggest]),
    createContentItem('With wh-words', 'open suggestion', 'Combine with 어디·뭐·언제 + 을까요? for open suggestions.', 'sentence', '어디에서 만날까요? — 영화관 입구에서요.', 'Where shall we meet? — At the theater entrance.',
      [{ korean: '어디에서 만날까요?', english: 'where shall we meet?' }, { korean: '뭐 먹을까요?', english: 'what shall we eat?' }, { korean: '몇 시에 만날까요?', english: 'what time?' }], [ACT.grammarSuggest]),

    createContentItem('V-(으)ㄹ래요? — casual "wanna?"', 'llaeyo', 'Casual invitation. Works friend-to-friend.', 'sentence', '같이 영화 보러 갈래요?', 'Wanna go see a movie?',
      [{ korean: '갈래요?', english: 'wanna go?' }, { korean: '먹을래요?', english: 'wanna eat?' }, { korean: '갈래요? vs 갈까요?', english: '갈래요 = more casual / personal' }], [ACT.grammarCasual]),
    createContentItem('Statement form: V-(으)ㄹ래요 — I will / I want to', 'self-statement', 'Same form without ? to declare your intention.', 'sentence', '저는 한국 영화 볼래요.', 'I will watch a Korean movie.',
      null, [ACT.grammarCasual]),
    createContentItem('Decline politely', '미안한데...', 'When declining, soften with 미안한데, 죄송한데, 약속이 있어서요.', 'sentence', '미안한데, 그날은 약속이 있어요.', 'Sorry, I have plans that day.',
      null, [ACT.grammarCasual]),

    createContentItem('Agree fast: 좋아요 / 그래요', 'simple yes', 'Most common quick agreements.', 'sentence', '좋아요. 몇 시에 만날까요?', 'Sure. What time?',
      null, [ACT.grammarAgreeing]),
    createContentItem('Counter-propose with ~ 대신', 'instead of', 'Use ~ 대신에 to suggest doing X instead of Y.', 'sentence', '영화 대신 카페에 갈까요?', 'Cafe instead of movie?',
      [{ korean: 'N 대신에', english: 'instead of N' }, { korean: '~ 어때요?', english: 'how about ~?' }], [ACT.grammarAgreeing]),
    createContentItem('Confirm details', 'time + place', 'Pin down with 그럼 X시에 Y에서 봐요.', 'sentence', '그럼 7시에 영화관 입구에서 봐요.', 'Then see you at 7 at the theater entrance.',
      null, [ACT.grammarAgreeing]),

    createContentItem('Movie listing', 'reading',
      'Read this cinema schedule.',
      'sentence',
      'CGV 구미점 / 영화: 한국 액션 영화 "마지막 임무" / 상영 시간: 14:00 · 17:30 · 20:45 / 가격: 13,000원 / 자막: 한국어 / 예매: cgv.co.kr',
      'CGV Gumi / Movie: Korean action "The Last Mission" / Showtimes: 2 PM, 5:30, 8:45 / Price: 13,000 KRW / Subtitles: Korean / Booking: cgv.co.kr',
      [
        { korean: '상영 시간', english: 'showtimes' },
        { korean: '예매', english: 'booking' },
        { korean: '자막', english: 'subtitles' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Use suggestion forms.', 'sentence',
      'Q1: 어떤 영화예요? · Q2: 표 한 장에 얼마예요? · Q3: 어떻게 예매해요?',
      'Q1: What movie? Q2: One ticket price? Q3: How to book?',
      [
        { korean: 'A1: 한국 액션 영화 "마지막 임무"예요.', english: 'Korean action movie "The Last Mission".' },
        { korean: 'A2: 13,000원이에요.', english: '13,000 won.' },
        { korean: 'A3: cgv.co.kr에서 예매해요.', english: 'On cgv.co.kr.' },
      ],
      [ACT.reading]),

    createContentItem('Movie plan', 'listening',
      'Setting up a Friday movie.',
      'conversation',
      'A: 사라 씨, 금요일 저녁에 시간 있어요?\nB: 네, 있어요. 왜요?\nA: 같이 영화 보러 갈까요? 새로 나온 한국 영화가 좋대요.\nB: 좋아요. 어떤 영화예요?\nA: 액션이에요. 7시 30분 표가 있어요.\nB: 7시 반이요? 좋아요. 영화관 입구에서 만날까요?\nA: 네. 7시 15분쯤에 봐요. 표는 미리 예매할게요.\nB: 고마워요. 그럼 그때 봐요!',
      'A: Sarah, free Friday? B: Yes, why? A: Wanna see a movie together? They say a new Korean film is good. B: Sure. What movie? A: Action. 7:30 tickets available. B: 7:30? Yes, meet at the entrance? A: Yes, around 7:15. I will book the tickets. B: Thanks. See you then!',
      [
        { korean: '~대요', english: 'they say (hearsay)' },
        { korean: '몇 시에 만날까요?', english: 'what time shall we meet?' },
        { korean: '미리 예매할게요', english: 'I will book in advance' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'KakaoTalk invite',
      'Use this for an invite.',
      'sentence',
      '[이름] 씨, [요일]에 시간 있어요? 같이 [활동]할까요? [시간]에 [장소]에서 만나요. 답장 기다릴게요!',
      '[name] · [day] · [activity] · [time + place] · [closing]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write a 3-4 sentence Kakao invite to a friend. Use V-(으)ㄹ까요? and one time + place.',
      'sentence', 'Example: 사라 씨, 토요일 저녁에 시간 있어요? 같이 영화 보러 갈까요? 7시에 CGV 입구에서 만나요. 답장 부탁해요!',
      'Example: Sarah, free Saturday evening? Want to see a movie? Meet 7 PM at CGV entrance. Reply please!',
      null, [ACT.writing]),

    createContentItem('Korean cinemas', 'culture',
      'Three main chains: CGV, 메가박스 (Megabox), 롯데시네마 (Lotte Cinema). Premium options: 4DX (motion seats), IMAX, Gold Class. Most foreigners book online via the chain\'s website or app.',
      'sentence', 'CGV, 메가박스, 롯데시네마가 한국의 큰 영화관이에요.',
      'CGV, Megabox, and Lotte Cinema are Korea\'s big chains.',
      [{ korean: 'CGV', english: 'most common chain' }, { korean: '4DX', english: 'motion seats' }, { korean: '예매', english: 'online booking' }], [ACT.culture]),

    createContentItem('과제: Plan a Friday movie', 'task',
      'Roleplay: Invite a classmate to a Friday movie. Use V-(으)ㄹ까요?, accept/decline, set time + place, mention booking.',
      'conversation',
      'You: [invite for Friday + 새로 나온 한국 영화]\nClassmate: 좋아요. 어떤 영화요?\nYou: [movie + genre]\nClassmate: 몇 시 표가 있어요?\nYou: [time + suggest meet place]\nClassmate: 좋아요. 그럼 표는?\nYou: [미리 예매할게요]\nClassmate: 그럼 그때 봐요!',
      'AI tutor will play the classmate.',
      [
        { korean: '같이 ~ 보러 갈까요?', english: 'shall we go see ~?' },
        { korean: '몇 시에 만날까요?', english: 'what time?' },
        { korean: '미리 예매할게요', english: 'I will book' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
