// Level 1 Unit 16 — Clubs & leisure
// Source: Book 1A·14 (재미있고 좋은 동아리가 많아)
// Functions: introducing a club, talking about hobbies, joining activities.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u16-orientation',
  pronunciation: 'l1u16-pronunciation',
  vocabularyClubs: 'l1u16-vocab-clubs',
  vocabularyActivities: 'l1u16-vocab-act',
  grammarConnector: 'l1u16-grammar-and',
  grammarContrast: 'l1u16-grammar-but',
  grammarModifier: 'l1u16-grammar-mod',
  reading: 'l1u16-reading',
  listening: 'l1u16-listening',
  writing: 'l1u16-writing',
  culture: 'l1u16-culture',
  task: 'l1u16-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Talk about clubs and hobbies.', 'Combine two descriptions with -고 (and).', 'Contrast with -지만 (but).', 'Describe nouns with descriptive forms.'],
    task: 'Imagine recommending a Kumoh club to a new student.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Connector sounds',
    goals: ['Apply 연음 in 재미있고 → [재미읻꼬].', 'Apply 비음화 in 좋은 → [조은].'],
    task: 'Read each connector aloud.' },
  { id: ACT.vocabularyClubs, section: 'Vocabulary I', title: 'Clubs & members',
    goals: ['Use 동아리·회원·모임·가입하다·활동·인기.'],
    task: 'Name three clubs you would join.' },
  { id: ACT.vocabularyActivities, section: 'Vocabulary II', title: 'Hobbies & sports',
    goals: ['Use 음악·춤·그림·운동·봉사·축구·농구·야구.'],
    task: 'Pair each activity with an opinion adjective.' },
  { id: ACT.grammarConnector, section: 'Grammar I', title: 'V/A-고 — and (parallel)',
    goals: ['Attach -고 to a verb/adjective stem to chain ideas.', 'Use for two same-tense descriptions of one subject.'],
    task: 'Make three -고 sentences.' },
  { id: ACT.grammarContrast, section: 'Grammar II', title: 'V/A-지만 — but (contrast)',
    goals: ['Attach -지만 to contrast two clauses.', 'Pair with negative forms (잘 못, 안 V).'],
    task: 'Make three -지만 sentences.' },
  { id: ACT.grammarModifier, section: 'Grammar III', title: 'A-(으)ㄴ N — descriptive form',
    goals: ['Convert an adjective into a noun-modifier: 좋은 음식 (good food).', 'For adjective ㅂ-irregulars: 어려운 책, 매운 음식.', 'For 있다/없다: 재미있는, 재미없는.'],
    task: 'Modify three nouns with descriptive adjectives.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A club bulletin',
    goals: ['Read a 4-5 sentence club announcement.'],
    task: 'Identify club name, activities, member count, meeting time.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Club recommendation chat',
    goals: ['Follow a 5-turn recommendation dialogue.'],
    task: 'Reproduce with a different club.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Describe your favorite club',
    goals: ['Write 4-5 sentences describing a club, using -고, -지만, A-(으)ㄴ N.'],
    task: 'Write your own club description.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean university 동아리 culture',
    goals: ['Know that 동아리 are central to Korean university social life.', 'Understand 신입생 (freshmen) being actively recruited.'],
    task: 'Pick one Korean campus club you would join.' },
  { id: ACT.task, section: 'Task', title: '과제 — Recommend a club',
    goals: ['Combine vocabulary, connector, contrast, and modifier in one continuous scene.'],
    task: 'Recommend a Kumoh club to a new exchange student.' },
];

const lesson = {
  title: '레벨 1 · 16과: 재미있고 좋은 동아리가 많아요 (Clubs and Leisure)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'introducing-club', label: 'Introducing a club', goal: 'Use V/A-고 to combine two positive descriptions.' },
    { id: 'sharing-hobby', label: 'Sharing a hobby', goal: 'State your hobby and one thing you do well or not well.' },
    { id: 'recommending-club', label: 'Recommending a club', goal: 'Use A-(으)ㄴ + N + 추천해요 to recommend.' },
  ],
  relatedPools: ['topic-school', 'topic-people'],
  content: [
    createContentItem('Lesson goal', 'clubs + leisure', 'By end: describe clubs with -고/-지만, modify nouns with adjectives, recommend a club.', 'word', 'Functions: describe · contrast · modify · recommend', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'club fair', 'It is 동아리 fair week at Kumoh. A new student asks you which club they should join.', 'word', 'New student: 어떤 동아리가 좋아요? — You: 음악 동아리는 재미있고 친구도 많아요.', 'New student: Which club is good? — You: The music club is fun and has many friends.', null, [ACT.orientation]),

    createContentItem('재미있고 → [재미읻꼬]', 'jaemiitggo', '경음화: ㅆ받침 (in 있) + ㄱ → ㄱ + ㄲ.', 'word', '재미있고 좋아요. → [재미읻꼬]', 'Fun and good.', null, [ACT.pronunciation]),
    createContentItem('좋은 → [조은]', 'joeun', 'ㅎ-deletion: the ㅎ받침 of 좋 disappears before 은.', 'word', '좋은 동아리 → [조은 동아리]', 'a good club.', null, [ACT.pronunciation]),
    createContentItem('많아요 → [마나요]', 'manayo', 'ㅀ-cluster reduces: ㄴ jumps over, ㅎ drops.', 'word', '동아리가 많아요. → [마나요]', 'There are many clubs.', null, [ACT.pronunciation]),
    createContentItem('가입했어요 → [가이패써요]', 'gaipaesseoyo', '격음화: ㅂ받침 + ㅎ → ㅍ; 연음 in 었어요.', 'word', '동아리에 가입했어요. → [가이패써요]', 'I joined a club.', null, [ACT.pronunciation]),

    createContentItem('동아리', 'dongari', 'club (school)', 'word', '동아리에 가입했어요.', 'I joined a club.', null, [ACT.vocabularyClubs]),
    createContentItem('가입하다', 'gaiphada', 'to join', 'word', '음악 동아리에 가입할 거예요.', 'I will join the music club.', null, [ACT.vocabularyClubs]),
    createContentItem('활동', 'hwaldong', 'activity', 'word', '활동이 많아요.', 'There are many activities.', null, [ACT.vocabularyClubs]),
    createContentItem('회원', 'hoewon', 'member', 'word', '회원이 30명이에요.', '30 members.', null, [ACT.vocabularyClubs]),
    createContentItem('회장', 'hoejang', 'club president', 'word', '회장이 친절해요.', 'The president is kind.', null, [ACT.vocabularyClubs]),
    createContentItem('모임', 'moim', 'meeting', 'word', '매주 토요일에 모임이 있어요.', 'Meeting every Saturday.', null, [ACT.vocabularyClubs]),
    createContentItem('인기 있다', 'ingi itda', 'to be popular', 'word', '이 동아리는 인기 있어요.', 'This club is popular.', null, [ACT.vocabularyClubs]),
    createContentItem('신입생', 'sinipsaeng', 'freshman / new student', 'word', '신입생을 모집해요.', 'We are recruiting new members.', null, [ACT.vocabularyClubs]),
    createContentItem('취미', 'chwimi', 'hobby', 'word', '취미가 뭐예요?', 'What is your hobby?', null, [ACT.vocabularyClubs]),

    createContentItem('음악', 'eumak', 'music', 'word', '음악 동아리가 인기 많아요.', 'The music club is popular.', null, [ACT.vocabularyActivities]),
    createContentItem('춤', 'chum', 'dance', 'word', '춤 동아리도 있어요.', 'There is also a dance club.', null, [ACT.vocabularyActivities]),
    createContentItem('그림', 'geurim', 'drawing', 'word', '그림을 그려요.', 'I draw pictures.', null, [ACT.vocabularyActivities]),
    createContentItem('운동', 'undong', 'sports / exercise', 'word', '운동 동아리가 재미있어요.', 'Sports clubs are fun.', null, [ACT.vocabularyActivities]),
    createContentItem('봉사', 'bongsa', 'volunteering', 'word', '봉사 활동도 해요.', 'We also do volunteer work.', null, [ACT.vocabularyActivities]),
    createContentItem('축구', 'chukgu', 'soccer', 'word', '축구 동아리에 가입했어요.', 'I joined the soccer club.', null, [ACT.vocabularyActivities]),
    createContentItem('농구', 'nonggu', 'basketball', 'word', '농구를 좋아해요.', 'I like basketball.', null, [ACT.vocabularyActivities]),
    createContentItem('야구', 'yagu', 'baseball', 'word', '야구 동아리도 있어요.', 'There is also a baseball club.', null, [ACT.vocabularyActivities]),
    createContentItem('밴드', 'baendeu', 'band', 'word', '밴드 동아리에 가입했어요.', 'I joined a band club.', null, [ACT.vocabularyActivities]),
    createContentItem('영화', 'yeonghwa', 'movie', 'word', '영화 동아리도 재미있어요.', 'The film club is also fun.', null, [ACT.vocabularyActivities]),

    createContentItem('V/A-고 — and (parallel)', 'go', 'Attach -고 to a verb or adjective stem to combine two descriptions of the same subject.', 'sentence', '음악 동아리는 재미있고 좋아요.', 'The music club is fun and good.',
      [
        { korean: '재미있 + 고', english: '재미있고 (is fun and)' },
        { korean: '좋 + 고', english: '좋고 (is good and)' },
        { korean: '가 + 고', english: '가고 (goes and)' },
      ],
      [ACT.grammarConnector]),
    createContentItem('Only the last verb shows tense', 'past with -고', 'When chaining past actions, only the LAST verb is in past tense.', 'sentence', '음악을 듣고 그림을 그렸어요.', 'I listened to music and drew.',
      null, [ACT.grammarConnector]),
    createContentItem('Different subjects also OK', 'flexibility', '-고 works even when subjects differ.', 'sentence', '저는 음악을 좋아하고 친구는 운동을 좋아해요.', 'I like music and my friend likes sports.',
      null, [ACT.grammarConnector]),

    createContentItem('V/A-지만 — but', 'jiman', 'Attach -지만 to contrast clauses. The contrast is the key meaning.', 'sentence', '운동을 좋아하지만 잘 못해요.', 'I like sports but I am not good at them.',
      [
        { korean: '좋아하 + 지만', english: 'like but' },
        { korean: '재미있 + 지만', english: 'is fun but' },
        { korean: '비싸 + 지만', english: 'is expensive but' },
      ],
      [ACT.grammarContrast]),
    createContentItem('Past with -지만', 'tense placement', '-지만 can attach to the past stem too: -았지만 / -었지만.', 'sentence', '시험을 잘 봤지만 피곤했어요.', 'I did well on the exam but was tired.',
      null, [ACT.grammarContrast]),
    createContentItem('-지만 vs 그렇지만 / 그런데', 'in-clause vs between', '-지만 connects within one sentence. 그렇지만 / 그런데 are sentence starters meaning "however".', 'sentence', '재미있어요. 그런데 좀 비싸요.', 'It is fun. However, it is a bit expensive.',
      null, [ACT.grammarContrast]),

    createContentItem('A-(으)ㄴ N — descriptive form', 'modify a noun', 'Attach -ㄴ (after vowel) or -은 (after consonant) to an adjective stem to make it modify a noun.', 'sentence', '좋은 책 · 예쁜 옷 · 큰 가방', 'a good book · pretty clothes · a big bag.',
      [
        { korean: '좋 + 은', english: 'good (consonant) → 좋은' },
        { korean: '예쁘 + ㄴ', english: 'pretty (vowel) → 예쁜' },
        { korean: '크 + ㄴ', english: 'big (vowel) → 큰' },
      ],
      [ACT.grammarModifier]),
    createContentItem('ㅂ-irregular adjectives', 'irregular modifier', 'For ㅂ-irregular adjectives, drop ㅂ and add -운: 어려운 (difficult), 매운 (spicy), 추운 (cold).', 'sentence', '어려운 시험 · 매운 음식 · 추운 날씨', 'a difficult exam · spicy food · cold weather.',
      [
        { korean: '어렵 → 어려운', english: '어렵 + 운 → 어려운' },
        { korean: '맵 → 매운', english: '맵 + 운 → 매운' },
        { korean: '쉽 → 쉬운', english: '쉽 + 운 → 쉬운' },
      ],
      [ACT.grammarModifier]),
    createContentItem('있다 / 없다 → -는', 'special pattern', '있다 and 없다 use -는 (not -은): 재미있는 영화, 맛없는 음식.', 'sentence', '재미있는 영화 · 맛없는 음식', 'a fun movie · bland food.',
      [
        { korean: '재미있 + 는', english: 'fun → 재미있는' },
        { korean: '맛없 + 는', english: 'tastes bad → 맛없는' },
      ],
      [ACT.grammarModifier]),

    createContentItem('A club bulletin', 'reading',
      'Read aloud.',
      'sentence',
      '안녕하세요! 음악 동아리입니다. 우리 동아리는 재미있고 활기찬 동아리예요. 회원이 50명 있어요. 매주 수요일 저녁 7시에 학생회관에서 모임이 있어요. 노래도 부르고 악기도 연주해요. 신입생을 환영합니다!',
      'Hello! We are the music club. Our club is fun and energetic. We have 50 members. We meet every Wednesday 7 PM at the student center. We sing and play instruments. Freshmen are welcome!',
      [
        { korean: '재미있고 활기찬', english: 'fun and energetic (-고)' },
        { korean: '회원이 50명', english: '50 members' },
        { korean: '노래도 부르고 악기도 연주해요', english: 'sing and play instruments (-고)' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Use full sentences.', 'sentence',
      'Q1: 회원이 몇 명이에요? · Q2: 언제 모임이 있어요? · Q3: 뭐 해요?',
      'Q1: How many members? Q2: When? Q3: What do they do?',
      [
        { korean: 'A1: 50명이에요.', english: '50 members.' },
        { korean: 'A2: 매주 수요일 저녁 7시에요.', english: 'Wednesdays 7 PM.' },
        { korean: 'A3: 노래하고 악기를 연주해요.', english: 'Sing and play instruments.' },
      ],
      [ACT.reading]),

    createContentItem('Club recommendation', 'listening',
      'New student gets a recommendation.',
      'conversation',
      'A: 동아리에 가입하고 싶어요. 추천해 주세요.\nB: 어떤 활동을 좋아해요?\nA: 음악을 좋아해요. 그런데 노래는 잘 못해요.\nB: 그러면 합창 동아리는 어때요? 재미있고 친구도 많이 사귈 수 있어요.\nA: 좋네요. 모임이 언제예요?\nB: 매주 수요일 저녁 7시예요.\nA: 그럼 다음 주에 가 볼게요. 고마워요.',
      'A: I want to join a club. Recommend? B: What activities? A: Music. But I cannot sing well. B: How about choir? It is fun and you can make friends. A: Nice. When? B: Wednesday 7 PM. A: I will try next week. Thanks.',
      [
        { korean: '추천해 주세요', english: 'please recommend' },
        { korean: '합창 동아리', english: 'choir club' },
        { korean: '사귀다', english: 'to make (friends)' },
      ],
      [ACT.listening]),
    createContentItem('Hobby chat', 'listening',
      'Two students share hobbies.',
      'conversation',
      'A: 사라 씨, 취미가 뭐예요?\nB: 저는 그림 그리는 걸 좋아해요. 잘 못하지만 재미있어요.\nA: 와, 멋있네요. 그림 동아리에 가입했어요?\nB: 아직요. 좋은 동아리 있어요?\nA: 우리 학교에 미술 동아리가 있어요. 재미있고 신입생도 환영해요.\nB: 진짜요? 같이 가 볼까요?\nA: 좋아요.',
      'A: Sarah, hobby? B: Drawing. I am not good but it is fun. A: Cool. In a drawing club? B: Not yet. Good club? A: Our school has an art club. Fun and welcomes freshmen. B: Really? Shall we go together? A: Sure.',
      [
        { korean: '그림 그리는 걸 좋아해요', english: 'I like drawing (V-는 거)' },
        { korean: '신입생도 환영해요', english: 'we welcome freshmen' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'club description',
      'Use this structure.',
      'sentence',
      '저는 [동아리]에 가입했어요. 우리 동아리는 [형용사]+고 [형용사] 동아리예요. 매주 [요일]에 [장소]에서 모임이 있어요. [활동]도 하고 [활동]도 해요. 잘 못하지만 정말 재미있어요.',
      '[club name] · [two adjectives] · [meeting day/place] · [two activities] · [feeling]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 sentences describing your favorite club. Use one -고, one -지만, and one A-(으)ㄴ N.',
      'sentence', 'Example: 저는 사진 동아리에 가입했어요. 우리 동아리는 작고 좋은 동아리예요. 회원은 10명이지만 매주 모여요. 사진을 잘 못 찍지만 배우고 있어요.',
      'Example: I joined the photo club. Our club is small and good. We have only 10 members but meet weekly. I do not take good photos but I am learning.',
      null, [ACT.writing]),

    createContentItem('Korean 동아리 culture', 'culture',
      'Korean university 동아리 are central to social life. Most students join 1-2 in their first year. 신입생 환영회 (freshman welcome party) is a major event. Many lifelong friendships start here.',
      'sentence', '한국 대학에서 동아리는 친구를 사귀는 가장 좋은 방법이에요.',
      'In Korean universities, clubs are the best way to make friends.',
      [{ korean: '신입생 환영회', english: 'freshman welcome' }, { korean: '동아리방', english: 'club room' }, { korean: 'MT', english: 'membership training (overnight trip)' }], [ACT.culture]),

    createContentItem('과제: Recommend a club', 'task',
      'Roleplay: A new exchange student asks which Kumoh club to join. Recommend one using -고, -지만, A-(으)ㄴ N.',
      'conversation',
      'New student: 한국에서는 동아리 활동이 중요하다고 들었어요. 어떤 동아리가 좋아요?\nYou: [recommend + describe with -고]\nNew student: 모임은 자주 있어요?\nYou: [frequency + 좋은 모임이에요]\nNew student: 잘 못해도 괜찮아요?\nYou: [-지만 sentence reassuring]\nNew student: 좋아요. 같이 가 볼래요?',
      'AI tutor will play the new student.',
      [
        { korean: '~ 동아리는 재미있고 좋아요', english: 'X club is fun and good' },
        { korean: '잘 못하지만 ~', english: 'cannot do well but ~' },
        { korean: '좋은 / 재미있는 N', english: 'good / fun N' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
