// Level 1 Unit 10 — Weather & preferences
// Source: Book 1A·10 (여름은 더워서 안 좋아해요)
// Functions: describing weather, expressing preference and reason.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u10-orientation',
  pronunciation: 'l1u10-pronunciation',
  vocabularyWeather: 'l1u10-vocab-weather',
  vocabularySeasons: 'l1u10-vocab-seasons',
  grammarReason: 'l1u10-grammar-reason',
  grammarLike: 'l1u10-grammar-like',
  grammarSuperlative: 'l1u10-grammar-best',
  reading: 'l1u10-reading',
  listening: 'l1u10-listening',
  writing: 'l1u10-writing',
  culture: 'l1u10-culture',
  task: 'l1u10-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe today\'s weather.', 'Name the four seasons + 사계절 activities.', 'State a reasoned preference using -아/어서.', 'Pick a "favorite" with 제일/가장.'],
    task: 'Picture a Korean friend asking which season you like best and why.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — ㅂ-irregular adjectives',
    goals: ['Apply ㅂ-irregular: 덥다 → 더워요, 춥다 → 추워요, 쉽다 → 쉬워요.', 'Apply 연음 in 좋아해요 → [조아해요].'],
    task: 'Read each conjugated form aloud.' },
  { id: ACT.vocabularyWeather, section: 'Vocabulary I', title: 'Weather conditions',
    goals: ['Use 비·눈·바람·맑다·흐리다·덥다·춥다·따뜻하다·시원하다.'],
    task: 'Describe today\'s weather in one sentence.' },
  { id: ACT.vocabularySeasons, section: 'Vocabulary II', title: 'Seasons & season activities',
    goals: ['Use 봄·여름·가을·겨울 + 꽃·단풍·해수욕·눈사람.'],
    task: 'Match one activity to each season.' },
  { id: ACT.grammarReason, section: 'Grammar I', title: 'V/A-아/어서 — because (cause/reason)',
    goals: ['Attach -아서/-어서 to the verb or adjective stem.', 'Use to give reasons or sequences.', 'NEVER use -아/어서 with imperative/suggestion in the second clause; use -(으)니까 instead.'],
    task: 'Make three -아/어서 sentences giving reasons.' },
  { id: ACT.grammarLike, section: 'Grammar II', title: '좋아하다 / 싫어하다 (verbs) — like / dislike',
    goals: ['Use N + 을/를 + 좋아해요 / 싫어해요 (verb form takes object).', 'Contrast with adjective forms 좋아요 / 싫어요 (take subject 이/가).'],
    task: 'Make four sentences using both forms correctly.' },
  { id: ACT.grammarSuperlative, section: 'Grammar III', title: '제일 / 가장 — the most',
    goals: ['Use 제일 or 가장 + adjective/verb to mean "the most" / "the best".'],
    task: 'Pick your most-liked food, season, and place using 제일.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A foreigner\'s favorite season',
    goals: ['Read a paragraph about season preferences in Korea.'],
    task: 'Identify what the writer likes/dislikes and why.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Comparing seasons',
    goals: ['Follow a season-preferences dialogue.'],
    task: 'Reproduce with your own preferences.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — My favorite season',
    goals: ['Write 4-5 sentences about your favorite season + reason.'],
    task: 'Write your own paragraph.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korea\'s four seasons & cultural moments',
    goals: ['Know iconic seasonal moments: 벚꽃 (spring), 장마 (summer), 단풍 (autumn), 설경 (winter).'],
    task: 'Pick one seasonal moment you would like to experience.' },
  { id: ACT.task, section: 'Task', title: '과제 — Plan a seasonal trip',
    goals: ['Combine season, weather, preference, and reason in one continuous task.'],
    task: 'Plan a seasonal trip with the AI tutor.' },
];

const lesson = {
  title: '레벨 1 · 10과: 여름은 더워서 안 좋아해요 (Weather and Preferences)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describing-weather', label: 'Describing the weather', goal: 'Use weather adjectives + -아/어요.' },
    { id: 'sharing-preference', label: 'Sharing preference with reason', goal: 'Use -아/어서 + 좋아하다/싫어하다.' },
    { id: 'picking-favorite', label: 'Picking the favorite', goal: 'Use 제일/가장 to pick the most-liked option.' },
  ],
  relatedPools: ['topic-weather', 'topic-society'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: describe weather, name seasons, give reasoned preferences, pick favorites.', 'word', 'Functions: describe · prefer · reason · rank', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'A Korean friend asks: 한국 사계절 중에 뭐 좋아해요? You need to pick, explain why, and ask back.', 'word', 'Friend: 어떤 계절을 좋아해요? — You: 가을이 시원해서 좋아요.', 'Friend: Which season do you like? — You: I like autumn because it is cool.', null, [ACT.orientation]),

    createContentItem('덥다 → 더워요', 'deowoyo', 'ㅂ-irregular: 덥 → 더우 + 어요 → 더워요.', 'word', '오늘 더워요. → [더워요]', 'It is hot today.', null, [ACT.pronunciation]),
    createContentItem('춥다 → 추워요', 'chuwoyo', 'ㅂ-irregular: 춥 → 추우 + 어요 → 추워요.', 'word', '겨울이 추워요.', 'Winter is cold.', null, [ACT.pronunciation]),
    createContentItem('좋아해요 → [조아해요]', 'joahaeyo', 'ㅎ-deletion: ㅎ받침 of 좋 disappears before 아.', 'word', '봄을 좋아해요. → [봄을 조아해요]', 'I like spring.', null, [ACT.pronunciation]),
    createContentItem('맑다 → [막따]', 'makta', 'Cluster ㄺ → ㄱ + 경음화: ㄷ tensifies after stop.', 'word', '하늘이 맑다. → [막따]', 'The sky is clear.', null, [ACT.pronunciation]),

    createContentItem('덥다', 'deopda', 'to be hot', 'word', '오늘 너무 더워요.', 'It is very hot today.', null, [ACT.vocabularyWeather]),
    createContentItem('춥다', 'chupda', 'to be cold', 'word', '겨울에는 정말 추워요.', 'Winter is really cold.', null, [ACT.vocabularyWeather]),
    createContentItem('따뜻하다', 'ttatteuthada', 'to be warm', 'word', '봄은 따뜻해요.', 'Spring is warm.', null, [ACT.vocabularyWeather]),
    createContentItem('시원하다', 'siwonhada', 'to be cool / refreshing', 'word', '가을은 시원해요.', 'Autumn is cool.', null, [ACT.vocabularyWeather]),
    createContentItem('비', 'bi', 'rain', 'word', '비가 와요.', 'It is raining.', null, [ACT.vocabularyWeather]),
    createContentItem('눈', 'nun', 'snow', 'word', '겨울에 눈이 와요.', 'It snows in winter.', null, [ACT.vocabularyWeather]),
    createContentItem('바람', 'baram', 'wind', 'word', '오늘 바람이 많이 불어요.', 'It is very windy today.', null, [ACT.vocabularyWeather]),
    createContentItem('맑다', 'makda', 'to be sunny / clear', 'word', '하늘이 맑아요.', 'The sky is clear.', null, [ACT.vocabularyWeather]),
    createContentItem('흐리다', 'heurida', 'to be cloudy', 'word', '오늘은 흐려요.', 'It is cloudy today.', null, [ACT.vocabularyWeather]),
    createContentItem('덥다/춥다 + 너무', 'extremes', '너무 + adjective = "too / very". Common pairing.', 'word', '너무 더워요.', 'It is too hot.', null, [ACT.vocabularyWeather]),
    createContentItem('습하다', 'seuphada', 'to be humid', 'word', '여름이 습해요.', 'Summer is humid.', null, [ACT.vocabularyWeather]),
    createContentItem('건조하다', 'geonjohada', 'to be dry', 'word', '겨울이 건조해요.', 'Winter is dry.', null, [ACT.vocabularyWeather]),

    createContentItem('봄', 'bom', 'spring', 'word', '봄에 꽃이 피어요.', 'Flowers bloom in spring.', null, [ACT.vocabularySeasons]),
    createContentItem('여름', 'yeoreum', 'summer', 'word', '여름은 더워요.', 'Summer is hot.', null, [ACT.vocabularySeasons]),
    createContentItem('가을', 'gaeul', 'autumn / fall', 'word', '가을에 단풍이 들어요.', 'Leaves turn color in autumn.', null, [ACT.vocabularySeasons]),
    createContentItem('겨울', 'gyeoul', 'winter', 'word', '겨울은 추워요.', 'Winter is cold.', null, [ACT.vocabularySeasons]),
    createContentItem('사계절', 'sagyejeol', 'the four seasons', 'word', '한국은 사계절이 뚜렷해요.', 'Korea has distinct four seasons.', null, [ACT.vocabularySeasons]),
    createContentItem('꽃', 'kkot', 'flower', 'word', '봄에 꽃이 많이 피어요.', 'Many flowers bloom in spring.', null, [ACT.vocabularySeasons]),
    createContentItem('단풍', 'danpung', 'autumn leaves', 'word', '단풍이 빨개요.', 'The autumn leaves are red.', null, [ACT.vocabularySeasons]),
    createContentItem('해수욕', 'haesuyok', 'sea bathing / beach', 'word', '여름에 해수욕하러 가요.', 'I go to the beach in summer.', null, [ACT.vocabularySeasons]),
    createContentItem('눈사람', 'nunsaram', 'snowman', 'word', '겨울에 눈사람을 만들어요.', 'I make a snowman in winter.', null, [ACT.vocabularySeasons]),
    createContentItem('계절', 'gyejeol', 'season', 'word', '어떤 계절을 좋아해요?', 'Which season do you like?', null, [ACT.vocabularySeasons]),

    createContentItem('V/A-아/어서 — because', '-aseo/eoseo', 'Attach -아서 (after ㅏ/ㅗ) or -어서 (others) to a verb/adjective stem.', 'sentence', '여름은 더워서 안 좋아해요.', 'I do not like summer because it is hot.',
      [
        { korean: '덥 + 어서', english: 'ㅂ-irreg → 더워서' },
        { korean: '오 + 아서', english: '와서' },
        { korean: '맛있 + 어서', english: '맛있어서' },
        { korean: '하다 → 해서', english: 'always -해서' },
      ],
      [ACT.grammarReason]),
    createContentItem('-아/어서 vs -(으)니까', 'cause restrictions', 'NEVER use -아/어서 with imperative or suggestion. Use -(으)니까 instead.', 'sentence', '바빠서 못 가요. (OK) vs 바쁘니까 가지 마세요. (Use -(으)니까 with imperative.)', 'Two cause connectors with different distributions.', null, [ACT.grammarReason]),
    createContentItem('Sequence with -아/어서', 'do A then B', '-아/어서 also expresses two actions linked in sequence (do A, then naturally B).', 'sentence', '집에 가서 자요.', 'I go home and then sleep.',
      null, [ACT.grammarReason]),

    createContentItem('좋아하다 / 싫어하다 (verbs)', '+ 을/를', 'These are VERBS — take an object with 을/를.', 'sentence', '저는 봄을 좋아해요.', 'I like spring.',
      [{ korean: '봄을 좋아해요', english: 'spring + 을 (object) + 좋아해요 (verb)' }, { korean: '여름을 싫어해요', english: 'dislike summer' }], [ACT.grammarLike]),
    createContentItem('좋다 / 싫다 (adjectives)', '+ 이/가', 'These are ADJECTIVES — take a subject with 이/가.', 'sentence', '저는 봄이 좋아요.', 'Spring is good (for me).',
      [{ korean: '봄이 좋아요', english: 'spring + 이 (subject) + 좋아요 (adjective)' }, { korean: '여름이 싫어요', english: 'summer is unpleasant' }], [ACT.grammarLike]),
    createContentItem('Either is fine', 'common usage', 'Both forms are common — pick whichever feels natural. They mean essentially the same thing.', 'sentence', '저는 봄이 좋아요. = 저는 봄을 좋아해요.', 'I like spring (both forms).', null, [ACT.grammarLike]),

    createContentItem('제일 / 가장 — the most', 'jeil / gajang', 'Place before any adjective or verb to mean "most".', 'sentence', '저는 가을이 제일 좋아요.', 'I like autumn the most.',
      [{ korean: '제일', english: 'most (casual)' }, { korean: '가장', english: 'most (slightly more formal)' }], [ACT.grammarSuperlative]),
    createContentItem('Combined: 제일 + 좋아하다', 'favorite', 'Combine 제일 + 좋아하다 to say "favorite".', 'sentence', '한국 음식 중에서 김치찌개를 제일 좋아해요.', 'Among Korean foods, I like kimchi stew the most.',
      [{ korean: 'N 중에서', english: 'among N' }, { korean: '제일 좋아해요', english: 'like the most' }], [ACT.grammarSuperlative]),

    createContentItem('A foreigner\'s favorite season', 'reading',
      'Read aloud, then answer.',
      'sentence',
      '저는 한국에서 살아요. 사계절 중에 가을을 제일 좋아해요. 가을은 시원해서 산책하기 좋아요. 단풍도 정말 예뻐요. 여름은 너무 덥고 습해서 별로예요. 겨울도 너무 추워요. 그래도 눈을 좋아해서 가끔 좋아요.',
      'I live in Korea. Among the four seasons, I like autumn the most. Autumn is cool, so it is good for walking. The autumn leaves are really pretty. Summer is too hot and humid, so it is not great. Winter is also too cold. But I like snow, so it is sometimes nice.',
      [
        { korean: '시원해서', english: 'because it is cool' },
        { korean: '덥고 습해서', english: 'because it is hot and humid' },
        { korean: '눈을 좋아해서', english: 'because I like snow' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Use -아/어서 in your answers.', 'sentence',
      'Q1: 어떤 계절을 제일 좋아해요? · Q2: 왜 여름은 별로예요? · Q3: 겨울도 좋아해요?',
      'Q1: Which season most? Q2: Why is summer not great? Q3: Does she also like winter?',
      [
        { korean: 'A1: 가을을 제일 좋아해요.', english: 'She likes autumn the most.' },
        { korean: 'A2: 너무 덥고 습해서요.', english: 'Because it is too hot and humid.' },
        { korean: 'A3: 가끔이요. 눈을 좋아해서요.', english: 'Sometimes. Because she likes snow.' },
      ],
      [ACT.reading]),

    createContentItem('Comparing seasons', 'listening',
      'Two friends compare season preferences.',
      'conversation',
      'A: 한국 사계절 중에 어떤 계절을 좋아해요?\nB: 저는 가을을 제일 좋아해요. 시원하고 단풍도 예뻐요.\nA: 여름은요?\nB: 여름은 너무 더워서 별로예요. 사라 씨는요?\nA: 저는 겨울이 좋아요. 눈을 좋아해서요.\nB: 아, 외국에서는 눈이 자주 와요?\nA: 네. 겨울이 정말 길어요.\nB: 한국 겨울도 추우니까 같이 눈사람 만들어요.\nA: 좋아요!',
      'A: Among Korea\'s four seasons, which do you like? B: Autumn most — cool, and the leaves are pretty. A: Summer? B: Too hot, not great. You? A: I like winter — I like snow. B: Oh, snow often in your country? A: Yes, winter is long. B: Korean winter is cold too, let us build a snowman together. A: Yes!',
      [
        { korean: '제일 좋아해요', english: 'like most' },
        { korean: '별로예요', english: 'not great' },
        { korean: '눈사람 만들다', english: 'build a snowman' },
      ],
      [ACT.listening]),
    createContentItem('Weather small talk', 'listening',
      'Quick weather exchange at the start of a day.',
      'conversation',
      'A: 오늘 날씨 어때요?\nB: 좀 흐려요. 비가 올 것 같아요.\nA: 그래요? 우산 챙겨야겠어요.\nB: 어제도 비가 와서 길이 좀 미끄러워요. 조심하세요.\nA: 고마워요.',
      'A: How is the weather today? B: A bit cloudy. Looks like rain. A: Really? I should bring an umbrella. B: It rained yesterday too, so the streets are slippery. Be careful. A: Thanks.',
      [
        { korean: '비가 올 것 같아요', english: 'looks like rain' },
        { korean: '우산 챙기다', english: 'bring an umbrella' },
        { korean: '조심하세요', english: 'be careful' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'template',
      'Use this structure.',
      'sentence',
      '저는 사계절 중에 [계절]을/를 제일 좋아해요. [계절]은 [형용사]+아/어서 좋아요. [활동]도 좋아해요. 반대로 [계절]은 [형용사]+아/어서 별로예요.',
      '[favorite season] · [reason] · [related activity] · [least favorite + reason]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 sentences about your favorite season. Include at least one -아/어서 reason and one 제일.',
      'sentence', 'Example: 저는 가을을 제일 좋아해요. 가을은 시원해서 좋아요. 단풍도 예뻐요. 그런데 여름은 너무 더워서 별로예요. 봄도 따뜻해서 좋아요.',
      'Example: I like autumn the most. It is cool and I like it. The leaves are pretty too. But summer is too hot. Spring is also nice because it is warm.',
      null, [ACT.writing]),

    createContentItem('Korea\'s seasonal cultural moments', 'culture',
      'Each season has iconic moments: 벚꽃 축제 (cherry blossoms, April) in 진해; 장마 (rainy season, June-July); 단풍놀이 (autumn-leaves viewing, October) in 설악산; 설경 (snow scenery, January) in 강원도.',
      'sentence', '벚꽃은 봄, 장마는 여름, 단풍은 가을, 눈은 겨울의 풍경이에요.',
      'Cherry blossoms = spring, monsoon = summer, autumn leaves = autumn, snow = winter scenery.',
      [
        { korean: '벚꽃', english: 'cherry blossoms' },
        { korean: '장마', english: 'monsoon / rainy season' },
        { korean: '단풍놀이', english: 'autumn-leaves viewing' },
        { korean: '설경', english: 'snow scenery' },
      ],
      [ACT.culture]),

    createContentItem('과제: Plan a seasonal trip', 'task',
      'Roleplay: A friend wants to know which season is best to visit Korea. Suggest one season, give reasons, and propose one activity.',
      'conversation',
      'Friend: 한국에 언제 가는 게 좋아요?\nYou: [pick a season + reason with -아/어서]\nFriend: 그 계절은 어때요?\nYou: [describe weather]\nFriend: 뭐 할 수 있어요?\nYou: [propose one activity + use 제일]\nFriend: 좋아요. 그때 가야겠어요.',
      'AI tutor will play the friend.',
      [
        { korean: '가을이 시원해서 좋아요', english: 'autumn is good because it is cool' },
        { korean: '단풍이 제일 예뻐요', english: 'autumn leaves are the prettiest' },
        { korean: '~을/를 추천해요', english: 'I recommend ~' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
