// Level 2 Unit 7 — 옳고 그름 (Right and wrong)
// Source: Book 2D Unit 7.
// Grammar: A/V-더라도, A/V-다고 보다, V-(으)ㄴ 채(로), A/V-(으)ㄴ지 ~ V-는지 ~.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2u7-orientation',
  vocabulary: 'l2u7-vocabulary',
  pronunciation: 'l2u7-pronunciation',
  grammar: 'l2u7-grammar',
  speaking: 'l2u7-speaking',
  readingSpeaking: 'l2u7-reading-speaking',
  listeningSpeaking: 'l2u7-listening-speaking',
  readingWriting: 'l2u7-reading-writing',
  culture: 'l2u7-culture',
  task: 'l2u7-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Assert and defend opinions on right/wrong with 4 advanced patterns.', 'Use -더라도, -다고 보다, -(으)ㄴ 채(로), -(으)ㄴ지 ~ -는지.', 'Discuss social etiquette in Korean public spaces.'],
    task: 'Imagine reporting noisy neighbors to your professor or discussing what counts as "manners" in Korea.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Opinions + behaviors + -질 suffix',
    goals: ['Use 의견·행동·논란·소음·규칙·예의.', 'Use the -질 suffix for negative-behavior nouns: 욕질, 손가락질, 새치기.'],
    task: 'Use one -질 word in a complaint.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '유음화 — Liquidization (ㄴ + ㄹ → ㄹ + ㄹ)',
    goals: ['Apply 유음화: 논란 [놀란], 신라 [실라], 권력 [궐력].'],
    task: 'Read 논란, 신라, 권력, 일년 with liquidization.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Argument patterns',
    goals: ['A/V-더라도 — even if', 'A/V-다고 보다 — view as', 'V-(으)ㄴ 채(로) — in the state of', 'A-(으)ㄴ지 V-는지 — whether ~ or ~'],
    task: 'Use each pattern in an argument.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Asserting opinions on dramas',
    goals: ['State your view with reasons.'],
    task: 'Assert a strong opinion about a K-drama.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Public-place behavior blog',
    goals: ['Read a blog post about etiquette.', 'Take a position.'],
    task: 'State your view on a public-place rule.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Apartment noise + arguments',
    goals: ['Listen to a complaint.', 'Argue with supporting examples.'],
    task: 'Defend a noise-related opinion.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Movie-theater proposal',
    goals: ['Read a proposal.', 'Write your own.'],
    task: 'Propose a rule for a Korean cinema.' },
  { id: ACT.culture, section: 'Culture Note', title: '신문고 — the petition drum',
    goals: ['Understand the historical 신문고 + modern petition systems (청와대 청원, 국민신문고).'],
    task: 'Compare with how citizens petition in your country.' },
  { id: ACT.task, section: 'Task', title: 'One-minute opinion speech',
    goals: ['Speak on a given topic for 60 seconds using all 4 patterns.'],
    task: 'Give a 1-minute opinion on whether food should be allowed on public buses.' },
];

const lesson = {
  title: '레벨 2 · 7과: 옳고 그름 (Right and Wrong)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'presenting-opinions', label: 'Presenting opinions', goal: 'Use A-다고 보다 / V-ㄴ/는다고 보다.' },
    { id: 'explaining-with-examples', label: 'Supporting with examples', goal: 'Use V-(으)ㄴ 채(로) to give a vivid example.' },
    { id: 'qualifying-opinion', label: 'Qualifying with "even if"', goal: 'Use A/V-더라도 to acknowledge counter-arguments.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: assert, defend, qualify opinions with native-like grammar.', 'word', 'Functions: assert · qualify · example · uncertain', 'Argument toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'Your upstairs neighbor parties past midnight every weekend. You decide to confront politely — you need careful Korean.', 'word', 'You: 늦더라도 한번 이야기해 볼게요. — Neighbor: 죄송해요.', 'You: Even if late, I will speak with them. — Neighbor: Sorry.', null, [ACT.orientation]),

    createContentItem('의견', 'uigyeon', 'opinion', 'word', '제 의견을 말할게요.', 'I will share my opinion.', null, [ACT.vocabulary]),
    createContentItem('행동', 'haengdong', 'action / behavior', 'word', '행동이 무례해요.', 'Behavior is rude.', null, [ACT.vocabulary]),
    createContentItem('논란', 'nollan [놀란]', 'controversy (유음화)', 'word', '큰 논란이 있어요.', 'Big controversy.', null, [ACT.vocabulary]),
    createContentItem('소음', 'soeum', 'noise', 'word', '아파트 소음이 심해요.', 'Apartment noise is severe.', null, [ACT.vocabulary]),
    createContentItem('규칙', 'gyuchik', 'rule', 'word', '규칙을 지켜야 해요.', 'Follow the rules.', null, [ACT.vocabulary]),
    createContentItem('예의', 'yeui', 'manners', 'word', '예의를 지키세요.', 'Mind your manners.', null, [ACT.vocabulary]),
    createContentItem('비매너', 'bimaeneo', 'rudeness', 'word', '비매너 행동이 많아요.', 'Lots of rude behavior.', null, [ACT.vocabulary]),
    createContentItem('새치기', 'saechigi', 'cutting in line', 'word', '새치기는 안 돼요.', 'No line-cutting.', null, [ACT.vocabulary]),
    createContentItem('욕질', 'yokjil', 'cursing (-질 suffix)', 'word', '공공장소에서 욕질하지 마세요.', 'No cursing in public.', null, [ACT.vocabulary]),
    createContentItem('손가락질', 'sonkkarakjil', 'finger-pointing (-질)', 'word', '손가락질은 무례해요.', 'Pointing fingers is rude.', null, [ACT.vocabulary]),
    createContentItem('험담질', 'heomdamjil', 'gossiping (-질)', 'word', '험담질을 그만하세요.', 'Stop gossiping.', null, [ACT.vocabulary]),
    createContentItem('찬성하다', 'chanseonghada', 'to agree', 'word', '의견에 찬성해요.', 'I agree.', null, [ACT.vocabulary]),
    createContentItem('반대하다', 'bandaehada', 'to oppose', 'word', '저는 반대해요.', 'I oppose it.', null, [ACT.vocabulary]),
    createContentItem('주장하다', 'jujanghada', 'to claim / assert', 'word', '자신의 의견을 주장해요.', 'Asserts one\'s opinion.', null, [ACT.vocabulary]),
    createContentItem('인정하다', 'injeonghada', 'to acknowledge', 'word', '잘못을 인정해요.', 'I acknowledge the mistake.', null, [ACT.vocabulary]),
    createContentItem('옳다 / 그르다', 'olta / geureuda', 'right / wrong', 'word', '옳고 그름을 판단해요.', 'I judge right and wrong.', null, [ACT.vocabulary]),

    createContentItem('논란 → [놀란]', 'nollan', '유음화 (liquidization): ㄴ + ㄹ → ㄹ + ㄹ.', 'word', '큰 논란이 있어요. → [놀라니]', 'Big controversy.', null, [ACT.pronunciation]),
    createContentItem('신라 → [실라]', 'silla', 'Same 유음화 rule.', 'word', '신라 시대', 'Silla era.', null, [ACT.pronunciation]),
    createContentItem('권력 → [궐력]', 'gwollyeok', '유음화 across syllable boundary.', 'word', '권력이 있어요. → [궐려기]', 'Has power.', null, [ACT.pronunciation]),
    createContentItem('일년 → [일련]', 'illyeon', 'Reverse direction: ㄹ + ㄴ → ㄹ + ㄹ.', 'word', '일년에 한 번 → [일려네]', 'Once a year.', null, [ACT.pronunciation]),

    createContentItem('A/V-더라도 — even if', 'deorado', 'Stronger than -아/어도. "Even if" with a hypothetical or strong contrast.', 'sentence', '늦더라도 꼭 와야 해요.', 'Even if late, you must come.',
      [{ korean: '늦 + 더라도', english: 'even if late' }, { korean: '비가 오 + 더라도', english: 'even if it rains' }], [ACT.grammar]),
    createContentItem('A/V-다고 보다 — view as / consider', 'dago boda', 'State a considered opinion. Softer than 생각하다.', 'sentence', '저는 그 행동이 무례하다고 봐요.', 'I view that behavior as rude.',
      [{ korean: 'A-다고 보다', english: 'adjective' }, { korean: 'V-ㄴ다/는다고 보다', english: 'verb' }], [ACT.grammar]),
    createContentItem('V-(으)ㄴ 채(로) — in the state of', 'chae', 'Express a continuing state while another action happens.', 'sentence', '신발을 신은 채로 들어왔어요.', 'They walked in still wearing shoes.',
      [{ korean: 'V-(으)ㄴ 채(로)', english: 'in the state of having V-ed' }, { korean: 'examples', english: '눈을 감은 채, 옷을 입은 채' }], [ACT.grammar]),
    createContentItem('A-(으)ㄴ지 ~ V-는지 — whether ~ or ~', 'either / or uncertainty', 'Express uncertainty between alternatives.', 'sentence', '이게 옳은지 그른지 잘 모르겠어요.', 'I do not know whether this is right or wrong.',
      [{ korean: 'A-(으)ㄴ지', english: 'adjective option' }, { korean: 'V-는지', english: 'verb option' }], [ACT.grammar]),

    createContentItem('Drama opinion', 'speaking',
      'Assert with reasons.',
      'sentence', '저는 그 주인공이 잘못했다고 봐요. 친구를 속인 채로 도와줘 봤자 진심이 아니에요.',
      'I view that the protagonist was wrong. Helping while deceiving a friend is not sincere.',
      null, [ACT.speaking]),

    createContentItem('Public-place behavior blog', 'reading',
      'Read this opinion post.',
      'sentence',
      '요즘 지하철에서 음식을 먹는 사람이 늘고 있어요. 저는 이게 옳은 행동이라고 보지 않아요. 다른 사람들이 불편해하더라도 자기만 편하게 행동하는 사람들이 있어요. 신발을 신은 채로 좌석에 다리를 올리는 경우도 있어요. 이런 행동들이 옳은지 그른지 한번 생각해 봐야 해요.',
      'Lately more people eat food on the subway. I do not view this as right behavior. Even if others are uncomfortable, some people only act for their own comfort. Some even put their feet on seats while still wearing shoes. We should think about whether these are right or wrong.',
      [
        { korean: '~다고 보다', english: 'view as' },
        { korean: '~더라도', english: 'even if' },
        { korean: '~(으)ㄴ 채로', english: 'in the state of' },
        { korean: '~(으)ㄴ지 ~ㄴ지', english: 'whether ~ or ~' },
      ],
      [ACT.readingSpeaking]),

    createContentItem('Apartment noise', 'listening',
      'Discussion about a noisy neighbor.',
      'conversation',
      'A: 윗집 소음이 너무 심해요. 어떻게 해야 할까요?\nB: 저도 그 행동이 너무하다고 봐요. 한번 직접 이야기해 보세요.\nA: 늦더라도 가서 정중하게 말해 볼게요. 그런데 어떻게 시작해야 할지 모르겠어요.\nB: 인사를 하고 자기소개를 한 채로 시작해요. 차분하게요.\nA: 좋은 조언이에요. 옳은 방법인지 좋은 방법인지 모르지만 한번 해 볼게요.\nB: 화내지 마세요.',
      'A: Upstairs noise severe. What to do? B: I also view it as too much. Talk to them directly. A: Even if late, I will speak politely. Not sure how to start. B: Greet, introduce yourself, calmly. A: Good advice. Whether the right way or good way, I will try. B: Do not get angry.',
      [
        { korean: '~다고 보다', english: 'view as' },
        { korean: '~더라도', english: 'even if' },
        { korean: '~ㄴ 채로', english: 'in the state of' },
        { korean: '~ㄴ지 ~지', english: 'whether or' },
      ],
      [ACT.listeningSpeaking]),

    createContentItem('Movie-theater proposal', 'reading + writing',
      'Sample proposal.',
      'sentence',
      '저는 영화관에서 휴대폰을 사용하는 행동이 옳지 않다고 봐요. 영화가 시작된 채로 화면을 켜면 다른 관객이 불편해요. 어떤 영화든 좋은 영화든 모두 즐길 권리가 있어요. 그래서 영화관에서는 휴대폰 사용을 금지하는 게 옳다고 봐요.',
      'I view phone use in movie theaters as wrong. Once the movie starts, turning on screens disturbs others. Every movie, good or bad, deserves to be enjoyed. So I view banning phones in theaters as right.',
      null, [ACT.readingWriting]),

    createContentItem('신문고 → modern petitions', 'culture',
      '신문고 was a drum at the palace in 조선 시대 where commoners could ring for grievances. Modern descendants: 국민신문고 (online complaint portal) and 청와대 청원 (presidential petition platform, 2017-2022, replaced by 국민동의청원 in 2022).',
      'sentence', '조선시대 신문고처럼 지금도 국민이 청원할 수 있어요.',
      'Like the Joseon-era 신문고, citizens can still petition today.',
      [
        { korean: '신문고', english: 'historical petition drum' },
        { korean: '국민신문고', english: 'modern complaint portal' },
        { korean: '청원', english: 'petition' },
      ],
      [ACT.culture]),

    createContentItem('과제: 1-minute opinion', 'task',
      'Roleplay: Speak for 60 sec on "Should food be allowed on public buses?". Use all 4 patterns.',
      'conversation',
      'Tutor: 시작하세요.\nYou: [opinion + ~ 다고 봐요 + ~ 더라도 + ~ ㄴ 채로 + ~ ㄴ지 ~ 는지]\nTutor: 좋아요. 반대 의견은요?\nYou: [counter-argue with same patterns]',
      'AI tutor will moderate.',
      [
        { korean: '~ 다고 봐요', english: 'I view as' },
        { korean: '~ 더라도', english: 'even if' },
        { korean: '~ ㄴ 채로', english: 'in the state of' },
        { korean: '~ ㄴ지 ~ 는지', english: 'whether or' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
