// Level 2 Track-Adult Unit 8 — 어디가 아프십니까? (Workplace medical)
// Source: Book 2A·8.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au8-orientation',
  pronunciation: 'l2au8-pronunciation',
  vocabularySymptoms: 'l2au8-vocab-symp',
  vocabularyMedical: 'l2au8-vocab-med',
  grammarSeems: 'l2au8-grammar-seems',
  grammarTry: 'l2au8-grammar-try',
  reading: 'l2au8-reading',
  listening: 'l2au8-listening',
  writing: 'l2au8-writing',
  culture: 'l2au8-culture',
  task: 'l2au8-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe workplace symptoms.', 'Request 병가 (sick leave) formally.', 'Soften with A-(으)ㄴ 것 같다.', 'Follow prescription instructions.'],
    task: 'Imagine waking up sick — call your manager, request half-day leave, get prescription.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Medical formal phrases',
    goals: ['Apply 비음화 in 신청합니다 → [신청함니다].', 'Apply 격음화 in 식후 30분 → [시쿠 삼십푼].'],
    task: 'Read each medical phrase.' },
  { id: ACT.vocabularySymptoms, section: 'Vocabulary I', title: 'Symptoms + medical conditions',
    goals: ['Use 두통·몸살·열·기침·콧물·복통·소화불량.'],
    task: 'Describe 3 symptoms.' },
  { id: ACT.vocabularyMedical, section: 'Vocabulary II', title: 'Medical services + 병가',
    goals: ['Use 병가·처방·약국·진료·내과·정형외과·보험증·진단서.'],
    task: 'Plan a clinic visit.' },
  { id: ACT.grammarSeems, section: 'Grammar I', title: 'A-(으)ㄴ 것 같다 / V-는 것 같다 — seems',
    goals: ['Soften statements with "seems".'],
    task: 'Soften 3 complaints.' },
  { id: ACT.grammarTry, section: 'Grammar II', title: 'V-아/어 보십시오 + N 후에',
    goals: ['Formal suggestion to "try".', 'Sequence with N 후에 / V-(으)ㄴ 후에.'],
    task: 'Give 3 medical pieces of advice.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Prescription',
    goals: ['Read a prescription label.'],
    task: 'Follow the dosage instructions.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Sick leave call',
    goals: ['Follow a 병가 request call.'],
    task: 'Reproduce with your symptoms.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Sick leave email',
    goals: ['Write a 3-4 line email requesting half-day sick leave.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — 국민건강보험 + 의원',
    goals: ['Know about 국민건강보험 (national health insurance).', 'Know that 의원 (small clinic) is cheap with insurance.'],
    task: 'Plan the cheapest way to see a doctor.' },
  { id: ACT.task, section: 'Task', title: '과제 — Request sick leave',
    goals: ['Combine 같다 soften + 보십시오 + 후에.'],
    task: 'Roleplay calling the manager.' },
];

const lesson = {
  title: '레벨 2 (직장) · 8과: 어디가 아프십니까? (Workplace Medical)',
  category: 'healthcare',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'requesting-leave', label: 'Requesting sick leave', goal: 'Use 몸이 안 좋다 + 병가 + V-고 싶다.' },
    { id: 'softening-complaint', label: 'Softening complaint', goal: 'Use A-(으)ㄴ 것 같다.' },
    { id: 'following-prescription', label: 'Following prescription', goal: 'Use 식후 N 후에 + 드십시오.' },
  ],
  relatedPools: ['topic-health'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: describe symptoms, request sick leave, follow prescription.', 'word', 'Functions: describe · soften · request · follow', 'Medical toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'You wake up with a fever. Call your manager, request a half-day, see a doctor, follow the prescription.', 'word', 'You: 몸살이 난 것 같습니다. 병가를 신청하고 싶습니다. — Manager: 푹 쉬세요.', 'Body aches. Want sick leave. — Rest well.', null, [ACT.orientation]),

    createContentItem('신청합니다 → [신청함니다]', 'sincheonghamnida', '비음화.', 'word', '병가를 신청합니다.', 'Applying for leave.', null, [ACT.pronunciation]),
    createContentItem('식후 30분 → [시쿠 삼십푼]', 'sikhu samsippun', '격음화 + 경음화.', 'word', '식후 30분 후에 드십시오.', '30 min after meal.', null, [ACT.pronunciation]),
    createContentItem('약국 → [약꾹]', 'yakkuk', '경음화: ㄱ-받침 + ㄱ → tense ㄲ.', 'word', '약국에 갑니다.', 'Go to pharmacy.', null, [ACT.pronunciation]),
    createContentItem('회복 → [회복]', 'hoebok', 'No major change.', 'word', '회복하세요.', 'Get well.', null, [ACT.pronunciation]),

    createContentItem('두통', 'dutong', 'headache', 'word', '두통이 심합니다.', 'Bad headache.', null, [ACT.vocabularySymptoms]),
    createContentItem('몸살', 'momsal', 'body aches / flu', 'word', '몸살이 났습니다.', 'I have body aches.', null, [ACT.vocabularySymptoms]),
    createContentItem('열', 'yeol', 'fever', 'word', '열이 납니다.', 'I have a fever.', null, [ACT.vocabularySymptoms]),
    createContentItem('기침', 'gichim', 'cough', 'word', '기침이 심합니다.', 'Bad cough.', null, [ACT.vocabularySymptoms]),
    createContentItem('콧물', 'konmul', 'runny nose', 'word', '콧물이 나요.', 'Runny nose.', null, [ACT.vocabularySymptoms]),
    createContentItem('복통', 'boktong', 'stomachache', 'word', '복통이 있습니다.', 'Stomachache.', null, [ACT.vocabularySymptoms]),
    createContentItem('소화불량', 'sohwa bullyang', 'indigestion', 'word', '소화불량이 있습니다.', 'Indigestion.', null, [ACT.vocabularySymptoms]),
    createContentItem('어지럽다', 'eojireopda', 'dizzy', 'word', '어지럽습니다.', 'I am dizzy.', null, [ACT.vocabularySymptoms]),
    createContentItem('감기', 'gamgi', 'cold', 'word', '감기에 걸렸습니다.', 'Caught a cold.', null, [ACT.vocabularySymptoms]),

    createContentItem('병가', 'byeonga', 'sick leave', 'word', '병가를 신청합니다.', 'Applying for sick leave.', null, [ACT.vocabularyMedical]),
    createContentItem('처방', 'cheobang', 'prescription', 'word', '의사가 처방했습니다.', 'Doctor prescribed.', null, [ACT.vocabularyMedical]),
    createContentItem('약국', 'yakguk', 'pharmacy', 'word', '약국에서 약을 받았습니다.', 'Got medicine at pharmacy.', null, [ACT.vocabularyMedical]),
    createContentItem('진료', 'jinryo', 'medical exam', 'word', '진료를 받았습니다.', 'Had an exam.', null, [ACT.vocabularyMedical]),
    createContentItem('내과', 'naegwa', 'internal medicine', 'word', '내과에 갑니다.', 'Go to internal medicine.', null, [ACT.vocabularyMedical]),
    createContentItem('정형외과', 'jeonghyeong oegwa', 'orthopedics', 'word', '정형외과에서 검사 받았어요.', 'Had orthopedic exam.', null, [ACT.vocabularyMedical]),
    createContentItem('이비인후과', 'iiinhugwa', 'ENT', 'word', '이비인후과에 가세요.', 'Go to ENT.', null, [ACT.vocabularyMedical]),
    createContentItem('보험증', 'boheomjeung', 'insurance card', 'word', '보험증 가지고 가세요.', 'Bring insurance card.', null, [ACT.vocabularyMedical]),
    createContentItem('진단서', 'jindanseo', 'medical certificate', 'word', '진단서 받았어요.', 'Got medical cert.', null, [ACT.vocabularyMedical]),
    createContentItem('식후', 'sikhu', 'after meal', 'word', '식후 30분에 드세요.', '30 min after meal.', null, [ACT.vocabularyMedical]),
    createContentItem('회복', 'hoebok', 'recovery', 'word', '빨리 회복하세요.', 'Get well soon.', null, [ACT.vocabularyMedical]),

    createContentItem('A-(으)ㄴ 것 같다 — seems A', 'soften', 'Soften a statement by saying "seems".', 'sentence', '몸살이 난 것 같습니다.', 'Seems I have body aches.',
      [{ korean: 'A-(으)ㄴ 것 같다', english: 'adjective' }, { korean: 'V-는 것 같다', english: 'verb' }, { korean: 'V-(으)ㄴ 것 같다', english: 'past' }], [ACT.grammarSeems]),
    createContentItem('Use case', 'professional softening', 'Use to avoid sounding too definitive when talking about health.', 'sentence', '두통이 있는 것 같습니다 (softer than 두통이 있습니다).', 'Softer for politeness.',
      null, [ACT.grammarSeems]),

    createContentItem('V-아/어 보십시오 — try V (formal)', 'try', 'Formal suggestion. Use for medical advice.', 'sentence', '내과에 한번 가 보십시오.', 'Try going to internal medicine.',
      [{ korean: 'V-아/어 보십시오', english: 'try (formal)' }, { korean: 'V-아/어 보세요', english: 'try (polite)' }], [ACT.grammarTry]),
    createContentItem('N 후에 / V-(으)ㄴ 후에', 'after', 'After N / after V-ing.', 'sentence', '식후 30분 후에 드십시오.', '30 min after meal.',
      [{ korean: '식후 N', english: 'N after meal' }, { korean: '먹은 후에', english: 'after eating' }], [ACT.grammarTry]),

    createContentItem('Prescription label', 'reading',
      'Read this medication label.',
      'sentence',
      '처방전\n· 환자명: 김민수\n· 약: 감기약 (3일분)\n· 복용법: 1일 3회, 식후 30분 후에 복용\n· 주의: 1) 운전 시 조심하십시오. 2) 술 드시지 마십시오. 3) 알레르기 있으면 즉시 중단하십시오.',
      'Prescription:\n- Patient: Kim Minsu\n- Med: cold med (3 days)\n- Dosage: 3x/day, 30 min after meal\n- Warnings: 1) Drive carefully. 2) No alcohol. 3) Stop if allergy.',
      [
        { korean: '복용법', english: 'dosage' },
        { korean: '주의', english: 'warning' },
        { korean: '중단하다', english: 'to stop' },
      ],
      [ACT.reading]),

    createContentItem('Sick-leave call', 'listening',
      'Calling the manager.',
      'conversation',
      'A (직원): 과장님, 안녕하십니까. 죄송하지만 오늘 몸이 너무 안 좋아서 병가를 신청하고 싶습니다.\nB (과장): 어디가 아프세요?\nA: 어제부터 두통이 심하고 몸살이 난 것 같습니다.\nB: 그러면 병원에 가 보세요. 진단서가 있으면 더 좋습니다.\nA: 네, 알겠습니다. 진료받고 다시 연락 드리겠습니다.\nB: 푹 쉬시고 빨리 회복하시기 바랍니다.',
      'A: Manager, hello. Sorry, not feeling well. Want sick leave. B: What hurts? A: Headache since yesterday, seems like body aches. B: See a doctor. Better with cert. A: Yes, will call back after. B: Rest well, recover quickly.',
      [
        { korean: '~ 신청하고 싶습니다', english: 'want to apply' },
        { korean: '~ 것 같습니다', english: 'seems' },
        { korean: '연락 드리겠습니다', english: 'will contact (humble)' },
      ],
      [ACT.listening]),

    createContentItem('Sick-leave email', 'writing',
      'Sample email.',
      'sentence',
      '안녕하십니까. 김민수입니다. 어제부터 몸살이 난 것 같아서 오늘 병가를 신청하고 싶습니다. 오전에 내과에 가서 진료를 받겠습니다. 진단서가 나오면 첨부해 드리겠습니다. 죄송합니다. 감사합니다.',
      'Hello. Kim Minsu. Body aches since yesterday — want sick leave today. Going to internal med this morning. Will attach medical cert. Sorry. Thanks.',
      null, [ACT.writing]),

    createContentItem('국민건강보험 + 의원', 'culture',
      '국민건강보험 (National Health Insurance) covers all residents including foreign workers. With insurance, a 의원 (clinic) visit costs about 5,000 won. Medicine at the 약국 typically 3,000-10,000 won. Foreign workers should get insurance card (보험증) registered immediately.',
      'sentence', '한국에서는 건강보험 덕분에 진료비가 저렴해요.',
      'In Korea, exams are cheap thanks to health insurance.',
      [
        { korean: '국민건강보험', english: 'NHI' },
        { korean: '의원', english: 'small clinic' },
        { korean: '보험증', english: 'insurance card' },
        { korean: '진료비', english: 'medical fee' },
      ],
      [ACT.culture]),

    createContentItem('과제: Request sick leave', 'task',
      'Roleplay: Call your manager to request half-day sick leave.',
      'conversation',
      'You: 과장님, 안녕하십니까. ~ 난 것 같습니다.\nManager: 어디가 아프세요?\nYou: ~ 입니다. 병가를 신청하고 싶습니다.\nManager: 병원에 가 보세요.\nYou: 진료받고 연락 드리겠습니다.\nManager: 푹 쉬시고 회복하세요.',
      'AI tutor will play the manager.',
      [
        { korean: '~ 것 같습니다', english: 'seems' },
        { korean: '병가를 신청하고 싶습니다', english: 'want sick leave' },
        { korean: '~ 가 보십시오', english: 'try going' },
        { korean: '식후 N 후에', english: 'N after meal' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
