// Level 2 Unit 5 — 속담과 관용어 (Proverbs and idioms)
// Source: Book 2D Unit 5.
// Grammar: A/V-고 해서, A-다더니/V-ㄴ다더니, A/V-기 마련이다, V-다 보니(까).

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2u5-orientation',
  vocabulary: 'l2u5-vocabulary',
  pronunciation: 'l2u5-pronunciation',
  grammar: 'l2u5-grammar',
  speaking: 'l2u5-speaking',
  readingSpeaking: 'l2u5-reading-speaking',
  listeningSpeaking: 'l2u5-listening-speaking',
  readingWriting: 'l2u5-reading-writing',
  culture: 'l2u5-culture',
  task: 'l2u5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Use 10+ Korean proverbs and body-part idioms.', 'Console & quote with -기 마련이다, -다더니, -고 해서.', 'Talk like a native uses sayings.'],
    task: 'Imagine consoling a Korean friend who failed an exam — use a proverb and the 기 마련이다 pattern.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Proverbs + body-part idioms',
    goals: ['10+ proverbs + 5+ body-part idioms (발/눈/손/귀/입).'],
    task: 'Pick 3 proverbs and explain their meaning in Korean.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Final cluster ㄺ, ㄻ',
    goals: ['Pronounce 닭 [닥], 삶 [삼], 흙 [흑], 옮 [옴] correctly.'],
    task: 'Read 닭, 삶, 흙, 닭고기, 삶다 aloud.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Quoting + consoling patterns',
    goals: ['A/V-고 해서 — and so on (multiple reasons)', 'A-다더니/V-ㄴ다더니 — they said ~ and indeed', 'A/V-기 마련이다 — is bound to', 'V-다 보니(까) — having continuously V-ed'],
    task: 'Use each pattern in a sentence.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Explaining a frustration with multiple reasons',
    goals: ['Use ~고 해서 to give multiple stacked reasons.'],
    task: 'Tell a small frustration.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Personality descriptions',
    goals: ['Read a personality profile using body-part idioms.', 'Describe someone.'],
    task: 'Describe a classmate using 2 idioms.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Consoling with proverbs',
    goals: ['Listen to a friend\'s problem.', 'Console with a proverb.'],
    task: 'Console using one proverb.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Quoting proverbs in writing',
    goals: ['Read short articles citing proverbs.', 'Write a piece quoting one.'],
    task: 'Write 3 sentences quoting a Korean proverb.' },
  { id: ACT.culture, section: 'Culture Note', title: 'Animals in Korean proverbs',
    goals: ['Recognize recurring characters: 호랑이, 소, 까마귀, 까치, 닭.'],
    task: 'Find a similar saying from your culture.' },
  { id: ACT.task, section: 'Task', title: 'Proverb pantomime',
    goals: ['Mime a proverb so others can guess.'],
    task: 'Pick 3 proverbs and describe without their words.' },
];

const lesson = {
  title: '레벨 2 · 5과: 속담과 관용어 (Proverbs and Idioms)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'quoting', label: 'Quoting a proverb', goal: 'Use A-다더니/V-ㄴ다더니.' },
    { id: 'consoling', label: 'Consoling someone', goal: 'Use A/V-기 마련이다.' },
    { id: 'reflecting', label: 'Reflecting on growth', goal: 'Use V-다 보니까 to show how you have changed.' },
  ],
  relatedPools: ['topic-proverbs-idioms', 'pos-proverbs', 'pos-idioms'],
  content: [
    createContentItem('Lesson goal', 'proverbs + idioms', 'By end: use 10+ proverbs/idioms, console with grammar patterns, sound native.', 'word', 'Functions: quote · console · reflect · explain', 'Native-like fluency.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'consoling friend', 'A Korean friend failed an exam. They are devastated. You console with a proverb — Koreans love this.', 'word', 'Friend: 시험을 또 못 봤어. — You: 실수는 누구나 하기 마련이야. 다음에 잘하면 돼.', 'Friend: Failed again. — You: Everyone makes mistakes. Next time.', null, [ACT.orientation]),

    createContentItem('속담', 'sokdam', 'proverb', 'word', '한국 속담을 배워요.', 'I learn Korean proverbs.', null, [ACT.vocabulary]),
    createContentItem('관용어', 'gwanyongeo', 'idiomatic expression', 'word', '관용어가 어려워요.', 'Idioms are difficult.', null, [ACT.vocabulary]),
    createContentItem('가는 말이 고와야 오는 말이 곱다', 'ganeun mari gowaya', 'kind words attract kind words', 'word', '가는 말이 고와야 오는 말이 곱대요.', 'They say kind words bring kind words back.', null, [ACT.vocabulary]),
    createContentItem('티끌 모아 태산', 'tikkeul moa taesan', 'many a little makes a mountain', 'word', '티끌 모아 태산이라고 매일 저금해요.', 'Saving daily — many a little makes a mickle.', null, [ACT.vocabulary]),
    createContentItem('소 잃고 외양간 고친다', 'so ilko oeyanggan gochinda', 'shutting the stable after the horse has bolted', 'word', '소 잃고 외양간 고치지 마세요.', 'Do not lock the barn after the cow escapes.', null, [ACT.vocabulary]),
    createContentItem('호랑이도 제 말 하면 온다', 'horangido je mal hamyeon onda', 'speak of the devil', 'word', '호랑이도 제 말 하면 온다고, 마침 왔네요.', 'Speak of the devil — they just arrived.', null, [ACT.vocabulary]),
    createContentItem('실수는 누구나 한다', 'silsuneun nuguna handa', 'everyone makes mistakes', 'word', '실수는 누구나 하기 마련이에요.', 'Everyone is bound to make mistakes.', null, [ACT.vocabulary]),
    createContentItem('서당개 삼 년에 풍월을 읊다', 'seodanggae sam nyeone pungwoleul eupda', 'practice makes perfect (dog at a temple recites poems)', 'word', '서당개 삼 년이면 풍월을 읊는다고요.', 'Three years at the school dog recites poems.', null, [ACT.vocabulary]),
    createContentItem('백문이 불여일견', 'baengmuni buryeoilgyeon', 'seeing is believing', 'word', '백문이 불여일견이래요.', 'Seeing is better than hearing 100 times.', null, [ACT.vocabulary]),
    createContentItem('우물 안 개구리', 'umul an gaeguri', 'frog in a well (limited view)', 'word', '우물 안 개구리가 되면 안 돼요.', 'Do not become a frog in a well.', null, [ACT.vocabulary]),

    createContentItem('발이 넓다', 'bari neopda', 'know many people (wide feet)', 'word', '저 사람은 발이 넓어요.', 'They have wide social network.', null, [ACT.vocabulary]),
    createContentItem('눈이 높다', 'nuni nopda', 'have high standards (high eyes)', 'word', '눈이 너무 높아요.', 'Their standards are too high.', null, [ACT.vocabulary]),
    createContentItem('한 귀로 듣고 한 귀로 흘리다', 'han gwiro deutgo han gwiro heullida', 'in one ear and out the other', 'word', '엄마 말씀을 한 귀로 듣고 한 귀로 흘려요.', 'Mom\'s words: in one ear and out the other.', null, [ACT.vocabulary]),
    createContentItem('손이 크다', 'soni keuda', 'be generous (big hands)', 'word', '저희 어머니는 손이 커요.', 'My mother is generous.', null, [ACT.vocabulary]),
    createContentItem('입이 무겁다', 'ibi mugeopda', 'keep a secret (heavy mouth)', 'word', '입이 무거운 친구예요.', 'A friend who keeps secrets.', null, [ACT.vocabulary]),
    createContentItem('머리가 좋다', 'meoriga jota', 'be smart (good head)', 'word', '머리가 정말 좋아요.', 'Really smart.', null, [ACT.vocabulary]),
    createContentItem('닭', 'dak [닥]', 'chicken (ㄺ → ㄱ)', 'word', '닭고기를 먹어요.', 'I eat chicken.', null, [ACT.vocabulary]),
    createContentItem('삶', 'sam [삼]', 'life (ㄻ → ㅁ)', 'word', '건강한 삶이 중요해요.', 'A healthy life matters.', null, [ACT.vocabulary]),
    createContentItem('흙', 'heuk [흑]', 'soil / earth (ㄺ → ㄱ)', 'word', '흙이 부드러워요.', 'The soil is soft.', null, [ACT.vocabulary]),

    createContentItem('닭 → [닥]', 'dak', '겹받침 ㄺ → [ㄱ] before consonant; 연음 before vowel.', 'word', '닭고기 → [닥꼬기]', 'chicken meat.', null, [ACT.pronunciation]),
    createContentItem('삶 → [삼]', 'sam', '겹받침 ㄻ → [ㅁ].', 'word', '삶이 좋아요. → [사미 조아요]', 'Life is good.', null, [ACT.pronunciation]),
    createContentItem('흙 → [흑]', 'heuk', '겹받침 ㄺ → [ㄱ].', 'word', '흙을 만져요. → [흐글 만져요]', 'I touch the soil.', null, [ACT.pronunciation]),
    createContentItem('닭이 → [달기]', 'dalgi', '연음: ㄺ before vowel → ㄹ받침 + ㄱ jumps to next syllable.', 'word', '닭이 운다. → [달기 운다]', 'The chicken crows.', null, [ACT.pronunciation]),

    createContentItem('A/V-고 해서 — and so on', 'multiple reasons', 'Stack multiple reasons. The implied "and other things too".', 'sentence', '오늘 비도 오고 친구도 바쁘고 해서 그냥 집에 있어요.', 'It rained and my friend was busy and so on, so I just stayed home.',
      [{ korean: '~고 해서', english: '~ and so on' }, { korean: 'multiple clauses', english: 'verb1 + 고, verb2 + 고, 해서' }], [ACT.grammar]),
    createContentItem('A-다더니 / V-ㄴ다더니 — they said ~ and indeed', 'confirming hearsay', 'Quote what was said + present-evidence.', 'sentence', '여기 음식이 맛있다더니 진짜 맛있네요!', 'They said the food is tasty — it really is!',
      [{ korean: 'A-다더니', english: 'adjective' }, { korean: 'V-ㄴ다더니 / V-는다더니', english: 'verb' }], [ACT.grammar]),
    createContentItem('A/V-기 마련이다 — is bound to', 'inevitable', 'Console / state that something is natural / inevitable.', 'sentence', '실수는 누구나 하기 마련이에요.', 'Everyone is bound to make mistakes.',
      [{ korean: '~기 마련이다', english: 'inevitable / natural' }], [ACT.grammar]),
    createContentItem('V-다 보니(까) — having kept V-ing', 'gradual change', 'Express a change that happened over time from continued action.', 'sentence', '한국에 살다 보니까 김치를 좋아하게 됐어요.', 'Living in Korea, I came to like kimchi.',
      [{ korean: '~다 보니까', english: 'having continued V → result' }], [ACT.grammar]),

    createContentItem('Frustration with multiple reasons', 'speaking',
      'Use ~고 해서 to stack reasons.',
      'sentence', '오늘 비도 오고 머리도 아프고 해서 학교에 안 갔어요.',
      'It rained, I had a headache, and so on, so I did not go to school.',
      null, [ACT.speaking]),

    createContentItem('Personality with idioms', 'reading',
      'Read this description of a friend.',
      'sentence',
      '제 친구 민수는 정말 발이 넓어요. 어디를 가도 아는 사람이 있어요. 그리고 입도 무거워서 비밀을 잘 지켜요. 다만 가끔 한 귀로 듣고 한 귀로 흘리는 점이 있어요. 그래도 손이 커서 친구들에게 항상 후해요.',
      'My friend Minsu has wide social feet. Wherever he goes, he knows someone. He also has a heavy mouth, so he keeps secrets well. But sometimes he lets things go in one ear and out the other. Still, he is big-handed, so he is always generous.',
      [
        { korean: '발이 넓다', english: 'wide social network' },
        { korean: '입이 무겁다', english: 'keeps secrets' },
        { korean: '손이 크다', english: 'generous' },
      ],
      [ACT.readingSpeaking]),

    createContentItem('Consoling with a proverb', 'listening',
      'Friend bombed exam; you console.',
      'conversation',
      'A: 시험을 또 못 봤어. 어떻게 해.\nB: 너무 자책하지 마. 실수는 누구나 하기 마련이야.\nA: 그래도 매번 같은 실수를 해서 속상해.\nB: 가는 말이 고와야 오는 말이 곱다고, 자기 자신한테도 친절해야 해. 그리고 매일 공부하다 보니까 점점 늘 거야.\nA: 고마워. 네 말이 맞아.',
      'A: Failed again. B: Do not blame yourself. Everyone makes mistakes. A: Same mistake every time. B: They say kind words for kind words back — be kind to yourself too. Studying daily, you will improve. A: Thanks.',
      [
        { korean: '~기 마련이야', english: 'is bound to' },
        { korean: '~다고', english: 'they say (proverb-quoting)' },
        { korean: '~다 보니까', english: 'having continued ~' },
      ],
      [ACT.listeningSpeaking]),

    createContentItem('Article citing a proverb', 'reading + writing',
      'Sample article excerpt.',
      'sentence',
      '"티끌 모아 태산"이라는 한국 속담이 있어요. 매일 만 원씩 저금하다 보니까 1년에 360만 원이 됐어요. 작은 돈도 모이기 마련이라는 뜻이에요. 우리 모두 이 속담을 기억하면 좋겠어요.',
      'There is a Korean proverb "many a little makes a mickle". Saving 10,000 won daily, I had 3.6 million won in a year. It means even small money adds up. We should all remember this proverb.',
      [
        { korean: '~이라는 속담', english: 'a proverb called ~' },
        { korean: '~다 보니까', english: 'having continued ~' },
        { korean: '~기 마련이다', english: 'is bound to' },
      ],
      [ACT.readingWriting]),

    createContentItem('Animals in proverbs', 'culture',
      'Korean proverbs feature recurring characters: 호랑이 (tiger — power), 소 (cow/ox — slow, hard-working), 까마귀 (crow — bad omen, gossip), 까치 (magpie — good news), 닭 (chicken — common scenes). Each animal carries cultural meaning.',
      'sentence', '한국 속담에는 호랑이, 소, 닭 같은 동물이 많이 나와요.',
      'Korean proverbs feature animals like tiger, ox, chicken.',
      [
        { korean: '호랑이', english: 'tiger' },
        { korean: '소', english: 'ox' },
        { korean: '까치', english: 'magpie (good news)' },
        { korean: '까마귀', english: 'crow (bad omen)' },
        { korean: '닭', english: 'chicken' },
      ],
      [ACT.culture]),

    createContentItem('과제: Proverb pantomime', 'task',
      'Roleplay: Describe a proverb WITHOUT using its key words. The AI tutor guesses.',
      'conversation',
      'You: [describe without proverb words]\nTutor: [guesses]\nYou: 맞아요! / 아니에요. 다른 거예요.\nTutor: [guesses again]\nYou: 정답! 이 속담의 뜻은 ~ 이에요.',
      'AI tutor will play the guesser.',
      [
        { korean: '~ 다 보니까', english: 'over time' },
        { korean: '~ 기 마련이에요', english: 'is bound to' },
        { korean: '~다더니', english: 'they said and indeed' },
        { korean: '~고 해서', english: 'and so on' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
