// Level 1 Unit 7 — Going places (now & later)
// Sources: Book 1A·8 (지금 어디에 가?) + Book 1B·10 (가족과 놀이공원에 갈 거예요)
// Functions: stating destination, expressing purpose, future plans.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u7-orientation',
  pronunciation: 'l1u7-pronunciation',
  vocabularyDestinations: 'l1u7-vocab-dest',
  vocabularyCompanions: 'l1u7-vocab-comp',
  grammarPurpose: 'l1u7-grammar-purpose',
  grammarFuture: 'l1u7-grammar-future',
  grammarParticles: 'l1u7-grammar-particles',
  reading: 'l1u7-reading',
  listening: 'l1u7-listening',
  writing: 'l1u7-writing',
  culture: 'l1u7-culture',
  task: 'l1u7-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['State where you are going and WHY.', 'Express future plans with V-(으)ㄹ 거예요.', 'Talk about who you are going with.'],
    task: 'Imagine a friend asks "where are you going?" — you should be able to say where, why, with whom, and when.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Future-tense and purpose sounds',
    goals: ['Pronounce ㄹ + ㄱ → 갈 거예요 → [갈꺼예요] (tensification).', 'Apply 연음 in 읽으러 → [일그러].'],
    task: 'Read each example aloud.' },
  { id: ACT.vocabularyDestinations, section: 'Vocabulary I', title: 'Destinations',
    goals: ['Name 12+ places people commonly go.'],
    task: 'List the five places you go most often.' },
  { id: ACT.vocabularyCompanions, section: 'Vocabulary II', title: 'Companions & purposes',
    goals: ['Use 가족·친구·동료·혼자.', 'Use purpose verbs: 만나다·먹다·사다·보다·공부하다·운동하다.'],
    task: 'Pair a place with a purpose verb for three different errands.' },
  { id: ACT.grammarPurpose, section: 'Grammar I', title: 'V-(으)러 가다 — go in order to V',
    goals: ['Attach -러 (after vowel/ㄹ) or -으러 (after consonant) to a verb stem.', 'Chain: PURPOSE + (으)러 + DESTINATION에 + 가다/오다.'],
    task: 'Make three purpose sentences: "I go to [place] to [verb]."' },
  { id: ACT.grammarFuture, section: 'Grammar II', title: 'V-(으)ㄹ 거예요 — will V (future/intent)',
    goals: ['Attach -ㄹ (after vowel) or -을 (after consonant) + 거예요.', 'Use for plans, intentions, predictions.'],
    task: 'Make three sentences about what you will do this weekend.' },
  { id: ACT.grammarParticles, section: 'Grammar III', title: '에 vs 에서 + 와/과/하고 (companion)',
    goals: ['Use 에 for destination (with 가다/오다).', 'Use 에서 for location of action.', 'Use N과/와/하고 to mean "with N".'],
    task: 'Make one sentence each using 에, 에서, 하고.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A busy Saturday',
    goals: ['Read a 5-stop weekend itinerary.'],
    task: 'Identify where the writer goes, why, and with whom.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Where are you off to?',
    goals: ['Follow two short "where are you going" dialogues.'],
    task: 'Reproduce one dialogue with your own plan.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — My weekend plan',
    goals: ['Write 4-5 sentences about an upcoming weekend.'],
    task: 'Write your own weekend plan using future tense and purpose.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Lotte World, Everland, and Saturday culture',
    goals: ['Know the two big Korean theme parks.', 'Understand the weekend rhythm (family / friends / 동아리).'],
    task: 'Describe one Korean weekend destination you would like to visit.' },
  { id: ACT.task, section: 'Task', title: '과제 — Share your weekend plan',
    goals: ['Combine destination, purpose, companion, and future tense in one scene.'],
    task: 'Roleplay sharing your weekend plan and inviting the AI tutor along.' },
];

const lesson = {
  title: '레벨 1 · 7과: 가족과 놀이공원에 갈 거예요 (Going Places)',
  category: 'travel',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-where-going', label: 'Asking where someone is going', goal: 'Use 어디에 가요? to ask about a destination.' },
    { id: 'stating-future-plan', label: 'Stating a future plan', goal: 'Use V-(으)ㄹ 거예요 to share a near-future plan.' },
    { id: 'expressing-purpose', label: 'Expressing purpose', goal: 'Use V-(으)러 가다 to say why you are going.' },
    { id: 'inviting-companion', label: 'Inviting someone along', goal: 'Use 같이 갈래요? to invite someone.' },
  ],
  relatedPools: ['topic-people', 'topic-society'],
  content: [
    createContentItem('Lesson goal', 'going somewhere', 'By end: state where, why, with whom you are going + use future tense V-(으)ㄹ 거예요.', 'word', 'Functions: destination · purpose · companion · future', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Saturday morning', 'A classmate sees you with a backpack and asks where you are off to.', 'word', 'Classmate: 어디에 가요? — You: 친구를 만나러 카페에 가요.', 'Classmate: Where are you going? — You: I am going to the cafe to meet a friend.', null, [ACT.orientation]),

    createContentItem('갈 거예요 → [갈꺼예요]', 'gal kkeoyeyo', 'ㄹ + ㄱ → tensification: the ㄱ of 거 becomes ㄲ.', 'word', '주말에 갈 거예요. → [갈꺼예요]', 'I will go on the weekend.', null, [ACT.pronunciation]),
    createContentItem('읽으러 → [일그러]', 'ilgeureo', '연음 of the ㄺ cluster: ㄱ jumps to the next syllable.', 'word', '책을 읽으러 가요. → [일그러 가요]', 'I am going to read a book.', null, [ACT.pronunciation]),
    createContentItem('학교에 → [학꾜에]', 'hakkyoe', '경음화: ㄱ받침 + ㄱ → ㄱ + ㄲ.', 'word', '학교에 가요. → [학꾜에 가요]', 'I go to school.', null, [ACT.pronunciation]),
    createContentItem('놀이공원 → [노리공원]', 'norigongwon', '연음: ㄹ받침 of 놀 jumps to 이.', 'word', '놀이공원에 가요. → [노리공워네 가요]', 'I am going to the amusement park.', null, [ACT.pronunciation]),

    createContentItem('가다', 'gada', 'to go', 'word', '학교에 가요.', 'I go to school.', null, [ACT.vocabularyDestinations]),
    createContentItem('오다', 'oda', 'to come', 'word', '친구가 한국에 와요.', 'My friend comes to Korea.', null, [ACT.vocabularyDestinations]),
    createContentItem('놀이공원', 'noligongwon', 'amusement park', 'word', '주말에 놀이공원에 갈 거예요.', 'I will go to the amusement park.', null, [ACT.vocabularyDestinations]),
    createContentItem('공원', 'gongwon', 'park', 'word', '공원에서 산책해요.', 'I take walks in the park.', null, [ACT.vocabularyDestinations]),
    createContentItem('백화점', 'baekhwajeom', 'department store', 'word', '백화점에 옷을 사러 가요.', 'I go to the department store to buy clothes.', null, [ACT.vocabularyDestinations]),
    createContentItem('영화관', 'yeonghwagwan', 'movie theater', 'word', '영화관에서 영화를 봐요.', 'I watch movies at the theater.', null, [ACT.vocabularyDestinations]),
    createContentItem('카페', 'kape', 'cafe', 'word', '친구하고 카페에 가요.', 'I go to a cafe with my friend.', null, [ACT.vocabularyDestinations]),
    createContentItem('서점', 'seojeom', 'bookstore', 'word', '서점에서 책을 사요.', 'I buy books at the bookstore.', null, [ACT.vocabularyDestinations]),
    createContentItem('병원', 'byeongwon', 'hospital / clinic', 'word', '병원에 가요.', 'I am going to the hospital.', null, [ACT.vocabularyDestinations]),
    createContentItem('시장', 'sijang', 'market', 'word', '시장에서 과일을 사요.', 'I buy fruit at the market.', null, [ACT.vocabularyDestinations]),
    createContentItem('체육관', 'cheyukgwan', 'gym', 'word', '체육관에 운동하러 가요.', 'I go to the gym to exercise.', null, [ACT.vocabularyDestinations]),
    createContentItem('식당', 'sikdang', 'restaurant', 'word', '식당에서 점심을 먹어요.', 'I eat lunch at a restaurant.', null, [ACT.vocabularyDestinations]),
    createContentItem('도서관', 'doseogwan', 'library', 'word', '도서관에 책을 읽으러 가요.', 'I go to the library to read.', null, [ACT.vocabularyDestinations]),
    createContentItem('박물관', 'bangmulgwan', 'museum', 'word', '박물관에 가요.', 'I am going to the museum.', null, [ACT.vocabularyDestinations]),

    createContentItem('가족', 'gajok', 'family', 'word', '가족과 같이 가요.', 'I am going with my family.', null, [ACT.vocabularyCompanions]),
    createContentItem('친구', 'chingu', 'friend', 'word', '친구하고 만나요.', 'I am meeting a friend.', null, [ACT.vocabularyCompanions]),
    createContentItem('동료', 'dongryo', 'coworker / colleague', 'word', '동료와 같이 가요.', 'I am going with a coworker.', null, [ACT.vocabularyCompanions]),
    createContentItem('혼자', 'honja', 'alone', 'word', '오늘은 혼자 영화를 봐요.', 'Today I am watching a movie alone.', null, [ACT.vocabularyCompanions]),
    createContentItem('같이', 'gachi', 'together', 'word', '같이 갈래요?', 'Shall we go together?', null, [ACT.vocabularyCompanions]),
    createContentItem('만나다', 'mannada', 'to meet', 'word', '친구를 만나러 가요.', 'I am going to meet a friend.', null, [ACT.vocabularyCompanions]),
    createContentItem('사다', 'sada', 'to buy', 'word', '옷을 사러 가요.', 'I am going to buy clothes.', null, [ACT.vocabularyCompanions]),
    createContentItem('먹다', 'meokda', 'to eat', 'word', '점심을 먹으러 가요.', 'I am going to eat lunch.', null, [ACT.vocabularyCompanions]),
    createContentItem('보다', 'boda', 'to see / watch', 'word', '영화를 보러 가요.', 'I am going to watch a movie.', null, [ACT.vocabularyCompanions]),

    createContentItem('V-(으)러 가다 — purpose of going', '-(eu)reo gada', 'Attach -러 (after vowel/ㄹ) or -으러 (after consonant) to a verb stem.', 'sentence', '책을 읽으러 도서관에 가요.', 'I go to the library to read a book.',
      [
        { korean: '읽 + 으러', english: '읽 ends in consonant → 으러' },
        { korean: '만나 + 러', english: '만나 ends in vowel → 러' },
        { korean: '도서관에 가요', english: 'destination + verb of motion' },
      ],
      [ACT.grammarPurpose]),
    createContentItem('Word order tips', 'flexible', 'Korean is flexible — both orders work: [PURPOSE + (으)러] [DEST + 에] [V] OR [DEST + 에] [PURPOSE + (으)러] [V].', 'sentence', '도서관에 책을 읽으러 가요. = 책을 읽으러 도서관에 가요.', 'Both correct.', null, [ACT.grammarPurpose]),
    createContentItem('Only with motion verbs', 'rule', '-(으)러 is ONLY used with 가다, 오다, 다니다 (going/coming verbs). For other purposes, use -(으)려고.', 'sentence', '커피를 마시러 카페에 가요. (movement) vs 커피를 마시려고 일찍 일어났어요. (any verb)', 'Different connector for non-motion.', null, [ACT.grammarPurpose]),

    createContentItem('V-(으)ㄹ 거예요 — future / will V', '-(eu)l geoyeyo', 'Attach -ㄹ (after vowel) or -을 (after consonant) + 거예요.', 'sentence', '주말에 친구를 만날 거예요.', 'I will meet a friend this weekend.',
      [
        { korean: '만나 + ㄹ + 거예요', english: '만나 (vowel) → 만날 거예요' },
        { korean: '먹 + 을 + 거예요', english: '먹 (consonant) → 먹을 거예요' },
        { korean: '하 + ㄹ + 거예요', english: '하 (vowel) → 할 거예요' },
      ],
      [ACT.grammarFuture]),
    createContentItem('Three uses of V-(으)ㄹ 거예요', 'meaning', 'Use for: (1) plans, (2) intentions, (3) predictions about the speaker or 3rd person.', 'sentence', '내일 비가 올 거예요. (prediction) · 내일 친구를 만날 거예요. (plan)', 'Same form, multiple uses.', null, [ACT.grammarFuture]),
    createContentItem('Question form', 'rising tone', 'No new ending — same form, rising intonation: 뭐 할 거예요?', 'sentence', '주말에 뭐 할 거예요? — 영화 볼 거예요.', 'What will you do? — I will see a movie.', null, [ACT.grammarFuture]),

    createContentItem('에 vs 에서', 'destination vs location', '에 = destination (with go/come). 에서 = location of action (eat/study/work AT).', 'sentence', '학교에 가요 (going TO) vs 학교에서 공부해요 (studying AT).', 'Different particle, different meaning.', null, [ACT.grammarParticles]),
    createContentItem('와/과/하고 — "with"', 'gwa/wa/hago', '와 after vowel, 과 after consonant. 하고 works for both (everyday).', 'sentence', '친구와 가요. = 친구하고 가요.', 'with a friend.',
      [{ korean: '친구 + 와', english: '친구 (vowel) → 와' }, { korean: '동생 + 과', english: '동생 (consonant) → 과' }, { korean: '하고', english: 'works for both, casual' }], [ACT.grammarParticles]),
    createContentItem('같이 — together', 'gachi', 'Often paired with 와/과/하고 for emphasis: "go together with".', 'sentence', '가족과 같이 갈 거예요.', 'I will go together with my family.',
      null, [ACT.grammarParticles]),

    createContentItem('A busy Saturday', 'reading',
      'Read aloud and note where the writer goes and why.',
      'sentence',
      '이번 토요일은 정말 바빠요. 아침에 친구를 만나러 카페에 가요. 점심에 가족과 같이 식당에서 밥을 먹을 거예요. 오후에는 옷을 사러 백화점에 갈 거예요. 저녁에는 동생하고 영화관에서 영화를 볼 거예요. 일요일은 도서관에서 공부할 거예요.',
      'This Saturday is really busy. In the morning I am going to the cafe to meet a friend. At lunch I will eat at a restaurant with my family. In the afternoon I will go to the department store to buy clothes. In the evening I will watch a movie at the theater with my sibling. On Sunday I will study at the library.',
      [
        { korean: '친구를 만나러 카페에', english: 'to the cafe to meet a friend (purpose)' },
        { korean: '가족과 같이 식당에서', english: 'at the restaurant with family' },
        { korean: '옷을 사러 백화점에', english: 'to the department store to buy clothes' },
        { korean: '동생하고 영화관에서', english: 'at the theater with my sibling' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'answer in Korean',
      'Use future tense and purpose forms.',
      'sentence',
      'Q1: 아침에 어디에 가요? · Q2: 점심에 누구와 같이 먹어요? · Q3: 일요일에 뭐 할 거예요?',
      'Q1: Where does she go in the morning? Q2: Whom is she eating with at lunch? Q3: What will she do on Sunday?',
      [
        { korean: 'A1: 카페에 가요. 친구를 만나러 가요.', english: 'A cafe. To meet a friend.' },
        { korean: 'A2: 가족과 같이 먹어요.', english: 'With her family.' },
        { korean: 'A3: 도서관에서 공부할 거예요.', english: 'She will study at the library.' },
      ],
      [ACT.reading]),

    createContentItem('Where are you going?', 'listening',
      'Two classmates run into each other.',
      'conversation',
      'A: 지금 어디에 가요?\nB: 카페에 커피를 마시러 가요. 같이 갈래요?\nA: 좋아요. 저도 커피 마시고 싶어요.\nB: 그럼 학교 앞 카페로 가요.\nA: 학교 앞에 새 카페가 생겼어요?\nB: 네, 지난주에 생겼어요. 한번 가 봐요.',
      'A: Where are you going right now?\nB: To the cafe to drink coffee. Want to come?\nA: Sure, I want coffee too.\nB: Then let us go to the cafe in front of school.\nA: A new cafe opened in front of school?\nB: Yes, last week. Let us try it.',
      [
        { korean: '같이 갈래요?', english: 'shall we go together?' },
        { korean: '새 카페가 생겼어요', english: 'a new cafe has opened' },
        { korean: '한번 가 봐요', english: 'let us try going' },
      ],
      [ACT.listening]),
    createContentItem('Weekend plans', 'listening',
      'Two friends compare weekends.',
      'conversation',
      'A: 주말에 뭐 할 거예요?\nB: 가족과 놀이공원에 갈 거예요. 사라 씨는요?\nA: 저는 친구하고 영화를 볼 거예요.\nB: 무슨 영화요?\nA: 한국 영화요. 재미있을 것 같아요.\nB: 좋네요. 영화 끝나고 카페에 와요. 우리도 그쪽으로 갈게요.\nA: 좋아요!',
      'A: What will you do on the weekend? B: I will go to the amusement park with my family. And you? A: I will watch a movie with a friend. B: What movie? A: A Korean movie. Looks fun. B: Nice. Come to the cafe after the movie. We will come over too. A: Great!',
      [
        { korean: '주말에 뭐 할 거예요?', english: 'what will you do?' },
        { korean: '영화 끝나고', english: 'after the movie' },
        { korean: '그쪽으로', english: 'over to that side' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'template',
      'Use this to structure your weekend plan.',
      'sentence',
      '이번 주말에 [요일]에 [장소]에 [목적]으러/러 갈 거예요. [동행자]하고 같이 가요. [동사]거나 [동사]을/를 거예요. 일요일에는 [장소]에서 [동사]할 거예요.',
      '[day] · [place] · [purpose] · [companion] · [activity] · [Sunday plan]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 sentences about your real upcoming weekend. Use 갈 거예요, V-(으)러 가다, and one companion phrase (-하고 같이).',
      'sentence', 'Example: 이번 토요일에 친구하고 같이 카페에 갈 거예요. 카페에서 커피를 마시고 한국어를 공부할 거예요. 저녁에는 영화관에 영화를 보러 갈 거예요.',
      'Example: This Saturday I will go to a cafe with a friend. We will drink coffee and study Korean. In the evening we will go to the cinema to watch a movie.',
      null, [ACT.writing]),

    createContentItem('Lotte World & Everland', 'culture',
      'Korea\'s two iconic amusement parks: 롯데월드 (Lotte World — indoor + outdoor, in Seoul) and 에버랜드 (Everland — Korea\'s largest, in Gyeonggi). Both are typical first-weekend destinations for couples and families.',
      'sentence', '주말에 가족과 같이 에버랜드에 갈 거예요.', 'I will go to Everland with my family on the weekend.',
      [{ korean: '롯데월드', english: 'Lotte World — Seoul' }, { korean: '에버랜드', english: 'Everland — Gyeonggi-do' }], [ACT.culture]),
    createContentItem('The weekend rhythm', 'culture',
      'Korean students typically split the weekend: Saturday = friends / 동아리 / dates, Sunday = family / 교회 / rest. Many also use weekends to study at 카페 or 도서관.',
      'sentence', '한국 대학생들은 보통 토요일에 친구를 만나고 일요일에 가족과 시간을 보내요.', 'Korean students usually meet friends on Saturday and spend Sunday with family.',
      null, [ACT.culture]),

    createContentItem('과제: Share your weekend plan', 'task',
      'Roleplay: A Korean friend asks about your weekend. Tell them where, why, with whom, and invite them along.',
      'conversation',
      'Friend: 주말에 뭐 할 거예요?\nYou: [destination + purpose + companion]\nFriend: 와, 재미있겠네요. 몇 시에 가요?\nYou: [time + invite]\nFriend: 좋아요. 같이 가요!',
      'AI tutor will play the friend.',
      [
        { korean: '주말에 ~할 거예요', english: 'I will ~ on the weekend' },
        { korean: '~을/를 ~ 러 ~에 가요', english: 'I am going to ~ to do ~' },
        { korean: '같이 갈래요?', english: 'shall we go together?' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
