// Level 2 Track-Adult Unit 2 — 저는 9시에 출근해요 (Work schedule)
// Source: Book 2A·2.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au2-orientation',
  pronunciation: 'l2au2-pronunciation',
  vocabularyShift: 'l2au2-vocab-shift',
  vocabularyTime: 'l2au2-vocab-time',
  grammarSchedule: 'l2au2-grammar-schedule',
  grammarFromTo: 'l2au2-grammar-from-to',
  reading: 'l2au2-reading',
  listening: 'l2au2-listening',
  writing: 'l2au2-writing',
  culture: 'l2au2-culture',
  task: 'l2au2-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['State your work hours, shift type, and breaks formally.', 'Ask a coworker about their schedule.', 'Handle shift-swap requests.'],
    task: 'Imagine being asked to switch a Saturday shift — you must understand and respond formally.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Time + 합니다',
    goals: ['Apply 비음화 in 합니다 → [함니다].', 'Apply 경음화 in 부터 → [부터] (no change).'],
    task: 'Read each schedule sentence.' },
  { id: ACT.vocabularyShift, section: 'Vocabulary I', title: 'Shift + schedule words',
    goals: ['Use 출근·퇴근·근무·야근·교대·휴일·아침/야간 근무.'],
    task: 'Describe a typical workday.' },
  { id: ACT.vocabularyTime, section: 'Vocabulary II', title: 'Time + workplace nouns',
    goals: ['Use 점심 시간·휴게실·지각·조퇴·연차.'],
    task: 'Use 5 schedule-related words.' },
  { id: ACT.grammarSchedule, section: 'Grammar I', title: 'Time + 에 + V-ㅂ/습니다',
    goals: ['Use 에 with times in formal speech.', 'Chain with -고 for sequence.'],
    task: 'State morning + afternoon actions.' },
  { id: ACT.grammarFromTo, section: 'Grammar II', title: 'N부터 N까지 — from N to N',
    goals: ['Mark shift hours, days, periods.', 'Difference from 에서 ~ 까지 (location).'],
    task: 'Define your shift in 2 ways.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Shift schedule notice',
    goals: ['Read a posted shift schedule.'],
    task: 'Answer who works when.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Schedule chat',
    goals: ['Follow a coworker schedule dialogue.'],
    task: 'Reproduce with your own shift.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Schedule request email',
    goals: ['Write a 3-4 line email requesting a shift swap.'],
    task: 'Write your own request.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean overtime culture',
    goals: ['Understand 야근 culture and recent 워라밸 push.', 'Know 주 52시간 (52-hour workweek law).'],
    task: 'Compare with your country.' },
  { id: ACT.task, section: 'Task', title: '과제 — Shift swap request',
    goals: ['Roleplay requesting a swap.'],
    task: 'Request a Saturday-to-Sunday swap.' },
];

const lesson = {
  title: '레벨 2 (직장) · 2과: 저는 9시에 출근합니다 (Work Schedule)',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'stating-schedule', label: 'Stating schedule', goal: 'Use time + 에 + 출근/퇴근합니다.' },
    { id: 'asking-shift', label: 'Asking about shift', goal: 'Use 몇 시부터 / 무슨 요일 to ask.' },
    { id: 'requesting-swap', label: 'Requesting a swap', goal: 'Use 부탁 + 바꿔 주시면 감사하겠습니다.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: state shift formally, ask coworker schedule, request shift swap.', 'word', 'Functions: state · ask · negotiate · swap', 'Schedule toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'A coworker asks you to swap Saturday for Sunday. You must understand their shift, agree/decline, propose details.', 'word', 'Coworker: 토요일에 바꿔 주실 수 있습니까? — You: 일요일은 가능합니다.', 'Coworker: Can you swap? — You: Sunday works.', null, [ACT.orientation]),

    createContentItem('출근합니다 → [출근함니다]', 'chulgeunhamnida', '비음화: ㅂ받침 + ㄴ → ㅁ + ㄴ.', 'word', '8시에 출근합니다.', 'I clock in at 8.', null, [ACT.pronunciation]),
    createContentItem('퇴근합니다 → [퇴근함니다]', 'toegeunhamnida', 'Same 비음화.', 'word', '6시에 퇴근합니다.', 'I leave at 6.', null, [ACT.pronunciation]),
    createContentItem('야근 → [야근]', 'yageun', 'No change. Clear ㄴ받침.', 'word', '오늘 야근합니다.', 'Overtime today.', null, [ACT.pronunciation]),
    createContentItem('근무 → [근무]', 'geunmu', 'No change.', 'word', '근무 시간', 'Work hours.', null, [ACT.pronunciation]),

    createContentItem('출근', 'chulgeun', 'going to work', 'word', '출근 시간이 8시입니다.', 'Clock-in is 8.', null, [ACT.vocabularyShift]),
    createContentItem('퇴근', 'toegeun', 'leaving work', 'word', '6시에 퇴근합니다.', 'Leave at 6.', null, [ACT.vocabularyShift]),
    createContentItem('근무', 'geunmu', 'work duty / shift', 'word', '야간 근무입니다.', 'Night shift.', null, [ACT.vocabularyShift]),
    createContentItem('야근', 'yageun', 'overtime', 'word', '오늘 야근합니다.', 'I work overtime today.', null, [ACT.vocabularyShift]),
    createContentItem('교대', 'gyodae', 'shift change', 'word', '교대 근무가 힘듭니다.', 'Shift work is hard.', null, [ACT.vocabularyShift]),
    createContentItem('아침 근무', 'achim geunmu', 'morning shift', 'word', '저는 아침 근무입니다.', 'I am on morning shift.', null, [ACT.vocabularyShift]),
    createContentItem('야간 근무', 'yagan geunmu', 'night shift', 'word', '야간 근무는 어렵습니다.', 'Night shift is hard.', null, [ACT.vocabularyShift]),
    createContentItem('주말 근무', 'jumal geunmu', 'weekend shift', 'word', '주말 근무도 있습니다.', 'There are weekend shifts.', null, [ACT.vocabularyShift]),
    createContentItem('휴일', 'hyuil', 'day off', 'word', '일요일은 휴일입니다.', 'Sunday is off.', null, [ACT.vocabularyShift]),
    createContentItem('연차', 'yeoncha', 'annual leave', 'word', '연차를 신청합니다.', 'I apply for leave.', null, [ACT.vocabularyShift]),

    createContentItem('점심 시간', 'jeomsim sigan', 'lunch break', 'word', '점심 시간은 12시부터 1시까지입니다.', 'Lunch is 12-1.', null, [ACT.vocabularyTime]),
    createContentItem('휴게실', 'hyugesil', 'break room', 'word', '휴게실에서 쉬세요.', 'Rest in break room.', null, [ACT.vocabularyTime]),
    createContentItem('지각', 'jigak', 'being late', 'word', '지각하면 안 됩니다.', 'Do not be late.', null, [ACT.vocabularyTime]),
    createContentItem('조퇴', 'jotoe', 'leaving early', 'word', '몸이 안 좋아서 조퇴합니다.', 'Leaving early because unwell.', null, [ACT.vocabularyTime]),
    createContentItem('출장', 'chuljang', 'business trip', 'word', '내일 출장입니다.', 'Business trip tomorrow.', null, [ACT.vocabularyTime]),
    createContentItem('회의 시간', 'hoeui sigan', 'meeting time', 'word', '회의 시간은 10시입니다.', 'Meeting is at 10.', null, [ACT.vocabularyTime]),
    createContentItem('주 52시간', 'ju 52 sigan', '52-hour workweek (law)', 'word', '주 52시간 근무제예요.', 'The 52-hour workweek system.', null, [ACT.vocabularyTime]),
    createContentItem('월요일~금요일', 'wol~geum', 'Mon-Fri (weekdays)', 'word', '월요일부터 금요일까지 일합니다.', 'I work Mon-Fri.', null, [ACT.vocabularyTime]),

    createContentItem('Time + 에 + V-ㅂ/습니다', 'time-action formal', '시 + 에 + verb in formal speech.', 'sentence', '저는 9시에 출근합니다.', 'I clock in at 9.',
      [{ korean: '9시에', english: 'at 9' }, { korean: '출근합니다', english: 'clock in (formal)' }], [ACT.grammarSchedule]),
    createContentItem('Chain with -고', 'and then', 'Connect two formal actions with -고. Tense only on last verb.', 'sentence', '9시에 출근하고 6시에 퇴근합니다.', 'I clock in at 9 and clock out at 6.',
      null, [ACT.grammarSchedule]),

    createContentItem('N부터 N까지 — from N to N', 'time / range', 'Mark time or sequence ranges.', 'sentence', '8시부터 5시까지 근무합니다.', 'I work 8 to 5.',
      [{ korean: '8시부터', english: 'from 8' }, { korean: '5시까지', english: 'until 5' }, { korean: '월요일부터 금요일까지', english: 'Mon-Fri' }], [ACT.grammarFromTo]),
    createContentItem('vs 에서 ~ 까지', 'time vs location', 'N부터 N까지 = time/sequence. N에서 N까지 = location.', 'sentence', '집에서 회사까지 1시간 (location) · 9시부터 5시까지 (time)', 'Different particles.',
      null, [ACT.grammarFromTo]),

    createContentItem('Shift schedule notice', 'reading',
      'Read this posted schedule.',
      'sentence',
      '근무 일정 안내\n· 김민수 사원: 월~금 09:00~18:00 (아침 근무) / 휴일: 토일\n· 박지영 사원: 화~토 14:00~23:00 (야간 근무) / 휴일: 일월\n· 점심 시간: 12:00~13:00\n· 회의 시간: 매주 화요일 10시',
      'Shift Schedule:\n- Kim Minsu: Mon-Fri 9-6 morning / off Sat-Sun\n- Park Jiyoung: Tue-Sat 2 PM-11 PM night / off Sun-Mon\n- Lunch break: 12-1\n- Meetings: every Tuesday 10 AM',
      [
        { korean: '근무 일정', english: 'work schedule' },
        { korean: '~부터 ~까지', english: 'from ~ to ~' },
      ],
      [ACT.reading]),

    createContentItem('Schedule chat', 'listening',
      'Coworkers discuss schedules.',
      'conversation',
      'A: 사라 씨, 내일 출근 시간이 어떻게 됩니까?\nB: 아침 근무라서 7시에 출근합니다. 4시에 퇴근합니다.\nA: 토요일에는 일하십니까?\nB: 토요일은 휴일입니다. 일요일에 야간 근무를 합니다.\nA: 야근이 많이 힘드시지요?\nB: 처음에는 힘들었는데 지금은 익숙해졌습니다.\nA: 다음 주 토요일에 근무 좀 바꿔 주실 수 있을까요?',
      'A: Sarah, your hours tomorrow? B: Morning shift — 7 in, 4 out. A: Saturdays? B: Off Sat. Night shift Sun. A: Night shifts must be tough? B: Hard at first, used to it now. A: Could we swap next Saturday?',
      [
        { korean: '~ 어떻게 됩니까?', english: 'how is ~?' },
        { korean: '익숙해지다', english: 'get used to' },
        { korean: '바꿔 주실 수 있을까요?', english: 'could you swap?' },
      ],
      [ACT.listening]),

    createContentItem('Shift swap email', 'writing',
      'Sample request email.',
      'sentence',
      '안녕하십니까. 김민수입니다. 다음 주 토요일에 개인 사정이 있어서 근무를 못 합니다. 혹시 박지영 사원과 일요일로 바꿔 주실 수 있을까요? 미리 양해 부탁드립니다. 감사합니다.',
      'Hello. Kim Minsu. I have a personal matter next Saturday and cannot work. Could we swap with Park Jiyoung for Sunday? Please understand in advance. Thanks.',
      null, [ACT.writing]),

    createContentItem('Korean overtime culture', 'culture',
      'Historically Korean workers did massive overtime (야근). Since 2018 the 주 52시간 (52-hour workweek) law caps weekly hours. Younger workers push 워라밸 (work-life balance) — 칼퇴 (leaving on time) is now a positive value, not laziness. But many SMEs still pressure overtime.',
      'sentence', '한국은 주 52시간 근무제를 시행하고 있어요.',
      'Korea enforces the 52-hour workweek.',
      [
        { korean: '주 52시간', english: '52-hour workweek' },
        { korean: '워라밸', english: 'work-life balance' },
        { korean: '칼퇴', english: 'leaving on time' },
      ],
      [ACT.culture]),

    createContentItem('과제: Shift swap', 'task',
      'Roleplay: Request a shift swap formally.',
      'conversation',
      'You: 안녕하십니까. ~ 사정으로 ~ 근무를 못 합니다.\nCoworker: 무슨 일이세요?\nYou: [reason]\nCoworker: 그럼 ~ 어떻습니까?\nYou: [accept or counter]\nCoworker: 알겠습니다.',
      'AI tutor will play the coworker.',
      [
        { korean: '~ 부터 ~ 까지', english: 'from to' },
        { korean: '~ 못 합니다', english: 'cannot' },
        { korean: '바꿔 주시면 감사하겠습니다', english: 'please swap' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
