// Level 1 Unit 13 — Transportation
// Source: Book 1B·11 (터미널에 어떻게 가요?)
// Functions: asking how to get somewhere, naming transport, taking bus/subway.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u13-orientation',
  pronunciation: 'l1u13-pronunciation',
  vocabularyModes: 'l1u13-vocab-modes',
  vocabularyVerbs: 'l1u13-vocab-verbs',
  grammarHow: 'l1u13-grammar-how',
  grammarMeans: 'l1u13-grammar-means',
  grammarRoute: 'l1u13-grammar-route',
  reading: 'l1u13-reading',
  listening: 'l1u13-listening',
  writing: 'l1u13-writing',
  culture: 'l1u13-culture',
  task: 'l1u13-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Ask how to get anywhere.', 'State which transport you take.', 'Describe routes with from-to + duration + transfer.'],
    task: 'Imagine asking how to get from Kumoh to Seoul — you need to ask, listen, and confirm.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Transport phrases',
    goals: ['Apply 비음화 in 어떻게 → [어떠케], 갔어요 → [가써요].'],
    task: 'Read each phrase aloud.' },
  { id: ACT.vocabularyModes, section: 'Vocabulary I', title: 'Transport modes & stops',
    goals: ['Name 8+ transport modes.', 'Use 정류장·역·공항·터미널.'],
    task: 'List two modes you use weekly.' },
  { id: ACT.vocabularyVerbs, section: 'Vocabulary II', title: 'Transport verbs',
    goals: ['Use 타다·내리다·갈아타다·걸리다·걷다·도착하다·출발하다.'],
    task: 'Pair a verb with a transport mode.' },
  { id: ACT.grammarHow, section: 'Grammar I', title: '~에 어떻게 가요? — How do I get to ~?',
    goals: ['Ask the route to a place.', 'Reply with means + duration + transfer.'],
    task: 'Ask and answer 3 routes.' },
  { id: ACT.grammarMeans, section: 'Grammar II', title: 'N(으)로 — by means of N',
    goals: ['Use 으로 (after consonant), 로 (after vowel/ㄹ) to mark transport.', 'Use 걸어서 for "on foot" (exception).'],
    task: 'State how you go to three places.' },
  { id: ACT.grammarRoute, section: 'Grammar III', title: 'N에서 N까지 + 얼마나 걸려요? + 갈아타다',
    goals: ['Use 에서 ~ 까지 for "from-to".', 'Ask 얼마나 걸려요? and read durations.', 'Describe transfers with 에서 + 으로 갈아타다.'],
    task: 'Plan a 2-leg journey.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A commute description',
    goals: ['Read a 4-sentence commute paragraph.'],
    task: 'Identify mode, route, duration.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Asking + confirming directions',
    goals: ['Follow two directions dialogues.'],
    task: 'Reproduce with your real destination.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Describe your commute',
    goals: ['Write 3-5 sentences describing how you get to school/work.'],
    task: 'Write your own commute.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — T-money, KTX, and Korean transit',
    goals: ['Know that 티머니카드 works on bus + subway + taxi.', 'Know KTX, ITX, SRT differences.'],
    task: 'Pick the best transport for a Seoul-to-Busan trip.' },
  { id: ACT.task, section: 'Task', title: '과제 — Plan a trip to Seoul',
    goals: ['Combine route, means, duration, transfer in one continuous task.'],
    task: 'Plan how to get from Gumi to Seoul with the AI tutor.' },
];

const lesson = {
  title: '레벨 1 · 13과: 터미널에 어떻게 가요? (Transportation)',
  category: 'travel',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-how-to-get', label: 'Asking how to get somewhere', goal: 'Use ~에 어떻게 가요? to ask the route.' },
    { id: 'stating-means', label: 'Stating means of transport', goal: 'Use N(으)로 to say which transport.' },
    { id: 'asking-duration', label: 'Asking how long', goal: 'Use 얼마나 걸려요? + 분/시간.' },
  ],
  relatedPools: ['topic-travel', 'topic-city'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: ask routes, state means, describe duration & transfers.', 'word', 'Functions: ask · state · duration · transfer', 'Four micro-skills.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'You need to go from 구미 (Gumi) to 서울 (Seoul) but never made the trip. You ask a stranger.', 'word', 'You: 서울에 어떻게 가요? — Stranger: KTX 타세요.', 'You: How do I get to Seoul? — Stranger: Take the KTX.', null, [ACT.orientation]),

    createContentItem('어떻게 → [어떠케]', 'eotteoke', '격음화: ㅎ + ㄱ → ㅋ.', 'word', '어떻게 가요? → [어떠케 가요]', 'How do I go?', null, [ACT.pronunciation]),
    createContentItem('지하철로 → [지하철로]', 'jihacheollo', '로 attaches smoothly to ㄹ받침. No sound change.', 'word', '지하철로 가요.', 'I go by subway.', null, [ACT.pronunciation]),
    createContentItem('걸려요 → [걸려요]', 'geollyeoyo', '연음 of ㄹ받침 + 어요. The double ㄹ stays clear.', 'word', '한 시간 걸려요.', 'Takes an hour.', null, [ACT.pronunciation]),
    createContentItem('100번 → [백뻔]', 'baekppeon', '경음화: ㄱ받침 of 백 tensifies ㅂ.', 'word', '100번 버스를 타세요. → [백뻔]', 'Take bus number 100.', null, [ACT.pronunciation]),

    createContentItem('버스', 'beoseu', 'bus', 'word', '버스로 학교에 가요.', 'I go to school by bus.', null, [ACT.vocabularyModes]),
    createContentItem('지하철', 'jihacheol', 'subway', 'word', '지하철이 빠르고 편해요.', 'The subway is fast and convenient.', null, [ACT.vocabularyModes]),
    createContentItem('택시', 'taeksi', 'taxi', 'word', '택시를 타요.', 'I take a taxi.', null, [ACT.vocabularyModes]),
    createContentItem('기차', 'gicha', 'train', 'word', '기차로 부산에 가요.', 'I go to Busan by train.', null, [ACT.vocabularyModes]),
    createContentItem('KTX', 'KTX', 'KTX (high-speed train)', 'word', 'KTX는 정말 빨라요.', 'KTX is really fast.', null, [ACT.vocabularyModes]),
    createContentItem('SRT', 'SRT', 'SRT (high-speed train, southern line)', 'word', 'SRT로 부산에 가요.', 'I take SRT to Busan.', null, [ACT.vocabularyModes]),
    createContentItem('비행기', 'bihaenggi', 'airplane', 'word', '비행기로 한국에 왔어요.', 'I came to Korea by plane.', null, [ACT.vocabularyModes]),
    createContentItem('자전거', 'jajeongeo', 'bicycle', 'word', '자전거를 타요.', 'I ride a bike.', null, [ACT.vocabularyModes]),
    createContentItem('걸어서', 'georeoseo', 'on foot', 'word', '학교에 걸어서 가요.', 'I walk to school.', null, [ACT.vocabularyModes]),
    createContentItem('정류장', 'jeongnyujang', 'bus stop', 'word', '버스 정류장이 어디에 있어요?', 'Where is the bus stop?', null, [ACT.vocabularyModes]),
    createContentItem('역', 'yeok', 'station', 'word', '서울역에서 만나요.', 'Let us meet at Seoul Station.', null, [ACT.vocabularyModes]),
    createContentItem('공항', 'gonghang', 'airport', 'word', '공항까지 1시간 걸려요.', 'An hour to the airport.', null, [ACT.vocabularyModes]),
    createContentItem('터미널', 'teomineol', 'terminal', 'word', '버스 터미널이 가까워요.', 'The bus terminal is close.', null, [ACT.vocabularyModes]),

    createContentItem('타다', 'tada', 'to ride / take (transport)', 'word', '지하철을 타요.', 'I take the subway.', null, [ACT.vocabularyVerbs]),
    createContentItem('내리다', 'naerida', 'to get off', 'word', '다음 역에서 내려요.', 'I get off at the next station.', null, [ACT.vocabularyVerbs]),
    createContentItem('갈아타다', 'garatada', 'to transfer', 'word', '서울역에서 갈아타세요.', 'Transfer at Seoul Station.', null, [ACT.vocabularyVerbs]),
    createContentItem('걸리다', 'geollida', 'to take (time)', 'word', '한 시간 걸려요.', 'It takes an hour.', null, [ACT.vocabularyVerbs]),
    createContentItem('걷다', 'geotda', 'to walk', 'word', '학교까지 걸어가요.', 'I walk to school.', null, [ACT.vocabularyVerbs]),
    createContentItem('도착하다', 'dochakhada', 'to arrive', 'word', '서울에 도착했어요.', 'I arrived in Seoul.', null, [ACT.vocabularyVerbs]),
    createContentItem('출발하다', 'chulbalhada', 'to depart', 'word', '8시에 출발해요.', 'We leave at 8.', null, [ACT.vocabularyVerbs]),

    createContentItem('어떻게 가요? — how do I get there?', 'how to go', 'The default route question.', 'sentence', '터미널에 어떻게 가요? — 버스로 가세요.', 'How do I get to the terminal? — Take the bus.',
      [{ korean: '터미널에', english: 'to the terminal' }, { korean: '어떻게', english: 'how' }, { korean: '가요?', english: 'do you go?' }], [ACT.grammarHow]),
    createContentItem('Tell-me-how variations', 'casual / formal', '~ 가는 방법 좀 알려 주세요. = "Please tell me how to get to ~". More polite.', 'sentence', '공항에 가는 방법 좀 알려 주세요.', 'Please tell me how to get to the airport.',
      null, [ACT.grammarHow]),

    createContentItem('N(으)로 — by means of', 'instrument', '으로 after consonant, 로 after vowel/ㄹ.', 'sentence', '저는 학교에 지하철로 가요.', 'I go to school by subway.',
      [
        { korean: '지하철 + 로', english: 'ends in ㄹ → 로 directly' },
        { korean: '버스 + 로', english: '버스 ends in vowel → 로' },
        { korean: '기차 + 로', english: '기차 ends in vowel → 로' },
      ],
      [ACT.grammarMeans]),
    createContentItem('걸어서 — on foot', 'exception', '걷다 (walk) → 걸어서 = "by walking". Always use this exact form for "on foot".', 'sentence', '학교에 걸어서 가요.', 'I walk to school.',
      null, [ACT.grammarMeans]),
    createContentItem('N(으)로 — direction (review)', 'two uses', '으로/로 also means "toward / via". Same particle, two related meanings.', 'sentence', '오른쪽으로 가세요. (direction) · 버스로 가세요. (means)', 'Same particle.',
      null, [ACT.grammarMeans]),

    createContentItem('N에서 N까지 — from N to N', 'route bounds', 'Mark start with 에서, end with 까지.', 'sentence', '여기에서 서울역까지 얼마나 걸려요?', 'How long from here to Seoul Station?',
      [{ korean: '여기에서', english: 'from here' }, { korean: '서울역까지', english: 'to Seoul Station' }], [ACT.grammarRoute]),
    createContentItem('얼마나 걸려요? — how long?', 'duration', 'Standard duration question. Reply with N시간 / N분.', 'sentence', '얼마나 걸려요? — 약 30분 걸려요.', 'How long? — About 30 minutes.',
      [{ korean: '약', english: 'about / approximately' }, { korean: '~분 / ~시간', english: 'minutes / hours' }], [ACT.grammarRoute]),
    createContentItem('갈아타다 — transfer', 'switching lines', 'Pattern: 에서 + (line number)으로 + 갈아타세요.', 'sentence', '서울역에서 4호선으로 갈아타세요.', 'Transfer to Line 4 at Seoul Station.',
      [{ korean: '~호선', english: 'Line ~' }, { korean: '~ 정거장', english: 'stop(s)' }], [ACT.grammarRoute]),

    createContentItem('A commute description', 'reading',
      'Read aloud, then answer.',
      'sentence',
      '저는 매일 학교에 갑니다. 집에서 지하철역까지 걸어서 10분 걸려요. 그리고 지하철로 30분 갑니다. 학교 앞 정류장에서 내려요. 모두 약 45분 걸려요. 비가 오면 버스를 타요.',
      'I go to school every day. From home to the subway station takes 10 minutes on foot. Then I go 30 minutes by subway. I get off at the stop in front of school. Total is about 45 minutes. If it rains I take the bus.',
      [
        { korean: '걸어서 10분', english: '10 minutes on foot' },
        { korean: '지하철로 30분', english: '30 minutes by subway' },
        { korean: '~ 앞 정류장에서 내려요', english: 'get off at the stop in front of ~' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Use the route forms.', 'sentence',
      'Q1: 집에서 지하철역까지 얼마나 걸려요? · Q2: 지하철로 몇 분 가요? · Q3: 비가 오면 어떻게 가요?',
      'Q1: Home to station? Q2: How long by subway? Q3: What if it rains?',
      [
        { korean: 'A1: 걸어서 10분 걸려요.', english: '10 minutes on foot.' },
        { korean: 'A2: 30분이요.', english: '30 minutes.' },
        { korean: 'A3: 버스를 타요.', english: 'I take the bus.' },
      ],
      [ACT.reading]),

    createContentItem('Asking the bus terminal', 'listening',
      'Asking a passerby.',
      'conversation',
      'A: 실례합니다. 버스 터미널에 어떻게 가요?\nB: 여기에서 100번 버스를 타세요.\nA: 어디에서 내려요?\nB: 터미널 앞 정류장에서 내리세요. 약 20분 걸려요.\nA: 시간이 얼마나 걸려요?\nB: 길이 안 막히면 20분이에요. 막히면 30분쯤이요.\nA: 감사합니다.',
      'A: Excuse me. How do I get to the bus terminal? B: Take bus 100. A: Where do I get off? B: Get off in front of the terminal. About 20 min. A: How long? B: 20 min if no traffic, 30 if traffic. A: Thanks.',
      [
        { korean: '~번 버스', english: 'bus number ~' },
        { korean: '~ 앞 정류장에서 내리세요', english: 'get off in front of ~' },
        { korean: '길이 막히다', english: 'traffic jam' },
      ],
      [ACT.listening]),
    createContentItem('Subway transfer', 'listening',
      'Multi-step subway directions.',
      'conversation',
      'A: 강남역에 어떻게 가요?\nB: 여기 1호선에서 시청역까지 가세요. 시청역에서 2호선으로 갈아타세요.\nA: 시청역에서 갈아타고요?\nB: 네. 그리고 두 정거장 가면 강남역이에요.\nA: 얼마나 걸려요?\nB: 약 30분 걸려요.\nA: 알겠습니다. 감사합니다.',
      'A: How to Gangnam Station? B: Take Line 1 to City Hall, then transfer to Line 2. A: Transfer at City Hall? B: Yes. Two more stops to Gangnam. A: How long? B: 30 min. A: Got it. Thanks.',
      [
        { korean: '~호선', english: 'Line ~' },
        { korean: '~으로 갈아타다', english: 'transfer to ~' },
        { korean: '두 정거장 가면', english: 'after two stops' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'commute template',
      'Use this structure.',
      'sentence',
      '저는 매일 [장소]에 가요. [출발지]에서 [목적지]까지 [수단]으로 가요. [수단]을/를 타면 [수]분 걸려요. 그리고 [장소]에서 내려요.',
      '[place] · [start] · [end] · [means] · [duration] · [get off point]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 3-5 sentences about your commute. Use at least one duration and one transfer (if any).',
      'sentence', 'Example: 저는 학교까지 지하철로 가요. 집에서 지하철역까지 걸어서 5분 걸려요. 그리고 두 정거장 가면 학교 앞 역이에요. 모두 20분 걸려요.',
      'Example: I take the subway to school. 5 min walk to the station. 2 stops to school. 20 min total.',
      null, [ACT.writing]),

    createContentItem('T-money card', 'culture',
      'A 티머니카드 is a rechargeable contactless card that works on bus, subway, AND taxi nationwide. Buy at any convenience store or subway station.',
      'sentence', '티머니카드 하나 사세요. 버스, 지하철, 택시 다 돼요.',
      'Get a T-money card. Works on bus, subway, taxi.',
      [{ korean: '티머니카드', english: 'T-money card' }, { korean: '충전하다', english: 'recharge' }, { korean: '편의점에서', english: 'at the convenience store' }], [ACT.culture]),
    createContentItem('KTX vs ITX vs SRT', 'culture',
      'KTX: high-speed bullet train from Seoul Station, fastest, most expensive. ITX: regular intercity train, slower, cheaper. SRT: same speed as KTX but departs from Suseo Station (south Seoul).',
      'sentence', '서울에서 부산까지 KTX로 약 2시간 30분이에요.',
      'Seoul to Busan by KTX is about 2.5 hours.',
      [{ korean: 'KTX', english: 'fastest (Seoul Station)' }, { korean: 'ITX', english: 'slower, cheaper' }, { korean: 'SRT', english: 'fast, Suseo Station' }], [ACT.culture]),

    createContentItem('과제: Plan a trip to Seoul', 'task',
      'Roleplay: You are in Gumi, want to go to Seoul. Ask the AI tutor route, mode, duration, and any transfers.',
      'conversation',
      'You: 서울에 어떻게 가요?\nTutor: [KTX or bus options]\nYou: [pick + ask duration]\nTutor: [duration]\nYou: [confirm + ask station/terminal]\nTutor: [reply]\nYou: 감사합니다.',
      'AI tutor will play the route guide.',
      [
        { korean: '~로 가요', english: 'go by ~' },
        { korean: '얼마나 걸려요?', english: 'how long?' },
        { korean: '~에서 갈아타다', english: 'transfer at ~' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
