// Level 2 Track-Adult Unit 6 — 기숙사 생활이 어떻습니까? (Dormitory life)
// Source: Book 2A·6.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au6-orientation',
  pronunciation: 'l2au6-pronunciation',
  vocabularySpaces: 'l2au6-vocab-spaces',
  vocabularyLiving: 'l2au6-vocab-living',
  grammarLive: 'l2au6-grammar-live',
  grammarEvaluate: 'l2au6-grammar-evaluate',
  reading: 'l2au6-reading',
  listening: 'l2au6-listening',
  writing: 'l2au6-writing',
  culture: 'l2au6-culture',
  task: 'l2au6-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe dorm rooms and shared spaces.', 'Evaluate with V-기 좋다/나쁘다.', 'Politely request quiet hours.'],
    task: 'Imagine living in a company dorm in Gumi — describe the space and resolve a noise issue.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Dorm vocabulary',
    goals: ['Apply 격음화: 기숙사 → [기숙싸], 빨래방 → [빨래방].'],
    task: 'Read aloud.' },
  { id: ACT.vocabularySpaces, section: 'Vocabulary I', title: 'Dorm spaces',
    goals: ['Use 기숙사·룸메이트·공용 공간·빨래방·주방·침대·샤워실.'],
    task: 'Describe your dorm.' },
  { id: ACT.vocabularyLiving, section: 'Vocabulary II', title: 'Living + rules words',
    goals: ['Use 소음·규칙·통금·편하다·불편하다·시끄럽다.'],
    task: 'List 3 dorm rules.' },
  { id: ACT.grammarLive, section: 'Grammar I', title: 'N에 살다 / V-기 좋다',
    goals: ['Use N에 살다 with location.', 'Nominalize verb + 기 + adjective.'],
    task: 'State where you live + evaluate.' },
  { id: ACT.grammarEvaluate, section: 'Grammar II', title: 'V-아/어 주실 수 있어요? — could you?',
    goals: ['Polite request form.', 'Use for roommate negotiations.'],
    task: 'Make 3 polite requests.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Dorm rules notice',
    goals: ['Read posted rules.'],
    task: 'Answer what is allowed/forbidden.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Dorm-life chat',
    goals: ['Follow a conversation about dorm life.'],
    task: 'Reproduce with your situation.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Dorm-life description',
    goals: ['Write 4-5 lines about your dorm.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean factory dorms',
    goals: ['Know that 사택 (company housing) is common for migrant workers.', 'Know typical 통금 11 PM.'],
    task: 'Compare with your country.' },
  { id: ACT.task, section: 'Task', title: '과제 — Quiet-hours request',
    goals: ['Politely ask roommate to lower volume.'],
    task: 'Roleplay the request.' },
];

const lesson = {
  title: '레벨 2 (직장) · 6과: 기숙사 생활이 어떻습니까? (Dormitory Life)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'comparing-living', label: 'Comparing living', goal: 'Use V-기 좋다/나쁘다.' },
    { id: 'requesting-roommate', label: 'Polite roommate request', goal: 'Use V-아/어 주실 수 있어요?' },
    { id: 'describing-dorm', label: 'Describing dorm', goal: 'Use N에 살다 + descriptors.' },
  ],
  relatedPools: ['topic-people'],
  content: [
    createContentItem('Lesson goal', 'dorm life', 'By end: describe dorm, evaluate, request changes politely.', 'word', 'Functions: describe · evaluate · request', 'Dorm toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'noisy roommate', 'Your roommate plays music loudly at midnight. You need to politely ask them to turn it down.', 'word', 'You: 죄송한데 소리 좀 줄여 주실 수 있어요? — Roommate: 미안해요.', 'You: Sorry, turn it down? — Roommate: Sorry.', null, [ACT.orientation]),

    createContentItem('기숙사 → [기숙싸]', 'gisuksa', '경음화: ㄱ-받침 + ㅅ → tense ㅆ.', 'word', '기숙사에 살아요.', 'Live in dorm.', null, [ACT.pronunciation]),
    createContentItem('빨래방 → [빨래방]', 'ppallaebang', 'No change.', 'word', '빨래방이 1층에 있어요.', 'Laundry is on 1F.', null, [ACT.pronunciation]),
    createContentItem('공용 → [공용]', 'gongyong', 'No change.', 'word', '공용 공간.', 'Common area.', null, [ACT.pronunciation]),
    createContentItem('익숙해지다 → [익쑤캐지다]', 'iksukaejida', '경음화 + 격음화.', 'word', '익숙해졌어요.', 'Got used to it.', null, [ACT.pronunciation]),

    createContentItem('기숙사', 'gisuksa', 'dormitory', 'word', '회사 기숙사에 살아요.', 'Live in company dorm.', null, [ACT.vocabularySpaces]),
    createContentItem('룸메이트', 'rumeiteu', 'roommate', 'word', '룸메이트가 친절해요.', 'Roommate is kind.', null, [ACT.vocabularySpaces]),
    createContentItem('공용 공간', 'gongyong gonggan', 'common area', 'word', '공용 공간을 깨끗하게.', 'Keep common area clean.', null, [ACT.vocabularySpaces]),
    createContentItem('빨래방', 'ppallaebang', 'laundry room', 'word', '빨래방은 1층입니다.', 'Laundry on 1F.', null, [ACT.vocabularySpaces]),
    createContentItem('주방', 'jubang', 'kitchen', 'word', '공용 주방에서 요리합니다.', 'I cook in shared kitchen.', null, [ACT.vocabularySpaces]),
    createContentItem('침대', 'chimdae', 'bed', 'word', '침대가 편해요.', 'Bed is comfortable.', null, [ACT.vocabularySpaces]),
    createContentItem('샤워실', 'syawosil', 'shower room', 'word', '샤워실이 층마다 있어요.', 'Shower per floor.', null, [ACT.vocabularySpaces]),
    createContentItem('현관', 'hyeongwan', 'entrance', 'word', '현관에 신발 두세요.', 'Leave shoes at entrance.', null, [ACT.vocabularySpaces]),
    createContentItem('사택', 'taek', 'company housing', 'word', '회사 사택이에요.', 'It is company housing.', null, [ACT.vocabularySpaces]),

    createContentItem('소음', 'soeum', 'noise', 'word', '밤에 소음이 있어요.', 'Noise at night.', null, [ACT.vocabularyLiving]),
    createContentItem('규칙', 'gyuchik', 'rule', 'word', '기숙사 규칙을 지켜요.', 'Follow dorm rules.', null, [ACT.vocabularyLiving]),
    createContentItem('통금', 'tonggeum', 'curfew', 'word', '통금이 11시예요.', 'Curfew is 11.', null, [ACT.vocabularyLiving]),
    createContentItem('편하다', 'pyeonhada', 'comfortable', 'word', '기숙사가 편해요.', 'Dorm is convenient.', null, [ACT.vocabularyLiving]),
    createContentItem('불편하다', 'bulpyeonhada', 'inconvenient', 'word', '소음 때문에 불편해요.', 'Inconvenient because of noise.', null, [ACT.vocabularyLiving]),
    createContentItem('시끄럽다', 'sikkeureopda', 'noisy', 'word', '너무 시끄러워요.', 'Too noisy.', null, [ACT.vocabularyLiving]),
    createContentItem('조용하다', 'joyonghada', 'quiet', 'word', '조용한 방을 좋아해요.', 'I prefer quiet rooms.', null, [ACT.vocabularyLiving]),
    createContentItem('익숙해지다', 'iksukaejida', 'get used to', 'word', '익숙해졌어요.', 'I got used to it.', null, [ACT.vocabularyLiving]),
    createContentItem('줄이다', 'jurida', 'turn down / lower', 'word', '소리를 줄여 주세요.', 'Turn down please.', null, [ACT.vocabularyLiving]),
    createContentItem('소리', 'sori', 'sound / volume', 'word', '소리가 크네요.', 'The volume is high.', null, [ACT.vocabularyLiving]),

    createContentItem('N에 살다 — live in N', 'reside', 'Use 에 (not 에서) with 살다.', 'sentence', '저는 회사 기숙사에 삽니다.', 'I live in the company dorm.',
      [{ korean: '기숙사 + 에 + 살다', english: 'location + 에 + reside' }], [ACT.grammarLive]),
    createContentItem('V-기 좋다/나쁘다 — good/bad to V', 'evaluative', 'Nominalize verb with -기 + 좋다/나쁘다.', 'sentence', '교통이 편해서 살기 좋습니다.', 'Convenient transit, good to live.',
      [{ korean: '살기 좋다', english: 'good to live' }, { korean: '자기 나쁘다', english: 'bad to sleep' }, { korean: '공부하기 좋다', english: 'good to study' }], [ACT.grammarLive]),

    createContentItem('V-아/어 주실 수 있어요? — could you?', 'polite request', 'Most polite request form.', 'sentence', '소리 좀 줄여 주실 수 있어요?', 'Could you turn down?',
      [{ korean: 'V-아/어 주실 수 있어요?', english: 'could you?' }, { korean: 'softer than 주세요', english: 'more deferential' }], [ACT.grammarEvaluate]),
    createContentItem('Add 좀 + 죄송한데', 'softener', 'For roommate requests, soften with 죄송한데 + 좀.', 'sentence', '죄송한데 소리 좀 줄여 주실 수 있어요?', 'Sorry but could you turn down?',
      null, [ACT.grammarEvaluate]),

    createContentItem('Dorm rules notice', 'reading',
      'Read this posted notice.',
      'sentence',
      '기숙사 규칙\n· 통금: 23:00\n· 공용 주방 청소: 사용 후 즉시\n· 빨래방: 06:00~22:00 (그 외에는 사용 금지)\n· 흡연: 외부 흡연 구역에서만\n· 소음: 22:00 이후 조용히 (다른 룸메이트 배려)\n· 룸메이트 변경 요청: 사감 선생님께 문의',
      'Dorm Rules:\n- Curfew: 11 PM\n- Shared kitchen: clean after use\n- Laundry: 6 AM-10 PM only\n- Smoking: outside zone only\n- Noise: quiet after 10 PM\n- Roommate change: ask dorm manager.',
      [
        { korean: '사용 금지', english: 'prohibited' },
        { korean: '배려', english: 'consideration' },
        { korean: '사감 선생님', english: 'dorm supervisor' },
      ],
      [ACT.reading]),

    createContentItem('Dorm-life chat', 'listening',
      'Roommates talk about life.',
      'conversation',
      'A: 사라 씨, 기숙사 생활 어떻습니까?\nB: 처음에는 좀 불편했는데 지금은 익숙해졌습니다. 룸메이트가 친절해서 좋습니다.\nA: 공용 주방은 자주 쓰십니까?\nB: 네, 매일 저녁에 요리합니다. 가끔 룸메이트하고 같이 먹어요.\nA: 통금은 몇 시입니까?\nB: 11시입니다. 그래서 일찍 들어와야 합니다.\nA: 살기 좋은 환경입니까?\nB: 교통이 편해서 살기 좋아요.',
      'A: Sarah, dorm life? B: Inconvenient at first, used to it now. Roommate is kind. A: Use shared kitchen? B: Yes, daily. Sometimes eat with roommate. A: Curfew? B: 11. Have to come in early. A: Good place to live? B: Yes, transit is convenient.',
      [
        { korean: '익숙해지다', english: 'get used to' },
        { korean: '살기 좋다', english: 'good place to live' },
      ],
      [ACT.listening]),

    createContentItem('Dorm description', 'writing',
      'Sample paragraph.',
      'sentence',
      '저는 회사 기숙사에 살고 있습니다. 룸메이트는 베트남에서 왔습니다. 공용 주방이 있어서 요리하기 좋습니다. 빨래방도 있어서 편리합니다. 다만 밤에 가끔 소음이 있어서 자기 좀 어렵습니다. 그래도 회사가 가까워서 살기 좋습니다.',
      'I live in the company dorm. My roommate is from Vietnam. There is a shared kitchen, good for cooking. Laundry room too — convenient. But sometimes noise at night makes sleeping hard. Still, the company is close so it is good to live in.',
      null, [ACT.writing]),

    createContentItem('Korean factory dorms', 'culture',
      'Korean factories often provide 사택 (company housing) for both Korean and foreign workers. Typical features: 2-4 person rooms, shared kitchen + bathroom, 통금 (curfew) 11 PM, sometimes shuttles to plant. Some have 사감 (resident supervisor) who enforces rules.',
      'sentence', '한국 공장은 보통 외국인 노동자에게 기숙사를 제공해요.',
      'Korean factories usually provide dorms to foreign workers.',
      [
        { korean: '사택', english: 'company housing' },
        { korean: '사감', english: 'dorm supervisor' },
        { korean: '통금', english: 'curfew' },
      ],
      [ACT.culture]),

    createContentItem('과제: Quiet-hours request', 'task',
      'Roleplay: Politely ask roommate to lower volume.',
      'conversation',
      'You: 죄송한데 소리 좀 ~ 주실 수 있어요? 밤이 늦어서요.\nRoommate: 아, 미안해요. 몰랐어요.\nYou: 괜찮아요. 룸메이트끼리니까 살기 좋게 해 봐요.\nRoommate: 네, 조심할게요.',
      'AI tutor will play the roommate.',
      [
        { korean: '~ 주실 수 있어요?', english: 'could you?' },
        { korean: '~ 살기 좋게', english: 'so we live well' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
