// Level 1 Unit 4 — Daily routines
// Sources: Book 1A·7 (난 책을 읽어) + Book 1B·4 (주말에는 보통 집에서 쉬어요)
// Functions: describing what you do daily, talking about routine.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u4-orientation',
  pronunciation: 'l1u4-pronunciation',
  vocabularyVerbs: 'l1u4-vocab-verbs',
  vocabularyTime: 'l1u4-vocab-time',
  grammarPolite: 'l1u4-grammar-polite',
  grammarParticles: 'l1u4-grammar-particles',
  grammarNegation: 'l1u4-grammar-negation',
  reading: 'l1u4-reading',
  listening: 'l1u4-listening',
  writing: 'l1u4-writing',
  culture: 'l1u4-culture',
  task: 'l1u4-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: [
      'Conjugate 15+ verbs into the polite -아/어요 present.',
      'Use the object marker 을/를 and the time/place marker 에 / 에서.',
      'Describe your weekday and weekend routines in 3-5 sentences.',
    ],
    task: 'Imagine telling a Korean friend how your typical day looks.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Verb-ending sound changes',
    goals: ['Apply 경음화 in 먹다 → [먹따], 읽다 → [익따].', 'Apply 격음화 in 좋다 → [조타].'],
    task: 'Read each verb stem + conjugation aloud.' },
  { id: ACT.vocabularyVerbs, section: 'Vocabulary I', title: 'Daily action verbs',
    goals: ['Learn 18+ common daily verbs (dictionary form + polite form).'],
    task: 'List your top five daily actions in Korean.' },
  { id: ACT.vocabularyTime, section: 'Vocabulary II', title: 'Time-of-day & frequency words',
    goals: ['Use 아침·점심·저녁·밤; 매일·자주·보통·가끔·항상; 평일·주말.'],
    task: 'Build a frequency line for one of your habits.' },
  { id: ACT.grammarPolite, section: 'Grammar I', title: 'The polite -아/어요 ending',
    goals: [
      'Apply the rule: ㅏ/ㅗ stem → -아요; other vowels → -어요; -하다 → -해요.',
      'Conjugate 가다 → 가요, 먹다 → 먹어요, 공부하다 → 공부해요, 마시다 → 마셔요.',
    ],
    task: 'Conjugate five verbs from their dictionary form into polite present.' },
  { id: ACT.grammarParticles, section: 'Grammar II', title: 'Particles: 을/를 (object), 에 (time/place), 에서 (place of action)',
    goals: ['Use 을/를 to mark the object of a verb.', 'Use 에 for time AND for the destination of movement.', 'Use 에서 for the place where an action happens.'],
    task: 'Make three sentences each using 을/를, 에, and 에서 correctly.' },
  { id: ACT.grammarNegation, section: 'Grammar III', title: 'Negation: 안 + V and V지 않다',
    goals: ['Use short negation 안 + V (everyday).', 'Use long negation V-지 않다 (more formal/written).', 'Place 안 BEFORE the verb root for V하다 → 운동 안 해요.'],
    task: 'Negate three of your habits using both 안 and -지 않다.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A typical Tuesday',
    goals: ['Read a daily-schedule paragraph and answer questions.'],
    task: 'Reply to comprehension questions in Korean.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Weekend routines',
    goals: ['Follow a 4-turn weekend-plans dialogue.', 'Reproduce with your own activities.'],
    task: 'Listen, then describe your own weekend routine.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Write your daily schedule',
    goals: ['Write 5-6 sentences describing a typical day, using time markers.'],
    task: 'Write your own daily schedule in 5-6 sentences.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean college life rhythm',
    goals: ['Understand the typical Korean student day (수업·동아리·아르바이트·기숙사).'],
    task: 'Compare one part of a Korean student\'s day to yours.' },
  { id: ACT.task, section: 'Task', title: '과제 — Compare your week with a Korean friend',
    goals: ['Combine vocabulary, conjugation, particles, and negation in one continuous scene.'],
    task: 'Roleplay comparing your weekday vs weekend routines with the AI tutor.' },
];

const lesson = {
  title: '레벨 1 · 4과: 주말에는 보통 집에서 쉬어요 (Daily Routines)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'describing-daily-activities', label: 'Describing daily activities', goal: 'Use -아/어요 to describe what you do at different times of day.' },
    { id: 'asking-what-do-daily', label: 'Asking what someone does', goal: 'Use 뭐 해요? / 무엇을 해요? to ask what someone does.' },
    { id: 'negating-action', label: 'Saying what you do NOT do', goal: 'Use 안 + V or V-지 않다 to negate an action.' },
  ],
  relatedPools: ['topic-people', 'topic-school'],
  content: [
    createContentItem('Lesson goal', 'routine speech', 'By end: describe your daily/weekly routine using polite present, particles, and negation.', 'word', 'Functions: conjugate · mark object/time/place · negate', 'Three skills that unlock present-tense speech in Korean.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'small talk', 'A Korean classmate asks "오늘 뭐 해요?" — you should be able to answer in 2-3 sentences.', 'word', 'Classmate: 오늘 뭐 해요? — You: 오전에 한국어를 공부해요. 오후에 친구를 만나요.', 'Classmate: What are you doing today? — You: I study Korean in the morning. I meet a friend in the afternoon.', null, [ACT.orientation]),

    createContentItem('먹다 → [먹따]', 'meokda', '경음화: ㄱ-받침 of 먹 makes the following ㄷ tense.', 'word', '점심을 먹다. → [먹따]', 'to eat lunch.', null, [ACT.pronunciation]),
    createContentItem('읽다 → [익따]', 'ikda', 'Double-final ㄺ reduces to [ㄱ], then 경음화 makes the ㄷ tense.', 'word', '책을 읽다. → [익따]', 'to read a book.', null, [ACT.pronunciation]),
    createContentItem('좋다 → [조타]', 'jota', '격음화: ㅎ-받침 + ㄷ → ㅌ. The verb is spelled with ㅎ but spoken with ㅌ.', 'word', '책이 좋다. → [좋타]', 'I like books.', null, [ACT.pronunciation]),
    createContentItem('많이 → [마니]', 'mani', 'ㅀ-받침: ㄴ jumps over, ㅎ disappears.', 'word', '많이 먹어요. → [마니 머거요]', 'I eat a lot.', null, [ACT.pronunciation]),

    createContentItem('일어나다', 'ireonada', 'to get up / wake up', 'word', '저는 7시에 일어나요.', 'I wake up at 7.', null, [ACT.vocabularyVerbs]),
    createContentItem('자다', 'jada', 'to sleep', 'word', '보통 11시에 자요.', 'I usually sleep at 11.', null, [ACT.vocabularyVerbs]),
    createContentItem('먹다', 'meokda', 'to eat', 'word', '아침을 먹어요.', 'I eat breakfast.', null, [ACT.vocabularyVerbs]),
    createContentItem('마시다', 'masida', 'to drink', 'word', '커피를 마셔요.', 'I drink coffee.', null, [ACT.vocabularyVerbs]),
    createContentItem('가다', 'gada', 'to go', 'word', '학교에 가요.', 'I go to school.', null, [ACT.vocabularyVerbs]),
    createContentItem('오다', 'oda', 'to come', 'word', '친구가 집에 와요.', 'My friend comes to my house.', null, [ACT.vocabularyVerbs]),
    createContentItem('공부하다', 'gongbuhada', 'to study', 'word', '한국어를 공부해요.', 'I study Korean.', null, [ACT.vocabularyVerbs]),
    createContentItem('일하다', 'ilhada', 'to work', 'word', '카페에서 일해요.', 'I work at a cafe.', null, [ACT.vocabularyVerbs]),
    createContentItem('쉬다', 'swida', 'to rest', 'word', '주말에 집에서 쉬어요.', 'I rest at home on weekends.', null, [ACT.vocabularyVerbs]),
    createContentItem('운동하다', 'undonghada', 'to exercise', 'word', '저녁에 운동해요.', 'I exercise in the evening.', null, [ACT.vocabularyVerbs]),
    createContentItem('보다', 'boda', 'to see / watch', 'word', '영화를 봐요.', 'I watch a movie.', null, [ACT.vocabularyVerbs]),
    createContentItem('듣다', 'deutda', 'to listen', 'word', '음악을 들어요.', 'I listen to music.', null, [ACT.vocabularyVerbs]),
    createContentItem('만나다', 'mannada', 'to meet', 'word', '친구를 만나요.', 'I meet a friend.', null, [ACT.vocabularyVerbs]),
    createContentItem('읽다', 'ikda', 'to read', 'word', '책을 읽어요.', 'I read a book.', null, [ACT.vocabularyVerbs]),
    createContentItem('쓰다', 'sseuda', 'to write / use', 'word', '한국어로 일기를 써요.', 'I write a diary in Korean.', null, [ACT.vocabularyVerbs]),
    createContentItem('씻다', 'ssitda', 'to wash', 'word', '아침에 얼굴을 씻어요.', 'I wash my face in the morning.', null, [ACT.vocabularyVerbs]),
    createContentItem('샤워하다', 'syawohada', 'to take a shower', 'word', '저녁에 샤워해요.', 'I take a shower in the evening.', null, [ACT.vocabularyVerbs]),
    createContentItem('요리하다', 'yorihada', 'to cook', 'word', '저녁에 요리해요.', 'I cook in the evening.', null, [ACT.vocabularyVerbs]),

    createContentItem('아침', 'achim', 'morning / breakfast', 'word', '아침을 먹어요.', 'I eat breakfast.', null, [ACT.vocabularyTime]),
    createContentItem('점심', 'jeomsim', 'noon / lunch', 'word', '점심에 친구를 만나요.', 'I meet a friend at lunch.', null, [ACT.vocabularyTime]),
    createContentItem('저녁', 'jeonyeok', 'evening / dinner', 'word', '저녁에 운동해요.', 'I exercise in the evening.', null, [ACT.vocabularyTime]),
    createContentItem('밤', 'bam', 'night', 'word', '밤에 자요.', 'I sleep at night.', null, [ACT.vocabularyTime]),
    createContentItem('오전 / 오후', 'ojeon / ohu', 'AM / PM', 'word', '오전에는 공부해요. 오후에는 일해요.', 'I study in the AM. I work in the PM.', null, [ACT.vocabularyTime]),
    createContentItem('평일', 'pyeongil', 'weekday', 'word', '평일에는 학교에 가요.', 'On weekdays I go to school.', null, [ACT.vocabularyTime]),
    createContentItem('주말', 'jumal', 'weekend', 'word', '주말에 쉬어요.', 'I rest on weekends.', null, [ACT.vocabularyTime]),
    createContentItem('매일', 'maeil', 'every day', 'word', '매일 운동해요.', 'I exercise every day.', null, [ACT.vocabularyTime]),
    createContentItem('항상', 'hangsang', 'always', 'word', '항상 7시에 일어나요.', 'I always wake up at 7.', null, [ACT.vocabularyTime]),
    createContentItem('자주', 'jaju', 'often', 'word', '자주 카페에 가요.', 'I often go to the cafe.', null, [ACT.vocabularyTime]),
    createContentItem('보통', 'botong', 'usually', 'word', '보통 11시에 자요.', 'I usually sleep at 11.', null, [ACT.vocabularyTime]),
    createContentItem('가끔', 'gakkeum', 'sometimes', 'word', '가끔 영화를 봐요.', 'Sometimes I watch a movie.', null, [ACT.vocabularyTime]),
    createContentItem('전혀 안', 'jeonhyeo an', 'never / not at all', 'word', '저는 술을 전혀 안 마셔요.', 'I never drink alcohol.', null, [ACT.vocabularyTime]),

    createContentItem(
      'ㅏ/ㅗ stem → -아요', 'rule 1',
      'If the verb stem\'s LAST vowel is ㅏ or ㅗ, attach -아요.',
      'sentence', '가다 → 가요 · 보다 → 봐요 · 살다 → 살아요',
      'Stem 가 (ㅏ) + 아요 = 가아요 → contracts to 가요.',
      [
        { korean: '가다 → 가요', english: '가 + 아요 → contracts (vowel + 아 = vowel)' },
        { korean: '보다 → 봐요', english: 'ㅗ + 아 → 와' },
        { korean: '오다 → 와요', english: 'ㅗ + 아 → 와' },
      ],
      [ACT.grammarPolite]),
    createContentItem(
      'Other vowels → -어요', 'rule 2',
      'If the stem\'s last vowel is anything else (ㅓ, ㅜ, ㅡ, ㅣ, ㅔ, etc.), attach -어요.',
      'sentence', '먹다 → 먹어요 · 마시다 → 마셔요 · 읽다 → 읽어요',
      'Stem 먹 (ㅓ) + 어요 = 먹어요.',
      [
        { korean: '먹다 → 먹어요', english: 'ㅓ + 어 (no contraction)' },
        { korean: '마시다 → 마셔요', english: 'ㅣ + 어 → 여' },
        { korean: '쉬다 → 쉬어요', english: 'ㅟ + 어 (no contraction)' },
      ],
      [ACT.grammarPolite]),
    createContentItem(
      '-하다 → -해요', 'rule 3',
      'Every -하다 verb (공부하다, 운동하다, 일하다, 요리하다) becomes -해요 in polite present.',
      'sentence', '공부하다 → 공부해요 · 운동하다 → 운동해요',
      'The -하- always becomes -해-.',
      [
        { korean: '공부하다 → 공부해요', english: 'study' },
        { korean: '운동하다 → 운동해요', english: 'exercise' },
        { korean: '일하다 → 일해요', english: 'work' },
      ],
      [ACT.grammarPolite]),
    createContentItem(
      'Question intonation', 'rising tone',
      'No new ending — just raise your voice at the end of the same sentence.',
      'sentence', '한국어 공부해요? — 네, 공부해요.',
      'Do you study Korean? — Yes, I study.',
      null, [ACT.grammarPolite]),

    createContentItem(
      '을/를 — object marker', 'eul / reul',
      '을 after consonant, 를 after vowel. Marks what the verb acts on.',
      'sentence', '저는 한국어를 공부해요.',
      'I study Korean.',
      [
        { korean: '한국어 + 를', english: '한국어 ends in vowel → 를' },
        { korean: '책 + 을 → 책을', english: '책 ends in consonant → 을' },
      ],
      [ACT.grammarParticles]),
    createContentItem(
      '에 — time AND destination', 'e',
      'For TIME: 7시에, 아침에, 주말에. For DESTINATION of 가다/오다: 학교에, 집에.',
      'sentence', '7시에 학교에 가요.',
      'I go to school at 7.',
      [
        { korean: '7시에', english: 'at 7 (time)' },
        { korean: '학교에', english: 'to school (destination)' },
        { korean: '가요', english: 'go' },
      ],
      [ACT.grammarParticles]),
    createContentItem(
      '에서 — place where action happens', 'eseo',
      'Use 에서 when the action HAPPENS at that place (eat AT, study AT, work AT).',
      'sentence', '학교에서 공부해요.',
      'I study at school.',
      [
        { korean: '학교에서', english: 'at school (action location)' },
        { korean: '집에서 쉬어요', english: 'rest at home' },
        { korean: '카페에서 일해요', english: 'work at a cafe' },
      ],
      [ACT.grammarParticles]),
    createContentItem(
      '에 vs 에서', 'when to use each',
      '에 = destination (with go/come). 에서 = location of the action.',
      'sentence', '학교에 가요 (going TO) vs 학교에서 공부해요 (studying AT).',
      'Different particle, different meaning.',
      null, [ACT.grammarParticles]),

    createContentItem(
      '안 + V (short negation)', 'an',
      'Place 안 directly before the verb. The most common spoken negation.',
      'sentence', '저는 커피를 안 마셔요.',
      'I do not drink coffee.',
      [
        { korean: '안 마셔요', english: 'do not drink' },
        { korean: '안 가요', english: 'do not go' },
      ],
      [ACT.grammarNegation]),
    createContentItem(
      'V-지 않다 (long negation)', 'ji anta',
      'Attach -지 않다 to the verb stem. More formal, more written.',
      'sentence', '저는 커피를 마시지 않아요.',
      'I do not drink coffee.',
      [
        { korean: '마시 + 지 않아요', english: 'mashi + ji anayo' },
        { korean: '가 + 지 않아요', english: 'ga + ji anayo' },
      ],
      [ACT.grammarNegation]),
    createContentItem(
      '운동하다 → 운동 안 해요', 'special pattern',
      'For V하다 verbs, the 안 goes BETWEEN the noun and 해요, not before the whole word. Common mistake!',
      'sentence', '저는 운동 안 해요. (NOT 안 운동해요)',
      'I do not exercise.',
      [
        { korean: '운동 안 해요', english: 'correct' },
        { korean: '공부 안 해요', english: 'do not study' },
        { korean: '일 안 해요', english: 'do not work' },
      ],
      [ACT.grammarNegation]),

    createContentItem(
      'A typical Tuesday',
      'reading practice',
      'Read aloud, then answer the questions.',
      'sentence',
      '저는 보통 7시에 일어나요. 8시에 아침을 먹어요. 9시에 학교에 가요. 학교에서 한국어를 공부해요. 12시에 친구하고 점심을 먹어요. 오후에 도서관에서 책을 읽어요. 저녁에 집에서 요리해요. 11시쯤 자요.',
      'I usually wake up at 7. I eat breakfast at 8. I go to school at 9. I study Korean at school. At 12 I eat lunch with a friend. In the afternoon I read books at the library. In the evening I cook at home. I sleep around 11.',
      [
        { korean: '7시에 일어나요', english: 'wake up at 7' },
        { korean: '학교에서 공부해요', english: 'study at school (에서)' },
        { korean: '도서관에서 책을 읽어요', english: 'read books at the library' },
        { korean: '11시쯤 자요', english: 'sleep around 11' },
      ],
      [ACT.reading]),
    createContentItem(
      'Comprehension', 'answer in Korean',
      'Use the polite present in your answers.',
      'sentence',
      'Q1: 몇 시에 일어나요? · Q2: 어디에서 한국어를 공부해요? · Q3: 저녁에 뭐 해요?',
      'Q1: When do you wake up? Q2: Where do you study Korean? Q3: What do you do in the evening?',
      [
        { korean: 'A1: 7시에 일어나요.', english: 'I wake up at 7.' },
        { korean: 'A2: 학교에서 공부해요.', english: 'I study at school.' },
        { korean: 'A3: 집에서 요리해요.', english: 'I cook at home.' },
      ],
      [ACT.reading]),

    createContentItem(
      'Weekend plans',
      'dialogue',
      'Two classmates talk about their weekend.',
      'conversation',
      'A: 주말에 보통 뭐 해요?\nB: 보통 집에서 쉬어요. 책도 읽어요.\nA: 운동도 해요?\nB: 가끔 해요. 토요일 아침에 공원에서 달려요. 사라 씨는요?\nA: 저는 주말에 친구를 만나요. 카페에서 같이 공부해요.\nB: 재미있겠네요.',
      'A: What do you usually do on weekends?\nB: I usually rest at home. I also read books.\nA: Do you exercise too?\nB: Sometimes. Saturday mornings I run in the park. And you, Sarah?\nA: On weekends I meet a friend. We study at a cafe together.\nB: Sounds fun.',
      [
        { korean: '주말에 보통', english: 'usually on weekends' },
        { korean: '가끔', english: 'sometimes' },
        { korean: '~씨는요?', english: 'and you?' },
      ],
      [ACT.listening]),
    createContentItem(
      'What are you doing today?',
      'dialogue',
      'A short same-day check-in.',
      'conversation',
      'A: 오늘 뭐 해요?\nB: 오전에 학교에 가요. 한국어 수업이 있어요.\nA: 오후에는요?\nB: 오후에는 친구를 만나요. 같이 영화를 봐요.\nA: 저녁에는요?\nB: 저녁에는 집에서 요리하고 쉬어요. 사라 씨는요?\nA: 저도 비슷해요.',
      'A: What are you doing today?\nB: In the morning I go to school. I have a Korean class.\nA: And in the afternoon?\nB: In the afternoon I meet a friend. We watch a movie.\nA: And in the evening?\nB: In the evening I cook and rest at home. And you?\nA: Same for me.',
      [
        { korean: '오전에 / 오후에 / 저녁에', english: 'morning / afternoon / evening' },
        { korean: '비슷해요', english: 'similar' },
      ],
      [ACT.listening]),

    createContentItem(
      'Model daily-routine paragraph',
      'writing template',
      'Use this structure for your own writing.',
      'sentence',
      '저는 [시간]에 일어나요. [시간]에 [장소]에 가요. [장소]에서 [동사]. 점심에는 [동사]. 저녁에는 [장소]에서 [동사]. 그리고 [시간]에 자요.',
      '[time] wake → [time/place] go → [place] do → [verb] → [evening place + verb] → [time] sleep.',
      null, [ACT.writing]),
    createContentItem(
      'Writing prompt', 'your turn',
      'Write your own 5-6 sentence daily schedule. Use at least one negation and one frequency word.',
      'sentence',
      'Example: 저는 매일 6시에 일어나요. 아침을 안 먹어요. 9시에 학교에 가요. 학교에서 한국어를 공부해요. 보통 5시에 집에 와요. 저녁에 요리해요.',
      'Example: I wake up at 6 daily. I do not eat breakfast. I go to school at 9. I study Korean at school. I usually come home at 5. I cook in the evening.',
      null, [ACT.writing]),

    createContentItem(
      'Korean college day',
      'culture',
      'A typical Korean university student\'s day mixes 수업 (classes), 동아리 (clubs), 아르바이트 (part-time work), and 기숙사 (dorm) life. Many students also study late at the 도서관.',
      'sentence',
      '많은 한국 대학생들은 수업이 끝난 후에 동아리 모임이나 아르바이트를 해요.',
      'Many Korean university students do club meetings or part-time work after class.',
      [
        { korean: '수업', english: 'class' },
        { korean: '동아리', english: 'club' },
        { korean: '아르바이트', english: 'part-time job' },
        { korean: '기숙사', english: 'dormitory' },
      ],
      [ACT.culture]),
    createContentItem(
      '24-hour study cafes',
      'culture',
      'Korea has 24-hour study cafes (스터디카페) and PC rooms. Many students study at the 도서관 or 스터디카페 until midnight, especially during 시험 (exam) period.',
      'sentence',
      '시험 기간에는 스터디카페에서 밤늦게까지 공부해요.',
      'During exam season, students study at study cafes until late at night.',
      null, [ACT.culture]),

    createContentItem(
      '과제: Compare your week',
      'consolidation task',
      'Roleplay: a Korean friend asks about your week. Compare weekday vs weekend. Use vocab, conjugation, particles, and at least one negation.',
      'conversation',
      'Friend: 평일에 보통 뭐 해요?\nYou: [3 sentences about weekday]\nFriend: 주말은 달라요?\nYou: [2 sentences about weekend + one negation]\nFriend: 운동도 해요?\nYou: [answer with frequency word]',
      'AI tutor will play the friend.',
      [
        { korean: '평일에는 [시간]에 일어나요...', english: 'On weekdays I wake at...' },
        { korean: '주말에는 보통...', english: 'On weekends I usually...' },
        { korean: '안 ___ / 가끔 ___', english: 'do not / sometimes' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
