// Level 1 Unit 14 — Ability (can / cannot)
// Source: Book 1B·12 (김치를 만들 수 있어요)
// Functions: stating ability, asking what someone can do, levels of skill.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u14-orientation',
  pronunciation: 'l1u14-pronunciation',
  vocabularySkills: 'l1u14-vocab-skills',
  vocabularyAdverbs: 'l1u14-vocab-adv',
  grammarCanCannot: 'l1u14-grammar-can',
  grammarMotVsAn: 'l1u14-grammar-mot',
  grammarGrade: 'l1u14-grammar-grade',
  reading: 'l1u14-reading',
  listening: 'l1u14-listening',
  writing: 'l1u14-writing',
  culture: 'l1u14-culture',
  task: 'l1u14-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Affirm and negate ability.', 'Grade with 잘/좀/잘 못/전혀 못.', 'Distinguish 못 (cannot — inability) from 안 (not — choice).'],
    task: 'Imagine introducing your skills at a 동아리 (club) interview — what you can do, can do a little, cannot do.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Ability endings',
    goals: ['Apply 경음화: 만들 수 → [만들쑤].', 'Apply 비음화: 못 + 해요 → [모태요] (격음화 with ㅎ).'],
    task: 'Read each ability form aloud.' },
  { id: ACT.vocabularySkills, section: 'Vocabulary I', title: 'Skill verbs',
    goals: ['Use 만들다·운전하다·수영하다·치다·타다·말하다·읽다·쓰다·요리하다·노래하다·춤추다.'],
    task: 'Pick three skills and self-rate.' },
  { id: ACT.vocabularyAdverbs, section: 'Vocabulary II', title: 'Skill-grading adverbs',
    goals: ['Use 잘·좀·잘 못·전혀 못·아직.'],
    task: 'Pair each adverb with a skill verb.' },
  { id: ACT.grammarCanCannot, section: 'Grammar I', title: 'V-(으)ㄹ 수 있다/없다',
    goals: ['Form ability with -ㄹ 수 있다/없다.', 'Question form: ~ㄹ 수 있어요?'],
    task: 'Make four ability sentences.' },
  { id: ACT.grammarMotVsAn, section: 'Grammar II', title: '못 V vs 안 V — inability vs choice',
    goals: ['Use 못 V to mean "cannot" (lack ability or external block).', 'Use 안 V to mean "do not" (choose not to).', 'Special: V하다 → 못 + 해요 sits BETWEEN noun + 해요 = N + 못해요.'],
    task: 'Distinguish in three pairs.' },
  { id: ACT.grammarGrade, section: 'Grammar III', title: 'Grading skill: 잘 V / 좀 V / 잘 못 V',
    goals: ['Layer adverbs before the verb.', 'Use 아직 못 (cannot yet) to indicate work-in-progress.'],
    task: 'Self-rate three skills using all four grades.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Sarah\'s self-evaluation',
    goals: ['Read a 5-sentence skill self-evaluation.'],
    task: 'Identify what she can / cannot do.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Comparing abilities',
    goals: ['Follow a skills + hobbies dialogue.'],
    task: 'Reproduce with your own skills.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — My skills',
    goals: ['Write 4-5 sentences listing skills + grades.'],
    task: 'Write your own skill paragraph.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Modesty in Korean self-evaluation',
    goals: ['Know that Koreans often understate their skills ("아직 잘 못해요").', 'Receive a compliment with 아니에요.'],
    task: 'Reply modestly to "한국어 잘 하시네요!".' },
  { id: ACT.task, section: 'Task', title: '과제 — Club interview',
    goals: ['Combine 잘/좀/못 + ability verb in a continuous scene.'],
    task: 'Roleplay a 동아리 interview at Kumoh.' },
];

const lesson = {
  title: '레벨 1 · 14과: 김치를 만들 수 있어요 (Ability)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-can-you', label: 'Asking if someone can do something', goal: 'Use V-(으)ㄹ 수 있어요? to ask about ability.' },
    { id: 'stating-skill', label: 'Stating a skill or limitation', goal: 'Combine 잘/좀/못 + verb to grade your level.' },
    { id: 'modest-reply', label: 'Replying modestly to a compliment', goal: 'Use 아니에요, 아직 잘 못해요 to deflect praise.' },
  ],
  relatedPools: ['topic-people'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: state abilities at every grade, distinguish 못 vs 안, reply modestly to compliments.', 'word', 'Functions: ability · grade · modesty', 'Three micro-skills.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'A Kumoh club leader asks "한국어 잘 하세요? 김치 만들 수 있어요?" — you should answer truthfully but modestly.', 'word', 'Leader: 한국어 잘 하세요? — You: 아니요, 아직 잘 못해요. 좀 할 수 있어요.', 'Leader: Do you speak Korean well? — You: No, I cannot yet. I can speak a little.', null, [ACT.orientation]),

    createContentItem('만들 수 → [만들쑤]', 'mandeulssu', '경음화: ㄹ받침 + ㅅ → ㄹ + ㅆ.', 'word', '김치를 만들 수 있어요. → [만들쑤 이써요]', 'I can make kimchi.', null, [ACT.pronunciation]),
    createContentItem('못해요 → [모태요]', 'motaeyo', '격음화: ㅅ받침 + ㅎ → ㅌ.', 'word', '운전 못해요. → [운전 모태요]', 'I cannot drive.', null, [ACT.pronunciation]),
    createContentItem('할 수 → [할쑤]', 'halssu', '경음화: ㄹ받침 + ㅅ → ㄹ + ㅆ.', 'word', '한국어 할 수 있어요. → [할쑤 이써요]', 'I can speak Korean.', null, [ACT.pronunciation]),
    createContentItem('잘 못 → [잘 몯]', 'jal mot', 'Three syllables in fast speech run together: [잘몯]. ㅅ받침 is unreleased.', 'word', '잘 못해요. → [잘 모태요]', 'I do not do it well.', null, [ACT.pronunciation]),

    createContentItem('만들다', 'mandeulda', 'to make', 'word', '김치를 만들 수 있어요.', 'I can make kimchi.', null, [ACT.vocabularySkills]),
    createContentItem('운전하다', 'unjeonhada', 'to drive', 'word', '저는 운전을 못해요.', 'I cannot drive.', null, [ACT.vocabularySkills]),
    createContentItem('수영하다', 'suyeonghada', 'to swim', 'word', '수영을 잘해요.', 'I swim well.', null, [ACT.vocabularySkills]),
    createContentItem('치다', 'chida', 'to play (instrument)', 'word', '피아노를 칠 수 있어요.', 'I can play piano.', null, [ACT.vocabularySkills]),
    createContentItem('타다', 'tada', 'to ride (bike/skate)', 'word', '자전거를 탈 수 있어요.', 'I can ride a bike.', null, [ACT.vocabularySkills]),
    createContentItem('말하다', 'malhada', 'to speak', 'word', '영어로 말할 수 있어요.', 'I can speak English.', null, [ACT.vocabularySkills]),
    createContentItem('읽다', 'ikda', 'to read', 'word', '한국어를 좀 읽을 수 있어요.', 'I can read Korean a bit.', null, [ACT.vocabularySkills]),
    createContentItem('쓰다', 'sseuda', 'to write', 'word', '한국어로 이메일을 쓸 수 있어요.', 'I can write Korean emails.', null, [ACT.vocabularySkills]),
    createContentItem('요리하다', 'yorihada', 'to cook', 'word', '저는 요리를 좀 해요.', 'I cook a bit.', null, [ACT.vocabularySkills]),
    createContentItem('노래하다', 'noraehada', 'to sing', 'word', '노래를 잘 못해요.', 'I do not sing well.', null, [ACT.vocabularySkills]),
    createContentItem('춤추다', 'chumchuda', 'to dance', 'word', '춤은 전혀 못 춰요.', 'I cannot dance at all.', null, [ACT.vocabularySkills]),
    createContentItem('피아노', 'piano', 'piano', 'word', '피아노를 좀 쳐요.', 'I play piano a bit.', null, [ACT.vocabularySkills]),
    createContentItem('기타', 'gita', 'guitar', 'word', '기타를 잘 못 쳐요.', 'I do not play guitar well.', null, [ACT.vocabularySkills]),

    createContentItem('잘', 'jal', 'well', 'word', '한국어를 잘해요.', 'I speak Korean well.', null, [ACT.vocabularyAdverbs]),
    createContentItem('좀', 'jom', 'a little', 'word', '한국어를 좀 해요.', 'I speak Korean a little.', null, [ACT.vocabularyAdverbs]),
    createContentItem('잘 못', 'jal mot', 'not well', 'word', '저는 노래를 잘 못해요.', 'I do not sing well.', null, [ACT.vocabularyAdverbs]),
    createContentItem('전혀 못', 'jeonhyeo mot', 'not at all', 'word', '저는 춤을 전혀 못 춰요.', 'I cannot dance at all.', null, [ACT.vocabularyAdverbs]),
    createContentItem('아직 못', 'ajik mot', 'cannot yet', 'word', '김치를 아직 못 만들어요.', 'I cannot make kimchi yet.', null, [ACT.vocabularyAdverbs]),
    createContentItem('진짜 / 정말 잘', 'really well', '진짜 / 정말 + 잘 = "really well".', 'word', '한국어를 정말 잘해요!', 'You speak Korean really well!', null, [ACT.vocabularyAdverbs]),

    createContentItem('V-(으)ㄹ 수 있다 — can', 'modal of ability', 'Attach -ㄹ 수 있다 (vowel) or -을 수 있다 (consonant) to a verb stem.', 'sentence', '김치를 만들 수 있어요.', 'I can make kimchi.',
      [
        { korean: '만들 + ㄹ 수 있다', english: '만들 (stem ends in ㄹ, so just add 수 있다)' },
        { korean: '먹 + 을 수 있다', english: '먹 (consonant) → 먹을 수 있다' },
      ],
      [ACT.grammarCanCannot]),
    createContentItem('V-(으)ㄹ 수 없다 — cannot', 'long form', 'Pair with 없다 for "cannot". More emphatic than 못.', 'sentence', '오늘은 갈 수 없어요. 약속이 있어서요.', 'I cannot go today. I have plans.',
      null, [ACT.grammarCanCannot]),
    createContentItem('Question form', 'check ability', '~ㄹ 수 있어요? = "Can you ~?"', 'sentence', '피아노를 칠 수 있어요? — 네, 좀 쳐요.', 'Can you play piano? — Yes, a bit.',
      null, [ACT.grammarCanCannot]),

    createContentItem('못 V — cannot (short)', 'mot', 'Place 못 directly before the verb. More common in speech than V-(으)ㄹ 수 없다.', 'sentence', '저는 운전 못해요.', 'I cannot drive.',
      [
        { korean: '못 + 가요 → 못 가요', english: 'cannot go' },
        { korean: '못 + 먹어요 → 못 먹어요', english: 'cannot eat' },
      ],
      [ACT.grammarMotVsAn]),
    createContentItem('못 vs 안 — inability vs choice', 'KEY contrast', '못 = "cannot" (lack of ability or external blocker). 안 = "do not" (chose not to).', 'sentence', '못 가요 = cannot go (blocked). 안 가요 = do not go (chose not to).', 'Critical distinction.',
      [
        { korean: '못 마셔요', english: 'cannot drink (allergic, sick)' },
        { korean: '안 마셔요', english: 'do not drink (personal choice)' },
      ],
      [ACT.grammarMotVsAn]),
    createContentItem('V하다 special pattern', 'N + 못해요', 'For -하다 verbs, 못 goes BETWEEN the noun and 해요: N 못해요.', 'sentence', '운전 못해요. (NOT 안 운전해요) · 공부 못해요.', 'I cannot drive. I cannot study (well).',
      [
        { korean: '공부 못해요', english: 'cannot study (well)' },
        { korean: '운동 못해요', english: 'cannot exercise' },
        { korean: '한국어 못해요', english: 'cannot speak Korean' },
      ],
      [ACT.grammarMotVsAn]),

    createContentItem('잘 V — do V well', 'high grade', 'Place 잘 before the verb.', 'sentence', '한국어를 잘 해요.', 'I speak Korean well.',
      null, [ACT.grammarGrade]),
    createContentItem('좀 V — V a little', 'mid grade', '좀 = "a little". Use to express modest ability.', 'sentence', '한국어를 좀 할 수 있어요.', 'I can speak a little Korean.',
      null, [ACT.grammarGrade]),
    createContentItem('잘 못 V — do not V well', 'low grade', 'Layer 잘 + 못 + V. Common in modest self-evaluation.', 'sentence', '저는 노래를 잘 못해요.', 'I do not sing well.',
      null, [ACT.grammarGrade]),
    createContentItem('전혀 못 V — cannot V at all', 'zero', '전혀 = "at all". Use with 못 to emphasize.', 'sentence', '저는 춤을 전혀 못 춰요.', 'I cannot dance at all.',
      null, [ACT.grammarGrade]),
    createContentItem('아직 못 V — cannot yet', 'in progress', 'Use 아직 + 못 + V to imply you are still learning.', 'sentence', '김치는 아직 못 만들어요.', 'I cannot make kimchi yet.',
      null, [ACT.grammarGrade]),

    createContentItem('Sarah\'s self-evaluation', 'reading',
      'Read aloud.',
      'sentence',
      '저는 사라예요. 미국에서 왔어요. 한국어는 좀 할 수 있어요. 영어는 잘해요. 김치는 아직 못 만들어요. 그런데 다른 음식은 잘해요. 피아노를 좀 쳐요. 운전은 못해요. 그래서 지하철을 타요.',
      'I am Sarah. I came from the USA. I can speak Korean a little. I speak English well. I cannot make kimchi yet. But I cook other food well. I play piano a bit. I cannot drive. So I take the subway.',
      [
        { korean: '한국어는 좀', english: 'Korean a little' },
        { korean: '아직 못', english: 'cannot yet' },
        { korean: '잘 / 좀 / 못', english: 'four levels of skill' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A', 'Use the ability forms.', 'sentence',
      'Q1: 사라는 한국어를 잘해요? · Q2: 김치를 만들 수 있어요? · Q3: 운전할 수 있어요?',
      'Q1: Does Sarah speak Korean well? Q2: Can she make kimchi? Q3: Can she drive?',
      [
        { korean: 'A1: 아니요, 좀 할 수 있어요.', english: 'No, she speaks a little.' },
        { korean: 'A2: 아직 못 만들어요.', english: 'She cannot yet.' },
        { korean: 'A3: 못해요.', english: 'She cannot.' },
      ],
      [ACT.reading]),

    createContentItem('Comparing abilities', 'listening',
      'Two friends compare skills.',
      'conversation',
      'A: 사라 씨, 한국어 잘 해요?\nB: 아니요, 잘 못해요. 좀 할 수 있어요.\nA: 한국에 온 지 얼마나 됐어요?\nB: 6개월 됐어요. 매일 공부해요.\nA: 멋있네요. 김치도 만들 수 있어요?\nB: 아니요, 김치는 아직 못 만들어요. 배우고 싶어요.\nA: 우리 같이 배워요. 어머니가 가르쳐 주실 거예요.\nB: 정말요? 좋아요.',
      'A: Sarah, do you speak Korean well? B: Not well. I can a little. A: How long in Korea? B: 6 months. Study daily. A: Cool. Can you make kimchi? B: Not yet. Want to learn. A: Let us learn together. My mom will teach. B: Really? Great.',
      [
        { korean: '아직 못 ~', english: 'still cannot ~' },
        { korean: '~ 고 싶어요', english: 'I want to ~' },
        { korean: '가르쳐 주실 거예요', english: 'will teach (honorific future)' },
      ],
      [ACT.listening]),
    createContentItem('Hobbies & abilities', 'listening',
      'Comparing music + sports skills.',
      'conversation',
      'A: 취미가 뭐예요?\nB: 저는 음악을 좋아해요. 기타를 좀 칠 수 있어요. 사라 씨는요?\nA: 저는 운동을 좋아해요. 수영을 잘해요.\nB: 와, 멋있네요. 저는 수영 못해요.\nA: 같이 배워요. 학교 수영장 있어요.\nB: 진짜요? 좋아요. 기타도 가르쳐 줄게요.\nA: 와! 좋아요.',
      'A: Hobby? B: Music. Guitar a bit. You? A: Sports. Swim well. B: Cool. I cannot swim. A: Let us learn together. There is a pool. B: Really? Great. I will teach guitar. A: Wow!',
      [
        { korean: '취미가 뭐예요?', english: 'what is your hobby?' },
        { korean: '같이 배워요', english: 'let us learn together' },
        { korean: '가르쳐 줄게요', english: 'I will teach you' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'skill template',
      'Use this structure.',
      'sentence',
      '저는 [활동1]을/를 잘해요. [활동2]을/를 좀 할 수 있어요. 그런데 [활동3]은/는 아직 못 해요. 앞으로 [활동4]을/를 배우고 싶어요.',
      '[strong] · [okay] · [not yet] · [want to learn]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 sentences listing your real skills. Use all four grades (잘 / 좀 / 아직 못 / 못).',
      'sentence', 'Example: 저는 영어를 잘해요. 한국어를 좀 할 수 있어요. 운전은 잘해요. 그런데 수영은 못해요. 다음에 배우고 싶어요.',
      'Example: I speak English well. Korean a little. I drive well. But I cannot swim. I want to learn next.',
      null, [ACT.writing]),

    createContentItem('Modest self-evaluation', 'culture',
      'Koreans typically understate their skills. If someone says "한국어 잘 하시네요!" (You speak Korean well!), the polite reply is "아니에요, 아직 잘 못해요." (No, I am not good yet). Direct self-praise comes across as arrogant.',
      'sentence', '한국어 잘 하시네요! — 아니에요, 아직 멀었어요.',
      'You speak Korean well! — No, I have a long way to go.',
      [{ korean: '아니에요', english: 'No (deflection)' }, { korean: '아직 멀었어요', english: 'I still have a long way' }], [ACT.culture]),

    createContentItem('과제: Club interview', 'task',
      'Roleplay: A 동아리 (club) leader asks about your skills. Use all four grades and at least one 못 V.',
      'conversation',
      'Leader: 동아리에 들어오고 싶어요? 어떤 거 잘해요?\nYou: [1 strong skill + 잘]\nLeader: 다른 건요?\nYou: [1 mid + 좀]\nLeader: 못하는 건 있어요?\nYou: [1 cannot + 못]\nLeader: 좋아요. 배우고 싶은 게 있어요?\nYou: [1 future + 배우고 싶어요]',
      'AI tutor will play the leader.',
      [
        { korean: '잘 V', english: 'do V well' },
        { korean: '좀 V', english: 'do V a little' },
        { korean: '못 V', english: 'cannot V' },
        { korean: '아직 못 V', english: 'cannot V yet' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
