// Level 2 Track-Adult Unit 5 — 얼마예요? (Buying in adult contexts)
// Source: Book 2A·5.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au5-orientation',
  pronunciation: 'l2au5-pronunciation',
  vocabularyShopping: 'l2au5-vocab-shop',
  vocabularyPayment: 'l2au5-vocab-pay',
  grammarPayment: 'l2au5-grammar-pay',
  grammarCommit: 'l2au5-grammar-commit',
  reading: 'l2au5-reading',
  listening: 'l2au5-listening',
  writing: 'l2au5-writing',
  culture: 'l2au5-culture',
  task: 'l2au5-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Buy daily necessities formally.', 'Choose card/cash payment.', 'Request refund or exchange with receipt.'],
    task: 'Imagine returning a shirt that does not fit at 이마트.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Shopping phrases',
    goals: ['Apply 격음화 in 환불 → [환불] (no change), 결제하겠습니다 → [결쩨하게씀니다] (경음화).'],
    task: 'Read each shopping phrase.' },
  { id: ACT.vocabularyShopping, section: 'Vocabulary I', title: 'Shopping items',
    goals: ['Use 편의점·마트·생필품·옷·신발·식료품.'],
    task: 'List 5 things you bought recently.' },
  { id: ACT.vocabularyPayment, section: 'Vocabulary II', title: 'Payment + service words',
    goals: ['Use 가격·계산·카드·현금·영수증·환불·교환·할인·포장.'],
    task: 'Use 5 payment-related words.' },
  { id: ACT.grammarPayment, section: 'Grammar I', title: 'N(으)로 결제하다 — pay by N',
    goals: ['Use N(으)로 for payment method.'],
    task: 'State 3 payment methods.' },
  { id: ACT.grammarCommit, section: 'Grammar II', title: 'V-(으)ㄹ게요 — I will (commitment)',
    goals: ['Use V-(으)ㄹ게요 for first-person commitment in service interactions.'],
    task: 'Make 3 commitments.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Receipt + refund policy',
    goals: ['Read a receipt and refund policy.'],
    task: 'Identify items, prices, refund window.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Refund request',
    goals: ['Follow a refund dialogue.'],
    task: 'Reproduce with your own item.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Refund email',
    goals: ['Write a 3-4 line refund-request email to an online store.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean shopping conventions',
    goals: ['Know 7-day refund policy.', 'Know 카카오페이 / 삼성페이 are common.'],
    task: 'Compare with your country.' },
  { id: ACT.task, section: 'Task', title: '과제 — Return + exchange',
    goals: ['Combine refund request + card payment.'],
    task: 'Roleplay returning a shirt.' },
];

const lesson = {
  title: '레벨 2 (직장) · 5과: 얼마입니까? (Buying Daily Necessities)',
  category: 'shopping',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'paying', label: 'Choosing payment', goal: 'Use 카드로 / 현금으로 결제하다.' },
    { id: 'asking-refund', label: 'Asking refund', goal: 'Use 환불받다 + V-고 싶다.' },
    { id: 'requesting-receipt', label: 'Requesting receipt', goal: 'Use 영수증 좀 주세요.' },
  ],
  relatedPools: ['topic-shopping'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: buy items, pay by method, request refund/exchange.', 'word', 'Functions: buy · pay · refund · commit', 'Shopping toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'You bought a shirt at 이마트 yesterday. It does not fit. You return it with the receipt for a refund.', 'word', 'You: 어제 산 셔츠인데 환불 가능합니까? — Staff: 영수증 있으세요?', 'You: Shirt I bought yesterday — refund? — Staff: Receipt?', null, [ACT.orientation]),

    createContentItem('결제하겠습니다 → [결쩨하게씀니다]', 'gyeoljehagetseumnida', '경음화 + 비음화.', 'word', '카드로 결제하겠습니다.', 'I will pay by card.', null, [ACT.pronunciation]),
    createContentItem('환불 → [환불]', 'hwanbul', 'No change.', 'word', '환불받고 싶습니다.', 'I want a refund.', null, [ACT.pronunciation]),
    createContentItem('할인 → [하린]', 'harin', '연음: ㄹ받침 jumps to 인.', 'word', '할인이 있습니다.', 'There is a discount.', null, [ACT.pronunciation]),
    createContentItem('영수증 → [영수증]', 'yeongsujeung', 'No change.', 'word', '영수증을 주십시오.', 'Receipt please.', null, [ACT.pronunciation]),

    createContentItem('편의점', 'pyeonuijeom', 'convenience store', 'word', '편의점에서 삽니다.', 'Buy at convenience store.', null, [ACT.vocabularyShopping]),
    createContentItem('마트', 'mateu', 'mart', 'word', '마트에서 장 봅니다.', 'I shop at the mart.', null, [ACT.vocabularyShopping]),
    createContentItem('생필품', 'saengpilpum', 'daily necessities', 'word', '생필품을 사야 합니다.', 'I need daily necessities.', null, [ACT.vocabularyShopping]),
    createContentItem('옷', 'ot', 'clothes', 'word', '새 옷을 샀어요.', 'I bought new clothes.', null, [ACT.vocabularyShopping]),
    createContentItem('신발', 'sinbal', 'shoes', 'word', '신발이 안 맞아요.', 'Shoes do not fit.', null, [ACT.vocabularyShopping]),
    createContentItem('식료품', 'singnyopum', 'groceries', 'word', '식료품을 샀어요.', 'I bought groceries.', null, [ACT.vocabularyShopping]),
    createContentItem('백화점', 'baekhwajeom', 'department store', 'word', '백화점은 비싸요.', 'Department stores are expensive.', null, [ACT.vocabularyShopping]),
    createContentItem('온라인 쇼핑몰', 'onrain syoping mol', 'online shopping mall', 'word', '온라인 쇼핑몰에서 주문합니다.', 'I order at online malls.', null, [ACT.vocabularyShopping]),

    createContentItem('가격', 'gagyeok', 'price', 'word', '가격이 어떻게 됩니까?', 'How much?', null, [ACT.vocabularyPayment]),
    createContentItem('계산', 'gyesan', 'payment', 'word', '계산해 주십시오.', 'Process payment.', null, [ACT.vocabularyPayment]),
    createContentItem('결제하다', 'gyeoljehada', 'to pay / settle', 'word', '카드로 결제할게요.', 'I will pay by card.', null, [ACT.vocabularyPayment]),
    createContentItem('카드', 'kadeu', 'card', 'word', '신용카드 있으세요?', 'Have a credit card?', null, [ACT.vocabularyPayment]),
    createContentItem('현금', 'hyeongeum', 'cash', 'word', '현금만 받습니다.', 'Cash only.', null, [ACT.vocabularyPayment]),
    createContentItem('영수증', 'yeongsujeung', 'receipt', 'word', '영수증을 주십시오.', 'Receipt please.', null, [ACT.vocabularyPayment]),
    createContentItem('환불', 'hwanbul', 'refund', 'word', '환불받고 싶습니다.', 'I want a refund.', null, [ACT.vocabularyPayment]),
    createContentItem('교환', 'gyohwan', 'exchange', 'word', '다른 사이즈로 교환합니다.', 'Exchange for different size.', null, [ACT.vocabularyPayment]),
    createContentItem('할인', 'harin', 'discount', 'word', '오늘은 할인이 있습니다.', 'Discount today.', null, [ACT.vocabularyPayment]),
    createContentItem('포장', 'pojang', 'wrapping', 'word', '포장해 주십시오.', 'Please wrap it.', null, [ACT.vocabularyPayment]),
    createContentItem('사이즈가 안 맞다', 'saijeu an matda', 'size does not fit', 'word', '사이즈가 안 맞아요.', 'Size doesn\'t fit.', null, [ACT.vocabularyPayment]),

    createContentItem('N(으)로 결제하다', 'pay by', 'Use (으)로 to specify payment method.', 'sentence', '카드로 결제하겠습니다.', 'I will pay by card.',
      [{ korean: '카드로', english: 'by card (vowel)' }, { korean: '현금으로', english: 'by cash (consonant)' }, { korean: '카카오페이로', english: 'by KakaoPay' }], [ACT.grammarPayment]),
    createContentItem('Other -(으)로 contexts', 'general means', 'Same particle used for transport (Unit 4) and method (here). Universal.', 'sentence', '버스로 (transport) · 카드로 (payment) · 한국어로 (language)', 'All means.',
      null, [ACT.grammarPayment]),

    createContentItem('V-(으)ㄹ게요 — I will (commit)', 'commitment', 'First-person commitment. Indicates intent + agreement.', 'sentence', '카드로 결제할게요.', 'I will pay by card.',
      [{ korean: '결제하 + ㄹ게요', english: '결제할게요' }, { korean: 'commits', english: 'first-person only' }, { korean: 'vs ~겠어요', english: 'V-겠어요 more formal, V-(으)ㄹ게요 personal' }], [ACT.grammarCommit]),
    createContentItem('Difference from V-(으)ㄹ 거예요', 'commitment vs prediction', 'V-(으)ㄹ게요 = "I commit". V-(으)ㄹ 거예요 = "I plan / it will".', 'sentence', '갈게요 (I commit to going) vs 갈 거예요 (I plan to go).', 'Different feel.',
      null, [ACT.grammarCommit]),

    createContentItem('Receipt + policy', 'reading',
      'Read this receipt.',
      'sentence',
      '이마트 영수증\n· 셔츠 (M사이즈) ₩29,000\n· 바지 ₩45,000\n· 비누 3개 ₩4,500\n· 합계 ₩78,500\n· 결제: 카드 (신한)\n· 환불 정책: 영수증 지참 시 구매 후 7일 이내 가능',
      'E-Mart Receipt:\n- Shirt (M) 29,000\n- Pants 45,000\n- Soap x3 4,500\n- Total 78,500\n- Paid: Card (Shinhan)\n- Refund policy: Within 7 days with receipt.',
      [
        { korean: '합계', english: 'total' },
        { korean: '환불 정책', english: 'refund policy' },
        { korean: '지참', english: 'bringing along' },
      ],
      [ACT.reading]),

    createContentItem('Refund dialogue', 'listening',
      'Returning a shirt.',
      'conversation',
      'A (직원): 무엇을 도와드릴까요?\nB (고객): 어제 산 셔츠인데요. 사이즈가 안 맞아서 환불받고 싶습니다.\nA: 영수증을 가지고 오셨어요?\nB: 네, 여기 있습니다.\nA: 카드로 결제하셨네요. 카드 환불해 드리겠습니다. 3-5일 정도 걸립니다.\nB: 알겠습니다. 감사합니다.\nA: 다음번에는 사이즈를 미리 확인하시면 좋겠습니다.',
      'A: How may I help? B: A shirt I bought yesterday. Size does not fit, refund please. A: Receipt? B: Yes, here. A: Paid by card. Will refund to card. 3-5 days. B: OK, thanks. A: Next time, check size in advance.',
      [
        { korean: '사이즈가 안 맞다', english: 'size does not fit' },
        { korean: '환불해 드리겠습니다', english: 'will refund (humble)' },
        { korean: '미리 확인하다', english: 'check in advance' },
      ],
      [ACT.listening]),

    createContentItem('Refund email', 'writing',
      'Sample request.',
      'sentence',
      '안녕하십니까. 11월 5일에 주문번호 12345로 주문한 셔츠인데요. 사이즈가 너무 작아서 환불받고 싶습니다. 카드로 결제했으니 카드로 환불해 주시면 감사하겠습니다. 영수증은 이메일에 첨부했습니다. 감사합니다.',
      'Hello. About shirt order #12345 placed Nov 5. Size too small, refund please. Paid by card; please refund to card. Receipt attached. Thanks.',
      null, [ACT.writing]),

    createContentItem('Korean shopping conventions', 'culture',
      'Korean stores typically allow refunds within 7 days with receipt. Online shops have stricter rules (often 14 days). Card payment is dominant — credit cards work for any purchase over 1,000 won. Mobile payments: 카카오페이, 네이버페이, 삼성페이.',
      'sentence', '한국은 카드 결제와 모바일 페이가 일반적이에요.',
      'Card and mobile payments are common in Korea.',
      [
        { korean: '카카오페이', english: 'KakaoPay' },
        { korean: '삼성페이', english: 'Samsung Pay' },
        { korean: '환불 7일 이내', english: 'refund within 7 days' },
      ],
      [ACT.culture]),

    createContentItem('과제: Return + exchange', 'task',
      'Roleplay: Return shoes. Get exchange or refund.',
      'conversation',
      'You: 어제 산 신발인데 안 맞아서 환불받고 싶습니다.\nStaff: 영수증 있으세요?\nYou: 네, 여기 있습니다.\nStaff: 카드 환불? 교환?\nYou: ~ㄹ게요 (commit one)\nStaff: 알겠습니다.',
      'AI tutor will play the staff.',
      [
        { korean: '~ 환불받고 싶습니다', english: 'want refund' },
        { korean: '~ 카드로 결제했습니다', english: 'paid by card' },
        { korean: '~ 교환할게요', english: 'will exchange' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
