// Level 2 Track-Adult Unit 12 — 함께 살 집이 필요합니다 (Housing search)
// Source: Book 2A·12.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au12-orientation',
  pronunciation: 'l2au12-pronunciation',
  vocabularyHousing: 'l2au12-vocab-housing',
  vocabularyContract: 'l2au12-vocab-contract',
  grammarModifier: 'l2au12-grammar-modifier',
  grammarOr: 'l2au12-grammar-or',
  reading: 'l2au12-reading',
  listening: 'l2au12-listening',
  writing: 'l2au12-writing',
  culture: 'l2au12-culture',
  task: 'l2au12-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Talk to a Korean real-estate agent.', 'Understand 월세 vs 전세 vs 보증금.', 'Sign a lease confidently.'],
    task: 'Imagine moving out of the company dorm to your own studio near Kumoh — you must navigate Korean real estate.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Housing terms',
    goals: ['Apply 격음화 in 월세 → [월쎄] (경음화), 보증금 → [보증금] (no change).'],
    task: 'Read each term aloud.' },
  { id: ACT.vocabularyHousing, section: 'Vocabulary I', title: 'Housing types',
    goals: ['Use 집·아파트·원룸·투룸·고시원·오피스텔·빌라.'],
    task: 'Describe ideal housing.' },
  { id: ACT.vocabularyContract, section: 'Vocabulary II', title: 'Lease + contract',
    goals: ['Use 월세·전세·보증금·관리비·계약·이사·부동산·중개사·임대차계약서.'],
    task: 'Use 5 contract words.' },
  { id: ACT.grammarModifier, section: 'Grammar I', title: 'V-(으)ㄹ + N — N to V',
    goals: ['Form a future-modifier clause.', 'Use for "place to live, person to meet, things to do".'],
    task: 'Make 3 future-modifier phrases.' },
  { id: ACT.grammarOr, section: 'Grammar II', title: 'N(이)나 N — N or N',
    goals: ['Express alternatives between nouns.'],
    task: 'Offer 3 pairs of alternatives.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Lease contract',
    goals: ['Read a sample 임대차계약서.'],
    task: 'Find rent, deposit, term.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Real-estate visit',
    goals: ['Follow a real-estate dialogue.'],
    task: 'Reproduce with your needs.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Housing-search request',
    goals: ['Write a 4-5 line request email to a 부동산.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — 전세 vs 월세 + 외국인 등록증',
    goals: ['Understand 전세 (huge upfront deposit, no rent) vs 월세.', 'Know 외국인 등록증 is required for any lease.'],
    task: 'Plan first-month housing costs.' },
  { id: ACT.task, section: 'Task', title: '과제 — Real-estate visit',
    goals: ['Combine question + describe needs + read lease.'],
    task: 'Roleplay finding a studio.' },
];

const lesson = {
  title: '레벨 2 (직장) · 12과: 함께 살 집이 필요합니다 (Housing Search)',
  category: 'shopping',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'asking-rent', label: 'Asking rent + deposit', goal: 'Use 월세 / 보증금 / 전세.' },
    { id: 'reading-contract', label: 'Reading lease', goal: 'Locate 월세·보증금·기간 fields.' },
    { id: 'describing-needs', label: 'Describing needs', goal: 'Use V-(으)ㄹ + N to describe future use.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: navigate Korean real estate confidently — find studio, understand lease, sign contract.', 'word', 'Functions: ask · compare · read lease · sign', 'Housing toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'You want to move out of the company dorm into your own studio near Kumoh. Visit a 부동산 and negotiate.', 'word', 'Agent: 보증금과 월세 예산은요? — You: 500만 원과 40만 원입니다.', 'Agent: Deposit + rent budget? — You: 5M + 400K.', null, [ACT.orientation]),

    createContentItem('월세 → [월쎄]', 'wolsse', '경음화: ㄹ-받침 + ㅅ → ㄹ + ㅆ.', 'word', '월세가 40만 원이에요.', 'Rent is 400K.', null, [ACT.pronunciation]),
    createContentItem('보증금 → [보증금]', 'bojeunggeum', 'No major change.', 'word', '보증금이 큽니다.', 'Deposit is large.', null, [ACT.pronunciation]),
    createContentItem('임대차 → [임대차]', 'imdaecha', 'No change.', 'word', '임대차계약서', 'lease contract.', null, [ACT.pronunciation]),
    createContentItem('원룸 → [원눔]', 'wonnum', '비음화: ㄴ-받침 + ㄹ → ㄴ + ㄴ.', 'word', '원룸을 찾아요.', 'Looking for studio.', null, [ACT.pronunciation]),

    createContentItem('집', 'jip', 'house', 'word', '새 집을 찾아요.', 'Looking for new place.', null, [ACT.vocabularyHousing]),
    createContentItem('아파트', 'apateu', 'apartment', 'word', '아파트에 살아요.', 'Live in apartment.', null, [ACT.vocabularyHousing]),
    createContentItem('원룸', 'wonrum', 'studio', 'word', '원룸이 좋아요.', 'Studio is good.', null, [ACT.vocabularyHousing]),
    createContentItem('투룸', 'turum', 'two-room', 'word', '투룸도 괜찮아요.', 'Two-room is OK.', null, [ACT.vocabularyHousing]),
    createContentItem('고시원', 'gosiwon', 'goshiwon (tiny single)', 'word', '고시원은 작아요.', 'Goshiwon is small.', null, [ACT.vocabularyHousing]),
    createContentItem('오피스텔', 'opiseutel', 'officetel (studio + office)', 'word', '오피스텔이 깨끗해요.', 'Officetel is clean.', null, [ACT.vocabularyHousing]),
    createContentItem('빌라', 'billa', 'villa (low-rise apt)', 'word', '빌라가 저렴해요.', 'Villa is cheap.', null, [ACT.vocabularyHousing]),
    createContentItem('동네', 'dongne', 'neighborhood', 'word', '동네가 조용해요.', 'Quiet neighborhood.', null, [ACT.vocabularyHousing]),

    createContentItem('월세', 'wolse', 'monthly rent', 'word', '월세가 50만 원이에요.', 'Rent 500K.', null, [ACT.vocabularyContract]),
    createContentItem('전세', 'jeonse', 'jeonse (lump-sum)', 'word', '전세는 보증금이 커요.', 'Jeonse: huge deposit.', null, [ACT.vocabularyContract]),
    createContentItem('보증금', 'bojeunggeum', 'deposit', 'word', '보증금이 1,000만 원이에요.', 'Deposit 10M.', null, [ACT.vocabularyContract]),
    createContentItem('관리비', 'gwallibi', 'maintenance fee', 'word', '관리비는 별도예요.', 'Maintenance separate.', null, [ACT.vocabularyContract]),
    createContentItem('계약', 'gyeyak', 'contract', 'word', '계약 전에 확인하세요.', 'Check before contract.', null, [ACT.vocabularyContract]),
    createContentItem('계약 기간', 'gyeyak gigan', 'contract length', 'word', '계약 기간은 2년입니다.', 'Contract is 2 years.', null, [ACT.vocabularyContract]),
    createContentItem('부동산', 'budongsan', 'real-estate office', 'word', '부동산에 갑니다.', 'Go to real estate.', null, [ACT.vocabularyContract]),
    createContentItem('중개사', 'junggaesa', 'real-estate agent', 'word', '중개사가 친절해요.', 'Agent is friendly.', null, [ACT.vocabularyContract]),
    createContentItem('임대차계약서', 'imdaechagyeyakseo', 'lease contract', 'word', '임대차계약서를 읽어요.', 'Read lease.', null, [ACT.vocabularyContract]),
    createContentItem('이사하다', 'isahada', 'to move', 'word', '다음 주에 이사해요.', 'Move next week.', null, [ACT.vocabularyContract]),
    createContentItem('외국인 등록증', 'oegugin deungrokjeung', 'alien reg card', 'word', '외국인 등록증이 필요해요.', 'Need ARC.', null, [ACT.vocabularyContract]),

    createContentItem('V-(으)ㄹ + N — N to V', 'future modifier', 'Attach -ㄹ (vowel) or -을 (consonant) to verb stem; modify the noun. Future/purpose meaning.', 'sentence', '함께 살 집이 필요합니다.', 'I need a place to live in together.',
      [
        { korean: '살 + N', english: 'place to live' },
        { korean: '만날 + N', english: 'person to meet' },
        { korean: '할 + N', english: 'thing to do' },
      ],
      [ACT.grammarModifier]),
    createContentItem('Compare with V-(으)ㄴ + N (past)', 'present vs past modifier', 'V-(으)ㄴ + N = past modifier ("the book I read"). V-(으)ㄹ + N = future modifier ("the book I will read").', 'sentence', '읽은 책 (read book) vs 읽을 책 (book to read).', 'Different tense.',
      null, [ACT.grammarModifier]),

    createContentItem('N(이)나 N — N or N', 'alternatives', 'Express alternatives between nouns. (이)나 after consonant, 나 after vowel.', 'sentence', '월세나 전세나 어떤 게 좋습니까?', 'Which is better, monthly rent or jeonse?',
      [{ korean: '월세 + 나', english: 'or jeonse (vowel)' }, { korean: '집 + 이나', english: 'or house (consonant)' }], [ACT.grammarOr]),

    createContentItem('Lease contract', 'reading',
      'Read this sample 임대차계약서.',
      'sentence',
      '임대차계약서\n· 임대인: 김 ◯◯\n· 임차인: 사라 ◯◯◯\n· 주소: 경상북도 구미시 ◯◯로 ◯◯ 301호\n· 보증금: 5,000,000원\n· 월세: 400,000원 (매월 1일 납부)\n· 관리비: 별도 50,000원\n· 계약 기간: 2026.05.11 ~ 2028.05.10 (2년)\n· 외국인 등록증 사본 첨부 필수',
      'Lease Contract:\n- Landlord: Kim\n- Tenant: Sarah\n- Address: Gyeongbuk Gumi ~ Apt 301\n- Deposit: 5,000,000\n- Rent: 400,000 (1st of each month)\n- Maintenance: 50,000 separate\n- Term: 2026.05.11 - 2028.05.10 (2 years)\n- Required: copy of ARC.',
      [
        { korean: '임대인', english: 'landlord' },
        { korean: '임차인', english: 'tenant' },
        { korean: '납부', english: 'payment' },
        { korean: '필수', english: 'required' },
      ],
      [ACT.reading]),

    createContentItem('Real-estate visit', 'listening',
      'Finding a studio.',
      'conversation',
      'A (사라): 안녕하세요. 원룸을 좀 알아보고 싶습니다.\nB (중개사): 어느 동네를 원하시나요?\nA: 금오공과대학교 근처면 좋습니다. 회사 셔틀을 타고 다닐 거예요.\nB: 보증금과 월세 예산은 어느 정도이십니까?\nA: 보증금은 500만 원, 월세는 40만 원 정도입니다.\nB: 그 조건에 맞는 원룸이 두 개 있습니다. 같이 보러 가실까요?\nA: 네, 좋습니다. 그런데 계약 기간은 보통 어떻게 됩니까?\nB: 보통 1년이나 2년입니다. 임대차계약서를 잘 읽고 사인하시면 됩니다.',
      'A: Hello. Want to look at studios. B: Which neighborhood? A: Near Kumoh. Will commute by shuttle. B: Deposit + rent budget? A: 5M + 400K. B: I have 2 studios matching. Go see them? A: Yes. Contract length? B: 1 or 2 years usually. Read lease + sign.',
      [
        { korean: '예산', english: 'budget' },
        { korean: 'N(이)나 N', english: 'N or N' },
        { korean: '계약 기간', english: 'contract length' },
      ],
      [ACT.listening]),

    createContentItem('Housing-search request', 'writing',
      'Sample request to agent.',
      'sentence',
      '안녕하세요. 사라입니다. 금오공과대학교 근처에 원룸을 찾고 있습니다. 보증금은 500만 원, 월세는 40만 원 정도가 좋습니다. 계약 기간은 1년이나 2년 둘 다 괜찮습니다. 함께 살 룸메이트는 없고 혼자 살 거예요. 추천해 주실 수 있는 매물이 있으면 알려 주시면 감사하겠습니다.',
      'Hello. Sarah. Looking for studio near Kumoh. Deposit 5M, rent 400K. Contract 1 or 2 years OK. No roommate — living alone. Please let me know if you have recommendations.',
      null, [ACT.writing]),

    createContentItem('전세 vs 월세', 'culture',
      '전세 (jeonse) = lump-sum deposit (often 50-80% of property value), NO monthly rent. Returned in full at end. 월세 = small deposit + monthly rent. Foreigners typically can\'t get 전세 without strong credit history. 외국인 등록증 is required for any lease.',
      'sentence', '한국에는 전세와 월세 두 가지가 있어요. 외국인은 월세가 일반적이에요.',
      'Korea has 전세 and 월세. Foreigners typically do 월세.',
      [
        { korean: '전세', english: 'lump-sum lease (no rent)' },
        { korean: '월세', english: 'monthly rent' },
        { korean: '외국인 등록증', english: 'alien registration card' },
      ],
      [ACT.culture]),

    createContentItem('과제: Real-estate visit', 'task',
      'Roleplay: Visit a Gumi 부동산 to find a studio.',
      'conversation',
      'You: 안녕하세요. 함께 살 집을 찾고 있는데요.\nAgent: 어디서 사실 거예요?\nYou: 금오공대 근처에 살 원룸을 찾고 있어요.\nAgent: 예산은요?\nYou: 보증금 N, 월세 N입니다. 계약 기간은 1년이나 2년 둘 다 괜찮아요.\nAgent: 그 조건의 매물이 있어요. 보러 가시겠어요?\nYou: 네. 그런데 임대차계약서는 어떻게 됩니까?\nAgent: 보통 N에 사인하시면 돼요.',
      'AI tutor will play the agent.',
      [
        { korean: 'V-(으)ㄹ + N', english: 'future modifier' },
        { korean: 'N(이)나 N', english: 'or' },
        { korean: '월세 / 전세 / 보증금', english: 'housing terms' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
