// Level 1 Unit 9 — Ordering food
// Sources: Book 1A·12 (우리 뭐 먹을까?) + Book 1B·7 (불고기 이 인분 주세요)
// Functions: ordering at a restaurant, asking what to eat, paying.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u9-orientation',
  pronunciation: 'l1u9-pronunciation',
  vocabularyDishes: 'l1u9-vocab-dishes',
  vocabularyTable: 'l1u9-vocab-table',
  grammarSuggest: 'l1u9-grammar-suggest',
  grammarOrder: 'l1u9-grammar-order',
  grammarMore: 'l1u9-grammar-more',
  reading: 'l1u9-reading',
  listening: 'l1u9-listening',
  writing: 'l1u9-writing',
  culture: 'l1u9-culture',
  task: 'l1u9-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Suggest a meal with V-(으)ㄹ까요?.', 'Order Korean food using N + 인분/개.', 'Ask for more and settle the bill.'],
    task: 'Imagine taking your professor out for kimchi-jjigae — you need to suggest, order, request side dishes, and pay.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Restaurant phrases',
    goals: ['Apply 비음화 in 갑니다 → [감니다], 먹을까요 → [머글까요].'],
    task: 'Read each phrase aloud.' },
  { id: ACT.vocabularyDishes, section: 'Vocabulary I', title: 'Korean dishes',
    goals: ['Recognize 12+ iconic Korean dishes.'],
    task: 'Pick three you would order tonight.' },
  { id: ACT.vocabularyTable, section: 'Vocabulary II', title: 'Table & service words',
    goals: ['Use 메뉴·반찬·물·계산·인분·자리·음료수.'],
    task: 'Read a Korean menu and identify each table-side word.' },
  { id: ACT.grammarSuggest, section: 'Grammar I', title: 'V-(으)ㄹ까요? — Shall we V?',
    goals: ['Attach -ㄹ까요 (vowel) / -을까요 (consonant) to make suggestions.', 'Use 어디·뭐·언제 + V-(으)ㄹ까요? for open suggestions.'],
    task: 'Make three V-(으)ㄹ까요? suggestions.' },
  { id: ACT.grammarOrder, section: 'Grammar II', title: 'Ordering: N + 인분/개 + 주세요',
    goals: ['Use 인분 for restaurant portions (Sino-Korean number).', 'Use 개 / 잔 / 그릇 for other countables.', 'Stack multiple items with 하고.'],
    task: 'Make a two-item order with the right counters.' },
  { id: ACT.grammarMore, section: 'Grammar III', title: '더 / 좀 더 / 계산해 주세요',
    goals: ['Use 더 (more), 좀 더 (a bit more), and 또 (one more).', 'Ask for the bill with 계산해 주세요 and answer 카드/현금.'],
    task: 'Ask for two extra items and settle the bill.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — A dinner review',
    goals: ['Read a 4-5 sentence restaurant review.'],
    task: 'Identify the restaurant, dishes, prices, and verdict.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Two restaurant scenes',
    goals: ['Follow a suggest+order dialogue and an order+pay dialogue.'],
    task: 'Reproduce with your own choices.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Recommend a Korean dish',
    goals: ['Write 4-5 sentences recommending a dish to a friend.'],
    task: 'Write your own recommendation.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — 반찬, 회식, and who pays',
    goals: ['Understand 무한 reflls of 반찬 (side dishes).', 'Know that the senior typically pays at 회식 (work dinners).'],
    task: 'Decide who should pay in three scenarios.' },
  { id: ACT.task, section: 'Task', title: '과제 — Take a friend to dinner',
    goals: ['Combine suggestion, order, request, and payment in one continuous scene.'],
    task: 'Roleplay a full dinner at a Korean restaurant.' },
];

const lesson = {
  title: '레벨 1 · 9과: 불고기 이 인분 주세요 (Ordering Food)',
  category: 'food',
  difficulty: 'beginner',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'suggesting-food', label: 'Suggesting what to eat', goal: 'Use V-(으)ㄹ까요? to suggest a dish or restaurant.' },
    { id: 'ordering-food', label: 'Ordering food', goal: 'State dish + 인분/개 + 주세요 to order.' },
    { id: 'paying-bill', label: 'Paying the bill', goal: 'Use 계산해 주세요 to settle.' },
    { id: 'asking-more', label: 'Asking for more', goal: 'Use 좀 더 + N + 주세요 to ask for extra.' },
  ],
  relatedPools: ['topic-food'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: suggest a dish, order with the right counter, ask for sides/refills, and pay.', 'word', 'Functions: suggest · order · request · pay', 'Four restaurant micro-skills.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'A Korean friend asks "오늘 저녁 뭐 먹을까요?" You should suggest, choose a place, order for two, and settle the bill.', 'word', 'Friend: 뭐 먹을까요? — You: 김치찌개 먹을까요? 학교 앞 식당이 좋아요.', 'Friend: What shall we eat? — You: Shall we have kimchi stew? The restaurant in front of school is good.', null, [ACT.orientation]),

    createContentItem('먹을까요 → [머글까요]', 'meogeulkkayo', '연음 + 경음화: ㄱ받침 of 먹 jumps to 을, then ㄲ tensifies in 까요.', 'word', '뭐 먹을까요? → [뭐 머글까요]', 'What shall we eat?', null, [ACT.pronunciation]),
    createContentItem('갑니다 → [감니다]', 'gamnida', '비음화: ㅂ받침 + ㄴ → ㅁ + ㄴ.', 'word', '같이 갑니다. → [감니다]', 'I will go with you.', null, [ACT.pronunciation]),
    createContentItem('계산해 → [게사내]', 'gyesanae', '연음: ㄴ받침 of 산 jumps to ㅎ — then ㅎ disappears.', 'word', '계산해 주세요. → [게사내 주세요]', 'Please bring the bill.', null, [ACT.pronunciation]),
    createContentItem('맛있어요 → [마시써요]', 'masisseoyo', '연음: ㅅ받침 jumps to 있; tense ㅆ stays.', 'word', '정말 맛있어요. → [정말 마시써요]', 'Really delicious.', null, [ACT.pronunciation]),

    createContentItem('식당', 'sikdang', 'restaurant', 'word', '학교 근처 식당이 좋아요.', 'The restaurant near school is nice.', null, [ACT.vocabularyDishes]),
    createContentItem('불고기', 'bulgogi', 'bulgogi (marinated beef)', 'word', '불고기를 좋아해요.', 'I like bulgogi.', null, [ACT.vocabularyDishes]),
    createContentItem('비빔밥', 'bibimbap', 'bibimbap', 'word', '점심에 비빔밥을 먹어요.', 'I eat bibimbap for lunch.', null, [ACT.vocabularyDishes]),
    createContentItem('김치찌개', 'gimchijjigae', 'kimchi stew', 'word', '오늘 저녁은 김치찌개예요.', 'Tonight\'s dinner is kimchi stew.', null, [ACT.vocabularyDishes]),
    createContentItem('된장찌개', 'doenjangjjigae', 'soybean-paste stew', 'word', '된장찌개도 좋아해요.', 'I like soybean-paste stew too.', null, [ACT.vocabularyDishes]),
    createContentItem('떡볶이', 'tteokbokki', 'tteokbokki (spicy rice cake)', 'word', '떡볶이는 매워요.', 'Tteokbokki is spicy.', null, [ACT.vocabularyDishes]),
    createContentItem('김밥', 'gimbap', 'gimbap (seaweed roll)', 'word', '김밥 두 줄 주세요.', 'Two rolls of gimbap please.', null, [ACT.vocabularyDishes]),
    createContentItem('라면', 'ramyeon', 'instant ramen', 'word', '라면 한 그릇 주세요.', 'One bowl of ramen please.', null, [ACT.vocabularyDishes]),
    createContentItem('갈비', 'galbi', 'short ribs (Korean BBQ)', 'word', '갈비 이 인분 주세요.', 'Two servings of galbi please.', null, [ACT.vocabularyDishes]),
    createContentItem('삼겹살', 'samgyeopsal', 'grilled pork belly', 'word', '삼겹살이 인기예요.', 'Samgyeopsal is popular.', null, [ACT.vocabularyDishes]),
    createContentItem('순두부찌개', 'sundubujjigae', 'soft-tofu stew', 'word', '순두부찌개도 맛있어요.', 'Soft-tofu stew is also delicious.', null, [ACT.vocabularyDishes]),
    createContentItem('잡채', 'japchae', 'glass-noodle stir-fry', 'word', '잡채는 달콤해요.', 'Japchae is sweet.', null, [ACT.vocabularyDishes]),

    createContentItem('밥', 'bap', 'rice / meal', 'word', '밥 좀 더 주세요.', 'Please give me more rice.', null, [ACT.vocabularyTable]),
    createContentItem('국', 'guk', 'soup', 'word', '국이 따뜻해요.', 'The soup is warm.', null, [ACT.vocabularyTable]),
    createContentItem('반찬', 'banchan', 'side dish', 'word', '반찬이 많아요.', 'There are many side dishes.', null, [ACT.vocabularyTable]),
    createContentItem('물', 'mul', 'water', 'word', '물 좀 주세요.', 'Please give me some water.', null, [ACT.vocabularyTable]),
    createContentItem('-인분', '-inbun', 'serving (counter)', 'word', '불고기 이 인분 주세요.', 'Two servings of bulgogi.', null, [ACT.vocabularyTable]),
    createContentItem('-그릇', '-geureut', 'bowl (counter)', 'word', '비빔밥 두 그릇 주세요.', 'Two bowls of bibimbap.', null, [ACT.vocabularyTable]),
    createContentItem('-줄', '-jul', 'roll (counter for gimbap)', 'word', '김밥 한 줄', 'one roll of gimbap', null, [ACT.vocabularyTable]),
    createContentItem('메뉴', 'menyu', 'menu', 'word', '메뉴 좀 주세요.', 'Please give me the menu.', null, [ACT.vocabularyTable]),
    createContentItem('음료수', 'eumryosu', 'beverage', 'word', '음료수도 시킬까요?', 'Shall we order drinks too?', null, [ACT.vocabularyTable]),
    createContentItem('계산하다', 'gyesanhada', 'to settle / pay the bill', 'word', '계산해 주세요.', 'Please bring the bill.', null, [ACT.vocabularyTable]),
    createContentItem('맛있다', 'masitda', 'to be delicious', 'word', '정말 맛있어요!', 'Really delicious!', null, [ACT.vocabularyTable]),

    createContentItem('V-(으)ㄹ까요? — Shall we?', 'kkayo', 'Attach -ㄹ까요 (vowel) or -을까요 (consonant) to a verb stem to make a suggestion.', 'sentence', '뭐 먹을까요? — 비빔밥 먹을까요?', 'What shall we eat? — Shall we have bibimbap?',
      [
        { korean: '먹 + 을까요', english: '먹 (consonant) → 먹을까요' },
        { korean: '가 + ㄹ까요', english: '가 (vowel) → 갈까요' },
        { korean: '마시 + ㄹ까요', english: '마시 (vowel) → 마실까요' },
      ],
      [ACT.grammarSuggest]),
    createContentItem('Open suggestion with 어디/뭐/언제', 'wh-question + 을까요', 'Combine question words for an open suggestion: where shall we ~? what shall we ~?', 'sentence', '어디에 갈까요? — 학교 근처 식당에 갈까요?', 'Where shall we go? — Shall we go near the school?',
      null, [ACT.grammarSuggest]),

    createContentItem('Sino + 인분 → restaurant servings', 'inbun', 'Use Sino-Korean numbers + 인분 ONLY for restaurant portions.', 'sentence', '불고기 이 인분 주세요.', 'Two servings of bulgogi.',
      [{ korean: '이 인분', english: 'two servings (이 = Sino 2)' }, { korean: '삼 인분', english: 'three servings' }], [ACT.grammarOrder]),
    createContentItem('Native + 개/그릇/잔/줄', 'native + counter', 'Use Native-Korean numbers with most other counters.', 'sentence', '비빔밥 두 그릇하고 물 한 잔 주세요.', 'Two bowls of bibimbap and one glass of water.',
      [{ korean: '두 그릇', english: 'two bowls (Native)' }, { korean: '한 잔', english: 'one cup (Native)' }, { korean: '두 줄', english: 'two rolls' }], [ACT.grammarOrder]),
    createContentItem('Stack multiple items with 하고', 'and', 'Use 하고 (or 와/과) to chain multiple orders.', 'sentence', '불고기 이 인분하고 김치찌개 하나 주세요.', 'Two bulgogi and one kimchi stew please.',
      null, [ACT.grammarOrder]),

    createContentItem('더 — more', 'deo', 'Place 더 before a noun or verb for "more".', 'sentence', '밥 좀 더 주세요. = 밥을 더 주세요.', 'Please give me more rice.',
      null, [ACT.grammarMore]),
    createContentItem('또 — one more / again', 'tto', 'Use 또 for "one more" or "another".', 'sentence', '같은 거 또 주세요.', 'Please give me the same one again.',
      null, [ACT.grammarMore]),
    createContentItem('계산해 주세요', 'check please', 'Standard line for paying. Pair with 카드/현금.', 'sentence', '계산해 주세요. 카드로 할게요.', 'Please bring the bill. I will pay by card.',
      [
        { korean: '카드로', english: 'by card' },
        { korean: '현금으로', english: 'by cash' },
        { korean: '계좌이체', english: 'bank transfer' },
      ],
      [ACT.grammarMore]),

    createContentItem('A dinner review', 'reading',
      'Read aloud, then answer.',
      'sentence',
      '어제 친구와 학교 앞 한식당에 갔어요. 김치찌개 한 그릇하고 불고기 이 인분을 시켰어요. 김치찌개는 좀 매웠지만 정말 맛있었어요. 반찬도 많아서 좋았어요. 모두 28,000원이었어요. 다음에 또 갈 거예요.',
      'Yesterday I went to a Korean restaurant in front of the school with a friend. We ordered one kimchi stew and two servings of bulgogi. The kimchi stew was a bit spicy but really delicious. There were lots of side dishes, which was great. Total was 28,000 won. We will go again.',
      [
        { korean: '시켰어요', english: 'ordered (past)' },
        { korean: '매웠지만 맛있었어요', english: 'was spicy but delicious' },
        { korean: '반찬도 많아서', english: 'because there were many sides' },
      ],
      [ACT.reading]),
    createContentItem('Comprehension', 'Q&A',
      'Answer based on the paragraph.',
      'sentence',
      'Q1: 어디에 갔어요? · Q2: 뭐 시켰어요? · Q3: 얼마였어요?',
      'Q1: Where? Q2: What did they order? Q3: How much?',
      [
        { korean: 'A1: 학교 앞 한식당에 갔어요.', english: 'A Korean restaurant in front of school.' },
        { korean: 'A2: 김치찌개와 불고기를 시켰어요.', english: 'Kimchi stew and bulgogi.' },
        { korean: 'A3: 28,000원이었어요.', english: '28,000 won.' },
      ],
      [ACT.reading]),

    createContentItem('Suggest a dinner', 'listening',
      'Two friends decide where to eat.',
      'conversation',
      'A: 저녁에 뭐 먹을까요?\nB: 학교 근처에 한식당이 있어요. 거기에 갈까요?\nA: 좋아요. 뭐가 맛있어요?\nB: 김치찌개가 정말 맛있어요. 불고기도 괜찮아요.\nA: 그럼 김치찌개 먹을까요?\nB: 좋아요. 같이 가요.',
      'A: What shall we eat? B: There is a Korean restaurant near school. Shall we go? A: Sure. What\'s good? B: Kimchi stew is great. Bulgogi is also good. A: Then shall we have kimchi stew? B: Sure, let us go.',
      [
        { korean: 'V-(으)ㄹ까요?', english: 'shall we V?' },
        { korean: '뭐가 맛있어요?', english: 'what is good?' },
        { korean: '괜찮아요', english: 'is okay/good' },
      ],
      [ACT.listening]),
    createContentItem('Order + pay', 'listening',
      'Full restaurant flow.',
      'conversation',
      'A (직원): 어서 오세요. 몇 분이세요?\nB (손님): 두 명이에요.\nA: 이쪽으로 앉으세요. 메뉴 여기 있습니다.\nB: 불고기 이 인분하고 김치찌개 하나 주세요. 물도 두 잔이요.\nA: 음료수는요?\nB: 음료수는 괜찮아요. ... (식사 후) 계산해 주세요.\nA: 모두 28,000원입니다. 어떻게 계산하시겠어요?\nB: 카드로 할게요.',
      'A: Welcome. How many? B: Two. A: This way please. Menu here. B: Two bulgogi, one kimchi stew, two waters. A: Drinks? B: No drinks. ... (after) Check please. A: 28,000 won. Pay how? B: Card.',
      [
        { korean: '몇 분이세요?', english: 'how many of you? (honorific)' },
        { korean: '음료수는요?', english: 'how about drinks?' },
        { korean: '어떻게 계산하시겠어요?', english: 'how would you like to pay?' },
      ],
      [ACT.listening]),

    createContentItem('Writing model', 'template',
      'Use this to structure your recommendation.',
      'sentence',
      '저는 [장소]을/를 추천해요. 거기에서 [요리]을/를 꼭 드세요. [수+인분/그릇]이면 [N]명이 같이 먹을 수 있어요. 가격은 [수]원이에요. 반찬도 [형용사].',
      '[place] · [dish] · [serving size] · [price] · [side-dish comment]',
      null, [ACT.writing]),
    createContentItem('Writing prompt', 'your turn',
      'Write 4-5 sentences recommending a Korean dish or restaurant. Include one V-(으)ㄹ까요? suggestion and one price.',
      'sentence', 'Example: 저는 김치찌개를 추천해요. 매워요. 그런데 정말 맛있어요. 학교 앞 식당에서 한 그릇에 8,000원이에요. 같이 먹을까요?',
      'Example: I recommend kimchi stew. It is spicy. But really good. At the restaurant in front of school, one bowl is 8,000 won. Shall we go together?',
      null, [ACT.writing]),

    createContentItem('무한 리필 반찬', 'culture',
      'Korean restaurants serve 반찬 (side dishes) for free, and you can ask for refills: "반찬 좀 더 주세요". Standard sides include 김치, 시금치나물, 콩나물, 깍두기.',
      'sentence', '반찬은 무료예요. 더 달라고 하세요.', 'Sides are free. Just ask for refills.',
      [{ korean: '반찬', english: 'side dishes' }, { korean: '무료', english: 'free' }, { korean: '리필', english: 'refill' }], [ACT.culture]),
    createContentItem('회식 culture & who pays', 'culture',
      'At a Korean 회식 (work dinner), the most senior person traditionally pays. Among friends, the inviter or the older friend usually picks up the bill. "내가 살게요" = "I\'ll pay."',
      'sentence', '회식에서는 보통 가장 높은 분이 계산해요.', 'At work dinners, the senior usually pays.',
      [{ korean: '회식', english: 'work dinner' }, { korean: '내가 살게요', english: 'I will pay' }], [ACT.culture]),

    createContentItem('과제: Take a friend to dinner', 'task',
      'Roleplay: Suggest a restaurant, order for two, request more sides, and settle the bill.',
      'conversation',
      'You: [suggest place + dish with V-(으)ㄹ까요?]\nFriend: 좋아요. 가요.\n[server greets]\nYou: [order 2 items with right counters]\nServer: 음료수는요?\nYou: [answer + ask for water]\n[end of meal]\nYou: [ask for the check + pay by card]',
      'AI tutor will play the friend and the server.',
      [
        { korean: '~ 먹을까요?', english: 'shall we eat ~?' },
        { korean: '~ 인분 / ~ 그릇 / ~ 잔 주세요', english: 'order phrases' },
        { korean: '계산해 주세요. 카드로 할게요.', english: 'check please. By card.' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
