// Level 2 Unit 3 — 스포츠의 세계 (World of sports)
// Source: Book 2D Unit 3. Vocab: 운동 경기, 승부와 상황.
// Grammar: V-(으)나 마나, V-는 바람에, N(이)라는 N, N에 비해(서).
// Pronunciation: 경음화 '바쁠걸요'. Culture: 씨름 (Korean wrestling).

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2u3-orientation',
  vocabulary: 'l2u3-vocabulary',
  pronunciation: 'l2u3-pronunciation',
  grammar: 'l2u3-grammar',
  speaking: 'l2u3-speaking',
  readingSpeaking: 'l2u3-reading-speaking',
  listeningSpeaking: 'l2u3-listening-speaking',
  readingWriting: 'l2u3-reading-writing',
  culture: 'l2u3-culture',
  task: 'l2u3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Recap a match result using cause + comparison + obviousness.', 'Use 4 advanced grammar patterns about sports/predictions.', 'Know basics of 씨름 (Korean wrestling).'],
    task: 'Imagine recapping last night\'s Korea vs Japan baseball game to your roommate.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Sports + victory/defeat words',
    goals: ['Name sports.', 'Use 이기다·지다·비기다·승부·점수·응원하다·기대되다.'],
    task: 'Recap a team\'s wins and losses.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '경음화 in -ㄹ걸요',
    goals: ['Apply 경음화: 바쁠걸요 → [바쁠껄요].', 'Soft prediction ending.'],
    task: 'Read 바쁠걸요, 좋을걸요, 갈걸요 aloud.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Sports-talk patterns',
    goals: ['V-(으)나 마나 — whether or not you V', 'V-는 바람에 — because of (unintended cause)', 'N(이)라는 N — a N called ~', 'N에 비해(서) — compared to N'],
    task: 'Use each pattern in a sports sentence.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Explaining the match result',
    goals: ['Recap a match using cause + comparison.'],
    task: 'Describe a recent match.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Stadium introductions',
    goals: ['Read intros to playing fields.', 'Introduce a stadium.'],
    task: 'Introduce 잠실 야구장 or 상암 월드컵 경기장.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Athlete attitudes + match predictions',
    goals: ['Discuss an athlete\'s mentality.', 'Predict match outcomes.'],
    task: 'Predict the next K-League match.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Futsal explanation + match writeup',
    goals: ['Read about futsal.', 'Write about a memorable match.'],
    task: 'Write 3 sentences about a memorable sports moment.' },
  { id: ACT.culture, section: 'Culture Note', title: '씨름 — Korean traditional wrestling',
    goals: ['Understand the rules and 추석 connection of 씨름.'],
    task: 'Compare 씨름 with wrestling from your country.' },
  { id: ACT.task, section: 'Task', title: 'Plan a Kumoh tournament',
    goals: ['Combine vocabulary + 4 grammar patterns in one scene.'],
    task: 'Plan a small soccer tournament for Kumoh.' },
];

const lesson = {
  title: '레벨 2 · 3과: 스포츠의 세계 (World of Sports)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'expressing-certainty', label: 'Expressing certainty', goal: 'Use V-(으)나 마나 to express that the outcome is obvious.' },
    { id: 'expressing-cause', label: 'Explaining unintended cause', goal: 'Use V-는 바람에 to explain why something went wrong.' },
    { id: 'comparing', label: 'Comparing two things', goal: 'Use N에 비해(서) to compare two athletes/teams.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'sports + advanced grammar', 'By end: recap matches with cause/comparison, use 4 advanced patterns, understand 씨름.', 'word', 'Functions: cause · comparison · obviousness · prediction', 'Sports-talk toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'sports chat', 'A friend asks who won last night\'s Korea vs Japan baseball game. You should be able to recap the score + key moments + a comparison.', 'word', 'Friend: 한국 어떻게 됐어요? — You: 비가 오는 바람에 잠시 멈췄지만 4대2로 이겼어요.', 'Friend: How did Korea do? — You: Paused for rain but won 4-2.', null, [ACT.orientation]),

    createContentItem('경기', 'gyeonggi', 'match / game', 'word', '어제 경기를 봤어요.', 'I watched yesterday\'s match.', null, [ACT.vocabulary]),
    createContentItem('선수', 'seonsu', 'player / athlete', 'word', '한국 선수가 1등이에요.', 'The Korean is 1st.', null, [ACT.vocabulary]),
    createContentItem('이기다', 'igida', 'to win', 'word', '우리 팀이 이겼어요.', 'Our team won.', null, [ACT.vocabulary]),
    createContentItem('지다', 'jida', 'to lose', 'word', '아쉽게 졌어요.', 'We lost regrettably.', null, [ACT.vocabulary]),
    createContentItem('비기다', 'bigida', 'to tie / draw', 'word', '경기가 1대1로 비겼어요.', 'The game tied 1-1.', null, [ACT.vocabulary]),
    createContentItem('승부', 'seungbu', 'win/loss outcome', 'word', '승부를 가리기 어려워요.', 'Hard to call a winner.', null, [ACT.vocabulary]),
    createContentItem('우승', 'useung', 'championship', 'word', '우승했어요!', 'We won the championship!', null, [ACT.vocabulary]),
    createContentItem('준우승', 'junuseung', 'runner-up', 'word', '준우승도 자랑스러워요.', 'Runner-up is also proud.', null, [ACT.vocabulary]),
    createContentItem('점수', 'jeomsu', 'score', 'word', '점수가 높아요.', 'High score.', null, [ACT.vocabulary]),
    createContentItem('응원하다', 'eungwonhada', 'to cheer for', 'word', '한국 팀을 응원해요.', 'I cheer for Korea.', null, [ACT.vocabulary]),
    createContentItem('축구', 'chukgu', 'soccer', 'word', '축구를 좋아해요.', 'I like soccer.', null, [ACT.vocabulary]),
    createContentItem('야구', 'yagu', 'baseball', 'word', '야구는 한국에서 인기예요.', 'Baseball is popular in Korea.', null, [ACT.vocabulary]),
    createContentItem('농구', 'nonggu', 'basketball', 'word', '농구도 해요.', 'I also play basketball.', null, [ACT.vocabulary]),
    createContentItem('배구', 'baegu', 'volleyball', 'word', '배구 경기가 재미있어요.', 'Volleyball matches are fun.', null, [ACT.vocabulary]),
    createContentItem('풋살', 'putsal', 'futsal', 'word', '풋살은 5명이 해요.', 'Futsal has 5 players.', null, [ACT.vocabulary]),
    createContentItem('연습', 'yeonseup', 'practice', 'word', '매일 연습해요.', 'I practice daily.', null, [ACT.vocabulary]),
    createContentItem('씨름', 'ssireum', 'Korean wrestling', 'word', '씨름은 한국 전통 운동이에요.', 'Ssireum is a Korean traditional sport.', null, [ACT.vocabulary]),
    createContentItem('태권도', 'taekwondo', 'taekwondo', 'word', '태권도는 한국에서 시작했어요.', 'Taekwondo started in Korea.', null, [ACT.vocabulary]),
    createContentItem('경기장', 'gyeonggijang', 'stadium / arena', 'word', '경기장에 사람이 많아요.', 'Many people at the stadium.', null, [ACT.vocabulary]),
    createContentItem('관중', 'gwanjung', 'audience / spectators', 'word', '관중이 환호해요.', 'The crowd cheers.', null, [ACT.vocabulary]),

    createContentItem('바쁠걸요 → [바쁠껄요]', 'bappeulkkeoryo', '경음화: ㄹ받침 + ㄱ → ㄹ + ㄲ.', 'word', '오늘은 바쁠걸요. → [바쁠껄요]', 'They will probably be busy.', null, [ACT.pronunciation]),
    createContentItem('좋을걸요 → [조을껄요]', 'joeulkkeoryo', 'Same 경음화 + ㅎ-deletion.', 'word', '내일은 좋을걸요. → [조을껄요]', 'Tomorrow should be good.', null, [ACT.pronunciation]),
    createContentItem('갈걸요 → [갈껄요]', 'galkkeoryo', '경음화 in soft prediction.', 'word', '아마 갈걸요. → [갈껄요]', 'They will probably go.', null, [ACT.pronunciation]),
    createContentItem('이겼어요 → [이겨써요]', 'igyeosseoyo', 'Smooth past tense.', 'word', '우리가 이겼어요.', 'We won.', null, [ACT.pronunciation]),

    createContentItem('V-(으)나 마나 — whether or not V', 'obvious outcome', 'Attach -나 마나 (vowel) or -으나 마나 (consonant). Suggests the action is pointless.', 'sentence', '연습하나 마나 1등은 못해요.', 'Whether you practice or not, you cannot win 1st.',
      [{ korean: '하 + 나 마나', english: '하나 마나' }, { korean: '먹 + 으나 마나', english: '먹으나 마나' }], [ACT.grammar]),
    createContentItem('V-는 바람에 — because of (unintended)', 'cause', 'Attach -는 바람에 to verb stem. Implies the cause was unintended/unwanted.', 'sentence', '비가 오는 바람에 경기가 취소됐어요.', 'Because of the rain, the match was canceled.',
      [{ korean: '오 + 는 바람에', english: '오는 바람에' }, { korean: '놓치 + 는 바람에', english: '놓치는 바람에 (because I missed it)' }], [ACT.grammar]),
    createContentItem('N(이)라는 N — a N called ~', 'introduction', 'Use to introduce a noun by name. (이)라는 attaches to the name.', 'sentence', '풋살이라는 운동을 아세요?', 'Do you know a sport called futsal?',
      [{ korean: '풋살 + 이라는 + 운동', english: 'sport called futsal' }, { korean: '~ 라는 사람', english: 'a person called ~' }], [ACT.grammar]),
    createContentItem('N에 비해(서) — compared to N', 'comparison', 'Attach 에 비해(서) to a noun for comparison.', 'sentence', '축구에 비해서 야구가 더 길어요.', 'Compared to soccer, baseball is longer.',
      [{ korean: '에 비해서', english: 'compared to (with 서)' }, { korean: '에 비해', english: 'compared to (without 서)' }], [ACT.grammar]),
    createContentItem('Bonus: -(으)ㄹ걸요 — probably will', 'soft prediction', 'Attach -ㄹ걸요 (vowel) or -을걸요 (consonant) for a soft prediction.', 'sentence', '한국 팀이 이길걸요. — Korea will probably win.', 'Soft future prediction.',
      null, [ACT.grammar]),

    createContentItem('Match recap', 'speaking model',
      'Use cause + comparison + obviousness in one sentence.',
      'sentence', '한국 선수가 일본 선수에 비해서 더 빨라요. 그래서 결국 이겼어요.',
      'The Korean is faster compared to the Japanese player. So in the end they won.',
      null, [ACT.speaking]),

    createContentItem('Stadium intro', 'reading',
      'Read this introduction to Korea\'s most iconic stadium.',
      'sentence',
      '잠실 야구장이라는 곳을 아세요? 서울에 있는 가장 큰 야구장이에요. 한 경기에 25,000명의 관중이 와요. 다른 야구장에 비해서 매우 크고 시설이 좋아요. 야구를 좋아하는 사람이라면 꼭 가 봐야 하는 곳이에요.',
      'Do you know the place called Jamsil Baseball Stadium? It is the biggest baseball stadium in Seoul. 25,000 spectators come per game. Compared to other stadiums, it is very large with great facilities. If you love baseball, this is a must-visit.',
      [
        { korean: '잠실 야구장이라는 곳', english: 'a place called Jamsil Stadium' },
        { korean: '~에 비해서', english: 'compared to' },
        { korean: '꼭 가 봐야 하는', english: 'a must-visit' },
      ],
      [ACT.readingSpeaking]),

    createContentItem('Match prediction', 'listening',
      'Two fans predict tomorrow\'s game.',
      'conversation',
      'A: 내일 한국 대 일본 축구 경기 어떻게 될 것 같아요?\nB: 한국 선수들이 일본에 비해 컨디션이 좋아요. 이길걸요.\nA: 글쎄요. 일본 골키퍼가 정말 잘해요. 연습하나 마나 어려울 수도 있어요.\nB: 그래도 한국 응원할 거예요. 결과가 기대돼요.\nA: 저도 같이 봐요.',
      'A: How do you think the Korea vs Japan match will go? B: Korean players are in better condition than Japan. They will probably win. A: Maybe. The Japanese goalkeeper is great. Whether they practice or not, it could be hard. B: I will still cheer for Korea. Looking forward to it. A: Let us watch together.',
      [
        { korean: '~에 비해', english: 'compared to' },
        { korean: '이길걸요', english: 'they will probably win' },
        { korean: '연습하나 마나', english: 'whether they practice or not' },
      ],
      [ACT.listeningSpeaking]),

    createContentItem('Futsal explained', 'reading + writing',
      'Sample paragraph about futsal.',
      'sentence',
      '풋살이라는 운동은 축구와 비슷하지만 다른 점이 있어요. 5명이 작은 코트에서 해요. 일반 축구에 비해서 빠르고 더 많은 골이 들어가요. 비가 오는 바람에 축구장에서 못 할 때 풋살을 많이 해요.',
      'A sport called futsal is similar to soccer but with differences. 5 players on a small court. Faster and more goals than regular soccer. People often play futsal when they cannot play soccer because of rain.',
      [
        { korean: '풋살이라는 운동', english: 'sport called futsal' },
        { korean: '일반 축구에 비해서', english: 'compared to regular soccer' },
        { korean: '비가 오는 바람에', english: 'because of the rain' },
      ],
      [ACT.readingWriting]),

    createContentItem('씨름 — Korean traditional wrestling', 'culture',
      '씨름 is Korea\'s traditional folk wrestling. Two opponents (장사 = strong man) grip each other\'s 샅바 (cloth belt) and try to topple the other. Most famous during 추석 — winners traditionally got an ox as a prize.',
      'sentence', '씨름은 한국의 전통 운동이에요. 추석에 큰 대회가 열려요.',
      'Ssireum is Korea\'s traditional sport. Big tournaments are held on Chuseok.',
      [
        { korean: '장사', english: 'strong man / wrestler' },
        { korean: '샅바', english: 'wrestling belt' },
        { korean: '천하장사', english: 'champion (lit. "strongest under heaven")' },
      ],
      [ACT.culture]),

    createContentItem('과제: Plan a Kumoh tournament', 'task',
      'Roleplay: Plan a soccer mini-tournament at Kumoh. Use ~ 라는 N, ~에 비해, ~ 바람에, ~ 으나 마나.',
      'conversation',
      'You: 우리 학교에서 풋살이라는 ___\nTutor: 좋아요. 언제 해요?\nYou: ~ 라는 날에 해요 / 비가 오는 바람에...\nTutor: 어느 팀이 강해요?\nYou: A팀에 비해 B팀이 약해요 / 연습하나 마나...\nTutor: 좋아요. 같이 응원해요.',
      'AI tutor will play your planning partner.',
      [
        { korean: '~ 라는 N', english: 'a N called ~' },
        { korean: '~에 비해', english: 'compared to ~' },
        { korean: '~ 바람에', english: 'because of ~' },
        { korean: '~ 으나 마나', english: 'whether or not ~' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
