// Level 2 Track-Adult Unit 10 — 잘 지켜야 합니다 (Rules and obligations)
// Source: Book 2A·10.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au10-orientation',
  pronunciation: 'l2au10-pronunciation',
  vocabularyRules: 'l2au10-vocab-rules',
  vocabularyCompliance: 'l2au10-vocab-comp',
  grammarMust: 'l2au10-grammar-must',
  grammarMakeSure: 'l2au10-grammar-make-sure',
  reading: 'l2au10-reading',
  listening: 'l2au10-listening',
  writing: 'l2au10-writing',
  culture: 'l2au10-culture',
  task: 'l2au10-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Explain Korean workplace + dorm rules.', 'Use 3 obligation patterns: V-아/어야 합니다 / V-(으)면 안 됩니다 / V-도록 하다.'],
    task: 'Imagine onboarding a new foreign coworker — you explain the rules.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Rule phrases',
    goals: ['Apply 비음화 in 합니다.', 'Apply 격음화 in 잊지 → [읻찌].'],
    task: 'Read each rule phrase.' },
  { id: ACT.vocabularyRules, section: 'Vocabulary I', title: 'Rules + etiquette',
    goals: ['Use 규칙·예절·매너·벌금·금지·지각.'],
    task: 'List 5 workplace rules.' },
  { id: ACT.vocabularyCompliance, section: 'Vocabulary II', title: 'Compliance + recycling',
    goals: ['Use 지키다·어기다·재활용·분리수거·출근부·보고.'],
    task: 'Use 5 compliance words.' },
  { id: ACT.grammarMust, section: 'Grammar I', title: 'V-아/어야 합니다 / V-(으)면 안 됩니다',
    goals: ['Must V (positive) vs must not V (negative).'],
    task: 'State 3 rules each.' },
  { id: ACT.grammarMakeSure, section: 'Grammar II', title: 'V-도록 하다 — make sure to V',
    goals: ['Formal directive form, slightly softer than 마십시오.'],
    task: 'Convert 3 rules to 도록 하다.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Company rule book',
    goals: ['Read a workplace rule list.'],
    task: 'Identify forbidden actions.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Onboarding new hire',
    goals: ['Follow a rule-explanation dialogue.'],
    task: 'Explain rules to AI tutor playing new hire.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Welcome memo',
    goals: ['Write a 4-5 line welcome memo with 3 key rules.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — 분리수거 and Korean strictness',
    goals: ['Know Korea\'s strict 분리수거 (separate-waste) culture.', 'Know that 회식 has unwritten rules.'],
    task: 'Compare with your country.' },
  { id: ACT.task, section: 'Task', title: '과제 — Onboard new hire',
    goals: ['Combine 3 obligation patterns + welcome.'],
    task: 'Roleplay onboarding.' },
];

const lesson = {
  title: '레벨 2 (직장) · 10과: 잘 지켜야 합니다 (Rules and Obligations)',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'explaining-rule', label: 'Explaining a rule', goal: 'Use V-아/어야 합니다.' },
    { id: 'confirming-understood', label: 'Confirming', goal: 'Use 이해하셨습니까?' },
    { id: 'softening-rule', label: 'Softening with 도록', goal: 'Use V-도록 하다.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('Lesson goal', 'rules', 'By end: explain rules + 3 obligation patterns + welcome new hire.', 'word', 'Functions: explain · prohibit · softer command', 'Rule toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'new hire onboarding', 'A new Filipino coworker just arrived. You explain the factory + dorm rules in clear formal Korean.', 'word', 'You: ~ 지키셔야 합니다. ~ 면 안 됩니다. ~ 도록 하세요.', 'Must follow ~. Must not ~. Make sure ~.', null, [ACT.orientation]),

    createContentItem('합니다 → [함니다]', 'hamnida', '비음화.', 'word', '지켜야 합니다.', 'Must keep.', null, [ACT.pronunciation]),
    createContentItem('잊지 → [읻찌]', 'itjji', '경음화: ㅈ → 찌.', 'word', '잊지 마십시오.', 'Do not forget.', null, [ACT.pronunciation]),
    createContentItem('규칙 → [규칙]', 'gyuchik', 'No change.', 'word', '회사 규칙', 'company rules.', null, [ACT.pronunciation]),
    createContentItem('재활용 → [재활용]', 'jaehwaryong', 'No major change.', 'word', '재활용을 잘 하세요.', 'Recycle well.', null, [ACT.pronunciation]),

    createContentItem('규칙', 'gyuchik', 'rule', 'word', '회사 규칙을 지키세요.', 'Follow company rules.', null, [ACT.vocabularyRules]),
    createContentItem('예절', 'yejeol', 'etiquette', 'word', '한국 예절을 배워요.', 'Learn Korean etiquette.', null, [ACT.vocabularyRules]),
    createContentItem('매너', 'maeneo', 'manners', 'word', '매너 모드로 해 주세요.', 'Switch to silent mode.', null, [ACT.vocabularyRules]),
    createContentItem('벌금', 'beolgeum', 'fine', 'word', '벌금을 내야 합니다.', 'Pay a fine.', null, [ACT.vocabularyRules]),
    createContentItem('금지', 'geumji', 'prohibition', 'word', '여기는 흡연 금지입니다.', 'No smoking here.', null, [ACT.vocabularyRules]),
    createContentItem('지각', 'jigak', 'tardiness', 'word', '지각하면 안 됩니다.', 'Do not be late.', null, [ACT.vocabularyRules]),
    createContentItem('보고', 'bogo', 'report', 'word', '상황을 보고하십시오.', 'Report the situation.', null, [ACT.vocabularyRules]),
    createContentItem('출근부', 'chulgeunbu', 'attendance log', 'word', '출근부에 사인하세요.', 'Sign the log.', null, [ACT.vocabularyRules]),
    createContentItem('근무 중', 'geunmu jung', 'during work', 'word', '근무 중에 휴대폰 사용 금지.', 'No phone during work.', null, [ACT.vocabularyRules]),

    createContentItem('지키다', 'jikida', 'observe (rule)', 'word', '약속을 지킵시다.', 'Let us keep our word.', null, [ACT.vocabularyCompliance]),
    createContentItem('어기다', 'eogida', 'break (rule)', 'word', '규칙을 어기지 마세요.', 'Do not break rules.', null, [ACT.vocabularyCompliance]),
    createContentItem('재활용', 'jaehwaryong', 'recycling', 'word', '재활용을 잘 합시다.', 'Let us recycle.', null, [ACT.vocabularyCompliance]),
    createContentItem('분리수거', 'bullisugeo', 'separate-waste', 'word', '분리수거 규칙이 엄격해요.', 'Separation rules are strict.', null, [ACT.vocabularyCompliance]),
    createContentItem('엄격하다', 'eomgyeokhada', 'strict', 'word', '규칙이 엄격해요.', 'Rules are strict.', null, [ACT.vocabularyCompliance]),
    createContentItem('이해하다', 'ihaehada', 'understand', 'word', '이해했습니다.', 'Understood.', null, [ACT.vocabularyCompliance]),
    createContentItem('흡연', 'heubyeon', 'smoking', 'word', '흡연 구역', 'smoking area.', null, [ACT.vocabularyCompliance]),
    createContentItem('휴식 시간', 'hyusik sigan', 'break time', 'word', '휴식 시간에 쓰세요.', 'Use during break.', null, [ACT.vocabularyCompliance]),

    createContentItem('V-아/어야 합니다 — must V', 'positive obligation', 'Stated requirement.', 'sentence', '회사 규칙을 잘 지켜야 합니다.', 'Must follow company rules.',
      [{ korean: '지키 + 어야 합니다', english: 'must keep' }, { korean: '쓰 + 아야 합니다', english: 'must wear' }], [ACT.grammarMust]),
    createContentItem('V-(으)면 안 됩니다 — must not V', 'negative obligation', 'Forbidden.', 'sentence', '근무 중에 휴대폰을 쓰면 안 됩니다.', 'No phone during work.',
      [{ korean: '쓰 + 면 안 됩니다', english: 'must not use' }, { korean: '지각하 + 면 안 됩니다', english: 'must not be late' }], [ACT.grammarMust]),

    createContentItem('V-도록 하다 — make sure to V', 'softer directive', 'Slightly softer/more polished than 마십시오. Suggests "see that this is done".', 'sentence', '재활용을 잘 하도록 하십시오.', 'Make sure to recycle well.',
      [{ korean: 'V-도록 하세요', english: 'see that you' }, { korean: 'tone', english: 'professional / formal' }], [ACT.grammarMakeSure]),
    createContentItem('Compared with V-(으)세요', '도록 vs 세요', 'V-(으)세요 = please. V-도록 하세요 = make sure to (with implied importance).', 'sentence', '재활용하세요. = 재활용을 하도록 하세요.', 'Both work; 도록 is more formal.',
      null, [ACT.grammarMakeSure]),

    createContentItem('Company rule book', 'reading',
      'Read this excerpt.',
      'sentence',
      '◆ 회사 규칙 ◆\n1. 매일 8시까지 출근부에 사인하셔야 합니다.\n2. 근무 중에는 휴대폰을 사용하면 안 됩니다.\n3. 안전모와 보호 장갑을 꼭 착용하도록 하십시오.\n4. 분리수거를 철저히 하셔야 합니다.\n5. 사고가 나면 즉시 보고하도록 하십시오.\n· 규칙을 어기면 벌금이 부과됩니다.',
      'Company Rules:\n1. Must sign attendance log by 8 daily.\n2. No phone use during work.\n3. Make sure to wear helmet + gloves.\n4. Must do separate-waste collection thoroughly.\n5. Report accidents immediately.\n- Breaking rules: fine.',
      [
        { korean: '착용하다', english: 'to wear' },
        { korean: '철저히', english: 'thoroughly' },
        { korean: '부과되다', english: 'be imposed' },
      ],
      [ACT.reading]),

    createContentItem('Onboarding new hire', 'listening',
      'Senior employee explains rules.',
      'conversation',
      'A: 사라 씨, 환영합니다. 회사 규칙을 좀 알려 드릴게요.\nB: 네, 부탁드립니다.\nA: 첫째, 매일 8시까지 출근부에 사인하셔야 합니다. 지각하면 안 됩니다.\nB: 네, 알겠습니다.\nA: 둘째, 근무 중에는 휴대폰을 사용하면 안 됩니다.\nB: 점심 시간에는 괜찮습니까?\nA: 네, 점심 시간과 휴식 시간에는 사용하셔도 됩니다. 또 분리수거를 잘 하도록 하세요.\nB: 이해했습니다. 잘 지키겠습니다.',
      'A: Welcome. Let me explain rules. B: Please. A: 1. Sign log by 8 daily. No tardiness. B: OK. A: 2. No phone during work. B: Lunch break OK? A: Yes, lunch + breaks fine. Also, recycle properly. B: Understood. Will follow.',
      [
        { korean: '~ 셔야 합니다', english: 'must (honorific)' },
        { korean: '~ 면 안 됩니다', english: 'must not' },
        { korean: '~ 도록 하세요', english: 'make sure to' },
      ],
      [ACT.listening]),

    createContentItem('Welcome memo', 'writing',
      'Sample memo.',
      'sentence',
      '안녕하십니까. 신입 직원 분들께 알려 드립니다. 첫째, 매일 8시까지 출근하셔야 합니다. 둘째, 근무 중에는 휴대폰을 사용하시면 안 됩니다. 셋째, 분리수거를 철저히 하도록 하십시오. 잘 지켜 주시면 감사하겠습니다.',
      'Hello. Notice for new employees: 1. Must clock in by 8 daily. 2. No phone during work. 3. Make sure to do separate-waste. Thank you for compliance.',
      null, [ACT.writing]),

    createContentItem('분리수거 culture', 'culture',
      'Korea\'s 분리수거 system is strict and color-coded: 일반 (general), 음식물 (food waste — must drain), 종이 (paper), 플라스틱, 캔, 유리. Violations bring 벌금. Each dorm/apt has dedicated bins.',
      'sentence', '한국 분리수거는 매우 엄격해요. 색깔별로 다르게 버려야 해요.',
      'Korean separation rules are very strict. Different bins by color.',
      [
        { korean: '일반 쓰레기', english: 'general waste' },
        { korean: '음식물 쓰레기', english: 'food waste' },
        { korean: '재활용', english: 'recyclables' },
      ],
      [ACT.culture]),

    createContentItem('과제: Onboard new hire', 'task',
      'Roleplay: Onboard a new foreign hire.',
      'conversation',
      'New hire: 안녕하십니까. 신입입니다.\nYou: 환영합니다. 회사 규칙을 알려 드릴게요.\n[3 rules using ~ 셔야 합니다 / ~ 면 안 됩니다 / ~ 도록 하세요]\nNew hire: 이해했습니다. 감사합니다.\nYou: 잘 지키시면 좋겠습니다.',
      'AI tutor will play the new hire.',
      [
        { korean: '~ 셔야 합니다', english: 'must (honorific)' },
        { korean: '~ 면 안 됩니다', english: 'must not' },
        { korean: '~ 도록 하세요', english: 'make sure to' },
        { korean: '이해하셨습니까?', english: 'understood?' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
