// Level 2 Track-Adult Unit 9 — 주말에 무엇을 합니까? (Weekend conversation)
// Source: Book 2A·9.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au9-orientation',
  pronunciation: 'l2au9-pronunciation',
  vocabularyActivities: 'l2au9-vocab-act',
  vocabularyHobbies: 'l2au9-vocab-hob',
  grammarPlan: 'l2au9-grammar-plan',
  grammarExperience: 'l2au9-grammar-exp',
  reading: 'l2au9-reading',
  listening: 'l2au9-listening',
  writing: 'l2au9-writing',
  culture: 'l2au9-culture',
  task: 'l2au9-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Engage in Monday small talk.', 'Use V-기로 하다 (decide) and V-(으)ㄴ 적이 있다 (have).'],
    task: 'Imagine Monday morning at the factory — coworkers ask about your weekend.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Small-talk phrases',
    goals: ['Apply 비음화: 갔습니다 → [갇씀니다], 했어요 → [해써요].'],
    task: 'Read each weekend phrase.' },
  { id: ACT.vocabularyActivities, section: 'Vocabulary I', title: 'Weekend activities',
    goals: ['Use 등산·낚시·산책·운동·영화 보기·맛집.'],
    task: 'List 3 activities you did.' },
  { id: ACT.vocabularyHobbies, section: 'Vocabulary II', title: 'Hobbies + plans',
    goals: ['Use 취미·모임·약속·계획·시간을 보내다.'],
    task: 'State 2 hobbies.' },
  { id: ACT.grammarPlan, section: 'Grammar I', title: 'V-기로 하다 — decide to V',
    goals: ['Express a decision/plan.'],
    task: 'State 3 plans.' },
  { id: ACT.grammarExperience, section: 'Grammar II', title: 'V-(으)ㄴ 적이 있다 — have V-ed',
    goals: ['Talk about past experience.'],
    task: 'Share 3 experiences.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Weekend diary',
    goals: ['Read a coworker\'s weekend recap.'],
    task: 'Compare with your weekend.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Monday chat',
    goals: ['Follow Monday small talk.'],
    task: 'Reproduce with your weekend.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Weekend summary',
    goals: ['Write a 3-4 line summary of your last weekend.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean workplace weekend rhythm',
    goals: ['Know 회식 happens Sat. 등산 + 가족 모임 common.'],
    task: 'Compare with your culture.' },
  { id: ACT.task, section: 'Task', title: '과제 — Monday small talk',
    goals: ['Combine experience + plan + small talk.'],
    task: 'Roleplay Monday chat.' },
];

const lesson = {
  title: '레벨 2 (직장) · 9과: 주말에 무엇을 합니까? (Weekend Conversation)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'sharing-weekend', label: 'Sharing weekend plans', goal: 'Use V-기로 하다.' },
    { id: 'recalling-experience', label: 'Recalling experience', goal: 'Use V-(으)ㄴ 적이 있다.' },
    { id: 'asking-back', label: 'Asking back politely', goal: 'Use ~씨는요?' },
  ],
  relatedPools: ['topic-people'],
  content: [
    createContentItem('Lesson goal', 'weekend chat', 'By end: chat about weekend with coworkers using experience + plan grammar.', 'word', 'Functions: share · recall · plan · invite', 'Small talk toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'Monday chat', 'It is Monday morning at the factory. Your team gathers for coffee — small talk time.', 'word', 'A: 주말 잘 보내셨어요? — B: 등산했어요. 사라 씨는요?', 'A: Good weekend? — B: I hiked. You?', null, [ACT.orientation]),

    createContentItem('갔습니다 → [갇씀니다]', 'gatseumnida', '경음화 + 비음화.', 'word', '주말에 갔습니다.', 'I went on the weekend.', null, [ACT.pronunciation]),
    createContentItem('등산하기 → [등산하기]', 'deungsanhagi', 'No major change.', 'word', '등산하기로 했어요.', 'Decided to hike.', null, [ACT.pronunciation]),
    createContentItem('적이 있다 → [저기 읻따]', 'jeogi itda', '연음 + 경음화.', 'word', '먹은 적이 있어요.', 'Have eaten.', null, [ACT.pronunciation]),
    createContentItem('계획 → [게획]', 'gyehoek', 'Smooth.', 'word', '계획이 있어요.', 'Have a plan.', null, [ACT.pronunciation]),

    createContentItem('주말', 'jumal', 'weekend', 'word', '주말이 짧습니다.', 'Weekend is short.', null, [ACT.vocabularyActivities]),
    createContentItem('등산', 'deungsan', 'hiking', 'word', '등산했어요.', 'I hiked.', null, [ACT.vocabularyActivities]),
    createContentItem('낚시', 'naksi', 'fishing', 'word', '낚시 좋아해요.', 'I like fishing.', null, [ACT.vocabularyActivities]),
    createContentItem('영화 보기', 'yeonghwa bogi', 'watching movies', 'word', '영화 보기를 좋아해요.', 'I like movies.', null, [ACT.vocabularyActivities]),
    createContentItem('산책', 'sanchaek', 'walk', 'word', '산책했어요.', 'I walked.', null, [ACT.vocabularyActivities]),
    createContentItem('운동하다', 'undonghada', 'to exercise', 'word', '아침에 운동해요.', 'I exercise in the morning.', null, [ACT.vocabularyActivities]),
    createContentItem('맛집', 'matjip', 'good restaurant', 'word', '맛집을 찾아갔어요.', 'I went to a good restaurant.', null, [ACT.vocabularyActivities]),
    createContentItem('여행', 'yeohaeng', 'trip', 'word', '여행을 다녀왔어요.', 'I traveled.', null, [ACT.vocabularyActivities]),
    createContentItem('쇼핑', 'syoping', 'shopping', 'word', '쇼핑하러 갔어요.', 'I went shopping.', null, [ACT.vocabularyActivities]),
    createContentItem('피곤하다', 'pigonhada', 'tired', 'word', '피곤했어요.', 'I was tired.', null, [ACT.vocabularyActivities]),

    createContentItem('취미', 'chwimi', 'hobby', 'word', '제 취미는 사진 찍기예요.', 'My hobby is photography.', null, [ACT.vocabularyHobbies]),
    createContentItem('모임', 'moim', 'gathering', 'word', '동료 모임이 있어요.', 'Coworker gathering.', null, [ACT.vocabularyHobbies]),
    createContentItem('약속', 'yaksok', 'plan', 'word', '주말에 약속이 있어요.', 'Plans this weekend.', null, [ACT.vocabularyHobbies]),
    createContentItem('계획', 'gyehoek', 'plan', 'word', '계획을 세웠어요.', 'I made a plan.', null, [ACT.vocabularyHobbies]),
    createContentItem('시간을 보내다', 'sigan bonaeda', 'spend time', 'word', '가족과 시간을 보냈어요.', 'I spent time with family.', null, [ACT.vocabularyHobbies]),
    createContentItem('휴식', 'hyusik', 'rest', 'word', '주말에 휴식이 필요해요.', 'Need rest on weekend.', null, [ACT.vocabularyHobbies]),
    createContentItem('가족과', 'gajokgwa', 'with family', 'word', '가족과 같이 보냈어요.', 'I spent time with family.', null, [ACT.vocabularyHobbies]),
    createContentItem('동료와', 'dongnyowa', 'with coworkers', 'word', '동료들과 모였어요.', 'I gathered with coworkers.', null, [ACT.vocabularyHobbies]),

    createContentItem('V-기로 하다 — decide to V', 'plan', 'Express a decision/plan made.', 'sentence', '주말에 등산하기로 했습니다.', 'I decided to hike this weekend.',
      [{ korean: '하 + 기로 했다', english: 'decided' }, { korean: '먹 + 기로 했다', english: 'decided to eat' }], [ACT.grammarPlan]),
    createContentItem('Plans with someone', 'with', 'Add ~와 함께 / ~하고 같이 for partner.', 'sentence', '동료들과 같이 등산하기로 했어요.', 'Decided to hike with coworkers.',
      null, [ACT.grammarPlan]),

    createContentItem('V-(으)ㄴ 적이 있다 — have V-ed (experience)', 'experience', 'Express past experience.', 'sentence', '한국 음식을 먹은 적이 있습니다.', 'I have eaten Korean food.',
      [{ korean: 'V-(으)ㄴ 적이 있다', english: 'have done' }, { korean: 'V-(으)ㄴ 적이 없다', english: 'have not done' }], [ACT.grammarExperience]),
    createContentItem('Soft V-아/어 본 적이 있다', 'tried before', 'Add V-아/어 보다 for "tried doing".', 'sentence', '한국 영화를 봐 본 적이 있어요.', 'I have tried watching Korean movies.',
      null, [ACT.grammarExperience]),

    createContentItem('Weekend diary', 'reading',
      'Read this coworker\'s weekend.',
      'sentence',
      '지난 주말에 동료들과 등산하기로 했습니다. 토요일 아침 일찍 출발해서 산에 갔습니다. 처음에는 좀 힘들었지만 정말 재미있었어요. 정상에서 사진도 많이 찍었어요. 등산이 끝난 후에 산 아래 맛집에서 점심을 먹었어요. 한국 식당에서 비빔밥을 먹은 적이 있지만 그날은 정말 더 맛있었어요. 정말 좋은 주말이었습니다.',
      'Last weekend I decided to hike with coworkers. Set off Saturday morning. Hard at first but really fun. Took many photos at the top. After hiking we ate lunch at a good restaurant. I had eaten bibimbap before, but that day was really better. Great weekend.',
      [
        { korean: 'V-기로 했다', english: 'decided to' },
        { korean: 'V-(으)ㄴ 적이 있다', english: 'have done' },
      ],
      [ACT.reading]),

    createContentItem('Monday chat', 'listening',
      'Coworkers chat Monday morning.',
      'conversation',
      'A: 좋은 아침입니다. 주말 잘 보내셨어요?\nB: 네, 잘 보냈습니다. 동료들하고 등산했어요. 사라 씨는요?\nA: 저는 처음으로 한국 영화관에 가 봤어요. 정말 재미있었습니다.\nB: 어떤 영화를 보셨어요?\nA: 액션 영화였어요. 자막이 없어서 좀 어려웠어요.\nB: 다음에는 한국어 자막이 있는 영화를 보세요. 공부에 도움이 됩니다.\nA: 좋은 생각이에요. 다음 주말에는 그렇게 하기로 할게요.',
      'A: Good morning. Good weekend? B: Yes, hiked with coworkers. You? A: Went to Korean movie theater for first time. Fun. B: What movie? A: Action. No subtitles, a bit hard. B: Next time, watch with Korean subtitles. Helps study. A: Good idea. I will plan that next weekend.',
      [
        { korean: '~기로 하다', english: 'decided to' },
        { korean: '~씨는요?', english: 'and you?' },
        { korean: '~ 에 도움이 됩니다', english: 'helps with ~' },
      ],
      [ACT.listening]),

    createContentItem('Weekend summary', 'writing',
      'Sample paragraph.',
      'sentence',
      '안녕하십니까. 지난 주말은 정말 좋았습니다. 토요일에 동료들과 등산하기로 해서 같이 다녀왔어요. 정상에서 사진을 찍은 적이 처음이라 신기했습니다. 일요일에는 집에서 쉬었어요. 다음 주말에는 가족과 시간을 보내기로 했습니다.',
      'Hello. Last weekend was great. Saturday decided to hike with coworkers. First time taking photos at a summit — felt new. Sunday rested at home. Next weekend decided to spend time with family.',
      null, [ACT.writing]),

    createContentItem('Korean weekend rhythm', 'culture',
      'Korean workers typically use Saturday for 회식 (work dinner) or 동아리 (clubs); Sunday for 가족 (family). 등산 (hiking) is very popular among mid-career workers. Many foreign workers gather with their national community on Sundays.',
      'sentence', '한국 직장인들은 주말에 등산이나 가족 모임을 많이 해요.',
      'Korean workers often hike or do family gatherings.',
      [
        { korean: '회식', english: 'work dinner' },
        { korean: '동아리', english: 'club' },
        { korean: '가족 모임', english: 'family gathering' },
      ],
      [ACT.culture]),

    createContentItem('과제: Monday small talk', 'task',
      'Roleplay: Monday chat with a Korean coworker.',
      'conversation',
      'Coworker: 좋은 아침입니다. 주말 잘 보내셨어요?\nYou: 네. ~ 하기로 해서 ~ 했어요.\nCoworker: 즐거우셨어요?\nYou: 네. ~ 한 적이 있지만 ~\nCoworker: 다음 주말은요?\nYou: ~ 기로 했어요.',
      'AI tutor will play the coworker.',
      [
        { korean: '~ 기로 하다', english: 'decide to' },
        { korean: '~ 한 적이 있다', english: 'have done' },
        { korean: '~ 씨는요?', english: 'and you?' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
