// Level 1 Unit 3 — Locations & directions
// Sources: Book 1A·6 (약국이 어디에 있어요?) + Book 1B·3 (화장실이 어디에 있어요?)
// Functions: asking where a place is, describing relative position, basic directions.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l1u3-orientation',
  pronunciation: 'l1u3-pronunciation',
  vocabularyPlaces: 'l1u3-vocab-places',
  vocabularyDirections: 'l1u3-vocab-directions',
  grammarWhere: 'l1u3-grammar-where',
  grammarPosition: 'l1u3-grammar-position',
  grammarDirection: 'l1u3-grammar-direction',
  reading: 'l1u3-reading',
  listening: 'l1u3-listening',
  writing: 'l1u3-writing',
  culture: 'l1u3-culture',
  task: 'l1u3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: [
      'Ask 어디에 있어요? to find any place in Korea.',
      'Give simple directions using straight / left / right / next to / behind.',
      'Describe your campus, dorm, or neighborhood with position words.',
    ],
    task: 'Imagine you are lost on the Kumoh campus and need to find the library and the cafeteria.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Sound changes',
    goals: ['Apply 연음 in 학교에 → [학꾜에], 도서관에 → [도서과네].'],
    task: 'Read each example aloud applying liaison and tensification.' },
  { id: ACT.vocabularyPlaces, section: 'Vocabulary I', title: 'Places in a city/campus',
    goals: ['Name 15+ common Korean places.'],
    task: 'List five places near your home/dorm.' },
  { id: ACT.vocabularyDirections, section: 'Vocabulary II', title: 'Position & direction words',
    goals: ['Use 위·아래·안·밖·옆·앞·뒤·사이·건너편.', 'Use 오른쪽·왼쪽·똑바로·이쪽·저쪽.'],
    task: 'Describe where two campus buildings are relative to each other.' },
  { id: ACT.grammarWhere, section: 'Grammar I', title: 'N이/가 어디에 있어요? — Where is N?',
    goals: ['Ask the location of any noun.', 'Reply with N은/는 [place]에 있어요.'],
    task: 'Ask and answer about three different places.' },
  { id: ACT.grammarPosition, section: 'Grammar II', title: 'N1 (의) N2 + position word + 에 있어요',
    goals: ['Stack a position word to be precise.', 'Drop 의 (possessive) in everyday speech.'],
    task: 'Make three sentences using N + position + 에 있어요.' },
  { id: ACT.grammarDirection, section: 'Grammar III', title: 'Movement: N에 가다/오다 + (으)로 가세요',
    goals: ['Use N에 가요/와요 to express "go to / come to" a place.', 'Use (으)로 to express the direction of movement.'],
    task: 'Give a short two-step direction using both grammar points.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Read a campus description',
    goals: ['Read a paragraph and identify the location of each building.'],
    task: 'Answer comprehension questions in Korean.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Asking for directions',
    goals: ['Follow a 5-turn directions dialogue.', 'Reproduce with a different destination.'],
    task: 'Listen / read, then ask directions to your real classroom.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Describe how to get somewhere',
    goals: ['Write 3-5 sentences guiding a visitor.'],
    task: 'Write directions from the school gate to your favorite spot.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean addresses & Naver Maps',
    goals: ['Understand 동·호수 in addresses.', 'Know why Koreans use Naver/Kakao maps, not Google.'],
    task: 'Read a sample Korean address and identify the city, district, building, and unit.' },
  { id: ACT.task, section: 'Task', title: '과제 — Welcome to Kumoh',
    goals: ['Guide a new exchange student from the main gate to the library.'],
    task: 'Roleplay giving directions using every grammar pattern from this lesson.' },
];

const lesson = {
  title: '레벨 1 · 3과: 화장실이 어디에 있어요? (Locations and Directions)',
  category: 'daily-life',
  difficulty: 'beginner',
  targetLang: 'ko',
  nativeLang: 'en',
  track: 'textbook',
  lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-where-place-is', label: 'Asking where a place is', goal: 'Use N이/가 어디에 있어요? to ask the location.' },
    { id: 'describing-position', label: 'Describing where something is', goal: 'Combine N + position word + 에 있어요.' },
    { id: 'giving-direction', label: 'Giving simple directions', goal: 'Combine 똑바로 / 오른쪽 / 왼쪽 + 가세요 to direct someone.' },
  ],
  relatedPools: ['topic-school', 'topic-city'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo',
      'By end of lesson: ask where something is, give 2-3 step directions, describe a building\'s position relative to another.',
      'word', 'Functions: ask location · describe position · give directions', 'Three skills that unlock independent travel in Korea.',
      null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang',
      'It is your second week at Kumoh and a new exchange student asks you where the library is. You need to direct them clearly.',
      'word', 'Visitor: 실례합니다, 도서관이 어디에 있어요?', 'Excuse me, where is the library?',
      null, [ACT.orientation]),

    createContentItem('어디에 → [어디에]', 'eodie', '"where" — usually pronounced clearly, no contraction.', 'word', '어디에 있어요?', 'Where is it?', null, [ACT.pronunciation]),
    createContentItem('학교에 → [학꾜에]', 'hakkyo-e', '경음화: 학 ㄱ받침 makes ㄱ tense, so 학교 sounds like [학꾜].', 'word', '학교에 가요. → [학꾜에 가요]', 'I go to school.', null, [ACT.pronunciation]),
    createContentItem('도서관에 → [도서과네]', 'doseogwane', '연음: ㄴ받침 of 관 jumps to the ㅇ of 에.', 'word', '도서관에 있어요. → [도서과네 이써요]', 'It is at the library.', null, [ACT.pronunciation]),
    createContentItem('식당 → [식땅]', 'sikttang', '경음화: ㄱ받침 of 식 makes the ㄷ tense.', 'word', '식당에 가요. → [식땅에 가요]', 'I go to the cafeteria.', null, [ACT.pronunciation]),
    createContentItem('옆에 → [여페]', 'yeope', '연음: ㅍ받침 of 옆 jumps to the 에.', 'word', '카페 옆에 있어요. → [카페 여페 이써요]', 'It is next to the cafe.', null, [ACT.pronunciation]),

    createContentItem('화장실', 'hwajangsil', 'bathroom / restroom', 'word', '화장실이 어디에 있어요?', 'Where is the bathroom?', null, [ACT.vocabularyPlaces]),
    createContentItem('도서관', 'doseogwan', 'library', 'word', '도서관에서 공부해요.', 'I study at the library.', null, [ACT.vocabularyPlaces]),
    createContentItem('식당', 'sikdang', 'cafeteria / restaurant', 'word', '학교 식당에서 점심을 먹어요.', 'I eat lunch at the cafeteria.', null, [ACT.vocabularyPlaces]),
    createContentItem('교실', 'gyosil', 'classroom', 'word', '교실에 학생들이 있어요.', 'There are students in the classroom.', null, [ACT.vocabularyPlaces]),
    createContentItem('학생회관', 'haksaenghoegwan', 'student center', 'word', '학생회관 1층에 카페가 있어요.', 'There is a cafe on the 1st floor of the student center.', null, [ACT.vocabularyPlaces]),
    createContentItem('기숙사', 'gisuksa', 'dormitory', 'word', '저는 기숙사에 살아요.', 'I live in the dorm.', null, [ACT.vocabularyPlaces]),
    createContentItem('약국', 'yakguk', 'pharmacy', 'word', '약국은 병원 옆에 있어요.', 'The pharmacy is next to the hospital.', null, [ACT.vocabularyPlaces]),
    createContentItem('병원', 'byeongwon', 'hospital / clinic', 'word', '병원이 학교 근처에 있어요.', 'There is a hospital near the school.', null, [ACT.vocabularyPlaces]),
    createContentItem('은행', 'eunhaeng', 'bank', 'word', '은행은 1층에 있어요.', 'The bank is on the first floor.', null, [ACT.vocabularyPlaces]),
    createContentItem('편의점', 'pyeonuijeom', 'convenience store', 'word', '편의점은 24시간 열어요.', 'Convenience stores are open 24 hours.', null, [ACT.vocabularyPlaces]),
    createContentItem('카페', 'kape', 'cafe', 'word', '카페에서 친구를 만나요.', 'I meet my friend at the cafe.', null, [ACT.vocabularyPlaces]),
    createContentItem('지하철역', 'jihacheolyeok', 'subway station', 'word', '지하철역이 학교 앞에 있어요.', 'The subway station is in front of the school.', null, [ACT.vocabularyPlaces]),
    createContentItem('버스 정류장', 'beoseu jeongnyujang', 'bus stop', 'word', '버스 정류장이 어디에 있어요?', 'Where is the bus stop?', null, [ACT.vocabularyPlaces]),
    createContentItem('우체국', 'uchegug', 'post office', 'word', '우체국에서 편지를 보내요.', 'I send letters at the post office.', null, [ACT.vocabularyPlaces]),
    createContentItem('공원', 'gongwon', 'park', 'word', '공원에서 산책해요.', 'I take a walk in the park.', null, [ACT.vocabularyPlaces]),

    createContentItem('위', 'wi', 'top / above', 'word', '책상 위에 책이 있어요.', 'There is a book on the desk.', null, [ACT.vocabularyDirections]),
    createContentItem('아래 / 밑', 'arae / mit', 'under / below', 'word', '의자 아래에 가방이 있어요.', 'My bag is under the chair.', null, [ACT.vocabularyDirections]),
    createContentItem('안', 'an', 'inside', 'word', '가방 안에 책이 있어요.', 'My book is in my bag.', null, [ACT.vocabularyDirections]),
    createContentItem('밖', 'bak', 'outside', 'word', '교실 밖에 친구가 있어요.', 'My friend is outside the classroom.', null, [ACT.vocabularyDirections]),
    createContentItem('옆', 'yeop', 'next to / beside', 'word', '도서관 옆에 카페가 있어요.', 'There is a cafe next to the library.', null, [ACT.vocabularyDirections]),
    createContentItem('앞', 'ap', 'front', 'word', '학교 앞에 버스 정류장이 있어요.', 'There is a bus stop in front of the school.', null, [ACT.vocabularyDirections]),
    createContentItem('뒤', 'dwi', 'back / behind', 'word', '집 뒤에 산이 있어요.', 'There is a mountain behind my house.', null, [ACT.vocabularyDirections]),
    createContentItem('사이', 'sai', 'between', 'word', '은행과 약국 사이에 카페가 있어요.', 'There is a cafe between the bank and the pharmacy.', null, [ACT.vocabularyDirections]),
    createContentItem('건너편', 'geonneopyeon', 'across (the street/from)', 'word', '학교 건너편에 카페가 있어요.', 'There is a cafe across from the school.', null, [ACT.vocabularyDirections]),
    createContentItem('근처', 'geuncheo', 'nearby / vicinity', 'word', '학교 근처에 병원이 있어요.', 'There is a hospital near the school.', null, [ACT.vocabularyDirections]),
    createContentItem('오른쪽', 'oreunjjok', 'right side', 'word', '오른쪽으로 가세요.', 'Go to the right.', null, [ACT.vocabularyDirections]),
    createContentItem('왼쪽', 'oenjjok', 'left side', 'word', '왼쪽으로 가세요.', 'Go to the left.', null, [ACT.vocabularyDirections]),
    createContentItem('똑바로', 'ttokbaro', 'straight', 'word', '똑바로 가세요.', 'Go straight.', null, [ACT.vocabularyDirections]),
    createContentItem('이쪽 / 저쪽', 'ijjok / jeojjok', 'this way / that way', 'word', '이쪽으로 오세요.', 'Come this way.', null, [ACT.vocabularyDirections]),

    createContentItem(
      'N이/가 어디에 있어요?', 'eodie isseoyo',
      'Ask the location of any noun. Use subject 이/가 on the searched-for thing.',
      'sentence', '화장실이 어디에 있어요?', 'Where is the bathroom?',
      [
        { korean: '화장실이', english: 'bathroom + subject 이' },
        { korean: '어디에', english: 'where (location)' },
        { korean: '있어요', english: 'is located' },
      ],
      [ACT.grammarWhere]),
    createContentItem(
      'N은/는 [place]에 있어요', 'is at [place]',
      'Reply with topic marker on the known thing. The place + 에 = the location.',
      'sentence', '화장실은 2층에 있어요.', 'The bathroom is on the 2nd floor.',
      [
        { korean: '화장실은', english: 'bathroom (topic — it is what we are talking about now)' },
        { korean: '2층에', english: 'on the 2nd floor' },
        { korean: '있어요', english: 'is located' },
      ],
      [ACT.grammarWhere]),
    createContentItem(
      'Negative location', 'is not at',
      'Replace 있어요 with 없어요 to say "it is not there."',
      'sentence', '편의점은 학교 안에 없어요. 학교 앞에 있어요.', 'The convenience store is not inside the school. It is in front.',
      null, [ACT.grammarWhere]),

    createContentItem(
      'N1 N2 + position + 에 있어요', 'precise location',
      'Stack: bigger location → smaller location → position word → 에 있어요.',
      'sentence', '도서관은 학생회관 옆에 있어요.', 'The library is next to the student center.',
      [
        { korean: '도서관은', english: 'library (topic)' },
        { korean: '학생회관 옆에', english: 'next to the student center' },
        { korean: '있어요', english: 'is located' },
      ],
      [ACT.grammarPosition]),
    createContentItem(
      'Triple-stacked location', 'maximally specific',
      'You can stack multiple levels: city → building → floor → position.',
      'sentence', '구미시 금오공과대학교 학생회관 1층 안에 카페가 있어요.', 'There is a cafe inside the 1st floor of the Kumoh student center in Gumi.',
      [
        { korean: '구미시', english: 'Gumi city' },
        { korean: '금오공과대학교', english: 'Kumoh National Institute of Technology' },
        { korean: '학생회관 1층 안에', english: 'inside the 1st floor of the student center' },
      ],
      [ACT.grammarPosition]),
    createContentItem(
      'Drop 의 in speech', 'possessive often omitted',
      'Written: 학교의 도서관. Spoken: 학교 도서관. Korean drops the 의 in everyday speech.',
      'sentence', '학교 도서관은 학생회관 옆에 있어요.', 'The school library is next to the student center.',
      null, [ACT.grammarPosition]),

    createContentItem(
      'N에 가요 / 와요', 'go / come to N',
      'Express movement TO a place with N + 에 + 가요/와요. Distinct from N에 있어요 (located at N).',
      'sentence', '도서관에 가요.', 'I am going to the library.',
      [
        { korean: '도서관에', english: 'to the library' },
        { korean: '가요', english: 'go (polite)' },
      ],
      [ACT.grammarDirection]),
    createContentItem(
      '(으)로 + 가다 — direction of movement', 'toward / via',
      '으로 after consonant, 로 after vowel or ㄹ. Indicates the DIRECTION you are moving.',
      'sentence', '오른쪽으로 가세요.', 'Go to the right.',
      [
        { korean: '오른쪽 + 으로', english: '오른쪽 ends in consonant → 으로' },
        { korean: '왼쪽으로', english: 'to the left' },
        { korean: '이쪽으로', english: 'this way' },
      ],
      [ACT.grammarDirection]),
    createContentItem(
      'Two-step direction', '똑바로 + 오른쪽으로',
      'Combine direction words to give a short route.',
      'sentence', '여기에서 똑바로 가세요. 그리고 카페에서 오른쪽으로 가세요.', 'Go straight from here. Then turn right at the cafe.',
      [
        { korean: '여기에서', english: 'from here' },
        { korean: '똑바로 가세요', english: 'go straight' },
        { korean: '그리고', english: 'and / then' },
        { korean: '~에서 오른쪽으로', english: 'turn right at ~' },
      ],
      [ACT.grammarDirection]),

    createContentItem(
      'Campus description',
      'reading practice',
      'Read aloud, then answer the questions.',
      'sentence',
      '여기는 금오공과대학교예요. 정문 앞에 버스 정류장이 있어요. 정문 안으로 들어가면 학생회관이 있어요. 학생회관 1층에 카페하고 식당이 있어요. 학생회관 옆에 도서관이 있어요. 도서관 뒤에 기숙사가 있어요.',
      'This is Kumoh National Institute of Technology. There is a bus stop in front of the main gate. When you go through the gate, there is a student center. On the 1st floor of the student center there is a cafe and a cafeteria. Next to the student center is the library. Behind the library is the dormitory.',
      [
        { korean: '정문', english: 'main gate' },
        { korean: '들어가면', english: 'when you go in' },
        { korean: '학생회관 1층', english: '1st floor of student center' },
      ],
      [ACT.reading]),
    createContentItem(
      'Comprehension', 'answer in Korean',
      'Answer based on the paragraph.',
      'sentence',
      'Q1: 정문 앞에 뭐가 있어요? · Q2: 카페는 어디에 있어요? · Q3: 도서관 뒤에 뭐가 있어요?',
      'Q1: What is in front of the gate? Q2: Where is the cafe? Q3: What is behind the library?',
      [
        { korean: 'A1: 버스 정류장이 있어요.', english: 'A bus stop.' },
        { korean: 'A2: 학생회관 1층에 있어요.', english: 'On the 1st floor of the student center.' },
        { korean: 'A3: 기숙사가 있어요.', english: 'The dormitory.' },
      ],
      [ACT.reading]),

    createContentItem(
      'Asking for the bathroom',
      'short dialogue',
      'Quick exchange between a visitor and a passerby.',
      'conversation',
      'A: 실례합니다, 화장실이 어디에 있어요?\nB: 화장실은 저기 카페 옆에 있어요.\nA: 카페 안에 있어요?\nB: 아니요, 카페 옆이에요. 오른쪽으로 가세요.\nA: 감사합니다.',
      'A: Excuse me, where is the bathroom?\nB: The bathroom is over there next to the cafe.\nA: Inside the cafe?\nB: No, next to it. Go right.\nA: Thank you.',
      [
        { korean: '실례합니다', english: 'excuse me' },
        { korean: '저기', english: 'over there' },
        { korean: '오른쪽으로', english: 'to the right' },
      ],
      [ACT.listening]),
    createContentItem(
      'Directions to the library',
      'multi-step',
      '5-turn dialogue. Notice 똑바로, ~에서, 그리고, 오른쪽으로.',
      'conversation',
      'A: 도서관에 어떻게 가요?\nB: 여기에서 똑바로 가세요. 그러면 학생회관이 보여요.\nA: 학생회관이요?\nB: 네. 학생회관 옆에 도서관이 있어요. 오른쪽으로 가세요.\nA: 알겠어요. 여기에서 똑바로 가서 학생회관 오른쪽으로 가면 되죠?\nB: 네, 맞아요.\nA: 정말 감사합니다.',
      'A: How do I get to the library?\nB: Go straight from here. Then you will see the student center.\nA: The student center?\nB: Yes. The library is next to it. Go to the right.\nA: Got it. So I go straight from here and then right at the student center?\nB: Yes, that is right.\nA: Thank you so much.',
      [
        { korean: '어떻게 가요?', english: 'how do I go?' },
        { korean: '~이/가 보여요', english: 'you can see ~' },
        { korean: '~으로 가면 되죠?', english: 'I should go toward ~, right?' },
      ],
      [ACT.listening]),

    createContentItem(
      'Model directions',
      'writing template',
      'Use this skeleton to write your own.',
      'sentence',
      '[출발지]에서 똑바로 가세요. [건물]이/가 보여요. [건물] [위치] [목적지]이/가 있어요. [방향]으로 가세요.',
      '[Start] → go straight → you see [building] → [destination] is [position] of [building] → go [direction].',
      null, [ACT.writing]),
    createContentItem(
      'Writing prompt',
      'your turn',
      'Write 3-5 sentences directing a friend from the main gate of Kumoh to your favorite spot on campus.',
      'sentence',
      'Example: 정문에서 똑바로 가세요. 그러면 학생회관이 보여요. 학생회관 1층에 카페가 있어요. 카페에서 친구를 만나요.',
      'Example: Go straight from the main gate. You will see the student center. The cafe is on the 1st floor. I meet my friend there.',
      null, [ACT.writing]),

    createContentItem(
      'Korean addresses (주소)',
      'how addresses work',
      'A Korean address reads BIG → SMALL: province → city → district (동) → street → building → unit (호).',
      'sentence',
      '경상북도 구미시 대학로 61 금오공과대학교 학생회관 101호',
      'Gyeongsangbuk-do, Gumi City, Daehak-ro 61, Kumoh National Institute of Technology, Student Center, Room 101',
      [
        { korean: '경상북도', english: 'Gyeongsangbuk-do (province)' },
        { korean: '구미시', english: 'Gumi City' },
        { korean: '대학로 61', english: 'Daehak-ro (street) #61' },
        { korean: '101호', english: 'Room 101 (호 = unit)' },
      ],
      [ACT.culture]),
    createContentItem(
      'Naver Maps & Kakao Maps',
      'use these, not Google',
      'Google Maps has poor walking directions in Korea due to mapping-data restrictions. Locals use Naver Maps (네이버 지도) or Kakao Maps (카카오맵).',
      'sentence',
      '한국에서는 네이버 지도를 쓰세요. 더 정확해요.',
      'In Korea, use Naver Maps. It is more accurate.',
      null, [ACT.culture]),

    createContentItem(
      '과제: Guide a new student',
      'consolidation task',
      'A new exchange student texts you from the Kumoh main gate. Guide them to the library using 3-5 sentences. Use 똑바로, 오른쪽으로/왼쪽으로, ~ 옆에/앞에/뒤에, ~이/가 있어요.',
      'conversation',
      'Student: 정문에 왔어요. 도서관이 어디에 있어요?\nYou: [give 2-step direction]\nStudent: 학생회관이 보여요. 그 다음은요?\nYou: [next step + final position]\nStudent: 감사합니다!',
      'Student: I arrived at the gate. Where is the library?\nYou: …\nStudent: I see the student center. What next?\nYou: …\nStudent: Thank you!',
      [
        { korean: '정문에서 똑바로 가세요.', english: 'Go straight from the gate.' },
        { korean: '학생회관 옆에 있어요.', english: 'It is next to the student center.' },
        { korean: '오른쪽으로 가세요.', english: 'Go right.' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
