// Level 2 Track-Thematic — 복습 3 (Review 3)
// Consolidates Units 7-9: 옳고 그름, 흥미로운 세상, 한국의 대중문화.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2r3-orientation',
  vocabulary: 'l2r3-vocabulary',
  grammar: 'l2r3-grammar',
  mixedSentences: 'l2r3-mixed',
  speaking: 'l2r3-speaking',
  listening: 'l2r3-listening',
  writing: 'l2r3-writing',
  task: 'l2r3-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What this review covers',
    goals: ['Recall vocab + grammar from U7 (right/wrong), U8 (cultures), U9 (pop culture).', 'Combine opinion + cultural description + interview answers.'],
    task: 'Imagine being interviewed about Korean culture and having to defend an opinion.' },
  { id: ACT.vocabulary, section: 'Vocabulary Review', title: 'Mixed vocab from U7-9',
    goals: ['Recall key vocab.'],
    task: 'Use 5 words in fresh sentences.' },
  { id: ACT.grammar, section: 'Grammar Review', title: 'Mixed grammar from U7-9',
    goals: ['Combine patterns from each unit.'],
    task: 'Write 4 sentences mixing patterns.' },
  { id: ACT.mixedSentences, section: 'Mixed Sentences', title: 'Multi-pattern combos',
    goals: ['Combine cross-unit patterns.'],
    task: 'Build 3 multi-pattern sentences.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Pop-culture debate roleplay',
    goals: ['Defend a controversial opinion.'],
    task: 'Roleplay celebrity interview defending a controversial take.' },
  { id: ACT.listening, section: 'Listening', title: 'Cross-unit interview',
    goals: ['Follow an interview that mixes culture + opinion + softening.'],
    task: 'Identify the grammar pattern in each turn.' },
  { id: ACT.writing, section: 'Writing', title: 'Cross-unit reflection',
    goals: ['Write 5-6 sentences combining all 3 themes.'],
    task: 'Write reflection.' },
  { id: ACT.task, section: 'Task', title: 'Celebrity interview',
    goals: ['Use all 3 units\' grammar.'],
    task: 'Be interviewed about Korean culture.' },
];

const lesson = {
  title: '레벨 2 · 복습 3 (Review of Units 7-9)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'review',
  activities,
  expressionPractice: [
    { id: 'review-mixed', label: 'Opinion + culture + interview', goal: 'Combine 3 functions.' },
    { id: 'cross-unit-defending', label: 'Defending with softening', goal: 'Use ~다고 보다 (U7) + ~ 거든 (U9) + ~ 듯하다 (U9).' },
  ],
  relatedPools: ['topic-society', 'topic-culture'],
  content: [
    createContentItem('복습 목표', 'bokseup mokpyo', 'By end: opinion + culture + interview across U7-9 grammar.', 'word', 'Units 7+8+9 combined', 'Mixed practice.', null, [ACT.orientation]),
    createContentItem('상황 설정', 'sanghwang seoljeong', 'A Korean magazine interviews you about your views on Korean culture and a controversial opinion.', 'word', 'Interviewer + You alternate roles', 'Cross-unit flow.', null, [ACT.orientation]),

    createContentItem('의견', 'uigyeon', 'opinion (U7)', 'word', '제 의견은 다릅니다.', 'My opinion differs.', null, [ACT.vocabulary]),
    createContentItem('논란', 'nollan', 'controversy (U7)', 'word', '큰 논란이 있어요.', 'Big controversy.', null, [ACT.vocabulary]),
    createContentItem('비매너', 'bimaeneo', 'rude behavior (U7)', 'word', '비매너 행동이 너무해요.', 'Rude behavior is too much.', null, [ACT.vocabulary]),
    createContentItem('특징', 'teukjing', 'characteristic (U8)', 'word', '한국 음식의 특징.', 'Korean food features.', null, [ACT.vocabulary]),
    createContentItem('전통', 'jeontong', 'tradition (U8)', 'word', '전통이 잘 보존돼 있어요.', 'Tradition preserved.', null, [ACT.vocabulary]),
    createContentItem('지역별', 'jiyeokbyeol', 'by region (U8)', 'word', '지역별 사투리가 달라요.', 'Dialects differ by region.', null, [ACT.vocabulary]),
    createContentItem('연예인', 'yeonyein', 'celebrity (U9)', 'word', '연예인을 봤어요.', 'I saw a celebrity.', null, [ACT.vocabulary]),
    createContentItem('대중문화', 'daejungmunhwa', 'pop culture (U9)', 'word', '한국 대중문화가 강해요.', 'Korean pop culture is strong.', null, [ACT.vocabulary]),
    createContentItem('인터뷰', 'inteobyu', 'interview (U9)', 'word', '인터뷰가 길었어요.', 'Interview was long.', null, [ACT.vocabulary]),

    createContentItem('~ 더라도 (U7)', 'even if', 'Even if A.', 'sentence', '늦더라도 가야 해요.', 'Even if late, must go.', null, [ACT.grammar]),
    createContentItem('~ 다고 보다 (U7)', 'view as', 'View as A.', 'sentence', '무례하다고 봐요.', 'View as rude.', null, [ACT.grammar]),
    createContentItem('~ 비롯해서 (U8)', 'including', 'Including N.', 'sentence', '한복을 비롯해서.', 'Including hanbok.', null, [ACT.grammar]),
    createContentItem('~ (으)며 (U8)', 'formal and', 'Formal connector.', 'sentence', '바람이 불며 따뜻해요.', 'Wind and warm.', null, [ACT.grammar]),
    createContentItem('~ 거든 (U9)', 'because you see', 'Soft reason.', 'sentence', '비가 왔거든요.', 'It rained, you see.', null, [ACT.grammar]),
    createContentItem('~ 았더라면 (U9)', 'past counterfactual', 'If had ~.', 'sentence', '갔더라면 좋았을 텐데.', 'If only had gone.', null, [ACT.grammar]),
    createContentItem('~ ㄴ 듯하다 (U9)', 'seems', 'Soft inference.', 'sentence', '곧 컴백할 듯해요.', 'Seems comeback soon.', null, [ACT.grammar]),

    createContentItem('Combo 1 (U7 + U9)', 'opinion + soften',
      '~ 다고 보다 + ~ 거든 + ~ 듯하다.',
      'sentence', '저는 그 행동이 무례하다고 보거든요. 그러나 사람마다 의견이 다른 듯해요.',
      'I view that behavior as rude, you see. But it seems opinions differ.',
      null, [ACT.mixedSentences]),
    createContentItem('Combo 2 (U7 + U8)', 'culture + even if',
      '~ 비롯해서 + ~ 더라도.',
      'sentence', '제주도를 비롯해서 지역별 문화가 다양하더라도 한국이라는 정체성은 같아요.',
      'Including Jeju, even though cultures vary by region, the Korean identity is the same.',
      null, [ACT.mixedSentences]),
    createContentItem('Combo 3 (U8 + U9)', 'culture + regret',
      '~ 비롯한 + ~ 았/었더라면.',
      'sentence', '그때 데뷔했더라면 그 작품을 비롯한 많은 인기 곡을 만들었을 거예요.',
      'If they had debuted then, they would have made many hits including that work.',
      null, [ACT.mixedSentences]),

    createContentItem('Defending controversial opinion', 'speaking',
      'Combine 다고 보다 + 거든 + 듯하다.',
      'sentence', '저는 그 영화가 너무 폭력적이라고 보거든요. 어린이들이 보면 안 된다고 보는 듯해요.',
      'I view that film as too violent, you see. It seems experts also think children should not watch.',
      null, [ACT.speaking]),

    createContentItem('Cross-unit interview', 'listening',
      'Magazine interview.',
      'conversation',
      'A: 한국 문화에서 가장 흥미로운 점은 뭐라고 보세요?\nB: 음, 지역별 사투리를 비롯해서 다양한 문화가 공존한다는 점이 흥미롭다고 봐요.\nA: 그런데 일부 사람들이 사투리를 비웃는 행동도 있다고 하더라고요.\nB: 그런 비매너 행동은 옳지 않다고 보거든요. 그렇더라도 사람마다 다르게 받아들이는 듯해요.\nA: 마지막으로 한 말씀 부탁드려요.\nB: 사투리를 비롯한 모든 한국 문화가 자랑스러움이 됐으면 좋겠어요.',
      'A: Most intriguing thing about Korean culture? B: That diverse cultures coexist, including regional dialects. A: Some people mock dialects though. B: That rude behavior is wrong, you see. Still, it seems people take it differently. A: A word? B: I hope all Korean culture including dialects becomes a point of pride.',
      [
        { korean: '~ 다고 보다 (U7)', english: 'view as' },
        { korean: '~ 비롯해서 (U8)', english: 'including' },
        { korean: '~ 거든요 (U9)', english: 'you see' },
        { korean: '~ 듯하다 (U9)', english: 'seems' },
      ],
      [ACT.listening]),

    createContentItem('Reflection paragraph', 'writing',
      'Sample paragraph combining all three units.',
      'sentence',
      '한국 문화는 흥미로워요. 지역별 사투리를 비롯해서 다양한 전통이 있는 듯해요. 하지만 사람들이 가끔 다른 문화를 비웃는 행동도 보는데, 저는 그게 옳지 않다고 봐요. 더라도 한국에 살다 보니까 다양함이 곧 매력이라고 느껴요. 한국에 오기 전에 알았더라면 더 빨리 적응했을 거예요.',
      'Korean culture is intriguing. Including regional dialects, there seem to be diverse traditions. But people sometimes mock other cultures, which I view as wrong. Still, living in Korea I feel that diversity is the appeal. If only I had known before coming, I would have adapted faster.',
      null, [ACT.writing]),

    createContentItem('과제: Be interviewed', 'task',
      'Roleplay: Be interviewed about Korean culture. Use 3 patterns from each unit.',
      'conversation',
      'Interviewer: 한국 문화에서 가장 인상적인 점은요?\nYou: ~ 비롯해서 ~ 다고 봐요.\nInterviewer: 비매너 행동에 대해서는?\nYou: 옳지 않다고 보거든요.\nInterviewer: 어떻게 해야 할까요?\nYou: ~ 더라도 ~ 듯해요.\nInterviewer: 마지막 한 말씀은요?\nYou: ~ 았/었더라면 ~',
      'AI tutor will play the interviewer.',
      [
        { korean: '~ 다고 보다 (U7)', english: 'view as' },
        { korean: '~ 비롯해서 (U8)', english: 'including' },
        { korean: '~ 거든요 (U9)', english: 'you see' },
        { korean: '~ 았더라면 (U9)', english: 'if had' },
        { korean: '~ 듯하다 (U9)', english: 'seems' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
