// Level 2 Track-Adult Unit 7 — 안전모를 벗지 마십시오 (Workplace safety)
// Source: Book 2A·7.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2au7-orientation',
  pronunciation: 'l2au7-pronunciation',
  vocabularyGear: 'l2au7-vocab-gear',
  vocabularyHazards: 'l2au7-vocab-hazards',
  grammarProhibit: 'l2au7-grammar-prohibit',
  grammarMustNot: 'l2au7-grammar-must-not',
  reading: 'l2au7-reading',
  listening: 'l2au7-listening',
  writing: 'l2au7-writing',
  culture: 'l2au7-culture',
  task: 'l2au7-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Read safety signs and follow rules.', 'Report a workplace accident.', 'Use 3 prohibition/requirement patterns.'],
    task: 'Imagine getting injured at a factory — you must report quickly and clearly to your supervisor.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '발음 — Safety phrases',
    goals: ['Apply 경음화 in 마십시오 → [마십씨오].', 'Apply 비음화 in 됩니다.'],
    task: 'Read each rule aloud.' },
  { id: ACT.vocabularyGear, section: 'Vocabulary I', title: 'Safety gear',
    goals: ['Use 안전모·안전화·보호 장갑·보호 안경·마스크.'],
    task: 'Name 5 safety items.' },
  { id: ACT.vocabularyHazards, section: 'Vocabulary II', title: 'Hazards + emergency',
    goals: ['Use 위험·사고·응급·다치다·조심하다·금연·비상구.'],
    task: 'Identify 5 hazards.' },
  { id: ACT.grammarProhibit, section: 'Grammar I', title: 'V-지 마십시오 / V-아/어야 합니다',
    goals: ['Express formal prohibition (마십시오) and requirement (해야 합니다).'],
    task: 'State 3 workplace rules.' },
  { id: ACT.grammarMustNot, section: 'Grammar II', title: 'V-(으)면 안 됩니다 — must not',
    goals: ['Express prohibition through conditional + 안 됩니다.'],
    task: 'Convert 3 negative rules.' },
  { id: ACT.reading, section: 'Reading and Speaking', title: '읽고 말하기 — Safety sign',
    goals: ['Read a factory safety poster.'],
    task: 'Translate rules into action.' },
  { id: ACT.listening, section: 'Listening and Speaking', title: '듣고 말하기 — Reporting an accident',
    goals: ['Follow an accident-report dialogue.'],
    task: 'Reproduce with your scenario.' },
  { id: ACT.writing, section: 'Writing', title: '읽고 쓰기 — Accident report',
    goals: ['Write a 4-5 line accident report.'],
    task: 'Write your own.' },
  { id: ACT.culture, section: 'Culture Note', title: '문화 산책 — Korean workplace safety',
    goals: ['Know 산업안전보건법 (industrial safety law).', 'Know 119 (emergency) + 1644 hotlines for migrant workers.'],
    task: 'List 3 must-have safety items at your job.' },
  { id: ACT.task, section: 'Task', title: '과제 — Report a hand injury',
    goals: ['Combine vocabulary + 3 rule patterns + emergency reporting.'],
    task: 'Roleplay reporting a finger injury.' },
];

const lesson = {
  title: '레벨 2 (직장) · 7과: 안전모를 벗지 마십시오 (Workplace Safety)',
  category: 'business',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'workplace',
  activities,
  expressionPractice: [
    { id: 'stating-rule', label: 'Stating a rule', goal: 'Use V-지 마십시오 / V-아/어야 합니다.' },
    { id: 'reporting-accident', label: 'Reporting an accident', goal: 'Report what, where, to whom in 2-3 sentences.' },
    { id: 'asking-help', label: 'Asking for help', goal: 'Use 도와주십시오 / 빨리 와 주세요.' },
  ],
  relatedPools: ['topic-society'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: follow safety rules, report accidents, request emergency help.', 'word', 'Functions: prohibit · require · report · request help', 'Safety toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'Your finger gets caught in a machine. You must alert the supervisor immediately and request first aid.', 'word', 'You: 과장님, 손가락을 다쳤습니다. — 과장님: 응급실로 가야 합니다.', 'I hurt my finger. — Must go to emergency.', null, [ACT.orientation]),

    createContentItem('마십시오 → [마십씨오]', 'masipssio', '경음화: ㅂ + ㅅ → ㅂ + ㅆ.', 'word', '벗지 마십시오.', 'Do not take off.', null, [ACT.pronunciation]),
    createContentItem('됩니다 → [됨니다]', 'doemnida', '비음화.', 'word', '안 됩니다.', 'Not allowed.', null, [ACT.pronunciation]),
    createContentItem('비상구 → [비상구]', 'bisanggu', 'No change.', 'word', '비상구', 'emergency exit.', null, [ACT.pronunciation]),
    createContentItem('다쳤습니다 → [다쳗씀니다]', 'dachyeoseumnida', '경음화 + 비음화.', 'word', '손을 다쳤습니다.', 'I hurt my hand.', null, [ACT.pronunciation]),

    createContentItem('안전모', 'anjeonmo', 'safety helmet', 'word', '안전모를 꼭 쓰십시오.', 'Wear the helmet.', null, [ACT.vocabularyGear]),
    createContentItem('안전화', 'anjeonhwa', 'safety shoes', 'word', '안전화를 신어야 합니다.', 'Must wear safety shoes.', null, [ACT.vocabularyGear]),
    createContentItem('보호 장갑', 'boho janggap', 'protective gloves', 'word', '보호 장갑을 끼십시오.', 'Wear gloves.', null, [ACT.vocabularyGear]),
    createContentItem('보호 안경', 'boho angyeong', 'safety goggles', 'word', '보호 안경을 끼십시오.', 'Wear goggles.', null, [ACT.vocabularyGear]),
    createContentItem('마스크', 'maseukeu', 'mask', 'word', '마스크를 끼세요.', 'Wear mask.', null, [ACT.vocabularyGear]),
    createContentItem('안전벨트', 'anjeonbelteu', 'safety belt', 'word', '안전벨트를 매십시오.', 'Buckle safety belt.', null, [ACT.vocabularyGear]),
    createContentItem('소방기', 'sobanggi', 'fire extinguisher', 'word', '소방기는 입구에 있습니다.', 'Extinguisher at entrance.', null, [ACT.vocabularyGear]),
    createContentItem('비상등', 'bisangdeung', 'emergency light', 'word', '비상등이 켜집니다.', 'Emergency light turns on.', null, [ACT.vocabularyGear]),

    createContentItem('위험', 'wiheom', 'danger', 'word', '여기는 위험합니다.', 'Dangerous here.', null, [ACT.vocabularyHazards]),
    createContentItem('사고', 'sago', 'accident', 'word', '사고가 났습니다.', 'There was an accident.', null, [ACT.vocabularyHazards]),
    createContentItem('응급', 'eunggeup', 'emergency', 'word', '응급 상황입니다.', 'Emergency situation.', null, [ACT.vocabularyHazards]),
    createContentItem('응급실', 'eunggeupsil', 'ER', 'word', '응급실로 가십시오.', 'Go to ER.', null, [ACT.vocabularyHazards]),
    createContentItem('다치다', 'dachida', 'get injured', 'word', '손을 다쳤습니다.', 'Hurt my hand.', null, [ACT.vocabularyHazards]),
    createContentItem('조심하다', 'josimhada', 'be careful', 'word', '조심하십시오.', 'Be careful.', null, [ACT.vocabularyHazards]),
    createContentItem('금연', 'geumyeon', 'no smoking', 'word', '여기는 금연 구역입니다.', 'No-smoking zone.', null, [ACT.vocabularyHazards]),
    createContentItem('비상구', 'bisanggu', 'emergency exit', 'word', '비상구를 막지 마십시오.', 'Do not block emergency exit.', null, [ACT.vocabularyHazards]),
    createContentItem('피가 나다', 'piga nada', 'to bleed', 'word', '피가 나요.', 'Bleeding.', null, [ACT.vocabularyHazards]),
    createContentItem('끼이다', 'kkiida', 'to get caught', 'word', '기계에 끼였어요.', 'Got caught in machine.', null, [ACT.vocabularyHazards]),

    createContentItem('V-지 마십시오 — formal "do not"', 'prohibition', 'For workplace rules + signs. Stronger than 마세요.', 'sentence', '안전모를 벗지 마십시오.', 'Do not remove the helmet.',
      [{ korean: '벗 + 지 마십시오', english: 'do not remove' }, { korean: '들어가 + 지 마십시오', english: 'do not enter' }], [ACT.grammarProhibit]),
    createContentItem('V-아/어야 합니다 — must V', 'requirement', 'Express formal requirement.', 'sentence', '항상 보호 장갑을 끼셔야 합니다.', 'Must always wear gloves.',
      [{ korean: '끼시 + 어야 합니다', english: 'must wear (honorific)' }, { korean: '신 + 어야 합니다', english: 'must wear (shoes)' }], [ACT.grammarProhibit]),

    createContentItem('V-(으)면 안 됩니다 — must not V', 'conditional prohibition', 'Express prohibition through conditional.', 'sentence', '비상구 앞에 짐을 두면 안 됩니다.', 'Must not place items at emergency exit.',
      [{ korean: '두 + 면 안 됩니다', english: 'must not place' }, { korean: '들어가 + 면 안 됩니다', english: 'must not enter' }], [ACT.grammarMustNot]),
    createContentItem('Comparison', 'three patterns', 'V-지 마십시오 = direct order. V-아/어야 합니다 = requirement. V-(으)면 안 됩니다 = "if X, no good".', 'sentence', '비상구를 막지 마십시오 = 비상구 앞에 짐을 두면 안 됩니다.', 'Both prohibit the same thing.',
      null, [ACT.grammarMustNot]),

    createContentItem('Safety poster', 'reading',
      'Read this poster.',
      'sentence',
      '⚠️ 안전 수칙 ⚠️\n1. 작업 중 안전모를 벗지 마십시오.\n2. 보호 장갑을 항상 끼셔야 합니다.\n3. 비상구 앞에 짐을 두면 안 됩니다.\n4. 금연 구역에서 담배를 피우지 마십시오.\n5. 사고 시 즉시 119에 신고하십시오.',
      '⚠️ Safety Rules:\n1. Do not remove helmet during work.\n2. Must wear gloves at all times.\n3. Do not block emergency exit.\n4. Do not smoke in no-smoking zones.\n5. Report accidents to 119 immediately.',
      [
        { korean: '수칙', english: 'rules' },
        { korean: '즉시', english: 'immediately' },
        { korean: '신고하다', english: 'to report' },
      ],
      [ACT.reading]),

    createContentItem('Reporting accident', 'listening',
      'Worker reports an injury.',
      'conversation',
      'A (직원): 과장님, 죄송합니다. 작업 중에 손을 좀 다쳤습니다.\nB (과장): 어떻게 다쳤어요? 많이 아픕니까?\nA: 기계에 손가락이 끼었습니다. 피가 좀 납니다.\nB: 빨리 응급실로 가야 합니다. 제가 같이 갈게요.\nA: 감사합니다. 보호 장갑을 끼고 있었는데도 다쳤습니다.\nB: 사고는 누구한테나 일어날 수 있어요. 일단 치료를 받고 보고서를 쓰지요.',
      'A: Manager, sorry. I hurt my hand while working. B: How? Hurts a lot? A: Finger caught in machine. Some blood. B: Must go to ER. I will come. A: Thanks. Wore gloves but still got hurt. B: Accidents happen. Get treatment first, then report.',
      [
        { korean: '기계에 끼이다', english: 'caught in machine' },
        { korean: '피가 나다', english: 'bleeding' },
        { korean: '보고서', english: 'report' },
      ],
      [ACT.listening]),

    createContentItem('Accident report', 'writing',
      'Sample written report.',
      'sentence',
      '사고 보고서\n· 일시: 2026년 5월 11일 14:30\n· 장소: 제 2 작업장\n· 사고 내용: 작업 중 기계에 오른손 검지가 끼였습니다. 보호 장갑을 끼고 있었으나 손가락 끝이 다쳤습니다.\n· 응급 조치: 즉시 응급실로 가서 치료를 받았습니다.\n· 작성자: 김민수',
      'Accident Report:\n- Date: May 11, 2026, 14:30\n- Location: Workshop 2\n- Details: Index finger caught in machine. Wore gloves but tip injured.\n- First aid: Went to ER immediately.\n- Author: Kim Minsu.',
      null, [ACT.writing]),

    createContentItem('Korean workplace safety', 'culture',
      '산업안전보건법 (Industrial Safety Law) requires PPE in factories. Migrant workers can call 1644-0644 for the migrant-worker hotline in their language. Emergency: 119 (fire/medical), 112 (police). Most factories run weekly safety drills.',
      'sentence', '한국 공장에서는 산업안전보건법을 지켜야 합니다.',
      'Korean factories must follow industrial safety law.',
      [
        { korean: '산업안전보건법', english: 'industrial safety law' },
        { korean: '119', english: 'emergency (fire/medical)' },
        { korean: '1644-0644', english: 'migrant worker hotline' },
      ],
      [ACT.culture]),

    createContentItem('과제: Report a hand injury', 'task',
      'Roleplay: Report a finger injury to the manager.',
      'conversation',
      'You: 과장님, 작업 중에 ~ 다쳤습니다.\nManager: 어떻게 다쳤어요?\nYou: 기계에 ~. ~ 끼고 있었지만 ~\nManager: ~ 가야 합니다.\nYou: 감사합니다.',
      'AI tutor will play the manager.',
      [
        { korean: '~ 다쳤습니다', english: 'I got hurt' },
        { korean: '~ 응급실로 가야 합니다', english: 'must go to ER' },
        { korean: '~ 마십시오 / ~야 합니다', english: 'rules' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
