// Level 2 Unit 6 — 공연과 축제 (Performances and festivals)
// Source: Book 2D Unit 6.
// Grammar: A/V-기는(요), A/V-든(지), N(이)야말로, 여간 A-(으)ㄴ 것이 아니다.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2u6-orientation',
  vocabulary: 'l2u6-vocabulary',
  pronunciation: 'l2u6-pronunciation',
  grammar: 'l2u6-grammar',
  speaking: 'l2u6-speaking',
  readingSpeaking: 'l2u6-reading-speaking',
  listeningSpeaking: 'l2u6-listening-speaking',
  readingWriting: 'l2u6-reading-writing',
  culture: 'l2u6-culture',
  task: 'l2u6-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Discuss performances + festivals with appreciation and recommendation.', 'Use 4 advanced patterns: ~기는요, ~든지, ~이야말로, 여간 ~ 아니다.', 'Sing Arirang or quote its meaning.'],
    task: 'Imagine inviting a friend to a Kumoh festival and recommending what to see.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Festival + performance words',
    goals: ['Use 공연·축제·관객·무대·가수·밴드·감상·평가.', 'Use the -거리 suffix (볼거리, 먹거리, 즐길거리).'],
    task: 'Use 3 -거리 nouns in sentences.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: 'Intonation of -기는요',
    goals: ['Use falling-then-rising contour to soften deflection.'],
    task: 'Read 3 -기는요 sentences naturally.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Festival-talk patterns',
    goals: ['A/V-기는(요) — deflecting compliment', 'A/V-든(지) — whatever / whichever', 'N(이)야말로 — truly the one', '여간 A-(으)ㄴ 것이 아니다 — exceptionally'],
    task: 'Use each pattern in a sentence.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Recommending participation',
    goals: ['Recommend a festival to a friend.'],
    task: 'Recommend one Korean festival.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Festival intros',
    goals: ['Read festival intros.', 'Introduce one in your own words.'],
    task: 'Introduce a festival from your country.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Festival news + appreciation',
    goals: ['Listen to news intro about a festival.', 'Discuss appreciation.'],
    task: 'Discuss a performance you liked.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Performance review',
    goals: ['Read a review.', 'Write your own.'],
    task: 'Write 3-sentence review.' },
  { id: ACT.culture, section: 'Culture Note', title: '아리랑 — Korea\'s representative folk song',
    goals: ['Know Arirang as Korea\'s most iconic folk song.', 'Know that UNESCO designated it intangible cultural heritage in 2012.'],
    task: 'Compare Arirang with a folk song from your culture.' },
  { id: ACT.task, section: 'Task', title: 'Recommend a festival',
    goals: ['Combine all 4 patterns + festival vocab.'],
    task: 'Recommend a Kumoh festival to the AI tutor.' },
];

const lesson = {
  title: '레벨 2 · 6과: 공연과 축제 (Performances and Festivals)',
  category: 'daily-life',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'introducing', label: 'Introducing as must-see', goal: 'Use N(이)야말로.' },
    { id: 'rating-assessing', label: 'Rating exceptionally', goal: 'Use 여간 A-(으)ㄴ 것이 아니다.' },
    { id: 'deflecting-compliment', label: 'Deflecting a compliment', goal: 'Use A/V-기는(요) to humbly deflect.' },
  ],
  relatedPools: ['topic-culture'],
  content: [
    createContentItem('학습 목표', 'hakseup mokpyo', 'By end: recommend festivals/performances with native-like emphasis patterns.', 'word', 'Functions: recommend · highlight · evaluate · deflect', 'Festival-talk toolkit.', null, [ACT.orientation]),
    createContentItem('오늘의 상황', 'oneurui sanghwang', 'Kumoh\'s annual 대학축제 (uni-festival) is in May. You invite Sarah, hyping the must-see acts and food.', 'word', 'You: 다음 주 우리 학교 축제 있어. 아리랑이야말로 꼭 들어 봐야 해.', 'You: Festival next week. Arirang is the must-listen.', null, [ACT.orientation]),

    createContentItem('공연', 'gongyeon', 'performance', 'word', '공연을 봐요.', 'I see a performance.', null, [ACT.vocabulary]),
    createContentItem('축제', 'chukje', 'festival', 'word', '축제가 5월에 있어요.', 'Festival in May.', null, [ACT.vocabulary]),
    createContentItem('관객', 'gwangaek', 'audience', 'word', '관객이 많아요.', 'Many in the audience.', null, [ACT.vocabulary]),
    createContentItem('무대', 'mudae', 'stage', 'word', '무대가 멋있어요.', 'Stage is impressive.', null, [ACT.vocabulary]),
    createContentItem('가수', 'gasu', 'singer', 'word', '유명 가수가 와요.', 'Famous singer comes.', null, [ACT.vocabulary]),
    createContentItem('밴드', 'baendeu', 'band', 'word', '밴드 공연이에요.', 'Band performance.', null, [ACT.vocabulary]),
    createContentItem('감상', 'gamsang', 'appreciation', 'word', '공연 감상을 써요.', 'I write impressions.', null, [ACT.vocabulary]),
    createContentItem('평가', 'pyeongga', 'evaluation', 'word', '평가가 좋아요.', 'Good evaluations.', null, [ACT.vocabulary]),
    createContentItem('볼거리', 'bolgeori', 'things to see', 'word', '볼거리가 많아요.', 'Many things to see.', null, [ACT.vocabulary]),
    createContentItem('먹거리', 'meokgeori', 'things to eat', 'word', '먹거리가 가득해요.', 'Full of food.', null, [ACT.vocabulary]),
    createContentItem('즐길거리', 'jeulgilgeori', 'things to enjoy', 'word', '즐길거리가 많아요.', 'Many fun activities.', null, [ACT.vocabulary]),
    createContentItem('아리랑', 'arirang', 'Arirang (folk song)', 'word', '아리랑이 대표 민요예요.', 'Arirang is the iconic folk song.', null, [ACT.vocabulary]),
    createContentItem('민요', 'minyo', 'folk song', 'word', '한국 민요를 좋아해요.', 'I like Korean folk songs.', null, [ACT.vocabulary]),
    createContentItem('전통', 'jeontong', 'tradition', 'word', '전통 공연이 멋있어요.', 'Traditional performances are great.', null, [ACT.vocabulary]),
    createContentItem('인기 있다', 'ingi itda', 'be popular', 'word', '이 가수가 인기 있어요.', 'This singer is popular.', null, [ACT.vocabulary]),

    createContentItem('잘하기는요 → [잘하기는요]', 'falling-rising', 'In -기는요, drop pitch on 기는 then rise on 요. Softens deflection.', 'word', '잘하기는요!', 'Hardly!', null, [ACT.pronunciation]),
    createContentItem('이야말로 → [이야말로]', 'iyamallo', 'Smooth flow — no major sound change.', 'word', '이거야말로!', 'This is the one!', null, [ACT.pronunciation]),
    createContentItem('여간 → [여간]', 'yeogan', 'No change. Clear ㄴ받침.', 'word', '여간 멋있는 게 아니에요.', 'Truly impressive.', null, [ACT.pronunciation]),
    createContentItem('볼거리 → [볼꺼리]', 'bolkkeori', '경음화: ㄹ받침 + ㄱ → tense ㄲ.', 'word', '볼거리가 많아요. → [볼꺼리가]', 'Many things to see.', null, [ACT.pronunciation]),

    createContentItem('A/V-기는(요) — deflecting compliment', 'kineunyo', 'Modestly deflect what someone said. Often paired with a humble follow-up.', 'sentence', '제가 잘하기는요. 아직 부족해요.', 'Me, do well? Hardly. Still lacking.',
      [{ korean: 'A/V-기는요', english: 'hardly / not really' }, { korean: 'follow-up', english: '아직 부족해요 / 별로예요' }], [ACT.grammar]),
    createContentItem('A/V-든(지) — whatever', 'deunji', 'Whatever / whichever option. Often paired with 다.', 'sentence', '뭘 먹든지 다 맛있어요.', 'Whatever you eat, all good.',
      [{ korean: '뭘 + 먹든지', english: 'whatever you eat' }, { korean: '~든지 ~든지', english: 'whether ~ or ~' }], [ACT.grammar]),
    createContentItem('N(이)야말로 — truly the one', 'iyamallo', 'Highlight N as THE definitive example. Strong emphasis.', 'sentence', '아리랑이야말로 한국의 대표 민요예요.', 'Arirang is THE Korean folk song.',
      [{ korean: '아리랑 + 이야말로', english: 'after consonant → 이야말로' }, { korean: '서울 + 야말로', english: 'after vowel → 야말로' }], [ACT.grammar]),
    createContentItem('여간 A-(으)ㄴ 것이 아니다 — exceptionally A', 'yeogan', 'Literally "not just A" — meaning "exceptionally A". Always with negation 아니다.', 'sentence', '여간 멋있는 공연이 아니었어요.', 'An exceptionally great performance.',
      [{ korean: '여간 + A-(으)ㄴ 것이 아니다', english: 'exceptionally A' }, { korean: '여간 + 어려운 것이 아니에요', english: 'exceptionally difficult' }], [ACT.grammar]),

    createContentItem('Recommending a festival', 'speaking',
      'Use ~이야말로 to hype.',
      'sentence', '한국에서 부산 국제 영화제야말로 꼭 가 봐야 해요. 여간 재미있는 게 아니에요.',
      'In Korea, the Busan International Film Festival is THE must-see. Exceptionally fun.',
      null, [ACT.speaking]),

    createContentItem('Festival intro', 'reading',
      'Read this intro to Korea\'s most famous festival.',
      'sentence',
      '진주 남강 유등 축제는 매년 10월에 열려요. 강에 만 개의 등이 떠 있는 모습이야말로 정말 환상적이에요. 볼거리와 먹거리가 가득하고, 가족 단위로도 즐기기 좋아요. 여간 멋있는 축제가 아니에요. 한 번쯤은 꼭 가 보시기를 추천해요.',
      'The Jinju Namgang Yudeung Festival is held every October. The sight of 10,000 lanterns floating on the river is truly fantastic. Full of sights and food, great for families. An exceptionally beautiful festival. I recommend visiting at least once.',
      [
        { korean: '~이야말로', english: 'truly the one' },
        { korean: '여간 ~ 아니다', english: 'exceptionally' },
      ],
      [ACT.readingSpeaking]),

    createContentItem('Festival invite', 'listening',
      'Inviting a friend.',
      'conversation',
      'A: 사라야, 다음 주에 우리 학교 대학 축제 있어. 같이 갈래?\nB: 좋아! 뭐가 있어?\nA: 가수 공연도 있고 먹거리도 가득하고 볼거리도 많아.\nB: 표는 비싸?\nA: 비싸기는요. 학생은 무료야.\nB: 와, 그러면 꼭 가야지. 아리랑이야말로 들어 보고 싶어.\nA: 그럼 5시에 정문 앞에서 봐.',
      'A: Festival next week. Come? B: Yes! What\'s there? A: Singers, food, sights. B: Tickets expensive? A: Hardly. Free for students. B: I gotta go. Arirang is the must-listen. A: 5 PM at the main gate.',
      [
        { korean: '비싸기는요', english: 'hardly expensive' },
        { korean: '아리랑이야말로', english: 'Arirang is the one' },
        { korean: '꼭 가야지', english: 'I should definitely go' },
      ],
      [ACT.listeningSpeaking]),

    createContentItem('Performance review', 'reading + writing',
      'Sample review.',
      'sentence',
      '어제 본 뮤지컬은 여간 감동적인 게 아니었어요. 무대도 멋있고 음악도 좋고 배우들의 실력도 뛰어났어요. 무엇을 평가하든지 다 좋았어요. 이 작품이야말로 올해 최고의 공연이라고 생각해요.',
      'The musical I saw yesterday was exceptionally moving. The stage was great, music great, actors were brilliant. Whatever you evaluate, it was all good. This piece is THE best performance of the year.',
      [
        { korean: '여간 ~ 아니다', english: 'exceptionally' },
        { korean: '~든지 ~', english: 'whatever ~' },
        { korean: '~이야말로', english: 'THE one' },
      ],
      [ACT.readingWriting]),

    createContentItem('아리랑 — Korea\'s folk song', 'culture',
      'Arirang (아리랑) is Korea\'s most representative folk song, with hundreds of regional variants. UNESCO designated it Intangible Cultural Heritage of Humanity in 2012. The lyrics evoke longing and separation. Iconic phrase: "아리랑 아리랑 아라리요, 아리랑 고개를 넘어간다."',
      'sentence', '아리랑은 한국의 대표 민요로, 유네스코 무형문화유산이에요.',
      'Arirang is Korea\'s iconic folk song, UNESCO Intangible Heritage.',
      [
        { korean: '아리랑', english: 'Arirang' },
        { korean: '민요', english: 'folk song' },
        { korean: '유네스코 무형문화유산', english: 'UNESCO Intangible Cultural Heritage' },
        { korean: '대표', english: 'representative' },
      ],
      [ACT.culture]),

    createContentItem('과제: Festival recommendation', 'task',
      'Roleplay: Recommend a Korean festival to a friend visiting from abroad. Use 4 patterns + at least one -거리.',
      'conversation',
      'Friend: 한국에서 꼭 가 봐야 할 축제가 뭐예요?\nYou: ~이야말로 ~ (highlight)\nFriend: 그래요? 그런데 비싸요?\nYou: 비싸기는요 ~ (deflect)\nFriend: 뭐가 있어요?\nYou: 볼거리, 먹거리, ~ 든지 ~ (multiple options)\nFriend: 좋아요. 가 봐야겠어요.\nYou: 여간 ~ 아닐 거예요.',
      'AI tutor will play the friend.',
      [
        { korean: '~이야말로', english: 'THE one' },
        { korean: '~기는요', english: 'hardly' },
        { korean: '~든지', english: 'whatever' },
        { korean: '여간 ~ 아니다', english: 'exceptionally' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
