// Level 2 Unit 8 — 흥미로운 세상 (Intriguing world)
// Source: Book 2D Unit 8.
// Grammar: V-아다(가)/어다(가), A-다는 N V-ㄴ/는다는 N, N을/를 비롯해서, A/V-(으)며.

const createContentItem = (
  korean, romanization, english, type = 'word',
  example = '', exampleEnglish = '', breakdown = null, activityIds = [],
) => ({
  type, activityIds,
  targetText: korean, romanization, nativeText: english, pronunciation: romanization,
  exampleTarget: example || korean, exampleNative: exampleEnglish || english,
  korean, english, example: example || korean, exampleEnglish: exampleEnglish || english,
  ...(breakdown ? { breakdown: breakdown.map(b => ({ target: b.korean, native: b.english, korean: b.korean, english: b.english })) } : {}),
});

const ACT = {
  orientation: 'l2u8-orientation',
  vocabulary: 'l2u8-vocabulary',
  pronunciation: 'l2u8-pronunciation',
  grammar: 'l2u8-grammar',
  speaking: 'l2u8-speaking',
  readingSpeaking: 'l2u8-reading-speaking',
  listeningSpeaking: 'l2u8-listening-speaking',
  readingWriting: 'l2u8-reading-writing',
  culture: 'l2u8-culture',
  task: 'l2u8-task',
};

const activities = [
  { id: ACT.orientation, section: 'Orientation', title: 'What you will be able to do',
    goals: ['Describe regional/cultural features with 4 advanced patterns.', 'Use -아다(가), -ㄴ다는 N, ~ 비롯해서, -(으)며.', 'Discuss 제주도 culture.'],
    task: 'Imagine giving a 5-minute presentation on a unique cultural feature of your country.' },
  { id: ACT.vocabulary, section: 'Vocabulary', title: 'Culture + -별 suffix',
    goals: ['Use 문화·특징·지역·사투리·전통·소수민족.', 'Use the -별 suffix (per/by): 나라별, 지역별, 도시별.'],
    task: 'Use 3 -별 words.' },
  { id: ACT.pronunciation, section: 'Pronunciation', title: '격음화 — Aspiration in 비롯해서',
    goals: ['Apply 격음화: 비롯해서 → [비로태서] (ㅅ + ㅎ → ㅌ).'],
    task: 'Read 비롯해서, 비롯하여 aloud.' },
  { id: ACT.grammar, section: 'Grammar and Expression', title: 'Description + inclusion patterns',
    goals: ['V-아다(가)/어다(가) — do elsewhere then bring back', 'A-다는 N / V-ㄴ다는 N — the N that ~', 'N을/를 비롯해서 — including N', 'A/V-(으)며 — and (formal connector)'],
    task: 'Use each pattern in cultural descriptions.' },
  { id: ACT.speaking, section: 'Speaking', title: 'Explaining a market',
    goals: ['Explain a finding from a market.'],
    task: 'Explain one fact about a market in your country.' },
  { id: ACT.readingSpeaking, section: 'Reading and Speaking', title: 'Game explanations',
    goals: ['Read game intros.', 'Explain a game.'],
    task: 'Explain a game from your hometown.' },
  { id: ACT.listeningSpeaking, section: 'Listening and Speaking', title: 'Korean dialect presentation',
    goals: ['Listen to a dialect presentation.', 'Ask questions.'],
    task: 'Ask 2 follow-up questions.' },
  { id: ACT.readingWriting, section: 'Reading and Writing', title: 'Minority culture writing',
    goals: ['Read about minorities.', 'Write explanation.'],
    task: 'Write 3 sentences about a minority culture.' },
  { id: ACT.culture, section: 'Culture Note', title: '제주도 정낭 — Jeju pole-fence gates',
    goals: ['Understand 정낭 (Jeju traditional gate) and what each pole position means.'],
    task: 'Compare 정낭 with traditional doors in your culture.' },
  { id: ACT.task, section: 'Task', title: 'Cultural presentation outline',
    goals: ['Combine 4 patterns in a presentation about your culture.'],
    task: 'Outline a 5-minute presentation.' },
];

const lesson = {
  title: '레벨 2 · 8과: 흥미로운 세상 (Intriguing World)',
  category: 'travel',
  difficulty: 'intermediate',
  targetLang: 'ko', nativeLang: 'en',
  track: 'textbook', lessonType: 'thematic',
  activities,
  expressionPractice: [
    { id: 'asking-questions', label: 'Asking questions', goal: 'Ask follow-up questions after a presentation.' },
    { id: 'replying', label: 'Replying with description', goal: 'Use A-다는 N / V-ㄴ/는다는 N to formulate a thoughtful answer.' },
    { id: 'introducing-feature', label: 'Introducing a key feature', goal: 'Use N을/를 비롯해서 to lead with one example.' },
  ],
  relatedPools: ['topic-culture'],
  content: [
    createContentItem('Lesson goal', 'culture + presentations', 'By end: describe cultural features with native-like connectors and inclusion patterns.', 'word', 'Functions: describe · include · connect · ask', 'Cultural-talk toolkit.', null, [ACT.orientation]),
    createContentItem('Real-world scenario', 'culture presentation', 'You give a presentation to your Korean class about a unique feature of your country: a market, a game, a tradition.', 'word', 'You: 우리 나라는 N을/를 비롯해서 ~. — Audience: 더 설명해 주세요.', 'You: My country includes N. — Audience: Tell us more.', null, [ACT.orientation]),

    createContentItem('문화', 'munhwa', 'culture', 'word', '한국 문화는 다양해요.', 'Korean culture is diverse.', null, [ACT.vocabulary]),
    createContentItem('특징', 'teukjing', 'characteristic', 'word', '특징을 설명할게요.', 'I will explain the features.', null, [ACT.vocabulary]),
    createContentItem('지역', 'jiyeok', 'region', 'word', '지역마다 달라요.', 'Differs by region.', null, [ACT.vocabulary]),
    createContentItem('사투리', 'saturi', 'dialect', 'word', '경상도 사투리는 강해요.', 'Gyeongsang dialect is strong.', null, [ACT.vocabulary]),
    createContentItem('전통', 'jeontong', 'tradition', 'word', '전통이 잘 보존돼 있어요.', 'Tradition is well preserved.', null, [ACT.vocabulary]),
    createContentItem('소수 민족', 'sosu minjok', 'minority group', 'word', '소수 민족 문화도 중요해요.', 'Minority culture matters too.', null, [ACT.vocabulary]),
    createContentItem('나라별', 'narabyeol', 'by country (-별)', 'word', '나라별 인사가 달라요.', 'Greetings differ by country.', null, [ACT.vocabulary]),
    createContentItem('지역별', 'jiyeokbyeol', 'by region', 'word', '지역별 음식이 다양해요.', 'Foods differ by region.', null, [ACT.vocabulary]),
    createContentItem('도시별', 'dosibyeol', 'by city', 'word', '도시별 인구가 달라요.', 'Populations differ by city.', null, [ACT.vocabulary]),
    createContentItem('연령별', 'yeonryeongbyeol', 'by age group', 'word', '연령별 통계예요.', 'Statistics by age.', null, [ACT.vocabulary]),
    createContentItem('정낭', 'jeongnang', 'Jeju pole-fence gate', 'word', '정낭은 제주도의 문이에요.', 'Jeongnang is a Jeju-style gate.', null, [ACT.vocabulary]),
    createContentItem('전통 시장', 'jeontong sijang', 'traditional market', 'word', '전통 시장이 활기차요.', 'Traditional market is lively.', null, [ACT.vocabulary]),
    createContentItem('보존하다', 'bojonhada', 'to preserve', 'word', '문화를 보존해요.', 'Preserve the culture.', null, [ACT.vocabulary]),
    createContentItem('흥미롭다', 'heungmiropda', 'be intriguing', 'word', '정말 흥미로워요.', 'Really intriguing.', null, [ACT.vocabulary]),

    createContentItem('비롯해서 → [비로태서]', 'birotaeso', '격음화: ㅅ + ㅎ → ㅌ.', 'word', '한복을 비롯해서 → [비로태서]', 'Including hanbok.', null, [ACT.pronunciation]),
    createContentItem('비롯하여 → [비로타여]', 'birotayeo', 'Same 격음화, formal form.', 'word', '~을/를 비롯하여 ~', 'Including ~.', null, [ACT.pronunciation]),
    createContentItem('막대기 → [막때기]', 'makttaegi', '경음화: ㄱ받침 + ㄷ → ㄱ + ㄸ.', 'word', '막대기 세 개 → [막때기]', 'Three poles.', null, [ACT.pronunciation]),
    createContentItem('-(으)며 → smooth', 'meuyeo', 'No major change. Practice the formal connector flow.', 'word', '~며 ~며 ~', 'and ~ and ~', null, [ACT.pronunciation]),

    createContentItem('V-아/어다(가) — do elsewhere then bring back', 'transport action', 'Two actions: do V1 elsewhere, then come/return and do something with the result.', 'sentence', '시장에서 사 가지고 와서 만들었어요.', 'I bought it at the market, brought it back, made it.',
      [{ korean: '사 + 어다가', english: 'buy and bring back' }, { korean: '가지 + 어다가', english: 'take and bring back' }], [ACT.grammar]),
    createContentItem('V-ㄴ/는다는 N — the N that ~', 'descriptive noun', 'Convert a fact into a noun modifier.', 'sentence', '한국에서는 명절을 중요시한다는 특징이 있어요.', 'A characteristic of Korea is that holidays are valued.',
      [
        { korean: 'A-다는 N', english: 'adjective' },
        { korean: 'V-ㄴ다는 N (vowel)', english: 'verb (vowel-ending stem)' },
        { korean: 'V-는다는 N (consonant)', english: 'verb (consonant-ending stem)' },
      ],
      [ACT.grammar]),
    createContentItem('N을/를 비롯해서 — including N', 'including', 'Lead with one example, implying more.', 'sentence', '한복을 비롯해서 한국 전통 옷이 많아요.', 'Including hanbok, many traditional Korean clothes.',
      [{ korean: 'N을/를 비롯해서', english: 'including (with 서)' }, { korean: 'N을/를 비롯한 N', english: 'N including N (adnominal)' }], [ACT.grammar]),
    createContentItem('A/V-(으)며 — and (formal)', 'formal and', 'Formal version of -고 for connecting clauses in writing/presentations.', 'sentence', '제주도는 바람이 많이 불며 따뜻해요.', 'Jeju has lots of wind and is warm.',
      [{ korean: '-(으)며', english: 'formal "and"' }, { korean: 'usage', english: 'writing, presentations, news' }], [ACT.grammar]),

    createContentItem('Market explanation', 'speaking',
      'Use -(으)며 in description.',
      'sentence', '제 나라의 전통 시장은 활기차며 음식이 정말 다양해요. 채소를 비롯해서 모든 것을 살 수 있어요.',
      'My country\'s traditional market is lively and has very diverse food. You can buy everything including vegetables.',
      null, [ACT.speaking]),

    createContentItem('Jeju jeongnang', 'reading',
      'Read this cultural intro.',
      'sentence',
      '제주도에는 정낭이라는 전통 문이 있어요. 정낭은 막대기 세 개로 만든다는 특징이 있으며 막대기의 위치로 집 상태를 알려요. 세 개 다 올라가 있으면 멀리 떠났다는 뜻이고, 두 개면 곧 돌아온다는 뜻이에요. 한복을 비롯해서 한국에는 많은 전통 문화가 있지만, 이 정낭은 제주만의 특징이에요.',
      'Jeju has a traditional gate called jeongnang. Its feature is being made of three poles, and the pole positions signal the household state. All three up means they have gone far; two means they will return soon. Including hanbok, Korea has many traditional cultures, but this jeongnang is unique to Jeju.',
      [
        { korean: '~이라는 N', english: 'a N called ~' },
        { korean: '~ㄴ다는 특징', english: 'the feature that ~' },
        { korean: '~ 비롯해서', english: 'including ~' },
      ],
      [ACT.readingSpeaking]),

    createContentItem('Dialect presentation', 'listening',
      'Q&A after a presentation.',
      'conversation',
      'A (발표자): 한국에는 지역별 사투리가 있어요. 경상도, 전라도, 충청도를 비롯해서 모든 지역에 특징이 있어요.\nB (청중): 어디 사투리가 가장 강해요?\nA: 경상도 사투리가 강하다는 평이 있어요. 짧고 직설적이며 억양이 독특해요.\nB: 제주도 사투리도 들어 봤어요?\nA: 네, 제주도 사투리는 다른 지역과는 완전히 달라요. 정낭이라는 전통 문화처럼 언어도 독특해요.\nB: 정말 흥미롭네요. 감사합니다.',
      'A (Presenter): Korea has regional dialects. Including Gyeongsang, Jeolla, Chungcheong, every region has features. B: Which is strongest? A: Gyeongsang dialect is said to be strong. Short and direct, with unique intonation. B: Jeju dialect? A: Yes, Jeju is completely different. Like the jeongnang tradition, the language is unique. B: Really interesting. Thanks.',
      [
        { korean: '~ 비롯해서', english: 'including' },
        { korean: '~다는 평', english: 'said to be ~' },
        { korean: '~ 며', english: 'and (formal)' },
      ],
      [ACT.listeningSpeaking]),

    createContentItem('Minority culture writing', 'reading + writing',
      'Sample paragraph.',
      'sentence',
      '제 나라에는 도시별로 다른 문화가 있어요. 수도를 비롯해서 모든 도시는 자기만의 전통이 있으며 그 특징이 잘 보존되고 있어요. 특히 한 도시에는 매년 가족이 모여 산에서 음식을 가져다가 함께 나눠 먹는다는 전통이 있어요. 정말 흥미로운 문화예요.',
      'My country has different cultures by city. Including the capital, every city has its own tradition, well preserved. One city has the tradition that every year families gather and share food brought from the mountain. Really an intriguing culture.',
      null, [ACT.readingWriting]),

    createContentItem('정낭 — Jeju pole-fence gate', 'culture',
      '정낭 is a traditional Jeju entrance: three wooden poles slotted into stone pillars in front of the house. Pole position signals household status: 0 up = home / 1 up = nearby / 2 up = will return soon / 3 up = away for the day. Visitors do not knock — they read the poles. Symbol of Jeju\'s communal trust.',
      'sentence', '정낭은 제주도의 신뢰 문화를 보여 줘요.',
      'Jeongnang shows Jeju\'s culture of trust.',
      [
        { korean: '정낭', english: 'pole-fence gate' },
        { korean: '신뢰 문화', english: 'culture of trust' },
        { korean: '제주도', english: 'Jeju Island' },
      ],
      [ACT.culture]),

    createContentItem('과제: Cultural presentation outline', 'task',
      'Roleplay: Outline a 5-min presentation about a unique cultural feature of your country. Use 4 patterns + 1 -별 word.',
      'conversation',
      'Tutor: 어떤 주제예요?\nYou: ~ 비롯해서 ~ (intro)\nTutor: 특징은 뭐예요?\nYou: ~ ㄴ다는 특징이 있어요.\nTutor: 어떻게 만들어요?\nYou: ~ 며 ~ 며 ~ (formal description)\nTutor: 다른 지역에도 있어요?\nYou: 지역별로 ~ 며 ~\nTutor: 좋은 발표예요.',
      'AI tutor will play the audience.',
      [
        { korean: '~ 비롯해서', english: 'including' },
        { korean: '~ ㄴ다는 N', english: 'the N that ~' },
        { korean: '~ (으)며', english: 'and (formal)' },
        { korean: '~별', english: 'per (suffix)' },
      ],
      [ACT.task]),
  ],
};

module.exports = lesson;
